### PR TITLE
Add proto for HonestMajorityShareShuffle protocol.

### PR DESCRIPTION
**Pull request by renjiezh**
- Added HonestMajorityShareShuffle protocol in duchy's proto.
- Update proto and database schema for Requisition and RequisitionService to accept either blob or a seed.
- Update ControlService to accept input for a certain stage of new protocol.
- Extract `RoleInComputation` and duchy `NoiseMechanism` from LLv2 specific message.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1348)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 45 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1348)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/ComputationTokenProtoQuery.kt` line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1348#-NkMBHQo98nDlWDGjIOp:-NkMBHQo98nDlWDGjIOq:b-dz2mn1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd582519fb660d6888a933d8b48611da5d672827/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/ComputationTokenProtoQuery.kt#L160)):*
> ```Kotlin
>             }
>             val dataPath = it.getString("PathToBlob")
>             if (!dataPath.isNullOrBlank()) {
> ```

NULL and empty string should be distinct. Do we write NULL or do we set this to empty string? If it's the latter, the column should be `NOT NULL`. (I prefer explicit NULL)



_Code quote:_
```Kotlin
isNullOrBlank()
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/ComputationTokenProtoQuery.kt` line 161 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1348#-NkMB6qr2OJRkD5Dz3u2:-NkMB6qs7Y_iQc8dl5P-:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd582519fb660d6888a933d8b48611da5d672827/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/ComputationTokenProtoQuery.kt#L161)):*
> ```Kotlin
>             val dataPath = it.getString("PathToBlob")
>             if (!dataPath.isNullOrBlank()) {
>               path = it.getString("PathToBlob")
> ```





_Suggestion:_
```Kotlin
dataPath
```
___
*[`src/main/proto/wfa/measurement/internal/duchy/computation_token.proto` line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1348#-NkM7AZ54JB8bpJUXlvz:-NkM7AZ54JB8bpJUXlw-:biq2jvx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd582519fb660d6888a933d8b48611da5d672827/src/main/proto/wfa/measurement/internal/duchy/computation_token.proto#L93)):*
> ```proto
>   ExternalRequisitionKey external_key = 1;
>   // Detail of the requisition.
>   RequisitionDetails details = 2;
> ```

Avoid retagging fields for in-use message types. Keep `details` as 3 and `path` as 2.
___
*[`src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1348#-NkM82AF5ncj7ZPz2zj2:-NkM82AF5ncj7ZPz2zj3:by84np2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd582519fb660d6888a933d8b48611da5d672827/src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto#L17)):*
> ```proto
> syntax = "proto3";
> 
> package org.wfa.measurement.config;
> ```

Fix the protobuf package to match file path.

The Java package should be the same as the protobuf package, but with `org.wfanet` instead of `wfa`.



_Suggestion:_
```proto
wfa.measurement.internal.duchy.config
```
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/secretsharing/BUILD.bazel` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1348#-NkM8lPX1BBXgK1rgJ4I:-NkM8lPX1BBXgK1rgJ4J:b78l42u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd582519fb660d6888a933d8b48611da5d672827/src/main/proto/wfa/measurement/internal/duchy/protocol/secretsharing/BUILD.bazel#L1)):*
> ```Starlark
> load("@rules_java//java:defs.bzl", "java_proto_library")
> ```

Why the subdirectory? This should parallel the structure for LLv2, which is just under `protocol`.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/secretsharing/share_shuffle_sketch_params.proto` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1348#-NkMAU0J9XJyT5tAaC6-:-NkMAU0J9XJyT5tAaC60:b-gr7uv2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd582519fb660d6888a933d8b48611da5d672827/src/main/proto/wfa/measurement/internal/duchy/protocol/secretsharing/share_shuffle_sketch_params.proto#L29)):*
> ```proto
>   // Length of each item in bytes. #_EDPs * max_frequency should be no more than
>   // 2^(bytes_per_item*8).
>   int32 bytes_per_item = 2;
> ```

Same notes here as in public API.



_Code quote:_
```proto
  // Length of each item in bytes. #_EDPs * max_frequency should be no more than
  // 2^(bytes_per_item*8).
  int32 bytes_per_item = 2;
```

**Review by kungfucraig — CHANGES_REQUESTED** [review]
It would be nice to see the the extraction of Role and Noise Mechanism in a separate PR.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1348#-:-NkMGNfpDgGLLT0jRE15:b-v3pl94)* status: all files reviewed, 6 unresolved discussions (waiting on @ple13 and @renjiezh)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
I should have not clicked submit so soon...

This should be at least three and probably four PRs.

1. Extraction of common stuff from LLv2. Refactoring should not be done alongside new stuff.
2. HM Share Shuffle protos. This should not require any kotlin changes.
3. DB update (maybe this is combined with updates to the control service, but ideally it can be separated)
4. Control service updates

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1348#-:-NkMGZIkBsglrP18wCZZ:b7mz9kx)* status: all files reviewed, 6 unresolved discussions (waiting on @ple13 and @renjiezh)

**Pull request closed without merging**
