### PR TITLE
Switch to create Deployment instead of Pod for all services/daemons.

### PR DESCRIPTION
**Pull request by wangyaopw**
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F610324077415&view=2c2927c0-626b-4740-8620-af2a93b7d623

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/303)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
Deployment is just something managing the pods. Create a deployment will create a list of pods (number = replicas) for us. The network policy still works on those pods, 

FYI, https://kubernetes.io/docs/concepts/workloads/pods/#working-with-pods
"You'll rarely create individual Pods directly in Kubernetes—even singleton Pods. This is because Pods are designed as relatively ephemeral, disposable entities. "

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/303#-:-MkrI5EY6nqqcNOvYNSP:bowi9gv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by oliver-amzn — APPROVED** [review]
Sounds good, thanks for the explainer!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/303#-:-MkrJ_NXDZ1foLEpGeXp:b-3sary)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @oliver-amzn and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/303)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/k8s/duchy.cue, line 107 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/303#-MkrxZMT-exeqzqoncUf:-MkrxZMT-exeqzqoncUg:b-fzagsn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/284ba433d0901134866b787676cbd398244349e2/src/main/k8s/duchy.cue#L107)):*
> ```
> //TODO(wangyao)
> ```
nit: use proper [TODO format](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format)
___
*[src/main/k8s/kingdom_and_three_duchies_local.cue, line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/303#-MkryvOb7x2xG3xjFDiI:-MkryvOb7x2xG3xjFDiJ:b-nkx8tn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/284ba433d0901134866b787676cbd398244349e2/src/main/k8s/kingdom_and_three_duchies_local.cue#L77)):*
> ```CUE
> 
> fake_pod: "fake-storage-server-deployment": #ServerDeployment & {
> 	_name:   "fake-storage-server"
> ```

There should also only ever be one of these, or else each replica needs the same `--blob-storage-directory` created and specified.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

___
*[src/main/k8s/duchy.cue, line 107 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/303#-MkrxZMT-exeqzqoncUf:-MksJjhS7r-yUQ_2KQnN:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/284ba433d0901134866b787676cbd398244349e2/src/main/k8s/duchy.cue#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> //TODO(wangyao)
> ```
nit: use proper [TODO format](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format)
</blockquote></details>

done
___
*[src/main/k8s/kingdom_and_three_duchies_local.cue, line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/303#-MkryvOb7x2xG3xjFDiI:-MksJuFX6FfXe1VQrD51:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/284ba433d0901134866b787676cbd398244349e2/src/main/k8s/kingdom_and_three_duchies_local.cue#L77)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There should also only ever be one of these, or else each replica needs the same `--blob-storage-directory` created and specified.
</blockquote></details>

done

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
