### PR TITLE
Implement Stream Measurements for Spanner Kingdom Internal Services

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264)

https://rally1.rallydev.com/#/?detail=/task/608869651649&fdp=true

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 86 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264#-MjAFJfR9G-ihVIPl_PV:-MjAFJfR9G-ihVIPl_PW:b1zf0jp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4df99e18b8d0120928c4c8b368d093d0947820b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L86)):*
> ```
> request
> ```

Verify the request here (also in other methods in all services)?

This method should never be called without external_measurement_consumer_id being set in the filter. In other words, we don't support querying all MCs' measurements in the database.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264#-MjBPSMX1ev7vwgjt9Sg:-MjBPSMX1ev7vwgjt9Sh:b-almhl6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4df99e18b8d0120928c4c8b368d093d0947820b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L26)):*
> ```
> private val view: Measurement.View,
> ```
we don't need view here.

This method will already be called COMPUTATION_VIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264#-MjBPSMX1ev7vwgjt9Sg:-MjBPwJo56-8pQi6QgB7:b-2yen91) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4df99e18b8d0120928c4c8b368d093d0947820b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L26)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> private val view: Measurement.View,
> ```
we don't need view here.

This method will already be called COMPUTATION_VIEW
</blockquote></details>

will *always* be called with COMPUTATION_VIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 86 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264#-MjAFJfR9G-ihVIPl_PV:-MjBP33JA8aMjV6Uq3tg:b-6cqgrq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4df99e18b8d0120928c4c8b368d093d0947820b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L86)):*
> This method should never be called without external_measurement_consumer_id being set in the filter. In other words, we don't support querying all MCs' measurements in the database.

Isn't this needed for the system StreamActiveComputations method, which doesn't filter by MC?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264#-MjBPSMX1ev7vwgjt9Sg:-MjBQD6uBufpHgtl3_nB:br3a1t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4df99e18b8d0120928c4c8b368d093d0947820b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L26)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

will *always* be called with COMPUTATION_VIEW
</blockquote></details>

Not true. If called for public ListMeasurements, it will use DEFAULT view.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264#-MjBPZl09v9lmKc-pwNC:-MjBPZl09v9lmKc-pwND:bb0cxpe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4df99e18b8d0120928c4c8b368d093d0947820b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L65)):*
> ```Kotlin
> 
>   companion object {
>     const val LIMIT = "limit"
> ```

nit: consider wrapping in a Params object so it's clear that these are all statement params. Alternatively, suffix each of these consts with `_PARAM`.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264#-MjBPSMX1ev7vwgjt9Sg:-MjBQZsU5U1bGV-NLHly:b-5qt4tr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4df99e18b8d0120928c4c8b368d093d0947820b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not true. If called for public ListMeasurements, it will use DEFAULT view.
</blockquote></details>

oh, yep. My bad.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 86 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264#-MjAFJfR9G-ihVIPl_PV:-MjBRKDM6ZE7vaUSd2kE:bneryl4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4df99e18b8d0120928c4c8b368d093d0947820b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L86)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> This method should never be called without external_measurement_consumer_id being set in the filter. In other words, we don't support querying all MCs' measurements in the database.

Isn't this needed for the system StreamActiveComputations method, which doesn't filter by MC?
</blockquote></details>

You are correct. Not sure what I was thinking.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264#-MjBPZl09v9lmKc-pwNC:-MjBWFj6-ujL3F-VC3BY:b-zcjvte) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4df99e18b8d0120928c4c8b368d093d0947820b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: consider wrapping in a Params object so it's clear that these are all statement params. Alternatively, suffix each of these consts with `_PARAM`.
</blockquote></details>

Thanks

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/264)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)

**Pull request merged**
