### PR TITLE
Add support for internal creation of direct measurements.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473#-MxlY76X6A0zVvLMQvqN:-MxlY76X6A0zVvLMQvqO:bxiu5c9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa6806476929466c9d24f38557c869ebf36bbda8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L64)):*
> ```Kotlin
> 
>     lateinit var initialMeasurementState: Measurement.State
>     lateinit var initialRequisitionState: Requisition.State
> ```

This is odd. Why not just have vals declared in each branch of the conditional? They don't appear to be used for anything else.

Or why have variables at all, rather than just passing the enum values to the parameters? Or better yet, since these values are always the same depending on which method is being called, why not have them be declared inside the method?



_Code quote:_
```Kotlin
    lateinit var initialMeasurementState: Measurement.State
    lateinit var initialRequisitionState: Requisition.State
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473#-MxlZRU55Uj5PPASWIrm:-MxlZRU55Uj5PPASWIrn:bro5xfb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa6806476929466c9d24f38557c869ebf36bbda8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L111)):*
> ```Kotlin
>       val dataProviderId = readDataProviderId(ExternalId(externalDataProviderId))
>       insertRequisition(
>         measurementConsumerId,
> ```

This block is exactly duplicated in two places. Extract function.



_Code quote:_
```Kotlin
    // Insert into Requisitions for each EDP
    for ((externalDataProviderId, dataProviderValue) in measurement.dataProvidersMap) {
      val dataProviderId = readDataProviderId(ExternalId(externalDataProviderId))
      insertRequisition(
        measurementConsumerId,
        measurementId,
        dataProviderId,
        dataProviderValue,
        initialRequisitionState
      )
    }
```

**Comment by tristanvuong2021** [comment]
> > Reviewed 1 of 3 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473)_ status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)
> 
> _[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473#-MxlY76X6A0zVvLMQvqN:-MxlY76X6A0zVvLMQvqO:bxiu5c9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa6806476929466c9d24f38557c869ebf36bbda8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L64)):_
> 
> > ```kotlin
> >     lateinit var initialMeasurementState: Measurement.State
> >     lateinit var initialRequisitionState: Requisition.State
> > ```
> 
> This is odd. Why not just have vals declared in each branch of the conditional? They don't appear to be used for anything else.
> 
> Or why have variables at all, rather than just passing the enum values to the parameters? Or better yet, since these values are always the same depending on which method is being called, why not have them be declared inside the method?
> 
> _Code quote:_
> 
> ```kotlin
>     lateinit var initialMeasurementState: Measurement.State
>     lateinit var initialRequisitionState: Requisition.State
> ```
> 
> _[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473#-MxlZRU55Uj5PPASWIrm:-MxlZRU55Uj5PPASWIrn:bro5xfb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa6806476929466c9d24f38557c869ebf36bbda8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L111)):_
> 
> > ```kotlin
> >       val dataProviderId = readDataProviderId(ExternalId(externalDataProviderId))
> >       insertRequisition(
> >         measurementConsumerId,
> > ```
> 
> This block is exactly duplicated in two places. Extract function.
> 
> _Code quote:_
> 
> ```kotlin
>     // Insert into Requisitions for each EDP
>     for ((externalDataProviderId, dataProviderValue) in measurement.dataProvidersMap) {
>       val dataProviderId = readDataProviderId(ExternalId(externalDataProviderId))
>       insertRequisition(
>         measurementConsumerId,
>         measurementId,
>         dataProviderId,
>         dataProviderValue,
>         initialRequisitionState
>       )
>     }
> ```

Made changes.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473#-MxlY76X6A0zVvLMQvqN:-MxpdlAZD6diOOYD5KFN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa6806476929466c9d24f38557c869ebf36bbda8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is odd. Why not just have vals declared in each branch of the conditional? They don't appear to be used for anything else.

Or why have variables at all, rather than just passing the enum values to the parameters? Or better yet, since these values are always the same depending on which method is being called, why not have them be declared inside the method?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473#-MxlZRU55Uj5PPASWIrm:-MxpdmMgANHS_SC6xdkO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa6806476929466c9d24f38557c869ebf36bbda8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L111)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This block is exactly duplicated in two places. Extract function.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 169 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473#-MxpQaA4Am8Luoi_Itzq:-Mxpdmu32_Q7x6UuE18x:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19f34c99fedd54714d7a253f9ee59bfd89065b85/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L169)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Despite the fact that we don't allow 0 as an ID, it shouldn't be used as a sentinel value in the database. Use NULL instead.

You may need to make the column nullable and update constraints/indexes to handle that.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 297 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473#-Mxprj2TEQvsorfXXt4U:-Mxprj2TEQvsorfXXt4V:b-b4m4u0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/828e758a2b1cd6167d4446510bdf712f4a0e6c73/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L297)):*
> ```
> 
> CREATE UNIQUE INDEX MeasurementsByExternalComputationId
>   ON Measurements(ExternalComputationId);
> ```

Should this be `NULL_FILTERED` now? See https://cloud.google.com/spanner/docs/secondary-indexes#null-indexing-disable

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 297 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473#-Mxprj2TEQvsorfXXt4U:-MxrFLsG62Z_vQbsTU02:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/828e758a2b1cd6167d4446510bdf712f4a0e6c73/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L297)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Should this be `NULL_FILTERED` now? See https://cloud.google.com/spanner/docs/secondary-indexes#null-indexing-disable
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/473)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
