### PR TITLE
Add detailed logging to event groups and metadata descriptors services

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1570)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1570)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 547 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1570#-NvYteZiBhia6TDFR6QM:-NvYteZiBhia6TDFR6QN:bd3u4iw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c9ccd13297a6b8089a3e7340679d3e5f814de6f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L547)):*
> ```Kotlin
>     get() =
>       mapOf(
>         "original_external_measurement_id" to
> ```

Nice catch, though also update the context keys.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/InternalStatusConversion.kt` line 371 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1570#-NvYu219ARwmJdZ7vouq:-NvYu219ARwmJdZ7vour:b-10nqmu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c9ccd13297a6b8089a3e7340679d3e5f814de6f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/InternalStatusConversion.kt#L371)):*
> ```Kotlin
>           put("providedMeasurementConsumer", providedMeasurementConsumerName)
>           errorMessage =
>             "EventGroup operation arguments original measurement: $originalMeasurementConsumerName and provided measurement: $providedMeasurementConsumerName invalid."
> ```

The actual issue here is that the MC references don't match



_Suggestion:_
```Kotlin
"EventGroup argument invalid: expected $originalMeasurementConsumerName but got $providedMeasurementConsumerName"
```

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1570)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 547 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1570#-NvYteZiBhia6TDFR6QM:-Nv_oHcN-xKa4qiTH-ER:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c9ccd13297a6b8089a3e7340679d3e5f814de6f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L547)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Nice catch, though also update the context keys.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/InternalStatusConversion.kt` line 371 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1570#-NvYu219ARwmJdZ7vouq:-Nv_orrV-JguB9L5y7W6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c9ccd13297a6b8089a3e7340679d3e5f814de6f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/InternalStatusConversion.kt#L371)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The actual issue here is that the MC references don't match
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1570)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1570)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
