### PR TITLE
Change the Measurement.aggregator_certificate field to a resource name.

### PR DESCRIPTION
**Pull request by SanjayVas**
This updates cross-media-measurement-api to 0.20.0 and common-jvm to 0.31.0.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/501)

### CODE REVIEW

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 16 of 24 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/501)* status: 22 of 24 files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 244 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/501#-MzQpEWa16ELTE4K-CwW:-MzQpEWa16ELTE4K-CwX:be4c486) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a7a0ebeea3802b6302abefee7c00cb6d2d58a92/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L244)):*
> ```Kotlin
>     }
> 
>     suspend fun getCertificateId(
> ```

Maybe rename so it is immediately obvious it is for a duchy certificate.
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement.proto, line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/501#-MzQoxD62ShLrJMavO20:-MzQoxD62ShLrJMavO21:b-355jk3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a7a0ebeea3802b6302abefee7c00cb6d2d58a92/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L150)):*
> ```protobuf
>   //
>   // Only set for COMPUTATION view.
>   repeated ComputationParticipant computation_participants = 15;
> ```

nit: 14

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/501)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 244 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/501#-MzQpEWa16ELTE4K-CwW:-MzR08C66X3TQZ3WTCjZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a7a0ebeea3802b6302abefee7c00cb6d2d58a92/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L244)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Maybe rename so it is immediately obvious it is for a duchy certificate.
</blockquote></details>

Done.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/501)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by chipingyeh — APPROVED** [review]
> Reviewed 5 of 24 files at r1, 4 of 6 files at r2, 7 of 9 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/501)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
