### PR TITLE
Set encrypted_metadata field in EventGroup created by EDP simulator.

### PR DESCRIPTION
**Pull request by SanjayVas**
This is for #768 and depends on #785

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/786)

### CODE REVIEW

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/786)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 853 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/786#-NInlgph5s0nhCAnyZOe:-NInlgph5s0nhCAnyZOf:b-tqkvpm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/167047f299f782ce455b59fa2106401a693865ac/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L853)):*
> ```Kotlin
>     for (dep in node.dependencies) {
>       addTransitiveDeps(dep)
>       fileDescriptors.add(node)
> ```

It looks like this line should be outside of the loop. Otherwise `node` is added once for each `dep` (granted, it's a set, so that doesn't really matter), and not at all if `node.dependencies` is empty.

Afterward you can also remove the line `fileDescriptors.add(root)` below.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/786)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @robinsons)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 853 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/786#-NInlgph5s0nhCAnyZOe:-NInnkR96v9rjwX9PLpP:bcyh8ap) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/167047f299f782ce455b59fa2106401a693865ac/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L853)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

It looks like this line should be outside of the loop. Otherwise `node` is added once for each `dep` (granted, it's a set, so that doesn't really matter), and not at all if `node.dependencies` is empty.

Afterward you can also remove the line `fileDescriptors.add(root)` below.
</blockquote></details>

Done, though slightly differently than you suggested. The line was supposed to be `fileDescriptors.add(dep)`.

**Review by robinsons — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/786)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/786)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/786)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
