### PR TITLE
Implement Public Report Schedules Service Get, List, and Stop Methods

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280)

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 291 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280#-NgKmrEk9FMw1q9_VR4Q:-NgKmrEk9FMw1q9_VR4R:bx3204w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8fb0a95e4231ade14e36ad4bd26b08f843a82ff4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L291)):*
> ```Kotlin
>     InternalReportSchedule.State.STOPPED -> ReportSchedule.State.STOPPED
>     InternalReportSchedule.State.STATE_UNSPECIFIED,
>     InternalReportSchedule.State.UNRECOGNIZED -> ReportSchedule.State.STATE_UNSPECIFIED
> ```

Should we raise an error for unrecognized states?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 303 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280#-NgKpRhmEf0rEOf6AKEd:-NgKpRhmEf0rEOf6AKEe:btvwesb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8fb0a95e4231ade14e36ad4bd26b08f843a82ff4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L303)):*
> ```Kotlin
>   return when (source.frequencyCase) {
>     InternalReportSchedule.Frequency.FrequencyCase.DAILY ->
>       ReportScheduleKt.frequency { daily = ReportScheduleKt.FrequencyKt.daily {} }
> ```

Use `getDefaultInstance()` instead

```diff
+ReportSchedule.Frequency.Daily.getDefaultInstance()
-ReportScheduleKt.FrequencyKt.daily {}
```



_Code quote:_
```Kotlin
ReportScheduleKt.FrequencyKt.daily {}
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 332 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280#-NgKqZ0o8tj2BQ1izp3G:-NgKqZ0o8tj2BQ1izp3H:b1trz9o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8fb0a95e4231ade14e36ad4bd26b08f843a82ff4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L332)):*
> ```Kotlin
>             count = source.trailingWindow.count
>             increment =
>               ReportSchedule.ReportWindow.TrailingWindow.Increment.valueOf(
> ```

How does `valueOf` handle the case when increment is `UNRECOGNIZED`?
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt` line 684 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280#-NgKvVLSDkf0K3kzQajX:-NgKvVLSDkf0K3kzQajY:b-55ipu9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8fb0a95e4231ade14e36ad4bd26b08f843a82ff4/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt#L684)):*
> ```Kotlin
>         )
>       )
>       .thenReturn(INTERNAL_REPORT_SCHEDULE)
> ```

nit: In real implementation, the state will be `STOPPED`.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 291 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280#-NgKmrEk9FMw1q9_VR4Q:-NgP5Hxm0RnEJx18oM62:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df1b0944ce50fce74dd090d6d5b988815cfc0107/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L291)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Should we raise an error for unrecognized states?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 303 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280#-NgKpRhmEf0rEOf6AKEd:-NgP5VUjBBvw-o_uriJK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df1b0944ce50fce74dd090d6d5b988815cfc0107/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L303)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Use `getDefaultInstance()` instead

```diff
+ReportSchedule.Frequency.Daily.getDefaultInstance()
-ReportScheduleKt.FrequencyKt.daily {}
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 332 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280#-NgKqZ0o8tj2BQ1izp3G:-NgP8Rvi0N2H0EQsyY_v:biz224l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df1b0944ce50fce74dd090d6d5b988815cfc0107/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L332)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

How does `valueOf` handle the case when increment is `UNRECOGNIZED`?
</blockquote></details>

valueOf is actually deprecated so I switched to forNumber and handled the unrecognized case

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt` line 871 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280#-NgPc7-v00okJ8p8px65:-NgPc7-v00okJ8p8px66:b-iipjm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b28608d3ee6f8af81a7d918753b3bbe9e0393f1b/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt#L871)):*
> ```Kotlin
>           frequency =
>             InternalReportScheduleKt.frequency {
>               daily = InternalReportScheduleKt.FrequencyKt.daily {}
> ```

nit: ditto
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt` line 910 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280#-NgPc8JI83IlTk9yYo_f:-NgPc8JI83IlTk9yYo_g:b-iipjm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b28608d3ee6f8af81a7d918753b3bbe9e0393f1b/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt#L910)):*
> ```Kotlin
>       eventStart = INTERNAL_REPORT_SCHEDULE.details.eventStart
>       eventEnd = INTERNAL_REPORT_SCHEDULE.details.eventEnd
>       frequency = ReportScheduleKt.frequency { daily = ReportScheduleKt.FrequencyKt.daily {} }
> ```

nit: ditto

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1280)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
