### PR TITLE
Compare expected RF results against actual using synthetic data for Reporting V2 integration tests

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: all files reviewed, 3 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 510 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NasVia5APAAJmNlvQ0W:-NasVia5APAAJmNlvQ0X:b-n411f4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41eb76f7ff832d279fba3cf8b09e9469c7dee866/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L510)):*
> ```Kotlin
>     assertThat(actualResult)
>       .reachValue()
>       .isWithinPercent(0.5)
> ```

Add TODOs to all these to use variance rather than fixed thresholds.



_Code quote:_
```Kotlin
isWithinPercent(0.5)
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 631 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NasVutTC4o2lKw1d2pm:-NasVutTC4o2lKw1d2pn:b-n6tr8o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41eb76f7ff832d279fba3cf8b09e9469c7dee866/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L631)):*
> ```Kotlin
>           }
>       }
>     assertThat(actualResult).reachValue().isWithinPercent(500.0).of(1)
> ```

Just to confirm, your expected reach value here is `1` and you want to be within 500% of that?

I guess that's fine, it just looks weird. You can probably narrow it down if you use a query with a higher expected reach value. I think with reasonable DP params and an expected reach >=2000 you should be able to reduce the threshold to like 10%.



_Code quote:_
```Kotlin
.isWithinPercent(500.0).of(1)
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1751 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NasXzvw4r_Zos3Ai2AK:-NasXzvw4r_Zos3Ai2AL:b-zadryt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41eb76f7ff832d279fba3cf8b09e9469c7dee866/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1751)):*
> ```Kotlin
>   ): Measurement.Result {
>     val reachAndFrequency =
>       MeasurementResults.computeReachAndFrequency(sampledVids.asIterable(), maximumFrequencyPerUser)
> ```

This parameter is the overall max frequency (largest bucket), not the max frequency per user. We don't actually support the latter for R/F measurements (see https://github.com/world-federation-of-advertisers/cross-media-measurement-api/issues/159).



_Code quote:_
```Kotlin
maximumFrequencyPerUser
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 510 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NasVia5APAAJmNlvQ0W:-Naw7wtR8DDh_4pD3DTf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/faa3494134e0019df22cc92617e0e2d99c873248/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L510)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add TODOs to all these to use variance rather than fixed thresholds.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 631 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NasVutTC4o2lKw1d2pm:-NawHoNY0qL6fApuAcHc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/faa3494134e0019df22cc92617e0e2d99c873248/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L631)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just to confirm, your expected reach value here is `1` and you want to be within 500% of that?

I guess that's fine, it just looks weird. You can probably narrow it down if you use a query with a higher expected reach value. I think with reasonable DP params and an expected reach >=2000 you should be able to reduce the threshold to like 10%.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1751 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NasXzvw4r_Zos3Ai2AK:-NawDGtEEt-cqWL-QNcy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/faa3494134e0019df22cc92617e0e2d99c873248/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1751)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This parameter is the overall max frequency (largest bucket), not the max frequency per user. We don't actually support the latter for R/F measurements (see https://github.com/world-federation-of-advertisers/cross-media-measurement-api/issues/159).
</blockquote></details>

Done.

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NawQJF5BVYFzILY9vlT:-NawQJF5BVYFzILY9vlU:bvb3em5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc50978b15bb8528df259c7bab263d6e4071aea2/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1132)):*
> ```Kotlin
>         } else {
>           assertThat(actualResult).reachValue().isWithinPercent(500.0).of(1)
>         }
> ```

Is the expected value equal to 1 because the event group used here is too small? If so, maybe we could use a larger event group?



_Code quote:_
```Kotlin
        if (resultAttribute.groupingPredicatesList.contains(grouping2Predicate1)) {
          assertThat(actualResult).reachValue().isWithinPercent(500.0).of(1)
        } else {
          assertThat(actualResult).reachValue().isWithinPercent(500.0).of(1)
        }
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1391 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NawqA60DxCmxCVY524p:-NawqA60DxCmxCVY524q:b-vvloxp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc50978b15bb8528df259c7bab263d6e4071aea2/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1391)):*
> ```Kotlin
>         }
>         .binResult
>         .value
> ```

Is it equivalent to

```Kotlin
retrievedMetric.result.frequencyHistogram.binsList.sumOf { bin -> bin.binResult.value }
```



_Code quote:_
```Kotlin
      retrievedMetric.result.frequencyHistogram.binsList
        .reduce { acc, bin ->
          acc.copy { binResult = acc.binResult.copy { value += bin.binResult.value } }
        }
        .binResult
        .value
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1511 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NawrFSTAn-ESFfJtovM:-NawrFSTAn-ESFfJtovN:bc26paa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc50978b15bb8528df259c7bab263d6e4071aea2/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1511)):*
> ```Kotlin
> 
>     // TODO(@tristanvuong2021): Calculate watch duration using synthetic spec. Current calculation
>     // is too large.
> ```

IIUC, we don't have duration measurements yet, and currently the EDP simulator simply outputs `externalDataProviderId`. Do we use a fake Kingdom here? 



_Code quote:_
```Kotlin
    // TODO(@tristanvuong2021): Calculate watch duration using synthetic spec. Current calculation
    // is too large.
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NawQJF5BVYFzILY9vlT:-NaxDF6oBr5SzGqzqkNX:b-d1wuum) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0889c2ac72588c4963bf2f5b7cf79eff06d49d0/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1132)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Is the expected value equal to 1 because the event group used here is too small? If so, maybe we could use a larger event group?
</blockquote></details>

These are a result of filters that result in no events. I updated the synthetic data to include events for this test case.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1391 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NawqA60DxCmxCVY524p:-NaxGcf0Ezt6B5l2mTip:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0889c2ac72588c4963bf2f5b7cf79eff06d49d0/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1391)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Is it equivalent to

```Kotlin
retrievedMetric.result.frequencyHistogram.binsList.sumOf { bin -> bin.binResult.value }
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1511 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NawrFSTAn-ESFfJtovM:-NaxGmhHCBkk9ABzJBZD:b-lkgwpp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0889c2ac72588c4963bf2f5b7cf79eff06d49d0/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1511)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

IIUC, we don't have duration measurements yet, and currently the EDP simulator simply outputs `externalDataProviderId`. Do we use a fake Kingdom here? 
</blockquote></details>

I was planning to just leave this until we change the calculation in the EDP simulator.

**Review by riemanli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NawQJF5BVYFzILY9vlT:-Nb0ahkeBvmXoE_3hcLH:bq1npwi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0889c2ac72588c4963bf2f5b7cf79eff06d49d0/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1132)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

These are a result of filters that result in no events. I updated the synthetic data to include events for this test case.
</blockquote></details>

With the updated synthetic data, should we update the expected value and the tolerance?

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/k8s/testing/data/synthetic_event_group_spec_1.textproto` line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-Nb0aNcR8P3hp5KjIKhd:-Nb0aNcS0zgRTKvqeBOE:b-q8ai5n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e42c6fdf27b698e4ed4da793b074b7eb7f77cc5d/src/main/k8s/testing/data/synthetic_event_group_spec_1.textproto#L83)):*
> ```
>     vid_range_specs {
>       vid_range {
>         start: 9000000
> ```

nit: since `0` is an invalid VID and the population VID range starts at 1, prefer to define event group spec ranges offset by 1

e.g. `[9000001, 9001001)`
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1511 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NawrFSTAn-ESFfJtovM:-Nb0b7tD1_EMxsC8gzlD:b-fxyefm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0889c2ac72588c4963bf2f5b7cf79eff06d49d0/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1511)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I was planning to just leave this until we change the calculation in the EDP simulator.
</blockquote></details>

FYI #1150 switches EventQuery to actually return labeled events, so it would be possible to update the simulator to do "real" durations after that. Of course, it would mean adding duration to the synthetic generator specs.

**Review by riemanli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NawQJF5BVYFzILY9vlT:-NbHKjhR-wucb7IZbmIs:but18w0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0889c2ac72588c4963bf2f5b7cf79eff06d49d0/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1132)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

With the updated synthetic data, should we update the expected value and the tolerance?
</blockquote></details>

Sorry did you mean you intentionally to obtain the expected result == 1?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NawQJF5BVYFzILY9vlT:-NbHTuWv2Icna9UIEhka:b-vhvien) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0889c2ac72588c4963bf2f5b7cf79eff06d49d0/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1132)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Sorry did you mean you intentionally to obtain the expected result == 1?
</blockquote></details>

That was before, but for this test case, the expected results are more normal now.

**Review by riemanli — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
Can you run a bazel coverage report for this test against the reporting server code base? I'd like to make sure we're covering all of the major functionality.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-:-NbLEB_06fn-p7HfqqQN:b-zbhufc)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r4, 1 of 2 files at r5, 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/BUILD.bazel` line 37 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NbVVoPV6wou6yRr2kgv:-NbVVoPV6wou6yRr2kgw:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd41d1f14f09a730471783ad70fb434d2b270f7/src/test/kotlin/org/wfanet/measurement/integration/postgres/BUILD.bazel#L37)):*
> ```Starlark
>         "//src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/server/postgres:services",
>         "//src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/testing",
>         "//src/test/kotlin/org/wfanet/measurement/integration/common/duchy:spanner_duchy_dependency_provider_rule",
> ```

ditto
___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NbVVj4d-jM1EY8atoCi:-NbVVj4d-jM1EY8atoCj:btow0z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd41d1f14f09a730471783ad70fb434d2b270f7/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L27)):*
> ```Kotlin
> import org.wfanet.measurement.integration.common.ALL_DUCHY_NAMES
> import org.wfanet.measurement.integration.common.InProcessDuchy
> import org.wfanet.measurement.integration.common.duchy.SpannerDuchyDependencyProviderRule
> ```

what was the reason for this change?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NbVVj4d-jM1EY8atoCi:-NbVX8QxAuOgrH8NzfMy:b-h5py94) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd41d1f14f09a730471783ad70fb434d2b270f7/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what was the reason for this change?
</blockquote></details>

The postgres duchy test rule is not fast enough for this test. With my test changes, it leads to frequent time outs.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NbVVj4d-jM1EY8atoCi:-NbWZwr14MuLqgEpsLtp:b-qr3gbm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd41d1f14f09a730471783ad70fb434d2b270f7/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L27)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The postgres duchy test rule is not fast enough for this test. With my test changes, it leads to frequent time outs.
</blockquote></details>

The name of the file is `V2PostgrestInProcess....`

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NbVVj4d-jM1EY8atoCi:-NbX2aoeE-Ek7PmBqhNq:b-3uyy2h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd41d1f14f09a730471783ad70fb434d2b270f7/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

The name of the file is `V2PostgrestInProcess....`
</blockquote></details>

The main point of this is to test the Reporting Server.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NbVVj4d-jM1EY8atoCi:-NbX4qas8a5cdsrlktKa:b-w4j97g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd41d1f14f09a730471783ad70fb434d2b270f7/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L27)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The main point of this is to test the Reporting Server.
</blockquote></details>

The file name is in reference to the Reporting Server.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @riemanli, and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NbVVj4d-jM1EY8atoCi:-Nb_3PnjEP4yTjow66HJ:brtkund) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd41d1f14f09a730471783ad70fb434d2b270f7/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L27)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The file name is in reference to the Reporting Server.
</blockquote></details>

Why is the Postgres rule so much slower? Is it that the `EmbeddedPostgresDatabaseProvider` is so much slower? This will become an issue as we port over to Postgres from Spanner. We should open a task or issue do deal with this imo FYI @SanjayVas

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @riemanli, and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NbVVj4d-jM1EY8atoCi:-Nb_Po-PDQokLpvTdSWd:b-q1x6ph) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd41d1f14f09a730471783ad70fb434d2b270f7/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Why is the Postgres rule so much slower? Is it that the `EmbeddedPostgresDatabaseProvider` is so much slower? This will become an issue as we port over to Postgres from Spanner. We should open a task or issue do deal with this imo FYI @SanjayVas 
</blockquote></details>

The Spanner rule uses an emulated Spanner database, but Postgres uses a docker container that runs an actual Postgres database in it.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NbVVj4d-jM1EY8atoCi:-Nb_gwpT5ugXR4EnIjs1:bdld0ld) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd41d1f14f09a730471783ad70fb434d2b270f7/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L27)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The Spanner rule uses an emulated Spanner database, but Postgres uses a docker container that runs an actual Postgres database in it.
</blockquote></details>

1. The "Postgres" distinction in the file name was incorrectly added in #1152, which is also the PR that switched it to use the Postgres Duchy implementation. The reason the distinction is inaccurate is that the test still uses a Spanner-based Kingdom.
2. I'm looking into what we can to do possibly speed up Postgres testing. Unfortunately there's no lightweight Postgres emulator the way there is for Spanner.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147#-NbVVj4d-jM1EY8atoCi:-NbaPsyoCvP5ux4PY0-8:b-bo2vrl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd41d1f14f09a730471783ad70fb434d2b270f7/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. The "Postgres" distinction in the file name was incorrectly added in #1152, which is also the PR that switched it to use the Postgres Duchy implementation. The reason the distinction is inaccurate is that the test still uses a Spanner-based Kingdom.
2. I'm looking into what we can to do possibly speed up Postgres testing. Unfortunately there's no lightweight Postgres emulator the way there is for Spanner.
</blockquote></details>

https://github.com/world-federation-of-advertisers/common-jvm/pull/211 attempts to improve the postgres testing situation. I did some informal testing with that change and I end up with the InProcessLifeOfAMeasurementIntegrationTest taking the same amount of time to run for both the Spanner and Postgres Duchy implementations.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @riemanli, and @tristanvuong2021)

**Review by kungfucraig — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @riemanli, and @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r4, 1 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @riemanli)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @riemanli)

**Pull request merged**
