### PR TITLE
feat: Extend last report time interval to end of report

### PR DESCRIPTION
**Pull request by tristanvuong2021**
feat: The last report time interval covers the end of the report

This adds a time interval that covers the end of the report even if the look back window goes past the report_end. This additional time interval just cuts off at report_end. Currently, if the look back window goes past the report_end, there is no time interval that partially covers it.

### CODE REVIEW

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 1145 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-O9k5iwA-kStedfDkZHZ:-O9k5iwA-kStedfDkZH_:b-bdpys9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d3f9f6536d403356926d64e171899600d3b71a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L1145)):*
> ```Kotlin
> 
>         if (Timestamps.compare(nextTimeIntervalEndTimestamp, reportEndTimestamp) > 0) {
>           if (Timestamps.compare(nextTimeIntervalStartTimestamp, reportEndTimestamp) != 0) {
> ```

I think a less than would make more sense here.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 2830 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-O9k3jET55PcP8mAIObT:-O9k3jET55PcP8mAIObU:baja665) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5c84f8051cd189e55f8c43ee2b9cc3f3a75e353/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L2830)):*
> ```Kotlin
>   }
> 
>   @Test
> ```

Do we have  the following tests:

1) start date and end date are identical, and if so, what is the behavior?
2) the first interval is a full week
3) the last interval is a full week

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 1145 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-O9k5iwA-kStedfDkZHZ:-O9kRjZJDxyysdA1G8La:bcr7zxx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d3f9f6536d403356926d64e171899600d3b71a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L1145)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think a less than would make more sense here.
</blockquote></details>

`Timestamp` is a protobuf message type. The generated Java class therefore does not implement the `Comparable` interface.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 1145 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-O9k5iwA-kStedfDkZHZ:-O9kSfCm2wnmwtPlaG9i:b-teb3tt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d3f9f6536d403356926d64e171899600d3b71a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L1145)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`Timestamp` is a protobuf message type. The generated Java class therefore does not implement the `Comparable` interface.
</blockquote></details>

Note that I believe we could add the operator extensions, but that probably belongs in common-jvm. See https://kotlinlang.org/docs/operator-overloading.html#comparison-operators

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @kungfucraig)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 2830 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-O9k3jET55PcP8mAIObT:-O9kVray4r6mcaW8R-Hu:b995ji0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5c84f8051cd189e55f8c43ee2b9cc3f3a75e353/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L2830)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Do we have  the following tests:

1) start date and end date are identical, and if so, what is the behavior?
2) the first interval is a full week
3) the last interval is a full week
</blockquote></details>

I added a test to cover number 1. That throws an error. 2 and 3 are already covered.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 1145 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-O9k5iwA-kStedfDkZHZ:-O9kXKQRBa26Ru7vB8gt:bjteyh8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d3f9f6536d403356926d64e171899600d3b71a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L1145)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that I believe we could add the operator extensions, but that probably belongs in common-jvm. See https://kotlinlang.org/docs/operator-overloading.html#comparison-operators
</blockquote></details>

It's calling Timestamps.compare, which should allow what I'm asking for. The line right above is using an inequality.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 1145 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-O9k5iwA-kStedfDkZHZ:-O9ka9HCC0gLW43anp9A:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d3f9f6536d403356926d64e171899600d3b71a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L1145)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It's calling Timestamps.compare, which should allow what I'm asking for. The line right above is using an inequality.
</blockquote></details>

Done.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 2830 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-O9k3jET55PcP8mAIObT:-O9kbAqu6Gg1S7g-M3Qt:b-ucfknh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5c84f8051cd189e55f8c43ee2b9cc3f3a75e353/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L2830)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I added a test to cover number 1. That throws an error. 2 and 3 are already covered.
</blockquote></details>

Thanks!

**Review by kungfucraig — CHANGES_REQUESTED** [review]
Can you update the API documentation?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-:-O9kbN9gCrMOO987Bfg1:b6p0z17)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-:-O9kcx6YA3sIDuBMgl8N:b-896fix)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @kungfucraig and @SanjayVas)

**Review by kungfucraig — COMMENTED** [review]
Update metric calculation spec too?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-:-O9lFDPA1DrlcM3baW5j:b-bbwomd)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by tristanvuong2021 — COMMENTED** [review]
done.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-:-O9lRxNw5tmJn8ocGm2E:b-7rl0jd)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @kungfucraig and @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 103 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869#-O9pjkMJ-skDcRHoyDeB:-O9pjkMJ-skDcRHoyDeC:b-js8moq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96bcaff2d0a7de2bc3765d26f6b6d62d0433cc3c/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L103)):*
> ```proto
>       // occurrence of the `day_of_week`. If `report_start` date is Monday and
>       // `day_of_week` is Tuesday, the first time interval will be created for
>       // the following day.
> ```

@tristanvuong2021 The behavior should be documented here and also on the Monthly frequency.

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1869)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
