### PR TITLE
Update cue files to accommodate multithreading mills.

### PR DESCRIPTION
**Pull request by renjiezh**
I will deploy it once it is approved.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1131)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1131)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1131)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @renjiezh)

___
*[`docs/gke/duchy-deployment.md` line 155 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1131#-Na828KB9mPwdF6awRWQ:-Na828KB9mPwdF6awRWR:bnbfsl4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b3a5f8a59c3866ce8ce0ff6cf8a51db223c30d3/docs/gke/duchy-deployment.md#L155)):*
> ```Markdown
> Due to the Mill's nature that runs in multithreading mode, it is recommended
> to use the T2D machine type in a dedicated node pool. To have the best 
> performance and cost-efficiency, use machine type `t2d-standard-8` for
> ```

Note that this is an overhead of nearly 4 extra vCPU and more importantly nearly 30 extra GiB of memory. What about t2d-standard-4 and setting the CPU request slightly lower to account for node overhead?



_Code quote:_
```Markdown
t2d-standard-8
```

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1131)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`docs/gke/duchy-deployment.md` line 155 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1131#-Na828KB9mPwdF6awRWQ:-Na8a5lxEYoyTO4P0hgZ:b-cjn8bt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b3a5f8a59c3866ce8ce0ff6cf8a51db223c30d3/docs/gke/duchy-deployment.md#L155)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that this is an overhead of nearly 4 extra vCPU and more importantly nearly 30 extra GiB of memory. What about t2d-standard-4 and setting the CPU request slightly lower to account for node overhead?
</blockquote></details>

We wanted 8 threads over 4 CPUs in the ideal case, right? If so Sanjay's suggestion is a good compromise. That reasoning should be noted in the comment. 
___
*[`src/main/terraform/gcloud/cmms/duchies.tf` line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1131#-Na8aWf_6CAQxuyc733z:-Na8aWf_6CAQxuyc734-:b2nhon3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b3a5f8a59c3866ce8ce0ff6cf8a51db223c30d3/src/main/terraform/gcloud/cmms/duchies.tf#L52)):*
> ```HCL
>   name            = "highmem"
>   service_account = module.common.cluster_service_account
>   machine_type    = "t2d-standard-8"
> ```

So

**Pull request closed without merging**
