### PR TITLE
Don't expose externalIds and get rid of parallel id generation in tests

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-Me_v_iD4cN8lTP1glrx:-Me_v_iD4cN8lTP1glry:b-ft48k8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt#L26)):*
> ```
> Parallel
> ```
This isn't about generating IDs in parallel, but rather remembering the IDs that have been generated. Perhaps CachingIdGenerator?
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-Me_wAuG7t1FQF4dPJJb:-Me_wAuG7t1FQF4dPJJc:b13ccvc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt#L42)):*
> ```
> getNext
> ```
Just expose the whole collection of IDs as a Sequence. You may want to push items to the front rather than the back so the sequence iteration order is from most recent to least recent. Document the order.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-MeaCOKZ2-uwqZJw_ShI:-MeaCOKZ2-uwqZJw_ShJ:bx5l5sy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L61)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   // protected val idGenerator =
>   //   RandomIdGenerator(TestClockWithNamedInstants(TEST_INSTANT), Random(RANDOM_SEED))
>   // protected val copyIdGenerator =
>   //   RandomIdGenerator(TestClockWithNamedInstants(TEST_INSTANT), Random(RANDOM_SEED))
> ```
</details>

delete?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-MeaCS1k2ZBrQwiYx7CA:-MeaCS1k2ZBrQwiYx7CB:b-5qipws) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L103)):*
> ```
> External 
> ```
External -> ExternalId
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-MeaCIw9BTs6xS9MLgHG:-MeaCIw9BTs6xS9MLgHH:b-8oazmc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt#L23)):*
> ```
> inaand
> ```
typo

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-Me_v_iD4cN8lTP1glrx:-MeaCXKgDzimTXFNRT3L:bu47yga) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Parallel
> ```
This isn't about generating IDs in parallel, but rather remembering the IDs that have been generated. Perhaps CachingIdGenerator?
</blockquote></details>

thanks, thought about memorizing. storing, none felt right. Caching sounds great.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-Me_wAuG7t1FQF4dPJJb:-MeaAsCAAUeZvH13LQNU:b-5ffpvp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt#L42)):*
> Why do we want to expose the whole collection and why as a sequence? There won't be any laziness here since the id generation is done at the code runtime and looking up the generated ids are at testing. .I documented the order.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-MeaCOKZ2-uwqZJw_ShI:-MeaDXLk9Tx7fp5oqSE0:bhjfvjp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L61)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>   // protected val idGenerator =
>   //   RandomIdGenerator(TestClockWithNamedInstants(TEST_INSTANT), Random(RANDOM_SEED))
>   // protected val copyIdGenerator =
>   //   RandomIdGenerator(TestClockWithNamedInstants(TEST_INSTANT), Random(RANDOM_SEED))
> ```
delete?
</blockquote></details>

from earlier snapshot
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-MeaCS1k2ZBrQwiYx7CA:-MeaDbQ599KI3RQM29mf:bd1czxm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L103)):*
> External
ah thanks
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-MeaCIw9BTs6xS9MLgHG:-MeaCsU92dsXKuRc0K5R:brqb90e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt#L23)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> inaand
> ```
typo
</blockquote></details>

weird, this is from an earlier snapshot of the code. I had fixed it. It looks like it's fixed.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-Me_wAuG7t1FQF4dPJJb:-MeaF-NU-wnuL5oYSSpf:b-6sk2w5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt#L42)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

> Why do we want to expose the whole collection and why as a sequence? There won't be any laziness here since the id generation is done at the code runtime and looking up the generated ids are at testing. .I documented the order. 
</blockquote></details>

This class shouldn't make any assumptions about how it's used. It's just an `IdGenerator` that wraps another one and stores/exposes the generated IDs. It's up to the caller how they want to use those stored values.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-Me_wAuG7t1FQF4dPJJb:-MeaRR_B1TUscI5BMulq:b-kd8tmf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This class shouldn't make any assumptions about how it's used. It's just an `IdGenerator` that wraps another one and stores/exposes the generated IDs. It's up to the caller how they want to use those stored values.
</blockquote></details>

I guess this should work or do you want me to get rid of the getNext Methods? I don't agree this class should not make any assumptions of about how its used. The main function is to use it with getNext. If you don't think this is reflected in the name maybe we can change it. I also changed the order so the take() method of sequence will return the earliest generated nodes.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-Me_wAuG7t1FQF4dPJJb:-MeaTC7pEVpSHOPUCUtW:bat3hcu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt#L42)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I guess this should work or do you want me to get rid of the getNext Methods? I don't agree this class should not make any assumptions of about how its used. The main function is to use it with getNext. If you don't think this is reflected in the name maybe we can change it. I also changed the order so the take() method of sequence will return the earliest generated nodes.
</blockquote></details>

Again, the idea is just to have something that remembers the generated IDs so that tests can access them. It's generally a good idea to keep classes for testing as simple as possible.

I think this class shouldn't even have getNext methods. The only way to mutate the internal state of an instance should be by generating IDs. Since this is only for testing, we expect each instance to be short-lived and not have many IDs remembered. Therefore, we don't need any mechanism for freeing up the collection of remembered IDs.

It's up to the caller if it wants to use a queue or stack or popping off "used" IDs.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-Me_wAuG7t1FQF4dPJJb:-MeajLYr89o54qAid5AI:bbw8ibd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Again, the idea is just to have something that remembers the generated IDs so that tests can access them. It's generally a good idea to keep classes for testing as simple as possible.

I think this class shouldn't even have getNext methods. The only way to mutate the internal state of an instance should be by generating IDs. Since this is only for testing, we expect each instance to be short-lived and not have many IDs remembered. Therefore, we don't need any mechanism for freeing up the collection of remembered IDs.

It's up to the caller if it wants to use a queue or stack or popping off "used" IDs.
</blockquote></details>

Gotcha, thanks for the explanation - best to keep testing classes simple as possible -  
Here is the problem. In test cases 
1) we insert an MC - this generates a bunch of ids. Then from the cachingIdGenerator we find the ids we are interested in and maybe we use them to make a call 
2) Then we insert a DP - this also generates some ids. We take the ones that we are interested in and maybe we use them to make a call 

If we don't have getNext, we would need to take the whole generated id sequence twice and depending on the order of insertMC or insertDP, we will have different indexes of the ids. We will need to do the id math in the test cases where as if we consume the ids with getNext, these functions (or any function that generates ids) can be treated independently - given they consume the ids they generate. 

If I am understanding this correctly what you are suggesting is having a function that returns the ids that are generated thus far as an immutable structure, while this will make the CachingIdGenerator simpler, it will make the test cases themselves more complicated. 

Maybe I am understanding wrong or thinking of this wrong. Does this make sense and if so do you think it is a valid tradeoff?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 139 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-MeasEQw8wCD6JB-oWtA:-MeasEQw8wCD6JB-oWtB:b-prnzf1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7381b0b7a99bb27d3fd78406dd2f1082ec16b24f/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L139)):*
> ```Kotlin
>     cachingIdGenerator.getNextGeneratedExternalId()
> 
>     return externalDataProviderId.value
> ```

Now that I think of it, why do we need to keep track of generated IDs at all for this test? Couldn't the `insertDataProvider` and `insertMeasurementConsumer` functions just return the entire created entity?
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-Me_wAuG7t1FQF4dPJJb:-MeamkBY7FFBNxvu_fWH:btpctwv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt#L42)):*
> If we don't have getNext, we would need to take the whole generated id sequence twice and depending on the order of insertMC or insertDP, we will have different indexes of the ids.

Couldn't you just use a separate instance of this generator for each, but share the underlying generator to guarantee that IDs remain unique?

> If I am understanding this correctly what you are suggesting is having a function that returns the ids that are generated thus far as an immutable structure

Technically `asSequence()` returns an unmodifiable view rather than an immutable snapshot, as it's automatically updated to reflect any mutations on the list.

> while this will make the CachingIdGenerator simpler, it will make the test cases themselves more complicated.

Not necessarily. The reason I suggested writing this IdGenerator is to avoid the clunkines of having to have parallel calls to generate/getNext for each ID.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-Me_wAuG7t1FQF4dPJJb:-Meb-uIYD8DM6biVCryW:boynq23) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bc4bf99e7121766f8eabf3d3e29e162796f332f/src/main/kotlin/org/wfanet/measurement/common/identity/testing/ParallelIdGenerator.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> If we don't have getNext, we would need to take the whole generated id sequence twice and depending on the order of insertMC or insertDP, we will have different indexes of the ids.

Couldn't you just use a separate instance of this generator for each, but share the underlying generator to guarantee that IDs remain unique?

> If I am understanding this correctly what you are suggesting is having a function that returns the ids that are generated thus far as an immutable structure

Technically `asSequence()` returns an unmodifiable view rather than an immutable snapshot, as it's automatically updated to reflect any mutations on the list.

> while this will make the CachingIdGenerator simpler, it will make the test cases themselves more complicated.

Not necessarily. The reason I suggested writing this IdGenerator is to avoid the clunkines of having to have parallel calls to generate/getNext for each ID.
</blockquote></details>

Thank you! I hadn't understand that "asSequence() returns an unmodifiable view rather than an immutable snapshot, as it's automatically updated to reflect any mutations on the list." Now it works. To your question about separate idgenerator instances:  that won't work unfortunately because all of the internal services use the same id generator. However this doesn't matter because of the unmodifiable view and adding the latest ids at head, it now satisfies the same property with the getNext about being able to implement independent functions.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 139 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149#-MeasEQw8wCD6JB-oWtA:-MebNJUM4G67InDiHlpG:blop9ez) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7381b0b7a99bb27d3fd78406dd2f1082ec16b24f/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L139)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Now that I think of it, why do we need to keep track of generated IDs at all for this test? Couldn't the `insertDataProvider` and `insertMeasurementConsumer` functions just return the entire created entity?
</blockquote></details>

You are right. They don't need to even return the entire entity, just the externalId. I fixed it and got rid of keeping track of Ids.

**Review by zachcwc — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: all files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 1 of 2 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 1 of 2 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/149)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

**Pull request merged**
