### PR TITLE
Check EDP authorization in the duchy RequisitionFulfillmentService.

### PR DESCRIPTION
**Pull request by wangyaopw**
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F615173529171&view=2c2927c0-626b-4740-8620-af2a93b7d623

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/377)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/377)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @efoxepstein)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/377)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/377#-Mopc1At40WIVcc9bJOW:-Mopc1At40WIVcc9bJOX:bj7qz8s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bc4dd84229cd475a4c68c5758fb8ef9d7c43ccfd/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L61)):*
> ```Kotlin
> 
>   private lateinit var edpJob: Job
>   private lateinit var dataProviderResourceName: String
> ```

Can you be consistent with the line above? Like, they should either both start with `edp` or both with `dataProvider` -- I prefer the latter.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/377)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/377#-Mopc1At40WIVcc9bJOW:-Motdly8E7OQwqhpilhV:b-5kp87e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bc4dd84229cd475a4c68c5758fb8ef9d7c43ccfd/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L61)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you be consistent with the line above? Like, they should either both start with `edp` or both with `dataProvider` -- I prefer the latter.
</blockquote></details>

renamed to `edpName` since everywhere else is using `edp`.

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/377)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
