### PR TITLE
feat: report processor to support incremental reach.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960#-ODlq3Gm9MiKOxleQKsB:-ODlq3Gm9MiKOxleQKsC:b7zoa00) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2da6ec2cacbab90a3db4b3fa8d820735ae3c84/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L34)):*
> ```Kotlin
> 
>   // TODO(@ple13): Move this function to a separate Origin-specific package.
>   fun convertTagToJsonFormat(tag: String): String {
> ```

My understanding is that the tags are already in JSON format. You just need to parse them into objects. Use the `Gson` library to get a `JsonObject`.

The whole point was to not have to write string manipulation/parsing code, but utilize the fact that the tags are already JSON objects.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960#-ODlq3Gm9MiKOxleQKsB:-ODlscohAxfzXtoHNUsl:b-cbatx0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2da6ec2cacbab90a3db4b3fa8d820735ae3c84/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

My understanding is that the tags are already in JSON format. You just need to parse them into objects. Use the `Gson` library to get a `JsonObject`.

The whole point was to not have to write string manipulation/parsing code, but utilize the fact that the tags are already JSON objects.
</blockquote></details>

You're right that the tags are in JSON format, however, we need to extract information from the value of the tag. And the value is just a structured string, not a json string. For example, for the following tag
`"measurementConsumers/TjyUnormbAg/reportingSets/f4fee2bcb73a4cf08a6bd1ad33a61e48": "{measured_entity=edp2, viewability=, set_operation=union,incrementality,cumulative,marked unions for reach only, position_in_incrementality=, version=1.0, lhs_reporting_set_ids=, rhs_reporting_set_ids=, target=edp2, incrementality_type=ENTITY, video_completion=, channels=, unique_Reach_Target=, media_type=DISPLAY, anchor=edp1, primitive_egroup_id=aDnfoB_curE, measurement_entities=edp2, measurement_policy_incrementality=AMI, campaign_id=0568606a-910b-4a36-a439-b38fc66fc4ae, measurement_policy=AMI}"`
has JSON format ("key": "value"), but "value" is not a JSON string.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960#-ODlq3Gm9MiKOxleQKsB:-ODlwSd28rHYmUmC-Zjz:b-wkpn9w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2da6ec2cacbab90a3db4b3fa8d820735ae3c84/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L34)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

You're right that the tags are in JSON format, however, we need to extract information from the value of the tag. And the value is just a structured string, not a json string. For example, for the following tag
`"measurementConsumers/TjyUnormbAg/reportingSets/f4fee2bcb73a4cf08a6bd1ad33a61e48": "{measured_entity=edp2, viewability=, set_operation=union,incrementality,cumulative,marked unions for reach only, position_in_incrementality=, version=1.0, lhs_reporting_set_ids=, rhs_reporting_set_ids=, target=edp2, incrementality_type=ENTITY, video_completion=, channels=, unique_Reach_Target=, media_type=DISPLAY, anchor=edp1, primitive_egroup_id=aDnfoB_curE, measurement_entities=edp2, measurement_policy_incrementality=AMI, campaign_id=0568606a-910b-4a36-a439-b38fc66fc4ae, measurement_policy=AMI}"`
has JSON format ("key": "value"), but "value" is not a JSON string.
</blockquote></details>

Ahh, okay I misunderstood. This PR is not needed then.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960#-ODlq3Gm9MiKOxleQKsB:-ODlxSfH8v7iJfx8_9KM:b-6r5o6o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2da6ec2cacbab90a3db4b3fa8d820735ae3c84/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ahh, okay I misunderstood. This PR is not needed then.
</blockquote></details>

This PR also adds support for incremental reach. I think it's cleaner to convert the value of the tag into json string, then parse it. In the future, we may need to use other fields such as viewability, video_completion, etc., and won't need to add code to handle them.

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960)* status: 2 of 12 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960#-ODlq3Gm9MiKOxleQKsB:-ODme2bcBujpQQOHbZqn:b94ifj5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2da6ec2cacbab90a3db4b3fa8d820735ae3c84/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This isn't actually JSON so there's no need to use JSON in your parsing. If you want to parse the whole tag, parse either into a specific Kotlin data class (if you want a schema) or some generic struct type (schemaless). I suppose for the latter you could use a Gson JSON object. Regardless, the point remains the same: do *parsing* into a Kotlin object, **not** string manipulation.

Importantly, it looks like you're trying to parse this into a ReportingSet message. We shouldn't be relying on the fact that Origin happens to copy a structure that *looks like* it contains the same fields as ReportingSet. CC @kungfucraig
</blockquote></details>

@SanjayVas what do you mean trying to parse into a "ReportingSet message?" This PR defines it's own ReportingSet message that seems to conform to the Origin side of the world. 

It makes sense that we have some structure like that. That said, I'm not a huge fan of overloading the names of the reporting server resources. ReportingSetSummary was not bad though.

@ple13 Are you going to continue with this approach or change it significantly? I'm trying to decide if I should read the PR now or wait.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960)* status: 2 of 12 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960#-ODlq3Gm9MiKOxleQKsB:-ODmhuQe54sW4eJcfmW7:b-ujhte0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2da6ec2cacbab90a3db4b3fa8d820735ae3c84/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L34)):*
> @SanjayVas what do you mean trying to parse into a "ReportingSet message?" This PR defines it's own ReportingSet message that seems to conform to the Origin side of the world.

Ah, I did not see that and definitely assumed it was the one from the Reporting API given that this file already imports other messages from that API. My statement stands that going from Origin tag to JSON to protobuf is a waste. Unless you need to pass these messages across API boundaries, just parse to Kotlin data classes directly.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960)* status: 2 of 12 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960#-ODlq3Gm9MiKOxleQKsB:-ODmgOY97ZHjorLOGqpH:b5l2rop) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2da6ec2cacbab90a3db4b3fa8d820735ae3c84/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> @SanjayVas what do you mean trying to parse into a "ReportingSet message?" This PR defines it's own ReportingSet message that seems to conform to the Origin side of the world.

Ah, I did not see that and definitely assumed it was the one from the Reporting API given that this file already imports other messages from that API. My statement stands that going from Origin tag to JSON to protobuf is a waste. Unless you need to pass these messages across API boundaries, just parse to Kotlin data classes directly.
</blockquote></details>

@SanjayVas the ReportingSet proto and MetricCalculationSpec proto are defined based on the Origin's tag. As the tag value string doesn't have a recognizable format, and is not well structured, I'd expect some string manipulation is needed. Converting the string to JSON first, then from JSON to either ReportingSet or MetricCalculationSpec requires the least amount of string manipulation. Ideally, the tag value should be in JSON format so that no string manipulation is needed.
@kungfucraig If @SanjayVas is okay with this approach, I'd like to stick to it. We could also ask for the tag to have JSON format, so that no string manipulation is needed (but this may introduce considerable overhead). Anyway, I think you could focus on the python code that adds the support for incremental reach first, and circle back to the Kotlin code later. WDYT?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960)* status: 2 of 12 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960#-ODlq3Gm9MiKOxleQKsB:-ODnAd0T0_2jLiEP2Fdh:bho4xi7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2da6ec2cacbab90a3db4b3fa8d820735ae3c84/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L34)):*
> the ReportingSet proto and MetricCalculationSpec proto are defined based on the Origin's tag

My suggestion is to make these Kotlin data classes rather than protobufs message types, but that's not a huge deal. The more important part is the following:

> Converting the string to JSON first, then from JSON to either ReportingSet or MetricCalculationSpec requires the least amount of string manipulation

There's no need to go through JSON in between. Just build your object directly. The only reason I even mentioned JSON is because I thought that Origin tag values were already JSON objects, where you could just call Gson.fromJson and be done.

> Ideally, the tag value should be in JSON format so that no string manipulation is needed.

No, ideally there are multiple tags and each of them is an unstructured flat value. Meaning Origin is already misusing the tagging feature by putting in structured data rather than using multiple tags. It's too late to fix this though.

> We could also ask for the tag to have JSON format

No, the point is to operate on what Origin already has.

**Review by SanjayVas — APPROVED** [review]
Approved Kotlin code.

> Reviewed 4 of 12 files at r1, 1 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960#-:-ODqh4u51XIOCa-iqb-b:b-juudcq)* status: 10 of 12 files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 4 of 12 files at r1, 3 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/tools/post_process_origin_report.py` line 88 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960#-ODvadztEezgaOZAURQ1:-ODvadztEezgaOZAURQ2:b-b0br5q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1969234e5f8669018e9cad027b88a7ca059ab04b/src/main/python/wfa/measurement/reporting/postprocessing/tools/post_process_origin_report.py#L88)):*
> ```Python
>     self._process_primitive_measurements()
> 
>     # Process unique reach measurements.
> ```

nit: Update comment

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @kungfucraig)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/tools/post_process_origin_report.py` line 88 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960#-ODvadztEezgaOZAURQ1:-ODwW_36BGcsmBkK7xGP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1969234e5f8669018e9cad027b88a7ca059ab04b/src/main/python/wfa/measurement/reporting/postprocessing/tools/post_process_origin_report.py#L88)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

nit: Update comment
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 12 files at r1, 2 of 5 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1960)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
