### PR TITLE
Update common-jvm for trace ID logging.

### LINKED ISSUE #766: Add ability to trace calls across Halo components
It would be useful if the logs across the reporting server and the Kingdom could be traced

- [x] https://github.com/world-federation-of-advertisers/common-jvm/pull/223
- [ ] #1334

### PR DESCRIPTION
**Pull request by SanjayVas**
Closes #766

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1334)

**Comment by SanjayVas** [comment]
Depends on https://github.com/world-federation-of-advertisers/common-jvm/pull/223 and #1332

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1334)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1334)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
