### PR TITLE
Update panel match client to use internal proto definitions.

### PR DESCRIPTION
**Pull request by robinsons**
Updates most of the panel match code to remove dependencies on classes in the `org.wfanet.measurement.api.v2alpha` package.

Most of the interesting changes are in the `src/main/kotlin/org/wfanet/panelmatch/client/launcher` directory, where some of the core interfaces for claiming and launching exchange tasks have been changed slightly.

A small number of dependencies on the v2alpha API still remain:

* `ProtoConversions.kt` - This class is specifically meant for converting the v2alpha messages into the panel match internal ones.
* `ExchangeWorkflowDaemonFromFlags.kt` and related integration test classes - These will continue to depend on v2alpha -- or the whatever the current API version is -- as long as there is an option for running Kingdom-based exchanges.
* `GrpcApiClient.kt` and `V2AlphaCertificateManager.kt` - Same as the previous bullet. These will continue to be used by any daemon that runs a Kingdom-based exchange.
* A few standalone tools continue to support the v2alpha message definitions alongside the new internal ones.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 71 of 71 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670)* status: all files reviewed, 5 unresolved discussions (waiting on @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImpl.kt` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670#-O0iviYs87BbcTndcnBQ:-O0iviYs87BbcTndcnBR:b-7g3q49) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1474324db4d91c94d96572427487d67fbe134b64/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImpl.kt#L44)):*
> ```Kotlin
>           "No ExchangeWorkflow known for RecurringExchange $recurringExchangeId",
>         )
>     val existingWorkflowFingerprint = farmHashFingerprint64(serializedExistingExchangeWorkflow)
> ```

so, if you're going to fingerprint these to ensure another workflow was not used nefariously, they need to use a cryptographically secure hash like sha256.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/launcher/GrpcApiClient.kt` line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670#-O0iwtR--V_pNXVakdyY:-O0iwtR--V_pNXVakdyZ:bcjlec9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1474324db4d91c94d96572427487d67fbe134b64/src/main/kotlin/org/wfanet/panelmatch/client/launcher/GrpcApiClient.kt#L83)):*
> ```Kotlin
>       stepIndex = exchangeStep.stepIndex,
>       workflow = packedV2AlphaWorkflow.unpack<ExchangeWorkflow>().toInternal(),
>       workflowFingerprint = farmHashFingerprint64(packedV2AlphaWorkflow.value),
> ```

as stated elsewhere, this should be a cryptographically secure hash rather than a fingerprint
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670#-O0iyo071osf3GT2F-2H:-O0iyo080L8xA_fwhtGh:baqkxpe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1474324db4d91c94d96572427487d67fbe134b64/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L111)):*
> ```Kotlin
> 
>   @Option(
>     names = ["--exchange-workflow-format"],
> ```

the format actually implies if the workflow is kingdomless or not. I'd prefer a `--kingdomless` flag instead or something like that that implies what format is used.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/CertificateManager.kt` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670#-O0j-Oqq-4uWME_dSs1L:-O0j-Oqq-4uWME_dSs1M:b-nc3iq5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1474324db4d91c94d96572427487d67fbe134b64/src/main/kotlin/org/wfanet/panelmatch/common/certificates/CertificateManager.kt#L33)):*
> ```Kotlin
>    *
>    * @param exchange the Exchange that the certificate is scoped for
>    * @param certName the name for the certificate we want to retrieve
> ```

i think a better comment is justified how the certName is derived. It could either be the public resource name or however it is decided for kingdomless, correct?
___
*[`src/main/kotlin/org/wfanet/panelmatch/integration/ExchangeWorkflowDaemonForTest.kt` line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670#-O0izMJF5Y6xzvUeC75y:-O0izMJF5Y6xzvUeC75z:b-g0exas) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1474324db4d91c94d96572427487d67fbe134b64/src/main/kotlin/org/wfanet/panelmatch/integration/ExchangeWorkflowDaemonForTest.kt#L102)):*
> ```Kotlin
>       is DataProviderKey -> Identity(provider.dataProviderId, Party.DATA_PROVIDER)
>       is ModelProviderKey -> Identity(provider.modelProviderId, Party.MODEL_PROVIDER)
>       else -> error("Invalid provider: $provider")
> ```

i believe the best practice is not include an else but make this exhaustive

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670)* status: 61 of 71 files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImpl.kt` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670#-O0iviYs87BbcTndcnBQ:-O0jv6MaEKeJUeR6Z1qm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1474324db4d91c94d96572427487d67fbe134b64/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImpl.kt#L44)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

so, if you're going to fingerprint these to ensure another workflow was not used nefariously, they need to use a cryptographically secure hash like sha256.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/launcher/GrpcApiClient.kt` line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670#-O0iwtR--V_pNXVakdyY:-O0jv7t768oZSqZNy2NS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1474324db4d91c94d96572427487d67fbe134b64/src/main/kotlin/org/wfanet/panelmatch/client/launcher/GrpcApiClient.kt#L83)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

as stated elsewhere, this should be a cryptographically secure hash rather than a fingerprint
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670#-O0iyo071osf3GT2F-2H:-O0jwvF574xhTiCZ_L8I:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1474324db4d91c94d96572427487d67fbe134b64/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L111)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

the format actually implies if the workflow is kingdomless or not. I'd prefer a `--kingdomless` flag instead or something like that that implies what format is used.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/CertificateManager.kt` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670#-O0j-Oqq-4uWME_dSs1L:-O0k-T_eCiW7KSY6V9r0:b5kda22) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1474324db4d91c94d96572427487d67fbe134b64/src/main/kotlin/org/wfanet/panelmatch/common/certificates/CertificateManager.kt#L33)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think a better comment is justified how the certName is derived. It could either be the public resource name or however it is decided for kingdomless, correct?
</blockquote></details>

Added more description. LMK if you want it tweaked further.
___
*[`src/main/kotlin/org/wfanet/panelmatch/integration/ExchangeWorkflowDaemonForTest.kt` line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670#-O0izMJF5Y6xzvUeC75y:-O0k00oB9ciRa8REswo2:bw3d80z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1474324db4d91c94d96572427487d67fbe134b64/src/main/kotlin/org/wfanet/panelmatch/integration/ExchangeWorkflowDaemonForTest.kt#L102)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i believe the best practice is not include an else but make this exhaustive
</blockquote></details>

`provider` is a `ResourceKey`. Since it's not a `sealed interface` I don't think I can make it exhaustive.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1670)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons)

**Pull request merged**
