### PR TITLE
Update internal API for Event Groups.

### PR DESCRIPTION
**Pull request by robinsons**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @stevenwarejones)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group.proto, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388#-MpwGpLF6Vw8ObdNdHvQ:-MpwGpLG-PWBsWNUAV1y:b1odwwy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19b77610070c8bdaabbd0d9883b7dd9c951106a9/src/main/proto/wfa/measurement/internal/kingdom/event_group.proto#L41)):*
> ```protobuf
>   }
> 
>   message Details {
> ```

You'll want an api_version field so that we know which version of the EncryptionPublicKey message to use for deserialization.

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group.proto, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388#-MpwGpLF6Vw8ObdNdHvQ:-MpwJeK_7cUhEeHVAD9N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19b77610070c8bdaabbd0d9883b7dd9c951106a9/src/main/proto/wfa/measurement/internal/kingdom/event_group.proto#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You'll want an api_version field so that we know which version of the EncryptionPublicKey message to use for deserialization.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @stevenwarejones)

**Review by chipingyeh — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group.proto, line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388#-Mq04lkJ4mmaCct0H5Zg:-Mq04lkJ4mmaCct0H5Zh:b-jj1eiz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc76652f646a822b603784b0549f7bdc69aacd26/src/main/proto/wfa/measurement/internal/kingdom/event_group.proto#L54)):*
> ```protobuf
>     // The Event Templates that this Event Group conforms to.
>     repeated EventTemplate event_templates = 5;
> ```

Did we opt to not have a custom "Metadata" message anymore?

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group.proto, line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388#-Mq04lkJ4mmaCct0H5Zg:-Mq0BQRtAiQoxFkXD522:b-ji035k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc76652f646a822b603784b0549f7bdc69aacd26/src/main/proto/wfa/measurement/internal/kingdom/event_group.proto#L54)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Did we opt to not have a custom "Metadata" message anymore?
</blockquote></details>

We will have one -- I'm putting together an options doc for it currently -- but it only needs to be included in the public API. By the time we get to the internal API, the metadata is just passed around as bytes in the `encrypted_metadata` field.

**Review by chipingyeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by duliomatos1 — COMMENTED** [review]
lgtm, just a nit.
Is this based on top of 77?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388#-:-MqGLdyw44WCsbf9OE3z:b726ewq)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group.proto, line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388#-MqGHfdV6IrhPzoUw9cJ:-MqGHfdV6IrhPzoUw9cK:b3pxecg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc76652f646a822b603784b0549f7bdc69aacd26/src/main/proto/wfa/measurement/internal/kingdom/event_group.proto#L41)):*
> ```protobuf
>   }
> 
>   message Details {
> ```

Nit-picking:

Not sure about the naming, `Details`, seems a bit vague. But do we need to package those fields as a separate message or can they be part of EventGroup?
If we need these fields separate in code, how about naming it something like `EventGroupSpecs` or `EventGroupDetails`?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group.proto, line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388#-MqGHfdV6IrhPzoUw9cJ:-MqGMRXR4rrobcy-r1ig:b6c1g8v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc76652f646a822b603784b0549f7bdc69aacd26/src/main/proto/wfa/measurement/internal/kingdom/event_group.proto#L41)):*
This is following the established pattern of our other internal entity messages. See other messages in this package.

> do we need to package those fields as a separate message or can they be part of EventGroup?

They need to be a separate message, as these are the fields that get serialized and stored into a single column. The other fields map directly to their own DB columns.

> If we need these fields separate in code, how about naming it something like EventGroupSpecs or EventGroupDetails?

It's a submessage of `EventGroup`, so `EventGroupDetails` would be redundant.

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group.proto, line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388#-MqGHfdV6IrhPzoUw9cJ:-MqGNEHs3rVkrU4bpRTx:b-3rostr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc76652f646a822b603784b0549f7bdc69aacd26/src/main/proto/wfa/measurement/internal/kingdom/event_group.proto#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is following the established pattern of our other internal entity messages. See other messages in this package.

> do we need to package those fields as a separate message or can they be part of EventGroup?

They need to be a separate message, as these are the fields that get serialized and stored into a single column. The other fields map directly to their own DB columns.

> If we need these fields separate in code, how about naming it something like EventGroupSpecs or EventGroupDetails?

It's a submessage of `EventGroup`, so `EventGroupDetails` would be redundant.
</blockquote></details>

Cool, seems fine to me then if it's a project pattern and for serialization

**Review by robinsons — COMMENTED** [review]
It's not (they're separate repos).

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388#-:-MqGMKr9-iKmSkpxKSW4:b-s9njqq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
