### PR TITLE
Fix option name of healthPort

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/660)

### CODE REVIEW

**Comment by iverson52000** [comment]
Tested KinD deployment and it's working after the changes

**Comment by iverson52000** [comment]
:lgtm:

**Review by iverson52000 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/660#-:-N98dcQCBcK11hk2bHXv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/660)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Comment by SanjayVas** [comment]
This fixes a bug introduced in #655.

**Review by stevenwarejones — COMMENTED** [review]
lgtm

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/660#-:-N9D1UfV2gehxaaChhkD:bb7k0qh)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
