### PR TITLE
refactor!: Improve performance of StreamRequisitions

### PR DESCRIPTION
**Pull request by tristanvuong2021**
refactor!: Improve performance of StreamRequisitions

BREAKING CHANGE: ListRequisitions page token has been modified. Old page tokens will return unexpected results.

StreamRequisitions does not meet performance expectations in certain situations when trying to meet the default rpc deadline of 30 seconds.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto` line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8IQatQEdcjWvU7sfX0:-O8IQatQEdcjWvU7sfX1:b54sefm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e14dba5286aab39b26787b2b545c3ff1e5edb04/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L66)):*
> ```proto
>   int32 limit = 2;
> 
>   enum OrderBy {
> ```

Allowing order to be specified breaks the after filter for next page token. I think we can instead just break the existing page tokens and change both the ordering and the page token to add the update time field.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto` line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8IQatQEdcjWvU7sfX0:-O8N8Rlz4cu0qpeXPUKF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5d9f19bcc6da23959ef233c96521836d081a3b3a/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Allowing order to be specified breaks the after filter for next page token. I think we can instead just break the existing page tokens and change both the ordering and the page token to add the update time field.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8NlhtN61MINg0r75G6:-O8NlhtN61MINg0r75G7:b-hcnwj9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19741c604dc0abf316f15bd2d6d9b80e676bea83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L34)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.common.DuchyIds
> 
> private object Params {
> ```

Put this inside companion object
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8NlnYgAokfEvGOqbhl:-O8NlnYgAokfEvGOqbhm:btmx7sw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19741c604dc0abf316f15bd2d6d9b80e676bea83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L52)):*
> ```Kotlin
>     get() = BASE_SQL
> 
>   private val BASE_SQL =
> ```

Move this to companion object
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt` line 83 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8NmbdX34PnT0pyHNRG:-O8NmbdX34PnT0pyHNRH:b-sxzxkn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19741c604dc0abf316f15bd2d6d9b80e676bea83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L83)):*
> ```Kotlin
> 
>   /** Optional ORDER BY clause that is appended at the end of the overall query. */
>   var orderByClause: String? = null
> ```

You should only need to do this in the case of temporary tables (e.g. using WITH). I'm not sure that this query needs that. Did you actually see a difference in the query plan when ORDER BY is present?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt` line 164 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8NmM5C5coRKJ1YWbwc:-O8NmM5C5coRKJ1YWbwd:bgzxr5i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19741c604dc0abf316f15bd2d6d9b80e676bea83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L164)):*
> ```Kotlin
> 
>   companion object {
>     private val DEFAULT_SQL =
> ```

Why two different queries (this and BASE_SQL)? Should always be able to do the same one since there's no views.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto` line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8Nn6EX-9Q2AC8Cp9jG:-O8Nn6EX-9Q2AC8Cp9jH:b-w36q9m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5d9f19bcc6da23959ef233c96521836d081a3b3a/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L54)):*
> ```proto
>     int64 external_data_provider_id = 3;
>     repeated Requisition.State states = 4;
>     google.protobuf.Timestamp updated_after = 5;
> ```

Why was this dropped? A caller should be able to filter by update time even without having a next page token from a previous call.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8NlhtN61MINg0r75G6:-O8NsueT3VpG7iDqR9J-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19741c604dc0abf316f15bd2d6d9b80e676bea83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Put this inside companion object
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8NlnYgAokfEvGOqbhl:-O8NsvBK9ggQp6k4Wssl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19741c604dc0abf316f15bd2d6d9b80e676bea83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move this to companion object
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt` line 83 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8NmbdX34PnT0pyHNRG:-O8NxDVaEK94RvW9XT3B:b-62yap8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19741c604dc0abf316f15bd2d6d9b80e676bea83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You should only need to do this in the case of temporary tables (e.g. using WITH). I'm not sure that this query needs that. Did you actually see a difference in the query plan when ORDER BY is present?
</blockquote></details>

I am using WITH.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt` line 164 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8NmM5C5coRKJ1YWbwc:-O8NxKbF1kzC9NAQSBGO:bob2aee) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19741c604dc0abf316f15bd2d6d9b80e676bea83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L164)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why two different queries (this and BASE_SQL)? Should always be able to do the same one since there's no views.
</blockquote></details>

It is so I can easily insert the where clause in between. I renamed BASE_SQL to WITH_SQL.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto` line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8Nn6EX-9Q2AC8Cp9jG:-O8NtQikBBkiUZ1Vu_Sv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5d9f19bcc6da23959ef233c96521836d081a3b3a/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why was this dropped? A caller should be able to filter by update time even without having a next page token from a previous call.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt` line 83 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8NmbdX34PnT0pyHNRG:-O8O4TYM6U0ySNH6Xi31:bxjvdd9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19741c604dc0abf316f15bd2d6d9b80e676bea83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L83)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I am using WITH.
</blockquote></details>

Yes, I see that you're using WITH. What I'm asking is whether you need to, meaning does it actually make a difference in the query plan to use WITH when ORDER BY is present?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt` line 83 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8NmbdX34PnT0pyHNRG:-O8bmp535RmY_5RohSQw:b71xpd7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19741c604dc0abf316f15bd2d6d9b80e676bea83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, I see that you're using WITH. What I'm asking is whether you need to, meaning does it actually make a difference in the query plan to use WITH when ORDER BY is present?
</blockquote></details>

It does. Initially I tried just updating the order by to get what I needed for the big query metrics, but it was timing out with the default rpc deadline.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt` line 86 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8c2w_OE4Gz14fXa0mN:-O8c2w_OE4Gz14fXa0mO:bv2dssr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f3b05d85f162f37b0f9621c93fc1bfe6bc45d43/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L86)):*
> ```Kotlin
>       )
> 
>       bind(UPDATED_AFTER to filter.after.updateTime.toGcloudTimestamp())
> ```

The after (page token) filter and the updated_after filter need to be bound to different parameters, as they could have different values.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt` line 164 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8NmM5C5coRKJ1YWbwc:-O8c13kx138uL02CXNsk:bq8j1jq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19741c604dc0abf316f15bd2d6d9b80e676bea83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L164)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It is so I can easily insert the where clause in between. I renamed BASE_SQL to WITH_SQL.
</blockquote></details>

I think my confusion here is that "default" sounds like what's used as an alternative. Meaning BASE_SQL was fine, and DEFAULT_SQL was perhaps the one that needed to be renamed. Perhaps `SUBQUERY_SQL` or something since it's the subquery forming the common table expression (CTE).
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt` line 130 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8c2CtZAXoO6h-3VJcm:-O8c2CtZAXoO6h-3VJcn:b-te56pu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f3b05d85f162f37b0f9621c93fc1bfe6bc45d43/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L130)):*
> ```Kotlin
> 
>   companion object {
>     private const val EXTERNAL_COMPUTATION_ID = "externalComputationId"
> ```

nit: I had meant that you could still keep this in the Params object, just to have that object be defined inside of the companion object.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt` line 86 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837#-O8c2w_OE4Gz14fXa0mN:-O8c_cZ57oXvSQMY41Fs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f3b05d85f162f37b0f9621c93fc1bfe6bc45d43/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L86)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The after (page token) filter and the updated_after filter need to be bound to different parameters, as they could have different values.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 7 files at r2, 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1837)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
