### PR TITLE
Add Filter validation to InProcess Simulation

### PR DESCRIPTION
**Pull request by uakyol**
1) EDP registers event groups to Templates
2) MC reads finds the templates event group registered to
3) MC constructs the CEL expression with qualifying each field by it's template name by querying event template type registry
4) EDP receives the filter, creates the environment for validation by  querying event template type registry

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482)* status: all files reviewed, 9 unresolved discussions (waiting on @duliomatos1 and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt, line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT1dgkCvgBi6g4PkkT:-MyT1dgkCvgBi6g4PkkU:b799cha) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L67)):*
> ```Kotlin
> val ALL_DUCHY_NAMES = DUCHY_ID_CONFIG.duchiesList.map { it.externalDuchyId }
> val ALL_EDP_DISPLAY_NAMES = listOf("edp1", "edp2", "edp3")
> // TODO(@uakyol): Add date, social grade, gender fields once filtration is implemented.
> ```

nit: KDoc syntax for properties
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT20hr-3B-R6lQ5WdG:-MyT20hr-3B-R6lQ5WdH:bt7erww) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L46)):*
> ```Starlark
>         "//src/main/proto/wfa/measurement/api/v2alpha:requisitions_service_kt_jvm_grpc_proto",
>         "//src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing:event_templates_java_proto",
>         "@any_sketch_java//src/main/java/org/wfanet/anysketch",
> ```

use the kt_jvm_proto target



_Code quote:_
```Starlark
java_proto
```
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 123 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyTPLBK7VNAtQu526Nn:-MyTPLBK7VNAtQu526No:byp18fd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L123)):*
> ```Kotlin
>   /** Creates an eventGroup for the MC. */
>   private suspend fun createEventGroup() {
>     // val eventTemplates =
> ```

Remove



_Code quote:_
```Kotlin
    // val eventTemplates =
```
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 203 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT2NPS9p6N4LA7dm7v:-MyT2NPS9p6N4LA7dm7w:b-4lc96u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L203)):*
> ```Kotlin
>         )
>       } catch (e: EventFilterValidationException) {
>         logger.info(
> ```

Warning at least?



_Code quote:_
```Kotlin
info
```
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 204 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT2Ydt-p0r262imPs6:-MyT2Ydt-p0r262imPs7:bwle8g3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L204)):*
> ```Kotlin
>       } catch (e: EventFilterValidationException) {
>         logger.info(
>           "RequisitionFulfillmentWorkflow failed due to: invalid EventFilter ${e.code}:${e.message}"
> ```

Use the logging method that takes in the exception. This way it logs all the exception info and the stack trace and you don't need to include that in your message.



_Code quote:_
```Kotlin
due to: invalid EventFilter ${e.code}:${e.message}
```
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT330XEgo7nm7tvNv5:-MyT330XEgo7nm7tvNv6:b-z682tw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel#L40)):*
> ```Starlark
>         "//src/main/proto/wfa/measurement/api/v2alpha:requisition_spec_kt_jvm_proto",
>         "//src/main/proto/wfa/measurement/api/v2alpha:requisitions_service_kt_jvm_grpc_proto",
>         "//src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing:event_templates_java_proto",
> ```

Same here re: kt proto target



_Code quote:_
```Starlark
java_proto
```
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyTUV6N2YF15PaKg358:-MyTUV6N2YF15PaKg359:bhh1zot) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L112)):*
> ```Kotlin
>   private val sketchStore: SketchStore,
>   private val runId: String,
>   private val eventTemplatesToFiltersMap: Map<String, String> = emptyMap()
> ```

nit: overly verbose name

While we prefer variables names in JVM to be more descriptive than languages such as Go, the convention for collections is to simply pluralize and leave off type information unless necessary for disambiguation. e.g. `eventTemplateFilters`

The KDoc for the param/property can give more details, e.g. "Map of event template names to filter expressions"



_Code quote:_
```Kotlin
eventTemplatesToFiltersMap
```
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 318 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyTuwhDCDFieoWJd6Ee:-MyTuwhDCDFieoWJd6Ef:bdehp5v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L318)):*
> ```Kotlin
>   }
> 
>   private suspend fun createFilterExpression(registeredEventTemplates: List<String>): String {
> ```

Document this param. Are these names (`my_template`) or types (`com.example.MyTemplate`)?



_Code quote:_
```Kotlin
registeredEventTemplates
```
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 318 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyTvIhL9pmKc7RJd9LT:-MyTvIhL9pmKc7RJd9LU:bfe7l8v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L318)):*
> ```Kotlin
>   }
> 
>   private suspend fun createFilterExpression(registeredEventTemplates: List<String>): String {
> ```

nit: prefer the least restrictive collection interface for parameters. e.g. if this only iterates through and doesn't use size or index, consider `Iterable`. If it does use size but non indexed access, consider `Collection`.



_Code quote:_
```Kotlin
List<String>
```

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482)* status: 4 of 9 files reviewed, 8 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt, line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT1dgkCvgBi6g4PkkT:-MyditelAbL13s3_dmOJ:b-97lpdz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L67)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: KDoc syntax for properties
</blockquote></details>

hope this works, these are weird since they are not defined yet.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT20hr-3B-R6lQ5WdG:-MydYtIw2DSE9zRrAzzC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

use the kt_jvm_proto target
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 123 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyTPLBK7VNAtQu526Nn:-MydG5xx6fVmJR7qyLkB:b-k73z76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L123)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

thanks
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 203 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT2NPS9p6N4LA7dm7v:-MydGBJY7BGEIMxn4bHS:buhc3bi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L203)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Warning at least?
</blockquote></details>

I can definitely do that but consider other error cases in this file that was written before, for example : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3e5f1370fe765f501f59e20de19313e1c13a6e5/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L152 

So I think there are 2 options : 

1) Keep them as is and keep this as info
2) Change all error cases to warning. 

wdyt?
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 204 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT2Ydt-p0r262imPs6:-MydajAd1Zm4bykWwLUS:bx496e0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L204)):*
>  logging method that takes in the exception
I  wasn't sure if this is what you were talking about, I just logged $e . Is this what you meant?
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT330XEgo7nm7tvNv5:-MydZ3iE-qmZBaIqHFGd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here re: kt proto target
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyTUV6N2YF15PaKg358:-MydZGB14stmgTt7YRtO:b-cxf3s3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L112)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: overly verbose name

While we prefer variables names in JVM to be more descriptive than languages such as Go, the convention for collections is to simply pluralize and leave off type information unless necessary for disambiguation. e.g. `eventTemplateFilters`

The KDoc for the param/property can give more details, e.g. "Map of event template names to filter expressions"
</blockquote></details>

thank you I was struggling with how to name this best. Left off the param property since it doesn't have for other params.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 318 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyTuwhDCDFieoWJd6Ee:-Myda6AO6IaWzJ8hKX-r:bffgusx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L318)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document this param. Are these names (`my_template`) or types (`com.example.MyTemplate`)?
</blockquote></details>

thanks, makes sense, added a KDoc



_Code quote:_
```Kotlin
createFilterExpression
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt, line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT1dgkCvgBi6g4PkkT:-MyhpEli1ufLp4WjH9pw:b-clbin1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L67)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

hope this works, these are weird since they are not defined yet.
</blockquote></details>

Put the TODO lower down. The first line should always be the summary, as that's what'll show up in tooling.

See https://developer.android.com/kotlin/style-guide#summary_fragment
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 203 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT2NPS9p6N4LA7dm7v:-Myhpjuv7bHmXIQeRz3A:b-gx058u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L203)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I can definitely do that but consider other error cases in this file that was written before, for example : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3e5f1370fe765f501f59e20de19313e1c13a6e5/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L152 

So I think there are 2 options : 

1) Keep them as is and keep this as info
2) Change all error cases to warning. 

wdyt?
</blockquote></details>

Change the other ones to warning (in a separate PR).
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 204 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT2Ydt-p0r262imPs6:-Myhq1tJ-X4paau2Qa5x:b-vnq61t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L204)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

>  logging method that takes in the exception
I  wasn't sure if this is what you were talking about, I just logged $e . Is this what you meant?
</blockquote></details>

No. There's a method on `Logger` that [takes in a `Throwable` param](https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html#log(java.util.logging.Level,%20java.lang.String,%20java.lang.Throwable)).

The syntax is admittedly not great. I thought we had a backlog item for using [Flogger](https://google.github.io/flogger/) eventually, but I can't find it.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyTUV6N2YF15PaKg358:-MyhssgfABpc8x8n26_w:bmwib1q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L112)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thank you I was struggling with how to name this best. Left off the param property since it doesn't have for other params.
</blockquote></details>

You can document the property rather than the constructor param by putting KDoc directly on the property declaration.

e.g.

```
/** Map of event template names to filter expressions. */
private val eventTemplateFilters: Map<String, String>
```

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 203 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT2NPS9p6N4LA7dm7v:-MyjYDWU374d7iP7fzOF:b-oyc361) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L203)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Change the other ones to warning (in a separate PR).
</blockquote></details>

gotcha, made this a Warning. Will have another PR for changing the rest
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 204 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-MyT2Ydt-p0r262imPs6:-MyjY41K0Kr6ViscpnkQ:beg38d3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f02e3badbf351e12674386df23125dd38554db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L204)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No. There's a method on `Logger` that [takes in a `Throwable` param](https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html#log(java.util.logging.Level,%20java.lang.String,%20java.lang.Throwable)).

The syntax is admittedly not great. I thought we had a backlog item for using [Flogger](https://google.github.io/flogger/) eventually, but I can't find it.
</blockquote></details>

awesome thank  you

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by duliomatos1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482#-:-MywoALH4AH5jEX_n2HO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 2 of 5 files at r2, 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Review by uakyol — COMMENTED** [review]
> Reviewed 3 of 9 files at r1, 1 of 5 files at r2, 3 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Comment by SanjayVas** [comment]
I think this may have broken the correctness test.

```
java.lang.UnsupportedOperationException: Empty collection can't be reduced.
        at org.wfanet.measurement.loadtest.frontend.FrontendSimulator.createFilterExpression(FrontendSimulator.kt:457)
        at org.wfanet.measurement.loadtest.frontend.FrontendSimulator.createDataProviderEntry(FrontendSimulator.kt:347)
        at org.wfanet.measurement.loadtest.frontend.FrontendSimulator$createDataProviderEntry$1.invokeSuspend(FrontendSimulator.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at org.wfanet.measurement.loadtest.frontend.FrontendSimulatorRunner.run(FrontendSimulatorRunner.kt:75)
        at org.wfanet.measurement.loadtest.frontend.ForwardedStorageFrontendSimulatorRunner.run(ForwardedStorageFrontendSimulatorRunner.kt:32)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at org.wfanet.measurement.common.CommandLinesKt.commandLineMain(CommandLines.kt:40)
        at org.wfanet.measurement.loadtest.frontend.ForwardedStorageFrontendSimulatorRunnerKt.main(ForwardedStorageFrontendSimulatorRunner.kt:36)
```

**Pull request merged**
