### PR TITLE
Fix various bugs to make all pods run on GKE.

### PR DESCRIPTION
**Pull request by wangyaopw**
TODO in future PR.
1. Create a template for kubernate Job.
2. Update EdpSimulator from Job to Pod

https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Fuserstory%2F606023914123&view=2c2927c0-626b-4740-8620-af2a93b7d623

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/248)

### CODE REVIEW

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/248)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/k8s/kingdom_and_three_duchies_gke.cue, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/248#-Micx4j48Mu_rNDV1u8h:-Micx4j53sswgH4cMJTR:b-a6y0ch) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20e9b0113359a29bf94ec2c7e848dc0c41c0bb98/src/main/k8s/kingdom_and_three_duchies_gke.cue#L36)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> // Group 2
> //objectSets: [ for d in duchies for v in d {v}] + [ for d in edp_simulators {}]
> // Group 3
> //objectSets: [
> // frontend_simulator,
> //]
> ```
</details>

What are these commented lines?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/248#-MicxLEd3KjZ-hGTqekn:-MicxLEd3KjZ-hGTqeko:bfmlh67) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20e9b0113359a29bf94ec2c7e848dc0c41c0bb98/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L71)):*
> ```Kotlin
>       .withVerboseLogging(kingdomApiServerFlags.debugVerboseGrpcClientLogging)
> 
>   // TODO: do we need something similar to .withDuchyIdentities() for EDP and MC?
> ```

Yes, we'll need to set up interceptors for all credentials. EDPs will need a config file just like the Duchy root SKID->ID mapping. MCs will use account credentials, which aren't implemented yet.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/248)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/k8s/kingdom_and_three_duchies_gke.cue, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/248#-Micx4j48Mu_rNDV1u8h:-MidOQ1Y5Hl-hr8i9GyD:b1rb45n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20e9b0113359a29bf94ec2c7e848dc0c41c0bb98/src/main/k8s/kingdom_and_three_duchies_gke.cue#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> // Group 2
> //objectSets: [ for d in duchies for v in d {v}] + [ for d in edp_simulators {}]
> // Group 3
> //objectSets: [
> // frontend_simulator,
> //]
> ```
What are these commented lines?
</blockquote></details>

we are going to deploy all pods/jobs in three stages. 

First the kingdom and the resourceSetJob, then we need to update the resource names in the cue file, build and deploy the duchies and edp simulator. Finally, we build and deploy the frontendSimulator.

The three ObjectSets are what we use for three builds.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/248)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/k8s/kingdom_and_three_duchies_gke.cue, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/248#-Micx4j48Mu_rNDV1u8h:-MidPgbZ1XBaMhOIsljn:b-sduv3b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20e9b0113359a29bf94ec2c7e848dc0c41c0bb98/src/main/k8s/kingdom_and_three_duchies_gke.cue#L36)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

we are going to deploy all pods/jobs in three stages. 

First the kingdom and the resourceSetJob, then we need to update the resource names in the cue file, build and deploy the duchies and edp simulator. Finally, we build and deploy the frontendSimulator.

The three ObjectSets are what we use for three builds.
</blockquote></details>

So we uncomment the objectSets we want to use in each build.

I used to modify code locally without checking in the code.

**Review by wangyaopw — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/248#-:-MidQga5D2PiFR5ZE6iq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Pull request merged**
