### PR TITLE
Removed VID wraparound logic

### PR DESCRIPTION
**Pull request by iverson52000**
Removed vid wraparound logic, moved privacyBucketsOverlap() to PrivayBucketGroup class, added unit test

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517)

### CODE REVIEW

**Review by uakyol — CHANGES_REQUESTED** [review]
great job Albert! Super clean and readable code. 

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-:-N-5EVOr7nvh1BoLSa6W:b-oiaakg)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000 and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5F1YR-4UbQQfPFQY-:-N-5F1YR-4UbQQfPFQY0:b-wkma7n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt#L41)):*
> ```Kotlin
> 
>   fun privacyBucketsOverlap(
>     bucketGroup1: PrivacyBucketGroup,
> ```

You don't need 2 inputs here. it should just be fun overlapsWith(other: PrivacyBucketGroup). But I am surprised it lets you do this in a DataClass. @sanjayvas do we have a policy here? Maybe we should just promote this to a proper class.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt, line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5CNsb3--kEHA4TcrC:-N-5CNsb3--kEHA4TcrD:bqj21xl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt#L59)):*
> ```Kotlin
>     }
> 
>     // Prior wrap-around logic is removed
> ```

I don't think you need this comment. Is there a specific reason for this?
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5DXsQB10PmB6K_UqJ:-N-5DXsQB10PmB6K_UqK:bo7cgcd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt#L20)):*
> ```Kotlin
> import org.junit.Test
> 
> class PrivacyBucketGroupTest {
> ```

Let's split this into 2 tests?

privacyBucketsOverlap

privacyBucketsDontOverlap
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt, line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5ED07DOj_X276QNeR:-N-5ED07DOj_X276QNeS:bz1rrpb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt#L56)):*
> ```Kotlin
>       )
> 
>     assertEquals(bucket1.privacyBucketsOverlap(bucket1, bucket2), false)
> ```

You can use assertTrue : https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/assert-true.html 
Example : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/duchy/db/computation/LiquidLegionsSketchAggregationV2ProtocolEnumStagesTest.kt#L30
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5ELYT667-1GRiY7mt:-N-5ELYT667-1GRiY7mu:b-dbftq5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt#L57)):*
> ```Kotlin
> 
>     assertEquals(bucket1.privacyBucketsOverlap(bucket1, bucket2), false)
>     assertEquals(bucket1.privacyBucketsOverlap(bucket2, bucket3), true)
> ```

ditto , assertFalse : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/duchy/db/computation/LiquidLegionsSketchAggregationV2ProtocolEnumStagesTest.kt#L35

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000, @matthewclegg, and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5_F107ufFsn-DHVQn:-N-5_F117KyvX3folEtl:bc21clo) (no related file):*
Is this your first PR? Make sure to take a peek at the  [Dev Standards Doc](https://docs.google.com/document/d/1DwbvIVjoMJ1svztNg42d7wFfAEtWno-B4ECUYfz90Jc/edit?usp=sharing) before you merge.

---
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5F1YR-4UbQQfPFQY-:-N-5_rG28FK2SB5iUUl9:bgkb5tm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt#L41)):*
> But I am surprised it lets you do this in a DataClass.

Data classes can have methods just fine. They're useful in the same cases as [AutoValue](https://github.com/google/auto), with the added benefit that they are built-in to the language.

> You don't need 2 inputs here. it should just be fun overlapsWith(other: PrivacyBucketGroup)

Correct. This should only be an instance method on PrivacyBucketGroup if it makes use of the instance's state.
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt, line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5ED07DOj_X276QNeR:-N-5auZp2qJLTM5RU7r8:b-es4sa8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt#L56)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

You can use assertTrue : https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/assert-true.html 
Example : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/duchy/db/computation/LiquidLegionsSketchAggregationV2ProtocolEnumStagesTest.kt#L30

</blockquote></details>

Minor addendum to use the Truth library rather than kotlin.test. I believe the only test assertion we should use from kotlin.test is `assertFailsWith`.

```
assertThat(bucket1.privacyBucketsOverlap(bucket1, bucket2)).isFalse()
```

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000, @matthewclegg, and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5_F107ufFsn-DHVQn:-N-95-Qb6a1FyYxdpDD8:bjrzcft) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this your first PR? Make sure to take a peek at the  [Dev Standards Doc](https://docs.google.com/document/d/1DwbvIVjoMJ1svztNg42d7wFfAEtWno-B4ECUYfz90Jc/edit?usp=sharing) before you merge.
</blockquote></details>

Yes it's my first PR! Thanks for providing the doc. Will definitely review it before I merge 

---

**Comment by iverson52000** [comment]
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt, line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5CNsb3--kEHA4TcrC:-N-99Dr05kRw3OON1iut:b-r052z8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt#L59)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I don't think you need this comment. Is there a specific reason for this?
</blockquote></details>

Make sense. Will remove it

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517)* status: all files reviewed, 5 unresolved discussions (waiting on @matthewclegg and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5F1YR-4UbQQfPFQY-:-N-9LD9SD8LM5PWkQax-:b-vletou) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> But I am surprised it lets you do this in a DataClass.

Data classes can have methods just fine. They're useful in the same cases as [AutoValue](https://github.com/google/auto), with the added benefit that they are built-in to the language.

> You don't need 2 inputs here. it should just be fun overlapsWith(other: PrivacyBucketGroup)

Correct. This should only be an instance method on PrivacyBucketGroup if it makes use of the instance's state.
</blockquote></details>

privacyBucketsOverlap(bucketGroup1, bucketGroup2) is being used in InMemoryBackingStore.kt as followed. In this case, how do we compare 2 groups with only 1 input?



_Code snippet:_
```Kotlin
override fun findIntersectingLedgerEntries(
    privacyBucketGroup: PrivacyBucketGroup,
  ): List<PrivacyBudgetLedgerEntry> {
    return transactionLedger.filter {
      privacyBucketGroup.privacyBucketsOverlap(privacyBucketGroup, it.privacyBucketGroup)
    }
  }
```
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5DXsQB10PmB6K_UqJ:-N-9EdbW5i7vB8_VSLeo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt#L20)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Let's split this into 2 tests?

privacyBucketsOverlap

privacyBucketsDontOverlap
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt, line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5ED07DOj_X276QNeR:-N-9EiC1BP9Aj9ctbIEz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Minor addendum to use the Truth library rather than kotlin.test. I believe the only test assertion we should use from kotlin.test is `assertFailsWith`.

```
assertThat(bucket1.privacyBucketsOverlap(bucket1, bucket2)).isFalse()
```
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5ELYT667-1GRiY7mt:-N-9EiVe0Gn-xhakdNSS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt#L57)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

ditto , assertFalse : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/duchy/db/computation/LiquidLegionsSketchAggregationV2ProtocolEnumStagesTest.kt#L35
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517)* status: all files reviewed, 5 unresolved discussions (waiting on @matthewclegg and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5F1YR-4UbQQfPFQY-:-N-9kb3_13Pc0oSA382Q:b-hnf4ol) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt#L41)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

privacyBucketsOverlap(bucketGroup1, bucketGroup2) is being used in InMemoryBackingStore.kt as followed. In this case, how do we compare 2 groups with only 1 input?
</blockquote></details>

One input is `this`.

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517)* status: all files reviewed, 5 unresolved discussions (waiting on @matthewclegg and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5F1YR-4UbQQfPFQY-:-N-9uDTS0AUvu_YGGwtN:bf1neas) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

One input is `this`.
</blockquote></details>

oh I got the idea! Thanks for the suggestions

**Review by uakyol — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @matthewclegg, @SanjayVas, and @uakyol)

___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt, line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5ED07DOj_X276QNeR:-N-Tq__v46SET8fyTmYI:b-q535dv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt#L56)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can you use .isFalse() as Sanjay suggested. Sorry, my suggestion was wrong
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5ELYT667-1GRiY7mt:-N-TqfeOCkG3OjUv8NE_:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt#L57)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @matthewclegg, @SanjayVas, and @uakyol)

___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt, line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5ED07DOj_X276QNeR:-N-Tww_dDRewvi5xeMFX:b-oidc93) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt#L56)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

can you use .isFalse() as Sanjay suggested. Sorry, my suggestion was wrong
</blockquote></details>

No problem. Done
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517#-N-5ELYT667-1GRiY7mt:-N-Tx06b-0gLLhnITVfr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d19679d02ce694ab86f260deb818c90eca241862/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroupTest.kt#L57)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by uakyol — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/517)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Pull request merged**
