### PR TITLE
refactor: Remove unneeded measurement view

### PR DESCRIPTION
**Pull request by tristanvuong2021**
refactor: Remove unneeded measurement view

[This](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1696) added the view, but [this](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1823) removed the need for the new view.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1854)

**Review by roaminggypsy — APPROVED** [review]
I don't have enough context on what full view means, and why it becomes unneeded, but the changes seem to achieve the goal to me. 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1854#-:-O9ELEil3602Cx1dQvb-:bc4rkwc)* status: 0 of 5 files reviewed, all discussions resolved

**Review by roaminggypsy — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1854)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
Added context to the PR description.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1854#-:-O9M8hwV3nmdlvR3rQE-:bdphk7m)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1854)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
