### PR TITLE
Implement requisition fulfillment with seeds.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 10 of 14 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt` line 339 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-Nl4fa-iCIahUotPr42q:-Nl4fa-iCIahUotPr42r:b-biu0rq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c28ccd0b27be4b3374611ee1486c04895104a39c/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt#L339)):*
> ```Kotlin
>     seed: ByteString
>   ) {
>     @Suppress("CANDIDATE_CHOSEN_USING_OVERLOAD_RESOLUTION_BY_LAMBDA_ANNOTATION")
> ```

I think you need to use the experimental [`@OverloadResolutionByLambdaReturnType`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-overload-resolution-by-lambda-return-type/) annotation rather than suppressing.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt` line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-Nl4paTc8sMkw7hTt8pT:-Nl4paTc8sMkw7hTt8pU:b47z9pn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c28ccd0b27be4b3374611ee1486c04895104a39c/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L100)):*
> ```Kotlin
>         //  is already marked fulfilled locally.
>         if (requisitionMetadata.dataCase == RequisitionMetadata.DataCase.DATA_NOT_SET) {
>           if (header.hasHonestMajorityShareShuffle()) {
> ```

Use exhaustive when on `protocolCase` to guarantee this code gets updated if a new protocol is added.

**Review by ple13 — CHANGES_REQUESTED** [review]
I suggest that we add a test to verify that only a non-empty seed or a non-empty blob path is provided.

> Reviewed 10 of 14 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-:-NlPVlB1BrNdR-w6wM_C:b-7i0kw5)* status: all files reviewed, 5 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt` line 660 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-NlPUZk-2YppLzNF6-XF:-NlPUZk-2YppLzNF6-XG:b-y39ce7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c28ccd0b27be4b3374611ee1486c04895104a39c/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt#L660)):*
> ```Kotlin
>     externalRequisitionKey: ExternalRequisitionKey,
>     pathToBlob: String? = null,
>     seed: ByteString? = null
> ```

Let's check that exactly one of them is not null?



_Code quote:_
```Kotlin
    pathToBlob: String? = null,
    seed: ByteString? = null
```
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsServiceTest.kt` line 519 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-NlPHZKyCfPciJ25KbzN:-NlPHZKyCfPciJ25KbzO:b5co62l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c28ccd0b27be4b3374611ee1486c04895104a39c/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsServiceTest.kt#L519)):*
> ```Kotlin
> 
>   @Test
>   fun `recordRequisitionSeed with empty seed raises error`() = runBlocking {
> ```

The test name is not consistent with the content (the recordRequisitionRequest has a non-empty seed).
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/writers/RecordRequisitionData.kt` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-NlPJVyL5IgVSEZalvgu:-NlPJVyL5IgVSEZalvgv:b-qylcmg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c28ccd0b27be4b3374611ee1486c04895104a39c/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/writers/RecordRequisitionData.kt#L46)):*
> ```Kotlin
> ) : PostgresWriter<ComputationToken>() {
>   override suspend fun TransactionScope.runTransaction(): ComputationToken {
>     require((pathToBlob != null && seed == null) || (pathToBlob == null && seed != null))
> ```

Let's have an error message for this check?

**Review by renjiezh — COMMENTED** [review]
Added it in public api test. 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-:-Nl_ISjZ0eyp24x-KhHK:b-c86cbu)* status: 11 of 16 files reviewed, 5 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt` line 339 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-Nl4fa-iCIahUotPr42q:-Nl_B7Ph2T7fRmVbzvkG:bxzisez) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c28ccd0b27be4b3374611ee1486c04895104a39c/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt#L339)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think you need to use the experimental [`@OverloadResolutionByLambdaReturnType`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-overload-resolution-by-lambda-return-type/) annotation rather than suppressing.
</blockquote></details>

The annotation `@OverloadResolutionByLambdaReturnType` has been used for the function `updateToken`. This Suppress is only to avoid the annoying warning even with the annotation. I think we can keep them.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt` line 660 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-NlPUZk-2YppLzNF6-XF:-Nl_D3US33fhKt8aw5f9:bs7wumb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c28ccd0b27be4b3374611ee1486c04895104a39c/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt#L660)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Let's check that exactly one of them is not null?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt` line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-Nl4paTc8sMkw7hTt8pT:-Nl_XnAb38K8YpabOfPc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c28ccd0b27be4b3374611ee1486c04895104a39c/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L100)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use exhaustive when on `protocolCase` to guarantee this code gets updated if a new protocol is added.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsServiceTest.kt` line 519 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-NlPHZKyCfPciJ25KbzN:-Nl_Xr5L3O8RKmPndO1_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c28ccd0b27be4b3374611ee1486c04895104a39c/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsServiceTest.kt#L519)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

The test name is not consistent with the content (the recordRequisitionRequest has a non-empty seed).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/writers/RecordRequisitionData.kt` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-NlPJVyL5IgVSEZalvgu:-Nl_Xs74CmUopnUixE24:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c28ccd0b27be4b3374611ee1486c04895104a39c/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/writers/RecordRequisitionData.kt#L46)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Let's have an error message for this check?
</blockquote></details>

Done.

**Review by ple13 — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt` line 339 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-Nl4fa-iCIahUotPr42q:-NlyMV4t57iCZumGsxuv:bbwqc7t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c28ccd0b27be4b3374611ee1486c04895104a39c/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt#L339)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

The annotation `@OverloadResolutionByLambdaReturnType` has been used for the function `updateToken`. This Suppress is only to avoid the annoying warning even with the annotation. I think we can keep them.
</blockquote></details>

Sorry, what I mean is that you need to opt in to the experimental feature rather than suppressing the warning that you're using it. e.g. `@OptIn(ExperimentalTypeInference::class)`.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt` line 339 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355#-Nl4fa-iCIahUotPr42q:-NlyPzecAECPu42l27vA:b-yztinh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c28ccd0b27be4b3374611ee1486c04895104a39c/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt#L339)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, what I mean is that you need to opt in to the experimental feature rather than suppressing the warning that you're using it. e.g. `@OptIn(ExperimentalTypeInference::class)`.
</blockquote></details>

From offline discussion, it looks like the warning is purely for using the experimental inference at all. We have the suppression elsewhere in the codebase.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 6 of 14 files at r1, 3 of 5 files at r2, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1355)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
