### PR TITLE
Implement postgres continuation token service

### PR DESCRIPTION
**Pull request by YuhongWang-Amazon**
This implements the Postgres continuation token service and its dependent readers/writers.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1051)

**Review by renjiezh — CHANGES_REQUESTED** [review]
Looks good exception the `idGenerator`.

> Reviewed 3 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1051#-:-NXMGQDV2aNP1piaRpX1:b-b8quyw)* status: all files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresContinuationTokensService.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1051#-NXMGIIl11ncp3tg1Oz9:-NXMGIIl11ncp3tg1OzA:b-y93pus) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3e31e337dac9d829666f20beb5949d0fbd142b47/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresContinuationTokensService.kt#L34)):*
> ```Kotlin
> class PostgresContinuationTokensService(
>   private val client: DatabaseClient,
>   private val idGenerator: IdGenerator,
> ```

`idGenerateor` is not used.

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1051)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresContinuationTokensService.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1051#-NXMGIIl11ncp3tg1Oz9:-NXMLYKiDCp-mpJAhB7t:b-1gum1h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3e31e337dac9d829666f20beb5949d0fbd142b47/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresContinuationTokensService.kt#L34)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

`idGenerateor` is not used.
</blockquote></details>

It is used in `setContinuationToken` method.

**Review by renjiezh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1051)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresContinuationTokensService.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1051#-NXMGIIl11ncp3tg1Oz9:-NXMU_pDDWio3bYDZ25h:b-ptu2gn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3e31e337dac9d829666f20beb5949d0fbd142b47/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresContinuationTokensService.kt#L34)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

It is used in `setContinuationToken` method.
</blockquote></details>

I see. It is required by writer.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1051)* status: all files reviewed, 2 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/writers/SetContinutationToken.kt` line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1051#-NXWMX0aA-Q_QXvHztTf:-NXWMX0b-PK6ToTHd7aJ:b5ze38d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3e31e337dac9d829666f20beb5949d0fbd142b47/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/writers/SetContinutationToken.kt#L33)):*
> ```Kotlin
>       boundStatement(
>         """
>       INSERT INTO HeraldContinuationTokens (Presence, ContinuationToken, UpdateTime)
> ```

Huh, I didn't realize this is how you have to do an `UPSERT`/`INSERT OR UPDATE` in PostgreSQL.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresContinuationTokensService.kt` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1051#-NXWMiTi5VXMH7t1jzXA:-NXWMiTj0ddgw5zx-nt1:bvnru0g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3e31e337dac9d829666f20beb5949d0fbd142b47/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresContinuationTokensService.kt#L52)):*
> ```Kotlin
>       SetContinuationToken(request.token).execute(client, idGenerator)
>     } catch (e: InvalidContinuationTokenException) {
>       failGrpc(Status.FAILED_PRECONDITION) { e.message ?: "Invalid continuation token." }
> ```

Include the cause in exceptions so that our logging interceptors can record the stack trace for debugging. These exceptions should also really be resulting in error details with context being set. See [`KingdomInternalException.asStatusRuntimeException`](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9094cf73b27c07dc7221227a68c7c3e549791b51/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L48). We eventually want to plumb all this info into the public API error details (see https://google.aip.dev/193)

If you're going to copy any patterns from KingdomInternalException, don't bother with the lambdas for setting the description. That was poorly conceived and copied from logger patterns where it actually has a use.

**Pull request closed without merging**
