### PR TITLE
Add CreateExchangeStepAttempt class to insert new Attempts

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttempt.kt, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152#-Meaat_31imoGuIkFOvU:-Meaat_31imoGuIkFOvV:b-amo4w0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1a19b1652faa4ae0f462b8be7e8407d69fd293ae/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttempt.kt#L62)):*
> ```Kotlin
>     val sql =
>       """
>       SELECT MAX(AttemptIndex) AS MaxAttemptIndex
> ```

What about `SELECT IFNULL(MAX(AttemptIndex), 0) AS MaxAttemptIndex` -- does that work? 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttempt.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152#-MeaadKZ8-4jLno1O4EO:-MeaadKZ8-4jLno1O4EP:bz915fh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1a19b1652faa4ae0f462b8be7e8407d69fd293ae/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttempt.kt#L71)):*
> ```Kotlin
>     val statement: Statement =
>       Statement.newBuilder(sql)
>         .bind("recurring_exchange_id")
> ```

Ugh I guess we should probably make another thing for this to allow `bind(x to y)`

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152)* status: all files reviewed, 2 unresolved discussions (waiting on @yunyeng)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152)* status: all files reviewed, 3 unresolved discussions (waiting on @yunyeng)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttemptTest.kt, line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152#-Mf40Swl5sQpNH9QIXlS:-Mf40Swl5sQpNH9QIXlT:b-ttsyfk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8cf214703359a5a8cfae58042a97cd9453afd67/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttemptTest.kt#L140)):*
> ```Kotlin
>       RECURRING_EXCHANGE_ID1,
>       DATE1,
>       1L,
> ```

Can you add argument names to these? In other words `insertExchangeStep(recurringExchangeId = RECURRING_EXCHANGE_ID1, ...)`

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttempt.kt, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152#-Meaat_31imoGuIkFOvU:-Mf44XGO9SG6RcqdTaor:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1a19b1652faa4ae0f462b8be7e8407d69fd293ae/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttempt.kt#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What about `SELECT IFNULL(MAX(AttemptIndex), 0) AS MaxAttemptIndex` -- does that work? 
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttempt.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152#-MeaadKZ8-4jLno1O4EO:-Mf44ZaK09-g33B7dgyM:b4ucdno) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1a19b1652faa4ae0f462b8be7e8407d69fd293ae/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttempt.kt#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ugh I guess we should probably make another thing for this to allow `bind(x to y)`
</blockquote></details>

I will send a pr to common-jvm for this.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttemptTest.kt, line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152#-Mf40Swl5sQpNH9QIXlS:-Mf44dsK0AxhSuJUakCD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8cf214703359a5a8cfae58042a97cd9453afd67/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttemptTest.kt#L140)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add argument names to these? In other words `insertExchangeStep(recurringExchangeId = RECURRING_EXCHANGE_ID1, ...)`
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
