### PR TITLE
Add classes to be run for measurement retention policy

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955)

**Review by kungfucraig — COMMENTED** [review]
Can we put these classes in 
 cross-media-measurement/src/main/kotlin/org/wfanet/measurement/kingdom/batch/

instead of
 cross-media-measurement/src/main/kotlin/org/wfanet/measurement/kingdom/service/

cc: @SanjayVas 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-:-NTPxvCl1w7dYxZ867um:blsl9m6)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by SanjayVas — COMMENTED** [review]
The service package is meant for the service impls. +1 to putting them elsewhere.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-:-NTQpdZV2iIcF9b6tzuQ:b-whjn9s)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 7 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955)* status: 7 of 11 files reviewed, all discussions resolved

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 4 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955)* status: all files reviewed, 7 unresolved discussions (waiting on @jcorilla)

___
*[`src/main/k8s/kingdom.cue` line 192 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NTym-7T4bF4kquX4hEr:-NTym-7U0vFvWZD3m7vF:b2g8166) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40c125f6c3a7154a3a435bf4a531ee257634e05e/src/main/k8s/kingdom.cue#L192)):*
> ```CUE
> 				_debug_verbose_grpc_client_logging_flag,
> 			]
> 			spec: schedule: "0 * * * *" // Every hour on the hour
> ```

nit: Considering staggering the schedule so these don't run at the same time. It's also common to avoid contentious times when other things might want to run (such as on the hour), so also consider using a specific minute within the hour.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/BUILD.bazel` line 11 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NTypWtn6UUlbhzZDuA6:-NTypWtn6UUlbhzZDuA7:bwxya8a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40c125f6c3a7154a3a435bf4a531ee257634e05e/src/main/kotlin/org/wfanet/measurement/kingdom/batch/BUILD.bazel#L11)):*
> ```Starlark
>     name = "measurements_retention",
>     srcs = [
>         "CompletedMeasurementsDeletion.kt",
> ```

nit: either have a single default target for the package that uses `glob`, or have separate targets for each source file. In this case I'd prefer the latter.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/CompletedMeasurementsDeletionJob.kt` line 42 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NTysTZN7iHBPLwbC-L7:-NTysTZN7iHBPLwbC-L8:b-tmssnk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40c125f6c3a7154a3a435bf4a531ee257634e05e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/CompletedMeasurementsDeletionJob.kt#L42)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--completed-measurements-time-to-live"],
> ```

Drop the prefixes since these flags only apply to their respective jobs.



_Code quote:_
```Kotlin
completed-measurements-
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt` line 45 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NTysEPz4lfUNH4hcQOI:-NTysEPz4lfUNH4hcQOJ:b-opdv2b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40c125f6c3a7154a3a435bf4a531ee257634e05e/src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt#L45)):*
> ```Kotlin
>   private val dryRun: Boolean = false,
> ) {
>   private val openTelemetry: OpenTelemetry = GlobalOpenTelemetry.get()
> ```

Inject `OpenTelemetry` instance (add an `openTelemetry` val to the constructor with a default of `GlobalOpenTelemetry.get()`)
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt` line 56 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NTypuNW9MxgPykSZwjX:-NTypuNW9MxgPykSZwjY:b-54c6q6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40c125f6c3a7154a3a435bf4a531ee257634e05e/src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt#L56)):*
> ```Kotlin
>       logger.warning("Time to live cannot be 0. TTL=$timeToLive")
>     }
>     val currentTime = Clock.systemUTC().instant()
> ```

Inject `Clock` instance as a dependency (add a `clock` val to the constructor with a default of `Clock.systemUTC()`)



_Code quote:_
```Kotlin
Clock.systemUTC()
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt` line 65 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NTyqHg4472mvwXvF5dI:-NTyqHg4472mvwXvF5dJ:b3im9fe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40c125f6c3a7154a3a435bf4a531ee257634e05e/src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt#L65)):*
> ```Kotlin
>                 StreamMeasurementsRequestKt.filter {
>                   states += COMPLETED_MEASUREMENT_STATES
>                   updatedBefore = currentTime.minusMillis(timeToLive.toMillis()).toProtoTime()
> ```

`Instant` has a `minus` method that takes a `Duration`.



_Suggestion:_
```Kotlin
currentTime.minus(timeToLive)
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt` line 81 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NTyrDe_0NCFed4rHR19:-NTyrDe_0NCFed4rHR1A:b5m8iwx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40c125f6c3a7154a3a435bf4a531ee257634e05e/src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt#L81)):*
> ```Kotlin
> 
>       if (dryRun) {
>         logger.info(
> ```

nit: Use lambda for log message so it gets skipped depending on log level



_Suggestion:_
```Kotlin
        logger.info {
          "Measurements that would have been deleted: $deleteRequests"
        }
```

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955)* status: 4 of 11 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/CompletedMeasurementsDeletionJob.kt` line 42 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NTysTZN7iHBPLwbC-L7:-NU2jYSoC8lHl_qOacHF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40c125f6c3a7154a3a435bf4a531ee257634e05e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/CompletedMeasurementsDeletionJob.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop the prefixes since these flags only apply to their respective jobs.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt` line 45 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NTysEPz4lfUNH4hcQOI:-NU2mYCj1tkqHSvJpkX1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40c125f6c3a7154a3a435bf4a531ee257634e05e/src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Inject `OpenTelemetry` instance (add an `openTelemetry` val to the constructor with a default of `GlobalOpenTelemetry.get()`)
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt` line 56 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NTypuNW9MxgPykSZwjX:-NU2mYXs4ILbhwj6I23e:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40c125f6c3a7154a3a435bf4a531ee257634e05e/src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Inject `Clock` instance as a dependency (add a `clock` val to the constructor with a default of `Clock.systemUTC()`)
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt` line 65 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NTyqHg4472mvwXvF5dI:-NU2fTOf1vbA6gf26-on:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40c125f6c3a7154a3a435bf4a531ee257634e05e/src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`Instant` has a `minus` method that takes a `Duration`.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/CompletedMeasurementsDeletionJob.kt` line 94 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NU3C3FS-G-IeMyzlM9W:-NU3C3FS-G-IeMyzlM9X:bhdci7w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05284e66a9f6f3cd55d850c36e6950b1635b5904/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/CompletedMeasurementsDeletionJob.kt#L94)):*
> ```Kotlin
>       internalMeasurementsClient,
>       flags.measurementsTimeToLive,
>       flags.dryRun
> ```

If you actually want the metrics, the metric reader has to be created using the sdk. There is auto instrumentation, but this job is too short-lived to be auto instrumented in time. An example can be found here and the register view part won't be necessary. The part you want is the registerMetricReader and the setResource(to give the metrics the name label you want). https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6172c4c95b48660a3ce01580e808c81decce38b8/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt#L132

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/CompletedMeasurementsDeletionJob.kt` line 94 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NU3C3FS-G-IeMyzlM9W:-NU40vV2Dg4TfrNJIUqV:btkbpsm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05284e66a9f6f3cd55d850c36e6950b1635b5904/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/CompletedMeasurementsDeletionJob.kt#L94)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

If you actually want the metrics, the metric reader has to be created using the sdk. There is auto instrumentation, but this job is too short-lived to be auto instrumented in time. An example can be found here and the register view part won't be necessary. The part you want is the registerMetricReader and the setResource(to give the metrics the name label you want). https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6172c4c95b48660a3ce01580e808c81decce38b8/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt#L132
</blockquote></details>

Actually, the auto instrumentation might work, but the cue files need to be updated to include the annotation for cron jobs. Right now, the annotation is only there for deployments.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 4 of 11 files at r2, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla)

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/CompletedMeasurementsDeletionJob.kt` line 94 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NU3C3FS-G-IeMyzlM9W:-NU7zaiJ1tJe7ZMLejBz:bs7wumx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05284e66a9f6f3cd55d850c36e6950b1635b5904/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/CompletedMeasurementsDeletionJob.kt#L94)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Actually, the auto instrumentation might work, but the cue files need to be updated to include the annotation for cron jobs. Right now, the annotation is only there for deployments.
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 5 of 7 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @jcorilla)

___
*[`src/main/k8s/base.cue` line 556 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955#-NU83n_S6VJGxRPG2tTO:-NU83n_S6VJGxRPG2tTP:b-7j1d3u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5305f81bf2d9db0495e83590cb779ba4e72a8469/src/main/k8s/base.cue#L556)):*
> ```CUE
> 						}
> 						annotations: {
> 							"instrumentation.opentelemetry.io/inject-java": string | *"true"
> ```

These jobs are short-lived so they might not be auto instrumented in time. Since the sdk is being used to ensure instrumentation, this annotation doesn't do anything. It won't hurt though, so it could perhaps be used to auto instrumented a future long-lived job.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/955)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
