### PR TITLE
Improve performance of StreamActiveComputations query.

### PR DESCRIPTION
**Pull request by SanjayVas**
* Reorder index columns to actually be useful for query.
* Apply clauses to Measurements table before other joins.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1651)

**Comment by SanjayVas** [comment]
Sample queries from halo-cmm-dev:
* [original-query.sql.txt](https://github.com/user-attachments/files/15686523/original-query.sql.txt)
* [updated-query.sql.txt](https://github.com/user-attachments/files/15686521/updated-query.sql.txt)

The updated query appears to halve the CPU time.

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1651)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1651#-Nzjf3aJ9NB8ar9Pvp6j:-Nzjf3aJ9NB8ar9Pvp6k:b-tw2fbo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e5e21d3f0647fa40afc6f648eea2c4974ab24e54/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L70)):*
> ```Kotlin
>     }
> 
>   override fun fillStatementBuilder(block: Statement.Builder.() -> Unit): SpannerReader<Result> {
> ```

Do you think it would make more sense to have the first argument be orderByClause: String?. Then there would be a comment describing that it adds the order by clause to the end of the query to order the final result.
___
*[`src/main/resources/kingdom/spanner/changelog.yaml` line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1651#-NzjVZr2-f72Mds3t1PU:-NzjVZr2-f72Mds3t1PV:b-ccm7i8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e5e21d3f0647fa40afc6f648eea2c4974ab24e54/src/main/resources/kingdom/spanner/changelog.yaml#L68)):*
> ```YAML
> - include:
>     file: reorder-measurements-by-continuation-token.sql
>     relativeToChangeLogFile: true
> ```

nit: missing newline
___
*[`src/main/resources/kingdom/spanner/reorder-measurements-by-continuation-token.sql` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1651#-NzjVczH2TnKZHAOMqaF:-NzjVczH2TnKZHAOMqaG:b-ccm7i8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e5e21d3f0647fa40afc6f648eea2c4974ab24e54/src/main/resources/kingdom/spanner/reorder-measurements-by-continuation-token.sql#L23)):*
> ```TSQL
> 
> CREATE INDEX MeasurementsByContinuationToken ON
>   Measurements(UpdateTime, ExternalComputationId, State);
> ```

nit: missing newline

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1651)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1651#-Nzjf3aJ9NB8ar9Pvp6j:-Nzjno19ASTgkXTo87qN:b-sli1dw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e5e21d3f0647fa40afc6f648eea2c4974ab24e54/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L70)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Do you think it would make more sense to have the first argument be orderByClause: String?. Then there would be a comment describing that it adds the order by clause to the end of the query to order the final result.
</blockquote></details>

The fillStatementBuilder signature comes from the base class here, so having a first argument isn't really feasible.

I added some documentation to help, as I agree this is a little janky.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1651)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1651)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
