### PR TITLE
Add additional validation to create report request

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/748)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/748)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/748)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 298 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/748#-NHAL0iPEzXQNIWzc2V0:-NHAL0iPEzXQNIWzc2V1:b-wlfkw7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63296d8eba62f8379b2b447d0f0c77e479b33720/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L298)):*
> ```Kotlin
>     grpcRequire(request.report.metricsList.isNotEmpty()) { "Metrics in Report cannot be empty." }
>     request.report.metricsList.forEach {
>       grpcRequire(it.setOperationsList.isNotEmpty()) { "Metric setOperationsList cannot be empty." }
> ```

for single edp measurements, is the operationsList empty?



_Code quote:_
```Kotlin
SetOperation.
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/748)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 298 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/748#-NHAL0iPEzXQNIWzc2V0:-NHAnDq-9cudQZwmV_6Q:babty31) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdb6c97ec6671b7c58a1d004e23509e9e49e2df4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L298)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

for single edp measurements, is the operationsList empty?
</blockquote></details>

It will always be needed. This is where the data is requested.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/748)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 298 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/748#-NHAL0iPEzXQNIWzc2V0:-NHArlyE6o-ZZc1K566v:b-mhs692) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdb6c97ec6671b7c58a1d004e23509e9e49e2df4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L298)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It will always be needed. This is where the data is requested.
</blockquote></details>

Specifically, this is where the desired reporting sets are set, and the reporting sets include the event groups.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/748)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Comment by riemanli** [comment]
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 304 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/748#-NOR77TwDHwt4COLZfad:-NOR77TwDHwt4COLZfae:bid62hg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5f476c16f4c308244a4ccb8892be0a2586a6f9c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L304)):*
> ```Kotlin
>         }
>         grpcRequire(
>           !namedSetOperation.setOperation.lhs.operandCase.equals(
> ```

Why do we need this check? Is it because we need grpc error specifically? Otherwise it's already covered in `SetOperationCompiler`. See [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/SetOperationCompiler.kt#L427).

**Pull request merged**
