### PR TITLE
Add ExchangeStepReader base class to retrieve ExchangeSteps

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepReader.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144#-MeA2rp-3-U-PLKFZMlG:-MeA2rp-3-U-PLKFZMlH:b7h0tfj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02ee5c313948293ce7f76e69c53fa0a72cab7d14/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepReader.kt#L48)):*
> ```Kotlin
>     """.trimIndent()
> 
>   override val externalIdColumn: String = "RecurringExchanges.ExternalRecurringExchangeId"
> ```

Should this be a column on the ExchangeSteps table? I guess there isn't really a unique id for it to read. Maybe what we want is a list of external id columns? Or should we just drop this concept from the interface?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepReader.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144#-MeA2rp-3-U-PLKFZMlG:-MeBL5GB53yaPlH76FEy:b2l99d4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02ee5c313948293ce7f76e69c53fa0a72cab7d14/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepReader.kt#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should this be a column on the ExchangeSteps table? I guess there isn't really a unique id for it to read. Maybe what we want is a list of external id columns? Or should we just drop this concept from the interface?
</blockquote></details>

Added in the table for now since ExchangeStep proto has the field as well.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepReader.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144#-MeA2rp-3-U-PLKFZMlG:-MeBN_IPAXTamxy-zORq:b-tmj1e8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02ee5c313948293ce7f76e69c53fa0a72cab7d14/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepReader.kt#L48)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Added in the table for now since ExchangeStep proto has the field as well. 
</blockquote></details>

Oh sorry, I didn't mean add `ExternalRecurringExchangeId` to `ExchangeSteps`, I meant since this is `ExchangeStepReader` and not `RecurringExchangeReader`, should the value of `externalIdColumn` reference some column in the `ExchangeSteps` table?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepReader.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144#-MeA2rp-3-U-PLKFZMlG:-MeBeltP1U-sawylbEPq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02ee5c313948293ce7f76e69c53fa0a72cab7d14/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepReader.kt#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Oh sorry, I didn't mean add `ExternalRecurringExchangeId` to `ExchangeSteps`, I meant since this is `ExchangeStepReader` and not `RecurringExchangeReader`, should the value of `externalIdColumn` reference some column in the `ExchangeSteps` table?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/144)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
