### PR TITLE
Add kt_jvm_proto_library targets

### PR DESCRIPTION
**Pull request by efoxepstein**
For future reference, the hard work was done with a find/replace:

Find regex: `(java_proto_library\([^)]+name = "(.+)_java_proto[^)]+deps = (\[[^\]]+\])[^)]+\))`
Replace regex: `$1\nkt_jvm_proto_library(name = "$2_kt_jvm_proto", srcs = $3, deps = [":$2_java_proto"])`

Then java_proto was replaced by kt_jvm_proto in the //src/{main,test}/kotlin/ subtrees.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202)* status: 12 of 44 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v1alpha/BUILD.bazel, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202#-MhPRByD8tfuxYBZj7J8:-MhPRByD8tfuxYBZj7J9:ba6d6yb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41991b97db797aa3addad0dcad71196bf0273239/src/main/proto/wfa/measurement/api/v1alpha/BUILD.bazel#L40)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> java_proto_library(
>     name = "metric_java_proto",
>     deps = ["@wfa_measurement_proto//src/main/proto/wfa/measurement/api/v1alpha:metric_proto"],
> )
> ```
</details>

do we have plan to delete those java_proto_librarys?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202)* status: 12 of 44 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/proto/wfa/measurement/api/v1alpha/BUILD.bazel, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202#-MhPRByD8tfuxYBZj7J8:-MhPUZRM7I0HXSLjlqOL:b73eda9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41991b97db797aa3addad0dcad71196bf0273239/src/main/proto/wfa/measurement/api/v1alpha/BUILD.bazel#L40)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> java_proto_library(
>     name = "metric_java_proto",
>     deps = ["@wfa_measurement_proto//src/main/proto/wfa/measurement/api/v1alpha:metric_proto"],
> )
> ```
do we have plan to delete those java_proto_librarys?
</blockquote></details>

For now, `kt_jvm_proto_library` depends on `java_proto_library`. We'll consult with the protobuf team to see if they want that dependency in the long run

**Review by SanjayVas — APPROVED** [review]
> Reviewed 32 of 32 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by oliver-amzn — APPROVED** [review]
Amazing regex work

> Reviewed 10 of 16 files at r1, 32 of 32 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202#-:-MhQ44Dm6HOorXRvK-I6:b939ryq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — DISMISSED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/proto/wfa/measurement/api/v1alpha/BUILD.bazel, line 7 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202#-MhQY2Op605TPPoCkPhu:-MhQY2Op605TPPoCkPhv:b-nv88hk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f7bf7240311f6ea004074cab6d455573096e0da/src/main/proto/wfa/measurement/api/v1alpha/BUILD.bazel#L7)):*
> ```Starlark
> package(default_visibility = ["//visibility:public"])
> 
> java_proto_library(
> ```

do we need both java_proto_libaries and kt_jvm ones?

**Review by efoxepstein — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202#-:-MhQZzwK3sLYgjkOUiR3:b-ucfknh)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v1alpha/BUILD.bazel, line 7 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202#-MhQY2Op605TPPoCkPhu:-MhQ_1920Pjj5Bx0xVZr:b-j5sn7b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f7bf7240311f6ea004074cab6d455573096e0da/src/main/proto/wfa/measurement/api/v1alpha/BUILD.bazel#L7)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we need both java_proto_libaries and kt_jvm ones?
</blockquote></details>

Yes: one of the inputs to `kt_jvm_library` is a `java_proto_library`. We could generate an invisible `java_proto_library` inside of `kt_jvm_proto_library` but chose not to. We'll chat with the protobuf team to see which way they prefer as we try to merge this into a more official repo.

**Review by efoxepstein — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202)* status: 44 of 46 files reviewed, all discussions resolved (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v1alpha/BUILD.bazel, line 7 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202#-MhQY2Op605TPPoCkPhu:-MhQguFdCwK7XZNbbqCc:b76us2e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f7bf7240311f6ea004074cab6d455573096e0da/src/main/proto/wfa/measurement/api/v1alpha/BUILD.bazel#L7)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yes: one of the inputs to `kt_jvm_library` is a `java_proto_library`. We could generate an invisible `java_proto_library` inside of `kt_jvm_proto_library` but chose not to. We'll chat with the protobuf team to see which way they prefer as we try to merge this into a more official repo.
</blockquote></details>

Dismissing this -- doesn't seem like it should be a blocker.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
