### PR TITLE
Specify next exchange date when creating RecurringExchange.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/448)

### CODE REVIEW

**Review by yunyeng — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/448)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/448)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 240 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/448#-MwgPLKyEspvymDGzJ_H:-MwgPLKyEspvymDGzJ_I:bg15kp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65ec4036377c4e1929006be18d0d6cbd63917324/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L240)):*
> ```Kotlin
> 
>     val serializedExchangeWorkflow = exchangeWorkflowFile.readBytes()
>     val v2AlphaExchangeWorkflow = ExchangeWorkflow.parseFrom(serializedExchangeWorkflow)
> ```

We also need to add exchangeIdentifiers in the workflow as well. This could be already edited in the file but I was thinking a change in the IntegrationTest something like that;

val updatedWorkflow = v2AlphaExchangeWorkflow.copy {
      exchangeIdentifiers = ExchangeWorkflowKt.exchangeIdentifiers {
        dataProvider = dataProviderName
        modelProvider = modelProviderName
        sharedStorageOwner = ExchangeWorkflow.Party.DATA_PROVIDER
        storage = ExchangeWorkflow.StorageType.GOOGLE_CLOUD_STORAGE
      }
    }

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/448)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/448)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 240 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/448#-MwgPLKyEspvymDGzJ_H:-Mwh2HGP4DdesaXIb7mM:b5br6uj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65ec4036377c4e1929006be18d0d6cbd63917324/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L240)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

We also need to add exchangeIdentifiers in the workflow as well. This could be already edited in the file but I was thinking a change in the IntegrationTest something like that;

val updatedWorkflow = v2AlphaExchangeWorkflow.copy {
      exchangeIdentifiers = ExchangeWorkflowKt.exchangeIdentifiers {
        dataProvider = dataProviderName
        modelProvider = modelProviderName
        sharedStorageOwner = ExchangeWorkflow.Party.DATA_PROVIDER
        storage = ExchangeWorkflow.StorageType.GOOGLE_CLOUD_STORAGE
      }
    }
</blockquote></details>

This CLI tool isn't meant to help you build an ExchangeWorkflow, only create each resource in the Kingdom. It's up to the caller to build the workflow message.

This tool has nothing to do with the in-process integration test.

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/448)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
