### PR TITLE
Add a Requisitions table as the child of the Computations table.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl, line 134 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50#-MZySaws69QMxpCAF-AM:-MZySawtCzvyfUsV_hfg:b-1wjfbh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e06451df2df37d46f093261932031046a161ae73/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl#L134)):*
> ```
>   -- The external requisition id.
>   ExternalRequisitionId STRING(MAX) NOT NULL,
> ```

Did you want to add the EDP participation signature here as well?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl, line 134 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50#-MZySaws69QMxpCAF-AM:-MZyTS4V1iqHCuYvfETA:b-il6xhc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e06451df2df37d46f093261932031046a161ae73/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl#L134)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Did you want to add the EDP participation signature here as well?
</blockquote></details>

The signatures are sent to the kingdom. Later all signatures will be passed to the herald and will be used to verify the EDP participations. Then these signatures are not useful anymore, so I feel no need to store them in the database.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @zachcwc)

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl, line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50#-M_2Gw1T3dmNRqJopmsv:-M_2Gw1U9yzoIvNvaYLO:b-cb3jlk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e06451df2df37d46f093261932031046a161ae73/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl#L141)):*
> ```
> 
> -- Enable querying by ExternalDataProviderId and ExternalRequisitionId.
> CREATE UNIQUE INDEX RequisitionsByExternalId ON Requisitions(
> ```

Could this be on RequisitionId only?

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl, line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50#-M_2Gw1T3dmNRqJopmsv:-M_4aQF59Dy4IKrJRu-a:bi2nlww) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e06451df2df37d46f093261932031046a161ae73/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl#L141)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Could this be on RequisitionId only?
</blockquote></details>

Good catch, Yes. 

Based on https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/933284c02cff0be89991c31178bb9538de70f01b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/kingdom.sdl#L273
ExternalRequisitionId is an index in the kingdom database's Requisition table.  so surely the duchy can just use it as an index.

**Comment by zachcwc** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl, line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50#-M_2Gw1T3dmNRqJopmsv:-M_WcJCO1Yie4ODRSxhl:bn2m79h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e06451df2df37d46f093261932031046a161ae73/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl#L141)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Good catch, Yes. 

Based on https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/933284c02cff0be89991c31178bb9538de70f01b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/kingdom.sdl#L273
ExternalRequisitionId is an index in the kingdom database's Requisition table.  so surely the duchy can just use it as an index.
</blockquote></details>

ExternalDataProviderId was added back in the most recent commit? Why can it not be RequisitionId only?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl, line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50#-M_2Gw1T3dmNRqJopmsv:-M_Wef_C8R-dFgpphHUP:b-5d6lb0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e06451df2df37d46f093261932031046a161ae73/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl#L141)):*
<details><summary><i>Previously, zachcwc wrote…</i></summary><blockquote>

ExternalDataProviderId was added back in the most recent commit? Why can it not be RequisitionId only?
</blockquote></details>

I forgot to update the comment here. Per the discussion during the design review last Friday. In the kingdom, the ExternalRequisitionId is indeed a unique index of the kingdom requisition table. But that is an implementation detail in the kingdom. From the API point of view, the client can only assume the requisitionId is distinct with in the same EDP. so the duchy needs to use both data_provider_id and requisition id as the index.

**Review by zachcwc — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl, line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/50#-M_2Gw1T3dmNRqJopmsv:-M_WicZa0ik1JUavIPpk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e06451df2df37d46f093261932031046a161ae73/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl#L141)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I forgot to update the comment here. Per the discussion during the design review last Friday. In the kingdom, the ExternalRequisitionId is indeed a unique index of the kingdom requisition table. But that is an implementation detail in the kingdom. From the API point of view, the client can only assume the requisitionId is distinct with in the same EDP. so the duchy needs to use both data_provider_id and requisition id as the index.
</blockquote></details>

Done.

**Pull request merged**
