### PR TITLE
Reduce usages of correlated lists in ReportsServiceTest.

### PR DESCRIPTION
**Pull request by SanjayVas**
Correlated lists are fragile and generally should not be used. This replaces some of the usage with maps. It also uses actual certificates/signatures to make the test more accurate.

This is pre-factoring for DataProvider public key signature verification.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824)

### CODE REVIEW

**Comment by SanjayVas** [comment]
Pre-factoring for #823.

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 401 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824#-NMo_usyDOirnL6vXu38:-NMo_usyDOirnL6vXu39:bvoh8fl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a967bbb660678dd4dc4d5ea2ebe40180974e1d51/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L401)):*
> ```Kotlin
>     ExternalId(664L).apiId.value
>   )
> private val COVERED_EVENT_GROUP_NAMES = COVERED_EVENT_GROUP_KEYS.map { it.toName() }
> ```

In order to minimize the usage of correlated list, should we remove `COVERED_EVENT_GROUP_NAMES` and always use `COVERED_EVENT_GROUP_KEYS` to get the name?
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 403 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824#-NMoaT0ZEDcoyD2U0FWD:-NMoaT0ZEDcoyD2U0FWE:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a967bbb660678dd4dc4d5ea2ebe40180974e1d51/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L403)):*
> ```Kotlin
> private val COVERED_EVENT_GROUP_NAMES = COVERED_EVENT_GROUP_KEYS.map { it.toName() }
> private val UNCOVERED_EVENT_GROUP_NAME = UNCOVERED_EVENT_GROUP_KEY.toName()
> private val COVERED_INTERNAL_EVENT_GROUP_KEYS = COVERED_EVENT_GROUP_KEYS.map { it.toInternal() }
> ```

ditto

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 401 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824#-NMo_usyDOirnL6vXu38:-NN31Hp12RsuVWN0FUtJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a967bbb660678dd4dc4d5ea2ebe40180974e1d51/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L401)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

In order to minimize the usage of correlated list, should we remove `COVERED_EVENT_GROUP_NAMES` and always use `COVERED_EVENT_GROUP_KEYS` to get the name?
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 403 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824#-NMoaT0ZEDcoyD2U0FWD:-NN335owCuK65L60wIG0:blyt8gm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a967bbb660678dd4dc4d5ea2ebe40180974e1d51/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L403)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done, also dropping `REPORTING_SET_EXTERNAL_IDS` and `REPORTING_SET_EXTERNAL_IDS.

**Review by riemanli — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 4071 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824#-NN3kPmR4ORodX8GB_IZ:-NN3kPmR4ORodX8GB_I_:b-45r8xu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85c3a059f22e98de71c460e2dcfa3ce37db02659/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L4071)):*
> ```Kotlin
>     ReportingSetKey(measurementConsumerReferenceId, ExternalId(externalReportingSetId).apiId.value)
> private val InternalReportingSet.resourceName: String
>   get() = resourceKey.toName()
> ```

This is neat!



_Code quote:_
```Kotlin
private val InternalReportingSet.resourceKey: ReportingSetKey
  get() =
    ReportingSetKey(measurementConsumerReferenceId, ExternalId(externalReportingSetId).apiId.value)
private val InternalReportingSet.resourceName: String
  get() = resourceKey.toName()
```

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1120 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824#-NN7oimA7fcHrSklRhiy:-NN7oimA7fcHrSklRhiz:b-o0ntv4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85c3a059f22e98de71c460e2dcfa3ce37db02659/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1120)):*
> ```Kotlin
>     eventGroupFilters: Map<String, String>,
>     internalReportingSetMap: Map<Long, InternalReportingSet>
>   ): Map<String, List<EventGroupEntry>> {
> ```

what do you think about changing the return type to `Map<DataProviderKey, List<EventGroupEntry>>` while you're tinkering here?

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1120 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824#-NN7oimA7fcHrSklRhiy:-NNDHkN98Dyfq4QegZfX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85c3a059f22e98de71c460e2dcfa3ce37db02659/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1120)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what do you think about changing the return type to `Map<DataProviderKey, List<EventGroupEntry>>` while you're tinkering here?
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
