### PR TITLE
Auto-fail expired ExchangeStepAttempts

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)

### CODE REVIEW

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhQjXd55P7kb14MJmfX:-MhQjXd55P7kb14MJmfY:b-d8etnh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f16636e36595560f966a2652a9cdeddbb1d149da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L97)):*
> ```Kotlin
> 
>   private fun Result.toClaimReadyExchangeStepResponse(): ClaimReadyExchangeStepResponse {
>     return claimReadyExchangeStepResponse {
> ```

Is this magic?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt, line 108 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhQhuP0-LZDVxbuvZ4n:-MhQhuP0-LZDVxbuvZ4o:b-r413c6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f16636e36595560f966a2652a9cdeddbb1d149da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt#L108)):*
> ```Kotlin
>         }
> 
>         if (externalModelProviderId != null) {
> ```

(externalDataProviderId != null)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhQheuZBJPfTpi7KLD9:-MhQheuZBJPfTpi7KLDA:b-5a7tae) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f16636e36595560f966a2652a9cdeddbb1d149da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L103)):*
> ```
> clock.instant().plus(24, ChronoUnit.HOURS).toGcloudTimestamp()
> ```
can this be function like Clock.now().add("1 hour") or something?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 110 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhQgqDg84iF2y9h1D2f:-MhQgoAvAGPznpblsKmv:byxgujy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f16636e36595560f966a2652a9cdeddbb1d149da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L110)):*
> ```
>   transactionContext.bufferInsertMutation(
> ```
What is the difference here actually with the new syntax of transactionContext?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 0 of 25 files reviewed, 4 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhQjXd55P7kb14MJmfX:-MhUCBDH10qEFSnHA5A1:b-d5a10n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f16636e36595560f966a2652a9cdeddbb1d149da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L97)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Is this magic?
</blockquote></details>

It's the new Kotlin proto DSL
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt, line 108 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhQhuP0-LZDVxbuvZ4n:-MhUCDysCHMkRPDrIQmf:b-t4jypw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f16636e36595560f966a2652a9cdeddbb1d149da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt#L108)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

(externalDataProviderId != null)
</blockquote></details>

Good catch! Thanks!
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhQheuZBJPfTpi7KLD9:-MhUCTpr4NYCh2KMhYOS:b-35vknj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f16636e36595560f966a2652a9cdeddbb1d149da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L103)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

> ```
> clock.instant().plus(24, ChronoUnit.HOURS).toGcloudTimestamp()
> ```
can this be function like Clock.now().add("1 hour") or something?
</blockquote></details>

I'm not sure what you're suggesting but `.plus` is part of the Java standard library -- doesn't seem worthwhile writing something custom as "24, HOURS" is pretty easy to read
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 110 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhQgqDg84iF2y9h1D2f:-MhUCpd0CNXbbmjdMeOM:b-bou00x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f16636e36595560f966a2652a9cdeddbb1d149da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L110)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

> ```
>   transactionContext.bufferInsertMutation(
> ```
What is the difference here actually with the new syntax of transactionContext?
</blockquote></details>

By using `TransactionContext.bufferInsertMutation` you can't forget to buffer it. It's hard to spot the bug in this code:

```
insertMutation {
  // 30 lines of code here
}
```

(where the last line forgets to call `.bufferTo(transactionContext)`)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 0 of 33 files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/proto/BUILD.bazel, line 0 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhUjEMj2nIX6LYZ91wz:-MhUjEMlBKK9m0OIBf76:b-mp5l6z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64f72bca12d2b657d0cfd2ad6f69f5ca6575718f/src/main/proto/BUILD.bazel#L0)):*
@sanjayvas -- to include a `.bzl` file, the linter seems to want `BUILD.bazel` files in all parent directories of the `.bzl` file up until some common ancestor of `BUILD.bazel` file and the `.bzl` file. Does this sound right? Figured I'd add you to this review to make sure I'm not unnecessarily adding BUILD files

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 0 of 33 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhQjXd55P7kb14MJmfX:-MhUq-Ov0pN5E1eQqkIK:b-jy7r03) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f16636e36595560f966a2652a9cdeddbb1d149da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L97)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's the new Kotlin proto DSL
</blockquote></details>

See https://developers.google.com/protocol-buffers/docs/reference/kotlin-generated#message
___
*[src/main/proto/BUILD.bazel, line  at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhUjEMj2nIX6LYZ91wz:-MhUolKeAQiP1yXcDo2d:b-83w54e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64f72bca12d2b657d0cfd2ad6f69f5ca6575718f/src/main/proto/BUILD.bazel#L)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@sanjayvas -- to include a `.bzl` file, the linter seems to want `BUILD.bazel` files in all parent directories of the `.bzl` file up until some common ancestor of `BUILD.bazel` file and the `.bzl` file. Does this sound right? Figured I'd add you to this review to make sure I'm not unnecessarily adding BUILD files
</blockquote></details>

I thought it was just the same directory that the `.bzl` file is in, making that directory into a Bazel package.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 16 files at r1, 7 of 12 files at r2, 6 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 17 of 33 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhQjXd55P7kb14MJmfX:-MhUwlxZED8ZxDOKXmQZ:bnbpmpv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f16636e36595560f966a2652a9cdeddbb1d149da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L97)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

See https://developers.google.com/protocol-buffers/docs/reference/kotlin-generated#message
</blockquote></details>

its fantastic!
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 75 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhUwbH86unPlgtJMpgZ:-MhUwbH86unPlgtJMpg_:b-eclqio) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64f72bca12d2b657d0cfd2ad6f69f5ca6575718f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L75)):*
> ```Kotlin
>           stepIndex = attempt.stepIndex
>           attemptNumber = attempt.attemptNumber
>           state = ExchangeStepAttempt.State.FAILED
> ```

it would also be nice to have a way for the system to no it auto-failed something vs a client reported it as failed. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhUxBBl404W3Q4tbqIE:-MhUxBBl404W3Q4tbqIF:bu19gw8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64f72bca12d2b657d0cfd2ad6f69f5ca6575718f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L103)):*
> ```Kotlin
> 
>       // TODO(@efoxepstein): make this variable based on the step type or something.
>       set("ExpirationTime" to clock.instant().plus(24, ChronoUnit.HOURS).toGcloudTimestamp())
> ```

make 24 a constant somewhere more accessible
___
*[src/main/proto/BUILD.bazel, line  at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhUjEMj2nIX6LYZ91wz:-MhUxaMt-Haslo3Fbeo8:b-ama2mn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64f72bca12d2b657d0cfd2ad6f69f5ca6575718f/src/main/proto/BUILD.bazel#L)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought it was just the same directory that the `.bzl` file is in, making that directory into a Bazel package.
</blockquote></details>

it has made me do that, too, in the past

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 9 of 33 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 75 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhUwbH86unPlgtJMpgZ:-MhUyvK9721UiTTyXgO7:b6ckn89) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64f72bca12d2b657d0cfd2ad6f69f5ca6575718f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L75)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

it would also be nice to have a way for the system to no it auto-failed something vs a client reported it as failed. 
</blockquote></details>

Should we add a separate state? I'm a little wary of having too many states, it makes it more likely to miss one somewhere and end up with a weird bug. For now can I add a TODO to consider this?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 9 of 33 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 75 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhUwbH86unPlgtJMpgZ:-MhUzW7p9bXpUl8iwNWW:b-cwl2ih) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64f72bca12d2b657d0cfd2ad6f69f5ca6575718f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L75)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should we add a separate state? I'm a little wary of having too many states, it makes it more likely to miss one somewhere and end up with a weird bug. For now can I add a TODO to consider this?
</blockquote></details>

is there a field to add a simple log entry for now? I agree that I don't want a separate state. Maybe we'll end up having sub-reasons at some point but lets not go there. Does a log message work?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 9 of 33 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhQheuZBJPfTpi7KLD9:-MhV-MmM-l4bSJp6sCYi:b-9ufoti) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f16636e36595560f966a2652a9cdeddbb1d149da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L103)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm not sure what you're suggesting but `.plus` is part of the Java standard library -- doesn't seem worthwhile writing something custom as "24, HOURS" is pretty easy to read
</blockquote></details>

All of this has been updated, @yunyeng PTAL
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhUxBBl404W3Q4tbqIE:-MhV-Ldc9bgAQlOGXIsV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64f72bca12d2b657d0cfd2ad6f69f5ca6575718f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L103)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

make 24 a constant somewhere more accessible
</blockquote></details>

Done.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 8 of 33 files reviewed, 6 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 75 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhUwbH86unPlgtJMpgZ:-MhV0NYb3mjFFCFdII25:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64f72bca12d2b657d0cfd2ad6f69f5ca6575718f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L75)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is there a field to add a simple log entry for now? I agree that I don't want a separate state. Maybe we'll end up having sub-reasons at some point but lets not go there. Does a log message work?
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 9 of 33 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, line 2 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhVonDn-w4Phe_tvgX2:-MhVonDn-w4Phe_tvgX3:b-b3468h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bfbd512f5b1e92c7c41fbd6cb20bce1c33653a69/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel#L2)):*
> ```Starlark
> load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
> load("//src/main/proto/wfa/measurement/internal/kingdom:all_protos.bzl", "KINGDOM_INTERNAL_PROTOS")  # buildifier: disable=bzl-visibility
> ```

why do you need to disable the visibility check? shouldn't the visibility of the target file get changed instead?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 9 of 33 files reviewed, 5 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, line 2 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205#-MhVonDn-w4Phe_tvgX2:-MhVrIW96cu2Jm00c3z4:byay6rg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bfbd512f5b1e92c7c41fbd6cb20bce1c33653a69/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel#L2)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why do you need to disable the visibility check? shouldn't the visibility of the target file get changed instead?
</blockquote></details>

https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#bzl-visibility -- "If a directory foo contains a subdirectory internal or private, only files located under foo can access it."

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 9 of 33 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: 9 of 33 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by yunyeng — APPROVED** [review]
> Reviewed 11 of 16 files at r1, 4 of 12 files at r2, 2 of 9 files at r3, 11 of 11 files at r4, 1 of 1 files at r5, 1 of 2 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
