### PR TITLE
adding charts to reporting ui

### PR DESCRIPTION
**Pull request by bdomen-ggl**
Adding charts to the report view.

Notes:
* There is a D3 wrapper to simplify steps for the higher level callers.
* There is a chart template for each chart used to further make the calls from the view easier. These can perhaps be removed since they're just calling a chart factory.
* We can likely refactor the data inputs to the <charts> component and make it more dynamically flexible/configurable. Making all the data required for now to simplify likely refactors as we develop the BFF more.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218)* status: 8 of 21 files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl and @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_factory.tsx` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEe73-D4Hc1vGtdnSq:-NeEe73-D4Hc1vGtdnSr:b-v5udww) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_factory.tsx#L42)):*
> ```XML
> 
> // TODO: Add Legend
> export function ChartFactory({cardId, title, data, config, type}: props) {
> ```

Why the `Factory`? Can't we just treat this component as being the chart?



_Code quote:_
```XML
ChartFactory
```
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/d3_wrapper.js` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEWjVuAfh38IbndFzS:-NeEWjVuAfh38IbndFzT:b-3gaxmm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/d3_wrapper.js#L28)):*
> ```JavaScript
>         .attr("height", height)
>         .attr("viewBox", [0, 0, width, height])
>         .attr("style", "max-width: 100%; height: auto; overflow: visible; font: 10px sans-serif;");
> ```

nit: prefer styling via sheet rather than `style` attr.
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/d3_wrapper.js` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEWqNg3_uQNwzQXaH7:-NeEWqNg3_uQNwzQXaH8:b-nj976a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/d3_wrapper.js#L33)):*
> ```JavaScript
> }
> 
> const setupUtcScale = (svg, data, dimensions, margins) => {
> ```

nit: "set up" is the verb phrase whereas "setup" is the noun. Function names are verb phrases.



_Suggestion:_
```JavaScript
setUpUtcScale
```
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/BUILD.bazel` line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEemouCE9MBU-la0KE:-NeEemovBk1cqrCp5-SV:b-5k8vho) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/BUILD.bazel#L9)):*
> ```Starlark
> )
> 
> js_library(
> ```

I think the package organization is off here. It looks like the current pattern is have a separate package in `component` for each component. If that's not the intent and you sometimes want to group components together in a single package, what you have seems backwards. What I mean there is that if your generic `Chart`/`ChartFactory` component is intended to be "private" and shared across your specific chart components, you probably want the specific ones to be in the parent package. If you want to have a single default target for each package, you can then hide the private generic component in a subpackage with limited visibility. Otherwise you can just have a bunch of granular targets for each component in the package, and just limit the visibility of the generic one.
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/dedupe_reach_by_demo.tsx` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEXMkp-PIvAXrmkcy3:-NeEXMkqBsL9uXY415De:bn7qqpd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/dedupe_reach_by_demo.tsx#L21)):*
> ```XML
> type DedupeReachByDemoProps = {
>     id: string,
>     demo: Demographic[],
> ```

Just as an aside, demographic isn't actually something we have in the CMMS. We instead have expressions on event templates, where event template fields *could* be demographic info (e.g. fields about the user) but also things like device type (e.g. fields about the impression event).
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/dedupe_reach_by_demo.tsx` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEX4SMBxGUzck9xUOg:-NeEX4SMBxGUzck9xUOh:b-zmncm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/dedupe_reach_by_demo.tsx#L25)):*
> ```XML
> }
> 
> export function DedupeReachByDemo({id, demo, pubColors}: DedupeReachByDemoProps) {
> ```

nit: noun phrase since this is effectively a type (even though it's implemented as a function)



_Suggestion:_
```XML
DedupedReachByDemo
```

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218)* status: 8 of 21 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_factory.tsx` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEe73-D4Hc1vGtdnSq:-NeEki1dBxsOuyhMcS_I:b-64gna4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_factory.tsx#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why the `Factory`? Can't we just treat this component as being the chart?
</blockquote></details>

Yeah that makes sense. Was going back and forth with some abstraction methods so not exactly a factory anymore.
Renamed to just `Chart`
Done
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/d3_wrapper.js` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEWjVuAfh38IbndFzS:-NeJ4SCz89Vqoc5OMrFA:brzpxhl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/d3_wrapper.js#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: prefer styling via sheet rather than `style` attr.
</blockquote></details>

Yep thanks. Copied this from an example.
Done
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/d3_wrapper.js` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEWqNg3_uQNwzQXaH7:-NeElgqg4BED66UOKkoM:b-pgs6ut) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/d3_wrapper.js#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: "set up" is the verb phrase whereas "setup" is the noun. Function names are verb phrases.
</blockquote></details>

Thanks, never noticed the nuance there. :+1: 
Done
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/BUILD.bazel` line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEemouCE9MBU-la0KE:-NeElp9C14u7IdNO40U7:b-4cnncp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/BUILD.bazel#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think the package organization is off here. It looks like the current pattern is have a separate package in `component` for each component. If that's not the intent and you sometimes want to group components together in a single package, what you have seems backwards. What I mean there is that if your generic `Chart`/`ChartFactory` component is intended to be "private" and shared across your specific chart components, you probably want the specific ones to be in the parent package. If you want to have a single default target for each package, you can then hide the private generic component in a subpackage with limited visibility. Otherwise you can just have a bunch of granular targets for each component in the package, and just limit the visibility of the generic one.
</blockquote></details>

Thanks, that makes sense. I was kind of going back and forth between and ended up on the wrong one.
WIP
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/dedupe_reach_by_demo.tsx` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEXMkp-PIvAXrmkcy3:-NeJ5_2D1PC4Iztkikqu:bdk437f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/dedupe_reach_by_demo.tsx#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just as an aside, demographic isn't actually something we have in the CMMS. We instead have expressions on event templates, where event template fields *could* be demographic info (e.g. fields about the user) but also things like device type (e.g. fields about the impression event).
</blockquote></details>

Yeah, this might be trickier to handle when we de-hardcode the data.
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/dedupe_reach_by_demo.tsx` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEX4SMBxGUzck9xUOg:-NeJ5WcQBGwJAMn8iKs7:b831m3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/dedupe_reach_by_demo.tsx#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: noun phrase since this is effectively a type (even though it's implemented as a function)
</blockquote></details>

:+1: 
Done

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218)* status: 2 of 29 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/BUILD.bazel` line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1218#-NeEemouCE9MBU-la0KE:-NeJ6BC8Exp5xmfG1b0M:b-7ttxb6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f50de1c37d75fdd93617c88f6e1f919b344d716/experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart_type/BUILD.bazel#L9)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Thanks, that makes sense. I was kind of going back and forth between and ended up on the wrong one.
WIP
</blockquote></details>

Just to make organization a bit easier to follow, I'm putting the charts in a chart subfolder, but will follow the general idea to have each one in their own sub-package and the helpers to be private to the sub-package (private in regards to bazel). Let me know if this isn't what you had in mind.
Done

**Pull request merged**
