### PR TITLE
Deploy Kingdom

### PR DESCRIPTION
**Pull request by wfa-siyengar**
- [x] Created Kingdom creation workflow.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, @TNATALI, and @wfa-siyengar)

___
*[`.github/workflows/create_kingdom.yml` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NR33mX324V5hHAN8-ZJ:-NR33mX324V5hHAN8-ZK:b38kdu2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6728f7dbc1321060880e22a5d02ae2f6c74bcb3a/.github/workflows/create_kingdom.yml#L17)):*
> ```YAML
> name: 'Create Kingdom'
> 
> on:
> ```

Need to trigger on workflow_run.

**Review by wfa-siyengar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl, @duliomatos1, @kungfucraig, @SanjayVas, and @TNATALI)

___
*[`.github/workflows/create_kingdom.yml` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NR33mX324V5hHAN8-ZJ:-NR7vB3s-BBnwhanyPQ0:bs0o0l6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cf5dd747e5f8192e8e0c8e3ad378e62905c52ca/.github/workflows/create_kingdom.yml#L17)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Need to trigger on workflow_run.
</blockquote></details>

@kungfucraig duchy is on dispatch too. Please let this change go for now. 
We will make the next PR to link all the modules and orchestrate them right.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, @TNATALI, and @wfa-siyengar)

___
*[`.github/workflows/create_kingdom.yml` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NR8EG7FASoC7Dr8kUNj:-NR8EG7FASoC7Dr8kUNk:bgxgxuf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cf5dd747e5f8192e8e0c8e3ad378e62905c52ca/.github/workflows/create_kingdom.yml#L15)):*
> ```YAML
> # limitations under the License.
> 
> name: 'Create Kingdom'
> ```

Deploy Kingdom
___
*[`.github/workflows/create_kingdom.yml` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NR33mX324V5hHAN8-ZJ:-NR8E9bg20nyy7BLHkAF:b-ezj3md) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cf5dd747e5f8192e8e0c8e3ad378e62905c52ca/.github/workflows/create_kingdom.yml#L17)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

@kungfucraig duchy is on dispatch too. Please let this change go for now. 
We will make the next PR to link all the modules and orchestrate them right.
</blockquote></details>

Please leave a TODO for workflow_run.
___
*[`.github/workflows/create_kingdom.yml` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NR8EQfK0Y3g1_VHZmDw:-NR8EQfK0Y3g1_VHZmDx:b-fm2243) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cf5dd747e5f8192e8e0c8e3ad378e62905c52ca/.github/workflows/create_kingdom.yml#L25)):*
> ```YAML
>         required: true
>       kingdom:
>         description: 'Name of the kingdom you are trying to create.'
> ```

What's this for?
___
*[`.github/workflows/create_kingdom.yml` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NR8EegnDVENYN6dO_Sm:-NR8EegnDVENYN6dO_Sn:b-wmucd0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cf5dd747e5f8192e8e0c8e3ad378e62905c52ca/.github/workflows/create_kingdom.yml#L38)):*
> ```YAML
> jobs:
>   terraform:
>     name: 'Halo CMM'
> ```

Halo Kingdom
___
*[`.github/workflows/create_kingdom.yml` line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NR8EnXAB6MljaRgFDDy:-NR8EnXAB6MljaRgFDDz:b-rr2rjs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cf5dd747e5f8192e8e0c8e3ad378e62905c52ca/.github/workflows/create_kingdom.yml#L65)):*
> ```YAML
>  #       with:
>  #         working-directory: ${{env.ROOT_PATH}}
>  #         environment: ${{ env.ENV }}
> ```

Please leave a TODO for the k8s deploy

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, and @TNATALI)

**Review by wfa-siyengar — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-:-NRI-cDDEKEnV_H--AxS:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @bdomen-ggl, @duliomatos1, @kungfucraig, @SanjayVas, and @TNATALI)

___
*[`.github/workflows/create_kingdom.yml` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NR8EG7FASoC7Dr8kUNj:-NR8FAji3uOj7nu5zpnW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cf5dd747e5f8192e8e0c8e3ad378e62905c52ca/.github/workflows/create_kingdom.yml#L15)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Deploy Kingdom
</blockquote></details>

Done.
___
*[`.github/workflows/create_kingdom.yml` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NR33mX324V5hHAN8-ZJ:-NR8FpIL3ZiUbNKn4dJV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cf5dd747e5f8192e8e0c8e3ad378e62905c52ca/.github/workflows/create_kingdom.yml#L17)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please leave a TODO for workflow_run.
</blockquote></details>

Done.
___
*[`.github/workflows/create_kingdom.yml` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NR8EQfK0Y3g1_VHZmDw:-NR8G8A55aO42RHuLt7t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cf5dd747e5f8192e8e0c8e3ad378e62905c52ca/.github/workflows/create_kingdom.yml#L25)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

What's this for?
</blockquote></details>

Done.

**Review by bdomen-ggl — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, and @TNATALI)

___
*[`.github/workflows/create_kingdom.yml` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NR8EQfK0Y3g1_VHZmDw:-NRZRP4C9O3TRvX5FhfS:b-jg5ew7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cf5dd747e5f8192e8e0c8e3ad378e62905c52ca/.github/workflows/create_kingdom.yml#L25)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is supposed to be used for the terraform step below right? This is so you can specify the component name that TF uses to prefix all the resources if I recall correctly.
```
component: ${{ inputs.kingdom }}
```
Looks like it's similar to the `duchy` input in the other file. I think you still need this, no?

I may be mistaken, but think you still need this

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, @TNATALI, and @wfa-siyengar)

___
*[`.github/workflows/deploy_duchy.yml` line 67 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NRc6e9v2baMG1kTQzQf:-NRc6e9v2baMG1kTQzQg:bsooel5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ad85fbb482419e58703af1ca838a0d34f1a14a9/.github/workflows/deploy_duchy.yml#L67)):*
> ```YAML
>           working-directory: ${{env.ROOT_PATH}}
>           environment: ${{ inputs.environment }}
>           component: ${{ inputs.duchy }}
> ```

Rename files to use hyphens not underscores.

**Review by wfa-siyengar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl, @duliomatos1, @kungfucraig, @SanjayVas, and @TNATALI)

___
*[`.github/workflows/deploy_duchy.yml` line 67 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NRc6e9v2baMG1kTQzQf:-NRdMSPY-4NQWyyBCUv_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ad85fbb482419e58703af1ca838a0d34f1a14a9/.github/workflows/deploy_duchy.yml#L67)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

Sure Craig, file name is changed, hyphens are added and underscores are removed 
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @kungfucraig, @TNATALI, and @wfa-siyengar)

___
*[`.github/workflows/deploy-duchy.yml` line 15 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NRdMjLD-e4_XsYVJMM-:-NRdMjLD-e4_XsYVJMM0:bs1d1pz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6683016613a8ee4a4a4972f9ad4c55dd11e031e4/.github/workflows/deploy-duchy.yml#L15)):*
> ```YAML
> # limitations under the License.
> 
> name: 'Deploy Duchy'
> ```

Unrelated change: this doesn't belong in this PR. This PR is just for adding the Kingdom deployment (at least that's what's stated in the description).
___
*[`.github/workflows/deploy-kingdom.yml` line 18 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NRdMtfpBqxh2NeybZ3x:-NRdMtfpBqxh2NeybZ3y:b-kvmmpm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6683016613a8ee4a4a4972f9ad4c55dd11e031e4/.github/workflows/deploy-kingdom.yml#L18)):*
> ```YAML
> 
> on:
>   #TODO: (@wfa-siyengar) add workflow_call
> ```

nit: follow TODO and comment format



_Suggestion:_
```YAML
# TODO(@wfa-siyengar):
```

**Review by kungfucraig — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @TNATALI, and @wfa-siyengar)

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @TNATALI, and @wfa-siyengar)

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @TNATALI, and @wfa-siyengar)

**Review by wfa-siyengar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @kungfucraig, @SanjayVas, and @TNATALI)

___
*[`.github/workflows/deploy-duchy.yml` line 15 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NRdMjLD-e4_XsYVJMM-:-NRdXplEEUGHQ9iiqk_I:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6683016613a8ee4a4a4972f9ad4c55dd11e031e4/.github/workflows/deploy-duchy.yml#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Unrelated change: this doesn't belong in this PR. This PR is just for adding the Kingdom deployment (at least that's what's stated in the description).
</blockquote></details>

Done.

**Review by wfa-siyengar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kungfucraig, @SanjayVas, and @TNATALI)

___
*[`.github/workflows/deploy-duchy.yml` line 15 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NRdMjLD-e4_XsYVJMM-:-NRdwa_qAPjKEgJ7Qx3k:b-8t6j7g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6683016613a8ee4a4a4972f9ad4c55dd11e031e4/.github/workflows/deploy-duchy.yml#L15)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@SanjayVas Request your approval.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @TNATALI, and @wfa-siyengar)

___
*[`.github/workflows/deploy-kingdom.yml` line 71 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-NRe8Mvd4dbr4gTyJ0KY:-NRe8Mvd4dbr4gTyJ0KZ:b-kvmmpm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d5c8859333e4bc11ef0fe4f411a393f42c5239c/.github/workflows/deploy-kingdom.yml#L71)):*
> ```YAML
>           environment: ${{ env.ENV }}
> 
> # TODO: (@wfa-hkawalkar) add k8s deploy.
> ```

nit: follow TODO and comment format



_Suggestion:_
```YAML
# TODO(@wfa-hkawalkar): add k8s deploy.
```

**Review by bdomen-ggl — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-:-NRhEyLB1HGh6ADQ-mbD:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @duliomatos1, @kungfucraig, @SanjayVas, and @TNATALI)

**Review by wfa-siyengar — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901#-:-NRhSrKFCmkFMaV8h_R0:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @kungfucraig and @SanjayVas)

**Review by wfa-siyengar — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/901)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wfa-siyengar)

**Pull request merged**
