### PR TITLE
Add OpenTelemetry Metrics Scraped by Managed Prometheus to GKE

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 1 of 3 files at r2, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`docs/gke/metrics-deployment.md` line 211 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698#-ND-DhpV2APR5FyA6EgS:-ND-DhpV2APR5FyA6EgT:b8hqygz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/411b287d0fda191116820d458bd88ec350eb242c/docs/gke/metrics-deployment.md#L211)):*
> ```Markdown
> ## Adding Additional Metrics
> 
> The above adds OpenTelemetry jvm and rpc metrics, and Cloud Spanner metrics, as 
> ```

nit: JVM and RPC



_Code quote:_
```Markdown
jvm and rpc
```
___
*[`src/main/k8s/base.cue` line 472 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698#-ND-BxTz-3keosHraHGt:-ND-BxTz-3keosHraHGu:b-4jzxnh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/411b287d0fda191116820d458bd88ec350eb242c/src/main/k8s/base.cue#L472)):*
> ```CUE
> #NetworkPolicy: {
> 	_name: string
> 	_labels: [_=string]: string
> ```

spec.podSelector.matchLabels is already a map, so there's not need to expose our own map here. Anyone who wants to set another label can just do so by directly referencing that field.



_Code quote:_
```CUE
_labels
```
___
*[`src/main/k8s/open_telemetry.cue` line 60 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698#-ND-Cw325t8vBWNC3VXX:-ND-Cw325t8vBWNC3VXY:b8ee736) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/411b287d0fda191116820d458bd88ec350eb242c/src/main/k8s/open_telemetry.cue#L60)):*
> ```CUE
> 		apiVersion: "opentelemetry.io/v1alpha1"
> 		kind:       "OpenTelemetryCollector"
> 		metadata: name: string | *"\(_name)-sidecar"
> ```

nit: do you maybe want to extract an #OpenTelemetryCollector definition?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/k8s/base.cue` line 472 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698#-ND-BxTz-3keosHraHGt:-ND-vETfEuFKd1PZ53ds:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/411b287d0fda191116820d458bd88ec350eb242c/src/main/k8s/base.cue#L472)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

spec.podSelector.matchLabels is already a map, so there's not need to expose our own map here. Anyone who wants to set another label can just do so by directly referencing that field.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/k8s/base.cue` line 585 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698#-ND08Fh131gd0b3ao7jg:-ND08Fh131gd0b3ao7jh:b-pyiq80) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/193f2df8af0676a1d5240e748ab4d042ba89286e/src/main/k8s/base.cue#L585)):*
> ```CUE
> // K8s custom resource defined by OpenTelemetry Operator used for creating
> // an OpenTelemetry Collector.
> #OpenTelemetryCollector: {
> ```

nit: I assumed this would be defined in open_telemetry.cue since nothing else needs it
___
*[`src/main/k8s/dev/open_telemetry_gke.cue` line 67 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698#-ND08gDW6H11KA2xqWYa:-ND08gDW6H11KA2xqWYb:babqct8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/193f2df8af0676a1d5240e748ab4d042ba89286e/src/main/k8s/dev/open_telemetry_gke.cue#L67)):*
> ```CUE
>                 """
> 			metadata: name: "deployment"
> 			spec: mode:     "deployment"
> ```

GKE uses deployment mode? I thought that we'd still be using sidecars for otel collector, but a single Prometheus.

I don't think there's a reason to be inconsistent between GKE and KinD w.r.t. whether we're using sidecar. We should use the same mode for both.



_Code quote:_
```CUE
"deployment"
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/dev/open_telemetry_gke.cue` line 67 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698#-ND08gDW6H11KA2xqWYa:-ND0DGh5BlrEQgerQCvZ:b-pd2d89) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/193f2df8af0676a1d5240e748ab4d042ba89286e/src/main/k8s/dev/open_telemetry_gke.cue#L67)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

GKE uses deployment mode? I thought that we'd still be using sidecars for otel collector, but a single Prometheus.

I don't think there's a reason to be inconsistent between GKE and KinD w.r.t. whether we're using sidecar. We should use the same mode for both.
</blockquote></details>

The sidecars are still there. There is just an additional deployment that grabs the cloud spanner metrics.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 6 files at r4, 1 of 3 files at r5, 1 of 3 files at r6, 2 of 2 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/698)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
