### PR TITLE
Refactor resource key to be across APIs

### PR DESCRIPTION
**Pull request by riemanli**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/599)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/599)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/RequisitionKey.kt` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/599#-N4TyVHkCLZBoOdvgpYS:-N4TyVHkCLZBoOdvgpYT:bhby3if) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d77e50b68a2fc55c575d61f0d8bc5b223150a266/src/main/kotlin/org/wfanet/measurement/api/v2alpha/RequisitionKey.kt#L17)):*
> ```Kotlin
> package org.wfanet.measurement.api.v2alpha
> 
> import org.wfanet.measurement.common.ResourceNameParser
> ```

I didn't realize `ResourceNameParser` is in common-jvm. Perhaps `ResourceKey` actually belongs there.
___
*[`src/main/kotlin/org/wfanet/measurement/common/api/ResourceKey.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/599#-N4U2W2-D9RbJSn-1Nhs:-N4U2W2-D9RbJSn-1Nht:btp060u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d77e50b68a2fc55c575d61f0d8bc5b223150a266/src/main/kotlin/org/wfanet/measurement/common/api/ResourceKey.kt#L19)):*
> ```Kotlin
> interface ResourceKey {
>   /** Converts this [ResourceKey] into a resource name. */
>   fun toName(): String
> ```

While you're touching this, consider adding a nested `Factory` interface that the companion object can implement.

```kotlin
interface ResourceKey {
  /** Converts this [ResourceKey] into a resource name. */
  fun toName(): String

  /** Factory for [T]. */
  interface Factory<out T : ResourceKey> {
    /**
     * Parses [resourceName] into a [T].
     * 
     * @return the [ResourceKey], or `null` if parsing failed
     */
    fun fromName(resourceName: String): T?
  }
}
```

It could then be implemented as such, e.g. in `DataProviderKey`:

```kotlin
companion object FACTORY: ResourceKey.Factory<DataProviderKey> {
    //...

    override fun fromName(resourceName: String): DataProviderKey? {
      return parser.parseIdVars(resourceName)?.let {
        DataProviderKey(it.getValue(IdVariable.DATA_PROVIDER))
      }
    }
  }
```

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/599)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/RequisitionKey.kt` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/599#-N4TyVHkCLZBoOdvgpYS:-N4UYEVkD9oZwi35NviX:bwfdcmb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d77e50b68a2fc55c575d61f0d8bc5b223150a266/src/main/kotlin/org/wfanet/measurement/api/v2alpha/RequisitionKey.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I didn't realize `ResourceNameParser` is in common-jvm. Perhaps `ResourceKey` actually belongs there.
</blockquote></details>

Good to know. If you don't mind, please allow me to defer that option for now.
___
*[`src/main/kotlin/org/wfanet/measurement/common/api/ResourceKey.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/599#-N4U2W2-D9RbJSn-1Nhs:-N4UyBpjAof6I8uMe6JZ:b-kcq82f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d77e50b68a2fc55c575d61f0d8bc5b223150a266/src/main/kotlin/org/wfanet/measurement/common/api/ResourceKey.kt#L19)):*
> FACTORY
This looks nice, but could you explain what benefit this change can bring in?

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/599)* status: 9 of 31 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/api/ResourceKey.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/599#-N4U2W2-D9RbJSn-1Nhs:-N4d92TP7DEdPPjv8fPv:bhjnsgv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d77e50b68a2fc55c575d61f0d8bc5b223150a266/src/main/kotlin/org/wfanet/measurement/common/api/ResourceKey.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The idea is to have a consistent interface for constructing a ResourceKey from a resource name. There's unfortunately no way to enforce that the companion object for a given ResourceKey impl also implements the interface.

Naming the object `FACTORY` is only for anyone using the library from Java, as it provides a static field. This would just be a convention that callers know they can use this to access the factory for any `ResourceKey` impl. It doesn't make a difference when calling from Kotlin.
</blockquote></details>

Thanks for explaining. I modified as suggested.

**Review by chipingyeh — APPROVED** [review]
> Reviewed 7 of 31 files at r1, 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/599)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/599)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Pull request merged**
