### PR TITLE
Create Demo-UI Deploy Scripts and Directions

### PR DESCRIPTION
**Pull request by bdomen-ggl**
Adding deployment script for the Demo UI and fully comprehensive directions.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352)* status: all files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl)

___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 13 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NkqswlU7eOodNg0aRNO:-NkqswlU7eOodNg0aRNP:b5egwoh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab62b671f0edc726b5f931a84c6ff2050767ff4c/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L13)):*
> ```Markdown
> compute capabilities.
> 
> # Setup K8S and GCloud
> ```

nit: Can leave this out and just say to make sure that kubectl is configured to point to the desired cluster.
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NkqtC-5DS5G0H4ZOH2c:-NkqtC-60d8gys4IdPWs:b4l27dy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab62b671f0edc726b5f931a84c6ff2050767ff4c/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L40)):*
> ```Markdown
> an alias to make changing clusters easier.
> Replace CLUSTER_NAME with the name of the cluster.
> ```

Isn't there a service account that needs to be set up with workload identity? You can link to https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/cluster-config.md#workload-identity
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NkqsMEb2yShIE5TtgCL:-NkqsMEb2yShIE5TtgCM:bqbko6l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab62b671f0edc726b5f931a84c6ff2050767ff4c/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L43)):*
> ```Markdown
> # Apply the Config
> 
> The configuration is already setup. We'll simply apply it to the cluster.
> ```

Like our other deployment docs, explain that the dev configuration is just one that can be used as a base. Explain that they should make their own copy so they can make any necessary customizations. In particular, note that the configuration uses a hard-coded GCS bucket.
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-Nkqsshn2hnr6fkd8VXR:-Nkqsshn2hnr6fkd8VXS:bco568s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab62b671f0edc726b5f931a84c6ff2050767ff4c/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L53)):*
> ```Markdown
> To verify the cluster, run the command:
> 
> ```
> ```

nit: Leave blank spaces around code fences as per Markdown spec. GitHub will understand, but some tools are more strict. Also specify the language when applicable.

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 13 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NkqswlU7eOodNg0aRNO:-Nkqu1gb8GGlxa_O0f1-:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab62b671f0edc726b5f931a84c6ff2050767ff4c/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L13)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Can leave this out and just say to make sure that kubectl is configured to point to the desired cluster.
</blockquote></details>

Done
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NkqtC-5DS5G0H4ZOH2c:-NkqtrE58b3X9lR9GAIK:bxjo8qs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab62b671f0edc726b5f931a84c6ff2050767ff4c/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Isn't there a service account that needs to be set up with workload identity? You can link to https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/cluster-config.md#workload-identity
</blockquote></details>

Yes, I'll update to include all the manual work I did including enabling the CSI FUSE addon and creating the bucket.

Done.
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NkqsMEb2yShIE5TtgCL:-Nl4ohQt4XBiXO3BiFZt:bg4di1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab62b671f0edc726b5f931a84c6ff2050767ff4c/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Like our other deployment docs, explain that the dev configuration is just one that can be used as a base. Explain that they should make their own copy so they can make any necessary customizations. In particular, note that the configuration uses a hard-coded GCS bucket.
</blockquote></details>

Updated to note the config as a base and to copy and modify it.

Done.
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-Nkqsshn2hnr6fkd8VXR:-Nl4onhyB7jwAq6U3Lhv:btuqmgl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab62b671f0edc726b5f931a84c6ff2050767ff4c/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Leave blank spaces around code fences as per Markdown spec. GitHub will understand, but some tools are more strict. Also specify the language when applicable.
</blockquote></details>

Fixed the blank spaces around code.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352)* status: all files reviewed, 7 unresolved discussions (waiting on @bdomen-ggl)

___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 5 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPTHLb81FDqhG4GhNv:-NlPTHLc16z1hu1CWRyt:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L5)):*
> ```Markdown
> Since the Demo UI is based on showing reports, it will be deployed to the Reporting K8S cluster. We will assume the cluster is already created.
> 
> To host the Demo UI, we are using NGINX as a simple webserver. In order to mount some configuration, it requires additional resource capacity. If the Reporting cluster was configured with the minimum, it may need to be reconfigured with an SSD boot disk and additional max node count. You can also create a new cluster in a similar fashion with the additional compute capabilities.
> ```

nit



_Suggestion:_
```Markdown
web server
```
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 7 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPTIu24i_buv32wdTV:-NlPTIu24i_buv32wdTW:b3hf2xx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L7)):*
> ```Markdown
> To host the Demo UI, we are using NGINX as a simple webserver. In order to mount some configuration, it requires additional resource capacity. If the Reporting cluster was configured with the minimum, it may need to be reconfigured with an SSD boot disk and additional max node count. You can also create a new cluster in a similar fashion with the additional compute capabilities.
> 
> To setup and configure the environment, you can generally follow these directions:
> ```

nit: grammar (verb phrase rather than noun)



_Suggestion:_
```Markdown
set up
```
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 12 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPU-DM1nUoClThn8ud:-NlPU-DM1nUoClThn8ue:b-kj7hyg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L12)):*
> ```Markdown
> They will be summarized below assuming we are updating a cluster.
> 
> # Setup the GCS Bucket
> ```

Only the page title should use `#`. Everything else should be at least `##`.
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 16 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPULaA8GQhjmgigB2l:-NlPULaA8GQhjmgigB2m:b-q6xir7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L16)):*
> ```Markdown
> ## Create a Bucket
> 
> In your GCS account, create a storage bucket and note the name. In the `reporting_ui.yaml` file, update this section to use your bucket name.
> ```

Move the object configuration customization part after where you first mention copying the YAML file.
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 58 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPTcf55k5VTvE_K_h2:-NlPTcf55k5VTvE_K_h3:b-7g06pg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L58)):*
> ```Markdown
> 
> ## Create and Configure a GKE Workload Identity
> ```

Reference the Workload Identity section in docs/gke/cluster-config.md
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPUkyq3EZh4BfiIKgQ:-NlPUkyq3EZh4BfiIKgR:b-jfwfv0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L99)):*
> ```Markdown
> ```
> 
> # Apply the Config
> ```

I'd split this into two: customizing the object configuration and applying the object configuration.
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 104 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPV02z9kQ0YplClmBq:-NlPV02z9kQ0YplClmBr:b-410eer) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L104)):*
> ```Markdown
> 
> ```shell
> kubectl apply experimental/reporting-ui/src/main/k8s/dev/reporting_ui
> ```

I don't think this command is correct. For applying a single reporting_ui.yaml file, it would be

```shell
kubectl apply -f path/to/reporting_ui.yaml
```

I'd avoid referencing the path in the Bazel project in this command and instead link to it in the above paragraph when indicating where to copy it from. We don't want people editing this file in-place.

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 5 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPTHLb81FDqhG4GhNv:-NlTZnVjAzT-zV8kHSQO:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 7 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPTIu24i_buv32wdTV:-NlTZoCr9kcHZbVaXY_X:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: grammar (verb phrase rather than noun)
</blockquote></details>

Done
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 12 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPU-DM1nUoClThn8ud:-NlTZosp1R_RH6C1WC0t:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L12)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Only the page title should use `#`. Everything else should be at least `##`.
</blockquote></details>

Done
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 16 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPULaA8GQhjmgigB2l:-NlTdz9P9EEgLFZddIE_:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L16)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move the object configuration customization part after where you first mention copying the YAML file.
</blockquote></details>

Done
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 58 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPTcf55k5VTvE_K_h2:-NlTeovjDQnBlX_OadzL:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Reference the Workload Identity section in docs/gke/cluster-config.md
</blockquote></details>

Done
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPUkyq3EZh4BfiIKgQ:-NlTgX7g0HKJI1tsEFua:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'd split this into two: customizing the object configuration and applying the object configuration.
</blockquote></details>

Done
___
*[`experimental/reporting-ui/docs/gke/demo-ui-deployment.md` line 104 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1352#-NlPV02z9kQ0YplClmBq:-NlTeuU04hCuy-Ii95bI:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60759064aea95bba540fc3650eb1adfd96d80f18/experimental/reporting-ui/docs/gke/demo-ui-deployment.md#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this command is correct. For applying a single reporting_ui.yaml file, it would be

```shell
kubectl apply -f path/to/reporting_ui.yaml
```

I'd avoid referencing the path in the Bazel project in this command and instead link to it in the above paragraph when indicating where to copy it from. We don't want people editing this file in-place.
</blockquote></details>

Done

**Pull request merged**
