### PR TITLE
Shutdown threads properly so Report Scheduling Process can complete

### PR DESCRIPTION
**Pull request by tristanvuong2021**
When running this in a Kubernetes Cron Job, the job isn't considered completed without this change.

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoSX0y9EbtgTEv68V4M:-NoSX0y9EbtgTEv68V4N:b1id3uk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b9d09467a4f1d9b1ae88a548004bb33bf8c2688/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L157)):*
> ```Kotlin
>   runBlocking { reportSchedulingJob.execute() }
>   // Ensures process is completed so any container running this can mark it as completed.
>   exitProcess(0)
> ```

`commandLineMain` does this for us. Indeed, we haven't needed it in any of our other jobs. I suspect something else is happening, such as in-process servers not being shut down.

You probably need to modify `startInProcessServerWithService` to return the server rather than the channel so that you can stop it.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoSX0y9EbtgTEv68V4M:-NoSZ0oH5mafsi-7ISTM:bdh2lhr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b9d09467a4f1d9b1ae88a548004bb33bf8c2688/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L157)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`commandLineMain` does this for us. Indeed, we haven't needed it in any of our other jobs. I suspect something else is happening, such as in-process servers not being shut down.

You probably need to modify `startInProcessServerWithService` to return the server rather than the channel so that you can stop it.
</blockquote></details>

You may also want to add withShutdownTimeout to your gRPC channels to give them time to shut down.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoSX0y9EbtgTEv68V4M:-NoSse7h-qL4mqOosu4D:b7xec2a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b9d09467a4f1d9b1ae88a548004bb33bf8c2688/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L157)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You may also want to add withShutdownTimeout to your gRPC channels to give them time to shut down.
</blockquote></details>

I tried both shutdown and shutdownNow, and neither has worked to end the process.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoSX0y9EbtgTEv68V4M:-NoStNn3-FlT0At9yIHK:b-490ljx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b9d09467a4f1d9b1ae88a548004bb33bf8c2688/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L157)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I tried both shutdown and shutdownNow, and neither has worked to end the process.
</blockquote></details>

No other job has needed to explicitly call `exitProcess`, so again something else has to be blocking process shutdown. I see you haven't yet added the channel shutdown hooks. Do so and see if they log anything. If not, then it means that the JVM isn't even trying to shut down. Also try adding some logging between the statements here to see if it's getting stuck awaiting termination.

Note that `commandLineMain` only explicitly calls `exitProcess` for non-zero exit status. In the success case it's just expecting the normal JVM shutdown process to work.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoSX0y9EbtgTEv68V4M:-NoSy9SRE3JTQCJCmy5Q:bg22w77) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b9d09467a4f1d9b1ae88a548004bb33bf8c2688/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L157)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No other job has needed to explicitly call `exitProcess`, so again something else has to be blocking process shutdown. I see you haven't yet added the channel shutdown hooks. Do so and see if they log anything. If not, then it means that the JVM isn't even trying to shut down. Also try adding some logging between the statements here to see if it's getting stuck awaiting termination.

Note that `commandLineMain` only explicitly calls `exitProcess` for non-zero exit status. In the success case it's just expecting the normal JVM shutdown process to work.
</blockquote></details>

I added print statements to everything. The in process channels and servers finish their respective awaitTermination calls, but the process is still running.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoSX0y9EbtgTEv68V4M:-NoT0hma31bYFrBPzJ2-:ba0pop5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b9d09467a4f1d9b1ae88a548004bb33bf8c2688/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L157)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I added print statements to everything. The in process channels and servers finish their respective awaitTermination calls, but the process is still running.
</blockquote></details>

And the channel shutdown hooks (`withShutdownTimeout`)?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoSX0y9EbtgTEv68V4M:-NoT7RVN-x5cxuZGQC9X:b-c5p63x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b9d09467a4f1d9b1ae88a548004bb33bf8c2688/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L157)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

And the channel shutdown hooks (`withShutdownTimeout`)?
</blockquote></details>

Did that and checked isShutdown as well. Still don't know what is running.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoSX0y9EbtgTEv68V4M:-NoTAKcvC2L17jVDYGbW:b-25rlev) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b9d09467a4f1d9b1ae88a548004bb33bf8c2688/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L157)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Did that and checked isShutdown as well. Still don't know what is running.
</blockquote></details>

I mean what happened with those hooks? Do you see the log messages from them?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoSX0y9EbtgTEv68V4M:-NoTCQ3I1AWTjXV0-Vn9:buwkfne) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b9d09467a4f1d9b1ae88a548004bb33bf8c2688/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L157)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I mean what happened with those hooks? Do you see the log messages from them?
</blockquote></details>

I don't.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoSX0y9EbtgTEv68V4M:-NoTEbd34oZEoe4WCz8H:b-bjpxez) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b9d09467a4f1d9b1ae88a548004bb33bf8c2688/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L157)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I don't.
</blockquote></details>

Alright, I guess leave the exitProcess(0) with a TODO to investigate why it's needed.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoSX0y9EbtgTEv68V4M:-NoTGv_e5th6Sn72iK3H:b-7quwem) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b9d09467a4f1d9b1ae88a548004bb33bf8c2688/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L157)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Alright, I guess leave the exitProcess(0) with a TODO to investigate why it's needed.
</blockquote></details>

Figured it out, it was the executor.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServersMethods.kt` line 32 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoTKCKM9g0E7pTmfBek:-NoTKCKM9g0E7pTmfBel:bsxz2h0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48df0571fc187a0cd7f246e00479b3dc3d337ca5/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServersMethods.kt#L32)):*
> ```Kotlin
>     executorService: ExecutorService?,
>     commonServerFlags: CommonServer.Flags,
>     service: ServerServiceDefinition
> ```

Make executorService an explicitly optional param



_Suggestion:_
```Kotlin
    serverName: String,
    commonServerFlags: CommonServer.Flags,
    service: ServerServiceDefinition,
    executorService: ExecutorService? = null,
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/server/V2AlphaPublicApiServer.kt` line 192 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoTKr7l8Ckecuowe1c2:-NoTKr7l8Ckecuowe1c3:byunyk9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48df0571fc187a0cd7f246e00479b3dc3d337ca5/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/server/V2AlphaPublicApiServer.kt#L192)):*
> ```Kotlin
>     )
> 
>   val executorService: ExecutorService =
> ```

nit: maybe rename to make it clear this is for in-process server?



_Suggestion:_
```Kotlin
inProcessExecutorService
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServersMethods.kt` line 32 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoTKCKM9g0E7pTmfBek:-NoTM83V3eH-zmIrADPE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48df0571fc187a0cd7f246e00479b3dc3d337ca5/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServersMethods.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Make executorService an explicitly optional param
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServersMethods.kt` line 36 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoTMix95MxpxPad5Jfd:-NoTMixA6ljGyg82cvHn:b-j67szq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9192efaa71bfa0a728f0d35829374b7db0a10b6c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServersMethods.kt#L36)):*
> ```Kotlin
>     return InProcessServerBuilder.forName(serverName)
>       .apply {
>         if (executorService != null) {
> ```

Oops, spotted an issue here. We want to explicitly use directExecutor() if no executor is specified. Otherwise InProcessServerBuilder will use its own cached thread pool that we have no control over.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServersMethods.kt` line 36 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429#-NoTMix95MxpxPad5Jfd:-NoTPIIk4rrZKvAyCw7O:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9192efaa71bfa0a728f0d35829374b7db0a10b6c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServersMethods.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Oops, spotted an issue here. We want to explicitly use directExecutor() if no executor is specified. Otherwise InProcessServerBuilder will use its own cached thread pool that we have no control over.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1429)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
