### PR TITLE
Update common-media-measurement-api to v0.2.0.

### PR DESCRIPTION
**Pull request by SanjayVas**
This updates internal and v2alpha public service implementations to handle world-federation-of-advertisers/cross-media-measurement-api#37.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179)

### CODE REVIEW

**Comment by SanjayVas** [comment]
CC @uakyol since this touches Kingdom internal service implementations.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179#-MgNReuQASCRiR7Ac3N1:-MgNReuREBtAibB_OFaG:be2jrv3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbc88840a3fb46e2821e1ff4f2777791c9a1fb5b/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel#L17)):*
> ```
> preferred_
> ```
delete?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179#-MgNReuQASCRiR7Ac3N1:-MgNa57e1q1K1kACnqRQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbc88840a3fb46e2821e1ff4f2777791c9a1fb5b/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel#L17)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> preferred_
> ```
delete?
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by wangyaopw — APPROVED** [review]
:lgtm:

> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179#-:-MgNd2Fp-qgFA9CURR0F:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179#-MgNpcPy3IzfEGGDe6s1:-MgNpcPy3IzfEGGDe6s2:bmx20yn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3011b8c77e9cb8fb5a913bbbeb67017100aeecae/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L41)):*
> ```
> PREFERRED
> ```
There are still some `preferred` in several tests. and two tests are failing. You may want to replace them all.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179)* status: 11 of 17 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179#-MgNpcPy3IzfEGGDe6s1:-MgRGLic-gwnxSqC16ml:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3011b8c77e9cb8fb5a913bbbeb67017100aeecae/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L41)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> PREFERRED
> ```
There are still some `preferred` in several tests. and two tests are failing. You may want to replace them all.
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @zachcwc)

**Review by corbantek — APPROVED** [review]
> Reviewed 10 of 17 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn and @zachcwc)

**Comment by oliver-amzn** [comment]
Rebase / resolve conflicts?

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 10 of 17 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Pull request merged**
