### PR TITLE
Implement logic to update Data Provider duchy list

### PR DESCRIPTION
**Pull request by jojijac0b**
Create ReplaceDataProviderRequiredDuchies class to update duchy list in DataProviderRequiredDuchies table. The return value of the TransactionScope.runTransaction method in this class is the DataProvider object with the updated duchy list

Implement replaceDataProviderRequiredDuchies in SpannerDataProvidersService to call the new ReplaceDataProviderRequiredDuchies class with the ReplaceDataProviderRequiredDuchiesRequest. This method will throw an error if the externalDataProviderId is not present in the request.

Create test that checks:
1. the returned DataProvider has the updated duchy list
2. the DataProviderRequiredDuchies table is updated

https://rally1.rallydev.com/#/604612930531d/iterationstatus?detail=%2Ftask%2F697342533129

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934)

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NSkNjBb9lSyGY_Q6FZW:-NSkrA1pB4f3EzbhFitt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2460ad303ab94bffabd81b4930f4b0688cd11594/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt#L58)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

As per above comment (throwing DataProvider exception) we should now capture and handle the exception if raised.

```
try {
  return ReplaceDataProviderRequiredDuchies(request).execute(client, idGenerator)
} catch (e: DataProviderNotFoundException) {
  e.throwStatusRuntimeException(Status.NOT_FOUND) { "DataProvider not found." }
}
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NSkMzvF3fspcyVblCue:-NSkrByx57JprUvNPBUa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2460ad303ab94bffabd81b4930f4b0688cd11594/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt#L39)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I know I suggested this change previously but I think we should treat it like we do in other part of that code (i.e. explicitly throwing an exception if DataProvider is not found):

(https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdatePublicKey.kt#L89)

```
DataProviderReader()
          .readByExternalDataProviderId(
            transactionContext,
            ExternalId(replaceDataProviderRequiredDuchiesRequest.externalDataProviderId)
          )
          ?: throw DataProviderNotFoundException(ExternalId(request.externalDataProviderId))
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NSkIDz8BoYMYSFVjt0v:-NSkrDuh5onaKj5MW_MQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2460ad303ab94bffabd81b4930f4b0688cd11594/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt#L46)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I would remove this check entirely as the method should accept any ```desiredRequiredDuchyList``` and simply replace the existing one with the new one. API caller is responsible to consume this API wisely and it's not actually an error if they replace a list with a new identical one.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt` line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NSkHxQm66vhwPV9CvXc:-NSkrETF4sS2sp03IRI9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2460ad303ab94bffabd81b4930f4b0688cd11594/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt#L47)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

This can resolve in a unwanted behavior. i.e. set1 = (1,2,3) AND set2 = (4,5,6) -> they have the same length but they containsdifferent values (it's a legitimate request). However in this case the check would return an exception.
</blockquote></details>

Done.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934)* status: all files reviewed, 6 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt` line 53 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NSvlzXg4QDyln381E7b:-NSvlzXg4QDyln381E7c:b-k2cw16) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41214fb611f6cfddab1f6de5223197789b3d8f0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt#L53)):*
> ```Kotlin
>       ?: failGrpc(Status.NOT_FOUND) { "DataProvider not found" }
>   }
>   override suspend fun replaceDataProviderRequiredDuchies(
> ```

nit: blank line between function definitions
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt` line 52 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NSvnVWXE1JbwXzUupls:-NSvnVWXE1JbwXzUuplt:b-ejkjha) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41214fb611f6cfddab1f6de5223197789b3d8f0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt#L52)):*
> ```Kotlin
>     // Delete old duchy list.
>     for (externalDuchyId in currentRequiredDuchyList) {
>       val duchyId =
> ```

I believe you can just use a prefix to delete all rows for a given DataProviderId.



_Suggestion:_
```Kotlin
    // Delete old duchy list.
    transactionContext.buffer(
      Mutation.delete(
        "DataProviderRequiredDuchies",
        KeySet.prefixRange(Key.of(dataProviderId))
      )
    )
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt` line 211 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NSvlehn8EGPpuLFsRgP:-NSvlehn8EGPpuLFsRgQ:bgiv5dg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41214fb611f6cfddab1f6de5223197789b3d8f0/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt#L211)):*
> ```Kotlin
>   fun `replaceDataProviderRequiredDuchies succeeds`() = runBlocking {
>     val dataProvider =
>       DataProvider.newBuilder()
> ```

Use Kotlin DSL protobuf builders for all new code.



_Code quote:_
```Kotlin
      DataProvider.newBuilder()
        .apply {
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt` line 227 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NSvm_sk-3GL9l142YNM:-NSvm_sk-3GL9l142YNN:b-9diwy3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41214fb611f6cfddab1f6de5223197789b3d8f0/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt#L227)):*
> ```Kotlin
>         .build()
>     val createdDataProvider = dataProvidersService.createDataProvider(dataProvider)
>     val desiredDuchyList = listOf("aggregator")
> ```

Use the established constant.



_Suggestion:_
```Kotlin
Population.AGGREGATOR_DUCHY.externalDuchyId
```

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934)* status: all files reviewed, 8 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt` line 230 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NTEgdfFDYX6BzmiUNmV:-NTEgdfFDYX6BzmiUNmW:b-bycp6h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a7bc2dc8c868dc07fd19f9e4e7e4f610a82d2c1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt#L230)):*
> ```Kotlin
>     val updatedDataProvider =
>       dataProvidersService.replaceDataProviderRequiredDuchies(
>         ReplaceDataProviderRequiredDuchiesRequest.newBuilder()
> ```

I prefer kotlin dsls here:
```
replaceDataProviderRequiredDuchiesRequest {
   externalDataProviderId = createdDataProvider.externalDataProviderId
   requiredExternalDuchyIds += desiredDuchyList
}
```

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt` line 240 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NTEgy8l-dPUOl19NB3p:-NTEgy8l-dPUOl19NB3q:bvmssw0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a7bc2dc8c868dc07fd19f9e4e7e4f610a82d2c1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt#L240)):*
> ```Kotlin
>     val dataProviderRead =
>       dataProvidersService.getDataProvider(
>         GetDataProviderRequest.newBuilder()
> ```

ditto on the kotlin dsls

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934)* status: all files reviewed, 7 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt` line 52 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NSvnVWXE1JbwXzUupls:-NTGl7IO7MVHEwWIEiN7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a7bc2dc8c868dc07fd19f9e4e7e4f610a82d2c1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe you can just use a prefix to delete all rows for a given DataProviderId.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt` line 211 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NSvlehn8EGPpuLFsRgP:-NTGlAEa5xb3TEwRSl4E:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a7bc2dc8c868dc07fd19f9e4e7e4f610a82d2c1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt#L211)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Kotlin DSL protobuf builders for all new code.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt` line 227 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NSvm_sk-3GL9l142YNM:-NTGlH8l5qtbeTfGUtI_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a7bc2dc8c868dc07fd19f9e4e7e4f610a82d2c1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt#L227)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the established constant.
</blockquote></details>

Done.

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt` line 230 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NTEgdfFDYX6BzmiUNmV:-NTGpsn0-G9WRMzMLX7b:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a7bc2dc8c868dc07fd19f9e4e7e4f610a82d2c1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt#L230)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I prefer kotlin dsls here:
```
replaceDataProviderRequiredDuchiesRequest {
   externalDataProviderId = createdDataProvider.externalDataProviderId
   requiredExternalDuchyIds += desiredDuchyList
}
```

</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt` line 240 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NTEgy8l-dPUOl19NB3p:-NTGptk2Cwjy4R8wrt_3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a7bc2dc8c868dc07fd19f9e4e7e4f610a82d2c1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt#L240)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto on the kotlin dsls
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934)* status: all files reviewed, 4 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt` line 31 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NTLgeWMDhzRxal_9uQ7:-NTLgeWMDhzRxal_9uQ8:bj6n7kw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9b5fc319eb895cc2b6b12ecbda21162630caf05/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt#L31)):*
> ```Kotlin
> 
> class ReplaceDataProviderRequiredDuchies(
>   private val replaceDataProviderRequiredDuchiesRequest: ReplaceDataProviderRequiredDuchiesRequest
> ```

nit: feel free to just call this `request`, since there wouldn't be any other request in the context of this class



_Code quote:_
```Kotlin
replaceDataProviderRequiredDuchiesRequest
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt` line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934#-NTLfsYn2ivFeTqlw68H:-NTLfsYn2ivFeTqlw68I:b3vs67a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9b5fc319eb895cc2b6b12ecbda21162630caf05/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt#L38)):*
> ```Kotlin
>         .readByExternalDataProviderId(
>           transactionContext,
>           ExternalId(replaceDataProviderRequiredDuchiesRequest.externalDataProviderId)
> ```

nit: extract this to a local variable since its used more than once



_Code quote:_
```Kotlin
ExternalId(replaceDataProviderRequiredDuchiesRequest.externalDataProviderId)
```

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b)

**Review by Marco-Premier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/934)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Pull request merged**
