### PR TITLE
feat: Add new Bigquery Table for Computation Participant Stages

### PR DESCRIPTION
**Pull request by tristanvuong2021**
feat: Add new Bigquery Table for Computation Participant Stages

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 3 of 11 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 76 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70TnJr3ArF7llxe72L:-O70TnJr3ArF7llxe72M:bfqa0hw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L76)):*
> ```Kotlin
>   private val streamWriterFactory: StreamWriterFactory = StreamWriterFactoryImpl(),
> ) {
>   suspend fun execute() {
> ```

Is this function writing all of the tables?

It also seems like if we start this job up against a system with an already very large database that we could have problems.

Is it possible to break this function up into smaller atomic parts? 

In general it should be very easy to add a new table without modifying (much if any) already working code.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70VBabDv4Xw1FbEZw0:-O70VBabDv4Xw1FbEZw1:b-tik83v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L140)):*
> ```Kotlin
>             streamWriterFactory = streamWriterFactory,
>           )
>           .use { requisitionsDataWriter ->
> ```

Why is something called "requisitionsDataWriter" operating on the computation participant stages table?
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 240 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70VpVs0lVydefJ-XkD:-O70VpVs0lVydefJ-XkE:bpvkvqj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/terraform/gcloud/modules/kingdom/main.tf#L240)):*
> ```HCL
>     "type": "STRING",
>     "mode": "REQUIRED",
>     "description": "REACH_AND_FREQUENCY, REACH, IMPRESSION, DURATION, or POPULATION"
> ```

This should always be REACH or REACH_AND_FREQUENCY?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 3 of 11 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 76 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70TnJr3ArF7llxe72L:-O70dyLO0dwhy9i3nWRz:b-tvqo5r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L76)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Is this function writing all of the tables?

It also seems like if we start this job up against a system with an already very large database that we could have problems.

Is it possible to break this function up into smaller atomic parts? 

In general it should be very easy to add a new table without modifying (much if any) already working code.
</blockquote></details>

It will depend how large. Dev has 150,000 measurements and that takes 10-15 minutes to process.

It could be possible to stream Measurements using the default view for the Measurements table, stream Requisitions for the Requisitions table, and implements stream Computation Participants for the Computation Participants table.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70VBabDv4Xw1FbEZw0:-O70dZ6xBi5rYu0xICy_:buaynvr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L140)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why is something called "requisitionsDataWriter" operating on the computation participant stages table?
</blockquote></details>

It is not. This is a chain of use statements for automatically closing the writers.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 3 of 11 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 76 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70TnJr3ArF7llxe72L:-O70nMI_CzuWyBnKGsOF:bqyqrz7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L76)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It will depend how large. Dev has 150,000 measurements and that takes 10-15 minutes to process.

It could be possible to stream Measurements using the default view for the Measurements table, stream Requisitions for the Requisitions table, and implements stream Computation Participants for the Computation Participants table.
</blockquote></details>

What happens if it fails 5 minutes through? Would we end up with duplicate rows in the BQ when the job runs the next time?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70tQ-l2WnZeXS-Lt96:-O70tQ-l2WnZeXS-Lt97:b-jfotb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L97)):*
> ```Kotlin
>         when (view) {
>           Measurement.View.DEFAULT -> DEFAULT_VIEW_SQL
>           Measurement.View.COMPUTATION -> COMPUTATION_VIEW_SQL
> ```

COMPUTATION view should not include non-failure log entries of the ComputationParticipant, meaning it should only be using the DEFAULT view of Computation (see other comment). Now that we can query inside of protobuf messages, you can actually have a clause that conditions on whether it's an error log entry.

There are a lot of these and the Duchy doesn't need them. It only needs to know information on whether there's a failure.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70swuHA1jYhOvJFgRk:-O70swuHA1jYhOvJFgRl:b-c50nhi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L60)):*
> ```proto
> 
>   DuchyMeasurementLogEntry failure_log_entry = 8;
>   repeated DuchyMeasurementLogEntry success_log_entries = 12;
> ```

Create a separate view for including these. We do not want to include them in ComputationParticipant reads by default.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70uSJg0s-NdP2WsNTU:-O70uSJg0s-NdP2WsNTV:blh2lox) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L60)):*
> ```proto
> 
>   DuchyMeasurementLogEntry failure_log_entry = 8;
>   repeated DuchyMeasurementLogEntry success_log_entries = 12;
> ```

These aren't actually "success" log entries, they're just not failure/error ones. That is to say they don't indicate success and are just informational.



_Code quote:_
```proto
success_log_entries
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 76 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70TnJr3ArF7llxe72L:-O717AHO7GGInUHSABCN:beqnjt2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L76)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

What happens if it fails 5 minutes through? Would we end up with duplicate rows in the BQ when the job runs the next time?
</blockquote></details>

I keep track of the last row written. If a table gets written to, but the table that keeps track of what has been written fails, then there will be some duplicates then. BigQuery doesn't keep track of duplicates so you could just filter out duplicates in Looker.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70uSJg0s-NdP2WsNTU:-O717nU3C9g0inGSiKwU:bicr7lj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These aren't actually "success" log entries, they're just not failure/error ones. That is to say they don't indicate success and are just informational.
</blockquote></details>

Oh, then is it actually possible to keep track of whether a stage has been completed. That was the intention for this table.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70uSJg0s-NdP2WsNTU:-O71R-4H7ZRLTttyd4OM:b5kl1sq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L60)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Oh, then is it actually possible to keep track of whether a stage has been completed. That was the intention for this table.
</blockquote></details>

I mainly meant the comment for the naming of this field, but what you ask depends on what you mean by "stage has been completed". The log entry tells you the *current* stage. From that, you can infer that it successfully transitioned out of a *previous* stage.

@renjiezh correct me if I've got that wrong

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70uSJg0s-NdP2WsNTU:-O75DIU81ZB2z5og5jL8:b-u5ovsu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I mainly meant the comment for the naming of this field, but what you ask depends on what you mean by "stage has been completed". The log entry tells you the *current* stage. From that, you can infer that it successfully transitioned out of a *previous* stage.

@renjiezh correct me if I've got that wrong
</blockquote></details>

Sanjay is correct.
The log entry tells either 
1) a transition happens. Which means success for the previous stage.
2) a new attempt for a stage starts. 
3) If the attempt fails, a failure log will be created. If it succeeds, (1) is created..

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 7 of 11 files reviewed, 5 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 76 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70TnJr3ArF7llxe72L:-O75w9Yw6naMMGej-lO5:b-yrm876) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L76)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I keep track of the last row written. If a table gets written to, but the table that keeps track of what has been written fails, then there will be some duplicates then. BigQuery doesn't keep track of duplicates so you could just filter out duplicates in Looker.
</blockquote></details>

Okay, I think that's probably fine for now. In the longer term we may need to look at some kind of batch loading scheme so we can prevent duplicates.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 203 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O75wVJO24L7HM0DOwKm:-O75wVJO24L7HM0DOwKn:b4wfiyk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/terraform/gcloud/modules/kingdom/main.tf#L203)):*
> ```HCL
> }
> 
> resource "google_bigquery_table" "computation_participant_stages" {
> ```

As an example, can you provide the set of rows that would be written to this table for a single successful computation?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 1 of 15 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70tQ-l2WnZeXS-Lt96:-O9ucx6F6ApjsMUdmUen:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L97)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

COMPUTATION view should not include non-failure log entries of the ComputationParticipant, meaning it should only be using the DEFAULT view of Computation (see other comment). Now that we can query inside of protobuf messages, you can actually have a clause that conditions on whether it's an error log entry.

There are a lot of these and the Duchy doesn't need them. It only needs to know information on whether there's a failure.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70uSJg0s-NdP2WsNTU:-O9uQL9bE5mXaj5ReAfM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L60)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Sanjay is correct.
The log entry tells either 
1) a transition happens. Which means success for the previous stage.
2) a new attempt for a stage starts. 
3) If the attempt fails, a failure log will be created. If it succeeds, (1) is created..
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70swuHA1jYhOvJFgRk:-O9ucxsB7IzcsOutis9Y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Create a separate view for including these. We do not want to include them in ComputationParticipant reads by default.
</blockquote></details>

Done.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 203 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O75wVJO24L7HM0DOwKm:-O9udiBf4NUO0IRcdJmw:bfvl7w5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/terraform/gcloud/modules/kingdom/main.tf#L203)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

As an example, can you provide the set of rows that would be written to this table for a single successful computation?
</blockquote></details>

Here are examples from a unit test.



_Code snippet:_
```HCL
measurement_consumer_id: "AAAAAAAABNI"
measurement_id: "AAAAAAAAAHs"
computation_id: "AAAAAAAAAHw"
duchy_id: "0"
measurement_type: REACH_AND_FREQUENCY
result: SUCCEEDED
stage_name: "stage_one"
stage_start_time {
  seconds: 100
}
completion_duration_seconds: 200
completion_duration_seconds_squared: 40000

measurement_consumer_id: "AAAAAAAABNI"
measurement_id: "AAAAAAAAAHs"
computation_id: "AAAAAAAAAHw"
duchy_id: "0"
measurement_type: REACH_AND_FREQUENCY
result: SUCCEEDED
stage_name: "stage_two"
stage_start_time {
  seconds: 300
}
completion_duration_seconds: 300
completion_duration_seconds_squared: 90000
```
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 240 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70VpVs0lVydefJ-XkD:-O9uQJ-16MtAgVasl4tk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/terraform/gcloud/modules/kingdom/main.tf#L240)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This should always be REACH or REACH_AND_FREQUENCY?
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 3 of 15 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O9vflhm5Cfkaiy3Dt6X:-O9vflhm5Cfkaiy3Dt6Y:bgyv7ow) (no related file):*
As before, split the Kingdom changes to a separate PR.

___
___
*[`src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O70swuHA1jYhOvJFgRk:-O9veQyv9liynDn8UHEP:b-spfo6o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f787b0f69955fe4da0a58295a6f93b5ed69e6011/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L60)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I had meant a separate view for Computations, not for Measurements. Alternatively, have a separate view for Measurements but move this field up to the Measurement level where it's not split by participant.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto` line 61 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O9vdN9J93yRfVcESHwy:-O9vdN9K9TAV36dR6eNG:bnvuphr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e13e289a1bf9dca97a58905557746d043d68f8b7/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L61)):*
> ```proto
>   DuchyMeasurementLogEntry failure_log_entry = 8;
>   // One log entry for each stage.
>   repeated DuchyMeasurementLogEntry log_entry_per_stage_unique = 12;
> ```

This should just be all the log entries denormalized. Do any filtering on these on the client.



_Code quote:_
```proto
log_entry_per_stage_unique
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 41 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O9vf8Pl52OcfkRgrM5h:-O9vf8Pl52OcfkRgrM5i:batft3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e13e289a1bf9dca97a58905557746d043d68f8b7/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L41)):*
> ```proto
> 
>     // Alternative view for computation that includes ComputationParticipants
>     // and additional log entries for ComputationParticipants, but does not
> ```

No. The Measurement view should only control which fields on Measurement are populated, not the fields of the denormalized Computations within Measurement.



_Code quote:_
```proto
and additional log entries for ComputationParticipants
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 1 of 16 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O9vflhm5Cfkaiy3Dt6X:-OATw2dVAva2aovx4l4K:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As before, split the Kingdom changes to a separate PR.
</blockquote></details>

Done.

___
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 41 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O9vf8Pl52OcfkRgrM5h:-OATuMHx-qNgZM-yvcFl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48dddcbf94bdb25b5a46608bf367375138d233fb/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No. The Measurement view should only control which fields on Measurement are populated, not the fields of the denormalized Computations within Measurement.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto` line 61 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O9vdN9J93yRfVcESHwy:-OATuO9j6Q6W2khFknyV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48dddcbf94bdb25b5a46608bf367375138d233fb/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should just be all the log entries denormalized. Do any filtering on these on the client.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r4, 5 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 8 of 16 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O9vflhm5Cfkaiy3Dt6X:-OAUB0Ic-leC-oSLbltz:b-700yue) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still seeing diffs in this PR, e.g. to MeasurementReader/StreamMeasurement.

___
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 568 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-OAU9ffn85gTqXk1kbMz:-OAU9ffn85gTqXk1kbN-:bv3xgcz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/048cdc9af21de438d028d336bae31f26a5855874/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L568)):*
> ```Kotlin
>                       }
> 
>                       for (i in 1 until sortedStageLogEntries.size) {
> ```

nit: this looks suspiciously like an aggregate operation. Consider if something like [`reduceTo`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/reduce-to.html), `reduce`, `fold`, etc would be clearer than handling the "previous"/"current" indices yourself. I assume what you're really primarily trying to compute here is the completion duration

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: 6 of 16 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805#-O9vflhm5Cfkaiy3Dt6X:-OAYdj5r116qbsM6v-BZ:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Still seeing diffs in this PR, e.g. to MeasurementReader/StreamMeasurement.
</blockquote></details>

Done.

___

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 15 files at r4, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 15 files at r4, 4 of 10 files at r5, 6 of 8 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @renjiezh)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1805)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
