### PR TITLE
fix!: Update maximum and default page_size for ListRequisitions and ListEventGroups

### LINKED ISSUE #1915: Maximum size for ListRequisitions, ListEventGroups results in response larger than gRPC limit
The default gRPC response size limit is 4 MiB. The current maximum size for both of these methods is 1000.

- [x] https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/219
- [x] https://github.com/world-federation-of-advertisers/bazel-registry/pull/70 
- [ ] #1916

### PR DESCRIPTION
**Pull request by SanjayVas**
Closes #1915

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1916)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1916)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt` line 453 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1916#-OBfrSbK00Sr_JBPPP-p:-OBfrSbK00Sr_JBPPP-q:b-o7xz24) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b4f4475db7c31502099521fc4c7f5b5d394e5ad/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L453)):*
> ```Kotlin
> 
>   companion object {
>     private const val DEFAULT_PAGE_SIZE = 10
> ```

shouldn't these ideally come from a config or a flag so that the market can define it based on the infra they have deployed/tuned?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1916)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt` line 453 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1916#-OBfrSbK00Sr_JBPPP-p:-OBftt2D76pftSPRrNaE:bmofibh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b4f4475db7c31502099521fc4c7f5b5d394e5ad/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L453)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't these ideally come from a config or a flag so that the market can define it based on the infra they have deployed/tuned?
</blockquote></details>

No. As stated in the Slack thread, these should be fixed and the operator should ensure that their infra can handle these within given deadlines. These haven't yet been specified, but the default deadline of 30s was chosen to be above and beyond what should ever be hit in a functioning system.

These values also need to be documented in the API definition which is inherently not configurable (see [AIP-158](https://google.aip.dev/158).

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1916)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1916)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1916)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
