### PR TITLE
Handle Duchy gRPC errors appropriately w.r.t. retryability.

### LINKED ISSUE #680: editVersion mismatch in RecordOutputBlobPath
Digging into an error that I sometimes (but not always) see popping up in the integration test. It shows up as `TRANSIENT` error in the LLv2 Mill. The source appears to be `GcpSpannerComputationsDatabaseTransactor`. Adding more logging gives the following:

```
wfa.measurement.internal.duchy.Computations RecordOutputBlobPath
WARNING: [DefaultDispatcher-worker-2 @coroutine#3852] gRPC error: UNKNOWN
java.lang.IllegalStateException: Failed to update because of editVersion mismatch.
  Token's editVersion: 1662062844075 (2022-09-01T20:07:24.075Z)
  Computations table's UpdateTime: 1662062846260 (2022-09-01T20:07:26.260354Z)
  Difference: PT2.185354S
	at org.wfanet.measurement.duchy.deploy.gcloud.spanner.computation.GcpSpannerComputationsDatabaseTransactor$runIfTokenFromLastUpdate$2.invokeSuspend(GcpSpannerComputationsDatabaseTransactor.kt:690)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### LINKED ISSUE #984: R/F Measurement result sometimes has incorrect reach value of 1
Observed in runs of the correctness test on halo-cmm-dev. This uses a [fixed dataset](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/k8s/testing/data/synthetic-labelled-events.csv) and query parameters (time, filters, etc.), and therefore should give the same result every time aside from DP noise (reach: 1296). Instead, we frequently (maybe 10% of runs?) get a reach value of 1.

From @jiayu-google:
> Ok, with vidSamplingWidth = 1, the error is not that large, Probability(observing 1296 | truth = 1) < 1e-50. So almost impossible.

## Sample

Expected:

```textproto
reach {
  value: 1296
}
frequency {
  relative_frequency_distribution {
    key: 1
    value: 0.3078817733990148
  }
  relative_frequency_distribution {
    key: 2
    value: 0.6042692939244664
  }
  relative_frequency_distribution {
    key: 3
    value: 0.031198686371100164
  }
  relative_frequency_distribution {
    key: 4
    value: 0.05008210180623974
  }
  relative_frequency_distribution {
    key: 5
    value: 0.004105090311986864
  }
  relative_frequency_distribution {
    key: 6
    value: 0.0024630541871921183
  }
}
```

Actual:

```textproto
reach {
  value: 1
}
frequency {
  relative_frequency_distribution {
    key: 1
    value: 0.0738255033557047
  }
  relative_frequency_distribution {
    key: 4
    value: 0.6510067114093959
  }
  relative_frequency_distribution {
    key: 6
    value: 0.026845637583892617
  }
  relative_frequency_distribution {
    key: 7
    value: 0.03355704697986577
  }
  relative_frequency_distribution {
    key: 8
    value: 0.21476510067114093
  }
}
```

### PR DESCRIPTION
**Pull request by SanjayVas**
* Handle gRPC errors at call sites.
* Follow gRPC guidelines for retryability based on status code.
* Mitigate write contention in `AsyncComputationControl.AdvanceComputation` method by retrying the read-modify-write operation on `ABORTED` errors.

This is intended to address failures due to editVersionMismatch errors. In tests, this would sometimes surface as R/F Measurements resulting in a reach value of 1.

Fixes #680
Fixes #984

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/ExponentialBackoff.kt` line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL-cMPD1FGGpIKni1F:-NeL-cMPD1FGGpIKni1G:bqe9jj7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/main/kotlin/org/wfanet/measurement/common/ExponentialBackoff.kt#L0)):*
Add some tests for this?
___
*[`src/main/kotlin/org/wfanet/measurement/common/ExponentialBackoff.kt` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL00izArExvO84-H5j:-NeL00izArExvO84-H5k:byphxj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/main/kotlin/org/wfanet/measurement/common/ExponentialBackoff.kt#L56)):*
> ```Kotlin
>         return initialDelay
>       }
>       return Duration.ofMillis(
> ```

If attemptNumber is one this should return the initial delay. You shouldn't need the special case above.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt` line 251 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL4iuJ3OdzVTf70urX:-NeL4iuK0mhVWrJRSiXz:bp7pma0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L251)):*
> ```Kotlin
>         }
>         .build()
>     try {
> ```

Seems like a function to encapsulate these try/catch blocks could be nice. It's repeated several times with the only difference being the message string.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt` line 286 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL5iR99QNhpKCK3dYd:-NeL5iR99QNhpKCK3dYe:b-89xblp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt#L286)):*
> ```Kotlin
>         computationReader = computationReader,
>       )
>     val token: ComputationToken =
> ```

Same thing with this block, though it is repeated less.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlService.kt` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL6Obg6rIYDZr-uJ1T:-NeL6Obg6rIYDZr-uJ1U:b-dh9neh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlService.kt#L44)):*
> ```Kotlin
>   private val computationsClient: ComputationsCoroutineStub,
>   /** Maximum number of attempts for [advanceComputation]. */
>   private val maxAdvanceAttempts: Int = Int.MAX_VALUE,
> ```

That's a big number... Maybe too big?

Maybe make this a flag?
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt` line 862 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL7Mis0n-vVYmfoDAn:-NeL7Mis0n-vVYmfoDAo:b-k725hp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt#L862)):*
> ```Kotlin
>               participantChildReferenceId = MILL_ID
>               errorMessage =
>                 """
> ```

I'm not a huge fan of doing cleanup alongside substantive changes.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/common/ExponentialBackoff.kt` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL00izArExvO84-H5j:-NeL898s22lfnrZyQ5qA:b-7pqlug) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/main/kotlin/org/wfanet/measurement/common/ExponentialBackoff.kt#L56)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

If attemptNumber is one this should return the initial delay. You shouldn't need the special case above.
</blockquote></details>

You're right that it's not necessary, just a minor optimization to skip some math/conversions. It also means that for the initial delay, you won't have any inaccuracies from floating point math.

Added a comment to clarify.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt` line 251 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL4iuJ3OdzVTf70urX:-NeLACZS316Zg0UxvlBB:b-e232mc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L251)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Seems like a function to encapsulate these try/catch blocks could be nice. It's repeated several times with the only difference being the message string.
</blockquote></details>

It's intentionally duplicated as each call in each context may have different conditions. For example, you may want to immediately retry UNAVAILABLE and DEADLINE_EXCEEDED for certain idempotent methods. It just happens to be that right now we use the same simple condition everywhere.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt` line 286 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL5iR99QNhpKCK3dYd:-NeLAnc--RewiqM2LPCF:b-4rrsig) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt#L286)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Same thing with this block, though it is repeated less.
</blockquote></details>

It's based on what each specific writer throws. The same exception also need not always result in the same status code. For example, a ComputationNotFoundException should result in a FAILED_PRECONDITION instead if it's not the subject resource of the operation.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlService.kt` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL6Obg6rIYDZr-uJ1T:-NeLBQel-DcAJXerzWsI:b-wp1jvz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlService.kt#L44)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

That's a big number... Maybe too big?

Maybe make this a flag?
</blockquote></details>

This is intentionally defaulted to unlimited retries (this is also the default for the [Kotlin Flow retry](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/retry.html) extension). Every RPC should have a deadline, so the default is just retrying until we hit the deadline.

I'll add flags to the server to make it configurable.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt` line 862 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL7Mis0n-vVYmfoDAn:-NeLC2wWEWbbzQBmoUtS:by1hmm5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt#L862)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I'm not a huge fan of doing cleanup alongside substantive changes.
</blockquote></details>

The actual string value changed, so this wasn't just reformatting to a raw string.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224)* status: 31 of 32 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @Marco-Premier)

___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt` line 862 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL7Mis0n-vVYmfoDAn:-NeLD1IzB5Kb5Qoe-STx:b-6quurm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt#L862)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The actual string value changed, so this wasn't just reformatting to a raw string.
</blockquote></details>

To clarify, the formatting would have needed to change slightly regardless since the first line no longer needed to be wrapped to fit in 100 cols.

If I were actually cleaning this up, I'd update the tests to not assert on the full exact error message strings since we should have the flexibility to change those a bit without having to update the test every time.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/ExponentialBackoff.kt` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL00izArExvO84-H5j:-NeP9xZ4-tYodGoYIkli:bjv29ck) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/main/kotlin/org/wfanet/measurement/common/ExponentialBackoff.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You're right that it's not necessary, just a minor optimization to skip some math/conversions. It also means that for the initial delay, you won't have any inaccuracies from floating point math.

Added a comment to clarify.
</blockquote></details>

Thanks for adding the comment.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt` line 862 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL7Mis0n-vVYmfoDAn:-NePA2me797KXtitvtQc:bfszeg8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt#L862)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify, the formatting would have needed to change slightly regardless since the first line no longer needed to be wrapped to fit in 100 cols.

If I were actually cleaning this up, I'd update the tests to not assert on the full exact error message strings since we should have the flexibility to change those a bit without having to update the test every time.
</blockquote></details>

Sorry, missed the substantive change.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224)* status: 28 of 35 files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/common/ExponentialBackoff.kt` line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL-cMPD1FGGpIKni1F:-NePlEzNDxPCUNZk3g_K:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/main/kotlin/org/wfanet/measurement/common/ExponentialBackoff.kt#L)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Add some tests for this?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlService.kt` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeL6Obg6rIYDZr-uJ1T:-NePlHWSDNr1p4MalA9R:b5muw3i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86fed3410fb6f8c2a762328b0b772e347f575544/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlService.kt#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is intentionally defaulted to unlimited retries (this is also the default for the [Kotlin Flow retry](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/retry.html) extension). Every RPC should have a deadline, so the default is just retrying until we hit the deadline.

I'll add flags to the server to make it configurable.
</blockquote></details>

Done.

The better example would have been Spanner, which does unlimited retries on ABORTED until the deadline is reached.

**Comment by SanjayVas** [comment]
Swapped external reviewer to @YuhongWang-Amazon who is back next week and may have more context.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @YuhongWang-Amazon)

**Review by YuhongWang-Amazon — CHANGES_REQUESTED** [review]
> Reviewed 28 of 32 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/DuchyInternalException.kt` line 122 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeceuJOB6t4Np4fxAUY:-NeceuJPE__y8rImcFiB:bthdo04) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f0ba9f62985a66ba3a78863fabfdcd12431ee6b0/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/DuchyInternalException.kt#L122)):*
> ```Kotlin
>         "computation_id" to computationId.toString(),
>         "version" to version.toString(),
>         "token_version" to tokenVersion.toString()
> ```

I had to look at the usage to figure out that `version` refers to the local token version and `token_version` refers to the remote one.
Would it be better if renaming the `token_version` to `remote_token_version`?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224)* status: all files reviewed, 2 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/DuchyInternalException.kt` line 122 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224#-NeceuJOB6t4Np4fxAUY:-Necp6bTDfSkr93ZhfDf:b-ij2qdh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f0ba9f62985a66ba3a78863fabfdcd12431ee6b0/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/DuchyInternalException.kt#L122)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

I had to look at the usage to figure out that `version` refers to the local token version and `token_version` refers to the remote one.
Would it be better if renaming the `token_version` to `remote_token_version`?
</blockquote></details>

"Token" already implies remote. A token is something passed from the caller.

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @YuhongWang-Amazon and @kungfucraig from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
