### PR TITLE
Add enabledHmssMeasurementConsumers into kingdom config

### PR DESCRIPTION
**Pull request by renjiezh**
Also merged two HMSS feature flags.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto` line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688#-O1Ypp9X1mOIwFEoDDDs:-O1Ypp9X1mOIwFEoDDDt:b8pz9tz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7aabcecc71e12a08bbe0dd27b5d99615886b5252/src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto#L47)):*
> ```proto
>   // List of MeasurementConsumer names who force to enable HMSS protocol
>   // regardless the feature flags.
>   repeated string enabled_measurement_consumers = 3;
> ```

This should be a flag next to `--enable-hmss` rather than in the ProtocolConfig. That way it's obvious how the two flags interact, or why one might see the HMSS protocol used despite `--enable-hmss` being false.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto` line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688#-O1Ypp9X1mOIwFEoDDDs:-O1YuXoL0698o-EiTaAW:bffrk2q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7aabcecc71e12a08bbe0dd27b5d99615886b5252/src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be a flag next to `--enable-hmss` rather than in the ProtocolConfig. That way it's obvious how the two flags interact, or why one might see the HMSS protocol used despite `--enable-hmss` being false.
</blockquote></details>

I see. It look clearer.  In this case, it is set by command line arguments instead of adding these value in config file.
it will be like:
```
--enable-hmss=false
--enabled_measurement_consumer measurememtConsumers/123abc1
--enabled_measurement_consumer measurememtConsumers/123abc2
```
The user needs to updates the k8s yml and redeploy it. Does it work better considering origin's practice?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto` line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688#-O1Ypp9X1mOIwFEoDDDs:-O1Z9JOT2NXN0m4tPNOe:b-jwu5yc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7aabcecc71e12a08bbe0dd27b5d99615886b5252/src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto#L47)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I see. It look clearer.  In this case, it is set by command line arguments instead of adding these value in config file.
it will be like:
```
--enable-hmss=false
--enabled_measurement_consumer measurememtConsumers/123abc1
--enabled_measurement_consumer measurememtConsumers/123abc2
```
The user needs to updates the k8s yml and redeploy it. Does it work better considering origin's practice?
</blockquote></details>

You have to update the K8s objects anyway in order to pick up configmap updates, at least if you're using Kustomize the way we recommend. If you're using non-hashed configmaps, then you at least need to restart your deployments.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto` line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688#-O1Ypp9X1mOIwFEoDDDs:-O1rdwMa0WqPGzAmu0IF:b-4h6pu1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7aabcecc71e12a08bbe0dd27b5d99615886b5252/src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You have to update the K8s objects anyway in order to pick up configmap updates, at least if you're using Kustomize the way we recommend. If you're using non-hashed configmaps, then you at least need to restart your deployments.
</blockquote></details>

+1 for having this next to the general "enabled" flag. This will be deleted once HMSS is fully launched.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto` line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688#-O1Ypp9X1mOIwFEoDDDs:-O1xHcLMAU7l9yGZAmiQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7aabcecc71e12a08bbe0dd27b5d99615886b5252/src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto#L47)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

+1 for having this next to the general "enabled" flag. This will be deleted once HMSS is fully launched.
</blockquote></details>

Done.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1688)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
