### PR TITLE
Create EventTemplate and EventField data classes

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445)

### CODE REVIEW

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventField.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445#-Mw8n1s63OQzXhQRHwmf:-Mw8n1s63OQzXhQRHwmg:b49i58c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/42b3f65039e2f868c807f4a8ebc73cac4ebbd490/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventField.kt#L19)):*
> ```Kotlin
> import com.google.protobuf.Descriptors
> 
> data class EventField(val descriptor: Descriptors.Descriptor) {
> ```

It could be good to add an `init { ... } ` block to verify that the descriptor has the `EventAnnotations.eventField` annotation. I'd rather it throw on initialization instead of when someone tries to access one of the fields.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventField.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445#-Mw8mv1T631qJUIGUuX2:-Mw8mv1UBnbS27ON7mht:b-jbi3mi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/42b3f65039e2f868c807f4a8ebc73cac4ebbd490/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventField.kt#L22)):*
> ```Kotlin
>   val displayName: String by lazy {
>     descriptor.options.getExtension(EventAnnotations.eventField).displayName
>   }
> ```

Can you add a line of whitespace between fields so that it's a little less squished?
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplate.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445#-Mw8ne_864zSnrJotokZ:-Mw8ne_864zSnrJotok_:bcjulyx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/42b3f65039e2f868c807f4a8ebc73cac4ebbd490/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplate.kt#L19)):*
> ```Kotlin
> import com.google.protobuf.Descriptors
> 
> data class EventTemplate(val descriptor: Descriptors.Descriptor) {
> ```

Same comments for this class as in the previous file about whitespace between fields and an `init` block.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplate.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445#-Mw8omINDWuIsjPi-FuZ:-Mw8omINDWuIsjPi-Fu_:bm3r9cx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/42b3f65039e2f868c807f4a8ebc73cac4ebbd490/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplate.kt#L27)):*
> ```Kotlin
>   }
>   val fields: List<EventField> by lazy {
>     descriptor.fields.map { field -> EventField(field.messageType) }
> ```

This seems to be making the assumption that event templates will only have fields that are formal "event fields", meaning that the fields are messages annotated with `EventAnnotations.eventField`. I think we should be a little more cautious, and check that `field.type == Type.MESSAGE` and that `field.messageType` has the expected annotation.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445)* status: all files reviewed, 6 unresolved discussions (waiting on @chipingyeh)

___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventFieldTest.kt, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445#-MwDIW2L3x7BawwpYLBy:-MwDIW2L3x7BawwpYLBz:bu5ipfr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/42b3f65039e2f868c807f4a8ebc73cac4ebbd490/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventFieldTest.kt#L24)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> class EventFieldTest {
> ```

to Stephen's early points, can you add the bad cases where someone pass in the wrong kind of descriptors?
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTest.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445#-MwDIdTzB9zG4JRzA_Mm:-MwDIdTzB9zG4JRzA_Mn:b-1rb85) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/42b3f65039e2f868c807f4a8ebc73cac4ebbd490/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTest.kt#L26)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> class EventTemplateTest {
> ```

ditto on the negative tests

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventField.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445#-Mw8n1s63OQzXhQRHwmf:-Mw9eH3y7qsZz48mTsPK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/42b3f65039e2f868c807f4a8ebc73cac4ebbd490/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventField.kt#L19)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

It could be good to add an `init { ... } ` block to verify that the descriptor has the `EventAnnotations.eventField` annotation. I'd rather it throw on initialization instead of when someone tries to access one of the fields.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventField.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445#-Mw8mv1T631qJUIGUuX2:-Mw9_osS8pTMBJHU7MRn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/42b3f65039e2f868c807f4a8ebc73cac4ebbd490/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventField.kt#L22)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Can you add a line of whitespace between fields so that it's a little less squished?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplate.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445#-Mw8ne_864zSnrJotokZ:-Mw9eICE8cpbtMaPWXpf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/42b3f65039e2f868c807f4a8ebc73cac4ebbd490/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplate.kt#L19)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Same comments for this class as in the previous file about whitespace between fields and an `init` block.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplate.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445#-Mw8omINDWuIsjPi-FuZ:-MwDYAHz90wvSvCrU3dd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/42b3f65039e2f868c807f4a8ebc73cac4ebbd490/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplate.kt#L27)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

This seems to be making the assumption that event templates will only have fields that are formal "event fields", meaning that the fields are messages annotated with `EventAnnotations.eventField`. I think we should be a little more cautious, and check that `field.type == Type.MESSAGE` and that `field.messageType` has the expected annotation.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventFieldTest.kt, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445#-MwDIW2L3x7BawwpYLBy:-MwDSA1_7vCTOAdyLIvp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/42b3f65039e2f868c807f4a8ebc73cac4ebbd490/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventFieldTest.kt#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

to Stephen's early points, can you add the bad cases where someone pass in the wrong kind of descriptors?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTest.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445#-MwDIdTzB9zG4JRzA_Mm:-MwDS9dsEflPXg21ETbM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/42b3f65039e2f868c807f4a8ebc73cac4ebbd490/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTest.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto on the negative tests
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @robinsons and @stevenwarejones)

**Review by robinsons — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Pull request merged**
