### PR TITLE
Update ConfigMap example in the Local Kubernetes Deployment documentation

### PR DESCRIPTION
**Pull request by iverson52000**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647)

### CODE REVIEW

**Review by jcorilla — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647#-:-N8QabQRD1R-x0XbleSC:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @duliomatos1, @matthewclegg, and @SanjayVas)

**Review by jcorilla — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647#-:-N8QabQRD1R-x0XbleSC:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @duliomatos1, @matthewclegg, and @SanjayVas)

**Review by matthewclegg — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @iverson52000)

___
*[`src/main/k8s/local/README.md` line 6 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647#-N8QyKZg42zOp7K2ZF5f:-N8QicOCDDlvpl1eUam9:bapvvxc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ef5ed96ff0cf50b31933b37c42615bb8c19a659/src/main/k8s/local/README.md#L6)):*
> ```Markdown
> [KiND](https://kind.sigs.k8s.io/).
> 
> This assumes that you have `kubectl` installed and configured to point to a local KiND cluster. You should have some
> ```

nit: keep wrapped to 80 cols

There's a Markdown formatter available to Googlers that makes this easy.
___
*[`src/main/k8s/local/README.md` line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647#-N8QysRf6ZC6BGMG2iXf:-N8QysRf6ZC6BGMG2iXg:b-9ox6ao) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ef5ed96ff0cf50b31933b37c42615bb8c19a659/src/main/k8s/local/README.md#L76)):*
> ```Markdown
> Create the file `authority_key_identifier_to_principal_map.textproto` with the content below, substituting the
> appropriate resource names. The AKIDs come from the EDP certificates in [secretfiles](../testing/secretfiles). The order
> of the entries follows the order of the EDP certificates in the secretfiles folder. For example, the first entry is
> ```

nit: EDP root certificates in lexicographic order (since order of files in a directory is technically undefined and is an artifact of whatever tool you use to visualize the contents)

More accurate would be to state that these come from the testing EDP root certificates, and are in order from EDP1 through EDP6.



_Code quote:_
```Markdown
of the entries follows the order of the EDP certificates in the secretfiles folde
```
___
*[`src/main/k8s/local/README.md` line 108 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647#-N8QzfFOB_3CfWLJj_YF:-N8QzfFOB_3CfWLJj_YG:b-yp9m7i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ef5ed96ff0cf50b31933b37c42615bb8c19a659/src/main/k8s/local/README.md#L108)):*
> ```Markdown
> ```
> 
> If needed, you can use the following command to inspect the AKID of each certificate. The byte literals in protobuf text
> ```

nit: define the AKID acronym above where it's first mentioned. Then you can just state here that you can use the OpenSSL CLI to view the AKID of a certificate. Finally, just indicate that as a reminder, byte literals in protobuf text format can be represented in hex by escaping with `\x`.

Basically, we want to make the advice general when possible.



_Code quote:_
```Markdown
If needed, you can use the following command to inspect the AKID of each certificate. The byte literals in protobuf text
format are two hex digits of the Authority Key Identifier output from this command preceded by `\x`
```
___
*[`src/main/k8s/local/README.md` line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647#-N8R-oQ_3dKeRiYYmPtO:-N8R-oQ_3dKeRiYYmPtP:by7sqsv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ef5ed96ff0cf50b31933b37c42615bb8c19a659/src/main/k8s/local/README.md#L111)):*
> ```Markdown
> format are two hex digits of the Authority Key Identifier output from this command preceded by `\x`
> 
> ```
> ```

nit: specify language in this code fence (i.e. `shell`)

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647)* status: all files reviewed, 5 unresolved discussions (waiting on @duliomatos1 and @iverson52000)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647#-N8R02jM5O3pPs2tVNOm:-N8R02jM5O3pPs2tVNOn:bwfrenl) (no related file):*
nit: be more specific in the PR description that you're updating this for #643,

___

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000)

**Review by iverson52000 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Pull request merged**
