### PR TITLE
refactor: Copy the dp consistency folder from the WFA experimental repository.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1757)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1757)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @ple13)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1757#-O4HN2IdDOWnqQo6BnAK:-O4HN2IdDOWnqQo6BnAL:bky679) (no related file):*
Did you mean to put this under the experimental/ tree in this repo? Otherwise this needs to follow the general cross-company review policy. Even under the experimental/ tree, this should still follow code style for this repo. This means using Bazel and putting  the python code under src/main/python or src/test/python

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1757#-O4HN3ns6jDO8SSDTVsM:-O4HN3ns6jDO8SSDTVsN:b-kjw6cb) (no related file):*
Normally we handle repo imports using `git-filter-repo` to remap the paths so that we can bring in the entire commit history.

___

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1757)* status: 0 of 26 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1757#-O4HN2IdDOWnqQo6BnAK:-O4HVwsW2xcf6ma-fl8X:b-lfgfff) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Did you mean to put this under the experimental/ tree in this repo? Otherwise this needs to follow the general cross-company review policy. Even under the experimental/ tree, this should still follow code style for this repo. This means using Bazel and putting  the python code under src/main/python or src/test/python
</blockquote></details>

Yeah, I'll put it under the experimental/ tree and will update the tree structure to have src/main/python and src/test/python. The files in the source repo do not have the license header and the lint checks fail. I'm thinking about adding the licence headers, and formating the files before copying them. WDYT?

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1757#-O4HN3ns6jDO8SSDTVsM:-O4HWYf19OPxUe-y5wi2:bxcjti5) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Normally we handle repo imports using `git-filter-repo` to remap the paths so that we can bring in the entire commit history.
</blockquote></details>

Thanks. I'm looking at this tool now.

___

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1757)* status: 0 of 26 files reviewed, 2 unresolved discussions (waiting on @ple13)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1757#-O4HN3ns6jDO8SSDTVsM:-O4HWr6OAcVl86n-kfAG:b-oxmlbm) (no related file):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Thanks. I'm looking at this tool now.
</blockquote></details>

This is not strictly necessary if we don't care about having the history. You'll need someone like me with admin access to merge the individual commits, as the repo configuration normally only allows squash commits.

For the PX repo import, I believe my process was to rewrite history in a separate branch in the source repo and then import those commits. The command from my history is 

```shell
git-filter-repo --paths-from-file ../panel-exchange-paths.txt --path-rename docs:docs/panelmatch --path-rename src/main/terraform:src/main/terraform/panel-match --replace-message ../panel-exchange-message-replacements.txt
```

panel-exchange-paths.txt contained the paths I wanted to include. panel-exchange-message-replacements.txt contained replacement directives for references (e.g. rewriting `#123` to `source-repo-owner/source-repo-name#123`)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1757#-O4HN2IdDOWnqQo6BnAK:-O4HXq6U-k0PrxGcCR5c:been3m7) (no related file):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Yeah, I'll put it under the experimental/ tree and will update the tree structure to have src/main/python and src/test/python. The files in the source repo do not have the license header and the lint checks fail. I'm thinking about adding the licence headers, and formating the files before copying them. WDYT?
</blockquote></details>

Yes, you'll want to clean everything up in the source repo before you import it here.

___

**Pull request closed without merging**
