### PR TITLE
Add Grafana

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737)

### CODE REVIEW

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737)* status: 0 of 12 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NFv3YvHBMnDmxy_YMWb:-NFv3YvHBMnDmxy_YMWc:b-tw5u9h) (no related file):*
Adding example dashboard and alerting configuration file for provisioning in another PR.

___

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737)* status: 5 of 12 files reviewed, 6 unresolved discussions (waiting on @tristanvuong2021)

___
*[`docs/gke/metrics-deployment.md` line 257 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NG48s3e-CF3b__M6xJU:-NG48s3e-CF3b__M6xJV:brabld3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4629b3ae3893f91ae8891b8ef6aff1b7bdef837f/docs/gke/metrics-deployment.md#L257)):*
> ```Markdown
> ## Grafana
> 
> Grafana has some core configuration settings. The settings can be found in
> ```

Reference the configmap rather than the .cue file. One big benefit to using a ConfigMap is that it can be updated after-the-fact instead of having to edit the .cue file.



_Code quote:_
```Markdown
Grafana has some core configuration settings. The settings can be found in
[`grafana.cue`](../../src/main/k8s/grafana.cue) under `grafana.ini`. Parts of
```
___
*[`src/main/k8s/base.cue` line 181 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NG45INn1PyONLWvgydQ:-NG45INn1PyONLWvgydR:b-ssvphr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4629b3ae3893f91ae8891b8ef6aff1b7bdef837f/src/main/k8s/base.cue#L181)):*
> ```CUE
> 	mountPath: string
> 	readOnly?: bool
> 	subPath:   string | *""
> ```

Leave out the default for these base defs for K8s API objects and just make optional fields optional. K8s has its own default already when not set. Otherwise we'll have to maintain our own set of defaults and keep them in-sync with the K8s ones.



_Code quote:_
```CUE
| *""
```
___
*[`src/main/k8s/grafana.cue` line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NG45mBmEm0x6XtIi1jd:-NG45mBmEm0x6XtIi1je:b4xxplw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4629b3ae3893f91ae8891b8ef6aff1b7bdef837f/src/main/k8s/grafana.cue#L32)):*
> ```CUE
> 					  [security]
> 					  admin_user = user
> 					  admin_password = password
> ```

Passwords should be kept secret, no? This belongs in a Secret rather than a ConfigMap then.
___
*[`src/main/k8s/grafana.cue` line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NG47AZnCGjWTVPdGree:-NG47AZnCGjWTVPdGref:bsbu5bg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4629b3ae3893f91ae8891b8ef6aff1b7bdef837f/src/main/k8s/grafana.cue#L118)):*
> ```CUE
> 				}
> 				spec: _mounts: {
> 					"grafana-config": #ConfigMapMount & {
> ```

ConfigMaps are meant to hold multiple entries. I think this could be a single ConfigMap for /etc/grafana with a [projected volume](https://kubernetes.io/docs/concepts/storage/projected-volumes/) to put files in the right subdirectories if those paths are significant.
___
*[`src/main/k8s/dev/open_telemetry_gke.cue` line 18 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NG49APdBo6at5J-tzvJ:-NG49APdBo6at5J-tzvK:bkk8dje) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4629b3ae3893f91ae8891b8ef6aff1b7bdef837f/src/main/k8s/dev/open_telemetry_gke.cue#L18)):*
> ```CUE
> 
> // Name of K8s service account for reading from Cloud Spanner.
> #CloudSpannerServiceAccount: "cloud-spanner-reader"
> ```

I didn't see any matching sections in the guides for creating these service accounts and giving the right permissions.

If this is meant to be a single service account that gets used for both the internal API server and otel, then the Kingdom deployment guide needs to be updated to reflect that. Otherwise this should be a separate service account named for its role, e.g. "otel-collector".



_Code quote:_
```CUE
 "cloud-spanner-reader"
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737)* status: 1 of 13 files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`docs/gke/metrics-deployment.md` line 257 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NG48s3e-CF3b__M6xJU:-NG4M-8a2JQQb_oOdDWB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4629b3ae3893f91ae8891b8ef6aff1b7bdef837f/docs/gke/metrics-deployment.md#L257)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Reference the configmap rather than the .cue file. One big benefit to using a ConfigMap is that it can be updated after-the-fact instead of having to edit the .cue file.
</blockquote></details>

Done.
___
*[`src/main/k8s/base.cue` line 181 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NG45INn1PyONLWvgydQ:-NG4M6J_Bfv6unQqQzFy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4629b3ae3893f91ae8891b8ef6aff1b7bdef837f/src/main/k8s/base.cue#L181)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Leave out the default for these base defs for K8s API objects and just make optional fields optional. K8s has its own default already when not set. Otherwise we'll have to maintain our own set of defaults and keep them in-sync with the K8s ones.
</blockquote></details>

Done.
___
*[`src/main/k8s/grafana.cue` line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NG45mBmEm0x6XtIi1jd:-NGIsu1K6fzBCxtOa-Pd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4629b3ae3893f91ae8891b8ef6aff1b7bdef837f/src/main/k8s/grafana.cue#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Passwords should be kept secret, no? This belongs in a Secret rather than a ConfigMap then.
</blockquote></details>

Done.
___
*[`src/main/k8s/grafana.cue` line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NG47AZnCGjWTVPdGree:-NG4M8kkDLyvMIOJhmam:b-x8rk6c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4629b3ae3893f91ae8891b8ef6aff1b7bdef837f/src/main/k8s/grafana.cue#L118)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

ConfigMaps are meant to hold multiple entries. I think this could be a single ConfigMap for /etc/grafana with a [projected volume](https://kubernetes.io/docs/concepts/storage/projected-volumes/) to put files in the right subdirectories if those paths are significant.
</blockquote></details>

Projected volume doesn't seem like the right solution, but I did discover config map volume source has an items array, which I used.
___
*[`src/main/k8s/dev/open_telemetry_gke.cue` line 18 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NG49APdBo6at5J-tzvJ:-NGIZd3AC5oBsu7jtF3U:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4629b3ae3893f91ae8891b8ef6aff1b7bdef837f/src/main/k8s/dev/open_telemetry_gke.cue#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I didn't see any matching sections in the guides for creating these service accounts and giving the right permissions.

If this is meant to be a single service account that gets used for both the internal API server and otel, then the Kingdom deployment guide needs to be updated to reflect that. Otherwise this should be a separate service account named for its role, e.g. "otel-collector".
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/grafana.cue` line 107 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NGJaJyR1EMZcSHeSTIp:-NGN6oYE2DeL-j88xEeJ:b-wo7vd4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/87a1a0878593db756cc3aaefa26cfda515c345e3/src/main/k8s/grafana.cue#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you not just mount this at `/etc/grafana`, since the secret only contains `grafana.ini`?
</blockquote></details>

I will add a comment, but /etc/grafana is an existing directory and there is a required file in there. If I wanted to do a single configmap, I could recreate the file and add it to the configmap.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737)* status: all files reviewed, 1 unresolved discussion

___
*[`src/main/k8s/grafana.cue` line 107 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NGJaJyR1EMZcSHeSTIp:-NGNS3he-2mgR--Vzfdi:b-t5y9xf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/87a1a0878593db756cc3aaefa26cfda515c345e3/src/main/k8s/grafana.cue#L107)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I will add a comment, but /etc/grafana is an existing directory and there is a required file in there. If I wanted to do a single configmap, I could recreate the file and add it to the configmap.
</blockquote></details>

Ah, gotcha. No, this is fine if that directory already exists in the image and has things in it.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1, 5 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/k8s/base.cue` line 393 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NGO7Jp71aa2J4A8s94B:-NGO7Jp71aa2J4A8s94C:bffegm3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c240e385d412c93603d2e559439b9dcd7aaa07c0/src/main/k8s/base.cue#L393)):*
> ```CUE
> #Deployment: {
> 	_name:        string
> 	_secretName?: string
> ```

why would this be nullable?
___
*[`src/main/k8s/testing/grafana/grafana.ini` line 2 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NGO7npJ3qct_RmAQNSl:-NGO7npJ3qct_RmAQNSm:b-candfu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c240e385d412c93603d2e559439b9dcd7aaa07c0/src/main/k8s/testing/grafana/grafana.ini#L2)):*
> ```INI
> [security]
> admin_user = user
> ```

shouldn't we be using env vars here? https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737)* status: 5 of 14 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/k8s/base.cue` line 393 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NGO7Jp71aa2J4A8s94B:-NGOZhquAvNZzicnjrcN:b-bbtata) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c240e385d412c93603d2e559439b9dcd7aaa07c0/src/main/k8s/base.cue#L393)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why would this be nullable?
</blockquote></details>

There is one deployment for gke, prometheus-frontend, I added where I am not using a secret volume.
___
*[`src/main/k8s/testing/grafana/grafana.ini` line 2 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/737#-NGO7npJ3qct_RmAQNSl:-NGOZgWR89cSpU3Coolg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c240e385d412c93603d2e559439b9dcd7aaa07c0/src/main/k8s/testing/grafana/grafana.ini#L2)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't we be using env vars here? https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
</blockquote></details>

Done.

**Pull request merged**
