### PR TITLE
Fix api-linter errors in system API.

### PR DESCRIPTION
**Pull request by SanjayVas**
This includes a breaking change to the Kingdom internal API to address inconsistencies in StreamMeasurements filtration.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1074)

**Comment by SanjayVas** [comment]
Depends on #1073

**Review by Marco-Premier — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1074)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation_log_entry.proto` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1074#-NYwK2Q87o-DSIP8pPX2:-NYwK2Q87o-DSIP8pPX3:b5h097f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6958435dca3e064c8de8d0ca8b66d215bdfdf1dd/src/main/proto/wfa/measurement/system/v1alpha/computation_log_entry.proto#L40)):*
> ```proto
> 
>   // Resource name.
>   string name = 1;
> ```

Shouldn't this be marked as ```OUTPUT_ONLY```?



_Code quote:_
```proto
string name = 1;
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1074)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation_log_entry.proto` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1074#-NYwK2Q87o-DSIP8pPX2:-NYyywbF8mF7PcrdmggZ:bfz1f51) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5fd3fb3553a49e6bc255dfc132e171ce5d3668ef/src/main/proto/wfa/measurement/system/v1alpha/computation_log_entry.proto#L40)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Shouldn't this be marked as ```OUTPUT_ONLY```?
</blockquote></details>

Resource names fields aren't inherently output-only. Consider the [standard Update method](https://google.aip.dev/134), where the caller must specify the `name` field in the resource message.

**Review by Marco-Premier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1074)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1074)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
