### PR TITLE
Fix SyntheticDataGeneration signature.

### PR DESCRIPTION
**Pull request by SanjayVas**
* Take in a single SyntheticEventGroupSpec.
* Output labeled events with VIDs and timestamps.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1101)

**Comment by SanjayVas** [comment]
CC @kungfucraig

**Review by kungfucraig — APPROVED** [review]
I would have caught this in the initial review, but wasn't able to get to it since I was on vacation. Sorry. 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1101#-:-N_FR9EN0NXbUKHV2HHg:b-6na8bs)* status: 0 of 19 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Comment by SanjayVas** [comment]
Updated to also include timestamp, generating one event per day in the date range.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 17 of 17 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
