### PR TITLE
Migrate Kingdom/Duchy Spanner schemata to Liquibase changelog format.

### PR DESCRIPTION
**Pull request by SanjayVas**
This updates each relevant Spanner JUnit tests to use the Liquibase Java API to create the schema.

This does not update K8s deployments nor the PushSpannerSchema tool to use Liquibase.

https://rally1.rallydev.com/#/?detail=/task/632271535815&fdp=true

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 47 of 48 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/testing/Schemata.kt` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546#-N0gqhFD72SJZD-F0iuz:-N0gqhFD72SJZD-F0iv-:b-xkf307) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20b03192753201cd9269edc7569124f9c1834559/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/testing/Schemata.kt#L31)):*
> ```Kotlin
>   }
> 
>   val DUCHY_CHANGELOG_PATH: Path = getResourcePath("changelog.yaml")
> ```

When does the JVM initialize this? First reference to `Schemata`? When this class is loaded by the classloader? Should this be lazy to avoid doing I/O until necessary?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/Schemata.kt` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546#-N0gqzV8-qW8pwdCCxyy:-N0gqzV8-qW8pwdCCxyz:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/16f30aff3830f2c6dc5d9bb2e407fa51731fc6a1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/Schemata.kt#L31)):*
> ```Kotlin
>   }
> 
>   val KINGDOM_CHANGELOG_PATH: Path = getResourcePath("changelog.yaml")
> ```

Ditto
___
*[`src/main/resources/kingdom/spanner/BUILD.bazel` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546#-N0grOW71moBYLxta1mO:-N0grOW8BbS9OldVH_V_:b-tnspvq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/16f30aff3830f2c6dc5d9bb2e407fa51731fc6a1/src/main/resources/kingdom/spanner/BUILD.bazel#L15)):*
> ```Starlark
> )
> 
> # Temporary target for code paths that don't yet handle Liquibase changelogs.
> ```

Could there be a TODO referencing an issue to clean this up?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/testing/Schemata.kt` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546#-N0gqhFD72SJZD-F0iuz:-N0gvE6hCjcqjY-_CCHz:bchghif) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20b03192753201cd9269edc7569124f9c1834559/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/testing/Schemata.kt#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

When does the JVM initialize this? First reference to `Schemata`? When this class is loaded by the classloader? Should this be lazy to avoid doing I/O until necessary?
</blockquote></details>

It loads the same as Java static initialization, so it should be on first reference to `Schemata`.

Since it's in a `testing` package, I figured it was fine to load eagerly. LMK if you'd rather it be lazy.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/testing/Schemata.kt` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546#-N0gqhFD72SJZD-F0iuz:-N0h41pf3EtwSxA8qFX2:b4k2het) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20b03192753201cd9269edc7569124f9c1834559/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/testing/Schemata.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It loads the same as Java static initialization, so it should be on first reference to `Schemata`.

Since it's in a `testing` package, I figured it was fine to load eagerly. LMK if you'd rather it be lazy.
</blockquote></details>

I guess the first reference to Schemata will be to access this property so probably irrelevant if it's lazy. I'm fine with it as it is.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546)* status: 41 of 51 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546#-N1PqB1lCfk6K4dJ6cBH:-N1PqB1lCfk6K4dJ6cBI:b-h3n0hp) (no related file):*
I reverted some of the changes to K8s deployment in favor of a different approach I'm working on in a follow-up PR. The new approach uses an initContainer on the internal server deployments to do any schema updates on startup. This way, updating to a new set of images includes any schema updates automatically.

---

**Comment by SanjayVas** [comment]
Depends on https://github.com/world-federation-of-advertisers/common-jvm/pull/107

**Review by efoxepstein — APPROVED** [review]
> Reviewed 6 of 10 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 40 of 48 files at r1, 1 of 1 files at r2, 3 of 10 files at r3, 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[`src/main/resources/kingdom/spanner/create-exchange-schema.sql` line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546#-N1efEna07kwA4oT-h4n:-N1efEna07kwA4oT-h4o:b-g9atwr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c46cee5b0f35ce814e0d40ee22e4f44ac203b5a4/src/main/resources/kingdom/spanner/create-exchange-schema.sql#L42)):*
> ```TSQL
> -- JSON provides debugging value.
> 
> -- changeset efoxepstein:create-model-providers-table dbms:cloudspanner
> ```

what are all these changeset comments for?
___
*[`src/main/resources/kingdom/spanner/create-measurement-schema.sql` line 72 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546#-N1efJGMD6HNjFNDSKdr:-N1efJGMD6HNjFNDSKds:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c46cee5b0f35ce814e0d40ee22e4f44ac203b5a4/src/main/resources/kingdom/spanner/create-measurement-schema.sql#L72)):*
> ```TSQL
> 
> -- X.509 certificates used for consent signaling.
> -- changeset sanjayvas:create-certificates-table dbms:cloudspanner
> ```

ditto

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[`src/main/resources/kingdom/spanner/BUILD.bazel` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546#-N0grOW71moBYLxta1mO:-N1kE0ODER86fQpkToKS:bub99cj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/16f30aff3830f2c6dc5d9bb2e407fa51731fc6a1/src/main/resources/kingdom/spanner/BUILD.bazel#L15)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could there be a TODO referencing an issue to clean this up?
</blockquote></details>

Sorry, I thought I left a reply to this. This will be dropped in the follow-up PR that I already have mostly written.
___
*[`src/main/resources/kingdom/spanner/create-exchange-schema.sql` line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546#-N1efEna07kwA4oT-h4n:-N1kEOTG36fml0bJ7gBw:bf78g50) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c46cee5b0f35ce814e0d40ee22e4f44ac203b5a4/src/main/resources/kingdom/spanner/create-exchange-schema.sql#L42)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what are all these changeset comments for?
</blockquote></details>

This is part of the Liquibase changelog format, where a changelog consists of multiple changesets.

See [Liquibase concepts](https://docs.liquibase.com/concepts/changelogs/sql-format.html)
___
*[`src/main/resources/kingdom/spanner/create-measurement-schema.sql` line 72 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546#-N1efJGMD6HNjFNDSKdr:-N1kEipx8rcPVPjp-HH_:b-redf51) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c46cee5b0f35ce814e0d40ee22e4f44ac203b5a4/src/main/resources/kingdom/spanner/create-measurement-schema.sql#L72)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Same answer.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 40 of 48 files at r1, 1 of 1 files at r2, 3 of 10 files at r3, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/546)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

**Pull request merged**
