### PR TITLE
test: prober integration test

### PR DESCRIPTION
**Pull request by roaminggypsy**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @roaminggypsy)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel` line 203 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtnuc33vVPinIkzFhE:-OAtn7tzE4_313EhUpZW:b-i7erxv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L203)):*
> ```Starlark
>     visibility = [
>         "//src/main/kotlin/org/wfanet/measurement/integration:__subpackages__",
>         "//src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud:__subpackages__",
> ```

I don't actually see this visibility expansion being used. That is to say that that I see the label being referenced from a target here, but I don't actually see the underlying dependency being used by that target.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel` line 291 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtqHNs5L65vLN-p0bx:-OAtqHNs5L65vLN-p0by:bj62da0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L291)):*
> ```Starlark
>         "//src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer:synthetic_generator_event_query",
>         "@wfa_common_jvm//imports/java/io/opentelemetry/sdk",
>         "@wfa_common_jvm//imports/java/io/opentelemetry/sdk/testing",
> ```

Trim the dependencies. e.g. I don't see this deps used



_Code quote:_
```Starlark
        "//src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer:simulator",
        "//src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer:synthetic_generator_event_query",
        "@wfa_common_jvm//imports/java/io/opentelemetry/sdk",
        "@wfa_common_jvm//imports/java/io/opentelemetry/sdk/testing",
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt` line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtpwLq0W6ADQfok_qJ:-OAtpwLr7UyHZ-rRAZUl:basnxux) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt#L121)):*
> ```Kotlin
> 
>   @Test
>   fun `prober creates first two measurements`(): Unit = runBlocking {
> ```

It only creates ones measurement?



_Code quote:_
```Kotlin
two
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt` line 153 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtps3w5xvmku3pSDvM:-OAtps3w5xvmku3pSDvN:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt#L153)):*
> ```Kotlin
>       nextPageToken = response.nextPageToken
>     } while (nextPageToken.isNotEmpty())
>     return listOf()
> ```





_Suggestion:_
```Kotlin
emptyList()
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt` line 189 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtph3XCO8gUpy0WWBG:-OAtph3XCO8gUpy0WWBH:b-5t2inr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt#L189)):*
> ```Kotlin
>     private val DURATION_BETWEEN_MEASUREMENT: Duration = Duration.ofSeconds(10)
>     private val MEASUREMENT_LOOKBACK_DURATION = Duration.ofDays(1)
>     private val CLOCK = Clock.systemUTC()
> ```

This is not a constant
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/BUILD.bazel` line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtoLPWDV8BJ9qt4QQD:-OAtoLPXD7OVBsIQnRYm:b-53ho5c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/kingdom/batch/BUILD.bazel#L7)):*
> ```Starlark
>     "//src/main/kotlin/org/wfanet/measurement/kingdom/batch/spanner:__subpackages__",
>     "//src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common:__subpackages__",
>     "//src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud:__subpackages__",
> ```

Same here re: dependency usage
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 198 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtop9NCEfVY-D1w0yJ:-OAtop9NCEfVY-D1w0yK:b-ul46hy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L198)):*
> ```Kotlin
>   }
> 
>   private suspend fun buildDataProviderNameToEventGroup(): MutableMap<String, EventGroup> {
> ```

nit: no need to expose mutability



_Suggestion:_
```Kotlin
Map
```
___
*[`src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/BUILD.bazel` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtqTuY1QtLDO3snPG3:-OAtqTuY1QtLDO3snPG4:b5nxcj1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/BUILD.bazel#L132)):*
> ```Starlark
>     srcs = ["GCloudSpannerInProcessMeasurementSystemProberIntegrationTest.kt"],
>     deps = [
>         "//src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/testing",
> ```

Trim the dependencies. This should be exactly the set of dependencies directly referenced in the code and no more. It should definitely **not** be using the Postgres Duchy implementation, and should therefore have no postgres deps.
___
*[`src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/BUILD.bazel` line 148 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtp9-xDA8wEVyL8AFG:-OAtp9-xDA8wEVyL8AFH:bwn0d34) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/BUILD.bazel#L148)):*
> ```Starlark
> )
> 
> java_test(
> ```

Assuming this is a java_test due to transitively having native deps via Duchies, then this should have the same TODO

`# TODO(bazelbuild/rules_kotlin#1088): Use kt_jvm_test when fixed.`

**Review by roaminggypsy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887)* status: 2 of 7 files reviewed, 8 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel` line 203 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtnuc33vVPinIkzFhE:-OAy5x6b26YmebUXJ-Bv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L203)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't actually see this visibility expansion being used. That is to say that that I see the label being referenced from a target here, but I don't actually see the underlying dependency being used by that target.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel` line 291 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtqHNs5L65vLN-p0bx:-OAy7FOZ2B3L-a3sspx5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L291)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Trim the dependencies. e.g. I don't see this deps used
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt` line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtpwLq0W6ADQfok_qJ:-OAy7LZQEY9eHtyUvj9K:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt#L121)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It only creates ones measurement?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt` line 153 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtps3w5xvmku3pSDvM:-OAy7PBs3rIsV91GR97N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt#L153)):*
> ```Kotlin
>       nextPageToken = response.nextPageToken
>     } while (nextPageToken.isNotEmpty())
>     return listOf()
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt` line 189 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtph3XCO8gUpy0WWBG:-OAy7l-C1o9zYiJzayq5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt#L189)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is not a constant
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/BUILD.bazel` line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtoLPWDV8BJ9qt4QQD:-OAyHgz68aQqGirkMXgw:b-qjemuy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/main/kotlin/org/wfanet/measurement/kingdom/batch/BUILD.bazel#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here re: dependency usage
</blockquote></details>

The first one needs to stay because the integration test needs prober. Otherwise I will get

ERROR: /usr/local/google/home/lindreamdeyi/IdeaProjects/cross-media-measurement/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel:276:15: in kt_jvm_library rule //src/main/kotlin/org/wfanet/measurement/integration/common:in_process_measurement_system_prober_integration_test: target '//src/main/kotlin/org/wfanet/measurement/kingdom/batch:measurement_system_prober' is not visible from target '//src/main/kotlin/org/wfanet/measurement/integration/common:in_process_measurement_system_prober_integration_test'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /usr/local/google/home/lindreamdeyi/IdeaProjects/cross-media-measurement/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel:276:15: Analysis of target '//src/main/kotlin/org/wfanet/measurement/integration/common:in_process_measurement_system_prober_integration_test' failed
___
*[`src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/BUILD.bazel` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtqTuY1QtLDO3snPG3:-OAyB2yi3NC6aWhfWKRZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/BUILD.bazel#L132)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Trim the dependencies. This should be exactly the set of dependencies directly referenced in the code and no more. It should definitely **not** be using the Postgres Duchy implementation, and should therefore have no postgres deps.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/BUILD.bazel` line 148 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAtp9-xDA8wEVyL8AFG:-OAyB41o9DsXbXYhqc-y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7324d9e76565e1f9ca3df36de1f8922708fc0ae8/src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/BUILD.bazel#L148)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Assuming this is a java_test due to transitively having native deps via Duchies, then this should have the same TODO

`# TODO(bazelbuild/rules_kotlin#1088): Use kt_jvm_test when fixed.`
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887)* status: all files reviewed, 2 unresolved discussions (waiting on @roaminggypsy)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel` line 287 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAySjx68Up3QSF0pRyE:-OAySjx68Up3QSF0pRyF:biw8qhw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c11807d2be42b053b6cef1e9a45b12fd0932e98/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L287)):*
> ```Starlark
>         "@wfa_common_jvm//imports/java/org/junit",
>         "@wfa_common_jvm//imports/kotlin/kotlinx/coroutines:core",
>         "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common/testing",
> ```

Missing dep for Truth
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt` line 164 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887#-OAyTEzP7I5a8AJ36yM4:-OAyTEzQ31FfY3XcbOIu:b-jyj90r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c11807d2be42b053b6cef1e9a45b12fd0932e98/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt#L164)):*
> ```Kotlin
>   }
> 
>   private suspend fun getRequisitionsForMeasurement(measurementName: String): List<Requisition> {
> ```

I don't see this used anywhere

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1887)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)

**Pull request merged**
