### PR TITLE
Add config for params for Reporting V1.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This is for facilitating Alpha testing.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 3 of 15 files at r1, 2 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: 5 of 15 files reviewed, 1 unresolved discussion (waiting on @jiayu-google, @riemanli, @SanjayVas, @tristanvuong2021, and @uakyol)

___
*[`src/main/k8s/local/measurement_spec_config.textproto` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdgiGK8-aHj_x4xerDH:-NdgiGK8-aHj_x4xerDI:b-x8rwwz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/k8s/local/measurement_spec_config.textproto#L22)):*
> ```
>   vidSamplingInterval {
>     randomStart {
>       width: 256
> ```

Should this be 3 to match the old config? Similar questions for other uses of width.

I'm trying to understand the mapping between the new and the old and trying to convince myself that all of the values are still the same, and am not sure.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: 5 of 15 files reviewed, 1 unresolved discussion (waiting on @jiayu-google, @kungfucraig, @riemanli, @SanjayVas, and @uakyol)

___
*[`src/main/k8s/local/measurement_spec_config.textproto` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdgiGK8-aHj_x4xerDH:-Ndh-vlv5YIqmGBVDo0I:bychsa0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/k8s/local/measurement_spec_config.textproto#L22)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Should this be 3 to match the old config? Similar questions for other uses of width.

I'm trying to understand the mapping between the new and the old and trying to convince myself that all of the values are still the same, and am not sure.
</blockquote></details>

I am not trying to map to the old values. I am trying to map to new values.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 5 of 15 files at r1, 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @jiayu-google, @riemanli, @SanjayVas, @tristanvuong2021, and @uakyol)

___
*[`src/main/k8s/local/measurement_spec_config.textproto` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkDW05A1WpyC12uYII:-NdkDW05A1WpyC12uYIJ:bfm1sys) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/k8s/local/measurement_spec_config.textproto#L1)):*
> ```
> # proto-file: wfa/measurement/config/reporting/measurement_spec_config.proto
> ```

Let's resolve our discussion offline about the specifics for the config values.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkCR8zAhRu-zSni2BJ:-NdkCR8zAhRu-zSni2BK:brz7flw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt#L1)):*
> ```Kotlin
> // Copyright 2022 The Cross-Media Measurement Authors
> ```

Are there tests for this file?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1417 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkIHci2y0QBk3O2hJF:-NdkIHci2y0QBk3O2hJG:b-pvhsh7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1417)):*
> ```Kotlin
> 
>   private class MeasurementSpecComponentFactory(
>     private val measurementSpecConfig: MeasurementSpecConfig,
> ```

It seems like there should be some code to validate this. For example that interval start and width are defining valid subinterval of [0, 1).
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1423 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkJoh8CuAyvfF2htJq:-NdkJoh8CuAyvfF2htJr:baf6bka) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1423)):*
> ```Kotlin
>     private val DEFAULT_VID_WIDTH = 1.0f
> 
>     private val reachOnlyDirectType =
> ```

Why not embed this in the only function that uses it like you did for the other MeasurementSpec objects? Same with reachOnlyMpcType below.
___
*[`src/main/proto/wfa/measurement/config/reporting/measurement_spec_config.proto` line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkACNt0bHJrr_bWasa:-NdkACNt0bHJrr_bWasb:b-2hfldk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/proto/wfa/measurement/config/reporting/measurement_spec_config.proto#L47)):*
> ```proto
> 
>     message RandomStart {
>       int32 num_vid_buckets = 1;
> ```

Can you document this field?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @riemanli, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkCR8zAhRu-zSni2BJ:-NdkM25q7WjShtxUoqGx:b-ot21tb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Are there tests for this file?
</blockquote></details>

No automated test, just manually testing it by deploying it.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1423 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkJoh8CuAyvfF2htJq:-NdkLGE964yhwZKAqYFX:bt7smnr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1423)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why not embed this in the only function that uses it like you did for the other MeasurementSpec objects? Same with reachOnlyMpcType below.
</blockquote></details>

These will be the same for every reach measurement so I wanted to create them just once and store them.

**Review by jiayu-google — CHANGES_REQUESTED** [review]
Thank you Tristan! The structure lgtm. We haven't finalized the parameters --- please expect to have the final params and change this PR accordingly in about 2 weeks.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-:-NdkYnPl8jG14He7JTR0:b-f4rs5n)* status: 13 of 15 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @riemanli, @SanjayVas, @tristanvuong2021, and @uakyol)

___
*[`src/main/k8s/local/measurement_spec_config.textproto` line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkYIuY7OqDuFy3Doqu:-NdkYIuY7OqDuFy3Doqv:b-1s8yfj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/k8s/local/measurement_spec_config.textproto#L29)):*
> ```
> reachAndFrequencyDirect {
>   reachPrivacyParams {
>     epsilon: 0.004728
> ```

Should be 0.000207 (=reachOnlyDirect.epsilon)

I didn't make it clear in the deck, sorry. You don't have to change this value now because we haven't decided the parameters. Just leaving a note here.
___
*[`src/main/k8s/local/measurement_spec_config.textproto` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkXnqJ-ImPHjhlmGen:-NdkXnqJ-ImPHjhlmGeo:b-7bgbyl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/k8s/local/measurement_spec_config.textproto#L53)):*
> ```
>   }
>   vidSamplingInterval {
>     randomStart {
> ```

IIUC`randomStart` here randomly selects vidSamplingInterval.start from {0, 1, ..., 43}. I didn't find the implementation of `randomStart`, could you double check?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 15 files at r1, 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: 13 of 15 files reviewed, 8 unresolved discussions (waiting on @kungfucraig, @riemanli, @tristanvuong2021, and @uakyol)

___
*[`src/main/proto/wfa/measurement/config/reporting/measurement_spec_config.proto` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkXlibEVmvwDA0IjQC:-NdkXlibEVmvwDA0IjQD:b94tzk1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/proto/wfa/measurement/config/reporting/measurement_spec_config.proto#L59)):*
> ```proto
>   }
> 
>   message ReachOnlyDirect {
> ```

The Reporting system has no control over the protocol, therefore it doesn't make sense to indicate "direct" vs. "MPC" in this config.

Let's also avoid "reach-only" as that might confuse people w.r.t. the protocol as well. Just stick with "reach" vs. "reach and frequency".



_Suggestion:_
```proto
ReachSingleDataProvider
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: 10 of 15 files reviewed, 8 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @riemanli, @SanjayVas, and @uakyol)

___
*[`src/main/k8s/local/measurement_spec_config.textproto` line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkYIuY7OqDuFy3Doqu:-NdklH9NEmfpAwc3KQX7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/k8s/local/measurement_spec_config.textproto#L29)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

Should be 0.000207 (=reachOnlyDirect.epsilon)

I didn't make it clear in the deck, sorry. You don't have to change this value now because we haven't decided the parameters. Just leaving a note here.
</blockquote></details>

Done.
___
*[`src/main/k8s/local/measurement_spec_config.textproto` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkXnqJ-ImPHjhlmGen:-Ndklu9Y78USLkWGHpII:b-gl5xcp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/k8s/local/measurement_spec_config.textproto#L53)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

IIUC`randomStart` here randomly selects vidSamplingInterval.start from {0, 1, ..., 43}. I didn't find the implementation of `randomStart`, could you double check?
</blockquote></details>

It is here https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a120c3e57973db02987c1cb9a533c7d5e6db7b9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1594
___
*[`src/main/proto/wfa/measurement/config/reporting/measurement_spec_config.proto` line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkACNt0bHJrr_bWasa:-Ndklyln9EGL9Y0H1-Xx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/proto/wfa/measurement/config/reporting/measurement_spec_config.proto#L47)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you document this field?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/config/reporting/measurement_spec_config.proto` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NdkXlibEVmvwDA0IjQC:-NdklKT8DN1MJpdxfgqX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e8d452dae6b43cfa7bedf697c40e94c6e0cb65d/src/main/proto/wfa/measurement/config/reporting/measurement_spec_config.proto#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The Reporting system has no control over the protocol, therefore it doesn't make sense to indicate "direct" vs. "MPC" in this config.

Let's also avoid "reach-only" as that might confuse people w.r.t. the protocol as well. Just stick with "reach" vs. "reach and frequency".
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 15 files at r1, 1 of 6 files at r2, 1 of 5 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: all files reviewed, 9 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @riemanli, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1184 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-Ndkv5Vd2iZ0nMqOICfS:-Ndkv5Vd2iZ0nMqOICfT:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/105d06c1ecbc993779efffa4c794cf434b2033c4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1184)):*
> ```Kotlin
>     internalMetricDetails: InternalMetricDetails,
>   ): MeasurementSpec {
>     val isDirect = nonceHashes.size == 1
> ```





_Suggestion:_
```Kotlin
isSingleDataProvider
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1538 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-Ndkvjyl06fzAfhdyyV1:-Ndkvjyl06fzAfhdyyV2:bf3923e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/105d06c1ecbc993779efffa4c794cf434b2033c4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1538)):*
> ```Kotlin
>     }
> 
>     private fun DifferentialPrivacyParams.isValid(): Boolean {
> ```

Shouldn't the validation of the MeasurementSpecConfig itself happen where the flag is read rather than in the service? e.g. https://picocli.info/#_custom_validation

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: 14 of 15 files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @riemanli, @SanjayVas, @tristanvuong2021, and @uakyol)

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 2 of 4 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: all files reviewed, 5 unresolved discussions (waiting on @jiayu-google, @riemanli, @tristanvuong2021, and @uakyol)

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: all files reviewed, 2 unresolved discussions (waiting on @jiayu-google, @riemanli, @SanjayVas, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1538 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-Ndkvjyl06fzAfhdyyV1:-Ndlke9r6lUzQ4HZXSk6:b-lh19ek) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/105d06c1ecbc993779efffa4c794cf434b2033c4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1538)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't the validation of the MeasurementSpecConfig itself happen where the flag is read rather than in the service? e.g. https://picocli.info/#_custom_validation
</blockquote></details>

The service should want to validate what it is being given before using it, so maybe both?

**Review by riemanli — COMMENTED** [review]
> Reviewed 7 of 15 files at r1, 3 of 6 files at r2, 1 of 5 files at r3, 2 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: all files reviewed, 2 unresolved discussions (waiting on @jiayu-google, @SanjayVas, @tristanvuong2021, and @uakyol)

**Review by kungfucraig — COMMENTED** [review]
@jiayu-google This PR will be part of the September release, and Origin will need to pick that up and eventually provide their own config file.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-:-NdpHhFEAM-ID0kqYi0o:bnxc43h)* status: all files reviewed, 2 unresolved discussions (waiting on @jiayu-google, @SanjayVas, @tristanvuong2021, and @uakyol)

**Review by riemanli — APPROVED** [review]
> Reviewed 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: all files reviewed, 2 unresolved discussions (waiting on @jiayu-google, @SanjayVas, @tristanvuong2021, and @uakyol)

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: 11 of 19 files reviewed, 2 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @riemanli, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1184 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-Ndkv5Vd2iZ0nMqOICfS:-Ndl0Lp4EN3ztn-RcSEA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/105d06c1ecbc993779efffa4c794cf434b2033c4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1184)):*
> ```Kotlin
>     internalMetricDetails: InternalMetricDetails,
>   ): MeasurementSpec {
>     val isDirect = nonceHashes.size == 1
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1538 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-Ndkvjyl06fzAfhdyyV1:-NeF2WEJ1MdQv6xfsrVl:b-jbocux) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/105d06c1ecbc993779efffa4c794cf434b2033c4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1538)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

The service should want to validate what it is being given before using it, so maybe both?
</blockquote></details>

I moved the validation to the public server class. It calls a method from another class that actually does the validation.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r7, 5 of 8 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: all files reviewed, 4 unresolved discussions (waiting on @jiayu-google, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt` line 125 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NeF4pO-3Hj_gvyBku7w:-NeF4pO-3Hj_gvyBku7x:bjm46xi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19d6553c6d49c79ff46c6e61a49d3a77a71174c5/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt#L125)):*
> ```Kotlin
>   } catch (e: IllegalArgumentException) {
>     throw IllegalArgumentException("MeasurementSpeConfig: ${e.message}")
>   }
> ```

Propagate cause, which will inherently propagate the wrapped message.



_Suggestion:_
```Kotlin
  try {
    measurementSpecConfig.validate()
  } catch (e: IllegalStateException) {
    throw IllegalArgumentException("Invalid MeasurementSpecConfig", e)
  }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/config/MeasurementSpecConfigValidator.kt` line 22 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NeF48Jd0G5kODCTFt73:-NeF48Jd0G5kODCTFt74:b5wek0v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19d6553c6d49c79ff46c6e61a49d3a77a71174c5/src/main/kotlin/org/wfanet/measurement/reporting/deploy/config/MeasurementSpecConfigValidator.kt#L22)):*
> ```Kotlin
> 
> /** Contains a single method that validates a [MeasurementSpecConfig]. */
> object MeasurementSpecConfigValidator {
> ```

You don't need to wrap public extension functions in an object.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/config/MeasurementSpecConfigValidator.kt` line 23 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NeF4EVF380ef1xYaJuC:-NeF4EVF380ef1xYaJuD:bwzvzm0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19d6553c6d49c79ff46c6e61a49d3a77a71174c5/src/main/kotlin/org/wfanet/measurement/reporting/deploy/config/MeasurementSpecConfigValidator.kt#L23)):*
> ```Kotlin
> /** Contains a single method that validates a [MeasurementSpecConfig]. */
> object MeasurementSpecConfigValidator {
>   fun MeasurementSpecConfig.validate() {
> ```

1. This should use IllegalStateException, since it's a method of MeasurementSpecConfig. The `error` and `check` convenience functions may help.
2. Add method documentation (KDoc) indicating that it throws an IllegalStateException if the config isn't valid.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1577 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NeF6nKB3pfWTfiXSadp:-NeF6nKB3pfWTfiXSadq:bvmfgka) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19d6553c6d49c79ff46c6e61a49d3a77a71174c5/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1577)):*
> ```Kotlin
>         maximumWatchDurationPerUser = duration {
>           seconds = maximumWatchDurationPerUserSeconds.toLong()
>         }
> ```

Use protobuf Durations util



_Suggestion:_
```Kotlin
        maximumWatchDurationPerUser = Durations.fromSeconds(maximumWatchDurationPerUserSeconds)
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: 15 of 19 files reviewed, 4 unresolved discussions (waiting on @jiayu-google, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt` line 125 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NeF4pO-3Hj_gvyBku7w:-NeFA2GT-_thcSIewXZd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19d6553c6d49c79ff46c6e61a49d3a77a71174c5/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt#L125)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Propagate cause, which will inherently propagate the wrapped message.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/config/MeasurementSpecConfigValidator.kt` line 22 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NeF48Jd0G5kODCTFt73:-NeFA3uX0wEKHVn8hS2M:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19d6553c6d49c79ff46c6e61a49d3a77a71174c5/src/main/kotlin/org/wfanet/measurement/reporting/deploy/config/MeasurementSpecConfigValidator.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You don't need to wrap public extension functions in an object.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/config/MeasurementSpecConfigValidator.kt` line 23 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NeF4EVF380ef1xYaJuC:-NeFB0qJ8fJtFaMqu4Ev:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19d6553c6d49c79ff46c6e61a49d3a77a71174c5/src/main/kotlin/org/wfanet/measurement/reporting/deploy/config/MeasurementSpecConfigValidator.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. This should use IllegalStateException, since it's a method of MeasurementSpecConfig. The `error` and `check` convenience functions may help.
2. Add method documentation (KDoc) indicating that it throws an IllegalStateException if the config isn't valid.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1577 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-NeF6nKB3pfWTfiXSadp:-NeFEysu-aJQmFHWowou:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19d6553c6d49c79ff46c6e61a49d3a77a71174c5/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1577)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use protobuf Durations util
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiayu-google and @uakyol)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 3 files at r7, 4 of 8 files at r10, 3 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiayu-google, @Marco-Premier, @stevenwarejones, and @uakyol)

**Review by riemanli — APPROVED** [review]
> Reviewed 4 of 8 files at r10, 3 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiayu-google, @Marco-Premier, @stevenwarejones, and @uakyol)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 5 of 15 files at r1, 1 of 6 files at r2, 1 of 4 files at r5, 2 of 3 files at r7, 4 of 8 files at r10, 3 of 4 files at r12, 1 of 1 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiayu-google, @stevenwarejones, and @uakyol)

**Review by kungfucraig — APPROVED** [review]
@jiayu-google The reason we're putting in the config is to avoid caring about what the defaults are. Origin can easily overwrite the config file for any of these things.

We do not intend to update the Halo code every time Origin change's their config. That is something that is strictly part of their deployment.

> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-:-NeP76hbAX7SyL7YkW57:b-7oego3)* status: all files reviewed, 8 unresolved discussions (waiting on @stevenwarejones, @tristanvuong2021, and @uakyol)

**Review by jiayu-google — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1202#-:-NePsc-E18BIam7BStv7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @uakyol)

**Pull request merged**
