### PR TITLE
Move Provider proto and related kotlin code to a shared location.

### PR DESCRIPTION
**Pull request by wangyaopw**
These will be used inside both kingdom and duchy.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/372)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 42 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/372)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @yunyeng)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/372)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @SanjayVas, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt, line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/372#-Moo8b304zULh6bi0EeO:-Moo8b304zULh6bi0EeP:b-t4vq69) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8135ae1b48c4a7d60c71b35488619ce87a5c2f50/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L110)):*
> ```Kotlin
> 
> /** Flags specific to the V2alpha API version. */
> class V2alphaFlags {
> ```

Can you make this private? Or maybe even split off into a separate file?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/372)* status: 43 of 44 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @efoxepstein, @SanjayVas, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt, line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/372#-Moo8b304zULh6bi0EeO:-MooA43v8mrhXfwyI4hQ:bp8jliw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8135ae1b48c4a7d60c71b35488619ce87a5c2f50/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L110)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you make this private? Or maybe even split off into a separate file?
</blockquote></details>

Made it private.

It will only be used in this `V2alphaPublicApiServer`, so out it inside seems fine.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/372)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @yunyeng)

**Review by SanjayVas — APPROVED** [review]
Thanks for cleaning this up!

> Reviewed 39 of 42 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/372#-:-MooEgjv1a51kTbsBm5W:bpvx0v6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @yunyeng)

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/372)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @yunyeng)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 39 of 42 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/372)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @yunyeng)

**Pull request merged**
