### PR TITLE
Delete old DP composition methods in Privacy Budget Manager and EDP si…

### PR DESCRIPTION
**Pull request by iverson52000**
…mulator

Rally task link: https://rally1.rallydev.com/#/?detail=/task/735170707983&fdp=true

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1403)

**Review by uakyol — APPROVED** [review]
Thanks so much for tackling this tedious task! 

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1403#-:-NpUt62Y9xJtqjtaq0j3:b9trkia)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Comment by uakyol** [comment]
@jiayu-google would you please also have a look and give a thumbs up on getting rid of the old accounting mechanism. Hope we are not missing anything.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 17 of 22 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1403)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiayu-google and @Marco-Premier)

**Pull request merged**
