### PR TITLE
Add tool for performing benchmarks of kingdom

### PR DESCRIPTION
**Pull request by matthewclegg**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646)

### CODE REVIEW

**Review by renjiezh — CHANGES_REQUESTED** [review]
> Reviewed 26 of 27 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646)* status: 26 of 27 files reviewed, 4 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt` line 412 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-N8Q0K8t1F6PmNEEzZ6U:-N8Q0K8t1F6PmNEEzZ6V:b-3lfta9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/047136e1c4f416423ebb2092c5ae8367deb1a4c4/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt#L412)):*
> ```Kotlin
>             value = eventGroupEntryValue {
>               collectionInterval = timeInterval {
>                 startTime = convertToTimestamp(it.eventStartTime)
> ```

We now use `it.eventStartTime.toProtoTime()` from`org.wfanet.measurement.common.toProtoTime`
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt` line 544 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-N8Q5tyzEpTpIh0urfEf:-N8Q5tyzEpTpIh0urfEg:b-cpkl9v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/047136e1c4f416423ebb2092c5ae8367deb1a4c4/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt#L544)):*
> ```Kotlin
>   }
>   /** List of tasks that have been submitted to the Kingdom. */
>   val taskList: MutableList<MeasurementTask> = mutableListOf()
> ```

I guess MutableList is not thread-safe. Does kotlin has thread-safe collection classes?
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt` line 641 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-N8Q8C8e3rAZ__UbK08P:-N8Q8C8e3rAZ__UbK08Q:btie960) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/047136e1c4f416423ebb2092c5ae8367deb1a4c4/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt#L641)):*
> ```Kotlin
>   ) {
>     while (taskList.size > 0) {
>       val task = taskList.get(0)
> ```

I guess `collectCompletedTasks` could block in the first task even though other tasks are complete. Thus the response time wouldn't be accurate for them.
One alternative is to query all tasks within the function `collectCompletedTasks`.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt` line 746 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-N8Q9akg0hkPI_v-nmuK:-N8Q9akg0hkPI_v-nmuL:b-8bdvf7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/047136e1c4f416423ebb2092c5ae8367deb1a4c4/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt#L746)):*
> ```Kotlin
>       }
> 
>       launch {
> ```

Potential race condition here for `taskList` as  `generateRequests()` is adding tasks while ` collectCompletedTasks()` is getting tasks.

**Review by matthewclegg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646)* status: 25 of 27 files reviewed, 4 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt` line 412 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-N8Q0K8t1F6PmNEEzZ6U:-N8W8xDN4EZDsb7lxCnt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/047136e1c4f416423ebb2092c5ae8367deb1a4c4/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt#L412)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

We now use `it.eventStartTime.toProtoTime()` from`org.wfanet.measurement.common.toProtoTime`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt` line 544 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-N8Q5tyzEpTpIh0urfEf:-N8WCLEb7OjABanXIWLw:b-z82v2x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/047136e1c4f416423ebb2092c5ae8367deb1a4c4/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt#L544)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I guess MutableList is not thread-safe. Does kotlin has thread-safe collection classes?
</blockquote></details>

Good catch.  Thanks!
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt` line 641 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-N8Q8C8e3rAZ__UbK08P:-N8WDCByENzHWQkhwWpT:bpx6dg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/047136e1c4f416423ebb2092c5ae8367deb1a4c4/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt#L641)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I guess `collectCompletedTasks` could block in the first task even though other tasks are complete. Thus the response time wouldn't be accurate for them.
One alternative is to query all tasks within the function `collectCompletedTasks`.
</blockquote></details>

Yes, it's a choice between spamming the Kingdom or having inaccurate response times if responses do not come in order.  My initial thinking was not to spam the Kingdom, but after reading your comment, I decided that it's better to have more accurate response Times.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt` line 746 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-N8Q9akg0hkPI_v-nmuK:-N8WDgOV1NybnxPgaPCW:b-d3wyry) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/047136e1c4f416423ebb2092c5ae8367deb1a4c4/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt#L746)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Potential race condition here for `taskList` as  `generateRequests()` is adding tasks while ` collectCompletedTasks()` is getting tasks.
</blockquote></details>

Correct me if I am wrong, but I don't think there is anything that can go wrong here.  Every request will eventually be put on the task list.  allRequestSent is not set to true until after all requests have been queued, so the while loop cannot terminate early.  On the other hand, every request will eventually receive a response or will timeout, so every request will eventually be handled.

**Review by renjiezh — APPROVED** [review]
:lgtm:

> Reviewed 1 of 27 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-:-N8Wioq023MSCKUwsFrn:bnfp4nl)* status: 26 of 27 files reviewed, all discussions resolved (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt` line 746 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-N8Q9akg0hkPI_v-nmuK:-N8WQwgwCXt-0X22NshL:b9zmey0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/047136e1c4f416423ebb2092c5ae8367deb1a4c4/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt#L746)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Correct me if I am wrong, but I don't think there is anything that can go wrong here.  Every request will eventually be put on the task list.  allRequestSent is not set to true until after all requests have been queued, so the while loop cannot terminate early.  On the other hand, every request will eventually receive a response or will timeout, so every request will eventually be handled.
</blockquote></details>

Yeah, with the thread-safe list of tasks, we are out of the woods now.

**Review by duliomatos1 — APPROVED** [review]
:lgtm: 

> Reviewed 26 of 27 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-:-N9CFsWt3wkF0S9_4BsL:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel` line 36 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-N9CF_JuBAmEqZnK0jNK:-N9CF_JvD-qxJ21YBVDh:bf2aaa0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37d73046bd578e35ccaf65ffaabbdf2a4db8032c/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel#L36)):*
> ```Starlark
> kt_jvm_test(
>     name = "BenchmarkTest",
>     size = "small",
> ```

just curious, this test is really `small` because of all of the mocking? lgtm

**Review by matthewclegg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646)* status: 24 of 27 files reviewed, all discussions resolved (waiting on @duliomatos1 and @renjiezh)

___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel` line 36 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646#-N9CF_JuBAmEqZnK0jNK:-N9ISKZy1HDBFD7erldZ:bb77ufg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37d73046bd578e35ccaf65ffaabbdf2a4db8032c/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel#L36)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

just curious, this test is really `small` because of all of the mocking? lgtm
</blockquote></details>

Yes.

**Review by matthewclegg — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/646)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Pull request merged**
