### PR TITLE
Define testRule for the InProcessKingdom.

### PR DESCRIPTION
**Pull request by wangyaopw**
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F609465361881&view=2c2927c0-626b-4740-8620-af2a93b7d623

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281#-Mk-79Bn4LYbuagZj3R4:-Mk-76Lc0a1APZwCBzb0:b-qdi1sv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a6697e518bf33e7964f8e6593eeaf6c8443a754/src/test/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L57)):*
> ```Starlark
>         "//src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol:async_computation_control_service",
>         "//src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationstats:service",
>         "//src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha:computation_control_service",
> ```

Is this still needed?

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281#-Mk2xwEq4xag9HPaF275:-Mk2xwEq4xag9HPaF276:b-740d6d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a6697e518bf33e7964f8e6593eeaf6c8443a754/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L109)):*
> ```
> GrpcTestServerRule
> ```
How are we handling mTLS for these servers, given that we rely on it already for e.g. exchange auth? Are we skipping TLS and using things like `setForTest`?

@efoxepstein

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281)* status: 2 of 27 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281#-Mk-79Bn4LYbuagZj3R4:-Mk343RXCqkZX5osgt3Y:b-896fjx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a6697e518bf33e7964f8e6593eeaf6c8443a754/src/test/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is this still needed?
</blockquote></details>

Done
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281#-Mk2xwEq4xag9HPaF275:-Mk34x8q3qo0amUgIxBA:b-vbblx5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a6697e518bf33e7964f8e6593eeaf6c8443a754/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L109)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> GrpcTestServerRule
> ```
How are we handling mTLS for these servers, given that we rely on it already for e.g. exchange auth? Are we skipping TLS and using things like `setForTest`?

@efoxepstein 
</blockquote></details>

I was thinking of just use plaintext channels if possible in the integration test. Not sure if the integration test needs to cover the authentication part.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 24 of 25 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281#-Mk2xwEq4xag9HPaF275:-Mk3QllUDvXw6XlO4gPg:b-neqrhy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a6697e518bf33e7964f8e6593eeaf6c8443a754/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L109)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I was thinking of just use plaintext channels if possible in the integration test. Not sure if the integration test needs to cover the authentication part.
</blockquote></details>

Is it hard to use mTLS here?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281#-Mk2xwEq4xag9HPaF275:-Mk3RF4T0Wr3krdgzy1i:bmds0in) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a6697e518bf33e7964f8e6593eeaf6c8443a754/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L109)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is it hard to use mTLS here?
</blockquote></details>

not sure yet. I'll find out soon when I glue those system together, likely in the next PR or two

**Review by efoxepstein — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281#-Mk2xwEq4xag9HPaF275:-Mk4-ieH0MOincmrxE7k:barurn7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a6697e518bf33e7964f8e6593eeaf6c8443a754/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L109)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

not sure yet. I'll find out soon when I glue those system together, likely in the next PR or two
</blockquote></details>

No strong opinion here. We should probably do it if it's easy.

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 24 of 25 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/281)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

**Pull request merged**
