### PR TITLE
Update Duchy's System Control Service to Support HMSS Protocol.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375)

**Review by SanjayVas — APPROVED** [review]
PR description is a bit vague. Maybe something like "Add HMSS protocol to ComputationControlService" ?

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-:-NlyVanh0PycaVXylD-D:bbswc1d)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375)* status: all files reviewed, 12 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt` line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm2PJNn7zFCV0Zu2b-R:-Nm2PJNn7zFCV0Zu2b-S:brtf2ep) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt#L60)):*
> ```Kotlin
>       mapOf(
>           INITIALIZED to setOf(SETUP_PHASE),
>           SETUP_PHASE to
> ```

According to the design doc https://docs.google.com/document/d/1i1EDd-rfVjgK8KRjWBqcPRR0GO4PlGiejziaw2mLQIw/edit?tab=t.0, the SETUP_PHASE will be followed by WAIT_ON_INPUT, and not SHUFFLE_PHASE.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt` line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm2Pxl16KRTnSQFMl_3:-Nm2Pxl16KRTnSQFMl_4:b-pf5ar6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt#L92)):*
> ```Kotlin
>         details: HonestMajorityShareShuffle.ComputationDetails
>       ): Boolean {
>         return when (stage) {
> ```

Let's check for other phases such as INITIALIZED and SETUP_PHASE as well.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt` line 124 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7jtFZ0yKy3WmTM7tG:-Nm7jtFZ0yKy3WmTM7tH:bueq49l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt#L124)):*
> ```Kotlin
>       ): Int {
>         return when (stage) {
>           SETUP_PHASE,
> ```

In the setup phase, workers do not have intermediate computation result.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt` line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7nLj37yNBpqQDrxoU:-Nm7nLj42-glaZVoTkbF:b7djl3y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt#L59)):*
> ```Kotlin
>   }
> 
> fun AdvanceComputationRequest.Header.doesExpectBlobInput(): Boolean =
> ```

Please add a description for this function.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7sp-iCkILeYXs23nD:-Nm7sp-iCkILeYXs23nE:b-cptuua) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt#L67)):*
> ```Kotlin
>       @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA") // Proto enum fields are never null.
>       when (honestMajorityShareShuffle.description) {
>         HonestMajorityShareShuffle.Description.SHUFFLE_PHASE_INPUT -> false
> ```

The shuffle phase in this protocol is similar to the setup phase in LLv2. Why doesn't the protocol expect input for this phase?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt` line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7uGOG3t4DNdjSOQ1B:-Nm7uGOG3t4DNdjSOQ1C:b-hd1vqk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt#L75)):*
> ```Kotlin
>   }
> 
> fun AdvanceComputationRequest.Header.doesExpectProtocolSpecificInput(): Boolean =
> ```

Can we read the seeds from computationDetails and omit this check?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt` line 193 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7rC-UBJ2WVUivo_33:-Nm7rC-UBJ2WVUivo_34:beepv6x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt#L193)):*
> ```Kotlin
>     honestMajorityShareShuffle = honestMajorityShareShuffle {
>       description = honestMajorityShareShuffleContentDescription
>       shufflePhaseInput = shufflePhaseInput { commonRandomSeed = seed }
> ```

Can the worker get the commonRandomSeed from the computationDetails other than from the Header? This could simplify things a lot as we do not need to check whether the seed is present in the header.
___
*[`src/main/proto/wfa/measurement/internal/duchy/async_computation_control_service.proto` line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7uiMu6Lef4D54V6Zf:-Nm7uiMu6Lef4D54V6Zg:b-fxd1ge) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/proto/wfa/measurement/internal/duchy/async_computation_control_service.proto#L53)):*
> ```proto
>   string blob_path = 4;
>   // The protocol specific input for a certain stage.
>   ComputationStageInput computation_stage_input = 5;
> ```

Can we read the seeds from computationDetails and omit this field?
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7phly3Bv8b4bRUg0L:-Nm7phly3Bv8b4bRUg0M:bgvn24l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L112)):*
> ```proto
>   }
> 
>   message ShufflePhaseInput {
> ```

Can we get this from the RandomSeeds in the computationDetails?
___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation_control_service.proto` line 138 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7qUir-ouF9m6HLH4u:-Nm7qUir-ouF9m6HLH4v:b-sopckm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/proto/wfa/measurement/system/v1alpha/computation_control_service.proto#L138)):*
> ```proto
>   }
>   // The input for shuffle phase.
>   ShufflePhaseInput shuffle_phase_input = 2;
> ```

What is the rationale for having this field?
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocolEnumStagesTest.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7vZyS5ZL1xOVnJpW5:-Nm7vZyS5ZL1xOVnJpW6:b8zaqd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/test/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocolEnumStagesTest.kt#L37)):*
> ```Kotlin
>     assertTrue {
>       HonestMajorityShareShuffleProtocol.EnumStages.validInitialStage(
>         HonestMajorityShareShuffle.Stage.WAIT_ON_INPUT
> ```

This may cause confusion as WAIT_ON_INPUT is not an initial stage for non-aggregators. Would it be better to have it named WAIT_ON_AGGREGATION_INPUT for the aggregator?
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocolEnumStagesTest.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7w6Q44jn7bTHHIv3o:-Nm7w6Q44jn7bTHHIv3p:b6tvizj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/test/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocolEnumStagesTest.kt#L79)):*
> ```Kotlin
>   fun `verify transistions`() {
>     assertTrue {
>       HonestMajorityShareShuffleProtocol.EnumStages.validTransition(
> ```

This is not a valid transition according to the design doc https://docs.google.com/document/d/123syhB_E5O3Gl29Ird-Wc5oWO-tWlk-z8UEBV4eGLbY/edit?resourcekey=0-hCDWLmpXyNJmfYNYx5ElAQ&tab=t.0#heading=h.cssqqm9caviw.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375)* status: 17 of 20 files reviewed, 12 unresolved discussions (waiting on @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt` line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm2PJNn7zFCV0Zu2b-R:-Nm7yM1d6TSDns4BHYMn:bl91c5j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt#L60)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

According to the design doc https://docs.google.com/document/d/1i1EDd-rfVjgK8KRjWBqcPRR0GO4PlGiejziaw2mLQIw/edit?tab=t.0, the SETUP_PHASE will be followed by WAIT_ON_INPUT, and not SHUFFLE_PHASE.
</blockquote></details>

Added a comment to explain this special case:
A Non-aggregator will skip WAIT_ON_INPUT stage if the requisition data from EDPs and seed from the peer worker has been received.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt` line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm2Pxl16KRTnSQFMl_3:-Nm8AdmE1tv8eh3-wkdw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt#L92)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Let's check for other phases such as INITIALIZED and SETUP_PHASE as well.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt` line 124 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7jtFZ0yKy3WmTM7tG:-Nm7yt7d2KRT3OixcTbs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt#L124)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

In the setup phase, workers do not have intermediate computation result.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt` line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7nLj37yNBpqQDrxoU:-Nm8-HHF2AI8f_0pXP90:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt#L59)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Please add a description for this function.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7sp-iCkILeYXs23nD:-Nm8-KXM9Vp6QMd20GZ3:b-yygxq3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt#L67)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

The shuffle phase in this protocol is similar to the setup phase in LLv2. Why doesn't the protocol expect input for this phase?
</blockquote></details>

This function is for blobInput. The shuffle phase requires protocol specific input (a field in the header).
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt` line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7uGOG3t4DNdjSOQ1B:-Nm80-dB2QHBicZAuI5-:b-i407nv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt#L75)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Can we read the seeds from computationDetails and omit this check?
</blockquote></details>

System ComputationControlService is protocol agnostic. It has no knowledge regarding the seeds. So we use the factory pattern to hide the details. 
Checking the computationDetails is an alternative way for the same purpose but unfortunately the controlService does not have the token when it receives the request.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt` line 193 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7rC-UBJ2WVUivo_33:-Nm80xtF5U9UU-Z24ia8:b-223lvo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt#L193)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Can the worker get the commonRandomSeed from the computationDetails other than from the Header? This could simplify things a lot as we do not need to check whether the seed is present in the header.
</blockquote></details>

This seed in the header is from the peer worker.
___
*[`src/main/proto/wfa/measurement/internal/duchy/async_computation_control_service.proto` line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7uiMu6Lef4D54V6Zf:-Nm81CizAfqJAKUNimBL:b-z156zw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/proto/wfa/measurement/internal/duchy/async_computation_control_service.proto#L53)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Can we read the seeds from computationDetails and omit this field?
</blockquote></details>

This input is from the peer worker.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7phly3Bv8b4bRUg0L:-Nm81K-f2FGLG7tPiHM3:bivco84) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L112)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Can we get this from the RandomSeeds in the computationDetails?
</blockquote></details>

As explained above.
___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation_control_service.proto` line 138 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7qUir-ouF9m6HLH4u:-Nm81LUQAxea7xYl9Hgr:bivco84) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/main/proto/wfa/measurement/system/v1alpha/computation_control_service.proto#L138)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

What is the rationale for having this field?
</blockquote></details>

As explained above.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocolEnumStagesTest.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7vZyS5ZL1xOVnJpW5:-Nm8B-fe5Dhp9MQLZlLe:b-a7kw9u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/test/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocolEnumStagesTest.kt#L37)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

This may cause confusion as WAIT_ON_INPUT is not an initial stage for non-aggregators. Would it be better to have it named WAIT_ON_AGGREGATION_INPUT for the aggregator?
</blockquote></details>

This is a good suggestion. Maybe we should diverge to have WAIT_ON_SHUFFLE_INPUT and WAIT_ON_AGGREGATION_INPUT. But it requires a large scope of change now. Guess I won't do it for now.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocolEnumStagesTest.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm7w6Q44jn7bTHHIv3o:-Nm820Aa5GED-NzaFJmK:bn401vs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db87796d27ee348f3a727d8900cc5a64d86da503/src/test/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocolEnumStagesTest.kt#L79)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

This is not a valid transition according to the design doc https://docs.google.com/document/d/123syhB_E5O3Gl29Ird-Wc5oWO-tWlk-z8UEBV4eGLbY/edit?resourcekey=0-hCDWLmpXyNJmfYNYx5ElAQ&tab=t.0#heading=h.cssqqm9caviw.
</blockquote></details>

As explained above. This is a special case.

**Review by ple13 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-Nm8J-aeCoG0lq5qKMLy:-Nm8J-aeCoG0lq5qKMLz:b-858gnl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db89f0fcd511954952ee028e44fdf3e00fd8c713/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt#L62)):*
> ```Kotlin
>           // A Non-aggregator will skip WAIT_ON_INPUT into SHUFFLE_PHASE if the requisition data
>           // from EDPs and seed
>           // from the peer worker has been received.
> ```

nit: new line is not needed here. Also, let's update the honest_majority_share_shuffle.proto to indicate that a worker will go to SHUFFLE from SETUP if its peer's seed has arrived.

**Review by ple13 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375#-:-Nm8KaJ-0qFvk2ZO2fjA:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh)

**Review by ple13 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 17 of 20 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1375)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
