### PR TITLE
Migrate Dev guide from google doc to markdown

### PR DESCRIPTION
**Pull request by jgoodknight**
copying https://docs.google.com/document/d/1DwbvIVjoMJ1svztNg42d7wFfAEtWno-B4ECUYfz90Jc/edit# to the repo to make it more accessible

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535)* status: all files reviewed, 4 unresolved discussions (waiting on @jgoodknight)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535#-N-yOGmZ4KOwXj_8VrBr:-N-yOGmZ4KOwXj_8VrBs:b-kb2i62) (no related file):*
PR description
Merge message

Pasted the original images above in case they're better than the ones from the doc.

---
___
*[README.md, line 166 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535#-N-yMathEOW6UYZeSb1E:-N-yMathEOW6UYZeSb1F:b-ujvjyp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cb0ec81fd27fcf3c3064e7ad477b3ea61b1fecc/README.md#L166)):*
> ```Markdown
> ## Developer Guide
> 
> ### Developer Environment
> ```

Can probably just drop this section, as I think it was meant to refer to some of what's covered in the Building doc.



_Code quote:_
```Markdown
### Developer Environment
See [Dev Guide](docs/dev-standards.md)
```
___
*[docs/dev-standards.md, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535#-N-yMkK_5JXNNGbo516a:-N-yMkK_5JXNNGbo516b:b-1pxnys) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cb0ec81fd27fcf3c3064e7ad477b3ea61b1fecc/docs/dev-standards.md#L7)):*
> ```Markdown
> This guide lays out the standards and practices for developers contributing to repositories owned by the WFA.
> 
> It is the intention that eventually this doc is converted to Markdown and put in one of the WFA GitHub repositories.
> ```

nit: can drop this line, as that's exactly what this PR is doing :)



_Code quote:_
```Markdown
It is the intention that eventually this doc is converted to Markdown and put in one of the WFA GitHub repositories.
```
___
*[docs/dev-standards.md, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535#-N-yNGG0ERWQUgp7uXWv:-N-yNGG0ERWQUgp7uXWw:b-jxkke2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cb0ec81fd27fcf3c3064e7ad477b3ea61b1fecc/docs/dev-standards.md#L16)):*
> ```Markdown
> [Example pull request:](https://github.com/world-federation-of-advertisers/common-jvm/pull/90)
> 
> example pull request body
> ```

nit: maybe more descriptive image names? If we end up putting in another image above this one, having it be named "1" might be confusing.



_Code quote:_
```Markdown
dev-std-image-1.png
```
___
*[docs/dev-standards.md, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535#-N-yNTz_9D3rbY1bqtTO:-N-yNTz_9D3rbY1bqtTP:byk69zt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cb0ec81fd27fcf3c3064e7ad477b3ea61b1fecc/docs/dev-standards.md#L16)):*
> ```Markdown
> [Example pull request:](https://github.com/world-federation-of-advertisers/common-jvm/pull/90)
> 
> example pull request body
> ```

nit: no strong opinion on this, but we have other images that we haven't ended up putting into a specific `img` subfolder so may want to be consistent



_Code quote:_
```Markdown
img/
```

**Review by jgoodknight — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[README.md, line 166 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535#-N-yMathEOW6UYZeSb1E:-N-yQB6x3aDT_E49Fhg7:b-piu5rd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cb0ec81fd27fcf3c3064e7ad477b3ea61b1fecc/README.md#L166)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can probably just drop this section, as I think it was meant to refer to some of what's covered in the Building doc.
</blockquote></details>

sorry I'm confused, you commented on the section I just added, but then referenced building: did you mean the section I just added or the building or deploying sections?
___
*[docs/dev-standards.md, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535#-N-yMkK_5JXNNGbo516a:-N-yPOqo6kdaB6p05ELe:b-kmxks8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cb0ec81fd27fcf3c3064e7ad477b3ea61b1fecc/docs/dev-standards.md#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: can drop this line, as that's exactly what this PR is doing :)
</blockquote></details>

lol, good catch thanks!

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535)* status: all files reviewed, 1 unresolved discussion (waiting on @jgoodknight)

___
*[README.md, line 166 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535#-N-yMathEOW6UYZeSb1E:-N-yYN2UC_-a5c4oLJAB:b610xfb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cb0ec81fd27fcf3c3064e7ad477b3ea61b1fecc/README.md#L166)):*
<details><summary><i>Previously, jgoodknight (Joey (Goodknight) Knightbrook) wrote…</i></summary><blockquote>

sorry I'm confused, you commented on the section I just added, but then referenced building: did you mean the section I just added or the building or deploying sections?
</blockquote></details>

The "Developer Environment" section, which existed but was empty prior to this PR.

**Review by jgoodknight — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/535)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jgoodknight)

**Pull request merged**
