### PR TITLE
Update EventGroupReader to return EventGroupId

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412)

### CODE REVIEW

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @robinsons and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412#-MsbMIfk1eLETMp5gecb:-MsbMIfk1eLETMp5gecc:b-pd9hgc) (no related file):*
I'm not sure why build + test is taking so long (20m and counting) -- wanted to get some initial feedback in the meantime.

---

**Review by robinsons — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412#-MsbMIfk1eLETMp5gecb:-MsbPs0YE9vsLBM_i-pZ:bgbv6fy) (no related file):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

I'm not sure why build + test is taking so long (20m and counting) -- wanted to get some initial feedback in the meantime.
</blockquote></details>

Looks good to me, pending test results.

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412#-MsbNpvu1yLDp7UOElSe:-MsbNpvu1yLDp7UOElSf:bhvvbq5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dea5dba232baea49eea260def33dcbf9a0fa6b24/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L42)):*
> ```Kotlin
> 
> class EventGroupReader : BaseSpannerReader<EventGroupReader.Result>() {
>   data class Result(val eventGroup: EventGroup, val internalEventGroupId: Long)
> ```

nit / optional: I personally prefer to make use of specialized types like `InternalId` rather than primitives like `Long`. But I've seen both approaches used in these `Result` classes, so I'll leave it to your discretion.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412#-MsbNpvu1yLDp7UOElSe:-MseufVR-LxgDTRzYPxm:b-cna7hb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dea5dba232baea49eea260def33dcbf9a0fa6b24/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L42)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

nit / optional: I personally prefer to make use of specialized types like `InternalId` rather than primitives like `Long`. But I've seen both approaches used in these `Result` classes, so I'll leave it to your discretion.
</blockquote></details>

Since I'll need to convert it to a `Long` for the database query I'll opt to leave as is for now. Can always update later if needed.

**Review by robinsons — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412#-MsbNpvu1yLDp7UOElSe:-MsfFC3H6PW5euHy6X9I:bv50ui0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dea5dba232baea49eea260def33dcbf9a0fa6b24/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L42)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Since I'll need to convert it to a `Long` for the database query I'll opt to leave as is for now. Can always update later if needed.
</blockquote></details>

The conversion is trivial. simply `internalEventGroupId.value`. For consistence, please use `InternalId` and `ExternalId `whenever possible. It also enforces the long value is >0

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412#-MsbNpvu1yLDp7UOElSe:-Msffm6f-PXLD6Kl_ZXw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dea5dba232baea49eea260def33dcbf9a0fa6b24/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L42)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

The conversion is trivial. simply `internalEventGroupId.value`. For consistence, please use `InternalId` and `ExternalId `whenever possible. It also enforces the long value is >0
</blockquote></details>

Done.

**Review by robinsons — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]

**Pull request merged**
