### PR TITLE
Add CreateExchange class to insert new Exchanges

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141)* status: all files reviewed, 2 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141#-Me1Pnk-ESQzexz-SOqo:-Me1Pnk-ESQzexz-SOqp:bmpbh34) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd0a23e7c8d8323f170c21fb252765bf84aa73f8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt#L38)):*
> ```Kotlin
>       .set("Date" to date.toCloudDate())
>       .set("State" to state)
>       .set("ExchangeDetails" to "")
> ```

Can you add some TODOs for all the unset fields?
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeTest.kt, line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141#-Me1Q7Pz1AKLJaf46sNj:-Me1Q7Pz1AKLJaf46sNk:bac0km4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd0a23e7c8d8323f170c21fb252765bf84aa73f8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeTest.kt#L92)):*
> ```Kotlin
>   ): Struct {
>     return Struct.newBuilder()
>       .set("RecurringExchangeId")
> ```

Does `set(x to y)` syntax work here? (If not can you add a similar helper function?)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141#-Me1Pnk-ESQzexz-SOqo:-Me1XGSi7aUBSocZJa09:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd0a23e7c8d8323f170c21fb252765bf84aa73f8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add some TODOs for all the unset fields?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeTest.kt, line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141#-Me1Q7Pz1AKLJaf46sNj:-Me1XIk89CZu3ScBwLt-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd0a23e7c8d8323f170c21fb252765bf84aa73f8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeTest.kt#L92)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Does `set(x to y)` syntax work here? (If not can you add a similar helper function?)
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141#-Me1oZL7AE9HVoDIkys0:-Me1oZL89D2xVjk_QBnR:b-ww1kvu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc35caca9046cae377dcb927a2b4543870e4b65b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt#L37)):*
> ```
> Mutation.newInsertBuilder("Exchanges")
> ```
nit: Use the newer DSL for this. See usage example in https://github.com/world-federation-of-advertisers/common-jvm/blob/f97ad14726a865f50bdd7aed75f8621df5803128/src/test/kotlin/org/wfanet/measurement/gcloud/spanner/MutationsTest.kt
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141#-Me1p4Jx5ff-s4dJjNhe:-Me1p4Jx5ff-s4dJjNhf:b-bh5hih) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc35caca9046cae377dcb927a2b4543870e4b65b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt#L50)):*
> ```
> .setExternalRecurringExchangeId
> ```
nit: prefer Kotlin property syntax. Use a [scope function](https://kotlinlang.org/docs/scope-functions.html#function-selection) such as `apply` to make this easier to write.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeTest.kt, line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141#-Me1Q7Pz1AKLJaf46sNj:-Me1pUBK9oPLaE5-TG-f:b-bfclz3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd0a23e7c8d8323f170c21fb252765bf84aa73f8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeTest.kt#L92)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could you add and use a [type-safe builder](https://kotlinlang.org/docs/type-safe-builders.html) as well? See what was done for Mutations in https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/100.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Structs.kt, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141#-Me1r11-ER5H3-r1esE8:-Me1r1105oeTLWLGyA9i:b5rhupy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc35caca9046cae377dcb927a2b4543870e4b65b/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Structs.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

Note that until we swap all the targets over, you'll need to duplicate any changes made to this package in https://github.com/world-federation-of-advertisers/common-jvm

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Structs.kt, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141#-Me1r11-ER5H3-r1esE8:-Me2-dIc-cx6tKqczrCS:b-8pwsfx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc35caca9046cae377dcb927a2b4543870e4b65b/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Structs.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that until we swap all the targets over, you'll need to duplicate any changes made to this package in https://github.com/world-federation-of-advertisers/common-jvm
</blockquote></details>

I will send that change
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141#-Me1p4Jx5ff-s4dJjNhe:-Me2-7hiBRrnQpbdqU9m:b-699kxd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc35caca9046cae377dcb927a2b4543870e4b65b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> .setExternalRecurringExchangeId
> ```
nit: prefer Kotlin property syntax. Use a [scope function](https://kotlinlang.org/docs/scope-functions.html#function-selection) such as `apply` to make this easier to write.
</blockquote></details>

This will need a change of variable names here as it doesn't allow externalRecurringExchangeId = externalRecurringExchangeId.value.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141#-Me1p4Jx5ff-s4dJjNhe:-Me2BwpY8eShmOQv5nuY:b-k8aikd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc35caca9046cae377dcb927a2b4543870e4b65b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt#L50)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

This will need a change of variable names here as it doesn't allow externalRecurringExchangeId = externalRecurringExchangeId.value.
</blockquote></details>

You can use `also` instead of `apply` so the builder property gets prefixed with `it.`

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
