### PR TITLE
Add Inprocess Reporting Integration Test

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 14 of 20 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessReportingServer.kt` line 100 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-ND48POX64eTt40h6xHk:-ND48POX64eTt40h6xHl:b2xslxf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d82e535653ef4f70b57f31afea8a7693ae3b00e9/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessReportingServer.kt#L100)):*
> ```Kotlin
> /** TestRule that starts and stops all Reporting Server gRPC services. */
> class InProcessReportingServer(
>   private val reportingServerDataServices: ReportingDataServer.Services,
> ```

Just take in the Channel so this could be used either with InProcessKingdom or with service mocks.

Stubbing should be part of the test rather than part of the server.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingClient.kt` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-ND4B-2aDHHRnCdtoxti:-ND4B-2aDHHRnCdtoxtj:b177opq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d82e535653ef4f70b57f31afea8a7693ae3b00e9/src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingClient.kt#L46)):*
> ```Kotlin
> 
> /** A client performing reporting operations. */
> class ReportingClient(
> ```

Do we need this? Can we just move these functions into the test or a test helper where the methods are called directly rather than via a top-level `execute`? That would make the tests more clear.

The only reason the LifeOfAMeasurement integration test follows this pattern is because it reuses the FrontendSimulator MC test harness. Having this be written more like a regular test would be clearer. If we need to run on K8s, we could stick the actual test runner in an image. (I'd argue this is how the LifeOfAMeasurement test should also be written).
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt` line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-ND4EBu5Bw6dse9UlxM_:-ND4EBu5Bw6dse9UlxMa:b-owfw05) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d82e535653ef4f70b57f31afea8a7693ae3b00e9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt#L63)):*
> ```Kotlin
>       val numRowsUpdated = executeStatement(updateMeasurementStatement).numRowsUpdated
>       if (numRowsUpdated == 0L) {
>         return@run
> ```

What is this change about? If the Measurement to update is not found, it should definitely throw a MeasurementNotFoundException.

If you want to make this method idempotent, that's orthogonal to whether a MeasurementNotFoundException exception should be thrown.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt` line 69 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-ND4EkF05d7Z3bJMBYS-:-ND4EkF05d7Z3bJMBYS0:bz0eeod) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d82e535653ef4f70b57f31afea8a7693ae3b00e9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt#L69)):*
> ```Kotlin
>       val numRowsUpdated = executeStatement(updateMeasurementStatement).numRowsUpdated
>       if (numRowsUpdated == 0L) {
>         return@run
> ```

Same here re: not found.

**Comment by tristanvuong2021** [comment]
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt` line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-ND4EBu5Bw6dse9UlxM_:-ND4lFhLCr_5Rd6IzXSC:b-4kcuni) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c7e8ce81c9e4147bf0c947c91fb779bf656bbe4/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What is this change about? If the Measurement to update is not found, it should definitely throw a MeasurementNotFoundException.

If you want to make this method idempotent, that's orthogonal to whether a MeasurementNotFoundException exception should be thrown.
</blockquote></details>

NumRowsUpdated only checks if rows were updated, which I thought was useful for a MeasurementNotFound check at first, but after testing concurrent transactions, I discovered that it was not if two requests are trying to get the report at the same time. Both would call this, one would eventually succeed, but the other would fail with a MeasurementNotFoundException, which is the wrong error.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt` line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-ND4EBu5Bw6dse9UlxM_:-ND4uQzeBzHJyGsdePrC:b-xgsm9e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c7e8ce81c9e4147bf0c947c91fb779bf656bbe4/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt#L63)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

NumRowsUpdated only checks if rows were updated, which I thought was useful for a MeasurementNotFound check at first, but after testing concurrent transactions, I discovered that it was not if two requests are trying to get the report at the same time. Both would call this, one would eventually succeed, but the other would fail with a MeasurementNotFoundException, which is the wrong error.
</blockquote></details>

Right, but we still need to handle the case where it's not found. May need to do a separate read first.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667)* status: 9 of 20 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessReportingServer.kt` line 100 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-ND48POX64eTt40h6xHk:-NDUvuqF1uzAaEDinkQK:b-3uryow) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c228b960a7845232ac687cf3671c6f8fa1048d6/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessReportingServer.kt#L100)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just take in the Channel so this could be used either with InProcessKingdom or with service mocks.

Stubbing should be part of the test rather than part of the server.
</blockquote></details>

Done, but discovered a bug in the process: https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/717
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingClient.kt` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-ND4B-2aDHHRnCdtoxti:-NDUvtKAEzGEFQi_uvgU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c228b960a7845232ac687cf3671c6f8fa1048d6/src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingClient.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we need this? Can we just move these functions into the test or a test helper where the methods are called directly rather than via a top-level `execute`? That would make the tests more clear.

The only reason the LifeOfAMeasurement integration test follows this pattern is because it reuses the FrontendSimulator MC test harness. Having this be written more like a regular test would be clearer. If we need to run on K8s, we could stick the actual test runner in an image. (I'd argue this is how the LifeOfAMeasurement test should also be written).
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667)* status: 9 of 20 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt` line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-ND4EBu5Bw6dse9UlxM_:-NDV6s6e1sROaAc_r7N7:b-ibo1n4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c228b960a7845232ac687cf3671c6f8fa1048d6/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Right, but we still need to handle the case where it's not found. May need to do a separate read first.
</blockquote></details>

https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/718
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt` line 69 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-ND4EkF05d7Z3bJMBYS-:-NDV6rpQ6yT46X1Hs0vR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c228b960a7845232ac687cf3671c6f8fa1048d6/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here re: not found.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 213 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-NDiKIEE92cA3D11CLp1:-NDiKIEE92cA3D11CLp2:b-bdpi2m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c241c598aaea74a6e592369a8ac3b6c766f3a636/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L213)):*
> ```Kotlin
>   }
>   private val publicReportsClient by lazy { ReportsCoroutineStub(reportingServer.publicApiChannel) }
> ```

Shouldn't there be a basic test for a single report?
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 215 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-NDiJhez1XIv-4exEkfP:-NDiJhez1XIv-4exEkfQ:b-m0e2eb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c241c598aaea74a6e592369a8ac3b6c766f3a636/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L215)):*
> ```Kotlin
> 
>   @Test
>   fun `create multiple Reports and check the results match the expected results`() = runBlocking {
> ```

Why? If this is trying to make sure it can handle parallel report requests, that's what should be in the test method name.



_Code quote:_
```Kotlin
create multiple Reports 
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 233 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-NDiJ9gw1clR0voGAd_z:-NDiJ9gw1clR0voGAda-:b5kuhz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c241c598aaea74a6e592369a8ac3b6c766f3a636/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L233)):*
> ```Kotlin
>       column.setOperationsList.forEach { sum += it }
>     }
>     assert(sum == 200.0)
> ```

Use Truth. It's also clearer to have helper functions that just return the results so your test method can do the assertion.



_Code quote:_
```Kotlin
assert(sum == 200.0)
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667)* status: 13 of 20 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 213 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-NDiKIEE92cA3D11CLp1:-NDo3aj95Y06-HwnKL_8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25a0f52ff61229b68c72856af81314ee18d071dc/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L213)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't there be a basic test for a single report?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 215 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-NDiJhez1XIv-4exEkfP:-NDo3bK756IN79w6-RbU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25a0f52ff61229b68c72856af81314ee18d071dc/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L215)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why? If this is trying to make sure it can handle parallel report requests, that's what should be in the test method name.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 233 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-NDiJ9gw1clR0voGAd_z:-NDo3bny04w26M6IXIMu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25a0f52ff61229b68c72856af81314ee18d071dc/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L233)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Truth. It's also clearer to have helper functions that just return the results so your test method can do the assertion.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by duliomatos1 — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 20 files at r1, 1 of 3 files at r3, 2 of 11 files at r4, 2 of 6 files at r5, 1 of 1 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/667#-:-NE650ND6nXFQtmx2R08:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
