### PR TITLE
Create and publish container images to GitHub Packages.

### PR DESCRIPTION
**Pull request by wfa-mdharmalingam**
Created separate templates to push the images to GHCR. 

- Build Image for Kingdom
- Push Image for Kingdom
- Build Image for Duchy
- Push Image for Duchy

### CODE REVIEW

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @wfa-mdharmalingam and @wfa-siyengar)

___
*[`.github/workflows/Image.yml` line 17 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NR33GUg-0eMrf-n0PSV:-NR33GUg-0eMrf-n0PSW:b8npsrg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc8b492065ee87cd92c4403e7906a6ab3ad94107/.github/workflows/Image.yml#L17)):*
> ```YAML
> name: Push Docker Image to Github Artifacts
> 
> on:
> ```

Triggers for image push need to be workflow_dispatch and workflow_run.
___
*[`.github/workflows/Image.yml` line 44 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NR33KrU-LidBLYrdlKB:-NR33KrU-LidBLYrdlKC:bg10yri) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc8b492065ee87cd92c4403e7906a6ab3ad94107/.github/workflows/Image.yml#L44)):*
> ```YAML
>           bazel query 'filter("push_duchy", kind("container_push", //src/main/docker:all))' |
>           xargs bazel build -c opt --define container_registry=ghcr.io \
>           --define image_repo_prefix=world-federation-of-advertisers/packages --platforms=//build/platforms:ubuntu_20_04_rbe --define image_tag=build-0001
> ```

Use the logic from container repo to get the image tag

https://github.com/world-federation-of-advertisers/containers/blob/main/.github/workflows/push-images.yml#L34

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @kungfucraig, @TNATALI, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/Image.yml` line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NREDOy89Bh66F65nYhI:-NREDOy89Bh66F65nYhJ:b-t7cy2d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a1875d0ae2662a35b09c4469cf7a88d91fc648b/.github/workflows/Image.yml#L1)):*
> ```YAML
> # Copyright 2023 The Cross-Media Measurement Authors
> ```

Filenames of workflows should be lowercase with hyphens for consistency.
___
*[`.github/workflows/Image.yml` line 25 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NREDaEB6BEIORwrDkhN:-NREDaEB6BEIORwrDkhO:b4zsm9n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a1875d0ae2662a35b09c4469cf7a88d91fc648b/.github/workflows/Image.yml#L25)):*
> ```YAML
> jobs:
>   push_docker_image:
>     runs-on: ubuntu-22.04
> ```

We're using `--platforms=//build/platforms:ubuntu_20_04_rbe` in Bazel commands, meaning we're telling the build system that we're running Ubuntu 20.04. We've only tested on this Ubuntu version.



_Suggestion:_
```YAML
20.04
```
___
*[`.github/workflows/Image.yml` line 45 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NREDCKaASnnlMAg2JVc:-NREDCKb1oaONy-_S4_Z:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a1875d0ae2662a35b09c4469cf7a88d91fc648b/.github/workflows/Image.yml#L45)):*
> ```YAML
>       - name: Build Duchy image
>         run: |
>           bazel query 'filter("push_duchy", kind("container_push", //src/main/docker:all))' |
> ```





_Suggestion:_
```YAML
bazelisk
```

**Review by wfa-siyengar — APPROVED** [review]
Done!

> Reviewed 1 of 2 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-:-NRIBJukDpXJlXXzyixf:b-896fja)* status: all files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @kungfucraig, @SanjayVas, and @TNATALI)

___
*[`.github/workflows/Image.yml` line 17 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NR33GUg-0eMrf-n0PSV:-NRI6aeiDgQG-9-5vokI:b8kv59e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc8b492065ee87cd92c4403e7906a6ab3ad94107/.github/workflows/Image.yml#L17)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Triggers for image push need to be workflow_dispatch and workflow_run.
</blockquote></details>

i will go with workflow_dispatch for now and will introduce workflow_call in a separate PR.
will add a TODO here.
___
*[`.github/workflows/Image.yml` line 44 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NR33KrU-LidBLYrdlKB:-NRIATLm7GVjHCt2T990:b-8oqfi1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc8b492065ee87cd92c4403e7906a6ab3ad94107/.github/workflows/Image.yml#L44)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Use the logic from container repo to get the image tag

https://github.com/world-federation-of-advertisers/containers/blob/main/.github/workflows/push-images.yml#L34
</blockquote></details>

It is now using the export tag logic.
___
*[`.github/workflows/Image.yml` line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NREDOy89Bh66F65nYhI:-NRIAg8r8k-8u2BhO_mm:b-ilb19) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a1875d0ae2662a35b09c4469cf7a88d91fc648b/.github/workflows/Image.yml#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Filenames of workflows should be lowercase with hyphens for consistency.
</blockquote></details>

Chanhged the name of the file to reflect the verb. Done!!
___
*[`.github/workflows/Image.yml` line 25 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NREDaEB6BEIORwrDkhN:-NRIAd5MDq4tnABtGamz:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a1875d0ae2662a35b09c4469cf7a88d91fc648b/.github/workflows/Image.yml#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We're using `--platforms=//build/platforms:ubuntu_20_04_rbe` in Bazel commands, meaning we're telling the build system that we're running Ubuntu 20.04. We've only tested on this Ubuntu version.
</blockquote></details>

Done
___
*[`.github/workflows/Image.yml` line 45 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NREDCKaASnnlMAg2JVc:-NRI9oE23rXvtPJQtGqx:b-896fjx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a1875d0ae2662a35b09c4469cf7a88d91fc648b/.github/workflows/Image.yml#L45)):*
> ```YAML
>       - name: Build Duchy image
>         run: |
>           bazel query 'filter("push_duchy", kind("container_push", //src/main/docker:all))' |
> ```

Done

**Review by wfa-siyengar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-:-NRIBbT_Ca2s3rDCCYsA:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @kungfucraig, @SanjayVas, and @TNATALI)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @kungfucraig, @TNATALI, and @wfa-mdharmalingam)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRJazKs7lWvcIrhtCos:-NRJazKs7lWvcIrhtCot:by34r32) (no related file):*
Approved assuming this has been tested and verified to work as intended.

___
___
*[`.github/workflows/create-and-push-image.yml` line 19 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRJaTORCVoccDHBZm2w:-NRJaTORCVoccDHBZm2x:b-78e83l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04dadaa75db7bd2fd722e55207e176611e2b0cca/.github/workflows/create-and-push-image.yml#L19)):*
> ```YAML
> on:
>   workflow_dispatch:
>   #TODO: (@wfa-siyengar): introduce workflow_call/workflow_run as appropriate.
> ```

nit: follow TODO format described in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#todos



_Suggestion:_
```YAML
# TODO(@wfa-siyengar):
```

**Review by bdomen-ggl — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 2 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @TNATALI, and @wfa-mdharmalingam)

**Review by wfa-siyengar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @kungfucraig, @SanjayVas, @TNATALI, and @wfa-mdharmalingam)

**Review by wfa-siyengar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @kungfucraig, @SanjayVas, @TNATALI, and @wfa-mdharmalingam)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wfa-mdharmalingam)

**Review by wfa-hkawalkar — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 2 files at r5, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @bdomen-ggl, @kungfucraig, @SanjayVas, and @wfa-siyengar)

___
*[`.github/workflows/create-and-push-image.yml` line 19 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRJaTORCVoccDHBZm2w:-NRc6OiI2-CVV4sgo62U:b-hpudvm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d5819207d3a427e4dd5c0743436ca9458c97e989/.github/workflows/create-and-push-image.yml#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: follow TODO format described in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#todos
</blockquote></details>

We have added TODO as per the format in the above document.
___
*[`.github/workflows/Image.yml` line 17 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NR33GUg-0eMrf-n0PSV:-NREErsy64fSctvE-EHF:b-vpr1j7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc8b492065ee87cd92c4403e7906a6ab3ad94107/.github/workflows/Image.yml#L17)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Triggers for image push need to be workflow_dispatch and workflow_run.
</blockquote></details>

We will add workflow_run in the file.
___
*[`.github/workflows/Image.yml` line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NREDOy89Bh66F65nYhI:-NREEm8q30lAPW4gZ-zV:bwfi5cu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a1875d0ae2662a35b09c4469cf7a88d91fc648b/.github/workflows/Image.yml#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Filenames of workflows should be lowercase with hyphens for consistency.
</blockquote></details>

I have changed the file name to lower case. 
___
*[`.github/workflows/Image.yml` line 45 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NREDCKaASnnlMAg2JVc:-NREExXz3EUSRKG8shtG:b80wz5q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a1875d0ae2662a35b09c4469cf7a88d91fc648b/.github/workflows/Image.yml#L45)):*
> ```YAML
>       - name: Build Duchy image
>         run: |
>           bazel query 'filter("push_duchy", kind("container_push", //src/main/docker:all))' |
> ```

Thank you Sanjay for pointing that out. I have changed the Ubuntu version to 20.04.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 3 unresolved discussions (waiting on @wfa-mdharmalingam)

___
*[`.github/workflows/create-and-push-image.yml` line 19 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRJaTORCVoccDHBZm2w:-NRdLMuL3Uujf6cPBGhJ:b3s94te) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d5819207d3a427e4dd5c0743436ca9458c97e989/.github/workflows/create-and-push-image.yml#L19)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

We have added TODO as per the format in the above document.
</blockquote></details>

I'm still not seeing the correct format. It should be `# TODO(@wfa-siyengar): introduce workflow_call/workflow_run as appropriate.`
___
*[`.github/workflows/create-and-push-image.yml` line 33 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRdMJ7O4VIcXFmK1k7r:-NRdMJ7O4VIcXFmK1k7s:byd5kcz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0c56344e47d2e8ae1e8a1263b0c1a80bba5df17/.github/workflows/create-and-push-image.yml#L33)):*
> ```YAML
>         env:
>           DEFAULT_BRANCH: main
>         run: chmod +x ./.github/workflows/export-image-tag.sh && ./.github/workflows/export-image-tag.sh
> ```

Update the permissions of the actual file under version control rather than modifying it in the workflow.



_Code quote:_
```YAML
chmod +x ./.github/workflows/export-image-tag.sh && 
```
___
*[`.github/workflows/create-and-push-image.yml` line 46 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRdLs34Byrqm9g8Pf6s:-NRdLs34Byrqm9g8Pf6t:b-ovkud3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0c56344e47d2e8ae1e8a1263b0c1a80bba5df17/.github/workflows/create-and-push-image.yml#L46)):*
> ```YAML
>         run: |
>           bazelisk query 'filter("push_kingdom", kind("container_push", //src/main/docker:all))' |
>           xargs bazel build -c opt --define container_registry=ghcr.io \
> ```

Still some places using `bazel` instead of `bazelisk`



_Suggestion:_
```YAML
bazelisk
```
___
*[`.github/workflows/create-duchy.yml` line 1 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRdLj8iE8yAvSAoRrNF:-NRdLj8iE8yAvSAoRrNG:bx3hnzr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0c56344e47d2e8ae1e8a1263b0c1a80bba5df17/.github/workflows/create-duchy.yml#L1)):*
> ```YAML
> # Copyright 2023 The Cross-Media Measurement Authors
> ```

Unrelated change. This rename doesn't belong in this PR.

**Review by wfa-siyengar — APPROVED** [review]
> Reviewed 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wfa-mdharmalingam)

___
*[`.github/workflows/create-duchy.yml` line 1 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRdLj8iE8yAvSAoRrNF:-NRdPg7o6OYsUIJQHtot:bq9ljpe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0c56344e47d2e8ae1e8a1263b0c1a80bba5df17/.github/workflows/create-duchy.yml#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Unrelated change. This rename doesn't belong in this PR.
</blockquote></details>

Apologies. Cleared.

**Review by wfa-siyengar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wfa-mdharmalingam)

**Review by wfa-siyengar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wfa-mdharmalingam)

**Review by wfa-siyengar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wfa-mdharmalingam)

___
*[`.github/workflows/create-duchy.yml` line 1 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRdLj8iE8yAvSAoRrNF:-NRdRCjcD0uMNqfxgINM:bfj7yyl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0c56344e47d2e8ae1e8a1263b0c1a80bba5df17/.github/workflows/create-duchy.yml#L1)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Apologies. Cleared.
</blockquote></details>

This was un-intentional, Apologies. its stands cleared now.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 2 unresolved discussions (waiting on @wfa-mdharmalingam)

**Review by wfa-siyengar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wfa-mdharmalingam)

___
*[`.github/workflows/create-and-push-image.yml` line 33 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRdMJ7O4VIcXFmK1k7r:-NRdRv_c8IehtC9Zi1iH:b-z5cr64) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0c56344e47d2e8ae1e8a1263b0c1a80bba5df17/.github/workflows/create-and-push-image.yml#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Update the permissions of the actual file under version control rather than modifying it in the workflow.
</blockquote></details>


Done!

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 2 unresolved discussions (waiting on @wfa-mdharmalingam and @wfa-siyengar)

___
*[`.github/workflows/create-and-push-image.yml` line 33 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRdMJ7O4VIcXFmK1k7r:-NRe46QM1_PKr4GlGMzG:b-2801h5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0c56344e47d2e8ae1e8a1263b0c1a80bba5df17/.github/workflows/create-and-push-image.yml#L33)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>


Done!
</blockquote></details>

This comment is marked as resolved/done, but I still see the `chmod` command here.

**Review by wfa-siyengar — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-:-NRde7iZ4dZaoO8PxMye:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`.github/workflows/create-and-push-image.yml` line 33 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRdMJ7O4VIcXFmK1k7r:-NRf0tD-E70SN1JlqcqN:b62ohkl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0c56344e47d2e8ae1e8a1263b0c1a80bba5df17/.github/workflows/create-and-push-image.yml#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This comment is marked as resolved/done, but I still see the `chmod` command here.
</blockquote></details>

Seem like the push did not go thru. Had to do a force push. Its done now.
___
*[`.github/workflows/create-and-push-image.yml` line 46 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900#-NRdLs34Byrqm9g8Pf6s:-NRf39fH7jDrdVUDGguh:b-qox3x9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0c56344e47d2e8ae1e8a1263b0c1a80bba5df17/.github/workflows/create-and-push-image.yml#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Still some places using `bazel` instead of `bazelisk`
</blockquote></details>

Changed it as per suggestion.

**Review by wfa-siyengar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by bdomen-ggl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by wfa-siyengar — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/900)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wfa-mdharmalingam)

**Pull request merged**
