### PR TITLE
Implement the aggregation phase of the HMSS protocol.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494)* status: all files reviewed, 9 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 249 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrB_dyk51HsPyNmGF76:-NrB_dyk51HsPyNmGF77:bmupnfv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L249)):*
> ```cpp
>         noiser->options().shift_offset * kNonAggregatorCount;
>     // Removes the noise baseline from the frequency histogram.
>     for (int i = 0; i < maximum_frequency; ++i) {
> ```

Consider using an iterator.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 264 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrBbFHFA3kgsNLa0MOO:-NrBbFHFA3kgsNLa0MOP:b-kh7jj4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L264)):*
> ```cpp
>   }
> 
>   // Sum of all frequencies from 0 to {maximum_frequency - 1}.
> ```

This is not really the sum of frequencies, but a count of the number of registers that have frequency value in the range [0, MF-1].  The frequencies are actually the keys of the histogram.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 266 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrB_fkzBbTp2O5t6sSh:-NrB_fkzBbTp2O5t6sSi:bmupnfv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L266)):*
> ```cpp
>   // Sum of all frequencies from 0 to {maximum_frequency - 1}.
>   int accumulated_count = 0;
>   for (int i = 0; i < maximum_frequency; i++) {
> ```

Consider using an iterator.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 270 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrBe5fwEuOqSRo3NRGF:-NrBe5fx9vmQgSaf26Xf:b8dq6sj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L270)):*
> ```cpp
>   }
> 
>   // Computes the value frequency_histogram[maximum_frequency+] from the current
> ```

The text of the comment uses opposite logic and documents the "else" block before the "if" block. Things would be easier to read if the comment paralleled the code.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 286 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrBeilBEJv-C1BEqrJX:-NrBeilBEJv-C1BEqrJY:b5um22r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L286)):*
> ```cpp
>   }
> 
>   if (adjusted_total == 0) {
> ```

Can you document why this is an error? 

I can see a case where accumulated_count == register_count and the number of zero buckets is zero that would trigger this, but wouldn't that be okay?
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 297 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrBjVQeEZlbD76nay5Y:-NrBjVQeEZlbD76nay5Z:bxaw7si) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L297)):*
> ```cpp
>   google::protobuf::Map<int64_t, double>& distribution =
>       *response.mutable_frequency_distribution();
>   for (int i = 1; i <= maximum_frequency; ++i) {
> ```

I'm having a hard time convincing myself that adjusted_total = sum(frequency_histogram.values[1:max]). Can you add some comments?
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility_helper.cc` line 163 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrBkrK23BhEtf30RftB:-NrBkrK23BhEtf30RftC:by6n2q0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility_helper.cc#L163)):*
> ```cpp
> }
> 
> absl::StatusOr<std::vector<uint32_t>> VectorAddMod(absl::Span<const uint32_t> X,
> ```

Use lower case variable names?
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility_helper.cc` line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrBkyMoD0t8KOg8RU7P:-NrBkyMoD0t8KOg8RU7Q:b-g0y9ba) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility_helper.cc#L172)):*
> ```cpp
>   for (int i = 0; i < X.size(); i++) {
>     if (X[i] >= modulus || Y[i] >= modulus) {
>       return absl::InvalidArgumentError(
> ```

It'd be good to indicate which one (or both) is bad.
___
*[`src/test/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility_helper_test.cc` line 233 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrBl_-sD2nklV1XKbvW:-NrBl_-sD2nklV1XKbvX:b677coc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/test/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility_helper_test.cc#L233)):*
> ```cpp
>   EXPECT_EQ(result, expected_result);
> }
> ```

Add tests for estimate reach and combine sketch shares?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494)* status: all files reviewed, 13 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrCT76Z7DIua9UXctfY:-NrCT76_5oUGm1grROge:b-b5130q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L55)):*
> ```cpp
>     GetBlindHistogramNoiser;
> 
> constexpr int kNonAggregatorCount = 2;
> ```

nit: We use "worker" as the other role



_Suggestion:_
```cpp
kWorkerCount
```
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 211 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrCTV6e85BVL8ONUUxY:-NrCTV6e85BVL8ONUUxZ:bh1dw82) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L211)):*
> ```cpp
>   if (maximum_frequency < 1) {
>     return absl::InvalidArgumentError(
>         "The maximum frequency should be greater than 0.");
> ```

I thought it needs to be >1, as max frequency of 1 is effectively reach-only. Unless we actually want to support that here? (We already check for >1 in the MeasurementSpec for R/F, I believe).
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 217 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrCURDM3SifZV2ar9lI:-NrCURDNETBVasU1wf7o:b-vhhgwv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L217)):*
> ```cpp
>   // frequency_histogram[i] = the number of times value i occurs where
>   // i in {0, ..., maximum_frequency-1}.
>   std::unordered_map<int, int64_t> frequency_histogram;
> ```

Prefer absl::flat_hash_map or absl::node_hash_map. See https://abseil.io/docs/cpp/guides/container and https://abseil.io/tips/136



_Code quote:_
```cpp
std::unordered_map
```
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 300 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrCeFw550-zsiCuJp8o:-NrCeFw550-zsiCuJp8p:b8haplk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L300)):*
> ```cpp
>     if (frequency_histogram[i] != 0) {
>       distribution[i] =
>           static_cast<double>(frequency_histogram[i]) / adjusted_total;
> ```

Prefer brace initialization for numeric type conversions. See https://google.github.io/styleguide/cppguide.html#Casting



_Code quote:_
```cpp
static_cast<double>
```

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494)* status: all files reviewed, 9 unresolved discussions (waiting on @kungfucraig and @renjiezh)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 286 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrBeilBEJv-C1BEqrJX:-Nrq_JU43jQl6Yxz_ZeD:b-w300sh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L286)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Yes, that case is okay. If f[0] = 0, we have adjusted_total = max(accumulated_count, register_count), which is not zero. The only case where it's zero is when f[0] = max(register_count, accumulated_count), which suggests that the sketchs are empty.
</blockquote></details>

Can you put this in a comment?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 286 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NrBeilBEJv-C1BEqrJX:-NrqunnW-3QKGSuy-AoY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/539778b4497465714228618451698e2865832a05/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L286)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you put this in a comment?
</blockquote></details>

Done.

**Review by renjiezh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 5 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @ple13, and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 255 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NsQAPRY5PQjWuR_fK0v:-NsQAPRY5PQjWuR_fK0w:b-73cqx2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e88be2dad983711331a50c19abd08fdf55d8c9c8/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L255)):*
> ```cpp
>     }
>     // Adjusts the non empty register count.
>     non_empty_register_count += noise_baseline_per_bucket;
> ```

nip: instead of adjusting it here, can we move `int64_t non_empty_register_count = register_count - frequency_histogram[0];` after the noise adjustment block? 
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 258 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NsQB9gK5u8z7K4w8o3b:-NsQB9gK5u8z7K4w8o3c:bffxzi9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e88be2dad983711331a50c19abd08fdf55d8c9c8/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L258)):*
> ```cpp
> 
>     // Ensures that non_empty_register_count is at least 0.
>     non_empty_register_count = std::max(0L, non_empty_register_count);
> ```

nip: std::clamp might help.
https://en.cppreference.com/w/cpp/algorithm/clamp

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 255 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NsQAPRY5PQjWuR_fK0v:-NsSNo0BEqj-8y2Kkbhj:b-3yrvl6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e88be2dad983711331a50c19abd08fdf55d8c9c8/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L255)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nip: instead of adjusting it here, can we move `int64_t non_empty_register_count = register_count - frequency_histogram[0];` after the noise adjustment block?
</blockquote></details>

There is a subtle difference between this approach and the current one. In your approach, non_empty_register_count may not have the correct distribution as f[0] may have truncated discrete gaussian noise. In order to do it this way, formal proof is needed to show that the truncated discrete gaussian noise does not affect (eps, delta)-DP guarantee. With the current implementation, non_empty_register_count has the correct distribution.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 258 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494#-NsQB9gK5u8z7K4w8o3b:-NsSSg8h1uTs07-bXL9h:bgc3jai) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e88be2dad983711331a50c19abd08fdf55d8c9c8/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L258)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nip: std::clamp might help.
https://en.cppreference.com/w/cpp/algorithm/clamp
</blockquote></details>

std::clamp has a weird return value, which is a reference to either non_empty_register_count, or a reference to the endpoints. We need to declare variables for those endpoints in order to avoid the dangling reference issue (See [go/totw/231](https://goto.google.com/totw/231)). I'd say it's as good to use std::min and std::max.

**Review by renjiezh — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 2 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 3 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1494)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by benjaminkreuter — APPROVED** [review]

**Pull request merged**
