### PR TITLE
Update the mill to enforce consent signaling checks.

### PR DESCRIPTION
**Pull request by wangyaopw**
https://rally1.rallydev.com/#/605340551071d/userstories?detail=%2Fuserstory%2F606022688385

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 17 files at r1, 3 of 5 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198)* status: all files reviewed, 6 unresolved discussions (waiting on @corbantek and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, line 92 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKEXvn9os-wv-RAVw4:-MhKEXvn9os-wv-RAVw5:b8kn65c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L92)):*
> ```Kotlin
>   protected val duchyId: String,
>   protected val keyStore: KeyStore,
>   protected val consentSignalCert: Certificate,
> ```

Just as a side note, I think we were considering 2-4 weeks for certificate rotation (for both consent signaling and TLS). I don't think we've figured out a way to hot-swap the TLS cert to restart all the channels. With this cert also being a startup config param, I guess we're doubly stuck with restarting jobs to rotate certs.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, line 5 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKFgJ5EIolhgfs3pKG:-MhKD2RS8gBTvW5IRayu:b-nb93ci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel#L5)):*
> ```
>     default_testonly = True,  #TODO: delete when InMemoryKeyStore and FakeHybridCipher are not used.
> ```

nit: Put this on the specific target. Putting it on the package is for when it's e.g. a `testing` package where we know all the targets should be testonly. In this case, it's a specific temporary exception.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 327 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKSsjs2iZ0IXVMUr1R:-MhKSsjs2iZ0IXVMUr1S:b-rvx6xo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L327)):*
> ```
> ${errorList.joinToString(separator = "\n")}
> ```
nit: unnecessary use of string interpolation with a complex expression

You're already doing string concatenation for this part.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 278 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKVBkeAOm1N7Tr9Wun:-MhKVBkeAOm1N7Tr9Wuo:b-a35lxj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L278)):*
> ```Kotlin
>       )
>   )
> // A key and its pre-computed signature used purely for consent signaling check.
> ```

minor: use KDoc syntax when documenting properties
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 526 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKXRtm4pyFbijrkXKD:-MhKXRtm4pyFbijrkXKE:baw1q3b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L526)):*
> ```
> setup
> ```
nit: more descriptive name
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 527 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKVu1-67MPpYXtgDSD:-MhKVu10C5LD6YMQfzAi:b7f6lnk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L527)):*
> ```Kotlin
>   @Before
>   fun setup() = runBlocking {
>     whenever(runBlocking { mockLiquidLegionsComputationControl.advanceComputation(any()) })
> ```

Does this stubbing need to be done in an `@Before` method (e.g. because it depends on a rule), or can it be done at mock declaration instead?

e.g. something like

```
  private val mockLiquidLegionsComputationControl: ComputationControlCoroutineImplBase =
    mock(useConstructor = UseConstructor.parameterless()) {
      onBlocking(mockLiquidLegionsComputationControl.advanceComputation(any())) {
        // doAnswer(...)
      }
    }
```
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 1759 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKXhjkED5s4Ylp5fo2:-MhKXhjkED5s4Ylp5fo3:b-2uhfaq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L1759)):*
> ```
> encrytion
> ```
nit: encryption

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198)* status: all files reviewed, 3 unresolved discussions (waiting on @corbantek and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, line 92 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKEXvn9os-wv-RAVw4:-MhLKU4sCkN069XDKCal:b-5gbor9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L92)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just as a side note, I think we were considering 2-4 weeks for certificate rotation (for both consent signaling and TLS). I don't think we've figured out a way to hot-swap the TLS cert to restart all the channels. With this cert also being a startup config param, I guess we're doubly stuck with restarting jobs to rotate certs.
</blockquote></details>

Not sure how to hot-swap the TLS cert, but for the consentSignaling cert, we can just have the mill to call the kingdom to get my preferred/latest cert (name) when needed, and then read from KMS. No need to have the consentSignaling Cert as startup config param.

Restarting jobs to rotate certs is the easiest way anyway.  All jobs can restart daily on workdays, similar to Google's boq daily release.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, line 5 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKFgJ5EIolhgfs3pKG:-MhLMABA93OshI6olw0r:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     default_testonly = True,  #TODO: delete when InMemoryKeyStore and FakeHybridCipher are not used.
> ```

nit: Put this on the specific target. Putting it on the package is for when it's e.g. a `testing` package where we know all the targets should be testonly. In this case, it's a specific temporary exception.
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 327 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKSsjs2iZ0IXVMUr1R:-MhLMnJr8TCDLrdmkbSG:b40w3sh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L327)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ${errorList.joinToString(separator = "\n")}
> ```
nit: unnecessary use of string interpolation with a complex expression

You're already doing string concatenation for this part.
</blockquote></details>

Done. Nice catch
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 278 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKVBkeAOm1N7Tr9Wun:-MhLNmim4E0IaN0AZJmi:b-zbzzgz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L278)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

minor: use KDoc syntax when documenting properties
</blockquote></details>

This comment was for two variables. A little confusing. I broke it into two comments.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 526 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKXRtm4pyFbijrkXKD:-MhLO2W77oicL7GmMPqZ:b-k9hl2v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L526)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> setup
> ```
nit: more descriptive name
</blockquote></details>

I thought setup is one of the default names. basically means everything before the actual test code.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 527 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKVu1-67MPpYXtgDSD:-MhLQ_ZT4r5D8JRrmiP1:b-h2b5as) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L527)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does this stubbing need to be done in an `@Before` method (e.g. because it depends on a rule), or can it be done at mock declaration instead?

e.g. something like

```
  private val mockLiquidLegionsComputationControl: ComputationControlCoroutineImplBase =
    mock(useConstructor = UseConstructor.parameterless()) {
      onBlocking(mockLiquidLegionsComputationControl.advanceComputation(any())) {
        // doAnswer(...)
      }
    }
```
</blockquote></details>

Moved to mock declaration, tests still pass. I guess I'll just always do this at mock declaration in the future expect for test specific mock response.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 1759 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKXhjkED5s4Ylp5fo2:-MhLQyyMA-5DFH0r_WSt:bcgnx6m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L1759)):*
> encrytion
Done

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 278 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKVBkeAOm1N7Tr9Wun:-MhLVImJ9iAfCIOaTox_:b4naiuw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L278)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

This comment was for two variables. A little confusing. I broke it into two comments.
</blockquote></details>

Those are still properties rather than variables and should use KDoc syntax for each.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 526 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKXRtm4pyFbijrkXKD:-MhLVR7KBvzzzPTgIh6Y:b-j8sgz4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L526)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I thought setup is one of the default names. basically means everything before the actual test code.
</blockquote></details>

"setUp" is a holdover from JUnit3 where you had to have a specific method name in order for it to be called by the test runner. JUnit4+ uses `@Before` annotations instead, allowing you to have multiple granular methods that are called prior to running the test methods. As a result, each annotated method should have a descriptive name.

Note that the relative order that `@Before` methods are called is undefined.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 527 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKVu1-67MPpYXtgDSD:-MhLWZ9ICxPEmucCc_25:b-nx8sl7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L527)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Moved to mock declaration, tests still pass. I guess I'll just always do this at mock declaration in the future expect for test specific mock response.
</blockquote></details>

Yeah. It basically helps keep each `@Before` method more focused, and has slightly less verbose syntax as an added bonus :)

**Review by corbantek — COMMENTED** [review]
> Reviewed 8 of 17 files at r1, 3 of 5 files at r2, 7 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 270 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhLscyI8ZOLcKbWUNZV:-MhLscyI8ZOLcKbWUNZW:b-d1tuvr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L270)):*
> ```Kotlin
>   ByteString.copyFromUtf8("some-serialized-measurement-spec")
> /** This is pre-calculated using a fixed certificate from common-jvm. */
> private val DATA_PROVIDER_SIGNATURE: ByteString =
> ```

Would it be better to not use Fixed Certs and generate the signature from the Data Provider dynamically before running the tests?  So we aren't reliant on those fixed certs and this special signature (in case later we want to add more items to the RequisitionSpec?)
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 526 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKXRtm4pyFbijrkXKD:-MhLsDTiAibc5xMBQzYd:b-jxfnv8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L526)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

"setUp" is a holdover from JUnit3 where you had to have a specific method name in order for it to be called by the test runner. JUnit4+ uses `@Before` annotations instead, allowing you to have multiple granular methods that are called prior to running the test methods. As a result, each annotated method should have a descriptive name.

Note that the relative order that `@Before` methods are called is undefined.
</blockquote></details>

@Before also runs before each test, is this intended to setup for all test or does it need to re-initialize before each test? If its the former maybe use @BeforeClass

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 270 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhLscyI8ZOLcKbWUNZV:-MhPRpLF0gsIXuTWHYAy:b-pums1t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L270)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Would it be better to not use Fixed Certs and generate the signature from the Data Provider dynamically before running the tests?  So we aren't reliant on those fixed certs and this special signature (in case later we want to add more items to the RequisitionSpec?)
</blockquote></details>

I started in that way. But then I need to initialize the keystore first and store the private key inside before I can call Encrypt using the key and cert, which means I need to move the assignment of the signature somewhere else maybe in a @Before or @BeforeClass. Then I just feel defining the signature as constant using pre-calculated value is simpler. 
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 278 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKVBkeAOm1N7Tr9Wun:-MhPTfjAA_BSSnsf2sHM:b-ss66ix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L278)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Those are still properties rather than variables and should use KDoc syntax for each.
</blockquote></details>

you mean using /** */? oh Done now
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 526 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198#-MhKXRtm4pyFbijrkXKD:-MhPUf8D1VF7Aldt-juO:b6j3nj6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4dab313bc3bcc009044fca9dadcbeb177bbd/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L526)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

@Before also runs before each test, is this intended to setup for all test or does it need to re-initialize before each test? If its the former maybe use @BeforeClass
</blockquote></details>

It is more of initializing the test object, i.e., mills. Only the line of storing the private key to keystore is suitable for putting in the @BeforeClass I guess. I'd rather save the trouble creating a companion object here anyway since it doesn't matter much.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek and @SanjayVas)

**Review by corbantek — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
