### PR TITLE
Add etag support to system ComputationParticipant.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1654)

**Review by renjiezh — CHANGES_REQUESTED** [review]
> Reviewed 4 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1654)* status: 4 of 30 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 400 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1654#-O-2t8hg0vnC9_JmJxlt:-O-2t8hh88xxX-tiudoP:bs7vo9q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50542a5b8e5f97270f864762aec56a5b1634ecfa/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L400)):*
> ```Kotlin
> ) : KingdomInternalException(ErrorCode.MEASUREMENT_ETAG_MISMATCH, message) {
>   override val context
>     get() = mapOf("actual_etag" to actualETag, "request_etag" to requestETag)
> ```

Is it possible to add the participant State into the context? So that the duchy can skip the rpc call if it is duplicated.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1654)* status: 4 of 30 files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 400 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1654#-O-2t8hg0vnC9_JmJxlt:-O-2wt4xAJuLFqb5hZkN:b-58vfgz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50542a5b8e5f97270f864762aec56a5b1634ecfa/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L400)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Is it possible to add the participant State into the context? So that the duchy can skip the rpc call if it is duplicated.
</blockquote></details>

The context should just be the variables of the error message. It shouldn't be used to pass resource info. If the caller wants the state, it should do another read.

**Review by renjiezh — APPROVED** [review]
> Reviewed 26 of 30 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1654)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Comment by SanjayVas** [comment]
Depends on #1664

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 25 of 30 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1654)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ETags.kt` line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1654#-O-b0RO61vd4KFtDbmdh:-O-b0RO61vd4KFtDbmdi:bhwa6fo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c861e93f1e7414b9251e2efafd97c7b9f72e87b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ETags.kt#L22)):*
> ```Kotlin
> import org.wfanet.measurement.gcloud.common.toInstant
> 
> object ETags {
> ```

why this duplicate object? that just calls common?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1654)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ETags.kt` line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1654#-O-b0RO61vd4KFtDbmdh:-O-bIIWu5oPbTSWkCsun:b-3lqkbl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c861e93f1e7414b9251e2efafd97c7b9f72e87b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ETags.kt#L22)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why this duplicate object? that just calls common?
</blockquote></details>

This version is for `com.google.cloud.Timestamp`, which is currently only used for Spanner. The top-level common shouldn't have that dependency

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1654)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
