### PR TITLE
Suppress all exceptions in the mill loop processing.

### PR DESCRIPTION
**Pull request by wangyaopw**
The spanner emulator has transicent errors not caught in the integration
  test, which kills the mill. This PR would prevent such transient/retriable
  errors from crashing the mill and breaking the
  GCloudInProcessLifeOfAMeasurementIntegrationTest.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, line 125 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364#-Mo_Hqpw1J9oSUlBtuGF:-Mo_HqpxBWJSa_P5lRAd:b-7mv3dt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df022777af9e8d0705b9dea79ea180750de51bb9/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L125)):*
> ```
> claimWork(
> ```
For example, exception from claimWork() is not suppressed in the old code.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @chipingyeh and @wangyaopw)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364#-Mo_JYPX-q65g704Z29I):*
> ```
>   test, which kills the mill. This PR should fix the TIMEOUT issue of the
>   GCloudInProcessLifeOfAMeasurementIntegrationTest.
> ```
The timestamp issue you mentioned before is still a bug, even if it's transient. Clarify that this is preventing such transient/retriable errors from crashing the mill and breaking the test, but that we still need to address such errors that are unexpected.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, line 168 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364#-Mo_JCet6xRxu_-2YQjQ:-Mo_JCet6xRxu_-2YQjR:b1mzhxt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df022777af9e8d0705b9dea79ea180750de51bb9/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L168)):*
> ```
>         // Treat all other errors as transient.
> ```
Not this PR, but I think that PERMANENT should be the default as that's safer than retrying forever. TRANSIENT should only be the things that we know are retriable.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, line 169 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364#-Mo_J2W0DrksoYlY75gl:-Mo_J2W1C-jfHR0_GCRy:bqfangg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df022777af9e8d0705b9dea79ea180750de51bb9/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L169)):*
> ```
> Level.SEVERE
> ```
WARNING maybe?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @chipingyeh and @SanjayVas)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364#-Mo_JYPX-q65g704Z29I):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>   test, which kills the mill. This PR should fix the TIMEOUT issue of the
>   GCloudInProcessLifeOfAMeasurementIntegrationTest.
> ```
The timestamp issue you mentioned before is still a bug, even if it's transient. Clarify that this is preventing such transient/retriable errors from crashing the mill and breaking the test, but that we still need to address such errors that are unexpected.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, line 168 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364#-Mo_JCet6xRxu_-2YQjQ:-Mo_N4MD-5CJWAJhLtrw:b2x4cf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df022777af9e8d0705b9dea79ea180750de51bb9/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L168)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>         // Treat all other errors as transient.
> ```
Not this PR, but I think that PERMANENT should be the default as that's safer than retrying forever. TRANSIENT should only be the things that we know are retriable.
</blockquote></details>

Depends on what you mean by "safer". I would think "safer" indicates that the system tries its best to finish the computation, and don't quit unless we know for sure the error is permanent.

If the default is PERMANENT, then we need to exhaustedly list all possible transient failures here, for example, retriable RPC failures, OOM, etc. If we miss something, there will be unnecessarily failed computations. 

If the default is TRANSIENT, the worst case is that the mill retries and fail many times until we notice it. Possibly we should add a MAXIMUM_RETRY_TIMES to all computations to prevent this.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, line 169 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364#-Mo_J2W0DrksoYlY75gl:-Mo_MC7a3f6Sc3r5HFs1:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df022777af9e8d0705b9dea79ea180750de51bb9/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L169)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Level.SEVERE
> ```
WARNING maybe?
</blockquote></details>

Done

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, line 168 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364#-Mo_JCet6xRxu_-2YQjQ:-Mo_tsr16Jkww2n36Wkb:byc9nwv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df022777af9e8d0705b9dea79ea180750de51bb9/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L168)):*
> If the default is TRANSIENT, the worst case is that the mill retries and fail many times until we notice it. Possibly we should add a MAXIMUM_RETRY_TIMES to all computations to prevent this.

+1 for having a max retries.

> Depends on what you mean by "safer". I would think "safer" indicates that the system tries its best to finish the computation, and don't quit unless we know for sure the error is permanent.
>
> If the default is PERMANENT, then we need to exhaustedly list all possible transient failures here, for example, retriable RPC failures, OOM, etc. If we miss something, there will be unnecessarily failed computations.

I'm thinking of this the same way as gRPC retriability. The common practice is to be conservative on retries, and only retry when there's known to be no risk of ending up in a bad state (e.g. reattempting a non-idempotent operation). You try to get everything to the right canonical error code, where`UNKNOWN` it not retriable.

That said, if the design of the protocols are such that there shouldn't be a way for Mill operations to put things into a non-retriable state then having the default be to retry is fine as long as there's a max to prevent the equivalent of an infinite loop. Feel free to leave a TODO for this.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, line 168 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364#-Mo_JCet6xRxu_-2YQjQ:-MoaCQgG7CvWYALfEw-t:b-ntxtet) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df022777af9e8d0705b9dea79ea180750de51bb9/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L168)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> If the default is TRANSIENT, the worst case is that the mill retries and fail many times until we notice it. Possibly we should add a MAXIMUM_RETRY_TIMES to all computations to prevent this.

+1 for having a max retries.

> Depends on what you mean by "safer". I would think "safer" indicates that the system tries its best to finish the computation, and don't quit unless we know for sure the error is permanent.
>
> If the default is PERMANENT, then we need to exhaustedly list all possible transient failures here, for example, retriable RPC failures, OOM, etc. If we miss something, there will be unnecessarily failed computations.

I'm thinking of this the same way as gRPC retriability. The common practice is to be conservative on retries, and only retry when there's known to be no risk of ending up in a bad state (e.g. reattempting a non-idempotent operation). You try to get everything to the right canonical error code, where`UNKNOWN` it not retriable.

That said, if the design of the protocols are such that there shouldn't be a way for Mill operations to put things into a non-retriable state then having the default be to retry is fine as long as there's a max to prevent the equivalent of an infinite loop. Feel free to leave a TODO for this.
</blockquote></details>

Added TA227 to add a maximum retry limit at the mill.

**Review by chipingyeh — APPROVED** [review]

**Review by chipingyeh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @SanjayVas)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
