### PR TITLE
SimpleReport CLI tool can list and get

### PR DESCRIPTION
**Pull request by renjiezh**
Also added types of Measurement

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)

### CODE REVIEW

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 134 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3_MVwg6b5W8u4BYzwB:-N3_YPxr9DXCjuDinDOi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65347da99e9d8108814b5433474ece901f79b98b/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L134)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add `private set` to all of these vars that cannot be private.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3_N82P5cCdf2MLAKUf:-N3__Vrs2pMf3Rqf7wAY:b-t74ntb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65347da99e9d8108814b5433474ece901f79b98b/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L142)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use `Delegates.byNotNull` delegate. This gives similar behavior as `lateinit` but for primitives, namely that we want it to be an error if it isn't initialized by Picocli.

The only time where we use a plain initialized `var` is when the flag is optional but the default cannot be represented by `defaultValue`, e.g. for Strings where we want empty string and null to have distinct meaning.
</blockquote></details>

Unfortunately decorator `@Option` cannot be applied to Delegates.notNull(). Thus I assigned default values to them and removed the `defaultValue`
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3_OVwo4pA-roMOi9Uu:-N3_xcNa3O9hlZSJbhHS:b-4vbosl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65347da99e9d8108814b5433474ece901f79b98b/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L171)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It should be clear that these are only used for impression and duration measurements.

Maybe it would be clearer to organize this with arg groups. You could have a mutually-exclusive group of mutually-dependent groups. Instead of an enum, you can have a boolean option within each of the groups.

e.g. `--reach-and-frequency --reach-epsilon=1.0`
</blockquote></details>

Done. Now have 3 ArgGroups representing 3 types. They are mutually exclusive.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3_N82P5cCdf2MLAKUf:-N3aYpG56xpYCXe8ucK6:b-gp2te7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65347da99e9d8108814b5433474ece901f79b98b/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L142)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That is definitely not true, as we use it elsewhere. You just may need to add `set:` to the annotation to indicate that it applies to the property setter. 

e.g. from FrontendSimulatorFlags:

```
@set:CommandLine.Option(
    names = ["--output-differential-privacy-epsilon"],
    description = ["The common epsilon used for all output's differential privacy noises."],
    required = true
  )
  var outputDpEpsilon by Delegates.notNull<Double>()
    private set
```
</blockquote></details>

Done.
Thanks for letting me know

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 472 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3aro713T8EFkeZiFIP:-N3aro713T8EFkeZiFIQ:b-naurbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53287b43cdbcbd47983e28f00e93bed48dc3792c/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L472)):*
> ```Kotlin
>     print(response)
> 
>     parent.channel.shutdown()
> ```

You shouldn't need to do this explicitly. Use `withShutdownTimeout` when instantiating the channel to add a hook that will take care of shutting down the channel on JVM shutdown.



_Code quote:_
```Kotlin
    parent.channel.shutdown()
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 472 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3aro713T8EFkeZiFIP:-N3axc4Z4ijp42u9wD9V:b-g7rryn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53287b43cdbcbd47983e28f00e93bed48dc3792c/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L472)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You shouldn't need to do this explicitly. Use `withShutdownTimeout` when instantiating the channel to add a hook that will take care of shutting down the channel on JVM shutdown.
</blockquote></details>

Done.
It works!

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli and @tristanvuong2021)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md` line 100 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3ezzxd2Jxkog37TPiN:-N3ezzxd2Jxkog37TPiO:berw1f5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecd96a26a21374e2af5a773a55b4a181edbaa56e/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md#L100)):*
> ```Markdown
>   --measurement-consumer=measurementConsumers/777 \
>   --reach-and-frequency \
>   --reach-privacy-epsilon=2.0 \
> ```

for all of these, can you put default values that are recommended? I believe @uakyol or @matthewclegg could help with that

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @matthewclegg, @riemanli, @SanjayVas, @stevenwarejones, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md` line 100 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3ezzxd2Jxkog37TPiN:-N3fTuQy2YYRWmtMor-U:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecd96a26a21374e2af5a773a55b4a181edbaa56e/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md#L100)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

for all of these, can you put default values that are recommended? I believe @uakyol or @matthewclegg could help with that
</blockquote></details>

Done.

**Review by matthewclegg — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @matthewclegg, @renjiezh, @riemanli, @SanjayVas, @stevenwarejones, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md` line 104 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3kWpts81J3hv77-pQm:-N3kWpts81J3hv77-pQn:bsndnct) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md#L104)):*
> ```Markdown
>   --frequency-privacy-epsilon=0.115 \
>   --frequency-privacy-delta=0.0 \
>   --vid-sampling-start=48.0 \
> ```

vid-sampling-start and width should be real numbers between 0 and 1. In this example, you might choose vid-sampling-start = 48.0/300.0 = 0.16. For reach and frequency queries, the recommended width is 5 buckets, e.g., 5.0/300. = 0.016666.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 191 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3kXAKJA9ivU_nekxoS:-N3kXAKJA9ivU_nekxoT:bejwvf3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L191)):*
> ```Kotlin
>     }
> 
>     class ImpressionParams {
> ```

This should also have a vid-sampling-start and vid-sampling-width.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 225 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3kXBw245coI-jrXts5:-N3kXBw245coI-jrXts6:bejwvf3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L225)):*
> ```Kotlin
>     }
> 
>     class DurationParams {
> ```

This should also have a vid-sampling-start and vid-sampling-width.
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReportTest.kt` line 434 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3kXcylBLMhtHI5YE8O:-N3kXcylBLMhtHI5YE8P:bcdf3ev) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReportTest.kt#L434)):*
> ```Kotlin
>         "--measurement-consumer=measurementConsumers/777",
>         "--reach-and-frequency",
>         "--reach-privacy-epsilon=2.0",
> ```

vid-sampling-start and vid-sampling-width should be between 0 and 1 and should sum to a value no more than 1.  Epsilon is usually a number that is between 0.001 and 0.1.  Delta is usually a very small number, often either 0 or 1.0e-9.

**Review by matthewclegg — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @matthewclegg, @renjiezh, @riemanli, @SanjayVas, @stevenwarejones, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md` line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3k_Rir0Ti4t2zC5P2x:-N3k_Ris5MinCx72PZSL:b-aqt4ym) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md#L60)):*
> ```Markdown
> See the [Examples](##Examples) section below.
> 
> ### List
> ```

One thing that I think would be really useful in this tool would be to have the ability to list (or search) the available event groups for a given EDP.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @matthewclegg, @riemanli, @SanjayVas, @stevenwarejones, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md` line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3k_Rir0Ti4t2zC5P2x:-N3qkUEI6_8Tw8PxSzS0:buqv7nk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md#L60)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

One thing that I think would be really useful in this tool would be to have the ability to list (or search) the available event groups for a given EDP.
</blockquote></details>

Yeah, I can add that sub-command in the next PR.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md` line 104 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3kWpts81J3hv77-pQm:-N3qk2td8EehI6gaVtO9:bl7p1s4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md#L104)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

vid-sampling-start and width should be real numbers between 0 and 1. In this example, you might choose vid-sampling-start = 48.0/300.0 = 0.16. For reach and frequency queries, the recommended width is 5 buckets, e.g., 5.0/300. = 0.016666.
</blockquote></details>

Done.
Thanks for pointing that.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 191 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3kXAKJA9ivU_nekxoS:-N3qkFZj9phP1oEnGFFz:bqqe0wh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L191)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

This should also have a vid-sampling-start and vid-sampling-width.
</blockquote></details>

From the .proto I did not see the vid-sampling params. How do we add it to the request?
https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L56-L69
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 225 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3kXBw245coI-jrXts5:-N3qkQaE2cNaEvvHaqTH:b-jusu5n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L225)):*
> From the .proto I did not see the vid-sampling params. How do we add it to the request?
> https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L56-L69
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReportTest.kt` line 434 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3kXcylBLMhtHI5YE8O:-N3qmX0gAlmzP5i9UoXu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReportTest.kt#L434)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

vid-sampling-start and vid-sampling-width should be between 0 and 1 and should sum to a value no more than 1.  Epsilon is usually a number that is between 0.001 and 0.1.  Delta is usually a very small number, often either 0 or 1.0e-9.
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @matthewclegg, @riemanli, @SanjayVas, @stevenwarejones, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 191 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3kXAKJA9ivU_nekxoS:-N3uGNM4DQVSkIxp8O2U:bkhriw4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L191)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

From the .proto I did not see the vid-sampling params. How do we add it to the request?
https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L56-L69
</blockquote></details>

@matthewclegg The options are in the parent `MeasurementParams` class, which matches where they exist in the `MeasurementSpec` message. That is to say that according to the API, these params are specified regardless of the measurement type.

See https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/104 which added them there.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 225 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3kXBw245coI-jrXts5:-N3uH3vME-6vs0k518NV:bp02iwo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L225)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

> From the .proto I did not see the vid-sampling params. How do we add it to the request?
> https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L56-L69

</blockquote></details>

See above response.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @matthewclegg, @riemanli, @SanjayVas, @stevenwarejones, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 191 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3kXAKJA9ivU_nekxoS:-N3uO7Ab98SgcldHmU2g:blipelf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L191)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@matthewclegg The options are in the parent `MeasurementParams` class, which matches where they exist in the `MeasurementSpec` message. That is to say that according to the API, these params are specified regardless of the measurement type.

See https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/104 which added them there.
</blockquote></details>

Got it. Please let me bump the api-repo version and fix all vid sampling params in a separated PR.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 225 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581#-N3kXBw245coI-jrXts5:-N3uO68KAPUGio7bgeTm:b-4hvi0m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27587ea271f40af1b5de6ea725f8eeca572aba2a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L225)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

See above response.
</blockquote></details>

Got it.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: all files reviewed, 5 unresolved discussions (waiting on @matthewclegg, @riemanli, @SanjayVas, and @tristanvuong2021)

**Review by matthewclegg — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/581)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

**Pull request merged**
