### PR TITLE
Drop the Provider message type from the internal API.

### PR DESCRIPTION
**Pull request by SanjayVas**
This is a vestige of an old attempt to unify auth/access for ModelProvider and DataProvider principals. It is inconsistent with newer code.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1292)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 40 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1292)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt` line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1292#-NgbjxazBqq9hClN62nc:-NgbjxazBqq9hClN62nd:ba9trx2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff4b0edd948050a476f80945fd5e4211fa5c1fe4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L88)):*
> ```Kotlin
>           mutableListOf(
>             "State = @${Params.RECURRING_EXCHANGE_STATE}",
>             "NextExchangeDate <= CURRENT_DATE('+0')",
> ```

NIT: Is ```+0``` for readability? I think it's redudant



_Code quote:_
```Kotlin
CURRENT_DATE('+0')
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt` line 216 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1292#-NgbkOOjAi8bOHYk-U_1:-NgbkOOk6kgGubD5iJ_6:bcv800q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff4b0edd948050a476f80945fd5e4211fa5c1fe4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L216)):*
> ```Kotlin
>       is AccountPrincipal,
>       is DuchyPrincipal,
>       is MeasurementConsumerPrincipal -> throw permissionDeniedStatus().asRuntimeException()
> ```

Why don't use ```else``` here, to better support other Principals we may have (eg. due to refactor) in future?



_Code quote:_
```Kotlin
      is AccountPrincipal,
      is DuchyPrincipal,
      is MeasurementConsumerPrincipal -> throw permissionDeniedStatus().asRuntimeException()
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1292)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt` line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1292#-NgbjxazBqq9hClN62nc:-NgdxU-_2F8BzRcEKy6V:b-t7jcpc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff4b0edd948050a476f80945fd5e4211fa5c1fe4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L88)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

NIT: Is ```+0``` for readability? I think it's redudant
</blockquote></details>

According to the docs, if you don't specify a time zone of offset then it defaults to `America/Los_Angeles`. Therefore the `+0` is necessary to indicate UTC.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt` line 216 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1292#-NgbkOOjAi8bOHYk-U_1:-Ngdxp_I4s6mH4WL2C00:bncaygx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff4b0edd948050a476f80945fd5e4211fa5c1fe4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L216)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Why don't use ```else``` here, to better support other Principals we may have (eg. due to refactor) in future?
</blockquote></details>

MeasurementPrincipal is a sealed interface. so the Kotlin compiler will enforce exhaustive `when`. Any PR that introduces a new principal will be forced to consider and update this code.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> Dismissed @Marco-Premier from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 35 of 40 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
