### PR TITLE
Implement internal FulfillRequisition method.

### PR DESCRIPTION
**Pull request by SanjayVas**
https://rally1.rallydev.com/#/604612930531d/tasks?detail=%2Ftask%2F607707408811&fdp=true?fdp=true

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-MieN0FV4Ra6BV_-pXjW:-MieN0FW-12RwLzbXwLN:b-ex2qn7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a6e469cf97c5cb732caa2b701abbf2b7a4142c2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L39)):*
> ```
> FulfillRequisition
> ```

If this is the last unfulfilled requisition, we need to transit the measurement from `PENDING_REQUISITION_FULFILLMENT` to `PENDING_PARTICIPANT_CONFIRMATION`.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-MieN0FV4Ra6BV_-pXjW:-MigNOik2jgx93V_CsCN:b-jzsl1r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a6e469cf97c5cb732caa2b701abbf2b7a4142c2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L39)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> FulfillRequisition
> ```

If this is the last unfulfilled requisition, we need to transit the measurement from `PENDING_REQUISITION_FULFILLMENT` to `PENDING_PARTICIPANT_CONFIRMATION`.
</blockquote></details>

Good catch! Working on that.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-MieN0FV4Ra6BV_-pXjW:-Mih2FFRDwKWJKR261F5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c77711597f9b5a180ed4d04acf6aa6f97ccf1a1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Good catch! Working on that.
</blockquote></details>

Done.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 84 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-MihMjBp16vDzEK33ZGQ:-MihMjBq57PCKkBILfWK:bn12p33) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41a0a9793a5ec28d842ace20a6752b5d421d568c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L84)):*
> ```
>       if (updatedMeasurementState != null) {
>         parentMeasurement = parentMeasurement.copy { this.state = updatedMeasurementState }
>       }
> ```

does 
```
      if (nonFulfilledRequisitionIds.singleOrNull() == requisitionId) {
          // All other Requisitions are already FULFILLED, so update Measurement state.
          Measurement.State.PENDING_PARTICIPANT_CONFIRMATION.also {
            updateMeasurementState(measurementConsumerId, measurementId, it)
          }
          parentMeasurement = parentMeasurement.copy { this.state = updatedMeasurementState }
      }

```
work?

i.e., removing the updatedMeasurementState variable.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 566 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-MihNXId7w7scd1h8LQ9:-MihNXId7w7scd1h8LQA:bcgpisg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41a0a9793a5ec28d842ace20a6752b5d421d568c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L566)):*
> ```Kotlin
>           }
>         )
>       )
> ```

maybe also call getMeasurement() to make sure the measurement is indeed in PENDING_PARTICIPANT_CONFIRMATION)?

The parentMeasurementState is just something we wrote to the response, not the actual state of the measurement.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 84 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-MihMjBp16vDzEK33ZGQ:-MihRsxp6nhWNdCDzuJj:b-1egcin) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41a0a9793a5ec28d842ace20a6752b5d421d568c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L84)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>       if (updatedMeasurementState != null) {
>         parentMeasurement = parentMeasurement.copy { this.state = updatedMeasurementState }
>       }
> ```

does 
```
      if (nonFulfilledRequisitionIds.singleOrNull() == requisitionId) {
          // All other Requisitions are already FULFILLED, so update Measurement state.
          Measurement.State.PENDING_PARTICIPANT_CONFIRMATION.also {
            updateMeasurementState(measurementConsumerId, measurementId, it)
          }
          parentMeasurement = parentMeasurement.copy { this.state = updatedMeasurementState }
      }

```
work?

i.e., removing the updatedMeasurementState variable.
</blockquote></details>

It technically does, but it's a bad practice to do work such as buffering another update mutation inside of a DSL builder scope.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 566 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-MihNXId7w7scd1h8LQ9:-MihSpI-BHj3bYYfqg-1:b-qcehs0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41a0a9793a5ec28d842ace20a6752b5d421d568c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L566)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

maybe also call getMeasurement() to make sure the measurement is indeed in PENDING_PARTICIPANT_CONFIRMATION)?

The parentMeasurementState is just something we wrote to the response, not the actual state of the measurement.
</blockquote></details>

It's covered by comparing to the response of the separate getRequisition call, which includes parentMeasurement. This way we ensure that the value was actually written to the DB, as getRequisition can't just pull the value out of thin air.

**Review by wangyaopw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-:-MihTqH4AfCNntY_iKOZ:bnfp4nl)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 84 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-MihMjBp16vDzEK33ZGQ:-MihTx-p-oEJz5gSfinM:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41a0a9793a5ec28d842ace20a6752b5d421d568c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L84)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It technically does, but it's a bad practice to do work such as buffering another update mutation inside of a DSL builder scope.
</blockquote></details>

sg
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 566 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-MihNXId7w7scd1h8LQ9:-MihU1uUCctl895dsNNx:batgv01) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41a0a9793a5ec28d842ace20a6752b5d421d568c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L566)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's covered by comparing to the response of the separate getRequisition call, which includes parentMeasurement. This way we ensure that the value was actually written to the DB, as getRequisition can't just pull the value out of thin air.
</blockquote></details>

oh, I didn't see the getRequestion() call. That is good

**Review by wangyaopw — APPROVED** [review]
> Reviewed 4 of 12 files at r1, 4 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-Mih_OPN1kOsqPFaEF3J:-Mih_OPN1kOsqPFaEF3K:b2te68p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41a0a9793a5ec28d842ace20a6752b5d421d568c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L71)):*
> ```
>         Measurement.State.PENDING_PARTICIPANT_CONFIRMATION.also {
>           updateMeasurementState(measurementConsumerId, measurementId, it)
>         }
> ```

this will revive a cancelled measurement. so we may want to check the measurement state before fulfilling it, i.e., only fulfill if the measurement is at `PENDING_REQUISITION_FULFILLMENT` and the requisition is `UNFULFILLED`

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-Mih_OPN1kOsqPFaEF3J:-MihcDoL7EIHx00orsZb:b-io6di0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41a0a9793a5ec28d842ace20a6752b5d421d568c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L71)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>         Measurement.State.PENDING_PARTICIPANT_CONFIRMATION.also {
>           updateMeasurementState(measurementConsumerId, measurementId, it)
>         }
> ```

this will revive a cancelled measurement. so we may want to check the measurement state before fulfilling it, i.e., only fulfill if the measurement is at `PENDING_REQUISITION_FULFILLMENT` and the requisition is `UNFULFILLED`
</blockquote></details>

Yeah, I was starting to implement that. I need confirmComputationParticipant to be implemented in order to get the Measurement into the right state for the test. Therefore, this is currently blocked on #226. @uakyol

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-Mih_OPN1kOsqPFaEF3J:-MihcpL-A5vtJ9B1eMep:bb7lbs2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41a0a9793a5ec28d842ace20a6752b5d421d568c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yeah, I was starting to implement that. I need confirmComputationParticipant to be implemented in order to get the Measurement into the right state for the test. Therefore, this is currently blocked on #226. @uakyol 
</blockquote></details>

nice

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-Mih_OPN1kOsqPFaEF3J:-Mihd6GZ693JXiksWvhH:b-d0cuwm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41a0a9793a5ec28d842ace20a6752b5d421d568c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L71)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

nice
</blockquote></details>

Nevermind, what I need is setRequisitionParams. Working on this change.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: 3 of 13 files reviewed, all discussions resolved (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-Mih_OPN1kOsqPFaEF3J:-Mihf-YSA3LdBpp7apZg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41a0a9793a5ec28d842ace20a6752b5d421d568c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Nevermind, what I need is setRequisitionParams. Working on this change.
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 3 of 12 files at r1, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek, @uakyol, and @zachcwc)

**Review by corbantek — APPROVED** [review]
:lgtm:

> Reviewed 3 of 12 files at r1, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249#-:-Mj-c6mY9dG1O9JqSd1T:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol and @zachcwc)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 12 files at r1, 3 of 10 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol and @zachcwc)

**Comment by SanjayVas** [comment]
This is for #103.

**Pull request merged**
