### PR TITLE
Update CLI tool to create account, mc_creation_token, and data_provider

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: all files reviewed, 4 unresolved discussions (waiting on @renjiezh)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 123 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv-uUTT4Z8MLXv2PeXx:-Mv-uUTT4Z8MLXv2PeXy:b-f8ai63) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10ef1db675a0ab9109296fae8a585d4257456bdc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L123)):*
> ```Kotlin
>     val internalAccount = runBlocking { internalAccountsClient.createAccount(account {}) }
>     val accountName = AccountKey(externalIdToApiId(internalAccount.externalAccountId)).toName()
>     println(accountName)
> ```

This also needs to print out the activation token.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 129 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv-ux89E-7T8nR8vb0Z:-Mv-ux89E-7T8nR8vb0_:brsctwh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10ef1db675a0ab9109296fae8a585d4257456bdc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L129)):*
> ```Kotlin
> }
> 
> @Command(name = "mc_creation_token", description = ["Get a Measurement Consumer Creation Token"])
> ```

Create



_Code quote:_
```Kotlin
Get
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 130 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv-tamG4LhNsMHJhP_A:-Mv-tamG4LhNsMHJhP_B:b-rn3gph) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10ef1db675a0ab9109296fae8a585d4257456bdc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L130)):*
> ```Kotlin
> 
> @Command(name = "mc_creation_token", description = ["Get a Measurement Consumer Creation Token"])
> private class CreateMCCreationTokenCommand : CreatePrincipalCommand() {
> ```

This shouldn't extend from CreatePrincipalCommand, as an MC creation token is not a Principal, and has no encryption key, etc.



_Code quote:_
```Kotlin
CreatePrincipalCommand
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 130 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv-uCkD22y1a51Ax_Hj:-Mv-uCkD22y1a51Ax_Hk:bc1mbdd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10ef1db675a0ab9109296fae8a585d4257456bdc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L130)):*
> ```Kotlin
> 
> @Command(name = "mc_creation_token", description = ["Get a Measurement Consumer Creation Token"])
> private class CreateMCCreationTokenCommand : CreatePrincipalCommand() {
> ```

`CreateMcCreationToken` or `CreateMeasurementConsumerCreationToken`

See https://developer.android.com/kotlin/style-guide#camel_case



_Code quote:_
```Kotlin
CreateMCCreationTokenCommand
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 123 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv-uUTT4Z8MLXv2PeXx:-Mv0-x5_-3qtVOtcPzaC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10ef1db675a0ab9109296fae8a585d4257456bdc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L123)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This also needs to print out the activation token.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 129 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv-ux89E-7T8nR8vb0Z:-Mv0-zW6CG5S3xu_H5iw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10ef1db675a0ab9109296fae8a585d4257456bdc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L129)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Create
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 130 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv-uCkD22y1a51Ax_Hj:-Mv014WvCKJtkIcwK8hq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10ef1db675a0ab9109296fae8a585d4257456bdc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L130)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`CreateMcCreationToken` or `CreateMeasurementConsumerCreationToken`

See https://developer.android.com/kotlin/style-guide#camel_case
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 130 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv-tamG4LhNsMHJhP_A:-Mv019nX2QYECUOutwfu:b-3exy0i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10ef1db675a0ab9109296fae8a585d4257456bdc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L130)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This shouldn't extend from CreatePrincipalCommand, as an MC creation token is not a Principal, and has no encryption key, etc.
</blockquote></details>

Sorry I don't really understand what Principal Command means. 
`CreateAccountCommand` does not need encryption key either. Guess it shouldn't extent from `CreatePrincipalCommand` as well?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 123 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv-uUTT4Z8MLXv2PeXx:-Mv08586B_e29-PjrY-L:b7zl19e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10ef1db675a0ab9109296fae8a585d4257456bdc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L123)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What I'm referring to is the [account activation token](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d653df14f1c5f54c31ff679e5a93516979611101/src/main/proto/wfa/measurement/api/v2alpha/account.proto#L76)

The operator will need to give this to the Account holder so they can activate the Account.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 127 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv08zTw9qdoXgjJQlaD:-Mv08zTw9qdoXgjJQlaE:ber6sw2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/59287ab4bb0c273a91b7d6a32bb90765f1f5f996/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L127)):*
> ```Kotlin
>     val mcCreationToken = runBlocking {
>       externalIdToApiId(
>         internalAccountsClient.createMeasurementConsumerCreationToken(
> ```

Let's avoid creating a creation token for convenience here, and let the operator run a separate command for that. There's theoretically a use case where an operator creates an Account, but some other MC owner will make that Account an owner of their MC. In that case, this Account holder doesn't need to create an MC.



_Code quote:_
```Kotlin
        internalAccountsClient.createMeasurementConsumerCreationToken(
            createMeasurementConsumerCreationTokenRequest {}
          )
          .measurementConsumerCreationToken
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 123 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv-uUTT4Z8MLXv2PeXx:-Mv1FoDvBeWQHAIHrPjt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10ef1db675a0ab9109296fae8a585d4257456bdc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L123)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What I'm referring to is the [account activation token](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d653df14f1c5f54c31ff679e5a93516979611101/src/main/proto/wfa/measurement/api/v2alpha/account.proto#L76)

The operator will need to give this to the Account holder so they can activate the Account.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 127 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv08zTw9qdoXgjJQlaD:-Mv1FnelAOQSn91ffych:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/59287ab4bb0c273a91b7d6a32bb90765f1f5f996/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L127)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Let's avoid creating a creation token for convenience here, and let the operator run a separate command for that. There's theoretically a use case where an operator creates an Account, but some other MC owner will make that Account an owner of their MC. In that case, this Account holder doesn't need to create an MC.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 125 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv1GCVN1jXlL_ELahnK:-Mv1GCVN1jXlL_ELahnL:b-s4pzme) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4814ae17bdd745fd78bcb883f27ed9656c895f90/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L125)):*
> ```Kotlin
>     val accountActivationToken = externalIdToApiId(internalAccount.activationToken)
>     println(accountName)
>     println("account-activation-token/$accountActivationToken")
> ```

This is an odd format, as it's making it look like it's a resource name when it's not.

Maybe just `"Activation token: $accountActivationToken"`?



_Code quote:_
```Kotlin
"account-activation-token/$accountActivationToken"
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md, line 31 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv1GXdMD9rI1CIZk29P:-Mv1GXdMD9rI1CIZk29Q:b-xedqcw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4814ae17bdd745fd78bcb883f27ed9656c895f90/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md#L31)):*
> ```Markdown
> Run the CLI tool with the flag `help` to check the instruction. Provide the credentials as required. Examples here
> ```shell
> # Create an Account
> ```

nit: move these comments outside of the command and into the markdown content, possibly making an Examples section with each of these as subsections.



_Code quote:_
```Markdown
# Create an Account
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 125 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv1GCVN1jXlL_ELahnK:-Mv1Qa958vEvJwMjv2u7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4814ae17bdd745fd78bcb883f27ed9656c895f90/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L125)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is an odd format, as it's making it look like it's a resource name when it's not.

Maybe just `"Activation token: $accountActivationToken"`?
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 124 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv5oyZo28zCek58SZjW:-Mv5oyZo28zCek58SZjX:bice9n7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22a8117ebcd981cb2afabf9f894e7ab3539ae7cc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L124)):*
> ```Kotlin
>     val accountName = AccountKey(externalIdToApiId(internalAccount.externalAccountId)).toName()
>     val accountActivationToken = externalIdToApiId(internalAccount.activationToken)
>     println(accountName)
> ```

nit `("Account Name: $accountName")`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 145 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv5ooHp55-uRRjcUdNw:-Mv5ooHp55-uRRjcUdNx:b-71u5bc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22a8117ebcd981cb2afabf9f894e7ab3539ae7cc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L145)):*
> ```Kotlin
>       )
>     }
>     println(mcCreationToken)
> ```

nit: `println("Creation Token: $mcCreationToken")`

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 124 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv5oyZo28zCek58SZjW:-Mv5sTUu1dvjBj3ZbQTH:b5sbsu6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22a8117ebcd981cb2afabf9f894e7ab3539ae7cc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L124)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit `("Account Name: $accountName")`
</blockquote></details>

`println(accountName)` gives us:
`accounts/ABCDEFG1234`
Do we want 
`Account Name: accounts/ABCDEFG1234`
Data Provider has the same format as `dataProviders/ABCDEFG1234`

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 124 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv5oyZo28zCek58SZjW:-MvJerhV6j4hVI4P5Fuv:b-3qm7j2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22a8117ebcd981cb2afabf9f894e7ab3539ae7cc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L124)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

`println(accountName)` gives us:
`accounts/ABCDEFG1234`
Do we want 
`Account Name: accounts/ABCDEFG1234`
Data Provider has the same format as `dataProviders/ABCDEFG1234`
</blockquote></details>

yeah - I'd prefer that

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 124 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-Mv5oyZo28zCek58SZjW:-MvKMVAU9qAMEWXsC4Gr:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22a8117ebcd981cb2afabf9f894e7ab3539ae7cc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L124)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - I'd prefer that
</blockquote></details>

Done

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md, line 34 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-MvKYq5T2ZX_va7BHx1z:-MvKYq5T2ZX_va7BHx2-:boi35es) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3a743bb367ff67a18715cb65c1f01bdc21e0968/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md#L34)):*
> ```Markdown
> ```shell
> create_resource account --tls-cert-file kingdom_tls.pem --tls-key-file kingdom_tls.key --cert-collection-file kingdom_root.pem \ 
>     --internal-api-cert-host localhost --internal-api-target localhost:8443 --certificate-der-file mc_cs_cert.der \
> ```

I don't think this is right. AFAIK Account resource doesn't use these fields.



_Suggestion:_
```Markdown
    --certificate-der-file mc_cs_cert.der \
    --encryption-public-key-file mc_enc_public.tink --encryption-public-key-signature-file mc_cs_cert.der
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md, line 34 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-MvKYq5T2ZX_va7BHx1z:-MvKgC7P5G9kQPZoKqYo:b-d7y9um) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3a743bb367ff67a18715cb65c1f01bdc21e0968/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this is right. AFAIK Account resource doesn't use these fields.
</blockquote></details>

Based on class `CreatePrincipalCommand`, these fields are required when `buildMutualTlsChannel()` [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/InternalApiFlags.kt)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md, line 34 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-MvKYq5T2ZX_va7BHx1z:-MvLD2NyCbG7blJR4jaG:binmjh9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3a743bb367ff67a18715cb65c1f01bdc21e0968/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md#L34)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Based on class `CreatePrincipalCommand`, these fields are required when `buildMutualTlsChannel()` [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/InternalApiFlags.kt)
</blockquote></details>

But Account shouldn't use CreatePrincipalCommand. Despite being an auth principal, it doesn't use the options that CreatePrincipalCommand asks for.

Note that I'm specifically referring to these options:

```
--certificate-der-file mc_cs_cert.der \
    --encryption-public-key-file mc_enc_public.tink --encryption-public-key-signature-file mc_cs_cert.der
```

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md, line 34 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435#-MvKYq5T2ZX_va7BHx1z:-MvLHLr63GlutBjlwEjC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3a743bb367ff67a18715cb65c1f01bdc21e0968/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

But Account shouldn't use CreatePrincipalCommand. Despite being an auth principal, it doesn't use the options that CreatePrincipalCommand asks for.

Note that I'm specifically referring to these options:

```
--certificate-der-file mc_cs_cert.der \
    --encryption-public-key-file mc_enc_public.tink --encryption-public-key-signature-file mc_cs_cert.der
```
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/435)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
