### PR TITLE
Update internal api with additional fields in CreateEventGroup

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
please get the linter and tests passing

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-:-Mq_JabpBMiIlrhJcorY:b-7siy59)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @chipingyeh)

___
*[build/repositories.bzl, line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_JZjR1lDpwmf3oJfF:-Mq_JZjR1lDpwmf3oJfG:b-mu0t41) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a73d3e1f1a9a08b718a7b7aa19af3737cc277d2/build/repositories.bzl#L41)):*
> ```Starlark
>         name = "wfa_measurement_proto",
>         repo = "cross-media-measurement-api",
>         chipingyeh-update-internal-api
> ```

remove this line

**Review by robinsons — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @chipingyeh)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 116 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_Pr46A1TA2jtO-gIc:-Mq_Pr46A1TA2jtO-gId:b5soxcs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a73d3e1f1a9a08b718a7b7aa19af3737cc277d2/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L116)):*
> ```Kotlin
> /** Converts an internal [InternalEventGroup] to a public [EventGroup]. */
> private fun InternalEventGroup.toEventGroup(): EventGroup {
>   return eventGroup {
> ```

We also need to populate the `measurement_consumer_certificate` and `encrypted_metadata`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 126 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_QEWE43P35pW3ZLrG:-Mq_QEWE43P35pW3ZLrH:b-u8bl3p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a73d3e1f1a9a08b718a7b7aa19af3737cc277d2/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L126)):*
> ```Kotlin
>       MeasurementConsumerKey(externalIdToApiId(externalMeasurementConsumerId)).toName()
>     eventGroupReferenceId = providedEventGroupId
>     measurementConsumerPublicKey =
> ```

Technically `measurementConsumerPublicKey` isn't a required field; it's only required if `encryptedMetadata` is specified. This means that when converting from internal event group to external, we should not set the public key if it doesn't exist.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 145 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_N6hj3wSiMN7RIY36:-Mq_N6hkBwcJcvpIv5qJ:bsang5p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a73d3e1f1a9a08b718a7b7aa19af3737cc277d2/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L145)):*
> ```Kotlin
>     }
> 
>   val eventGroup = request.eventGroup
> ```

nit: Since this is an extension function on `EventGroup`, you can refer to the event group as `this`, instead of using `request.eventGroup`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 151 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_OxeK2zvfAuuvbePr:-Mq_OxeK2zvfAuuvbePs:b-ur7my2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a73d3e1f1a9a08b718a7b7aa19af3737cc277d2/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L151)):*
> ```Kotlin
>     }
> 
>   return internalEventGroup {
> ```

On the internal event group, we also need to populate `measurement_consumer_certificate_id`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 156 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_OcfREqEGVApSbr18:-Mq_OcfREqEGVApSbr19:bll1q9m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a73d3e1f1a9a08b718a7b7aa19af3737cc277d2/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L156)):*
> ```Kotlin
>     providedEventGroupId = eventGroupReferenceId
>     details =
>       details {
> ```

On the details message, we also need to populate `api_version` and `encrypted_metadata`.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[build/repositories.bzl, line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_JZjR1lDpwmf3oJfF:-Mqp0xVACUn6zdQjBDGv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97cd0bbf9b050f0c73cc10ee8281d32a55a72f65/build/repositories.bzl#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

remove this line
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 116 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_Pr46A1TA2jtO-gIc:-MqpAjCxCljbKKchp0gw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97cd0bbf9b050f0c73cc10ee8281d32a55a72f65/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L116)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

We also need to populate the `measurement_consumer_certificate` and `encrypted_metadata`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 126 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_QEWE43P35pW3ZLrG:-MqpF25lEwxZXkr0JJXB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97cd0bbf9b050f0c73cc10ee8281d32a55a72f65/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L126)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Technically `measurementConsumerPublicKey` isn't a required field; it's only required if `encryptedMetadata` is specified. This means that when converting from internal event group to external, we should not set the public key if it doesn't exist.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 145 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_N6hj3wSiMN7RIY36:-MqpWo9lBT0W36R2HHWM:b-2obluv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97cd0bbf9b050f0c73cc10ee8281d32a55a72f65/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L145)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

nit: Since this is an extension function on `EventGroup`, you can refer to the event group as `this`, instead of using `request.eventGroup`.
</blockquote></details>

Basic syntax question - how would we refer to the `EventGroup` `this` within `details`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 151 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_OxeK2zvfAuuvbePr:-Mqp7-0tDLa65uEmxllP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97cd0bbf9b050f0c73cc10ee8281d32a55a72f65/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L151)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

On the internal event group, we also need to populate `measurement_consumer_certificate_id`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 156 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_OcfREqEGVApSbr18:-MqpX2BNCUquq1rlj4Fe:b-uafup7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97cd0bbf9b050f0c73cc10ee8281d32a55a72f65/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L156)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

On the details message, we also need to populate `api_version` and `encrypted_metadata`.
</blockquote></details>

Sorry I'm not clear - where will `api_version` come from?

**Review by robinsons — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 116 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_Pr46A1TA2jtO-gIc:-Mqp_hh_73u9bYjwINHz:b5dwmfd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97cd0bbf9b050f0c73cc10ee8281d32a55a72f65/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L116)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Note that `measurementConsumerCertificate` is also not a required field, so we should check that `externalMeasurementConsumerCertificateId` is non-empty before trying to populate it.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 145 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_N6hj3wSiMN7RIY36:-MqpaV78-90ftok4r--4:b-7n6526) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97cd0bbf9b050f0c73cc10ee8281d32a55a72f65/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L145)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Basic syntax question - how would we refer to the `EventGroup` `this` within `details`?
</blockquote></details>

Good question. In general you can do this by adding `@label` to refer to an outer scope. In this case, I think that this would work:

```
details = details {
  foo = this@toInternal.foo
}
```

We would use `@toInternal` as the label since that's the function name.

There's some more info [here](https://kotlinlang.org/docs/this-expressions.html).
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 156 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_OcfREqEGVApSbr18:-Mqpg0oOE3O_UfWH_2p6:beet0qf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97cd0bbf9b050f0c73cc10ee8281d32a55a72f65/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L156)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Sorry I'm not clear - where will `api_version` come from?
</blockquote></details>

All of the service implementations in this package are part of "v2alpha". You can check out another service like [this one](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt#L66) to see how they set it.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 158 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-MqpejbN8bA1DH692ht-:-MqpejbO38t_5VDQkCMl:b5wcshe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c238f4413e946d1f2f4be9fbf402dcc70c6e07e6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L158)):*
> ```Kotlin
>       "Measurement consumer is either unspecified or invalid"
>     }
>   val measurementConsumerCertificateId =
> ```

nit: Could we call this `measurementConsumerCertificateKey`?

**Review by chipingyeh — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-:-MqujXed6EoIVO3_CmHT:bnfp4nl)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 116 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_Pr46A1TA2jtO-gIc:-Mqu_Zrm3R1BmVtUx2ZU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97cd0bbf9b050f0c73cc10ee8281d32a55a72f65/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L116)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Note that `measurementConsumerCertificate` is also not a required field, so we should check that `externalMeasurementConsumerCertificateId` is non-empty before trying to populate it.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 145 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_N6hj3wSiMN7RIY36:-MquZTRx5cbi2FoKff-K:b-7cqyw6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97cd0bbf9b050f0c73cc10ee8281d32a55a72f65/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L145)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Good question. In general you can do this by adding `@label` to refer to an outer scope. In this case, I think that this would work:

```
details = details {
  foo = this@toInternal.foo
}
```

We would use `@toInternal` as the label since that's the function name.

There's some more info [here](https://kotlinlang.org/docs/this-expressions.html).
</blockquote></details>

Thanks for the reference! Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 156 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-Mq_OcfREqEGVApSbr18:-MquXdMTD-Ye1L-q8tpm:b-dgqt6r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97cd0bbf9b050f0c73cc10ee8281d32a55a72f65/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L156)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

All of the service implementations in this package are part of "v2alpha". You can check out another service like [this one](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt#L66) to see how they set it.
</blockquote></details>

Got it - done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 158 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-MqpejbN8bA1DH692ht-:-MquWkymEz2VCUjxM1_y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c238f4413e946d1f2f4be9fbf402dcc70c6e07e6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L158)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

nit: Could we call this `measurementConsumerCertificateKey`?
</blockquote></details>

Done.

**Review by robinsons — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 77 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-MquswK6-4qfSJD6g_aN:-MquswK6-4qfSJD6g_aO:b-c3p7f6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c206583200ac0ea76934b1a0217579bc56ef6d27/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L77)):*
> ```Kotlin
>   }
> 
>   override suspend fun createEventGroup(request: CreateEventGroupRequest): EventGroup {
> ```

Can you add `grpcRequire()` checks for fields according to the documentation in [`event_group.proto`](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto)? For example, the comments in that file mention that `measurementConsumerPublicKey` must be set if `encryptedMetadata` is set.

And to go with that, corresponding test(s) to make sure that `createEventGroup()` fails with `INVALID_ARGUMENT` when required fields are missing.

Sorry for bringing this up late in the review -- it only just crossed my mind.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 77 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396#-MquswK6-4qfSJD6g_aN:-Mqz6cY1-SD26s5a7WB2:b-vvio5f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c206583200ac0ea76934b1a0217579bc56ef6d27/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L77)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Can you add `grpcRequire()` checks for fields according to the documentation in [`event_group.proto`](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto)? For example, the comments in that file mention that `measurementConsumerPublicKey` must be set if `encryptedMetadata` is set.

And to go with that, corresponding test(s) to make sure that `createEventGroup()` fails with `INVALID_ARGUMENT` when required fields are missing.

Sorry for bringing this up late in the review -- it only just crossed my mind.
</blockquote></details>

No worries, it's good to have more consistent/robust code - done.

**Review by robinsons — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 3 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 1 of 3 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @robinsons and @stevenwarejones)

**Review by robinsons — APPROVED** [review]
> Reviewed 2 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/396)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Pull request merged**
