### PR TITLE
Implement SpannerRecurringExchangesService.

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @uakyol and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt, line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgM87LWE23971m5kVP6:-MgM87LWE23971m5kVP7:b-9h10in) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/431bb9867a451b8cc87827a2f2b5ad109d96398d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt#L83)):*
> ```Kotlin
> /** Base test class for [RecurringExchangesCoroutineImplBase] implementations. */
> abstract class RecurringExchangesServiceTest {
>   protected abstract fun createModelProvider(idGenerator: IdGenerator): ModelProvider
> ```

@sanjayvas how do you feel about this way of building in implementation-specific test helpers versus just explicitly spinning up all the necessary services? (E.g. in this case, `/RecurringExchanges`, `/ModelProviders`, and `/DataProvieders`)

At least in the short term I prefer this because we don't yet have a `SpannerModelProvidersService` impl

**Review by yunyeng — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMK7bWB0C2fopcbxiL:-MgMK7bWB0C2fopcbxiM:bw5d0g5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/431bb9867a451b8cc87827a2f2b5ad109d96398d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L26)):*
> ```
>  val certificateId: Long
> ```
not specific to this PR, just wondering why the internal Id is included in all these spanner reader result. The internal Id in the result is not used anywhere.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt, line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgM87LWE23971m5kVP6:-MgMKjgRD2plAQWUmxld:b-3qkixz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/431bb9867a451b8cc87827a2f2b5ad109d96398d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt#L83)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@sanjayvas how do you feel about this way of building in implementation-specific test helpers versus just explicitly spinning up all the necessary services? (E.g. in this case, `/RecurringExchanges`, `/ModelProviders`, and `/DataProvieders`)

At least in the short term I prefer this because we don't yet have a `SpannerModelProvidersService` impl
</blockquote></details>

maybe at least add a TODO to switch to the actual implementation when it is done.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, @uakyol, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMK7bWB0C2fopcbxiL:-MgMNOIi7wtKutyJYM6i:b-go7w8r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/431bb9867a451b8cc87827a2f2b5ad109d96398d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L26)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  val certificateId: Long
> ```
not specific to this PR, just wondering why the internal Id is included in all these spanner reader result. The internal Id in the result is not used anywhere.
</blockquote></details>

@uakyol any ideas?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt, line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgM87LWE23971m5kVP6:-MgMUCPS4WCUqySHvIu-:bkd5ega) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/431bb9867a451b8cc87827a2f2b5ad109d96398d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt#L83)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

maybe at least add a TODO to switch to the actual implementation when it is done.
</blockquote></details>

Added a TODO

**Review by SanjayVas — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: all files reviewed, 3 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, @stevenwarejones, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMeraODp-dSu_Lbt2f:-MgMeraPAjNb1E7LIC78:b-xa9wzq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt#L46)):*
> ```
> RecurringExchange.State.ACTIVE
> ```
nit: consider extracting an INITIAL_STATE constant to reuse when building return value.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt, line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgM87LWE23971m5kVP6:-MgMfBpK7bvg-7CN9nMs:b8lx9bn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/431bb9867a451b8cc87827a2f2b5ad109d96398d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt#L83)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Added a TODO
</blockquote></details>

Prefer spinning up actual services so we don't have to maintain parallel code for testing. Keeping this with TODO is fine for now. Just switch to KDoc syntax since it's documenting a function.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: all files reviewed, 6 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, @uakyol, and @wangyaopw)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMluvG98bucOaGfJXs:-MgMluvHCLWb5CgTVe9X:bjjqtvt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/-- commits#L2)):*
do you know what setting is causing these commit messages to show up in reviewable?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMmPSAB5TW3SJuCUd_:-MgMmPSAB5TW3SJuCUda:bf5bsnc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L68)):*
> ```Kotlin
>     return certificateBuilder
>       .apply {
>         @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA") // Proto enum fields are never null.
> ```

whats the best practice here? throw in `@supress` or a `requirenotnull`
___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMmwv94xKR9rmPTfMV:-MgMmwv94xKR9rmPTfMW:bkkha1f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L26)):*
> ```protobuf
>   // Expects a valid CRON expression.
>   // See https://en.wikipedia.org/wiki/Cron#CRON_expression.
>   // TODO: this is too complex; change to just DAILY/WEEKLY/MONTHLY or similar.
> ```

I'm not sure about this todo. Oftentimes (although its not in the standard) other strings like "@yearly" are supported.
See https://www.freebsd.org/cgi/man.cgi?crontab%285%29

I like the flexibility of choosing based on the full string. Why is it too complex?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, @SanjayVas, @stevenwarejones, @uakyol, and @yunyeng)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMluvG98bucOaGfJXs:-MgMt9MqDknu0ceH8_J0:bc2df81) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/-- commits#L2)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you know what setting is causing these commit messages to show up in reviewable?
</blockquote></details>

Absolutely no idea! It's annoying, though
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMmPSAB5TW3SJuCUd_:-MgMtEpHDCiTo80RgKRj:b-5gvhnr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L68)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the best practice here? throw in `@supress` or a `requirenotnull`
</blockquote></details>

@sanjayvas, do you have an opinion? `@Suppress` adds no runtime penalty -- but null checking isn't exactly expensive. `@Suppress` conveys a little more intent, too. But it's more verbose
___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMmwv94xKR9rmPTfMV:-MgMtXNf0kGxOBvz-i6F:bkkkthe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm not sure about this todo. Oftentimes (although its not in the standard) other strings like "@yearly" are supported.
See https://www.freebsd.org/cgi/man.cgi?crontab%285%29

I like the flexibility of choosing based on the full string. Why is it too complex?
</blockquote></details>

Either we have to pull in a crontab parser or roll our own.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, @SanjayVas, @uakyol, and @yunyeng)

___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMmwv94xKR9rmPTfMV:-MgN1i0VAC1LgGkH9Q57:b6qjo70) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Either we have to pull in a crontab parser or roll our own.
</blockquote></details>

i vote pull in crontab parser.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, @SanjayVas, @stevenwarejones, @uakyol, and @yunyeng)

___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMmwv94xKR9rmPTfMV:-MgN6GgTArbj3HdHFfec:b3ftb89) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i vote pull in crontab parser.
</blockquote></details>

Such as?

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: all files reviewed, 3 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMmPSAB5TW3SJuCUd_:-MgNXwRP9fh2rM00KZ9T:bjndics) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L68)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@sanjayvas, do you have an opinion? `@Suppress` adds no runtime penalty -- but null checking isn't exactly expensive. `@Suppress` conveys a little more intent, too. But it's more verbose
</blockquote></details>

`@Suppress` in this case, as we're just giving the Kotlin compiler some information that the Java proto library can't communicate on its own. It is in fact enforced in that library, so a runtime check here would be redundant and incorrectly communicate that the field *could* be null.

**Review by yunyeng — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: all files reviewed, 3 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, @stevenwarejones, and @uakyol)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: all files reviewed, 2 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, and @uakyol)

___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMmwv94xKR9rmPTfMV:-MgQm8sF2hU7ao1_1vGv:b-eyb92r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Such as?
</blockquote></details>

Looks like there are a few different options out there:
http://cron-parser.com/
https://www.javadoc.io/doc/org.quartz-scheduler/quartz/latest/org/quartz/CronExpression.html
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/support/CronExpression.html

Maybe its more trouble than its worth but its pretty handy for testing.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: all files reviewed, 2 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, @stevenwarejones, and @uakyol)

___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMmwv94xKR9rmPTfMV:-MgQsh4P5e7r-0RAUDkZ:beouguf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Looks like there are a few different options out there:
http://cron-parser.com/
https://www.javadoc.io/doc/org.quartz-scheduler/quartz/latest/org/quartz/CronExpression.html
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/support/CronExpression.html

Maybe its more trouble than its worth but its pretty handy for testing.
</blockquote></details>

Let's punt on this for now -- this TODO can serve as a reminder to do /something/ with crons. Sound good?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: all files reviewed, 2 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, and @uakyol)

___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMmwv94xKR9rmPTfMV:-MgR3LyYBY1Pk0fWx9zE:bsh6vgz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Let's punt on this for now -- this TODO can serve as a reminder to do /something/ with crons. Sound good?
</blockquote></details>

yeah - I completely agree with punting. I don't like the todo statement though. It should be more exploratory in nature.

**Review by cs-sswaminathan — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @kgaynor, and @uakyol)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, @SanjayVas, @stevenwarejones, @uakyol, and @yunyeng)

___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMmwv94xKR9rmPTfMV:-MgRCcjJ1yZBZoNNtkWV:bcv6twh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce9404708f855402006445475d692d9327be7552/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - I completely agree with punting. I don't like the todo statement though. It should be more exploratory in nature.
</blockquote></details>

Removed the TODO, let's not waste any more time on this please

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @cs-sswaminathan, @kgaynor, @SanjayVas, @uakyol, and @yunyeng)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @cs-sswaminathan, @kgaynor, @SanjayVas, @uakyol, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMK7bWB0C2fopcbxiL:-MgRCuOO5P0Fa7gzEYGj:b-pmtzmh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/431bb9867a451b8cc87827a2f2b5ad109d96398d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@uakyol any ideas?
</blockquote></details>

@wangyaopw can we take this one offline so it's not blocking the PR?

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @cs-sswaminathan, @kgaynor, @SanjayVas, @uakyol, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMK7bWB0C2fopcbxiL:-MgRK0__0hdxgZyT4q2i:b-7j86r0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/431bb9867a451b8cc87827a2f2b5ad109d96398d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@wangyaopw can we take this one offline so it's not blocking the PR?
</blockquote></details>

sure.

**Review by efoxepstein — COMMENTED** [review]
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @cs-sswaminathan, @kgaynor, @SanjayVas, @uakyol, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177#-MgMK7bWB0C2fopcbxiL:-MgRLxjhENmw3O4bjbxJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/431bb9867a451b8cc87827a2f2b5ad109d96398d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L26)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

sure.
</blockquote></details>

Done.

**Review by yunyeng — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kgaynor and @uakyol)

**Pull request merged**
