### PR TITLE
Use signing certificate instead of measurement consumer certificate when creating measurement

### PR DESCRIPTION
**Pull request by riemanli**
Fix the wrong assumption that the signing private key in the reporting server is paired with the certificate in the measurement consumer resource. This PR adds a private data class, `SigningConfig`, to `ReportsService` and use the signing certificate to create a measurement.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 255 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8AQmfF2yPZSFf6cd1A:-N8AQmfG6PnOJ-mFFTqg:b-y846zq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b14be48c9d91df3e44f8e481e76ff9def7f03ad/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L255)):*
> ```Kotlin
>   private val certificateStub: CertificatesCoroutineStub,
>   private val encryptionKeyPairStore: EncryptionKeyPairStore,
>   private val signingPrivateKey: PrivateKey,
> ```

Just take in the `SigningKeyHandle` here so you don't have to construct it later.



_Code quote:_
```Kotlin
  private val signingPrivateKey: PrivateKey,
  private val signingCertificate: X509Certificate,
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1075 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8ARCs375K-TCa6M-yF:-N8ARCs375K-TCa6M-yG:b-7t2wrp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b14be48c9d91df3e44f8e481e76ff9def7f03ad/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1075)):*
> ```Kotlin
>     val measurement = measurement {
>       name = measurementResourceName
>       this.measurementConsumerCertificate = measurementConsumer.certificate
> ```

This is also incorrect. Is thing being fixed in a separate PR? If so, add a TODO.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @riemanli and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8AXkuCAdPczDOKv25d:-N8AXkuCAdPczDOKv25e:b4gh12e) (no related file):*
It looks like both #640 and this are trying to address the same thing. @tristanvuong2021 

___

**Comment by riemanli** [comment]
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8AXkuCAdPczDOKv25d:-N8AYuy53EUcJWOIlCWs:b8xqqeg) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It looks like both #640 and this are trying to address the same thing. @tristanvuong2021 
</blockquote></details>

Ah. I can close this one. I think Tristan knows how to handle the issue better than me. Let me know if that's okay to you both @sanjayvas and @tristanvuong2021 .

**Comment by tristanvuong2021** [comment]
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1075 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8ARCs375K-TCa6M-yF:-N8AbJ1u6DcCFBgS7oDB:bsm5kg0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b14be48c9d91df3e44f8e481e76ff9def7f03ad/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1075)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is also incorrect. Is thing being fixed in a separate PR? If so, add a TODO.
</blockquote></details>

@riemanli I am not handling this right, just changing it to use the config file. Could just focus on this with this PR.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1075 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8ARCs375K-TCa6M-yF:-N8AXG273Q0zEQc4wuBQ:b-l9kkx8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b14be48c9d91df3e44f8e481e76ff9def7f03ad/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1075)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

@riemanli I am not handling this right, just changing it to use the config file. Could just focus on this with this PR.
</blockquote></details>

@tristanvuong2021 Got it.

@sanjayvas Good catch. I missed this one.

Are we able to get a `Certificate` from a `SigningKeyHandle `? Based on your comment in the other discussion, there will be no `Certificate` and `SigningPrivateKey` but `SigningKeyHandle`, so I am not sure where to get the `Certificate` for this field.

**Comment by tristanvuong2021** [comment]
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1075 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8ARCs375K-TCa6M-yF:-N8Ad1bK43TA8FcJp7j7:buqquad) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b14be48c9d91df3e44f8e481e76ff9def7f03ad/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1075)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@tristanvuong2021 Got it.

@sanjayvas Good catch. I missed this one.

Are we able to get a `Certificate` from a `SigningKeyHandle `? Based on your comment in the other discussion, there will be no `Certificate` and `SigningPrivateKey` but `SigningKeyHandle`, so I am not sure where to get the `Certificate` for this field.
</blockquote></details>

I am getting the certificate and the private key based on the config and leaving the creation of the handle alone. A file pointing to the secret directory is passed in and not tthe handle.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1075 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8ARCs375K-TCa6M-yF:-N8AkpxW7tZCm-6WLVEL:bhhk6zl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b14be48c9d91df3e44f8e481e76ff9def7f03ad/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1075)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I am getting the certificate and the private key based on the config and leaving the creation of the handle alone. A file pointing to the secret directory is passed in and not tthe handle.
</blockquote></details>

Regardless, the `certificate` field of SigningKeyHandle is public.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 255 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8AQmfF2yPZSFf6cd1A:-N8BeOGNCjj8LGWQBIyY:bvfgaq2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b14be48c9d91df3e44f8e481e76ff9def7f03ad/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L255)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just take in the `SigningKeyHandle` here so you don't have to construct it later.
</blockquote></details>

Due to the changes from the other PR, `signingPrivateKey` and `signingCertificate` will be created in function calls.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1075 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8ARCs375K-TCa6M-yF:-N8BfPOO6ISZsaRZM7Du:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b14be48c9d91df3e44f8e481e76ff9def7f03ad/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1075)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Regardless, the `certificate` field of SigningKeyHandle is public.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 344 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8PQMv96rEUQJQY6T27:-N8PQMv96rEUQJQY6T28:bg3ewl3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17d5bc8c363bf174e8406d55bc56125cc4718527/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L344)):*
> ```Kotlin
> 
>     val signingPrivateKeyDer: ByteString =
>       signingPrivateKeyDir.resolve(principal.config.signingPrivateKeyPath).readByteString()
> ```

nit: add a TODO to factor this out to a separate class similar to EncryptionKeyPairStore

We technically have a purpose-built class for this already called [`SigningKeyStore`](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/crypto/SigningKeyStore.kt), but we'd need some adapting to use it (e.g. putting all keys within a specific subdirectory and using PEM).
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 346 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8PPyku9kxHfEyi__fb:-N8PPyku9kxHfEyi__fc:bcdjvwl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17d5bc8c363bf174e8406d55bc56125cc4718527/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L346)):*
> ```Kotlin
>       signingPrivateKeyDir.resolve(principal.config.signingPrivateKeyPath).readByteString()
> 
>     val signingCertificateDer: ByteString =
> ```

nit: extract method and add a TODO to cache certificates or have them stored alongside the private key

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 344 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8PQMv96rEUQJQY6T27:-N8PeLvVABr_lMBwpUYQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17d5bc8c363bf174e8406d55bc56125cc4718527/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L344)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: add a TODO to factor this out to a separate class similar to EncryptionKeyPairStore

We technically have a purpose-built class for this already called [`SigningKeyStore`](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/crypto/SigningKeyStore.kt), but we'd need some adapting to use it (e.g. putting all keys within a specific subdirectory and using PEM).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 346 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642#-N8PPyku9kxHfEyi__fb:-N8PiKbzBxfdARnLEaQM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17d5bc8c363bf174e8406d55bc56125cc4718527/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L346)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: extract method and add a TODO to cache certificates or have them stored alongside the private key
</blockquote></details>

Done.

**Pull request merged**
