### PR TITLE
refactor: Graduate Report post-processing from experimental

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/BUILD.bazel` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9B1Vsy1EUlAyBMDPgz:-O9B1Vsz1_DLQfxUhGW5:bnejthe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9240b2106a253c04d28ce5c0b9b299d8032fa58/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/BUILD.bazel#L18)):*
> ```Starlark
>         "//src/main/proto/wfa/measurement/reporting/postprocessing/v2alpha:report_summary_kt_jvm_proto",
>         "//src/main/proto/wfa/measurement/reporting/v2alpha:report_kt_jvm_proto",
>         "@maven//:com_google_protobuf_protobuf_java_util",
> ```

Use alias from `//imports` for all Maven deps. Depending on which Bazel module added this dep, this may be under `@rules_kotlin_jvm//imports` or `@wfa_common_jvm//imports`



_Code quote:_
```Starlark
"@maven//:com_google_protobuf_protobuf_java_util",
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9B71SB8ByAW9Ts37LV:-O9B71SC7BSyzqaov39I:b-mdd931) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9240b2106a253c04d28ce5c0b9b299d8032fa58/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L63)):*
> ```Kotlin
>   }
> 
>   fun getSetOperation(tag: String): String {
> ```

This can be done in a later PR, but can we split off anything that references Origin-specific tags (i.e. anything in this file that references tags at all) to their own package? All Origin-specific code in this repo is temporary and should eventually be deleted.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorImpl.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9B53BsBSwFknvpnqVM:-O9B53BsBSwFknvpnqVN:bwndw3a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9240b2106a253c04d28ce5c0b9b299d8032fa58/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorImpl.kt#L37)):*
> ```Kotlin
>  * returns the a [Report] of which all measurements are consistent.
>  */
> class ReportProcessorImpl : ReportProcessor {
> ```

nit: This can still be a singleton object while implementing the interface.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: 32 of 37 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/BUILD.bazel` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9B1Vsy1EUlAyBMDPgz:-O9BSiJD8mkLZo4Hiz_D:b-tvr342) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9240b2106a253c04d28ce5c0b9b299d8032fa58/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/BUILD.bazel#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use alias from `//imports` for all Maven deps. Depending on which Bazel module added this dep, this may be under `@rules_kotlin_jvm//imports` or `@wfa_common_jvm//imports`
</blockquote></details>

Done. It turns out that we don't need this dependency at all.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9B71SB8ByAW9Ts37LV:-O9BTfS6B8tnIacMirEd:bva1m0k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9240b2106a253c04d28ce5c0b9b299d8032fa58/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This can be done in a later PR, but can we split off anything that references Origin-specific tags (i.e. anything in this file that references tags at all) to their own package? All Origin-specific code in this repo is temporary and should eventually be deleted.
</blockquote></details>

Done. I've added TODOs for these functions.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorImpl.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9B53BsBSwFknvpnqVM:-O9BR1wvE0nfySo7x6wR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9240b2106a253c04d28ce5c0b9b299d8032fa58/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorImpl.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: This can still be a singleton object while implementing the interface.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9RPAA3ANugOPKYdriX:-O9RPAA3ANugOPKYdriY:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/00a6e73619670dd933a4883d8263a35188e34541/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L50)):*
> ```Kotlin
>   }
> 
>   // TODO(@ple13): Move this function to a separate package that handles the tags.
> ```

nit



_Suggestion:_
```Kotlin
Origin-specific package
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorImpl.kt` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9RPPTZCXoPTKEhV9qW:-O9RPPT_55dbhw7qYe4z:b-wx101t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/00a6e73619670dd933a4883d8263a35188e34541/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorImpl.kt#L36)):*
> ```Kotlin
>  * returns the a [Report] of which all measurements are consistent.
>  */
> object ReportProcessorImpl : ReportProcessor {
> ```

I should have been more clear: follow the pattern of kotlin.Random. There the interface as a companion object named Default which provides the default impl.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 32 of 37 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13)

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: 33 of 38 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9RPAA3ANugOPKYdriX:-O9V_R1-8hc7gBuD21fr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/00a6e73619670dd933a4883d8263a35188e34541/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorImpl.kt` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9RPPTZCXoPTKEhV9qW:-O9WQwCD8X6aNs5f1fY8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/00a6e73619670dd933a4883d8263a35188e34541/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorImpl.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I should have been more clear: follow the pattern of kotlin.Random. There the interface as a companion object named Default which provides the default impl.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 31 of 37 files at r1, 2 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessor.kt` line 93 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9odaAB3KXOknTumUmy:-O9odaAB3KXOknTumUmz:bfwzc1l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/147a626e42949f7676728eace580f26ab5ec1a77/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessor.kt#L93)):*
> ```Kotlin
> 
>       // TODO(bazelbuild/bazel#17629): Execute the Python zip directly once this bug is fixed.
>       val processBuilder = ProcessBuilder("python3", tempFile.toPath().toString())
> ```

what do you think about using this workaround instead?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 50 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9od3fXEluVyLqOZvmY:-O9od3fXEluVyLqOZvmZ:b-ro8ppq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/147a626e42949f7676728eace580f26ab5ec1a77/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L50)):*
> ```Kotlin
>   }
> 
>   // TODO(@ple13): Move this function to a separate Origin-specific package.
> ```

is there a doc somewhere on how we want this to look long-term?

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 50 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9od3fXEluVyLqOZvmY:-O9pkvNIDz4isz0fCSUY:bw1ds48) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/147a626e42949f7676728eace580f26ab5ec1a77/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L50)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is there a doc somewhere on how we want this to look long-term?
</blockquote></details>

The noise correction code will be part of the new MC API. As part of Phase II we'll have a doc that answers your question.

We should make it a goal to delete or relocate everything in this PR by the end of 2025.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessor.kt` line 93 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9odaAB3KXOknTumUmy:-O9pewKSDz1XQKTvaeil:b9pnv35) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/147a626e42949f7676728eace580f26ab5ec1a77/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessor.kt#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what do you think about using this workaround instead?
</blockquote></details>

The workaround solves the problem. @SanjayVas WDYT about using the workaround?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessor.kt` line 93 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9odaAB3KXOknTumUmy:-O9q99yP4VCBD9xTXBrC:bte2wga) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/147a626e42949f7676728eace580f26ab5ec1a77/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessor.kt#L93)):*
> what do you think about using this workaround instead?

Sorry, which workaround do you mean? Do you mean the workaround that's already in the code to call `python3`? That's fine until the bug in the TODO is fixed, after which we should execute the pyzip itself.

If it's some other workaround, perhaps there's a code suggestion that's not showing up for me?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessor.kt` line 93 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9odaAB3KXOknTumUmy:-O9qJMrU7NwbDOkkqU9Z:bnlcffn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/147a626e42949f7676728eace580f26ab5ec1a77/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessor.kt#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> what do you think about using this workaround instead?

Sorry, which workaround do you mean? Do you mean the workaround that's already in the code to call `python3`? That's fine until the bug in the TODO is fixed, after which we should execute the pyzip itself.

If it's some other workaround, perhaps there's a code suggestion that's not showing up for me?
</blockquote></details>

We are talking about this workaround https://github.com/bazelbuild/bazel/issues/17629#issuecomment-2207375102.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessor.kt` line 93 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9odaAB3KXOknTumUmy:-O9qWfJg3cCo0ED7f68m:bt9afpq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/147a626e42949f7676728eace580f26ab5ec1a77/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessor.kt#L93)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

We are talking about this workaround https://github.com/bazelbuild/bazel/issues/17629#issuecomment-2207375102.
</blockquote></details>

Oh, that one is messy and may break when the bug is fixed. This workaround we have should continue to work even after the bug is fixed, and is easier to clean up.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 50 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9od3fXEluVyLqOZvmY:-O9tHsboEj501Jf3Dti6:b-5e7h5n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/147a626e42949f7676728eace580f26ab5ec1a77/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L50)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

The noise correction code will be part of the new MC API. As part of Phase II we'll have a doc that answers your question.

We should make it a goal to delete or relocate everything in this PR by the end of 2025.
</blockquote></details>

can you add some tests for these functions with example tags?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt` line 50 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853#-O9od3fXEluVyLqOZvmY:-O9u8JGsA9bShROXeU2T:bqqb46a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/147a626e42949f7676728eace580f26ab5ec1a77/src/main/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversion.kt#L50)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add some tests for these functions with example tags?
</blockquote></details>

I believe this is covered by existing tests. The sample tags are in the test data JSON Reports.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

**Pull request merged**
