### PR TITLE
Refactor HMSS to remove sketch params

### PR DESCRIPTION
**Pull request by renjiezh**
Depends on public api change https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/210

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt` line 129 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689#-O1rTFp0CJ_GP8MV6lj1:-O1rTFp1DuMD2xEyg00M:b-9aahxn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c277b201da6a455fe6bcad896a0150118404cb0/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L129)):*
> ```Kotlin
>             recordLlv2RequisitionLocally(computationToken, externalRequisitionKey, blob.blobKey)
>           }
>           val seed =
> ```

Why is this changed? It doesn't appear to be related to the API change.
___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 168 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689#-O1rTyas6k-sc9L94zK1:-O1rTyas6k-sc9L94zK2:b-f2imhy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88645c9710508106e2b21c434839e06624eba788/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L168)):*
> ```proto
> 
>     // Configuration for the Honest Majority Share Shuffle protocol.
>     message HonestMajorityShareShuffle {
> ```

FYI this change is only okay because this hasn't been used yet. Otherwise the system API follows similar rules to the CMMS public API.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt` line 960 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689#-O1rUbub1bHhJRRJg0Jg:-O1rUbub1bHhJRRJg0Jh:btp8uli) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88645c9710508106e2b21c434839e06624eba788/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt#L960)):*
> ```Kotlin
>             registerCount = 100
>             maximumCombinedFrequency = 30
>             ringModulus = 127
> ```

If changing the value in `HMSS_PARAMETERS` would also require this value to change, then this should just come from that constant.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689)* status: 23 of 25 files reviewed, 2 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt` line 129 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689#-O1rTFp0CJ_GP8MV6lj1:-O1s6ED69gTAWeTzP_d7:b-tc31lt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c277b201da6a455fe6bcad896a0150118404cb0/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L129)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this changed? It doesn't appear to be related to the API change.
</blockquote></details>

This is unused code which raises compiler warning.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt` line 960 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689#-O1rUbub1bHhJRRJg0Jg:-O1s6O_Z9kZYHrWGQaRM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88645c9710508106e2b21c434839e06624eba788/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt#L960)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If changing the value in `HMSS_PARAMETERS` would also require this value to change, then this should just come from that constant.
</blockquote></details>

Done.

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 23 of 25 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689)* status: all files reviewed, 5 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/k8s/testing/secretfiles/hmss_protocol_config_config.textproto` line 6 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689#-O1wAdvT2wSBwE0YufdF:-O1wAdvT2wSBwE0YufdG:b-b0vc3u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9bf8673104a0e756ddf4cb9b2fa991f923b1c533/src/main/k8s/testing/secretfiles/hmss_protocol_config_config.textproto#L6)):*
> ```
>   noise_mechanism: DISCRETE_GAUSSIAN
>   reach_and_frequency_ring_modulus: 127
>   reach_ring_modulus: 127
> ```

1. nit: use reach_only to mirror the reach_and_frequency?
2. The modulus for the reach only protocol is a prime number. We should have a comment to indicate that the modulus used in the reach only protocol must be a prime.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto` line 145 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689#-O1wD54m4lV9c3eACKtf:-O1wD54nA9SQZh2Szxb6:bdps35f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9bf8673104a0e756ddf4cb9b2fa991f923b1c533/src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto#L145)):*
> ```proto
> 
>     // The modulus used in the protocol for Reach Measurement.
>     int32 reach_ring_modulus = 4;
> ```

nit: same as above. pls consider reach_only_ring_modulus to mirror the R/F name.
___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 173 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689#-O1wDQHy4AwVcN8BUOs_:-O1wDQHy4AwVcN8BUOsa:bxsyvcc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9bf8673104a0e756ddf4cb9b2fa991f923b1c533/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L173)):*
> ```proto
>           [(google.api.field_behavior) = REQUIRED];
>       // The modulus used in the MPC protocol for Reach Measurement.
>       int32 reach_ring_modulus = 2 [(google.api.field_behavior) = REQUIRED];
> ```

nit: same about the name as above.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689)* status: all files reviewed, 3 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/k8s/testing/secretfiles/hmss_protocol_config_config.textproto` line 6 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689#-O1wAdvT2wSBwE0YufdF:-O1wYUfe5uoh1kUgzX5W:bdvo8yq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9bf8673104a0e756ddf4cb9b2fa991f923b1c533/src/main/k8s/testing/secretfiles/hmss_protocol_config_config.textproto#L6)):*
> nit: use reach\_only to mirror the reach\_and\_frequency?

This is mirroring the Measurement types of REACH and REACH_AND_FREQUENCY.

The only place we use "reach only" is for reach only LLv2, as that's a separate protocol. The Measurement type is still REACH.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689)* status: 24 of 25 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/k8s/testing/secretfiles/hmss_protocol_config_config.textproto` line 6 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689#-O1wAdvT2wSBwE0YufdF:-O1wco1g7OV86wT14hHP:bfmicqq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9bf8673104a0e756ddf4cb9b2fa991f923b1c533/src/main/k8s/testing/secretfiles/hmss_protocol_config_config.textproto#L6)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> nit: use reach\_only to mirror the reach\_and\_frequency?

This is mirroring the Measurement types of REACH and REACH_AND_FREQUENCY.

The only place we use "reach only" is for reach only LLv2, as that's a separate protocol. The Measurement type is still REACH.
</blockquote></details>

Done.
Comment added in protocol_config.proto.

**Review by ple13 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 10 of 25 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/BUILD.bazel` line 126 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689#-O26VJfo-QjyDFgfCf5n:-O26VJfp2p8P8nRTEe9s:b8wp01c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e4f3238531033c7f14eaf8c8101079a99f3105f/src/main/proto/wfa/measurement/internal/duchy/protocol/BUILD.bazel#L126)):*
> ```Starlark
> 
> proto_library(
>     name = "share_shuffle_sketch_params_proto",
> ```

proto library name must match file name



_Code quote:_
```Starlark
share_shuffle_sketch_params_proto
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/BUILD.bazel` line 126 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689#-O26VJfo-QjyDFgfCf5n:-O26_5oy8-jrOpX0n9hU:b6rs0km) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e4f3238531033c7f14eaf8c8101079a99f3105f/src/main/proto/wfa/measurement/internal/duchy/protocol/BUILD.bazel#L126)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

proto library name must match file name
</blockquote></details>

Done.
Nice catch!

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 9 of 25 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 13 of 16 files at r4, 2 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1689)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
