### PR TITLE
feat: Report processor supports cumulative and total measurements with different sets of EDP combinations.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)

**Comment by SanjayVas** [comment]
Removing myself as reviewer since the vast majority of this is in the Python processing code.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 3 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: 5 of 6 files reviewed, 11 unresolved discussions (waiting on @ple13)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUXmU1Eg9mQR_QrMdE:-OAUXmU1Eg9mQR_QrMdF:b-xqb6rg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L39)):*
> ```Python
> 
> 
> def get_cover_relationships(edp_combinations: list[FrozenSet[str]]):
> ```

I would tend to decompose this a bit and provide the following functions:

isCover(s, possible_cover):

getCovers(s, other_sets):


If you have these it will be much easier to read and test.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 77 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUYlW489XuCkzgRZk7:-OAUYlW489XuCkzgRZk8:b-h253o4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L77)):*
> ```Python
>   __reach_time_series_by_edp_combination: dict[
>     FrozenSet[str], list[Measurement]]
>   __reach_whole_campaign_by_edp_combination: dict[FrozenSet[str], Measurement]
> ```

You can drop these. It's enough to assign to them in the __init__ function, however you should document them in the doc string of the class.

Also, prefer single underscores for members.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 84 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUbcsCAdUg8qyiQC2U:-OAUbcsCAdUg8qyiQC2V:b7qtiyc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L84)):*
> ```Python
>         FrozenSet[str], list[Measurement]],
>       reach_whole_campaign_by_edp_combination: dict[
>         FrozenSet[str], Measurement] = None,
> ```

Do you really need to default this? Won't your client always pass it?
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUc52W3RQZBTQ9aBJY:-OAUc52W3RQZBTQ9aBJZ:b-6vrng) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L99)):*
> ```Python
>     )
> 
>     if reach_whole_campaign_by_edp_combination is None:
> ```

What you're doing is fine, especially for such a long variable name, but writing the following is better:

member = {} if input_var is None else input_var

Shortening the member variable names wouldn't hurt, but in a separate PR, if you want to.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 130 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUdM_UAcxG0MET9Giv:-OAUdM_UAcxG0MET9Giw:bb6fg3k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L130)):*
> ```Python
>     return self.__reach_whole_campaign_by_edp_combination[edp_combination]
> 
>   def get_cumulative_edp_combinations(self):
> ```

These aren't returning/operating on combinations. They seem to just be return a set of the keys and out counting the number of keys of the various dicts.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 146 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUe83l4x44yoY1Hluc:-OAUe83l4x44yoY1Hlud:bwc8uxf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L146)):*
> ```Python
> 
>   def get_cumulative_subset_relationships(self):
>     edp_combinations = list(self.__reach_time_series_by_edp_combination)
> ```

No need for the temporary.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 150 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUeBGQCLPEiVEAVKxf:-OAUeBGQCLPEiVEAVKxg:b-816h6l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L150)):*
> ```Python
> 
>   def get_whole_campaign_subset_relationships(self):
>     edp_combinations = list(self.__reach_whole_campaign_by_edp_combination)
> ```

Same.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 154 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUeESb9NvsXh49CvQ_:-OAUeESb9NvsXh49CvQa:b-816h6l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L154)):*
> ```Python
> 
>   def get_cumulative_cover_relationships(self):
>     edp_combinations = list(self.__reach_time_series_by_edp_combination)
> ```

Same.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 158 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUeHsm-XUEmE4WoqqQ:-OAUeGfQ9RpAZP023d7q:b-816h6l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L158)):*
> ```Python
> 
>   def get_whole_campaign_cover_relationships(self):
>     edp_combinations = list(self.__reach_whole_campaign_by_edp_combination)
> ```

Same.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 345 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUgkfq0OBIExaVtY_9:-OAUgkfq0OBIExaVtY_A:bc15hwv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L345)):*
> ```Python
>         )
> 
>   def __add_subset_relations_to_spec(self, spec):
> ```

It sure would be nice to have tests for each of these functions.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/tools/post_process_origin_report.py` line 234 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAU_fV54WZAwjI91U_Y:-OAU_fV54WZAwjI91U_Z:b4ejifg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/tools/post_process_origin_report.py#L234)):*
> ```Python
> 
> 
> def buildCorrectedExcel(correctedReport, excel):
> ```

Do we still need the excel functions?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: 1 of 7 files reviewed, 11 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUXmU1Eg9mQR_QrMdE:-OAq7yCU6Xvlb6oghidq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L39)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I would tend to decompose this a bit and provide the following functions:

isCover(s, possible_cover):

getCovers(s, other_sets):


If you have these it will be much easier to read and test.
</blockquote></details>

Done.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 77 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUYlW489XuCkzgRZk7:-OAWQNnH5KGlMj08X2Gt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L77)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

You can drop these. It's enough to assign to them in the __init__ function, however you should document them in the doc string of the class.

Also, prefer single underscores for members.
</blockquote></details>

Done.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 84 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUbcsCAdUg8qyiQC2U:-OAWSEwB0QDGUqmhI6fH:bsndwya) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L84)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Do you really need to default this? Won't your client always pass it?
</blockquote></details>

This doesn't need a default value. I had it so that I didn't need to update previous unit tests. Anyway, I've updated the code and remove the default value.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUc52W3RQZBTQ9aBJY:-OAWRWHv3sbTnHxPzvY8:btp7hpn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L99)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

What you're doing is fine, especially for such a long variable name, but writing the following is better:

member = {} if input_var is None else input_var

Shortening the member variable names wouldn't hurt, but in a separate PR, if you want to.
</blockquote></details>

Thanks. I've updated it.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 130 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUdM_UAcxG0MET9Giv:-OAWUhkM3TJkr6fYp3UO:bqjbgnz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L130)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

These aren't returning/operating on combinations. They seem to just be return a set of the keys and out counting the number of keys of the various dicts.
</blockquote></details>

The keys of the dictionaries here are the edp_combinations. e.g. self._reach_whole_campaign_by_edp_combination is a dictionary that maps edp_combination to reach measurements.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 146 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUe83l4x44yoY1Hluc:-OAWV4inCHOAbqvO_idS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L146)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

No need for the temporary.
</blockquote></details>

Done.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 150 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUeBGQCLPEiVEAVKxf:-OAWVawW6dBqFTXoHtlh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L150)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 154 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUeESb9NvsXh49CvQ_:-OAWVle297LbSuFjaxlc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L154)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 158 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUeHsm-XUEmE4WoqqQ:-OAWVn-A6ZFtAkLQSKTb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L158)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 345 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAUgkfq0OBIExaVtY_9:-OApuRfv6tnqSITVPh_l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L345)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It sure would be nice to have tests for each of these functions.
</blockquote></details>

Done.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/tools/post_process_origin_report.py` line 234 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAU_fV54WZAwjI91U_Y:-OAWVpt68TNHhPrvUDmR:b-2kzi0f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0250c7fb7f8218cf962758fecd9004b74596fb10/src/main/python/wfa/measurement/reporting/postprocessing/tools/post_process_origin_report.py#L234)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Do we still need the excel functions?
</blockquote></details>

We don't need them any more. I've removed them.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: all files reviewed, 3 unresolved discussions (waiting on @ple13 and @stevenwarejones)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py` line 177 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAxbGmU1JRzvE6K6F2O:-OAxbGmU1JRzvE6K6F2P:b-x6w9vs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4463cb89fcec43b31b89872f51ac276e9e44a82/src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py#L177)):*
> ```Python
>                           problem=self._problem())
>     else:
>       while attempt_count < 10:
> ```

Introduce a file level constant for this.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 53 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAxbWQg3RlnU7qRf4Gj:-OAxbWQg3RlnU7qRf4Gk:b-ht931y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4463cb89fcec43b31b89872f51ac276e9e44a82/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L53)):*
> ```Python
>       lambda x, y: x.union(y), possible_cover
>   )
>   if union_of_possible_cover == target_set:
> ```

return union_of_possible_cover == target_set

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py` line 177 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAxbGmU1JRzvE6K6F2O:-OAy3E5o5KNhVM8wMu8j:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4463cb89fcec43b31b89872f51ac276e9e44a82/src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py#L177)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Introduce a file level constant for this.
</blockquote></details>

Done.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 53 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OAxbWQg3RlnU7qRf4Gj:-OAy3Cv16CXk62ukeJ6w:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4463cb89fcec43b31b89872f51ac276e9e44a82/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L53)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

return union_of_possible_cover == target_set
</blockquote></details>

Done.

**Review by stevenwarejones — COMMENTED** [review]
what do you think about using pyre for type checking?

> Reviewed 1 of 6 files at r1, 1 of 6 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-:-OBWDwrv22il9rqxnBKU:b-xtvq8y)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @kungfucraig)

**Review by SanjayVas — COMMENTED** [review]
Rieman had done an analysis on how to add Python infrastructure to Halo repos back when Planning was still a priority. IIRC, the main issue was the lack of Bazel support for all of the common type checkers.

FWIW internally at Google we use PyType

> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-:-OBWb7JdCk258mQINQ1c:b-1kxbn2)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @kungfucraig)

**Review by ple13 — COMMENTED** [review]
I've created an issue for the type checking https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1912

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-:-OBX9NWZAD6YhwUpAVy0:b-s4o8tl)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @kungfucraig)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 26 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OBfrziy-trJDl2UfVGw:-OBfrziy-trJDl2UfVGx:bsitfph) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61d0b00e3018f2a94067aec10a2fe3d6a0153d21/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L26)):*
> ```Python
> 
> 
> def get_subset_relationships(edp_combinations: list[FrozenSet[str]]):
> ```

i'd prefer all return types be explicitly stated - you can probably use MonkeyType to generate a lot of these for you
https://github.com/Instagram/MonkeyType

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 55 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OBfs8QGDkTLg6QjWdo7:-OBfs8QGDkTLg6QjWdo8:b-nqa120) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61d0b00e3018f2a94067aec10a2fe3d6a0153d21/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L55)):*
> ```Python
>   return union_of_possible_cover == target_set
> 
> def get_covers(target_set, other_sets):
> ```

can you explicitly type all the input and output params of functions?

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: all files reviewed, 3 unresolved discussions (waiting on @ple13)

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 26 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OBfrziy-trJDl2UfVGw:-OC6HFGp6-W0xFklDI7x:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61d0b00e3018f2a94067aec10a2fe3d6a0153d21/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'd prefer all return types be explicitly stated - you can probably use MonkeyType to generate a lot of these for you
https://github.com/Instagram/MonkeyType
</blockquote></details>

Done.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 55 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OBfs8QGDkTLg6QjWdo7:-OC6HdUb2c7XUD2UtzHJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61d0b00e3018f2a94067aec10a2fe3d6a0153d21/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L55)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you explicitly type all the input and output params of functions?
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r4, 2 of 5 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 222 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OCFhTqX9CzIdiI4h_9d:-OCFhTqX9CzIdiI4h_9e:b4fs0ew) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e7708ceddf6a3c0604968db591f250fc4bea9aec/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L222)):*
> ```Python
>                                    between metrics. Each key is a parent metric,
>                                    and the value is a list of its child metrics.
>         _cumulative_inconsistency_allowed_edp_combinations: A set of EDP
> ```

whats the use case for allowing inconsistencies with only some EDPs?
___
*[`src/test/python/wfa/measurement/reporting/postprocessing/report/test_report.py` line 1287 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OCFiMbOB7QplqLYt0iK:-OCFiMbOB7QplqLYt0iL:b9gouf7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e7708ceddf6a3c0604968db591f250fc4bea9aec/src/test/python/wfa/measurement/reporting/postprocessing/report/test_report.py#L1287)):*
> ```Python
>     )
> 
>     corrected = report.get_corrected_report()
> ```

can you add some comments to each of these corrections what you are checking was properly corrected?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 6 files at r4, 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 222 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OCFhTqX9CzIdiI4h_9d:-OD7ftT19OrzVW4hzRil:b-5gbje2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e7708ceddf6a3c0604968db591f250fc4bea9aec/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L222)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the use case for allowing inconsistencies with only some EDPs?
</blockquote></details>

please add a comment that this is for TV

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/report/report.py` line 222 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OCFhTqX9CzIdiI4h_9d:-OD7n6cJESAhRezh75sN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e7708ceddf6a3c0604968db591f250fc4bea9aec/src/main/python/wfa/measurement/reporting/postprocessing/report/report.py#L222)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

please add a comment that this is for TV
</blockquote></details>

Done.
___
*[`src/test/python/wfa/measurement/reporting/postprocessing/report/test_report.py` line 1287 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885#-OCFiMbOB7QplqLYt0iK:-OD7rZUqAX6F8g5_Vczs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e7708ceddf6a3c0604968db591f250fc4bea9aec/src/test/python/wfa/measurement/reporting/postprocessing/report/test_report.py#L1287)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add some comments to each of these corrections what you are checking was properly corrected?
</blockquote></details>

Done.

**Review by ple13 — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 6 files at r4, 3 of 5 files at r6, 1 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1885)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
