### PR TITLE
Suspend start/update until all retries are complete.

### PR DESCRIPTION
**Pull request by SanjayVas**
This follows the more common practice of having a function either be suspending or return with background coroutines still running, but not both.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 184 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586#-N5umIn0Bhm8LVHdQTc6:-N5umIn0Bhm8LVHdQTc7:bu758jq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a920ba5fac2713b584d5851a4c31c84cfda3a28c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L184)):*
> ```Kotlin
>         val result = runCatching { withContext(rpcDispatcher) { block(systemComputation) } }
>         if (result.isFailure) {
>           delay(timeMillis = minOf((1L shl attemptNumber) * 1000L, 60_000L))
> ```

Maybe we can pull out a nice abstraction here, wdyt?

```
sealed interface ResultOrRetry
data class Result<T>(val value: T): ResultOrRetry
class Retry

fun <T> retryWithExponentialBackoff(maxAttempts, initialDelay, delayExponent, maxDelay, performAttempt: (attemptNumber: Int) -> ResultOrRetry<T> {
  for (attemptNumber in 1..maxAttempts) {
    when (val result = performAttempt(attemptNumber) {
      is Retry -> delay(...)
      is Result -> return result.value
    }
  }
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 184 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586#-N5unxFq-tEZxhSw3GTB:-N5unxFq-tEZxhSw3GTC:bj8ptv2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a920ba5fac2713b584d5851a4c31c84cfda3a28c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L184)):*
> ```Kotlin
>         val result = runCatching { withContext(rpcDispatcher) { block(systemComputation) } }
>         if (result.isFailure) {
>           delay(timeMillis = minOf((1L shl attemptNumber) * 1000L, 60_000L))
> ```

Consider doing `Math.randInt(0, (1L shl attemptNumber) * 1000L)` (or otherwise randomizing the delay to avoid weird retry patterns)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 184 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586#-N5umIn0Bhm8LVHdQTc6:-N5w2Lkv0KGXqTUkuzTu:bev1stk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a920ba5fac2713b584d5851a4c31c84cfda3a28c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L184)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe we can pull out a nice abstraction here, wdyt?

```
sealed interface ResultOrRetry
data class Result<T>(val value: T): ResultOrRetry
class Retry

fun <T> retryWithExponentialBackoff(maxAttempts, initialDelay, delayExponent, maxDelay, performAttempt: (attemptNumber: Int) -> ResultOrRetry<T> {
  for (attemptNumber in 1..maxAttempts) {
    when (val result = performAttempt(attemptNumber) {
      is Retry -> delay(...)
      is Result -> return result.value
    }
  }
}
```
</blockquote></details>

I'm hesitant to introduce an abstraction for blind retries.

We have retries happening at two levels here: one conditionally based on whether an RPC is retriable with no delays, and another at a lower level that blindly retries regardless of the error but does have a delay. The former is using an extension on `Flow`, where the latter retries arbitrary code.

This is all wrapped in a bigger infinite retry loop where the Herald may eventually crash on a bad computation and pick it up on next run. This one can be infinite, though at least it has exponential backoff at the Kubernetes level.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 184 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586#-N5unxFq-tEZxhSw3GTB:-N5wGeMZ2lomOeBTinr1:bacueld) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a920ba5fac2713b584d5851a4c31c84cfda3a28c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L184)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Consider doing `Math.randInt(0, (1L shl attemptNumber) * 1000L)` (or otherwise randomizing the delay to avoid weird retry patterns)
</blockquote></details>

Done.

Used proper exponential backoff with randomness.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by matthewclegg — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 188 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586#-N6xiIWl0n_X-OlnENU5:-N6xyCxh1GD1LX9LxY8h:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/737cfdeb838d5d5c74051ee14be40c8bec1e627b/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L188)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should all these params be configurable via the contructor?
</blockquote></details>

Done.

**Review by matthewclegg — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
