### PR TITLE
Create K8s manifest for kingdom

### PR DESCRIPTION
**Pull request by wfa-mdharmalingam**
Created separate templates for kingdom.

Create K8s secret
Create K8s Manifest

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR8sK7ZBgezxkwXyrRQ:-NR8sK7ZBgezxkwXyrRR:bsek8h0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-manifest_kingdom.yml#L1)):*
> ```YAML
> # Copyright 2023 The Cross-Media Measurement Authors
> ```

@SanjayVas Do we want underscores in filename? Existing actions look like they only use hyphens.
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR8s8Dn5dLNcAUvjlDu:-NR8s8Dn5dLNcAUvjlDv:b-2hn9rc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-manifest_kingdom.yml#L42)):*
> ```YAML
>           --define image_tag=build-0001
> 
>     #    - name: Apply k8s manifest
> ```

Let's add the boolean like we did with apply terraform.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908)* status: all files reviewed, 8 unresolved discussions (waiting on @bdomen-ggl, @kungfucraig, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR8sK7ZBgezxkwXyrRQ:-NR9LLOo31LZKfYYwrW6:b-i51i91) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-manifest_kingdom.yml#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@SanjayVas Do we want underscores in filename? Existing actions look like they only use hyphens.
</blockquote></details>

Existing naming conventions should be followed. In this case, that means hyphens. This also means there should be a separate PR to rename `create_duchy.yml`.
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR9LVKYDM7lA3toghkg:-NR9LVKYDM7lA3toghkh:bj31f3l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-manifest_kingdom.yml#L19)):*
> ```YAML
> on:
>   push:
>     branches: [ "feature/create_k8s_manifest_kingdom"]
> ```

This is the wrong trigger.



_Code quote:_
```YAML
  push:
    branches: [ "feature/create_k8s_manifest_kingdom"]
```
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR9MEHm-4j9F7w5G8RT:-NR9MEHm-4j9F7w5G8RU:byqbx2c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-manifest_kingdom.yml#L23)):*
> ```YAML
> jobs:
>   push_create_k8s_manifest:
>     runs-on: ubuntu-22.04
> ```

Use ubuntu-20.04 for any workflow that calls Bazel. We haven't tested on ubuntu-22.04, which may have too new a version of glibc.



_Code quote:_
```YAML
ubuntu-22.04
```
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR9MCPQBuJefft_NMGZ:-NR9MCPQBuJefft_NMG_:b-giy8vm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-manifest_kingdom.yml#L28)):*
> ```YAML
>         uses: actions/checkout@v2
> 
>       - name: Install Kubectl
> ```

Kubectl is already installed in this runner. See https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR9MNjc204HdGAapjuq:-NR9MNjc204HdGAapjur:b-qznzfz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-manifest_kingdom.yml#L38)):*
> ```YAML
>       - name: Build K8s manifest
>         run: |
>           bazel build //src/main/k8s/dev:kingdom_gke \
> ```

You need to use Bazelisk to run Bazel otherwise it won't read the `.bazelversion` file to pick up the correct version. The runner has a different version installed by default.



_Suggestion:_
```YAML
bazelisk
```
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR9MbpR0XAp9Umho2X-:-NR9MbpR0XAp9Umho2X0:b5tho0r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-manifest_kingdom.yml#L40)):*
> ```YAML
>           bazel build //src/main/k8s/dev:kingdom_gke \
>           --define=k8s_kingdom_secret_name=certs-and-configs-abcdedg \
>           --define image_tag=build-0001
> ```

These values cannot be hard-coded.

1. The image tag should be an input. When triggered by a release (including by a parent workflow that's triggered on release), the image tag needs to match the one used by the workflow that pushes images (i.e. the release version).
2. The name of the secret is dynamic. You'll need to actually create the secret first in order to determine the name.



_Code quote:_
```YAML
          --define=k8s_kingdom_secret_name=certs-and-configs-abcdedg \
          --define image_tag=build-0001
```
___
*[`.github/workflows/k8s-secrets_kingdom.yml` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR9O7pw8DwVjyn_AWGB:-NR9O7pw8DwVjyn_AWGC:bdh80wg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-secrets_kingdom.yml#L28)):*
> ```YAML
>         uses: actions/checkout@v2
> 
>       - name: copying kingdom_tls.pem secrets for testing
> ```

For the QA environment, you should be able to run `bazelisk run //src/main/k8s/testing/secretfiles:apply_kustomization`. Note that you'll need kubectl to be pointing to the correct cluster already.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908)* status: all files reviewed, 7 unresolved discussions (waiting on @bdomen-ggl, @kungfucraig, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/export-image-tag.sh` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NREXH_V93pPCnjLbeNK:-NREXH_V93pPCnjLbeNL:b40fcu6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ad7cc10574242d5bee23c32caaaa7bd3f7efa86/.github/workflows/export-image-tag.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

This file shouldn't be added by this PR, but rather #900.

If you need to do dependent PRs, make sure the later PR branch is based on the former (both making sure the branches depend on each other in Git and setting the base branch on the later PR in GitHub). Make sure never to merge any PR to a branch other than `main`, meaning you need to wait for #900 to be merged before you can merge this PR.

That said, I don't think you'll need to do this if you make the image tag an input to this workflow.
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR9MNjc204HdGAapjuq:-NREaUi95HLNDyEiDBma:ba8nh1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-manifest_kingdom.yml#L38)):*
> Looks like the deployment documents need an update as well.

The deployment docs are correct. On a normal dev machine, either `bazel` would be symlinked to `bazelisk` or the correct version of Bazel would already be installed. This isn't true for the GitHub actions runner.
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 18 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NREYDyB2aH144Jc0l9m:-NREYDyB2aH144Jc0l9n:b-gvfenl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ad7cc10574242d5bee23c32caaaa7bd3f7efa86/.github/workflows/k8s-manifest_kingdom.yml#L18)):*
> ```YAML
> 
> on:
>   workflow_dispatch:
> ```

I believe you also need a `workflow_call` trigger so this can be called from another workflow.
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NREYcppAu6BKztsL4Bh:-NREYcppAu6BKztsL4Bi:b-xpm0ql) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ad7cc10574242d5bee23c32caaaa7bd3f7efa86/.github/workflows/k8s-manifest_kingdom.yml#L27)):*
> ```YAML
>   push_create_k8s_manifest:
>     runs-on: ubuntu-20.04
>     steps:
> ```

The image tag should be probably be an input to this workflow rather than being computed again.

During a release, the workflow that builds and publishes the images should generate/output an image tag. This can then be passed into this workflow.

During a manual run (workflow_dispatch), the caller can specify the image tag.
___
*[`.github/workflows/k8s-secrets_kingdom.yml` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR9O7pw8DwVjyn_AWGB:-NREb-PYCeBdzefgL_3J:b-2dhb9x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-secrets_kingdom.yml#L28)):*
<details><summary><i>Previously, wfa-mdharmalingam wrote…</i></summary><blockquote>

Need some more detail, we will connect with you on this. 
</blockquote></details>

For testing, we're just using our testing secret files that are checked-in to the repo. The `//src/main/k8s/testing/secretfiles:apply_kustomization` target will call kubectl to apply the Kustomization with the secret generator for you. You'll need to ensure that you use the generated secret name in later steps, e.g. by reading the output of the command.

**Review by wfa-siyengar — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 3 files at r8, 1 of 2 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908)* status: all files reviewed, 7 unresolved discussions (waiting on @bdomen-ggl, @kungfucraig, @SanjayVas, and @wfa-mdharmalingam)

___
*[`.github/workflows/export-image-tag.sh` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NREXH_V93pPCnjLbeNK:-NREg6CeAh2F0DBB7yiJ:b-9ui6zr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ad7cc10574242d5bee23c32caaaa7bd3f7efa86/.github/workflows/export-image-tag.sh#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This file shouldn't be added by this PR, but rather #900.

If you need to do dependent PRs, make sure the later PR branch is based on the former (both making sure the branches depend on each other in Git and setting the base branch on the later PR in GitHub). Make sure never to merge any PR to a branch other than `main`, meaning you need to wait for #900 to be merged before you can merge this PR.

That said, I don't think you'll need to do this if you make the image tag an input to this workflow.
</blockquote></details>

It will conflict. yo are right. if 900 already gives us, this will not get in. We have kept it here just for completeness, else our workflow fails.
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR9MbpR0XAp9Umho2X-:-NRIDk3w1haVvKqP78ot:b840zrn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-manifest_kingdom.yml#L40)):*
<details><summary><i>Previously, wfa-mdharmalingam wrote…</i></summary><blockquote>

We are working on this 
</blockquote></details>

We will get the image_tag as an input to this workflow.
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 18 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NREYDyB2aH144Jc0l9m:-NRIDLjwAwI_beXxQ803:bu6f75o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ad7cc10574242d5bee23c32caaaa7bd3f7efa86/.github/workflows/k8s-manifest_kingdom.yml#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe you also need a `workflow_call` trigger so this can be called from another workflow.
</blockquote></details>

Correct, we will do the needful. This will align in the final PR. We keep it as dispatch for now.
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NREYcppAu6BKztsL4Bh:-NRIDbrr0hNpo34qAF4z:b-2tkptl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ad7cc10574242d5bee23c32caaaa7bd3f7efa86/.github/workflows/k8s-manifest_kingdom.yml#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The image tag should be probably be an input to this workflow rather than being computed again.

During a release, the workflow that builds and publishes the images should generate/output an image tag. This can then be passed into this workflow.

During a manual run (workflow_dispatch), the caller can specify the image tag.
</blockquote></details>

Got that. Sure.

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 1 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @wfa-mdharmalingam, and @wfa-siyengar)

**Review by wfa-siyengar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, and @wfa-mdharmalingam)

___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR9MbpR0XAp9Umho2X-:-NRcBXs03fClf8e2v2id:b-ivdg2o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-manifest_kingdom.yml#L40)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

We will get the image_tag as an input to this workflow.
</blockquote></details>

This will be coming as input from a higher level flow in a separate PR.
___
*[`.github/workflows/k8s-manifest_kingdom.yml` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NREYcppAu6BKztsL4Bh:-NRcB9766ZGfkth259cq:bq1xnag) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ad7cc10574242d5bee23c32caaaa7bd3f7efa86/.github/workflows/k8s-manifest_kingdom.yml#L27)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Got that. Sure.
</blockquote></details>

IMAGE_TAG will be input this will come from a separate PR.

**Review by wfa-siyengar — COMMENTED** [review]
> Reviewed 1 of 3 files at r15, 1 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, and @wfa-mdharmalingam)

___
*[`.github/workflows/export-image-tag.sh` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NREXH_V93pPCnjLbeNK:-NRfBCnT0UbiELq2ExF0:beyoc4o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ad7cc10574242d5bee23c32caaaa7bd3f7efa86/.github/workflows/export-image-tag.sh#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> We have kept it here just for completeness, else our workflow fails

If that's the case, then you'll need to do the dependent PRs as I mentioned. Each PR **must** *only* contain the relevant changes.
</blockquote></details>

We will ensure we follow this way going ahead.

**Review by wfa-siyengar — APPROVED** [review]
Made few more changes basis of other comments.

> Reviewed 2 of 3 files at r16.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-:-NRfC9tx1pZbGDYwS39V:b-7x0xj7)* status: all files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, and @wfa-mdharmalingam)

**Review by wfa-siyengar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-:-NRfDHjI-_BknfcpX_T6:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, and @wfa-mdharmalingam)

**Review by wfa-hkawalkar — COMMENTED** [review]
> Reviewed 1 of 3 files at r8, 1 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908)* status: all files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl and @SanjayVas)

___
*[`.github/workflows/k8s-secrets_kingdom.yml` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NR9O7pw8DwVjyn_AWGB:-NRfDlKt3dzTMglg-hz2:b-nfcmes) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71106377344129637e4b7e40cff80ee8edcd4e45/.github/workflows/k8s-secrets_kingdom.yml#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

For testing, we're just using our testing secret files that are checked-in to the repo. The `//src/main/k8s/testing/secretfiles:apply_kustomization` target will call kubectl to apply the Kustomization with the secret generator for you. You'll need to ensure that you use the generated secret name in later steps, e.g. by reading the output of the command.
</blockquote></details>

okay, so we will use testing secret files for QA environment. Thank you Sanjay.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r8, 2 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908)* status: all files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl and @wfa-mdharmalingam)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NRiDIIZ87jAvkoVJvGC:-NRiDIIZ87jAvkoVJvGD:b-hk5mjw) (no related file):*
I had mentioned this in one of our meetings, but the Bazel targets that generate the K8s object configs (manifests) are currently hard-coded to use the Google Cloud Container Registry. I've gone ahead and created PR #916 to respect the `container_registry` and `image_repo_prefix` vars.

___
___
*[`.github/workflows/k8s-secrets-kingdom.yml` line 1 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NRiD7hb3fYeU4AYRaAp:-NRiD7hb3fYeU4AYRaAq:b-3nvj4h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6e4acccb53cf5e662ca67d9ea26ae7b84c653f9a/.github/workflows/k8s-secrets-kingdom.yml#L1)):*
> ```YAML
> # Copyright 2023 The Cross-Media Measurement Authors
> ```

As indicated in the other comment, just use `bazelisk run //src/main/k8s/testing/secretfiles:apply_kustomization` to apply the secret for testing.
___
*[`.github/workflows/create-duchy.yml` line 1 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NRiCnmD2_K1XG7ypJIx:-NRiCnmD2_K1XG7ypJIy:bcr3qyz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6e4acccb53cf5e662ca67d9ea26ae7b84c653f9a/.github/workflows/create-duchy.yml#L1)):*
> ```YAML
> # Copyright 2023 The Cross-Media Measurement Authors
> ```

Unrelated change. This file should not be in this PR.

**Review by wfa-siyengar — APPROVED** [review]
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908)* status: all files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, and @wfa-mdharmalingam)

___
*[`.github/workflows/create-duchy.yml` line 1 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908#-NRiCnmD2_K1XG7ypJIx:-NRkDRq-9ZzXFJ9997RL:b-2ytuc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6e4acccb53cf5e662ca67d9ea26ae7b84c653f9a/.github/workflows/create-duchy.yml#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Unrelated change. This file should not be in this PR.
</blockquote></details>

It is removed from this PR. But this file is here due to a rebase. Request to not worry about it. in case of a merge conflict we will take care to use the version from main.

**Review by wfa-hkawalkar — APPROVED** [review]
> Reviewed 3 of 3 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/908)* status: all files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, and @wfa-mdharmalingam)

**Pull request closed without merging**
