### PR TITLE
Adding base test framework for react

### PR DESCRIPTION
**Pull request by bdomen-ggl**
Adding the base test framework for React integrated with Bazel.

Notes:
* Aspect_jest re-creates a jest config in the subpackage directory, which is used instead of a jest.config.js that I define. So I can't create a global, base jest config at the root.
* After testing a bit more, just having the modules in webpack was enough. I didn't need babelrc.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1085)

**Comment by bdomen-ggl** [comment]
@SanjayVas Ready for review. There's a weird linting error I'm working on, but I think the rest is good to start.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 9 of 14 files at r1, 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1085)* status: all files reviewed, 1 unresolved discussion

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 9 of 14 files at r1, 5 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1085)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Pull request merged**
