### PR TITLE
Implement event template and event filter for CsvEventQuery

### PR DESCRIPTION
**Pull request by jcorilla**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650)

### CODE REVIEW

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @matthewclegg and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650#-N8VeqXGD-xf1FGCFwey:-N8VeqXGD-xf1FGCFwez:b-n9hjqx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7f29bda4f50f34e6b879910a415e4e62671d7ac9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L35)):*
> ```Kotlin
> /** Fulfill the query with data pulled in from csv source. */
> // TODO replace csvEvents input with implementation of object from CSV reader
> class CsvEventQuery(csvEvents: List<Map<String, Any>>) : EventQuery() {
> ```

Just FYI I am still working on the part of querying data from CSV file https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/alberthsuu-local-csv

**Review by matthewclegg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650#-N8VeqXGD-xf1FGCFwey:-N8W0ts419sy1CDfhwIY:bbyhfud) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7f29bda4f50f34e6b879910a415e4e62671d7ac9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L35)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Just FYI I am still working on the part of querying data from CSV file https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/alberthsuu-local-csv
</blockquote></details>

My thinking had been that the filtering logic would be independent of the underlying data format or data source.  I had thought that this code would apply a CEL expression filter to a list of events or to a source of events, producing a stream of filtered events.  @uakyol , what are your thoughts?

**Review by uakyol — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @iverson52000, @matthewclegg, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650#-N8VeqXGD-xf1FGCFwey:-N8YRbuCAJJJ6D3BDq58:bwkh34u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7f29bda4f50f34e6b879910a415e4e62671d7ac9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L35)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

My thinking had been that the filtering logic would be independent of the underlying data format or data source.  I had thought that this code would apply a CEL expression filter to a list of events or to a source of events, producing a stream of filtered events.  @uakyol , what are your thoughts?
</blockquote></details>

EventQuery classes thus far are coupled with the underlying data sources. (e.g. BigDataEventQuery). I think this approach makes sense. 
" this code would apply a CEL expression filter to a list of events or to a source of events, producing a stream of filtered events" -> this is basically getUserVirtualIds function Joe implemented in this file. An improvement can be if/when there are other  EventQuery s that need filtering, we should move the code in this function to a common file that can be used elsewhere too.

**Review by uakyol — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @jcorilla, @matthewclegg, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650#-N8YUxqO8hSo3HWsWceq:-N8YUxqO8hSo3HWsWcer:b-kb4vfr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7f29bda4f50f34e6b879910a415e4e62671d7ac9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L34)):*
> ```Kotlin
> 
> /** Fulfill the query with data pulled in from csv source. */
> // TODO replace csvEvents input with implementation of object from CSV reader
> ```

Here is an example TODO comment. Please update accordingly : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55f6ea378f7386df5e30f072890c4fc5c2b73a4d/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L22

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @matthewclegg, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650#-N8YUxqO8hSo3HWsWceq:-N8_OJvpEdMjE73xX4OO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7f29bda4f50f34e6b879910a415e4e62671d7ac9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L34)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Here is an example TODO comment. Please update accordingly : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55f6ea378f7386df5e30f072890c4fc5c2b73a4d/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L22
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650#-N8VeqXGD-xf1FGCFwey:-N8_PI7k4p_aArLYiVSs:b-r8tu29) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7f29bda4f50f34e6b879910a415e4e62671d7ac9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L35)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

EventQuery classes thus far are coupled with the underlying data sources. (e.g. BigDataEventQuery). I think this approach makes sense. 
" this code would apply a CEL expression filter to a list of events or to a source of events, producing a stream of filtered events" -> this is basically getUserVirtualIds function Joe implemented in this file. An improvement can be if/when there are other  EventQuery s that need filtering, we should move the code in this function to a common file that can be used elsewhere too. 
</blockquote></details>

The filtering right now returns an Iterable Seqeunce of virtual ids as longs (but not events) like Ugur mentioned with an example filter expression written in the format below. Right now it just uses the filtering and matching from the EventFilter class, so it converts each "csv line" into the proto Message testEvent before any filtering.



_Code snippet:_
```Kotlin
private val EVENT_FILTER = eventFilter {
  expression =
    "privacy_budget.age.value == 1 || banner_ad.gender.value == 2"
}
```

**Review by uakyol — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @matthewclegg, and @uakyol)

**Review by iverson52000 — COMMENTED** [review]
The main focus of this PR is on event template so maybe a clearer PR title is "Implement event template and event filter for CsvEventQuery"

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650#-:-N93PPs26OYKgUNzU3lx:b-73yq4p)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @matthewclegg, and @uakyol)

**Review by jcorilla — COMMENTED** [review]
I agree - Done

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650#-:-N93rFNH7UsQ78sOqSJK:b-1efz4r)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @matthewclegg, and @uakyol)

**Review by jcorilla — COMMENTED** [review]
Merging will happen with the review for changes from @iverson52000 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650#-:-N9blpiW8FnC7Q1FODAZ:b-3glrp4)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 39 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650#-N9bSrSp3M6eMBAi2A2K:-N9bf9OW1q89nyr1yxUI:btmdaxx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56f4f3fa29e21e734da2787e4d12d7fd1b97d09e/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L39)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

nit: "Gender" seems to be a more appropriate name for column "Sex", right?
</blockquote></details>

The sample data we are testing with uses "Sex" as the heading while the proto message uses "Gender". Keeping this as "Sex" to match our current expected input - but would be good to know whether sex or gender would be the expected field for real data.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 70 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650#-N9bT92ODCfnRsldBti7:-N9bf-KY7WGYg-H8nEXI:bnfrro8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56f4f3fa29e21e734da2787e4d12d7fd1b97d09e/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L70)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

nit: you could just use long constants so you won't need to convert below
```val matchingVids = listOf(1000650L, 1000997L, 1001028L, 1001096L, 1001096L, 1001289L)```

same change would be needed in `CSV_EVENTS_LIST`
</blockquote></details>

Done (CSV_EVENTS_LIST still contains ints to match expected csv input)

**Comment by iverson52000** [comment]
Merging this PR to https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/669

**Review by matthewclegg — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/650)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @uakyol)

**Pull request closed without merging**
