### PR TITLE
Ensure Kingdom internal server only trusts Kingdom certs.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/430)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
This is just extra layer of protection. The internal server is already protected by the networkPolicy. Only kingdom pods can call the internal server.

If we want the ultimate security, maybe each server needs its own all_trusted_root_certs, e.g,
public_api_trusted_root_certs.pem
system_api_trusted_root_certs.pem
internal_api_trusted_root_certs.pem

but I am not sure if we need it since we are already using those akid for authentication.



 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/430#-:-MuY7fPyC3GlmpbOxjQp:b9zg9i5)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
Yeah, we should eventually split up the trusted cert collections to make them more granular, but the Kingdom internal server in particular is vulnerable due to not having any other auth. It's defense-in-depth, just in case someone gets network access.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/430#-:-MuYCX2t6YaPFd6Nt6N0:bbinazr)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/430)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/430)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/k8s/kingdom.cue, line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/430#-MulF9m53pd8Ua9S9roU:-MulF9m53pd8Ua9S9roV:b-cz6egg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f906af357006c638e769ca9c55aabfa5cf8d491d/src/main/k8s/kingdom.cue#L88)):*
> ```CUE
> 				_kingdom_tls_key_file_flag,
> 				// Internal Kingdom API server should only trust Kingdom certs.
> 				_kingdom_root_cert_file_flag,
> ```

Not sure how this will impact the health check probe in the dev deployment. Maybe the health_probe_root.pem also needs to be added into the trusted root certs list of the kingdom.

Even better, we may want to move the health probe cert config out of the base.cue, so we can use different health_probe_tls  certificates at different places in the test.

In production, this is not an issue since each component (kingdom or duchy) can use the same root to generate its health probe tls cert.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/430)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/430)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @wangyaopw)

___
*[`src/main/k8s/kingdom.cue` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/430#-MulF9m53pd8Ua9S9roU:-NDoov_R-KLFVreSlHcl:bn44wk1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f906af357006c638e769ca9c55aabfa5cf8d491d/src/main/k8s/kingdom.cue#L88)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Not sure how this will impact the health check probe in the dev deployment. Maybe the health_probe_root.pem also needs to be added into the trusted root certs list of the kingdom.

Even better, we may want to move the health probe cert config out of the base.cue, so we can use different health_probe_tls  certificates at different places in the test.

In production, this is not an issue since each component (kingdom or duchy) can use the same root to generate its health probe tls cert.
</blockquote></details>

The Health probe now runs on a different port without TLS.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/430)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[`src/main/k8s/kingdom.cue` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/430#-MulF9m53pd8Ua9S9roU:-NDorbXr63mQ03FEvK-s:b-7m74ox) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f906af357006c638e769ca9c55aabfa5cf8d491d/src/main/k8s/kingdom.cue#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The Health probe now runs on a different port without TLS.
</blockquote></details>

nice!

**Pull request merged**
