### PR TITLE
Check duchy identity in the kingdom system API.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/386)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/386)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationLogEntriesService.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/386#-Mpn6IJ_6ERP2MUAa00P:-Mpn6IJ_6ERP2MUAa00Q:b-7pyi1t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb41eb7fe1d60406585c5bad6a59dad0aaa9023a/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationLogEntriesService.kt#L38)):*
> ```Kotlin
>     request: CreateComputationLogEntryRequest
>   ): ComputationLogEntry {
>     duchyIdentityProvider()
> ```

What is this call for? Here and in `ComputationParticipantsService`

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/386)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationLogEntriesService.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/386#-Mpn6IJ_6ERP2MUAa00P:-Mpn9SmDCIw0SVpalgAe:b-ej38bd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb41eb7fe1d60406585c5bad6a59dad0aaa9023a/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationLogEntriesService.kt#L38)):*
> ```
> duchyIdentityProvider()
> ```
My understanding is that without explicitly calling it, the service won't try to get the identity from the context. The call is to force the following code to be executed. 
```
val duchyIdentityFromContext: DuchyIdentity
  get() =
    requireNotNull(DUCHY_IDENTITY_CONTEXT_KEY.get()) {
      "gRPC context is missing key $DUCHY_IDENTITY_CONTEXT_KEY"
    }
```
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L46

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/386)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationLogEntriesService.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/386#-Mpn6IJ_6ERP2MUAa00P:-MpnF1zj0G1-JvKx2yK8:bqq8m8b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb41eb7fe1d60406585c5bad6a59dad0aaa9023a/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationLogEntriesService.kt#L38)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> duchyIdentityProvider()
> ```
My understanding is that without explicitly calling it, the service won't try to get the identity from the context. The call is to force the following code to be executed. 
```
val duchyIdentityFromContext: DuchyIdentity
  get() =
    requireNotNull(DUCHY_IDENTITY_CONTEXT_KEY.get()) {
      "gRPC context is missing key $DUCHY_IDENTITY_CONTEXT_KEY"
    }
```
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L46
</blockquote></details>

If the call is supposed to be authenticated and the credentials are missing, it should result in an`UNAUTHENTICATED` gRPC error. I believe this already occurs in the interceptor. This is why the `duchyIdentityFromContext` getter uses `requireNotNull`, as it represents a programming error (e.g. interceptor not installed).

We should just call `duchyIdentityProvider()` when we need to check the caller Duchy, which we should incidentally be doing for every method in ComputationParticipants service (comparing to the Duchy ID in the resource name).

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/386)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationLogEntriesService.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/386#-Mpn6IJ_6ERP2MUAa00P:-MpnL2zH4ISCowlfPVnn:b-ks41ef) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb41eb7fe1d60406585c5bad6a59dad0aaa9023a/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationLogEntriesService.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If the call is supposed to be authenticated and the credentials are missing, it should result in an`UNAUTHENTICATED` gRPC error. I believe this already occurs in the interceptor. This is why the `duchyIdentityFromContext` getter uses `requireNotNull`, as it represents a programming error (e.g. interceptor not installed).

We should just call `duchyIdentityProvider()` when we need to check the caller Duchy, which we should incidentally be doing for every method in ComputationParticipants service (comparing to the Duchy ID in the resource name).
</blockquote></details>

yep, you are right.

Updated

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/386)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by chipingyeh — APPROVED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/386)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
