### PR TITLE
Add terraform for AWS worker2 duchy infrastructures

### PR DESCRIPTION
**Pull request by YuhongWang-Amazon**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 24 files at r1, 3 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237)* status: 11 of 24 files reviewed, 8 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/terraform/aws/cmms/duchies.tf` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NetmNCpBubJoqXQ4mW1:-NetmNCpBubJoqXQ4mW2:b-dcab7j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/cmms/duchies.tf#L88)):*
> ```HCL
> }
> 
> provider "kubernetes" {
> ```

Do you not need the same `depends_on` trick here that we have to use with the Google provider? There we end up needing to do a separate read to handle the case when the cluster doesn't already exist (and therefore we cannot automatically use properties like `cluster_certificate_authority_data`)?
___
*[`src/main/terraform/aws/cmms/main.tf` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NetoJJ1-v0LfxbMZlXu:-NetoJJ1-v0LfxbMZlXv:bnjr9qc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/cmms/main.tf#L17)):*
> ```HCL
> terraform {
>   backend "s3" {
>     bucket = "halo-cmm-dev-tf-state"
> ```

Don't hard-code the bucket and region. These should come from the caller's backend configuration.
___
*[`src/main/terraform/aws/cmms/README.md` line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NetooHq7aR0JmEgGfX3:-NetooHq7aR0JmEgGfX4:bqdraan) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/cmms/README.md#L3)):*
> ```Markdown
> # Cross-Media Measurement System
> 
> Root module for a single-project CMMS and Reporting system. This is generally
> ```

This isn't true here. The root module just gives you infra for one Duchy, not a whole CMMS (Kingdom and Duchies) and a whole Reporting system.



_Code quote:_
```Markdown
single-project CMMS and Reporting system
```
___
*[`src/main/terraform/aws/cmms/variables.tf` line 18 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-Netp5uzDjPtUFuDYhGn:-Netp5uzDjPtUFuDYhGo:b-bigbee) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/cmms/variables.tf#L18)):*
> ```HCL
>   description = "AWS region"
>   type        = string
>   default     = "us-west-2"
> ```

Avoid having defaults for regions if we can. I think the only place where it even appears that we do this in the gcloud modules is the Spanner instance config, and only because the configuration name just *happens* to be based on the Spanner region (which may be independent of your cluster zone/region).
___
*[`src/main/terraform/aws/modules/duchy/main.tf` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NetphOW7nOm627NAU8M:-NetphOW7nOm627NAU8N:by845im) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/modules/duchy/main.tf#L44)):*
> ```HCL
>         ],
>         "Resource" : [
>           "arn:aws:secretsmanager:us-west-2:010295286036:secret:rds!*"
> ```

Is it okay for this to be a hard-coded value? (I'm not actually sure what this is)
___
*[`src/main/terraform/aws/modules/duchy/variables.tf` line 16 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NetlnUp3fvN6o4RYCfw:-NetlnUp3fvN6o4RYCfx:bgwjd1q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/modules/duchy/variables.tf#L16)):*
> ```HCL
> 
> variable "eks_oidc_provider_arn" {
>   type     = string
> ```

nit: include description for every variable
___
*[`src/main/terraform/aws/modules/duchy/variables.tf` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NetljrM7N5Jgsy3EYBD:-NetljrM7N5Jgsy3EYBE:btkiusf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/modules/duchy/variables.tf#L21)):*
> ```HCL
> 
> variable "s3_bucket_arn" {
>   description = "arn of the s3 bucket"
> ```

nit: appropriate capitalization in descriptions



_Suggestion:_
```HCL
  description = "ARN of the S3 bucket"
```
___
*[`src/main/terraform/aws/modules/eks-cluster/main.tf` line 119 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NetnJdi9vcNCA0to7KZ:-NetnJdi9vcNCA0to7K_:bgtq2at) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/modules/eks-cluster/main.tf#L119)):*
> ```HCL
> }
> 
> resource "helm_release" "aws_load_balancer_controller" {
> ```

I guess EKS clusters don't come with load balancing by default? On GKE, everything in the kube-system namespace gets created for you based on your settings in the cluster resource.

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237)* status: 5 of 24 files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/terraform/aws/cmms/duchies.tf` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NetmNCpBubJoqXQ4mW1:-Nf9YzMfCama6HUQUpbm:b-ls5ltp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/cmms/duchies.tf#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do you not need the same `depends_on` trick here that we have to use with the Google provider? There we end up needing to do a separate read to handle the case when the cluster doesn't already exist (and therefore we cannot automatically use properties like `cluster_certificate_authority_data`)?
</blockquote></details>

I was able to use this  terraform to create a new eks cluster. My assumption is that this provider used some output from the eks module which implicitly adds a dependency on the creation of the cluster.
___
*[`src/main/terraform/aws/cmms/main.tf` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NetoJJ1-v0LfxbMZlXu:-Nf9_TMkEh2cSTh2Z_mS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/cmms/main.tf#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't hard-code the bucket and region. These should come from the caller's backend configuration.
</blockquote></details>

Done.
___
*[`src/main/terraform/aws/cmms/README.md` line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NetooHq7aR0JmEgGfX3:-Nf9Zs_W4dGgpK5SbLvj:bv7tu9b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/cmms/README.md#L3)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This isn't true here. The root module just gives you infra for one Duchy, not a whole CMMS (Kingdom and Duchies) and a whole Reporting system.
</blockquote></details>

Done. Updated to use [partial configuration](https://developer.hashicorp.com/terraform/language/settings/backends/configuration#partial-configuration). The bucket and region are expected to be passed in from init command as follows:
```
terraform init \                                       
-backend-config="bucket=${TFSTATE_BUCKET}" \
-backend-config="region=${TFSTATE_REGION}"
```
___
*[`src/main/terraform/aws/cmms/variables.tf` line 18 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-Netp5uzDjPtUFuDYhGn:-Nf9a8VC9jtxEwdXoC5P:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/cmms/variables.tf#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Avoid having defaults for regions if we can. I think the only place where it even appears that we do this in the gcloud modules is the Spanner instance config, and only because the configuration name just *happens* to be based on the Spanner region (which may be independent of your cluster zone/region).
</blockquote></details>

Done.
___
*[`src/main/terraform/aws/modules/duchy/main.tf` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NetphOW7nOm627NAU8M:-Nf9aFL37_3UOO3iBio8:b-1lrhcy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/modules/duchy/main.tf#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is it okay for this to be a hard-coded value? (I'm not actually sure what this is)
</blockquote></details>

This is the secrets manager secret name, which stores the postgres user credentials.
In my current setup, this secret key will be automatically generated by the RDS postgres, with a prefix. `arn:aws:secretsmanager:us-west-2:010295286036:secret:rds!`.  I replaced the region and account id in this ARN with variables.
___
*[`src/main/terraform/aws/modules/eks-cluster/main.tf` line 119 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NetnJdi9vcNCA0to7KZ:-Nf9cCKpCPm3813SZfM3:bebfah6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1112307cb2975d9413786b2182d85141b30f89f/src/main/terraform/aws/modules/eks-cluster/main.tf#L119)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I guess EKS clusters don't come with load balancing by default? On GKE, everything in the kube-system namespace gets created for you based on your settings in the cluster resource.
</blockquote></details>

By default, EKS use classic AWS loadbalancer for K8s service, which does not support some of the required features and is not very flexible. E.g. it does not work with fargate pods, it does not support fixed elastic IP neither.
This [aws-load-balancer-controller addon](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/service/nlb_ip_mode/) will create a newer version of NLB resource. This addon also supports a bunch of annotations for customization.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 7 of 24 files at r1, 6 of 9 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237)* status: all files reviewed, 2 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/terraform/aws/modules/rds-postgres/main.tf` line 44 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NfCW8Kp-OzeIuYvZ8gs:-NfCW8Kp-OzeIuYvZ8gt:b-8elsfm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76aef43269d5e11da1c04d46ef42d40fda653826/src/main/terraform/aws/modules/rds-postgres/main.tf#L44)):*
> ```HCL
>   engine         = "postgres"
>   engine_version = "15.4"
>   instance_class = "db.t3.micro"
> ```

nit: this should probably be a variable.

Reusable modules should have variables for whatever someone might want to configure. The root/example modules need only have variables for whatever would differ by environment (e.g. region), but can fill in values like this.
___
*[`src/main/terraform/aws/modules/s3-bucket/outputs.tf` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237#-NfCWma25BbN1EUbmo1U:-NfCWma25BbN1EUbmo1V:b-3matv9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76aef43269d5e11da1c04d46ef42d40fda653826/src/main/terraform/aws/modules/s3-bucket/outputs.tf#L15)):*
> ```HCL
> # limitations under the License.
> 
> output "s3_bucket_arn" {
> ```

nit: prefer outputting the entire created resource

**Review by YuhongWang-Amazon — COMMENTED** [review]
> Reviewed 9 of 24 files at r1, 6 of 9 files at r2, 5 of 6 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1237)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Pull request merged**
