### PR TITLE
Implement SpannerModelProvidersService.

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/199)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/199)* status: all files reviewed, 1 unresolved discussion (waiting on @kgaynor, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelProvidersServiceTest.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/199#-MhEtwBgEpH7xjHBCWsJ:-MhEtwBh4TRmSzOwhtD5:b-es5pep) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8dfa95e6a26fb1c8929e2daf1d53ac0d739e77b/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelProvidersServiceTest.kt#L40)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> abstract class ModelProvidersServiceTest<T : ModelProvidersCoroutineImplBase> {
> ```

Do we need this to use generics?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/199)* status: 9 of 16 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelProvidersServiceTest.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/199#-MhEtwBgEpH7xjHBCWsJ:-MhEy2Wn05qiDsIg_C8R:bb710yj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8dfa95e6a26fb1c8929e2daf1d53ac0d739e77b/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelProvidersServiceTest.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do we need this to use generics?
</blockquote></details>

Nope

**Review by efoxepstein — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/199)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kgaynor and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 9 of 16 files at r1, 2 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/199)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kgaynor)

**Review by yunyeng — COMMENTED** [review]
> Reviewed 6 of 16 files at r1, 2 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/199)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
