### PR TITLE
input task should allow an additional certificate-resource-name input

### PR DESCRIPTION
**Pull request by stevenwarejones**
This fixes an issue where ProductionExchangeTaskMapper had no tests nor were any of the e2e workflow tests testing generate_certificate step. Additionally, this alters the export task to allow 2 inputs labels now:
1. The file to export
2. The certificate of the exported resource (in order to wait for generation). https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1330/files previously added this step but because those workflows were not being tested, this issue was missed.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1358)

**Review by stevenwarejones — COMMENTED** [review]
@SanjayVas - might be good to get this into 0.4.3. What's our process for that currently? Open a pr against that branch?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1358#-:-NlUd_h-0_Ez6sugWOAZ:b-a0y3o1)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jonmolle, @Marco-Premier, and @SanjayVas)

**Review by jonmolle — APPROVED** [review]
LGTM, I didn't realize single supported a predicate.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1358#-:-NlV0eUg39Q97bhrZOYJ:bwqf4ie)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> [@SanjayVas](https://github.com/SanjayVas) - might be good to get this into 0.4.3. What's our process for that currently? Open a pr against that branch?

Yeah, open a PR against the v0.4.x branch with cherry-picks and make sure the tests pass. Make sure the final merge commit has the cherry-pick info (e.g. "cherry picked from ..."). Once merged we can cut a new release. Note that the AWS EKS worker2 Duchy in halo-cmm-dev might have to be manually turned down to avoid conflicts when K8s testing in that environment since v0.4.x still has that Duchy on GKE.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1358#-:-Nl_9SaW08gWJcoVHwut:bqefeoj)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1358)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapperTest.kt` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1358#-NljfVw52kdp2ZZ_bDdl:-NljfVw52kdp2ZZ_bDdm:bpoe1t5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bc76f613147ccdb4b30078d49adc5478863702ae/src/test/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapperTest.kt#L41)):*
> ```Kotlin
> import org.wfanet.panelmatch.common.testing.runBlockingTest
> 
> private val WORKFLOW = exchangeWorkflow {
> ```

nit: put constants in the companion object in new code

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1358)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
