### PR TITLE
Implement public authenticate.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 142 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-Motqyz9EFX-wb4yxX7K:-MotqyzA3PnVFDhJEaM3:b-bdhi5l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2daa725ec24566b124e3ca22f1c8a449bbbe3b68/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L142)):*
> ```Kotlin
>       internalAccountsStub.generateOpenIdRequestParams(generateOpenIdRequestParamsRequest {})
> 
>     var uriString =
> ```

I'd recommend building the query part of the URI as a list of strings and joining with `&` rather than concatenating.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 145 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-MotXVmY5X1R7jXi4-mK:-MotXVmY5X1R7jXi4-mL:boxywet) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2daa725ec24566b124e3ca22f1c8a449bbbe3b68/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L145)):*
> ```
> Longs.toByteArray(openIdRequestParams.state).base64UrlEncode()
> ```
Convert this to a public API ID instead (`externalIdToApiId`)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 147 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-MotWsaC-9ZE0j4w1gpf:-MotWsaC-9ZE0j4w1gpg:b8hs8gw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2daa725ec24566b124e3ca22f1c8a449bbbe3b68/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L147)):*
> ```
> Longs.toByteArray(openIdRequestParams.nonce).base64UrlEncode()
> ```
The nonce is expected to be a number, so this can just be openIdRequestParams.nonce.toString()

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 147 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-MotWsaC-9ZE0j4w1gpf:-MouMdxFAhfUzJWjfQqk:bf3qmtm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dbf42b1207c414b4a5a33682ac7779c335a54f90/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L147)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Longs.toByteArray(openIdRequestParams.nonce).base64UrlEncode()
> ```
The nonce is expected to be a number, so this can just be openIdRequestParams.nonce.toString()
</blockquote></details>

The examples in the open id spec are just strings, including letters, and the description says string.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 147 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-MotWsaC-9ZE0j4w1gpf:-MouO-ag9XndQQPvgmzj:b-d43zfk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dbf42b1207c414b4a5a33682ac7779c335a54f90/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L147)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The examples in the open id spec are just strings, including letters, and the description says string.
</blockquote></details>

Hrm, okay. If a string, then use the same `externalIdToApiId`.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 145 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-MotXVmY5X1R7jXi4-mK:-MouQZLI5ADAT4HKHcuI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dbf42b1207c414b4a5a33682ac7779c335a54f90/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L145)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Longs.toByteArray(openIdRequestParams.state).base64UrlEncode()
> ```
Convert this to a public API ID instead (`externalIdToApiId`)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 147 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-MotWsaC-9ZE0j4w1gpf:-MouQZkK8BCzvw9PZweb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dbf42b1207c414b4a5a33682ac7779c335a54f90/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L147)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Hrm, okay. If a string, then use the same `externalIdToApiId`.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-MpgteNjAnR_ZKytYS6Q:-MpgteNjAnR_ZKytYS6R:b-j8c2q0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84db61f16c2b54bee21af3799d3f25e539404ce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L50)):*
> ```
> private const val REDIRECT_URI = "https://localhost:2048"
> ```
This should be a command-line flag value.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 147 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-Mpgttmo1x8JDCSIWA3j:-Mpgttmo1x8JDCSIWA3k:bk3s37z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84db61f16c2b54bee21af3799d3f25e539404ce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L147)):*
> ```
> "https://self-issued.me"
> ```
Extract constant

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-MpgteNjAnR_ZKytYS6Q:-Mph2wP1E9dZwfxY9P4N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84db61f16c2b54bee21af3799d3f25e539404ce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> private const val REDIRECT_URI = "https://localhost:2048"
> ```
This should be a command-line flag value.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 147 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-Mpgttmo1x8JDCSIWA3j:-Mph2xDP41PZHyM0jwvJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84db61f16c2b54bee21af3799d3f25e539404ce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L147)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> "https://self-issued.me"
> ```
Extract constant
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-Mph4YAYCGUaeeaMCu3Z:-Mph4YAYCGUaeeaMCu3_:benj1xk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13753f5496ba48fc613033733f3c13ca7269a07b/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L54)):*
> ```
> ""
> ```
This shouldn't be optional.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376#-Mph4YAYCGUaeeaMCu3Z:-Mph810fAHf4uNdrIgX6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13753f5496ba48fc613033733f3c13ca7269a07b/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ""
> ```
This shouldn't be optional.
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by tristanvuong2021 — COMMENTED** [review]
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @SanjayVas and @tristanvuong2021)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
