### PR TITLE
feat: Report processor supports custom measurement policy.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/test/python/wfa/measurement/reporting/postprocessing/tools/test_post_process_origin_report.py` line 209 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-OEKpZsNCOIk5x3K4R-w:-OEKpZsNCOIk5x3K4R-x:bdwu9ep) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/741259c62e70430ab275d9b7a8c6f7cbb9c7e361/src/test/python/wfa/measurement/reporting/postprocessing/tools/test_post_process_origin_report.py#L209)):*
> ```Python
>                          expected_unique_reach_map)
> 
>   def test_report_with_custom_policy_is_corrected_successfully(self):
> ```

where are you comparing custom to AMI?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/test/python/wfa/measurement/reporting/postprocessing/tools/test_post_process_origin_report.py` line 209 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-OEKpZsNCOIk5x3K4R-w:-OEKvCrH0xAtIOfgglMk:b-spk15d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/741259c62e70430ab275d9b7a8c6f7cbb9c7e361/src/test/python/wfa/measurement/reporting/postprocessing/tools/test_post_process_origin_report.py#L209)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

where are you comparing custom to AMI?
</blockquote></details>

Thanks for spotting this. I've added the asserts to check these relationships.

**Review by kungfucraig — COMMENTED** [review]
Python LGTM

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-:-OEKvkVZ5Hk_HpCp6RSp:b-frzdxp)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by kungfucraig — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-:-OEKvpZk8kYO4TVXCL65:bnfp4nl)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @ple13, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorTest.kt` line 43 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-OEL9zIOAf6riviHDuv6:-OEL9zIPC6nWzStpLb9W:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45b65797cfc7c47be240ccec7e545d7bd862d478/src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorTest.kt#L43)):*
> ```Kotlin
>     val updatedReportAsJson = ReportProcessor.processReportJson(reportAsJson)
>     val updatedReport = ReportConversion.getReportFromJsonString(updatedReportAsJson)
>     assertThat(updatedReport.hasConsistentCumulativeMeasurements()).isEqualTo(true)
> ```

nit



_Suggestion:_
```Kotlin
isTrue()
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorTest.kt` line 124 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-OELAV16CNPE7OjCAzMs:-OELAV16CNPE7OjCAzMt:b-9mvl95) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45b65797cfc7c47be240ccec7e545d7bd862d478/src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorTest.kt#L124)):*
> ```Kotlin
>         metricReportByPolicy[policy] = this.toMetricReport(policy)
>       }
>       return metricReportByPolicy
> ```

nit: use idiomatic Kotlin structures, defining a constant for the set of policies



_Suggestion:_
```Kotlin
      return POLICIES.associateWith { policy -> this.toMetricReport(policy) }
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorTest.kt` line 153 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-OELBdvw-FRPui7xSDdF:-OELBdvw-FRPui7xSDdG:b7cytfp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45b65797cfc7c47be240ccec7e545d7bd862d478/src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorTest.kt#L153)):*
> ```Kotlin
>         }
>       }
>       return true
> ```

nit: use idiomatic Kotlin structures



_Suggestion:_
```Kotlin
      return this.toReportSummaries().all {
        it.toReportByPolicy().values.all { metricReport ->
          metricReport.hasConsistentCumulativeMeasurements()
        }
      }
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversionTest.kt` line 118 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-OEL928TC-lXPjVUwjrf:-OEL928TC-lXPjVUwjrg:b-1k2vbt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45b65797cfc7c47be240ccec7e545d7bd862d478/src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversionTest.kt#L118)):*
> ```Kotlin
>           )
>       )
>       .isEqualTo(true)
> ```

Use the features of Truth subjects. You should rarely be using `isEqualTo` with a boolean, and only using booleans or `isTrue`/`isFalse` if the actual value you're comparing to is inherently a boolean.

Note that the below suggestion does not compare order by default. You can add `.inOrder()` to do that.



_Suggestion:_
```Kotlin
    assertThat(reportSummary[0].measurementDetailsList)
      .containsExactly(unionCustomEdp1Edp2MeasurementDetail, cummulativeCustomEdp1Edp2MeasurementDetail)
```

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversionTest.kt` line 118 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-OEL928TC-lXPjVUwjrf:-OELG0ev9368g1WkuPL8:bgoczyp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45b65797cfc7c47be240ccec7e545d7bd862d478/src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversionTest.kt#L118)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the features of Truth subjects. You should rarely be using `isEqualTo` with a boolean, and only using booleans or `isTrue`/`isFalse` if the actual value you're comparing to is inherently a boolean.

Note that the below suggestion does not compare order by default. You can add `.inOrder()` to do that.
</blockquote></details>

These are just two out of many protos that are in the report summary[0].measurementDetailsList. As the list is long, I only check a few custom measurements to make sure that the report is parsed correctly.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorTest.kt` line 43 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-OEL9zIOAf6riviHDuv6:-OELDzBd4as4OQthNdof:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45b65797cfc7c47be240ccec7e545d7bd862d478/src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorTest.kt#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorTest.kt` line 124 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-OELAV16CNPE7OjCAzMs:-OELF_LeCyOJ-Re-iiLv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45b65797cfc7c47be240ccec7e545d7bd862d478/src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorTest.kt#L124)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use idiomatic Kotlin structures, defining a constant for the set of policies
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorTest.kt` line 153 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-OELBdvw-FRPui7xSDdF:-OELFya0Esp_lNd5KRzI:boyexbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45b65797cfc7c47be240ccec7e545d7bd862d478/src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportProcessorTest.kt#L153)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use idiomatic Kotlin structures
</blockquote></details>

Done. Thanks.

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

**Review by kungfucraig — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
Approved for Kotlin

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-:-OELHl-mBppFzMQ7ii0T:b-uydias)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversionTest.kt` line 118 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-OEL928TC-lXPjVUwjrf:-OELHS644WjBj9kkqBcS:b-qkntia) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45b65797cfc7c47be240ccec7e545d7bd862d478/src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversionTest.kt#L118)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

These are just two out of many protos that are in the report summary[0].measurementDetailsList. As the list is long, I only check a few custom measurements to make sure that the report is parsed correctly.
</blockquote></details>

You can use `containsAtLeast` then to still check multiple as you were doing before.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversionTest.kt` line 118 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974#-OEL928TC-lXPjVUwjrf:-OELeY_O57JjuQ4UL1aK:boyexbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45b65797cfc7c47be240ccec7e545d7bd862d478/src/test/kotlin/org/wfanet/measurement/reporting/postprocessing/v2alpha/ReportConversionTest.kt#L118)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can use `containsAtLeast` then to still check multiple as you were doing before.
</blockquote></details>

Done. Thanks.

**Review by ple13 — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1974)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
