### PR TITLE
Add target for exporting shareshuffle library as a Maven artifact.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1674)

**Comment by SanjayVas** [comment]
Depends on https://github.com/world-federation-of-advertisers/common-jvm/pull/256

**Review by kungfucraig — APPROVED** [review]
Thank you for doing this!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1674#-:-O0PAmJwEQNBbBD6nbve:bff479j)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/FulfillRequisitionRequestBuilder.kt` line 168 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1674#-O0PBFHSC1DHZIAaGdY9:-O0PBFHT3FIwrLHY2hKu:b-46y85m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7093942bf3b12ad5034c15c7284b31a62c1461e3/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/FulfillRequisitionRequestBuilder.kt#L168)):*
> ```Kotlin
>     }
> 
>     private fun loadNativeLibrary() {
> ```

nit: Inline this in the init block or leave a TODO to move it to common JVM?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1674)* status: 1 of 8 files reviewed, all discussions resolved (waiting on @kungfucraig)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1674#-O0RSbiS8DcfwBD81bfK:-O0RSbiS8DcfwBD81bfL:b-4nulu8) (no related file):*
I reworked this a bit to behave more like native TLS deps for grpc-java. There's a separate `shareshuffle-native` artifact that you can add as a runtime dependency. If it's found, the native library will be loaded from there. If not, it'll be loaded from your library path.

This gives a convenient way for anyone to use our prebuilt shared library if they desire. Otherwise they can compile it themselves (e.g. with a different libc) and include it in their library path.

___
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/FulfillRequisitionRequestBuilder.kt` line 168 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1674#-O0PBFHSC1DHZIAaGdY9:-O0RSJ6o0yCPGHNybEPS:bi483io) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7093942bf3b12ad5034c15c7284b31a62c1461e3/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/FulfillRequisitionRequestBuilder.kt#L168)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

nit: Inline this in the init block or leave a TODO to move it to common JVM?
</blockquote></details>

This is extracted to a function rather than having a comment over a block of code. It's a common readability pattern.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1674)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1674)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @kungfucraig and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1674#-O0W7yG3BnECvpDUd7AI:-O0W7yG43gQArFwTBX4d:brdg3h) (no related file):*
Will follow up with a workflow to publish these artifacts on release.

___

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 6 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1674)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Pull request merged**
