### PR TITLE
Set up testing path for internal kingdom services

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczF1gv2L1M5ZIEII4S:-MczF1gv2L1M5ZIEII4T:b-nmj71h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d772b48212a8821e017127ebf0afffbc1699eee8/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L31)):*
> ```Kotlin
>   abstract val service: MeasurementConsumersCoroutineImplBase
>   @Test
>   fun `getMeasurementConsumer fails for missing MeasurementConsumer`() = runBlocking {
> ```

are these just two examples here? I assume there would be more tests here.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersServiceTest.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczEHh67EmTC_K7H8ad:-MczEHh67EmTC_K7H8ae:b-3ljbvr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d772b48212a8821e017127ebf0afffbc1699eee8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersServiceTest.kt#L25)):*
> ```
> MeasurementConsumersServiceTest
> ```
I guess I didn't fully follow the discussion about https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/103, but now I got the idea.


just a question, do you expect adding any additional spanner specific test here?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczHS_r4iatLDjO_T1u:-MczHS_r4iatLDjO_T1v:b3vpf37) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d772b48212a8821e017127ebf0afffbc1699eee8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt#L26)):*
> ```
> KingdomDataServicesProviderRule
> ```
naming it `SpannerKingdomDataServicesProviderRule`?

I know the path already has spanner in it, but similar to /spanner/SpannerMeasurementConsumerService.kt, a `spanner` in the class name is more clear.

**Comment by uakyol** [comment]
Part of #103

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczHS_r4iatLDjO_T1u:-MczJ6u88RMoCKha-6NZ:b1hxa1z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d772b48212a8821e017127ebf0afffbc1699eee8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt#L26)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> KingdomDataServicesProviderRule
> ```
naming it `SpannerKingdomDataServicesProviderRule`?

I know the path already has spanner in it, but similar to /spanner/SpannerMeasurementConsumerService.kt, a `spanner` in the class name is more clear.
</blockquote></details>

We can do that, another point is that we named it KingdomDatabasesProviderRule etc.. for the previous files
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczF1gv2L1M5ZIEII4S:-MczIolYDHyX1y-3Dqc7:b-42qiq4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d772b48212a8821e017127ebf0afffbc1699eee8/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L31)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

are these just two examples here? I assume there would be more tests here.
</blockquote></details>

Correct. just examples, there will be more.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersServiceTest.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczEHh67EmTC_K7H8ad:-MczIzOVBS6-oB7nrGvh:b-5fjndp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d772b48212a8821e017127ebf0afffbc1699eee8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersServiceTest.kt#L25)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> MeasurementConsumersServiceTest
> ```
I guess I didn't fully follow the discussion about https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/103, but now I got the idea.


just a question, do you expect adding any additional spanner specific test here?


</blockquote></details>

I am not planning on adding any DB type specific tests. Do you have some in mind?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersServiceTest.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczEHh67EmTC_K7H8ad:-MczJgV8721QUWf_0HnK:bmcvp6i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d772b48212a8821e017127ebf0afffbc1699eee8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersServiceTest.kt#L25)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I am not planning on adding any DB type specific tests. Do you have some in mind?
</blockquote></details>

I raised this question because I was wondering where we put those spanner specific helper methods.

For example, create a requisition such that we can test GetRequisition(). The only place I can think of is at the KingdomDatabasesProviderRule or KingdomDatabase, but it is a little weird to put so many helper methods there.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersServiceTest.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczEHh67EmTC_K7H8ad:-MczO5-R5hqiKW7EkE0M:bwhaysd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d772b48212a8821e017127ebf0afffbc1699eee8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersServiceTest.kt#L25)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I raised this question because I was wondering where we put those spanner specific helper methods.

For example, create a requisition such that we can test GetRequisition(). The only place I can think of is at the KingdomDatabasesProviderRule or KingdomDatabase, but it is a little weird to put so many helper methods there.
</blockquote></details>

nvm, I think we don't need those helper methods at all. We'll just write all test using the interface only.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: all files reviewed, 3 unresolved discussions (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/KingdomDataServices.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczSD3p0f-1WB68h7_r:-MczSD3q0MZDf5W53twA:bnkrkxg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d772b48212a8821e017127ebf0afffbc1699eee8/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/KingdomDataServices.kt#L19)):*
> ```Kotlin
> import org.wfanet.measurement.internal.kingdom.MeasurementConsumersGrpcKt.MeasurementConsumersCoroutineImplBase
> 
> data class KingdomDataServices(
> ```

Why have this be just for testing? If we want to define a data class like this, it would make sense to also use it in the DataServices interface. This way, you can guarantee that any implementation binds all the necessary service impls.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersServiceTest.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczEHh67EmTC_K7H8ad:-MczT1Zk1ZaXlX-cMBaU:b4u9o76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d772b48212a8821e017127ebf0afffbc1699eee8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersServiceTest.kt#L25)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

nvm, I think we don't need those helper methods at all. We'll just write all test using the interface only.
</blockquote></details>

Correct. We expect each impl of the abstract MeasurementConsumersServiceTest to just instantiate the service impls. We *could* theoretically add tests that poke the underlying tables, but that's testing implementation details rather than what's observable through the interface (generally a bad practice).

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersServiceTest.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczEHh67EmTC_K7H8ad:-MczYckI33KvsIpyMp6p:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4e0e95eb6da092b0fdec40afc7090afe161d86e/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersServiceTest.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Correct. We expect each impl of the abstract MeasurementConsumersServiceTest to just instantiate the service impls. We *could* theoretically add tests that poke the underlying tables, but that's testing implementation details rather than what's observable through the interface (generally a bad practice).
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/KingdomDataServices.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczSD3p0f-1WB68h7_r:-Md-7iAB88Zvdy2ORGK0:bnx7mjr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4e0e95eb6da092b0fdec40afc7090afe161d86e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/KingdomDataServices.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why have this be just for testing? If we want to define a data class like this, it would make sense to also use it in the DataServices interface. This way, you can guarantee that any implementation binds all the necessary service impls.
</blockquote></details>

Thank you for the discussion, implemented it.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt, line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-Md-CT5W7T6YUIygfxG3:-Md-CT5XCzqtRm5Eyeo6:bhr2xha) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f08a28c6543d1b1538df61cea8e229ce2beda7a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt#L47)):*
> ```
> DataServices 
> ```
we have two more now, ComputationParticipantsService and MeasurementLogEntriesService

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczHS_r4iatLDjO_T1u:-Md-CfaV0K9beX-R3cKF:bwp889c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4e0e95eb6da092b0fdec40afc7090afe161d86e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt#L26)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

We can do that, another point is that we named it KingdomDatabasesProviderRule etc.. for the previous files
</blockquote></details>

I've no strong opinion. @sanjayvas, what is your suggestion here?

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczHS_r4iatLDjO_T1u:-Md-Cv8G8SQ5zh9Tj02r:bxjei6c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4e0e95eb6da092b0fdec40afc7090afe161d86e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt#L26)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I've no strong opinion. @sanjayvas, what is your suggestion here?
</blockquote></details>

oops, you have already added kingdom to the class name. nvm

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczHS_r4iatLDjO_T1u:-Md-D5ZA5r2SR269Dqqo:b-m2h03p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4e0e95eb6da092b0fdec40afc7090afe161d86e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt#L26)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

oops, you have already added kingdom to the class name. nvm
</blockquote></details>

sorry, we were talking about adding a `spanner` prefix, not `kingdom`.... not sure what I was thinking.

**Review by SanjayVas — APPROVED** [review]
> Setup testing path for internal kingdom services

nit: "Set up" for verb phrase, vs. "setup" for singular noun.

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-:-Md-HAR1CX9Yg7EfNCY4:b7cnsq1)* status: all files reviewed, 2 unresolved discussions (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczHS_r4iatLDjO_T1u:-Md-Fwyw1TsFubj_Wy7P:b-plr6d3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4e0e95eb6da092b0fdec40afc7090afe161d86e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt#L26)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

sorry, we were talking about adding a `spanner` prefix, not `kingdom`.... not sure what I was thinking.
</blockquote></details>

So the rule of thumb I use is that I normally avoid redundant naming for things already covered by the package, *except* in cases where the differentiation would be useful. One such case where it's often useful is to identify the particular implementation of an interface or base class. Hence, I'd lean towards adding Spanner here. That said, I also have no strong preference given that I don't expect this to be used outside of the spanner package tree.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: 7 of 16 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt, line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-Md-CT5W7T6YUIygfxG3:-Md-IXNu6idUGZJuxgl1:bh8anzk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f08a28c6543d1b1538df61cea8e229ce2beda7a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt#L47)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> DataServices 
> ```
we have two more now, ComputationParticipantsService and MeasurementLogEntriesService
</blockquote></details>

Thanks for catching. Added them.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 2 of 10 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @wangyaopw, and @zachcwc)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 2 of 10 files at r2, 8 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw and @zachcwc)

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczHS_r4iatLDjO_T1u:-Md-uh1j5SU1hWxHWbSv:bke8xyr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4e0e95eb6da092b0fdec40afc7090afe161d86e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

So the rule of thumb I use is that I normally avoid redundant naming for things already covered by the package, *except* in cases where the differentiation would be useful. One such case where it's often useful is to identify the particular implementation of an interface or base class. Hence, I'd lean towards adding Spanner here. That said, I also have no strong preference given that I don't expect this to be used outside of the spanner package tree.
</blockquote></details>

Since this doesn't seem to be a huge issue. I am merging this PR in the spirit of moving fast and leaving this as is.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-MczHS_r4iatLDjO_T1u:-Md-uwaKE3xWKbvvJnXg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4e0e95eb6da092b0fdec40afc7090afe161d86e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt#L26)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Since this doesn't seem to be a huge issue. I am merging this PR in the spirit of moving fast and leaving this as is.
</blockquote></details>

Done.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt, line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/121#-Md-CT5W7T6YUIygfxG3:-Md-v-9Y6nC0grXAjoUv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f08a28c6543d1b1538df61cea8e229ce2beda7a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt#L47)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Thanks for catching. Added them.
</blockquote></details>

Done.

**Pull request merged**
