### PR TITLE
Update duchy and kingdom cue files to match the v2alpa design.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/k8s/duchy_rpc_config.textproto, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142#-Me2KjGyB4Owh4Nk7rEq:-Me2KjGyB4Owh4Nk7rEr:burtvfd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45fbdb1b66cc3f2b7734c8e244d5edee39d2ebc9/src/main/k8s/duchy_rpc_config.textproto#L5)):*
> ```
> "$(AGGREGATOR_COMPUTATION_CONTROL_SERVER_SERVICE_HOST):$(AGGREGATOR_COMPUTATION_CONTROL_SERVER_SERVICE_PORT)
> ```

does $(XXX) work here in the proto string field?

It works inside the cue file, not sure it works here

**Comment by wangyaopw** [comment]
The kingdom internal servers are not added yet.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/k8s/duchy_rpc_config.textproto, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142#-Me2KjGyB4Owh4Nk7rEq:-Me5tqKY5LWGYl8YmORL:bhqnrrl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45fbdb1b66cc3f2b7734c8e244d5edee39d2ebc9/src/main/k8s/duchy_rpc_config.textproto#L5)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> "$(AGGREGATOR_COMPUTATION_CONTROL_SERVER_SERVICE_HOST):$(AGGREGATOR_COMPUTATION_CONTROL_SERVER_SERVICE_PORT)
> ```

does $(XXX) work here in the proto string field?

It works inside the cue file, not sure it works here
</blockquote></details>

This will be put into the cue file as a triple-quoted string literal. It looks like interpolation should still work on the cue side. See https://cuelang.org/docs/tutorials/tour/types/stringlit/

**Review by oliver-amzn — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142)* status: all files reviewed, 3 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/k8s/duchy.cue, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142#-Me6vFq_-7f9_PyT6yp2:-Me6vFqb0t7ds4Xv8KNF:bfc9il1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6ede457582ff0a98f68e0dfbda6fa1723b38343/src/main/k8s/duchy.cue#L38)):*
> ```CUE
> 	_duchy_image_pull_policy: string
> 
> 	_duchy_id_flags: [ for d in _duchy_names {"--duchy-ids=duchy-\(d)"}]
> ```

I removed `--duchy-ids` in PR #106 so I think there's a lot more here that can go.

`_duchy_names`, `duchy_ids`, maybe more? 
___
*[src/main/k8s/duchy_rpc_config.textproto, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142#-Me2KjGyB4Owh4Nk7rEq:-Me6qoTF6XnBoN8qRdir:bnnki8p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45fbdb1b66cc3f2b7734c8e244d5edee39d2ebc9/src/main/k8s/duchy_rpc_config.textproto#L5)):*
> ```
> WORKER_2_COMPUTATION_CONTROL_SERVER_SERVICE_HOST
> ```
Out of interest, where / how is this substituted later? 
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt, line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142#-Me6pZD40VgETI0sGJ3E:-Me6pZD40VgETI0sGJ3F:b-xf2i3a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6ede457582ff0a98f68e0dfbda6fa1723b38343/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt#L42)):*
> ```Kotlin
>   protected fun run(storageClient: StorageClient) {
>     val duchyName = flags.duchy.duchyName
>     val otherDuchyNames = flags.computationControlServiceTargets.keys.minus(duchyName).toList()
> ```

Thanks for cleaning this up, I think this was related to one of my PRs.

It looks like you removed all references to `computationControlServiceTargets` - want to remove it from LiquidLegionsV2MillFlags.kt?  

(you removed the one reference to `--computation-control-service-target` from the cue file)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142)* status: 4 of 21 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/k8s/duchy.cue, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142#-Me6vFq_-7f9_PyT6yp2:-Me732Hg-ELalBuohF1H:b-iry7x8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6ede457582ff0a98f68e0dfbda6fa1723b38343/src/main/k8s/duchy.cue#L38)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

I removed `--duchy-ids` in PR #106 so I think there's a lot more here that can go.

`_duchy_names`, `duchy_ids`, maybe more? 
</blockquote></details>

Done, thanks
___
*[src/main/k8s/duchy_rpc_config.textproto, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142#-Me2KjGyB4Owh4Nk7rEq:-Me73ASF9BXNeX9CYDYG:btfb241) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45fbdb1b66cc3f2b7734c8e244d5edee39d2ebc9/src/main/k8s/duchy_rpc_config.textproto#L5)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> ```
> WORKER_2_COMPUTATION_CONTROL_SERVER_SERVICE_HOST
> ```
Out of interest, where / how is this substituted later? 
</blockquote></details>

I think this only works in current version, in which we define all pods in the same cue file. so the compiler knows the address of all pods.

Eventually each duchy will have its own cue file, and we need to set the target using the actual address.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt, line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142#-Me6pZD40VgETI0sGJ3E:-Me73gUoBUjWO-BAO6YZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6ede457582ff0a98f68e0dfbda6fa1723b38343/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt#L42)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Thanks for cleaning this up, I think this was related to one of my PRs.

It looks like you removed all references to `computationControlServiceTargets` - want to remove it from LiquidLegionsV2MillFlags.kt?  

(you removed the one reference to `--computation-control-service-target` from the cue file)
</blockquote></details>

Done.

**Review by oliver-amzn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142)* status: 4 of 21 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/k8s/duchy_rpc_config.textproto, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/142#-Me2KjGyB4Owh4Nk7rEq:-MeAqbBYATgjbiosOrA_:bb7p5eq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45fbdb1b66cc3f2b7734c8e244d5edee39d2ebc9/src/main/k8s/duchy_rpc_config.textproto#L5)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I think this only works in current version, in which we define all pods in the same cue file. so the compiler knows the address of all pods.

Eventually each duchy will have its own cue file, and we need to set the target using the actual address.
</blockquote></details>

thx!

**Pull request merged**
