### PR TITLE
Implement Internal Report Schedule Iterations Service

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1297)

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 6 of 15 files at r1, 1 of 1 files at r2, 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1297)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetReportScheduleIterationState.kt` line 38 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1297#-NhUo47ZEnKu2MH46UcH:-NhUo47ZEnKu2MH46UcI:b-2fiu4w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dbd34d855aab0299bfe9640ebe92fd71e3f9de02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetReportScheduleIterationState.kt#L38)):*
> ```Kotlin
>  * * ReportScheduleIterationStateInvalidException] ReportScheduleIteration state invalid.
>  */
> class SetReportScheduleIterationState(private val request: SetReportScheduleIterationStateRequest) :
> ```

What are the state this function switched to? Does it allow any state in the request?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetReportScheduleIterationState.kt` line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1297#-NhUnVyT924Fu1AO-Xv4:-NhUnVyT924Fu1AO-Xv5:b-f252gx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dbd34d855aab0299bfe9640ebe92fd71e3f9de02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetReportScheduleIterationState.kt#L54)):*
> ```Kotlin
>         ))
> 
>     if (result.reportScheduleIteration.state == ReportScheduleIteration.State.REPORT_CREATED) {
> ```

Is it because `REPORT_CREATED` is terminal state? If so, could you add a comment above to note that?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetReportScheduleIterationState.kt` line 73 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1297#-NhUoNIH1lSUjPYPm9Ez:-NhUoNIH1lSUjPYPm9F-:b-kze01g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dbd34d855aab0299bfe9640ebe92fd71e3f9de02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetReportScheduleIterationState.kt#L73)):*
> ```Kotlin
>       ) {
>         bind("$1", request.state)
>         bind("$2", result.reportScheduleIteration.numAttempts + 1)
> ```

What is the logic behind this? Does any state change increment the number of attempts?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1297)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetReportScheduleIterationState.kt` line 38 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1297#-NhUo47ZEnKu2MH46UcH:-NhYuIiUC1kSSUF9SHvU:bhnlkkl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d0d52b24b3852261863fed080978b0bb391a9966/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetReportScheduleIterationState.kt#L38)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

What are the state this function switched to? Does it allow any state in the request?
</blockquote></details>

This allows any state, but the scheduling job won't call this for the initial state.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetReportScheduleIterationState.kt` line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1297#-NhUnVyT924Fu1AO-Xv4:-NhYs26C51oCsefTXxhJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d0d52b24b3852261863fed080978b0bb391a9966/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetReportScheduleIterationState.kt#L54)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Is it because `REPORT_CREATED` is terminal state? If so, could you add a comment above to note that?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetReportScheduleIterationState.kt` line 73 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1297#-NhUoNIH1lSUjPYPm9Ez:-NhYtyaz3bGqUlqw_Mro:bfa780b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d0d52b24b3852261863fed080978b0bb391a9966/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetReportScheduleIterationState.kt#L73)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

What is the logic behind this? Does any state change increment the number of attempts?
</blockquote></details>

State changes will increment the number of attempts, although the scheduling job won't call this for the initial state.

**Review by riemanli — APPROVED** [review]
> Reviewed 1 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1297)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 5 of 15 files at r1, 1 of 1 files at r2, 6 of 8 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1297)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
