### PR TITLE
Add ErrorInfo for Kingdom's Internal Usage

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464)

https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/247

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @renjiezh and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9Gxo5Q-0cbV3u8Qh:-MxL9Gxo5Q-0cbV3u8Qi:bkwzfan) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L28)):*
> ```Kotlin
>   code: ErrorDetail.ErrorCode,
>   domain: String,
>   extraInfo: Map<String, String> = emptyMap(),
> ```

The error domain should be hard-coded to the fully-qualified name of the ErrorCode enum.



_Code quote:_
```Kotlin
  domain: String,
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9VkR2uMgjEBz-2RH:-MxL9VkR2uMgjEBz-2RI:b-32os0c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L30)):*
> ```Kotlin
>   extraInfo: Map<String, String> = emptyMap(),
>   provideDescription: () -> String,
> ): Nothing {
> ```

What is this for? Shouldn't this have no return value?



_Code quote:_
```Kotlin
Nothing
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9c0X1rTbysNJ-dNL:-MxL9c0X1rTbysNJ-dNM:b50jtxm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L33)):*
> ```Kotlin
> 
>   val info =
>     ErrorInfo.newBuilder()
> ```

Use Kotlin proto DSL builder syntax.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9jNHE2oGWAYGXlol:-MxL9jNHE2oGWAYGXlom:bs5wk2d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L41)):*
> ```Kotlin
>       .build()
>   val detail =
>     ErrorDetail.newBuilder()
> ```

This looks like it's using our own ErrorDetail message, when we should be using https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto from googleapis.



_Code quote:_
```Kotlin
ErrorDetail
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9Gxo5Q-0cbV3u8Qh:-MxLUjPo2TPypkEz_C0V:b-kv03t1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The error domain should be hard-coded to the fully-qualified name of the ErrorCode enum.
</blockquote></details>

Done.
Coded as `ErrorDetail::class.qualifiedName.toString()`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9VkR2uMgjEBz-2RH:-MxLUqfdElVA10lJndem:bg1ok02) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What is this for? Shouldn't this have no return value?
</blockquote></details>

`failGrpcWithDetail()` throws the exception which is consistent with `failGrpc()`. Do you suggest other way?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9c0X1rTbysNJ-dNL:-MxLV76m-ActpepJQvj4:bqgcix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Kotlin proto DSL builder syntax.
</blockquote></details>

Done.
Good to know that. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9jNHE2oGWAYGXlol:-MxLVA1v1UepwdS_yk6G:blwl49o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This looks like it's using our own ErrorDetail message, when we should be using https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto from googleapis.
</blockquote></details>

Our `ErrorDetail` message  wrapped `ErrorInfo` (from google/rpc/error_details.proto). 
The reason I did not use `ErrorInfo` directly is that , the `reason` field in `ErrorInfo` is just a string. So I encapsulated as 
``` 
# src/main/proto/wfa/measurement/internal/kingdom/error_detail.proto
message ErrorDetail {
  ErrorCode code = 1;
  google.rpc.ErrorInfo info = 2;
}
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9Gxo5Q-0cbV3u8Qh:-Mx_U7co90rj0ImiusdO:b-bjdp87) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L28)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
Coded as `ErrorDetail::class.qualifiedName.toString()`
</blockquote></details>

Should be the qualified name `ErrorCode`, not the enclosing message.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9VkR2uMgjEBz-2RH:-Mx_UDQx0xYXOBpfglRs:b-2ommwk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L30)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

`failGrpcWithDetail()` throws the exception which is consistent with `failGrpc()`. Do you suggest other way?
</blockquote></details>

Throwing the exception is correct. I'm trying to figure out why this has any return type specified.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9jNHE2oGWAYGXlol:-Mx_UQOI20CBORcLD23P:b-vp8zha) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L41)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Our `ErrorDetail` message  wrapped `ErrorInfo` (from google/rpc/error_details.proto). 
The reason I did not use `ErrorInfo` directly is that , the `reason` field in `ErrorInfo` is just a string. So I encapsulated as 
``` 
# src/main/proto/wfa/measurement/internal/kingdom/error_detail.proto
message ErrorDetail {
  ErrorCode code = 1;
  google.rpc.ErrorInfo info = 2;
}
```
</blockquote></details>

Having it be just a string is fine. Don't encapsulate the message. We're just going to document for our errors that if you see an error with the domain set to the qualified name of our ErrorCode, then it means the error is the string name of the value in that enum.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9Gxo5Q-0cbV3u8Qh:-Mx_zZOL9EXDeRzrue5F:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Should be the qualified name `ErrorCode`, not the enclosing message.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9VkR2uMgjEBz-2RH:-Mx_nVJJC6PVLQco3Vz2:b2sfkgf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Throwing the exception is correct. I'm trying to figure out why this has any return type specified.
</blockquote></details>

I was following:
[Nothing type](https://kotlinlang.org/docs/exceptions.html#the-nothing-type) and [failGrpc()](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/grpc/Preconditions.kt#L51)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9jNHE2oGWAYGXlol:-Mx_zaGG8N6qhbzv09YB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Having it be just a string is fine. Don't encapsulate the message. We're just going to document for our errors that if you see an error with the domain set to the qualified name of our ErrorCode, then it means the error is the string name of the value in that enum.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @renjiezh and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-Mxeq37E5oI23qbnc7uH:-Mxeq37E5oI23qbnc7uI:b-d05lez) (no related file):*
You might want to split this up into separate PRs: one for adding the new error code, one for updating KingdomInternalException, etc.

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 76 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-Mxeo0Tx6CNc-pIi2HDW:-Mxeo0Tx6CNc-pIi2HDX:b-6jyvjt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/36220a40f1d47393386f03ca2d1109303b447490/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L76)):*
> ```Kotlin
>       when (e.code) {
>         KingdomInternalException.Code.ACCOUNT_NOT_FOUND -> {
>           failGrpcWithInfo(
> ```

Rather than calling failGrpcWithInfo here, have something that converts KingdomInternalException to StatusRuntimeException and throws that.
___
*[src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, line 171 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxeohW43VigUz40_DoQ:-MxeohW43VigUz40_DoR:b-hyq38k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/36220a40f1d47393386f03ca2d1109303b447490/src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel#L171)):*
> ```Starlark
>     srcs = ["error_code.proto"],
>     deps = [
>         "@com_google_googleapis//google/rpc:error_details_proto",
> ```

Why would this depend on error details?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/464#-MxL9VkR2uMgjEBz-2RH:-Mxenxa06G_eOF8S7X2t:bkds65a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f311da68b3a0ba519aea4249a196228660e0f3ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ErrorDetail.kt#L30)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I was following:
[Nothing type](https://kotlinlang.org/docs/exceptions.html#the-nothing-type) and [failGrpc()](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/grpc/Preconditions.kt#L51)
</blockquote></details>

Ah, gotcha.

**Pull request closed without merging**
