### PR TITLE
Push Kingdom images in parallel with Duchy images

### PR DESCRIPTION
**Pull request by wfa-siyengar**
This also fixes the permissions on `export-image-tag.sh` to make it executable.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/926)

**Comment by SanjayVas** [comment]
Copied from initial comment by @wfa-siyengar:

image


image


image

**Review by SanjayVas — CHANGES_REQUESTED** [review]
I updated the PR description to be more accurate and follow https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/926#-:-NS7ykh6D2P7uRQa_7aM:bufrstt)* status: all files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl, @wfa-hkawalkar, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/926#-NS7zUoY5dHg9Yf1WmY_:-NS7zUoY5dHg9Yf1WmYa:b-or7wpx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4ce7cdeb157824bd4c8e83435294c43f8848e46/.github/workflows/create-cmm-images.yml#L34)):*
> ```YAML
>       - id: generate-tag
>         run: ./.github/workflows/export-image-tag.sh
>       - id: get-image-tag-step
> ```

nit: Steps don't need IDs unless you need to reference them. They should have names though, as that's what appears in the UI/logs.



_Suggestion:_
```YAML
name: Output image tag
```
___
*[`.github/workflows/create-cmm-images.yml` line 91 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/926#-NS8-5jk5ymtMS7QJGWz:-NS8-5jk5ymtMS7QJGX-:b-pr9x44) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4ce7cdeb157824bd4c8e83435294c43f8848e46/.github/workflows/create-cmm-images.yml#L91)):*
> ```YAML
>       - name: Build Duchy image
>         run: |
>           bazelisk query 'filter("push_duchy", kind("container_push", //src/main/docker:all))' |
> ```

I don't think this will actually parallelize the build, as you can only have one Bazel command running at a time for the same workspace. This command will likely just output a message that it's waiting for the other command to complete.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/926)* status: all files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl, @wfa-hkawalkar, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 91 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/926#-NS8-5jk5ymtMS7QJGWz:-NS8-cz-213Q6dy6-JWI:b-dz2plp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4ce7cdeb157824bd4c8e83435294c43f8848e46/.github/workflows/create-cmm-images.yml#L91)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this will actually parallelize the build, as you can only have one Bazel command running at a time for the same workspace. This command will likely just output a message that it's waiting for the other command to complete.
</blockquote></details>

Note that there's not much benefit to said parallelism either. The build step will efficiently utilize the available CPU.

**Review by wfa-siyengar — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/926#-:-NSEITDgDJmaDEp2piuy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl, @SanjayVas, @wfa-hkawalkar, and @wfa-mdharmalingam)

___
*[`.github/workflows/create-cmm-images.yml` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/926#-NS7zUoY5dHg9Yf1WmY_:-NSEKYT63-bigTNJY8eP:b-y0nlmg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/467bc9c17d14555fec9a5872279d5670f11ee687/.github/workflows/create-cmm-images.yml#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Steps don't need IDs unless you need to reference them. They should have names though, as that's what appears in the UI/logs.
</blockquote></details>

Corrected. I believed we may need both name and ID to be always written as part of best followed practices. 
___
*[`.github/workflows/create-cmm-images.yml` line 91 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/926#-NS8-5jk5ymtMS7QJGWz:-NSEKLxtANvvXVTqJBnh:b-6bevv2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/467bc9c17d14555fec9a5872279d5670f11ee687/.github/workflows/create-cmm-images.yml#L91)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that there's not much benefit to said parallelism either. The build step will efficiently utilize the available CPU.
</blockquote></details>

Noted. Hope there is no action needed from our end.

**Review by wfa-siyengar — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/926)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl, @SanjayVas, @wfa-hkawalkar, and @wfa-mdharmalingam)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/926)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl, @wfa-hkawalkar, and @wfa-mdharmalingam)

___
*[`.github/workflows/create-cmm-images.yml` line 91 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/926#-NS8-5jk5ymtMS7QJGWz:-NSHY35B1c0gz6vSAbqi:b-ctbxcr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/467bc9c17d14555fec9a5872279d5670f11ee687/.github/workflows/create-cmm-images.yml#L91)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Noted. Hope there is no action needed from our end.
</blockquote></details>

I was actually incorrect here. These are separate jobs not steps, so they can be totally parallelized. No action needed, feel free to merge.

**Comment by SanjayVas** [comment]
I just tried running this workflow and it doesn't work correctly. The image tag is generated fine, but it doesn't properly get read by the build-kingdom-image and build-duchy-image jobs. See https://github.com/world-federation-of-advertisers/cross-media-measurement/actions/runs/4623005553 (I cancelled the jobs early as they were running with an empty image tag).

**Pull request merged**
