### PR TITLE
Fix cronSchedule not being set when creating RecurringExchange.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/463)

### CODE REVIEW

**Comment by SanjayVas** [comment]
CC @yunyeng

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/463)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 227 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/463#-MxGB7Hk9Oln_TQdlHsq:-MxGB7Hk9Oln_TQdlHsr:bg0yj75) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfd010a0a6872f5f5e022ec1ec6b3e409630981/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L227)):*
> ```Kotlin
>           this.externalExchangeWorkflow = serializedExchangeWorkflow.toByteString()
>           exchangeWorkflow = v2AlphaExchangeWorkflow.toInternal()
>           cronSchedule = "@daily"
> ```

Can we make this as constant as CRON_SCHEDULE under API_VERSION ? So, it is easier to see.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/463)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 227 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/463#-MxGB7Hk9Oln_TQdlHsq:-MxGHItg5LybyvXvwvEU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfd010a0a6872f5f5e022ec1ec6b3e409630981/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L227)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Can we make this as constant as CRON_SCHEDULE under API_VERSION ? So, it is easier to see.
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/463)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @yunyeng from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/463)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/463)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
