### PR TITLE
test: Update confidence interval for integration tests.

### PR DESCRIPTION
**Pull request by ple13**
The current threshold (3.291 x sigma) guarantees that each noisy measurement is 99.9% within the confidence interval. However, the integration tests consist of at least 30 independent noisy values. This pushes the failure rate to (1-0.999^30 ~ 0.03), which is a bit high and causes the presubmit test to be flaky. Increasing this threshold to 5 x sigma will bring the failure rate down to below 0.0001.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1742)

**Review by jiayu-google — APPROVED** [review]
:lgtm: per offline discussion

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1742#-:-O3iZsum4LDjscznM7OU:bwfbmaf)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @renjiezh and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1742)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1742)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1742)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
