### PR TITLE
Plumb vid sampling intervals through the Duchy

### PR DESCRIPTION
**Pull request by matthewclegg**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/450)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/450)* status: all files reviewed, 4 unresolved discussions (waiting on @matthewclegg)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 576 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/450#-MwcxUbtDAIRoIc75rqW:-MwcxUbtDAIRoIc75rqX:b-vmh6k6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a44008356a5ca4481492d7f9899d7de18530d99e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L576)):*
> ```Kotlin
>     val (bytes, tempToken) =
>       existingOutputOr(token) {
>         val measurementSpec =
> ```

Guard this with a public API version check (see other examples in this file), since we're deserializing a message from a specific public API version here.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 272 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/450#-MwcyWk0904v76AdZTmK:-MwcyWk0904v76AdZTmL:bi4769w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a44008356a5ca4481492d7f9899d7de18530d99e/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L272)):*
> ```Kotlin
>           reachPrivacyParams = outputDpParams
>           frequencyPrivacyParams = outputDpParams
>           vidSamplingInterval = VidSamplingInterval.newBuilder().apply { width = 1.0f }.build()
> ```

nit: use Kotlin protobuf DSL builder rather than Java protobuf builder
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 320 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/450#-MwcyjHTBZNfU9KeRjZW:-MwcyjHTBZNfU9KeRjZX:b-k2lr75) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a44008356a5ca4481492d7f9899d7de18530d99e/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L320)):*
> ```Kotlin
>   nonceHashes += TEST_REQUISITION_3.nonceHash
>   reachAndFrequency =
>     ReachAndFrequency.newBuilder()
> ```

nit: Use Kotlin protobuf DSL builder
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 1627 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/450#-Mwcyny2AD-YR7-KhBBl:-Mwcyny2AD-YR7-KhBBm:bfsefhu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a44008356a5ca4481492d7f9899d7de18530d99e/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L1627)):*
> ```Kotlin
>     val computationDetailsWithVidSamplingWidth =
>       AGGREGATOR_COMPUTATION_DETAILS
>         .toBuilder()
> ```

nit: Use Kotlin protobuf DSL builder (i.e. `copy` rather than `toBuilder`)

**Review by matthewclegg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/450)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 576 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/450#-MwcxUbtDAIRoIc75rqW:-Mwix98O4sT6dZ8SUae9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a44008356a5ca4481492d7f9899d7de18530d99e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L576)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Guard this with a public API version check (see other examples in this file), since we're deserializing a message from a specific public API version here.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/450)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/450)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/450)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Pull request merged**
