### PR TITLE
Implement internal add and remove mc owner.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 130 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrYZ9s3Dv84q42p9urQ:-MrYZ9s4B6hXyVyl73aA:bbkz6os) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8eab169775eac800865b182a661ba1674d19494d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L130)):*
> ```Kotlin
>       measurementConsumersService.createMeasurementConsumer(MEASUREMENT_CONSUMER)
> 
>     assertThat(MEASUREMENT_CONSUMER)
> ```

This should be the actual value, not the expected.  i.e. it should be `assertThat(createdMeasurementConsumer)`. See https://truth.dev/faq#order



_Code quote:_
```Kotlin
assertThat(MEASUREMENT_CONSUMER)
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 285 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrYZmZ-BNaHn2JVvCaC:-MrYZmZ-BNaHn2JVvCaD:bt2449p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8eab169775eac800865b182a661ba1674d19494d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L285)):*
> ```Kotlin
> 
>   /**
>    * TODO(https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/404/):
> ```

Incorrect TODO format for GitHub Issue/PR. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format.

Also be a bit more clear under what condition to remove the `@Ignore`, e.g. 

```
Remove `@Ignore` once PR has been merged.
```



_Code quote:_
```Kotlin
https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/404/
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 229 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrY_Uun0onBNVGiBUCf:-MrY_Uun0onBNVGiBUCg:b6a3q70) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8eab169775eac800865b182a661ba1674d19494d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L229)):*
> ```Kotlin
>     externalCreatorAccountId: Long = 0L,
>     externalOwnedMeasurementConsumerId: Long = 0L
>   ): AccountInfo {
> ```

Any reason not to split this up into separate `createAccount` and `activateAccount` methods? It's more explicit and you don't need to return two different values.



_Code quote:_
```Kotlin
AccountInfo
```

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 229 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrY_Uun0onBNVGiBUCf:-MrYdY_ZCRmkj2t8kvSP:brng4a6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8eab169775eac800865b182a661ba1674d19494d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L229)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Any reason not to split this up into separate `createAccount` and `activateAccount` methods? It's more explicit and you don't need to return two different values.
</blockquote></details>

I have been doing it as one method for convenience purposes.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 229 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrY_Uun0onBNVGiBUCf:-MrYdo9d97bqVRkFpmf1:bityc76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8eab169775eac800865b182a661ba1674d19494d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L229)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I have been doing it as one method for convenience purposes.
</blockquote></details>

But I suppose calling 2 methods instead of one isn't that bad.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @ignore and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 130 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrYZ9s3Dv84q42p9urQ:-MrYgsVZEkdEZ2xaffrR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8eab169775eac800865b182a661ba1674d19494d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L130)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be the actual value, not the expected.  i.e. it should be `assertThat(createdMeasurementConsumer)`. See https://truth.dev/faq#order
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 285 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrYZmZ-BNaHn2JVvCaC:-MrYgrq6-8xPyIIHZNWp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8eab169775eac800865b182a661ba1674d19494d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L285)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Incorrect TODO format for GitHub Issue/PR. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format.

Also be a bit more clear under what condition to remove the `@Ignore`, e.g. 

```
Remove `@Ignore` once PR has been merged.
```
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409)* status: all files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 131 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrZH5A814i2hMn97XHG:-MrZH5A814i2hMn97XHH:bxnsau6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c5d2155e60673e12cedf48cc4751b195319d982/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L131)):*
> ```Kotlin
> 
>     assertThat(createdMeasurementConsumer)
>       .comparingExpectedFieldsOnly()
> ```

I don't think this is what we want here. `comparingExpectedFieldsOnly` is useful when you explicitly know that you don't care what the values that aren't specified in your expected message are. In this case, we do care if there are other fields set that we don't expect.

`ignoringFieldDescriptors` would be better in this case to ignore specific fields.



_Code quote:_
```Kotlin
  .comparingExpectedFieldsOnly()
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 141 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrZHtnI5fzPkW4l1mVp:-MrZHtnI5fzPkW4l1mVq:bzgz8py) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c5d2155e60673e12cedf48cc4751b195319d982/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L141)):*
> ```Kotlin
>             }
>         }
>       )
> ```

Add additional assertions for what we can know about the fields we're ignoring in the previous assertion. e.g. that `externalMeasurementConsumerId` is set, and that it matches the value in `certificate`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrZIHCA36zyZEp-OxZk:-MrZIHCBA4Bgz8XoBqP5:b-qzgxfn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c5d2155e60673e12cedf48cc4751b195319d982/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L149)):*
> ```Kotlin
>       measurementConsumersService.createMeasurementConsumer(MEASUREMENT_CONSUMER)
> 
>     val measurementConsumerRead =
> ```

nit: not from this PR, but rename to `readMeasurementConsumer` to parallel the naming of `createdMeasurementConsumer`.



_Code quote:_
```Kotlin
measurementConsumerRead
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 177 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrZIWV0DkkDszSzLI2L:-MrZIWV0DkkDszSzLI2M:b1xcgbb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c5d2155e60673e12cedf48cc4751b195319d982/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L177)):*
> ```Kotlin
> 
>     assertThat(exception.status.code).isEqualTo(Status.Code.NOT_FOUND)
>     assertThat(exception).hasMessageThat().contains("MeasurementConsumer not found")
> ```

I'm not a fan of checking exception messages in tests unless you really need to in order to differentiate.

Since this is a base test class, the tests here form a contract that all implementations must follow. Ideally you want to allow maximum flexibility for error messages, so if you're checking the exception message then only check the substring(s) that the message *must* contain.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 236 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrZKllZARQZAj69Cr_J:-MrZKllZARQZAj69Cr_K:bpxsjfa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c5d2155e60673e12cedf48cc4751b195319d982/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L236)):*
> ```Kotlin
>   }
> 
>   /** Activates the [Account] and returns the id token used to activate it. */
> ```

nit: maybe be clearer that this generates a self-issued ID token, and that's what it's returning.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 131 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrZH5A814i2hMn97XHG:-MrZUG3bDQraD6YBo4NQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c5d2155e60673e12cedf48cc4751b195319d982/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L131)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this is what we want here. `comparingExpectedFieldsOnly` is useful when you explicitly know that you don't care what the values that aren't specified in your expected message are. In this case, we do care if there are other fields set that we don't expect.

`ignoringFieldDescriptors` would be better in this case to ignore specific fields.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 141 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrZHtnI5fzPkW4l1mVp:-MrZUGWI87KAO24LzcGB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c5d2155e60673e12cedf48cc4751b195319d982/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add additional assertions for what we can know about the fields we're ignoring in the previous assertion. e.g. that `externalMeasurementConsumerId` is set, and that it matches the value in `certificate`.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 270 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/409#-MrcgWzTBi-ACvZiwS8k:-MrcgWzU7eKMpK19jtET:b-tbwsw5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b83310e17e583954ac36985c221bffbf7a11341/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L270)):*
> ```Kotlin
>   ): String {
>     val uriParts = mutableListOf<String>()
>     uriParts.add("openid://?response_type=id_token")
> ```

see my other comments about a single uri builder

**Pull request merged**
