### PR TITLE
Add a job cue template.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/k8s/base.cue, line 142 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279#-MjjQ-7nDlIZQP60JKA2:-MjjQ-7nDlIZQP60JKA3:bg1bput) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f3759f3f8b8a0ab4f5600023e77728184fc6794/src/main/k8s/base.cue#L142)):*
> ```
> _image:           string | *""
> ```

Not sure what is going on here
`_image:           string` doesn't work, and I have to add the default here.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol and @wangyaopw)

___
*[src/main/k8s/base.cue, line 142 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279#-MjjQ-7nDlIZQP60JKA2:-MjjVcAh3yLjfJp9l9R3:b-cgaw2e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f3759f3f8b8a0ab4f5600023e77728184fc6794/src/main/k8s/base.cue#L142)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> _image:           string | *""
> ```

Not sure what is going on here
`_image:           string` doesn't work, and I have to add the default here.



</blockquote></details>

Is there something that uses this that doesn't override `_image`?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @uakyol)

___
*[src/main/k8s/base.cue, line 142 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279#-MjjQ-7nDlIZQP60JKA2:-MjjbZ888Vd0k3F233Ov:bffreox) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f3759f3f8b8a0ab4f5600023e77728184fc6794/src/main/k8s/base.cue#L142)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is there something that uses this that doesn't override `_image`?
</blockquote></details>

only the two files in this PR use this. They both override `_image`.

If I override by ` _image: "the string"` then it works. But if it is `_image: _another_variable`, it fails.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @uakyol, and @wangyaopw)

___
*[src/main/k8s/base.cue, line 142 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279#-MjjQ-7nDlIZQP60JKA2:-MjjhfPj8goXlyQzui4v:bwjhahj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f3759f3f8b8a0ab4f5600023e77728184fc6794/src/main/k8s/base.cue#L142)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

only the two files in this PR use this. They both override `_image`.

If I override by ` _image: "the string"` then it works. But if it is `_image: _another_variable`, it fails.
</blockquote></details>

Can it prove that `_another_variable` is a string?
Do you have a minimal example? Something like:

```
#Foo: {
  _a: string
}

#Bar: #Foo & {
  _a: _b
  _b: string
}
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, and @uakyol)

___
*[src/main/k8s/base.cue, line 142 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279#-MjjQ-7nDlIZQP60JKA2:-MjjkNh423f1fdwbs3aQ:b-g11ch5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f3759f3f8b8a0ab4f5600023e77728184fc6794/src/main/k8s/base.cue#L142)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can it prove that `_another_variable` is a string?
Do you have a minimal example? Something like:

```
#Foo: {
  _a: string
}

#Bar: #Foo & {
  _a: _b
  _b: string
}
```
</blockquote></details>

well, I think this PR is an example already.

If I delete `| *""` here in the template. The build fails. `_image` in `resource_setup.cue ` is overridden using `_job_image` which is a string

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @uakyol, and @wangyaopw)

___
*[src/main/k8s/base.cue, line 142 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279#-MjjQ-7nDlIZQP60JKA2:-MjjmZKD1hxC4dcjUeY1:bgff15z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f3759f3f8b8a0ab4f5600023e77728184fc6794/src/main/k8s/base.cue#L142)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

well, I think this PR is an example already.

If I delete `| *""` here in the template. The build fails. `_image` in `resource_setup.cue ` is overridden using `_job_image` which is a string
</blockquote></details>

Very weird, no idea!

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol and @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Pull request merged**
