### PR TITLE
Add support for chaining multiple authentication interceptors.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 32 files at r1, 10 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422)* status: 18 of 34 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, line 60 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MtxvieV0Jv70VEcxF3j:-MtxvieWBqxsTaTTCJRY:b-mrq337) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b51f2b233f61a06b650fa22068b67a722b486209/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt#L60)):*
> ```Kotlin
>     if (idToken == null) {
>       if (call.methodDescriptor.fullMethodName ==
>           "wfa.measurement.api.v2alpha.Accounts/ActivateAccount"
> ```

We shouldn't have hard-coded method-specific checks in the interceptor. Each method that needs to should be able to determine its own auth requirements from the context. Either that or we should have some declarative way to tell the interceptor to do some alternative behavior that lives closer to the method itself, e.g. an annotation.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MtxwaQ56LTpqIQgTuV2:-MtxwaQ56LTpqIQgTuV3:bkkk7db) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b51f2b233f61a06b650fa22068b67a722b486209/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt#L76)):*
> ```Kotlin
>       val deferredListener = DeferredListener<ReqT>()
> 
>       CoroutineScope(Dispatchers.Default).launch {
> ```

Use Dispatchers.IO for RPCs.



_Code quote:_
```Kotlin
Dispatchers.Default
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422)* status: 17 of 34 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, line 60 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MtxvieV0Jv70VEcxF3j:-Mty6eCAEYsEfa0xXFOX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b51f2b233f61a06b650fa22068b67a722b486209/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We shouldn't have hard-coded method-specific checks in the interceptor. Each method that needs to should be able to determine its own auth requirements from the context. Either that or we should have some declarative way to tell the interceptor to do some alternative behavior that lives closer to the method itself, e.g. an annotation.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MtxwaQ56LTpqIQgTuV2:-Mty6g5I0wQTXkN0-CGB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b51f2b233f61a06b650fa22068b67a722b486209/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Dispatchers.IO for RPCs.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 32 files at r1, 7 of 18 files at r2, 1 of 1 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422)* status: 33 of 34 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MtxwaQ56LTpqIQgTuV2:-Mtyy498C8Qja3-qUIqz:bx65zcf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b51f2b233f61a06b650fa22068b67a722b486209/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt#L76)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Couldn't you just use Dispatchers.IO for the outer `CoroutineScope` and not use a separate `withContext`? Once inside `launch`, can't you just call any suspending function without wrapping it?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 71 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MtyzrNF03yuSfBVC4hL:-MtyzrNF03yuSfBVC4hM:b-mesgpu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97ae810ba04eda55b6f14e87c2181e36653aac49/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L71)):*
> ```Kotlin
>     val measurementConsumerKey =
>       if (principal.resourceKey is MeasurementConsumerKey) {
>         principal.resourceKey as MeasurementConsumerKey
> ```

Doesn't smart cast take care of this so you can just have principal.resourceKey here?

Alternatively, maybe use the safe cast (`as?`) operator:

```
val authenticatedMeasurementConsumerKey = principal.resourceKey as? MeasurementConsumerKey ?: failGrpc...
```

Same with other instances below.



_Code quote:_
```Kotlin
principal.resourceKey as MeasurementConsumerKey
```

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MtxwaQ56LTpqIQgTuV2:-Mtz4w88EiVCsFKQyYJf:b-rwlelu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b51f2b233f61a06b650fa22068b67a722b486209/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Couldn't you just use Dispatchers.IO for the outer `CoroutineScope` and not use a separate `withContext`? Once inside `launch`, can't you just call any suspending function without wrapping it?
</blockquote></details>

Done. Looked it up and turns out doing withContext(Dispatchers.IO) inside CoroutineScope(Dispatchers.Default) doesn't do anything anyways.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 71 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MtyzrNF03yuSfBVC4hL:-Mtz5C2b4vH1Fml5CesD:bpbba2s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97ae810ba04eda55b6f14e87c2181e36653aac49/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Doesn't smart cast take care of this so you can just have principal.resourceKey here?

Alternatively, maybe use the safe cast (`as?`) operator:

```
val authenticatedMeasurementConsumerKey = principal.resourceKey as? MeasurementConsumerKey ?: failGrpc...
```

Same with other instances below.
</blockquote></details>

Done. Smart cast only works within the scope of the check. Switched to the safe cast operator.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 9 of 32 files at r1, 12 of 18 files at r2, 1 of 1 files at r3, 1 of 4 files at r4, 3 of 3 files at r5, 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, line 77 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MuCuZZc6hH7rODO7Wjz:-MuCuZZd5pzyPAxh-BQu:b-ql2jga) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/16a90e62f385107ed61acb747712b9bd4defea9a/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt#L77)):*
> ```Kotlin
>         } catch (e: Exception) {
>           when (e) {
>             is StatusRuntimeException, is StatusException -> {}
> ```

can you explain a little whats going on with these exceptions and why you map it this way?
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt, line 235 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MuCvG1h17URgHNf50MF:-MuCvG1h17URgHNf50MG:b-2l3cip) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/16a90e62f385107ed61acb747712b9bd4defea9a/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt#L235)):*
> ```Kotlin
>       )
>       .isEqualTo(
>         org.wfanet.measurement.internal.kingdom.getMeasurementConsumerRequest {
> ```

nit: import this
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt, line 265 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MuCvB3SAkrNMI10C5Zz:-MuCvB3SAkrNMI10C5_-:b-2l3cip) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/16a90e62f385107ed61acb747712b9bd4defea9a/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt#L265)):*
> ```Kotlin
>       )
>       .isEqualTo(
>         org.wfanet.measurement.internal.kingdom.getMeasurementConsumerRequest {
> ```

nit: import this

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, line 77 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MuCuZZc6hH7rODO7Wjz:-MuCvew96EcN1mWusKTM:b-otj3ke) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46bbba0fe8dd1f05f951b920cd9ce39ae79e34b5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt#L77)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you explain a little whats going on with these exceptions and why you map it this way?
</blockquote></details>

I should add some comments here, but the reason is that there is a situation where there is an id token in the metadata, but I don't want to check if it belongs to an existing account.  So if the authentication fails, then I don't want to close the call in case it is that situation.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422)* status: 32 of 34 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, line 77 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MuCuZZc6hH7rODO7Wjz:-MuD3B-x-u1D_dHveR0F:b-we80hu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46bbba0fe8dd1f05f951b920cd9ce39ae79e34b5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt#L77)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I should add some comments here, but the reason is that there is a situation where there is an id token in the metadata, but I don't want to check if it belongs to an existing account.  So if the authentication fails, then I don't want to close the call in case it is that situation.
</blockquote></details>

But only if it was a failure with a gRPC code. I still wanted to close it if it was not an exception that caught and replaced with a gRPC exception. Maybe it is better to not close the call in any situation and just add logging when we have our logging setup.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422)* status: 32 of 34 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, line 77 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422#-MuCuZZc6hH7rODO7Wjz:-MuD66gC6DA4QANNq1tt:b2nid0f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46bbba0fe8dd1f05f951b920cd9ce39ae79e34b5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt#L77)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

But only if it was a failure with a gRPC code. I still wanted to close it if it was not an exception that caught and replaced with a gRPC exception. Maybe it is better to not close the call in any situation and just add logging when we have our logging setup.
</blockquote></details>

thx

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/422)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
