### PR TITLE
Add doc to instruct enabling reach-only llv2.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`docs/operations/enabling-reach-only-llv2.md` line 6 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRpzNF4bQrXHJf1FI2:-NfRpzNF4bQrXHJf1FI3:br40r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b50b2fed15eee874af9578aef052d9e77c8dfc/docs/operations/enabling-reach-only-llv2.md#L6)):*
> ```Markdown
> Duchies, and EDPs need to deploy these operations.
> 
> # Steps
> ```

nit: Generally we only use `#` for the page title. Everything else should be at `##` or below.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`docs/operations/enabling-reach-only-llv2.md` line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRUWXsDb1L0r90q05v:-NfRUWXsDb1L0r90q05w:b-lywt1l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b50b2fed15eee874af9578aef052d9e77c8dfc/docs/operations/enabling-reach-only-llv2.md#L13)):*
> ```Markdown
> sketches according to the protocol.
> 
> **Note: if an EDP ignores the protocol thus fulfills reach-only llv2 protocol
> ```

Something we could consider adding as part of the secret sharing design is for the EDP to send a hash of the sketch config that was used. Not sure it's worth it, but it could definitely catch some serious and subtle errors.
___
*[`docs/operations/enabling-reach-only-llv2.md` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRVGo2Bkf9Jlb-XVBP:-NfRVGo2Bkf9Jlb-XVBQ:bdshknu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b50b2fed15eee874af9578aef052d9e77c8dfc/docs/operations/enabling-reach-only-llv2.md#L32)):*
> ```Markdown
> register, but llv2 sketches have two extra fields for each register.
> 
> The change can be easily done by using an updated `SketchConfig`. Deleting the
> ```

Maybe just. point to the sketch config to use in this case and some code that switches between the old version and the new version?
___
*[`docs/operations/enabling-reach-only-llv2.md` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRVT8pBdS3INYTIMI5:-NfRVT8qCR-c96bCL6PA:bk87j1i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b50b2fed15eee874af9578aef052d9e77c8dfc/docs/operations/enabling-reach-only-llv2.md#L40)):*
> ```Markdown
> automatically ignore duplicate insertion.
> 
> Note that, an `index` in the ReachOnlyLiquidLegionsV2 sketch should guarantee
> ```

I know what you're saying here, but if no VID is inserted then the register will be unpopulated. I'm not sure we have to include this paragraph.
___
*[`docs/operations/enabling-reach-only-llv2.md` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRVcKI0aqVVCx-ewoc:-NfRVcKI0aqVVCx-ewod:brpo8q3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b50b2fed15eee874af9578aef052d9e77c8dfc/docs/operations/enabling-reach-only-llv2.md#L51)):*
> ```Markdown
> ## Kingdom Flips the Feature Flag
> 
> Kingdom updates the binary image to support the reach-only llv2 protocol. Add
> ```

Can you point to where this flag is defined and set in GitHub?
___
*[`docs/operations/enabling-reach-only-llv2.md` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRVkNz0Vql8E3ZeRbP:-NfRVkNz0Vql8E3ZeRbQ:bsho0cn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b50b2fed15eee874af9578aef052d9e77c8dfc/docs/operations/enabling-reach-only-llv2.md#L55)):*
> ```Markdown
> Restarting the kingdom will apply the new protocol for new Reach measurements.
> 
> ## Duchies Update Deployment
> ```

This should be the first or second step.
___
*[`docs/operations/enabling-reach-only-llv2.md` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRr6_EEwmjs3EctVpZ:-NfRr6_EEwmjs3EctVp_:b5ykbim) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce0fe7931ced428af8d314173647ef18a7419fd4/docs/operations/enabling-reach-only-llv2.md#L1)):*
> ```Markdown
> # Enabling Reach-Only LiquidLegionsV2 Protocol
> ```

Can you note the first release in which this feature is available?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`docs/operations/enabling-reach-only-llv2.md` line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRUWXsDb1L0r90q05v:-NfRsN3G1YldxaguTcbA:b-if7hyn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b50b2fed15eee874af9578aef052d9e77c8dfc/docs/operations/enabling-reach-only-llv2.md#L13)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Something we could consider adding as part of the secret sharing design is for the EDP to send a hash of the sketch config that was used. Not sure it's worth it, but it could definitely catch some serious and subtle errors.
</blockquote></details>

It is good to have sketch validation! As sketch config is a proto object, the serialization of it is not deterministic given two exactly same objects. But anyway, it is a great direction. Thanks for sharing.
___
*[`docs/operations/enabling-reach-only-llv2.md` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRVGo2Bkf9Jlb-XVBP:-NfRx5Mz3MnZnLZ2qTZ_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b50b2fed15eee874af9578aef052d9e77c8dfc/docs/operations/enabling-reach-only-llv2.md#L32)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Maybe just. point to the sketch config to use in this case and some code that switches between the old version and the new version?
</blockquote></details>

Done.
___
*[`docs/operations/enabling-reach-only-llv2.md` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRVT8pBdS3INYTIMI5:-NfRv8aj2DAuXxYIIFWh:b-f9lrj6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b50b2fed15eee874af9578aef052d9e77c8dfc/docs/operations/enabling-reach-only-llv2.md#L40)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I know what you're saying here, but if no VID is inserted then the register will be unpopulated. I'm not sure we have to include this paragraph.
</blockquote></details>

I see. Deleted.
___
*[`docs/operations/enabling-reach-only-llv2.md` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRVcKI0aqVVCx-ewoc:-NfRx8X4DgWPMdzFoIKm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b50b2fed15eee874af9578aef052d9e77c8dfc/docs/operations/enabling-reach-only-llv2.md#L51)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you point to where this flag is defined and set in GitHub?
</blockquote></details>

Done.
___
*[`docs/operations/enabling-reach-only-llv2.md` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRVkNz0Vql8E3ZeRbP:-NfRx9TM4WWen9QQEzTO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b50b2fed15eee874af9578aef052d9e77c8dfc/docs/operations/enabling-reach-only-llv2.md#L55)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This should be the first or second step.
</blockquote></details>

Done.
___
*[`docs/operations/enabling-reach-only-llv2.md` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfRr6_EEwmjs3EctVpZ:-NfRwxY6BnMsLYf1EnR7:bs7wumx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce0fe7931ced428af8d314173647ef18a7419fd4/docs/operations/enabling-reach-only-llv2.md#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you note the first release in which this feature is available?
</blockquote></details>

Done.

**Review by ple13 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`docs/operations/enabling-reach-only-llv2.md` line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfScBSK2I5rpl-Ew9N3:-NfScBSK2I5rpl-Ew9N4:b-ntvz5p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27f51357fa15a91480f642a2e146513cc7d9e43d/docs/operations/enabling-reach-only-llv2.md#L39)):*
> ```Markdown
> SketchConfig, the extra fields of LiquidLegionsV2’s sketch will be ignored.
> However, it is welcomed to update the code to reduce unnecessary processing.
> The `index` is set as `UNIQUE`, it will automatically ignore duplicate
> ```

If the 'index' ...

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @ple13)

___
*[`docs/operations/enabling-reach-only-llv2.md` line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261#-NfScBSK2I5rpl-Ew9N3:-NfTEnueAbl6d_QIC9Su:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27f51357fa15a91480f642a2e146513cc7d9e43d/docs/operations/enabling-reach-only-llv2.md#L39)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

If the 'index' ...
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @Marco-Premier)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @Marco-Premier)

**Review by renjiezh — COMMENTED** [review]
> Dismissed @kungfucraig from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1261)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
