### PR TITLE
Update WORKSPACE with common_jvm

### PR DESCRIPTION
**Pull request by enfreck**
Update WORKSPACE to be more dependent on common_jvm.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @enfreck)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184#-MgRWkhH5g8WHCx2UYWK:-MgRWkhH5g8WHCx2UYWL:b1vyb64) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49960f7712c1c822ec356f7dd7286ad3e938c71/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L42)):*
> ```Kotlin
>       ClaimReadyExchangeStep(
>           externalModelProviderId =
>             if (request.externalModelProviderId > 0) request.externalModelProviderId else null,
> ```

why this change? is this recommended by the compiler?

I personally prefer hasXXX().

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184#-MgRWkhH5g8WHCx2UYWK:-MgRa0sb7J9dRtrHW-eV:bch8xdz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49960f7712c1c822ec356f7dd7286ad3e938c71/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L42)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

why this change? is this recommended by the compiler?

I personally prefer hasXXX().
</blockquote></details>

It seems like the proto compiler has removed the `hasX()` methods for scalars upon moving to `common-jvm` apparently. It doesn't matter anyway as file should be reverted once this PR is rebased to main (since Yunus just updated this file)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck and @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184#-MgRaJ789POD-AAj9T8y:-MgRaJ789POD-AAj9T8z:b5iqcji) (no related file):*
Please `git pull`

---

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck and @wangyaopw)

___
*[WORKSPACE, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184#-MgRa-YREKhcf1dSGQF_:-MgRa-YREKhcf1dSGQFa:b-red6ar) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49960f7712c1c822ec356f7dd7286ad3e938c71/WORKSPACE#L33)):*
> ```
> common_cpp_repositories
> ```
Does this mean that all repos polling from common_cpp will load all the common_cpp_repositories even if a subset of them are needed?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @enfreck)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184#-MgRWkhH5g8WHCx2UYWK:-MgRa_1R7DN1vADIlZJV:b-4tld5n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49960f7712c1c822ec356f7dd7286ad3e938c71/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It seems like the proto compiler has removed the `hasX()` methods for scalars upon moving to `common-jvm` apparently. It doesn't matter anyway as file should be reverted once this PR is rebased to main (since Yunus just updated this file)
</blockquote></details>

removing hasX() for oneOf fields doesn't sound good, even for scalars. I'll double check later

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184#-MgRWkhH5g8WHCx2UYWK:-MgRbTHb-uc206lQw3rb:b7ioohv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49960f7712c1c822ec356f7dd7286ad3e938c71/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L42)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

removing hasX() for oneOf fields doesn't sound good, even for scalars. I'll double check later
</blockquote></details>

Alrighty, @enfreck please let us know when you've pulled and this file has been fixed

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck and @wangyaopw)

___
*[WORKSPACE, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184#-MgRa-YREKhcf1dSGQF_:-MgRfobyDanfBBoDl0CU:b7u03hh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49960f7712c1c822ec356f7dd7286ad3e938c71/WORKSPACE#L33)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> common_cpp_repositories
> ```
Does this mean that all repos polling from common_cpp will load all the common_cpp_repositories even if a subset of them are needed? 
</blockquote></details>

Correct

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck)

___
*[WORKSPACE, line 169 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184#-MgSIOYb2uFNWNyb-5xW:-MgSIOYb2uFNWNyb-5xX:b-gdbm6l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b26f3f6e131f5fcc042787225951fcf31ae26e22/WORKSPACE#L169)):*
> ```Starlark
>     "org.mockito.kotlin:mockito-kotlin": "3.2.0",
>     "info.picocli:picocli": "4.4.0",
>     "junit:junit": "4.13",
> ```

what if we need to add another artifact?

for example, cmms needs "com.google.crypto.tink:tink": "1.6.0",

should we update the COMMON_JVM_MAVEN_TARGETS in the common-jvm or just add locally?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck and @wangyaopw)

___
*[WORKSPACE, line 169 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184#-MgSIOYb2uFNWNyb-5xW:-MgSKreu3lOg0JEg8Ygv:b-xzvez3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b26f3f6e131f5fcc042787225951fcf31ae26e22/WORKSPACE#L169)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

what if we need to add another artifact?

for example, cmms needs "com.google.crypto.tink:tink": "1.6.0",

should we update the COMMON_JVM_MAVEN_TARGETS in the common-jvm or just add locally?
</blockquote></details>

It's fine to add locally if nothing else needs it. Just write:

```
MAVEN_ARTIFACTS = ...
maven_install(
  artifacts = common_jvm_maven_artifacts() + MAVEN_ARTIFACTS,
 ...
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck)

___
*[WORKSPACE, line 169 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184#-MgSIOYb2uFNWNyb-5xW:-MgSMs5n2_RtW3y5hE21:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b26f3f6e131f5fcc042787225951fcf31ae26e22/WORKSPACE#L169)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's fine to add locally if nothing else needs it. Just write:

```
MAVEN_ARTIFACTS = ...
maven_install(
  artifacts = common_jvm_maven_artifacts() + MAVEN_ARTIFACTS,
 ...
```
</blockquote></details>

sg

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by corbantek — APPROVED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @oliver-amzn, @stevenwarejones, and @zachcwc)

___
*[WORKSPACE, line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184#-Mggmnb5-Cbcg0YeiM36:-Mggmnb5-Cbcg0YeiM37:b-8qh32v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/166b3f1a21c75e61c9a897587d9f034860128783/WORKSPACE#L22)):*
> ```Starlark
> 
> # Common-cpp
> http_archive(
> ```

Can this just use the **wfa_repo_archive** function like `wfa_common_jvm`?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @corbantek, @efoxepstein, @oliver-amzn, @stevenwarejones, and @zachcwc)

___
*[WORKSPACE, line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184#-Mggmnb5-Cbcg0YeiM36:-Mgh5kH84O7nvpekh3ZJ:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/166b3f1a21c75e61c9a897587d9f034860128783/WORKSPACE#L22)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Can this just use the **wfa_repo_archive** function like `wfa_common_jvm`?
</blockquote></details>

Done

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn, @stevenwarejones, and @zachcwc)

**Pull request merged**
