### PR TITLE
Add a guide covering leaf certificate and encryption key rotation.

### LINKED ISSUE #764: Add certificate/key rotation guide and explainer
- There is no documented process on how to rotate certificates which has blocked the team from executing integration tasks
- Work around is to create new resources which causes delay and rework
- Halo has provided some help to aide with the knowledge gap but after following instructions there is still unexpected results which might imply there is a bug in the code
- Further analysis is required

### PR DESCRIPTION
**Pull request by SanjayVas**
Closes #764

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @kungfucraig)

___
*[`docs/operations/certificate-key-rotation.md` line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220#-NeOPoWNBCBFkOKrCTMa:-NePocXU8m77u4SbYb5R:bw0rpqp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10137522ea61c71f09014d66b7fa173bb86283f1/docs/operations/certificate-key-rotation.md#L3)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This document describes how to ...
</blockquote></details>

This is following the style used in other operations guides.
___
*[`docs/operations/certificate-key-rotation.md` line 74 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220#-NeORyF-2jMxxl72So1j:-NePreXw4ApMgDw5lKa2:b-aa1trk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10137522ea61c71f09014d66b7fa173bb86283f1/docs/operations/certificate-key-rotation.md#L74)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It's worth mentioning we use TLS for gRPC authn.
</blockquote></details>

Done (mentioned using the AKID of the client cert).
___
*[`docs/operations/certificate-key-rotation.md` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220#-NeOQhfDAw537U6KRHgn:-NePok6l97qVvXKK9GJi:b-taa65y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10137522ea61c71f09014d66b7fa173bb86283f1/docs/operations/certificate-key-rotation.md#L78)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think you want lower case here.
</blockquote></details>

If referring to the casing on `Secret`, that's intentional. I added code formatting and a link to the relevant resource in the K8s API to make it clearer.
___
*[`docs/operations/certificate-key-rotation.md` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220#-NeOQxrq89ZIWyvik6Gx:-NePpF4m6A_Nq7dYiIfp:bke6vrp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10137522ea61c71f09014d66b7fa173bb86283f1/docs/operations/certificate-key-rotation.md#L80)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Typically we'll want to support both the old cert and the new cert for a period of time. I think it would be good to note this process: 1) add new cert; 2) communicate this to clients; 3) allow some time to pass and confirm old cert is out of use; 4) remove old cert.

I think this applies equally to the TLS section.
</blockquote></details>

For TLS, the sender unilaterally chooses when the new cert is used. For API certs, adding a new cert does not prevent the old one from being used as it's still valid. Revocation to invalidate a certificate is covered separately in the "Compromise" section.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`docs/operations/certificate-key-rotation.md` line 90 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220#-NePvNjj1UTjO1uNIEae:-NePvNjj1UTjO1uNIEaf:b61zjx0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10137522ea61c71f09014d66b7fa173bb86283f1/docs/operations/certificate-key-rotation.md#L90)):*
> ```Markdown
>     [`Certificate` resource](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/certificate.proto).
> 
>     Call the
> ```

Does the CLI support these operations?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @kungfucraig)

___
*[`docs/operations/certificate-key-rotation.md` line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220#-NeORUoRAzZRN35W-Qzs:-NejRlSBElWmp9-K4w5O:bbrx1zz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10137522ea61c71f09014d66b7fa173bb86283f1/docs/operations/certificate-key-rotation.md#L83)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Having an example build up around this would be helpful.
</blockquote></details>

Added/updated examples in CLI tool documentation.
___
*[`docs/operations/certificate-key-rotation.md` line 90 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220#-NePvNjj1UTjO1uNIEae:-NejRqXl2MB3YTwcO3eq:b-igsjmp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10137522ea61c71f09014d66b7fa173bb86283f1/docs/operations/certificate-key-rotation.md#L90)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Does the CLI support these operations?
</blockquote></details>

Yes. Added a reference to the tools.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1220)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by mariolamassaavedra — APPROVED** [review]

**Pull request merged**
