### PR TITLE
Update the KingdomDataServer and V2alphaPublicApiServer.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/186)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/186)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/186#-MgSqxu5D0RoULvGbSB6:-MgSqxu5D0RoULvGbSB7:biuq8cv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efb5530371a1dcdee6a6f56341ef04977ef95ea3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L48)):*
> ```Kotlin
>     channel ->
>     listOf(
>       DataProvidersService(DataProvidersCoroutineStub(channel)),
> ```

I can imagine this could be pretty confusing for someone because it looks like each service is connecting to itself. Would it make sense to use import aliases to call the internal things like `InternalDataProvidersCoroutineStub`?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/186)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/186#-MgSqxu5D0RoULvGbSB6:-MgTBXVb-5b2FDRea-rB:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efb5530371a1dcdee6a6f56341ef04977ef95ea3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I can imagine this could be pretty confusing for someone because it looks like each service is connecting to itself. Would it make sense to use import aliases to call the internal things like `InternalDataProvidersCoroutineStub`?
</blockquote></details>

Done

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by corbantek — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
