### PR TITLE
Catch UNAVAILABLE exception when ComputationServer not ready

### PR DESCRIPTION
**Pull request by renjiezh**
Mill always has logs at the beginning of running. It is because the ComputationServer pods usually take longer to get ready. This PR is to catch these errors and log at INFO level.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/701)

### CODE REVIEW

**Comment by renjiezh** [comment]
I tried to make the container init wait until the downstream servers are in READY status. (So far it wait until dependencies are RUNNING, which might not be READY). But it is hard to implement without third party library. And I think it is not a bad thing to start the init even when dependencies not ready.

**Review by matthewclegg — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/701)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by matthewclegg — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/701)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/701)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/701)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/701)* status: all files reviewed, 1 unresolved discussion

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 136 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/701#-NCvAtIM2tFA2nZofxQN:-NCvAtIM2tFA2nZofxQO:bv5ysvm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc19ce1c701f65e97da8a232d43cf531ea434d66/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L136)):*
> ```Kotlin
>       } catch (ex: StatusException) {
>         if (!computationsServerReady && ex.status.code == Status.Code.UNAVAILABLE) {
>           logger.info("ComputationServer not ready")
> ```

Note that UNAVAILABLE doesn't necessarily happen exclusively at startup, but any time a connection to the server cannot be established. It's expected to happen as servers restart or are moved. It's usually a safe error code to retry on, ideally with a delay backoff.

See https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/695.



_Code quote:_
```Kotlin
    logger.info("ComputationServer not ready")
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/701)* status: all files reviewed, 1 unresolved discussion

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 136 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/701#-NCvAtIM2tFA2nZofxQN:-NCvCG2IBw88SR49SWQB:b-3rcyze) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc19ce1c701f65e97da8a232d43cf531ea434d66/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L136)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that UNAVAILABLE doesn't necessarily happen exclusively at startup, but any time a connection to the server cannot be established. It's expected to happen as servers restart or are moved. It's usually a safe error code to retry on, ideally with a delay backoff.

See https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/695.
</blockquote></details>

computationsServerReady is the variable indicating whether at least one call succeeded. This catch block will not suppress UNAVAILABLE afterward.
yeah, I agree we will eventually use ServiceConfig for most retries if not all. 



_Code quote:_
```Kotlin
computationsServerReady
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/701)* status: all files reviewed, 1 unresolved discussion

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 133 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/701#-NCw9M-R6VMcsb_SQsa9:-NCw9M-R6VMcsb_SQsaA:bfi565s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc19ce1c701f65e97da8a232d43cf531ea434d66/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L133)):*
> ```Kotlin
>     val claimWorkResponse =
>       try {
>         dataClients.computationsClient.claimWork(claimWorkRequest)
> ```

This might be a simpler approach.



_Suggestion:_
```Kotlin
dataClients.computationsClient.withWaitForReady().claimWork(claimWorkRequest)
```

**Pull request merged**
