### PR TITLE
Remove public_key and certificate for ModelProvider

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522)

### CODE REVIEW

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @renjiezh)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522#-N-TuAhw4slwesRJuty6:-N-TuAhx4we5U1Re0tGY:b-sibwts) (no related file):*
You can also get rid of ModelProviderCertificateKey.kt.

---

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522#-N-TuAhw4slwesRJuty6:-N-Tzjgb6NKnZqErYb4i:b-896fix) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

You can also get rid of ModelProviderCertificateKey.kt.
</blockquote></details>

Done.

---

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @renjiezh)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522#-N-UIuKU1lI5eGIhMLgL:-N-UIuKV6m__IokUvs4B:br692dc) (no related file):*
Make sure to work with Yunus to update the [deployment doc](https://docs.google.com/document/d/1tx_R6TJFyj1Sm-lZ-mTprmb0hI6k6Qc5Y-ufESgb9BQ/edit?usp=sharing&resourcekey=0-QAXP4Z9oaHUKLFxbPybJGw) after this is merged. In particular, the steps for MP resource creation are now slightly different than for EDP due to the former not having certificate and public key.

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522#-N-UJKj07fh-8XrmNxpl:-N-UJKj07fh-8XrmNxpm:bdvulwq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4fd22d2d187041f832808bcb257a0fb844c3f8a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L160)):*
> ```Kotlin
> 
> @Command(name = "model-provider", description = ["Creates a ModelProvider"])
> private class CreateModelProviderCommand : CreatePrincipalCommand() {
> ```

This should no longer extend `CreatePrincipalCommand`, as that includes options for certificate and public key.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522#-N-UJf415AnWAr8RpYYK:-N-UJf415AnWAr8RpYYL:b-86kfrv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4fd22d2d187041f832808bcb257a0fb844c3f8a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L160)):*
> ```Kotlin
> 
> @Command(name = "model-provider", description = ["Creates a ModelProvider"])
> private class CreateModelProviderCommand : CreatePrincipalCommand() {
> ```

Update the example in the README. Should probably have examples for both `DataProvider` and `ModelProvider` since they are now different.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522#-N-UJKj07fh-8XrmNxpl:-N-UaA323OUW6zk0REDY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4fd22d2d187041f832808bcb257a0fb844c3f8a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L160)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should no longer extend `CreatePrincipalCommand`, as that includes options for certificate and public key.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522#-N-UJf415AnWAr8RpYYK:-N-UaAO233DC5rze-JI-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4fd22d2d187041f832808bcb257a0fb844c3f8a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L160)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Update the example in the README. Should probably have examples for both `DataProvider` and `ModelProvider` since they are now different.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @renjiezh, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 161 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522#-N-Z08R52fAi7GmZkFOo:-N-Z08R52fAi7GmZkFOp:bimzp65) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/daee8bbd3b59e791cd678e30fb91f444edda7124/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L161)):*
> ```Kotlin
> @Command(name = "model-provider", description = ["Creates a ModelProvider"])
> private class CreateModelProviderCommand : Runnable {
>   @ParentCommand private lateinit var parent: CreateResource
> ```

nit: add blank line between property and function

**Review by renjiezh — COMMENTED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, 1 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/522)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein and @stevenwarejones)

**Pull request merged**
