### PR TITLE
Update PrivacyQueryMapper for ACDP composition

### PR DESCRIPTION
**Pull request by iverson52000**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @RibeiroAna, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163#-NbVZQR5AL7iOqmPw7SA:-NbVZQR5AL7iOqmPw7SB:b-fezjz4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d020ea17043abc4ae6734f743d813bd3c822df/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt#L29)):*
> ```Kotlin
> import org.wfanet.measurement.eventdataprovider.privacybudgetmanagement.Reference
> 
> private const val SENSITIVITY = 1.0
> ```

this should initialized with the object/class imo

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @RibeiroAna, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163#-NbVZQR5AL7iOqmPw7SA:-NbVaGiN5Og5-QdB1swM:b-eykgx8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d020ea17043abc4ae6734f743d813bd3c822df/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this should initialized with the object/class imo
</blockquote></details>

Done. Make sense thanks

**Comment by uakyol** [comment]
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163#-NbVZQR5AL7iOqmPw7SA:-NbWf0AA2a81iYDqcoq0:b-fkkkj3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d020ea17043abc4ae6734f743d813bd3c822df/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt#L29)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done. Make sense thanks
</blockquote></details>

Do we ever want to initialize the PBM with a different sensitivity?

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @RibeiroAna and @uakyol)

**Review by uakyol — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163)* status: all files reviewed, 1 unresolved discussion (waiting on @RibeiroAna and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163#-NbVZQR5AL7iOqmPw7SA:-Nb_iDEt5wkFv5tMgQE3:b-yvw55i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d020ea17043abc4ae6734f743d813bd3c822df/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt#L29)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Do we ever want to initialize the PBM with a different sensitivity?
</blockquote></details>

Synced offline, seems we would need to do this.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163)* status: all files reviewed, 1 unresolved discussion (waiting on @RibeiroAna and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163#-NbVZQR5AL7iOqmPw7SA:-Nb_ppaO9ChTBf2K7iPC:bwoyv60) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d020ea17043abc4ae6734f743d813bd3c822df/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt#L29)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Synced offline, seems we would need to do this. 
</blockquote></details>

change this to a class with the sensitivity passed in to the constructor then?

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163)* status: all files reviewed, 1 unresolved discussion (waiting on @RibeiroAna and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163#-NbVZQR5AL7iOqmPw7SA:-NbaOBYB7-JnAvV5taIQ:b-num76h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d020ea17043abc4ae6734f743d813bd3c822df/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

change this to a class with the sensitivity passed in to the constructor then?
</blockquote></details>

The SENSITIVITY is subject to change in the future in some ways. From Pasin, the SENSITIVITY may be different from 1.0 for `impression` and `duration`. It may be fixed constant, or an output from another function depends on the design of other ACDP PBM add-on features. I suggest we leave `PrivacyQueryMapper` as it is for now and update it later when needed.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1163)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RibeiroAna)

**Pull request merged**
