### PR TITLE
Add GetReport Proto Definition to the BFF

### PR DESCRIPTION
**Pull request by bdomen-ggl**
Creating get report proto definition for the BFF. It is a nested object of metrics: time interval -> demographic -> publisher (individual, complement, union) -> metric.

The UI can use the source names in the metric to perform basic calculations for displaying one, some combination, or all the results.

Working on a build error: `No dependencies were provided.`
Probably has something to do with the Bazel tools: Go Rules and Gazelle.
UPDATE: Will manually add the Time Interval proto and do more investigation. MAYBE can just update the go rules and gazelle versions.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360)

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-NlZrfKS3Yt_LI6qKYHB:-NlZrUPQ1UWfH95xyM6B:b-asc0nt) (no related file):*
@SanjayVas Added the `interval.proto` from googleapis temporarily with a TODO to remove it later. Was able to get the build locally to work.

___

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @bdomen-ggl and @iverson52000)

___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-Nlj0MpbBaP36BRRLZJJ:-Nlj0MpbBaP36BRRLZJK:b5y36ja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L28)):*
> ```proto
> option go_package = "wfa/measurement/reporting/bff/v1alpha/reportingpb";
> 
> message Metric {
> ```

Move this inside of Report since it's only used there. Also maybe pick a name that's not so overloaded.
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-Nlj1Q-4DmiAMhoT2LHm:-Nlj1Q-4DmiAMhoT2LHn:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L30)):*
> ```proto
> message Metric {
>   string source_name = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
>   int64 impressions = 2 [(google.api.field_behavior) = OUTPUT_ONLY];
> ```





_Suggestion:_
```proto
impression_count
```
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-Nlj1fh438fQA4FSOJGs:-Nlj1fh438fQA4FSOJGt:b62oupq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L30)):*
> ```proto
> message Metric {
>   string source_name = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
>   int64 impressions = 2 [(google.api.field_behavior) = OUTPUT_ONLY];
> ```

Note that you may need more structure here so we can support things like error bars in the future. Take a look at MetricResult in Reporting v2.
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-Nlj1Xxl7CrvqCIDORPW:-Nlj1Xxl7CrvqCIDORPX:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L31)):*
> ```proto
>   string source_name = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
>   int64 impressions = 2 [(google.api.field_behavior) = OUTPUT_ONLY];
>   int64 frequency = 3 [(google.api.field_behavior) = OUTPUT_ONLY];
> ```





_Suggestion:_
```proto
 map<int32, double> frequency_histogram
```
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/time_interval.proto` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-Nlj09yn1h3fBhthmqMM:-Nlj027x2PMBZZ14QBKT:b5y36ja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/time_interval.proto#L29)):*
> ```proto
> option go_package = "wfa/measurement/reporting/bff/v1alpha/reportingpb";
> 
> message TimeInterval {
> ```

Move this inside of Report since it's only used there. Also maybe pick a name that's not so overloaded.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360)* status: all files reviewed, 8 unresolved discussions (waiting on @bdomen-ggl and @iverson52000)

___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/demo_bucket.proto` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-NljNqlJ6N6B1LAFRGYQ:-NljNqlJ6N6B1LAFRGYR:bkqorzo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/demo_bucket.proto#L27)):*
> ```proto
> 
> option go_package = "wfa/measurement/reporting/bff/v1alpha/reportingpb";
> ```

Please add documentation for the messages and fields.
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-NljOB-m3gYZ0lsMAu33:-NljOB-m3gYZ0lsMAu34:bmhtwlu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L29)):*
> ```proto
> 
> message Metric {
>   string source_name = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
> ```

Where does this come from?

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360)* status: all files reviewed, 8 unresolved discussions (waiting on @iverson52000, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/demo_bucket.proto` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-NljNqlJ6N6B1LAFRGYQ:-NlxuZse9jovcIMMxNEM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/demo_bucket.proto#L27)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please add documentation for the messages and fields.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-Nlj0MpbBaP36BRRLZJJ:-NlxnGKy4O0DWdrJqPPT:b-uwdcfe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move this inside of Report since it's only used there. Also maybe pick a name that's not so overloaded.
</blockquote></details>

Done.

Also moved the demo_bucket.
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-NljOB-m3gYZ0lsMAu33:-Nlxp_a0-E5xr_2pN7dd:b-3gtuu5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L29)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Where does this come from?
</blockquote></details>

Still thinking about it. The easiest is probably through the reporting set tags. A lot of these will be the individual publisher, but many won't (full union and complement sets).
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-Nlj1Q-4DmiAMhoT2LHm:-Nlxn_y3DzvPVURZGPBH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L30)):*
> ```proto
> message Metric {
>   string source_name = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
>   int64 impressions = 2 [(google.api.field_behavior) = OUTPUT_ONLY];
> ```

Done.
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-Nlj1fh438fQA4FSOJGs:-NlxutIE8ecpL2Q4oyM0:b-j613k1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that you may need more structure here so we can support things like error bars in the future. Take a look at MetricResult in Reporting v2.
</blockquote></details>

I was going to do that later when we have more requirements around this, but that's a good call to put in now. Will surely be added in the future.
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-Nlj1Xxl7CrvqCIDORPW:-NljB5Ja9nS3cKGVEKBJ:b-idjx91) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L31)):*
> ```proto
>   string source_name = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
>   int64 impressions = 2 [(google.api.field_behavior) = OUTPUT_ONLY];
>   int64 frequency = 3 [(google.api.field_behavior) = OUTPUT_ONLY];
> ```

Yeah... I was realizing I couldn't do the histogram with one frequency. Thinking about doing the same kind of thing as Reporting V2 by using the bins (except these will be 1+, 2+, ... instead of 1, 2, ...).

Done.
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/time_interval.proto` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-Nlj09yn1h3fBhthmqMM:-NlxnIVi-MZLe85yDuYX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/time_interval.proto#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move this inside of Report since it's only used there. Also maybe pick a name that's not so overloaded.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360)* status: all files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl, @iverson52000, and @kungfucraig)

___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/report.proto` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-NlyVO_cE5DAjV7e-JWP:-NlyVO_cE5DAjV7e-JWQ:biblcd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdfe5a160977768a19225633404eceebf3422907/src/main/proto/wfa/measurement/reporting/bff/v1alpha/report.proto#L62)):*
> ```proto
>     // Mostly copied from
>     // https://github.com/googleapis/googleapis/blob/master/google/type/interval.proto
>     // TODO(@bdomen-ggl): Remove when we get the GRPC Gateway protos working by
> ```

The blocking PR was merged, so you *might* be able to get this working now.

**Review by iverson52000 — APPROVED** [review]
Do we need external approval since these changes are outside of `experimental` folder?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-:-Nlz4PkXCcHjO-QZQTjT:b-ecbex1)* status: all files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl and @kungfucraig)

**Review by bdomen-ggl — COMMENTED** [review]
I guess technically, but we haven't for these protos since they're bff specific which is experimental. I think we added these before we decided to go with the experimental folder. We only got an external review on the first commit.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-:-Nm1hA-O74cU3WJgyTrf:bwtj8x)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/report.proto` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-NlyVO_cE5DAjV7e-JWP:-Nm1asbe820Om0Z3yoMp:bgaxplu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdfe5a160977768a19225633404eceebf3422907/src/main/proto/wfa/measurement/reporting/bff/v1alpha/report.proto#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The blocking PR was merged, so you *might* be able to get this working now.
</blockquote></details>

Yep, it's working now. Thanks.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-NljOB-m3gYZ0lsMAu33:-Nm2Irg47M4DC38_EXT7:b-vnuf81) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L29)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Still thinking about it. The easiest is probably through the reporting set tags. A lot of these will be the individual publisher, but many won't (full union and complement sets).
</blockquote></details>

I don't understand. Are you wanting to merge this PR?

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-NljOB-m3gYZ0lsMAu33:-Nm2QPiv9ylZqXBJbSYA:bk6l2oq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6670b0a0481e155e7f9643ea96bc2c1443bb73b/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L29)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I don't understand. Are you wanting to merge this PR?
</blockquote></details>

Yes. The idea is generally going to be to provide info on which reporting sets are for the individual publishers and which ones are for the publisher complements so we can do the unique calculations. Still thinking about the exact formatting of the strings. Makes the most sense for the info to come from the reporting set tags since the user who created them (ie. us) can specify them as such.

**Review by kungfucraig — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360#-:-Nm34PX5442GzSZw2ueH:bnfp4nl)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1360)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl)

**Pull request merged**
