### PR TITLE
Update reporting measurements service to update reports when possible

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616)

### CODE REVIEW

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/MeasurementResultsReader.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616#-N6jkUUhBu712l8jMS8Q:-N6npQeeBfuTTDqANBPa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/39a1a924646b5054a37fffdcc8059c75abfc49a6/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/MeasurementResultsReader.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The number of duplicated columns here is small, so it's not worth the JSON serialization/parsing overhead. Just select all the measurement columns + report ID.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt` line 106 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616#-N6jmapyEBAPWJ1J0PeL:-N6npREb1RFYEHxlj89n:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/39a1a924646b5054a37fffdcc8059c75abfc49a6/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt#L106)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the `bind` overload for protobuf messages rather than serializing yourself.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616#-N6jjhq9AmXbmNyoCNdm:-N6npRlB19kRplZ2E9j5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/39a1a924646b5054a37fffdcc8059c75abfc49a6/src/main/resources/reporting/postgres/create-reporting-schema.sql#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Keep the binary serialization.

If you're looking at the Spanner Kingdom internal service impl, it has some write-only JSON serialized protobuf messages for debugging alongside the binary serialized ones, but in those cases it's still the binary serialization used for actual business logic.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/MeasurementResultsReader.kt` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616#-N6oGsRt0DcQHi4jTlPg:-N6oGsRt0DcQHi4jTlPh:bq1ed9c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a2f44523d16fdd02d35890b7421417660695961a/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/MeasurementResultsReader.kt#L77)):*
> ```Kotlin
> 
>   private fun buildResult(row: ResultRow): Measurement.Result? {
>     val result = row.get<String?>("Result") ?: return null
> ```

```kotlin
return row.getProtoMessage("Result", Measurement.Result.parser())
```



_Code quote:_
```Kotlin
    val result = row.get<String?>("Result") ?: return null
    return Measurement.Result.parseFrom(result.base64UrlDecode())
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616#-N6oHmSN7ogfoRNvcYnV:-N6oHmSN7ogfoRNvcYnW:bcvusmu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a2f44523d16fdd02d35890b7421417660695961a/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt#L62)):*
> ```Kotlin
>       ) {
>         bind("$1", Measurement.State.SUCCEEDED_VALUE)
>         bind("$2", request.result.toByteString().base64UrlEncode())
> ```

Don't do your own alternate encoding of protobuf messages.



_Code quote:_
```Kotlin
.toByteString().base64UrlEncode()
```
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616#-N6jjhq9AmXbmNyoCNdm:-N6oIlbM74hxa9lP1_bM:b-i9kvtj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/39a1a924646b5054a37fffdcc8059c75abfc49a6/src/main/resources/reporting/postgres/create-reporting-schema.sql#L104)):*
> -- protobuf message encoded as base64url.

Nope. Always binary serialization.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 124 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616#-N6oIvbW0v3GkQFpE9DG:-N6oIvbW0v3GkQFpE9DH:b-d2dza6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a2f44523d16fdd02d35890b7421417660695961a/src/main/resources/reporting/postgres/create-reporting-schema.sql#L124)):*
> ```TSQL
>   Failure bytea,
> 
>   -- Serialized org.wfanet.measurement.internal.reporting.Measurement.Result
> ```

Same here. Canonical persistence as protobuf binary.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616)* status: 6 of 10 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/MeasurementResultsReader.kt` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616#-N6oGsRt0DcQHi4jTlPg:-N6oQoB7Bxxob8foLnv_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a2f44523d16fdd02d35890b7421417660695961a/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/MeasurementResultsReader.kt#L77)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

```kotlin
return row.getProtoMessage("Result", Measurement.Result.parser())
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616#-N6oHmSN7ogfoRNvcYnV:-N6oQoh16LLK96jJfXO6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a2f44523d16fdd02d35890b7421417660695961a/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't do your own alternate encoding of protobuf messages.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616#-N6jjhq9AmXbmNyoCNdm:-N6oQpB-Bt0PjzrUavR3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/39a1a924646b5054a37fffdcc8059c75abfc49a6/src/main/resources/reporting/postgres/create-reporting-schema.sql#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> -- protobuf message encoded as base64url.

Nope. Always binary serialization.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 124 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616#-N6oIvbW0v3GkQFpE9DG:-N6oQpfa6vYsXSK6KZZU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a2f44523d16fdd02d35890b7421417660695961a/src/main/resources/reporting/postgres/create-reporting-schema.sql#L124)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here. Canonical persistence as protobuf binary.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 9 files at r1, 1 of 6 files at r2, 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt` line 237 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616#-N7qiibbD7U8qWsLhC4g:-N7qiibcCmz5SrsT6XEX:b-v5vam0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7f86824230f25d9f90eec67d6c07c3250f66de9e/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt#L237)):*
> ```Kotlin
>         calculateFrequencyHistogramResults(measurementResultsList)
>       Metric.Details.MetricTypeCase.METRICTYPE_NOT_SET -> {
>         error("Metric Type should've been set.")
> ```

nit: "Metric Type should be set."

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 4 of 9 files at r1, 1 of 6 files at r2, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/616)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
