### PR TITLE
Add Reporting V2 Event Group Metadata Descriptors Service.

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group_metadata_descriptors_service.proto` line 29 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc-O4nk5xeY9NsWfqIb:-Nc-O4nk5xeY9NsWfqIc:b-mf2swp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/38e11d6edcb793f67750132253222e65cc76f0ae/src/main/proto/wfa/measurement/reporting/v2alpha/event_group_metadata_descriptors_service.proto#L29)):*
> ```proto
> 
> // Service for interacting with `EventGroupMetadataDescriptor` resources.
> service EventGroupMetadataDescriptors {
> ```

The intent was not to add a new service to the Reporting API but rather serve the Kingdom's API service from the Reporting API server.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group_metadata_descriptors_service.proto` line 29 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc-O4nk5xeY9NsWfqIb:-Nc36X1y9C0oZ-y1LAJR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/38e11d6edcb793f67750132253222e65cc76f0ae/src/main/proto/wfa/measurement/reporting/v2alpha/event_group_metadata_descriptors_service.proto#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The intent was not to add a new service to the Reporting API but rather serve the Kingdom's API service from the Reporting API server.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 18 files at r1, 1 of 10 files at r2, 1 of 3 files at r3, 1 of 11 files at r5, 2 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162)* status: 7 of 18 files reviewed, 6 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt` line 49 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc4aSe3CIrksFd_i0es:-Nc4aSe3CIrksFd_i0et:bdoe9aa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfa99377470d0fe3201eeb0dbf88fb4e25fc7980/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L49)):*
> ```Kotlin
>     val apiAuthenticationKey: String = principal.config.apiKey
> 
>     grpcRequireNotNull(EventGroupMetadataDescriptorKey.fromName(request.name)) {
> ```

This is fine, but not strictly required. The delegate will handle this.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt` line 57 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc4aM_t1kjVb5YZW0E9:-Nc4aM_t1kjVb5YZW0EA:b-rgrn1u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfa99377470d0fe3201eeb0dbf88fb4e25fc7980/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L57)):*
> ```Kotlin
>         .withAuthenticationKey(apiAuthenticationKey)
>         .getEventGroupMetadataDescriptor(
>           getEventGroupMetadataDescriptorRequest { name = request.name }
> ```

Just pass the request messages through directly, No need to build new ones.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt` line 59 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc4_u4iDJyX4WDfz80n:-Nc4_u4iDJyX4WDfz80o:b-y9bqj1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfa99377470d0fe3201eeb0dbf88fb4e25fc7980/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L59)):*
> ```Kotlin
>           getEventGroupMetadataDescriptorRequest { name = request.name }
>         )
>     } catch (e: StatusException) {
> ```

A proxy is the rare case when you can just let the underlying StatusException bubble up.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 1 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc4bWqz-K6J3u1-TuU_:-Nc4bWqz-K6J3u1-TuUa:bdhlm7t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfa99377470d0fe3201eeb0dbf88fb4e25fc7980/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L1)):*
> ```Kotlin
> /*
> ```

I don't think it was strictly necessary to add this to the CLI tool, but since you already did it it's fine :)
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 511 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc4b9c4DQZwUKnqZtD_:-Nc4b9c4DQZwUKnqZtDa:b-fjrowz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfa99377470d0fe3201eeb0dbf88fb4e25fc7980/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L511)):*
> ```Kotlin
>   @CommandLine.ParentCommand private lateinit var parent: EventGroupMetadataDescriptorsCommand
> 
>   @CommandLine.Option(
> ```

nit: You can use a [positional parameter](https://picocli.info/#_positional_parameters) for this the same way you would for Get.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162)* status: 4 of 18 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt` line 57 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc4aM_t1kjVb5YZW0E9:-Nc5YnSODqXs3b5rTHOv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfa99377470d0fe3201eeb0dbf88fb4e25fc7980/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just pass the request messages through directly, No need to build new ones.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt` line 59 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc4_u4iDJyX4WDfz80n:-Nc5YoUpDw6WMJTnPxaE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfa99377470d0fe3201eeb0dbf88fb4e25fc7980/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

A proxy is the rare case when you can just let the underlying StatusException bubble up.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 18 files at r1, 2 of 10 files at r2, 4 of 11 files at r5, 1 of 1 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1726 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc9UtjN50zMwZFhqmrb:-Nc9UtjO0g87vkyOICvG:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1d03aea014d4a24626923ee1291a204ce32741f/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1726)):*
> ```Kotlin
>     for (eventGroup in eventGroups) {
>       descriptorNames.add(eventGroup.metadata.eventGroupMetadataDescriptor)
>     }
> ```





_Suggestion:_
```Kotlin
    val descriptorNames = eventGroups.map { it.metadata.eventGroupMetadataDescriptor }
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsServiceTest.kt` line 93 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc9UCVB-u-cD5S-VCXe:-Nc9UCVB-u-cD5S-VCXf:b-krxph0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1d03aea014d4a24626923ee1291a204ce32741f/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsServiceTest.kt#L93)):*
> ```Kotlin
> 
>     assertThat(response).isEqualTo(EVENT_GROUP_METADATA_DESCRIPTOR)
> ```

Use [HeaderCapturingInterceptor](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/testing/HeaderCapturingInterceptor.kt) to verify that we're passing the API key.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162)* status: 15 of 18 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1726 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc9UtjN50zMwZFhqmrb:-NcO6R26-a1IcwFM1ZYb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/754d928f1ad5b60452a7e9596edff0f6a3868eab/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1726)):*
> ```Kotlin
>     for (eventGroup in eventGroups) {
>       descriptorNames.add(eventGroup.metadata.eventGroupMetadataDescriptor)
>     }
> ```

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsServiceTest.kt` line 93 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162#-Nc9UCVB-u-cD5S-VCXe:-NcO6QEo6WeKGiKwS8Na:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/754d928f1ad5b60452a7e9596edff0f6a3868eab/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupMetadataDescriptorsServiceTest.kt#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use [HeaderCapturingInterceptor](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/testing/HeaderCapturingInterceptor.kt) to verify that we're passing the API key.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 18 files at r1, 2 of 10 files at r2, 1 of 3 files at r3, 2 of 11 files at r5, 5 of 6 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
