### PR TITLE
Add get method to internal reporting sets service.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621)* status: all files reviewed, 5 unresolved discussions (waiting on @duliomatos1 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt` line 139 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621#-N6onlQDCIby4pFLwEF5:-N6onlQE3iRzR2iXD6JG:b-u46qbn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdf5e35da2b788abe23233b73c5d463c0cca4b0c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt#L139)):*
> ```Kotlin
>       filter = row["Filter"]
>       displayName = row["DisplayName"]
>       val eventGroupsArr = row.get<Array<String>>("EventGroups")
> ```

`Json`



_Code quote:_
```Kotlin
String
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621#-N6oqpPv6dZ7uHnOotSj:-N6oqpPv6dZ7uHnOotSk:b-clgqqm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdf5e35da2b788abe23233b73c5d463c0cca4b0c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L33)):*
> ```Kotlin
> class CreateReportingSet(private val request: ReportingSet) : PostgresWriter<ReportingSet>() {
>   override suspend fun TransactionScope.runTransaction(): ReportingSet {
>     val internalReportingSetId = idGenerator.generateInternalId().value
> ```

Use the `bind` overloads for `InternalId` and `ExternalId` to keep the specific types as long as possible.



_Code quote:_
```Kotlin
.value
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621#-N6or6Re2rXanHBbciCS:-N6or6Re2rXanHBbciCT:bgdgzle) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdf5e35da2b788abe23233b73c5d463c0cca4b0c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L36)):*
> ```Kotlin
>     val externalReportingSetId = idGenerator.generateExternalId().value
> 
>     val statement =
> ```

Extract an `insertReportingSet` function, as that will make it more clear that this is method is doing two things: inserting the reporting set, then inserting the corresponding event groups.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621#-N6ooxV4CtIN_uKT7HyG:-N6ooxV4CtIN_uKT7HyH:b-q1gzpe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdf5e35da2b788abe23233b73c5d463c0cca4b0c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L50)):*
> ```Kotlin
>       }
> 
>     transactionContext.run {
> ```

This seems rather unnecessary as it appears to only be removing one reference. In general, only use scope functions when they improve readability.

```kotlin
      try {
        transactionContext.executeStatement(statement)
      } catch (e: R2dbcDataIntegrityViolationException) {
        throw ReportingSetAlreadyExistsException()
      }
      coroutineScope {
        for (eventGroupKey in request.eventGroupsKeysList) {
          launch { insertReportingSetEventGroup(eventGroupKey, internalReportingSetId) }
        }
      }
```



_Code quote:_
```Kotlin
 transactionContext.run {
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/ReportingInternalException.kt` line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621#-N6orZgB2VqhpxG4E8rD:-N6orZgB2VqhpxG4E8rE:b3xu46o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdf5e35da2b788abe23233b73c5d463c0cca4b0c/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/ReportingInternalException.kt#L84)):*
> ```Kotlin
> 
> class ReportingSetNotFoundException(
>   provideDescription: () -> String = { "Reporting Set not found" }
> ```

Add a TODO to specify the appropriate context when each of these exceptions is thrown.

Make sure to avoid leaking any internal IDs.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt` line 139 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621#-N6onlQDCIby4pFLwEF5:-N6p2HCQ-A5wEU2aam1S:b-851put) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdf5e35da2b788abe23233b73c5d463c0cca4b0c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt#L139)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`Json`
</blockquote></details>

This doesn't work. It tries to apply StringArrayCodec. I am assuming it can only use one codec: it can't use ArrayCodec then JsonCodec so there has to be a custom JsonArrayCodec.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621#-N6oqpPv6dZ7uHnOotSj:-N6p2Hsm1_pMitOWfpHq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdf5e35da2b788abe23233b73c5d463c0cca4b0c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the `bind` overloads for `InternalId` and `ExternalId` to keep the specific types as long as possible.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621#-N6or6Re2rXanHBbciCS:-N6p2IWCBXoj6hyROwkF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdf5e35da2b788abe23233b73c5d463c0cca4b0c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Extract an `insertReportingSet` function, as that will make it more clear that this is method is doing two things: inserting the reporting set, then inserting the corresponding event groups.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621#-N6ooxV4CtIN_uKT7HyG:-N6p2JO33Q31ponJZ9n9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdf5e35da2b788abe23233b73c5d463c0cca4b0c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This seems rather unnecessary as it appears to only be removing one reference. In general, only use scope functions when they improve readability.

```kotlin
      try {
        transactionContext.executeStatement(statement)
      } catch (e: R2dbcDataIntegrityViolationException) {
        throw ReportingSetAlreadyExistsException()
      }
      coroutineScope {
        for (eventGroupKey in request.eventGroupsKeysList) {
          launch { insertReportingSetEventGroup(eventGroupKey, internalReportingSetId) }
        }
      }
```



</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/ReportingInternalException.kt` line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621#-N6orZgB2VqhpxG4E8rD:-N6qH9602O2wW-JY8_hb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdf5e35da2b788abe23233b73c5d463c0cca4b0c/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/ReportingInternalException.kt#L84)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add a TODO to specify the appropriate context when each of these exceptions is thrown.

Make sure to avoid leaking any internal IDs.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt` line 139 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621#-N6onlQDCIby4pFLwEF5:-N6sgEn-231IXZ9xyxpn:bz7rfni) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdf5e35da2b788abe23233b73c5d463c0cca4b0c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt#L139)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This doesn't work. It tries to apply StringArrayCodec. I am assuming it can only use one codec: it can't use ArrayCodec then JsonCodec so there has to be a custom JsonArrayCodec.
</blockquote></details>

That's unfortunate :(. I guess it makes sense, as Java immediately loses the type information for the nested type param.

r2dbc definitely needs a better way of handling nested structures/collections.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621#-N6sjegD1XSVn-cWkITb:-N6sjegD1XSVn-cWkITc:b-er5nld) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5bb3af29b5c1b7ef026e4dc1132cd9230766e4cf/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L40)):*
nit: from the [Kotlin Coding Conventions](https://kotlinlang.org/docs/coding-conventions.html#loops-on-ranges), which we look to when the [Kotlin Style Guide](https://developer.android.com/kotlin/style-guide) is ambiguous:

> Prefer using higher-order functions (filter, map etc.) to loops. Exception: forEach (prefer using a regular for loop instead, unless the receiver of forEach is nullable or forEach is used as part of a longer call chain).

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 6 of 9 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/621)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
