### PR TITLE
Add Manual Instrumentation of Metrics to Mill

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730)* status: all files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021)

___
*[`imports/java/io/opentelemetry/sdk/BUILD.bazel` line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFEtNndD6SSOQVaYckJ:-NFEtNndD6SSOQVaYckK:b-1pycus) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76581db4e7aa0b837e93e40f7f203655c236d485/imports/java/io/opentelemetry/sdk/BUILD.bazel#L4)):*
Make sure these all match the Java package. Copying from a comment on another PR:

> * If a Maven artifact is the only one which includes symbols for a given Java package, we put the target in the BUILD file under the Bazel package path that matches the Java package and give the target the same name as the Bazel package.
> * If there are multiple Maven artifacts that include symbols from the same Java package, then the target for each artifact should be in the BUILD file under the Bazel package path that matches the lowest common Java package. The target name generally references the artifact name in some way, and does not take on the name of the Bazel package.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 175 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFEzarU4NDpdyTPqyG5:-NFEzarU4NDpdyTPqyG6:b-stzaky) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76581db4e7aa0b837e93e40f7f203655c236d485/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L175)):*
> ```Kotlin
> 
>       processComputation(token)
>       stageWallClockDurationHistogram.record(timeMark.elapsedNow().toDouble(DurationUnit.SECONDS))
> ```

Why not just merge this into the logger classes, changing their implementations to use TimeSource? Then metrics get recorded and logged in the same place.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt` line 157 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFEzrt2B9mOsjdfpORa:-NFEzrt2B9mOsjdfpORb:bp1rnvd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76581db4e7aa0b837e93e40f7f203655c236d485/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L157)):*
> ```Kotlin
> 
>   private val initializationPhaseCryptoCpuTimeDurationHistogram: DoubleHistogram =
>     meter.histogramBuilder("initialization_phase_crypto_cpu_time_duration_seconds").build()
> ```

Why are we recording in seconds rather than ms like we do for logging? Is that granularity just observed to be too small?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt` line 133 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFEyCvq9oV7IRf7HTgQ:-NFEyCvq9oV7IRf7HTgR:b-yjqtbu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76581db4e7aa0b837e93e40f7f203655c236d485/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt#L133)):*
> ```Kotlin
> 
>     val otlpEndpoint: String? = System.getenv(OTEL_EXPORTER_OTLP_ENDPOINT)
>     val otelServiceName: String? = System.getenv(OTEL_SERVICE_NAME)
> ```

I made a comment when millId was added that unfortunately didn't make it before merging.

We should only be using environment variables for code we can't control that reads them. Otherwise, these should all be command line options. The options can be set using existing K8s environment variables if those exist.



_Code quote:_
```Kotlin
    val otlpEndpoint: String? = System.getenv(OTEL_EXPORTER_OTLP_ENDPOINT)
    val otelServiceName: String? = System.getenv(OTEL_SERVICE_NAME)
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt` line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFEyvDWA3d0k1NuYRzJ:-NFEyvDWA3d0k1NuYRzK:b-sxxxju) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76581db4e7aa0b837e93e40f7f203655c236d485/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt#L158)):*
> ```Kotlin
>               View.builder()
>                 .setAggregation(
>                   Aggregation.explicitBucketHistogram(
> ```

Is there not a way to get automatic buckets? e.g. specifying we want X buckets using doubling



_Code quote:_
```Kotlin
explicitBucketHistogram
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730)* status: all files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFF-7W94p60S3b7Ks9h:-NFF-7W94p60S3b7Ks9i:b2hfano) (no related file):*
Adding @matthewclegg since this affects the Duchy.

___

**Comment by tristanvuong2021** [comment]
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt` line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFEyvDWA3d0k1NuYRzJ:-NFFAXdf7qCP2ifayg8K:b1ozzlx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76581db4e7aa0b837e93e40f7f203655c236d485/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt#L158)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is there not a way to get automatic buckets? e.g. specifying we want X buckets using doubling
</blockquote></details>

The default is exponential buckets, but you don't get any control over the strategy. I will run it with millisecond times and see what buckets I get after a bunch of readings.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730)* status: 8 of 17 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`imports/java/io/opentelemetry/sdk/BUILD.bazel` line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFEtNndD6SSOQVaYckJ:-NFFG5aI-8aeLdjnwLwr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76581db4e7aa0b837e93e40f7f203655c236d485/imports/java/io/opentelemetry/sdk/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Make sure these all match the Java package. Copying from a comment on another PR:

> * If a Maven artifact is the only one which includes symbols for a given Java package, we put the target in the BUILD file under the Bazel package path that matches the Java package and give the target the same name as the Bazel package.
> * If there are multiple Maven artifacts that include symbols from the same Java package, then the target for each artifact should be in the BUILD file under the Bazel package path that matches the lowest common Java package. The target name generally references the artifact name in some way, and does not take on the name of the Bazel package.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt` line 157 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFEzrt2B9mOsjdfpORa:-NFFG75F7bdz-0nZGHPH:b-wulzna) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76581db4e7aa0b837e93e40f7f203655c236d485/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L157)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why are we recording in seconds rather than ms like we do for logging? Is that granularity just observed to be too small?
</blockquote></details>

Switch to milliseconds, could just do math to get seconds.

**Comment by tristanvuong2021** [comment]
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt` line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFEyvDWA3d0k1NuYRzJ:-NFFR8aZ9iZxGjT8ZdAQ:b-utwksh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76581db4e7aa0b837e93e40f7f203655c236d485/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt#L158)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The default is exponential buckets, but you don't get any control over the strategy. I will run it with millisecond times and see what buckets I get after a bunch of readings.
</blockquote></details>

I did some research. OpenTelemetry has exponential histogram buckets, but Prometheus is still working on their equivalent, sparse histograms. Prometheus only supports explicit buckets for now, but the sparse histogram branch is in active development.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730)* status: 6 of 18 files reviewed, 4 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 175 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFEzarU4NDpdyTPqyG5:-NFFasZeEHz_M2tERD_k:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76581db4e7aa0b837e93e40f7f203655c236d485/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L175)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why not just merge this into the logger classes, changing their implementations to use TimeSource? Then metrics get recorded and logged in the same place.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt` line 133 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFEyCvq9oV7IRf7HTgQ:-NFFn3005ZF3xd5bfJCM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76581db4e7aa0b837e93e40f7f203655c236d485/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt#L133)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I made a comment when millId was added that unfortunately didn't make it before merging.

We should only be using environment variables for code we can't control that reads them. Otherwise, these should all be command line options. The options can be set using existing K8s environment variables if those exist.
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730)* status: 6 of 18 files reviewed, 4 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt` line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFEyvDWA3d0k1NuYRzJ:-NFLQarK8yyT_yaWYZxL:btp0ak2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76581db4e7aa0b837e93e40f7f203655c236d485/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt#L158)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I did some research. OpenTelemetry has exponential histogram buckets, but Prometheus is still working on their equivalent, sparse histograms. Prometheus only supports explicit buckets for now, but the sparse histogram branch is in active development.
</blockquote></details>

Sparse histograms have been added to Prometheus, but a release hasn't been cut yet, and OpenTelemetry still needs to add the conversion for their exponential histograms to Prometheus sparse histograms. Using explicit buckets for now.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r3, 1 of 5 files at r5, 3 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillFlags.kt` line 110 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFj32xI9Us3Lke94r3l:-NFj32xI9Us3Lke94r3m:b-ol4if0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af5805eb3972cba4406ecce0b55f77dcc1330b22/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillFlags.kt#L110)):*
> ```Kotlin
>       names = ["--otel-exporter-otlp-endpoint"],
>       description = ["Endpoint for OpenTelemetry Collector."],
>       required = true,
> ```

The code treats this as effectively not required. Would be clearer to do required=false with no default value and have it be nullable instead.

```kotlin
var  otelExporterOtlpEndpoint: String? = null
  private set
```



_Code quote:_
```Kotlin
      required = true,
      defaultValue = ""
```

**Comment by tristanvuong2021** [comment]
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillFlags.kt` line 110 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFj32xI9Us3Lke94r3l:-NFj7jPuA5Ev9AKReo_W:b-llh6hd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af5805eb3972cba4406ecce0b55f77dcc1330b22/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillFlags.kt#L110)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The code treats this as effectively not required. Would be clearer to do required=false with no default value and have it be nullable instead.

```kotlin
var  otelExporterOtlpEndpoint: String? = null
  private set
```
</blockquote></details>

I am adding a comment and making it nullable, but the required here should be true. It is part of an ArgGroup so making it both options required here means either all options are required to be set or none at all.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillFlags.kt` line 110 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730#-NFj32xI9Us3Lke94r3l:-NFj8fUL9bh7EFElQpcy:bbe47vp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af5805eb3972cba4406ecce0b55f77dcc1330b22/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillFlags.kt#L110)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I am adding a comment and making it nullable, but the required here should be true. It is part of an ArgGroup so making it both options required here means either all options are required to be set or none at all.
</blockquote></details>

Sorry, I missed that.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 6 of 13 files at r1, 7 of 9 files at r3, 1 of 5 files at r5, 2 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/730)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Pull request merged**
