### PR TITLE
Update integration tests to verify direct measurement results

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1212)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1212** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1212" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1212?utm_source=stack-comment).

**Review by SanjayVas — COMMENTED** [review]
> Add integration tests for direct measurements.

nit: technically this isn't adding integration tests for direct measurements, but rather updating integration tests to verify direct methodologies.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1212#-:-Ne5NRYx5LrJunT_5MWH:bxezjqh)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 240 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1212#-Ne5Mmhu5Uci7IyLcQP4:-Ne5Mmhu5Uci7IyLcQP5:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75fb61aff7404707eaed5fbbd3141753cc2f6297/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L240)):*
> ```Kotlin
>           reachAndFrequencyResult.reach.noiseMechanism == NoiseMechanism.CONTINUOUS_GAUSSIAN
>       )
>       .isTrue()
> ```





_Suggestion:_
```Kotlin
    assertThat(reachAndFrequencyResult.reach.noiseMechanism)
      .isIn(listOf(NoiseMechanism.CONTINUOUS_LAPLACE, NoiseMechanism.CONTINUOUS_GAUSSIAN))
```

**Review by riemanli — COMMENTED** [review]
Thanks for the suggestion. Updated the title to reflect the real change.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1212#-:-Ne6mj8BAs5dNMc0vbl0:b-357ic7)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 240 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1212#-Ne5Mmhu5Uci7IyLcQP4:-NeAV5iC-glIuEZ226DO:btuy6tr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75fb61aff7404707eaed5fbbd3141753cc2f6297/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L240)):*
> ```Kotlin
>           reachAndFrequencyResult.reach.noiseMechanism == NoiseMechanism.CONTINUOUS_GAUSSIAN
>       )
>       .isTrue()
> ```

Based on an offline discussion, we made the expected direct noise mechanism configurable from the constructor argument. That said, now the caller of the MC simulator needs to specified what the expected direct noise mechanism is according to their protocol config and EDP simulator setup.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1212)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1212)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/k8s/SyntheticGeneratorCorrectnessTest.kt` line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1212#-NeAZekA89oBGy4smQ_K:-NeAZekBE9NXyfRScMk1:buw6hbh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dce9004e8dda982618ae2e54c3faf6fc00bc8da4/src/test/kotlin/org/wfanet/measurement/integration/k8s/SyntheticGeneratorCorrectnessTest.kt#L47)):*
> ```Kotlin
> /**
>  * Test for correctness of an existing CMMS on Kubernetes where the EDP simulators use
>  * [SyntheticGeneratorEventQuery] with [SyntheticGenerationSpecs.POPULATION_SPEC].
> ```

I believe you need to make the same note about assuming the simulators are using ACDP composition here.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1212)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/k8s/SyntheticGeneratorCorrectnessTest.kt` line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1212#-NeAZekA89oBGy4smQ_K:-NeA_SXA3E3RF0IqHvPg:br6a2kk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dce9004e8dda982618ae2e54c3faf6fc00bc8da4/src/test/kotlin/org/wfanet/measurement/integration/k8s/SyntheticGeneratorCorrectnessTest.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe you need to make the same note about assuming the simulators are using ACDP composition here.
</blockquote></details>

Thanks for catching that! Added.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Pull request merged**
