### PR TITLE
Adding show report skeleton to UI

### PR DESCRIPTION
**Pull request by bdomen-ggl**
Adding the core pieces for the show report view.
Will add the actual UI components in the next PR since there's quite a few.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1198)

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1198)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/view/show_report/show_report_view.tsx` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1198#-NdGoF803HzzrV8vGQuq:-NdGoF803HzzrV8vGQur:b2okbay) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64d1938c9a84bfb56e0f5129282e40d2cbcfc512/experimental/reporting-ui/src/main/react/reporting-ui/view/show_report/show_report_view.tsx#L43)):*
> ```XML
> 
>   if (TERMINAL_STATES.includes(report.status)) {
>     return <div>{report.name}</div>
> ```

Will add the components to render the report and update the UI model in the next PR.

We don't currently have designs for the other cases (error, loading, and a non-completed report).

**Review by SanjayVas — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1198)* status: all files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl and @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/view/show_report/show_report_view.tsx` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1198#-NdHmErj9HJ6r_lvOndb:-NdHmErj9HJ6r_lvOndc:bl15a5q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64d1938c9a84bfb56e0f5129282e40d2cbcfc512/experimental/reporting-ui/src/main/react/reporting-ui/view/show_report/show_report_view.tsx#L22)):*
> ```XML
> import { TERMINAL_STATES } from '../../model/reporting';
> 
> export const ShowReportView = () => {
> ```

nit: Why the "Show"? Why not just `ReportView`?



_Code quote:_
```XML
ShowReportView
```

**Review by SanjayVas — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1198)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/view/show_report/show_report_view.tsx` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1198#-NdHmErj9HJ6r_lvOndb:-NdacFiP8U45-iocgcAN:buck52a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64d1938c9a84bfb56e0f5129282e40d2cbcfc512/experimental/reporting-ui/src/main/react/reporting-ui/view/show_report/show_report_view.tsx#L22)):*
> Or you mean like JUST "ReportView" and "ReportViewModel" without an additional description to Report? I can do that.

Yes. `ReportView` meaning the view for a single Report. We could rename to add other modifiers if end up with multiple views for a single Report, e.g. `ReportSummaryView` and `ReportDetailsView`.

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1198)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/view/show_report/show_report_view.tsx` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1198#-NdHmErj9HJ6r_lvOndb:-Ndafs5Y61zsUc12-rkF:belavxt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/64d1938c9a84bfb56e0f5129282e40d2cbcfc512/experimental/reporting-ui/src/main/react/reporting-ui/view/show_report/show_report_view.tsx#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Or you mean like JUST "ReportView" and "ReportViewModel" without an additional description to Report? I can do that.

Yes. `ReportView` meaning the view for a single Report. We could rename to add other modifiers if end up with multiple views for a single Report, e.g. `ReportSummaryView` and `ReportDetailsView`.
</blockquote></details>

Done.

Sorry, forgot to publish.

**Pull request merged**
