### PR TITLE
Delete legacy kingdom codes.

### PR DESCRIPTION
**Pull request by wangyaopw**
The majoritoy of these codes should be deleted.
Some of them can be updated and reused. However, updating them takes
long time. It may be easier to delete them and rewrite when needed.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
Those test related code might be useful, but they need significant amount of updates to make them build. Better just get rid of them for now. We can copy/paste/fix them form milestone0 branch when we add integrationTest for v2alpha.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-:-MgT67id1M8AMNJOGxed:b-bmw2hu)* status: 0 of 147 files reviewed, all discussions resolved (waiting on @efoxepstein and @SanjayVas)

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 95 of 147 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)* status: 95 of 147 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 28 of 147 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)* status: 123 of 147 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-Mgfns391Q5JFQhGQ0tG:-Mgfns391Q5JFQhGQ0tH:bf2znyf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5a3ee279a49bc713c1d3d879736cff07daa45ff/src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt#L136)):*
> ```Kotlin
>  * forcing indexes.
>  */
> fun StreamRecurringExchangesFilter.hasDataProviderFilter(): Boolean {
> ```

Isn't this still in use? This isn't legacy
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdomAndDuchyIntegrationTestBase.kt, line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-Mgfoa9Z7K_COO9PGbXu:-Mgfoa9Z7K_COO9PGbXv:b9qlpf0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5a3ee279a49bc713c1d3d879736cff07daa45ff/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdomAndDuchyIntegrationTestBase.kt#L0)):*
Is this test still running? Do we have some other similar test?
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRecurringExchangesServiceTest.kt, line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-Mgfoi-A98dyaEqSbs9x:-Mgfoi-B3YHv2jDW1b4m:b-3z9lud) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5a3ee279a49bc713c1d3d879736cff07daa45ff/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRecurringExchangesServiceTest.kt#L0)):*
Why is this being deleted? `SpannerRecurringExchangesService` is new

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 24 of 147 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriterTest.kt, line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-MgfpYIG9_5muSZCN7Ti:-MgfpYIG9_5muSZCN7Tj:bhv7h8p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5a3ee279a49bc713c1d3d879736cff07daa45ff/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriterTest.kt#L0)):*
We might want to keep this around as it's testing a library that's heavily used?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)* status: 131 of 147 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-Mgfns391Q5JFQhGQ0tG:-Mgfvn4559Ro8A0c_DVG:bhjqcac) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5a3ee279a49bc713c1d3d879736cff07daa45ff/src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt#L136)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Isn't this still in use? This isn't legacy
</blockquote></details>

yep. It is not deleted.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdomAndDuchyIntegrationTestBase.kt, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-Mgfoa9Z7K_COO9PGbXu:-Mgg5MZl9cEXHS7r1P4x:bksajx1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5a3ee279a49bc713c1d3d879736cff07daa45ff/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdomAndDuchyIntegrationTestBase.kt#L)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is this test still running? Do we have some other similar test?
</blockquote></details>

No, all tests inside are broken and are ignored currently.

The plan is to add a similar one back later.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriterTest.kt, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-MgfpYIG9_5muSZCN7Ti:-Mgg5fKq8apDKSvKbDj2:b-iwda8k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5a3ee279a49bc713c1d3d879736cff07daa45ff/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriterTest.kt#L)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We might want to keep this around as it's testing a library that's heavily used?
</blockquote></details>

Added back
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRecurringExchangesServiceTest.kt, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-Mgfoi-A98dyaEqSbs9x:-Mgg5hPWByIBeMxfEzZF:bxn81hk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5a3ee279a49bc713c1d3d879736cff07daa45ff/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRecurringExchangesServiceTest.kt#L)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why is this being deleted? `SpannerRecurringExchangesService` is new
</blockquote></details>

Must due to Friday afternoon accident.

Added back

**Review by efoxepstein — APPROVED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-Mgfns391Q5JFQhGQ0tG:-Mgg5u6O5JYro3nEDeDP:b-ixoa3h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5a3ee279a49bc713c1d3d879736cff07daa45ff/src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt#L136)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

yep. It is not deleted.
</blockquote></details>

Oh weird, Reviewable definitely confused me

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 131 of 147 files at r1, 16 of 16 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-MggCA4pA9sRCwV7cAR7:-MggCA4pA9sRCwV7cAR8:b-ahijta) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71f4416e56a9add36d01fb509ee313a69bc60685/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L1)):*
> ```Kotlin
> // Copyright 2020 The Cross-Media Measurement Authors
> ```

This whole file should eventually go away once the panel exchange tests are no longer depending on it.

@efoxepstein 
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriterTest.kt, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-MggDQ2NBCL0Ac04BjZi:-MggDQ2NBCL0Ac04BjZj:b-9ozsdv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71f4416e56a9add36d01fb509ee313a69bc60685/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriterTest.kt#L34)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> class SpannerWriterTest : KingdomDatabaseTestBase() {
> ```

Would you mind adding a TODO here to have this use some toy schema rather than the Kingdom one?

Eventually, the readers/writers should be treated as generic Spanner infra and moved out of the kingdom package tree.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-MggCA4pA9sRCwV7cAR7:-MggGQgBAtKtTpAi_xNT:b660tp3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71f4416e56a9add36d01fb509ee313a69bc60685/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This whole file should eventually go away once the panel exchange tests are no longer depending on it.

@efoxepstein 
</blockquote></details>

Agreed. @yunyeng will take care of deleting this one once we implement a few more internal services. Free free to drop in a TODO here for Yunus.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)* status: 146 of 147 files reviewed, all discussions resolved (waiting on @corbantek, @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-MggCA4pA9sRCwV7cAR7:-MggiaEo3yq8SIEf699b:b-iwmm5x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71f4416e56a9add36d01fb509ee313a69bc60685/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Agreed. @yunyeng will take care of deleting this one once we implement a few more internal services. Free free to drop in a TODO here for Yunus.
</blockquote></details>

Added TODO
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriterTest.kt, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187#-MggDQ2NBCL0Ac04BjZi:-MgghuoZ7ICjXIdFyM61:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71f4416e56a9add36d01fb509ee313a69bc60685/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriterTest.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Would you mind adding a TODO here to have this use some toy schema rather than the Kingdom one?

Eventually, the readers/writers should be treated as generic Spanner infra and moved out of the kingdom package tree.
</blockquote></details>

Done

**Review by corbantek — APPROVED** [review]
> Reviewed 129 of 147 files at r1, 7 of 16 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Comment by wangyaopw** [comment]
@yunyeng @uakyol since you are touching the kingdom code base.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/187)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
