### PR TITLE
update initial support for population measurement type

### PR DESCRIPTION
**Pull request by stevenwarejones**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 20 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159)* status: all files reviewed, 3 unresolved discussions (waiting on @riemanli and @stevenwarejones)

___
*[`build/repositories.bzl` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159#-Nbp6jSw-dt3gWgWKWkE:-Nbp6jSw-dt3gWgWKWkF:b66bscd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96efbe277fab55edc15131cd500a3490a0a6a1e/build/repositories.bzl#L41)):*
> ```Starlark
>     )
> 
>     # TODO: Update before merging
> ```

nit: reference the PR so it's easy to spot where this came from



_Suggestion:_
```Starlark
# DO_NOT_SUBMIT(world-federation-of-advertisers/cross-media-measurement-api#XXX): Use version
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 875 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159#-Nbp8Q9_89r2zkjEyWBT:-Nbp8Q9_89r2zkjEyWBU:be0g0d8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96efbe277fab55edc15131cd500a3490a0a6a1e/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L875)):*
> ```Kotlin
>     return dataProviderEntry {
>       val requisitionSpec = requisitionSpec {
>         events =
> ```

The main point of marking the field as deprecated (rather than deleting it) is to avoid breaking existing EDPs. Therefore we need to temporarily populate both the deprecated field and its replacement. This applies here and in the Reporting implementation.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt` line 419 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159#-Nbp76LO114zsicAkSRH:-Nbp76LO114zsicAkSRI:b-exgw3x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96efbe277fab55edc15131cd500a3490a0a6a1e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt#L419)):*
> ```Kotlin
>   ): CreateComputationLogEntryRequest {
>     return CreateComputationLogEntryRequest.newBuilder()
>       .apply {
> ```

Why was this switched to use the old Java builders rather than Kotlin DSL builders?

It looks like the old code had a bug where it was building the submessages but never assigning them to the parent message.

**Review by riemanli — COMMENTED** [review]
> Reviewed 6 of 20 files at r1, 11 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 766 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159#-NbpGECc7w2TC9pyxAds:-NbpGECd5jZQ3kQzmq30:buuuine) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96efbe277fab55edc15131cd500a3490a0a6a1e/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L766)):*
> ```Kotlin
>         MeasurementSpec.MeasurementTypeCase.IMPRESSION,
>         MeasurementSpec.MeasurementTypeCase.DURATION,
>         MeasurementSpec.MeasurementTypeCase.POPULATION, -> {}
> ```

Looks like we want to merge this PR before the [my API change PR](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/163) and its implementation #1154. We should discuss what makes sense to do for this population result when direct methodology is enforced.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159)* status: 17 of 22 files reviewed, 3 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 875 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159#-Nbp8Q9_89r2zkjEyWBT:-NbuQ_QK-V1FvMLZoiCH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96efbe277fab55edc15131cd500a3490a0a6a1e/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L875)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The main point of marking the field as deprecated (rather than deleting it) is to avoid breaking existing EDPs. Therefore we need to temporarily populate both the deprecated field and its replacement. This applies here and in the Reporting implementation.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt` line 419 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159#-Nbp76LO114zsicAkSRH:-NbuQZbJ0JXRBdr39Hra:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96efbe277fab55edc15131cd500a3490a0a6a1e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt#L419)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why was this switched to use the old Java builders rather than Kotlin DSL builders?

It looks like the old code had a bug where it was building the submessages but never assigning them to the parent message.
</blockquote></details>

Done.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159)* status: 15 of 22 files reviewed, 3 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 766 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159#-NbpGECc7w2TC9pyxAds:-NbuaXIe-ZqxmVEjP8Pj:bb7ohn6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96efbe277fab55edc15131cd500a3490a0a6a1e/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L766)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Looks like we want to merge this PR before the [my API change PR](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/163) and its implementation #1154. We should discuss what makes sense to do for this population result when direct methodology is enforced.
</blockquote></details>

sgtm

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

**Review by riemanli — APPROVED** [review]
> Reviewed 1 of 20 files at r1, 1 of 15 files at r2, 5 of 5 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1159)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
