### PR TITLE
Revoke NONE type of noise mechanism in protocol config

### PR DESCRIPTION
**Pull request by riemanli**
Implementation of the API change in https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/173.

### CODE REVIEW

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1226** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1226" target="_blank">Graphite</a> 
    * **PR #1233** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1233" target="_blank">Graphite</a>  👈
    * **PR #1184** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1184" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1233?utm_source=stack-comment).

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1233)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1233)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1233)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1233#-NenKzIrCheFZuSgpUKz:-NenKzIs46WWkLAidu5T:b77t3ix) (no related file):*
I assume we're dropping this PR due to the fact that TV EDPs are expected to not add noise? See discussion on https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/173

___

**Comment by riemanli** [comment]
Closed this PR as its API PR is closed. See https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/173 for more details.

**Pull request closed without merging**
