### PR TITLE
Add metrics for HMSS mill.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1633)

**Review by SanjayVas — COMMENTED** [review]
Would you mind rebasing this on #1623 ? That makes significant changes to how we do metrics.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1633#-:-NzZndBN4i7RXdsxPTvY:bcdbyim)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by renjiezh — COMMENTED** [review]
I will sync with that PR once it is merged. Thanks!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1633#-:-Nz_-5iB6z2Vh82_YCAu:bgy1kw6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1633)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13, @renjiezh, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 451 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1633#-O-DubiE5Ox1wBf9Ww8t:-O-DubiE5Ox1wBf9Ww8u:b6mk1xv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cb3bd9474eda82feb3f9bb6733bac8b0052dc58f/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L451)):*
> ```Kotlin
>     logWallClockDuration(
>       token,
>       DATA_TRANSMISSION_WALL_CLOCK_DURATION,
> ```

nit: this is not technically data transmission time but rather RPC time, of which data transmission is a component. This includes whatever processing the server is doing for this call.

**Review by ple13 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1633)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1633)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @tristanvuong2021)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1633)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
