### PR TITLE
Use new build targets for release workflows.

### PR DESCRIPTION
**Pull request by SanjayVas**
* //src/main/docker:push_all_gke_images target for push image workflow
* Kustomize-based targets for K8s workflows.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/965)

**Comment by SanjayVas** [comment]
Depends on #948

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/965)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/965)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`.github/workflows/configure-kingdom.yml` line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/965#-NTx_xUt0QQffLWErInr:-NTx_xUu7e6AiZSvFzmn:b-9i71ct) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69d405bc4a6531b2bcb2a26b1de3c725b5f5090a/.github/workflows/configure-kingdom.yml#L110)):*
> ```YAML
>         uses: google-github-actions/get-gke-credentials@v1
>         with:
>           cluster_name: kingdom
> ```

you want this fixed?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/965)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`.github/workflows/configure-kingdom.yml` line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/965#-NTx_xUt0QQffLWErInr:-NTygmwQ0kv6JmDsLcbC:bkkab5q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69d405bc4a6531b2bcb2a26b1de3c725b5f5090a/.github/workflows/configure-kingdom.yml#L110)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you want this fixed?
</blockquote></details>

It simplifies things to have the cluster names be static. We don't plan to put more than one Kingdom cluster in the QA/nightly cloud projects. I just recreated the cluster in halo-cmm-dev to match this name.

This is consistent with how we use static cluster names for the Duchies as well (worker1_duchy, worker2_duchy, aggregator_duchy).

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/965)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
