### PR TITLE
Implement v2alpha public API MeasurementConsumers service.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)

### CODE REVIEW

**Comment by SanjayVas** [comment]
GitHub unfortunately doesn't pick it up, but the new service and test are copied from DataProviders service and switched over with find-and-replace.

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-:-MfYpNuJ8cnW-E3kM18i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn, @stevenwarejones, and @zachcwc)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[WORKSPACE, line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcQhdPB23kr5aWxjPs:-MfcQhdPB23kr5aWxjPt:bll0lsr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/WORKSPACE#L91)):*
> ```Starlark
>     repo = "common-jvm",
>     sha256 = "6778aa7cfb009cd94af138fa051c17d9cc5e986c96f83bb378d14f96a31fa873",
>     version = "0.1.0",
> ```

are we going to start enforcing major.minor.patch on just common or all repos?
___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-MfcPxjiCDI83fpmxI2O:br7nu9l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
> ```Starlark
>     else:
>         fail("version or commit must be specified")
> ```

can you make the hash required?
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt, line 205 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcQZT39N_DQU3ivF5g:-MfcQZT40bs2UdbY4E3b:b-x407nd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt#L205)):*
> ```Kotlin
>     init {
>       val pemPath: Path = checkNotNull(getRuntimePath(TESTDATA_DIR.resolve("server.pem")))
>       serverCertificate = readCertificate(pemPath.toFile())
> ```

do you want to pull these in from common?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @stevenwarejones, and @zachcwc)

___
*[WORKSPACE, line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcQhdPB23kr5aWxjPs:-MfcypTXBvMdUi__j6_d:b-vynwvk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/WORKSPACE#L91)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are we going to start enforcing major.minor.patch on just common or all repos?
</blockquote></details>

I think we should switch to using releases with SemVer, especially since it's easier to tell what's happening in code review. That said, not doing a blanket migration or enforcement just yet.
___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-MfczbfH2plJAtPBlm6D:b-ayih9c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you make the hash required?
</blockquote></details>

I went back-and-forth on this one. I agree that we should have the sha256 specified for all archives before submitting. There are two reasons I left is as optional in this macro:
1. It's not required by `http_archive`, so it's a bit of inconsistent enforcement.
2. The easiest way to get the hash when updating an archive is to leave it off and build, then copy it from the warning that Bazel shows.

That said, I don't have a strong feeling about this and will change it if you do.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt, line 205 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcQZT39N_DQU3ivF5g:-Mfd0ZsN1-OjqFFUBUqj:b-7oerta) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt#L205)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you want to pull these in from common?
</blockquote></details>

They don't exist yet in common-jvm v0.1.0. Once https://github.com/world-federation-of-advertisers/common-jvm/pull/15 has been merged we can cut a new release of common-jvm and swap over.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-Mfd6rb457tGblWNa5tu:byf9ij4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I went back-and-forth on this one. I agree that we should have the sha256 specified for all archives before submitting. There are two reasons I left is as optional in this macro:
1. It's not required by `http_archive`, so it's a bit of inconsistent enforcement.
2. The easiest way to get the hash when updating an archive is to leave it off and build, then copy it from the warning that Bazel shows.

That said, I don't have a strong feeling about this and will change it if you do.
</blockquote></details>

i normally just download it myself and get the hash. Takes about 30 seconds. I do strongly like hash enforcement. If we're not going to enforce, we should just get rid of it.

1. Enforce hashes if the commit is mentioned. Optionally, in the error message include the hash for convenience.
2. If a version is mentioned, I'd prefer we just refer to the minor and automatically grab the latest patch version. If that's the case, it should throw an error if the hash is specified.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt, line 205 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcQZT39N_DQU3ivF5g:-Mfd7Q81-hcT4dctmwKL:b-f5ll67) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt#L205)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

They don't exist yet in common-jvm v0.1.0. Once https://github.com/world-federation-of-advertisers/common-jvm/pull/15 has been merged we can cut a new release of common-jvm and swap over.
</blockquote></details>

i'm fine with that

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-Mfd8sZCB6VRg9l1i_fZ:bbd4fu8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
> If we're not going to enforce, we should just get rid of it.

The issue is that we *can't* enforce it at build time unless we wrap all repository rule targets referenced by the WORKSPACE. e.g. `http_archive` doesn't require it, and the [docs](https://docs.bazel.build/versions/4.1.0/repo/http.html#http_archive-sha256) say it's optional for development purposes but is a security risk to omit it when shipping. Ideally we'd have this enforced as a GitHub workflow check, but for now we just try to catch it in code review.

As I said though, if you'd feel strongly that this macro require it despite the fact that other repo targets don't then I can make that change.

> Optionally, in the error message include the hash for convenience.

I would like to do this, but I don't think it's possible from a macro.

> If a version is mentioned, I'd prefer we just refer to the minor and automatically grab the latest patch version. If that's the case, it should throw an error if the hash is specified.

We want to always use pinned specific versions with checksum verification for all deps to ensure hermetic builds. It also serves as a mitigation so something malicious doesn't get snuck in, e.g. if a dependency GitHub account gets compromised. The only place where we use a floating release is for GitHub Actions, which aren't included in any deployable artifacts.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @zachcwc)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-MfeGdSv1WmlI0nYEhDK:b7tsjcq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> If we're not going to enforce, we should just get rid of it.

The issue is that we *can't* enforce it at build time unless we wrap all repository rule targets referenced by the WORKSPACE. e.g. `http_archive` doesn't require it, and the [docs](https://docs.bazel.build/versions/4.1.0/repo/http.html#http_archive-sha256) say it's optional for development purposes but is a security risk to omit it when shipping. Ideally we'd have this enforced as a GitHub workflow check, but for now we just try to catch it in code review.

As I said though, if you'd feel strongly that this macro require it despite the fact that other repo targets don't then I can make that change.

> Optionally, in the error message include the hash for convenience.

I would like to do this, but I don't think it's possible from a macro.

> If a version is mentioned, I'd prefer we just refer to the minor and automatically grab the latest patch version. If that's the case, it should throw an error if the hash is specified.

We want to always use pinned specific versions with checksum verification for all deps to ensure hermetic builds. It also serves as a mitigation so something malicious doesn't get snuck in, e.g. if a dependency GitHub account gets compromised. The only place where we use a floating release is for GitHub Actions, which aren't included in any deployable artifacts.
</blockquote></details>

Yes - make it mandatory please. I think that would help ensure best practices.

Why couldn't a macro download the file in question and compute the hash?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-MfeQwXo1EPODmPOJL8n:b-52ssi2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
> Yes - make it mandatory please. I think that would help ensure best practices.

Will do.

> Why couldn't a macro download the file in question and compute the hash?

Macros are evaluated during Bazel's [loading phase](https://docs.bazel.build/versions/4.1.0/skylark/concepts.html). The `http_archive` rule is what actually handles downloading the file, which it sets up to happen during the execution phase.

To do what you described, we'd need to implement our own custom repo rule that does what `http_archive` does, except tweak it to require the sha256 and output the error message during its execution phase.

**Review by zachcwc — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-MfhKi5NAidIc_HQCw1g:bebxzb3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Yes - make it mandatory please. I think that would help ensure best practices.

Will do.

> Why couldn't a macro download the file in question and compute the hash?

Macros are evaluated during Bazel's [loading phase](https://docs.bazel.build/versions/4.1.0/skylark/concepts.html). The `http_archive` rule is what actually handles downloading the file, which it sets up to happen during the execution phase.

To do what you described, we'd need to implement our own custom repo rule that does what `http_archive` does, except tweak it to require the sha256 and output the error message during its execution phase.
</blockquote></details>

yeah - thats what I was thinking. But that might be too much trouble. Just make the hash mandatory and we're good.

Actually... one more thought... how do you suggest we make version bumps mandatory? I'd prefer the build fail it the version isn't increased. In the past, I've just made it one of the github tests that reads the version from a file and compares to prior commit's version.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-MfhNTEF4g7-SShoNLOM:b-jkkexb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - thats what I was thinking. But that might be too much trouble. Just make the hash mandatory and we're good.

Actually... one more thought... how do you suggest we make version bumps mandatory? I'd prefer the build fail it the version isn't increased. In the past, I've just made it one of the github tests that reads the version from a file and compares to prior commit's version.
</blockquote></details>

There are often times where the version of a dependency cannot be upgraded until some migration is completed. Let's make sure to not cripple developer workflow by adding too many constraints and checks.

@sanjayvas the way I usually upgrade http_archives is by just changing a random character in the old SHA256 instead of deleting it. Bazel complains about the mismatch and gives the right one. This works fine if the sha256 is required. We could leverage this and set up a macro that wraps http_archive like:

```
def http_archive2(sha256, **kwargs):
  sha256 = sha256 or '0'*32  # With ridiculously high probability, this is not the SHA256 of any real archive
  http_archive(sha256=sha256, **kwargs)
```

So if you leave off the SHA256, it will use '0000000000000000000000...' and with exceedingly high probability fail and print out what the SHA256 should have been. If you provide the SHA256, it operates identically to `http_archive`.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-MfhWkvv7LXxA77AQltZ:b-t8qthg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

There are often times where the version of a dependency cannot be upgraded until some migration is completed. Let's make sure to not cripple developer workflow by adding too many constraints and checks.

@sanjayvas the way I usually upgrade http_archives is by just changing a random character in the old SHA256 instead of deleting it. Bazel complains about the mismatch and gives the right one. This works fine if the sha256 is required. We could leverage this and set up a macro that wraps http_archive like:

```
def http_archive2(sha256, **kwargs):
  sha256 = sha256 or '0'*32  # With ridiculously high probability, this is not the SHA256 of any real archive
  http_archive(sha256=sha256, **kwargs)
```

So if you leave off the SHA256, it will use '0000000000000000000000...' and with exceedingly high probability fail and print out what the SHA256 should have been. If you provide the SHA256, it operates identically to `http_archive`.
</blockquote></details>

```There are often times where the version of a dependency cannot be upgraded until some migration is completed. Let's make sure to not cripple developer workflow by adding too many constraints and checks.```

I wasn't thinking that the versions of all the repos would align. Is that what you were thinking? If they don't align, I'm not sure how I see that making a version bump mandatory adds too many constraints and checks.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-MfiALmo7auTRncwCE17:b-emewrb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
> the way I usually upgrade http_archives is by just changing a random character in the old SHA256 instead of deleting it. Bazel complains about the mismatch and gives the right one. 

That's much better than the way I've been doing it, haha.

Made the macro arg required. Punting on doing anything broad for `http_archive` for now, but it's not a bad idea. Not sure I quite understand the version bump question. Perhaps bring it up over Slack?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt, line 205 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcQZT39N_DQU3ivF5g:-MfdByf89dK08jMaIOSa:b-rwd3lg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt#L205)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'm fine with that
</blockquote></details>

Making this change.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-MfiCMoVAGpR2J2aQZYt:b-tv6en1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> the way I usually upgrade http_archives is by just changing a random character in the old SHA256 instead of deleting it. Bazel complains about the mismatch and gives the right one. 

That's much better than the way I've been doing it, haha.

Made the macro arg required. Punting on doing anything broad for `http_archive` for now, but it's not a bad idea. Not sure I quite understand the version bump question. Perhaps bring it up over Slack?
</blockquote></details>

do you want to set the hash to default value if its left out?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-MfiE3Bz9uIve3kr3qy4:b6ozx9k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you want to set the hash to default value if its left out?
</blockquote></details>

Not needed for this case. The main use would be for something that replaces `http_archive` to keep similar syntax but different semantics.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @stevenwarejones, and @zachcwc)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt, line 205 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcQZT39N_DQU3ivF5g:-MfiFEOlARbd_KHoiQ8o:b56aw9j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt#L205)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Making this change.
</blockquote></details>

Nevermind, there are other changes needed in this repo to bump the version of common-jvm enough. Saving for a separate PR.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @efoxepstein, @oliver-amzn, @stevenwarejones, and @zachcwc)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)* status: 8 of 11 files reviewed, all discussions resolved (waiting on @efoxepstein, @oliver-amzn, @stevenwarejones, and @zachcwc)

___
*[build/wfa/repositories.bzl, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166#-MfcPxjiCDI83fpmxI2N:-MfiGIfJ6uVGbDH6vN0-:b-melg8g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea47b720cf5f50c0906f0f7d00fe5eae2f2bbaac/build/wfa/repositories.bzl#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not needed for this case. The main use would be for something that replaces `http_archive` to keep similar syntax but different semantics.
</blockquote></details>

lets talk about the version bump on slack or next call

**Pull request merged**
