### PR TITLE
Move SecretSeed from database to RequisitionDetails proto.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592)* status: 5 of 24 files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592#-NwMhYK0-QFwSB_DyVoP:-NwMhYK103uo6gv6L2Bg:b92ut0x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/826c509c4a99de1dd85b360acd284357119e0cb2/src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto#L23)):*
> ```proto
> 
> // Protocol specific details in the Requisition.
> message RequisitionProtocolDetails {
> ```

Why split this out to a separate message? Is it used outside of RequisitionDetails?
___
*[`src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592#-NwMhEVk6IGR6dSZsLRP:-NwMhEVk6IGR6dSZsLRQ:b-e3uj3n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/826c509c4a99de1dd85b360acd284357119e0cb2/src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto#L57)):*
> ```proto
> 
>   // Protocol specific details in the Requisition.
>   RequisitionProtocolDetails protocol_details = 5;
> ```

I assume this hasn't been written to any DB yet (including halo-cmm-dev)? Otherwise this is not a safe change.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592)* status: 5 of 24 files reviewed, 2 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592#-NwMhYK0-QFwSB_DyVoP:-NwqHa6F3YE4J-ILs4Id:b-4d3a28) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/826c509c4a99de1dd85b360acd284357119e0cb2/src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why split this out to a separate message? Is it used outside of RequisitionDetails?
</blockquote></details>

Some database functions have it as argument. E.g. 
```
suspend fun writeRequisitionBlobPath(
    token: ComputationEditToken<ProtocolT, StageT>,
    externalRequisitionKey: ExternalRequisitionKey,
    pathToBlob: String,
    publicApiVersion: String,
    protocolDetails: RequisitionProtocolDetails? = null,
  )
```
So I extracted it out from RequisitionDetails.
___
*[`src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592#-NwMhEVk6IGR6dSZsLRP:-NwqI2JVAa3ooSqn3pBC:b-g4tjva) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/826c509c4a99de1dd85b360acd284357119e0cb2/src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I assume this hasn't been written to any DB yet (including halo-cmm-dev)? Otherwise this is not a safe change.
</blockquote></details>

Right. Nothing is written into DB for this column even in dev yet.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592)* status: 5 of 24 files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592#-NwMhYK0-QFwSB_DyVoP:-NwqKPPX7FSQhDfDKmDi:b-841jhx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/826c509c4a99de1dd85b360acd284357119e0cb2/src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto#L23)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Some database functions have it as argument. E.g. 
```
suspend fun writeRequisitionBlobPath(
    token: ComputationEditToken<ProtocolT, StageT>,
    externalRequisitionKey: ExternalRequisitionKey,
    pathToBlob: String,
    publicApiVersion: String,
    protocolDetails: RequisitionProtocolDetails? = null,
  )
```
So I extracted it out from RequisitionDetails.
</blockquote></details>

That doesn't preclude it being defined a nested type, e.g. `protocolDetails: RequisitionDetails.Protocol? = null,`. The main reason not to do that would be if we intent to have it used inside other protobuf message types.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592)* status: 5 of 24 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592#-NwMhYK0-QFwSB_DyVoP:-NwqLLpl2okhKHdOQPk8:b-q8uv48) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/826c509c4a99de1dd85b360acd284357119e0cb2/src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That doesn't preclude it being defined a nested type, e.g. `protocolDetails: RequisitionDetails.Protocol? = null,`. The main reason not to do that would be if we intent to have it used inside other protobuf message types.
</blockquote></details>

I see. I will move it inside RequisitionDetails.

**Review by ple13 — APPROVED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592)* status: 12 of 24 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592#-NwMhYK0-QFwSB_DyVoP:-NxOHst_98P2vr9NncHG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/826c509c4a99de1dd85b360acd284357119e0cb2/src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto#L23)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I see. I will move it inside RequisitionDetails.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 8 of 24 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto` line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592#-NxOLW4-5f0GPF32nvQ-:-NxOLW400vXKIhRdXm7h:b-9daadz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/980c2827a23b83a3664f817d6d1f2e1203c723bb/src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto#L37)):*
> ```proto
> 
>   // Protocol specific details in the Requisition.
>   message RequisitionProtocolDetails {
> ```

nit: you can leave the Details suffix off these message types as they are in the context of a RequisitionDetails. By convention, the "Details" message of a DB entity is the part that we persist as a serialized message.



_Code quote:_
```proto
Details
```

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 6 of 24 files at r1, 8 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592)* status: 19 of 24 files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/duchy/computation_token.proto` line 102 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592#-NxOa8UtC12DY1G_Cuk5:-NxOa8UtC12DY1G_Cuk6:bwqs92y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/652228f4a9e6b66f7c294d09dc6fa1ffedeea1e3/src/main/proto/wfa/measurement/internal/duchy/computation_token.proto#L102)):*
> ```proto
>   // The requisition data in format of a secret seed. It is ciphertext
>   // containing a serialized `SignedMessage` message from the CMMS public API.
>   bytes secret_seed_ciphertext = 4;
> ```

whats the overall thinking of moving this to details but not other fields like path?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592)* status: 19 of 24 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/duchy/computation_token.proto` line 102 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592#-NxOa8UtC12DY1G_Cuk5:-NxOh76-8aJncIrTiIwa:b-8876sv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/652228f4a9e6b66f7c294d09dc6fa1ffedeea1e3/src/main/proto/wfa/measurement/internal/duchy/computation_token.proto#L102)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the overall thinking of moving this to details but not other fields like path?
</blockquote></details>

Good question.
Path is the core of fulfillment for both llv2 and hmss protocols. We check whether path is empty to determine the fulfillment state. It is stored as a column in database so it is hard to move.  But `registerCount`, `SecretSeed` and so on are assumed as protocol specific info stored in protobuf objects.
The external_key is fixed id so it is standalone.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 24 files at r1, 5 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1592)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
