### PR TITLE
Add missing test cases for Exchange services

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221)* status: all files reviewed, 10 unresolved discussions (waiting on @kgaynor and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStep.kt, line 46 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MiOSWCOCyW5RM72yN-F:-MiOSWCP6hk5VV49v8aN:b-n19w8g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStep.kt#L46)):*
> ```Kotlin
>   state: ExchangeStep.State
> ) {
>   if (exchangeStep.state == state) return
> ```

shouldn't we log this?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, line 98 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MiOSvE1COdg0hAo8_Nv:-MiOSvE1COdg0hAo8_Nw:b-63iqii) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt#L98)):*
> ```Kotlin
> 
> private val DATE: Date =
>   Date.newBuilder()
> ```

ditto on the builder

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r7, 4 of 13 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221)* status: 4 of 15 files reviewed, 16 unresolved discussions (waiting on @efoxepstein, @kgaynor, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt, line 1 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjWbSJcDGZqPPlxxPSx:-MjWbSJcDGZqPPlxxPSy:bkiqmlc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

This filename doesn't quite make sense to me anymore -- usually `TestBase` refers to an abstract base class
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt, line 55 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjWbFCBAlYxEkvtw-o6:-MjWbFCCCPAgnOOvv8xB:bnwcjss) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt#L55)):*
> ```Kotlin
>   )
> 
> internal suspend fun ExchangesCoroutineImplBase.getAndAssertExchange(
> ```

Maybe a better name is `assertTestExchangeHasState`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt, line 58 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjWb6_W0j6Cvpna-N19:-MjWb6_W0j6Cvpna-N1A:b-6el9vq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt#L58)):*
> ```Kotlin
>   exchangeState: Exchange.State
> ) {
>   ProtoTruth.assertThat(
> ```

please import `assertThat` itself
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt, line 76 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjWbjDFD7l_Qy694zZ6:-MjWbjDFD7l_Qy694zZ7:b-il7iwk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt#L76)):*
> ```Kotlin
> }
> 
> internal suspend fun ExchangeStepsCoroutineImplBase.getAndAssertExchangeStep(
> ```

Ditto, maybe call this `assertTestExchangeStepHasState`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt, line 101 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjWbnmpBV-2NKiRMeSb:-MjWbnmpBV-2NKiRMeSc:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt#L101)):*
> ```Kotlin
> }
> 
> internal suspend fun ExchangeStepAttemptsCoroutineImplBase.getAndAssertExchangeStepAttempt(
> ```

Ditto
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt, line 129 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjWbojJE7dYQp0xExnZ:-MjWbojJE7dYQp0xExn_:b-824810) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt#L129)):*
> ```Kotlin
> }
> 
> internal fun getModelProvider(): Provider {
> ```

This can just be a constant `val SOMETHING: Provider = ...`

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r7, 8 of 13 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221)* status: 11 of 15 files reviewed, 17 unresolved discussions (waiting on @efoxepstein, @kgaynor, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 337 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjZknCsBUbLNjtJeruU:-MjZknCsBUbLNjtJeruV:bgxr3wg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L337)):*
> ```Kotlin
>     val row: Struct = transactionContext.executeQuery(statement).single()
> 
>     // If only returns current Step still IN_PROGRESS, then done.
> ```

not sure of the grammar here and what you're meaning to say but its a little confusing to me. Do you mean `It only...`

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221)* status: 9 of 17 files reviewed, 17 unresolved discussions (waiting on @efoxepstein, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 337 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjZknCsBUbLNjtJeruU:-Mj_Jz7Q88TaMCPtMPs8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L337)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

not sure of the grammar here and what you're meaning to say but its a little confusing to me. Do you mean `It only...`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, line 98 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MiOSvE1COdg0hAo8_Nv:-Mj_K3KB5ujnn84s9C40:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt#L98)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto on the builder
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, line 211 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-Mi87k4kCROwa1K92Jr0:-Mj_K59k-Za2OwvXgQrw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt#L211)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In all of these tests, you should probably call `getExchangeStep` and `getExchangeStepAttempt` and `getExchange` to make sure all the states are correct.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, line 332 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-Mi87WYy47cSg-DasbV-:-Mj_K6FZ45j7DiRi8lFK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt#L332)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

2L here?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, line 340 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-Mi87QLr3x4Kmf5N0l2g:-Mj_K6a9ECJZfG5FJJHs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt#L340)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

2L here?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, line 362 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-Mi88xgD6zDzxadyrBa1:-Mj_K7McBpA37BnjJues:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt#L362)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe just default this to 1?

`attemptNo: Int = 1`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 231 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-Mi88EM62T81_cznF0wL:-Mj_S-y55oIAcpTADYxW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L231)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please verify that calling `claimReadyExchangeStep` again returns nothing.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 235 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-Mi8853KCjtVzbepXg5O:-Mj_S-mWEZW_AJtdrMFe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L235)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you implement this test in this PR too please?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 237 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-Mi88Ggc3tvTsNrynH6C:-Mj_R_I5D3F4VDMqgcqI:bpecn9b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L237)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please add a test for `claimReadyExchangeStep` when there's nothing ready to claim. (There should be exchange steps in other, non-ready states. One challenge: getting the exchange steps into that state.)

For now if you want, you can add TODOs here for this.
</blockquote></details>

After this PR I will send the ExchangeSteps.createExchangeStep() then we should be able to test with it. Added TODO for this PR.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 237 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-Mi88QhN9klI52In-Gde:-Mj_RZoV2iCMLCzgIoIY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L237)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please add a test to make sure it grabs `exchangeStep`s in `READY_FOR_RETRY` states. For now if you want, you can add TODOs here for this.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStep.kt, line 46 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MiOSWCOCyW5RM72yN-F:-Mj_Rkhz6Koah6gq1BVw:b-cj3bi5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStep.kt#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't we log this?
</blockquote></details>

Can I leave it to the next PR? I might write a one pager as well on things we should log. Currently, there is no logger exists in /writers
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt, line 1 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjWbSJcDGZqPPlxxPSx:-Mj_K-_vAxDu5fgtW_DP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This filename doesn't quite make sense to me anymore -- usually `TestBase` refers to an abstract base class
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt, line 55 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjWbFCBAlYxEkvtw-o6:-Mj_K0FfBRNQ_z3W9aXf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe a better name is `assertTestExchangeHasState`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt, line 58 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjWb6_W0j6Cvpna-N19:-Mj_K0fJ1nJnWk3fWpNi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt#L58)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

please import `assertThat` itself
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt, line 76 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjWbjDFD7l_Qy694zZ6:-Mj_K1JM0fA7WgkzknSf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt#L76)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto, maybe call this `assertTestExchangeStepHasState`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt, line 101 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjWbnmpBV-2NKiRMeSb:-Mj_K1pr4uhN_95vq87W:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt#L101)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt, line 129 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjWbojJE7dYQp0xExnZ:-Mj_K2fI1RXGi1_q0V6i:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeServicesTestBase.kt#L129)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This can just be a constant `val SOMETHING: Provider = ...`
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 5 files at r6, 6 of 13 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221)* status: all files reviewed, 5 unresolved discussions (waiting on @kgaynor, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 337 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjZknCsBUbLNjtJeruU:-Mj_qGE35OLD3_g_f9jE:b9o7eqj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L337)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe `Since the current step is still IN_PROGRESS, if this is 1 then after updating the current step, there will be no more incomplete steps.`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 271 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-Mj_s4djBJxjDHxfxOMB:-Mj_s4djBJxjDHxfxOMC:b-fmlpbx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3f1ddad43aea2c14c041b419bbdf78ea5588f7d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L271)):*
> ```Kotlin
>     exchangeStepAttemptsService.assertTestExchangeStepAttemptHasState(
>       ExchangeStepAttempt.State.FAILED,
>       1
> ```

can you add `attemptNumber = 1` here? (Or whatever the parameter name is called
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 275 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-Mj_s1fl5SsnTxkqMMRb:-Mj_s1fl5SsnTxkqMMRc:b-jltba6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3f1ddad43aea2c14c041b419bbdf78ea5588f7d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L275)):*
> ```Kotlin
>     exchangeStepAttemptsService.assertTestExchangeStepAttemptHasState(
>       ExchangeStepAttempt.State.ACTIVE,
>       2
> ```

can you add `attemptNumber = 2` here? (Or whatever the parameter name is called

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @kgaynor, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 337 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjZknCsBUbLNjtJeruU:-Mja0TcOA1MQk_dnIwKY:btg58fw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L337)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe `Since the current step is still IN_PROGRESS, if this is 1 then after updating the current step, there will be no more incomplete steps.`
</blockquote></details>

could you combine your current comment with Eli's?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStep.kt, line 46 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MiOSWCOCyW5RM72yN-F:-Mja0btEAhUO5OnL_v3M:b-5twdbw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStep.kt#L46)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Can I leave it to the next PR? I might write a one pager as well on things we should log. Currently, there is no logger exists in /writers
</blockquote></details>

sure, please add a TODO here at least so we don't forget about this one

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 13 files at r8, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221)* status: all files reviewed, 2 unresolved discussions (waiting on @kgaynor and @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 337 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MjZknCsBUbLNjtJeruU:-MjaI8_W4ysymOG9F6Gl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d28e699057df94e9f78ce1c153f3a83a6dc2a02a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L337)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

could you combine your current comment with Eli's?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStep.kt, line 46 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221#-MiOSWCOCyW5RM72yN-F:-MjaI9DV5K9Fy9-6b-JS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8f0ef4fa37caa7fb84299d8ed4a90c8cf9b11f2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStep.kt#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sure, please add a TODO here at least so we don't forget about this one
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221)* status: all files reviewed, 2 unresolved discussions (waiting on @kgaynor and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/221)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kgaynor)

**Pull request merged**
