### PR TITLE
Add etag validation option for internal batch measurement operations

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933)

**Review by jcorilla — COMMENTED** [review]
@tristanvuong2021, not sure if there is a better way to do this since BatchCancelMeasurements isn't merged yet. If you could look over the changes for etag implementation (the second commit), I'd appreciate it! 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-:-NSOcsHe255swmiQIhVN:bikimma)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by jcorilla — COMMENTED** [review]
> BatchCancelMeasurements was merged so all changes here are reviewable now!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-:-NSRTyHD51lUvhSwJ8Re:b-9ipulg)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933)* status: 11 of 12 files reviewed, all discussions resolved

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933)* status: all files reviewed, 3 unresolved discussions (waiting on @jcorilla)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 151 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-NSSZsdj2M6UUdLjhZnO:-NSSZsdj2M6UUdLjhZnP:bid0miw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73546eaff524c9f55245468058b5c0659c5a329f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L151)):*
> ```Kotlin
> 
> class MeasurementEtagMismatchException(
>   val internalMeasurementEtag: String,
> ```

"internal" and "provided" are a bit overloaded. Perhaps "requested" and "actual"?



_Code quote:_
```Kotlin
internalMeasurementEtag
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 154 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-NSSXShR9MKqzAe6OcAP:-NSSXShR9MKqzAe6OcAQ:b-hw29iw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73546eaff524c9f55245468058b5c0659c5a329f/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L154)):*
> ```protobuf
>   repeated ComputationParticipant computation_participants = 13;
> 
>   // Output only. A checksum computed on-demand from update time. This may be
> ```

This is an implementation detail. How the ETag is computed is irrelevant to the consumer so long as it has the following properties:
1. If the underlying entity has changed, the ETag should also have changed.
2. If the underlying entity has not changed, the ETag should not have changed.



_Code quote:_
```protobuf
A checksum computed on-demand from update time.
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-NSSYc4gE-9YvYBPvS3p:-NSSYc4gE-9YvYBPvS3q:b-n9reey) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73546eaff524c9f55245468058b5c0659c5a329f/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L111)):*
> ```protobuf
>   fixed64 external_measurement_id = 2;
> 
>   // Optional weakly validated etag computed from update time.
> ```

1. The fact that it's based on update time is an implementation detail.
2. I think it's technically using strong validation as any change to the entity should result in the update time being updated. Regardless, I don't think we need to specify the validator here as the ETag itself will indicate that if following RFC 7232.



_Code quote:_
```protobuf
weakly validated etag computed from update time.
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933)* status: all files reviewed, 3 unresolved discussions (waiting on @jcorilla)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-NSSYc4gE-9YvYBPvS3p:-NSSaKYp4Pa25S57O6S7:b-6eii7c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73546eaff524c9f55245468058b5c0659c5a329f/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L111)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. The fact that it's based on update time is an implementation detail.
2. I think it's technically using strong validation as any change to the entity should result in the update time being updated. Regardless, I don't think we need to specify the validator here as the ETag itself will indicate that if following RFC 7232.
</blockquote></details>

Sorry, ignore my advice on weakly validated. I saw that AIP-154 makes this clear.

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933)* status: 6 of 12 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 151 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-NSSZsdj2M6UUdLjhZnO:-NSvh2He7q443m5bHsRa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce8ace76a8b7420c9cb250d7f10cb57c6eba160f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L151)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

"internal" and "provided" are a bit overloaded. Perhaps "requested" and "actual"?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 154 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-NSSXShR9MKqzAe6OcAP:-NSvh1Nr75frIY8aoOpa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce8ace76a8b7420c9cb250d7f10cb57c6eba160f/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L154)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is an implementation detail. How the ETag is computed is irrelevant to the consumer so long as it has the following properties:
1. If the underlying entity has changed, the ETag should also have changed.
2. If the underlying entity has not changed, the ETag should not have changed.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-NSSYc4gE-9YvYBPvS3p:-NSvgQQD6BbB6N551uOr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce8ace76a8b7420c9cb250d7f10cb57c6eba160f/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L111)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, ignore my advice on weakly validated. I saw that AIP-154 makes this clear.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r1, 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 187 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-NSwQo2L0nO0E8SnuJJB:-NSwQo2L0nO0E8SnuJJC:b-qgu55) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/412f85051a1b6298eb279c544ac55dafa8a17ace/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L187)):*
> ```Kotlin
>      * @throws [MeasurementNotFoundException] when the Measurement is not found
>      */
>     suspend fun readUpdateTimeByKey(
> ```

Let's have the methods be a public `readEtag(readContext: AsyncDatabaseClient.ReadContext, primaryKey: Key)` and a private `getEtag(updateTime)`.



_Code quote:_
```Kotlin
    /**
     * Returns a [Timestamp] for the update time of a [Measurement] specified by Measurement Key
     *
     * @throws [MeasurementNotFoundException] when the Measurement is not found
     */
    suspend fun readUpdateTimeByKey(
      readContext: AsyncDatabaseClient.ReadContext,
      measurementKey: Key
    ): Timestamp {
      val column = "UpdateTime"
      return readContext
        .readRow("Measurements", measurementKey, listOf(column))
        ?.getTimestamp(column)
        ?: throw MeasurementNotFoundException() { "Measurement not found for $measurementKey" }
    }

    fun generateEtagByUpdateTime(updateTime: Timestamp): String {
      return "W/\"${updateTime.toProto().hashCode()}\""
    }
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 199 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-NSwRiPREHJJ0wYKhg9_:-NSwRiPREHJJ0wYKhg9a:bltn9oi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/412f85051a1b6298eb279c544ac55dafa8a17ace/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L199)):*
> ```Kotlin
> 
>     fun generateEtagByUpdateTime(updateTime: Timestamp): String {
>       return "W/\"${updateTime.toProto().hashCode()}\""
> ```

This is not guaranteed to be stable across builds, nor is the binary serialization of protobufs.

You need to come up with your own deterministic encoding. e.g. the sha256 hash of the concatenation of the big endian 64-bit `seconds` and the big endian 32-bit nanos. You implement this using ByteBuffer, e.g. 

```kotlin
val buffer = ByteBuffer.allocate(8+4).order(ByteOrder.BIG_ENDIAN).putLong(seconds).putInt(nanos)..asReadOnlyBuffer()
buffer.flip()
val hash = HexString(MessageDigest.getInstance(SHA_256).apply { update(buffer) }.digest().toByteString())
```



_Code quote:_
```Kotlin
hashCode()
```

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933)* status: 5 of 12 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 187 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-NSwQo2L0nO0E8SnuJJB:-NT0UUJC6eSXs05jaGvM:b-jo9jqe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/412f85051a1b6298eb279c544ac55dafa8a17ace/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L187)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Let's have the methods be a public `readEtag(readContext: AsyncDatabaseClient.ReadContext, primaryKey: Key)` and a private `getEtag(updateTime)`.
</blockquote></details>

ReadEtag works as public when it's called for comparison in runTransaction() calls, but in buildResult() from ResultScope there doesn't seem to be access to read/transactionContext for reading in update time - so it relies on the existing commitTimeStamp to get the etag. 
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 199 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933#-NSwRiPREHJJ0wYKhg9_:-NT-n06Z1MnnG7BoGLQ4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/412f85051a1b6298eb279c544ac55dafa8a17ace/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L199)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is not guaranteed to be stable across builds, nor is the binary serialization of protobufs.

You need to come up with your own deterministic encoding. e.g. the sha256 hash of the concatenation of the big endian 64-bit `seconds` and the big endian 32-bit nanos. You implement this using ByteBuffer, e.g. 

```kotlin
val buffer = ByteBuffer.allocate(8+4).order(ByteOrder.BIG_ENDIAN).putLong(seconds).putInt(nanos)..asReadOnlyBuffer()
buffer.flip()
val hash = HexString(MessageDigest.getInstance(SHA_256).apply { update(buffer) }.digest().toByteString())
```
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 12 files at r1, 1 of 6 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 4 of 6 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by jcorilla — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, 3 of 6 files at r2, 6 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
