### PR TITLE
Add CreateModelProvider class

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/133)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/133)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelProvider.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/133#-MdSrjyyB5qD950TJ2-n:-MdSrjyyB5qD950TJ2-o:b-1osirn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a7e4eb98a62dabbf4cbd4d5a129d4b6c00601334/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelProvider.kt#L27)):*
> ```Kotlin
>     val externalId = idGenerator.generateExternalId()
>     Mutation.newInsertBuilder("ModelProviders")
>       .set("ModelProviderId")
> ```

Can you use the `set(x to y)` syntax please?
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelProviderTest.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/133#-MdSrv1Q1S6cnSgWV788:-MdSrv1Q1S6cnSgWV789:b-snmgpx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a7e4eb98a62dabbf4cbd4d5a129d4b6c00601334/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelProviderTest.kt#L36)):*
> ```Kotlin
>   @Test
>   fun success() =
>     runBlocking<Unit> {
> ```

Maybe steal this: https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/common/testing/RunBlockingTest.kt

In fact, we should pull that into `common-jvm` repo at some point.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/133)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelProvider.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/133#-MdSrjyyB5qD950TJ2-n:-MdT9XIg1xWwc2WNja93:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a7e4eb98a62dabbf4cbd4d5a129d4b6c00601334/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelProvider.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you use the `set(x to y)` syntax please?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelProviderTest.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/133#-MdSrv1Q1S6cnSgWV788:-MdT9YRF1X66O6gGsLbK:brxpixt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a7e4eb98a62dabbf4cbd4d5a129d4b6c00601334/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelProviderTest.kt#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe steal this: https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/common/testing/RunBlockingTest.kt

In fact, we should pull that into `common-jvm` repo at some point.
</blockquote></details>

Will add the file in next PR

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/133)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/133#-:-MdTCyyi9mXyF3mkmpt-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
