### PR TITLE
Migrate deps to common_cpp

### PR DESCRIPTION
**Pull request by enfreck**
Migrate /time and part of encryption_utility_helper to common_cpp

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/169)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/169#-:-Mfdqyow3ZILFE36gEsO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/169)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @oliver-amzn, and @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/169#-MfdrBX49ditv-Eaztvo:-MfdrBX5-vc19fsQAuqG:beygshh) (no related file):*
Can you change the PR title to use the imperative mood? "Migrate deps ..."

---

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/169)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck and @wangyaopw)

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/169)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/169#-MfdrBX49ditv-Eaztvo:-Mfdsua55IxyD3vlvC2L:b-896fix) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you change the PR title to use the imperative mood? "Migrate deps ..."
</blockquote></details>

Done.

---

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/169)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by wangyaopw — APPROVED** [review]

**Pull request merged**
