### PR TITLE
Update common-jvm dep for grpc-java and netty-codec-http2.

### LINKED ISSUE #1553: io.netty:netty-codec-http2 vulnerable to HTTP/2 Rapid Reset Attack
https://github.com/advisories/GHSA-xpw8-rcwv-8f8p

io.netty:netty-codec-http2 is picked up implicitly as a dependency of io.grpc:grpc-netty. Therefore the simplest path would be if we could just upgrade io.grpc:grpc-netty, which itself is a dependency of grpc-java.

- [ ] https://github.com/world-federation-of-advertisers/common-jvm/pull/241
- [ ] #1555

### PR DESCRIPTION
**Pull request by SanjayVas**
Closes #1553

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1555)

**Comment by SanjayVas** [comment]
Depends on world-federation-of-advertisers/common-jvm#241

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1555)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1555)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
