### PR TITLE
Implement Internal Report Schedules Service Create Method

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281)

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 6 of 14 files at r1, 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt` line 98 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281#-NgLNFEgEaeCIHrJTrfY:-NgLNFEgEaeCIHrJTrfZ:b-l6timl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73d21303270248d354d6ca8b38b802e375797ec1/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt#L98)):*
> ```Kotlin
>         Timestamps.compare(createdReportSchedule.createTime, createdReportSchedule.updateTime)
>       )
>       .isEqualTo(0)
> ```

How about `assertThat(createdReportSchedule.createTime.equals(createdReportSchedule.updateTime)).isTrue()`?



_Code quote:_
```Kotlin
    assertThat(
        Timestamps.compare(createdReportSchedule.createTime, createdReportSchedule.updateTime)
      )
      .isEqualTo(0)
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt` line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281#-NgLOhFrCltkW9tKFhY5:-NgLOhFsCZd2YAXwyTyk:b-5jy2v1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73d21303270248d354d6ca8b38b802e375797ec1/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt#L171)):*
> ```Kotlin
> 
>   @Test
>   fun `createReportSchedule throws NOT_FOUND when ReportingSet not found`() = runBlocking {
> ```

Is this unit test different from the one below?



_Code quote:_
```Kotlin
fun `createReportSchedule throws NOT_FOUND when ReportingSet not found`()
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt` line 392 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281#-NgLJZN_8LqhHdqL0bYS:-NgLJZN_8LqhHdqL0bYT:b-3h4ylx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73d21303270248d354d6ca8b38b802e375797ec1/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt#L392)):*
> ```Kotlin
>       return reportSchedule {
>         this.cmmsMeasurementConsumerId = CMMS_MEASUREMENT_CONSUMER_ID
>         state = ReportSchedule.State.ACTIVE
> ```

State should be unset for a requesting report schedule and be checked in the unit tests of creation.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt` line 441 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281#-NgLJmWBBP9TTVE6L3TX:-NgLJmWBBP9TTVE6L3TY:b6kkkkf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73d21303270248d354d6ca8b38b802e375797ec1/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt#L441)):*
> ```Kotlin
>               day = 1
>             }
>             frequency = ReportScheduleKt.frequency { daily = ReportScheduleKt.FrequencyKt.daily {} }
> ```

Use `getDefaultInstance()` instead



_Code quote:_
```Kotlin
ReportScheduleKt.FrequencyKt.daily {}
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt` line 98 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281#-NgLNFEgEaeCIHrJTrfY:-NgPCsvXDtG-Lcg8db-i:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e27e843120aa30b7f980e6e699d05c343b7f5d6/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt#L98)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

How about `assertThat(createdReportSchedule.createTime.equals(createdReportSchedule.updateTime)).isTrue()`?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt` line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281#-NgLOhFrCltkW9tKFhY5:-NgPKnoY35xFWk5daC2A:b-k23r64) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e27e843120aa30b7f980e6e699d05c343b7f5d6/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt#L171)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Is this unit test different from the one below?
</blockquote></details>

It is different. I made it more obvious it is different.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt` line 392 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281#-NgLJZN_8LqhHdqL0bYS:-NgPDZTg7P-6rjs35lEq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e27e843120aa30b7f980e6e699d05c343b7f5d6/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt#L392)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

State should be unset for a requesting report schedule and be checked in the unit tests of creation.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt` line 441 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281#-NgLJmWBBP9TTVE6L3TX:-NgPDfsmBQulUVTzDVXz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e27e843120aa30b7f980e6e699d05c343b7f5d6/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt#L441)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Use `getDefaultInstance()` instead
</blockquote></details>

Done.

**Review by riemanli — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt` line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281#-NgLOhFrCltkW9tKFhY5:-NgPk0zEBMLr35UFk58U:bspbavq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e27e843120aa30b7f980e6e699d05c343b7f5d6/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt#L171)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It is different. I made it more obvious it is different.
</blockquote></details>

Does the code do things differently when one reporting is not found and when all reporting sets are not found? I thought they are all caught in the code in src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportSchedule.kt

```kotlin
    if (reportingSetMap.size < externalReportingSetIds.size) {
      throw ReportingSetNotFoundException()
    }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt` line 332 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281#-NgPdREO48baCba0W1mK:-NgPdREO48baCba0W1mL:b-iipjm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30600112f017e8c2b8c017443fdd2deae69934d0/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt#L332)):*
> ```Kotlin
>             day = 1
>           }
>           frequency = ReportScheduleKt.frequency { daily = ReportScheduleKt.FrequencyKt.daily {} }
> ```

nit: ditto



_Code quote:_
```Kotlin
ReportScheduleKt.FrequencyKt.daily {}
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt` line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281#-NgLOhFrCltkW9tKFhY5:-NgPs8du8aX7KxnG3FUS:b1mt7tc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e27e843120aa30b7f980e6e699d05c343b7f5d6/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportSchedulesServiceTest.kt#L171)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Does the code do things differently when one reporting is not found and when all reporting sets are not found? I thought they are all caught in the code in src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportSchedule.kt

```kotlin
    if (reportingSetMap.size < externalReportingSetIds.size) {
      throw ReportingSetNotFoundException()
    }
```
</blockquote></details>

They are supposed to do the same thing. I have the tests to confirm that.

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281)* status: 13 of 14 files reviewed, all discussions resolved

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 6 of 14 files at r1, 6 of 8 files at r2, 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1281)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
