### PR TITLE
Configure Kingdom cluster.

### PR DESCRIPTION
**Pull request by wfa-hkawalkar**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, and @wfa-siyengar)

___
*[`.github/workflows/configure-kingdom.yml` line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NRneRRD2a6wbCD6FgAI:-NS-jot58kFhn5CtE0am:bzbiyb3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82578d04ea26d4c46d43c7cea0b9549fe4b2404d/.github/workflows/configure-kingdom.yml#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't there be a step that updates your local KUBECONFIG so that `kubectl` commands will point to the right cluster? Without this, no apply steps would work. e.g. 

```shell
gcloud container clusters get-credentials kingdom --zone us-central1-c
```

or whatever Action is the equivalent, assuming that you already have credentials for the correct project. The actual cluster name and zone will depend on what's in the Terraform configs, I assume.
</blockquote></details>

Done, we have added.
___
*[`.github/workflows/configure-kingdom.yml` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NRndwxEAR5eKwrEKSXv:-NS-jtZ5B1Etbnkl1uZQ:bd8j57o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82578d04ea26d4c46d43c7cea0b9549fe4b2404d/.github/workflows/configure-kingdom.yml#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same comment as on #920. The actual value of this comes from the "Apply secrets" step.
</blockquote></details>

We will make changes.

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, and @wfa-siyengar)

___
*[`.github/workflows/configure-kingdom.yml` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NRndq2Q3oWcZK3J1SiD:-NS-kimt14Cw9HO1hXdH:b-boiosa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82578d04ea26d4c46d43c7cea0b9549fe4b2404d/.github/workflows/configure-kingdom.yml#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same comment as on #920. This isn't needed here.
</blockquote></details>

Done.  we have removed the Github login.

**Review by wfa-siyengar — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-:-NS-nrCj-jANiOpULbLy:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl and @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)* status: all files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl and @wfa-hkawalkar)

___
*[`.github/workflows/configure-kingdom.yml` line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NRneRRD2a6wbCD6FgAI:-NS7h1oM7Xm0zKy6zlI0:bte0fhh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82578d04ea26d4c46d43c7cea0b9549fe4b2404d/.github/workflows/configure-kingdom.yml#L39)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

Done, we have added.
</blockquote></details>

Where? Is it handled by a separate workflow?
___
*[`.github/workflows/configure-kingdom.yml` line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS7gCdX0eV0D4W2lLUM:-NS7gCdX0eV0D4W2lLUN:bc6bjz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d326d0fe27e4f678d604bdbb9a195e5cb80c832/.github/workflows/configure-kingdom.yml#L18)):*
> ```YAML
> 
> on:
>   workflow_call:
> ```

I believe this needs the same inputs as the `workflow_dispatch` trigger.



_Code quote:_
```YAML
workflow_call:
```
___
*[`.github/workflows/configure-kingdom.yml` line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS7gRn0DDtr6CVnW94G:-NS7gRn0DDtr6CVnW94H:bjpk66d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d326d0fe27e4f678d604bdbb9a195e5cb80c832/.github/workflows/configure-kingdom.yml#L41)):*
> ```YAML
>         uses: actions/checkout@v2
> 
>       # TODO(wfa-hkawalkar): applying manifest failing.
> ```

Is this comment still true?

Note that if something is failing, it means that the PR isn't ready for review. It's not a valid condition for a TODO.



_Code quote:_
```YAML
# TODO(wfa-hkawalkar): applying manifest failing.
```

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl and @SanjayVas)

___
*[`.github/workflows/configure-kingdom.yml` line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NRneRRD2a6wbCD6FgAI:-NS7mIr9-wgfilQyEQqA:bwqconc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82578d04ea26d4c46d43c7cea0b9549fe4b2404d/.github/workflows/configure-kingdom.yml#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Where? Is it handled by a separate workflow?
</blockquote></details>

Apologize Sanjay, I have added the kubeconfig file with the name of the cluster.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl and @wfa-hkawalkar)

___
*[`.github/workflows/configure-kingdom.yml` line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS81efs20kGZQftR0dY:-NS81efs20kGZQftR0dZ:bbxeg2a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17528857986ed4567523d13f40ef26996c07815a/.github/workflows/configure-kingdom.yml#L46)):*
> ```YAML
>         run: bazelisk run //src/main/k8s/testing/secretfiles:apply_kustomization
> 
>       - name: Get Hash Value
> ```

This isn't right. The hash is part of the name that is generated by the "Apply secrets" step, which runs `kubectl apply` underneath. To make it easier to capture the name, you can build the tar file, extract it, and apply it yourself so that you can control the output. Something like:

```shell
bazelisk build //src/main/k8s/testing/secretfiles:kustomization.tar
mkdir secretfiles
tar -xf "$(bazelisk info bazel-bin)/src/main/k8s/testing/secretfiles/kustomization.tar" -C secretfiles
secret_name="$(kubectl apply -k secretfiles/src/main/k8s/testing/secretfiles/kustomization -o name)"
```
___
*[`.github/workflows/configure-kingdom.yml` line 58 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS81VXf7Jnh5W_nXGjK:-NS81VXf7Jnh5W_nXGjL:b-n3hay1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17528857986ed4567523d13f40ef26996c07815a/.github/workflows/configure-kingdom.yml#L58)):*
> ```YAML
>           --define image_tag=${{ inputs.image_tag }}
> 
>       - name: Adding Kubeconfig
> ```

This step needs to be before "Apply secrets", as that runs `kubectl apply` underneath.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl and @wfa-hkawalkar)

___
*[`.github/workflows/configure-kingdom.yml` line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS81efs20kGZQftR0dY:-NS85tSy6tlWrbP-Y25N:b-c0yszz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17528857986ed4567523d13f40ef26996c07815a/.github/workflows/configure-kingdom.yml#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This isn't right. The hash is part of the name that is generated by the "Apply secrets" step, which runs `kubectl apply` underneath. To make it easier to capture the name, you can build the tar file, extract it, and apply it yourself so that you can control the output. Something like:

```shell
bazelisk build //src/main/k8s/testing/secretfiles:kustomization.tar
mkdir secretfiles
tar -xf "$(bazelisk info bazel-bin)/src/main/k8s/testing/secretfiles/kustomization.tar" -C secretfiles
secret_name="$(kubectl apply -k secretfiles/src/main/k8s/testing/secretfiles/kustomization -o name)"
```
</blockquote></details>

Sorry, the value in the above example will be the full resource name e.g. `secret/certs-and-configs-4c4b9ttf29`. You'll want to run `basename` on that to get the value that's expected by later commands e.g. `certs-and-configs-4c4b9ttf29`.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl and @wfa-hkawalkar)

___
*[`.github/workflows/configure-kingdom.yml` line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS81efs20kGZQftR0dY:-NSCQ_cv5jhxsgWiNXkw:bttma92) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17528857986ed4567523d13f40ef26996c07815a/.github/workflows/configure-kingdom.yml#L46)):*
You seem to have misunderstood. The commands I gave above are a replacement for `bazelisk run //src/main/k8s/testing/secretfiles:apply_kustomization`. It's decomposing what that Bazel target does so that you can control/capture the output of `kubectl apply`.

> As cluster is not created it will not be able to apply to cluster.

Why would this be the case? If you're running this workflow directly, it's up to you to ensure the cluster already exists. If you're running it from the QA deployment workflow, then the Terraforming workflow should have already created the cluster.
___
*[`.github/workflows/configure-kingdom.yml` line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NSCROI2Ae5PXo1_tAAj:-NSCROI2Ae5PXo1_tAAk:b-6gxe42) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9d3250dc5c9562c724ed44c9b64df80d0682ad68/.github/workflows/configure-kingdom.yml#L41)):*
> ```YAML
>         uses: actions/checkout@v2
> 
>   # TODO(wfa-hkawalkar): add gcloud authentication to connect to cluster.
> ```

I cannot see how this workflow would possibly work without the auth. You'll probably need the gcloud project name as an input so that this workflow can be reused for other environments. You can use that to call the gcloud auth action.

Please address all of the comments and get the workflow functioning and *then* publish your responses to let reviewers know that it's ready to look at again.



_Code quote:_
```YAML
  # TODO(wfa-hkawalkar): add gcloud authentication to connect to cluster.
```

**Review by wfa-mdharmalingam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl and @SanjayVas)

___
*[`.github/workflows/configure-kingdom.yml` line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS7gCdX0eV0D4W2lLUM:-NSCf3wU9UuYT9KNCOE6:b-wn391o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d326d0fe27e4f678d604bdbb9a195e5cb80c832/.github/workflows/configure-kingdom.yml#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe this needs the same inputs as the `workflow_dispatch` trigger.
</blockquote></details>

This file will call from high-level
___
*[`.github/workflows/configure-kingdom.yml` line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS81efs20kGZQftR0dY:-NSCfVzc6ynEgZhnq7kG:bgdjo30) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17528857986ed4567523d13f40ef26996c07815a/.github/workflows/configure-kingdom.yml#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You seem to have misunderstood. The commands I gave above are a replacement for `bazelisk run //src/main/k8s/testing/secretfiles:apply_kustomization`. It's decomposing what that Bazel target does so that you can control/capture the output of `kubectl apply`.

> As cluster is not created it will not be able to apply to cluster.

Why would this be the case? If you're running this workflow directly, it's up to you to ensure the cluster already exists. If you're running it from the QA deployment workflow, then the Terraforming workflow should have already created the cluster.
</blockquote></details>

We have added the Build instead of run
___
*[`.github/workflows/configure-kingdom.yml` line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NSCROI2Ae5PXo1_tAAj:-NSCf9s612SWPS4S65bC:bykmrmz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9d3250dc5c9562c724ed44c9b64df80d0682ad68/.github/workflows/configure-kingdom.yml#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I cannot see how this workflow would possibly work without the auth. You'll probably need the gcloud project name as an input so that this workflow can be reused for other environments. You can use that to call the gcloud auth action.

Please address all of the comments and get the workflow functioning and *then* publish your responses to let reviewers know that it's ready to look at again.
</blockquote></details>

Earlier WFI was not working for us, we have added a new WFI for this file

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)* status: all files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl, @wfa-hkawalkar, and @wfa-mdharmalingam)

___
*[`.github/workflows/configure-kingdom.yml` line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS7gCdX0eV0D4W2lLUM:-NSDc_0M5wLQtKGpzoc6:bs3ditm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d326d0fe27e4f678d604bdbb9a195e5cb80c832/.github/workflows/configure-kingdom.yml#L18)):*
<details><summary><i>Previously, wfa-mdharmalingam wrote…</i></summary><blockquote>

This file will call from high-level
</blockquote></details>

I'm not certain what you mean. I'm saying that you'll need the same inputs regardless of whether the trigger is `workflow_dispatch` or `workflow_call`. That is to say I believe you need to copy the `inputs` section to the other trigger as well.
___
*[`.github/workflows/configure-kingdom.yml` line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS81efs20kGZQftR0dY:-NSDdmdtD4MEiDStyvtd:b4z2lor) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17528857986ed4567523d13f40ef26996c07815a/.github/workflows/configure-kingdom.yml#L46)):*
<details><summary><i>Previously, wfa-mdharmalingam wrote…</i></summary><blockquote>

We have added the Build instead of run
</blockquote></details>

The build target is `//src/main/k8s/testing/secretfiles:kustomization.tar`.

I'd recommend just putting all of the commands into a single step, since logically all you're doing is still applying the secret.

```yaml
- name: Apply secret
  run: |
    bazelisk build //src/main/k8s/testing/secretfiles:kustomization.tar
    mkdir secretfiles
    tar -xf "$(bazelisk info bazel-bin)/src/main/k8s/testing/secretfiles/kustomization.tar" -C secretfiles
    resource_name="$(kubectl apply -k secretfiles/src/main/k8s/testing/secretfiles/kustomization -o name)"
    echo "SECRET_NAME=$(basename $resource_name)" >> "$GITHUB_ENV"
```
___
*[`.github/workflows/configure-kingdom.yml` line 63 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NSDdJM6BKD5SK2sJMBA:-NSDdJM6BKD5SK2sJMBB:b-391rz7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d363c226bb3e1a4c95ca3748bc66a802f7abfee/.github/workflows/configure-kingdom.yml#L63)):*
> ```YAML
>           --define container_registry=${{ env.REGISTRY }} \
>           --define image_repo_prefix=${{ env.REPO_PREFIX }} \
>           --define image_tag=${{ inputs.image_tag }}        
> ```

nit: trim trailing whitespace



_Code quote:_
```YAML
········
```

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, and @wfa-mdharmalingam)

___
*[`.github/workflows/configure-kingdom.yml` line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS7gCdX0eV0D4W2lLUM:-NSF54q047QA1Bb8mYin:b8h1f0d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d326d0fe27e4f678d604bdbb9a195e5cb80c832/.github/workflows/configure-kingdom.yml#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not certain what you mean. I'm saying that you'll need the same inputs regardless of whether the trigger is `workflow_dispatch` or `workflow_call`. That is to say I believe you need to copy the `inputs` section to the other trigger as well.
</blockquote></details>

Done. so now the workflow_call was take the same input as workflow_dispatch.
___
*[`.github/workflows/configure-kingdom.yml` line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS81efs20kGZQftR0dY:-NSF4Sy70_wo1wfY1AgT:b-1g2usp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17528857986ed4567523d13f40ef26996c07815a/.github/workflows/configure-kingdom.yml#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The build target is `//src/main/k8s/testing/secretfiles:kustomization.tar`.

I'd recommend just putting all of the commands into a single step, since logically all you're doing is still applying the secret.

```yaml
- name: Apply secret
  run: |
    bazelisk build //src/main/k8s/testing/secretfiles:kustomization.tar
    mkdir secretfiles
    tar -xf "$(bazelisk info bazel-bin)/src/main/k8s/testing/secretfiles/kustomization.tar" -C secretfiles
    resource_name="$(kubectl apply -k secretfiles/src/main/k8s/testing/secretfiles/kustomization -o name)"
    echo "SECRET_NAME=$(basename $resource_name)" >> "$GITHUB_ENV"
```
</blockquote></details>

Done. the commands are combined now.  
___
*[`.github/workflows/configure-kingdom.yml` line 63 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NSDdJM6BKD5SK2sJMBA:-NSF4HmB97EN_8Qrx8-T:b-l6dm22) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df81275496497c15cfa8bf2e11c1cf558a426f36/.github/workflows/configure-kingdom.yml#L63)):*
> nit: trim trailing whitespace
removed the exta spaces. thank you for point it out.

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, and @wfa-mdharmalingam)

___
*[`.github/workflows/configure-kingdom.yml` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NRndwxEAR5eKwrEKSXv:-NSGHi9OAAD0u8xGVd0p:b-2i5ulw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82578d04ea26d4c46d43c7cea0b9549fe4b2404d/.github/workflows/configure-kingdom.yml#L56)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

We will make changes. 
</blockquote></details>


I have replaced certs and config values with $SECRET_NAME.
___
*[`.github/workflows/configure-kingdom.yml` line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921#-NS7gCdX0eV0D4W2lLUM:-NSGEaGF2psOmgUHXbO-:bmpgubf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d326d0fe27e4f678d604bdbb9a195e5cb80c832/.github/workflows/configure-kingdom.yml#L18)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

Done. so now the workflow_call was take the same input as workflow_dispatch.
</blockquote></details>

As confirmed, the workflow call will be put to use in a separate PR.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/921)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl and @wfa-mdharmalingam)

**Pull request merged**
