### PR TITLE
Add CLI commands for model suite

### PR DESCRIPTION
**Pull request by jojijac0b**
Create CLI create, get, and list commands for model suites. 
Write tests for CLI commands
Delete unused SUCCEEDED_DATA_PROVIDER in MeasurementSystemTest.kt

### CODE REVIEW

**Review by Marco-Premier — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011)* status: all files reviewed, 15 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel` line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1g66SCgsqeouyrYzy:-NW1g66SCgsqeouyrYzz:b9cvn4i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel#L75)):*
> ```Starlark
>         "//src/main/proto/wfa/measurement/api/v2alpha:measurement_kt_jvm_proto",
>         "//src/main/proto/wfa/measurement/api/v2alpha:measurements_service_kt_jvm_grpc_proto",
>         "//src/main/proto/wfa/measurement/api/v2alpha:model_suites_service_kt_jvm_grpc_proto",
> ```

is this needed? I don't see ```ModelSuite``` being imported in ```Benchmark.kt``` class



_Code quote:_
```Starlark
"//src/main/proto/wfa/measurement/api/v2alpha:model_suites_service_kt_jvm_grpc_proto",
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1139 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1V2FOCDIFo-YyFw7c:-NW1V2FOCDIFo-YyFw7d:bgxagrh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1139)):*
> ```Kotlin
>     private set
> 
>   val modelProviderStub: ModelSuitesCoroutineStub by lazy {
> ```

nit: ```modelSuiteStub```



_Code quote:_
```Kotlin
modelProviderStub
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1148 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1bxDXBOiSKpJMGkz7:-NW1bxDXBOiSKpJMGkz8:brq2iip) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1148)):*
> ```Kotlin
>     required = true,
>   )
>   private lateinit var modelProviderName: String
> ```

the ```parent``` is only needed for ```createModelSuite``` and ```ListModelSuite```, therefore it needs to be moved as function parameter only for those two method. Otherwise it becomes required also for ```getModelSuite``` but it shouldn't.

I.e. delete ```modelProviderName``` from here and add it as parameters to ```create``` and ```stream``` functions only.



_Code quote:_
```Kotlin
private lateinit var modelProviderName: String
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1173 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1ayp--P86KJ1XTV1E:-NW1ayp--P86KJ1XTV1F:b-1ya6fg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1173)):*
> ```Kotlin
>       names = ["--create-time"],
>       description = ["Unix time stamp of when model suite was created."],
>       required = true,
> ```

```description``` is not a required field. To check what fields are required, please check public api (https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/model_suite.proto#L39)

i.e.

```
modelSuiteDescription: String? = null,
@Option(
   ...
   required = false,
)
```



_Code quote:_
```Kotlin
required = true,
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1175 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1aCu2-834ovLKrVB1:-NW1aCu34RXvLgyKN973:b-w8t698) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1175)):*
> ```Kotlin
>       required = true,
>     )
>     modelSuiteCreateTime: Long
> ```

CreateTime is an OUTPUT-ONLY field generated by ```CreateModelSuite```  spanner, therefore it must not be provided by the caller.

i.e. remove ```modelSuiteCreateTime``` option



_Code quote:_
```Kotlin
    @Option(
      names = ["--create-time"],
      description = ["Unix time stamp of when model suite was created."],
      required = true,
    )
    modelSuiteCreateTime: Long
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1183 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1amvx59FECjbvEDxh:-NW1amvx59FECjbvEDxi:b-n7f3wv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1183)):*
> ```Kotlin
>         displayName = modelSuiteDisplayName
>         description = modelSuiteDescription
>         createTime = timestamp { seconds = modelSuiteCreateTime }
> ```

same as above. remove ```createTime```.



_Code quote:_
```Kotlin
createTime = timestamp { seconds = modelSuiteCreateTime }
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1208 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1cjyl4R1QoJtjf9oI:-NW1cjyl4R1QoJtjf9oJ:b-sn41ta) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1208)):*
> ```Kotlin
> 
>   @Command(description = ["Lists model suites for a model provider."])
>   fun stream(
> ```

nit: stream is the name we use for internal API. For public api this should change to ```list```.

```fun list( ... ```



_Code quote:_
```Kotlin
stream
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1212 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1bdiQCfdquta7wVM-:-NW1bdiQCfdquta7wVM0:bbg6myw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1212)):*
> ```Kotlin
>       names = ["--page-size"],
>       description = ["The maximum number of ModelSuites to return."],
>       required = true,
> ```

```pageSize``` is not a required field.

```
  required = false,
)
listPageSize: Int? = null,
```



_Code quote:_
```Kotlin
required = true,
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1221 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1bhX82O2ezqv-og6S:-NW1bhX82O2ezqv-og6T:ble2rd4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1221)):*
> ```Kotlin
>           "A page token, received from a previous `ListModelSuitesRequest` call. Provide this to retrieve the subsequent page."
>         ],
>       required = true,
> ```

```pageToken``` is not a required field.

```
  required = false,
)
listPageToken: String? = null,
```




_Code quote:_
```Kotlin
required = true,
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1232 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1bpCgEiniwvszmi4h:-NW1bpCgEiniwvszmi4i:b-2gqqms) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1232)):*
> ```Kotlin
>     val response =
>       runBlocking(parentCommand.rpcDispatcher) { modelProviderStub.listModelSuites(request) }
>     response.modelSuiteList
> ```

nit: I think this is redundant and can be removed.



_Code quote:_
```Kotlin
response.modelSuiteList
```
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1004 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1dkWx2Cao3YbTE0aw:-NW1dkWx2Cao3YbTE0ax:b-8qpaf8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1004)):*
> ```Kotlin
>           "Description",
>           "--create-time",
>           "3000"
> ```

Remove ```--create-time``` param from the request.



_Code quote:_
```Kotlin
          "--create-time",
          "3000"
```
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1013 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1dsZc5YOvXbnn3MjJ:-NW1dsZc5YOvXbnn3MjK:bqas9po) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1013)):*
> ```Kotlin
>       }
> 
>     assertThat(request.modelSuite).comparingExpectedFieldsOnly().isEqualTo(MODEL_SUITE)
> ```

Since now request no longer contains the ```create-time``` field this assertion would fails.
So you need to ignore the field ```create-time```:

```
assertThat(request.modelSuite)
.ignoringFields(ModelSuite.CREATE_TIME_FIELD_NUMBER)
.isEqualTo(MODEL_SUITE)
```



_Code quote:_
```Kotlin
assertThat(request.modelSuite).comparingExpectedFieldsOnly().isEqualTo(MODEL_SUITE)
```
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1013 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1eUR915hL-kKEvoC5:-NW1eUR915hL-kKEvoC6:bb1pb39) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1013)):*
> ```Kotlin
>       }
> 
>     assertThat(request.modelSuite).comparingExpectedFieldsOnly().isEqualTo(MODEL_SUITE)
> ```

```comparingExpectedFieldsOnly()``` does nothing when you only have one proto resource to compare.
In case you compare a list of proto(s) resources, invoking ```comparingExpectedFieldsOnly()``` method, limits the comparison only to those fields that are present in all the proto(s) resources.



_Code quote:_
```Kotlin
comparingExpectedFieldsOnly()
```
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1020 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1esgsENezk7tnXYOM:-NW1esgsENezk7tnXYON:b-pflcm4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1020)):*
> ```Kotlin
>     val args =
>       commonArgs +
>         arrayOf("model-suites", "--parent=$MODEL_PROVIDER_NAME", "get", "--name", MODEL_SUITE_NAME)
> ```

Please see comment in ```MeasurementSystem```. The ```parent``` field is not part of the ```GetModelSuiteRequest``` and therefore needs to be removed.



_Code quote:_
```Kotlin
--parent=$MODEL_PROVIDER_NAME", 
```
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1042 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-NW1ig7r511R5DAqdu5B:-NW1ig7r511R5DAqdu5C:brvp1oi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a9326ea8b7fa25c6efff4ef28086af9ef07a2cb/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1042)):*
> ```Kotlin
>           "10",
>           "--page-token",
>           "token"
> ```

I would add another test similar to this one. except that ```--page-size``` and ```--page-token``` are omitted so that we also test the command when null values are provided.



_Code quote:_
```Kotlin
          "--page-size",
          "10",
          "--page-token",
          "token"
```

**Review by stevenwarejones — COMMENTED** [review]
Are you comandeering this one @Marco-Premier ?

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011#-:-NW9OJZc2MQxTAnUr-gJ:bncc4zg)* status: all files reviewed, 15 unresolved discussions (waiting on @jojijac0b)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1011)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b)

**Pull request merged**
