### PR TITLE
Add Report Scheduling Tables

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1259)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/resources/reporting/postgres/add-report-scheduling-tables.sql` line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1259#-NfN54YQ31fdY6iD2qG4:-NfN54YQ31fdY6iD2qG5:bumyd0j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a9534e7650415050cc669d59d64ca7547813c02/src/main/resources/reporting/postgres/add-report-scheduling-tables.sql#L96)):*
> ```TSQL
>   ReportScheduleId bigint NOT NULL,
> 
>   PRIMARY KEY(MeasurementConsumerId, ReportId, ReportScheduleId),
> ```

I chose this order for the primary key because the query I expect to use would be to get a report and then check if a report schedule is tied to it. If report was dual parented instead, then I would have used the other order.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/add-report-scheduling-tables.sql` line 48 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1259#-NfRqV2x9tavqOFtC7Zk:-NfRqV2x9tavqOFtC7Zl:bpg69v9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82cf39a2b58521051a8e8a9d190114dbc370b5de/src/main/resources/reporting/postgres/add-report-scheduling-tables.sql#L48)):*
> ```TSQL
>   ExternalReportScheduleId text NOT NULL,
> 
>   CreateReportScheduleRequestId text,
> ```

Do we need to support idempotent requests here? It's a nice feature to have, but you can save yourself some code if we don't need it.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

___
*[`src/main/resources/reporting/postgres/add-report-scheduling-tables.sql` line 48 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1259#-NfRqV2x9tavqOFtC7Zk:-Nfm73hY6lAxMmNG3Y78:b-uy7t0c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffd47054847749f82c3c3b84c2303f55ee90d126/src/main/resources/reporting/postgres/add-report-scheduling-tables.sql#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we need to support idempotent requests here? It's a nice feature to have, but you can save yourself some code if we don't need it.
</blockquote></details>

I don't know how much we need it, but the code to support it isn't that much

**Pull request merged**
