### PR TITLE
Update CMMS to use the latest version of the anysketch library.

### PR DESCRIPTION
**Pull request by wangyaopw**
A kingdom internal ElGamalKey proto is also created, since the common
one in anysketch is not shared across repos any more.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/70)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/70)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/crypto.proto, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/70#-Ma9n1Y00maSgUrcIXvr:-Ma9n1Y00maSgUrcIXvs:b84urjk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/91e08033900ecc58a0c60c440cbd82011680073f/src/main/proto/wfa/measurement/internal/kingdom/crypto.proto#L23)):*
> ```protobuf
> 
> // A public key in the ElGamal crypto system.
> message ElGamalPublicKey {
> ```

Can we just name the file `el_gamal_public_key.proto` too? `crypto.proto` is so vague and bundling a bunch of kind-of related messages together in a file isn't great

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/70)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/crypto.proto, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/70#-Ma9n1Y00maSgUrcIXvr:-Ma9nqN21T2c0qoeo972:bkj5yb3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/91e08033900ecc58a0c60c440cbd82011680073f/src/main/proto/wfa/measurement/internal/kingdom/crypto.proto#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we just name the file `el_gamal_public_key.proto` too? `crypto.proto` is so vague and bundling a bunch of kind-of related messages together in a file isn't great
</blockquote></details>

we have a crypto.proto in the cmms-api repo. https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0e1c9d33776d02527820181712d8dc289abc0b7c/src/main/proto/wfa/measurement/api/v2alpha/crypto.proto

I am fine with creating a file for each message, but one file for all related messages also makes sense to me.

Do you have strong preference between these two?

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/crypto.proto, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/70#-Ma9n1Y00maSgUrcIXvr:-Ma9wXh36mV1PTvPgYXm:b743raw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/91e08033900ecc58a0c60c440cbd82011680073f/src/main/proto/wfa/measurement/internal/kingdom/crypto.proto#L23)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

we have a crypto.proto in the cmms-api repo. https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0e1c9d33776d02527820181712d8dc289abc0b7c/src/main/proto/wfa/measurement/api/v2alpha/crypto.proto

I am fine with creating a file for each message, but one file for all related messages also makes sense to me.

Do you have strong preference between these two?
</blockquote></details>

Not a strong preference. It's fine as is.

**Review by zachcwc — APPROVED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
