### PR TITLE
Reporting CLI can create, list and get Reports

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604)* status: all files reviewed, 9 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 282 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56OiY6A3-Ay5hLgvbv:-N56OiY6A3-Ay5hLgvbw:b-jdiiwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L282)):*
> ```Kotlin
>   @CommandLine.Option(
>     names = ["--metric"],
>     description = ["String of serialized Metric"],
> ```

"Serialized" for protobufs generally implies serialization to the binary wire format.

In this case, I believe you mean "A Metric protobuf message in text format"



_Code quote:_
```Kotlin
String of serialized Metric
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 285 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56PNom0A5tuzUYTyFR:-N56PNom0A5tuzUYTyFS:b-eohem2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L285)):*
> ```Kotlin
>     required = true,
>   )
>   private lateinit var serializedMetrics: List<String>
> ```

Maybe `textFormat`?



_Code quote:_
```Kotlin
serialized
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 316 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56PwZk5JH-7eDb2uUM:-N56PwZk5JH-7eDb2uUN:bip0d74) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L316)):*
> ```Kotlin
>         }
> 
>         timeInput.periodicTimeIntervalInput?.let {
> ```

nit: `let` is primarily used when you want to do something with the lambda result. I think in this case, you're looking for `also`. See https://kotlinlang.org/docs/scope-functions.html#function-selection

Note that it may be clearer to just use standard conditionals for the timeinterval oneof. e.g.

```kotlin
if (timeInput.timeIntervals != null) {
  timeIntervals = timeIntervals {
    timeIntervals += timeInput.timeIntervals.map {
      // ...
    }
  }
} else {
  val periodicInput = checkNotNull(timeInput.periodicTimeIntervalInput)
  periodicTimeInterval = periodicTimeInterval {
    startTime = periodicInput.periodicIntervalStartTime.toProtoTime()
    // ...
  }
}
```



_Code quote:_
```Kotlin
let
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 326 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56Sl9E8219_nMazB9c:-N56Sl9E8219_nMazB9d:b-17t5q1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L326)):*
> ```Kotlin
>         serializedMetrics.map {
>           val metricsBuilder = Metric.newBuilder()
>           TextFormat.getParser().merge(it, metricsBuilder)
> ```

nit: use `org.wfanet.measurement.common.parseTextProto` e.g.

```kotlin
for (textFormatMetric in textFormatMetrics) {
  metrics += textFormatMetric.reader().use {
    parseTextProto(it, Metric.getDefaultInstance())
  }
}
```



_Code quote:_
```Kotlin
          val metricsBuilder = Metric.newBuilder()
          TextFormat.getParser().merge(it, metricsBuilder)
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 359 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56UCXY212c_xiS_NAF:-N56UCXY212c_xiS_NAG:bj66xhk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L359)):*
> ```Kotlin
>     val response = runBlocking(Dispatchers.IO) { parent.reportsStub.listReports(request) }
> 
>     response.reportsList.map { println(it.name + " " + it.state.toString()) }
> ```

Don't use `map` when you aren't transforming anything. Use a regular for loop, or `forEach` for the less-common cases where the functional style would help readability.



_Code quote:_
```Kotlin
map 
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/metric.textproto` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56VQpHEe1EmFCkKU9O:-N56VQpHEe1EmFCkKU9P:b-pxixgq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/metric.textproto#L1)):*
> ```
> reach { }
> ```

nit: include annotations for the protobuf editor

```textproto
# proto-file: wfa/measurement/reporting/v1alpha/metric.proto
# proto-message: Metric
```

If you have your protobuf editor plugin in IntelliJ properly configured to import from `src/main/proto`, then it'll check the syntax for you.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt` line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56WFatEhBzIn3D-ZDo:-N56WFatEhBzIn3D-ZDp:bncm4kj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt#L71)):*
> ```Kotlin
>   getRuntimePath(
>     Paths.get(
>       "wfa_measurement_system/src/test/kotlin/org/wfanet/measurement/reporting" +
> ```

Why was this changed from the varargs syntax? While we only technically support Linux, the other syntax makes sure to use the appropriate separator characters for your file system.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt` line 255 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56Wty_22cE6ETXOT-4:-N56Wty_22cE6ETXOT-5:b-fqkfg3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt#L255)):*
> ```Kotlin
>     val metric =
>       """
>     reach { }
> ```

nit: do you not want to put these into textproto files too?
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt` line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56X2lwDBwNlj5eBUzb:-N56X2lwDBwNlj5eBUzc:bwhi46h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d27f6763736acd5ad6382cdb8a5a6d47ce2bf85/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt#L100)):*
> ```Kotlin
> }
> 
> private fun Duration.toProtoDuration(): ProtoDuration = protoDuration {
> ```

Add TODO to use version from common-jvm once available.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 282 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56OiY6A3-Ay5hLgvbv:-N56jC3ZBL5O0X_iJ78s:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L282)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

"Serialized" for protobufs generally implies serialization to the binary wire format.

In this case, I believe you mean "A Metric protobuf message in text format"
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 285 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56PNom0A5tuzUYTyFR:-N56lPyX44avrre03yst:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L285)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Maybe `textFormat`?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 326 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56Sl9E8219_nMazB9c:-N56tlpm5ZEU2nV5rQHW:b5jscz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L326)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use `org.wfanet.measurement.common.parseTextProto` e.g.

```kotlin
for (textFormatMetric in textFormatMetrics) {
  metrics += textFormatMetric.reader().use {
    parseTextProto(it, Metric.getDefaultInstance())
  }
}
```
</blockquote></details>

Cool. Good to know .reader() could make it work
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 359 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56UCXY212c_xiS_NAF:-N56twYp7A4b281W5s6D:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L359)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't use `map` when you aren't transforming anything. Use a regular for loop, or `forEach` for the less-common cases where the functional style would help readability.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt` line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56WFatEhBzIn3D-ZDo:-N56u58I0AM0eOSvT8EV:b-fot2r4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why was this changed from the varargs syntax? While we only technically support Linux, the other syntax makes sure to use the appropriate separator characters for your file system.
</blockquote></details>

Good to know that. Thanks
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt` line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56X2lwDBwNlj5eBUzb:-N56pV7d2X_AMEyrFmyQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d27f6763736acd5ad6382cdb8a5a6d47ce2bf85/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt#L100)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add TODO to use version from common-jvm once available.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 359 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56UCXY212c_xiS_NAF:-N57n7sp42nI-ZNLpBYM:bocxtk7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L359)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the change?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 311 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N57mkHKE6QiuE_dobFv:-N57mkHKE6QiuE_dobFw:bjfatbi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdee2f6f556e123cb3d14437da3a86eca0ad99cf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L311)):*
> ```Kotlin
>         if (timeInput.timeIntervals != null) {
>           timeIntervals = timeIntervals {
>             timeInput.timeIntervals!!.forEach {
> ```

Is Kotlin unable to smart cast this for you? If so, assign to a local val first so it can.



_Code quote:_
```Kotlin
timeInput.timeIntervals!!
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 321 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N57mw544gzwJJYro0Mh:-N57mw544gzwJJYro0Mi:b-f6swkw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdee2f6f556e123cb3d14437da3a86eca0ad99cf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L321)):*
> ```Kotlin
>           periodicTimeInterval = periodicTimeInterval {
>             startTime =
>               timeInput.periodicTimeIntervalInput!!.periodicIntervalStartTime.toProtoTime()
> ```

I had used a local val with `checkNotNull` in the example to avoid use of the `!!` operator here.



_Code quote:_
```Kotlin
timeInput.periodicTimeIntervalInput!!
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 359 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N56UCXY212c_xiS_NAF:-N5BXKuU-EdTEsngKMJM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/924219ff2dd9b47f9b5e3cc817912c619d98c58a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L359)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see the change?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 311 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N57mkHKE6QiuE_dobFv:-N5BXJHf7yCS7lr3ONRN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdee2f6f556e123cb3d14437da3a86eca0ad99cf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L311)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is Kotlin unable to smart cast this for you? If so, assign to a local val first so it can.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 321 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N57mw544gzwJJYro0Mh:-N5BXK5C9VvP8EfMvI0H:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bdee2f6f556e123cb3d14437da3a86eca0ad99cf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L321)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I had used a local val with `checkNotNull` in the example to avoid use of the `!!` operator here.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli and @tristanvuong2021)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/README.md` line 62 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N5Hh8h16Q4490CCCHbU:-N5HjzFb5KF6k1eetmbb:b4x0kre) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d06119bb95ba24084a3427e1597ddb10c85f5a77/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/README.md#L62)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

wouldn't it just be simpler to just have 3 params: `interval-start-time`, `--interval-end-time`, `--interval-peridocity` with the peridocity defaulting to 1?
</blockquote></details>

There are two types of time settings. [proto here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto#L78-L83). The `time_intervals` is repeated but `periodic_time_interval`is not.
In terms of the e CLI tool, I understand that we can merge these tw. But I feel it is better to keep the arguments consistent with our proto definition.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt` line 112 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N5HiSKP4TXLTJdpn8DI:-N5Hm-ZY-6hOLl0eL9J1:bjsbkap) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d06119bb95ba24084a3427e1597ddb10c85f5a77/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt#L112)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

add a todo to move this to common-jvm
</blockquote></details>

Could you please approve this PR so I can update it right away.
[common-jvm PR](https://github.com/world-federation-of-advertisers/common-jvm/pull/132)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @riemanli, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt` line 112 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N5HiSKP4TXLTJdpn8DI:-N5HyHBLE14JLX_QJPEv:b-dlnt20) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d06119bb95ba24084a3427e1597ddb10c85f5a77/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt#L112)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Could you please approve this PR so I can update it right away.
[common-jvm PR](https://github.com/world-federation-of-advertisers/common-jvm/pull/132)
</blockquote></details>

Updated.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/README.md` line 62 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604#-N5Hh8h16Q4490CCCHbU:-N5LGI4h7PjNU0zSdgMJ:b-3orla2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d06119bb95ba24084a3427e1597ddb10c85f5a77/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/README.md#L62)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

There are two types of time settings. [proto here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto#L78-L83). The `time_intervals` is repeated but `periodic_time_interval`is not.
In terms of the e CLI tool, I understand that we can merge these tw. But I feel it is better to keep the arguments consistent with our proto definition.

</blockquote></details>

hmmmm.... I'm not sure they need to map exactly. I guess its okay as-is.

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 3 of 5 files at r3, 2 of 3 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh, @riemanli, @stevenwarejones, and @tristanvuong2021)

**Review by renjiezh — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/604)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli and @tristanvuong2021)

**Pull request merged**
