### PR TITLE
Update the EdpSimulator to pass the correctness tes

### PR DESCRIPTION
**Pull request by wangyaopw**
updated EDP simulator to set EdpParticipantionSignature.
fixed the EDP simulator to build the correct encryptSketchRequest.
Updated the EDP simulator to load the JNI library.

https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F607228901955&view=2c2927c0-626b-4740-8620-af2a93b7d623

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[build/repositories.bzl, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270#-MjH18mJ4gfjiCycb4DU:-MjH18mJ4gfjiCycb4DV:b-ygy7wl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c97f0b760037a66bf453a2fbed89b1a5f619e1b8/build/repositories.bzl#L70)):*
> ```Starlark
>         repo = "consent-signaling-client",
>         sha256 = "7bbf4a11897b25089d91c731211cec11b18355e74f25497cc254a5312bf518df",
>         commit = "b273402960d65d5bb00b90c4ee3058cb12c3881e",
> ```

This will be updated to the new version when https://github.com/world-federation-of-advertisers/consent-signaling-client/pull/20 is merged.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270)* status: 0 of 20 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270#-MjH64dfBfyUAIQt4CQa:-MjH64dfBfyUAIQt4CQb:b-jbb99i) (no related file):*
Please split the Kingdom, Duchy, and simulator changes into separate PRs.

---

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270#-MjH64dfBfyUAIQt4CQa:-MjUJ7LlAZY_D3uUgRVH:b-hsm5so) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Please split the Kingdom, Duchy, and simulator changes into separate PRs.
</blockquote></details>

I'm fine with doing this in one PR

---

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270)* status: 4 of 20 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270#-MjH64dfBfyUAIQt4CQa:-MjV4DY31QI61RJaZ529:b-xaofrh) (no related file):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

I'm fine with doing this in one PR
</blockquote></details>

Broke this into 4 PRs.

---

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 71 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270#-MjVJjt64zaWYfJU4dAE:-MjVJjt64zaWYfJU4dAF:bniir2q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8efc813b57f08ee42df7783a9a63bdabe383a61f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L71)):*
> ```
> id
> ```
nit: ID

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 3 of 20 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

___
*[build/repositories.bzl, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/270#-MjH18mJ4gfjiCycb4DU:-MjWZDxu6JquK4kS5QmC:b-6yg331) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c97f0b760037a66bf453a2fbed89b1a5f619e1b8/build/repositories.bzl#L70)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

This will be updated to the new version when https://github.com/world-federation-of-advertisers/consent-signaling-client/pull/20 is merged. 
</blockquote></details>

Will updated in future PR for this

**Pull request merged**
