### PR TITLE
Update cross-media-measurement-api version

### PR DESCRIPTION
**Pull request by Marco-Premier**
Replace Timestamps with google.type.Date in ModelRolloutService Fix broken tests

Internal proto resources remained the same. What changed is the way public proto resources are converted into internal ones and viceversa.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1781 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-N_oIRrfAkP2cujT6lxm:-N_oIRrfAkP2cujT6lxn:bphcevg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7848a568c824ab85aa579335a38cb3df9433a4c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1781)):*
> ```Kotlin
>       required = false,
>     )
>     rolloutStartDate: Instant? = null,
> ```

Picocli supports `LocalDate`, which is the Java equivalent of the `google.type.Date` protobuf message type.



_Suggestion:_
```Kotlin
LocalDate
```

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)* status: 4 of 12 files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1781 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-N_oIRrfAkP2cujT6lxm:-N_reZ2k2WEWyYO-0nms:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7848a568c824ab85aa579335a38cb3df9433a4c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1781)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Picocli supports `LocalDate`, which is the Java equivalent of the `google.type.Date` protobuf message type.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)* status: 4 of 12 files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1816 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-N_tcvxe0IuVHlqtzzvb:-N_tcvxe0IuVHlqtzzvc:b-8cwale) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5615dc5c900c33ed273323a352b4c74c966d0930/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1816)):*
> ```Kotlin
>             month = instantRolloutDate.monthValue
>             day = instantRolloutDate.dayOfMonth
>           }
> ```

Use `org.wfanet.measurement.common.toProtoDate` extension



_Suggestion:_
```Kotlin
          this.instantRolloutDate = instantRolloutDate.toProtoDate()
```

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)* status: 4 of 12 files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1816 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-N_tcvxe0IuVHlqtzzvb:-NaCB3o25WVhk5AHmjgJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5615dc5c900c33ed273323a352b4c74c966d0930/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1816)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use `org.wfanet.measurement.common.toProtoDate` extension
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)* status: 6 of 12 files reviewed, 3 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt` line 382 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-NaDPkXGD7FwHSJqgfU4:-NaDPkXGD7FwHSJqgfU5:b-woxd8v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78e9592993bd2fbedaaf0b13ec455b8c2c164204/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt#L382)):*
> ```Kotlin
>       month = localDate.monthValue
>       day = localDate.dayOfMonth
>     }
> ```

You can chain the existing conversion methods. You may want to do this explicitly rather than hiding the implementation in an extension method.



_Suggestion:_
```Kotlin
    return toInstant().atZone(ZoneOffset.UTC).toLocalDate().toProtoDate()
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt` line 392 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-NaDQLgnB3jsyQnAKMbA:-NaDQLgnB3jsyQnAKMbB:b2gz6lh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78e9592993bd2fbedaaf0b13ec455b8c2c164204/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt#L392)):*
> ```Kotlin
>       seconds = instant.epochSecond
>       nanos = instant.nano
>     }
> ```

You can chain the existing conversion methods. You may want to do this explicitly rather than hiding the implementation in an extension method, or at least being explicit in the method name that this is converting to start of day UTC.



_Suggestion:_
```Kotlin
   return toLocalDate().atStartOfDay().toInstant(ZoneOffset.UTC).toProtoTime()
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 928 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-NaDSNo42vDbD4xNCjKq:-NaDSNo42vDbD4xNCjKr:b-yqctwk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78e9592993bd2fbedaaf0b13ec455b8c2c164204/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L928)):*
> ```Kotlin
> }
> 
> // TODO(@MarcoPremier): Move this function to common-jvm.
> ```

I believe you have these defined in 4 locations. Even if you want them and intend to move to common-jvm later, at least put them in some common location in this repo now.

**Review by jojijac0b — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt` line 309 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-NacqAdf6X9EyV78zBRq:-NacqAdg4ZUMMVoZnwfU:b-9z2fp9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78e9592993bd2fbedaaf0b13ec455b8c2c164204/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt#L309)):*
> ```Kotlin
>               source.filter.hasRolloutPeriodOverlapping() &&
>               source.filter.rolloutPeriodOverlapping.startDate ==
>                 this.rolloutPeriodOverlapping.startTime.toDate() &&
> ```

feels funny to update only some of these from times to date. The latest cm-api as `rolloutPeriodOverlapping.startDate`

**Review by Marco-Premier — COMMENTED** [review]
@SanjayVas I've avoided to update common-jvm in favor of concatenation of existing methods. thanks

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-:-NafJ1sF3KIwRRfCI-we:b-7sucu0)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt` line 309 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-NacqAdf6X9EyV78zBRq:-NafJFtB74mU82NntlqE:b-2bu291) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78e9592993bd2fbedaaf0b13ec455b8c2c164204/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt#L309)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

feels funny to update only some of these from times to date. The latest cm-api as `rolloutPeriodOverlapping.startDate`
</blockquote></details>

That's because underlying startDate / endDate management in internal APIs did not change. So the service take care of converting dates to prototimes before forwarding requests internally
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt` line 382 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-NaDPkXGD7FwHSJqgfU4:-NaGGgSL8KxQ7ve3DE16:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78e9592993bd2fbedaaf0b13ec455b8c2c164204/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt#L382)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can chain the existing conversion methods. You may want to do this explicitly rather than hiding the implementation in an extension method.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt` line 392 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-NaDQLgnB3jsyQnAKMbA:-NaGGsPuDAMtHdPwamj9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78e9592993bd2fbedaaf0b13ec455b8c2c164204/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt#L392)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can chain the existing conversion methods. You may want to do this explicitly rather than hiding the implementation in an extension method, or at least being explicit in the method name that this is converting to start of day UTC.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 928 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-NaDSNo42vDbD4xNCjKq:-NafJ0O38Zc79VzroB8R:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78e9592993bd2fbedaaf0b13ec455b8c2c164204/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L928)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe you have these defined in 4 locations. Even if you want them and intend to move to common-jvm later, at least put them in some common location in this repo now.
</blockquote></details>

Done.

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt` line 309 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-NacqAdf6X9EyV78zBRq:-Nag_M4I2sibcJ0cjCY6:bi59bzq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78e9592993bd2fbedaaf0b13ec455b8c2c164204/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt#L309)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

That's because underlying startDate / endDate management in internal APIs did not change. So the service take care of converting dates to prototimes before forwarding requests internally
</blockquote></details>

@SanjayVas - are you okay with this mis-alignment of the internal and public api?

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 2 of 4 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt` line 309 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-NacqAdf6X9EyV78zBRq:-NagyRI620b1LPFPGPFt:brae9lp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78e9592993bd2fbedaaf0b13ec455b8c2c164204/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt#L309)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@SanjayVas - are you okay with this mis-alignment of the internal and public api?
</blockquote></details>

Yes, it's fine. We have something like this in other places as well (off the top of my head, ProtocolConfig is handled differently internally).

One of the reasons we have separate APIs is to allow them to evolve independently, e.g. to avoid data migrations on DBs. Basically we need to weigh whether it's worth changing the internal API whenever we make a public API change.
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1949 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-NagzgHq6vmreePF56G8:-NagzgHq6vmreePF56G9:bm116p5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbaaaef02599cff47d99c415286c2e8c4747ffb8/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1949)):*
> ```Kotlin
> }
> 
> // TODO(@MarcoPremier): Move this function to common-jvm.
> ```

nit: I think you missed this one
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsServiceTest.kt` line 1038 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123#-NagzmcbBdQ_H63eLZqq:-NagzmcbBdQ_H63eLZqr:b-rf3s2j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbaaaef02599cff47d99c415286c2e8c4747ffb8/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsServiceTest.kt#L1038)):*
> ```Kotlin
> }
> 
> // TODO(@MarcoPremier): Move this function to common-jvm.
> ```

nit: I think you missed this one.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 1 of 4 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)* status: 10 of 12 files reviewed, all discussions resolved (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
