### PR TITLE
Update cross-media-measurement-api dep for DataProvider capabilities.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)

**Comment by SanjayVas** [comment]
Depends on https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/199

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 7 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: 7 of 19 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nqbo0K871Lv6cMN3Gy_:-Nqbo0K871Lv6cMN3Gya:ba4x2mk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382ed55ad724e47e9ad66515c543efe8845ca60c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt#L38)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.writers.ReplaceDataProviderRequiredDuchies
> 
> // TODO(@marcopremier): Add method to update data provider required duchies list.
> ```

is this TODO still needed with the move to HM Shuffle?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nqbo8fBEzqo1NOO6dJc:-Nqbo8fBEzqo1NOO6dJd:b-s6gcji) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382ed55ad724e47e9ad66515c543efe8845ca60c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L141)):*
> ```Kotlin
> 
>     @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA") // Protobuf enum fields are never null.
>     return when (request.measurement.details.protocolConfig.protocolCase) {
> ```

shouldn't the kingdom be setting the protocol? eg aggressively choosing the cheapest option appropriate for that market but falling back to other methods if certain EDPs do not support?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: 6 of 19 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nqbo0K871Lv6cMN3Gy_:-NqnG5N4-yTXGGH5ZSYE:b-4q686) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382ed55ad724e47e9ad66515c543efe8845ca60c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt#L38)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this TODO still needed with the move to HM Shuffle?
</blockquote></details>

Done. The method appears to have already been added (`replaceDataProviderRequiredDuchies`).
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nqbo8fBEzqo1NOO6dJc:-NqnF4E21SWxAUu7TPBX:b5wzmlp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382ed55ad724e47e9ad66515c543efe8845ca60c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L141)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't the kingdom be setting the protocol? eg aggressively choosing the cheapest option appropriate for that market but falling back to other methods if certain EDPs do not support?
</blockquote></details>

The Kingdom *is* setting the protocol. It's handled in the public API service impl.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: 6 of 19 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nqbo8fBEzqo1NOO6dJc:-NqnH0GV04afzpOj0PJv:b-o4jif8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382ed55ad724e47e9ad66515c543efe8845ca60c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The Kingdom *is* setting the protocol. It's handled in the public API service impl.
</blockquote></details>

Ah wait, I see your point. I'll need to have the public API service make separate calls to get the DataProviders then, as the logic that select the protocol is in the public service impl. The internal service doesn't make decisions and just does what it's told.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: 3 of 23 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nqbo8fBEzqo1NOO6dJc:-NsuF2FY37hmqsBRMABG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382ed55ad724e47e9ad66515c543efe8845ca60c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah wait, I see your point. I'll need to have the public API service make separate calls to get the DataProviders then, as the logic that select the protocol is in the public service impl. The internal service doesn't make decisions and just does what it's told.
</blockquote></details>

Done.

**Comment by SanjayVas** [comment]
CC @renjiezh for HMSS capability

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 19 files at r1, 13 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: 17 of 23 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 384 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1aNtI3XigB9B_i2lO:-Nt1aNtI3XigB9B_i2lP:b-rghsbl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5487bdf0f14c4fabb9073458c7355e939e0ba70/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L384)):*
> ```Kotlin
>       val internalCreateMeasurementRequest =
>         createMeasurementRequest.buildInternalCreateMeasurementRequest(
>           dataProviderCapabilities.filterKeys { it in externalDataProviderIds }.values,
> ```

why do we need to filter here? Aren't they filtered above already? When wouldn't it already be present in externalDataProviderIds?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 500 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1b3bo4EGa2KemtjPm:-Nt1b3bo4EGa2KemtjPn:bi18ysc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5487bdf0f14c4fabb9073458c7355e939e0ba70/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L500)):*
> ```Kotlin
>           }
>         } else {
>           if (reachOnlyLlV2Enabled) {
> ```

don't we support Hmss for reach only, too?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 571 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1bV4g06LaSscJ3Vlf:-Nt1bV4g06LaSscJ3Vlg:b-ybcc4n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5487bdf0f14c4fabb9073458c7355e939e0ba70/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L571)):*
> ```Kotlin
>       }
>       MeasurementSpec.MeasurementTypeCase.POPULATION -> {
>         protocolConfig { direct = InternalProtocolConfig.Direct.getDefaultInstance() }
> ```

I believe for population, `deterministicCount` should be set.

**Review by renjiezh — APPROVED** [review]
> Reviewed 4 of 19 files at r1, 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 384 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1aNtI3XigB9B_i2lO:-Nt399gu1LaQwOSrkaB7:b-9q4x61) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L384)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why do we need to filter here? Aren't they filtered above already? When wouldn't it already be present in externalDataProviderIds?
</blockquote></details>

This function is for batch creation usage. `externalDataProviderIds` has all ids for multiple Measurements.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 500 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1b3bo4EGa2KemtjPm:-Nt360a0CDCsjde4CRGj:b6vd3qc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L500)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

don't we support Hmss for reach only, too?
</blockquote></details>

I will change the feature flag here so that `reach-only` Measurements uses hmss as well.

**Review by renjiezh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-:-Nt39Ufa-QIekE3iyfIz:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 384 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1aNtI3XigB9B_i2lO:-Nt39bfT2UAkOxbT8tIf:b-7ele4n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L384)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

This function is for batch creation usage. `externalDataProviderIds` has all ids for multiple Measurements.
</blockquote></details>

maybe add a comment around that. that was non-obvious to me at first glance.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 500 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1b3bo4EGa2KemtjPm:-Nt39jT61SpQL6puHC-U:b-84a9fb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L500)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I will change the feature flag here so that `reach-only` Measurements uses hmss as well.
</blockquote></details>

can't we go ahead and add it this pr? its already in this pr for r&f

**Review by renjiezh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 477 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt39brYBz4RqYCLYMMB:-Nt39brZ6PvEgBGPFKAy:b-q5trfj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L477)):*
> ```Kotlin
>   }
> 
>   private fun buildInternalProtocolConfig(
> ```

nit: what about moving this to ProtoConversion file?

**Review by renjiezh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 500 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1b3bo4EGa2KemtjPm:-Nt3A0NmDuUjta8cyTkU:b-jb8lbh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L500)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can't we go ahead and add it this pr? its already in this pr for r&f
</blockquote></details>

HMSS is still under implementing. The feature flag will only be ready  along with the executable class. A TODO here might help to resolve the confusion.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 477 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt39brYBz4RqYCLYMMB:-Nt3P5fd4T2efzoj5Ygf:b-2s5vyl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L477)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nit: what about moving this to ProtoConversion file?
</blockquote></details>

I actually moved this logic out of there intentionally to avoid having to pass instance state fields over (e.g. noiseMechanisms).

As an aside, I don't actually like the central ProtoConversions.kt file as it forces each service library target to depend on the protobufs for all of the services. IMO only the ones that need to be shared between services should be extracted to a common location.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 500 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1b3bo4EGa2KemtjPm:-Nt3QJUc68jEe4PrbBGc:b-6n8055) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L500)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

HMSS is still under implementing. The feature flag will only be ready  along with the executable class. A TODO here might help to resolve the confusion.
</blockquote></details>

@renjiezh I had thought HMSS was only for R/F. Does it have a different config for reach-only? If it's the same config, I can include it in this PR. If not, I'll leave a TODO.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 571 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1bV4g06LaSscJ3Vlf:-Nt3QI_N35IcJ_PQUlqP:b-bqivcu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L571)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I believe for population, `deterministicCount` should be set.
</blockquote></details>

Will fix.

**Review by renjiezh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 500 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1b3bo4EGa2KemtjPm:-Nt3RF5o-1EiHS9l6sZ3:b-f2hmh2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L500)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@renjiezh I had thought HMSS was only for R/F. Does it have a different config for reach-only? If it's the same config, I can include it in this PR. If not, I'll leave a TODO.
</blockquote></details>

It could be used for reach-only Measurement. The config is the same but the dp params is different (specified by MC though)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: 21 of 23 files reviewed, 2 unresolved discussions (waiting on @renjiezh and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 384 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1aNtI3XigB9B_i2lO:-Nt3RtYy3bCn1JZuQInq:b-xfavy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L384)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

maybe add a comment around that. that was non-obvious to me at first glance.
</blockquote></details>

Renamed to `allDataProviderCapabilities` paralleling `allExternalDataProviderIds`.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 500 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1b3bo4EGa2KemtjPm:-Nt3SXvi20nRyqi68sbn:b-lidx0n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L500)):*
Done.

> The config is the same but the dp params is different (specified by MC though)

I don't think that's relevant to this PR, as this is just concerned with the protocol config.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 571 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472#-Nt1bV4g06LaSscJ3Vlf:-Nt3RGQt5qLCLpPeBbD6:b-k16xx4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ad50a437be83e2186b757cc975b0176417bce6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L571)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Will fix.
</blockquote></details>

Done. Note that this is different than the code state prior to this PR, as the original code was extracted from ProtoConversions.kt

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 6 of 19 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1472)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
