### PR TITLE
Implement internal UpdateEventGroupMetadataDescriptor

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @robinsons)

___
*[src/main/proto/wfa/measurement/internal/kingdom/error_code.proto, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502#-MzPwcnCCwdvxs8EyJH9:-MzPwcnCCwdvxs8EyJHA:bumrvpq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/230a1f7cf4aa9f71a1255e633bf78efff8a7f21a/src/main/proto/wfa/measurement/internal/kingdom/error_code.proto#L69)):*
> ```protobuf
>   /** EventGroup modification args are invalid. */
>   EVENT_GROUP_INVALID_ARGS = 21;
>   /** EventGroupMetadataDescriptor modification args are invalid. */
> ```

is this the right comment? This error is thrown if its not found. It doesn't necessarily mean the args are invalid, right?

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502#-MzQde_W8sSBVKogj5nr:-MzQde_X6HeHM_ucBnxR:bb4kbck) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/230a1f7cf4aa9f71a1255e633bf78efff8a7f21a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel#L27)):*
> ```Starlark
>         "//imports/org/reflections",
>         "//src/main/proto/wfa/measurement/api/v2alpha:event_annotations_java_proto",
>         "@wfa_common_jvm//imports/java/com/google/common:guava",
> ```

Are you using this dep in this PR, or is it an artifact of your other PR?

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502#-MzQde_W8sSBVKogj5nr:-MzQmybPA6cnTb2FD10o:b-orwuel) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/230a1f7cf4aa9f71a1255e633bf78efff8a7f21a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel#L27)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Are you using this dep in this PR, or is it an artifact of your other PR?
</blockquote></details>

I think this is an artifact of my other PR, which might be changed in the near future. Do you think it should be changed in this PR?
___
*[src/main/proto/wfa/measurement/internal/kingdom/error_code.proto, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502#-MzPwcnCCwdvxs8EyJH9:-MzQnnhv09wHqXKoEXQS:bx9h6za) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/230a1f7cf4aa9f71a1255e633bf78efff8a7f21a/src/main/proto/wfa/measurement/internal/kingdom/error_code.proto#L69)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this the right comment? This error is thrown if its not found. It doesn't necessarily mean the args are invalid, right?
</blockquote></details>

Good catch - done.

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502#-MzQde_W8sSBVKogj5nr:-MzVu8LwBZlhiK_rihjh:bw6ubqs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/230a1f7cf4aa9f71a1255e633bf78efff8a7f21a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel#L27)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

I think this is an artifact of my other PR, which might be changed in the near future. Do you think it should be changed in this PR?
</blockquote></details>

I would only include changes that are relevant to this PR. If the template registry PR needs this, then it should be that PR which adds it.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502)* status: all files reviewed, 2 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502#-MzQde_W8sSBVKogj5nr:-MzWG2qKAnb7YQunnyws:b-s08gaz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/230a1f7cf4aa9f71a1255e633bf78efff8a7f21a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel#L27)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

I would only include changes that are relevant to this PR. If the template registry PR needs this, then it should be that PR which adds it.
</blockquote></details>

Acknowledged. Please let me know if there are any other comments or if this PR can be approved (and clear one of the tasks).

**Review by chipingyeh — COMMENTED** [review]
> Reviewed 14 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502)* status: all files reviewed, 2 unresolved discussions (waiting on @robinsons and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons)

**Review by robinsons — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by chipingyeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by chipingyeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/502)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Pull request merged**
