### PR TITLE
Add verbose logging for EDP simulator.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @Marco-Premier, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt` line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-NqiuB7K9Q5HE5PYEboD:-NqiuB7K9Q5HE5PYEboE:bf9brfu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ce98f208809420eb5a518925f5ee5fa08b3b492/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt#L112)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--verbose"],
> ```

We only need a flag to control logging of sensitive info (such as plaintext sketch), so be specific about that. Logging of more details that aren't necessarily sensitive can just be done at a more granular log level.

Therefore, this flag should be more specific so it's clear that it's about logging sensitive/plaintext info.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @renjiezh, and @stevenwarejones)

___
*[`src/main/k8s/edp_simulator.cue` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-NqiuazXBfNdqImm6Cg-:-NqiuazXBfNdqImm6Cg0:b65mn10) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ce98f208809420eb5a518925f5ee5fa08b3b492/src/main/k8s/edp_simulator.cue#L30)):*
> ```CUE
> 	_duchy_public_api_target:   string
> 	_kingdom_public_api_target: string
> 	_verboseSketchLogging:      bool | *false
> ```

Can we use Lever.FINE, FINER, or FINEST instead of introducing this flag?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 590 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-Nqiu4sFAPYYhBE9aL2Q:-Nqiu4sFAPYYhBE9aL2R:bsxx6g7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ce98f208809420eb5a518925f5ee5fa08b3b492/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L590)):*
> ```Kotlin
>           }
> 
>         if (verbose) {
> ```

Can we log this always?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 937 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-NqiuA90CAeS9PUTbELT:-NqiuA90CAeS9PUTbELU:b-dydsu3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ce98f208809420eb5a518925f5ee5fa08b3b492/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L937)):*
> ```Kotlin
> 
>   private fun logSketch(sketch: Sketch) {
>     logger.log(Level.INFO, "SketchConfig:\n${sketch.config}")
> ```

Can we always log these and log the registers under verbose mode?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1562 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-NqiuEpm1CuLa1F4m3vV:-NqiuEpm1CuLa1F4m3vW:b-meyg6g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ce98f208809420eb5a518925f5ee5fa08b3b492/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1562)):*
> ```Kotlin
>     measurementResult: Measurement.Result,
>   ) {
>     if (verbose) {
> ```

Can we always log these too?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @Marco-Premier, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 937 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-Nqiv3JC8_-vmbC0ioy7:-Nqiv3JC8_-vmbC0ioy8:b2nmysw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ce98f208809420eb5a518925f5ee5fa08b3b492/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L937)):*
> ```Kotlin
> 
>   private fun logSketch(sketch: Sketch) {
>     logger.log(Level.INFO, "SketchConfig:\n${sketch.config}")
> ```

Use logging method overloads that take a lambda for the message. That way the string isn't even built unless there's an associated handler for that log level.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/edp_simulator.cue` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-NqiuazXBfNdqImm6Cg-:-Nqj2a86B68_V7NlvBLT:b-d66ljt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ce98f208809420eb5a518925f5ee5fa08b3b492/src/main/k8s/edp_simulator.cue#L30)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can we use Lever.FINE, FINER, or FINEST instead of introducing this flag?
</blockquote></details>

I prefer to keeping use this flag. Renamed it into `log-sketch` with a warning message.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 590 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-Nqiu4sFAPYYhBE9aL2Q:-Nqj1Q6A6CTRKEAWnYsc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ce98f208809420eb5a518925f5ee5fa08b3b492/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L590)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can we log this always?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 937 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-Nqiv3JC8_-vmbC0ioy7:-Nqj1Vjs6uJclRqgnR7l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ce98f208809420eb5a518925f5ee5fa08b3b492/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L937)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use logging method overloads that take a lambda for the message. That way the string isn't even built unless there's an associated handler for that log level.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1562 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-NqiuEpm1CuLa1F4m3vV:-Nqj2ImW1hkpZ8vEOQP_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ce98f208809420eb5a518925f5ee5fa08b3b492/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1562)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can we always log these too?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt` line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-NqiuB7K9Q5HE5PYEboD:-Nqj2_1ND7DzSITPlz97:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ce98f208809420eb5a518925f5ee5fa08b3b492/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt#L112)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We only need a flag to control logging of sensitive info (such as plaintext sketch), so be specific about that. Logging of more details that aren't necessarily sensitive can just be done at a more granular log level.

Therefore, this flag should be more specific so it's clear that it's about logging sensitive/plaintext info.
</blockquote></details>

Done.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @Marco-Premier, @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 936 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-Nqj3cnV594KVDva9hYV:-Nqj3cnV594KVDva9hYW:b-1u0scp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3737a321706012ce4e3b259d4c258706cc2c8282/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L936)):*
> ```Kotlin
>   private fun logSketch(sketch: Sketch) {
>     logger.log(Level.INFO) { "SketchConfig:\n${sketch.config}" }
>     logger.log(Level.INFO) { "Registers Size:\n${sketch.registersList.size}" }
> ```

Can you move this and the line above it into the parent function, and maybe call this method logSketchDetails?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 936 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482#-Nqj3cnV594KVDva9hYV:-Nqj5ac1BOL5gFP7Rd1t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3737a321706012ce4e3b259d4c258706cc2c8282/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L936)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you move this and the line above it into the parent function, and maybe call this method logSketchDetails?
</blockquote></details>

Done.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1482)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
