### PR TITLE
Follow semantic conventions for OpenTelemetry instruments.

### PR DESCRIPTION
**Pull request by SanjayVas**
This reuses the OpenTelemetry instance created by the Java agent in code. This also switches to the `googlecloud` OpenTelemetry exporter on GKE, which avoids conversion loss from OpenTelemetry->Managed Prometheus->Cloud Monitoring.

Superfluous instruments were also dropped:
* `active_non_daemon_thread_count` - can be obtained from an existing default JVM instrument
* `stage_cpu_time_duration_millis` - this did not work correctly and is not really useful (it was measuring CPU time across all JVM threads)
* Instruments specific to a computation stage - dropped in favor of adding computation type and stage attributes

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1623)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1623)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by tristanvuong2021 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1623)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Comment by SanjayVas** [comment]
Depends on https://github.com/world-federation-of-advertisers/bazel-registry/pull/43

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 23 of 25 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1623)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`.github/actions/install-otel-operator/action.yml` line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1623#-NzdqQoK0M0bUoEJUROo:-NzdqQoK0M0bUoEJUROp:b-ccm7i8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a480118e0649ce03a4af36b096e9f5d257b2b1d2/.github/actions/install-otel-operator/action.yml#L39)):*
> ```YAML
>       for deployment in $(kubectl --namespace=opentelemetry-operator-system get deployments -o name); do
>         kubectl --namespace=opentelemetry-operator-system rollout status "$deployment" --timeout=5m
>       done
> ```

nit: missing newline

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 13 of 23 files at r1, 22 of 25 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1623)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
