### PR TITLE
fix: Fix type_url for EncryptionPublicKey.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1774)

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1774)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt` line 483 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1774#-O4qnxu89yx3c4koL7J_:-O4qnxu89yx3c4koL7Ja:b87egu5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57f0ceca5048b35809a75baf89ea1efcecf225d8/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L483)):*
> ```Kotlin
>           typeUrl =
>             when (apiVersion) {
>               Version.V2_ALPHA -> ProtoReflection.getTypeUrl(EncryptionPublicKey.getDescriptor())
> ```

Do we need to update the EDP simulator to check for the typeUrl as well?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1774)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @ple13, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt` line 483 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1774#-O4qnxu89yx3c4koL7J_:-O4qtbz23uVq2RgKxjSU:b-8m9vj8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57f0ceca5048b35809a75baf89ea1efcecf225d8/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L483)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Do we need to update the EDP simulator to check for the typeUrl as well?
</blockquote></details>

Done.
Updated in the EDP library to use unpack(), which will check the typeUrl.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1774)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @stevenwarejones)

**Review by ple13 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1774)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1774)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1774)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
