### PR TITLE
perf: Recreate metric reuse index

### PR DESCRIPTION
**Pull request by tristanvuong2021**
The current index isn't actually capable of being used and is leading to sequential scans. The new index along with the corresponding query changes allows the index to actually be used, cutting the execution time to 1/10th of what it is currently.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1949)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1949)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1949#-ODCZewD80tju6G6Vzym:-ODCZewE0XoyRVVhha2c:blsw4wk) (no related file):*
Could you add a little more information to the PR description body on why you're doing this?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 348 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1949#-ODCbHXp-oZEULsVMq36:-ODCbHXq6HM8Ow0tDQeA:b-goobkk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a72e608e2fc98797bda103eb5a321ff8c6a47ca4/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L348)):*
> ```Kotlin
>         .trimIndent()
> 
>     val sqlJoins: String =
> ```

nit: can this small string just be inlined? It looks like it's only used once
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 358 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1949#-ODCaOSy4TPhqrXTYCSv:-ODCaOSzAumjpetUvnvV:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a72e608e2fc98797bda103eb5a321ff8c6a47ca4/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L358)):*
> ```Kotlin
>       StringBuilder(
>         """
>           WITH ReusableMetricIDs AS (
> ```

nit



_Suggestion:_
```Kotlin
ReusableMetricIds
```
___
*[`src/main/resources/reporting/postgres/recreate-metric-reuse-index.sql` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1949#-ODCZsVI5Gl1_AbTBqI7:-ODCZsVI5Gl1_AbTBqI8:b-9g2b5k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a72e608e2fc98797bda103eb5a321ff8c6a47ca4/src/main/resources/reporting/postgres/recreate-metric-reuse-index.sql#L42)):*
> ```TSQL
> --           └── ReportsReportSchedules
> 
> -- changeset tristanvuong2021:drop-metrics-comparison-index dbms:postgresl
> ```

nit: You can do both operations as a single changeset

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1949)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1949#-ODCZewD80tju6G6Vzym:-ODClIiS3Tgd0YlcWATa:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Could you add a little more information to the PR description body on why you're doing this?
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1949)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1949)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
