### PR TITLE
Replace testing certificates which expire within 3 years.

### PR DESCRIPTION
**Pull request by SanjayVas**
Some of our testing certs were expired/expiring. This replaces them with ones that are valid for 10 years.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/643)

### CODE REVIEW

**Comment by SanjayVas** [comment]
Command to verify certificates:

```shell
bazel build //src/main/k8s/testing/secretfiles:gen_trusted_certs && openssl verify -attime 1722211428 -trusted bazel-bin/src/main/k8s/testing/secretfiles/all_root_certs.pem src/main/k8s/testing/secretfiles/*cs_cert.der src/main/k8s/testing/secretfiles/*.pem
```

Where the timestamp provided is Monday, July 29, 2024 12:03:48 AM UTC

**Review by matthewclegg — APPROVED** [review]
> Reviewed 73 of 73 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/643)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @tristanvuong2021)

**Review by matthewclegg — APPROVED** [review]
Thanks, Sanjay!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/643#-:-N8AMMf57m5ZM8ZIpZhV:b-vme7ab)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 73 of 73 files at r1, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/643)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Pull request merged**
