### PR TITLE
Refactor kingdom internal exception

### PR DESCRIPTION
**Pull request by renjiezh**
https://docs.google.com/document/d/1BHhO6gRgMPtlLHQSzc1rhS8hVWfn0BJF_gXU3T-cXio/edit#

1. KingdomInternalException is now a sealed class. Each error code has 1 or more derivative class to create the instance of internal exception with required contextual information.
For example, 
`MEASUREMENT_CONSUMER_NOT_FOUND` has one class `MeasurementConsumerNotFound` requiring `externalMeasurementConsumerId` as context info
`MEASUREMENT_NOT_FOUND` has two classes: `MeasurementNotFoundByComputation` requires `externalComputationId`; `MeasurementNotFoundByMeasurementConsumer` requires `externalMeasurementConsumerId` and `externalMeasurementId`.
`CERITIFICATE_NOT_FOUND` is complicated. It has `DataProviderCertificateNotFoundByExternal`, `DataProviderCertificateNotFoundByInternal`, `MeasurementConsumerCertificateNotFoundByExternal`, `MeasurementConsumerCertificateNotFoundByInternal` and `DuchyCertificateNotFound`.  (Please share your thought if any other idea)

2. Applied the new mechanism to exception throwers.
In .../spanner/writers/ConfirmComputationParticipant.kt, one of the errors should be `MeasurementStateIllegal` in stead of `ComputationParticipantStateIllegal`. 

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)* status: 2 of 36 files reviewed, 4 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0CPa2S5ntX0Eb9z7KE:-N0CPa2TA-35EeABslry:bs799im) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eb74440191e305947b4aad8e620e83469a918f38/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L32)):*
> ```Kotlin
> sealed class KingdomInternalException : Exception {
>   val code: ErrorCode
>   abstract val context: Map<String, String>
> ```

`protected`, as nothing outside of KingdomInternalException should be able to access this.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 48 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0CPt8C2akd3RTYU-Sb:-N0CPt8C2akd3RTYU-Sc:b-mzvhwk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eb74440191e305947b4aad8e620e83469a918f38/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L48)):*
> ```Kotlin
> }
> 
> private fun throwStatusRuntimeException(
> ```

This is unnecessary. Should just be a method inside of KingdomInternalException, as nothing outside should be able to access the context map.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0CRVdP5NzzLW44NNKd:-N0CRVdP5NzzLW44NNKe:b-kacp2w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eb74440191e305947b4aad8e620e83469a918f38/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L71)):*
> ```Kotlin
> }
> 
> class MeasurementConsumerNotFound(
> ```

nit: by convention, all exception types end in `Exception`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 197 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0CQjwq20LZXRKZhiO4:-N0CQjwq20LZXRKZhiO5:b-klvia0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eb74440191e305947b4aad8e620e83469a918f38/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L197)):*
> ```Kotlin
>     get() =
>       mapOf(
>         "internal_measurement_consumer_id" to internalMeasurementConsumerId.toString(),
> ```

Internal IDs must not be exposed outside of the internal service, so must not be included in gRPC exceptions.



_Code quote:_
```Kotlin
"internal_measurement_consumer_id" to internalMeasurementConsumerId.toString(),
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)* status: 1 of 40 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0CPa2S5ntX0Eb9z7KE:-N0CjGk6-JTJuGizJTEC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eb74440191e305947b4aad8e620e83469a918f38/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`protected`, as nothing outside of KingdomInternalException should be able to access this.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 48 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0CPt8C2akd3RTYU-Sb:-N0CjPadBSuWOh3kLsnY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eb74440191e305947b4aad8e620e83469a918f38/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is unnecessary. Should just be a method inside of KingdomInternalException, as nothing outside should be able to access the context map.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 197 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0CQjwq20LZXRKZhiO4:-N0Cjr799iX6QouVbbr9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eb74440191e305947b4aad8e620e83469a918f38/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L197)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Internal IDs must not be exposed outside of the internal service, so must not be included in gRPC exceptions.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 34 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)* status: 3 of 40 files reviewed, 3 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 156 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0WwyXA25T32HZ-PJHs:-N0WwyXBB_-HhXJkinry:bx3wh24) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3a9929026fbc2f3a512e718c1b4f2a6498cb59d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L156)):*
> ```Kotlin
> }
> 
> class DataProviderCertificateNotFoundByInternalException(
> ```

See if we can drop the "ByInternal" variants of these exceptions. Since we can't expose the internal ID, this is not really useful to the user. There's also not a meaningful difference between not found by internal vs. external, as usually we're doing an external -> internal lookup first. Finding by external vs. internal are equivalent: it doesn't matter which one you do, as both will succeed or fail under the same conditions.



_Code quote:_
```Kotlin
ByInternal
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt` line 211 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0Ww67I7OPnkq8Unj_z:-N0Ww67I7OPnkq8Unja-:b-ulkpy4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3a9929026fbc2f3a512e718c1b4f2a6498cb59d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L211)):*
> ```Kotlin
>   ) {
>     for ((externalDataProviderId, dataProviderValue) in dataProvidersMap) {
>       val dataProviderId = readDataProviderId(ExternalId(externalDataProviderId))
> ```

If you push this read down into insertRequisition, we can use the more useful exception with external ID.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdatePublicKey.kt` line 64 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0WwW6q-_9L0g4utnx7:-N0WwW6q-_9L0g4utnx8:bag88d3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3a9929026fbc2f3a512e718c1b4f2a6498cb59d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdatePublicKey.kt#L64)):*
> ```Kotlin
>           ExternalId(request.externalCertificateId)
>         )
>         ?: throw MeasurementConsumerCertificateNotFoundByInternalException(
> ```

We have the external measurement consumer ID above this, so can use the more useful exception type.



_Code quote:_
```Kotlin
MeasurementConsumerCertificateNotFoundByInternalException
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)* status: 3 of 40 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 156 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0WwyXA25T32HZ-PJHs:-N0XD6mF4JTT_AxyjB6_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3a9929026fbc2f3a512e718c1b4f2a6498cb59d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L156)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

See if we can drop the "ByInternal" variants of these exceptions. Since we can't expose the internal ID, this is not really useful to the user. There's also not a meaningful difference between not found by internal vs. external, as usually we're doing an external -> internal lookup first. Finding by external vs. internal are equivalent: it doesn't matter which one you do, as both will succeed or fail under the same conditions.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt` line 211 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0Ww67I7OPnkq8Unj_z:-N0XD84m54a_9GM9W9eJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3a9929026fbc2f3a512e718c1b4f2a6498cb59d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L211)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you push this read down into insertRequisition, we can use the more useful exception with external ID.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdatePublicKey.kt` line 64 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0WwW6q-_9L0g4utnx7:-N0XD9bL5uy280_FmQG3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3a9929026fbc2f3a512e718c1b4f2a6498cb59d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdatePublicKey.kt#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We have the external measurement consumer ID above this, so can use the more useful exception type.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 32 files at r1, 13 of 34 files at r4, 2 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)* status: 19 of 40 files reviewed, 9 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 170 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0XYGOq2AWV7dsZVhOW:-N0XYGOq2AWV7dsZVhOX:b-hr0lt5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c57855dad13e65ef580cedca9719ca4e3ae468b9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L170)):*
> ```Kotlin
> 
> class DuchyCertificateNotFoundException(
>   val internalDuchyId: InternalId,
> ```

Drop this param



_Code quote:_
```Kotlin
val internalDuchyId: InternalId,
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt` line 87 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0XYoB4BC8xPciPmrv8:-N0XYoB4BC8xPciPmrv9:bkjlwx7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c57855dad13e65ef580cedca9719ca4e3ae468b9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L87)):*
> ```Kotlin
>           )
>           ?.dataProviderId
>           ?: throw DataProviderNotFoundException(ExternalId(certificate.externalDataProviderId))
> ```

nit: extract variable since this is used in more than one place in this function.



_Code quote:_
```Kotlin
ExternalId(certificate.externalDataProviderId)
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt` line 96 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0XYx-l-Ju9POGuAYvN:-N0XYx-l-Ju9POGuAYvO:b-5168x7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c57855dad13e65ef580cedca9719ca4e3ae468b9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L96)):*
> ```Kotlin
>           ?.measurementConsumerId
>           ?: throw MeasurementConsumerNotFoundException(
>             ExternalId(certificate.externalMeasurementConsumerId)
> ```

nit: extract variable



_Code quote:_
```Kotlin
ExternalId(certificate.externalMeasurementConsumerId)
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt` line 211 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0Ww67I7OPnkq8Unj_z:-N0XZHYk-R4Q8LydN3QX:bevwhri) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3a9929026fbc2f3a512e718c1b4f2a6498cb59d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L211)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I had suggested pushing the external->internal mapping down into the other function. No function should take in both the internal and external.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt` line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0XZi6OCHqIetpSCHvE:-N0XZi6OCHqIetpSCHvF:b-nb5wqt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c57855dad13e65ef580cedca9719ca4e3ae468b9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt#L28)):*
> ```Kotlin
> /**
>  * Checks that a given Measurement Consumer certificate is valid and returns its ID.
>  * @throws KingdomInternalException if not found or invalid.
> ```

nit: change this to note the specific exceptions and conditions.



_Code quote:_
```Kotlin
@throws KingdomInternalException if not found or invalid.
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt` line 48 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0XZqA86J6z5-TlgjUd:-N0XZqA86J6z5-TlgjUe:b-dy5kjm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c57855dad13e65ef580cedca9719ca4e3ae468b9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt#L48)):*
> ```Kotlin
>   }
>     ?: throw MeasurementConsumerCertificateNotFoundException(
>       ExternalId(measurementConsumerId),
> ```

nit: extract variables



_Code quote:_
```Kotlin
ExternalId(measurementConsumerId)
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalExceptionTest.kt` line 55 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0X_B360wcJDPLegQJb:-N0X_B360wcJDPLegQJc:b-18hxmb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c57855dad13e65ef580cedca9719ca4e3ae468b9/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalExceptionTest.kt#L55)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> class KingdomInternalExceptionTest {
> ```

These tests aren't particularly valuable due to testing something so simple. As a result, they end up functioning as [change-detector tests](https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html).

This code should get inherently exercised by other tests. e.g. updating the tests for code that throws the exceptions to verify the specifics.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalExceptionTest.kt` line 74 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0X_Lpq4aFn5QH9iGrt:-N0X_Lpq4aFn5QH9iGru:bt0zdre) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c57855dad13e65ef580cedca9719ca4e3ae468b9/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalExceptionTest.kt#L74)):*
> ```Kotlin
> 
>   @Test
>   fun `MeasurementConsumerNotFound works as expected`() {
> ```

We shouldn't have tests that just say "works as expected" (the ones that currently exist in the codebase should be rewritten). Instead, the test function name should be specific about which behaviors it's verifying.



_Code quote:_
```Kotlin
 works as expected
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)* status: 5 of 53 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 170 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0XYGOq2AWV7dsZVhOW:-N0XdZOK5gP1DiD29aN8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c57855dad13e65ef580cedca9719ca4e3ae468b9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L170)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop this param
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt` line 211 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0Ww67I7OPnkq8Unj_z:-N0XfzWu80xBbQe_ioW5:b-tcg4xw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3a9929026fbc2f3a512e718c1b4f2a6498cb59d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L211)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I had suggested pushing the external->internal mapping down into the other function. No function should take in both the internal and external.
</blockquote></details>

Done. Oh yes, I was stupid.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalExceptionTest.kt` line 55 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0X_B360wcJDPLegQJb:-N0XrLcb6DRCQrHuHX8C:br8o74o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c57855dad13e65ef580cedca9719ca4e3ae468b9/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalExceptionTest.kt#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These tests aren't particularly valuable due to testing something so simple. As a result, they end up functioning as [change-detector tests](https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html).

This code should get inherently exercised by other tests. e.g. updating the tests for code that throws the exceptions to verify the specifics.
</blockquote></details>

Let me delete the tests and verify them when applying functions to throwers in the next PR.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalExceptionTest.kt` line 74 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N0X_Lpq4aFn5QH9iGrt:-N0XrWJPB5fGYXdl9TZS:b-k7mx7q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c57855dad13e65ef580cedca9719ca4e3ae468b9/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalExceptionTest.kt#L74)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We shouldn't have tests that just say "works as expected" (the ones that currently exist in the codebase should be rewritten). Instead, the test function name should be specific about which behaviors it's verifying.
</blockquote></details>

Deleted.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 32 files at r1, 23 of 34 files at r4, 1 of 9 files at r5, 7 of 10 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 15 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N14kO73BmTi1Q_OOleA:-N14kO73BmTi1Q_OOleB:b8hoh5a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/099ddc2b2ac6c87acfaabef5f5a02804310298cc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.kingdom.deploy.gcloud.spanner.common
> ```

Putting all of the errors in one file makes for a problematic dependency issue.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 15 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537#-N14kO73BmTi1Q_OOleA:-N14nB3g8sysoaqJJYve:b-1mwpzh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/099ddc2b2ac6c87acfaabef5f5a02804310298cc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L15)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Putting all of the errors in one file makes for a problematic dependency issue. 
</blockquote></details>

Can you elaborate? It's currently a necessity for using `sealed` classes in this version of Kotlin, and in a later version it's only relaxed to being defined in the same package.

**Review by chipingyeh — APPROVED** [review]
> Reviewed 2 of 32 files at r1, 23 of 34 files at r4, 1 of 9 files at r5, 7 of 10 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 2 of 32 files at r1, 23 of 34 files at r4, 1 of 9 files at r5, 6 of 10 files at r6, 1 of 1 files at r7, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

**Review by renjiezh — COMMENTED** [review]
> Dismissed @kungfucraig from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/537)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Pull request merged**
