### PR TITLE
Allow ResourceSetup to retry its first request to the Kingdom

### PR DESCRIPTION
**Pull request by matthewclegg**
The resource-setup-job is typically executed immediately after the deployment of gcp-kingdom-data-server, and resource-setup-job depends on gcp-kingdom-data-server because it makes requests to it in order to obtain various configuration values.  However, gcp-kingdom-data-server often takes significantly longer to initialize than resource-setup-job.  This can cause the resource-setup-job to timeout and fail, which then breaks the deployment.  This patch allows the resource-setup-job to perform multiple retries of its first request to gcp-kingdom-data-server, so this potential breakage is avoided.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601)

### CODE REVIEW

**Review by matthewclegg — COMMENTED** [review]
Thank you for pointing me to that.  Is it the case that PR 505 simply causes the resource-setup-job to wait until gcp-kingdom-data-server enters the running state?  If so, unfortunately that is not sufficient.  I have observed numerous instances where resource-setup-job fails when launched after gcp-kingdom-data-server enters the running state.  Evidently gcp-kingdom-data-server has some internal setup that it needs to do.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-:-N4cVjiT2Vt6MAb1UmpW:bhwfe9e)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @iverson52000 and @uakyol)

**Review by SanjayVas — COMMENTED** [review]
Not just running, but ready. This means that the health check succeeds, which cannot happen until the server is fully ready and able to receive requests. See where the health status is set in [CommonServer.start](https://github.com/world-federation-of-advertisers/common-jvm/blob/4a99a9f174ea268e9e25e6adbced2e32c0a9796d/src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt#L52)

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-:-N4cbaPI2BpSd_H1NvuK:b-1jzn9b)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @iverson52000 and @uakyol)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @matthewclegg, and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N4ccFAS7gnfoRWNOO5c:-N4ccFAS7gnfoRWNOO5d:b-z83fo6) (no related file):*
Moving this to a blocking comment. #505 should handle what's needed.

If for some reason the Kingdom data server is indicating that it's ready when it isn't, that's a bug that should be addressed there by ensuring it's actually ready before calling `CommonServer.start`.

___

**Review by matthewclegg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N4ccFAS7gnfoRWNOO5c:-N51d58cCeeoTXmiCgir:b-40cl5j) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

See also #449, where resource setup retries were intentionally disabled, as it's not actually retriable in the case of partial success. Any retry needs to be done manually by deleting and recreating the job, as the user has to manually verify that it's retriable (i.e. no partial success). Otherwise, the user needs to first clear out the DB entries that would otherwise conflict.
</blockquote></details>

Per our offline conversation, I have updated the code to make a more stringent check of the status code returned by gRPC in the event that it fails.

___

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @iverson52000 and @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 141 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N56_yrSD50mBsoTBb7y:-N56_yrSD50mBsoTBb7z:b-3hw40d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6a6e2c5131006813ef6aaf2128ad36a319a1ec3/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L141)):*
> ```Kotlin
>   ): MeasurementConsumerAndKey {
>     // The initial account is created via the Kingdom Internal API by the Kingdom operator.
>     // This is our first attempt to contact the Kingdom.  If it fails, we will retry it.
> ```

Move the retry functionality into `process` so it's clear we're doing it on the first call rather than relying on the fact that we know `createMeasurementConsumer` is called first.



_Code quote:_
```Kotlin
// This is our first attempt to contact the Kingdom.
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N56_Qz94fB93Y1-QyXM:-N56_QzA5Ezf_2blVpy0:bqild0j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6a6e2c5131006813ef6aaf2128ad36a319a1ec3/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L142)):*
> ```Kotlin
>     // The initial account is created via the Kingdom Internal API by the Kingdom operator.
>     // This is our first attempt to contact the Kingdom.  If it fails, we will retry it.
>     // This is to allow the Kingdom more time to start up.
> ```

Add  TODO to remove this when we properly ensure that this isn't run until the Kingdom is ready to receive requests.

That's still the proper fix, we just apparently haven't gotten it working yet.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 144 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N56Zd_XAfvAQDPSrEtf:-N56Zd_XAfvAQDPSrEtg:b-enqtoz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6a6e2c5131006813ef6aaf2128ad36a319a1ec3/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L144)):*
> ```Kotlin
>     // This is to allow the Kingdom more time to start up.
>     var internalAccount: InternalAccount
>     var retryCount = 0
> ```

kotlinx.coroutines.flow has built-in `retry` and `retryWhen` extensions. See https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/retry.html

e.g. something like

```kotlin
val internalAccount = flow {
  emit(internalAccountsClient.createAccount(internalAccount {}))
}.retry(maxRetryCount) { e ->
  isRetriable(e).also { if (it) delay(sleepIntervalMillis) }
}.single()
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 162 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N56Z57W7--yBzGViCdp:-N56Z57W7--yBzGViCdq:b-uy6reg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6a6e2c5131006813ef6aaf2128ad36a319a1ec3/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L162)):*
> ```Kotlin
>             "Retrying in ${sleepIntervalMillis / 1000} seconds ..."
>         )
>         Thread.sleep(sleepIntervalMillis)
> ```

You don't want to use `Thread.sleep` when using coroutines. The coroutine equivalent is `delay`.



_Code quote:_
```Kotlin
Thread.sleep(sleepIntervalMillis)
```

**Review by matthewclegg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @iverson52000 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 141 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N56_yrSD50mBsoTBb7y:-N5BQJTiD8LV-LgShF9q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6a6e2c5131006813ef6aaf2128ad36a319a1ec3/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move the retry functionality into `process` so it's clear we're doing it on the first call rather than relying on the fact that we know `createMeasurementConsumer` is called first.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N56_Qz94fB93Y1-QyXM:-N5BRzob9ITgNkxz_qGW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6a6e2c5131006813ef6aaf2128ad36a319a1ec3/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L142)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add  TODO to remove this when we properly ensure that this isn't run until the Kingdom is ready to receive requests.

That's still the proper fix, we just apparently haven't gotten it working yet.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 144 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N56Zd_XAfvAQDPSrEtf:-N5BS-hIBnBHROh1r9uF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6a6e2c5131006813ef6aaf2128ad36a319a1ec3/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L144)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

kotlinx.coroutines.flow has built-in `retry` and `retryWhen` extensions. See https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/retry.html

e.g. something like

```kotlin
val internalAccount = flow {
  emit(internalAccountsClient.createAccount(internalAccount {}))
}.retry(maxRetryCount) { e ->
  isRetriable(e).also { if (it) delay(sleepIntervalMillis) }
}.single()
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 162 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N56Z57W7--yBzGViCdp:-N5BS0k47x6DNufJqspB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6a6e2c5131006813ef6aaf2128ad36a319a1ec3/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L162)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You don't want to use `Thread.sleep` when using coroutines. The coroutine equivalent is `delay`.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601)* status: all files reviewed, 3 unresolved discussions (waiting on @iverson52000 and @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N5BTTsx8TjaTcbrOAkF:-N5BTTsx8TjaTcbrOAkG:b-fsckzy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5689a6765db1d22d396f56534ea27a21351a5bf/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L63)):*
> ```Kotlin
> private val API_VERSION = Version.V2_ALPHA
> 
> // Maximum number of times that we will retry the first request to the Kingdom.
> ```

Use KDoc syntax for properties.

See https://developer.android.com/kotlin/style-guide#documentation
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N5BTOsoAXk3FgcAKuh-:-N5BTOsoAXk3FgcAKuh0:b1b4dc5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5689a6765db1d22d396f56534ea27a21351a5bf/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L68)):*
> ```Kotlin
> // time to launch.  Therefore, the first few attempts to communicate with the
> // Kingdom may fail because it is still initializing.
> private const val maxRetryCount = 30L
> ```

Use UPPER_SNAKE_CASE for constants.

See https://developer.android.com/kotlin/style-guide#constant_names



_Code quote:_
```Kotlin
maxRetryCount
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 169 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N5BS_rv5eZhTZTRqRVS:-N5BS_rv5eZhTZTRqRVT:b-g2h5pl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5689a6765db1d22d396f56534ea27a21351a5bf/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L169)):*
> ```Kotlin
>   }
> 
>   fun isRetriable(e: Throwable) =
> ```

This can be a [local function](https://kotlinlang.org/docs/functions.html#local-functions) defined inside of `createAccountWithRetries` since that's the only place it's referenced and/or valid.

**Review by matthewclegg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @iverson52000 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N5BTTsx8TjaTcbrOAkF:-N5BWuYNCG-UXYZqWdlg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5689a6765db1d22d396f56534ea27a21351a5bf/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use KDoc syntax for properties.

See https://developer.android.com/kotlin/style-guide#documentation
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N5BTOsoAXk3FgcAKuh-:-N5BWuzB-gKMMdoHuZXJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5689a6765db1d22d396f56534ea27a21351a5bf/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L68)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use UPPER_SNAKE_CASE for constants.

See https://developer.android.com/kotlin/style-guide#constant_names
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 169 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-N5BS_rv5eZhTZTRqRVS:-N5BWvnm58l2gmpRPwLI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5689a6765db1d22d396f56534ea27a21351a5bf/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L169)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This can be a [local function](https://kotlinlang.org/docs/functions.html#local-functions) defined inside of `createAccountWithRetries` since that's the only place it's referenced and/or valid.
</blockquote></details>

Done.

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by matthewclegg — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601#-:-N5CStCK-QHrCqcxYcd4:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @matthewclegg)

**Review by matthewclegg — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/601)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Pull request merged**
