### PR TITLE
model line public api

### PR DESCRIPTION
**Pull request by Marco-Premier**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 153 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012#-NVkaf404ZicRFLPpfLr:-NVkaf404ZicRFLPpfLs:bjse8po) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49a6c11286eb19de40a56c7928052c580a8053f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L153)):*
> ```Kotlin
>       RequisitionsService(InternalRequisitionsCoroutineStub(channel))
>         .withPrincipalsFromX509AuthorityKeyIdentifiers(principalLookup)
>         .withApiKeyAuthenticationServerInterceptor(internalApiKeysCoroutineStub),
> ```

nit: I forgot to mention this earlier, but the withApiKeyAuthenticationServerInterceptor doesn't do anything if there isn't anything a measurementConsumerPrincipal can access.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelLinesService.kt` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012#-NVoJMPN27i4b3-2CL02:-NVoJMPN27i4b3-2CL03:bpa22ap) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49a6c11286eb19de40a56c7928052c580a8053f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelLinesService.kt#L22)):*
> ```Kotlin
> import java.time.Clock
> import kotlinx.coroutines.flow.Flow
> import kotlinx.coroutines.flow.map
> ```

What are the changes involving "e.message ?:" for
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelLinesService.kt` line 215 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012#-NVoDR010rh0lyh9gCKJ:-NVoDR010rh0lyh9gCKK:b-k9ycul) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49a6c11286eb19de40a56c7928052c580a8053f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelLinesService.kt#L215)):*
> ```Kotlin
>             lastModelLine = previousPageEnd {
>               createTime = results[results.lastIndex - 1].createTime
>               externalModelLineId = results[results.lastIndex - 1].externalModelLineId
> ```

Missing externalModelSuiteId and externalModelProviderId for previousPageEnd
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelLinesServiceTest.kt` line 143 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012#-NVoNgDKAUt03dusKeWE:-NVoNgDKAUt03dusKeWF:b61vcdv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49a6c11286eb19de40a56c7928052c580a8053f/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelLinesServiceTest.kt#L143)):*
> ```Kotlin
>         .thenAnswer {
>           val request = it.getArgument<InternalModelLine>(0)
>           if (request.externalModelSuiteId != 123L) {
> ```

Where is this 123L from. If it is one of the externalModelSuiteId constants, should just use that instead

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 12 of 16 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto` line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012#-NW9OfHj-7X0uxwTeebZ:-NW9OfHj-7X0uxwTeeb_:b-ta317k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ba761e11d88f6034e59519c19b7192e2addb60df/src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto#L39)):*
> ```protobuf
> message StreamModelLinesRequest {
>   message AfterFilter {
>     fixed64 external_model_provider_id = 1;
> ```

i don't think we're allowing renumbering - please add these as 3,4 fields

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 4 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto` line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012#-NW9OfHj-7X0uxwTeebZ:-NW9brE2CPYEKVgJ9ph0:b-q9ffw2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ba761e11d88f6034e59519c19b7192e2addb60df/src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto#L39)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i don't think we're allowing renumbering - please add these as 3,4 fields
</blockquote></details>

Whether we allow renumbering depends on whether the message is persisted and whether it's being used yet.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 12 of 16 files at r1, 3 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1012)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
