### PR TITLE
Add GetExchangeStep classes to retrieve an ExchangeStep

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 402 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146#-MeWKeT0CJblxUPsB7dj:-MeWKeT0CJblxUPsB7dk:b-jhgan6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49f3466a8bc8af0b5a80dd836fa41eef81f09e11/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L402)):*
> ```Kotlin
>   ) {
>     write(
>       Mutation.newInsertBuilder("ExchangeSteps")
> ```

Can you please use this? https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt#L117

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 402 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146#-MeWKeT0CJblxUPsB7dj:-MeWW_hU9-jXwqdbwehj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49f3466a8bc8af0b5a80dd836fa41eef81f09e11/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L402)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you please use this? https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt#L117
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146#-MecABEwB5DgX9G3fLbp:-MecABExAVV8xAfCiCvC:b-ljma8r) (no related file):*
It seems like this revision is undoing a lot of the changes you did before. I just want to confirm that's intentional

---

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: 1 of 80 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/BUILD.bazel, line 13 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146#-MefkhCb6SBFxhXJb25t:-MefkhCb6SBFxhXJb25u:b-kcc37a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea56d856b01d42636569d9f5f7541b5ea1559470/src/main/kotlin/org/wfanet/measurement/common/identity/BUILD.bazel#L13)):*
> ```Starlark
>     deps = [
> <<<<<<< HEAD
> <<<<<<< HEAD
> ```

Something went wrong here.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3, 23 of 74 files at r7, 3 of 7 files at r8, 57 of 57 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: all files reviewed, 2 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt, line 304 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146#-Mehc0BSArHy6o5li_0v:-Mehc0BSArHy6o5li_0w:btuy3gi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9a9d9183f833279c80737baeed497d75b5944083/src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt#L304)):*
> ```Kotlin
> 
> private fun <V> ExternalId?.ifNotNull(block: (ExternalId) -> V): V? =
>   this?.let { if (it.value.compareTo(0L) == 0) null else block(it) }
> ```

How is `it.value.compareTo(0) == 0` different from `it.value == 0`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 402 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146#-MehcOyU02xwygM_4tSd:-MehcOyU02xwygM_4tSe:b-x7nuot) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9a9d9183f833279c80737baeed497d75b5944083/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L402)):*
> ```Kotlin
>   ) {
>     write(
>       Mutation.newInsertBuilder("ExchangeSteps")
> ```

Use `insertMutation`?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: 79 of 84 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt, line 304 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146#-Mehc0BSArHy6o5li_0v:-MekRzJw5imCpJyaQMcM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9a9d9183f833279c80737baeed497d75b5944083/src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt#L304)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How is `it.value.compareTo(0) == 0` different from `it.value == 0`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 402 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146#-MehcOyU02xwygM_4tSd:-MekRtfrB9SR1YEAPs8-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9a9d9183f833279c80737baeed497d75b5944083/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L402)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Use `insertMutation`?
</blockquote></details>

Done.

**Comment by yunyeng** [comment]
FYI, rebase for the previous commits failed. I edited GetExchangeStep class to accept filters now so it can be used in multiple purposes. e.g. to retrieve ExchangeStep either primary keys or just Model/Data provider ids.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt, line 304 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146#-MekTLAS3gSEsnBRGlWk:-MekTLATCrn09_Mftm7X:bbv7ocj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a7e28284f3b7a293ac58778fdb5fe07a3f9d2c7/src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt#L304)):*
> ```Kotlin
> 
> private fun <V> ExternalId?.ifNotNull(block: (ExternalId) -> V): V? =
>   this?.let { if (it.value == 0L) null else block(it) }
> ```

Of out curiosity, why do we need this comparison at all? Like, we can't we just use `this?.let { block(it) }`? Is there a reason to think that we'll get `ExternalId`s with a zero in them?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: 83 of 84 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt, line 304 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146#-MekTLAS3gSEsnBRGlWk:-Mekbb6j3f9CZONSvtKX:bhhkqdp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a7e28284f3b7a293ac58778fdb5fe07a3f9d2c7/src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt#L304)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Of out curiosity, why do we need this comparison at all? Like, we can't we just use `this?.let { block(it) }`? Is there a reason to think that we'll get `ExternalId`s with a zero in them?
</blockquote></details>

Since ExternalId does not allow value 0 we shouldn't need this check. Removed

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt, line 306 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146#-Mel5JcnDTPe4dQdroi3:-Mel5JcnDTPe4dQdroi4:b-1dnmuu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7fba4ba06d4e70754301a250508f1be068290209/src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt#L306)):*
> ```Kotlin
> 
> private fun <V> Long?.ifNotNull(block: (Long) -> V): V? =
>   this?.let { if (it == 0L) null else block(it) }
> ```

I guess I'll ask my question again for Long. Why are we converting 0L into null?

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
