### PR TITLE
Add the workflow deploy-duchy.

### PR DESCRIPTION
**Pull request by wfa-hkawalkar**
workflow meant for deploying duchy.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/914)

**Comment by wfa-hkawalkar** [comment]
Adding this PR as old create-duchy file is deleted from main which was merged using PR 897.

**Review by wfa-siyengar — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/914)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl and @wfa-hkawalkar)

**Review by wfa-siyengar — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/914)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl and @SanjayVas)

___
*[`.github/workflows/deploy-duchy.yml` line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/914#-NRiTslqBjDuz5jqWHK7:-NRii94y6ZMOZ1f_WL4c:b-47ddrb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61ad53762ff1ebd21c0aa331d2e0d7c242e34b6f/.github/workflows/deploy-duchy.yml#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add a TODO to build and apply K8s object configurations.
</blockquote></details>

Added TODO as requested.

**Review by wfa-siyengar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/914#-:-NRirVpx6KVnib6svfKu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl and @SanjayVas)

**Review by bdomen-ggl — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/914)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Pull request merged**
