### PR TITLE
Fix bug in findReadyExchangeSteps

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @efoxepstein)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, line 507 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382#-Mp80l0A8tl5wJSrq8uV:-Mp80l0A8tl5wJSrq8uW:b-joay98) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13f4d80ef5d0bfded41a438f99654bd607582cec/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt#L507)):*
> ```Kotlin
>     attemptNo: Int = 1,
>     stepProvider: Provider = PROVIDER,
>     stepInd: Int = STEP_INDEX
> ```

`stepIndex` please (you will then need to use `this.stepIndex` on the left-hand side below

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, line 507 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382#-Mp80l0A8tl5wJSrq8uV:-Mp89EcY0HCkvM4_Ud9w:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13f4d80ef5d0bfded41a438f99654bd607582cec/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt#L507)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`stepIndex` please (you will then need to use `this.stepIndex` on the left-hand side below
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382)* status: all files reviewed, 2 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 187 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382#-Mp89JkSEkWQtyq_mqJO:-Mp89JkT2C3bj5pCndbR:b-a8gv4m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/395f9971e5bda29318ee7abc455d54fb8fc60610/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L187)):*
> ```Kotlin
>     return workflow.stepsList
>       .filter { step -> !completedStepIndexes.contains(step.stepIndex) }
>       .filter { step ->
> ```

Combine into one filter?

```
.filter { step ->
  step.stepIndex !in completedStepIndexes &&
  step.prerequisiteStepIndicesCount > 0 &&
  step.prerequisiteStepIndicesList.all { it in completedStepIndexes }
}
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, line 287 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382#-Mp89gdZES1Hv-2oU7NA:-Mp89gdZES1Hv-2oU7NB:b-y8pyp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/395f9971e5bda29318ee7abc455d54fb8fc60610/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt#L287)):*
> ```Kotlin
>           RECURRING_EXCHANGE.details.copy {
>             exchangeWorkflow =
>               exchangeWorkflow {
> ```

Consider a helper function like:

```
private fun ExchangeWorkflowKt.Dsl.addNextStep(party, prerequisites: Iterable<Int>) {
  steps += step {
    stepIndex = steps.size + 1
    this.party = party
    prerequisiteStepIndices += prerequisites
  }
}
```

so that here you can have:

```
exchangeWorkflow {
  addNextStep(MODEL_PROVIDER, emptyList())
  addNextStep(MODEL_PROVIDER, listOf(3))
  addNextStep(MODEL_PROVIDER, listOf(2))
}
```

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, line 287 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382#-Mp89gdZES1Hv-2oU7NA:-Mp8JuI-A4UOolZmkoc2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/395f9971e5bda29318ee7abc455d54fb8fc60610/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt#L287)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Consider a helper function like:

```
private fun ExchangeWorkflowKt.Dsl.addNextStep(party, prerequisites: Iterable<Int>) {
  steps += step {
    stepIndex = steps.size + 1
    this.party = party
    prerequisiteStepIndices += prerequisites
  }
}
```

so that here you can have:

```
exchangeWorkflow {
  addNextStep(MODEL_PROVIDER, emptyList())
  addNextStep(MODEL_PROVIDER, listOf(3))
  addNextStep(MODEL_PROVIDER, listOf(2))
}
```

</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
