### PR TITLE
Scale direct reach value by sampling rate in EDP simulator

### PR DESCRIPTION
**Pull request by iverson52000**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)

### CODE REVIEW

**Review by riemanli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @matthewclegg, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 454 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBTxdzT4WPbiFkCwp02:-NBTxdzT4WPbiFkCwp03:b-aglmvo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5318db2e9f5c93f92796ffb110acace707f1f840/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L454)):*
> ```Kotlin
> 
>     val (reachValue, frequencyMap) =
>       calculateDirectReachAndFrequency(vidList, vidSamplingIntervalWidth)
> ```

@matthewclegg Please correct me if I am wrong. I think sampling rate is not equivalent to VID sampling width. For example, the VID bucket range is [0~47]/300 and the default VID width is 3/300 for reach-only query. The sampling rate is not 3/300 but 3/48.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 588 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBTzQlBEt89CCc3z94N:-NBTzQlBEt89CCc3z94O:bxeyb1i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5318db2e9f5c93f92796ffb110acace707f1f840/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L588)):*
> ```Kotlin
>           (frequencyMap.getValue(frequency) / reachValue.toDouble()) / samplingRate.toDouble()
>         frequencyMap[frequency] =
>           (frequencyMap.getValue(frequency) * 1000).roundToInt().toDouble() / 1000
> ```

Could you explain what this line is doing?

**Comment by iverson52000** [comment]
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 588 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBTzQlBEt89CCc3z94N:-NBU58oQ-G0gUC-rCa4J:b-qxhkov) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5318db2e9f5c93f92796ffb110acace707f1f840/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L588)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Could you explain what this line is doing?
</blockquote></details>

This is rounding since the division in the previous line will will generate very small decimal numbers

**Review by riemanli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @matthewclegg, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 588 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBTzQlBEt89CCc3z94N:-NBU6sOh5QHVnrhgB2Jg:bwf8nts) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5318db2e9f5c93f92796ffb110acace707f1f840/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L588)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

This is rounding since the division in the previous line will will generate very small decimal numbers
</blockquote></details>

How do we come up with 1000 or 3 decimal places? Maybe set the number as a constant to indicate that the rounding is to N decimal places?

**Comment by iverson52000** [comment]
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 588 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBTzQlBEt89CCc3z94N:-NBUEIzj3FQ4czhw_ZRE:b-46vonc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5318db2e9f5c93f92796ffb110acace707f1f840/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L588)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

How do we come up with 1000 or 3 decimal places? Maybe set the number as a constant to indicate that the rounding is to N decimal places?
</blockquote></details>

Of course we can use number other than 1000. Changed it to const variable

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @matthewclegg, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 454 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBTxdzT4WPbiFkCwp02:-NBY9Fnv-jI2f69FFlGI:bpn5x03) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5318db2e9f5c93f92796ffb110acace707f1f840/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L454)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@matthewclegg Please correct me if I am wrong. I think sampling rate is not equivalent to VID sampling width. For example, the VID bucket range is [0~47]/300 and the default VID width is 3/300 for reach-only query. The sampling rate is not 3/300 but 3/48.
</blockquote></details>

Good question. Will need Matt's feedback

**Review by matthewclegg — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)* status: all files reviewed, 3 unresolved discussions (waiting on @iverson52000, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 454 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBTxdzT4WPbiFkCwp02:-NBZ45Am2C5glIJhhtZM:b-y9bwfy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5318db2e9f5c93f92796ffb110acace707f1f840/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L454)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Good question. Will need Matt's feedback
</blockquote></details>

Actually, they are the same.  In Rieman's example, the vidSamplingWidth should be 3/300.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 588 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBTzQlBEt89CCc3z94N:-NBZ6ZtBDZr-AcnSl7to:b-wfc5lx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5318db2e9f5c93f92796ffb110acace707f1f840/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L588)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Of course we can use number other than 1000. Changed it to const variable
</blockquote></details>

Since the frequencies are represented as percentages, there is no need to divide by the sampling rate.  I believe that lines 586-589 should be replaced with:

```
frequencyMap[frequency] = frequencyMap.getValue(frequency) / reachValue.toDouble()
```

In other words, this part of the code should be left as it was previously.

https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8ac81fc5d4420586081334ffd279815efc71d639/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L113
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 566 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBZ90t72l07D5-VtbLj:-NBZ90t72l07D5-VtbLk:b11t3yw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6f7466bf7426e96f61f4bff7a955eede3ac7ccf3/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L566)):*
> ```Kotlin
>      * Function to calculate direct reach and frequency from VIDs in
>      * fulfillDirectReachAndFrequencyMeasurement(). Reach and frequency need to scale by sampling
>      * rate
> ```

Define the parameters and return values used by this function.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)* status: all files reviewed, 2 unresolved discussions (waiting on @iverson52000, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 454 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBTxdzT4WPbiFkCwp02:-NBZD-u80HEybgTKBdcH:bnqbtyl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5318db2e9f5c93f92796ffb110acace707f1f840/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L454)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Actually, they are the same.  In Rieman's example, the vidSamplingWidth should be 3/300.
</blockquote></details>

Got it. I thought the sampling was based on the VID bucket range of that specific metric. Thanks for the clarification Matt.

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @matthewclegg, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 588 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBTzQlBEt89CCc3z94N:-NBmdUZH-BLTelmj1Dpo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5318db2e9f5c93f92796ffb110acace707f1f840/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L588)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Since the frequencies are represented as percentages, there is no need to divide by the sampling rate.  I believe that lines 586-589 should be replaced with:

```
frequencyMap[frequency] = frequencyMap.getValue(frequency) / reachValue.toDouble()
```

In other words, this part of the code should be left as it was previously.

https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8ac81fc5d4420586081334ffd279815efc71d639/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L113

</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 566 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBZ90t72l07D5-VtbLj:-NBmdSe1ECn_-x6qngyp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6f7466bf7426e96f61f4bff7a955eede3ac7ccf3/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L566)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Define the parameters and return values used by this function.
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)* status: all files reviewed, 3 unresolved discussions (waiting on @iverson52000, @matthewclegg, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 573 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBrx-mO0tYXvHcNv75i:-NBrx-mO0tYXvHcNv75j:bso3swd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7fe37807ae754f48cf9d22c095f3004c15cb878c/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L573)):*
> ```Kotlin
>       samplingRate: Float
>     ): Pair<Long, Map<Long, Double>> {
>       require(samplingRate > 0) { "Invalid samplingRate $samplingRate" }
> ```

why not just `require (samplingRate > 0 && samplingRate <= 1.0) { ... }`?

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @matthewclegg, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 573 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683#-NBrx-mO0tYXvHcNv75i:-NBsMfro77NmC2tX10KR:b8go2vd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7fe37807ae754f48cf9d22c095f3004c15cb878c/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L573)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why not just `require (samplingRate > 0 && samplingRate <= 1.0) { ... }`?
</blockquote></details>

Good catch. Thanks!

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @matthewclegg and @stevenwarejones)

**Review by matthewclegg — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by iverson52000 — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Pull request merged**
