### PR TITLE
Move EncryptionKeyPairStore one level up.

### PR DESCRIPTION
**Pull request by riemanli**
Moving EncryptionKeyPairStore to be sharable across different versions in reporting.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/941)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/941)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/EncryptionKeyPairStoreTest.kt` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/941#-NSqoq_k4dhUtXlpUM3S:-NSqoq_k4dhUtXlpUM3T:b-b80zap) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7a9d14405223a77b0c59469969da9cf62a876ae8/src/test/kotlin/org/wfanet/measurement/reporting/service/api/EncryptionKeyPairStoreTest.kt#L17)):*
> ```Kotlin
> package org.wfanet.measurement.reporting.service.api
> 
> import com.google.common.truth.Truth
> ```

Revert this part of the change. We want to import `assertThat`.



_Suggestion:_
```Kotlin
import com.google.common.truth.Truth.assertThat
```

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/941)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/EncryptionKeyPairStoreTest.kt` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/941#-NSqoq_k4dhUtXlpUM3S:-NSqqY7n7JN8qHeE6lCr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7a9d14405223a77b0c59469969da9cf62a876ae8/src/test/kotlin/org/wfanet/measurement/reporting/service/api/EncryptionKeyPairStoreTest.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Revert this part of the change. We want to import `assertThat`.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
