### PR TITLE
Update Bazel container image to latest.

### PR DESCRIPTION
**Pull request by SanjayVas**
---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/361)

### CODE REVIEW

**Comment by SanjayVas** [comment]
This doesn't fix anything w.r.t. running the script from MacOS. Just some little cleanups.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/361)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/361)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by chipingyeh — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/361)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
