### PR TITLE
Extract common ComputationParticipant building logic to ComputationParticipantReader.

### PR DESCRIPTION
**Pull request by SanjayVas**
https://rally1.rallydev.com/#/604612930531d/portfolioitemstreegrid?detail=%2Ftask%2F607712261053&fdp=true?fdp=true

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/231)

### CODE REVIEW

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/231)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)

**Review by corbantek — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/231)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/231)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @zachcwc)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/231)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Comment by SanjayVas** [comment]
This is for #103.

**Pull request merged**
