### PR TITLE
Implement list event group metadata descriptors

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt` line 88 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967#-NUXV7yh321oqtNTDKbD:-NUXV7yi7Iy6Hkk8M0j8:brtzbvi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b62ed42da3c0c2a289030eae1bba6c863dda8614/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt#L88)):*
> ```Kotlin
>     request: StreamEventGroupMetadataDescriptorsRequest,
>   ): Flow<EventGroupMetadataDescriptor> {
>     grpcRequire(request.filter.externalDataProviderId >= 0L) {
> ```

We shouldn't have any relative to `0` checks on IDs. Technically we should only need to check whether the ID is specified (assuming it's required), where unspecified == 0. It just happens to be that our external ID generator currently doesn't generate negative numbers, but that may change (there's a long-standing TODO in my head to do that since we're otherwise losing half of our potential ID space).
___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 45 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967#-NUX_cNI95CGJmOrDMSM:-NUX_cNI95CGJmOrDMSN:bfo1526) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79756a5957ee0b5f4833fdd8ea16c38af0ac1d5f/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L45)):*
> ```protobuf
>     fixed64 external_event_group_metadata_descriptor_id = 2;
>   }
>   PreviousPageEnd last_event_group_metadata_Descriptor = 3;
> ```

typo: `last_event_group_metadata_descriptor`
___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto` line 57 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967#-NUX_n2B6aWkeH6rUjUK:-NUX_n2B6aWkeH6rUjUL:b-pydsqe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79756a5957ee0b5f4833fdd8ea16c38af0ac1d5f/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto#L57)):*
> ```protobuf
>     repeated fixed64 external_event_group_metadata_descriptor_ids = 2;
> 
>     // for next page token, both after fields need to be set
> ```

We're not actually doing what our filter API implies. We have two separate "after" fields, and we've stated that filter fields are conjuncts (ANDed together). Instead we may return items where the EDP ID is *equal to* (not *after*) the specified ID.

This should actually be a `key_after` field, where the corresponding key is a message that includes both IDs.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt` line 88 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967#-NUXV7yh321oqtNTDKbD:-NUXjPqk74WP0ppQoE11:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b62ed42da3c0c2a289030eae1bba6c863dda8614/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We shouldn't have any relative to `0` checks on IDs. Technically we should only need to check whether the ID is specified (assuming it's required), where unspecified == 0. It just happens to be that our external ID generator currently doesn't generate negative numbers, but that may change (there's a long-standing TODO in my head to do that since we're otherwise losing half of our potential ID space).
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 45 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967#-NUX_cNI95CGJmOrDMSM:-NUXjQtd3Gxv5WolM4ty:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79756a5957ee0b5f4833fdd8ea16c38af0ac1d5f/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

typo: `last_event_group_metadata_descriptor`
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto` line 57 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967#-NUX_n2B6aWkeH6rUjUK:-NUXjRNT83AmFS_6v9nC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79756a5957ee0b5f4833fdd8ea16c38af0ac1d5f/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We're not actually doing what our filter API implies. We have two separate "after" fields, and we've stated that filter fields are conjuncts (ANDed together). Instead we may return items where the EDP ID is *equal to* (not *after*) the specified ID.

This should actually be a `key_after` field, where the corresponding key is a message that includes both IDs.
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt` line 88 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967#-NUXV7yh321oqtNTDKbD:-NUY1v-hBeKp3EzHKLUT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b62ed42da3c0c2a289030eae1bba6c863dda8614/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Still seeing the check here
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroupMetadataDescriptors.kt` line 58 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967#-NUXtVyi-fwwyKgrwFzT:-NUY4Ooz6L8bAGL1SWFf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0dfd038529efd5b78bc832438965c16be05428e7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroupMetadataDescriptors.kt#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can just check `filter.hasKeyAfter`
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 4 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/967)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
