### PR TITLE
Prevent setting of participant requisition params with invalid duchy certificate

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368#-MoeeIN-0go_GkHMiUzR:-MoeeIN0AXAcw-oxnj7J:b-2ra0hs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5741acc496dcc557b4c585075d4fe261903bd3b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L136)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     val certificate = certificateResult.certificate
> 
>     if (certificate.revocationState != Certificate.RevocationState.REVOCATION_STATE_UNSPECIFIED ||
>         certificateResult.isNotYetActive ||
>         certificateResult.isExpired
>     ) {
>       throw KingdomInternalException(KingdomInternalException.Code.CERTIFICATE_IS_INVALID)
>     }
> ```
</details>


How about adding an additional`isValid` value in the CertificateReader.Result. I expect this logic will be useful in many places.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, line 74 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368#-MoehbvH-E200JY5O5mM:-MoehbvH-E200JY5O5mN:bk61eu5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5741acc496dcc557b4c585075d4fe261903bd3b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L74)):*
> ```
> ComputationParticipantReader
> ```

Before processing, we may want to check if `computationParticipantResult.measurementState == PENDING_REQUISITION_PARAMS` or not. If not, fail the request with `MEASUREMENT_STATE_ILLEGAL`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, line 253 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368#-Moeh-Nm90zLrFXFTuOF:-Moeh-Nn39GvySRxE1NY:b8edp0v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5741acc496dcc557b4c585075d4fe261903bd3b4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L253)):*
> ```
> revokeCertificate(
> ```
After this, the measurement should be FAILED after your another PR is merged.

So it is a little hard to test this scenario since it is not a case should exist in reality. Maybe we can skip this one.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, line 253 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368#-Moeh-Nm90zLrFXFTuOF:-MoejDf0CtBMaUDPlYyV:b-nexu46) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5741acc496dcc557b4c585075d4fe261903bd3b4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L253)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> revokeCertificate(
> ```
After this, the measurement should be FAILED after your another PR is merged.

So it is a little hard to test this scenario since it is not a case should exist in reality. Maybe we can skip this one.
</blockquote></details>

oh, nevermind. The certificate is not associated with the measurement yet. So revoking it won't fail the measurement

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, line 74 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368#-MoehbvH-E200JY5O5mM:-Moes9shBEV6B5mPNvKh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5741acc496dcc557b4c585075d4fe261903bd3b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L74)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> ComputationParticipantReader
> ```

Before processing, we may want to check if `computationParticipantResult.measurementState == PENDING_REQUISITION_PARAMS` or not. If not, fail the request with `MEASUREMENT_STATE_ILLEGAL`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368#-MoeeIN-0go_GkHMiUzR:-MoesAPM0dc0wsoMgO-p:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5741acc496dcc557b4c585075d4fe261903bd3b4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L136)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     val certificate = certificateResult.certificate
> 
>     if (certificate.revocationState != Certificate.RevocationState.REVOCATION_STATE_UNSPECIFIED ||
>         certificateResult.isNotYetActive ||
>         certificateResult.isExpired
>     ) {
>       throw KingdomInternalException(KingdomInternalException.Code.CERTIFICATE_IS_INVALID)
>     }
> ```

How about adding an additional`isValid` value in the CertificateReader.Result. I expect this logic will be useful in many places.
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, line 144 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368#-MoeuRkw8uxuGhP7bN3W:-MoeuRkw8uxuGhP7bN3X:byqfitk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c69ca196e42fd51dbb38ed71145625dabd123e7d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L144)):*
> ```
> certificate
> ```
nit: use `certificateResult.certificate` here directly. No need to define `val certificate`

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones, @tristanvuong2021, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, line 125 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368#-Moeww0PELqzr4SJFtWy:-Moeww0PELqzr4SJFtWz:bdzxzrs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/609a05532fd1adb2417c773c15fdaf6656b7881e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L125)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>     val certificateResult =
>       CertificateReader(CertificateReader.ParentType.DUCHY)
>         .fillStatementBuilder {
>           appendClause("WHERE DuchyId = @duchyId AND CertificateId = @certificateId")
>           bind("duchyId" to duchyId)
>           bind("certificateId" to duchyCertificateId)
>         }
>         .execute(transactionContext)
>         .single()
> 
>     if (!certificateResult.isValid) {
>       throw KingdomInternalException(KingdomInternalException.Code.CERTIFICATE_IS_INVALID)
>     }
> ```
</details>

Move this above line 61?

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones, @tristanvuong2021, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, line 125 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368#-Moeww0PELqzr4SJFtWy:-MoexwgTENevQeM_XC9_:busodhz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/609a05532fd1adb2417c773c15fdaf6656b7881e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L125)):*
> ```
> SetParticipantRequisitionParamsRequest
> ```
or maybe above line 95.  We should check if the computationParticipant exist or not.

The point is that we shouldn't `updateMeasurementState` if we are going to fail the request later.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, line 125 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368#-Moeww0PELqzr4SJFtWy:-Mof5CrTEWVU1PMx_lbF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/609a05532fd1adb2417c773c15fdaf6656b7881e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L125)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> SetParticipantRequisitionParamsRequest
> ```
or maybe above line 95.  We should check if the computationParticipant exist or not.

The point is that we shouldn't `updateMeasurementState` if we are going to fail the request later.
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
