### PR TITLE
Fix creation of measurementCalculations in public reports service

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791)

### CODE REVIEW

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1034 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791#-NJNkyCs3TtTHov91aCr:-NJNkyCs3TtTHov91aCs:b-jzky4z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a26fd0c840502e02231a9796e5fadf058d2242c5/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1034)):*
> ```Kotlin
>     val measurementCalculations = mutableListOf<MeasurementCalculation>()
>     setOperationResult.weightedMeasurementInfoList
>       .groupBy { it.timeInterval }
> ```

Good to know `groupby` can use the class from a proto message as a key!
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 141 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791#-NJNmhf1ENacqMMob0NN:-NJNmhf1ENacqMMob0NO:bg1lnge) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a26fd0c840502e02231a9796e5fadf058d2242c5/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L141)):*
> ```Kotlin
> import org.wfanet.measurement.internal.reporting.ReportingSetKt as InternalReportingSetKt
> import org.wfanet.measurement.internal.reporting.ReportingSetsGrpcKt.ReportingSetsCoroutineImplBase as InternalReportingSetsCoroutineImplBase
> import org.wfanet.measurement.internal.reporting.ReportingSetsGrpcKt.ReportingSetsCoroutineImplBase
> ```

Duplicate with the import at line 140 which uses an alias.



_Code quote:_
```Kotlin
import org.wfanet.measurement.internal.reporting.ReportingSetsGrpcKt.ReportingSetsCoroutineImplBase
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1545 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791#-NJO9yGl-rQBJQIhJoKE:-NJO9yGl-rQBJQIhJoKF:bfptcrx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a26fd0c840502e02231a9796e5fadf058d2242c5/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1545)):*
> ```Kotlin
>     }
> 
>     withMeasurementConsumerPrincipal(MEASUREMENT_CONSUMER_NAMES[0], CONFIG) {
> ```

Should we get the result and check if it matched with the expected?
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1643 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791#-NJO8fwhBE0zJRkGf77L:-NJO8fwhBE0zJRkGf77M:b-4iuqfu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a26fd0c840502e02231a9796e5fadf058d2242c5/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1643)):*
> ```Kotlin
>             InternalCreateReportRequestKt.measurementKey {
>               measurementConsumerReferenceId = MEASUREMENT_CONSUMER_REFERENCE_IDS[0]
>               measurementReferenceId = REACH_MEASUREMENT_REFERENCE_ID
> ```

Why does `measurements` have two `REACH_MEASUREMENT_REFERENCE_ID`s instead of `REACH_MEASUREMENT_REFERENCE_ID` and `REACH_MEASUREMENT_REFERENCE_ID_2`?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 141 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791#-NJNmhf1ENacqMMob0NN:-NJOPhRJB55ttGOEwMpS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a26fd0c840502e02231a9796e5fadf058d2242c5/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L141)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Duplicate with the import at line 140 which uses an alias.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1545 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791#-NJO9yGl-rQBJQIhJoKE:-NJQwOHe1eJ2SNU4FjI2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a26fd0c840502e02231a9796e5fadf058d2242c5/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1545)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Should we get the result and check if it matched with the expected?
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1643 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791#-NJO8fwhBE0zJRkGf77L:-NJQwNmwBMcmvQl8olpX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a26fd0c840502e02231a9796e5fadf058d2242c5/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1643)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Why does `measurements` have two `REACH_MEASUREMENT_REFERENCE_ID`s instead of `REACH_MEASUREMENT_REFERENCE_ID` and `REACH_MEASUREMENT_REFERENCE_ID_2`?
</blockquote></details>

Done.

**Review by riemanli — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
