### PR TITLE
Add more explanation to the local deployment

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1456)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1456** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1456?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1456?utm_source=stack-comment).

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1456)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/main/k8s/local/README.md` line 188 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1456#-Npagw8C0QCWHTC5_gQX:-Npagw8C0QCWHTC5_gQY:b-xjnt88) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a67c12d33d6b6eded118e889955a147da5602eb8/src/main/k8s/local/README.md#L188)):*
> ```Markdown
> create the Duchies and EDP simulators.
> 
> To use the Kingdom CLI tool, you need to forward the port again:
> ```

Port-forwarding is the standard term.
___
*[`src/main/k8s/local/README.md` line 217 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1456#-NpagvdK6m5nQ3p1XMa4:-Npag5WO7fOMxtNh_xYs:b-rqxvo7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a67c12d33d6b6eded118e889955a147da5602eb8/src/main/k8s/local/README.md#L217)):*
> ```Markdown
> `cmms_with_reporting_v2`.
> 
> To use the Reporting CLI tool, you need to forward the port again. For example:
> ```

ditto.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1456)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/k8s/local/README.md` line 188 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1456#-Npagw8C0QCWHTC5_gQX:-NpbGIjL4Sm78UtBHlfF:bsav0rd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a67c12d33d6b6eded118e889955a147da5602eb8/src/main/k8s/local/README.md#L188)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Port-forwarding is the standard term.
</blockquote></details>

I agree with you if we need a noun. How do you rewrite in this case? In addition, we already used a similar wording at https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a67c12d33d6b6eded118e889955a147da5602eb8/src/main/k8s/local/README.md?plain=1#L104

**Review by tristanvuong2021 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1456)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Pull request merged**
