### PR TITLE
add default value for non-required option

### PR DESCRIPTION
**Pull request by Marco-Premier**
Add default value for requiredDuchies option

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/871)

**Review by renjiezh — CHANGES_REQUESTED** [review]
In `src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlags.kt`, there is another occurrence of this issue. Could you also update that?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/871#-:-NPTBIzs1o2AT7Zj6EPf:b-xhk5ar)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 151 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/871#-NPTIhiq3JMQp72hy9Zn:-NPTIhirAqQlR3SYXVii:b-hdhgkf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57edb39a912edb9bc5f2199f0b010e687db15b6a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L151)):*
> ```Kotlin
>       ],
>     required = false,
>     defaultValue = ""
> ```

Picocli failed to convert "" into an empty list. What about `private var requiredDuchyies: List<String> = emptyOf()`?.

**Review by Marco-Premier — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/871#-:-NPWQh5c0qits9RU21yH:b-896fix)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 151 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/871#-NPTIhiq3JMQp72hy9Zn:-NPWPJr08P8abR9DT5GW:bwgg1eh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57edb39a912edb9bc5f2199f0b010e687db15b6a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L151)):*
> private var requiredDuchyies: List<String> = emptyOf()
my bad, sorry.

**Review by renjiezh — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/871#-:-NPYkCC6ERECm4dMmiae:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/871)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @renjiezh)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/871)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

**Review by Marco-Premier — COMMENTED** [review]
:lgtm:

> Dismissed @renjiezh from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/871#-:-NPaTLp7DeYBLYZNoTav:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
