### PR TITLE
Add report tags

### PR DESCRIPTION
**Pull request by riemanli**
This PR implements the tags field which was added to `Report` in #1251. A change to the DB schema is needed.

### CODE REVIEW

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1283** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1283" target="_blank">Graphite</a> 
    * **PR #1288** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1288" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1288?utm_source=stack-comment).

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1288)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1288)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1288)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Pull request merged**
