### PR TITLE
Implement internal reports service report create for reporting v2

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1060)

**Review by riemanli — COMMENTED** [review]
> Reviewed 9 of 12 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1060)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1060#-NXv8Lg7E3tcwoudwOOQ:-NXv8Lg7E3tcwoudwOOR:by3lq7r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6a6f702c4bc23c2248019a8bf591b3aa6250582/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L74)):*
> ```Kotlin
>     val externalReportingSetIds = mutableListOf<ExternalId>()
>     request.report.reportingMetricEntriesMap.entries.forEach {
>       externalReportingSetIds.add(ExternalId(it.key))
> ```

nit: Based on my past experience, it seems like `+=` is more preferable.

```diff
- externalReportingSetIds.add(ExternalId(it.key))
+ externalReportingSetIds += ExternalId(it.key)
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1060#-NXv_lVr3oNGcF3lpZQl:-NXv_lVsAgETssgEDvhu:b2eu23a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6a6f702c4bc23c2248019a8bf591b3aa6250582/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L92)):*
> ```Kotlin
>     val createdReportingSet = createReportingSet(CMMS_MEASUREMENT_CONSUMER_ID, reportingSetsService)
> 
>     val report = report {
> ```

Would it be better if we wrap it to a function with necessary args like `createReport` that can be reused in other tests?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1060)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1060#-NXv_lVr3oNGcF3lpZQl:-NXvv6z88PYPdqgI2TMN:b-kat2d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6a6f702c4bc23c2248019a8bf591b3aa6250582/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L92)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Would it be better if we wrap it to a function with necessary args like `createReport` that can be reused in other tests?
</blockquote></details>

Refactored it a bit.

**Review by riemanli — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1060)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 9 of 12 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1060)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
