### PR TITLE
Update EdpSimulatorRunner and cue configurations.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574)

**Comment by renjiezh** [comment]
Deployed in GCP dev environment.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/k8s/local/edp_simulators.cue` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574#-Nvh-6tM22A-PRho6L7T:-Nvh5ls5EGykaLn5HY7G:b2lsf5y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b7aba68a2fec582abd3aab5877335d42e7b54831/src/main/k8s/local/edp_simulators.cue#L82)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Could we fix the format to make it align better?
</blockquote></details>

I wrote it in a better format but command line `cue fmt` refactored it like this. As our github workflow forces the formatter, guess we have to keep it like this.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/k8s/local/edp_simulators.cue` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574#-Nvh-6tM22A-PRho6L7T:-Nvh6cN-5Hws7JSYuqpm:bvjr201) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b7aba68a2fec582abd3aab5877335d42e7b54831/src/main/k8s/local/edp_simulators.cue#L82)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I wrote it in a better format but command line `cue fmt` refactored it like this. As our github workflow forces the formatter, guess we have to keep it like this.
</blockquote></details>

I tried again with your alignment. `cue fmt` allows it. Sweet.

**Review by ple13 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574)* status: all files reviewed, 4 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/k8s/edp_simulator.cue` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574#-NvhG45k4Yxzu1fITmA3:-NvhG45k4Yxzu1fITmA4:bh5hbdl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4455af25d0c3f0dcdc11b8dd352b807a7ab1f943/src/main/k8s/edp_simulator.cue#L42)):*
> ```CUE
> 	_additional_args: [...string]
> 
> 	_requisitionFulfillmentServiceFlags: [ for config in _requisitionFulfillmentServiceConfigs for flag in {
> ```

nit: I'm pretty sure you could use list.FlattenN rather than the nested comprehensions

https://cuelang.org/docs/howto/use-list-flattenn-to-flatten-lists/
___
*[`src/main/k8s/dev/edp_simulator_gke.cue` line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574#-NvhGXzzDPLjqgFEkNyX:-NvhGXzzDPLjqgFEkNyY:b-r9dapp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4455af25d0c3f0dcdc11b8dd352b807a7ab1f943/src/main/k8s/dev/edp_simulator_gke.cue#L35)):*
> ```CUE
> _kingdomPublicApiTarget: string @tag("kingdom_public_api_target")
> 
> _worker1Id:              "worker1"
> ```

I had suggested hard-coding these in the workflow, not in the cue files. This way someone building it could still specify alternate IDs, but the workflows for our test environments would assume them.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574#-NvhGy7j3xNnkCWqczcF:-NvhGy7j3xNnkCWqczcG:b-y0h44i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4455af25d0c3f0dcdc11b8dd352b807a7ab1f943/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L172)):*
> ```Kotlin
>   private val eventGroupMetadataDescriptorsStub: EventGroupMetadataDescriptorsCoroutineStub,
>   private val requisitionsStub: RequisitionsCoroutineStub,
>   private val requisitionFulfillmentStubMap: Map<String, RequisitionFulfillmentCoroutineStub>,
> ```

The String type doesn't give any clues on what the map key is on its own. Make this more clear by adding property documentation and/or naming the field such that it's obvious (e.g. `requisitionFulfillmentStubsByDuchyId`)
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 329 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574#-NvhHhlG2Km2AuwlhhYI:-NvhHhlG2Km2AuwlhhYJ:bp7dppq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4455af25d0c3f0dcdc11b8dd352b807a7ab1f943/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L329)):*
> ```Kotlin
>   }
> 
>   // TODO(ple13): Create two requisitionFulfillmentStubs for HMSS test.
> ```

Use correct TODO format for GitHub usernames. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format



_Suggestion:_
```Kotlin
TODO(@ple13)
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574)* status: all files reviewed, 5 unresolved discussions (waiting on @renjiezh)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574#-NvhI3RC9KsXjzBO9SFY:-NvhI3RC9KsXjzBO9SFZ:babyauz) (no related file):*
The [Simulator Deployment Guide](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/simulator-deployment.md) also needs to be updated to reflect the change in Make vars.

___

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574)* status: 5 of 15 files reviewed, 4 unresolved discussions (waiting on @ple13 and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574#-NvhI3RC9KsXjzBO9SFY:-Nvi0Q8Z2v-VrQsp0Nva:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The [Simulator Deployment Guide](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/simulator-deployment.md) also needs to be updated to reflect the change in Make vars.
</blockquote></details>

Done.

___
___
*[`src/main/k8s/dev/edp_simulator_gke.cue` line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574#-NvhGXzzDPLjqgFEkNyX:-Nvi0VF8D3_xYWUzaQyq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4455af25d0c3f0dcdc11b8dd352b807a7ab1f943/src/main/k8s/dev/edp_simulator_gke.cue#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I had suggested hard-coding these in the workflow, not in the cue files. This way someone building it could still specify alternate IDs, but the workflows for our test environments would assume them.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574#-NvhGy7j3xNnkCWqczcF:-Nvi0Vmx1yaAXF4svS-M:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4455af25d0c3f0dcdc11b8dd352b807a7ab1f943/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L172)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The String type doesn't give any clues on what the map key is on its own. Make this more clear by adding property documentation and/or naming the field such that it's obvious (e.g. `requisitionFulfillmentStubsByDuchyId`)
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 329 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574#-NvhHhlG2Km2AuwlhhYI:-Nvi0WNH4JzzWVK3FKzi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4455af25d0c3f0dcdc11b8dd352b807a7ab1f943/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L329)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use correct TODO format for GitHub usernames. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format
</blockquote></details>

Done.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574)* status: 5 of 15 files reviewed, 4 unresolved discussions (waiting on @ple13 and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574#-NvhI3RC9KsXjzBO9SFY:-Nvi1jzD2ylUuljyl9yf:b-yhnyqb) (no related file):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Successfully deployed in GCP after modification.

___

**Review by SanjayVas — APPROVED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 15 files at r1, 1 of 1 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1574)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
