### PR TITLE
Hardcode EventGroup IDs that EDP simulators will fail Requisitions on

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195#-NdBjplT2gtSGtG-liE5:-NdBjplT2gtSGtG-liE6:bqu01er) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3c6454c689ebe1d1cc928c47d211518483eb8ba/src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt#L23)):*
> ```Kotlin
>   const val SIMULATOR_EVENT_GROUP_REFERENCE_ID_PREFIX = "sim-eg"
> 
>   /** Resource IDs for EventGroups that fail Requisitions if used. */
> ```

KDoc only applies to the symbol that it immediately precedes. You'll need a separate KDoc for each property.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195#-NdBjplT2gtSGtG-liE5:-NdCrjHtAuG23zYT5YX0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad23340c1ba0478bd261c5de822ecce897722bad/src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

KDoc only applies to the symbol that it immediately precedes. You'll need a separate KDoc for each property.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 536 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195#-NdHSM_o4dErLdeGucwM:-NdHSM_o4dErLdeGucwN:b-roj3j4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dda6d3f3bb9687848e8bebff247b2b52f4f885ef/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L536)):*
> ```Kotlin
>         for (eventGroupEntry in requisitionSpec.events.eventGroupsList) {
>           val eventGroupId = EventGroupKey.fromName(eventGroupEntry.key)!!.eventGroupId
>           if (eventGroupId == CONSENT_SIGNAL_INVALID_EVENT_GROUP_ID) {
> ```

this feels like a messy way to communicate that the edp simulator should fail. why do you want to set it up this way? Why not set up separate test cases that actually fail?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @mariolamassaavedra, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 536 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195#-NdHSM_o4dErLdeGucwM:-NdHjQo-817oAfeYQOmq:by3qr2n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dda6d3f3bb9687848e8bebff247b2b52f4f885ef/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L536)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this feels like a messy way to communicate that the edp simulator should fail. why do you want to set it up this way? Why not set up separate test cases that actually fail?
</blockquote></details>

This was requested by @mariolamassaavedra for use in their testing environment. They wanted a way to easily trigger specific failure conditions.

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)* status: all files reviewed, 1 unresolved discussion (waiting on @mariolamassaavedra, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 536 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195#-NdHSM_o4dErLdeGucwM:-Nd_jSsiDMfya6KE_kmb:bfp2bkv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dda6d3f3bb9687848e8bebff247b2b52f4f885ef/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L536)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This was requested by @mariolamassaavedra for use in their testing environment. They wanted a way to easily trigger specific failure conditions.
</blockquote></details>

The reason for this is to be able to trigger the various error conditions in a live (QA) environment, though I see it being potentially useful for integration testing too.

For what it's worth I've used this "sentinel value" approach for triggering specific behavior in functional tests quite a bit in the past and it works well.

The updates to the "EDPSimulatorTest" below should be seen as testing the behavior of the Simulator and that it generates the right errors upon the proper input, so that clients can properly rely on that behavior.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)* status: all files reviewed, 2 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt` line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195#-NdaFe8Z5ZAdyoi2gA9I:-NdaFe8Z5ZAdyoi2gA9J:blq16dq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c83ab3cc82674f3483020ae06221b016bbc32a57/src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt#L24)):*
> ```Kotlin
> 
>   /** Resource ID for EventGroup that fails Requisitions with CONSENT_SIGNAL_INVALID if used. */
>   const val CONSENT_SIGNAL_INVALID_EVENT_GROUP_ID = "consent-signal-invalid"
> ```

what about making these internal to the EdpSimulator only? I'm not sure what I think about using them elsewhere

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt` line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195#-NdaFe8Z5ZAdyoi2gA9I:-NdaQHTB11olMgGXlicB:b-4pasx8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c83ab3cc82674f3483020ae06221b016bbc32a57/src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what about making these internal to the EdpSimulator only? I'm not sure what I think about using them elsewhere
</blockquote></details>

Making them private will act as a hint for the rest of the Halo code base not to use them, but since anyone can copy the strings and basically use them it doesn't really stop anything.

Also, it's arguably that having Halo's integration tests be able to take advantage of these could help test some unhappy paths, and that would be valuable.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt` line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195#-NdaFe8Z5ZAdyoi2gA9I:-NdaV5Ui0jefitzqKNxX:bi8v6gc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c83ab3cc82674f3483020ae06221b016bbc32a57/src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt#L24)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Making them private will act as a hint for the rest of the Halo code base not to use them, but since anyone can copy the strings and basically use them it doesn't really stop anything.

Also, it's arguably that having Halo's integration tests be able to take advantage of these could help test some unhappy paths, and that would be valuable.
</blockquote></details>

i like making them private for the simulator for now - we can revisit other use cases in the future

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt` line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195#-NdaFe8Z5ZAdyoi2gA9I:-NdaehGk0H1F1EcHYYyU:bb7ohn6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c83ab3cc82674f3483020ae06221b016bbc32a57/src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i like making them private for the simulator for now - we can revisit other use cases in the future
</blockquote></details>

sgtm

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt` line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195#-NdaFe8Z5ZAdyoi2gA9I:-NdamnYH-T66vi0OLbbB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c83ab3cc82674f3483020ae06221b016bbc32a57/src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt#L24)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

sgtm
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariolamassaavedra)

**Pull request merged**
