### PR TITLE
build: Update common-jvm dep for Maven BOMs

### LINKED ISSUE #1794: Use BOMs for Maven dependencies where available
rules_jvm_external now supports using bill of materials (BOM) for Maven dependencies via the new `maven` resolver. This reduces the risk of having incompatible versions when we update a dependency. In particular, it should reduce the "dependency hell" of trying to find compatible versions of low-level dependencies.

- [x] Prefactoring
  - [x] https://github.com/world-federation-of-advertisers/rules_kotlin_jvm/pull/6
  - [x] https://github.com/world-federation-of-advertisers/rules_kotlin_jvm/pull/7
  - [x] https://github.com/world-federation-of-advertisers/common-jvm/pull/270
- [x] https://github.com/world-federation-of-advertisers/rules_kotlin_jvm/pull/8
- [x] https://github.com/world-federation-of-advertisers/bazel-registry/pull/57
- [x] https://github.com/world-federation-of-advertisers/common-jvm/pull/268
- [x] https://github.com/world-federation-of-advertisers/bazel-registry/pull/58
- [ ] #1790 

https://rally1.rallydev.com/#/?detail=/userstory/807695041095&fdp=true

### PR DESCRIPTION
**Pull request by SanjayVas**
Closes #1794

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1790)

**Comment by SanjayVas** [comment]
Depends on world-federation-of-advertisers/common-jvm#268

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1790)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1790)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
