### PR TITLE
Cleanup unused queries code

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein and @stevenwarejones)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ProviderFilter.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355#-MoBUKMT0qDZQrR-KLPb:-MoBUKMT0qDZQrR-KLPc:b9p3y59) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8135983057cab20e4da650ed677eee63597f720/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ProviderFilter.kt#L26)):*
> ```Kotlin
>   provider: Provider,
>   param: String = PROVIDER_PARAM,
>   prefix: String = "  AND "
> ```

I'm not totally old about the prefix, I think I'd prefer adding it in separately, not as part of this method.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355)* status: 13 of 18 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ProviderFilter.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355#-MoBUKMT0qDZQrR-KLPb:-MoBXoyx6hFGfUm7EVkh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8135983057cab20e4da650ed677eee63597f720/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ProviderFilter.kt#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm not totally old about the prefix, I think I'd prefer adding it in separately, not as part of this method.
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 13 of 18 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355)* status: all files reviewed, 3 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 69 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355#-MoG-DWLDvlu3a6UANxN:-MoG-DWMBeZ_1lwlRAe1:b-qucs7p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da825c4f709aa84fac811c7b4ca77820d6efb060/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L69)):*
> ```Kotlin
>           """.trimIndent()
>           )
>           appendClause("  AND ${providerFilter(request.provider)}")
> ```

Maybe just put all the clauses together in one string?

```
appendClause(
  """
  WHERE RecurringExchanges.ExternalRecurringExchangeId = @external_recurring_exchange_id
      AND ExchangeSteps.Date = @date
      AND ExchangeSteps.StepIndex = @step_index
      AND ${providerFilter(request.provider)}
  """
)
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangesService.kt, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355#-MoG-QvO7VxlvT5jnrle:-MoG-QvO7VxlvT5jnrlf:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da825c4f709aa84fac811c7b4ca77820d6efb060/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangesService.kt#L48)):*
> ```Kotlin
>           "WHERE RecurringExchanges.ExternalRecurringExchangeId = @external_recurring_exchange_id"
>         )
>         appendClause("AND Exchanges.Date = @date")
> ```

Ditto
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355#-MoG-Vyr1LldvEVE95v3:-MoG-VysDQDa0gudpIJe:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da825c4f709aa84fac811c7b4ca77820d6efb060/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L99)):*
> ```Kotlin
>         bind("recurringExchangeState" to RecurringExchange.State.ACTIVE)
>         bind("exchangeState" to Exchange.State.FAILED)
>         appendClause("  AND ${providerFilter(provider)}")
> ```

Ditto

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355)* status: 15 of 18 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 69 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355#-MoG-DWLDvlu3a6UANxN:-MoG31Cg9WGemfGAyOn3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da825c4f709aa84fac811c7b4ca77820d6efb060/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L69)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe just put all the clauses together in one string?

```
appendClause(
  """
  WHERE RecurringExchanges.ExternalRecurringExchangeId = @external_recurring_exchange_id
      AND ExchangeSteps.Date = @date
      AND ExchangeSteps.StepIndex = @step_index
      AND ${providerFilter(request.provider)}
  """
)
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangesService.kt, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355#-MoG-QvO7VxlvT5jnrle:-MoG32Bm3oUfbckeo-uP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da825c4f709aa84fac811c7b4ca77820d6efb060/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangesService.kt#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355#-MoG-Vyr1LldvEVE95v3:-MoG33-v6Y-iJkiAhaA4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da825c4f709aa84fac811c7b4ca77820d6efb060/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L99)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 64 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355#-MoG2w487GoOTKA2YWyc:-MoG2w487GoOTKA2YWyd:b-99t88h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8345e68f35baada2fc1994c827f276b07d1493a8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L64)):*
> ```Kotlin
>           appendClause(
>             """
>           WHERE RecurringExchanges.ExternalRecurringExchangeId = @external_recurring_exchange_id
> ```

Supernit: align "W" in "WHERE" with the first opening quote (`"`):

```
appendClause(
  """
  W...
```

**Review by yunyeng — COMMENTED** [review]
> Reviewed 13 of 18 files at r1, 2 of 5 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/355)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
