### PR TITLE
Move FilterEventQuery into own class

### PR DESCRIPTION
**Pull request by jcorilla**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641)

### CODE REVIEW

**Review by uakyol — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @jcorilla and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 105 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641#-N8UmW-f94wLm5BoMwwh:-N8UmW-f94wLm5BoMwwi:b8drctl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/423763e4f7ca3fbe8e9574fffeddef2d32822e11/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L105)):*
> ```Kotlin
>             requisitionFulfillmentStub = requisitionFulfillmentClient,
>             sketchStore = SketchStore(storageClient),
>             eventQuery = FilterEventQuery(events),
> ```

Im wondering why you changed this at all? Just moving the FilterEventQuery to main and writing a test for it is enough. We don't really want to change the EDPSimulator initialization.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/FilterEventQuery.kt` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641#-N8UJCn2DhbUSv7CnH4D:-N8UJCn32MxA8pU9Panv:b32oi4v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/423763e4f7ca3fbe8e9574fffeddef2d32822e11/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/FilterEventQuery.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

would you mind updating these comments with this new format : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L1
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/FilterEventQueryTest.kt` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641#-N8UJhi5DJhBl4QUgKDi:-N8UJhi5DJhBl4QUgKDj:bb7txij) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/423763e4f7ca3fbe8e9574fffeddef2d32822e11/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/FilterEventQueryTest.kt#L1)):*
> ```Kotlin
> // Copyright 2022 The Cross-Media Measurement Authors
> ```

Ditto here

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @jcorilla and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 105 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641#-N8UmW-f94wLm5BoMwwh:-N8UsgkF52oDueW1jpwN:bh1o3ti) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/423763e4f7ca3fbe8e9574fffeddef2d32822e11/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L105)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Im wondering why you changed this at all? Just moving the FilterEventQuery to main and writing a test for it is enough. We don't really want to change the EDPSimulator initialization.
</blockquote></details>

Leaving this with the RandomEventQuery is good with me. The reason for the change was thinking we initially wanted to replace RandomEventQuery

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/FilterEventQuery.kt` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641#-N8UJCn2DhbUSv7CnH4D:-N8V2oUcBXphuI5odx6N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/423763e4f7ca3fbe8e9574fffeddef2d32822e11/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/FilterEventQuery.kt#L1)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

would you mind updating these comments with this new format : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L1
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/FilterEventQueryTest.kt` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641#-N8UJhi5DJhBl4QUgKDi:-N8V2nFIBxVS1sNcod8l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/423763e4f7ca3fbe8e9574fffeddef2d32822e11/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/FilterEventQueryTest.kt#L1)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Ditto here
</blockquote></details>

Done.

**Review by uakyol — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @uakyol)

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
