### PR TITLE
Add internal spanner batch measurement deletion

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918)

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt` line 170 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NRngrqW9H9K2NCUurwM:-NRoEXDS8XC-ohsMvz0t:b-olwq02) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/474a6f5b8192a538b9dcc056113dd7b8ac9c19f5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L170)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

MeasurementNotFoundByMeasurementConsumerException is thrown in BatchDelete
</blockquote></details>

MeasurementNotFoundException is the parent class of the exception. The cancelMeasurement and setMeasurementResult functions also throw that parent class instead of the child class so I was thinking it was better to maintain that pattern. I can update this (and the others as well to explicitly catch the child class) if you feel it's a better pattern.



_Code quote:_
```Kotlin
MeasurementNotFoundException
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BatchDeleteMeasurements.kt` line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NRnhcXI4dij8QtE9j9R:-NRoNPUhEz0VK-__2FkS:b-nl5owk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/474a6f5b8192a538b9dcc056113dd7b8ac9c19f5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BatchDeleteMeasurements.kt#L47)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

An error should be thrown in the service when the number of requests is over the max. Otherwise, the caller wouldn't know which ones were deleted without looking at this code, which could change.
</blockquote></details>

Done. Added more validation to the batch deletion request.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteMeasurement.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NRnjILd06ZuLauOXuAV:-NRo5t_1Et5hAbuKClW7:bc6x1qb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/474a6f5b8192a538b9dcc056113dd7b8ac9c19f5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteMeasurement.kt#L29)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Is this used anywhere.
</blockquote></details>

Removing, forgot to delete this class from an earlier commit.

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt` line 170 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NRngrqW9H9K2NCUurwM:-NRom2HQBYV23aCyu6mx:btqfv5d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/474a6f5b8192a538b9dcc056113dd7b8ac9c19f5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L170)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

MeasurementNotFoundException is the parent class of the exception. The cancelMeasurement and setMeasurementResult functions also throw that parent class instead of the child class so I was thinking it was better to maintain that pattern. I can update this (and the others as well to explicitly catch the child class) if you feel it's a better pattern.
</blockquote></details>

In that case, it is good as is.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt` line 181 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NRomNem1fkgNg7o5d88:-NRomNem1fkgNg7o5d89:b32vk6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8629f2ccd802ce92dc9e0540e03a2dfa0b941b8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L181)):*
> ```Kotlin
> 
>   private fun validateBatchDeleteMeasurementsRequest(request: BatchDeleteMeasurementsRequest) {
>     grpcRequire(request.requestsList.size < MAX_BATCH_DELETE) {
> ```

<=
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt` line 1373 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NRonPTa4jLdMvRC09Mr:-NRonPTa4jLdMvRC09Ms:b-c22vrg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8629f2ccd802ce92dc9e0540e03a2dfa0b941b8/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L1373)):*
> ```Kotlin
> 
>   @Test
>   fun `batchDeleteMeasurements throws NOT_FOUND when Measurement does not exist`(): Unit =
> ```

Add tests covering the validation.

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt` line 181 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NRomNem1fkgNg7o5d88:-NRouG9z4GfUwxHrTk7c:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8629f2ccd802ce92dc9e0540e03a2dfa0b941b8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L181)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

<=
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt` line 1373 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NRonPTa4jLdMvRC09Mr:-NRscOMG2q42XD3fJL3n:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8629f2ccd802ce92dc9e0540e03a2dfa0b941b8/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L1373)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Add tests covering the validation.
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BatchDeleteMeasurements.kt` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NS7GQvJ5EVnNbLyOZkj:-NS7fMWWDXRTxzXCwsh_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a064b7bac82db0aa34bdc594cf90642f6362f1fd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BatchDeleteMeasurements.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`@throws` is for when a method throws an exception directly. That is not the case here, where we are instead documenting the exceptions thrown by the`execute` method. We document this here because `execute` is the method that is called by the public interface of this class, but the method is not overridden.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BatchDeleteMeasurements.kt` line 51 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NS7HF2A4lPBuwfwWPfT:-NSC963t9xyPLOq-8Vca:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a064b7bac82db0aa34bdc594cf90642f6362f1fd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BatchDeleteMeasurements.kt#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since we're not returning the `Measurement`s we don't need to do the read for an entire `Measurement` entity which is heavy due to the joins involved.

The most efficient thing to do would be to use a `DELETE FROM` statement, i.e. execute Spanner DML rather than using mutations. This has the downside of not being able to pass on the context of which Measurement was not found in the case of an error. Therefore the next most efficient thing is a specific query that returns the `Key` for a Measurement row given its external IDs (`readKeyByExternalIds`). I would recommend adding this method to MeasurementReader's companion object.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918)* status: all files reviewed, 4 unresolved discussions (waiting on @jcorilla)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 128 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NSCXvjo369zDyL_PGDv:-NSCXvjo369zDyL_PGDw:b-ux6wf5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73e07332edf737830033040c7e53f2dc05f0e8e4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L128)):*
> ```Kotlin
>     }
> 
>     suspend fun readKeyByExternalIds(
> ```

Add KDoc, documenting the thrown exceptions.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 137 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NSCV58Q9FOrC7o4evl6:-NSCV58Q9FOrC7o4evl7:b-t75gxb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73e07332edf737830033040c7e53f2dc05f0e8e4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L137)):*
> ```Kotlin
>           SELECT
>           Measurements.MeasurementId AS measurementId,
>           Measurements.MeasurementConsumerId AS measurementConsumerId,
> ```

nit: Consistent query formatting



_Suggestion:_
```Kotlin
      val sql =
        """
        SELECT
          Measurements.MeasurementId AS measurementId,
          Measurements.MeasurementConsumerId AS measurementConsumerId
        FROM
          Measurements
          JOIN MeasurementConsumers USING (MeasurementConsumerId)
        """
          .trimIndent()
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 153 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NSCSuBOEA0OqHDan0aB:-NSCSuBOEA0OqHDan0aC:brmasud) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73e07332edf737830033040c7e53f2dc05f0e8e4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L153)):*
> ```Kotlin
>         .bind("externalMeasurementConsumerId")
>         .to(externalMeasurementConsumerId.value)
>         .bind("externalMeasurementId")
> ```

nit: Use DSL builder



_Suggestion:_
```Kotlin
      val statement = statement(sql) {
        appendClause(
          """
          WHERE
            ExternalMeasurementConsumerId = @externalMeasurementConsumerId
            AND ExternalMeasurementId = @externalMeasurementId
          """ .trimIndent()
        )
        bind("externalMeasurementConsumerId").to(externalMeasurementConsumerId.value)
        bind("externalMeasurementId").to(externalMeasurementId.value)
        appendClause("LIMIT 1")
      }
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 159 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NSCXhNABwGPlej4iEbn:-NSCXhNB2j50cLv2_2Wd:bb981aa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73e07332edf737830033040c7e53f2dc05f0e8e4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L159)):*
> ```Kotlin
>       val row: Struct =
>         readContext.executeQuery(statement.build()).singleOrNull()
>           ?: throw MeasurementNotFoundException { "Measurement not found $externalMeasurementId" }
> ```

I believe the version for when you have both an external MC ID and an external Measurement ID is `MeasurementNotFoundByMeasurementConsumerException`.



_Code quote:_
```Kotlin
MeasurementNotFoundException
```

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 128 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NSCXvjo369zDyL_PGDv:-NSH5lDW3dwLwzJ-2Rj4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73e07332edf737830033040c7e53f2dc05f0e8e4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L128)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add KDoc, documenting the thrown exceptions.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 159 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NSCXhNABwGPlej4iEbn:-NSDPieP4gsI5j_hhlyG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73e07332edf737830033040c7e53f2dc05f0e8e4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L159)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe the version for when you have both an external MC ID and an external Measurement ID is `MeasurementNotFoundByMeasurementConsumerException`.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 134 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NSHc6-rA8v5wRlEFy_r:-NSHc6-rA8v5wRlEFy_s:b28pzvo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9864ca6d9cf3542074ce3f7ad371715b601ee26/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L134)):*
> ```Kotlin
>      * ID pair.
>      *
>      * Throws a subclass of [KingdomInternalException]:
> ```

nit: you don't need this line here since you have `@throws`, which is explicit.



_Code quote:_
```Kotlin
     *
     * Throws a subclass of [KingdomInternalException]:
```

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BatchDeleteMeasurements.kt` line 44 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918#-NSKbZw81MdBkxlgMedu:-NSKbZw81MdBkxlgMedv:b-jzgstu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e208de07a2688c79624169fd8d40512624158431/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BatchDeleteMeasurements.kt#L44)):*
> ```Kotlin
> 
>     for (request in requests.requestsList) {
>       val externalMeasurementConsumerId = ExternalId(request.externalMeasurementConsumerId)
> ```

nit: I'd avoid to instantiate new variables for every entry in the ```requestsList```. I'd rather instantiate ExternalId objects inside ```readKeyByExteranlIds``` params



_Code quote (i):_
```Kotlin
val externalMeasurementConsumerId
```



_Code snippet (ii):_
```Kotlin
MeasurementReader.readKeyByExternalIds(
  transactionContext,
  ExternalId(request.externalMeasurementConsumerId),
  ExternalId(request.externalMeasurementId)
)
```

**Review by jcorilla — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/918)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
