### PR TITLE
fix: Allow zero reach in relative frequency variance computation.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1883)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1883)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1883)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt` line 164 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1883#-OANfyE2EXxb27VeM56F:-OANfyE2EXxb27VeM56G:b-b6zt5c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/114c15a55a9704de2cc068255473d0e5cde69384/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt#L164)):*
> ```Kotlin
>       relativeFrequencyMeasurementVarianceParams
> 
>     require(totalReach >= 0) { "Total reach must be non-negarive, but got $totalReach." }
> ```

`non-negative`

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1883)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13)

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1883)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt` line 164 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1883#-OANfyE2EXxb27VeM56F:-OAO_GHL7rxgusFWn3FX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/114c15a55a9704de2cc068255473d0e5cde69384/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt#L164)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`non-negative`
</blockquote></details>

Done.

**Review by ple13 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1883)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by ple13 — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1883)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
