### PR TITLE
Specify a default deadline on RPCs to Duchy internal Computations server.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/713)

### CODE REVIEW

**Comment by SanjayVas** [comment]
Related to #711

**Review by renjiezh — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/713)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt` line 124 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/713#-NDcr28m5XU1YO7ZrMPo:-NDcr28n9NtPLmluu9T8:budne9o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c3a7a9153ee24956c43beebbdcd3aa9e2486e32/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L124)):*
> ```Kotlin
>       heraldId = heraldId,
>       duchyId = flags.duchy.duchyName,
>       internalComputationsClient = ComputationsCoroutineStub(internalComputationsChannel),
> ```

There is a val `internalComputationsClient` above. Is it unused?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/713)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt` line 124 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/713#-NDcr28m5XU1YO7ZrMPo:-NDd1nEHB_Egjtxd1Gu-:bp231yb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c3a7a9153ee24956c43beebbdcd3aa9e2486e32/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L124)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

There is a val `internalComputationsClient` above. Is it unused?
</blockquote></details>

Done.

Was the result of a bad merge.

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/713)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/713)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
