### PR TITLE
Implement skeleton for reporting v2 integration test.

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 14 of 20 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075)* status: all files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075#-NYZBs3a3Hc3a2Qtbek9:-NYZBs3a3Hc3a2QtbekA:b-qcg6tb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7282ba3e35af85ca856df91b180711b2b4a27032/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt#L53)):*
> ```Kotlin
>   @After
>   fun stopComponents() {
>     inProcessComponents.stopEdpSimulators()
> ```

nit: only combine things into the same `@Before` or `@After` method if there's an ordering requirement.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075#-NYZCQHr3tKVx3kULl7R:-NYZCQHr3tKVx3kULl7S:b-xl7662) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7282ba3e35af85ca856df91b180711b2b4a27032/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt#L61)):*
> ```Kotlin
>     runBlocking {
>       // Use frontend simulator to create a reach and frequency measurement and verify its result.
>       inProcessComponents.frontendSimulator.executeReachAndFrequency("1234")
> ```

FrontendSimulator is the base test harness for the Life of a Measurement test. It doesn't need to be in the shared components.

The API stubs can all be created from the Kingdom channel (stubs are cheap so don't worry about having duplicates). You may need to expose the created resource information from InProcessComponents.



_Code quote:_
```Kotlin
inProcessComponents.frontendSimulator
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 114 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075#-NYZDk9WEHFWgbRK-5EW:-NYZDk9WEHFWgbRK-5EX:be8a42z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7282ba3e35af85ca856df91b180711b2b4a27032/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L114)):*
> ```Kotlin
>         signingPrivateKeyPath = MC_SIGNING_PRIVATE_KEY_PATH
>       }
>     }
> ```

Push uses of `runBlocking` up the stack where possible. This way if the caller happens to be a suspending function, we're not dropping in and out of blocking code.



_Suggestion:_
```Kotlin
    val measurementConsumerConfigGenerator: suspend () -> MeasurementConsumerConfig = {
      val measurementConsumerData = inProcessKingdomComponents.getMeasurementConsumerData()

      val measurementConsumer = 
        publicKingdomMeasurementConsumersClient
          .withAuthenticationKey(measurementConsumerData.apiAuthenticationKey)
          .getMeasurementConsumer(
            getMeasurementConsumerRequest { name = measurementConsumerData.name }
          )

      measurementConsumerConfig {
        apiKey = measurementConsumerData.apiAuthenticationKey
        signingCertificateName = measurementConsumer.certificate
        signingPrivateKeyPath = MC_SIGNING_PRIVATE_KEY_PATH
      }
    }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/server/ReportingDataServer.kt` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075#-NYZE_3m-TIiHXDKIecL:-NYZE_3m-TIiHXDKIecM:b-4cg9fh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7282ba3e35af85ca856df91b180711b2b4a27032/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/server/ReportingDataServer.kt#L30)):*
> ```Kotlin
> import picocli.CommandLine
> 
> abstract class ReportingDataServer : Runnable {
> ```

nit: I'd personally prefer not to copy the confusing "data server" naming. This is really the server that hosts the internal Reporting API services.



_Suggestion:_
```Kotlin
InternalReportingServer
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075#-NYZF75JBYzPT9QEMx2D:-NYZF75JBYzPT9QEMx2E:b-ha2t7p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7282ba3e35af85ca856df91b180711b2b4a27032/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt#L24)):*
> ```Kotlin
> 
> class EventGroupsService : EventGroupsCoroutineImplBase() {
>   override suspend fun listEventGroups(request: ListEventGroupsRequest): ListEventGroupsResponse {
> ```

There's not really a point to this override if you're just going to call `super` and not even have any comments.

Maybe drop this and just put a TODO on the class to implement all service methods.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075)* status: 6 of 21 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075#-NYZCQHr3tKVx3kULl7R:-NY_72FCEb4P2wOsYUqq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7282ba3e35af85ca856df91b180711b2b4a27032/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

FrontendSimulator is the base test harness for the Life of a Measurement test. It doesn't need to be in the shared components.

The API stubs can all be created from the Kingdom channel (stubs are cheap so don't worry about having duplicates). You may need to expose the created resource information from InProcessComponents.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 114 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075#-NYZDk9WEHFWgbRK-5EW:-NY_73ZK1blBcWvWeKu7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7282ba3e35af85ca856df91b180711b2b4a27032/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L114)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Push uses of `runBlocking` up the stack where possible. This way if the caller happens to be a suspending function, we're not dropping in and out of blocking code.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075#-NYZF75JBYzPT9QEMx2D:-NY_91B2-niUunbeGcn1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7282ba3e35af85ca856df91b180711b2b4a27032/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There's not really a point to this override if you're just going to call `super` and not even have any comments.

Maybe drop this and just put a TODO on the class to implement all service methods.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 6 of 20 files at r1, 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1075)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
