### PR TITLE
model outage internal api

### PR DESCRIPTION
**Pull request by Marco-Premier**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010)* status: all files reviewed, 4 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelOutageReader.kt` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010#-NVkUXq04rK-8-OIUgnk:-NVkUXq04rK-8-OIUgnl:bp0piuz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdf186ac571ca1369e81b6a6b101756afe339ba9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelOutageReader.kt#L57)):*
> ```Kotlin
>       FROM ModelOutages
>       JOIN ModelLines USING (ModelLineId)
>       JOIN ModelSuites ON (ModelSuites.ModelSuiteId = ModelLines.ModelSuiteId)
> ```

Joining on these tables needs to be done using the full primary key. So joining ModelLines with ModelSuites requires ModelProviderId and ModelSuiteId. ModelSuiteId is only unique for a ModelProviderId and is not globally unique.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelOutage.kt` line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010#-NVk_AIQ1KDJAiH_8SHr:-NVk_AIQ1KDJAiH_8SHs:bahmuuk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdf186ac571ca1369e81b6a6b101756afe339ba9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelOutage.kt#L96)):*
> ```Kotlin
>     ModelLines.ModelLineId
>     FROM ModelSuites JOIN ModelProviders USING(ModelProviderId)
>     JOIN ModelLines USING(ModelSuiteId)
> ```

Same here regarding the joins.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelOutagesServiceTest.kt` line 363 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010#-NVkX9KQCJN3RCI47O_Z:-NVkX9KQCJN3RCI47O__:bcut1bh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdf186ac571ca1369e81b6a6b101756afe339ba9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelOutagesServiceTest.kt#L363)):*
> ```Kotlin
> 
>   @Test
>   fun `streamModelOutages returns all all ACTIVE and DELETED model outages`(): Unit = runBlocking {
> ```

nit: all appears twice
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_outages_service.proto` line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010#-NVkXxDADsCfjGewD9Hy:-NVkXpI8BQupyYObRrtG:bvq5d0g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdf186ac571ca1369e81b6a6b101756afe339ba9/src/main/proto/wfa/measurement/internal/kingdom/model_outages_service.proto#L60)):*
> ```protobuf
>     fixed64 external_model_line_id = 3;
>     // Inclusive time.
>     google.protobuf.Timestamp model_outage_start_time = 4;
> ```

model_outage_start_time and model_outage_end_time are used together as a range so they should be part of a message like how AfterFilter is its own message.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelOutageReader.kt` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010#-NVo1EFC6yEEz9-ZZXIO:-NVo1EFC6yEEz9-ZZXIP:bbcqaed) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a53046a2d14b650bbcc873e3017ae4d616022002/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelOutageReader.kt#L56)):*
> ```Kotlin
>       ModelProviders.ExternalModelProviderId,
>       FROM ModelOutages
>       JOIN ModelLines
> ```

nit: should be able to just use USING for the joins since the column names are the same. i.e. USING(ModelProviderId, ModelSuiteId, ModelLineId)
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelOutage.kt` line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010#-NVo1yff35jOd3f2Cvex:-NVo1yff35jOd3f2Cvey:b-vdhdo0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a53046a2d14b650bbcc873e3017ae4d616022002/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelOutage.kt#L97)):*
> ```Kotlin
>     FROM ModelSuites JOIN ModelProviders USING(ModelProviderId)
>     JOIN ModelLines
>       ON(
> ```

nit: same here

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 12 of 18 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010)* status: all files reviewed, 4 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_outage.proto` line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010#-NW9NxMfAMbjX9uwxFTY:-NW9NxMfAMbjX9uwxFTZ:bhoo1fv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1b859c3cdf8e8145654bab41f4a1d5609507ede/src/main/proto/wfa/measurement/internal/kingdom/model_outage.proto#L40)):*
> ```protobuf
>     // The ModelOutage has been created.
>     ACTIVE = 1;
>     // The ModelOutage has been deleted.
> ```

mark that this is a terminal state
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_outage.proto` line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010#-NW9O4cdCaBUEG_1P6cu:-NW9O4cdCaBUEG_1P6cv:b436p5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1b859c3cdf8e8145654bab41f4a1d5609507ede/src/main/proto/wfa/measurement/internal/kingdom/model_outage.proto#L47)):*
> ```protobuf
> 
>   // When the ModelOutage was created.
>   google.protobuf.Timestamp create_time = 8;
> ```

these are both output only right?

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_outage.proto` line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010#-NW9NxMfAMbjX9uwxFTY:-NWBf4wz5yRUQj_xS5KI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1b859c3cdf8e8145654bab41f4a1d5609507ede/src/main/proto/wfa/measurement/internal/kingdom/model_outage.proto#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

mark that this is a terminal state
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_outage.proto` line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010#-NW9O4cdCaBUEG_1P6cu:-NWBf11uBmtqwTeZvL0A:b-hwc1xp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1b859c3cdf8e8145654bab41f4a1d5609507ede/src/main/proto/wfa/measurement/internal/kingdom/model_outage.proto#L47)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

these are both output only right?
</blockquote></details>

Yes indeed. Added the comment.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1010)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Pull request merged**
