### PR TITLE
Implement CreateMeasurementConsumer, CreateCertificate

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123)

### CODE REVIEW

**Comment by uakyol** [comment]
Part of #103

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 30 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123)* status: 30 of 31 files reviewed, 6 unresolved discussions (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md3LjHX2-v3c7H_YSzf:-Md3LjHX2-v3c7H_YSzg:bdb4t2p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt#L22)):*
> ```
> idSeed
> ```
nit: the term "seed" is generally used in the context of RNG. Perhaps `initialId` (which also implies that you post-increment in the getter)?
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md3LtvU2NKcKeNA17Xa:-Md3LtvU2NKcKeNA17Xb:b-gsoxqi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt#L22)):*
> ```
> DeterministicIdGenerator
> ```
`FixedIdGenerator` is also deterministic. Maybe `IncrementingIdGenerator`?
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md3M1LN1TnHUj6yTAQP:-Md3M1LN1TnHUj6yTAQQ:bhzzz9g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt#L22)):*
> ```
> iter
> ```
This isn't an iterator or an iterable. I think what you're referring to is the increment.

This should also probably have a default of 1. Otherwise, the default instance isn't meaningfully different than `FixedIdGenerator`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md3Kn63BnVdl2dIlqys:-Md3Kn64BbCEOtE0wUt4:b-i1dajb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L40)):*
> ```
> Mutation.newInsertBuilder
> ```
Use the Mutations DSL for any new code. See example usage in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46cb8174418645ecb0052d6a8ff714228d68c2b9/src/test/kotlin/org/wfanet/measurement/gcloud/spanner/MutationsTest.kt.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md3V4ElASk6bhNowoW-:-Md3V4ElASk6bhNowoW0:bj09j4q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt#L70)):*
> ```Kotlin
>     return measurementConsumer
>       .toBuilder()
>       .setExternalMeasurementConsumerId(externalMeasurementConsumerId)
> ```

I think you need to specify all of the IDs you generate, meaning the external certificate ID fields as well.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificateTest.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md3WGZC79bXABgf6d3z:-Md3WGZC79bXABgf6d4-:brcred4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificateTest.kt#L36)):*
> ```
> CreateCertificateTest
> ```
@efoxepstein are these Writer tests useful, or can we treat the Writers as implementation details that don't need testing since they should be covered by the Spanner service impl tests? I'd also therefore want to see the service method impl and test added in the same PR as the Writer. I've been thinking of the Writers as implementation details personally, as we don't strictly speaking need them and could just use AsyncDatabaseClient directly.  See https://testing.googleblog.com/2015/01/testing-on-toilet-prefer-testing-public.html

If we can drop the tests, we can also leave `KingdomDatabaseTestBase` alone in this PR and delete it when cleaning up the legacy path.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123)* status: 30 of 31 files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificateTest.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md3WGZC79bXABgf6d3z:-Md3qqG35ecMg-Xb75j2:b6htblh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificateTest.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> CreateCertificateTest
> ```
@efoxepstein are these Writer tests useful, or can we treat the Writers as implementation details that don't need testing since they should be covered by the Spanner service impl tests? I'd also therefore want to see the service method impl and test added in the same PR as the Writer. I've been thinking of the Writers as implementation details personally, as we don't strictly speaking need them and could just use AsyncDatabaseClient directly.  See https://testing.googleblog.com/2015/01/testing-on-toilet-prefer-testing-public.html

If we can drop the tests, we can also leave `KingdomDatabaseTestBase` alone in this PR and delete it when cleaning up the legacy path.
</blockquote></details>

this would be so good!

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123)* status: 30 of 31 files reviewed, 7 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md3M1LN1TnHUj6yTAQP:-Md3w6n7131EaLbgwW9f:b-3uslbx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt#L22)):*
> ```
>  var iter: Int = 0
> ```
 var iter: Int = 0 doesn't need to be a constructor parameter. Just define it as an internal var

maybe rename to `private var offset = 0`
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md3LtvU2NKcKeNA17Xa:-Md3wbKH887dZTlF8V6T:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> DeterministicIdGenerator
> ```
`FixedIdGenerator` is also deterministic. Maybe `IncrementingIdGenerator`?
</blockquote></details>

+1
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/LegacyKingdomDatabaseTestBase.kt, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md3xRG20t20tOhPkSBE:-Md3xRG20t20tOhPkSBF:b2t2r43) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/LegacyKingdomDatabaseTestBase.kt#L49)):*
> ```Kotlin
>     .build()
> 
> abstract class LegacyKingdomDatabaseTestBase : UsingSpannerEmulator(KINGDOM_LEGACY_SCHEMA) {
> ```

At a certain point, we need to delete all these legacy stuffs, so we don't need to mess with the code. The best time was before you started these PRs. 

whenever you have a clean branch, maybe take a pause and delete all these stuffs + the unsed protos such as Report, ReportConfig etc.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificateTest.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md3WGZC79bXABgf6d3z:-Md3xLhV2aX5zCjHyFDl:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificateTest.kt#L36)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

this would be so good!
</blockquote></details>

+1

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123)* status: 30 of 31 files reviewed, 8 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md40oSj4XsWjM--Lxi4:-Md40oSj4XsWjM--Lxi5:b-owby0v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt#L24)):*
> ```Kotlin
> import org.wfanet.measurement.internal.kingdom.MeasurementConsumer
> 
> class CreateMeasurementConsumer(private val measurementConsumer: MeasurementConsumer) :
> ```

I know that the internal.MeasurementConsumer doesn't have a `title` field, but the v2api.MeasurementConsumer does. 
Where does this field go? is it useful?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123)* status: 30 of 31 files reviewed, 8 unresolved discussions (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/123#-Md40oSj4XsWjM--Lxi4:-Md43rDg2-t2x0VAaSjW:b-w5fm84) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de7deb535aeffe2b3e5afcd0cf2f4adba627d84/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt#L24)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I know that the internal.MeasurementConsumer doesn't have a `title` field, but the v2api.MeasurementConsumer does. 
Where does this field go? is it useful?
</blockquote></details>

This came up in another discussion and I didn't get around to dealing with it, but the idea was to drop the `title` field from MeasurementConsumer and the `display_name` field from DataProvider in the public API. We can always add them back if we have a need for them.

**Pull request closed without merging**
