### PR TITLE
Update example exchange workflow

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468#-Mx_6f8q2Z-Zphh0C4oS:-Mx_6f8r8Nsk9XJHDvnq:bc0k4v) (no related file):*
Should be maybe delete this file from this repo instead? It doesn't appear to be used by any tests, and it's normally configured/serialized by EDP or MP.

---

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468#-Mx_6f8q2Z-Zphh0C4oS:-Mx_9vG65-OzXfT7Y-S8:b7tniji) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Should be maybe delete this file from this repo instead? It doesn't appear to be used by any tests, and it's normally configured/serialized by EDP or MP.
</blockquote></details>

I am okay with deleting this. But PanelMatchResourceSetup uses it which is not deployed currently. But I strongly support to keep that job there in case in the future there is a need of creating 1 EDP + 1 MP + 1 Rec. Exchange quickly for testing purposes.

---

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468#-Mx_6f8q2Z-Zphh0C4oS:-Mx_E05g6zBCyKbPqnEc:b-80tlqk) (no related file):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

I am okay with deleting this. But PanelMatchResourceSetup uses it which is not deployed currently. But I strongly support to keep that job there in case in the future there is a need of creating 1 EDP + 1 MP + 1 Rec. Exchange quickly for testing purposes.
</blockquote></details>

Sure.

---

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/k8s/testing/secretfiles/exchange_workflow.textproto, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468#-MxaQxZ2BsjILQpdCnHz:-MxaQxZ2BsjILQpdCnI-:b3ndskx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34a7799d52aefe41c2777b57c13cad6cda0a732b/src/main/k8s/testing/secretfiles/exchange_workflow.textproto#L1)):*
> ```
> # EDP generates a certificate.
> ```

I don't want to maintain copies in both repos -- can these live in cross-media-measurement-api or somewhere else @sanjayvas @yunyeng

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/k8s/testing/secretfiles/exchange_workflow.textproto, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468#-MxaQxZ2BsjILQpdCnHz:-MxaSUc44iwzDm3ub1XR:b3quqat) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34a7799d52aefe41c2777b57c13cad6cda0a732b/src/main/k8s/testing/secretfiles/exchange_workflow.textproto#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I don't want to maintain copies in both repos -- can these live in cross-media-measurement-api or somewhere else @sanjayvas @yunyeng 
</blockquote></details>

Lets merge the one in panel-exchange-client and we will get back to this one?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/k8s/testing/secretfiles/exchange_workflow.textproto, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468#-MxaQxZ2BsjILQpdCnHz:-Mxas1dY1ZlOXu6cdune:b-jcu6ny) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34a7799d52aefe41c2777b57c13cad6cda0a732b/src/main/k8s/testing/secretfiles/exchange_workflow.textproto#L1)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Lets merge the one in panel-exchange-client and we will get back to this one?
</blockquote></details>

That also SGTM. We can just leave the panel resource setup job alone for now.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @yunyeng)

___
*[src/main/k8s/testing/secretfiles/exchange_workflow.textproto, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468#-MxaQxZ2BsjILQpdCnHz:-Mxkq8EE6Cj1A4wATo-j:bmvoxzl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34a7799d52aefe41c2777b57c13cad6cda0a732b/src/main/k8s/testing/secretfiles/exchange_workflow.textproto#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That also SGTM. We can just leave the panel resource setup job alone for now.
</blockquote></details>

one problem there is there will be a circular dep. panel exchange already depends on this repo

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/k8s/testing/secretfiles/exchange_workflow.textproto, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468#-MxaQxZ2BsjILQpdCnHz:-MxlTKzN1a4i-M6oasXW:b-28094f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34a7799d52aefe41c2777b57c13cad6cda0a732b/src/main/k8s/testing/secretfiles/exchange_workflow.textproto#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

one problem there is there will be a circular dep. panel exchange already depends on this repo
</blockquote></details>

Sorry, what I meant was we don't need to update this workflow in cross-media-measurement right now, as it's only used by the panel resource setup job (which itself is not currently used). I had assumed that's what you were suggesting.

We should not have a dependency between this repo and panel-exchange-client in either direction.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/k8s/testing/secretfiles/exchange_workflow.textproto, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468#-MxaQxZ2BsjILQpdCnHz:-MxntWvNAUABgXI-y3YY:b-eeti9z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34a7799d52aefe41c2777b57c13cad6cda0a732b/src/main/k8s/testing/secretfiles/exchange_workflow.textproto#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, what I meant was we don't need to update this workflow in cross-media-measurement right now, as it's only used by the panel resource setup job (which itself is not currently used). I had assumed that's what you were suggesting.

We should not have a dependency between this repo and panel-exchange-client in either direction.
</blockquote></details>

can we move these files to cross-media-measurement-api then since both repos need exact copies of this file?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/k8s/testing/secretfiles/exchange_workflow.textproto, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468#-MxaQxZ2BsjILQpdCnHz:-Mxp-tKCB6APtrh5ox56:b8obias) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34a7799d52aefe41c2777b57c13cad6cda0a732b/src/main/k8s/testing/secretfiles/exchange_workflow.textproto#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can we move these files to cross-media-measurement-api then since both repos need exact copies of this file?
</blockquote></details>

They don't technically need exact copies of the file. The one in panel-exchange-client is purely documentation, giving an example. The one in cross-media-measurement is used by panel resource setup, which is currently unused but could theoretically be used for some kind of panel exchange correctness test. There's nothing requiring them to be the same.

That said, I'm personally dubious on keeping panel resource setup, partially because I'm not entirely certain of the best way to even set up a panel exchange correctness test in our current configuration given that requires code from two repos.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/468)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
