### PR TITLE
Implement updateRequisitionsAndKeySets() at the herald.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ComputationConversions.kt, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89#-MbDeuJt-IX6zoriX8uj:-MbDeuJt-IX6zoriX8uk:b7wd3u9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ae38a55c025bbc8383107e24a6aad206db210c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ComputationConversions.kt#L69)):*
> ```
> publicApiVersion: String
> ```
Technically affects an existing function too, but generally one of the benefits of using a specific type (enum) over strings is to be able to pass the specific type around. Prefer doing the enum conversion in the caller rather than passing the string.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 167 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89#-MbDffNC0E0ukfZqyR_V:-MbDffNC0E0ukfZqyR_W:b1kqoq1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ae38a55c025bbc8383107e24a6aad206db210c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L167)):*
> ```
> Attempt
> ```
nit: Attempts
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 169 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89#-MbDi2Uz4CQWoxCLCkhD:-MbDi2Uz4CQWoxCLCkhE:bfao446) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ae38a55c025bbc8383107e24a6aad206db210c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L169)):*
> ```
> pushing
> ```
The Kingdom doesn't push anything. I assume this means the Herald retrieving an updated system `Computation`.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 171 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89#-MbDglwPDhdpnPP-hGKQ:-MbDglwPDhdpnPP-hGKR:bhoh5x2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ae38a55c025bbc8383107e24a6aad206db210c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L171)):*
> ```Kotlin
>    * computation state and kingdom pushing globalComputation update to the herald.
>    */
>   private suspend fun runWithRetry(
> ```

I know this already existed before this PR, but this is somewhat odd behavior. The usual Kotlin convention for coroutine functions is that they either suspends *or* run something in "the background" by having the receiver type be CoroutineScope. Additionally, you generally want to use a scope specified by the caller rather than GlobalScope. (The caller is free to use GlobalScope, but it's better to use a specific scope such that the couritine isn't running "headless").

Is there a reason this needs to do the first attempt immediately rather than having all attempts happening in another scope?
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 188 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89#-MbDjtUe0IdL9O4Ytwb0:-MbDjtUe0IdL9O4Ytwb1:b-aqocai) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ae38a55c025bbc8383107e24a6aad206db210c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L188)):*
> ```
> IllegalStateException(message)
> ```
1. This should include the final attempt exception as its cause.
2. Use a logging method that takes in an exception so that the log includes the stack trace.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89#-MbDl81SEnR1O9E1ByEv:-MbDl81SEnR1O9E1ByEw:b8s5uvj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ae38a55c025bbc8383107e24a6aad206db210c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L84)):*
> ```
> Impl
> ```
nit: Usually Impl is for classes. I think the `Internal` suffix is more common for this case.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ComputationConversions.kt, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89#-MbDeuJt-IX6zoriX8uj:-MbIIx2nEbK7jT6-_Jsw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ae38a55c025bbc8383107e24a6aad206db210c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ComputationConversions.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> publicApiVersion: String
> ```
Technically affects an existing function too, but generally one of the benefits of using a specific type (enum) over strings is to be able to pass the specific type around. Prefer doing the enum conversion in the caller rather than passing the string.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 169 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89#-MbDi2Uz4CQWoxCLCkhD:-MbIJI3u7nOQCZdqRR2d:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ae38a55c025bbc8383107e24a6aad206db210c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L169)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> pushing
> ```
The Kingdom doesn't push anything. I assume this means the Herald retrieving an updated system `Computation`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 171 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89#-MbDglwPDhdpnPP-hGKQ:-MbIL9-9EWDEaWHYMBXY:b-58o6il) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ae38a55c025bbc8383107e24a6aad206db210c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L171)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I know this already existed before this PR, but this is somewhat odd behavior. The usual Kotlin convention for coroutine functions is that they either suspends *or* run something in "the background" by having the receiver type be CoroutineScope. Additionally, you generally want to use a scope specified by the caller rather than GlobalScope. (The caller is free to use GlobalScope, but it's better to use a specific scope such that the couritine isn't running "headless").

Is there a reason this needs to do the first attempt immediately rather than having all attempts happening in another scope?
</blockquote></details>

@efoxepstein the author of this part.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 188 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89#-MbDjtUe0IdL9O4Ytwb0:-MbIKu1--6L8P5sWjYnp:bm9x1ot) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ae38a55c025bbc8383107e24a6aad206db210c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L188)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> IllegalStateException(message)
> ```
1. This should include the final attempt exception as its cause.
2. Use a logging method that takes in an exception so that the log includes the stack trace.
</blockquote></details>

This is a TODO in line 69 to fail the computation using the system ComputationParticipantsService. I'll deal with this when doing that TODO.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 188 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89#-MbDjtUe0IdL9O4Ytwb0:-MbILnIO-AtDv0dx3gnZ:b-tyyk7s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ae38a55c025bbc8383107e24a6aad206db210c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L188)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

This is a TODO in line 69 to fail the computation using the system ComputationParticipantsService. I'll deal with this when doing that TODO.
</blockquote></details>

typo, "there is a TODO"

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @zachcwc)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 171 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89#-MbDglwPDhdpnPP-hGKQ:-MbNND8UCgW5IXLoLLW-:b-gpzw7h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ae38a55c025bbc8383107e24a6aad206db210c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L171)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

@efoxepstein the author of this part.
</blockquote></details>

I vaguely remember Jason preferring things this way but maybe I'm making that up. Agreed that this should probably take in a passed-in coroutine scope, and agreed that the first attempt should also run in the launched coroutine.

One thing to be careful of is a big backlog. There's no backpressure on the stream of `Computation`s coming in if we do it this way. We could use a semaphore: each new `Computation` acquires from the semaphore and each finished coroutine releases to it.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by zachcwc — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by zachcwc — APPROVED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
