### PR TITLE
Merge SimpleReport into MeasurementSystem CLI tool

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 644 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612#-N5LuwXPCDqVp1I2J5d5:-N5LuwXQDySWPfNTRTu3:bsd7y8z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b6a341b9e8b73437720b7c2062da08b22ea32d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L644)):*
> ```Kotlin
>   @ParentCommand private lateinit var parentCommand: Measurements
> 
>   @Option(
> ```

This is inconsistent with existing commands in MeasurementSystem, which use a Parameter rather than an Option for the resource being acted upon.

e.g. `accounts activate [options] <resource name>`

As an aside, I've been considering whether one of the following patterns would be better to avoid redundantly specifying the resource type:

* `measurements get --parent=measurementConsumers/xyz <resource ID>`
* `measurements get --measurement-consumer=<MC ID> <resource ID>`
    * Each ancestor resource in the chain has its own option for the ID, which makes copy-pasting easier between commands that share an ancestor
    * The code gets slightly more complicated when dealing with multiple parent paths, e.g. for `certificate` resources.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md` line 94 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612#-N5M-XBvDOS1m0zYPZQh:-N5M-XBw7xxukN2d7A48:b6o1f3j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b6a341b9e8b73437720b7c2062da08b22ea32d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md#L94)):*
> ```Markdown
>   
>   ```shell
>   MeasurementConsumer \
> ```

`MeasurementSystem` in examples instead of `MeasurementConsumer`



_Code quote:_
```Markdown
MeasurementConsumer
```
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 302 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612#-N5M0LKuBedJs92Nqr0P:-N5M0LKuBedJs92Nqr0Q:b-5tv8o6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b6a341b9e8b73437720b7c2062da08b22ea32d/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L302)):*
> ```Kotlin
> private class ExitException(val status: Int) : RuntimeException()
> 
> private class HeaderCapturingInterceptor : ServerInterceptor {
> ```

nit: I tend to keep the general helper classes/functions at the bottom to reduce the amount that someone has to scroll to see the actual tests. These should eventually be moved to common-jvm. In this file, you'd have the benefit of avoiding unnecessary diffs from moving things around.

Specific helpers for test setup I tend to keep close to the constants.

See https://developer.android.com/kotlin/style-guide#top-level_declarations for guidance on organization.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 644 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612#-N5LuwXPCDqVp1I2J5d5:-N6OnyBrDoACSZ8tIPXu:buqt7f8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b6a341b9e8b73437720b7c2062da08b22ea32d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L644)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is inconsistent with existing commands in MeasurementSystem, which use a Parameter rather than an Option for the resource being acted upon.

e.g. `accounts activate [options] <resource name>`

As an aside, I've been considering whether one of the following patterns would be better to avoid redundantly specifying the resource type:

* `measurements get --parent=measurementConsumers/xyz <resource ID>`
* `measurements get --measurement-consumer=<MC ID> <resource ID>`
    * Each ancestor resource in the chain has its own option for the ID, which makes copy-pasting easier between commands that share an ancestor
    * The code gets slightly more complicated when dealing with multiple parent paths, e.g. for `certificate` resources.
</blockquote></details>

Thanks.
I changed the measurement name as a parameter instead of an option. But the get command doesn't require to specify the parent. I prefer to keep the complete measurement name instead of separating them into `parent+id`. It is still easy to copy&paste and easy to understand the usage  ---- just give it the name of the measurement.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md` line 94 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612#-N5M-XBvDOS1m0zYPZQh:-N6O_VAA5TCdMFeb8O6U:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b6a341b9e8b73437720b7c2062da08b22ea32d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md#L94)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`MeasurementSystem` in examples instead of `MeasurementConsumer`
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 644 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612#-N5LuwXPCDqVp1I2J5d5:-N6nQp0C5TYrCvys6cr1:b-iqqday) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b6a341b9e8b73437720b7c2062da08b22ea32d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L644)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Thanks.
I changed the measurement name as a parameter instead of an option. But the get command doesn't require to specify the parent. I prefer to keep the complete measurement name instead of separating them into `parent+id`. It is still easy to copy&paste and easy to understand the usage  ---- just give it the name of the measurement.
</blockquote></details>

To clarify, it's not a question of separating to parent + ID but rather to using the IDs rather than the resource names to avoid redundancy.

e.g.

```shell
measurements get --measurement-consumer=YENiIm1WA94 WB2djZKqANU
```

vs.

```shell
measurements get measurementConsumers/YENiIm1WA94/measurements/WB2djZKqANU
```

In the latter case, you're specifying the resource collection twice: once in the subcommand name and once in the resource name. The options defining the parent can be reused for other commands on the same resource collection, such as ListMeasurements:

```shell
measurements list --measurement-consumer=YENiIm1WA94
```

That said, what you have is also fine. There are tradeoffs with any pattern.
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 210 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612#-N6nY3xZ7LNctyguS8J5:-N6nY3xZ7LNctyguS8J6:b-mnwen6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1b83c57325074cabf02b6e7861b5d396283ebf1/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L210)):*
> ```Kotlin
>     }
>   results +=
>     MeasurementKt.resultPair {
> ```

nit: you can go ahead and import these builder functions as long as they're not ambiguous.

Unfortunately, we can't use import aliases for these without breaking things for IntelliJ users. In cases where the name is ambiguous, you need to continue to import the containing type. See https://youtrack.jetbrains.com/issue/KTIJ-16471



_Code quote:_
```Kotlin
MeasurementKt.resultPair
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 644 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612#-N5LuwXPCDqVp1I2J5d5:-N6nfTi05rUY-dzdCWb-:b-j80w9c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b6a341b9e8b73437720b7c2062da08b22ea32d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L644)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify, it's not a question of separating to parent + ID but rather to using the IDs rather than the resource names to avoid redundancy.

e.g.

```shell
measurements get --measurement-consumer=YENiIm1WA94 WB2djZKqANU
```

vs.

```shell
measurements get measurementConsumers/YENiIm1WA94/measurements/WB2djZKqANU
```

In the latter case, you're specifying the resource collection twice: once in the subcommand name and once in the resource name. The options defining the parent can be reused for other commands on the same resource collection, such as ListMeasurements:

```shell
measurements list --measurement-consumer=YENiIm1WA94
```

That said, what you have is also fine. There are tradeoffs with any pattern.
</blockquote></details>

Thanks for clarifying that.

**Review by renjiezh — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/612)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
