### PR TITLE
Add script to run api-linter.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1073)

**Comment by SanjayVas** [comment]
This is similar to what was done in the cross-media-measurement-api repo.

**Comment by SanjayVas** [comment]
@tristanvuong2021 @riemanli FYI for the API linter config for v2 Reporting. Basically the v2 Reporting API should pass all linter rules except for 'core::0191::java-package' and 'core::0146::any'.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1073)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
