### PR TITLE
Implement v2alpha public certificates service

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 77 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-Mgw9s2yAiYjlkIKDZ5z:-Mgw9s2yAiYjlkIKDZ6-:b-yys68a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L77)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>         when {
>           DataProviderKey.fromName(request.parent) != null ->
>             DataProviderKey.fromName(request.parent)
>           DuchyKey.fromName(request.parent) != null -> DuchyKey.fromName(request.parent)
>           MeasurementConsumerKey.fromName(request.parent) != null ->
>             MeasurementConsumerKey.fromName(request.parent)
>           else -> null
> ```
</details>

Can you reuse `createResourceKey` here?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 226 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MgwA7On5slTEinLdQvm:-MgwA7On5slTEinLdQvn:btmosfm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L226)):*
> ```
> Any
> ```
`ResourceKey`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 228 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-Mgw9zX6DKW6ErWXWkXn:-Mgw9zX6DKW6ErWXWkXo:b7dut9f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L228)):*
> ```
> DataProviderCertificateKey.fromName(name)
> ```
This ends up parsing the name into a key twice for the selected one.

Perhaps a simple if chain? e.g.
```
var resourceKey: ResourceKey =  DuchyCertificateKey.fromName(name)
if (resourceKey != null) {
  return resourceKey
}
resourceKey = ...
```
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 346 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MgwAhv7-_Ju2JwzSsWv:-MgwAhv7-_Ju2JwzSsWw:b-t7vvic) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L346)):*
> ```Kotlin
> 
>   @Test
>   fun `refuseRequisition throws INVALID_ARGUMENT when name is missing`() {
> ```

Unrelated code changes?

**Comment by tristanvuong2021** [comment]
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 346 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MgwAhv7-_Ju2JwzSsWv:-MgwMfFv6gRmqKtaETx4:buqz2du) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L346)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Unrelated code changes?
</blockquote></details>

It wasn't doing anything because I already wrapped the call inside with run blocking so I just got rid of it.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 226 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MgwA7On5slTEinLdQvm:-MgwOptu2zkNxG2uUTw5:b2jubed) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L226)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Any
> ```
`ResourceKey`
</blockquote></details>

I actually tried this initially, but I couldn't get it to work.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 77 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-Mgw9s2yAiYjlkIKDZ5z:-Mgwla1f9hk7DUARZC6-:b-xzpazc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L77)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>         when {
>           DataProviderKey.fromName(request.parent) != null ->
>             DataProviderKey.fromName(request.parent)
>           DuchyKey.fromName(request.parent) != null -> DuchyKey.fromName(request.parent)
>           MeasurementConsumerKey.fromName(request.parent) != null ->
>             MeasurementConsumerKey.fromName(request.parent)
>           else -> null
> ```
Can you reuse `createResourceKey` here?
</blockquote></details>

Maybe? The comment on the proto said parent resource so I assumed DataProvider, Duchy, and MeasurementConsumer, but below the comment it says it is a Certificate. If it is also a Certificate, then I can use it here as well.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 67 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-Mh-WgU542WHUWMUE0PI:-Mh-WgU542WHUWMUE0PJ:bv4nrol) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L67)):*
> ```
>     val result = internalCertificatesStub.getCertificate(internalGetCertificateRequest)
>     return result.toCertificate()
> ```

nit, just
```
return internalCertificatesStub.getCertificate(internalGetCertificateRequest).toCertificate()
```
for all the methods
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 77 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-Mgw9s2yAiYjlkIKDZ5z:-Mh-Tp_U3jyV1NfkpsTB:b-dpwciq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L77)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Maybe? The comment on the proto said parent resource so I assumed DataProvider, Duchy, and MeasurementConsumer, but below the comment it says it is a Certificate. If it is also a Certificate, then I can use it here as well.
</blockquote></details>

The parent is for sure a DataProvider, Duchy, or MeasurementConsumer.

maybe just
```
  val dataProviderKey = DataProviderKey.fromName(request.parent)
  val duchyKey = DuchyKey.fromName(request.parent)
  val measurementConsumerKey = MeasurementConsumerKey.fromName(request.parent)

    val internalCertificate =
      parseCertificateDer(request.certificate.x509Der)
        .toBuilder()
        .apply {
                 when {
          dataProviderKey != null ->
              externalDataProviderId = dataProviderKey.dataProviderId
          duchyKey !=null ->
              ...
          }
        }
        .build()
```

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 77 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-Mgw9s2yAiYjlkIKDZ5z:-MhF2sw5BFX9hTZQUOGL:b-ilb5k1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L77)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

The parent is for sure a DataProvider, Duchy, or MeasurementConsumer.

maybe just
```
  val dataProviderKey = DataProviderKey.fromName(request.parent)
  val duchyKey = DuchyKey.fromName(request.parent)
  val measurementConsumerKey = MeasurementConsumerKey.fromName(request.parent)

    val internalCertificate =
      parseCertificateDer(request.certificate.x509Der)
        .toBuilder()
        .apply {
                 when {
          dataProviderKey != null ->
              externalDataProviderId = dataProviderKey.dataProviderId
          duchyKey !=null ->
              ...
          }
        }
        .build()
```


</blockquote></details>

Good idea so I did this.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 226 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MgwA7On5slTEinLdQvm:-MhK8m5OAUshBFmRwLYR:b-qur74h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L226)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I actually tried this initially, but I couldn't get it to work.
</blockquote></details>

That doesn't make sense, given that all of these types should extend from ResourceKey. Did you perhaps accidentally import the wrong ResourceKey when you tried? It should be `org.wfanet.measurement.api.v2alpha.ResourceKey`.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 346 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MgwAhv7-_Ju2JwzSsWv:-MhK7x5X1q1zj7ZBynHH:b2t1bft) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L346)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It wasn't doing anything because I already wrapped the call inside with run blocking so I just got rid of it.
</blockquote></details>

We normally don't put unrelated code changes together in a PR. You don't otherwise need to touch this service in this PR. That said, this is a pretty minor cleanup and fine to stay given that you've made it clear that it's intentional.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 226 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MgwA7On5slTEinLdQvm:-MhKEzqR9g0l7xYmD9zM:b-996za4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L226)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That doesn't make sense, given that all of these types should extend from ResourceKey. Did you perhaps accidentally import the wrong ResourceKey when you tried? It should be `org.wfanet.measurement.api.v2alpha.ResourceKey`.
</blockquote></details>

Oh, it was the wrong one.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 226 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MgwA7On5slTEinLdQvm:-MhKWnfT56PHs6iik_6l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aa14e3385ed5b465e7f6bb4e032d0bcfe6aa6a01/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L226)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Oh, it was the wrong one.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn, @stevenwarejones, and @zachcwc)

**Review by corbantek — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 3 of 4 files at r4, 1 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn, @stevenwarejones, and @zachcwc)

**Review by corbantek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @stevenwarejones, @tristanvuong2021, and @zachcwc)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesServiceTest.kt, line 76 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MhOjLR1EKNtcGWeWflU:-MhOjLR1EKNtcGWeWflV:be9a1im) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3620b6a054c560413f427c094a7e87ecd2af4abb/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesServiceTest.kt#L76)):*
> ```Kotlin
> 
>   @Before
>   fun initService() {
> ```

Question: Is the desired behavior to re-initialize before every Test?

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 3 of 4 files at r4, 1 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones, @tristanvuong2021, and @zachcwc)

___
*[src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel, line 30 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MhP-U3-81fh0Z5nyMrc:-MhP-U3-81fh0Z5nyMrd:b-fu5ks5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3620b6a054c560413f427c094a7e87ecd2af4abb/src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel#L30)):*
> ```Starlark
> )
> 
> alias(
> ```

For my own benefit: why do we always create an addtl entry here and refer to that in the project instead of referring to the wfa_measurement_proto repo directly?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @zachcwc)

___
*[src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel, line 30 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MhP-U3-81fh0Z5nyMrc:-MhP6vRs-hFOogGK-M6Y:bp9h3h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3620b6a054c560413f427c094a7e87ecd2af4abb/src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel#L30)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

For my own benefit: why do we always create an addtl entry here and refer to that in the project instead of referring to the wfa_measurement_proto repo directly? 
</blockquote></details>

It lets us treat the proto_library like it's defined in this repo, and shortens repetition (which will become more useful as we add other language targets such as kt_jvm_proto_library).
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesServiceTest.kt, line 76 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MhOjLR1EKNtcGWeWflU:-MhP7h4P-1OviDEScOlf:bg33va2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3620b6a054c560413f427c094a7e87ecd2af4abb/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesServiceTest.kt#L76)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Question: Is the desired behavior to re-initialize before every Test?
</blockquote></details>

We generally take the approach of instance initialization by default, where using class initialization is an optimization we can sometimes use. Some cases are ones that it's trivial to prove that state leakage won't be an issue (e.g. constants). Others we sometimes do because it's particularly expensive to initialize (e.g. Cloud Spanner emulator).

In this case, the test server rule will cause the channel to get initialized for each Test instance so each service must also have per-instance initialization.

**Review by oliver-amzn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @zachcwc)

___
*[src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel, line 30 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/194#-MhP-U3-81fh0Z5nyMrc:-MhPDPEA21KbYtGHJuBN:b3bko73) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3620b6a054c560413f427c094a7e87ecd2af4abb/src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It lets us treat the proto_library like it's defined in this repo, and shortens repetition (which will become more useful as we add other language targets such as kt_jvm_proto_library).
</blockquote></details>

🚀
thx!

**Pull request merged**
