### PR TITLE
Optimize privacy budget charge for reach and frequency measurement.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1650)

**Review by pasin30055 — APPROVED** [review]
LGTM. Thanks!

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1650)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13, @SanjayVas, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapperTest.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1650#-NznPTQz6MaGy8q-OeIt:-NznOk--ADp_zRNSaZbO:b3xk4vw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6588bfddd6518841516a96a2f4a21fe941340edd/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapperTest.kt#L67)):*
> ```Kotlin
>     val referenceId = "RequisitionId1"
>     val acdpChargeForReach =
>       AcdpParamsConverter.getLlv2AcdpCharge(
> ```

Why are you calling the llv2 methods?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1650)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapperTest.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1650#-NznPTQz6MaGy8q-OeIt:-NznT2FMAQsjMN6FOFYO:b-4k650l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6588bfddd6518841516a96a2f4a21fe941340edd/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapperTest.kt#L67)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why are you calling the llv2 methods?
</blockquote></details>

The method getLlv2AcdpCharge actually does the conversion for discrete Gaussian noise. For now, the HMSS protocol is using discrete Gaussian noise, so the method is used to calculate the conversion.

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1650)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @uakyol)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1650)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @uakyol)

**Review by uakyol — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1650#-:-NzoRp_6901-Ed828jc-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1650)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
