### PR TITLE
Update internal GetRequisition() for direct requisitions

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503)

### CODE REVIEW

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503)* status: all files reviewed, 5 unresolved discussions (waiting on @renjiezh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 212 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQwTZ8AbF5h2GpiUKy:-MzQwTZ8AbF5h2GpiUKz:b-t7blsd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L212)):*
> ```Kotlin
>       if (isComputedMeasurement(measurementStruct)) {
>         if (state == Requisition.State.FULFILLED) {
>           val fulfillingDuchyId = requisitionStruct.getLong("FulfillingDuchyId")
> ```

Could simply check whether FulfillingDuchyId is set in order to determine whether to set `externalFulfillingDuchyId`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 218 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQwOba3ZHt9LzBE9fk:-MzQwOba3ZHt9LzBE9fl:bzbcxp5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L218)):*
> ```Kotlin
>             }
>         }
>         for ((externalDuchyId, participantStruct) in participantStructs) {
> ```

This doesn't strictly need to be in the if block, as participantStructs will be empty in this case.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 263 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQuvse3_XwaPNY4rY5:-MzQuvse3_XwaPNY4rY6:b-4fbpff) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L263)):*
> ```Kotlin
> 
>     private fun isComputedMeasurement(struct: Struct): Boolean {
>       val measurementDetails =
> ```

Not a big fan of the fact that this is resulting in a extra details parse.

Is there not a way to tell this from one of the top-level columns? e.g. whether `ExternalComputationId` is set?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 543 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQxlnG2GX8TozcjbrU:-MzQxlnG2GX8TozcjbrV:batrdfb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L543)):*
> ```Kotlin
> 
>   @Test
>   fun `getRequisition returns expected direct requisition`() = runBlocking {
> ```

nit: "getRequisition returns expected requisition for direct measurement"

There's no such thing as a "direct requisition", only a "direct measurement".



_Code quote:_
```Kotlin
getRequisition returns expected direct requisition
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 645 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQyJcr51VWieKX46w3:-MzQyJcr51VWieKX46w4:b-invcrk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L645)):*
> ```Kotlin
> 
>   @Test
>   fun `getRequisitionByDataProviderId returns direct requisition`() = runBlocking {
> ```

nit: "getRequisitionByDataProviderId returns requisition for direct measurement"



_Code quote:_
```Kotlin
getRequisitionByDataProviderId returns direct requisition
```

**Comment by tristanvuong2021** [comment]
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 263 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQuvse3_XwaPNY4rY5:-MzR2UKn06jZE0V0I7Gd:bki6ptf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L263)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not a big fan of the fact that this is resulting in a extra details parse.

Is there not a way to tell this from one of the top-level columns? e.g. whether `ExternalComputationId` is set?
</blockquote></details>

ExternalComputationId would work. It is null for direct measurements.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 212 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQwTZ8AbF5h2GpiUKy:-MzRBdQj28S4ix1O3f4o:b-o4gjrn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L212)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Could simply check whether FulfillingDuchyId is set in order to determine whether to set `externalFulfillingDuchyId`
</blockquote></details>

Sorry sanjay, I didn't quite understand the change you suggested.
`DuchyIds.getExternalId(fulfillingDuchyId)` returns `String?`instead of `String` so it has to be a `checkNotNull()` to get `externalFulfillingDuchyId `. Thus cannot use only `!requisitionStruct.isNull("requisitionStruct")`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 218 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQwOba3ZHt9LzBE9fk:-MzR4mLMAVH-11_DhLjM:b-2osfnt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L218)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't strictly need to be in the if block, as participantStructs will be empty in this case.
</blockquote></details>

It looks clearer to me to keep all computation related fields together inside the if block though. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 263 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQuvse3_XwaPNY4rY5:-MzR5D_iDUT-WJy8SGEl:b9171is) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L263)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

ExternalComputationId would work. It is null for direct measurements.
</blockquote></details>

Done. 
Thanks for the solution. I have struggled a b due to the duplicated parse

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @renjiezh, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 212 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQwTZ8AbF5h2GpiUKy:-MzREIh80GsVrx0t1DEM:b-igwpc9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L212)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Sorry sanjay, I didn't quite understand the change you suggested.
`DuchyIds.getExternalId(fulfillingDuchyId)` returns `String?`instead of `String` so it has to be a `checkNotNull()` to get `externalFulfillingDuchyId `. Thus cannot use only `!requisitionStruct.isNull("requisitionStruct")`
</blockquote></details>

I'm suggesting dropping the unnecessary `isComputedMeasurement` check.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 218 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQwOba3ZHt9LzBE9fk:-MzRE72e1Ll2MwzpaGBB:b-hu5iq6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L218)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

It looks clearer to me to keep all computation related fields together inside the if block though. 
</blockquote></details>

I disagree, and prefer to reduce nesting.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 212 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQwTZ8AbF5h2GpiUKy:-MzRG96445XXAe9QJo20:b15o0cx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L212)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm suggesting dropping the unnecessary `isComputedMeasurement` check.
</blockquote></details>

Done.
Got rid of function `isComputedMeasurement()`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 218 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzQwOba3ZHt9LzBE9fk:-MzRG8Ei0xXXyYzKp9_v:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L218)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I disagree, and prefer to reduce nesting.
</blockquote></details>

Done.

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @renjiezh, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 186 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzRInNfBmnFAc2llwfy:-MzRInNfBmnFAc2llwfz:b-8od1nt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L186)):*
> ```Kotlin
>       // Map of external Duchy ID to ComputationParticipant struct.
>       val participantStructs =
>         if (isComputedMeasurement(struct))
> ```

Now that I think about it, is the change here even necessary. I think it would just be an empty list in the case of a direct measurement and associateBy will then create an empty map.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 186 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzRInNfBmnFAc2llwfy:-MzRKAGI7ol63BiI3xFh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0e83345036b2aeb531d806f5ace4df65517a0dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L186)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Now that I think about it, is the change here even necessary. I think it would just be an empty list in the case of a direct measurement and associateBy will then create an empty map.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 193 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503#-MzW7tcI668L6KhjH_8D:-MzW7tcI668L6KhjH_8E:bsmw8i2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9bb5112ecdc3e926606dd6cc1d40f56ab7c15048/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L193)):*
> ```Kotlin
>       return buildRequisition(struct, struct, participantStructs)
>     }
> ```

nit: accidental whitespace removal?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/503)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
