### PR TITLE
Create eventgroup metadata table and proto

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @robinsons)

___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxaR_H903sFl1XccfO6:-MxaR_H903sFl1XccfO7:bq9txlh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L25)):*
> ```protobuf
>   option (google.api.resource) = {
>     type: "halo.wfanet.org/EventGroupMetadataDescriptor"
>     pattern: "dataProviders/{ data_provider }/eventGroupMetadataDescriptors/{ event_group_metadata_descriptor }"
> ```

shouldn't the spaces be removed?

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469)* status: all files reviewed, 11 unresolved discussions (waiting on @chipingyeh)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxan1hi9KsySoK1HQO2:-Mxan1hi9KsySoK1HQO3:bg8ggl4) (no related file):*
Just a general comment around naming: Try to be careful to clearly distinguish between "event group metadata" and "event group metadata descriptor". The event group metadata is an instance that contains concrete data about an event group, like `campaign_id` or something. The descriptor is just the schema that describes the structure (type info, field names, etc.) of a metadata instance.

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 236 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxagjgtDQ4kABgEDUDv:-MxagjgtDQ4kABgEDUDw:bbw2qen) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L236)):*
> ```
>   INTERLEAVE IN PARENT DataProviders ON DELETE CASCADE;
> 
> CREATE TABLE EventGroupMetadata (
> ```

The table name should be the plural of the resource name: `EventGroupMetadataDescriptors`. Likewise, its ID column would be `EventGroupMetadataDescriptorId`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 238 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxagbh77_76jklfIeSO:-Mxagbh77_76jklfIeSP:byd5e2o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L238)):*
> ```
> CREATE TABLE EventGroupMetadata (
>   EventGroupMetadataId                    INT64 NOT NULL,
>   DataProviderId                          INT64 NOT NULL,
> ```

Can you swap the order of these IDs? Looking at the other tables, it looks like the columns are defined in primary key order.



_Code quote:_
```
  EventGroupMetadataId                    INT64 NOT NULL,
  DataProviderId                          INT64 NOT NULL,
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 240 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxah60v8_kDs9Ea-8Fp:-Mxah60v8_kDs9Ea-8Fq:b-cmrdzj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L240)):*
> ```
>   DataProviderId                          INT64 NOT NULL,
> 
>   DescriptorName                          STRING(MAX) NOT NULL,
> ```

What is the descriptor name?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 246 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxahPFtCvp-zQ-CzQed:-MxahPFtCvp-zQ-CzQee:bt8ysav) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L246)):*
> ```
>   DescriptorDetailsJson                   STRING(MAX) NOT NULL,
> 
>   FOREIGN KEY (DataProviderId)
> ```

We shouldn't need a foreign key, since this table is interleaved in `DataProviders` already.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxahgpE9E6I90ze7Ulw:-MxahgpE9E6I90ze7Ulx:b-u5lyd4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L1)):*
> ```protobuf
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

File name should be `event_group_metadata_descriptor.proto`.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxahup5AGb58ln85M_i:-Mxahup5AGb58ln85M_j:b5mq1d6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L22)):*
> ```protobuf
> option java_multiple_files = true;
> 
> message EventGroupMetadata {
> ```

Message name should be `EventGroupMetadataDescriptor`.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxai-3n50SKwZUCrEOk:-Mxai-3n50SKwZUCrEOl:b-1g6cea) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L23)):*
> ```protobuf
> 
> message EventGroupMetadata {
>   option (google.api.resource) = {
> ```

This is message in the internal system, so it doesn't need the `google.api.resource` annotation. Only the message definitions in the public API have those.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxaiCyZ7cMArMdZa9TY:-MxaiCyZ7cMArMdZa9TZ:b-yydjfw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L29)):*
> ```protobuf
> 
>   // Reference name of the metadata Descriptor.
>   string name = 1;
> ```

Rather than the resource name, this should be the data provider's ID and the descriptor's ID. You can reference an existing message like `EventGroup` as an example: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/kingdom/event_group.proto
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxajo0b7lpsFm3js6v2:-Mxajo0b7lpsFm3js6v3:bylamng) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L32)):*
> ```protobuf
> 
>   // FileDescriptorSet of the original metadata proto message.
>   FileDescriptorSet descriptor_set = 2;
> ```

In our other internal messages, we use a `Details` message to wrap the "body" of the resource. You can look at `EventGroup` for an example.

Using a wrapper just makes it easy to add new fields in the future, since they can be put into the `Details` message and serialized without updating the database schema.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469)* status: 0 of 3 files reviewed, 11 unresolved discussions (waiting on @robinsons and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxan1hi9KsySoK1HQO2:-Mxf8dcVBbmCF8nkeHbw:booay1t) (no related file):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Just a general comment around naming: Try to be careful to clearly distinguish between "event group metadata" and "event group metadata descriptor". The event group metadata is an instance that contains concrete data about an event group, like `campaign_id` or something. The descriptor is just the schema that describes the structure (type info, field names, etc.) of a metadata instance.
</blockquote></details>

Thanks for the feedback, this is noted.

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 236 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxagjgtDQ4kABgEDUDv:-MxeNB-REDpYLklKvp1L:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L236)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

The table name should be the plural of the resource name: `EventGroupMetadataDescriptors`. Likewise, its ID column would be `EventGroupMetadataDescriptorId`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 238 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxagbh77_76jklfIeSO:-MxeNEjw35d7DRkxuu3o:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L238)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Can you swap the order of these IDs? Looking at the other tables, it looks like the columns are defined in primary key order.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 240 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxah60v8_kDs9Ea-8Fp:-Mxf4f8TE1QUyW1C-9NH:b-uk0zun) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L240)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

What is the descriptor name?
</blockquote></details>

This was to be an externally-available id to identify the Descriptor with -- please see followup question in the proto file comment.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 246 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxahPFtCvp-zQ-CzQed:-MxeNI1QAN9RTGBgvikf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L246)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

We shouldn't need a foreign key, since this table is interleaved in `DataProviders` already.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxahgpE9E6I90ze7Ulw:-MxeNNL2EvNDVpvK8EZ0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L1)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

File name should be `event_group_metadata_descriptor.proto`.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxahup5AGb58ln85M_i:-MxeNOlC00wJ3z7_naWz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L22)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Message name should be `EventGroupMetadataDescriptor`.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxai-3n50SKwZUCrEOk:-MxeNQ_Q8TZeuaF1pVGW:b-vo6rda) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L23)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

This is message in the internal system, so it doesn't need the `google.api.resource` annotation. Only the message definitions in the public API have those.
</blockquote></details>

Ah, got it. Thanks -- done.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxaR_H903sFl1XccfO6:-MxeNSbs-wglOy8V2pg2:b89p8v1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't the spaces be removed?
</blockquote></details>

Good point, not sure why it was linted that way. This is being removed anyway, though.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxaiCyZ7cMArMdZa9TY:-Mxf4-6-84RFuTfu930S:b-yqk2ua) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L29)):*
> https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/kingdom/event_group.proto
Tentatively updated -- if the internal ID is automatically generated, will we need to maintain an external ID as well? How will clients query the Descriptor without the name/external id?
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxajo0b7lpsFm3js6v2:-MxeZmMI4e3SWy6YzpP2:b-cty1g3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L32)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

In our other internal messages, we use a `Details` message to wrap the "body" of the resource. You can look at `EventGroup` for an example.

Using a wrapper just makes it easy to add new fields in the future, since they can be put into the `Details` message and serialized without updating the database schema.
</blockquote></details>

That makes sense -- done.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 240 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-Mxah60v8_kDs9Ea-8Fp:-MxjY_lG2dj6kBjgxEkF:bss4a2b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L240)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

This was to be an externally-available id to identify the Descriptor with -- please see followup question in the proto file comment.
</blockquote></details>

Removed.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 239 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxfkxufETxyim6uWwTi:-MxjYqKOCNzhDfX6GV91:b-shltb4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b8de50e13ec0691e84d5c617ec29c2aaaabb8e2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L239)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

There should be an additional column for `ExternalEventGroupMetadataDescriptorId`.
</blockquote></details>

Thanks, this answers my question from below -- done.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxaiCyZ7cMArMdZa9TY:-MxjYk96CkQFO4Zo9SBo:b4tyswi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27ec868345d112a7a4f0a36c3226bfe73190e077/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata.proto#L29)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

This should be the same as what you did previously when implementing the EventGroups service. For instance, right here we use the helper function `apiIdToExternalId()` to do the conversion: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L307
</blockquote></details>

Thanks, wanted to confirm that was the approach we wanted here as well -- done.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptor.proto, line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxflC7LALi2F7plcu1T:-MxjYjG68qx7-qeg1nIW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b8de50e13ec0691e84d5c617ec29c2aaaabb8e2/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptor.proto#L24)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Please use the full name, `external_event_group_metadata_descriptor_id` for clarity.
</blockquote></details>

Done.

**Review by robinsons — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 241 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469#-MxkeJcF5t3I-OZGuwZ4:-MxkeJcF5t3I-OZGuwZ5:b-dqftys) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/38ba203df3454ff118a448cbba3554d939bf22cb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L241)):*
> ```
>   ExternalEventGroupMetadataDescriptorId  INT64 NOT NULL,
> 
>   -- wfa.measurement.internal.kingdom.EventGroupMetadata.FileDescriptorSet serialized proto.
> ```

nit: update this comment to point to the new proto path.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh)

**Review by robinsons — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/469)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
