### PR TITLE
Fix order of batch get measurements response

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1519)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt` line 276 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1519#-NsntjDJ4GmkZn3ZylR8:-NsntjDJ4GmkZn3ZylR9:bteq11) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d867756032244a9282aa0b28ca5ef4246f9ed998/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L276)):*
> ```Kotlin
>     request: BatchGetMeasurementsRequest
>   ): BatchGetMeasurementsResponse {
>     val externalMeasurementIds = request.externalMeasurementIdsList.distinct()
> ```

This may mess with the order. You can instead throw an invalid argument error if there are duplicates if you prefer. Alternatively, just allow duplicate values in the response.



_Code quote:_
```Kotlin
.distinct()
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1519)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt` line 276 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1519#-NsntjDJ4GmkZn3ZylR8:-NsoJnaC-Oomy7ZpVYng:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d867756032244a9282aa0b28ca5ef4246f9ed998/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L276)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This may mess with the order. You can instead throw an invalid argument error if there are duplicates if you prefer. Alternatively, just allow duplicate values in the response.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1519)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1519)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
