### PR TITLE
Fix the duchy for correctness test.

### PR DESCRIPTION
**Pull request by wangyaopw**
Two major changes.
1. new computations are created at INITIALIZATION_PHASE stage instead of
CONFIRMATION_PHASE. No output blob is expected from this stage.
2. Updated the RequisitionStore and ComputationStore to use the Store
interface.

https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F607228901955&view=2c2927c0-626b-4740-8620-af2a93b7d623

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271)

### CODE REVIEW

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271#-MjVK5miAmbHzhd84qzn:-MjVK5miAmbHzhd84qzo:b-z6zflh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/36d973287f77968c4bd8efbdff4e4516c2bcad3e/src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt#L49)):*
> ```Kotlin
>     val blobKey = generateBlobKey().withBlobKeyPrefix()
>     val createdBlob = storageClient.createBlob(blobKey, content)
>     return Blob(blobKey, createdBlob)
> ```

This part was intentional. The `Store` classes privately hold the prefix such that the actual blob key cannot be determined without using the `Store` to read it. The prefixed blob key should never leak outside of the `Store` object.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271#-MjVK5miAmbHzhd84qzn:-MjVNGOJ9yWTSLYXPB6i:bhjfawu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/36d973287f77968c4bd8efbdff4e4516c2bcad3e/src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This part was intentional. The `Store` classes privately hold the prefix such that the actual blob key cannot be determined without using the `Store` to read it. The prefixed blob key should never leak outside of the `Store` object.
</blockquote></details>

The ComputationStore doesn't work that way. It is using the actual path as the blob key.
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/duchy/storage/ComputationStore.kt

so when the duchy reads blobs, it is expecting the key to be the actual path to the blob.

Not including the prefix makes the duchy code more complex. For example, the input blobs to a computation stage can be mixed of
1. intermediate result generated locally, which has path starting with `/computations/`
2. locally fulfilled requisitions, which has path starting with `/requisitions/`
3. intermediate result collected from other duchies, which has path starting with `/requisitions/` (TODO on line 32 is to fix this, currently it just reuses the RequisitionStore)

When a computation stages begins, it reads all input blobs and concatenate them. This uses the same `ReadAllInputBlobs()` for all stages. If we want to use a specific `Store` object for a specific blob source, then we need to add a flag to tell which `Store` was used to write a blob. Currently, we only store the path of the blob in the duchy database.


I feel the prefix is more of avoiding key conflict, do we need to hide it?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271#-MjVK5miAmbHzhd84qzn:-MjVbyhK-54uqLOvokN8:b-986mfo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/36d973287f77968c4bd8efbdff4e4516c2bcad3e/src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt#L49)):*
> I feel the prefix is more of avoiding key conflict, do we need to hide it?

It's both. Each store should have a unique prefix to ensure it doesn't collide with any other store, and the prefix should be private to ensure that the blob can't be accessed without using that store.

>  If we want to use a specific Store object for a specific blob source, then we need to add a flag to tell which Store was used to write a blob.

Alternatively, you can have have a single store with an additional public prefix. Either way, each blob should only be accessible from one store.

> The ComputationStore doesn't work that way. It is using the actual path as the blob key.

Then it should be fixed not to do that.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271#-MjVK5miAmbHzhd84qzn:-MjVh9m3EYMYn6uccXzQ:b-652ls9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/36d973287f77968c4bd8efbdff4e4516c2bcad3e/src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I feel the prefix is more of avoiding key conflict, do we need to hide it?

It's both. Each store should have a unique prefix to ensure it doesn't collide with any other store, and the prefix should be private to ensure that the blob can't be accessed without using that store.

>  If we want to use a specific Store object for a specific blob source, then we need to add a flag to tell which Store was used to write a blob.

Alternatively, you can have have a single store with an additional public prefix. Either way, each blob should only be accessible from one store.

> The ComputationStore doesn't work that way. It is using the actual path as the blob key.

Then it should be fixed not to do that.
</blockquote></details>

In that case, I'll delete all other stores and only keep the computationStore.

There is already a TODO for that at line 32

**Review by SanjayVas — APPROVED** [review]
> Reviewed 7 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
Deleted the RequisitionStore, now the duchy uses the ComputationStore everywhere to avoid recording which store is used for which blob.

The additional public prefix (localComputationId, etc) in the path is removed since it is not adding much value and makes the test complicated.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271#-:-MjWESRYCPBt4oBUnRaC:b-7w19eb)* status: 8 of 20 files reviewed, all discussions resolved (waiting on @oliver-amzn and @SanjayVas)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
Added back RequisitionStore, and refactored the RequisitionStore and ComputationStore to use the new Store interface.

PTAL 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271#-:-Mj_Saq2ACTGChE0kWVj:b5cr962)* status: 10 of 23 files reviewed, all discussions resolved (waiting on @oliver-amzn and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 12 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/storage/ComputationStore.kt, line 24 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271#-Mj_dAgpB1csz8ZSazJm:-Mj_dAgq3ObNubrAAITl:bo90vm4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b75690e1871763cb26f93f152088731b0e7ca8e/src/main/kotlin/org/wfanet/measurement/duchy/storage/ComputationStore.kt#L24)):*
> ```
> "computations"
> ```
nit: start this with a `/`
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 478 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271#-Mj_dmdFEStt1X5pxyBC:-Mj_dmdFEStt1X5pxyBD:b-5mbpgm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b75690e1871763cb26f93f152088731b0e7ca8e/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L478)):*
> ```Kotlin
>   private val blobCount = AtomicInteger()
>   private val generatedBlobKeys = mutableListOf<String>()
>   private fun generateComputationBlobKey(context: ComputationBlobContext): String {
> ```

Note that if you want, you can just skip the context param and specify these functions to `forTesting` using lambda syntax. No harm, just letting you know that there's not a strict need to actually use the context in tests.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271)* status: 21 of 23 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/storage/ComputationStore.kt, line 24 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271#-Mj_dAgpB1csz8ZSazJm:-Mj_m8gt6EKC0T5SiCwG:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b75690e1871763cb26f93f152088731b0e7ca8e/src/main/kotlin/org/wfanet/measurement/duchy/storage/ComputationStore.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> "computations"
> ```
nit: start this with a `/`
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 478 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271#-Mj_dmdFEStt1X5pxyBC:-Mj_m5Tg2Uv3J5XnY4JL:b-q8jzb0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b75690e1871763cb26f93f152088731b0e7ca8e/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L478)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that if you want, you can just skip the context param and specify these functions to `forTesting` using lambda syntax. No harm, just letting you know that there's not a strict need to actually use the context in tests.
</blockquote></details>

got it

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 8 of 11 files at r1, 2 of 12 files at r3, 8 of 13 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
