### PR TITLE
Fix Hardcoded Project ID in Terraform File

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1579)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1579)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/terraform/gcloud/cmms/main.tf` line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1579#-Nvmulnl7HE-2rttNwBC:-Nvmulnl7HE-2rttNwBD:b-mbw3sw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/763a51e3df4d4727ad49f5dce73618692570b3cf/src/main/terraform/gcloud/cmms/main.tf#L97)):*
> ```HCL
> 
> resource "google_project_iam_member" "cloud_traces_agent" {
>   project = data.google_project.project.project_id
> ```

Sorry, I realized we have the google_client_config data resource already that can get this, so no need to add a google_project data resource.

`data.google_client_config.default.project`

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1579)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/terraform/gcloud/cmms/main.tf` line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1579#-Nvmulnl7HE-2rttNwBC:-Nvn8asP5HyyJmwFZaTT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/763a51e3df4d4727ad49f5dce73618692570b3cf/src/main/terraform/gcloud/cmms/main.tf#L97)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, I realized we have the google_client_config data resource already that can get this, so no need to add a google_project data resource.

`data.google_client_config.default.project`
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
Tested using tf plan in workflow.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1579#-:-Nvn8iRj9jTOuzmEwWJz:b-10f3tp)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
