### PR TITLE
Add release-test into github workflow

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1450)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1450)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`.github/workflows/release-test.yml` line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1450#-NpRv7ljB-izVF4xs35m:-NpSOLhU5nI28G0rSTDF:bcrqs8m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f24f8121265eec304c64afd86b5108e30449f492/.github/workflows/release-test.yml#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do you need all these defs here for that one test?
</blockquote></details>

Done.
Have to leave `--host_platform` to use the cache.
___
*[`.github/workflows/release-test.yml` line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1450#-NpRumdrAZk_4Dha--vP:-NpSOTwS72ra67xmHuSr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f24f8121265eec304c64afd86b5108e30449f492/.github/workflows/release-test.yml#L68)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You might not need this if you're not building everything.
</blockquote></details>

Done.
___
*[`.github/workflows/release-test.yml` line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1450#-NpRugtB3w-EoQCQjJGT:-NpSOViO4Q3FJf850x8Q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f24f8121265eec304c64afd86b5108e30449f492/.github/workflows/release-test.yml#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't build all the targets. That's already covered by presubmit.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1450)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`.github/workflows/release-test.yml` line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1450#-NpV_qsN3E4vjbVCacKZ:-NpV_qsN3E4vjbVCacK_:bqtbzs2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed694f3a115ba84b5aad12da69dfa727a9e05a5b/.github/workflows/release-test.yml#L55)):*
> ```YAML
>           ${{ steps.get-cache-params.outputs.restore-key }}
> 
>     - name: Build
> ```

nit: you don't need to split build and test when it's a single target, as test will automatically build.

The reason we do a separate build on presubmit is because not every build target is covered by an automated test

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1450)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`.github/workflows/release-test.yml` line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1450#-NpV_qsN3E4vjbVCacKZ:-NpVaOOx7_HsXPB_4IvQ:b-hdoej2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed694f3a115ba84b5aad12da69dfa727a9e05a5b/.github/workflows/release-test.yml#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: you don't need to split build and test when it's a single target, as test will automatically build.

The reason we do a separate build on presubmit is because not every build target is covered by an automated test
</blockquote></details>

Good to know that.
I feel separating them make it easier to view the log on the webpage.

**Pull request merged**
