### PR TITLE
Implement duchy's RequisitionFulfillment v2alpha api.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-Maii-a84hD_AMmyJZ--:-Maii-a84hD_AMmyJZ-0:b-gl9eji) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L45)):*
> ```
> StorageClient
> ```
Don't use StorageClient directly. Wrap it in a Store that encapsulates the real blob key by adding a private unique prefix. See `MetricValueStore`.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaigDphALI19SWtvD3a:-MaigCDNA7bQ_w6Sz9v0:b-1gpu9h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L72)):*
> ```
>         return FULFILLED_RESPONSE
> ```
Since we aren't verifying that the content bytes are the same as what was previously sent, this should be a `FAILED_PRECONDITION` error (requisition is in the wrong state to fulfill).

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: all files reviewed, 5 unresolved discussions (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaitKJ8EqDR9NAvgAfo:-MaitKJ9DM_PqLCVGin7:ba60h5v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L69)):*
> ```Kotlin
>             it.externalDataProviderId == externalRequisitionKey.externalDataProviderId &&
>               it.externalRequisitionId == externalRequisitionKey.externalRequisitionId
>           }!!
> ```

I feel like we should return a more meaningful error if we can't find this -- NPE isn't ideal, I think we want IllegalArgumentException. 

How about:

```
val matchingRequisition = gRpcRequireNotNull(computationToken.requisitionsList.find {  ... })
if (matcingRequisition.path.isNotBlank()) ...
```
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaiuTnYACQGHDcMjpBF:-MaiuTnZ3DlrCrcWj-1e:b-isy9oz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L76)):*
> ```Kotlin
> 
>       val blobKey = externalRequisitionKey.toBlobKey()
>       if (storageClient.getBlob(blobKey) == null) {
> ```

Should we have a `storageClient.hasBlob` method? It might be a lot more efficient.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 105 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-Maiur4M2WclFfI1FBgu:-Maiur4M2WclFfI1FBgv:b-pmr0t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L105)):*
> ```Kotlin
>           GetComputationTokenRequest.newBuilder().also { it.requisitionKey = this }.build()
>         )
>       } catch (e: StatusException) {
> ```

Maybe pull the try/catch out to a helper?

```
private suspend fun ExternalRequisitionKey.toComputationToken(): ComputationToken {
  val request = GetComputationTokenRequest.newBuilder().also { it.requisitionKey = this }.build()
  return getComputationToken(request).token
}

fun getComputationToken(request: GetComputationTokenRequest): Whatever {
  return try { computationsClient.getComputationToken(request) } catch (e: StatusException) { ... }
}
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-Maii-a84hD_AMmyJZ--:-Maj2AEX1vvYft9gkEjQ:bpmmrkn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> StorageClient
> ```
Don't use StorageClient directly. Wrap it in a Store that encapsulates the real blob key by adding a private unique prefix. See `MetricValueStore`.
</blockquote></details>

I am not sure if it is necessary to wrap it in another store to add a prefix.  In this case, the prefix is `/requisitions`
```
  private fun ExternalRequisitionKey.toBlobKey(): String {
    return "/requisitions/$externalDataProviderId/$externalRequisitionId"
  }
```

Even wrapping the code to a RequisitionStore, there is still no way to ensure the private prefix is unique among all the wrapper stores.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaitKJ8EqDR9NAvgAfo:-Maj145w0YGbjaljxxEV:bbvrlbb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L69)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I feel like we should return a more meaningful error if we can't find this -- NPE isn't ideal, I think we want IllegalArgumentException. 

How about:

```
val matchingRequisition = gRpcRequireNotNull(computationToken.requisitionsList.find {  ... })
if (matcingRequisition.path.isNotBlank()) ...
```
</blockquote></details>

requisition could not find is handled by 
```
/** Sends a request to get computation token. */
  private suspend fun getComputationToken(
    request: GetComputationTokenRequest
  ): GetComputationTokenResponse {
    return try {
      computationsClient.getComputationToken(request)
    } catch (e: StatusException) {
      if (e.status.code == Status.Code.NOT_FOUND) {
        throw Status.NOT_FOUND
          .withDescription("No computation is expecting this requisition $this.")
          .asRuntimeException()
      } else {
        throw Status.INTERNAL.withCause(e).asRuntimeException()
      }
    }
  }
```

If a computationToken is returned, the requisition is guaranteed to exist. There won't be NPE.

Checking if `path.isNotBlank()` is to tell if the requisition is already marked fulfilled locally or not. If yes, writing blob would be skipped, and the duchy can directly send fulfillRequisitionRequest to the kingdom.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaigDphALI19SWtvD3a:-Maj-6Tb2LdJso7VMu5l:bmttwqg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>         return FULFILLED_RESPONSE
> ```
Since we aren't verifying that the content bytes are the same as what was previously sent, this should be a `FAILED_PRECONDITION` error (requisition is in the wrong state to fulfill).
</blockquote></details>

You actually pointed out a bug here.

If the requisition is already marked fulfilled at the duchy, the duchy should only skip writing the blob, but still try to fulfill the requisition at the kingdom.

This is not try to handle the case that a EDP sends duplicated requests to the duchy, but an error case that the duchy stores the data and updates duchy database successfully but then the rpc to the kingdom fails due to whatever reason. In that case, the duchy cannot ack the EDP, and the EDP should get a FULFILLED_RESPONSE when it retries.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaiuTnYACQGHDcMjpBF:-Maiz-JhC7tdWWtEDSoy:bren1zc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L76)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should we have a `storageClient.hasBlob` method? It might be a lot more efficient.
</blockquote></details>

No. Won't that just be 
```
fun hasBlob(blobKey) : boolean = getBlob(blobKey)!=null
```
?
Is there a more efficient way?
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 105 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-Maiur4M2WclFfI1FBgu:-MaiyocN7-WWwwzdVnsk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L105)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe pull the try/catch out to a helper?

```
private suspend fun ExternalRequisitionKey.toComputationToken(): ComputationToken {
  val request = GetComputationTokenRequest.newBuilder().also { it.requisitionKey = this }.build()
  return getComputationToken(request).token
}

fun getComputationToken(request: GetComputationTokenRequest): Whatever {
  return try { computationsClient.getComputationToken(request) } catch (e: StatusException) { ... }
}
```
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-Maii-a84hD_AMmyJZ--:-MajMWfN91mM1qGB8rEk:bosv0ek) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L45)):*
> I am not sure if it is necessary to wrap it in another store to add a prefix. In this case, the prefix is `/requisitions`

The broader idea is that the service implementation shouldn't know where the blob is actually stored, just that it has some way to create one and read it back. Therefore, the prefix is something that's hidden from the service implementation. Separately, the blob key should contain some component to avoid collisions (e.g. two things trying to fulfill the same requisition at the same time), since the blob write happens before the Kingdom DB operation can detect a conflicting write. For the previous MetricValue implementation, the blob key exposed to the service is actually just a UUID, and `MetricValueStore` adds a prefix to help identify the blob type (e.g. for cleaning up orphan blobs where DB write failed after blob creation).

> there is still no way to ensure the private prefix is unique among all the wrapper stores.

True, but it's still far easier to get it right when all the prefixes are in the same place and under the responsibility of the storage layer rather than sprinkled throughout various service implementations.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-Maii-a84hD_AMmyJZ--:-Majcx5W4j53UrVyJbc5:b-oryycz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I am not sure if it is necessary to wrap it in another store to add a prefix. In this case, the prefix is `/requisitions`

The broader idea is that the service implementation shouldn't know where the blob is actually stored, just that it has some way to create one and read it back. Therefore, the prefix is something that's hidden from the service implementation. Separately, the blob key should contain some component to avoid collisions (e.g. two things trying to fulfill the same requisition at the same time), since the blob write happens before the Kingdom DB operation can detect a conflicting write. For the previous MetricValue implementation, the blob key exposed to the service is actually just a UUID, and `MetricValueStore` adds a prefix to help identify the blob type (e.g. for cleaning up orphan blobs where DB write failed after blob creation).

> there is still no way to ensure the private prefix is unique among all the wrapper stores.

True, but it's still far easier to get it right when all the prefixes are in the same place and under the responsibility of the storage layer rather than sprinkled throughout various service implementations.
</blockquote></details>

I switched to reuse the MetricValueStore. I'll rename it to RequisitionStore after MetricValueService is deleted.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaigDphALI19SWtvD3a:-MajccQb025hsZOojsoO:b-nokv4e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L72)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

You actually pointed out a bug here.

If the requisition is already marked fulfilled at the duchy, the duchy should only skip writing the blob, but still try to fulfill the requisition at the kingdom.

This is not try to handle the case that a EDP sends duplicated requests to the duchy, but an error case that the duchy stores the data and updates duchy database successfully but then the rpc to the kingdom fails due to whatever reason. In that case, the duchy cannot ack the EDP, and the EDP should get a FULFILLED_RESPONSE when it retries.
</blockquote></details>

Ah. The part that concerns me is that there's still no guarantee that the EDP sends the same content bytes on the retried call. From the EDP's POV, the failed call shouldn't have any side effects. Therefore if the EDP tries again but for some reason decides to send a different sketch than before (unlikely, but possible), then that sketch is what should get stored.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaiuTnYACQGHDcMjpBF:-MajeEUp8teaRpzBIjVf:b-picpy5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L76)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

No. Won't that just be 
```
fun hasBlob(blobKey) : boolean = getBlob(blobKey)!=null
```
?
Is there a more efficient way?
</blockquote></details>

`getBlob` doesn't actually result in the content being read, it just returns an object that has a `read` method.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaigDphALI19SWtvD3a:-Majfrrv-sAcmOgLIiy3:b8r9t9e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah. The part that concerns me is that there's still no guarantee that the EDP sends the same content bytes on the retried call. From the EDP's POV, the failed call shouldn't have any side effects. Therefore if the EDP tries again but for some reason decides to send a different sketch than before (unlikely, but possible), then that sketch is what should get stored.
</blockquote></details>

Do you think we should always store the data to a new blob and overwrite the recorded blobpath in the duchy db if EDP retries?

In that case, the duchy can not prevent an attack from the EDP if the EDP just wants to repeatedly fulfill a requisition thousands of times. Unless the duchy has a way to confirm this requisition is also marked fulfilled at the kingdom, and if yes reject EDP retries.

Not sure we care about this in the implementation for now.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaigDphALI19SWtvD3a:-Majs_01DAnYCS8uumLA:bdnzpuh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L72)):*
> Unless the duchy has a way to confirm this requisition is also marked fulfilled at the kingdom, and if yes reject EDP retries.

It does have a way to do this. The Kingdom Computations service exposes the Requisition state. I'm not sure if the Duchy currently caches this on computation updates. It would make sense to check for terminal states and fail fast. This could also save a write if the requisition has already been refused, or already fulfilled elsewhere in the unlikely case that the EDP interacts with more than one Duchy.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaigDphALI19SWtvD3a:-Majya7nDqKsEwxEed-s:b1jafzu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Unless the duchy has a way to confirm this requisition is also marked fulfilled at the kingdom, and if yes reject EDP retries.

It does have a way to do this. The Kingdom Computations service exposes the Requisition state. I'm not sure if the Duchy currently caches this on computation updates. It would make sense to check for terminal states and fail fast. This could also save a write if the requisition has already been refused, or already fulfilled elsewhere in the unlikely case that the EDP interacts with more than one Duchy.
</blockquote></details>

The kingdom requisition state changes are only passed to the duchies when all requisitions are fulfilled at the kingdom, i.e., the computation enters PENDING_PARTICIPANT_CONFIRMATION. During PENDING_REQUISITION_FULFILLMENT, the duchy/herald won't hear any update about the computation. In other words, if the duchy wants to know if the requisition is refused or fulfilled at another duchy, it needs to call the kingdom's computations service to get the latest state of the requisition.

I would say let's forget about weird cases like a EDP sends different data for a same requisition multiple times or fulfills a same requisitions at different duchies, or fulfills a requisition after it refuses it at the kingdom. These are like intentional bad behavior.

But a duchy's rpc to the kingdom fails after requisition locally received for sure would happen sometimes if there are tons of rpcs.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaigDphALI19SWtvD3a:-Mb7GDQB4pexeEds1jz0:bd9dl86) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L72)):*
> I would say let's forget about weird cases like a EDP sends different data for a same requisition multiple times or fulfills a same requisitions at different duchies, or fulfills a requisition after it refuses it at the kingdom. These are like intentional bad behavior.

We should be guarding against what could be intentional bad behavior as well, especially for public API calls. I agree it's not critical to address now, but we should at least document the possible error cases and add a TODO for how to address them.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82#-MaigDphALI19SWtvD3a:-Mb7d7b69pYbpUjCbAh5:b-gk6prr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48b7c0969bb44bd3732219f25ac90b12e4b51e76/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I would say let's forget about weird cases like a EDP sends different data for a same requisition multiple times or fulfills a same requisitions at different duchies, or fulfills a requisition after it refuses it at the kingdom. These are like intentional bad behavior.

We should be guarding against what could be intentional bad behavior as well, especially for public API calls. I agree it's not critical to address now, but we should at least document the possible error cases and add a TODO for how to address them.
</blockquote></details>

sg. Added a TODO for this.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by zachcwc — APPROVED** [review]
> Reviewed 6 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/82)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
