### PR TITLE
Implement getResult and getEsitimatedResult in the FE simulator.

### PR DESCRIPTION
**Pull request by wangyaopw**
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Fuserstory%2F606023913139

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhLLOt26le4FgUkdSdL:-MhLLOt26le4FgUkdSdM:b-7mj4e3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ca7de0ae21a82c194ee24842de09fe4750f2c3e/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L20)):*
> ```Kotlin
> import org.wfanet.measurement.api.v2alpha.MeasurementConsumer
> 
> interface FrontendSimulator {
> ```

Not part of this PR, but why do we have a separate interface and impl for the simulator? Do we expect multiple impls?
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt, line 338 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhLR-wq6KojHMiFz3SG:-MhLR-wq6KojHMiFz3SH:blw19n3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ca7de0ae21a82c194ee24842de09fe4750f2c3e/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt#L338)):*
> ```Kotlin
>       loadLibrary(
>         name = "estimators",
>         directoryPath = Paths.get("any_sketch_java/src/main/java/org/wfanet/estimation")
> ```

nit: use varargs overload of Paths.get to avoid hard-coding POSIX path separator
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/storage/SketchStore.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhLUEcm7Qit4TCoa_kL:-MhLUEcm7Qit4TCoa_kM:b7ld42s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ca7de0ae21a82c194ee24842de09fe4750f2c3e/src/main/kotlin/org/wfanet/measurement/loadtest/storage/SketchStore.kt#L26)):*
> ```
> called
> ```
nit: caller
___
*[src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhLUUqIB1ZORmthTonE:-MhLUUqIB1ZORmthTonF:b5egk47) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ca7de0ae21a82c194ee24842de09fe4750f2c3e/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L109)):*
> ```Kotlin
>   @Rule @JvmField val tempDirectory = TemporaryFolder()
> 
>   @get:Rule val ruleChain = chainRulesSequentially(tempDirectory, grpcTestServerRule)
> ```

Do we actually need the temp directory rule to trigger before the gRPC test server? Looks like our test server is just for mocks.

If we do, then I think that you'd leave the `@Rule` annotation off of `tempDirectory` since I believe this chaining rule handles that.
___
*[src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt, line 155 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhLUlp994nCOLqsYOX-:-MhLUlp994nCOLqsYOX0:baw1q3b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ca7de0ae21a82c194ee24842de09fe4750f2c3e/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L155)):*
> ```
> setup
> ```
nit: more descriptive name

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhLLOt26le4FgUkdSdL:-MhPFrOg1YFqTfMQg7pf:bmw3f8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ca7de0ae21a82c194ee24842de09fe4750f2c3e/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not part of this PR, but why do we have a separate interface and impl for the simulator? Do we expect multiple impls?
</blockquote></details>

Well, I didn't add those interfaces in the beginning. But since the m0 correctness test has an interface and impl class, and somehow I feel it is not a bad idea, so I added them.

One benefit of defining an interface is that we have a place to  easily see what the main functionalities of the class are. There won't be multiple impls anyway.

I don't mind deleting all those interfaces if they are non-necessary.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt, line 338 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhLR-wq6KojHMiFz3SG:-MhPHx_kDY6jSFtJC5NV:b7myghl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ca7de0ae21a82c194ee24842de09fe4750f2c3e/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt#L338)):*
> ```
> directoryPath
> ```
Done
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/storage/SketchStore.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhLUEcm7Qit4TCoa_kL:-MhPI7uL5davanl2q1Rp:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ca7de0ae21a82c194ee24842de09fe4750f2c3e/src/main/kotlin/org/wfanet/measurement/loadtest/storage/SketchStore.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> called
> ```
nit: caller
</blockquote></details>

Done
___
*[src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhLUUqIB1ZORmthTonE:-MhPKPFYE6ps5heepuDC:b99nok) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ca7de0ae21a82c194ee24842de09fe4750f2c3e/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L109)):*
> ```
> grpcTestServerRule
> ```
You are right. Deleted chainRules.
___
*[src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt, line 155 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhLUlp994nCOLqsYOX-:-MhPQh3Y2dy5W7pAHqey:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ca7de0ae21a82c194ee24842de09fe4750f2c3e/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L155)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> setup
> ```
nit: more descriptive name
</blockquote></details>

Done

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhLLOt26le4FgUkdSdL:-MhQ2ZF27ETetOdVeyPr:b8qy22) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ca7de0ae21a82c194ee24842de09fe4750f2c3e/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L20)):*
> I don't mind deleting all those interfaces if they are non-necessary.

That'd be great. Obviously not a high priority or something that needs to be included in this PR.
___
*[src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhQ2vuTD52hUAdn9cgJ:-MhQ2vuTD52hUAdn9cgK:b-2ag82j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/463d1666c8e446f30f9cbc58127236736f787fad/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L70)):*
> ```Kotlin
>         aggregator = Aggregator.UNIQUE
>         distributionBuilder.uniformBuilder.apply {
>           numValues = 10 * 1000 * 1000 // 10M
> ```

FYI: You can use underscores in integer literals for readability, e.g. `10_000_000`
___
*[src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt, line 195 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhQ3XghEF61cuZXNbck:-MhQ3XghEF61cuZXNbcl:b-barvp4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/463d1666c8e446f30f9cbc58127236736f787fad/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L195)):*
> ```Kotlin
>             .build()
> 
>         val sketchStore = SketchStore(FileSystemStorageClient(temporaryFolder.root))
> ```

Could make this a companion object property as well, so you don't have to have a separate instance in each test run. Optional though as it's a pretty cheap object.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhLLOt26le4FgUkdSdL:-MhQGWF54_Je8KMQpP1h:b-wiu54y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ca7de0ae21a82c194ee24842de09fe4750f2c3e/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I don't mind deleting all those interfaces if they are non-necessary.

That'd be great. Obviously not a high priority or something that needs to be included in this PR.
</blockquote></details>

A got another PR for this
___
*[src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhQ2vuTD52hUAdn9cgJ:-MhQDa9X-Cu4gb5ZTwO7:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/463d1666c8e446f30f9cbc58127236736f787fad/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

FYI: You can use underscores in integer literals for readability, e.g. `10_000_000`
</blockquote></details>

Done
___
*[src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt, line 195 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhQ3XghEF61cuZXNbck:-MhQDbUc612Q_GBkEJqH:bsevblc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/463d1666c8e446f30f9cbc58127236736f787fad/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L195)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Could make this a companion object property as well, so you don't have to have a separate instance in each test run. Optional though as it's a pretty cheap object.
</blockquote></details>

I tried that, it failed with error `the temporary folder has not yet been created`

` val sketchStore = SketchStore(FileSystemStorageClient(temporaryFolder.root))`
or 
` @JvmField @ClassRule sketchStore = SketchStore(FileSystemStorageClient(temporaryFolder.root))`
both failed.

There must be a way to make it work. any idea?

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt, line 195 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhQ3XghEF61cuZXNbck:-MhQIhel2zVUAuZk2UFK:b-pnolfz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/463d1666c8e446f30f9cbc58127236736f787fad/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L195)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I tried that, it failed with error `the temporary folder has not yet been created`

` val sketchStore = SketchStore(FileSystemStorageClient(temporaryFolder.root))`
or 
` @JvmField @ClassRule sketchStore = SketchStore(FileSystemStorageClient(temporaryFolder.root))`
both failed.

There must be a way to make it work. any idea?
</blockquote></details>

It'd be a `lateinit var` with `private set` that you initialize from a `@BeforeClass` function.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt, line 195 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhQ3XghEF61cuZXNbck:-MhU6kJO3biWZ24uwIQP:b-xxe4jg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/463d1666c8e446f30f9cbc58127236736f787fad/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L195)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It'd be a `lateinit var` with `private set` that you initialize from a `@BeforeClass` function.
</blockquote></details>

Done, Thanks

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @oliver-amzn)

**Review by corbantek — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt, line 177 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhUQV8vAlkOjO9t6Kde:-MhUQV8vAlkOjO9t6Kdf:b4lhi5e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4b73013a4eb6d3d6b49a18a051f44573dbebd8b/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt#L177)):*
> ```Kotlin
>           ::fakeGetHybridCryptorForCipherSuite
>         )
>       Result.parseFrom(signedResult.data)
> ```

Should you also verify the signature of the Result here too?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt, line 177 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201#-MhUQV8vAlkOjO9t6Kde:-MhUV2M_6XsX7Gq78ks-:byy43kz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4b73013a4eb6d3d6b49a18a051f44573dbebd8b/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt#L177)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Should you also verify the signature of the Result here too?
</blockquote></details>

I think yes.

I added to https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/203 so I don't need to refactor it again.

Thanks

**Review by corbantek — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
