### PR TITLE
Implement delete api for event group service

### PR DESCRIPTION
**Pull request by jcorilla**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822)

### CODE REVIEW

**Review by kungfucraig — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt` line 243 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822#-NMebvvE1lJSnHPqEK8f:-NMebvvF15l2LYpoalQ4:bgpkmih) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/843ad410231bc12cd810e150649212264f6eb179/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L243)):*
> ```Kotlin
>       else -> {
>         failGrpc(Status.PERMISSION_DENIED) {
>           "Caller does not have permission to delete EventGroups"
> ```

"Only a DataProvider can delete an event group"?

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt` line 243 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822#-NMebvvE1lJSnHPqEK8f:-NMeio03D1nJqWRwR_gQ:b-2y69hm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/843ad410231bc12cd810e150649212264f6eb179/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L243)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

"Only a DataProvider can delete an event group"?
</blockquote></details>

Yes, that's as intended. The idea is that DPs populate EGs for MCs, and that this API is to allows DPs to implement a retention policy. Allowing MCs to delete EGs will make synchronizing data from EDP->EGService quite a bit more difficult and I think for little gain.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt` line 243 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822#-NMebvvE1lJSnHPqEK8f:-NMemhKe8uADbk51LpuB:bcfqyi5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/843ad410231bc12cd810e150649212264f6eb179/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L243)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Yes, that's as intended. The idea is that DPs populate EGs for MCs, and that this API is to allows DPs to implement a retention policy. Allowing MCs to delete EGs will make synchronizing data from EDP->EGService quite a bit more difficult and I think for little gain.
</blockquote></details>

No. I meant just to update the message  to `"Only a DataProvider can delete an event group"` :)

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt` line 243 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822#-NMebvvE1lJSnHPqEK8f:-NMf5AB39PBzrIbVaWuF:b923zpj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/843ad410231bc12cd810e150649212264f6eb179/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L243)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

No. I meant just to update the message  to `"Only a DataProvider can delete an event group"` :)
</blockquote></details>

Changing the comment to be more specific

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
