### PR TITLE
Connecting Reporting UI to BFF

### PR DESCRIPTION
**Pull request by bdomen-ggl**
Changes:
* Remove the client requirements for TLS to connect to the GRPC-Gateway.
* Finished adding the API calls in the UI, fixing some of them.
* Added connection from UI to BFF, but the BFF isn't deployed yet, so will update the URL when it is. Unfortunately can't pass as a command line parameter or environment variable.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1345)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1345)* status: all files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl and @iverson52000)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/index.tsx` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1345#-NlV-k5H7L5YBnmMYdd7:-NlV-k5H7L5YBnmMYdd8:bropxqp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e2a81f87f6f5fc6e07c46197ab1550a02aa1ca6/experimental/reporting-ui/src/main/react/reporting-ui/index.tsx#L27)):*
> ```XML
> const configProps = {
>   reportingClient: new ReportingClientImpl(
>     {
> ```

Leave a TODO to figure out how to make this configurable.

My current thought is making this a template and filling it in from Make vars using `expand_template`. See [this example](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4877bb901568597cf3d0ef8030e1b7e82e074803/src/test/kotlin/org/wfanet/measurement/integration/k8s/BUILD.bazel#L88C1-L88C1) from our K8s tests.
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/model/reporting/init_api_props.ts` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1345#-NlV0gM12sVOWfiDITnd:-NlV0gM12sVOWfiDITne:bve2zwo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e2a81f87f6f5fc6e07c46197ab1550a02aa1ca6/experimental/reporting-ui/src/main/react/reporting-ui/model/reporting/init_api_props.ts#L18)):*
> ```XML
>   // eslint-disable-next-line node/no-unsupported-features/node-builtins
>   endpoint: URL;
>   measurementConsumer: string;
> ```

Add TODO for multi-MC support.

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1345)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @iverson52000 and @SanjayVas)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/index.tsx` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1345#-NlV-k5H7L5YBnmMYdd7:-NlVE9xD8AmHO9i11o0e:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e2a81f87f6f5fc6e07c46197ab1550a02aa1ca6/experimental/reporting-ui/src/main/react/reporting-ui/index.tsx#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Leave a TODO to figure out how to make this configurable.

My current thought is making this a template and filling it in from Make vars using `expand_template`. See [this example](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4877bb901568597cf3d0ef8030e1b7e82e074803/src/test/kotlin/org/wfanet/measurement/integration/k8s/BUILD.bazel#L88C1-L88C1) from our K8s tests.
</blockquote></details>

Done
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/model/reporting/init_api_props.ts` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1345#-NlV0gM12sVOWfiDITnd:-NlVEAmN3GD8paQBPgsF:bgx98i7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e2a81f87f6f5fc6e07c46197ab1550a02aa1ca6/experimental/reporting-ui/src/main/react/reporting-ui/model/reporting/init_api_props.ts#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add TODO for multi-MC support.
</blockquote></details>

Done

Should I also add it to the BFF? I'm leaving it here for now and will add some notes to the Reporting Demo UI doc for future work since this is a larger effort.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1345)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/model/reporting/init_api_props.ts` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1345#-NlV0gM12sVOWfiDITnd:-Nl_BCU9-wwi-Xxrm8jT:b-bpe42x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e2a81f87f6f5fc6e07c46197ab1550a02aa1ca6/experimental/reporting-ui/src/main/react/reporting-ui/model/reporting/init_api_props.ts#L18)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Done

Should I also add it to the BFF? I'm leaving it here for now and will add some notes to the Reporting Demo UI doc for future work since this is a larger effort.
</blockquote></details>

Your plan SGTM. I just spotted this as a place to leave a TODO since this prop would be deleted.

**Pull request merged**
