### PR TITLE
Update cross-media-measurement-api for EventGroup pattern.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by SanjayVas** [comment]
Depends on world-federation-of-advertisers/cross-media-measurement-api#148

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063#-NXqcWSb9O0-1hp5pbJT:-NXqcWSb9O0-1hp5pbJU:bvzvwe) (no related file):*
Need to fix the v2 EventGroupKey.

___

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063#-NXqb3LdAjqS4SaXR4eG:-NXqb3LeAWYvlyImP4ia:b-bgs8pd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcf13f4d0dcc61b1a73297322dfd65f4fe937040/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt#L38)):*
> ```Kotlin
>  * Throws one of the following [KingdomInternalException] types on [execute]:
>  * * [EventGroupNotFoundException] EventGroup not found
>  * * [EventGroupNotFoundByMeasurementConsumerException] EventGroup not found
> ```

This exception was added in the comment, but I don't see it used here.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063#-NXqcWSb9O0-1hp5pbJT:-NXqt0R-2_hobR_8o7iM:b4a5a83) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Need to fix the v2 EventGroupKey.
</blockquote></details>

I split that out into #1064 instead.

___

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063#-NXqb3LdAjqS4SaXR4eG:-NXqtNnx7coUR9pHXDOp:b28sz34) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcf13f4d0dcc61b1a73297322dfd65f4fe937040/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt#L38)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This exception was added in the comment, but I don't see it used here.
</blockquote></details>

Done.

I had originally tried to support Delete by the secondary pattern, but then realized only DataProviders can delete event groups anyway.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — DISMISSED** [review]
> Reviewed 8 of 20 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupKey.kt` line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063#-NXuqanX5l-GJQI7ls_S:-NXuqanX5l-GJQI7ls_T:b-j83rop) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e977044fb8bc02a98debb7eecde7a69b4ffea250/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupKey.kt#L24)):*
> ```Kotlin
> 
> /** [ResourceKey] of an EventGroup. */
> data class EventGroupKey(val dataProviderId: String, val eventGroupId: String) : ChildResourceKey {
> ```

rename to DataProviderEventGroupKey

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063)* status: 20 of 23 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupKey.kt` line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063#-NXuqanX5l-GJQI7ls_S:-NXv2euIEiLMuSWN3-mk:b-733ytk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e977044fb8bc02a98debb7eecde7a69b4ffea250/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupKey.kt#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

rename to DataProviderEventGroupKey
</blockquote></details>

The naming is intentional. The `ResourceKey` type without a prefix is the canonical ones. The ones with prefixes are the non-canonical ones.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 16 of 20 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1063)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
