### PR TITLE
Apply filter expression to EventGroup message.

### PR DESCRIPTION
**Pull request by SanjayVas**
This also fixes an issue where an error would be thrown if metadata wasn't set.

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/788)

### CODE REVIEW

**Comment by SanjayVas** [comment]
Includes workarounds for projectnessie/cel-java#295.

**Comment by SanjayVas** [comment]
Replaces #752.

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/788)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/788#-NJ7RM2XCbSks5cKrmVe:-NJ7RM2XCbSks5cKrmVf:bkptvyz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/986e4a96c6147ba7e2b94e5a0f78672da5cacbc5/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L67)):*
> ```Kotlin
>    * TODO(projectnessie/cel-java#295): Remove when fixed.
>    */
>   private val knownMetadataTypes: TypeRegistry = TypeRegistry.getEmptyTypeRegistry()
> ```

Are you planning to make a separate PR for the deployment/docs using this field.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/788)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/788#-NJ7RM2XCbSks5cKrmVe:-NJ7bnBz-YUBy-6Bp-rd:b-d0xgqx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bbe1b1019f6ada9deef5fb96c575f491faf8948/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L67)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Are you planning to make a separate PR for the deployment/docs using this field.
</blockquote></details>

It's only needed when the metadata message is one that happens to be compiled into the binary. I don't think that case will be hit in production. It's just by the test since we have the message as a compile-time dependency.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/788)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by duliomatos1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/788#-:-NJIrCTp7_VwLRhcRAYW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Comment by SanjayVas** [comment]
This was incorrectly marked as merged due to a base change combined with auto-merge. It has **not** been merged.

**Pull request merged**
