### PR TITLE
Lint repo with ktfmt 0.34

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/483)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 53 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/483)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 53 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/483)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/483)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Comment by SanjayVas** [comment]
Went ahead and rebased this on HEAD and merging to avoid this sitting for too long and drifting.

**Pull request merged**
