### PR TITLE
Build mTLS channels everywhere in the CMMS

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @stevenwarejones, @wangyaopw, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfJcZwn2zT6KY5_BK81:-MfJcZwo5ePOmmnM-mO1:b-e006l6) (no related file):*
I thought that you and @stevenwarejones had discussed the fact that he ended up co-opting the test cert generation as part of world-federation-of-advertisers/common-jvm#15. I prefer how that PR puts test cert generation in a more common location that may be used by both the consent signaling client and CMMS K8s targets.

---

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @stevenwarejones, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfJcZwn2zT6KY5_BK81:-MfJm_Nc855iMgD88Q64:b-xy33p1) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought that you and @stevenwarejones had discussed the fact that he ended up co-opting the test cert generation as part of world-federation-of-advertisers/common-jvm#15. I prefer how that PR puts test cert generation in a more common location that may be used by both the consent signaling client and CMMS K8s targets.
</blockquote></details>

yeah, that makes sense. I'll wait until that PR is in and then use the code in the common-jvm

---

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfJcZwn2zT6KY5_BK81:-MfhYGuYC5BZs2nziyt4:b-lhch7s) (no related file):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

yeah, that makes sense. I'll wait until that PR is in and then use the code in the common-jvm
</blockquote></details>

Its in FYI: https://github.com/world-federation-of-advertisers/common-jvm/pull/15

---

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @stevenwarejones, @wangyaopw, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfJcZwn2zT6KY5_BK81:-MfiTWFo2J69EX1r-t-q:bpalrcq) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Its in FYI: https://github.com/world-federation-of-advertisers/common-jvm/pull/15
</blockquote></details>

I created a v0.2.0 release of common-jvm that includes the change. Note that there are some other incompatible changes (e.g. to `buildChannel`) that you'll need to handle in order to update to that version. I'd personally recommend doing that in a separate PR.

---

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @stevenwarejones, @wangyaopw, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfJcZwn2zT6KY5_BK81:-MfiTyLZ2WKHmy9n_GOc:b606cd1) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I created a v0.2.0 release of common-jvm that includes the change. Note that there are some other incompatible changes (e.g. to `buildChannel`) that you'll need to handle in order to update to that version. I'd personally recommend doing that in a separate PR.
</blockquote></details>

Though I guess if this change also covers swapping everything over to the TLS overloads for buildChannel, then it's fine to do it in the same PR.

---

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfJcZwn2zT6KY5_BK81:-MfiUKtUBNBargPEaERn:b-q76ds1) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Though I guess if this change also covers swapping everything over to the TLS overloads for buildChannel, then it's fine to do it in the same PR.
</blockquote></details>

yep, the pr basically covers everything about TLS, including updating buildChannels and fixing the cue files. Should be ready soon.

---

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 22 files at r2, 27 of 39 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: 28 of 45 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt, line 72 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjSK9j8EY2kuKnIE74:-MfjSK9j8EY2kuKnIE75:byx4q1h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1b0d83ba05ca1c4e40457ad094a424e8c2ce86e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L72)):*
> ```
> The authority used with TLS and HTTP virtual hosting of the Kingdom's system API
> ```
Similar to my comment about the name, I think rather than trying to derive the description from the confusing `overrideAuthority` method, we instead make it clear that this is the expected hostname in the server's TLS certificate?
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt, line 75 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjPyNGCRuS9i81bQDC:-MfjPyNGCRuS9i81bQDD:b-w8cbsc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1b0d83ba05ca1c4e40457ad094a424e8c2ce86e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L75)):*
> ```
> Authority
> ```
I believe the "authority" in `overrideAuthority` where I assume this name comes from refers to the authority component of a URI (i.e.. The salient information for the flag isn't just that it's an authority, but specifically that it's the one listed in the TLS certificate.

Confusingly, that component refers to host and port together (hence why we reference it in the description of target flags). As far as I know, you don't have a port number in an X.509 subject alternative name. Perhaps `CertHost` instead of `Authority`?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: 28 of 45 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt, line 75 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjPyNGCRuS9i81bQDC:-MfjTVWsA3or7QjTfp7I:bsha0s7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1b0d83ba05ca1c4e40457ad094a424e8c2ce86e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L75)):*
> CertHost
CertHost works for me.
Before I chose `Authority`, I was using `CertSanHost`, which I gave up for some reason. How do you like that one?

**Review by oliver-amzn — CHANGES_REQUESTED** [review]
> Reviewed 9 of 39 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: 34 of 45 files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/k8s/base.cue, line 111 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjSmSp0jlIKQWWWabG:-MfjSmSp0jlIKQWWWabH:bcgi66h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a52ca2a075e553f832ac5c2815b3fad337ad1061/src/main/k8s/base.cue#L111)):*
> ```
> all-test-certs-cfc2f5h25g
> ```

Dat name though.

Does this refer to the secret name in your kubernetes cluster that you created manually? 
How does this work with e.g. KiND? 
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt, line 87 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjY_zl0vNV5D3pYBKa:-MfjY_zl0vNV5D3pYBKb:b-m86tim) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a52ca2a075e553f832ac5c2815b3fad337ad1061/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L87)):*
> ```
> names = ["--computations-service-authority"],
> ```

There's a bit of repetition here as this is repeated in four places - is there a way to pul this (and maybe some of the others flags) out and have them just in one place?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: 34 of 45 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt, line 75 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjPyNGCRuS9i81bQDC:-MfjZ-CkDnm2lOtNMI1g:b8dqzte) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1b0d83ba05ca1c4e40457ad094a424e8c2ce86e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L75)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> CertHost
CertHost works for me.
Before I chose `Authority`, I was using `CertSanHost`, which I gave up for some reason. How do you like that one?
</blockquote></details>

Of the two I think I'd prever just `CertHost`. We can indicate that the hostname comes from the SAN in the description.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: 27 of 46 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[src/main/k8s/base.cue, line 111 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjSmSp0jlIKQWWWabG:-MfjjIsH0jZh4WoYhLlB:b-ela2zv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a52ca2a075e553f832ac5c2815b3fad337ad1061/src/main/k8s/base.cue#L111)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> ```
> all-test-certs-cfc2f5h25g
> ```

Dat name though.

Does this refer to the secret name in your kubernetes cluster that you created manually? 
How does this work with e.g. KiND? 
</blockquote></details>

The hash in the name matches the secret generated using the test certificates checked in this PR.

In KIND, it is likely we don't need to use kubernetes secert, and can just read from local files. Doesn't have chance to test KIND yet.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt, line 72 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjSK9j8EY2kuKnIE74:-Mfjk3Vm4hLaBe-eWcMo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1b0d83ba05ca1c4e40457ad094a424e8c2ce86e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> The authority used with TLS and HTTP virtual hosting of the Kingdom's system API
> ```
Similar to my comment about the name, I think rather than trying to derive the description from the confusing `overrideAuthority` method, we instead make it clear that this is the expected hostname in the server's TLS certificate?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt, line 75 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjPyNGCRuS9i81bQDC:-Mfjk3F82mE7XWMwpEs-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1b0d83ba05ca1c4e40457ad094a424e8c2ce86e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L75)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Of the two I think I'd prever just `CertHost`. We can indicate that the hostname comes from the SAN in the description.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt, line 87 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjY_zl0vNV5D3pYBKa:-Mfjj2ff5_DCjexIwsby:b-6iphp0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a52ca2a075e553f832ac5c2815b3fad337ad1061/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L87)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> ```
> names = ["--computations-service-authority"],
> ```

There's a bit of repetition here as this is repeated in four places - is there a way to pul this (and maybe some of the others flags) out and have them just in one place?
</blockquote></details>

Good suggestion. Defined all these flags in a common file, i.e., `ServerFlags.kt`. The code looks much cleaner now.
Thanks.

**Review by oliver-amzn — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 24 of 39 files at r4, 7 of 14 files at r6, 7 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @zachcwc)

___
*[src/main/k8s/base.cue, line 111 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjSmSp0jlIKQWWWabG:-Mfk0H6M8uuDB7vLyyEi:bnapte3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a52ca2a075e553f832ac5c2815b3fad337ad1061/src/main/k8s/base.cue#L111)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

The hash in the name matches the secret generated using the test certificates checked in this PR.

In KIND, it is likely we don't need to use kubernetes secert, and can just read from local files. Doesn't have chance to test KIND yet.
</blockquote></details>

Ok, I guess in that case we would need to change the mount for KiND to not use the secret but either add the files to the container or mount them otherwise, right?
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/ServiceFlags.kt, line 1 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-Mfk11rO8sBZPVdUKGY7:-Mfk11rP-1MDZ7lW0bCI:b-2trwp6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63829f81e10d17b331b7e9caef562471ff9d8461/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/ServiceFlags.kt#L1)):*
> ```
> ServiceFlags.kt
> ```

👍
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt, line 87 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjY_zl0vNV5D3pYBKa:-Mfk0Wdz27QjXt7NyQuX:b44u5k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a52ca2a075e553f832ac5c2815b3fad337ad1061/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L87)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Good suggestion. Defined all these flags in a common file, i.e., `ServerFlags.kt`. The code looks much cleaner now.
Thanks.
</blockquote></details>

🚀

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @zachcwc)

___
*[src/main/k8s/base.cue, line 111 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjSmSp0jlIKQWWWabG:-Mfn4_Oz0XiyLzkzwUe_:bp5wrtz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a52ca2a075e553f832ac5c2815b3fad337ad1061/src/main/k8s/base.cue#L111)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Ok, I guess in that case we would need to change the mount for KiND to not use the secret but either add the files to the container or mount them otherwise, right?
</blockquote></details>

Likely, but I will figure it out later, after the test harness is done.

**Review by oliver-amzn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @zachcwc)

___
*[src/main/k8s/base.cue, line 111 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfjSmSp0jlIKQWWWabG:-Mfn59_bBuAj0BNM-Wht:b44tpx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a52ca2a075e553f832ac5c2815b3fad337ad1061/src/main/k8s/base.cue#L111)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Likely, but I will figure it out later, after the test harness is done.
</blockquote></details>

👍

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 39 files at r4, 7 of 14 files at r6, 7 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/ComputationControlServer.kt, line 44 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfnG7e886X7LG8_Zvzs:-MfnG7e886X7LG8_Zvzt:bl1el5d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63829f81e10d17b331b7e9caef562471ff9d8461/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/ComputationControlServer.kt#L44)):*
> ```Kotlin
> 
>     val clientCerts =
>       SigningCerts.fromPemFiles(
> ```

Optional future improvement: Could add a `toSigningCerts` extension method on TlsFlags.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/ComputationControlServer.kt, line 44 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159#-MfnG7e886X7LG8_Zvzs:-MfnI_e87YcYx_jDCRvE:b3fvlwu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63829f81e10d17b331b7e9caef562471ff9d8461/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/ComputationControlServer.kt#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Optional future improvement: Could add a `toSigningCerts` extension method on TlsFlags.
</blockquote></details>

yep, would add one in the common-jvm repo.

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 26 of 39 files at r4, 7 of 14 files at r6, 7 of 7 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/159)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Pull request merged**
