### PR TITLE
Move API and TLS flags to parent CreateResource command.

### PR DESCRIPTION
**Pull request by SanjayVas**
This makes it clearer that these flags are common rather than specific to a given subcommand.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459)

### CODE REVIEW

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459#-MxB9FKgBFGKoFulLNyl:-MxB9FKgBFGKoFulLNym:b91mqif) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e75dcb619aef7bae178cb46ae117e96c006cb47/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md#L5)):*
> ```Markdown
> Command-line tools for Kingdom operators.
> 
> ## `CreateResource`
> ```

LG. What do you think of giving an example usage of resource creation in this readme?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459#-MxBI7KyAh26qRdZP65c:-MxBI7KyAh26qRdZP65d:b6o9b1e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d428b56d90c2c44de88eba6a8556f4d5a2206cf/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L294)):*
> ```Kotlin
>  *
>  * ```
>  * $ bazel build //src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools:create_resource
> ```

why is this going away?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459#-MxB9FKgBFGKoFulLNyl:-MxBIB3d0n9MBm7BOSpf:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e75dcb619aef7bae178cb46ae117e96c006cb47/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md#L5)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

LG. What do you think of giving an example usage of resource creation in this readme?
</blockquote></details>

+1

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459#-MxBI7KyAh26qRdZP65c:-MxBK-YLAUffQ6m7KVZW:b-a1fr3h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d428b56d90c2c44de88eba6a8556f4d5a2206cf/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L294)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why is this going away?
</blockquote></details>

Unnecessary duplication that would need to be manually kept in sync.

The Bazel target is in the `BUILD.bazel` file. The usage info is gotten by using the `help` command.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459#-MxB9FKgBFGKoFulLNyl:-MxBJldO176gFOr1TrXx:bijaki7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e75dcb619aef7bae178cb46ae117e96c006cb47/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md#L5)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done, though it's made me realize we should probably update the tool to create the `EncryptionPublicKey` message and signature for you.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459#-MxB9FKgBFGKoFulLNyl:-MxBLrXH4gBjVRHfxbXX:b-lg5cz2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e75dcb619aef7bae178cb46ae117e96c006cb47/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Done, though it's made me realize we should probably update the tool to create the `EncryptionPublicKey` message and signature for you.
</blockquote></details>

Sorry, I mean we should probably have a separate tool for that, as obviously the Kingdom operator won't have access to the signing private key.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @yunyeng from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
