### PR TITLE
Internal reporting measurements service

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)* status: 6 of 18 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateMeasurement.kt` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N4htJDQAjamja6rg7hr:-N4hlAsu4hT8tzgonreC:b-v5ngkd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71644a6acf4e77abe681661651f3dc1e639a18fc/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateMeasurement.kt#L34)):*
> ```Kotlin
>         bind("$1", request.measurementConsumerReferenceId)
>         bind("$2", request.measurementReferenceId)
>         bind("$3", Measurement.State.PENDING_VALUE)
> ```

I've been trying to decide whether we should map to a Postgres enum using `EnumCodec`
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N4hltvX9GpQBm9tup56:-N4hltvX9GpQBm9tup57:bk17uln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71644a6acf4e77abe681661651f3dc1e639a18fc/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt#L35)):*
> ```Kotlin
>       ) {
>         bind("$1", Measurement.State.FAILED_VALUE)
>         bind("$2", request.failure.toByteArray())
> ```

Use the `bind` overload for protobuf messages rather than converting to bytes yourself.



_Code quote:_
```Kotlin
bind("$2", request.failure.toByteArray())
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/MeasurementsServiceTest.kt` line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N4hucG593UQf_q0i39Q:-N4hucG69MuhpILeKPCP:be09ju2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71644a6acf4e77abe681661651f3dc1e639a18fc/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/MeasurementsServiceTest.kt#L53)):*
> ```Kotlin
>     service = newService(idGenerator)
>   }
> ```

There are no tests that confirm that the correct value was actually persisted, just that the methods return an expected value.  To do that, you'll need to either
1. Implement a service method that retrieves a measurement (e.g. getMeasurement)
2. Add an abstract method to this test class that does the same, such that subclasses must implement it.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)* status: 2 of 19 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N4hltvX9GpQBm9tup56:-N4iHeYyAZh4kI8RIwzS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71644a6acf4e77abe681661651f3dc1e639a18fc/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the `bind` overload for protobuf messages rather than converting to bytes yourself.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/MeasurementsServiceTest.kt` line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N4hucG593UQf_q0i39Q:-N4iHfCcDH5LtUQUtGq_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71644a6acf4e77abe681661651f3dc1e639a18fc/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/MeasurementsServiceTest.kt#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There are no tests that confirm that the correct value was actually persisted, just that the methods return an expected value.  To do that, you'll need to either
1. Implement a service method that retrieves a measurement (e.g. getMeasurement)
2. Add an abstract method to this test class that does the same, such that subclasses must implement it.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 9 of 18 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateMeasurement.kt` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N4j2Yy39LWkoFqADTxN:-N4j2Yy39LWkoFqADTxO:b-z027qc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e66e559e12dc83dc1fa9c047d88cdc66985cf3c0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateMeasurement.kt#L28)):*
> ```Kotlin
>  *
>  * Throws a subclass of [ReportingInternalException] on [execute].
>  * @throws [MeasurementAlreadyExistsException] Measurement already exists
> ```

nit: `@throws` here is implying that the constructor throws this exception



_Code quote:_
```Kotlin
@throws 
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/MeasurementsServiceTest.kt` line 194 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N4j3V0u3xmK_zy6Spp-:-N4j3V0u3xmK_zy6Spp0:b-xyw3nc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e66e559e12dc83dc1fa9c047d88cdc66985cf3c0/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/MeasurementsServiceTest.kt#L194)):*
> ```Kotlin
> 
>     runBlocking {
>       val exception =
> ```

nit: `runBlocking` can return a value, so this can be written as

```kotlin
    val exception = runBlocking {
      assertFailsWith<StatusRuntimeException> { service.setMeasurementFailure(request) }
    }
    assertThat(exception.status.code).isEqualTo(Status.Code.NOT_FOUND)
```



_Suggestion:_
```Kotlin
    val exception = runBlocking {
      assertFailsWith<StatusRuntimeException> { service.setMeasurementFailure(request) }
    }
    assertThat(exception.status.code).isEqualTo(Status.Code.NOT_FOUND)
```
___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N4j446d4QUlypjpY4fU:-N4j446eEnmSUP-G1M7R:b-x5a9ga) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e66e559e12dc83dc1fa9c047d88cdc66985cf3c0/src/main/proto/wfa/measurement/internal/reporting/report.proto#L97)):*
> ```protobuf
>   Details details = 8;
> 
>   // Seconds since the report was created. Output-only.
> ```

Why not return the create timestamp? Seconds since creation will be stale a second after it's retrieved, since it's relative to the time the system computed it.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)* status: 13 of 19 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N4j446d4QUlypjpY4fU:-N4n2a7tAc_SaWkyk3cR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e66e559e12dc83dc1fa9c047d88cdc66985cf3c0/src/main/proto/wfa/measurement/internal/reporting/report.proto#L97)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why not return the create timestamp? Seconds since creation will be stale a second after it's retrieved, since it's relative to the time the system computed it.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateMeasurement.kt` line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N56XMU-5-4USqzKmBsY:-N56XMU0BjSyWHoimEGg:b-7p4rni) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/764e414ee08e16a8658a526f488cea350f95e60f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateMeasurement.kt#L27)):*
> ```Kotlin
>  * Inserts a Measurement into the database.
>  *
>  * Throws a subclass of [ReportingInternalException] on [execute].
> ```

nit: maybe more clear by indicating that you're going to give a list of exceptions/conditions:

```kotlin
* Throws the following on [execute]:
*   * [MeasurementAlreadyExistsException] if the Measurement already exists
```

On `execute` itself, put `@throws ReportingInternalException on failure. See [PostgresWriter] subclass for specifics.`



_Code quote:_
```Kotlin
 * Throws a subclass of [ReportingInternalException] on [execute].
 * [MeasurementAlreadyExistsException] Measurement already exists
```

**Comment by riemanli** [comment]
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 94 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N5DdBm66T0SJFDYXcPn:-N5DdBm7E1yhpSEoQ39R:budtaov) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6f25de336529b7b955dd99a121dd8a784f777fa1/src/main/proto/wfa/measurement/internal/reporting/report.proto#L94)):*
> ```protobuf
> 
>     // Set only when `state` is `SUCCEEDED`. Output-only.
>     Result result = 2;
> ```

Should be repeated.

**Review by riemanli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)* status: 16 of 21 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 37 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N5E-BmW8JMBvONkO3KY:-N5E-BmW8JMBvONkO3KZ:bxqmlw5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6f25de336529b7b955dd99a121dd8a784f777fa1/src/main/proto/wfa/measurement/internal/reporting/report.proto#L37)):*
> ```protobuf
>     PeriodicTimeInterval periodic_time_interval = 4;
>   }
> ```

Missing `report_idempotency_key`.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)* status: 14 of 21 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 37 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N5E-BmW8JMBvONkO3KY:-N5GdDpG3t0P9KoNQul8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6f25de336529b7b955dd99a121dd8a784f777fa1/src/main/proto/wfa/measurement/internal/reporting/report.proto#L37)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Missing `report_idempotency_key`.
</blockquote></details>

Done.

**Review by riemanli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)* status: 14 of 21 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 86 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N5HkICo25Gs8zVqEH5f:-N5HkICo25Gs8zVqEH5g:b-403wae) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/263495f60c0d048ceac75c9771dbcbae882a7d00/src/main/proto/wfa/measurement/internal/reporting/report.proto#L86)):*
> ```protobuf
>           string column_header = 1;
>           // Required to be in the same order as `row_headers`.
>           repeated int32 set_operations = 2;
> ```

According to the [design of internal measurement](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/reporting/measurement.proto#L68), this should be `Double`.

**Comment by riemanli** [comment]
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 86 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N5HkICo25Gs8zVqEH5f:-N5HqsXh0qCxpfsv98IC:bwtpqmx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/263495f60c0d048ceac75c9771dbcbae882a7d00/src/main/proto/wfa/measurement/internal/reporting/report.proto#L86)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

According to the [design of internal measurement](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/reporting/measurement.proto#L68), this should be `Double`.
</blockquote></details>

Or do we just want to show the integer part of  the percentage in the frequency distribution? 
+@sanjayvas

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)* status: 14 of 21 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 86 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N5HkICo25Gs8zVqEH5f:-N5IDh042NRvAfcjkrM0:b-hs897e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/263495f60c0d048ceac75c9771dbcbae882a7d00/src/main/proto/wfa/measurement/internal/reporting/report.proto#L86)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Or do we just want to show the integer part of  the percentage in the frequency distribution? 
+@sanjayvas 
</blockquote></details>

This is why I suggested possibly needing to handle multiple value types :P.

Probably should give highest accuracy we have available.

**Comment by riemanli** [comment]
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 83 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N5IMpsW7SSdpB7eIVhk:-N5IMpsW7SSdpB7eIVhl:b-8jv5xv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/263495f60c0d048ceac75c9771dbcbae882a7d00/src/main/proto/wfa/measurement/internal/reporting/report.proto#L83)):*
> ```protobuf
>         }
>         repeated Row rows = 1;
>         message Column {
> ```

Can we move the `Column` message one level up so that both `ScalarTable` and `HistogramTable` can share one `Column` message?

**Comment by riemanli** [comment]
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 73 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N5IPeyv5LyoluyEzMj3:-N5IPeyv5LyoluyEzMj4:bh71f58) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/263495f60c0d048ceac75c9771dbcbae882a7d00/src/main/proto/wfa/measurement/internal/reporting/report.proto#L73)):*
> ```protobuf
>           repeated int32 set_operations = 2;
>         }
>         repeated Column column = 2;
> ```

Should it be `columns`?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)* status: 14 of 21 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 73 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N5IPeyv5LyoluyEzMj3:-N5LKPPm0mxqvmPZQ5_G:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/263495f60c0d048ceac75c9771dbcbae882a7d00/src/main/proto/wfa/measurement/internal/reporting/report.proto#L73)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Should it be `columns`?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 83 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N5IMpsW7SSdpB7eIVhk:-N5LKvdA0CO2zxEtoLia:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/263495f60c0d048ceac75c9771dbcbae882a7d00/src/main/proto/wfa/measurement/internal/reporting/report.proto#L83)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Can we move the `Column` message one level up so that both `ScalarTable` and `HistogramTable` can share one `Column` message?
</blockquote></details>

Done.

**Review by riemanli — APPROVED** [review]
> Reviewed 8 of 18 files at r1, 4 of 8 files at r2, 2 of 6 files at r3, 5 of 5 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @riemanli, @SanjayVas, and @stevenwarejones)

**Comment by riemanli** [comment]
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 86 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602#-N5HkICo25Gs8zVqEH5f:-N5N6Mq31CXXCipDOC0-:b-vkwuew) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/263495f60c0d048ceac75c9771dbcbae882a7d00/src/main/proto/wfa/measurement/internal/reporting/report.proto#L86)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is why I suggested possibly needing to handle multiple value types :P.

Probably should give highest accuracy we have available.
</blockquote></details>

Just talked to @matthewclegg. We think it's better to output the frequency histogram with counts (i.e. percentage * reach) for each frequency. In this way, users can get more information (Reach) and are still able to compute the percentage if they want.

Note that even though what the frequency histogram contains is "count", that doesn't mean it needs to be integer as it is an estimate.

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 8 of 18 files at r1, 4 of 8 files at r2, 2 of 6 files at r3, 5 of 5 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/602)* status: all files reviewed, 1 unresolved discussion (waiting on @matthewclegg, @SanjayVas, and @stevenwarejones)

**Pull request merged**
