### PR TITLE
Deploy Duchy

### PR DESCRIPTION
**Pull request by wfa-siyengar**
- [x] Created separate templates for init, plan and apply.
- [x] Now works with Workload Identity.
- [x] Has the Apply commented.
- [x] Created duchy creation workflow.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, @TNATALI, @wfa-hkawalkar, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/create_duchy.yml` line 17 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897#-NQywfjj3Lup09NgsxwH:-NQywfjj3Lup09NgsxwI:b6fsglv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a4ba9898419caee2458081b4043b0849061aa3d4/.github/workflows/create_duchy.yml#L17)):*
> ```YAML
> name: 'Create Duchy Plan'
> 
> on:
> ```

Setup for workflow_run and workflow_dispatch.
___
*[`.github/workflows/create_duchy.yml` line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897#-NQywnah3jNBoZqAs81I:-NQywnah3jNBoZqAs81J:bfum52n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a4ba9898419caee2458081b4043b0849061aa3d4/.github/workflows/create_duchy.yml#L28)):*
> ```YAML
> env:
>   ROOT_PATH: '${{ github.workspace }}/src/main/terraform/duchy/gcloud'
>   ENV: '${{ vars.ENV }}'
> ```

Instead of vars.ENV and use vars.QA_ENV

**Review by bdomen-ggl — COMMENTED** [review]
This part looks good for me. Just Craig's comments and using the component variable instead of project variable is all I think.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897#-:-NQz-IjT-Hz0dyt84KUz:bc61kf9)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @TNATALI, @wfa-hkawalkar, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/template/apply/action.yml` line 35 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897#-NQz-4GN7bAJdqQd7Km4:-NQz-4GO1AAfkinCsNf2:b-uxtwvl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a4ba9898419caee2458081b4043b0849061aa3d4/.github/template/apply/action.yml#L35)):*
> ```YAML
>       run: |
>         terraform apply ${{ inputs.environment }}_tfplan
>         
> ```

nit: there's some extra spaces on the last line
___
*[`.github/workflows/create_duchy.yml` line 56 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897#-NQz-9_tEjZEWHo-NTWF:-NQz-9_tEjZEWHo-NTWG:b-ottjpq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a4ba9898419caee2458081b4043b0849061aa3d4/.github/workflows/create_duchy.yml#L56)):*
> ```YAML
>           project: ${{ env.PROJECT }}
> 
>  #     - name: Terraform Apply
> ```

We'll enable this at the end sometime right?

**Review by wfa-siyengar — COMMENTED** [review]
Have made changes accordingly.

> Reviewed 5 of 10 files at r2, 1 of 4 files at r3, 4 of 5 files at r4, 2 of 3 files at r5, all commit messages.
> Dismissed @bdomen-ggl and @kungfucraig from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897#-:-NQzDais7Qk2DEjB8WAu:bhmbp4k)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, @TNATALI, @wfa-hkawalkar, and @wfa-mdharmalingam)

___
*[`.github/template/apply/action.yml` line 35 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897#-NQz-4GN7bAJdqQd7Km4:-NQzDx4A8PVOs_7XvDae:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a4ba9898419caee2458081b4043b0849061aa3d4/.github/template/apply/action.yml#L35)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

nit: there's some extra spaces on the last line
</blockquote></details>

done.
___
*[`.github/workflows/create_duchy.yml` line 17 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897#-NQywfjj3Lup09NgsxwH:-NQzEOgZE-7_bHxrOWYs:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a4ba9898419caee2458081b4043b0849061aa3d4/.github/workflows/create_duchy.yml#L17)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Setup for workflow_run and workflow_dispatch.
</blockquote></details>

done
___
*[`.github/workflows/create_duchy.yml` line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897#-NQywnah3jNBoZqAs81I:-NQzER_2-tYMI4du6GYY:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a4ba9898419caee2458081b4043b0849061aa3d4/.github/workflows/create_duchy.yml#L28)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Instead of vars.ENV and use vars.QA_ENV
</blockquote></details>

done
___
*[`.github/workflows/create_duchy.yml` line 56 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897#-NQz-9_tEjZEWHo-NTWF:-NQzE3hK5w_tBPtH1225:b-wzx8v8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a4ba9898419caee2458081b4043b0849061aa3d4/.github/workflows/create_duchy.yml#L56)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

We'll enable this at the end sometime right?
</blockquote></details>

thats right. Will enable and then push, once approved.

**Review by wfa-siyengar — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897#-:-NQzFp4VExT8KkaKgqgK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, @TNATALI, @wfa-hkawalkar, and @wfa-mdharmalingam)

**Review by bdomen-ggl — COMMENTED** [review]
Looks good

> Reviewed 3 of 10 files at r2, 1 of 4 files at r3, 3 of 5 files at r4, 1 of 3 files at r5, 3 of 5 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/897#-:-NQzzB_b7aTwyY72GMfm:bsrfkwe)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
