### PR TITLE
Implement exchange deletion for internal spanner implementation

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000)* status: all files reviewed, 3 unresolved discussions (waiting on @jcorilla)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt` line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000#-NVCm-pR5twgfIQEogHO:-NVCm-pR5twgfIQEogHP:b4nnm68) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c08cceb6b1edd274364cd78246992195ab976b8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt#L104)):*
> ```Kotlin
> 
>       val row: Struct =
>         readContext.executeQuery(statement).singleOrNull()
> ```

This should just return the result of singleOrNull and let the caller decide to throw the exception.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt` line 313 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000#-NVCi6PHEzL_YSBlcqdK:-NVCi6PHEzL_YSBlcqdL:bfos4t6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c08cceb6b1edd274364cd78246992195ab976b8/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt#L313)):*
> ```Kotlin
>   @Test
>   fun `batchDeleteExchanges deletes all requested Exchanges`(): Unit = runBlocking {
>     val exchangeRequest1 = CreateExchangeRequest.newBuilder().apply { exchange = EXCHANGE }.build()
> ```

Use dsl builder
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt` line 350 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000#-NVCiX5u8L3rPT88xlki:-NVCiX5u8L3rPT88xlkj:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c08cceb6b1edd274364cd78246992195ab976b8/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt#L350)):*
> ```Kotlin
>     runBlocking {
>       val exchangeRequest1 =
>         CreateExchangeRequest.newBuilder().apply { exchange = EXCHANGE }.build()
> ```

Ditto

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt` line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000#-NVCm-pR5twgfIQEogHO:-NVFukDP3rrYMmFqWfP5:b-edu56r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c08cceb6b1edd274364cd78246992195ab976b8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt#L104)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This should just return the result of singleOrNull and let the caller decide to throw the exception.
</blockquote></details>

Since the key creation occurs inside this function, it ends up needing its own null checks if the error isn't thrown here. I can move the key creation out of this function and into the caller (this function would then return the internal recurringExchangeId instead of a key) to return the singleOrNull  if you recommend that. Was basing the key generation by IDs off of 

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abdd7d3956c353e61aaa2664dfd04e82cfe31665/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L142. A function directly returning the key was recommended there.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt` line 313 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000#-NVCi6PHEzL_YSBlcqdK:-NVFnr8F4FD2b4r6DgWL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c08cceb6b1edd274364cd78246992195ab976b8/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt#L313)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Use dsl builder
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt` line 350 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000#-NVCiX5u8L3rPT88xlki:-NVFnqrY9XJAabGENNW4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c08cceb6b1edd274364cd78246992195ab976b8/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt#L350)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt` line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000#-NVCm-pR5twgfIQEogHO:-NVWF-UVBVtFDkp_VmKv:b-vcqmf5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c08cceb6b1edd274364cd78246992195ab976b8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt#L104)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I guess we haven't really been consistent on this. I think returning the result of singleOrNull is used more, but I haven't counted.
</blockquote></details>

Yeah, looks like we haven't been consistent. Returning null when not found is better so you don't pay the exception overhead for something that can be communicated by the return value.

I'm not sure what bearing key creation has on this. You would just return null instead of throwing the exception.

```kotlin
      val row: Struct =
        readContext.executeQuery(statement).singleOrNull() ?: return null
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt` line 380 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000#-NVWGDyo0IDAoTuQ_S3H:-NVWGDyo0IDAoTuQ_S3I:bb7phvt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcc1c28fb8dd5743215c10fd43dfdcad53f50345/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt#L380)):*
> ```Kotlin
> 
>   @Test
>   fun `batchDeleteExchanges deletes throws NOT_FOUND when Exchange is missing`(): Unit =
> ```

typo



_Suggestion:_
```Kotlin
throws
```

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt` line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000#-NVCm-pR5twgfIQEogHO:-NV_rsgeCEpHQhIlUS4y:bt9ukkl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c08cceb6b1edd274364cd78246992195ab976b8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yeah, looks like we haven't been consistent. Returning null when not found is better so you don't pay the exception overhead for something that can be communicated by the return value.

I'm not sure what bearing key creation has on this. You would just return null instead of throwing the exception.

```kotlin
      val row: Struct =
        readContext.executeQuery(statement).singleOrNull() ?: return null
```
</blockquote></details>

Got it, I don't remember what I was thinking with the key - makes sense to return null immediately. Changing both readers for consistency.

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla, @Marco-Premier, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/error_code.proto` line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000#-NW3EVcq8Z9t_9OzZPlQ:-NW3EVcq8Z9t_9OzZPlR:bvaqhrf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd7172ec1526409bfd0e7708839a3734797d202d/src/main/proto/wfa/measurement/internal/kingdom/error_code.proto#L83)):*
> ```protobuf
>   /** Measurement etag requested does not match actual Measurement etag. */
>   MEASUREMENT_ETAG_MISMATCH = 28;
>   /** ModelSuite resource queried could not be found. */
> ```

This looks like it is from a different PR or a newer commit.

**Review by tristanvuong2021 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt` line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000#-NVCm-pR5twgfIQEogHO:-NWE-8V-7IwhGP-Zxdkp:bpdut5t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c08cceb6b1edd274364cd78246992195ab976b8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt#L104)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

Got it, I don't remember what I was thinking with the key - makes sense to return null immediately. Changing both readers for consistency. 
</blockquote></details>

@SanjayVas PTAL, updated with recommended changes
___
*[`src/main/proto/wfa/measurement/internal/kingdom/error_code.proto` line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000#-NW3EVcq8Z9t_9OzZPlQ:-NWDzhvuDwZ5jafJ4fU8:bgijpzx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd7172ec1526409bfd0e7708839a3734797d202d/src/main/proto/wfa/measurement/internal/kingdom/error_code.proto#L83)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This looks like it is from a different PR or a newer commit.
</blockquote></details>

This was due to a conflict when rebasing on more recent changes.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 5 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by jcorilla — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 5 of 7 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1000)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
