### PR TITLE
Update Kotlin to 1.4

### PR DESCRIPTION
**Pull request by tristanvuong2021**
Updated Kotlin version, kotlinx.coroutines version, and rule_kotlin version

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Updated Kotlin to 1.4

nit: Use an imperative sentence for a PR description, e.g. "Update Kotlin" rather than "Updated Kotlin".

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-:-McLfisT4o4IcFybUxwP:bdvrnwy)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McLh3z43wVdi892wTU4:-McLh3z43wVdi892wTU5:b-33n6kw) (no related file):*
Make sure you get approval from at least one reviewer external to Google prior to merging.

---

**Comment by tristanvuong2021** [comment]
I changed both the PR description and the commit message from Updated to Update. Didn't see that squash and merge as the default so I force pushed it.

**Comment by tristanvuong2021** [comment]
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McLh3z43wVdi892wTU4:-McLpfLmCDCHxbfmRiH9:bb3jnxs) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Make sure you get approval from at least one reviewer external to Google prior to merging.
</blockquote></details>

Which reviewers are external to Google?

---

**Review by oliver-amzn — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: all files reviewed, 3 unresolved discussions (waiting on @corbantek, @SanjayVas, @tristanvuong2021, and @zachcwc)

___
*[WORKSPACE, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McQ24a-4rqGmgF2fvXJ:-McQ24a-4rqGmgF2fvXK:b-dre8ho) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/015a8d068e03173379e5a06197fd252773a8ae9b/WORKSPACE#L66)):*
> ```
> "v1.5.0-alpha-3"
> ```

Is this the new Kotlin version? Or is it 1.4.20 from a few lines below? 
___
*[src/main/kotlin/org/wfanet/measurement/duchy/DuchyPublicKeys.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McQ1HuMC1OBTJXeN7jR:-McPqRtNAwd7SPqlK66K:b9cydbo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/015a8d068e03173379e5a06197fd252773a8ae9b/src/main/kotlin/org/wfanet/measurement/duchy/DuchyPublicKeys.kt#L45)):*
> ```
> maxBy
> ```

Is this change intended?

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/duchy/DuchyPublicKeys.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McQ1HuMC1OBTJXeN7jR:-McQ3CHF0B_g8wEdu8m4:b40ohqd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/015a8d068e03173379e5a06197fd252773a8ae9b/src/main/kotlin/org/wfanet/measurement/duchy/DuchyPublicKeys.kt#L45)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> ```
> maxBy
> ```

Is this change intended? 
</blockquote></details>

maxBy was deprecated in 1.4 and maxByOrNull is the replacement.

**Comment by tristanvuong2021** [comment]
___
*[WORKSPACE, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McQ24a-4rqGmgF2fvXJ:-McQ3UFfA1Y7EhNX8okf:bpjraxf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/015a8d068e03173379e5a06197fd252773a8ae9b/WORKSPACE#L66)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> ```
> "v1.5.0-alpha-3"
> ```

Is this the new Kotlin version? Or is it 1.4.20 from a few lines below? 
</blockquote></details>

1.4.20 is the new Kotlin version. This is the corresponding rules_kotlin version.

**Review by oliver-amzn — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @SanjayVas, @tristanvuong2021, and @zachcwc)

___
*[WORKSPACE, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McQ24a-4rqGmgF2fvXJ:-McQ7yTSCWV-bLytquyo:b61s5v7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/015a8d068e03173379e5a06197fd252773a8ae9b/WORKSPACE#L66)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

1.4.20 is the new Kotlin version. This is the corresponding rules_kotlin version.
</blockquote></details>

Why 1.4.20 and not the latest 1.4 (i see 1.4.32 on their page?)
___
*[src/main/kotlin/org/wfanet/measurement/duchy/DuchyPublicKeys.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McQ1HuMC1OBTJXeN7jR:-McQ8CIQ5OFydbWkF8f3:b-hd5lof) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/015a8d068e03173379e5a06197fd252773a8ae9b/src/main/kotlin/org/wfanet/measurement/duchy/DuchyPublicKeys.kt#L45)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

maxBy was deprecated in 1.4 and maxByOrNull is the replacement.
</blockquote></details>

Ah ok, thx!

**Review by corbantek — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @tristanvuong2021, and @zachcwc)

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[WORKSPACE, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McQ24a-4rqGmgF2fvXJ:-McQ9Kmb4G6A1lUN8VTu:bv06nmt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/015a8d068e03173379e5a06197fd252773a8ae9b/WORKSPACE#L66)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Why 1.4.20 and not the latest 1.4 (i see 1.4.32 on their page?)
</blockquote></details>

This is the compiler version that this rules_kotlin release is known to be compatible with. That said, we *could* try newer versions at the same minor version and they *should* theoretically work and include bug fixes.

See release notes: https://github.com/bazelbuild/rules_kotlin/releases/tag/v1.5.0-alpha-3

**Review by corbantek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @zachcwc)

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @tristanvuong2021, and @zachcwc)

___
*[WORKSPACE, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McQ24a-4rqGmgF2fvXJ:-McUz06G-W_URFHr24DA:b-9ibg0p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/015a8d068e03173379e5a06197fd252773a8ae9b/WORKSPACE#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is the compiler version that this rules_kotlin release is known to be compatible with. That said, we *could* try newer versions at the same minor version and they *should* theoretically work and include bug fixes.

See release notes: https://github.com/bazelbuild/rules_kotlin/releases/tag/v1.5.0-alpha-3
</blockquote></details>

Might as well just go with the latest 1.4.x version to get all those bug fixes? @tristanvuong2021 - if you prefer 1.4.20 then that's fine

**Comment by tristanvuong2021** [comment]
___
*[WORKSPACE, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McQ24a-4rqGmgF2fvXJ:-McQ9SVl0iOFvFKKLuB8:baoxo5j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/015a8d068e03173379e5a06197fd252773a8ae9b/WORKSPACE#L66)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Might as well just go with the latest 1.4.x version to get all those bug fixes? @tristanvuong2021 - if you prefer 1.4.20 then that's fine 
</blockquote></details>

I updated it to 1.4.32.

**Review by corbantek — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @zachcwc)

**Review by oliver-amzn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @tristanvuong2021, and @zachcwc)

___
*[WORKSPACE, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McQ24a-4rqGmgF2fvXJ:-Mckrqac15izRo2eFt-R:b-ucfknh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/015a8d068e03173379e5a06197fd252773a8ae9b/WORKSPACE#L66)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I updated it to 1.4.32.
</blockquote></details>

Thanks!

**Review by corbantek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @tristanvuong2021, and @zachcwc)

**Comment by tristanvuong2021** [comment]
I changed the rules_kotlin version to a slightly older version because the newest version has an issue with kotlinx_coroutines: https://github.com/bazelbuild/rules_kotlin/issues/500.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 28 files at r4, 1 of 23 files at r5, 4 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: 6 of 57 files reviewed, 2 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, @tristanvuong2021, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McoiK5r-j1T26aR-rYr:-McoiK5r-j1T26aR-rYs:buf818w) (no related file):*
Something went wrong with updating this branch on top of the latest main, where it thinks some of the commits on the base branch are part of this PR and therefore is showing unrelated diffs.

---

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 7 files at r6, 50 of 50 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021 and @zachcwc)

**Comment by tristanvuong2021** [comment]
___
*[WORKSPACE, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109#-McQ24a-4rqGmgF2fvXJ:-McocgaJDIa2rAqGEdns:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/015a8d068e03173379e5a06197fd252773a8ae9b/WORKSPACE#L66)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Done.

**Review by corbantek — APPROVED** [review]
> Reviewed 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @zachcwc)

**Comment by tristanvuong2021** [comment]
:lgtm:

**Review by tristanvuong2021 — COMMENTED** [review]
> Dismissed @oliver-amzn from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Pull request merged**
