### PR TITLE
Marcopremier fix confirmcomputationparticipant

### PR DESCRIPTION
**Pull request by Marco-Premier**
PR to solve issue #1269

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272)

**Review by Marco-Premier — COMMENTED** [review]
Hey @uakyol  just added the test :)

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272#-:-NfyryTm24dZgr7uTOPj:b-nmmbx4)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by uakyol — CHANGES_REQUESTED** [review]
thank you :), added some minor comments.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272#-:-Ng-PVgA6oDA45lug0a2:b-hvsi4e)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt` line 704 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272#-Ng-P2wZ0N_1Y-yWLqZI:-Ng-P2wZ0N_1Y-yWLqZJ:bxythff) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52692cfad2ec586b07d0e944e3518018e19759c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L704)):*
> ```Kotlin
> 
>   @Test
>   fun `confirmComputationParticipant succeeds with two duchies`() = runBlocking {
> ```

What do you think about changing the name to `confirmComputationParticipant succeeds with a subset of registered duchies` since 2 is arbitrary, we are trying to test if this would work if not all duchies are included.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt` line 705 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272#-Ng-OliG3e3_C5UmHezB:-Ng-OliG3e3_C5UmHezC:b-c1zvx1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52692cfad2ec586b07d0e944e3518018e19759c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L705)):*
> ```Kotlin
>   @Test
>   fun `confirmComputationParticipant succeeds with two duchies`() = runBlocking {
>     val duchies = DUCHIES.take(2)
> ```

consider using droplast() (https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/drop-last.html).
This way if someone changes the DUCHIES in the Population class to 2 duchies this test will still be correct.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt` line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272#-Ng-NRytB6YGuUpM_bW_:-Ng-NRytB6YGuUpM_bWa:bpbq4fl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52692cfad2ec586b07d0e944e3518018e19759c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L90)):*
> ```Kotlin
>     val WORKER1_DUCHY = DuchyIds.Entry(2, "worker1", VALID_ACTIVE_START_TIME..VALID_ACTIVE_END_TIME)
>     val WORKER2_DUCHY = DuchyIds.Entry(3, "worker2", VALID_ACTIVE_START_TIME..VALID_ACTIVE_END_TIME)
>     val DUCHIES = listOf(AGGREGATOR_DUCHY, WORKER1_DUCHY, WORKER2_DUCHY)
> ```

Consider adding an inactive duchy? 
There are lots of other tests using this object and after those tests are refactored to account for this change. The functionality of removing a duchy should work. As things stand, we caught this bug but there might be others. This change would uncover more if any.

For example if we had an inactive duchy here, the above tests would have failed.

wdyt? If you think this is a good idea too, feel free to tackle this in another PR.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt` line 704 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272#-Ng-P2wZ0N_1Y-yWLqZI:-Ng2yuuTE6mm1pNsnMd2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52692cfad2ec586b07d0e944e3518018e19759c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L704)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

What do you think about changing the name to `confirmComputationParticipant succeeds with a subset of registered duchies` since 2 is arbitrary, we are trying to test if this would work if not all duchies are included.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt` line 705 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272#-Ng-OliG3e3_C5UmHezB:-Ng2zLk8A0y6jGb9P0b2:b9wl7j2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52692cfad2ec586b07d0e944e3518018e19759c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L705)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

consider using droplast() (https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/drop-last.html).
This way if someone changes the DUCHIES in the Population class to 2 duchies this test will still be correct.
</blockquote></details>

yeah I agree even though some constraint will remain. e.g. if someone change the order of DUCHIES ad put the aggregator as last element in the list, test would fail.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt` line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272#-Ng-NRytB6YGuUpM_bW_:-Ng3-lZQ6dh7UsFScOw9:b-3x6qx6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52692cfad2ec586b07d0e944e3518018e19759c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L90)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Consider adding an inactive duchy? 
There are lots of other tests using this object and after those tests are refactored to account for this change. The functionality of removing a duchy should work. As things stand, we caught this bug but there might be others. This change would uncover more if any.

For example if we had an inactive duchy here, the above tests would have failed.

wdyt? If you think this is a good idea too, feel free to tackle this in another PR.
</blockquote></details>

I see your point. I think it would be even more helpful to add a duchy which is active but is not a "required duchy" in any data provider.
Inactive duchy are automatically "dropped" when a measurement is created instead active ones my be added to the list of participant if the minimum number of required duchies is not met.

I'll follow up in a different PR :)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt` line 145 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272#-Ng4zm8z3Ufjb2pgylwF:-Ng4zm8z3Ufjb2pgylwG:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffac5b6c2f3a220e217df587561817210c7a8005/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt#L145)):*
> ```Kotlin
>   }
> 
>   private suspend fun TransactionScope.getComputationParticipants(
> ```

nit



_Suggestion:_
```Kotlin
getComputationParticipantDuchyIds
```

**Review by uakyol — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt` line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272#-Ng-NRytB6YGuUpM_bW_:-Ng5nvOLABoBvx1N_NPC:bl4mvpg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52692cfad2ec586b07d0e944e3518018e19759c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L90)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I see your point. I think it would be even more helpful to add a duchy which is active but is not a "required duchy" in any data provider.
Inactive duchy are automatically "dropped" when a measurement is created instead active ones my be added to the list of participant if the minimum number of required duchies is not met.

I'll follow up in a different PR :)
</blockquote></details>

awesome thanks :)

**Comment by SanjayVas** [comment]
Waiting on this for the 0.4.1 patch release.

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
