### PR TITLE
Update common-jvm to v0.10.0.

### PR DESCRIPTION
**Pull request by SanjayVas**
This swaps Spanner code to use the newer/preferred overloads.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/262)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/262)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 162 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/262#-Mj5ridW6Sp8rrpIs1bk:-Mj5ridW6Sp8rrpIs1bl:bb7hquh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eab41436ad56d167c6c11eb3f02e14b88bbef3b1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L162)):*
> ```Kotlin
>         statement(
>           sql,
>           fun Statement.Builder.() {
> ```

huh?

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 162 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/262#-Mj5ridW6Sp8rrpIs1bk:-Mj6Zog551hZjVND-hUJ:b3642z1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eab41436ad56d167c6c11eb3f02e14b88bbef3b1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L162)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

huh?
</blockquote></details>

Bad Kotlin auto-refactor.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
