### PR TITLE
Create a top level React App component and a feedback button in the Reporting UI

### PR DESCRIPTION
**Pull request by iverson52000**
Refactor out a top level React App component which will have routes and other components. Create a floating feedback button across all pages. The feedback button will direct users to a Google form to share feedback.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1363)

**Review by bdomen-ggl — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1363)* status: all files reviewed, 3 unresolved discussions (waiting on @iverson52000 and @SanjayVas)

___
*[`pnpm-lock.yaml` line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1363#-Nl_c9Oo27UAdYKetyPW:-Nl_c9Oo27UAdYKetyPX:bvns60h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5dcb2516525034b4f259deed48ca9ab3796ef05d/pnpm-lock.yaml#L0)):*
You shouldn't need to update this. You can leave it as is. There might have been some auto-updates when we ran `pnpm i` to fix the syntax highlighting.
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/app.tsx` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1363#-Nl_c_lo5cW60wpoKCak:-Nl_c_lo5cW60wpoKCal:bmwwrgx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5dcb2516525034b4f259deed48ca9ab3796ef05d/experimental/reporting-ui/src/main/react/reporting-ui/app.tsx#L27)):*
> ```XML
>         <React.Fragment>
>             <RouterProvider router={router} />
>             <div id="fixed-bottom">
> ```

I would suggest to make this it's own component under the component's folder like `reporting-ui/components/feedbackButton` and you can put the tsx and css there. Since this is a higher level view, it will make it easier to organize the layout.
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/app.tsx` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1363#-Nl_cyAd-ZBQYb0C-oty:-Nl_cyAd-ZBQYb0C-otz:b-9x3ui8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5dcb2516525034b4f259deed48ca9ab3796ef05d/experimental/reporting-ui/src/main/react/reporting-ui/app.tsx#L28)):*
> ```XML
>             <RouterProvider router={router} />
>             <div id="fixed-bottom">
>                 <a href="https://docs.google.com/document/d/1HRUCoGLr34frH18iI_o3mNAJ-I6ylsDdJF-7usT4XZg/edit?usp=sharing">
> ```

While I would normally suggest adding a click event to the button, since we're just linking to a Google Doc, this should be fine.

However, I would suggest to open in a new tab using `target="_blank"`

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1363)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl and @SanjayVas)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/app.tsx` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1363#-Nl_c_lo5cW60wpoKCak:-Nldcw-W8f4_AHfShCCd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5dcb2516525034b4f259deed48ca9ab3796ef05d/experimental/reporting-ui/src/main/react/reporting-ui/app.tsx#L27)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

I would suggest to make this it's own component under the component's folder like `reporting-ui/components/feedbackButton` and you can put the tsx and css there. Since this is a higher level view, it will make it easier to organize the layout.
</blockquote></details>

Done.
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/app.tsx` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1363#-Nl_cyAd-ZBQYb0C-oty:-Nldcx5eDAtRTSPIh7lt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5dcb2516525034b4f259deed48ca9ab3796ef05d/experimental/reporting-ui/src/main/react/reporting-ui/app.tsx#L28)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

While I would normally suggest adding a click event to the button, since we're just linking to a Google Doc, this should be fine.

However, I would suggest to open in a new tab using `target="_blank"`
</blockquote></details>

Done.
___
*[`pnpm-lock.yaml` line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1363#-Nl_c9Oo27UAdYKetyPW:-Nldd-1VBmjSeAftw9Ku:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5dcb2516525034b4f259deed48ca9ab3796ef05d/pnpm-lock.yaml#L)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

You shouldn't need to update this. You can leave it as is. There might have been some auto-updates when we ran `pnpm i` to fix the syntax highlighting.
</blockquote></details>

Done.

**Review by bdomen-ggl — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1363)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1363)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Review by iverson52000 — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1363)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Pull request merged**
