### PR TITLE
Adding List Reports view

### PR DESCRIPTION
**Pull request by bdomen-ggl**
Adding the List Reports view to the Reporting UI.
To support the MVVM pattern we chose, these pieces were added:
- view: renders the content with high level UI logic (like showing loading and error components).
- view model: the glue to hook up the view with the model.
- repository: a UI model (not the API model) that includes knowledge of API calls to make and translating the API models into UI models.
- component: any view specific components to help increase readability.

Other supporting feature:
- routing: there's only one view right now, but routing is easy to add and we'll need it anyways.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174)* status: 20 of 23 files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl and @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/general_component/BUILD.bazel` line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYj4C_A2DzrMBlg6fD:-NcYj4C_A2DzrMBlg6fE:b-8nvkvw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d144922fcbac884d9b679a475748b274b04b175/experimental/reporting-ui/src/main/react/reporting-ui/general_component/BUILD.bazel#L10)):*
> ```Starlark
> )
> 
> js_library(
> ```

If I'm guessing correctly that each .tsx file in here corresponds to some common component, I'd recommend sticking this into some package for common components with separate targets for each one. I'm also assuming that we're using the term "component" to refer to an equivalent of a simple web component rather than something that has a View.

Maybe `error` and `loader` under `/component`?
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYk_HeCR5Derv2wCMB:-NcYk_HeCR5Derv2wCMC:b9f1lw3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d144922fcbac884d9b679a475748b274b04b175/experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts#L17)):*
> ```XML
> import appConfig from '../../../client/initialize';
> 
> export const ReportListModel = () => {
> ```

Why is this defined under the /view package? Or I guess the broader question is how are you planning on organizing the Models, Views, and ViewModels?

Keep in mind that in MVVM you can have multiple Views using the same ViewModel type, and multiple ViewModels using the same Model type. It's likely that each of our ViewModel types will be used by exactly one View, but depending on how you organize things you might be committing to that always being the cas (which is okay, just wanted you to be aware and consider the decision).
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYpM5Y-sWkYgDa9RFG:-NcYpM5Y-sWkYgDa9RFH:b-3egihh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d144922fcbac884d9b679a475748b274b04b175/experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts#L20)):*
> ```XML
>   async function loadReports() {
>     const response = await appConfig.reportingApi!.listReports();
>     return response.reports;
> ```

Alright, so it looks like you're doing a repository pattern[^1] here rather than a stateful model. Maybe keep this under some model package but rename it to `ReportRepository`?

As an aside, if you were looking for other examples of what kind of logic might go in this layer, it could be things like caching or client-side filtering.

[^1]: https://developer.android.com/codelabs/basic-android-kotlin-training-repository-pattern
___
*[`experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/BUILD.bazel` line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYu-slCKQQBXgXwSF_:-NcYu-smDTjjtMykSud2:b-nkc23k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2140819d03f083c2b3f00bb3ada2623dbd76045/experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/BUILD.bazel#L4)):*
> ```Starlark
> load("@aspect_rules_jest//jest:defs.bzl", "jest_test")
> 
> js_library(
> ```

I only see a library here. Shouldn't there be a `_test` target?



_Code quote:_
```Starlark
js_library
```
___
*[`experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/report_list_model_test.ts` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYz_pkC9vVVFfwRArD:-NcYz_pkC9vVVFfwRArE:b-uq92zp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2140819d03f083c2b3f00bb3ada2623dbd76045/experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/report_list_model_test.ts#L17)):*
> ```XML
> import '@testing-library/jest-dom';	
> import '@testing-library/jest-dom/extend-expect';	
> import { ReportListModel } from '../../../../../../main/react/reporting-ui/view/report/list/report_list_model';
> ```

Maybe use absolute paths for importing from the main tree? It looks like Aspect's rules_js doesn't have any way to specify an import prefix like we have for other language rules. e.g. our C++ includes don't need to specify `src/main/cc`, including from tests.

This may be a reason to just let the tests live in the src/main tree.



_Code quote:_
```XML
'../../../../../../
```

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174)* status: 20 of 23 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/general_component/BUILD.bazel` line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYj4C_A2DzrMBlg6fD:-NcZ03rL6JQC2R783a7K:b-i3bokv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d144922fcbac884d9b679a475748b274b04b175/experimental/reporting-ui/src/main/react/reporting-ui/general_component/BUILD.bazel#L10)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If I'm guessing correctly that each .tsx file in here corresponds to some common component, I'd recommend sticking this into some package for common components with separate targets for each one. I'm also assuming that we're using the term "component" to refer to an equivalent of a simple web component rather than something that has a View.

Maybe `error` and `loader` under `/component`?
</blockquote></details>

Right that was the idea - components that aren't specific to any particular view and can be shared all over the app vs components that are specific to a view to help with modularity, encapsulation, and/or readability. Yeah I can rename that and create a package for each specific component instead of requiring them to be grouped all together.
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYk_HeCR5Derv2wCMB:-NcZ0R-NB7YPZe6wfcYw:b-hyfexd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d144922fcbac884d9b679a475748b274b04b175/experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this defined under the /view package? Or I guess the broader question is how are you planning on organizing the Models, Views, and ViewModels?

Keep in mind that in MVVM you can have multiple Views using the same ViewModel type, and multiple ViewModels using the same Model type. It's likely that each of our ViewModel types will be used by exactly one View, but depending on how you organize things you might be committing to that always being the cas (which is okay, just wanted you to be aware and consider the decision).
</blockquote></details>

Right, at least in React, the view, view model (or similar), and model are often all even in the same JS function, implying 1:1:1 (view to view model to model).
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYpM5Y-sWkYgDa9RFG:-NcZ2ClP48MOB6kkQP4M:b9mu9d5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d144922fcbac884d9b679a475748b274b04b175/experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Alright, so it looks like you're doing a repository pattern[^1] here rather than a stateful model. Maybe keep this under some model package but rename it to `ReportRepository`?

As an aside, if you were looking for other examples of what kind of logic might go in this layer, it could be things like caching or client-side filtering.

[^1]: https://developer.android.com/codelabs/basic-android-kotlin-training-repository-pattern
</blockquote></details>

It's kind of another React-ism, but is somewhat close to the repository pattern or maybe more generally a domain driven pattern. They often group a view with any related functionality that is specific to that view in the same folder. Any general code like API calls or components used across the app can live in some kind of common directory.

Similar comment to above, React tends to prefer writing logic/models specific to the view (thus they're often even written in the same function). React developers I've known like to think about it as "domains", like a Report domain that may have list and get "sub-domains." I'll look to switch that or at least follow the conventions of the repository pattern more closely.
___
*[`experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/BUILD.bazel` line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYu-slCKQQBXgXwSF_:-NcZ3AVd-Dxj-6UyFNL1:bbnr9zt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2140819d03f083c2b3f00bb3ada2623dbd76045/experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I only see a library here. Shouldn't there be a `_test` target?
</blockquote></details>

Ah, I was going to execute all the tests into the root test runner for the main js_test rule. It's usually preferred to run all the tests at once, although now that you mention it, I was thinking in a non-bazel environment. I can switch it up so each package will run its own tests as well.
___
*[`experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/report_list_model_test.ts` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYz_pkC9vVVFfwRArD:-NcZ3awK4NlQ0zL0rZuf:b3v60sq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2140819d03f083c2b3f00bb3ada2623dbd76045/experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/report_list_model_test.ts#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Maybe use absolute paths for importing from the main tree? It looks like Aspect's rules_js doesn't have any way to specify an import prefix like we have for other language rules. e.g. our C++ includes don't need to specify `src/main/cc`, including from tests.

This may be a reason to just let the tests live in the src/main tree.
</blockquote></details>

Yeah I've not found JS to be good in that case. I can move the tests to live in src/main. I'll start with the typical side-by-side with the src code. Let me know if you'd prefer something else.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174)* status: 21 of 23 files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl and @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYk_HeCR5Derv2wCMB:-NcZD5Ar4qJS9p5upTSw:b3hmiyk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d144922fcbac884d9b679a475748b274b04b175/experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts#L17)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Right, at least in React, the view, view model (or similar), and model are often all even in the same JS function, implying 1:1:1 (view to view model to model).
</blockquote></details>

I certainly don't think we want to limit Models to being used by a single View. Those at the very least should be split out and shareable, if not also the ViewModels.
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYpM5Y-sWkYgDa9RFG:-NcZCuGC6O4cn7siLQnP:ba4mwk3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d144922fcbac884d9b679a475748b274b04b175/experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts#L20)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

It's kind of another React-ism, but is somewhat close to the repository pattern or maybe more generally a domain driven pattern. They often group a view with any related functionality that is specific to that view in the same folder. Any general code like API calls or components used across the app can live in some kind of common directory.

Similar comment to above, React tends to prefer writing logic/models specific to the view (thus they're often even written in the same function). React developers I've known like to think about it as "domains", like a Report domain that may have list and get "sub-domains." I'll look to switch that or at least follow the conventions of the repository pattern more closely.
</blockquote></details>

Generally when I've seen the term "domain" used in this context it's referring to something like domain models, e.g. API resources.

I think the repository pattern isn't anything particularly complex. It's really just about how you do data access in your model layer, and is mostly characterized by having your functions return results as opposed to updating state the way that ViewModels do.
___
*[`experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/BUILD.bazel` line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYu-slCKQQBXgXwSF_:-NcZCKvA9QKAnXZJjkAf:bj7kina) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2140819d03f083c2b3f00bb3ada2623dbd76045/experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/BUILD.bazel#L4)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Ah, I was going to execute all the tests into the root test runner for the main js_test rule. It's usually preferred to run all the tests at once, although now that you mention it, I was thinking in a non-bazel environment. I can switch it up so each package will run its own tests as well.
</blockquote></details>

For a Bazel project, each individual unit test should be its own test target so it can be run individually. It's easy to run all tests for a subtree or for the entire repo using target patterns e.g. `bazel test //experimental/src/main/react/reporting-ui/view/report/...`.

**Review by bdomen-ggl — COMMENTED** [review]
@

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-:-NccEGiw9SOBjDSG1YGh:b3krf)* status: 6 of 34 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/BUILD.bazel` line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYu-slCKQQBXgXwSF_:-NccBv7f-uuJMRsMvAzc:b-71pcmp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2140819d03f083c2b3f00bb3ada2623dbd76045/experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

For a Bazel project, each individual unit test should be its own test target so it can be run individually. It's easy to run all tests for a subtree or for the entire repo using target patterns e.g. `bazel test //experimental/src/main/react/reporting-ui/view/report/...`.
</blockquote></details>

Removed the root test. Same with another thread, moved the test to sit next to the src.
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/general_component/BUILD.bazel` line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYj4C_A2DzrMBlg6fD:-NcZ8Tl_DizjolQgW-kP:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d144922fcbac884d9b679a475748b274b04b175/experimental/reporting-ui/src/main/react/reporting-ui/general_component/BUILD.bazel#L10)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Right that was the idea - components that aren't specific to any particular view and can be shared all over the app vs components that are specific to a view to help with modularity, encapsulation, and/or readability. Yeah I can rename that and create a package for each specific component instead of requiring them to be grouped all together.
</blockquote></details>

Done
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYk_HeCR5Derv2wCMB:-NcbqA1v0hoOt9_o8P5e:b-f75dai) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d144922fcbac884d9b679a475748b274b04b175/experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I certainly don't think we want to limit Models to being used by a single View. Those at the very least should be split out and shareable, if not also the ViewModels.
</blockquote></details>

OK. I put the view models and ui models in their own higher level folders so the models aren't tied to a view model and view models aren't tied to a view. We already have a `models` folder so I put the ui models there. If you'd prefer I create a `domain` folder like in the example linked below I can do that instead.
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYpM5Y-sWkYgDa9RFG:-Ncc4lUcAvvelpi9cpkS:bzvt7j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d144922fcbac884d9b679a475748b274b04b175/experimental/reporting-ui/src/main/react/reporting-ui/view/report/list/report_list_model.ts#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Generally when I've seen the term "domain" used in this context it's referring to something like domain models, e.g. API resources.

I think the repository pattern isn't anything particularly complex. It's really just about how you do data access in your model layer, and is mostly characterized by having your functions return results as opposed to updating state the way that ViewModels do.
</blockquote></details>

Updated per above comment.
___
*[`experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/report_list_model_test.ts` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-NcYz_pkC9vVVFfwRArD:-Ncc5_iX32tfgPs9f4CW:b-tinqjj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2140819d03f083c2b3f00bb3ada2623dbd76045/experimental/reporting-ui/src/test/react/reporting-ui/view/report/list/report_list_model_test.ts#L17)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Yeah I've not found JS to be good in that case. I can move the tests to live in src/main. I'll start with the typical side-by-side with the src code. Let me know if you'd prefer something else.
</blockquote></details>

OK, I moved the test and test framework. I don't think the jest config should go specifically in the reporting app, so I moved it one up under the react folder. I have an example test in model/report_list.

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174)* status: 25 of 34 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/model/report_list/BUILD.bazel` line 21 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-Ncce97rBUXjNun76tZn:-Nch8K_XCx381-Cuu5wa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ec46fb97e4c3e66e6ad77ab84407000d98d3d28/experimental/reporting-ui/src/main/react/reporting-ui/model/report_list/BUILD.bazel#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Name the tests targets after the library they are testing. This is usually also the basename of the test file.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl and @stevenwarejones)

___
*[`experimental/reporting-ui/src/test/react/jest/mocks/BUILD.bazel` line 7 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-Nd28sXC65Ng7RgULfFa:-Nd28sXC65Ng7RgULfFb:b-ktf45f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc017afd32d1d6ced02e78924b10f8de37cb5136/experimental/reporting-ui/src/test/react/jest/mocks/BUILD.bazel#L7)):*
> ```Starlark
> )
> 
> js_library(
> ```

Test infrastructure goes under a `testing` tree in `src/main`. The only thing that goes under `src/test` is tests themselves.

The exception is when the infrastructure is small (doesn't warrant tests of its own) *and* is only used by one leaf package. In that case, it may be defined in the same leaf package as the tests that use it.

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174)* status: 28 of 34 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/jest/BUILD.bazel` line 2 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-Nccdc6r6RdVDsEvwl1C:-NcwIDXh4iChDr7uogXb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ec46fb97e4c3e66e6ad77ab84407000d98d3d28/experimental/reporting-ui/src/main/react/jest/BUILD.bazel#L2)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move this under a `testing` package while you're at it and mark as testonly.
</blockquote></details>

Done.
___
*[`experimental/reporting-ui/src/test/react/jest/mocks/BUILD.bazel` line 7 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-Nd28sXC65Ng7RgULfFa:-Nd5rWFN3VA-TQE2JCr2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc017afd32d1d6ced02e78924b10f8de37cb5136/experimental/reporting-ui/src/test/react/jest/mocks/BUILD.bazel#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Test infrastructure goes under a `testing` tree in `src/main`. The only thing that goes under `src/test` is tests themselves.

The exception is when the infrastructure is small (doesn't warrant tests of its own) *and* is only used by one leaf package. In that case, it may be defined in the same leaf package as the tests that use it.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174)* status: all files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl and @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/jest/BUILD.bazel` line 2 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-Nccdc6r6RdVDsEvwl1C:-Nd7JFRiCC9_qz6relU4:b-s8y9dk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ec46fb97e4c3e66e6ad77ab84407000d98d3d28/experimental/reporting-ui/src/main/react/jest/BUILD.bazel#L2)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see `testing` in the path.
___
*[`experimental/reporting-ui/src/test/react/jest/mocks/BUILD.bazel` line 7 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-Nd28sXC65Ng7RgULfFa:-Nd7JJJy1tOD51TGoX4B:b-s8y9dk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc017afd32d1d6ced02e78924b10f8de37cb5136/experimental/reporting-ui/src/test/react/jest/mocks/BUILD.bazel#L7)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see `testing` in the path.

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174)* status: 30 of 34 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`experimental/reporting-ui/src/test/react/jest/mocks/BUILD.bazel` line 7 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-Nd28sXC65Ng7RgULfFa:-Nd7JZkL8vLhA_KMjWgA:b-z0bjs7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc017afd32d1d6ced02e78924b10f8de37cb5136/experimental/reporting-ui/src/test/react/jest/mocks/BUILD.bazel#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see `testing` in the path.
</blockquote></details>

Ah sorry, didn't realize you literally meant a `testing` folder vs a package for testing. I figured a package for "jest" was OK since Jest is only used for testing. I'll try to remember that for next time.

Also updated so the jest config/helpers are in `//experimental/reporting-ui/src/main/react/testing/jest`

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174)* status: 30 of 34 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`experimental/reporting-ui/src/main/react/jest/BUILD.bazel` line 2 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174#-Nccdc6r6RdVDsEvwl1C:-Nd7NU_SD0n2Wfh7dA05:b-byyjcw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ec46fb97e4c3e66e6ad77ab84407000d98d3d28/experimental/reporting-ui/src/main/react/jest/BUILD.bazel#L2)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see `testing` in the path.
</blockquote></details>

Sorry, same as below.

Moved to "//experimental/reporting-ui/src/main/react/testing/jest" and updated references.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1174)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
