### PR TITLE
Add more ComputationsService tests

### PR DESCRIPTION
**Pull request by YuhongWang-Amazon**
This adds api tests for the following ComputationsService RPCs:
* DeleteComputation
* PurgeComputations
* GetComputationToken
* UpdateComputationDetails
* AdvanceComputationStage

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887)* status: all files reviewed, 5 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 134 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887#-NQWPZBJ694pI86RQucH:-NQWPZBJ694pI86RQucI:bs5cwva) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/764e4d26286e9f4bc8c1786518ec50dbe33ee720/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L134)):*
> ```Kotlin
>     val doesNotExistComputationId = 1234L
> 
>     val deleteRequest = deleteComputationRequest { localComputationId = doesNotExistComputationId }
> ```

Would you mind adding a TODO here to change this behavior? Delete should actually result in a NOT_FOUND in this case.

The TODO format is documented in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887#-NQWQVv708B-mSuFvSW0:-NQWQVv708B-mSuFvSW1:by3xsvi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/764e4d26286e9f4bc8c1786518ec50dbe33ee720/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L140)):*
> ```Kotlin
>   @Test
>   fun `non-force purgeComputations returns the matched computation IDs`() = runBlocking {
>     val computation1 = service.createComputation(DEFAULT_CREATE_COMPUTATION_REQUEST)
> ```

nit: condition goes last

The general form is "X does Y [when Z]"



_Suggestion:_
```Kotlin
purgeComputations returns matched computation IDs when force is false
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 169 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887#-NQWRL82ACk3nnRhUJsm:-NQWRL82ACk3nnRhUJsn:b-hyo1sa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/764e4d26286e9f4bc8c1786518ec50dbe33ee720/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L169)):*
> ```Kotlin
> 
>   @Test
>   fun `getComputationToken returns computations of non-force purgeComputations requests`() =
> ```

nit: This can be phrased more clearly to indicate what it's actually trying to verify.

This is okay even though the method you're technically calling to verify is Get



_Suggestion:_
```Kotlin
purgeComputations does not delete Computations when force is false
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 413 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887#-NQWYQCP5PA7B-ChWzy4:-NQWYQCP5PA7B-ChWzy5:b-x1mkt6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/764e4d26286e9f4bc8c1786518ec50dbe33ee720/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L413)):*
> ```Kotlin
>           DEFAULT_REQUISITION_ENTRY.value.copy {
>             nonce = newNonce
>             nonceHash = newNonce.toByteString()
> ```

The `nonce_hash` field is documented as being immutable. It's set on Create. When a Requisition is fulfilled, the DataProvider sends the Duchy the actual `nonce` which the Duchy verifies against the `nonce_hash` that it persisted previously. It would not be incorrect for updateComputationDetails to throw an error if there's an attempt to change the value of `nonce_hash`.

All this is to say that the test shouldn't try to change this value.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 455 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887#-NQWSE2y4-GxzVhJr2Aj:-NQWSE2y4-GxzVhJr2Ak:b-2gwxh5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/764e4d26286e9f4bc8c1786518ec50dbe33ee720/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L455)):*
> ```Kotlin
>         }
> 
>       assertThat(exception.message).isEqualTo("The protocol type cannot change.")
> ```

nit: Checking for exact message strings is brittle, and we want to allow some flexibility for the actual message. Just verify enough to distinguish the exception.



_Suggestion:_
```Kotlin
contains("type")
```

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 134 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887#-NQWPZBJ694pI86RQucH:-NQ_g4-V98RZVahgMsId:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/764e4d26286e9f4bc8c1786518ec50dbe33ee720/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L134)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Would you mind adding a TODO here to change this behavior? Delete should actually result in a NOT_FOUND in this case.

The TODO format is documented in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 413 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887#-NQWYQCP5PA7B-ChWzy4:-NQ_g5kP8HcqHBaUVDSS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/764e4d26286e9f4bc8c1786518ec50dbe33ee720/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L413)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The `nonce_hash` field is documented as being immutable. It's set on Create. When a Requisition is fulfilled, the DataProvider sends the Duchy the actual `nonce` which the Duchy verifies against the `nonce_hash` that it persisted previously. It would not be incorrect for updateComputationDetails to throw an error if there's an attempt to change the value of `nonce_hash`.

All this is to say that the test shouldn't try to change this value.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887)* status: all files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 134 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887#-NQaTHXT1QxO7wvxX9Bg:-NQaTHXT1QxO7wvxX9Bh:b948bgf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2174f00a161a3f6aad3db5e10e9855cbe6dca3db/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L134)):*
> ```Kotlin
>     val doesNotExistComputationId = 1234L
> 
>     // TODO(world-federation-of-advertisers/cross-media-measurement#889): deleteComputation should
> ```

nit: formatting

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 134 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887#-NQaTHXT1QxO7wvxX9Bg:-NQaWxIl9BOQl3rkHtLR:b-kuodpf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2174f00a161a3f6aad3db5e10e9855cbe6dca3db/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L134)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: formatting
</blockquote></details>

Opps.  Fixed! 😬

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/887)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Pull request merged**
