### PR TITLE
feat: Build and test dp consistency with bazel.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1787)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 26 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1787)* status: 8 of 26 files reviewed, 2 unresolved discussions (waiting on @ple13)

___
*[`experimental/dp_consistency/src/main/python/noiseninja/BUILD.bazel` line 7 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1787#-O5VFm8X16HmyaNeW9e1:-O5VFm8X16HmyaNeW9e2:b4gx0uz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8465864e9a0a4227a82b12417f0474559a103baf/experimental/dp_consistency/src/main/python/noiseninja/BUILD.bazel#L7)):*
> ```Starlark
>     name = "noised_measurements",
>     srcs = ["noised_measurements.py"],
>     visibility = ["//visibility:public"],
> ```

nit: just set package default visibility to public if all of the targets will be public
___
*[`experimental/dp_consistency/src/main/python/noiseninja/solver.py` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1787#-O5VFvPT-VemOf9LlEwU:-O5VFvPT-VemOf9LlEwV:bqyhk9t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8465864e9a0a4227a82b12417f0474559a103baf/experimental/dp_consistency/src/main/python/noiseninja/solver.py#L21)):*
> ```Python
> from qpsolvers import solve_problem, Problem, Solution
> 
> from experimental.dp_consistency.src.main.python.noiseninja.noised_measurements import SetMeasurementsSpec
> ```

We want src/main/python and src/test/python to be module roots such that the import here would start at `noiseninja`. My understanding is that this should just work. See https://github.com/bazelbuild/bazel/issues/6903

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1787)* status: 5 of 28 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`experimental/dp_consistency/src/main/python/noiseninja/BUILD.bazel` line 7 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1787#-O5VFm8X16HmyaNeW9e1:-O5ZaMfM5JlNrrdi9pqT:bjfxngx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8465864e9a0a4227a82b12417f0474559a103baf/experimental/dp_consistency/src/main/python/noiseninja/BUILD.bazel#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: just set package default visibility to public if all of the targets will be public
</blockquote></details>

I've updated this to produce only 1 target for this package.
___
*[`experimental/dp_consistency/src/main/python/noiseninja/solver.py` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1787#-O5VFvPT-VemOf9LlEwU:-O5Zyl0E7mA-uI5cQbTN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8465864e9a0a4227a82b12417f0474559a103baf/experimental/dp_consistency/src/main/python/noiseninja/solver.py#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We want src/main/python and src/test/python to be module roots such that the import here would start at `noiseninja`. My understanding is that this should just work. See https://github.com/bazelbuild/bazel/issues/6903
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 26 files at r1, 1 of 5 files at r2, 15 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1787)* status: 21 of 28 files reviewed, 1 unresolved discussion (waiting on @ple13)

___
*[`experimental/dp_consistency/src/main/python/BUILD.bazel` line 7 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1787#-O5_kDkDDIJxD8v2k8iG:-O5_kDkDDIJxD8v2k8iH:bhiilya) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1e809783de1972db44a32b8bcb7165c54041f6b/experimental/dp_consistency/src/main/python/BUILD.bazel#L7)):*
> ```Starlark
> )
> 
> py_library(
> ```

This is incorrect. Each library target must only reference source files in the same Bazel package. These library targets must therefore be defined in their respective Bazel packages.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1787)* status: 18 of 28 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`experimental/dp_consistency/src/main/python/BUILD.bazel` line 7 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1787#-O5_kDkDDIJxD8v2k8iG:-O5arlCL18nHJ-7V2r0R:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1e809783de1972db44a32b8bcb7165c54041f6b/experimental/dp_consistency/src/main/python/BUILD.bazel#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is incorrect. Each library target must only reference source files in the same Bazel package. These library targets must therefore be defined in their respective Bazel packages.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 26 files at r1, 2 of 19 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1787)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
