### PR TITLE
Add PrincipalServerInterceptor to extract principals from X509 certs

### PR DESCRIPTION
**Pull request by efoxepstein**
https://rally1.rallydev.com/#/?detail=/task/608271743003&fdp=true

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)

### CODE REVIEW

**Comment by efoxepstein** [comment]
This is for https://rally1.rallydev.com/#/?detail=/task/608271743003&fdp=true

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261#-Mj5qmI5EtN4pdfH9BTZ:-Mj5qmI5EtN4pdfH9BT_:b-eifvhd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d2961c8fb51ef6bcaa116b2b45d6f42c2222e9d1/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L89)):*
> ```Kotlin
>     }
> 
>     call.close(Status.UNAUTHENTICATED.withDescription("No Duchy identity found"), Metadata())
> ```

Note: this is a behavior change. It looks like it fixes a potential bug but we should discuss.

**Review by SanjayVas — APPROVED** [review]
FYI I believe the Rally URL has to go into the initial comment to be picked up by [the bot](https://techdocs.broadcom.com/us/en/ca-enterprise-software/agile-development-and-management/rally-platform-ca-agile-central/rally/integrating-top/connectors/source-code-integrations/rally-bot-github-app-integration.html).

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261#-:-MjARguGCXIq4EL2W7Ag:bv73amg)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261#-MjA_jXL9Ujls-moXDlS:-MjA_jXL9Ujls-moXDlT:b-ieksck) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d481fff28991e97fe0036eb4d485e070b1bb1d98/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt#L45)):*
> ```Kotlin
> class PrincipalServerInterceptor(private val principalLookup: PrincipalLookup) : ServerInterceptor {
> 
>   interface PrincipalLookup {
> ```

So this only works in cases where principal can be identified from AKID? Meaning this wouldn't cover MCs, as multiple of them may connect from the same FE so they're instead identified by API keys. API key or user account lookups also need to hit DB rather than config file.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @oliver-amzn, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261#-MjA_jXL9Ujls-moXDlS:-MjAiXFl3P9kOijFVx1B:b5x05yq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d481fff28991e97fe0036eb4d485e070b1bb1d98/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

So this only works in cases where principal can be identified from AKID? Meaning this wouldn't cover MCs, as multiple of them may connect from the same FE so they're instead identified by API keys. API key or user account lookups also need to hit DB rather than config file.
</blockquote></details>

Is there additional data that we should pass to `PrincipalLookup` that would solve this? Like the `Metadata`?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @oliver-amzn, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261#-MjA_jXL9Ujls-moXDlS:-MjAnuhg-R65R_0bIcr2:b77aw45) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d481fff28991e97fe0036eb4d485e070b1bb1d98/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is there additional data that we should pass to `PrincipalLookup` that would solve this? Like the `Metadata`?
</blockquote></details>

X.509 is sort of a special case, since TLS does the validation for us so we're just left with a authenticated identifier (the AKID).

For other credential types, we may need to do a DB lookup to determine the Principal resource (e.g. mapping a username or OIDC ID token to an Account resource name). We then need to validate the credential (e.g. comparing API key or password to hash in DB).

Final step which is method-specific  and happens after any interceptors is authorization. This also may involve DB lookups (e.g. making sure that the Account is an owner of the MC that they're creating an API key for).

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @oliver-amzn, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261#-MjA_jXL9Ujls-moXDlS:-MjB5RRK87ihOVmaUyiu:bgga0ji) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d481fff28991e97fe0036eb4d485e070b1bb1d98/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

X.509 is sort of a special case, since TLS does the validation for us so we're just left with a authenticated identifier (the AKID).

For other credential types, we may need to do a DB lookup to determine the Principal resource (e.g. mapping a username or OIDC ID token to an Account resource name). We then need to validate the credential (e.g. comparing API key or password to hash in DB).

Final step which is method-specific  and happens after any interceptors is authorization. This also may involve DB lookups (e.g. making sure that the Account is an owner of the MC that they're creating an API key for).
</blockquote></details>

I agree with all that.

My question is: should we rename this class to mention AKIDs? Or should we expand the data passed to PrincipalLookup so it has enough data to do the right DB query?

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @wangyaopw)

**Review by SanjayVas — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261#-MjA_jXL9Ujls-moXDlS:-MjBgUS0B9S2PVVNQblg:b-ya7hm0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d481fff28991e97fe0036eb4d485e070b1bb1d98/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I agree with all that.

My question is: should we rename this class to mention AKIDs? Or should we expand the data passed to PrincipalLookup so it has enough data to do the right DB query?
</blockquote></details>

I'd leave a TODO here to  handle other types of credentials in the future :)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @oliver-amzn, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261#-Mj5qmI5EtN4pdfH9BTZ:-MjBiq4J-YP0Qa83dTPn:bkgy229) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d481fff28991e97fe0036eb4d485e070b1bb1d98/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L89)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Note: this is a behavior change. It looks like it fixes a potential bug but we should discuss.
</blockquote></details>

@sanjayvas @wangyaopw you cool with this change?

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261#-Mj5qmI5EtN4pdfH9BTZ:-MjBjvJG7a2N7_Qpduy_:b-6htm5d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d481fff28991e97fe0036eb4d485e070b1bb1d98/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L89)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@sanjayvas @wangyaopw you cool with this change?
</blockquote></details>

LGTM.


It just change the  behavior a little bit.

The old code fails at line 49

```
val duchyIdentityFromContext: DuchyIdentity
  get() =
    requireNotNull(DUCHY_IDENTITY_CONTEXT_KEY.get()) {
      "gRPC context is missing key $DUCHY_IDENTITY_CONTEXT_KEY"
    }
```

new code fails here with a more accurate error code.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261#-Mj5qmI5EtN4pdfH9BTZ:-MjBxScWDDjXfqN5_n1d:b-ucfknh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d481fff28991e97fe0036eb4d485e070b1bb1d98/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L89)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

LGTM.


It just change the  behavior a little bit.

The old code fails at line 49

```
val duchyIdentityFromContext: DuchyIdentity
  get() =
    requireNotNull(DUCHY_IDENTITY_CONTEXT_KEY.get()) {
      "gRPC context is missing key $DUCHY_IDENTITY_CONTEXT_KEY"
    }
```

new code fails here with a more accurate error code.

</blockquote></details>

Thanks!

**Pull request merged**
