### PR TITLE
Set missing fields on internal Measurement.

### PR DESCRIPTION
**Pull request by SanjayVas**
Note that this does not yet include reading all appropriate fields for the COMPUTATION view.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207)

### CODE REVIEW

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 207 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207#-MhUna1ZCJZoP8XqE6PM:-MhUna1ZCJZoP8XqE6PN:bxy0gvq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2d0d9c3c788c7173bf51e75ddeba46db3b34b6b0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L207)):*
> ```
> CertificateId 
> ```
Add a comment saying that this is the measurementConsumer's ceritificate?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207#-MhUpYtz8xBSiJl4j5Hk:-MhUpYtz8xBSiJl4j5Hl:bleucf4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2d0d9c3c788c7173bf51e75ddeba46db3b34b6b0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L31)):*
> ```
> RequisitionKt
> ```
nit: import `RequisitionKt.details` so we don't import the entire object? maybe it doesn't matter

**Review by wangyaopw — APPROVED** [review]
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @uakyol)

**Review by wangyaopw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207#-:-MhUuH6M99QNt6VZ1Zwc:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @uakyol)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 249 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207#-MhUv5tZEzD9-vLI1xI-:-MhUv5tZEzD9-vLI1xI0:b-wrcihi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fa8ba02a2c2910bb947923a6eeb0f758acab75c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L249)):*
> ```
> CreateTime     
> ```
do we want to replace this with a UpdateTime? maybe in another PR.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 84 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207#-MhV8uDXDhWO03zZM21K:-MhV8uDXDhWO03zZM21L:b-dx3xcz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fa8ba02a2c2910bb947923a6eeb0f758acab75c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L84)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     return measurement
>       .toBuilder()
>       .also {
>         it.externalMeasurementId = externalMeasurementId.value
>         it.externalComputationId = externalComputationId.value
>       }
>       .build()
> ```
</details>

```
return measurement.copy{
  externalMeasurementId = externalMeasurementId.value
  externalComputationId = externalComputationId.value
}
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 207 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207#-MhUna1ZCJZoP8XqE6PM:-MhVe6_40IVrxKaxJPhN:bb9i4em) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2d0d9c3c788c7173bf51e75ddeba46db3b34b6b0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L207)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> CertificateId 
> ```
Add a comment saying that this is the measurementConsumer's ceritificate?
</blockquote></details>

It's covered by the foreign key constraint. LMK if you still want the comment.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 249 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207#-MhUv5tZEzD9-vLI1xI-:-MhVeCOYCZ7asbYQNPI0:bu3vd1l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fa8ba02a2c2910bb947923a6eeb0f758acab75c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L249)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> CreateTime     
> ```
do we want to replace this with a UpdateTime? maybe in another PR.
</blockquote></details>

I'll send a separate PR.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207#-MhUpYtz8xBSiJl4j5Hk:-MhVef530lQehhVn9ipv:bh9lkho) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2d0d9c3c788c7173bf51e75ddeba46db3b34b6b0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L31)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> RequisitionKt
> ```
nit: import `RequisitionKt.details` so we don't import the entire object? maybe it doesn't matter
</blockquote></details>

Done. Used an import alias to make it clearer since we have multiple `Details` submessages.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, @uakyol, and @zachcwc)

**Review by uakyol — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @zachcwc)

**Review by corbantek — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 1 of 1 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn and @zachcwc)

**Comment by SanjayVas** [comment]
This is for #103.

**Pull request merged**
