### PR TITLE
Introduce the concept of known EventGroup metadata types.

### LINKED ISSUE #1511: Enforce message type uniqueness for EventGroupMetadataDescriptors
Each EventGroupMetadataDescriptor must describe globally unique protobuf message types. This is necessary to avoid errors where there are multiple definitions for the same message. The requirement is not currently enforced.

### PR DESCRIPTION
**Pull request by SanjayVas**
Known EventGroup metadata types are types expected to be known by all callers. These need not be included in the EventGroupMetadataDescriptor FileDescriptorSet, and are instead loaded separately.

This also enforces uniqueness for EventGroupMetadataDescriptor message types. Note that this only affects the creation of new resources. Existing resources may exist that already violate this constraint.

Includes a workaround for bazelbuild/rules_proto#203.

Closes #1511

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1512)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1512)* status: 9 of 10 files reviewed, all discussions resolved

**Comment by SanjayVas** [comment]
This was significantly reworked to account for the fact that some metadata message types _should_ be shared. One example is SyntheticEventGroupSpec. PTAL.

CC @robinsons

**Review by stevenwarejones — COMMENTED** [review]
What's the use case for sharing metadata messages?

> Reviewed 19 of 59 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1512#-:-NsQ0GAw3vr0cYlQP6M0:bv0snbu)* status: 29 of 68 files reviewed, all discussions resolved

**Review by SanjayVas — COMMENTED** [review]
1. We use shared metadata message types for the simulator test event groups
2. A given market may want all EventGroups across all EDPs to have a field with some common message type

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1512#-:-NsQ_9PS2GAO5pcZeUN_:bsw3lof)* status: 29 of 68 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — COMMENTED** [review]
2. Will this be the case? EDPs probably use different taxonomies and will need different event group metadata.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1512#-:-NsTa2lI4M2UvEiAdAEN:b-6f34vw)* status: 29 of 68 files reviewed, all discussions resolved

**Review by SanjayVas — COMMENTED** [review]
A field with a common message type is not the whole message type. Basically the metadata can have a common part and an EDP-specific part. IIUC, having some commonality is a desire that has already been expressed by Origin.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1512#-:-NsULsu99Vkkc2G_hzdQ:b-o4rgq)* status: 29 of 68 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 38 of 59 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1512)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1512)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1512)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
