### PR TITLE
Implement public FulfillDirectRequisition

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)

### CODE REVIEW

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 226 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-MyUGOFd6rh8EEDWW14T:-MyUGOFe3DRilRY1bszq:b7rmuiz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29f4a43acd7e383421c1cfa80210171f42c88a2b/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L226)):*
> ```Kotlin
>     internalRequisitionStub.fulfillRequisition(
>       fulfillRequisitionRequest {
>         this.requisitionType = FulfillRequisitionRequest.RequisitionType.DIRECT
> ```

nit: leave out the `this.` qualifier unless necessary



_Code quote:_
```Kotlin
this.
```
___
*[src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, line 74 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-MyUHOY98EKSpT1t66S7:-MyUHOY98EKSpT1t66S8:bhoabn6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29f4a43acd7e383421c1cfa80210171f42c88a2b/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L74)):*
> ```protobuf
> 
> message FulfillRequisitionRequest {
>   // Only used for default requisition
> ```

Let's get these terms sorted. So far I've seen "Duchy measurement" and "computation measurement".

How about "computed measurement" vs. "direct measurement"?



_Code quote:_
```protobuf
 default requisition
```
___
*[src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-MyUHB1jA0nJfD01yGzP:-MyUHB1jA0nJfD01yGzQ:b9i6t0h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29f4a43acd7e383421c1cfa80210171f42c88a2b/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L92)):*
> ```protobuf
>   bytes encrypted_data = 5;
> 
>   enum RequisitionType {
> ```

Ditch this enum and wrap fields that are only used for one type or the other in messages inside of a oneof.



_Code quote:_
```protobuf
  enum RequisitionType {
    DEFAULT = 0;
    DIRECT = 1;
  }
  RequisitionType requisition_type = 6;
```

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 739 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-MyUSWAQCDOowpeTaaM0:-MyUSWAQCDOowpeTaaM1:borsfye) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29f4a43acd7e383421c1cfa80210171f42c88a2b/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L739)):*
> ```Kotlin
> 
>   @Test
>   fun `fulfillDirectRequisition throw INVALID_ARGUMENT when id is invalid`() = runBlocking {
> ```

Should be name not id.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: 1 of 10 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, line 74 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-MyUHOY98EKSpT1t66S7:-MyequvaCd5LQwfzJN3V:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29f4a43acd7e383421c1cfa80210171f42c88a2b/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L74)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Let's get these terms sorted. So far I've seen "Duchy measurement" and "computation measurement".

How about "computed measurement" vs. "direct measurement"?
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-MyUHB1jA0nJfD01yGzP:-MyeqvV7EWOiXoEe6CpR:boecr3f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29f4a43acd7e383421c1cfa80210171f42c88a2b/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L92)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ditch this enum and wrap fields that are only used for one type or the other in messages inside of a oneof.
</blockquote></details>

Now we have oneof params between computedParams and directParams
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 739 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-MyUSWAQCDOowpeTaaM0:-Myer2VO8ZjsUr1u5IfO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29f4a43acd7e383421c1cfa80210171f42c88a2b/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L739)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Should be name not id.
</blockquote></details>

Done.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt, line 85 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-Myn1X7S9Ey23LtoLEMD:-MynDX6REuamB_VlbNQs:bd6f34h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab4f6f1a372873e7ceac0acd0fa53ba3c9874755/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt#L85)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This looks like it will throw an error when fulfilling a requisition for a direct Measurement.
</blockquote></details>

Solved in the implementation of internal api. It will be included in the next PR.
___
*[src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-Myn3G6DEXKEbsfa-0Y2:-MynF6Uo2SMMXccq4SWx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab4f6f1a372873e7ceac0acd0fa53ba3c9874755/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that the "computed" vs. "direct" modifier applies to the Measurement that this Requisition is a part of rather than the Requisition itself. Adding some documentation to this may help clarify.

e.g. "Requisition parameters for a Computed Measurement."
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @renjiezh)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 719 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-MynXA4r7_WfZZGw-3oI:-MynXA4r7_WfZZGw-3oJ:b-s7dm4n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/614d60bca8d7fef0f13a76b3c4eff5cc2cd998c6/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L719)):*
> ```Kotlin
>     runBlocking {
>       val request = fulfillDirectRequisitionRequest {
>         name = INVALID_REQUISITION_NAME
> ```

This test is missing the encrypted_data and has an invalid name. Wouldn't be able to confirm it is the missing data that is causing the exception just by looking at this test. The name should be valid.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @SanjayVas, and @tristanvuong2021)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 719 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-MynXA4r7_WfZZGw-3oI:-MynaGnO0Llbt46Sr36H:bnputky) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/614d60bca8d7fef0f13a76b3c4eff5cc2cd998c6/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L719)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This test is missing the encrypted_data and has an invalid name. Wouldn't be able to confirm it is the missing data that is causing the exception just by looking at this test. The name should be valid.
</blockquote></details>

Done. Thanks

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 6 of 9 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 125 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-MyuFevn-daVFVO1Fc0h:-MyuFevn-daVFVO1Fc0i:bogphkg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d6c614c7c17633c0623ddbf23ada04076ab8e1/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L125)):*
> ```Kotlin
>   )
> 
> private val REQUISITION_ENCRYPTED_DATA = ByteString.copyFromUtf8("foo")
> ```

nit: "foo".toByteStringUtf8()
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 126 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-MyuFiQg6Qv0EXIlSryU:-MyuFiQg6Qv0EXIlSryV:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d6c614c7c17633c0623ddbf23ada04076ab8e1/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L126)):*
> ```Kotlin
> 
> private val REQUISITION_ENCRYPTED_DATA = ByteString.copyFromUtf8("foo")
> private val REQUISITION_FINGERPRINT = ByteString.copyFromUtf8("bar")
> ```

ditto

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @stevenwarejones, and @tristanvuong2021)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 126 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488#-MyuFiQg6Qv0EXIlSryU:-MyuO-gG9BHcaiAHb1vm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d6c614c7c17633c0623ddbf23ada04076ab8e1/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L126)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 6 of 9 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

**Review by renjiezh — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/488)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
