### PR TITLE
Add VariancesInterface

### PR DESCRIPTION
**Pull request by riemanli**
* Add VariancesInterface for its user services easier testing.
* Set methodology-specific variance calculation functions private.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1279)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1265** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1265" target="_blank">Graphite</a> 
    * **PR #1253** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1253" target="_blank">Graphite</a> 
      * **PR #1279** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1279" target="_blank">Graphite</a>  👈
      * **PR #1266** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1266" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1279?utm_source=stack-comment).

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1279)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt` line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1279#-Ng0mjFtBs4hzsG2TBFx:-Ng0mjFtBs4hzsG2TBFy:bxye176) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68da49ebe4e1e5e9cc7d1f2d31b959c31a77dfa2/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt#L29)):*
> ```Kotlin
> 
> /** The interface of Variance. */
> interface VariancesInterface {
> ```

Call this Variances and the object VariancesImpl.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1279)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt` line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1279#-Ng0mjFtBs4hzsG2TBFx:-Ng1tH9EBN3NVqaL155W:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68da49ebe4e1e5e9cc7d1f2d31b959c31a77dfa2/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Call this Variances and the object VariancesImpl.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1279)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt` line 82 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1279#-NgKfSop0r1B2-nFfpbi:-NgKfSoq2cOrQMhKSoTN:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bf192785e56e045daba651bcb38c4ef43afea06/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt#L82)):*
> ```Kotlin
> }
> 
> /** Functions to compute different variances. */
> ```

nit



_Suggestion:_
```Kotlin
Default implementation of [Variances].
```

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1279)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt` line 82 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1279#-NgKfSop0r1B2-nFfpbi:-NgLPvrVAbia-w9YspB2:bdi1gae) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bf192785e56e045daba651bcb38c4ef43afea06/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt#L82)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Thanks for the suggestions! Done.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
