### PR TITLE
Add EncryptionKeyPairStore, InMemoryEncryptionKeyPairStore and EncryptionKeyPairMap

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618)

### CODE REVIEW

**Review by chipingyeh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @renjiezh, @riemanli, and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EncryptionKeyPairStoreTest.kt` line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6iNK_777UYnK5qN-gT:-N6iNK_777UYnK5qN-gU:bsdxkry) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ffd6aa1793537c9ae4ffade5fc752f2b4accee1/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EncryptionKeyPairStoreTest.kt#L76)):*
> ```Kotlin
> 
>     runTest(args) { keyPairStore ->
>       assertThat(keyPairStore.getPrivateKey(PUBLIC_KEY_1)).isNotNull()
> ```

Is there a way to test if the correct private key was retrieved?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @riemanli, and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EncryptionKeyPairStoreTest.kt` line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6iNK_777UYnK5qN-gT:-N6j0MWE4iDj6nuPtyYp:b7abn3g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ffd6aa1793537c9ae4ffade5fc752f2b4accee1/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EncryptionKeyPairStoreTest.kt#L76)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Is there a way to test if the correct private key was retrieved?
</blockquote></details>

Done.
Added the process of encryption and decryption to verify the private key

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @SanjayVas)

**Review by chipingyeh — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618)* status: all files reviewed, 5 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/BUILD.bazel` line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6oRGN488JafqZ3baek:-N6oRGN488JafqZ3bael:bzgmhpg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b755d10b74a0343d6ffd41bbc088529fc2024ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/BUILD.bazel#L4)):*
> ```Starlark
> 
> package(
>     default_testonly = True,
> ```

This isn't a `testing` package, so it shouldn't be `default_testonly`.

My assumption is that you want to mark `encryption_key_pair_store` as testonly, which means that you need to mark anything that depends on it as testonly. Do so with a TODO on each for removing it once key loading has been moved out of testing.



_Code quote:_
```Starlark
    default_testonly = True,
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt` line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6oXOh0ARkwo1Uvk5rd:-N6oXOh0ARkwo1Uvk5re:b-p2yqim) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b755d10b74a0343d6ffd41bbc088529fc2024ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt#L26)):*
> ```Kotlin
> 
> interface EncryptionKeyPairStore {
>   fun getPrivateKey(publicKey: ByteString): PrivateKeyHandle? {
> ```

This should be a suspending function in case there are implementations that need to perform I/O.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6oZ6IZAihmNknhERu8:-N6oZ6IZAihmNknhERu9:b9wugz5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b755d10b74a0343d6ffd41bbc088529fc2024ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt#L31)):*
> ```Kotlin
> }
> 
> // TODO(@renjiez): Move this class to deploy folder
> ```

Don't move this class to deploy, just separate out the command-line related parts from this class and have those be under `deploy`.

e.g. have the class just take in a Map in the constructor



_Code quote:_
```Kotlin
// TODO(@renjiez): Move this class to deploy folder
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt` line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6oZRMjAQaZKS662RlG:-N6oZRMjAQaZKS662RlH:b-48ls4h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b755d10b74a0343d6ffd41bbc088529fc2024ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt#L38)):*
> ```Kotlin
>   class EncryptionKeyPair {
>     @Option(
>       names = ["--encryption-public-key-file"],
> ```

Having all these individual files would mean having to manually update a section of the K8s manifest for the server.

Instead, I'd recommend having two flags: one for a config file with the key mappings, and another for the directory where the files are located.

My recommendation for the config file format is a textproto of a map of public key file name to private key file name.



_Code quote:_
```Kotlin
  names = ["--encryption-public-key-file"],
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6oaBIMEcpz7l0b5g0P:-N6oaBIMEcpz7l0b5g0Q:bpnaelp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b755d10b74a0343d6ffd41bbc088529fc2024ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt#L58)):*
> ```Kotlin
> 
>   private val map: Map<ByteString, PrivateKeyHandle> by lazy {
>     encryptionKeyPairs.associate { it.publicKey to it.privateKeyHandle }
> ```

Having the map key be a serialized public key seems inefficient, as you have to keep the entire public key in memory. Consider using a fingerprint/hash of the public key instead.



_Code quote:_
```Kotlin
Map<ByteString, PrivateKeyHandle>
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618)* status: all files reviewed, 5 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6oZ6IZAihmNknhERu8:-N6slqYB2jx3KuE7Z8C8:b-9gebcb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b755d10b74a0343d6ffd41bbc088529fc2024ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt#L31)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

If the deploy part only provides a map, I wonder if it might cause mismatch because the map will use the key of fingerprint instead of the entire public key. 
If moving the entire `InMemoryEncryptionKeyPairStore`, it seems easier to write a unit test as we keep the implementation as a whole.
</blockquote></details>

The class need not use the map as-is. e.g. the constructor argument can be a map of ByteString to PrivateKeyHandle and can compute the fingerprints to build its own internal map.

There's a distinct difference between a generic in-memory key store and one that eagerly reads from a filesystem and then caches the keys in memory. You could instead define this store class to take in the files if you want to make the filesystem reading a part of the class, but how it gets those files (i.e. CLI options) should still be kept separate.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/BUILD.bazel` line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6oRGN488JafqZ3baek:-N6s_LIN-IMAadmQj6i2:b6i0dug) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b755d10b74a0343d6ffd41bbc088529fc2024ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This isn't a `testing` package, so it shouldn't be `default_testonly`.

My assumption is that you want to mark `encryption_key_pair_store` as testonly, which means that you need to mark anything that depends on it as testonly. Do so with a TODO on each for removing it once key loading has been moved out of testing.
</blockquote></details>

Done.
Marked as todo. Will fix it in the next PR.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt` line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6oXOh0ARkwo1Uvk5rd:-N6s_QKW6Iwg63txr96a:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b755d10b74a0343d6ffd41bbc088529fc2024ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be a suspending function in case there are implementations that need to perform I/O.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6oZ6IZAihmNknhERu8:-N6tOQJaEez6-HuC0Vra:bvs9d5k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b755d10b74a0343d6ffd41bbc088529fc2024ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The class need not use the map as-is. e.g. the constructor argument can be a map of ByteString to PrivateKeyHandle and can compute the fingerprints to build its own internal map.

There's a distinct difference between a generic in-memory key store and one that eagerly reads from a filesystem and then caches the keys in memory. You could instead define this store class to take in the files if you want to make the filesystem reading a part of the class, but how it gets those files (i.e. CLI options) should still be kept separate.
</blockquote></details>

Done.
Sounds good.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt` line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6oZRMjAQaZKS662RlG:-N6tOI89CM_xhiNue_fQ:b49l4fo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b755d10b74a0343d6ffd41bbc088529fc2024ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Having all these individual files would mean having to manually update a section of the K8s manifest for the server.

Instead, I'd recommend having two flags: one for a config file with the key mappings, and another for the directory where the files are located.

My recommendation for the config file format is a textproto of a map of public key file name to private key file name.
</blockquote></details>

Done.
Great idea!

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r3, 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @renjiezh, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMap.kt` line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tPFnmC7NPcUVRtG7f:-N6tPFnmC7NPcUVRtG7g:b-u6kd07) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMap.kt#L31)):*
> ```Kotlin
>       description = ["Path to the directory of MeasurementConsumer's encryption keys"],
>   )
>   private lateinit var keyFilesDirectory: String
> ```

`File`



_Code quote:_
```Kotlin
String
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMap.kt` line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tPJ-G59YtM9yEaM9P:-N6tPJ-G59YtM9yEaM9Q:b-bbpj3z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMap.kt#L41)):*
> ```Kotlin
>   val keyPairs: Map<ByteString, PrivateKeyHandle> by lazy {
>     parseTextProto(keyPairListFile, encryptionKeyPairMap {}).entriesList.associate {
>       val publicKeyFile = File(keyFilesDirectory, it.publicKeyFilename)
> ```

`keyFilesDirectory.resolve(it.publicKeyFilename)`



_Code quote:_
```Kotlin
File(keyFilesDirectory, it.publicKeyFilename)
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tPwa384cf_w-B1u9J:-N6tPwa384cf_w-B1u9K:b-a2m42k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt#L23)):*
> ```Kotlin
> interface EncryptionKeyPairStore {
>   suspend fun getPrivateKey(publicKey: ByteString): PrivateKeyHandle? {
>     return null
> ```

Don't put a default implementation. You want to force implementations to implement this function.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt` line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tQmAIC4zJN9h6-Jpt:-N6tQmAJ8apbe0eK0Zst:b-fx1ee1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt#L30)):*
> ```Kotlin
>     EncryptionKeyPairStore {
>   private val keyPairMap: Map<ByteString, PrivateKeyHandle> =
>       keyPairs.mapKeys { hashSha256(it.key) }
> ```

nit: consider a different fingerprinting algorithm

We don't need this to be a secure hash, just a fast [fingerprint](https://en.wikipedia.org/wiki/Fingerprint_(computing)) with low collision chance. Since we're not persisting the hashes, perhaps `goodFastHash` with 128 bits from the [Guava hashing library](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/hash/Hashing.html#goodFastHash(int)).



_Code quote:_
```Kotlin
hashSha256
```
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/BUILD.bazel` line 155 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tTB-H1-Rw6BahbJS4:-N6tTB-H1-Rw6BahbJS5:bcd59c8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/main/proto/wfa/measurement/reporting/v1alpha/BUILD.bazel#L155)):*
> ```Starlark
> 
> # Config
> ```

This isn't strictly part of the API and therefore should be in this package.

Perhaps under `//src/main/proto/wfa/measurement/config/reporting`?
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/encryption_key_pair_map.proto` line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tT_Hu9hvUp8jiSlPV:-N6tT_Hu9hvUp8jiSlPW:by0nwo9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/main/proto/wfa/measurement/reporting/v1alpha/encryption_key_pair_map.proto#L22)):*
> ```protobuf
> option java_multiple_files = true;
> 
> message EncryptionKeyPairMap {
> ```

I'd recommend having this something like `EncryptionKeyConfig` with a proto3 `map` field for the actual map.



_Code quote:_
```protobuf
EncryptionKeyPairMap
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMapTest.kt` line 66 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tU2311_bCVLRDydQI:-N6tU2311_bCVLRDydQJ:biebpsq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/test/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMapTest.kt#L66)):*
> ```Kotlin
> private val PLAIN_TEXT = "THis is plain text".toByteStringUtf8()
> 
> @RunWith(JUnit4::class)
> ```

Have a test just for the store impl. If desired, you can test the flags class independently.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618)* status: 2 of 12 files reviewed, 6 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMap.kt` line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tPFnmC7NPcUVRtG7f:-N6v0lviC5ILYwCzZ7lP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMap.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`File`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMap.kt` line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tPJ-G59YtM9yEaM9P:-N6v106d4buIapLcG_n8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMap.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`keyFilesDirectory.resolve(it.publicKeyFilename)`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tPwa384cf_w-B1u9J:-N6v1ZTSDiyi6bGLLRy2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't put a default implementation. You want to force implementations to implement this function.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMapTest.kt` line 66 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tU2311_bCVLRDydQI:-N6xmRxLCBtOIkxA5EgX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/test/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMapTest.kt#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Have a test just for the store impl. If desired, you can test the flags class independently.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/BUILD.bazel` line 155 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tTB-H1-Rw6BahbJS4:-N6v6EK-9vg-_Vuc_icR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/main/proto/wfa/measurement/reporting/v1alpha/BUILD.bazel#L155)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This isn't strictly part of the API and therefore should be in this package.

Perhaps under `//src/main/proto/wfa/measurement/config/reporting`?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/encryption_key_pair_map.proto` line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6tT_Hu9hvUp8jiSlPV:-N6v9p0f-palUVUXlcg9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6fbc9e1985e6ec13a09ab2ca95f4680231e2517/src/main/proto/wfa/measurement/reporting/v1alpha/encryption_key_pair_map.proto#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'd recommend having this something like `EncryptionKeyConfig` with a proto3 `map` field for the actual map.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 5 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMap.kt` line 33 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6yC0OV3eYKAIXBaVb-:-N6yC0OV3eYKAIXBaVb0:b-eqghum) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/402e3b551df2c1e2f789051b650ed4916f9f8d27/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMap.kt#L33)):*
> ```Kotlin
>   private lateinit var keyFilesDirectory: File
> 
>   @Option(
> ```

nit: rename this to match the fact that the config message was renamed, and make it clear in the description that this is expected to be a file containing an `EncryptionKeyPairConfig` protobuf message in text format.



_Code quote:_
```Kotlin
  @Option(
    names = ["--key-pair-map-file"],
    description = ["Path to the map of of MeasurementConsumer's encryption keys"],
    required = true
  )
  private lateinit var keyPairListFile: File
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618#-N6yBMki9EAglqOyYg7V:-N6yBMki9EAglqOyYg7W:b-1c96st) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/402e3b551df2c1e2f789051b650ed4916f9f8d27/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EncryptionKeyPairStore.kt#L31)):*
> ```Kotlin
>   private val hashFunction = goodFastHash(DEFAULT_HASH_MINIMUM_BITS)
> 
>   private fun hash(key: ByteString) = hashFunction.hashBytes(key.toByteArray()).toString()
> ```

nit: maybe `fingerprint` to be more clear that this doesn't necessarily need to be a hash algorithm



_Code quote:_
```Kotlin
hash
```

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 11 files at r3, 1 of 5 files at r4, 6 of 9 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/618)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Pull request merged**
