### PR TITLE
Configure metrics in K8s workflows.

### PR DESCRIPTION
**Pull request by SanjayVas**
This also adds missing NetworkPolicy resources for EDP simulators. Enabling metrics in a cluster results in NetworkPolicy resources being added. When adding any NetworkPolicy to the cluster, all traffic not covered by the policy appears to be blocked by default.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`docs/gke/metrics-deployment.md` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017#-NXHBFpx1vYgVt_V7yDI:-NXHBFpx1vYgVt_V7yDJ:b-wkczxe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44704b4ebb111c6ca99a28990220732c6c8d6c38/docs/gke/metrics-deployment.md#L118)):*
> ```Markdown
> ```
> 
> Verify the pods have the label `scrape=true` with
> ```

I forgot to remove this when I switched from sidecars for each pod to a single collector.  There is no label `scrape=true` for reach pod anymore.
___
*[`src/main/k8s/dev/edp_simulator_gke.cue` line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017#-NXH8JXy6dmRF12Bg_XC:-NXH8JXy6dmRF12Bg_XD:b-o9mfly) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44704b4ebb111c6ca99a28990220732c6c8d6c38/src/main/k8s/dev/edp_simulator_gke.cue#L88)):*
> ```CUE
> }
> 
> networkPolicies: [Name=_]: #NetworkPolicy & {
> ```

What is this for. I already see it added to the base.
___
*[`src/main/k8s/dev/prometheus_gke.cue` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017#-NXHC1Qu14fbmITlYgWY:-NXHC1Qu14fbmITlYgWZ:bao0e1e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44704b4ebb111c6ca99a28990220732c6c8d6c38/src/main/k8s/dev/prometheus_gke.cue#L26)):*
> ```CUE
> 
> clusterPodMonitorings: {
> 	"gcp-prometheus-pod-monitoring": {
> ```

This first clusterPodMonitoring is also unused right now. It is meant for scraping any pod with a sidecar collector, but as of right now there isn't any.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017)* status: 11 of 28 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`docs/gke/metrics-deployment.md` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017#-NXHBFpx1vYgVt_V7yDI:-NXHw13w3FvwaALj_dQy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44704b4ebb111c6ca99a28990220732c6c8d6c38/docs/gke/metrics-deployment.md#L118)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I forgot to remove this when I switched from sidecars for each pod to a single collector.  There is no label `scrape=true` for reach pod anymore.
</blockquote></details>

Done.
___
*[`src/main/k8s/dev/edp_simulator_gke.cue` line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017#-NXH8JXy6dmRF12Bg_XC:-NXHwG7_1KtbSqBZPX1z:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44704b4ebb111c6ca99a28990220732c6c8d6c38/src/main/k8s/dev/edp_simulator_gke.cue#L88)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

What is this for. I already see it added to the base.
</blockquote></details>

Done.
___
*[`src/main/k8s/dev/prometheus_gke.cue` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017#-NXI-1R62scILbdw503K:-NXI-1R62scILbdw503L:bs9iirs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44704b4ebb111c6ca99a28990220732c6c8d6c38/src/main/k8s/dev/prometheus_gke.cue#L18)):*
> ```CUE
> 
> // K8s service account for access to Cloud Monitoring.
> #MonitoringServiceAccount: "gmp-monitoring"
> ```

Since this account is no longer used, I dropped it from the Terraform config as well.
___
*[`src/main/k8s/dev/prometheus_gke.cue` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017#-NXHC1Qu14fbmITlYgWY:-NXHzWYq5DVPeK2aHoFq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44704b4ebb111c6ca99a28990220732c6c8d6c38/src/main/k8s/dev/prometheus_gke.cue#L26)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This first clusterPodMonitoring is also unused right now. It is meant for scraping any pod with a sidecar collector, but as of right now there isn't any.
</blockquote></details>

Done.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`docs/gke/metrics-deployment.md` line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017#-NXLQwmc3UiDkLyBScTr:-NXLQwmd1qfkT-OuHHsf:b-p685ts) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da8b93b3814f61ce5011d1e8c22a22a54da3517e/docs/gke/metrics-deployment.md#L26)):*
> ```Markdown
>     *   `open-telemetry-java-agent`
> *   GMP ClusterPodMonitoring
>     *   `prometheus-pod-monitor`
> ```

nit: The first ClusterPodMonitoring is no longer created.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 11 of 14 files at r1, 16 of 17 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1017)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
