### PR TITLE
Refine logs of herald and mill

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/699)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/699)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by matthewclegg — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/699)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/699#-NCf8-pV23SKyJc0esHb:-NCf8-pV23SKyJc0esHc:b-vbf5vq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/720bacec5b214af682f60ebe6195a12b3ccdbc16/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L163)):*
> ```Kotlin
>     require(computation.name.isNotEmpty()) { "Resource name not specified" }
>     val globalId: String = computation.key.computationId
>     logger.info("[id=$globalId]: Processing updated GlobalComputation")
> ```

Consider keeping this logging code but setting the log level to fine.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/699)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/699)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/699)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/699#-NCf8-pV23SKyJc0esHb:-NCgKB9d6FB2HlwR_rci:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/720bacec5b214af682f60ebe6195a12b3ccdbc16/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L163)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Consider keeping this logging code but setting the log level to fine.
</blockquote></details>

Done.



_Code quote:_
```Kotlin
    val globalId: String = computation.key.computationId
    logger.info("[id=$globalId]: Processing updated GlobalComputation")
```

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/699)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @matthewclegg)

**Review by renjiezh — COMMENTED** [review]
> Dismissed @matthewclegg from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/699)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
