### PR TITLE
Add Deployment Images for Reporting V2

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1099)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1099)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1099#-N_6AKWr2BNskK_wM8We:-N_6AKWr2BNskK_wM8Wf:be1pj0g) (no related file):*
Note that after this point we should probably lock the initial schema changeset and require additional schema changes to be done in new changesets.

___
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/gcloud/postgres/server/GCloudPostgresInternalReportingServer.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1099#-N_6AGx1DYdahSx7PCCo:-N_6AGx1DYdahSx7PCCp:b-20g7g3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ba7b12639cb10437102579382165af19078a4f57/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/gcloud/postgres/server/GCloudPostgresInternalReportingServer.kt#L37)):*
> ```Kotlin
>   showDefaultValues = true
> )
> class GCloudPostgresReportingDataServer : InternalReportingServer() {
> ```

nit: Drop `Data`



_Code quote:_
```Kotlin
DataServer
```

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 10 of 13 files at r1, 2 of 2 files at r2, 2 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1099)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1099)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Pull request merged**
