### PR TITLE
Ensure all files end in a newline.

### PR DESCRIPTION
**Pull request by efoxepstein**
This ignores Bazel files (which the formatter insists not end in
newlines) and the /third_party/ directory.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/9)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]

**Review by stevenwarejones — APPROVED** [review]
Can we enable some kind of linting (maybe github actions) to keep this consistent in the future?

**Review by efoxepstein — COMMENTED** [review]
Yeah, good idea! It's kind of dubious how much effort we should invest in trailing newlines... I'll think about it.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/9#-:-MYCE4vc5gkD-krL6D1m:b-lnbhjf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlekseiS, @oliver-amzn, and @zasadnyy)

**Comment by stevenwarejones** [comment]
> Yeah, good idea! It's kind of dubious how much effort we should invest in trailing newlines... I'll think about it.
> 
> > _[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/9#-:-MYCE4vc5gkD-krL6D1m:b-lnbhjf)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlekseiS, @oliver-amzn, and @zasadnyy)

Agree that its not worth it for newline only.... but if we want consistent linting, the only way that's going to happen is if its enforced.

**Review by SanjayVas — COMMENTED** [review]
The way I'd put it is if something like files ending in newline isn't enforced by a linter/formatter, then it shouldn't be commented on in code reviews.

If anyone feels strongly about whether files end in newline, you can update the lint script at https://github.com/world-federation-of-advertisers/actions/blob/main/lint/lint.sh. You'd then need to create a new release of our actions and update the workflow in each repo to use the new version.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/9#-:-MYCF8Na4BrBEtgdRHSa:b90wmun)* status: 27 of 29 files reviewed, all discussions resolved (waiting on @AlekseiS, @oliver-amzn, @SanjayVas, and @zasadnyy)

**Pull request merged**
