### PR TITLE
Enable HMSS in kingdom with k8s test for both MPC protocols

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/k8s/dev/edp_simulator_gke.cue` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813#-O7Vo9Kg1QnYXDvegb0_:-O7Vo9Kg1QnYXDvegb0a:b966lzc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17a6326eef1bca107f7a98f261836c0de035dfb3/src/main/k8s/dev/edp_simulator_gke.cue#L58)):*
> ```CUE
> 		displayName:      "edp\(Number)"
> 		publisherId:      Number
> 		if (i < len(_edpResourceNames)/2) {
> ```

Use Mod from math package



_Suggestion:_
```CUE
math.Mod(Number, 2) == 0
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/dev/edp_simulator_gke.cue` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813#-O7Vo9Kg1QnYXDvegb0_:-O7Vpad0A27xrvnsAO1M:bjlypq2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17a6326eef1bca107f7a98f261836c0de035dfb3/src/main/k8s/dev/edp_simulator_gke.cue#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Mod from math package
</blockquote></details>

The purpose is to make the first 3 EDP simulators support HMSS. Because we have 3 synthetic_event_specs, and simulator 1, 2, 3 are a complete set.

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/k8s/dev/edp_simulator_gke.cue` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813#-O7ZVihT9tjoseYLTF-G:-O7ZVihT9tjoseYLTF-H:b-czvku9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17a6326eef1bca107f7a98f261836c0de035dfb3/src/main/k8s/dev/edp_simulator_gke.cue#L58)):*
> ```CUE
> 		displayName:      "edp\(Number)"
> 		publisherId:      Number
> 		if (i < len(_edpResourceNames)/2) {
> ```

can you explain the logic here?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/k8s/dev/edp_simulator_gke.cue` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813#-O7ZVihT9tjoseYLTF-G:-O7ZZnO80xB8_zLNcZP0:bsdms44) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17a6326eef1bca107f7a98f261836c0de035dfb3/src/main/k8s/dev/edp_simulator_gke.cue#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you explain the logic here?
</blockquote></details>

We have 6 EDP simulators and 3 synthettic_event_specs.  Simulator i and i+3 are the same regarding the synthetic_event_spec. They are two sets of EDPs. https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/58eb5f261ac0fb24c854c0d20400b04ec623348b/src/main/k8s/dev/synthetic_generator_edp_simulator_gke.cue#L37-L38
In order to test both LLv2 and HMSS in our dev/qa environment, we can make the first set of simulators supports HMSS and the other set not. Thus add this feature flag to  the first 3 simulators.  By specifying the EDP, a test can run against either protocol.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/k8s/dev/edp_simulator_gke.cue` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813#-O7ZVihT9tjoseYLTF-G:-O7ZbLKs9eiJsYre9wmA:btgdt49) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17a6326eef1bca107f7a98f261836c0de035dfb3/src/main/k8s/dev/edp_simulator_gke.cue#L58)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

We have 6 EDP simulators and 3 synthettic_event_specs.  Simulator i and i+3 are the same regarding the synthetic_event_spec. They are two sets of EDPs. https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/58eb5f261ac0fb24c854c0d20400b04ec623348b/src/main/k8s/dev/synthetic_generator_edp_simulator_gke.cue#L37-L38
In order to test both LLv2 and HMSS in our dev/qa environment, we can make the first set of simulators supports HMSS and the other set not. Thus add this feature flag to  the first 3 simulators.  By specifying the EDP, a test can run against either protocol.
</blockquote></details>

@renjiezh Since you've been asked this twice in this PR, can you add a comment in the code itself? Something like "Support HMSS on the first half of the EDPs so that we have one EDP with each event source supporting the protocol"

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/k8s/dev/edp_simulator_gke.cue` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813#-O7ZVihT9tjoseYLTF-G:-O7_1DuqEJ8C5-sBv9EE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17a6326eef1bca107f7a98f261836c0de035dfb3/src/main/k8s/dev/edp_simulator_gke.cue#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@renjiezh Since you've been asked this twice in this PR, can you add a comment in the code itself? Something like "Support HMSS on the first half of the EDPs so that we have one EDP with each event source supporting the protocol"
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/dev/edp_simulator_gke.cue` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813#-O7ZVihT9tjoseYLTF-G:-O7e1yb87cE3cfEGgktA:b-m2zip9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17a6326eef1bca107f7a98f261836c0de035dfb3/src/main/k8s/dev/edp_simulator_gke.cue#L58)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why not be more explicit and say 
```
if name in ["_edp1_name", "_edp2_name", "_edp3_name"]
   supportHmss: true
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/k8s/dev/edp_simulator_gke.cue` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813#-O7ZVihT9tjoseYLTF-G:-O7e4LEP1MMxMVjz50vv:bvs9d5k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17a6326eef1bca107f7a98f261836c0de035dfb3/src/main/k8s/dev/edp_simulator_gke.cue#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why not be more explicit and say 
```
if name in ["_edp1_name", "_edp2_name", "_edp3_name"]
   supportHmss: true
```

</blockquote></details>

Done.
Sounds good.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1813)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
