### PR TITLE
Fill missing fields for internal Measurement DEFAULT view.

### PR DESCRIPTION
**Pull request by SanjayVas**
https://rally1.rallydev.com/#/604612930531d/portfolioitemstreegrid?detail=%2Ftask%2F607712261053&fdp=true?fdp=true

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/225)

### CODE REVIEW

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/225)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @SanjayVas, and @zachcwc)

**Review by corbantek — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/225)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Comment by SanjayVas** [comment]
This is for #103.

**Pull request merged**
