### PR TITLE
Authenticate /ExchangeSteps and /ExchangeStepAttempts

### PR DESCRIPTION
**Pull request by efoxepstein**
This adds authn and authz for ClaimReadyExchangeStep and FinishExchangeStepAttempt.

https://rally1.rallydev.com/#/?detail=/userstory/608272166863&fdp=true

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)

### CODE REVIEW

**Review by yunyeng — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGB3HgBuCnvdTT_SuH:-MjGB3HgBuCnvdTT_SuI:b-p63iuo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/523e96cf4efc0d057e588a89e9de764f3d1e8bff/src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt#L16)):*
> ```
> package org.wfanet.measurement.common.identity
> ```
Should have caught this in the previous PR and it can be done in a separate one at low priority, but these interceptors should be in `grpc` not `identity`.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGCsGY4U-vc5i1KL7O:-MjGCNX91lKkKThGjU38:bpncutg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/523e96cf4efc0d057e588a89e9de764f3d1e8bff/src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt#L38)):*
> ```Kotlin
>   get() =
>     AUTHORITY_KEY_IDENTIFIERS_CONTEXT_KEY.get()
>       ?: failGrpc(Status.UNAUTHENTICATED) { "No authority keys available" }
> ```

Not every method requires mTLS. e.g. account activation, which should *not* pass through a registered MC frontend to avoid leaking credentials. Those cases are therefore expected not to have a client cert.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGB3HgBuCnvdTT_SuH:-MjGKeMu0gvww9gpGsFp:bkd5ega) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/523e96cf4efc0d057e588a89e9de764f3d1e8bff/src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt#L16)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> package org.wfanet.measurement.common.identity
> ```
Should have caught this in the previous PR and it can be done in a separate one at low priority, but these interceptors should be in `grpc` not `identity`.
</blockquote></details>

Added a TODO
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGCsGY4U-vc5i1KL7O:-MjGKjT49-Gmbj-FaMTo:b-i5p5ec) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/523e96cf4efc0d057e588a89e9de764f3d1e8bff/src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not every method requires mTLS. e.g. account activation, which should *not* pass through a registered MC frontend to avoid leaking credentials. Those cases are therefore expected not to have a client cert.
</blockquote></details>

Concretely, what does that mean? Can we just NOT install this ServerInterceptor on the service used for account activation? Alternatively, the account activation endpoint can just never call `authorityKeyIdentifiersFromCurrentContext`?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGCsGY4U-vc5i1KL7O:-MjGn1glDY0k9l50kQz0:b-xelrha) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/523e96cf4efc0d057e588a89e9de764f3d1e8bff/src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Concretely, what does that mean? Can we just NOT install this ServerInterceptor on the service used for account activation? Alternatively, the account activation endpoint can just never call `authorityKeyIdentifiersFromCurrentContext`?
</blockquote></details>

My instinct was to just have this property be an empty list and have PrincipalServerInterceptor throw an error if it can't find any principal.

I suppose if we have a service where we know for all methods that we don't rely on mTLS for client authentication, then it'd be fine to just swap the interceptors to prevent it from being called. I had envisioned the expected principal to be a per-method consideration, and PrincipalServerInterceptor to handle all possible credential types.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 83 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGyGNs4JHcNj8sHprP:-MjGyGNs4JHcNj8sHprQ:b-7u1mop) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L83)):*
> ```
> ensure that the current gRPC context is authorized to read the ExchangeStep.
> ```
What's the failure case if the authenticated principal is not authorized for this operation (i.e. the mTLS cert belongs to some known provider, but not the right one)? Do we just get a NOT_FOUND from `GetExchangeStep`? If so, shouldn't this code handle that and throw the appropriate status?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt, line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGzi5v9EznlwtJOuMl:-MjGzi5v9EznlwtJOuMm:b-jsf03i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt#L59)):*
> ```Kotlin
> }
> 
> private val PRINCIPAL_CONTEXT_KEY: Context.Key<Principal<*>> =
> ```

Add KDoc here indicating that this is the context key for the *authenticated* principal? Similarly on `principalFromCurrentContext`.

I realized we should really be clear on expectations and that anybody calling this should be able to trust that the principal has already been authenticated (e.g. via mTLS, verification of secret/token, etc.). Similarly, nobody should set this unless it's been authenticated.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGtveQ8sq_eKtYAZ4e:-MjGtveR0_to7OXWuW2l:bf9pqni) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt#L36)):*
> ```
> failGrpc
> ```
Specify the correct status code here.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: all files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 83 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGyGNs4JHcNj8sHprP:-MjUEPX5A035tL93cr7R:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ensure that the current gRPC context is authorized to read the ExchangeStep.
> ```
What's the failure case if the authenticated principal is not authorized for this operation (i.e. the mTLS cert belongs to some known provider, but not the right one)? Do we just get a NOT_FOUND from `GetExchangeStep`? If so, shouldn't this code handle that and throw the appropriate status?
</blockquote></details>

+1
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt, line 147 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjUFGsR95YtJ7_G2D9n:-MjUFGsR95YtJ7_G2D9o:b-1qszyw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt#L147)):*
> ```Kotlin
>   fun appendLogEntry() {
>     val request =
>       AppendLogEntryRequest.newBuilder()
> ```

nit: update protos to new kotlin format
feel free to ignore since its old code
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt, line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjUFT8P0-24e7i9Oibl:-MjUFT8P0-24e7i9Oibm:b-iipjm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt#L158)):*
> ```Kotlin
>     verifyProtoArgument(internalExchangeStepAttempts, InternalExchangeStepAttempts::appendLogEntry)
>       .isEqualTo(
>         InternalAppendLogEntryRequest.newBuilder()
> ```

nit: ditto
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt, line 205 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjUGPFx19vliskc-Kih:-MjUGPFy6S68_tOBg8aW:b-jz3k9g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt#L205)):*
> ```Kotlin
>         }
>       }
>     assertThat(e.status.code).isEqualTo(Status.Code.UNAUTHENTICATED)
> ```

`Status.Code.PERMISSION_DENIED` assuming they are a valid party, mtls succeeds but they aren't a valid party for this transaction
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, line 135 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjUG0m3962Ng4Z1aj4f:-MjUG0m44C1AhpHCwZt8:b5kuu3t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt#L135)):*
> ```Kotlin
> 
>   @Test
>   fun `claimReadyExchangeStep for DataProvider`() {
> ```

you could abstract these tests out for each party.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: all files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGCsGY4U-vc5i1KL7O:-MjV09vY8Zx33Qz69D1m:bcmn5e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/523e96cf4efc0d057e588a89e9de764f3d1e8bff/src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

My instinct was to just have this property be an empty list and have PrincipalServerInterceptor throw an error if it can't find any principal.

I suppose if we have a service where we know for all methods that we don't rely on mTLS for client authentication, then it'd be fine to just swap the interceptors to prevent it from being called. I had envisioned the expected principal to be a per-method consideration, and PrincipalServerInterceptor to handle all possible credential types.
</blockquote></details>

If `AuthorityKeyServerInterceptor` is installed, this will never be null (because the interceptor always sets it or closes the call with an UNAUTHENTICATED error).

I thought it would be safer to throw in this case to ensure that if we're trying to access this Context key, the ServerInterceptor is installed.

Maybe a change we could make is NOT failing with UNAUTHENTICATED when there's some X509 cert without an AKID. WDYT?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 83 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGyGNs4JHcNj8sHprP:-MjV4iCq0j94aE31vvJh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L83)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt, line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGzi5v9EznlwtJOuMl:-MjV5Zyx5bmlLtEGJBt_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add KDoc here indicating that this is the context key for the *authenticated* principal? Similarly on `principalFromCurrentContext`.

I realized we should really be clear on expectations and that anybody calling this should be able to trust that the principal has already been authenticated (e.g. via mTLS, verification of secret/token, etc.). Similarly, nobody should set this unless it's been authenticated.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGtveQ8sq_eKtYAZ4e:-MjV5l0e7Fi2c_nAIxIz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> failGrpc
> ```
Specify the correct status code here.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt, line 147 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjUFGsR95YtJ7_G2D9n:-MjVF3_G7JD0y6SlQisc:bnrdr5i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt#L147)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit: update protos to new kotlin format
feel free to ignore since its old code
</blockquote></details>

A dedicated cleanup PR can do this
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt, line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjUFT8P0-24e7i9Oibl:-MjVF5SYD3g8TBHEsEnn:bnrdr5i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt#L158)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit: ditto
</blockquote></details>

A dedicated cleanup PR can do this
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt, line 205 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjUGPFx19vliskc-Kih:-MjVF3AQCPNk8-Z_IATA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt#L205)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`Status.Code.PERMISSION_DENIED` assuming they are a valid party, mtls succeeds but they aren't a valid party for this transaction
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, line 135 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjUG0m3962Ng4Z1aj4f:-MjVJhjq9e5PP_LVtPe2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518e2951ad5b0b216e348479f946305859aaf5/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt#L135)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you could abstract these tests out for each party.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGCsGY4U-vc5i1KL7O:-MjVTn_DEftEdPmSF2Ei:bxa4ldv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/523e96cf4efc0d057e588a89e9de764f3d1e8bff/src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt#L38)):*
So there's two parts here. Can we require mTLS at the service level rather than the method level? If so, then having this interceptor throw UNAUTHENTICATED when there's no valid client cert (i.e. one with an AKID) is fine, and we just don't install the interceptor for that service. If we instead need to require mTLS at the method level or require it conditionally, we need the interceptor to pass and allow the method impl to throw UNAUTHENTICATED if needed. Note that this latter behavior is correct even in the case where we could put the requirement at the service level. It just requires us to make sure we have the check in every method impl.

The following statements assume that we choose to go with the more flexible second option.

> I thought it would be safer to throw in this case to ensure that if we're trying to access this Context key, the ServerInterceptor is installed.

Sounds like the server interceptor should set the context key to empty list when it doesn't find a client X.509 cert. This way we can still throw when trying to access if it if it's not set.

> Maybe a change we could make is NOT failing with UNAUTHENTICATED when there's some X509 cert without an AKID. WDYT?

Yes, if we assume that not all services that have this interceptor installed require a valid client cert (mTLS) then we would in fact need a way to have it not fail at the interceptor level.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 97 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjVOwGCBKKfpokyrKuX:-MjVOwGCBKKfpokyrKuY:b-nrbav0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47b3645becc0932f8a9586eb048862611de73d78/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L97)):*
> ```
> Status.Code.NOT_FOUND
> ```
Sorry, should have been more clear in the previous comment that I think that it might still be incorrect to throw PERMISSION_DENIED here if the parent ExchangeStep is not found.

1. For a resource-oriented API, I believe if the parent resource is not found then the child resource should also be not found since that's part of the child resource's name.
2. The internal Get should return NOT_FOUND if the resource with the specified IDs isn't found, and PERMISSION_DENIED if the specified provider doesn't match.

Therefore, you should be able to map internal parent Get NOT_FOUND to public API child NOT_FOUND.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @stevenwarejones, and @yunyeng)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, and @yunyeng)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 97 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjVOwGCBKKfpokyrKuX:-MjVh3sWBrk3t5Vtg9wY:b-3ecd50) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47b3645becc0932f8a9586eb048862611de73d78/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L97)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Status.Code.NOT_FOUND
> ```
Sorry, should have been more clear in the previous comment that I think that it might still be incorrect to throw PERMISSION_DENIED here if the parent ExchangeStep is not found.

1. For a resource-oriented API, I believe if the parent resource is not found then the child resource should also be not found since that's part of the child resource's name.
2. The internal Get should return NOT_FOUND if the resource with the specified IDs isn't found, and PERMISSION_DENIED if the specified provider doesn't match.

Therefore, you should be able to map internal parent Get NOT_FOUND to public API child NOT_FOUND.
</blockquote></details>

My understanding of https://google.aip.dev/211 is that we want to avoid leaking existence of the `ExchangeStep` here to unauthorized callers. Shouldn't we always return PERMISSION_DENIED instead of NOT_FOUND in the internal service?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGCsGY4U-vc5i1KL7O:-MjVp4o97QAYYA7oD0va:bvqb8dd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/523e96cf4efc0d057e588a89e9de764f3d1e8bff/src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

So there's two parts here. Can we require mTLS at the service level rather than the method level? If so, then having this interceptor throw UNAUTHENTICATED when there's no valid client cert (i.e. one with an AKID) is fine, and we just don't install the interceptor for that service. If we instead need to require mTLS at the method level or require it conditionally, we need the interceptor to pass and allow the method impl to throw UNAUTHENTICATED if needed. Note that this latter behavior is correct even in the case where we could put the requirement at the service level. It just requires us to make sure we have the check in every method impl.

The following statements assume that we choose to go with the more flexible second option.

> I thought it would be safer to throw in this case to ensure that if we're trying to access this Context key, the ServerInterceptor is installed.

Sounds like the server interceptor should set the context key to empty list when it doesn't find a client X.509 cert. This way we can still throw when trying to access if it if it's not set.

> Maybe a change we could make is NOT failing with UNAUTHENTICATED when there's some X509 cert without an AKID. WDYT?

Yes, if we assume that not all services that have this interceptor installed require a valid client cert (mTLS) then we would in fact need a way to have it not fail at the interceptor level.
</blockquote></details>

Can we revisit this at a later time when we've thought a little more about how this will be used? The current behavior is good enough for panel matching stuff and before we implement auth more generally we probably need to agree on a design doc.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 97 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjVOwGCBKKfpokyrKuX:-MjVr1-s0o99DRMWyEeb:bksejr3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47b3645becc0932f8a9586eb048862611de73d78/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L97)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

My understanding of https://google.aip.dev/211 is that we want to avoid leaking existence of the `ExchangeStep` here to unauthorized callers. Shouldn't we always return PERMISSION_DENIED instead of NOT_FOUND in the internal service?
</blockquote></details>

Also, I think we need to audit the error codes in all of the panel match APIs because I'm sure a lot of them are wrong. Would it be OK to file a bug for that and submit this as is?

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjGCsGY4U-vc5i1KL7O:-MjW1G2BD1m7mS5h2B4Y:bxknve4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/523e96cf4efc0d057e588a89e9de764f3d1e8bff/src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we revisit this at a later time when we've thought a little more about how this will be used? The current behavior is good enough for panel matching stuff and before we implement auth more generally we probably need to agree on a design doc.
</blockquote></details>

Sure. I had left this disposition as "Discussing".
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 97 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjVOwGCBKKfpokyrKuX:-MjW1pzc483iTMB15Bl0:by26mjv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47b3645becc0932f8a9586eb048862611de73d78/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L97)):*
> My understanding of https://google.aip.dev/211 is that we want to avoid leaking existence of the ExchangeStep here to unauthorized callers.

Ah, good call.

> Also, I think we need to audit the error codes in all of the panel match APIs because I'm sure a lot of them are wrong. Would it be OK to file a bug for that and submit this as is?

Sure.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 97 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/267#-MjVOwGCBKKfpokyrKuX:-MjW3Y7s6itrQDf1FtpG:ba8t6ey) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47b3645becc0932f8a9586eb048862611de73d78/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L97)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> My understanding of https://google.aip.dev/211 is that we want to avoid leaking existence of the ExchangeStep here to unauthorized callers.

Ah, good call.

> Also, I think we need to audit the error codes in all of the panel match APIs because I'm sure a lot of them are wrong. Would it be OK to file a bug for that and submit this as is?

Sure.
</blockquote></details>

DE3 is tracking this now

**Pull request merged**
