### PR TITLE
Output machine-readable data from ResourceSetup.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694)

### CODE REVIEW

**Review by matthewclegg — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`docs/gke/correctness-test.md` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-NCf9wsu2nPsbG3-Grik:-NCf9wsu2nPsbG3-Gril:b-ad0p4q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/720bacec5b214af682f60ebe6195a12b3ccdbc16/docs/gke/correctness-test.md#L132)):*
> ```Markdown
> ```prototext
> # proto-file: wfa/measurement/config/authority_key_to_principal_map.proto
> # proto-message: AuthorityKeyToPrincipalMap
> ```

Consider keeping this as an example.
___
*[`docs/gke/correctness-test.md` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-NCfH7cN9OEBR2HMfBYN:-NCfH7cN9OEBR2HMfBYO:b56mf1f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa22bbcf09d929d86dfa2dd04d11bab7a22cc612/docs/gke/correctness-test.md#L132)):*
> ```Markdown
> `authority_key_identifier_to_principal_map.textproto` file with entries for each
> of the test EDPs, using the AKIDs from the test certificates in
> [secretfiles](../../src/main/k8s/testing/secretfiles). You can copy this file
> ```

Since the resource setup job runs in kubernetes, I assume its output will be written somewhere in the local filesystem of the pod where it runs.  If this is so, then won't the user need to copy the output file from the kubernetes pod to their local machine so that the `kubectl create configmap` command will be able to find it?  If so, could you please add an example of the command that would be used for copying it out of the kubernetes pod? 

It would be really cool if resource setup up could do the configmap update itself.
___
*[`docs/operations/creating-resources.md` line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-NCfAGAk4eH7FmHVDeK_:-NCfAGAk4eH7FmHVDeKa:bnbih6u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa22bbcf09d929d86dfa2dd04d11bab7a22cc612/docs/operations/creating-resources.md#L71)):*
> ```Markdown
> identifies that principal. The AKID is common represented as a series of bytes
> in hexadecimal. Byte literals in protobuf text format can be represented by the
> `\x` escape sequence followed by the two-digit hex value.
> ```

Include an example of the file.
___
*[`src/main/k8s/local/README.md` line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-NCfKgwhCA9_DmeqcLaj:-NCfKgwhCA9_DmeqcLak:b-g8aw72) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa22bbcf09d929d86dfa2dd04d11bab7a22cc612/src/main/k8s/local/README.md#L100)):*
> ```Markdown
> update the `config-files` ConfigMap.
> 
> The resource setup job will output an
> ```

Where will the file be located?  As above, does it need to be copied out of a kubernetes pod?  If so, give instructions on how to do so.
___
*[`src/main/k8s/local/README.md` line 159 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-NCfAeJvBQo8hdFr6FHS:-NCfAeJvBQo8hdFr6FHT:bs70q1l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/720bacec5b214af682f60ebe6195a12b3ccdbc16/src/main/k8s/local/README.md#L159)):*
> ```Markdown
> ```
> 
> ## Re-deploy Kingdom
> ```

Is this obsolete?  This seems like helpful advice.  If it is still applicable, I would leave it in.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/Output.kt` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-NCfCK3a83aZ7CiFUQ1O:-NCfCK3a83aZ7CiFUQ1P:b-ptqj9p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa22bbcf09d929d86dfa2dd04d11bab7a22cc612/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/Output.kt#L22)):*
> ```Kotlin
> import java.io.File
> 
> internal sealed interface Output {
> ```

Please add some comments explaining the intended use of the classes in this file.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694)* status: 10 of 12 files reviewed, 6 unresolved discussions (waiting on @matthewclegg)

___
*[`docs/gke/correctness-test.md` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-NCfH7cN9OEBR2HMfBYN:-NCusvT-2z9KdgVP7xht:b-rjmfjb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa22bbcf09d929d86dfa2dd04d11bab7a22cc612/docs/gke/correctness-test.md#L132)):*
> It would be really cool if resource setup up could do the configmap update itself.

`ConfigMap`s are always mounted as read-only and therefore cannot be updated by a pod. See https://github.com/kubernetes/kubernetes/issues/62099

> Since the resource setup job runs in kubernetes, I assume its output will be written somewhere in the local filesystem of the pod where it runs. If this is so, then won't the user need to copy the output file from the kubernetes pod to their local machine

This actually outputs to stdout by default. There's an option to output to a file system directory instead (`--output-dir`), but that's up to a user to decide if they want to use and leaves it up to them how they want to mount a file system and get the files. (We can't just use an emptydir as those require a running pod to access, and K8s Jobs are specifically for workloads that eventually complete.)
___
*[`docs/gke/correctness-test.md` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-NCf9wsu2nPsbG3-Grik:-NCux1RC8Bu_Ozh_9P40:b-6uo87v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/720bacec5b214af682f60ebe6195a12b3ccdbc16/docs/gke/correctness-test.md#L132)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Consider keeping this as an example.
</blockquote></details>

Added to creating-resources.md, which is linked below this.
___
*[`docs/operations/creating-resources.md` line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-NCfAGAk4eH7FmHVDeK_:-NCuyURqCmOKRIjT2Sms:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa22bbcf09d929d86dfa2dd04d11bab7a22cc612/docs/operations/creating-resources.md#L71)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Include an example of the file.
</blockquote></details>

Done.
___
*[`src/main/k8s/local/README.md` line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-NCfKgwhCA9_DmeqcLaj:-NCuzCWP0VXmionqJeZR:bjqbw0v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa22bbcf09d929d86dfa2dd04d11bab7a22cc612/src/main/k8s/local/README.md#L100)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Where will the file be located?  As above, does it need to be copied out of a kubernetes pod?  If so, give instructions on how to do so.
</blockquote></details>

Added a note that all resource setup output is written to STDOUT by default.
___
*[`src/main/k8s/local/README.md` line 159 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-NCfAeJvBQo8hdFr6FHS:-NCuzVb97FYWlXrQ4Fwt:bmwkiah) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/720bacec5b214af682f60ebe6195a12b3ccdbc16/src/main/k8s/local/README.md#L159)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Is this obsolete?  This seems like helpful advice.  If it is still applicable, I would leave it in.
</blockquote></details>

The reader shouldn't need to do this as part of running the correctness test. Having it here turned out to be more likely to result in people blindly assuming that this was a step to follow and redeploying the whole Kingdom unconditionally.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/Output.kt` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-NCfCK3a83aZ7CiFUQ1O:-NCv0SmwD_gQYxV75oND:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa22bbcf09d929d86dfa2dd04d11bab7a22cc612/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/Output.kt#L22)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Please add some comments explaining the intended use of the classes in this file.
</blockquote></details>

Done.

**Review by matthewclegg — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by duliomatos1 — APPROVED** [review]
:lgtm_strong: 

> Reviewed 7 of 12 files at r1, 3 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694#-:-ND4p96h8TY20BBlBVON:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
