### PR TITLE
Add k8s files for reporting v2 deployment

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/k8s/local/BUILD.bazel` line 252 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118#-N_oPHrl3XJIsRLUmWT6:-N_oPHrl3XJIsRLUmWT7:b-zb79l5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a087cbf572066535a77cf09a82950d7f9ab317d4/src/main/k8s/local/BUILD.bazel#L252)):*
> ```Starlark
>         "empty_akid_mapping_config.textproto",
>         "empty_encryption_key_pair_config.textproto",
>         "empty_metric_spec_config.textproto",
> ```

I don't think you need an empty one here, as MetricSpecConfig doesn't reference any resource names.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`docs/gke/reporting-v2-server-deployment.md` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118#-N_oJi4t84GlrqTE2Fxd:-N_ojhbaEu3SSKj2ogEz:b-7hqz7h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e26adf9158775bcce7b7c1ba8e5f9f8061ea44/docs/gke/reporting-v2-server-deployment.md#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What is left for Reporting v2? Is it basically ready? If so, I think we should rename the v1 guide to `reporting-v1-server-deployment.md` and put this guide at `reporting-server-deployment.md`.

Regardless, we should add a note at the top of the v1 guide to indicate that it's for an older version of the Reporting system and link to the v2 guide. Similarly, we should add a note to the top of the v2 guide to highlight that it's for v2 and add a link for anyone looking for the older v1.
</blockquote></details>

It is basically ready. It can be deployed with this PR and https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1116 adds the CLI tool for testing it out.
___
*[`docs/gke/reporting-v2-server-deployment.md` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118#-N_oO3X51fBqLNHzoPyg:-N_okfp09LlMM4Nr2qoY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e26adf9158775bcce7b7c1ba8e5f9f8061ea44/docs/gke/reporting-v2-server-deployment.md#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The dev K8s config appears to be hard-coded to use `reporting-v2`
</blockquote></details>

Done.
___
*[`src/main/k8s/local/BUILD.bazel` line 252 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118#-N_oPHrl3XJIsRLUmWT6:-N_ol0aH-lTqFrHkYEOC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e26adf9158775bcce7b7c1ba8e5f9f8061ea44/src/main/k8s/local/BUILD.bazel#L252)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think you need an empty one here, as MetricSpecConfig doesn't reference any resource names.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/k8s/local/BUILD.bazel` line 252 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118#-N_oPHrl3XJIsRLUmWT6:-N_pfCgL-ZAhu_StiADS:b-anb0rq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e26adf9158775bcce7b7c1ba8e5f9f8061ea44/src/main/k8s/local/BUILD.bazel#L252)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, what I meant is that you can use the real one instead of an empty one since it can be known before resource setup.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/local/BUILD.bazel` line 252 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118#-N_oPHrl3XJIsRLUmWT6:-N_puPYF-qDb_M7g2P9E:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e26adf9158775bcce7b7c1ba8e5f9f8061ea44/src/main/k8s/local/BUILD.bazel#L252)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, what I meant is that you can use the real one instead of an empty one since it can be known before resource setup.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 7 of 12 files at r1, 2 of 2 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
