### PR TITLE
Temporarily disable correctness test in Build and test workflow.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/807)

### CODE REVIEW

**Comment by SanjayVas** [comment]
See #805. While this is disabled, PR authors should verify that the correctness test passes locally before merging.

CC @kungfucraig

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/807)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`.github/workflows/build-test.yml` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/807#-NLXrzng9L_BXR0PPnNB:-NLXrzng9L_BXR0PPnNC:b-l98wdw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6184fb99fa02e25c15d66c12a86dabb341471822/.github/workflows/build-test.yml#L44)):*
> ```YAML
>             --host_platform=//build/platforms:ubuntu_20_04
> 
>       - name: Bazel build and test K8s Correctness Test
> ```

i'd slightly prefer you just comment it out with a comment to re-enable later

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/807)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[`.github/workflows/build-test.yml` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/807#-NLXrzng9L_BXR0PPnNB:-NLXuqNm1J3-T4EO9peR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6184fb99fa02e25c15d66c12a86dabb341471822/.github/workflows/build-test.yml#L44)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'd slightly prefer you just comment it out with a comment to re-enable later
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/807)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
