### PR TITLE
Update cross-media-measurement-api dep for CustomMaximumFrequencyPerUser in DeterministicCount methodology

### PR DESCRIPTION
**Pull request by iverson52000**
For API change in https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/197

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1462)

**Review by SanjayVas — COMMENTED** [review]
Shouldn't this also be updating the variance calculation?

> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1462#-:-Nrq6dKW32xzkNQCe9H9:b-df0p97)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by iverson52000 — COMMENTED** [review]
From what I know, we will be using the same variance formula as McSpecifiedCap with CustomMaximumFrequencyPerUser when they are both using DeterministicCount methodology

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1462#-:-NrqAzSeC13329lIgQBk:b-50bbf2)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
Yes, but that needs to happen in this PR.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1462#-:-NrqG4ol4tn5syxBBrrW:bcp2an9)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1462)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Review by iverson52000 — COMMENTED** [review]
Done. Updated variance calculation.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1462#-:-NrqmJnxAdEw4udtnsAj:bswodjq)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
CC @riemanli 

> Reviewed 1 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1462#-:-Nrr1LwD27YS0b3lV7G5:b-1ptkxa)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1462)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Review by iverson52000 — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1462)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1462)* status: all files reviewed, 1 unresolved discussion

___
*[`MODULE.bazel` line 139 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1462#-NsA_0gQA8s8CG1DzuiL:-NsA_0gQA8s8CG1DzuiM:b5obwjr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ac7ec4e2a3b877a0c35bbb187864b600a77f3d2/MODULE.bazel#L139)):*
> ```Starlark
> bazel_dep(
>     name = "cross-media-measurement-api",
>     version = "0.60.0",
> ```

This jumped straight from 0.58.0 to 0.60.0 without waiting for the intervening PR to handle the changes for 0.59.0. CC @renjiezh

**Pull request merged**
