### PR TITLE
Add listReportingSets

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #985** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/985" target="_blank">Graphite</a> 
    * **PR #992** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/992" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/992?utm_source=stack-comment).

**Review by jcorilla — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt` line 889 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992#-NV6nFHl4uTsOF1JFfxR:-NV6nFHl4uTsOF1JFfxS:b-m6snse) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f01ea1c2302385e8ef0adbd014dba93b5c2348c4/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt#L889)):*
> ```Kotlin
>       }
> 
>     val expected = listReportingSetsResponse {
> ```

Should expected not have a nextPageToken?

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt` line 889 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992#-NV6nFHl4uTsOF1JFfxR:-NV6xBeJ2q1gUh-MGDfU:b40jrgb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f01ea1c2302385e8ef0adbd014dba93b5c2348c4/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt#L889)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

Should expected not have a nextPageToken?
</blockquote></details>

No, it shouldn't. Only when there is any reporting set left. See the corresponding code [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/riemanli_v2alpha_list_reporting_sets/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt#L358).

**Review by jcorilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt` line 889 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992#-NV6nFHl4uTsOF1JFfxR:-NVAd9901YJNI2b3t0Hi:bhex3fq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f01ea1c2302385e8ef0adbd014dba93b5c2348c4/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt#L889)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

No, it shouldn't. Only when there is any reporting set left. See the corresponding code [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/riemanli_v2alpha_list_reporting_sets/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt#L358).
</blockquote></details>

Got it, renaming this test might clarify that there shouldn't be a next page token

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt` line 889 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992#-NV6nFHl4uTsOF1JFfxR:-NVAwVKo8Zrfosq9r_M_:b-4jnr0o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f01ea1c2302385e8ef0adbd014dba93b5c2348c4/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt#L889)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

Got it, renaming this test might clarify that there shouldn't be a next page token
</blockquote></details>

Oh thanks for catching that. I forgot to rename the unit test. Done.

**Review by jcorilla — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by Marco-Premier — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt` line 334 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992#-NVVD6dr1SywyhVXOQQO:-NVVD6dr1SywyhVXOQQP:b-39xvgw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10f3d5f9f413dce330cbbab7e4aff62b627856ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt#L334)):*
> ```Kotlin
> 
>     when (val principal: ReportingPrincipal = principalFromCurrentContext) {
>       is MeasurementConsumerPrincipal -> {
> ```

Can DataProviderPrincipal / ModelProviderPrincipal and others access this resource?



_Code quote:_
```Kotlin
is MeasurementConsumerPrincipal -> {
```

**Review by tristanvuong2021 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt` line 334 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992#-NVVD6dr1SywyhVXOQQO:-NVVGMVk4Hhi4YzOpRtN:b-31y4ii) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10f3d5f9f413dce330cbbab7e4aff62b627856ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt#L334)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Can DataProviderPrincipal / ModelProviderPrincipal and others access this resource?
</blockquote></details>

Right now ReportingPrincipal only has a MeasurementConsumerPrincipal.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt` line 334 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992#-NVVD6dr1SywyhVXOQQO:-NVVR7Gr3A5KRNXXqhsw:bpz8gpr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10f3d5f9f413dce330cbbab7e4aff62b627856ba/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt#L334)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Right now ReportingPrincipal only has a MeasurementConsumerPrincipal.
</blockquote></details>

Got it. thanks

**Review by riemanli — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)

**Review by riemanli — COMMENTED** [review]
> Dismissed @Marco-Premier from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/992)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Pull request merged**
