### PR TITLE
Add YouTube QA EDP root cert to testing trusted cert collections.

### PR DESCRIPTION
**Pull request by SanjayVas**
This allows the YouTube QA EDP to integrate with Halo testing environments.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/testing/secretfiles/youtube_qa_edp_root.pem` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581#-Nvs3PbzD5Nc_aoSWIgx:-Nvs3PbzD5Nc_aoSWIgy:bu8s3os) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4769a293e26bb7b1a04a8b08ceb2332b74a7a5b1/src/main/k8s/testing/secretfiles/youtube_qa_edp_root.pem#L1)):*
> ```
> -----BEGIN CERTIFICATE-----
> ```

hmmm.... i'm not sure I love this model. this would mean any EDP that wants to do QA testing would need to push their root cert here? I don't love this process. What other options do we have? 
1. What you have here
2. You could use a known EDP private/public that anyone could use
3. ??

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/k8s/testing/secretfiles/youtube_qa_edp_root.pem` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581#-Nvs3PbzD5Nc_aoSWIgx:-Nvs9yAM6m6wH7Ohgr88:b-1fs57b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4769a293e26bb7b1a04a8b08ceb2332b74a7a5b1/src/main/k8s/testing/secretfiles/youtube_qa_edp_root.pem#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

hmmm.... i'm not sure I love this model. this would mean any EDP that wants to do QA testing would need to push their root cert here? I don't love this process. What other options do we have? 
1. What you have here
2. You could use a known EDP private/public that anyone could use
3. ??
</blockquote></details>

This was covered in https://docs.google.com/document/d/1xnvesQ8b6hJk5DPa5b0Tm0f_cge5yTUKIQ2Rf9qVkqw/edit?usp=sharing, which was shared on March 5.

Option 2 has the issue that everyone has access to the private key. The cert should uniquely identify a known EDP integrator that no other integrator can impersonate. Therefore the only option is to use a root cert where only that integrator has the private key, ideally using a managed CA service such that the key material cannot be exfiltrated from a KMS.

Note that additionally, someone with internal API access to the Halo QA Kingdom would also have to provision the DataProvider resource. Anyone with that access would be a Halo engineer with write access to the repository.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/k8s/testing/secretfiles/youtube_qa_edp_root.pem` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581#-Nvs3PbzD5Nc_aoSWIgx:-NvsC4HB2E_whyNBLjTg:bec0ohr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4769a293e26bb7b1a04a8b08ceb2332b74a7a5b1/src/main/k8s/testing/secretfiles/youtube_qa_edp_root.pem#L1)):*
> The cert should uniquely identify a known EDP integrator that no other integrator can impersonate.

To clarify, this is for cross-EDP testing. Whomever is running a test needs to know which real EDP integrators are included in the test.

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/k8s/testing/secretfiles/youtube_qa_edp_root.pem` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581#-Nvs3PbzD5Nc_aoSWIgx:-NvsHHv-5bv99eEWJUgw:b122vgk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4769a293e26bb7b1a04a8b08ceb2332b74a7a5b1/src/main/k8s/testing/secretfiles/youtube_qa_edp_root.pem#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> The cert should uniquely identify a known EDP integrator that no other integrator can impersonate.

To clarify, this is for cross-EDP testing. Whomever is running a test needs to know which real EDP integrators are included in the test.
</blockquote></details>

Can we run with this for now? The cert is public.

This may not be perfect but it's not bad.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @kungfucraig)

___
*[`src/main/k8s/testing/secretfiles/youtube_qa_edp_root.pem` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581#-Nvs3PbzD5Nc_aoSWIgx:-NvsgzMu3OkTDB8VVXMD:byvo1fs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4769a293e26bb7b1a04a8b08ceb2332b74a7a5b1/src/main/k8s/testing/secretfiles/youtube_qa_edp_root.pem#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can we run with this for now? The cert is public.

This may not be perfect but it's not bad.
</blockquote></details>

approving to unblock but we should revisit this. Maybe there's a 3rd option we can talk about later.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1581)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
