### PR TITLE
Fix always-true conditional check in SpannerDataProviderService

### PR DESCRIPTION
**Pull request by Marco-Premier**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/986)

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/986)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jojijac0b, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/986#-NV00Oxi4VQdFDt-_aVp:-NV07A1U2_lHUj9waV1d:bpuebkd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca746921c4176e0461745212c5888c35ce339f43/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt#L57)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Should be != in case in the future we want to allow negatives and this wouldn't silently break.
</blockquote></details>

That's interesting, thanks

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/986)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/986)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Pull request merged**
