### PR TITLE
Create PanelMatchResourceSetup from Channels

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/298)

### CODE REVIEW

**Comment by yunyeng** [comment]
Created #295
Reverted #295 on #297 for not having external reviewers
Recreated #298

**Review by wangyaopw — APPROVED** [review]

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/298)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1, @oliver-amzn, and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/298)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/298)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
