### PR TITLE
Update protcolConfig proto in the kingdom.

### PR DESCRIPTION
**Pull request by wangyaopw**
The protocol_metadata is dead code never used.

https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Fuserstory%2F606023914123%2Ftasks&view=2c2927c0-626b-4740-8620-af2a93b7d623

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
Please LGTM the proto change first, then I'll fix all usages.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-:-Mi8uJqI2y_J1nrRE1F-:b9d16zh)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @kungfucraig and @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
:lgtm: for proto changes

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-:-Mi90MuPDAo4SFEqWnSe:bg89oth)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Comment by wangyaopw** [comment]
Please review the proto change again, it is changed significantly.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement.proto, line 112 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiTclnM8bCe-4zg03Q0:-MiTclnM8bCe-4zg03Q1:bvarrck) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2e999a3f1090686135b8818b83f002cd63158b63/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L112)):*
> ```protobuf
>     DuchyProtocolConfig duchy_protocol_config = 6;
>     // The protocol config used in this measurement.
>     ProtocolConfig protocol_config = 7;
> ```

super nit: should probably be before DuchyProtocolConfig
___
*[src/main/proto/wfa/measurement/system/v1alpha/computation.proto, line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiTdK8Q5fWoMcCkWTdE:-MiTdK8Q5fWoMcCkWTdF:b1pntdn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2e999a3f1090686135b8818b83f002cd63158b63/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L104)):*
> ```
>   // The config contains information from both the kingdom internal
>   // `DuchyProtocolConfig` and public API `ProtocolConfig`.
> ```
nit: Shouldn't mention this implementation detail here, since this API is independent of the internal one.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235)* status: 4 of 43 files reviewed, all discussions resolved (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement.proto, line 112 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiTclnM8bCe-4zg03Q0:-MiVT0QxDj9Fw8fS_77Q:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2e999a3f1090686135b8818b83f002cd63158b63/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L112)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

super nit: should probably be before DuchyProtocolConfig
</blockquote></details>

Done
___
*[src/main/proto/wfa/measurement/system/v1alpha/computation.proto, line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiTdK8Q5fWoMcCkWTdE:-MiVT4v03F4C3y9nwnua:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2e999a3f1090686135b8818b83f002cd63158b63/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>   // The config contains information from both the kingdom internal
>   // `DuchyProtocolConfig` and public API `ProtocolConfig`.
> ```
nit: Shouldn't mention this implementation detail here, since this API is independent of the internal one.
</blockquote></details>

Done

**Review by wangyaopw — COMMENTED** [review]
The kotlin codes are fixed now. PTAL

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-:-MiVTVSG47ClD_7X7FRl:bvuk82i)* status: 4 of 43 files reviewed, all discussions resolved (waiting on @kungfucraig and @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 39 of 39 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235)* status: all files reviewed, 5 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/k8s/configs/llv2_protocol_config_config.textproto, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiXKO-V5o34o07YIy1h:-MiXKO-WAvS-QYo3ZIbc:bs2uzec) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e54f7b5095e47d76d38c679aae443d123005e1e3/src/main/k8s/configs/llv2_protocol_config_config.textproto#L1)):*
> ```
> # proto-file: src/main/proto/wfa/measurement/internal/kingdom/llv2_protocol_config_config.proto
> ```

Ah, I had expected the config file to be for all of the possible configs for all protocols rather than a single config for a single protocol. This way ends up with a separate config param per protocol, which is fine if we expect a small number of protocols and to just hard-code the config for that protocol for a given deployment.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiXRvdrEdhtuiqR15fv:-MiXRvdrEdhtuiqR15fw:ba866g8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e54f7b5095e47d76d38c679aae443d123005e1e3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L39)):*
> ```Kotlin
> 
> /**
>  * The protocol_config_id column in the measurement table in not used in current design yet. Set the
> ```

Would it be easy to just drop the column in this PR, or is that a lot of separate work?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, line 247 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiXU-B686JUP7irKnTA:-MiXU-B686JUP7irKnTB:b-aky5gr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e54f7b5095e47d76d38c679aae443d123005e1e3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel#L247)):*
> ```Starlark
>         "//src/main/proto/wfa/measurement/internal/kingdom:protocol_config_kt_jvm_proto",
>         "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common/identity",
>     ],
> ```

Mark this with private visibility
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, line 191 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiXUm5vDzkpvTRzDjGu:-MiXUm5vDzkpvTRzDjGv:b-q3ub4j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e54f7b5095e47d76d38c679aae443d123005e1e3/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt#L191)):*
> ```
> /** Converts a kingdom internal Requisition.State to system Api Requisition.State. *
> ```
Incorrect comment
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt, line 192 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiXQw943OSIz0GMpnD0:-MiXQw943OSIz0GMpnD1:b-uq6ah7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e54f7b5095e47d76d38c679aae443d123005e1e3/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt#L192)):*
> ```
> : InternalMeasurement
> ```
optional: While it's never wrong to specify the type explicitly, it is a little redundant in cases like this where the type is basically mentioned thrice :stuck_out_tongue:

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/k8s/configs/llv2_protocol_config_config.textproto, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiXKO-V5o34o07YIy1h:-MiXadwK0T5Bv2fzA7hq:bvlvrw5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e54f7b5095e47d76d38c679aae443d123005e1e3/src/main/k8s/configs/llv2_protocol_config_config.textproto#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, I had expected the config file to be for all of the possible configs for all protocols rather than a single config for a single protocol. This way ends up with a separate config param per protocol, which is fine if we expect a small number of protocols and to just hard-code the config for that protocol for a given deployment.
</blockquote></details>

Let's revisit this when we have a second protocol. Should be easy to refactor at that time.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiXRvdrEdhtuiqR15fv:-MiXap5rDEt9ZbdAXgdO:bjtrvkk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e54f7b5095e47d76d38c679aae443d123005e1e3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Would it be easy to just drop the column in this PR, or is that a lot of separate work?
</blockquote></details>

Should be easy to drop it now.

I am wondering if it is hard to add it back in the future when we really have a protocolConfig resource.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, line 247 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiXU-B686JUP7irKnTA:-MiXbVX702vMBixa9qfA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e54f7b5095e47d76d38c679aae443d123005e1e3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel#L247)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Mark this with private visibility
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, line 191 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiXUm5vDzkpvTRzDjGu:-MiXcH0MDb-cJ8Gpi0gZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e54f7b5095e47d76d38c679aae443d123005e1e3/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt#L191)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> /** Converts a kingdom internal Requisition.State to system Api Requisition.State. *
> ```
Incorrect comment
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt, line 192 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiXQw943OSIz0GMpnD0:-MiXaIk-E1vbmeVdBtR-:b-sgd7o8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e54f7b5095e47d76d38c679aae443d123005e1e3/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt#L192)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> : InternalMeasurement
> ```
optional: While it's never wrong to specify the type explicitly, it is a little redundant in cases like this where the type is basically mentioned thrice :stuck_out_tongue: 
</blockquote></details>

ha, sure, I definitely wouldn't do it this way. This part is copy/pasted.

Done

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiXRvdrEdhtuiqR15fv:-MiXoIho0n5omyeHh873:b-d5bd30) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e54f7b5095e47d76d38c679aae443d123005e1e3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L39)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Should be easy to drop it now.

I am wondering if it is hard to add it back in the future when we really have a protocolConfig resource.
</blockquote></details>

I'm not sure we will have such a resource. If so, we can deal with it then. Unless we actually fill the IDs now, there'd need to be a data backfill either way.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235)* status: 44 of 46 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235#-MiXRvdrEdhtuiqR15fv:-MiXqqNQ6FisgTF62zwt:bdq5asx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e54f7b5095e47d76d38c679aae443d123005e1e3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not sure we will have such a resource. If so, we can deal with it then. Unless we actually fill the IDs now, there'd need to be a data backfill either way.
</blockquote></details>

Deleted this column in the measurement table.

It is not used anywhere, so just several lines of change to drop it.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 2 of 39 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 39 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 4 files at r2, 34 of 39 files at r3, 6 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
