### PR TITLE
Allow SyntheticGenerator to be used for correctness test on GKE.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1127)

**Comment by SanjayVas** [comment]
Current PR stack:

* #1128 
* #1127 <-- This PR
* #1112 <-- Base PR

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
