### PR TITLE
Rearrange joins on ComputationParticipantReader.

### PR DESCRIPTION
**Pull request by SanjayVas**
This is to reduce the number of table rows scanned. Spanner Query Insights on QA showed an average latency of ~300ms and average rows scanned of ~4162.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/847)

### CODE REVIEW

**Comment by SanjayVas** [comment]
[queryPlanBefore.json.txt](https://github.com/world-federation-of-advertisers/cross-media-measurement/files/10679914/queryPlanBefore.json.txt)
[queryPlanAfter.json.txt](https://github.com/world-federation-of-advertisers/cross-media-measurement/files/10679915/queryPlanAfter.json.txt)

**Review by Marco-Premier — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/847#-:-NNqKya177FLleVFCxLu:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/847)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/847)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
