### PR TITLE
Use structured logging for all Java Containers on GKE.

### LINKED ISSUE #762: Use structured logging for Google Cloud Logging
All Halo's logging is captured as ERROR by the GCP log tooling. This makes debugging complicated and hard to understand what is going on

- [ ] https://github.com/world-federation-of-advertisers/common-jvm/pull/220
- [ ] #1332

### PR DESCRIPTION
**Pull request by SanjayVas**
Closes #762

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1332)

**Comment by SanjayVas** [comment]
Depends on world-federation-of-advertisers/common-jvm#220

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1332)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`build/repositories.bzl` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1332#-NjMBbMe81ZdP7ldrV4h:-NjMBbMe81ZdP7ldrV4i:br57kje) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b0a4261c80cc143cae3f2ddcd49e2fc31bee7c91/build/repositories.bzl#L29)):*
> ```Starlark
>     wfa_repo_archive(
>         name = "wfa_common_jvm",
>         # DO_NOT_SUBMIT(world-federation-of-advertisers/common-jvm#220): Use version.
> ```

nit is this a reminder not to submit this?



_Code quote:_
```Starlark
# DO_NOT_SUBMIT(world-federation-of-advertisers/common-jvm#220): Use version.
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1332)* status: 34 of 35 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

___
*[`build/repositories.bzl` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1332#-NjMBbMe81ZdP7ldrV4h:-NjO4eTu43agc6bEs-ZV:b-rgguur) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b0a4261c80cc143cae3f2ddcd49e2fc31bee7c91/build/repositories.bzl#L29)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

nit is this a reminder not to submit this?
</blockquote></details>

It's a reminder not to submit (AKA merge) until world-federation-of-advertisers/common-jvm#220 has been merged and a common-jvm release has been cut.

I've done that now.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
