### PR TITLE
Catch KingdomInternalException and throw Grpc errors

### PR DESCRIPTION
**Pull request by renjiezh**
Issue: https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/247

 When a specific resource is not found, use `FAILED_PRECONDITION`, `INVALID_ARGUMENT` or `NOT_FOUND`?

 As `INVALID_ARGUMENT` is more about the format of arguments, avoid to use it in our cases.

 When the major entity is not found, use `NOT_FOUND`. For example, if `getMeasurement` or `updateMeasurement` fail to find the `Measurement`, we call it `NOT_FOUND`.

 Other than the major entity, use `FAILED_PRECONDITION`. For example, for `getMeasurement` or `updateMeasurement`, if `Account`/`MeasurementConsumer`/`Certificate` not found, call it `FAILED_PRECONDITION`.

 

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 43 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559)* status: 3 of 73 files reviewed, 6 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt` line 77 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jy8HDC6tX2otP-utu:-N1jy8HDC6tX2otP-utv:bxa8jnd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L77)):*
> ```Kotlin
>     } catch (e: AccountNotFoundException) {
>       e.throwStatusRuntimeException(Status.NOT_FOUND) {
>         "Creator's Account not found. " + e.contextToString()
> ```

Shouldn't `throwStatusRuntimeException` handle adding the context to the message?



_Code quote:_
```Kotlin
e.contextToString()
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt` line 111 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jv8ax5LevvpLHU0WT:-N1jv8ax5LevvpLHU0WU:b-3o796y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L111)):*
> ```Kotlin
>       }
>     } catch (e: DuplicateAccountIdentityException) {
>       e.throwStatusRuntimeException(Status.INVALID_ARGUMENT) {
> ```

This should be FAILED_PRECONDITION, as it's the system state that makes this an error.



_Suggestion:_
```Kotlin
Status.INVALID_ARGUMENT 
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jvX7a0cikd-YMwyeS:-N1jvX7a0cikd-YMwyeT:b73u9wn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L115)):*
> ```Kotlin
>       }
>     } catch (e: AccountActivationStateIllegalException) {
>       e.throwStatusRuntimeException(Status.PERMISSION_DENIED) {
> ```

`FAILED_PRECONDITION` as well, as the credentials are not the problem.



_Code quote:_
```Kotlin
PERMISSION_DENIED
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt` line 136 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jvwev0cVI1QqwVIys:-N1jvwev0cVI1QqwVIyt:brnb7gh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L136)):*
> ```Kotlin
>         .execute(client, idGenerator)
>     } catch (e: DuplicateAccountIdentityException) {
>       e.throwStatusRuntimeException(Status.INVALID_ARGUMENT) {
> ```

`FAILED_PRECONDITION`



_Code quote:_
```Kotlin
INVALID_ARGUMENT
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt` line 123 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jxY80949LG0pyljqA:-N1jxY80949LG0pyljqB:bm2q1mt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L123)):*
> ```Kotlin
>       "RevokeCertificateRequest is missing parent field"
>     }
>     // TODO(world-federation-of-advertisers/cross-media-measurement#178) : Update fail conditions
> ```

Drop this TODO, as I believe this PR is the one fixing this conditions.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt` line 133 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jxQKS9I7SR-H-DM-G:-N1jxQKS9I7SR-H-DM-H:bihjsmb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L133)):*
> ```Kotlin
>     } catch (e: DuchyNotFoundException) {
>       e.throwStatusRuntimeException(Status.NOT_FOUND) { "Duchy not found. " + e.contextToString() }
>     } catch (e: KingdomInternalException) {
> ```

Does this not also need to handle `CertificateRevocationStateIllegalException`?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559)* status: 0 of 73 files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt` line 77 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jy8HDC6tX2otP-utu:-N1pZZbc8pTXvuAm9_w0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L77)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't `throwStatusRuntimeException` handle adding the context to the message?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt` line 111 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jv8ax5LevvpLHU0WT:-N1pZ_733aK9tDrSh7hJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L111)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be FAILED_PRECONDITION, as it's the system state that makes this an error.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jvX7a0cikd-YMwyeS:-N1pZ_UPDmqgRFQtGf8U:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`FAILED_PRECONDITION` as well, as the credentials are not the problem.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt` line 136 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jvwev0cVI1QqwVIys:-N1pZa6sAazjLFIwT6_N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L136)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`FAILED_PRECONDITION`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt` line 123 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jxY80949LG0pyljqA:-N1pZbaICA99vpE599EJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L123)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop this TODO, as I believe this PR is the one fixing this conditions.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt` line 133 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jxQKS9I7SR-H-DM-G:-N1pZbxN0z1zEodrgl4g:b-evymv6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L133)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does this not also need to handle `CertificateRevocationStateIllegalException`?
</blockquote></details>

RevokeCertificate() does not throw CertificateRevocationStateIllegalException.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 28 of 51 files at r2, 31 of 43 files at r7, 14 of 14 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt` line 123 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jxY80949LG0pyljqA:-N1uHeSl13BA5oAlN4dk:b3xj94w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L123)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see the TODO on this line?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt` line 133 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559#-N1jxQKS9I7SR-H-DM-G:-N1uHsr95H5ySAVTl9Mi:bpj4yxv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5246bcc2b0003394c52fbd03dcaef7d8cf54d577/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L133)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

RevokeCertificate() does not throw CertificateRevocationStateIllegalException.
</blockquote></details>

That sounds like you found a bug, but it can be dealt with in another PR.

e.g. `REVOKED` is a terminal revocation state, so you can't move a certificate from `REVOKED` to `HOLD`.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 3 of 51 files at r2, 6 of 43 files at r7, 11 of 14 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/559)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
