### PR TITLE
Replace timeinterval with rollout deploy period

### PR DESCRIPTION
**Pull request by Marco-Premier**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1091)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1091)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1770 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1091#-NZg9OEz6LM5YYawt05U:-NZg9OEz6LM5YYawt05V:b-a6y3ya) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bed00bddc845023a5ad27f64d474ca9bedf83716/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1770)):*
> ```Kotlin
>   ) {
> 
>     if (instantRolloutTime == null && (rolloutStartTime == null || rolloutEndTime == null)) {
> ```

nit: You might be able to implement this using [Argument Groups](https://picocli.info/#_argument_groups)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1091)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1091)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1770 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1091#-NZg9OEz6LM5YYawt05U:-N_6CVZ04sCT56EWkmTn:b6a8kg1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1533eb8a4f7d0ff9e989f4c6bbcf913a1c027c59/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1770)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: You might be able to implement this using [Argument Groups](https://picocli.info/#_argument_groups)
</blockquote></details>

Nice, don't have capacity today. will fix in following PR. Merging to unlock: [https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1092](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1092)

**Pull request merged**
