### PR TITLE
Prevent creating log entries for terminal Measurements at Kingdom.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by renjiezh** [comment]
https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/857

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/864)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt` line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/864#-NOuGqHjB9nY2qypxUhF:-NOurlR811s4KowMZPh2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e866250b026a7f1dd45559dd6ae62a36218ec63/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These conditions represent a system invariant being violated, and therefore indicate a serious error. We can just use the `error` function here which will result in an IllegalStateException.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/864)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt` line 174 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/864#-NOusDUC-8A6Kzs6Ntux:-NOusDUC-8A6Kzs6Ntuy:b-u3bfg8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1249a1c3bcfab0814436880cf3156942aedc638a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt#L174)):*
> ```Kotlin
>     return transactionContext
>       .executeQuery(
>         Statement.newBuilder(baseSql)
> ```

nit: use `org.wfanet.measurement.gcloud.spanner.statement` DSL builder



_Suggestion:_
```Kotlin
        statement(baseSql) {
          bind("externalComputationId").to(request.externalComputationId)
        }
```

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/864)

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/864)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/864)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
