### PR TITLE
Refactor Report Time

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 5 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: 5 of 29 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report.proto` line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NnuGlj0B-EWdVx6d4fz:-NnuGlj0B-EWdVx6d4g-:bmn9f09) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6681419decf33fdac45363cbf4976bad73b8115/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto#L88)):*
> ```proto
>     map<string, string> tags = 1;
> 
>     message ReportingInterval {
> ```

Why don't we want this in the oneof that was removed?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NnuH81W3huPbW6UXi3-:-NnuH81W3huPbW6UXi30:b-jaapzb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6681419decf33fdac45363cbf4976bad73b8115/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L79)):*
> ```proto
> 
>   // Describes the frequencies at which results are generated.
>   message FrequencySpec {
> ```

ResultFrequencySpec, just to make it stand out from the measurement type Frequency?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NnuHIFP8ZWTWeo5rqRg:-NnuHIFP8ZWTWeo5rqRh:bypbesu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6681419decf33fdac45363cbf4976bad73b8115/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L141)):*
> ```proto
>     }
>   }
>   Window window = 9;
> ```

@SanjayVas What do you think of defaulting the window to the frequency with count=1 if it's not specified? This is likely to be the common use case.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: 4 of 30 files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NnuHIFP8ZWTWeo5rqRg:-Nnuiz-vCOBy7AcwaGgn:bhscmxn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6681419decf33fdac45363cbf4976bad73b8115/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L141)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@SanjayVas What do you think of defaulting the window to the frequency with count=1 if it's not specified? This is likely to be the common use case.
</blockquote></details>

By convention all of our "Spec" messages are immutable. Therefore whatever is in such a field should be explicit, as we can't return the appropriate default for you on creation as that would require mutation.

The alternative would be to document the count field saying the default is assumed to be 1 if not specified, but that's rather messy too. Ideally proto3 definitions should be written in such a way that they work with the true default value of the type (in this case `0`)
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NnuiO7I8jAJW4k8tPCU:-NnuiO7I8jAJW4k8tPCV:bu3dww7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/488d7d38bc9e36191bc8d2c5924efa111bc24e46/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L80)):*
> ```proto
>   // Describes the frequencies at which results are generated.
>   message FrequencySpec {
>     // When Daily is selected the time specified by the report_start field in
> ```

nit: This comment should be for the message type itself. There should be a separate comment on the field in the oneof.

As per the API linter, every type and field must be documented.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: 3 of 31 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NnuH81W3huPbW6UXi3-:-NnyhCkT1tdYtoFEv7xa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6681419decf33fdac45363cbf4976bad73b8115/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L79)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

ResultFrequencySpec, just to make it stand out from the measurement type Frequency?
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: 2 of 32 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @riemanli)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report.proto` line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NnuGlj0B-EWdVx6d4fz:-NnzwVS54hL1Igif_WLd:bi6g419) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6681419decf33fdac45363cbf4976bad73b8115/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto#L88)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why don't we want this in the oneof that was removed?
</blockquote></details>

I added back the oneof, but moved it to details.

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 5 of 29 files at r1, 2 of 17 files at r2, 4 of 15 files at r3, 3 of 7 files at r4, 6 of 10 files at r5, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: 21 of 32 files reviewed, 10 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecsService.kt` line 424 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoUEM2A46yVCQdY-YC2:-NoUEM2A46yVCQdY-YC3:b-gdu4oq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c762968ae25455bdb27d11ecdd17bc83904a61e/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecsService.kt#L424)):*
> ```Kotlin
>             } else {
>               failGrpc { "report_start_time is false" }
>             }
> ```

nit: Equivalent to

```kotlin
grpcRequire(source.reportStartTime) { "report_start_time is false" }
reportStartTime=true
```



_Code quote:_
```Kotlin
            if (source.reportStartTime) {
              reportStartTime = true
            } else {
              failGrpc { "report_start_time is false" }
            }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 519 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoUJIpHBWRFG32yHegL:-NoUJIpHBWRFG32yHegM:b-fqsjnr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c762968ae25455bdb27d11ecdd17bc83904a61e/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L519)):*
> ```Kotlin
>   ): List<Report.MetricCalculationResult> {
>     return internalReportingMetricEntries.flatMap {
>       (reportingSetId, reportingMetricCalculationSpec),
> ```

Is this intentional?



_Code quote:_
```Kotlin
,
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 598 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoUJwxA1YsiKrDbAHQc:-NoUJwxA1YsiKrDbAHQd:b-gn2cio) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c762968ae25455bdb27d11ecdd17bc83904a61e/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L598)):*
> ```Kotlin
>       report = internalReport {
>         @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA")
>         when (request.report.timeCase) {
> ```

nit: it would be more concise to put `when` clause into `details` DSL.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 117 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoT-z3YBS-pmbCS3B5e:-NoT-z3YBS-pmbCS3B5f:bguaham) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c762968ae25455bdb27d11ecdd17bc83904a61e/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L117)):*
> ```proto
>   ResultFrequencySpec result_frequency_spec = 8;
> 
>   message Window {
> ```

nit: As per the API linter, every type and field must be documented.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 133 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoUD_Bl9JKwTaulvPkZ:-NoUD_Bl9JKwTaulvPk_:b7mza15) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c762968ae25455bdb27d11ecdd17bc83904a61e/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L133)):*
> ```proto
> 
>     // How far back the Metrics at each period (as defined by
>     // `result_frequency_spec) cover. Required.
> ```

Extra backtick or missing one?



_Code quote:_
```proto
`
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 134 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoT_Sz7Beuy7na7TyTl:-NoT_Sz7Beuy7na7TyTm:b-u97q2y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c762968ae25455bdb27d11ecdd17bc83904a61e/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L134)):*
> ```proto
>     // How far back the Metrics at each period (as defined by
>     // `result_frequency_spec) cover. Required.
>     oneof window {
> ```

I know it's mentioned in `Report`, but maybe mentioning again that a window cannot be earlier than `ReportingInterval.reportStart` would be more clear ?



_Code quote:_
```proto
    // How far back the Metrics at each period (as defined by
    // `result_frequency_spec) cover. Required.
    oneof window {
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 142 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoT4HlQ4JYrPQGXxv2X:-NoT4HlQ4JYrPQGXxv2Y:bkosvym) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c762968ae25455bdb27d11ecdd17bc83904a61e/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L142)):*
> ```proto
>     }
>   }
>   Window window = 9;
> ```

1. What's the reason to wrap the oneof with a message?
2. When I read the implementation, sometimes I got confused by the case where only `ResultFrequencySpec` is checked due to the assumption that `Window` is always along with. Since `ResultFrequencySpec` and `Window` have to be set at the same time, why not wrap them together with another message? It will be less confusing and no hidden logic.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: 17 of 32 files reviewed, 7 unresolved discussions (waiting on @kungfucraig and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 519 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoUJIpHBWRFG32yHegL:-NoXUxOn98bK1CWD6Ogm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c762968ae25455bdb27d11ecdd17bc83904a61e/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L519)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Is this intentional?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NnuHIFP8ZWTWeo5rqRg:-NoXWN2hDbTlCp6TkOUP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6681419decf33fdac45363cbf4976bad73b8115/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

By convention all of our "Spec" messages are immutable. Therefore whatever is in such a field should be explicit, as we can't return the appropriate default for you on creation as that would require mutation.

The alternative would be to document the count field saying the default is assumed to be 1 if not specified, but that's rather messy too. Ideally proto3 definitions should be written in such a way that they work with the true default value of the type (in this case `0`)
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 133 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoUD_Bl9JKwTaulvPkZ:-NoXVz16AEfVmyYxJ01C:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c762968ae25455bdb27d11ecdd17bc83904a61e/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L133)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Extra backtick or missing one?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 134 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoT_Sz7Beuy7na7TyTl:-NoXZ6SL8DK34qflAwds:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c762968ae25455bdb27d11ecdd17bc83904a61e/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L134)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I know it's mentioned in `Report`, but maybe mentioning again that a window cannot be earlier than `ReportingInterval.reportStart` would be more clear ?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 142 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoT4HlQ4JYrPQGXxv2X:-NoXjkt18H52Khs_q89j:b2au5tg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c762968ae25455bdb27d11ecdd17bc83904a61e/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L142)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

1. What's the reason to wrap the oneof with a message?
2. When I read the implementation, sometimes I got confused by the case where only `ResultFrequencySpec` is checked due to the assumption that `Window` is always along with. Since `ResultFrequencySpec` and `Window` have to be set at the same time, why not wrap them together with another message? It will be less confusing and no hidden logic.
</blockquote></details>

1. It is not just the oneof, but the sub messages are wrapped too. The sub messages are only used in the oneof so it makes sense to group them together.
2. Done

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: 17 of 32 files reviewed, 9 unresolved discussions (waiting on @kungfucraig, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 134 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoY5gSJ9T1FW6hX5xme:-NoY5gSK779vhOxMAgkQ:b-4eznql) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56e041acea5c6485e0f20e99db30398f836c4e96/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L134)):*
> ```proto
>     // `metric_frequency_spec`) cover. The time covered is lower bounded by
>     // `ReportingInterval.report_start`. Required.
>     oneof window {
> ```

This oneof is unnecessary. Just indicate that if the window is not specified then it's assumed that it starts from `report_start`.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 143 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoY8nB00jq_8mPO8SeC:-NoY8nB00jq_8mPO8SeD:b-bs86ar) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56e041acea5c6485e0f20e99db30398f836c4e96/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L143)):*
> ```proto
>   }
> 
>   message MetricFrequencySpecAndWindow {
> ```

nit: avoid "And" in names when you can come up with a better one. Though if you follow my advice above, I think you can just have separate MetricFrequencySpec and TrailingWindow fields.



_Suggestion:_
```proto
WindowedMetricFrequencySpec
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: 17 of 32 files reviewed, 8 unresolved discussions (waiting on @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 134 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoY5gSJ9T1FW6hX5xme:-NoYUVJW7RwLKRfBolez:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56e041acea5c6485e0f20e99db30398f836c4e96/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L134)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This oneof is unnecessary. Just indicate that if the window is not specified then it's assumed that it starts from `report_start`.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: 18 of 32 files reviewed, 9 unresolved discussions (waiting on @kungfucraig, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 115 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoYW2w-5Q2bmNFthz9V:-NoYW2w-5Q2bmNFthz9W:b-2xxucf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/294d13266c17376a28a9c07d06dc027520cb9b9f/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L115)):*
> ```proto
>   }
>   MetricFrequencySpec metric_frequency_spec = 8
>       [(google.api.field_behavior) = IMMUTABLE];
> ```

Need field documentation. Note that since this field is not required the documentation should be clear on what the behavior is when it is or isn't specified.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 133 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoYVLgN7AEqo-5fRH8T:-NoYVLgN7AEqo-5fRH8U:bj3bskx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/294d13266c17376a28a9c07d06dc027520cb9b9f/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L133)):*
> ```proto
>     Increment increment = 2 [(google.api.field_behavior) = REQUIRED];
>   }
>   // If not set, metrics will start from `ReportingInterval.report_start`. If
> ```

nit: incorrect format for field documentation. This should start with a summary fragment describing the field itself.

e.g. on the TrailingWindow message: "The trailing window for a `MetricCalculationSpec`, indicating how far back..." and on the trailing_window field "The trailing window for this `MetricCalculationSpec`. The time covered is bounded by... If not specified..."

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: 17 of 32 files reviewed, 9 unresolved discussions (waiting on @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt` line 438 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoYmF6JELfRHVpKe7Iy:-NoYztvRB2fCkm6k4W8a:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/294d13266c17376a28a9c07d06dc027520cb9b9f/src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt#L438)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is misleading as there is both a Timestamp and a DateTime. We need some way to avoid confusion given that there are two sources of info for the time, but only one is being used. Perhaps rename to something that makes it clear it's only pulling the zone or offset info. e.g. "withXFrom" (I can't come up with a good value for X at the moment)
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 115 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NoYW2w-5Q2bmNFthz9V:-NoYzuMqBb-t06gh2KWM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/294d13266c17376a28a9c07d06dc027520cb9b9f/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Need field documentation. Note that since this field is not required the documentation should be clear on what the behavior is when it is or isn't specified.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 29 files at r1, 3 of 17 files at r2, 2 of 7 files at r4, 4 of 10 files at r5, 1 of 4 files at r6, 8 of 11 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: all files reviewed, 9 unresolved discussions (waiting on @kungfucraig, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 1055 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-Nolw-be5TB0MJMxXGmA:-Nolw-be5TB0MJMxXGmB:b-xy6zwj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4fcda6b35d326b07943dae14e915bc679fac21c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L1055)):*
> ```Kotlin
>  * * [DateTimeException] when values in DateTime are invalid.
>  */
> fun DateTime.toOffsetDateTime(): OffsetDateTime {
> ```

nit: add TODOs to move these to common-jvm.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 877 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-NolwDjc4OYAwtdrnSg6:-NolwDjc4OYAwtdrnSg7:bx27ndn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4fcda6b35d326b07943dae14e915bc679fac21c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L877)):*
> ```Kotlin
> }
> 
> /** Validate [Report] time fields. Throws grpc exception if error found. */
> ```

nit: Use the `@throws` KDoc tag (not the `@Throws` Kotlin annotation) for this.



_Suggestion:_
```Kotlin

@throws StatusRuntimeException with code [Status.Code.INVALID_ARGUMENT] if [report] is invalid
```

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r8, 2 of 3 files at r9, 9 of 19 files at r11, 9 of 9 files at r12, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 1006 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-Np17JsTBvNjD-ctqZX5:-Np17JsTBvNjD-ctqZX6:bdefzxt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/088ff78279f96ddff87353b517a6adaf4185603e/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L1006)):*
> ```Kotlin
> }
> 
> private fun generateTimeIntervals(
> ```

missing kdoc at the top of the function.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 157 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-Np0swVe7kx_-eXf1Q81:-Np0swVe7kx_-eXf1Q82:buwp3dt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/088ff78279f96ddff87353b517a6adaf4185603e/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L157)):*
> ```Kotlin
>       )
> 
>     assertThat(baseReport)
> ```

Why does it compare to `baseReport` but not `report`?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: 30 of 33 files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 1006 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-Np17JsTBvNjD-ctqZX5:-Np5WC5k2vOBALwI1dka:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/088ff78279f96ddff87353b517a6adaf4185603e/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L1006)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

missing kdoc at the top of the function.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 157 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-Np0swVe7kx_-eXf1Q81:-Np5bGIu3sNoEtpiP4v8:b-ij4cc8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/088ff78279f96ddff87353b517a6adaf4185603e/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L157)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Why does it compare to `baseReport` but not `report`?
</blockquote></details>

That is a mistake. Fixed it.

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r15, 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 278 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416#-Np6Oqyp5NkVQDQ-8NPW:-Np6Oqyp5NkVQDQ-8NPX:b-ictfzm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df2fff6afb6665986941da181270e51c27f409b9/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L278)):*
> ```Kotlin
> 
>                 val metrics = sourceMetrics {
>                   cumulative = metricCalculationResult.cumulative
> ```

Since we are not touching any code in v1alpha, does this line need to be removed?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 15 files at r3, 5 of 19 files at r11, 2 of 9 files at r12, 1 of 1 files at r15, 1 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig)

**Review by tristanvuong2021 — COMMENTED** [review]
> Dismissed @kungfucraig from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1416)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

**Pull request merged**
