### PR TITLE
Implement system computationParticipantsService.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/129)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/129)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsService.kt, line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/129#-MdKC_y38cjxJuIdac5B:-MdKC_y38cjxJuIdac5C:bbuzhz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/180b911c272874772196ba7ec15eaa7dad8b3afb/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsService.kt#L121)):*
> ```
> failure.stageAttempt.toInternalStageAttempt()
> ```
`stage_attempt` isn't required (e.g. if failure occurs in Duchy before initialization phase). Only set it in internal request if it's set in system request.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsServiceTest.kt, line 257 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/129#-MdKD_6PBCLj8p9Zrgt8:-MdKD_6PBCLj8p9Zrgt9:bobq7jx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/180b911c272874772196ba7ec15eaa7dad8b3afb/src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsServiceTest.kt#L257)):*
> ```Kotlin
>       )
>   }
> }
> ```

Add tests for error cases.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/129)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsService.kt, line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/129#-MdKC_y38cjxJuIdac5B:-MdNXdBBD6Nx_dOKYfcE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/180b911c272874772196ba7ec15eaa7dad8b3afb/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsService.kt#L121)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> failure.stageAttempt.toInternalStageAttempt()
> ```
`stage_attempt` isn't required (e.g. if failure occurs in Duchy before initialization phase). Only set it in internal request if it's set in system request.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsServiceTest.kt, line 257 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/129#-MdKD_6PBCLj8p9Zrgt8:-MdNXf6LE7wxmngjmo28:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/180b911c272874772196ba7ec15eaa7dad8b3afb/src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsServiceTest.kt#L257)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add tests for error cases.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
