### PR TITLE
Implement v2alpha public event groups service

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/200)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/200)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/200#-MhPCqZj9Ki9srWGeOpn:-MhPCaG5DC0Kyw_Hy9OC:bbwsoi5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/947ef804479623757d9acf03108e4d82f7f1b068/src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto#L45)):*
> ```protobuf
>   message Filter {
>     int64 external_data_provider_id = 1;
>     repeated int64 external_measurement_consumer_ids = 2;
> ```

I suppose the use case for this is an EDP listing EventGroups for specific MCs? An MC caller can only specify their own ID.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt, line 194 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/200#-MhPDCCTCr0s0QQUTN6Q:-MhPDCCTCr0s0QQUTN6R:b-c5wgco) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/947ef804479623757d9acf03108e4d82f7f1b068/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt#L194)):*
> ```
> DataProviderKey.fromName(DATA_PROVIDER_NAME)!!
> ```
Since `DATA_PROVIDER_NAME` is a constant, you can similarly have a constant for the resulting `DataProviderKey` rather than having to repeatedly construct one.

**Comment by tristanvuong2021** [comment]
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/200#-MhPCqZj9Ki9srWGeOpn:-MhPTm_lAUih-mQsDtMd:b-cufyv2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/947ef804479623757d9acf03108e4d82f7f1b068/src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I suppose the use case for this is an EDP listing EventGroups for specific MCs? An MC caller can only specify their own ID.
</blockquote></details>

I added a TODO to take note of this.

**Comment by tristanvuong2021** [comment]
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt, line 194 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/200#-MhPDCCTCr0s0QQUTN6Q:-MhPTvriEplJ8-eNJWAO:b7cjcne) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/947ef804479623757d9acf03108e4d82f7f1b068/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt#L194)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> DataProviderKey.fromName(DATA_PROVIDER_NAME)!!
> ```
Since `DATA_PROVIDER_NAME` is a constant, you can similarly have a constant for the resulting `DataProviderKey` rather than having to repeatedly construct one.
</blockquote></details>

I added a constant for the id instead.

**Review by corbantek — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
