### PR TITLE
Add ModelProvider as Certificate parent

### PR DESCRIPTION
**Pull request by efoxepstein**
https://rally1.rallydev.com/#/?detail=/task/609683196371&fdp=true

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[build/repositories.bzl, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkt82Du9bWZ5SO0ExBV:-Mkt82Du9bWZ5SO0ExBW:b1watb0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/build/repositories.bzl#L42)):*
> ```Starlark
>         repo = "cross-media-measurement-api",
>         sha256 = "78122d642c9a4fdad3463ddb1d4902b9448e6ef733c9608fd9df33e942a454b6",
>         commit = "d7746e5eec85b679fd64459e82779b40f1c7850e",
> ```

Right before submitting, I'll make a release and set this to the latest version.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderCertificateKey.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-MktK8oB2kXAbMFvRcnh:-MktK8oB2kXAbMFvRcni:b1rfq9q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderCertificateKey.kt#L46)):*
> ```
> dataProviderCertificateName
> ```
I've seen the lowerCamelCase naming convention for type-safe DSL builders. It feels a little weird for these as they aren't even factories given that the return type is String. I was confused when I saw these being called and had to look around for where/how they were defined.

I'm not sure this makes it more readable given that doesn't really fit the convention.

As an aside, what would probably be the "proper way" is having a type-safe `ResourceName<T : ResourceKey>` wrapper to avoid interacting with the string as much as possible. I figure something similar to HexString, where the canonical wrapped value is the ResourceKey.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-MktJ06-5dw1cqrsAK4h:-MktJ06-5dw1cqrsAK4i:b-4bdakb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L100)):*
> ```Kotlin
>           ?: throw KingdomInternalException(KingdomInternalException.Code.DUCHY_NOT_FOUND)
>       Certificate.ParentCase.EXTERNAL_MODEL_PROVIDER_ID ->
>         ModelProviderReader()
> ```

Mind adding a TODO here to change all these to use index lookups or simple queries? Readers sometimes do joins in order to assemble all the data, and that's overkill when all you care about is external->internal ID mapping.
___
*[src/main/proto/wfa/measurement/internal/kingdom/certificate.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-MktOB5KBSHXUjL3KYHC:-MktOB5KBSHXUjL3KYHD:b-pxoq8r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/proto/wfa/measurement/internal/kingdom/certificate.proto#L29)):*
> ```
> 10
> ```
We've been making incompatible changes by renumbering the fields until we have something deployed, but I know that's 1. Not the safe thing to do once anything is using this protos and 2. A pain to do manually.

Fine either way, but I figured when we were going to stop renumbering we'd also want to use a mechanism to track the latest unused ID. e.g.
```
reserved 10 to max; // Next ID
```

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 8 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)* status: all files reviewed, 8 unresolved discussions (waiting on @efoxepstein and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkw8jF0A7cdCWTu-owF:-Mkw8jF0A7cdCWTu-owG:b4u0ckk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L61)):*
> ```Kotlin
>         KingdomInternalException.Code.DUCHY_NOT_FOUND ->
>           failGrpc(Status.NOT_FOUND) { "Duchy not found" }
>         KingdomInternalException.Code.MODEL_PROVIDER_NOT_FOUND,
> ```

add a message
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkw8qRUBdRmPNnCltwi:-Mkw8qRUBdRmPNnCltwj:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt#L103)):*
> ```Kotlin
>         KingdomInternalException.Code.DUCHY_NOT_FOUND ->
>           failGrpc(Status.NOT_FOUND) { "Duchy not found" }
>         KingdomInternalException.Code.MODEL_PROVIDER_NOT_FOUND,
> ```

ditto
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkw8unT7hmcMHJgPdB5:-Mkw8unT7hmcMHJgPdB6:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L57)):*
> ```Kotlin
>         KingdomInternalException.Code.CERTIFICATE_NOT_FOUND ->
>           failGrpc(Status.INVALID_ARGUMENT) { "Certificate not found" }
>         KingdomInternalException.Code.MODEL_PROVIDER_NOT_FOUND,
> ```

ditto
___
*[src/main/proto/wfa/measurement/internal/kingdom/certificates_service.proto, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkw9t008mMqKb13tLKc:-Mkw9t008mMqKb13tLKd:b-glpim7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/proto/wfa/measurement/internal/kingdom/certificates_service.proto#L54)):*
> ```protobuf
>     fixed64 external_measurement_consumer_id = 2;
>     string external_duchy_id = 3;
>     fixed64 external_model_provider_id = 6;
> ```

since nothing is deployed, why not renumber all these so these are sequential (for now at least)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)* status: all files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderCertificateKey.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-MktK8oB2kXAbMFvRcnh:-MkwFJ7SBiQi94u-k4EJ:b-ln0i9v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderCertificateKey.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> dataProviderCertificateName
> ```
I've seen the lowerCamelCase naming convention for type-safe DSL builders. It feels a little weird for these as they aren't even factories given that the return type is String. I was confused when I saw these being called and had to look around for where/how they were defined.

I'm not sure this makes it more readable given that doesn't really fit the convention.

As an aside, what would probably be the "proper way" is having a type-safe `ResourceName<T : ResourceKey>` wrapper to avoid interacting with the string as much as possible. I figure something similar to HexString, where the canonical wrapped value is the ResourceKey.
</blockquote></details>

I'll just remove these. Basically, the idea was to replace `FooKey(x, y).toName()` with `fooName(x, y)` to declutter but `fooName(x, y).toString()` seems just as bad. As a last hail-mary, how about `makeFooName(x, y)`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkw8jF0A7cdCWTu-owF:-MkwF-9y8Y8QO6S77j8V:bb76mu4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L61)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

add a message
</blockquote></details>

Why?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkw8qRUBdRmPNnCltwi:-MkwF0n6CiqCjKxzyfiW:bb76mu4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt#L103)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Why?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkw8unT7hmcMHJgPdB5:-MkwF1Rq50M78hcNQxIx:bb76mu4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L57)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Why?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-MktJ06-5dw1cqrsAK4h:-MkwF3fa25UxVENTT9CX:bebrt1w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L100)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Mind adding a TODO here to change all these to use index lookups or simple queries? Readers sometimes do joins in order to assemble all the data, and that's overkill when all you care about is external->internal ID mapping.
</blockquote></details>

Will do
___
*[src/main/proto/wfa/measurement/internal/kingdom/certificate.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-MktOB5KBSHXUjL3KYHC:-MkwFCwp6jbqzMCDD42i:b61gjsp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/proto/wfa/measurement/internal/kingdom/certificate.proto#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> 10
> ```
We've been making incompatible changes by renumbering the fields until we have something deployed, but I know that's 1. Not the safe thing to do once anything is using this protos and 2. A pain to do manually.

Fine either way, but I figured when we were going to stop renumbering we'd also want to use a mechanism to track the latest unused ID. e.g.
```
reserved 10 to max; // Next ID
```
</blockquote></details>

I'll renumber
___
*[src/main/proto/wfa/measurement/internal/kingdom/certificates_service.proto, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkw9t008mMqKb13tLKc:-MkwFH5c03LiI-upuRuk:bebrt1w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/proto/wfa/measurement/internal/kingdom/certificates_service.proto#L54)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

since nothing is deployed, why not renumber all these so these are sequential (for now at least)
</blockquote></details>

Will do

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)* status: all files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkw8jF0A7cdCWTu-owF:-MkwJ42X51MiXGPdHF5-:bil9su6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L61)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Looking at the lines above, I was thinking it would be consistent to do
```
        KingdomInternalException.Code.MODEL_PROVIDER_NOT_FOUND ->
          failGrpc(Status.NOT_FOUND) { "Model Provider not found" }
```

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)* status: all files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkw8jF0A7cdCWTu-owF:-MkwK2g50X8fsAe0ZLAI:b-94vigk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L61)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Looking at the lines above, I was thinking it would be consistent to do
```
        KingdomInternalException.Code.MODEL_PROVIDER_NOT_FOUND ->
          failGrpc(Status.NOT_FOUND) { "Model Provider not found" }
```
</blockquote></details>

Ah yes, for this one it makes sense -- for the ones where there's no good reason that they should be doing anything with model providers, it doesn't make sense.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkw8jF0A7cdCWTu-owF:-MkwS921B2Ooiddpq0-Q:bf2vbqa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L61)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ah yes, for this one it makes sense -- for the ones where there's no good reason that they should be doing anything with model providers, it doesn't make sense.
</blockquote></details>

agree - just this one.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 98 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-MkwSOsd8I-6l4vQM4_0:-MkwSOsd8I-6l4vQM4_1:bvolkw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L98)):*
> ```Kotlin
>         }
>         GetCertificateRequest.ParentCase.EXTERNAL_MODEL_PROVIDER_ID ->
>           CertificateReader(CertificateReader.ParentType.MODEL_PROVIDER)
> ```

do you need `.bindWhereClause(ExternalId(request.externalModelProviderId), externalCertificateId)`

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderCertificateKey.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-MktK8oB2kXAbMFvRcnh:-MkwZRQi1dWpQa1723oH:bxgsdms) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderCertificateKey.kt#L46)):*
> As a last hail-mary, how about `makeFooName(x, y)`?

Sure.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 98 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-MkwSOsd8I-6l4vQM4_0:-Mkwg--ABhcJAWwFRCpq:b-iry7x8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L98)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you need `.bindWhereClause(ExternalId(request.externalModelProviderId), externalCertificateId)`
</blockquote></details>

Done, thanks

**Review by tristanvuong2021 — APPROVED** [review]

**Review by stevenwarejones — APPROVED** [review]
just take care of the version pin

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-:-MkxFfNT3vNCUx7Q9idF:b-6mtpfq)* status: 9 of 24 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)* status: 9 of 24 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

___
*[build/repositories.bzl, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-Mkt82Du9bWZ5SO0ExBV:-MkxH9Wp3unsAJRoAzz_:b-mn2by8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c0d22c913a075424f47757cca4faf7f045768e9/build/repositories.bzl#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Right before submitting, I'll make a release and set this to the latest version.
</blockquote></details>

Some issue with `consent-signaling-client` is preventing this from being updated, so I'm leaving it as is with a TODO.

**Review by stevenwarejones — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308#-:-MlAG0-t38Q1-7_zbEoY:bnfp4nl)* status: 8 of 24 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 6 of 18 files at r1, 15 of 15 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 8 of 18 files at r1, 15 of 15 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/308)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
