### PR TITLE
Ensure Java-based pods have JVM memory options specified.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610)

### CODE REVIEW

**Comment by SanjayVas** [comment]
Potential alternative to #605.

**Comment by SanjayVas** [comment]
`kubectl top` from KinD with frontend simulator kicked off ~30m ago, all containers built using `-c opt`:

```
NAME                                                              CPU(cores)   MEMORY(bytes)   
aggregator-async-computation-control-server-deployment-8d85v4fd   5m           243Mi           
aggregator-computation-control-server-deployment-8695685b7j5qq9   7m           330Mi           
aggregator-herald-daemon-deployment-785dfc4b65-cwtpl              2m           195Mi           
aggregator-liquid-legions-v2-mill-daemon-deployment-8688f5chw9f   5m           704Mi           
aggregator-requisition-fulfillment-server-deployment-7bf987h654   7m           214Mi           
aggregator-spanner-computations-server-deployment-65f74486d2n94   12m          412Mi           
edp1-simulator-deployment-c9db757f8-kw8wl                         3m           277Mi           
edp2-simulator-deployment-74c54f8c8b-mlncg                        3m           262Mi           
edp3-simulator-deployment-67ff5c6649-d8j2s                        3m           259Mi           
edp4-simulator-deployment-55b6f4fbdc-gnqfl                        3m           230Mi           
edp5-simulator-deployment-6d9594bdf7-wpqhk                        3m           289Mi           
edp6-simulator-deployment-55dfb9c557-r9xxz                        3m           323Mi           
fake-storage-server-deployment-79bcd9fb8f-xftb2                   14m          502Mi           
gcp-kingdom-data-server-deployment-6486d8b5cd-w64n5               18m          504Mi           
spanner-emulator-pod                                              38m          57Mi            
system-api-server-deployment-78977c47cc-2flbm                     9m           413Mi           
v2alpha-public-api-server-deployment-7765bb4456-tcjpl             15m          366Mi           
worker1-async-computation-control-server-deployment-56f6b8nmhr7   6m           247Mi           
worker1-computation-control-server-deployment-5bd96dc6d8-94ss5    6m           325Mi           
worker1-herald-daemon-deployment-dc7f46dd9-nqx22                  2m           194Mi           
worker1-liquid-legions-v2-mill-daemon-deployment-8675fc9ffc7xzm   8m           674Mi           
worker1-requisition-fulfillment-server-deployment-664d5f4bg2kvp   4m           480Mi           
worker1-spanner-computations-server-deployment-757fbd7b94-rsl9f   12m          442Mi           
worker2-async-computation-control-server-deployment-5c4c66mxr8k   7m           240Mi           
worker2-computation-control-server-deployment-77b9796fb7-vj2s9    4m           305Mi           
worker2-herald-daemon-deployment-58c65fb74b-qxtjn                 2m           194Mi           
worker2-liquid-legions-v2-mill-daemon-deployment-575d84b9cgt9vm   5m           598Mi           
worker2-requisition-fulfillment-server-deployment-756d9dcbx7fwb   10m          213Mi           
worker2-spanner-computations-server-deployment-5c9c466f5b-685j5   13m          464Mi           

```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @matthewclegg)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610#-N5I0g8u4Dh0VWa6c_e5:-N5I0g8v6qEMHjwkz-PD:b9dycyl) (no related file):*
Note that apparently JDK 11 and even some backported versions of JDK 8 can now automatically detect container RAM limits via cgroups and set a max heap size based on percentage of that limit. It might be worth playing with that rather than fixed sizes.

___

**Review by matthewclegg — COMMENTED** [review]
I tried it, and it works for me.  Thanks for this PR!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610#-:-N5Lf06F1rnr7-8kHJpz:b-8chafv)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610#-N5I0g8u4Dh0VWa6c_e5:-N5MFNQg9A07ORnQRIW-:b70tdvd) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that apparently JDK 11 and even some backported versions of JDK 8 can now automatically detect container RAM limits via cgroups and set a max heap size based on percentage of that limit. It might be worth playing with that rather than fixed sizes.
</blockquote></details>

That sounds like a great idea.  For what it's worth, I found the following article that might be helpful.  https://developers.redhat.com/articles/2022/04/19/java-17-whats-new-openjdks-container-awareness#

FYI, if I run `docker info`, the following is printed:

```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

...

WARNING: Support for cgroup v2 is experimental
```

___

**Review by matthewclegg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610#-:-N5MkRvgDxMhQtYDlXhU:bnfp4nl)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @SanjayVas)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 15 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610)* status: 15 of 23 files reviewed, 2 unresolved discussions (waiting on @matthewclegg, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/dev/kingdom_gke.cue` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610#-N5elgKn5zv4UxIYA8VK:-N5elgKn5zv4UxIYA8VL:b-94wgdx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a328f4462d6365e4c3bf0cfa437b79ac6965432/src/main/k8s/dev/kingdom_gke.cue#L23)):*
> ```CUE
> 	resources: {
> 		requests: {
> 			cpu: "100m"
> ```

don't you want a request memory like the original?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610)* status: 15 of 23 files reviewed, 2 unresolved discussions (waiting on @matthewclegg, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/dev/kingdom_gke.cue` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610#-N5elgKn5zv4UxIYA8VK:-N5f06yw7MF9gTzVbIyj:b-z1td0m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a328f4462d6365e4c3bf0cfa437b79ac6965432/src/main/k8s/dev/kingdom_gke.cue#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

don't you want a request memory like the original?
</blockquote></details>

Since we're following the oft-recommended practice of having -Xms == -Xmx for JVM flags, it means that we don't really have a difference between request and limit when it comes to memory.

From the K8s docs, if request isn't set but limit is then the limit is used for the request value.

**Review by matthewclegg — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610)* status: 15 of 23 files reviewed, 3 unresolved discussions (waiting on @matthewclegg, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/dev/kingdom_gke.cue` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610#-N6JXXC1BFAlWipO8g1R:-N6JXXC1BFAlWipO8g1S:byg3tyo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a328f4462d6365e4c3bf0cfa437b79ac6965432/src/main/k8s/dev/kingdom_gke.cue#L27)):*
> ```CUE
> 		limits: {
> 			cpu:    "400m"
> 			memory: "512Mi"
> ```

Unfortunately, I found that this does not seem to work as intended.  I modified the `memory` to 1024Mi and the `jvmHeapSize` to 800m.  Then, when I executed `bazel build //src/main/k8s/dev:kingdom_gke     --define=k8s_kingdom_secret_name=blahblah`, I received many lines of error output, starting with the following:

```
#DefaultResourceConfig.jvmHeapSize: conflicting values "800m" and "400m":
    ./src/main/k8s/dev/base_gke.cue:49:15
    ./src/main/k8s/dev/kingdom_gke.cue:30:15
#DefaultResourceConfig.resources.limits.memory: conflicting values "1024Mi" and "512Mi":
    ./src/main/k8s/dev/base_gke.cue:46:12
    ./src/main/k8s/dev/kingdom_gke.cue:27:12
kingdom._resource_configs."gcp-kingdom-data-server".jvmHeapSize: conflicting values "800m" and "400m":
    ./src/main/k8s/dev/base_gke.cue:49:15
    ./src/main/k8s/dev/kingdom_gke.cue:30:15
    ./src/main/k8s/dev/kingdom_gke.cue:68:32
kingdom._resource_configs."gcp-kingdom-data-server".resources.limits.memory: conflicting values "1024Mi" and "512Mi":
    ./src/main/k8s/dev/base_gke.cue:46:12
    ./src/main/k8s/dev/kingdom_gke.cue:27:12
    ./src/main/k8s/dev/kingdom_gke.cue:68:32
... etc.
```

By the way, I made these changes because when I tried deploying the Kingdom to GKE with the limits that are defined in this file, `gcp-kingdom-data-server` began crash-looping.  Increasing the memory limits seems to have solved the problem.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610)* status: 11 of 23 files reviewed, 3 unresolved discussions (waiting on @matthewclegg, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/dev/kingdom_gke.cue` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610#-N6JXXC1BFAlWipO8g1R:-N6jB8wg6yI8e7zNpQoz:b-m0ozjo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eb244686d6f992442a107538f33e00b6254db3da/src/main/k8s/dev/kingdom_gke.cue#L27)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Unfortunately, I found that this does not seem to work as intended.  I modified the `memory` to 1024Mi and the `jvmHeapSize` to 800m.  Then, when I executed `bazel build //src/main/k8s/dev:kingdom_gke     --define=k8s_kingdom_secret_name=blahblah`, I received many lines of error output, starting with the following:

```
#DefaultResourceConfig.jvmHeapSize: conflicting values "800m" and "400m":
    ./src/main/k8s/dev/base_gke.cue:49:15
    ./src/main/k8s/dev/kingdom_gke.cue:30:15
#DefaultResourceConfig.resources.limits.memory: conflicting values "1024Mi" and "512Mi":
    ./src/main/k8s/dev/base_gke.cue:46:12
    ./src/main/k8s/dev/kingdom_gke.cue:27:12
kingdom._resource_configs."gcp-kingdom-data-server".jvmHeapSize: conflicting values "800m" and "400m":
    ./src/main/k8s/dev/base_gke.cue:49:15
    ./src/main/k8s/dev/kingdom_gke.cue:30:15
    ./src/main/k8s/dev/kingdom_gke.cue:68:32
kingdom._resource_configs."gcp-kingdom-data-server".resources.limits.memory: conflicting values "1024Mi" and "512Mi":
    ./src/main/k8s/dev/base_gke.cue:46:12
    ./src/main/k8s/dev/kingdom_gke.cue:27:12
    ./src/main/k8s/dev/kingdom_gke.cue:68:32
... etc.
```

By the way, I made these changes because when I tried deploying the Kingdom to GKE with the limits that are defined in this file, `gcp-kingdom-data-server` began crash-looping.  Increasing the memory limits seems to have solved the problem.
</blockquote></details>

Fixed the overridability of values.

Feel free to send a follow-up PR for adjusting resource config for specific containers. Note that if they're crashing due to memory but not showing a Java OOM, then the initial action should be creating a bigger gap between the JVM heap size and the container memory limit.

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 5 of 23 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610)* status: all files reviewed, 2 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/k8s/dev/kingdom_gke.cue` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610#-N6JXXC1BFAlWipO8g1R:-N6xkNZqBN8xzMaKJrwt:b5j7e0g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eb244686d6f992442a107538f33e00b6254db3da/src/main/k8s/dev/kingdom_gke.cue#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Fixed the overridability of values.

Feel free to send a follow-up PR for adjusting resource config for specific containers. Note that if they're crashing due to memory but not showing a Java OOM, then the initial action should be creating a bigger gap between the JVM heap size and the container memory limit.
</blockquote></details>

Please experimentally test all these params before merging.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @matthewclegg from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Pull request merged**
