### PR TITLE
Stop setting deprecated event_groups field in RequisitionSpec.

### PR DESCRIPTION
**Pull request by SanjayVas**
The field has been deprecated since v0.4.0.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 662 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277#-Ng-KtaP5Qh6kckq5xpb:-Ng-KtaP5Qh6kckq5xpc:b-ns2wpv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c1ea5521994752f0068ed67d53c972dc96057359/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L662)):*
> ```Kotlin
>           }
>         events = RequisitionSpecKt.events { this.eventGroups += eventGroups }
>         this.eventGroups += eventGroups
> ```

have we verified all EDPs aren't expecting this field?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 662 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277#-Ng-KtaP5Qh6kckq5xpb:-Ng1Fq0lDKtKF0KDlZp_:b6100dc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c1ea5521994752f0068ed67d53c972dc96057359/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L662)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

have we verified all EDPs aren't expecting this field?
</blockquote></details>

This field was marked as deprecated in the last (0.4.0) release, so we should be able to drop it by the next (0.5.0) release.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 662 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277#-Ng-KtaP5Qh6kckq5xpb:-Ng4VllY0JZLS7FJgxlP:b-g9c8cf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c1ea5521994752f0068ed67d53c972dc96057359/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L662)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This field was marked as deprecated in the last (0.4.0) release, so we should be able to drop it by the next (0.5.0) release.
</blockquote></details>

I don't think that's a fair expectation already - I'd prefer deprecated fields only get dropped in major releases - not minor -- @kungfucraig wdyt?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 662 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277#-Ng-KtaP5Qh6kckq5xpb:-NgUX1KeAkOL0TSX-dhe:b-3vje9k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c1ea5521994752f0068ed67d53c972dc96057359/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L662)):*
The reason we're only increasing the minor component on each release right now is because we're using the special `0` major value for initial development where we're making frequent breaking changes. From semver.org:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Each of these minor releases on major version 0 is effectively a major release. Additionally as per the "Update Requirements" section in [Production Reliability Strategy](https://docs.google.com/document/d/155aYNSCOa7A4RkUi15AhpikPI8L8PydO-efdsvn31pc/edit?usp=sharing&resourcekey=0-ZMrKidEQ3TxG4pGf0yWwFA), everyone should be no more than one minor release behind.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 662 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277#-Ng-KtaP5Qh6kckq5xpb:-NgZdUUMCMSKpoNuwB43:b-12cubj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c1ea5521994752f0068ed67d53c972dc96057359/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L662)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The reason we're only increasing the minor component on each release right now is because we're using the special `0` major value for initial development where we're making frequent breaking changes. From semver.org:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Each of these minor releases on major version 0 is effectively a major release. Additionally as per the "Update Requirements" section in [Production Reliability Strategy](https://docs.google.com/document/d/155aYNSCOa7A4RkUi15AhpikPI8L8PydO-efdsvn31pc/edit?usp=sharing&resourcekey=0-ZMrKidEQ3TxG4pGf0yWwFA), everyone should be no more than one minor release behind.
</blockquote></details>

if this is the case, do we want to go ahead and remove the field from the public API entirely?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 662 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277#-Ng-KtaP5Qh6kckq5xpb:-Ng_5WDF-a30A5gGbsVi:bjgm7db) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c1ea5521994752f0068ed67d53c972dc96057359/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L662)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

if this is the case, do we want to go ahead and remove the field from the public API entirely?
</blockquote></details>

Yes, that was my plan. It of course needs to be a separate PR since it's the API repo, and it need not block this PR.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 662 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277#-Ng-KtaP5Qh6kckq5xpb:-Ng_DhCx6BV9dLvPfazI:b15q7t5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c1ea5521994752f0068ed67d53c972dc96057359/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L662)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, that was my plan. It of course needs to be a separate PR since it's the API repo, and it need not block this PR.
</blockquote></details>

Sorry, we can't actually remove the field from the public API as it's used in a serialized type (RequisitionSpec). This means that EDPs will still need to read the old field for old Requisitions where the new one isn't set.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 662 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277#-Ng-KtaP5Qh6kckq5xpb:-Ng_qipbDSUpY1hQ4hJM:b1xw2iv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c1ea5521994752f0068ed67d53c972dc96057359/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L662)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, we can't actually remove the field from the public API as it's used in a serialized type (RequisitionSpec). This means that EDPs will still need to read the old field for old Requisitions where the new one isn't set.
</blockquote></details>

That's unfortuante.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
