### PR TITLE
Add ModelShard public api

### PR DESCRIPTION
**Pull request by Marco-Premier**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 9 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: 9 of 18 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt` line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWJObJaCG9c20eahyXQ:-NWJObJaCG9c20eahyXR:btt0vtp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd91c5d6da9fbfffc8c4d7bf7f882bdd8ef3a6cc/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt#L75)):*
> ```Kotlin
>       is ModelProviderPrincipal -> {}
>       else -> {
>         failGrpc(Status.PERMISSION_DENIED) {
> ```

we need to validatete that the principal matches the modelProvider in the ModelRelease

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: 9 of 18 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt` line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWJOkPG5jNwKaR1_pLJ:-NWJOkPG5jNwKaR1_pLK:b-x27va9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd91c5d6da9fbfffc8c4d7bf7f882bdd8ef3a6cc/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt#L104)):*
> ```Kotlin
> 
>     when (principalFromCurrentContext) {
>       is ModelProviderPrincipal -> {}
> ```

ditto on checking the principal
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWJOsWL0sJVS9y6fgIA:-NWJOsWL0sJVS9y6fgIB:btxfat8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd91c5d6da9fbfffc8c4d7bf7f882bdd8ef3a6cc/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt#L141)):*
> ```Kotlin
>     when (principalFromCurrentContext) {
>       is ModelProviderPrincipal -> {}
>       is DataProviderPrincipal -> {}
> ```

We'll need to check the either the parent resource is the principal for the data provider use case. For the model provider use case, we need to make sure to return only those whose ModelRelease's modelProvider matches the principal.

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt` line 87 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWNc1O36SFF79sQYvGZ:-NWNc1O36SFF79sQYvG_:b-6u7qwy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd91c5d6da9fbfffc8c4d7bf7f882bdd8ef3a6cc/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt#L87)):*
> ```Kotlin
>       when (ex.status.code) {
>         Status.Code.NOT_FOUND ->
>           failGrpc(Status.NOT_FOUND, ex) { ex.message ?: "ModelShard not found" }
> ```

ModelShard not found doesn't make sense as a fallback when trying to create a model shard.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsServiceTest.kt` line 488 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWNesIc-x1PoHU4wV1z:-NWNesIc-x1PoHU4wV2-:b-ix4jpt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc72819d2f9bcabe000017053b7be44faf6d5de3/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsServiceTest.kt#L488)):*
> ```Kotlin
> 
>   @Test
>   fun `listModelShards throws PERMISSION_DENIED when DataProvider parent doesn't match`() {
> ```

Is it too long to say doesn't match principal

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt` line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWJObJaCG9c20eahyXQ:-NWN-6kh8YCTGugGnCAL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd91c5d6da9fbfffc8c4d7bf7f882bdd8ef3a6cc/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt#L75)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

we need to validatete that the principal matches the modelProvider in the ModelRelease
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt` line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWJOkPG5jNwKaR1_pLJ:-NWN5MsX-XTGwUyB_2i0:b4a8g6n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd91c5d6da9fbfffc8c4d7bf7f882bdd8ef3a6cc/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt#L104)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto on checking the principal
</blockquote></details>

As per comment below, the resource name comes in the form:
```dataProviders/{data_provider}/modelShards/{model_shard}```, so there's no ```modelProvider``` parent to check against.

What I did was to forward the externalModelProviderId to internal API when principal is ModelProvider.
Internal API checks that the provided model provided matches the one owning the ModelShard's ModelRelease.
If there's no match a ```ModelShardInvalidArgsException``` is thrown.

I've also updated test accordingly to cover these scenario
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWJOsWL0sJVS9y6fgIA:-NWNG7cjDYZcUsX7Iud0:be8ae47) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd91c5d6da9fbfffc8c4d7bf7f882bdd8ef3a6cc/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt#L141)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

We'll need to check the either the parent resource is the principal for the data provider use case. For the model provider use case, we need to make sure to return only those whose ModelRelease's modelProvider matches the principal.
</blockquote></details>

For DataProviderPrincipal I check that the parent matches as usual.
For ModelProviderPrincipal, there's no ModelProvider parent to check against so I forward the externalModelProviderId as filter, so that internal API can return only ```ModelShards``` that have ```ModelRelease``` owned by the model provider caller.

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: 22 of 23 files reviewed, 8 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt` line 149 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWNqCAn3dNgLt6PVivi:-NWNqCAn3dNgLt6PVivj:bo3oezq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76cbe5dd04f60f85b06743186ee666c5bd189d16/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt#L149)):*
> ```Kotlin
>       }
> 
>     var externalModelProviderId: Long? = null
> ```

Could just do 0 like you did above. 0 is already the default value for the proto field so it doesn't matter if you set the field to 0.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt` line 217 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWNqwSgB6gYSiBeFWs_:-NWNqwSgB6gYSiBeFWsa:b-vas2cc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76cbe5dd04f60f85b06743186ee666c5bd189d16/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt#L217)):*
> ```Kotlin
>         if (externalModelProviderId != null) {
>           grpcRequire(this.externalModelProviderId == externalModelProviderId) {
>             "Arguments must be kept the same when using a page token"
> ```

Unit test for this case
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelShardsServiceTest.kt` line 456 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWNjbWsB7mk4iy4l5Db:-NWNjbWtE2KK7_EPCbMl:b-uun4eu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76cbe5dd04f60f85b06743186ee666c5bd189d16/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelShardsServiceTest.kt#L456)):*
> ```Kotlin
>         .toList()
> 
>     assertThat(modelShards).comparingExpectedFieldsOnly().containsExactly(modelShard1).inOrder()
> ```

nit: don't need inOrder when there is only 1 element.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: 22 of 23 files reviewed, 7 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt` line 87 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWNc1O36SFF79sQYvGZ:-NWbTHV9DII978ZZ3VX6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd91c5d6da9fbfffc8c4d7bf7f882bdd8ef3a6cc/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt#L87)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

ModelShard not found doesn't make sense as a fallback when trying to create a model shard.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt` line 149 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWNqCAn3dNgLt6PVivi:-NWbUId5-zO7xZOg7FCB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76cbe5dd04f60f85b06743186ee666c5bd189d16/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt#L149)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Could just do 0 like you did above. 0 is already the default value for the proto field so it doesn't matter if you set the field to 0.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt` line 217 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWNqwSgB6gYSiBeFWs_:-NWbWvEy2bvBn-1RBeQq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76cbe5dd04f60f85b06743186ee666c5bd189d16/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsService.kt#L217)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Unit test for this case
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsServiceTest.kt` line 488 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWNesIc-x1PoHU4wV1z:-NWbVvUBBbw2BXj-_B2M:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc72819d2f9bcabe000017053b7be44faf6d5de3/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsServiceTest.kt#L488)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Is it too long to say doesn't match principal
</blockquote></details>

Done.

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsServiceTest.kt` line 488 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWNesIc-x1PoHU4wV1z:-NWhZlM94vjxa5Yi5fTG:b-brc9m0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc72819d2f9bcabe000017053b7be44faf6d5de3/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsServiceTest.kt#L488)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant adding it to the end as in DataProvider parent doesn't match principal. If it doesn't fit, then it is okay.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: 22 of 23 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsServiceTest.kt` line 488 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NWNesIc-x1PoHU4wV1z:-NWkm_Lj7V5XrUXfcC6b:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc72819d2f9bcabe000017053b7be44faf6d5de3/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsServiceTest.kt#L488)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I meant adding it to the end as in DataProvider parent doesn't match principal. If it doesn't fit, then it is okay.
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 18 files at r1, 7 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsServiceTest.kt` line 359 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026#-NXB07x40dY8yI7nDmmZ:-NXB07x5EOoGQHIEcaAx:b-5yvowv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6b81e3a388631a620128aa72ff03bc963972a74c/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelShardsServiceTest.kt#L359)):*
> ```Kotlin
>       }
> 
>     val expected = listModelShardsResponse {
> ```

I think the expected for this test should be a subset of what is returned in the following test. Meaning, the data provider gets the results for all model providers but the model provider only gets ones related to itself.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1026)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
