### PR TITLE
Add privacy budget ledger

### PR DESCRIPTION
**Pull request by matthewclegg**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/485)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/485)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Review by uakyol — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/485)* status: all files reviewed, 1 unresolved discussion (waiting on @matthewclegg)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/485#-MydcQmX2cW-FY6pye84:-MydcQmX2cW-FY6pye85:b5bnwmm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e638fb6895b69109ad95c6d3f12d9663888fa14/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L68)):*
> ```Kotlin
> 
>     // The complexity of the following code illustrates why allowing
>     // VID sampling buckets to wrap around was a poor design choice.
> ```

Is it too late to change this design decision?

**Review by matthewclegg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/485)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/485#-MydcQmX2cW-FY6pye84:-MyoQmbxEx9_gLybL2Jl:brjkpud) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e638fb6895b69109ad95c6d3f12d9663888fa14/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L68)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Is it too late to change this design decision?
</blockquote></details>

I don't know of a reason why it would be too late, but that should probably be proposed in some broader forum, possibly starting with an internal design review.

**Review by matthewclegg — COMMENTED** [review]
> Dismissed @uakyol from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/485)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @uakyol)

**Pull request merged**
