### PR TITLE
Move data classes for v2alpha public API resource keys to a common package.

### PR DESCRIPTION
**Pull request by SanjayVas**
This allows them to be shared across Duchy and Kingdom services. In particular, this moves them to the JVM package that the API is defined in.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122)

### CODE REVIEW

**Comment by SanjayVas** [comment]
CC @yunyeng @uakyol. This is related to #111.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122#-Mczyy2l1-qesAaYghYs:-Mczyy2m3vJ-jkR04Qi_:bqmhgl1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf981b1c97f7c575791c8120422fec3e462ded5c/src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel#L4)):*
> ```Starlark
> load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")
> 
> package(default_visibility = [
> ```

The system services also depend on this. For example, when converting an internal measurement to a system computation, we need set the protocol_config (to be renamed from protocol_config_id since we are going to use resource name here) field. From external_protocol_config_id to protocol_config resource name, it requires the ProtocolConfigKey class.

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L50

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122#-Mczyy2l1-qesAaYghYs:-Md-FMQa715Jwuq_GOwQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf981b1c97f7c575791c8120422fec3e462ded5c/src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel#L4)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

The system services also depend on this. For example, when converting an internal measurement to a system computation, we need set the protocol_config (to be renamed from protocol_config_id since we are going to use resource name here) field. From external_protocol_config_id to protocol_config resource name, it requires the ProtocolConfigKey class.

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L50
</blockquote></details>

Done.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 22 of 23 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @wangyaopw, and @zachcwc)

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122#-Md1F4s3DiEDicR4W1XJ:-Md1F4s3DiEDicR4W1XK:boy751c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a42b2c789e848aa44a173c6a2ad3cd91aa6b039e/src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel#L9)):*
> ```
>  Remove once Herald no longer depends on public API.
> ```

why this TODO?

Herald gets  system computations from the kingdom, which contain public api resource names. Since herald needs to create local computation/requisition using the external ids, it needs to depend on the resource_key classes.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122#-Md1F4s3DiEDicR4W1XJ:-Md36Y2sBVOXJyxL8Dh1:bda8bpw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a42b2c789e848aa44a173c6a2ad3cd91aa6b039e/src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel#L9)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  Remove once Herald no longer depends on public API.
> ```

why this TODO?

Herald gets  system computations from the kingdom, which contain public api resource names. Since herald needs to create local computation/requisition using the external ids, it needs to depend on the resource_key classes.
</blockquote></details>

This TODO was from before you pointed out to me that system API callers will need resource name parsing :). I'll remove.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122#-Md1F4s3DiEDicR4W1XJ:-Md3E2Sy0P9OzQYfp-w2:b9q6hhg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a42b2c789e848aa44a173c6a2ad3cd91aa6b039e/src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This TODO was from before you pointed out to me that system API callers will need resource name parsing :). I'll remove.
</blockquote></details>

Decided to just expose to entire Kingdom and Duchy trees.

Not just public since other repos shouldn't depend on this.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)

**Pull request merged**
