### PR TITLE
modelrollout internal api

### PR DESCRIPTION
**Pull request by Marco-Premier**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018)* status: all files reviewed, 6 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 179 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018#-NW9OBQM0rERwhPmRq-Q:-NW9OBQM0rERwhPmRq-R:bay4m9i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ec38470496a5de2406c775994c4cdf618396b61/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L179)):*
> ```Kotlin
>         "external_model_suite_id" to externalModelSuiteId.toString(),
>         "external_model_line_id" to externalModelLineId.toString(),
>         "externalModelRolloutId" to externalModelRolloutId.toString()
> ```

nit: externalModelRolloutId should be in the format consistent with the rest
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelRollouts.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018#-NW9P2ha0OXBRa4WyDW0:-NW9P2ha0OXBRa4WyDW1:b-ts45xc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ec38470496a5de2406c775994c4cdf618396b61/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelRollouts.kt#L36)):*
> ```Kotlin
>       appendClause(
>         """
>           ORDER BY ModelRollouts.RolloutPeriodStartTime ASC,
> ```

Did you want to order by RolloutPeriodStartTime or CreateTime. If the order by fields are different from the fields used for the page token, then the paging won't work.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelRolloutReader.kt` line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018#-NW9QsrKBjxD--hKdU6x:-NW9QsrL3kHaI2w8spvz:b-qx3see) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ec38470496a5de2406c775994c4cdf618396b61/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelRolloutReader.kt#L72)):*
> ```Kotlin
>       JOIN ModelProviders ON (ModelSuites.ModelProviderId = ModelProviders.ModelProviderId)
>       LEFT JOIN ModelRollouts as PreviousModelRollout ON (ModelRollouts.PreviousModelRollout = PreviousModelRollout.ModelRolloutId)
>       LEFT JOIN ModelReleases ON (ModelRollouts.ModelRelease = ModelReleases.ModelReleaseId)
> ```

The schema has ModelRelease as NOT NULL so this should not be a LEFT JOIN.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 187 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018#-NW9Sj84ElTzW97fOK37:-NW9Sj85DVB37K_q8ZeA:bmdpkah) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ec38470496a5de2406c775994c4cdf618396b61/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L187)):*
> ```Kotlin
>         AND ModelLines.ModelSuiteId = ModelSuites.ModelSuiteId
>       )
>     JOiN ModelProviders ON ModelProviders.ModelProviderId = ModelSuites.ModelProviderId
> ```

nit: JOIN instead of JOiN
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelRolloutsServiceTest.kt` line 324 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018#-NW9VaBJ6w3TMxYf8YUE:-NW9VaBJ6w3TMxYf8YUF:b-p1rw2b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ec38470496a5de2406c775994c4cdf618396b61/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelRolloutsServiceTest.kt#L324)):*
> ```Kotlin
> 
>   @Test
>   fun `createModelRollout fails when rollout period end time precedes rollout period end time`() =
> ```

precedes rollout period start time
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_rollouts_service.proto` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018#-NW9NUdO0oXi3_POGukf:-NW9NUdO0oXi3_POGukg:bxq6jfr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ec38470496a5de2406c775994c4cdf618396b61/src/main/proto/wfa/measurement/internal/kingdom/model_rollouts_service.proto#L34)):*
> ```protobuf
>   rpc ScheduleModelRolloutFreeze(ScheduleModelRolloutFreezeRequest)
>       returns (ModelRollout);
>   // Sets the active_end_time for a `ModelLine`.
> ```

Wrong comment

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018)* status: 11 of 18 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelRollouts.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018#-NW9P2ha0OXBRa4WyDW0:-NWBowgS9MoIg1-RMMPR:b-7u3bzk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ec38470496a5de2406c775994c4cdf618396b61/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelRollouts.kt#L36)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Did you want to order by RolloutPeriodStartTime or CreateTime. If the order by fields are different from the fields used for the page token, then the paging won't work.
</blockquote></details>

Oh nice one! thanks for this. Yes it has to order by ```RolloutPeriodStartTime```.
I've changed the ```AfterFilter``` and also updated the ```streamModelRollouts can get one page at a time``` test to make sure it's consistently ordering by ```RolloutPeriodStartTime```.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelRolloutReader.kt` line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018#-NW9QsrKBjxD--hKdU6x:-NWBi5-7EOfl87xDYUYu:b8fau0f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ec38470496a5de2406c775994c4cdf618396b61/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelRolloutReader.kt#L72)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The schema has ModelRelease as NOT NULL so this should not be a LEFT JOIN.
</blockquote></details>

That's right. thanks
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelRolloutsServiceTest.kt` line 324 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018#-NW9VaBJ6w3TMxYf8YUE:-NWBhavg0tFy9QH_IKGA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ec38470496a5de2406c775994c4cdf618396b61/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelRolloutsServiceTest.kt#L324)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

precedes rollout period start time
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_rollouts_service.proto` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018#-NW9NUdO0oXi3_POGukf:-NWBi2kP6E1qu_mFB_x6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ec38470496a5de2406c775994c4cdf618396b61/src/main/proto/wfa/measurement/internal/kingdom/model_rollouts_service.proto#L34)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Wrong comment
</blockquote></details>

Done.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelRolloutReader.kt` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018#-NWD0-ldDC1eaglG6Y3B:-NWD0-ldDC1eaglG6Y3C:b-5f9435) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/657eff21ef52a242174be8d6e93529b8e2f6fb1e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelRolloutReader.kt#L61)):*
> ```Kotlin
>       JOIN ModelLines USING (ModelProviderId, ModelSuiteId, ModelLineId)
>       JOIN ModelSuites USING (ModelProviderId, ModelSuiteId)
>       JOIN ModelProviders ON (ModelSuites.ModelProviderId = ModelProviders.ModelProviderId)
> ```

nit: Joining ModelProviders can also be done with USING
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelRolloutsServiceTest.kt` line 874 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018#-NWD-I9h3SBeCbAkfQzu:-NWD-I9h3SBeCbAkfQzv:b-zbiyzf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/657eff21ef52a242174be8d6e93529b8e2f6fb1e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelRolloutsServiceTest.kt#L874)):*
> ```Kotlin
>                 after = afterFilter {
>                   rolloutPeriodStartTime = modelRollouts[0].rolloutPeriodStartTime
>                   rolloutPeriodStartTime = modelRollouts[0].rolloutPeriodStartTime
> ```

nit: rolloutPeriodStartTime is set twice to the same thing

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 11 of 18 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1018)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
