### PR TITLE
Reject zero values of delta

### PR DESCRIPTION
**Pull request by matthewclegg**
The differential privacy protocols currently in use for Liquid Legions v2 require that delta > 0.  If a 0 value of delta was supplied, the C++ code for sketch creation and noising would generate an exception, causing the duchy to crash.  This patch causes the herald to check for a non-zero value of delta before further processing is allowed.  If a zero value is found, then the Herald generates an exception.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/607)

### CODE REVIEW

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/607)* status: all files reviewed, 1 unresolved discussion (waiting on @matthewclegg)

**Review by matthewclegg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/607)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt` line 301 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/607#-N56nPhZ10EvCgxLW5E6:-N80yqnZBQc9TuUNGGTJ:b-l0q372) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f85cf89875ab990fe61511089ab04e6c49945e2a/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L301)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this true of LLv2 in general, or just our current implementation? If it's the latter, then adjust the error message and add a TODO to drop this once our implementation supports zero.
</blockquote></details>

It's true of LLv2 in general.

**Review by matthewclegg — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/607#-:-N8hjKKn2cbrV99gseJM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by matthewclegg — COMMENTED** [review]
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/607)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

**Pull request merged**
