### PR TITLE
Implement internal api keys service.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 10 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393)* status: 10 of 28 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/ApiKeysServerInterceptor.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393#-MqH22qPA4X9qIIlogDx:-MqH22qPA4X9qIIlogDy:b3gnryl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c51f75870d1e025786189b53e44c3cf4656a89f5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/ApiKeysServerInterceptor.kt#L42)):*
> ```
> Context.current()
> ```
Can this just be `context` since you declared that variable earlier?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerApiKeysService.kt, line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393#-MqH33RHCpRAu_fxkE9N:-MqH33RHCpRAu_fxkE9O:bjvppc0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c51f75870d1e025786189b53e44c3cf4656a89f5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerApiKeysService.kt#L100)):*
> ```
>     val apiAuthenticationKey =
>       getApiAuthenticationKey()
> ```
Sorry, I should have caught this before. I think it would be simpler to have the public service grab the key from context and pass the hash in `AuthenticateApiKeyRequest`.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerApiKeysService.kt, line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393#-MqH33RHCpRAu_fxkE9N:-MqHH_nx45_V_5Lq6gWX:bpni3l5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35206e98c5805289a447c3c34206882ff7aac8b5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerApiKeysService.kt#L100)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     val apiAuthenticationKey =
>       getApiAuthenticationKey()
> ```
Sorry, I should have caught this before. I think it would be simpler to have the public service grab the key from context and pass the hash in `AuthenticateApiKeyRequest`.
</blockquote></details>

True, if I do this, then I don't need the internal interceptor.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/ApiKeysServerInterceptor.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393#-MqH22qPA4X9qIIlogDx:-MqHSIoG3MuHDvzfis4h:b-csh9l4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35206e98c5805289a447c3c34206882ff7aac8b5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/ApiKeysServerInterceptor.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Context.current()
> ```
Can this just be `context` since you declared that variable earlier?
</blockquote></details>

Since the hash is now in the request, I removed this.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 13 of 28 files at r1, 8 of 9 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393)* status: 27 of 29 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto, line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393#-MqLFjDO5Z0NcbH8tum2:-MqLFjDO5Z0NcbH8tum3:b-gpo07m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce8e173011aa7fce3e78844b5f426ba247c637d4/src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto#L35)):*
> ```
> DeleteApiKeyRequest
> ```
I believe this method actually revokes rather than deletes. It should be named accordingly.

**Comment by tristanvuong2021** [comment]
___
*[src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto, line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393#-MqLFjDO5Z0NcbH8tum2:-MqLJEpz31C2o88HbhWI:b5t4gys) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce8e173011aa7fce3e78844b5f426ba247c637d4/src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> DeleteApiKeyRequest
> ```
I believe this method actually revokes rather than deletes. It should be named accordingly.
</blockquote></details>

Renamed it.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeysService.kt, line 69 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393#-MqLNH2PA548_kn6_UK4:-MqLNH2PA548_kn6_UK5:b7thpvz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55826f3d3946323bdcddd97878ebd240af846ecb/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeysService.kt#L69)):*
> ```
> deleteApiKey
> ```
This should get changed as well since it's not a standard delete method, but I know that needs another PR to update the API repo.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeApiKey.kt, line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393#-MqLNCNZERB3urjY-qEc:-MqLNCNZERB3urjY-qEd:b40bypa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55826f3d3946323bdcddd97878ebd240af846ecb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeApiKey.kt#L26)):*
> ```
> Creates an account in the database.
> ```
Fix description

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeysService.kt, line 69 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393#-MqLNH2PA548_kn6_UK4:-MqLSkb98DsM75NzNa5r:b4aynmt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55826f3d3946323bdcddd97878ebd240af846ecb/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeysService.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> deleteApiKey
> ```
This should get changed as well since it's not a standard delete method, but I know that needs another PR to update the API repo.
</blockquote></details>

Does it matter if it is publicly a delete. There is no undoing a revoke so as far as a public user is concerned, it is deleted.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeysService.kt, line 69 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393#-MqLNH2PA548_kn6_UK4:-MqLyVCXDTY-Io0scpc2:b-u8ucwc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55826f3d3946323bdcddd97878ebd240af846ecb/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeysService.kt#L69)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Does it matter if it is publicly a delete. There is no undoing a revoke so as far as a public user is concerned, it is deleted.
</blockquote></details>

If it's going to be called Delete, it needs to behave as a [standard delete method](https://google.aip.dev/135) as defined by the AIPs. Otherwise, we should have it be a custom method and expose the revocation status in the public API.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393)* status: 30 of 31 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeApiKey.kt, line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393#-MqLNCNZERB3urjY-qEc:-MqLSj1F7c31TL4GE8Ce:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55826f3d3946323bdcddd97878ebd240af846ecb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeApiKey.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Creates an account in the database.
> ```
Fix description
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 15 of 28 files at r1, 5 of 6 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 8 of 8 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/393)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Pull request merged**
