### PR TITLE
Refactor Metric Reuse to handle Metric State

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1564)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1564)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 173 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1564#-NvY4brI7eSBK0jryGiV:-NvY4brI7eSBK0jryGiW:bpylv03) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b723ce5adcfc55319797089947b47aa78d8d4313/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L173)):*
> ```Kotlin
>         .toSet()
> 
>     // Retrieve existing metrics and group by `MetricCalculationSpecReportingMetricKey`
> ```

nit: maybe update this comment to mention using the most recently created Metric for each key?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 377 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1564#-NvYJPzI9bSKifvL0iZo:-NvYJPzI9bSKifvL0iZp:b-scrkm9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b723ce5adcfc55319797089947b47aa78d8d4313/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L377)):*
> ```Kotlin
>                   metricId = null
>                   UUID.randomUUID()
>                 }
> ```

nit: this is effectively initializing two variables. I think this might be one of the few cases where a Pair would simplify things when combined with an immediate destructuring declaration



_Suggestion:_
```Kotlin
              val (createMetricRequestId: UUID, metricId: InternalId?) =
                if (existingReportingMetric != null) {
                  UUID.fromString(existingReportingMetric.createMetricRequestId) to existingReportingMetric.metricId
                } else {
                  UUID.randomUUID() to null
                }
```

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1564)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1564)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
