### PR TITLE
Fix K8s dev config error of missing rollv2 textproto.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1119)

**Comment by renjiezh** [comment]
Hi @SanjayVas, could you please trigger the deployment you need to verify the fix? Thanks a lot!

**Review by SanjayVas — APPROVED** [review]
Successfully deployed.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1119#-:-N_k2Y_c6uObTpuYaSGe:bajsqgk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by YuhongWang-Amazon — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1119)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
