### PR TITLE
Fix Metric.SetOperation.reporting_set to be a resource reference.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/566)

### CODE REVIEW

**Comment by SanjayVas** [comment]
CC @riemanli

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/566)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/566#-N2IalZy1I2FWj39EMxj:-N2IalZy1I2FWj39EMxk:b9lk4rt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce2eb77dc1c77bd80b7af3023a19bcf163e45c5/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L80)):*
> ```protobuf
>         string reporting_set = 1 [(google.api.resource_reference).type =
>                                       "reporting.halo-cmm.org/ReportingSet"];
>         // Nested `SetOperation`.
> ```

Nit: I feel like the previous comment provided a little more information. Can we make this a little more descriptive?

**Review by chipingyeh — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/566)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/566)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/566#-N2IalZy1I2FWj39EMxj:-N2IqMZE8tK6UkXhOxtl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce2eb77dc1c77bd80b7af3023a19bcf163e45c5/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L80)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Nit: I feel like the previous comment provided a little more information. Can we make this a little more descriptive?
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/566)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
