### PR TITLE
Update the network-config policy for kingdom and duchies.

### PR DESCRIPTION
**Pull request by wangyaopw**
- The duchy ones are missing the object-prefix.
- `from` and `podSelector` should be list object.

https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F610324078661&view=2c2927c0-626b-4740-8620-af2a93b7d623

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/299)

### CODE REVIEW

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/299)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/299)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/k8s/kingdom_and_three_duchies_gke.cue, line 175 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/299#-Mkqri9Q-Dd_bQAc6D7L:-Mkqri9R3L58hE2vP-Ed:bwp6l8k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d59a3739b4bc80e39a8efd98bd7fcbc7b5b7288/src/main/k8s/kingdom_and_three_duchies_gke.cue#L175)):*
> ```CUE
> 
> // This policy will deny ingress traffic to all unconfigured pods.
> default_deny_ingress: [{
> ```

Why not make this part of the kingdom_internal_network_policies? 

Also, this could live in base.cue as this should apply to the duchy as well, no?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/299)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/k8s/kingdom_and_three_duchies_gke.cue, line 175 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/299#-Mkqri9Q-Dd_bQAc6D7L:-MkrGYzC08AxUAlyV8MU:bt7e23f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d59a3739b4bc80e39a8efd98bd7fcbc7b5b7288/src/main/k8s/kingdom_and_three_duchies_gke.cue#L175)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Why not make this part of the kingdom_internal_network_policies? 

Also, this could live in base.cue as this should apply to the duchy as well, no? 
</blockquote></details>

This applies to all pods deployed in a cluster. So for this kingdom_and_three duchies_gke.cue, we only need one copy of this.

But yes, I agree this should live in base.cue.

Done

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/299)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[src/main/k8s/kingdom_and_three_duchies_gke.cue, line 175 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/299#-Mkqri9Q-Dd_bQAc6D7L:-MkrI62RCPFX3mnso9e3:b-pw5z1l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d59a3739b4bc80e39a8efd98bd7fcbc7b5b7288/src/main/k8s/kingdom_and_three_duchies_gke.cue#L175)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

This applies to all pods deployed in a cluster. So for this kingdom_and_three duchies_gke.cue, we only need one copy of this.

But yes, I agree this should live in base.cue.

Done
</blockquote></details>

Ah ok, makes sense. :thumbsup:

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/299)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
