### PR TITLE
Add In Process Reach Measurement Accuracy Test for HMSS.

### PR DESCRIPTION
**Pull request by ple13**
1. Fix the bug in the computation of HMSS variances: the noise variances should be computed using the method computeDistributedNoiseVariance other than computeNoiseVariance.
2. Add the in process Reach Measurement Accuracy Test for HMSS.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717)

**Review by renjiezh — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717)* status: all files reviewed, 2 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @ple13, and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717#-O34YT8l0NsgFbklyArB:-O34YT8m-JmH-8YN1dUB:b-f0b0bs) (no related file):*
Also need to update `.github/workflows/release-test.yml` to register it as a pre-release test

___
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessReachMeasurementAccuracyTest.kt` line 269 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717#-O34YkpH8ejf9HRnfajk:-O34YkpH8ejf9HRnfajl:bm1ktcw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/03254a8e9ea9b5fcd5bf818d02b680142bb6da9f/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessReachMeasurementAccuracyTest.kt#L269)):*
> ```Kotlin
> 
>   @Test
>   fun `reach-only hmss results should be accurate with respect to the variance`() = runBlocking {
> ```

What about changing it to use reach from r/f hmss? As far I as I know, people intend to use r/f in our current product env.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717)* status: all files reviewed, 2 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessReachMeasurementAccuracyTest.kt` line 269 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717#-O34YkpH8ejf9HRnfajk:-O34haD737syT1AzgxVH:b-3u6qma) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/03254a8e9ea9b5fcd5bf818d02b680142bb6da9f/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessReachMeasurementAccuracyTest.kt#L269)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

What about changing it to use reach from r/f hmss? As far I as I know, people intend to use r/f in our current product env.
</blockquote></details>

IIRC, the REACH measurement type is still useful for unique reach since you can't do set difference operations on frequency histograms. For single/union reach, it's more efficient to use R/F if you're also going to be displaying a union frequency histogram.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @jiayu-google, @kungfucraig, @renjiezh, and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717#-O34YT8l0NsgFbklyArB:-O37AYdx0Z1VxYP6BGY9:bgkcrir) (no related file):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Also need to update `.github/workflows/release-test.yml` to register it as a pre-release test
</blockquote></details>

New tests are in the same target that has been declared in release-test.yml.

___
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessReachMeasurementAccuracyTest.kt` line 269 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717#-O34YkpH8ejf9HRnfajk:-O37ADRq9RBsn4PLAzVP:b8plauh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/03254a8e9ea9b5fcd5bf818d02b680142bb6da9f/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessReachMeasurementAccuracyTest.kt#L269)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

IIRC, the REACH measurement type is still useful for unique reach since you can't do set difference operations on frequency histograms. For single/union reach, it's more efficient to use R/F if you're also going to be displaying a union frequency histogram.
</blockquote></details>

For completeness, I added a separated test that uses the reach result from reach-and-frequency measurement.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717)* status: all files reviewed, 2 unresolved discussions (waiting on @jiayu-google and @renjiezh)

**Review by renjiezh — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiayu-google)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717)* status: all files reviewed, 1 unresolved discussion (waiting on @jiayu-google and @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 478 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717#-O38qD9e6bC21ArGG5l4:-O38qD9e6bC21ArGG5l5:b97repg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d80605fbf95c579e6e7d4ae5be46b7dd87ac21ba/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L478)):*
> ```Kotlin
>     // Get the CMMS computed result and compare it with the expected result.
>     var reachAndFrequencyResult = getReachAndFrequencyResult(measurementName)
>     var nAttempts = 0
> ```

nit: Our code style does not use variable prefixes or so-called "Hungarian notation", preferring more verbose names



_Suggestion:_
```Kotlin
attemptCount
```

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @jiayu-google, @kungfucraig, @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 478 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717#-O38qD9e6bC21ArGG5l4:-O39C2crDODZtl4I143q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d80605fbf95c579e6e7d4ae5be46b7dd87ac21ba/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L478)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Our code style does not use variable prefixes or so-called "Hungarian notation", preferring more verbose names
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiayu-google and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 1 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiayu-google)

**Review by jiayu-google — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1717#-:-O3EjI2n52EKl3YClHol:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
