### PR TITLE
Update EventGroup resource pattern in Reporting v2 API.

### PR DESCRIPTION
**Pull request by SanjayVas**
This takes advantage of the secondary resource pattern for EventGroups in the CMMS API.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt` line 517 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064#-NXujV2w6nGuQcOwt6M1:-NXujV2w6nGuQcOwt6M2:b-m54yfb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/23a9fb33c242c29562c449559abb8a48e9469749/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt#L517)):*
> ```Kotlin
>   return InternalReportingSetKt.primitive {
>     eventGroupKeys +=
>       source.cmmsEventGroupsList.map { cmmsEventGroup ->
> ```

How do we make sure that the measurement consumer has the permission to those event groups? Or is that their responsibility to maintain a valid set of event groups?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt` line 517 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064#-NXujV2w6nGuQcOwt6M1:-NXumpOc6HbfamblbggQ:b854gr3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/23a9fb33c242c29562c449559abb8a48e9469749/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt#L517)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

How do we make sure that the measurement consumer has the permission to those event groups? Or is that their responsibility to maintain a valid set of event groups?
</blockquote></details>

It's up to the MC to put in EventGroups that belong to them, the same as they would when using the CMMS API. Generally they'd only have their own EGs that they got from calling ListEventGroups.

Ultimate enforcement would happen during Requisition fulfillment. An EDP should refuse Requisitions for an MC if any EventGroups don't belong to that MC.

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 9 of 14 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/reporting_set.proto` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064#-NYbRvWSAxPwpEzJYhJ0:-NYbRvWSAxPwpEzJYhJ1:b-u0lw7d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af73529f74b13355584fa9c7788dd1c0ee3c7aa9/src/main/proto/wfa/measurement/internal/reporting/v2/reporting_set.proto#L34)):*
> ```proto
>     message EventGroupKey {
>       // `DataProvider` ID from the CMMS public API.
>       string cmms_data_provider_id = 1;
> ```

Is this being used already? e.g. is the number changing allowed in this case?



_Code quote:_
```proto
1;
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/reporting_set.proto` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064#-NYbRvWSAxPwpEzJYhJ0:-NYdKzif1JFiBnWF0QFU:bg0ebsf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af73529f74b13355584fa9c7788dd1c0ee3c7aa9/src/main/proto/wfa/measurement/internal/reporting/v2/reporting_set.proto#L34)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Is this being used already? e.g. is the number changing allowed in this case?
</blockquote></details>

Yes, it's allowed because this is not yet being used. There aren't yet deployment artifacts for it, so it *can't* yet be used.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 8 of 14 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1064)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
