### PR TITLE
Use index in existing Measurements check when creating Measurements

### PR DESCRIPTION
**Pull request by tristanvuong2021**
The request ID index isn't actually being used right now. Instead, a table scan is being done. This refactors the query to actually use the index.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1641)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1641)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 429 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1641#-Nzdq3feAl_wIxZ_n_tm:-Nzdq3ff2SLsyPCxUdtc:b8r0i4h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f65d08f6c8540357de85a5cb61b5acd34e50027/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L429)):*
> ```Kotlin
>     val fromClause =
>       """
>       FROM
> ```

MeasurementReader shouldn't have a caller-specified FROM clause. More specifically, we shouldn't need to parameterize the JOINs - it should pick those values up from the WHERE clause. If you *really* think this is needed, then factor it out to a separate path in MeasurementReader rather than having the FROM clause passed by the caller.

If you just want the caller to be able to specify the index, take a look at how RecurringExchangeReader does it as an example.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1641)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 429 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1641#-Nzdq3feAl_wIxZ_n_tm:-Nze5DBN1DkxsZOJEF-m:b-adazvb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2402db9b76f6481d61546e5fe2aed78fe2412d0f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L429)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

MeasurementReader shouldn't have a caller-specified FROM clause. More specifically, we shouldn't need to parameterize the JOINs - it should pick those values up from the WHERE clause. If you *really* think this is needed, then factor it out to a separate path in MeasurementReader rather than having the FROM clause passed by the caller.

If you just want the caller to be able to specify the index, take a look at how RecurringExchangeReader does it as an example.
</blockquote></details>

The performance is much worse without this change.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1641)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 429 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1641#-Nzdq3feAl_wIxZ_n_tm:-NzeLUqX2wgMKAN6B8F1:b-r36x0w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a1f06d428df3b1a45b7005b0486c1526dea0531e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L429)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The performance is much worse without this change.
</blockquote></details>

I modeled it after RecurringExchangeReader. I just needed to make sure the null check is in the where clause.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1641)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1641)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
