### PR TITLE
Implement batchGetEventGroupMetadataDescriptors

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/590)

### CODE REVIEW

**Review by chipingyeh — COMMENTED** [review]
Not sure why build in seemingly unrelated areas; unit tests passed locally

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/590#-:-N3uylb_5XoUZCZ2xArp:b-ezv53r)* status: 0 of 3 files reviewed, all discussions resolved

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/590)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/590)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt` line 191 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/590#-N4-0_IT3LSEGx_imDhp:-N4-0_IUCFRw2fDisl1s:b8xff86) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7b3a9941785e9b5d6c5436d2ca481e3e042e87ce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L191)):*
> ```Kotlin
>           )
>         }
>       } catch (e: NullPointerException) {
> ```

Don't use an asserted non-null (`!!`) and check for NPE. NPE is used to indicate a programming error, not e.g. bad input. The `!!` operator should only be used in cases where the compiler cannot detect the invariant that something cannot be null.

Instead, explicitly check whether `fromName` returns null and throw a StatusRuntimeException (e.g. using `failGrpc`) from there.



_Code quote:_
```Kotlin
catch (e: NullPointerException) {
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt` line 202 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/590#-N4-1sbv9zai7Y5Q5bKQ:-N4-1sbv9zai7Y5Q5bKR:b-mz589n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7b3a9941785e9b5d6c5436d2ca481e3e042e87ce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L202)):*
> ```Kotlin
>     }
> 
>     val results: List<InternalEventGroupMetadataDescriptor> =
> ```

The `Stream` method does not guarantee two conditions that `BatchGet` must
1. The order of the items in the response must match the order of the resources names in the `BatchGet` request.
2. The response must contain an entry for every resource name, or else it's an error.

Stream only guarantees that it returns all results which match the filter predicate. It says nothing about their order, nor that it must contain an entry for each term in the filter predicate.

You must handle these two conditions here.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/590)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt` line 191 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/590#-N4-0_IT3LSEGx_imDhp:-N445RlTC50B8DqqRHrf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7b3a9941785e9b5d6c5436d2ca481e3e042e87ce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L191)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't use an asserted non-null (`!!`) and check for NPE. NPE is used to indicate a programming error, not e.g. bad input. The `!!` operator should only be used in cases where the compiler cannot detect the invariant that something cannot be null.

Instead, explicitly check whether `fromName` returns null and throw a StatusRuntimeException (e.g. using `failGrpc`) from there.
</blockquote></details>

Done.

**Review by chipingyeh — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/590)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

**Review by chipingyeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/590)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Pull request merged**
