### PR TITLE
Add internal Measurement state to Requisition.

### PR DESCRIPTION
**Pull request by SanjayVas**
This is needed by the public service implementation to filter the visibility of Requisitions. The Requisition message definition is moved into measurement.proto to avoid a circular dependency.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/212)

### CODE REVIEW

**Comment by SanjayVas** [comment]
This is intended to be merged into main after parent PR #211

**Review by efoxepstein — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @zachcwc)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/212)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @corbantek and @zachcwc)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)

**Comment by SanjayVas** [comment]
This is for #103.

**Pull request merged**
