### PR TITLE
Implement postgres computations service

### PR DESCRIPTION
**Pull request by YuhongWang-Amazon**
This implements postgres computations service

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089)

**Review by renjiezh — CHANGES_REQUESTED** [review]
I noticed the database reader/writer functions expand the ComputationToken into separated parameters comparing with spanner implementation. I wonder if it is a good idea regarding the consistency with spanner implementation? I'd like to know your thought s behind it.
cc. @SanjayVas 

> Reviewed 5 of 26 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-:-N_BBvsW5SfSQe_BWUDH:b-ko0znx)* status: 6 of 26 files reviewed, 4 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresComputationsService.kt` line 261 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-N_B7KvJDHkTTDCYKP1j:-N_B7KvJDHkTTDCYKP1k:b-yp6sdx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85efd75a5ace21e7f01a1f72c1b13ed1c8a0cb43/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresComputationsService.kt#L261)):*
> ```Kotlin
>       for (globalId in globalIds) {
>         val computation: ComputationReader.Computation =
>           computationReader.readComputation(client.singleUse(), globalId) ?: continue
> ```

Can we stick to use readComputationToken in service to keep consistent with spanner implementation? Thus we will never call `readComputation`. In the future we need to maintain both spanner and postgres. I think the more consistency, the better,
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/readers/ComputationReader.kt` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-N_AxSGS7kcy5j7-RBcZ:-N_AxSGS7kcy5j7-RBc_:brgkio3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85efd75a5ace21e7f01a1f72c1b13ed1c8a0cb43/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/readers/ComputationReader.kt#L46)):*
> ```Kotlin
> 
> /**
>  * Performs read operations on Computations, Requisitions, and ComputationBlobReferences tables
> ```

The responsibility of ComputationReader should be read Computations/ComputationTokens. Ideally, it should not be called to read Requisitions or BlobReferences. Besides, there is RequisitionReader and BlobReferenceReader already, thus ComputationReader is supposed to call other readers instead of having its own ReadRequisition functions (you might want to move these to RequisitionReader).
The spanner implementation uses a large single sql query to read the ComputationToken for performance. I wonder if we can do the same thing with postgres. 

My suggestion is:
1. Use a (large) single sql query to get the the ComputationToken directly. This is likely to eliminate the dependency on readRequisitions.
2. Move readComputationBlobKeys and readRequsitionBlobKeys into a new class `BlobReader`. (readGlobalComputationId is fine to be here.). Use the new class `BlobReader` in ComputationReader if needed.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/readers/ComputationReader.kt` line 240 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-N_AvZ_6-cgY7YlYzxD8:-N_AvZ_6-cgY7YlYzxD9:b-fw3w2a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85efd75a5ace21e7f01a1f72c1b13ed1c8a0cb43/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/readers/ComputationReader.kt#L240)):*
> ```Kotlin
>    * @param client The [DatabaseClient] to the Postgres database.
>    * @param globalComputationId A global identifier for a computation.
>    * @return [ComputationToken] when a Computation with globalComputationId is found. or null
> ```

nit: ... is found`, `or null...
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/writers/AdvanceComputationStage.kt` line 121 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-N_BHUU_BKNdx_LVPq8D:-N_BHUU_BKNdx_LVPq8E:b-7eimud) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85efd75a5ace21e7f01a1f72c1b13ed1c8a0cb43/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/writers/AdvanceComputationStage.kt#L121)):*
> ```Kotlin
>       details =
>         attemptDetails
>           .toBuilder()
> ```

Please avoid `toBuilder` by 
```
details = 
  attemptDetails.copy {
    reasonEnded = ComputationStageAttemptDetails.EndReason.SUCCEEDED
  }
```
As well as other occurrences.

**Review by SanjayVas — COMMENTED** [review]
@renjiezh can you point to an example line of code here?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-:-N_FF64c6-xTjmAIW8IV:bu533nu)* status: 6 of 26 files reviewed, 4 unresolved discussions (waiting on @renjiezh and @YuhongWang-Amazon)

**Review by renjiezh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089)* status: 6 of 26 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresComputationsService.kt` line 303 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-N_FMoCE-Tg2Y3yYmyaw:-N_FMoCE-Tg2Y3yYmyax:b7crerm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85efd75a5ace21e7f01a1f72c1b13ed1c8a0cb43/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresComputationsService.kt#L303)):*
> ```Kotlin
>     request: FinishComputationRequest
>   ): FinishComputationResponse {
>     FinishComputation(
> ```

@SanjayVas 
This is a example of function signatures I mentioned. Compare it with [spanner version](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0875884eab0ff7368d8350b15e11aa70aeec9e1e/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsService.kt#L208).
In spanner we wrap these parameters into a ComputationEditToken. I wonder if we want prostgres implementation to follows the same pattern?

**Review by renjiezh — CHANGES_REQUESTED** [review]
I feel it is helpful if you can break this PR into multiple parts. The database reader and writer are kinda independent so you can separate them into maybe 2 or 3 PRs. Once the database operations are merged in, you can start another PR for the ComputionService. 
Once we make one database PR approved, you can apply all the patterns to other PRs.
If we use a single large PR, I am afraid that each comment costs you tons of time to resolve. And sometimes we have to do modification back and forth. 
Please let me know your thoughts about it. I understand the pain to partition such a large PR.

> Reviewed 14 of 26 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-:-N_FUp4z340x5VCtEcs8:bb76ljl)* status: 21 of 26 files reviewed, 7 unresolved discussions (waiting on @SanjayVas and @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/readers/ComputationStageAttemptReader.kt` line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-N_FU5b96WaumFPv8aOb:-N_FU5b96WaumFPv8aOc:b-51x0hm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85efd75a5ace21e7f01a1f72c1b13ed1c8a0cb43/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/readers/ComputationStageAttemptReader.kt#L63)):*
> ```Kotlin
>   }
> 
>   suspend fun blobIdToPathMapByDepType(
> ```

This can be moved to BlobReader.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/writers/AdvanceComputationStage.kt` line 45 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-N_FRnX39DxG2cLCNADE:-N_FRnX39DxG2cLCNADF:b-9jej3c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85efd75a5ace21e7f01a1f72c1b13ed1c8a0cb43/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/writers/AdvanceComputationStage.kt#L45)):*
> ```Kotlin
>  * @param protocolStagesEnumHelper See [ComputationProtocolStagesEnumHelper].
>  */
> class AdvanceComputationStage<ProtocolT, StageT, StageDT : Message>(
> ```

Great move!
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/writers/ComputationMutations.kt` line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-N_FQG-T7hnVhMttabC6:-N_FQG-T7hnVhMttabC7:b-7kke79) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85efd75a5ace21e7f01a1f72c1b13ed1c8a0cb43/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/writers/ComputationMutations.kt#L30)):*
> ```Kotlin
> 
> /** Insert a new row into the Postgres Computations table. */
> suspend fun PostgresWriter.TransactionScope.insertComputation(
> ```

Can we follow the pattern of writers in Kingdom's spanner implementations? 
1. Use class/function name like `createComputation` instead of `insertComputation`. This applies to other `insertFoo` functions.
2. Each file only contains one type of writing operation. This means we do not collect them into a single Mutation file.

**Review by YuhongWang-Amazon — COMMENTED** [review]
I think that make sense. I also like the smaller PRs. Let me do three then. Will prepare PRs for readers, writers and then service. The only concern is that readers and writers does not have test coverage, and it might be harder to reason some implementation logics, (like parameters, return types and such.).

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-:-N_JjZax6L8qlTerGCWQ:b1ulyhp)* status: 21 of 26 files reviewed, 7 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresComputationsService.kt` line 261 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-N_B7KvJDHkTTDCYKP1j:-N_EdmDZ1VaZFA5lwS02:b5l3oau) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85efd75a5ace21e7f01a1f72c1b13ed1c8a0cb43/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/PostgresComputationsService.kt#L261)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Can we stick to use readComputationToken in service to keep consistent with spanner implementation? Thus we will never call `readComputation`. In the future we need to maintain both spanner and postgres. I think the more consistency, the better,
</blockquote></details>

I didn't use `readComputationToken` because this method will read from multiple tables (`Computations`, `ComputationStages`, `ComputationBlobReferences`, `Requisitions`). However, this method does not need the requisition and blob informations. Hence I used this method which only reads what is required. It seems that this is the only place that uses this method. I agree that it would be easier to maintain with more consistency, especially when we have two versions. Will update.

**Review by YuhongWang-Amazon — COMMENTED** [review]
@renjiezh @SanjayVas splited this into 4 PRs:
[migrate postgres package under common directory](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1103)
[Implement postgres computation readers](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1104#-N_L6sQE8Ec7Gf_HK3hb)
[Implement postgres computation writers](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1105#-N_LBqJB3I3FvHUYUkUL)
[Implement postgres computation service](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1106)

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-:-N_LSFR150l-97wCrHUl:b-pb3zjd)* status: 21 of 26 files reviewed, 7 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/readers/ComputationStageAttemptReader.kt` line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1089#-N_FU5b96WaumFPv8aOb:-N_L7rkP-BY3AOdBPUg8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/85efd75a5ace21e7f01a1f72c1b13ed1c8a0cb43/src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/readers/ComputationStageAttemptReader.kt#L63)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

This can be moved to BlobReader.
</blockquote></details>

Done.

**Pull request closed without merging**
