### PR TITLE
CMM Orchestrator

### PR DESCRIPTION
**Pull request by wfa-mdharmalingam**
We have created a flow which will deploy Deploy CMM project.  

Note: The 'Push image' function is not working because our GitHub permission were removed.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)

**Review by wfa-siyengar — APPROVED** [review]
It does not Need any permission @wfa-mdharmalingam @wfa-hkawalkar and 950 was tested.

> Reviewed 22 of 23 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-:-NT3DAf14DPrXe33Pmhe:bbv0xve)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl and @SanjayVas)

**Review by wfa-siyengar — APPROVED** [review]
Just that it cannot be tested without being Merged to main. But i have done the Straight path testing and seem working fine.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-:-NT3D_Na5U2gwV2FTrg0:bhq95zl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl and @SanjayVas)

**Comment by wfa-siyengar** [comment]
image

**Review by wfa-siyengar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, and @wfa-mdharmalingam)

___
*[`.github/workflows/create-cmm-images.yml` line 53 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTElErW-1eogSsKxld3:-NTHBuMB6IrEhQPJ7yFx:b5n7grd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/39cc4e224aaa04f25cef125e2d51780b36c25d1f/.github/workflows/create-cmm-images.yml#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There is no `token` in the `github` context. I assume this is supposed to be `secrets.GITHUB_TOKEN`?
</blockquote></details>

Hope this helps :)

https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 53 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTElErW-1eogSsKxld3:-NTLeyEAAZy6XuN0fXhq:bp7k4ka) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/39cc4e224aaa04f25cef125e2d51780b36c25d1f/.github/workflows/create-cmm-images.yml#L53)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Hope this helps :)

https://docs.github.com/en/actions/security-guides/automatic-token-authentication



</blockquote></details>

Good to know. That said, I don't know if accessing it through this context works when using workflow_call with secrets  inheritance. `secrets.GITHUB_TOKEN` may work in that case, since its the `secrets` context that's being inherited.

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 21 of 27 files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/deploy-cmm.yml` line 58 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTEmZnV4IK3cBZqb384:-NTOT5rA4CXvcMdVhDmc:b9uxezq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/39cc4e224aaa04f25cef125e2d51780b36c25d1f/.github/workflows/deploy-cmm.yml#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be calling the other workflows. As we discussed, this should be entirely possible even without env access by passing whatever is needed as inputs.
</blockquote></details>

Done. We have removed and called all the workflow from Deploy CMM.

**Review by bdomen-ggl — COMMENTED** [review]
Looks OK aside from Sanjay's comments.

> Reviewed 19 of 23 files at r1, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-:-NTOqRcYANvqfafD-P6-:beetev7)* status: 21 of 27 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @wfa-mdharmalingam, and @wfa-siyengar)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r33, 1 of 1 files at r36, 1 of 2 files at r40, 1 of 1 files at r43, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 25 of 27 files reviewed, 10 unresolved discussions (waiting on @wfa-mdharmalingam and @wfa-siyengar)

___
*[`.github/workflows/configure-duchy.yml` line 19 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPdObtCtFxoPUYDCN1:-NTPdObtCtFxoPUYDCN2:b-vksght) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/031fff3e1fd5ad980e10eb06c949919b3e247d11/.github/workflows/configure-duchy.yml#L19)):*
> ```YAML
> on:
>   workflow_call:
>   workflow_dispatch:
> ```

Why was workflow_dispatch dropped? All of these workflows should have both triggers so that they can be called manually.
___
*[`.github/workflows/configure-kingdom.yml` line 20 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPdeCEEDSgaKGilXx-:-NTPdeCEEDSgaKGilXx0:buo9nmt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/031fff3e1fd5ad980e10eb06c949919b3e247d11/.github/workflows/configure-kingdom.yml#L20)):*
> ```YAML
>   # TODO(wfa-siyengar): to detail the workflow_call.
>   workflow_call:
>   workflow_dispatch:
> ```

Same here
___
*[`.github/workflows/create-cmm-images.yml` line 22 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPdm9nCGwQDdOLlDS-:-NTPdm9nCGwQDdOLlDS0:b-p2ryvt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35002ad976a12663120c9df8134a56d1cb94c82a/.github/workflows/create-cmm-images.yml#L22)):*
> ```YAML
>     outputs:
>       image_tag:
>         description: 'Image_tag to be generated'
> ```

nit: it's an output, so it's already been pushed



_Suggestion:_
```YAML
Tag of images that were pushed
```
___
*[`.github/workflows/create-cmm-images.yml` line 29 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPfN5012P4P7TZmiJP:-NTPfN5012P4P7TZmiJQ:bfni8uo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35002ad976a12663120c9df8134a56d1cb94c82a/.github/workflows/create-cmm-images.yml#L29)):*
> ```YAML
> 
> permissions:
>   contents: 'read'
> ```

I don't think these are necessary (I've been able to run the version of this action without these)

* `read` is already the default for `contents` (otherwise actions/checkout would fail).
* `id-token` is for using GitHub's OIDC provider if you use that to authenticate to GCloud. This workflow doesn't interact with GCloud.
* The packages for these container images should already be writable, but if you find this not to be true then go ahead and leave the `packages` permission.



_Code quote:_
```YAML
permissions:
  contents: 'read'
  id-token: 'write'
  packages: 'write'
```
___
*[`.github/workflows/create-cmm-infra.yml` line 1 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPhAvK2tdqUEh-AUC_:-NTPhAvK2tdqUEh-AUCa:b-vg48lg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35002ad976a12663120c9df8134a56d1cb94c82a/.github/workflows/create-cmm-infra.yml#L1)):*
> ```YAML
> # Copyright 2023 The Cross-Media Measurement Authors
> ```

This change is part of #925 and shouldn't be in this PR. As mentioned repeatedly, each change must only exist in one PR. If one PR depends on another then the second PR should be based on the first PR's branch.
___
*[`.github/workflows/deploy-cmm.yml` line 66 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPgiyP5BHOpkU1-LI3:-NTPgiyP5BHOpkU1-LI4:bo1bb6o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35002ad976a12663120c9df8134a56d1cb94c82a/.github/workflows/deploy-cmm.yml#L66)):*
> ```YAML
>     with:
>       image_tag: ${{ needs.create-image-tag.outputs.image_tag }}
>       kubectl_apply: false #${{ inputs.kubectl_apply }}
> ```

Looks like input value is commented out and this is hard-coded to false?



_Code quote:_
```YAML
kubectl_apply: false #${{ inputs.kubectl_apply }}
```
___
*[`.github/workflows/deploy-duchy.yml` line 0 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPhLPN8pWz0WJDbQJ8:-NTPhLPN8pWz0WJDbQJ9:bhy5csx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35002ad976a12663120c9df8134a56d1cb94c82a/.github/workflows/deploy-duchy.yml#L0)):*
This change is part of #925 and shouldn't be in this PR.
___
*[`.github/workflows/deploy-kingdom.yml` line 0 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPhLlOErGtGaofhCGq:-NTPhLlOErGtGaofhCGr:bhy5csx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35002ad976a12663120c9df8134a56d1cb94c82a/.github/workflows/deploy-kingdom.yml#L0)):*
This change is part of #925 and shouldn't be in this PR.

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 23 of 27 files reviewed, 10 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/configure-kingdom.yml` line 20 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPdeCEEDSgaKGilXx-:-NTUR9-a8T36dSkKYkOt:b-ocatf8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/031fff3e1fd5ad980e10eb06c949919b3e247d11/.github/workflows/configure-kingdom.yml#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

We removed the workflow dispatch to call the workflow as the inputs were not been taken. We will add it back once the

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 23 of 27 files reviewed, 10 unresolved discussions (waiting on @bdomen-ggl, @wfa-hkawalkar, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/configure-kingdom.yml` line 20 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPdeCEEDSgaKGilXx-:-NTUVcC6AI32um8_Py32:b-ffdtg2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/031fff3e1fd5ad980e10eb06c949919b3e247d11/.github/workflows/configure-kingdom.yml#L20)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

We removed the workflow dispatch to call the workflow as the inputs were not been taken. We will add it back once the 
</blockquote></details>

I never saw a version where the inputs were specified correctly. The `inputs` section needs to be duplicated under both triggers.

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 23 of 27 files reviewed, 10 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 29 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPfN5012P4P7TZmiJP:-NTUTxp71QRF1yCzTA-J:bmjj116) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35002ad976a12663120c9df8134a56d1cb94c82a/.github/workflows/create-cmm-images.yml#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think these are necessary (I've been able to run the version of this action without these)

* `read` is already the default for `contents` (otherwise actions/checkout would fail).
* `id-token` is for using GitHub's OIDC provider if you use that to authenticate to GCloud. This workflow doesn't interact with GCloud.
* The packages for these container images should already be writable, but if you find this not to be true then go ahead and leave the `packages` permission.
</blockquote></details>

Done, we have removed the permissions.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 23 of 27 files reviewed, 10 unresolved discussions (waiting on @bdomen-ggl, @wfa-hkawalkar, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 29 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPfN5012P4P7TZmiJP:-NTUWjLw27Yc_p5_-M8F:bo3prac) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35002ad976a12663120c9df8134a56d1cb94c82a/.github/workflows/create-cmm-images.yml#L29)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

Done, we have removed the permissions.
</blockquote></details>

I still see them here. Did you forget to push before you published comments?

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 23 of 27 files reviewed, 10 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 29 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPfN5012P4P7TZmiJP:-NTUeOXv1A87lAaF7G1W:b-cat1hw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35002ad976a12663120c9df8134a56d1cb94c82a/.github/workflows/create-cmm-images.yml#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I still see them here. Did you forget to push before you published comments?
</blockquote></details>

Yes Sanjay, it is pushed. I checked again.
___
*[`.github/workflows/deploy-cmm.yml` line 18 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTEmh62E4E9_uDUdOs_:-NTUeYXf1eZ3fQHnAq0H:b-dectnx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/031fff3e1fd5ad980e10eb06c949919b3e247d11/.github/workflows/deploy-cmm.yml#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why was this TODO removed? I don't see a release trigger.
</blockquote></details>

Done. TODO is added for release.
___
*[`.github/workflows/deploy-cmm.yml` line 66 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPgiyP5BHOpkU1-LI3:-NTUeexu3x_P4q2m8rnA:b-ju0q5o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35002ad976a12663120c9df8134a56d1cb94c82a/.github/workflows/deploy-cmm.yml#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Looks like input value is commented out and this is hard-coded to false?
</blockquote></details>

I apologize Sanjay, It was for testing. It is removed now

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 23 files at r1, 1 of 2 files at r53, 1 of 1 files at r56, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 25 of 27 files reviewed, 10 unresolved discussions (waiting on @bdomen-ggl, @wfa-hkawalkar, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/duchy/gke.tf` line 26 at r56](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTUjnNc9zbVwt74fm6b:-NTUjnNdCvK3dY6U_bxf:bsvr0fv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f030cc149ba88a7b76026e85389a7ef67ebfb9e2/src/main/terraform/gcloud/duchy/gke.tf#L26)):*
> ```HCL
>   location = local.zone
>   initial_node_count = local.duchy.cluster_node_count
>  # database_encryption {
> ```

Why is this commented out? The created clusters must have their secrets encrypted with a KMS key.



_Code quote:_
```HCL
 # database_encryption {
  #  key_name = "projects/${local.project}/locations/${local.zone}/keyRings/test-key-ring/k8s-secret"
  #  state = "ENCRYPTED"
  #}
```
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 25 at r56](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTUkIhx3E5jOR4Dby1x:-NTUkIhx3E5jOR4Dby1y:bbukmcu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f030cc149ba88a7b76026e85389a7ef67ebfb9e2/src/main/terraform/gcloud/kingdom/service_account.tf#L25)):*
> ```HCL
>   display_name = "Spanner Access Service Account"
> }
> resource "google_spanner_database_iam_member" "database_iam_member" {
> ```

These appear to be changes from #925. Again, every change must only exist in a single PR.

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 19 of 27 files reviewed, 10 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/configure-duchy.yml` line 19 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPdObtCtFxoPUYDCN1:-NTYAmTnE3JpQR0j_SCC:b-9m20vf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/031fff3e1fd5ad980e10eb06c949919b3e247d11/.github/workflows/configure-duchy.yml#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why was workflow_dispatch dropped? All of these workflows should have both triggers so that they can be called manually.
</blockquote></details>

Workflow_dispactch is added with same inputs.
___
*[`.github/workflows/configure-kingdom.yml` line 20 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPdeCEEDSgaKGilXx-:-NTYAdNJ49wXQEQGgilv:byn2zmp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/031fff3e1fd5ad980e10eb06c949919b3e247d11/.github/workflows/configure-kingdom.yml#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I never saw a version where the inputs were specified correctly. The `inputs` section needs to be duplicated under both triggers.
</blockquote></details>

Done. workflow_call and workflow_dispatch has been added with same inputs.

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 19 of 27 files reviewed, 10 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/duchy/gke.tf` line 26 at r56](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTUjnNc9zbVwt74fm6b:-NTYBEMa8E-sFe1XqL_2:b-e7yzbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f030cc149ba88a7b76026e85389a7ef67ebfb9e2/src/main/terraform/gcloud/duchy/gke.tf#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this commented out? The created clusters must have their secrets encrypted with a KMS key.
</blockquote></details>

Done. the comment was for testing. I have removed the comment.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 9 of 23 files at r1, 2 of 3 files at r42, 1 of 2 files at r57, 2 of 3 files at r66, 1 of 1 files at r69, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 25 of 27 files reviewed, 9 unresolved discussions (waiting on @bdomen-ggl, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 29 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPfN5012P4P7TZmiJP:-NTZvpkZ6Vw-Nu4F6KK-:bu42cvi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35002ad976a12663120c9df8134a56d1cb94c82a/.github/workflows/create-cmm-images.yml#L29)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

Yes Sanjay, it is pushed. I checked again.
</blockquote></details>

There's still a `permissions` section on this line.

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950)* status: 24 of 27 files reviewed, 9 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 29 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/950#-NTPfN5012P4P7TZmiJP:-NTZyDpvCZ6GZOTsQe44:bumfklu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35002ad976a12663120c9df8134a56d1cb94c82a/.github/workflows/create-cmm-images.yml#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There's still a `permissions` section on this line.
</blockquote></details>

For packages the permissions are required to push images. token and  content option is removed.

**Pull request closed without merging**
