### PR TITLE
Add shaded jar for beam main

### PR DESCRIPTION
**Pull request by stevenwarejones**
* Adds a shaded jar for beam main for use with Spark
* Changes Beam Main to accept an exchange workflow instead of an exchange step

image

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1484)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1484)* status: all files reviewed, 2 unresolved discussions (waiting on @jonmolle and @stevenwarejones)

___
*[`MODULE.bazel` line 183 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1484#-NqjScXF9F60B_ea56bd:-NqjScXF9F60B_ea56be:b-cjnhxq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa059664f94ce0bb48b1d1ca5277478d38d68166/MODULE.bazel#L183)):*
> ```Starlark
>     repo_name = "com_google_riegeli",
> )
> bazel_dep(
> ```

Move this into the "Bazel Central Registry modules" section instead of the "WFA registry modules" section.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 115 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1484#-NqjTNqC46GvOCZ4KzzJ:-NqjTIX27_mJttdiyqUO:be59vmn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa059664f94ce0bb48b1d1ca5277478d38d68166/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L115)):*
> ```Kotlin
>   }
> 
>   @Option(
> ```

Resource key and resource ID are not interchangeable terms. I assume this is a resource ID from the CMMS public API? If so, use "id" instead of "key" in the option and variable names.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1484)* status: all files reviewed, 2 unresolved discussions (waiting on @jonmolle and @SanjayVas)

___
*[`MODULE.bazel` line 183 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1484#-NqjScXF9F60B_ea56bd:-NqjV9Zp5sZd-N0wTkMZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa059664f94ce0bb48b1d1ca5277478d38d68166/MODULE.bazel#L183)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move this into the "Bazel Central Registry modules" section instead of the "WFA registry modules" section.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 115 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1484#-NqjTNqC46GvOCZ4KzzJ:-NqjVU-xAXtsDgXux7rV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa059664f94ce0bb48b1d1ca5277478d38d68166/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Resource key and resource ID are not interchangeable terms. I assume this is a resource ID from the CMMS public API? If so, use "id" instead of "key" in the option and variable names.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1484)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

**Pull request merged**
