### PR TITLE
feat: Add new filter for checking externalComputationId, and checking externalComputationId if view is COMPUTATION or COMPUTATION_STATS

### PR DESCRIPTION
**Pull request by tristanvuong2021**
feat: Add new filter for checking externalComputationId, and checking externalComputationId if view is COMPUTATION or COMPUTATION_STATS

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt` line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753#-O4CWZaZ6OR9b3a8fi2c:-O4CWZaZ6OR9b3a8fi2d:b4pddvj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/acc35e0bce9fd2976ffd8146989f3f39693e8337/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L91)):*
> ```Kotlin
>       val conjuncts = mutableListOf<String>()
> 
>       if (view == Measurement.View.COMPUTATION) {
> ```

The view shouldn't filter, but rather should error. Filtering should *only* happen based on the `filter` field.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt` line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753#-O4CWZaZ6OR9b3a8fi2c:-O4Calzp4RyXe05RviRU:b5m6yb2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/acc35e0bce9fd2976ffd8146989f3f39693e8337/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L91)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The view shouldn't filter, but rather should error. Filtering should *only* happen based on the `filter` field.
</blockquote></details>

If I filter then that would imply that including direct measurements is possible.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt` line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753#-O4CWZaZ6OR9b3a8fi2c:-O4Cb4Jl9AAnhfAPtabE:b2l87s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/acc35e0bce9fd2976ffd8146989f3f39693e8337/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L91)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

If I filter then that would imply that including direct measurements is possible.
</blockquote></details>

*If I filter based on a filter field*

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt` line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753#-O4CWZaZ6OR9b3a8fi2c:-O4Cc9Lw-oah-zL1gQs_:b-9mrglw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/acc35e0bce9fd2976ffd8146989f3f39693e8337/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L91)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

*If I filter based on a filter field*
</blockquote></details>

I can leave a comment mentioning that it will throw an error if the wrong value is set and the view is COMPUTATION.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt` line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753#-O4CWZaZ6OR9b3a8fi2c:-O4CbEEI0cRtgqNczQ6C:b-hbqhnf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/acc35e0bce9fd2976ffd8146989f3f39693e8337/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L91)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I can leave a comment mentioning that it will throw an error if the wrong value is set and the view is COMPUTATION.
</blockquote></details>

I'm saying that using the COMPUTATION view when the filter does not cause the result to only contain Measurements having computations IDs should be an error. Our existing use cases avoid this as they always filter by computation participant (Duchy) ID.

What this PR should do is:
1. Add a way to filter based on the presence of computation ID (e.g. `having_computation_id`).
2. (Optional) error if we'd return any rows without computation IDs when the view is COMPUTATION, documenting this behavior.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt` line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753#-O4CWZaZ6OR9b3a8fi2c:-O4CuSRi9vjXbb6x5L4J:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/acc35e0bce9fd2976ffd8146989f3f39693e8337/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L91)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm saying that using the COMPUTATION view when the filter does not cause the result to only contain Measurements having computations IDs should be an error. Our existing use cases avoid this as they always filter by computation participant (Duchy) ID.

What this PR should do is:
1. Add a way to filter based on the presence of computation ID (e.g. `having_computation_id`).
2. (Optional) error if we'd return any rows without computation IDs when the view is COMPUTATION, documenting this behavior.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt` line 148 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753#-O4Curuh42gSkgyLSziH:-O4Curuh42gSkgyLSziI:b14lvpf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e3dff2970fb75172d4fd2ba499c238de61a774e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L148)):*
> ```Kotlin
>       .catch {
>         if (it is MeasurementNotComputationException) {
>           throw it.asStatusRuntimeException(Status.Code.INVALID_ARGUMENT, "Measurement that is not Computation found")
> ```

nit: this is not INVALID_ARGUMENT, as whether the error condition depends on the system state (i.e. whether there are any filtered rows without a computation ID). For example, the error is not thrown if the filter would allow direct Measurements, but there don't happen to be any.

If instead the error condition was based on the filters themselves (e.g. whether hasExtenrnalComputationId is true or whether the filter contains an external computation ID), then this would make sense as INVALID_ARGUMENT.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 44 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753#-O4CwNjh4Zuv3K4AZFsh:-O4CwNjh4Zuv3K4AZFsi:b-w35uvh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e3dff2970fb75172d4fd2ba499c238de61a774e/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L44)):*
> ```proto
>   //
>   // If the view is `Measurement.View.COMPUTATION` and the response contains
>   // Measurements that aren't Computations, then an error is returned.
> ```

nit: this should probably be about whether the filter ensures that no values without computation IDs would be returned (see above comment)



_Code quote:_
```proto
  // If the view is `Measurement.View.COMPUTATION` and the response contains
  // Measurements that aren't Computations, then an error is returned.
```

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 94 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753#-O4Cwfc0-WrcRr5Pxbh_:-O4Cwfc0-WrcRr5Pxbha:bix81nh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e3dff2970fb75172d4fd2ba499c238de61a774e/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L94)):*
> ```proto
>     repeated Measurement.State states = 3;
>     google.protobuf.Timestamp updated_after = 4;
>     string externalDuchyId = 7;
> ```

nit: maybe fix this while in here? It shouldn't really change the generated code



_Suggestion:_
```proto
external_duchy_id
```

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
Can you elaborate under what scenarios this exception would be expected to be thrown?

> Reviewed 2 of 8 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753#-:-O4DkV4g5wphYH1H_3iy:b-7zjdd4)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 8 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1753)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
