### PR TITLE
Set measurement results for direct measurements.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: 1 of 13 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[build/repositories.bzl, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N--4zN6CFLzkC1Y2kdT:-N--4zN7CRcFK-eU3W7m:b-gjh4gv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a185888e6bde696edca7dd7be7fdef0b22f7d03/build/repositories.bzl#L41)):*
> ```Starlark
>         name = "wfa_measurement_proto",
>         repo = "cross-media-measurement-api",
>         sha256 = "92836ba83e00303a65cbb76331a83f58de9129c918722e9dd7c4bd25fa0f33cd",
> ```

Add DO_NOT_SUBMIT comment here to use appropriate version before submitting.
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement.proto, line 130 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N--5Qrv-azWsufZjvmU:-N--5Qrv-azWsufZjvmV:b-hd91hy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a185888e6bde696edca7dd7be7fdef0b22f7d03/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L130)):*
> ```protobuf
> 
>     message ResultInfo {
>       oneof certificate_parent {
> ```

Cross-references to other resources/entities shouldn't go in Details. In the DB, we should have all the foreign key references in place. In this case, we need to reference multiple rows in the *Certificates table for each Measurement. The standard way to do this in a relational DB would be another table (e.g. `MeasurementResultCertificates`), where each row is a Measurement->*Certificate mapping.

This maybe need to be multiple tables (one for each corresponding parent type), or maybe you can do it with separate columns for the different parent IDs. Not sure what comes out cleaner.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[build/repositories.bzl, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N--4zN6CFLzkC1Y2kdT:-N-3MsVRDdXojJwojgNd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a185888e6bde696edca7dd7be7fdef0b22f7d03/build/repositories.bzl#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add DO_NOT_SUBMIT comment here to use appropriate version before submitting.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement.proto, line 130 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N--5Qrv-azWsufZjvmU:-N-3MtHEEgYHggo3pxas:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a185888e6bde696edca7dd7be7fdef0b22f7d03/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L130)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Cross-references to other resources/entities shouldn't go in Details. In the DB, we should have all the foreign key references in place. In this case, we need to reference multiple rows in the *Certificates table for each Measurement. The standard way to do this in a relational DB would be another table (e.g. `MeasurementResultCertificates`), where each row is a Measurement->*Certificate mapping.

This maybe need to be multiple tables (one for each corresponding parent type), or maybe you can do it with separate columns for the different parent IDs. Not sure what comes out cleaner.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: 6 of 14 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 345 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-59ti16DHXhIKCi2JN:-N-59ti16DHXhIKCi2JO:b-d9tkwc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/72ebbae62fe6140bb1a788c41d1482b357bc796d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L345)):*
> ```
> CREATE INDEX RequisitionsByState ON Requisitions(DataProviderId, State);
> 
> CREATE TABLE DuchyCertificates (
> ```

nit: leave this where it was if it's not necessary to move to avoid an unnecessary diff
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 420 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-59OXj1-R_rj36j5J6:-N-59OXj1-R_rj36j5J7:b-i0jssz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/72ebbae62fe6140bb1a788c41d1482b357bc796d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L420)):*
> ```
>   ON DuchyMeasurementLogEntries(DuchyId, ExternalComputationLogEntryId);
> 
> CREATE TABLE MeasurementResultDataProviderCertificates (
> ```

Since this contains the result itself rather than just being a certificate relation, maybe `DataProviderMeasurementResults`/`DuchyMeasurementResults`?

Note: see later comment about Requisitions



_Code quote:_
```
MeasurementResultDataProviderCertificates
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 437 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-5972k0dLPnUxRD-0c:-N-5972lD17b-hppF0Tx:bi5mat8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/72ebbae62fe6140bb1a788c41d1482b357bc796d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L437)):*
> ```
>   INTERLEAVE IN PARENT Measurements ON DELETE CASCADE;
> 
> CREATE TABLE MeasurementResultAggregatorDuchyCertificates (
> ```

nit: probably don't need the aggregator distinction anymore



_Code quote:_
```
Aggregato
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 176 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-5CDz-7Q0TmTK7h2Is:-N-5CDz-7Q0TmTK7h2It:b-9q8rz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/72ebbae62fe6140bb1a788c41d1482b357bc796d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L176)):*
> ```Kotlin
>     encryptedResult: ByteString
>   ) {
>     StreamRequisitions(
> ```

Sorry for the churn. I just realized seeing this part that we actually have a place to store per-EDP results and certificates already: within each Requisition! We don't need a separate table at all.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: 6 of 14 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 437 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-5972k0dLPnUxRD-0c:-N-5FPCn4DrATo5uVfeK:bez57a0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/72ebbae62fe6140bb1a788c41d1482b357bc796d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L437)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: probably don't need the aggregator distinction anymore
</blockquote></details>

Should I even keep this table then it will just be the aggregator setting the results, or would keeping this table be preferred since the results wouldn't always come from the aggregator duchy.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: 2 of 14 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 176 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-5CDz-7Q0TmTK7h2Is:-N-5Qohs5k9Ely2IKELc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/72ebbae62fe6140bb1a788c41d1482b357bc796d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L176)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry for the churn. I just realized seeing this part that we actually have a place to store per-EDP results and certificates already: within each Requisition! We don't need a separate table at all.
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: 2 of 14 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 420 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-59OXj1-R_rj36j5J6:-N-5TQ08707zA4zXjQPv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/72ebbae62fe6140bb1a788c41d1482b357bc796d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L420)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since this contains the result itself rather than just being a certificate relation, maybe `DataProviderMeasurementResults`/`DuchyMeasurementResults`?

Note: see later comment about Requisitions
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1, 5 of 13 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 437 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-5972k0dLPnUxRD-0c:-N-5e-q0-0YkBabnHn8t:b-2e960l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/72ebbae62fe6140bb1a788c41d1482b357bc796d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L437)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Should I even keep this table then it will just be the aggregator setting the results, or would keeping this table be preferred since the results wouldn't always come from the aggregator duchy.
</blockquote></details>

Up to you. The public API supports multiple Duchy results, but it's also an output-only field so it need not be supported by the underlying implementation. Maybe simpler to just keep the columns in Measurement?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 294 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-5f3toATyi4SrQ3WOF:-N-5f3toATyi4SrQ3WOG:b-kj3icr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a70be3c406338eaf35a265f9bb8aaf8bf90a33ab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L294)):*
> ```Kotlin
>     }
> 
>     if (measurementSucceeded) {
> ```

Shouldn't this only be if the Requisition has a result?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 437 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-5972k0dLPnUxRD-0c:-N-5nIeX574u19Z-CLqN:b8jv5o1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/72ebbae62fe6140bb1a788c41d1482b357bc796d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L437)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Up to you. The public API supports multiple Duchy results, but it's also an output-only field so it need not be supported by the underlying implementation. Maybe simpler to just keep the columns in Measurement?
</blockquote></details>

I will just keep it this way so it doesn't look like the results are only stored in Measurement.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 294 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-5f3toATyi4SrQ3WOF:-N-5n_EgCzngAJhBLr14:bt2ejqh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a70be3c406338eaf35a265f9bb8aaf8bf90a33ab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L294)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this only be if the Requisition has a result?
</blockquote></details>

If the measurement succeeded, then all the requisitions have something. If a requisition is refused, the measurement is set to failed.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 294 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-5f3toATyi4SrQ3WOF:-N-5v72iAmpYa6mesRd9:bt5pqgw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a70be3c406338eaf35a265f9bb8aaf8bf90a33ab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L294)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

If the measurement succeeded, then all the requisitions have something. If a requisition is refused, the measurement is set to failed.
</blockquote></details>

Just realized what you meant. Will fix.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: 9 of 14 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 294 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516#-N-5f3toATyi4SrQ3WOF:-N-5yzAaAZ-H4s07FfXZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a70be3c406338eaf35a265f9bb8aaf8bf90a33ab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L294)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Just realized what you meant. Will fix.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 13 files at r2, 2 of 5 files at r3, 2 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 6 of 13 files at r2, 2 of 3 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/516)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
