### PR TITLE
Add corresponding seed encryption key in HMSS requisitions.

### PR DESCRIPTION
**Pull request by renjiezh**
SetParticipantRequisitionParams() called by the last participant will set the fulfillingDuchyId among workers based on the requisitionId.
ListRequisitions() will inject seed encryption key to the corresponding duchyEntry w.r.t fulfillingDuchyId. 
The kingdom does not really know the role of duchies, so it check whether the tinkPublicKey is empty to tell.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585)* status: all files reviewed, 5 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt` line 171 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585#-NwGGPEDE_fKuY17snnZ:-NwGGPEE9xqeM1t6lr9b:b-7uf2tm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15988a8c4cd87b2137b6e758842c32817e3a3e68/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L171)):*
> ```Kotlin
>     }
> 
>     val otherComputationParticipants =
> ```

Why did the type information get dropped?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt` line 207 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585#-NwGJLlbCabJ4QVrpSoA:-NwGJLlbCabJ4QVrpSoB:brdddl7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15988a8c4cd87b2137b6e758842c32817e3a3e68/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L207)):*
> ```Kotlin
>         .collect {
>           transactionContext.bufferUpdateMutation("Requisitions") {
>             val requisitionId = it.getLong("RequisitionId")
> ```

nit: move this declaration outside of the bufferUpdateMutation lambda
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt` line 285 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585#-NwGIuB49K51Z9OgGSxD:-NwGIuB49K51Z9OgGSxE:b-y70h0w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15988a8c4cd87b2137b6e758842c32817e3a3e68/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L285)):*
> ```Kotlin
>   }
> 
>   private fun selectFulfillingDuchyId(
> ```

Leave a TODO here for changing this when the HMSS Duchy role is in config, as in that case the "candidate" worker selection can be handled on Measurement creation.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt` line 313 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585#-NwGHefR8hN1xgcDiY0f:-NwGHefR8hN1xgcDiY0g:bnjpzwu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15988a8c4cd87b2137b6e758842c32817e3a3e68/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L313)):*
> ```Kotlin
> 
>     candidateDuchyIds.sort()
>     return candidateDuchyIds[requisitionId.toInt() % candidateDuchyIds.size]
> ```

This is truncating the ID to an Int before the mod operator. We instead just need to convert the remainder to an Int so it's a valid list index.



_Suggestion:_
```Kotlin
(requisitionId % candidateDuchyIds.size).toInt()
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt` line 475 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585#-NwGK9IX-7sJqBe7Qdc8:-NwGK9IX-7sJqBe7Qdc9:b-hj9aa0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15988a8c4cd87b2137b6e758842c32817e3a3e68/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L475)):*
> ```Kotlin
>   val source = this
>   return DuchyEntryKt.honestMajorityShareShuffle {
>     if (addingEncryptionKey) {
> ```

nit: since the function behavior is almost completely different when this boolean is set, perhaps two different functions instead? e.g. `toDuchyEntryHmssWithPublicKey`?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt` line 171 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585#-NwGGPEDE_fKuY17snnZ:-NwLM1roEXA6nL_UQNk_:b-ex724p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15988a8c4cd87b2137b6e758842c32817e3a3e68/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L171)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why did the type information get dropped?
</blockquote></details>

Added it back.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt` line 285 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585#-NwGIuB49K51Z9OgGSxD:-NwLM5Jz1HL0VlF2Brm3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15988a8c4cd87b2137b6e758842c32817e3a3e68/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L285)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Leave a TODO here for changing this when the HMSS Duchy role is in config, as in that case the "candidate" worker selection can be handled on Measurement creation.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt` line 313 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585#-NwGHefR8hN1xgcDiY0f:-NwLMHM1BBVtlO9Wh6ux:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15988a8c4cd87b2137b6e758842c32817e3a3e68/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L313)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is truncating the ID to an Int before the mod operator. We instead just need to convert the remainder to an Int so it's a valid list index.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by ple13 — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1585)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
