### PR TITLE
modelline internal api

### PR DESCRIPTION
**Pull request by Marco-Premier**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987)* status: all files reviewed, 12 unresolved discussions (waiting on @jcorilla, @jojijac0b, @Marco-Premier, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelLinesService.kt` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBxKz18YG1RNT0KhM9:-NVBxKz18YG1RNT0KhMA:b-clb9tt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelLinesService.kt#L48)):*
> ```Kotlin
>   override suspend fun createModelLine(request: ModelLine): ModelLine {
>     grpcRequire(request.hasActiveStartTime()) {
>       "ActiveStartTime field of ModelLine is missing fields."
> ```

Just "is missing"
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelLine.kt` line 137 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBupoY1S3t06YE2Xc5:-NVBupoY1S3t06YE2Xc6:bg5b1si) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelLine.kt#L137)):*
> ```Kotlin
>         set("HoldbackModelLine" to holdbackModelLineResult.modelLineId)
>       }
>       set("CreateTime" to Value.COMMIT_TIMESTAMP)
> ```

set the UpdateTime too.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt` line 242 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBtadAD40ljTZkBlM4:-NVBtadAD40ljTZkBlM5:b-hubf3k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L242)):*
> ```Kotlin
>     }
>     require(!exchangeStepAttempt.state.isTerminal) {
>       "Attempt for Step: ${exchangeStepAttempt.stepIndex} " + "."
> ```

Why is the terminal state part removed.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBwsVw0h_2UP-LasmI:-NVBwsVw0h_2UP-LasmJ:b-mt82wc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L19)):*
> ```Kotlin
> package org.wfanet.measurement.kingdom.service.internal.testing
> 
> import com.google.common.truth.Truth
> ```

Only assertThat is used so the imports can be ...Truth.assertThat and ....ProtoTruth.assertThat
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBwbby-WNsvwtHwQ7n:-NVBwbby-WNsvwtHwQ7o:b-kuguq3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L81)):*
> ```Kotlin
> 
>   @Test
>   fun `createModelLine fails for missing fields`() = runBlocking {
> ```

Test name should include what field is missing.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBzFQIAkdvND9pUEK_:-NVBzFQIAkdvND9pUEKa:b-sws6ba) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L101)):*
> ```Kotlin
> 
>   @Test
>   fun `createModelLine fails for wrong activeStartTime fields`() = runBlocking {
> ```

Should be more explicitly like the other test names in this file. In this case, activeStartTime is in the past.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBzQQG4xUIdmdTA-tM:-NVBzQQG4xUIdmdTA-tN:bielos1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L121)):*
> ```Kotlin
> 
>   @Test
>   fun `createModelLine fails for wrong activeEndTime fields`() = runBlocking {
> ```

Same thing with the test name here. ActiveEndTime before ActiveStartTime
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBzb3AEi2dpAGclTyp:-NVBzb3AEi2dpAGclTyq:b8b1yzx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L144)):*
> ```Kotlin
> 
>   @Test
>   fun `createModelLine fails for wrong type fields`() = runBlocking {
> ```

Same thing with the test name here. Type is TYPE_UNSPECIFIED
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 203 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVC-3V43E59r7L3ErWD:-NVC-3V43E59r7L3ErWE:b-5bbowz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L203)):*
> ```Kotlin
> 
>   @Test
>   fun `createModelLine fails if HoldbackModelLine is set has type != 'HOLDBACK'`() = runBlocking {
> ```

"but has". If the name is too long, you can always put the runBlocking { on the next line
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVC-H1M5xKWQVyhK9_q:-NVC-H1M5xKWQVyhK9_r:b7abln9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L236)):*
> ```Kotlin
>       .hasMessageThat()
>       .contains(
>         "Only ModelLines with type equal to 'PROD' can have a HoldbackModelLine having type equal to 'HOLDBACK'."
> ```

This isn't the right error. The model line does have type prod so the error should be about the HoldBackModelLine.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 324 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVByG1O5hTsBTl9droB:-NVByG1O5hTsBTl9droC:bmdnyan) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L324)):*
> ```Kotlin
> 
>   @Test
>   fun `setActiveEndTime fails if ActiveEndTime is in older than ActiveStartTime`() = runBlocking {
> ```

"ActiveEndTime is before ActiveStartTime"
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVC-eec8gMKJ3Z7jQ7u:-NVC-eec8gMKJ3Z7jQ7v:b-qjwxtu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto#L42)):*
> ```protobuf
>     int64 external_model_provider_id = 1;
>     int64 external_model_suite_id = 2;
>     google.protobuf.Timestamp created_after = 3;
> ```

Same issue as the other PR. If we want to handle possible exact same create times, there would need to be a new message that contains the created_after and the ids for the model line to skip to.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987)* status: 14 of 20 files reviewed, 12 unresolved discussions (waiting on @jcorilla, @jojijac0b, @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelLinesService.kt` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBxKz18YG1RNT0KhM9:-NVDzjih3UA_-5zZicOS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelLinesService.kt#L48)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Just "is missing"
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelLine.kt` line 137 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBupoY1S3t06YE2Xc5:-NVE-6bKEHOl8JJO9Wbt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelLine.kt#L137)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

set the UpdateTime too.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBwsVw0h_2UP-LasmI:-NVE-nxgC_OlId6KfUuR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L19)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Only assertThat is used so the imports can be ...Truth.assertThat and ....ProtoTruth.assertThat
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBwbby-WNsvwtHwQ7n:-NVE03ZY1jL5ztKTVa_c:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L81)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Test name should include what field is missing.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBzFQIAkdvND9pUEK_:-NVE0H7HElLvDRy7xPhq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L101)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Should be more explicitly like the other test names in this file. In this case, activeStartTime is in the past.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBzQQG4xUIdmdTA-tM:-NVE0RSI3ENuDoQ_ejTJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L121)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Same thing with the test name here. ActiveEndTime before ActiveStartTime
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBzb3AEi2dpAGclTyp:-NVE0d50BEal3cf4GmWG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L144)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Same thing with the test name here. Type is TYPE_UNSPECIFIED
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 203 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVC-3V43E59r7L3ErWD:-NVE0s0dEiusp9ix9hK4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L203)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

"but has". If the name is too long, you can always put the runBlocking { on the next line
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVC-H1M5xKWQVyhK9_q:-NVE3-ELAkZmWUiO0lFj:bcbdwog) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L236)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This isn't the right error. The model line does have type prod so the error should be about the HoldBackModelLine.
</blockquote></details>

that's right. I no longer override the error message in ```SpannerModelLineService``` and I let the message come directly from ```CreateModelLine``` spanner which is more specific
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt` line 324 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVByG1O5hTsBTl9droB:-NVE19tg92FpUJyDvEKn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt#L324)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

"ActiveEndTime is before ActiveStartTime"
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVC-eec8gMKJ3Z7jQ7u:-NVEF15y2clOv0XtX2CD:bqx7l82) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto#L42)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Same issue as the other PR. If we want to handle possible exact same create times, there would need to be a new message that contains the created_after and the ids for the model line to skip to.
</blockquote></details>

right. thanks
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt` line 242 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVBtadAD40ljTZkBlM4:-NVEFv9g8ulNlvHO3Rri:brxhxjj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L242)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Why is the terminal state part removed.
</blockquote></details>

This was an error. I revert changes introduced by this PR

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987)* status: all files reviewed, 3 unresolved discussions (waiting on @jcorilla, @jojijac0b, @Marco-Premier, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelLines.kt` line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVFzGy12q4U9Nctlukw:-NVFzGy12q4U9Nctlukx:btd1ejs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/32a95ccea8f400a652496ab069ef3daa5aede67e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelLines.kt#L54)):*
> ```Kotlin
>     if (filter.hasCreatedAfter()) {
>       if (filter.externalModelLineId != 0L) {
>         println("================================================= filtro presente")
> ```

the print statement
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelLines.kt` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVFzgi03i-0-BUiHxfX:-NVFzgi03i-0-BUiHxfY:bi5d1xx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/32a95ccea8f400a652496ab069ef3daa5aede67e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelLines.kt#L58)):*
> ```Kotlin
>           """
>           ((ModelLines.CreateTime  > @${CREATED_AFTER})
>           OR (ModelLines.CreateTime  > @${CREATED_AFTER}
> ```

the second createTime comparison should be =
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVC-eec8gMKJ3Z7jQ7u:-NVFzolH4XWpLkSdkoD7:b1bbdkm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto#L42)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

right. thanks
</blockquote></details>

I know it wasn't done this way in other files which was a mistake, but there should be a separate message that contains the create_time and external_model_line_id that is used for a single after field in the filter. This would then make it a proper conjunction.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987)* status: 17 of 20 files reviewed, 3 unresolved discussions (waiting on @jcorilla, @jojijac0b, @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelLines.kt` line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVFzGy12q4U9Nctlukw:-NVT8yD0E9hde6cFHA7j:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/32a95ccea8f400a652496ab069ef3daa5aede67e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelLines.kt#L54)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

the print statement
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelLines.kt` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVFzgi03i-0-BUiHxfX:-NVT9L6s5WQ_7vkkqLuq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/32a95ccea8f400a652496ab069ef3daa5aede67e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelLines.kt#L58)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

the second createTime comparison should be =
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-NVC-eec8gMKJ3Z7jQ7u:-NVTE8Pm9bipCP9dPlp7:bwyxxww) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7a1d6f734528fb276c79375d4e79449bd35426/src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto#L42)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I know it wasn't done this way in other files which was a mistake, but there should be a separate message that contains the create_time and external_model_line_id that is used for a single after field in the filter. This would then make it a proper conjunction.
</blockquote></details>

I see. I wrapped those 2 fields in a new message ```AfterField```. Not entirely sure whether we want to use a different  name for this kind of filter? 
thanks

**Review by jojijac0b — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987#-:-NVUmsLT5JYgVK9s-jci:bnfp4nl)* status: 16 of 20 files reviewed, 3 unresolved discussions (waiting on @jcorilla, @riemanli, @stevenwarejones, and @tristanvuong2021)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 11 of 20 files at r1, 3 of 6 files at r2, 1 of 4 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/987)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla, @riemanli, and @stevenwarejones)

**Pull request merged**
