### PR TITLE
Implement Public Report Schedules Create Method.

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335)

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335)* status: 4 of 7 files reviewed, 7 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 984 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjPVWNb4k2c6xNQPV8V:-NjPVWNb4k2c6xNQPV8W:b-b4mq6m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/240d8ba5f604a3e2c8f29ca4b740182f6b089819/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L984)):*
> ```Kotlin
>  */
> fun DateTime.toTimestamp(): Timestamp {
>   return if (hasUtcOffset()) {
> ```

nit: Consider using the convention we have as following

```kotlin
val source = this
return if (source.hasUtcOffset()) {
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 999 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjPVjcX38Tvv2Cjfofj:-NjPVjcX38Tvv2Cjfofk:behdd8s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/240d8ba5f604a3e2c8f29ca4b740182f6b089819/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L999)):*
> ```Kotlin
>  * window.
>  */
> fun buildReportWindowStartTimestamp(
> ```

IMHO, this is not really a conversion method. Mind considering to put this function to `ReportSchedulesService`?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 464 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjPdf_OB_FyPl3RvhHI:-NjPdf_OB_FyPl3RvhHJ:bpfu3dv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/240d8ba5f604a3e2c8f29ca4b740182f6b089819/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L464)):*
> ```Kotlin
>             this.externalMetricCalculationSpecIds += items
>           }
>         )
> ```

Does `batchGetMetricCalculationSpecs` have limit?



_Code quote:_
```Kotlin
        internalMetricCalculationSpecsStub.batchGetMetricCalculationSpecs(
          batchGetMetricCalculationSpecsRequest {
            cmmsMeasurementConsumerId = measurementConsumerKey.measurementConsumerId
            this.externalMetricCalculationSpecIds += items
          }
        )
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 859 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjPjXez-IdeqC48Tmuz:-NjPjXez-IdeqC48Tmv-:bjpr8e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/240d8ba5f604a3e2c8f29ca4b740182f6b089819/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L859)):*
> ```Kotlin
>       for (internalReportingSet in internalReportingSets) {
>         if (internalReportingSet.hasPrimitive()) {
>           for (eventGroupKey in internalReportingSet.primitive.eventGroupKeysList) {
> ```

Since you only need `eventGroupKey`s, you could get a set of `eventGroupKey`s beforehand and replace `internalReportingSets` with it.



_Code quote:_
```Kotlin
      for (internalReportingSet in internalReportingSets) {
        if (internalReportingSet.hasPrimitive()) {
          for (eventGroupKey in internalReportingSet.primitive.eventGroupKeysList) {
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjKW4WlCME5PDLixKyn:-NjKW4WlCME5PDLixKyo:b-elauc9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/240d8ba5f604a3e2c8f29ca4b740182f6b089819/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L55)):*
> ```proto
> 
>   // Template for every `Report` that is created. `time` is ignored. The
>   // `MetricCalculationSpec` used cannot have cumulative set to true.
> ```

Any reason why we can't set `cumulative` to true?



_Code quote:_
```proto
// `MetricCalculationSpec` used cannot have cumulative set to true.
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjPZcpzDCcK8mmaQDpL:-NjPZcpzDCcK8mmaQDpM:b-p074d2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/240d8ba5f604a3e2c8f29ca4b740182f6b089819/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L59)):*
> ```proto
> 
>   // Specifies when the scheduling will start as well as the time of day used
>   // for every `Report`. `year`, `month, `day`, and `time_offset` are
> ```

What does `as well as the time of day used for every Report` mean?



_Code quote:_
```proto
  // Specifies when the scheduling will start as well as the time of day used
  // for every `Report`. `year`, `month, `day`, and `time_offset` are
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 95 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjP_POYCMaPklnVU6l3:-NjP_POYCMaPklnVU6l4:b-1zen0f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/240d8ba5f604a3e2c8f29ca4b740182f6b089819/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L95)):*
> ```proto
> 
>   // Defines the time interval that a `Report` will cover.
>   message ReportWindow {
> ```

Could you explain how a `ReportWindow` is used and the use cases?



_Code quote:_
```proto
message ReportWindow
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 999 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjPVjcX38Tvv2Cjfofj:-NjSwgez5yDlJJa2imhv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4da3e29a60a3a7047bcb79322d2da1449e66a3e/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L999)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

IMHO, this is not really a conversion method. Mind considering to put this function to `ReportSchedulesService`?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 859 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjPjXez-IdeqC48Tmuz:-NjSyZ8J70TgqA2H3Y4n:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4da3e29a60a3a7047bcb79322d2da1449e66a3e/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L859)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Since you only need `eventGroupKey`s, you could get a set of `eventGroupKey`s beforehand and replace `internalReportingSets` with it.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjKW4WlCME5PDLixKyn:-NjT-25G5TqJEC7-JKQz:b-yiiz98) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4da3e29a60a3a7047bcb79322d2da1449e66a3e/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L55)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Any reason why we can't set `cumulative` to true?
</blockquote></details>

I thought about it and realized I could just create a periodic time interval with an increment of 1 if cumulative is true.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjPZcpzDCcK8mmaQDpL:-NjT-Fxw1n4nqZB_3Pum:b-gv9ex1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4da3e29a60a3a7047bcb79322d2da1449e66a3e/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L59)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

What does `as well as the time of day used for every Report` mean?
</blockquote></details>

A Report will be anchored on a chosen time. If the time is 6 AM, New York, then every Report created under the schedule will go from 6 AM on the first day of the time interval to 6 AM on the last day of the time interval.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 95 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjP_POYCMaPklnVU6l3:-NjT-dz-4fVuBgpTCQXP:b3pgqag) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4da3e29a60a3a7047bcb79322d2da1449e66a3e/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L95)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Could you explain how a `ReportWindow` is used and the use cases?
</blockquote></details>

The ReportWindow is a lookback window. For a trailing window, say the next Report is scheduled for Nov 16 and the increment is DAY and the count is 5 days. Then the Report will cover Nov 11 to Nov 16. If the following Report is scheduled for Nov 23, then the Report will cover Nov 18 to Nov 23. For a fixed window, say the next Report is scheduled for Nov 16 and the date set for the fixed window is Nov 1, then the Report will cover Nov 1 to Nov 16. If the following Report is scheduled for Nov 23, then the Report will cover Nov 1 to Nov 23.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 464 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335#-NjPdf_OB_FyPl3RvhHI:-NjTAbXoAfZ5JbCWJtOU:b27eib1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4da3e29a60a3a7047bcb79322d2da1449e66a3e/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L464)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Does `batchGetMetricCalculationSpecs` have limit?
</blockquote></details>

There isn't, but I removed this code block so I will address that in a separate PR.

**Review by riemanli — APPROVED** [review]
> Reviewed 2 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 2 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1335)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
