### PR TITLE
feat: Fulfill hmss requisition via the share shuffle library.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 89 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3t5O9o7FPfn4P5i-p0:-O3t5O9o7FPfn4P5i-p1:b-rl5jh0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L89)):*
> ```Kotlin
> 
>   init {
>     val populationSpec = populationSpec {
> ```

It looks like you have this block twice. Extract a `toPopulationSpec()` conversion extension for SyntheticPopulationSpec.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 106 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3t2fsd9KdEm9DhFGLs:-O3t2fse-yLtwOsr52b8:b-njbkor) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L106)):*
> ```Kotlin
>         InMemoryVidIndexMap.build(populationSpec)
>       } else {
>         InMemoryVidIndexMap.build(PopulationSpec.getDefaultInstance())
> ```

Rather than building from a default PopulationSpec, have a singleton empty constant value in the companion object of the VidIndexMap interface. i.e. `VidIndexMap.EMPTY`.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1137 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3t1O032pdy7JmR4Dqz:-O3t1O032pdy7JmR4Dr-:b-jfcm2p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1137)):*
> ```Kotlin
>   }
> 
>   private suspend fun fulfillRequisition(
> ```

This overload is no longer obviously for HMSS. At first glance, I'd expect the other overload to call this one now. The only difference in behavior appears to be how the Duchy is selected.

Refactor this so that we aren't calling fulfillRequisition on the stub in multiple places. I believe this is doable by just passing in either the stub or the Duchy ID.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt` line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3t59RBDerh7Gl3TZYk:-O3t59RBDerh7Gl3TZYl:b-ctrph2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt#L57)):*
> ```Kotlin
>     metadataByReferenceIdSuffix: Map<String, Message>,
>     knownEventGroupMetadataTypes: Iterable<Descriptors.FileDescriptor>,
>     vidIndexMap: VidIndexMap = InMemoryVidIndexMap.build(PopulationSpec.getDefaultInstance()),
> ```

See above comment



_Suggestion:_
```Kotlin
VidIndexMap.EMPTY
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 880 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3t5fKt8dqu3vkV64Oa:-O3t5fKt8dqu3vkV64Ob:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L880)):*
> ```Kotlin
>         privacyBudgetManager,
>         TRUSTED_CERTIFICATES,
>         InMemoryVidIndexMap.build(PopulationSpec.getDefaultInstance()),
> ```





_Suggestion:_
```Kotlin
VidIndexMap.EMPTY
```

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: all files reviewed, 6 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/FulfillRequisitionRequestBuilder.kt` line 132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3ySAms1AqbqPkXRcj_:-O3ySAms1AqbqPkXRcja:b-8hz57i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/FulfillRequisitionRequestBuilder.kt#L132)):*
> ```Kotlin
>           name = requisition.name
>           requisitionFingerprint = computeRequisitionFingerprint(requisition)
>           this.nonce = requisitionNonce
> ```

Why can't we get this from the Requisition?

**Review by kungfucraig — COMMENTED** [review]
I'll be out. Please don't block on my approval.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-:-O3ySMnS7EyssnWCHYqc:b-lnkwg1)* status: all files reviewed, 6 unresolved discussions (waiting on @ple13 and @renjiezh)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: all files reviewed, 5 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/FulfillRequisitionRequestBuilder.kt` line 132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3ySAms1AqbqPkXRcj_:-O46V6o808SdYKHAyxPU:bjcuoxe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/FulfillRequisitionRequestBuilder.kt#L132)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why can't we get this from the Requisition?
</blockquote></details>

This call is what eventually populates that Requisition.nonce field. That is to say that it's populated by the EDP decrypting the nonce value and passing it back in the FulfillRequisition request.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: 3 of 13 files reviewed, 5 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/FulfillRequisitionRequestBuilder.kt` line 132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3ySAms1AqbqPkXRcj_:-O4CF1eyCMo092p_WcGG:b-xyaykz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/FulfillRequisitionRequestBuilder.kt#L132)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This call is what eventually populates that Requisition.nonce field. That is to say that it's populated by the EDP decrypting the nonce value and passing it back in the FulfillRequisition request.
</blockquote></details>

When EDP gets the requisition, the field requisition.nonce is not set. We either need to pass requisitionSpec.nonce to the builder, or update requisition before passing it to the builder.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 89 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3t5O9o7FPfn4P5i-p0:-O4CCVYN7zwIqkabKjw0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It looks like you have this block twice. Extract a `toPopulationSpec()` conversion extension for SyntheticPopulationSpec.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 106 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3t2fsd9KdEm9DhFGLs:-O4CDk7x6wUFyXPVA8Lq:byhrp1e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L106)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rather than building from a default PopulationSpec, have a singleton empty constant value in the companion object of the VidIndexMap interface. i.e. `VidIndexMap.EMPTY`.
</blockquote></details>

I've added VidIndexMap.EMPTY.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1137 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3t1O032pdy7JmR4Dqz:-O4C_5Pe6ihutmzLKvHm:b-s0u5wl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1137)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This overload is no longer obviously for HMSS. At first glance, I'd expect the other overload to call this one now. The only difference in behavior appears to be how the Duchy is selected.

Refactor this so that we aren't calling fulfillRequisition on the stub in multiple places. I believe this is doable by just passing in either the stub or the Duchy ID.
</blockquote></details>

I've updated the function fulfillRequisition to take the stub as an argument.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt` line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3t59RBDerh7Gl3TZYk:-O4CE_VX4L3vLvh5iRe0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

See above comment
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 880 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O3t5fKt8dqu3vkV64Oa:-O4CEbkz6clxjUDTmXWS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d79542de724f79b40e39f41f63ea379ac0d6d14/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L880)):*
> ```Kotlin
>         privacyBudgetManager,
>         TRUSTED_CERTIFICATES,
>         InMemoryVidIndexMap.build(PopulationSpec.getDefaultInstance()),
> ```

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/testing/PopulationSpecConverter.kt` line 17 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4Cu8K9D2F4k3nK_RWG:-O4Cu8K9D2F4k3nK_RWH:b-c44ic7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52bbafa2a9f483cba1713782ecb29ebce399506c/src/main/kotlin/org/wfanet/measurement/common/testing/PopulationSpecConverter.kt#L17)):*
> ```Kotlin
>  */
> 
> package org.wfanet.measurement.common.testing
> ```

This isn't the right package, as this is not common at all and really specifically for the EDP simulator. I think this can just go in the same package as EdpSimulator.kt.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: 6 of 13 files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/testing/PopulationSpecConverter.kt` line 17 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4Cu8K9D2F4k3nK_RWG:-O4GgREz9l6LI4ResitX:b-7ohaot) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52bbafa2a9f483cba1713782ecb29ebce399506c/src/main/kotlin/org/wfanet/measurement/common/testing/PopulationSpecConverter.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This isn't the right package, as this is not common at all and really specifically for the EDP simulator. I think this can just go in the same package as EdpSimulator.kt.
</blockquote></details>

Thanks. I've moved it.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 10 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 1 of 6 files at r2, 4 of 10 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 1 of 10 files at r3, 3 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4HrBBp6tYylacyoiua:-O4HrBBp6tYylacyoiub:bhqgt00) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/648a25dd72bc80a2e6ba0982253a8b6cdd52d940/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L93)):*
> ```Kotlin
>         InMemoryVidIndexMap.build(populationSpec)
>       } else {
>         VidIndexMap.EMPTY
> ```

why do we need an empty option? why can't we just make vidIndexMap nullable?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4HrBBp6tYylacyoiua:-O4HsI7M4ncz08dkBf5t:b-ohly17) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/648a25dd72bc80a2e6ba0982253a8b6cdd52d940/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why do we need an empty option? why can't we just make vidIndexMap nullable?
</blockquote></details>

Just like any other Map/Collection, using empty is preferred over littering null checks everywhere.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 1 of 6 files at r2, 2 of 10 files at r3, 3 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: all files reviewed, 3 unresolved discussions (waiting on @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/VidIndexMap.kt` line 48 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4gMpgAC_kaG2qnXp6g:-O4gMpgAC_kaG2qnXp6h:be390yz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f17104448e76eba6f167d61f1009fffa56ab4c78/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/VidIndexMap.kt#L48)):*
> ```Kotlin
> 
>         override val populationSpec: PopulationSpec
>           get() = PopulationSpec.getDefaultInstance()
> ```

shouldn't this throw an error?
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4HrBBp6tYylacyoiua:-O4gMauS0TReDCCUDaxy:b-n7kc18) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/648a25dd72bc80a2e6ba0982253a8b6cdd52d940/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just like any other Map/Collection, using empty is preferred over littering null checks everywhere.
</blockquote></details>

well, in this case, its a collection that should _not_ be used at all. an empty map implies it can be used.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 195 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4gN9JD98Ivy5ePnAgy:-O4gN9JD98Ivy5ePnAgz:b-yyxes4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f17104448e76eba6f167d61f1009fffa56ab4c78/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L195)):*
> ```Kotlin
>     add(ProtocolConfig.Protocol.ProtocolCase.LIQUID_LEGIONS_V2)
>     add(ProtocolConfig.Protocol.ProtocolCase.REACH_ONLY_LIQUID_LEGIONS_V2)
>     if (vidIndexMap.size != 0L) {
> ```

this feels yucky to me to check the size to decide whether to add this protocol. I guess its okay for a simulator but its messy imo. Why can't the protocols be part of a config?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/VidIndexMap.kt` line 48 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4gMpgAC_kaG2qnXp6g:-O4gczBv0FFB2XoLzyrK:bids6wh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f17104448e76eba6f167d61f1009fffa56ab4c78/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/VidIndexMap.kt#L48)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't this throw an error?
</blockquote></details>

By definition, a VidIndexMap object is computed from a population spec. I think it's better to have an empty population spec that is associated with the EMPTY object.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4HrBBp6tYylacyoiua:-O4gfFuED0_Ukcxoiic-:b-jo5n4d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/648a25dd72bc80a2e6ba0982253a8b6cdd52d940/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

well, in this case, its a collection that should _not_ be used at all. an empty map implies it can be used.
</blockquote></details>

The EMPTY VidIndexMap can be used like any other VidIndexMap objects as we implemented all the methods declared in the interface.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 195 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4gN9JD98Ivy5ePnAgy:-O4ggLUJCT7zjmQaWUPg:b-p2a5ka) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f17104448e76eba6f167d61f1009fffa56ab4c78/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L195)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this feels yucky to me to check the size to decide whether to add this protocol. I guess its okay for a simulator but its messy imo. Why can't the protocols be part of a config?
</blockquote></details>

I think we could have the supported protocols be part of a config. If we decide we will do it, it could be in another PR, WDYT?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: all files reviewed, 4 unresolved discussions (waiting on @ple13 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4HrBBp6tYylacyoiua:-O4gs1o0CIR3DJXCn5_F:b-i6evfw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/648a25dd72bc80a2e6ba0982253a8b6cdd52d940/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L93)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

The EMPTY VidIndexMap can be used like any other VidIndexMap objects as we implemented all the methods declared in the interface.
</blockquote></details>

@ple13 I believe Steven's point is that the map is explicitly not used, where using null instead of empty would prevent its usage. This somewhat ties into the comment below on having an explicit signal for whether HMSS is supported rather than checking whether the map is empty.

@stevenwarejones would it be sufficient to name the property in EdpSimulator `hmssVidIndexMap` and have it be nullable, where `null` means HMSS isn't supported?
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 121 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4gtW8dCVTOsf2MYspW:-O4gtW8e7lzR2Ha7h2uk:b-fyz9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f17104448e76eba6f167d61f1009fffa56ab4c78/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L121)):*
> ```Kotlin
>           object :
>             SyntheticGeneratorEventQuery(
>               SyntheticGenerationSpecs.SYNTHETIC_POPULATION_SPEC_SMALL,
> ```

I think there might be a bug here. `syntheticPopulationSpec` is passed into the constructor and we're using that to build the VidIndexMap, but we're passing a different population spec into the event query.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 195 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4gN9JD98Ivy5ePnAgy:-O4gtxQk-h1zj_p6jlm3:b-laoxym) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f17104448e76eba6f167d61f1009fffa56ab4c78/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L195)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I think we could have the supported protocols be part of a config. If we decide we will do it, it could be in another PR, WDYT?
</blockquote></details>

See other comment about renaming the field.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: 8 of 13 files reviewed, 4 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4HrBBp6tYylacyoiua:-O4knLph7zmXojChEoU7:b342jq9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/648a25dd72bc80a2e6ba0982253a8b6cdd52d940/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@ple13 I believe Steven's point is that the map is explicitly not used, where using null instead of empty would prevent its usage. This somewhat ties into the comment below on having an explicit signal for whether HMSS is supported rather than checking whether the map is empty.

@stevenwarejones would it be sufficient to name the property in EdpSimulator `hmssVidIndexMap` and have it be nullable, where `null` means HMSS isn't supported?
</blockquote></details>

Thanks @SanjayVas for the clarification. We could add a method isEmpty() to the VidIndexMap interface as well. @stevenwarejones, please let me know.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 121 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4gtW8dCVTOsf2MYspW:-O4knm0A1CeSzUJ0Rlmz:bskl31r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f17104448e76eba6f167d61f1009fffa56ab4c78/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L121)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think there might be a bug here. `syntheticPopulationSpec` is passed into the constructor and we're using that to build the VidIndexMap, but we're passing a different population spec into the event query.
</blockquote></details>

I see. There could be discrepancy between the two if we are not careful. We should have passed the same syntheticPopulationSpec to construct eventQuery as well. I'll update this.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 195 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4gN9JD98Ivy5ePnAgy:-O4kpqQL6BJYgf-qUWOp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f17104448e76eba6f167d61f1009fffa56ab4c78/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L195)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

See other comment about renaming the field.
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/VidIndexMap.kt` line 48 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4gMpgAC_kaG2qnXp6g:-O4lGez649z0wdBO4MHE:bobo5tg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f17104448e76eba6f167d61f1009fffa56ab4c78/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/VidIndexMap.kt#L48)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

By definition, a VidIndexMap object is computed from a population spec. I think it's better to have an empty population spec that is associated with the EMPTY object.
</blockquote></details>

this is addressed by your other changes imo
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 195 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748#-O4gN9JD98Ivy5ePnAgy:-O4lGSc18aSNzch_8gHz:b-hr0zlk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f17104448e76eba6f167d61f1009fffa56ab4c78/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L195)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

this works for me. We should consider passing in a config as a future pr though.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 5 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1748)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
