### PR TITLE
Handle the InitializationPhase in the llv2 mill.

### PR DESCRIPTION
**Pull request by wangyaopw**
More specifically
1. A local elgamalkeypair is generated and stored in the computation details.
2. The public key is sent to the kingdom.
3. The ducy computation then enters WAIT_REQUISITIONS_AND_KEY_SET stage.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/92)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Comment by zachcwc** [comment]
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, line 102 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/92#-Mbc_JVME-H8E6Ci9CIO:-Mbc_JVN0pppxyDSDkp0:b76snvs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ae5ff1e51aed2dbcc86a2ba7d6d12617b1b855e1/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L102)):*
> ```Kotlin
> 
>   private val systemComputationParticipantsStub by lazy {
>     SystemCComputationParticipantsCoroutineStub(kingdomChannel).withDuchyId(duchyId)
> ```

Typo in SystemCComputation?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/92)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, line 102 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/92#-Mbc_JVME-H8E6Ci9CIO:-MbcbgcABZH2zTE9mxMO:b-5azuex) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ae5ff1e51aed2dbcc86a2ba7d6d12617b1b855e1/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L102)):*
<details><summary><i>Previously, zachcwc wrote…</i></summary><blockquote>

Typo in SystemCComputation?
</blockquote></details>

Yep! Thanks for catching this

**Review by zachcwc — APPROVED** [review]
> Reviewed 10 of 13 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
