### PR TITLE
Add support for reach only HMSS.

### PR DESCRIPTION
**Pull request by ple13**
1. EdpSimulator to charge privacy budget for reach-only HMSS.
2. HMSS Mill supports reach-only HMSS.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655)* status: all files reviewed, 3 unresolved discussions (waiting on @ple13, @renjiezh, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 394 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655#-O-2n38XA3x4CQo1AzWu:-O-2n38XA3x4CQo1AzWv:b-7n5qfh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa31214a4f61521da66383e7675ecab47451fdda/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L394)):*
> ```Kotlin
>           CompleteShufflePhaseRequest.NonAggregatorOrder.SECOND
>         }
>       if (hmss.parameters.hasReachDpParams()) {
> ```

Why add the "has" checks?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 477 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655#-O-2nQB48Gg55Us6DzWX:-O-2nQB48Gg55Us6DzWY:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa31214a4f61521da66383e7675ecab47451fdda/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L477)):*
> ```Kotlin
>         }
>       }
>       if (hmss.parameters.hasReachDpParams()) {
> ```

Same as above.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt` line 1113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655#-O-2oi5TCOhepmSO-OjO:-O-2oi5TCOhepmSO-OjP:b-42dizm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa31214a4f61521da66383e7675ecab47451fdda/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt#L1113)):*
> ```Kotlin
>     val requisitionBlobContext3 =
>       RequisitionBlobContext(GLOBAL_ID, REACH_ONLY_REQUISITION_3.externalKey.externalRequisitionId)
>     // TODO(@renjiez): Use ShareShuffleSketch from any-sketch-java when it is available..
> ```

Use FrequencyVector?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @renjiezh, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 394 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655#-O-2n38XA3x4CQo1AzWu:-O-2p4jkBaAFhhB58t9b:b-qoog6i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa31214a4f61521da66383e7675ecab47451fdda/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L394)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why add the "has" checks?
</blockquote></details>

In Herald (https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77d12ac8f444f01f9fde2f171f7c44cf84bad83d/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L167), we do not always set the reach/frequency DP params. The `has` checks are to make sure that we will only set the fields if they exist.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 477 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655#-O-2nQB48Gg55Us6DzWX:-O-2qGpq0rKNLFI59Z5N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa31214a4f61521da66383e7675ecab47451fdda/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L477)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt` line 1113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655#-O-2oi5TCOhepmSO-OjO:-O-2r34TDXV0xk3wiI-t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa31214a4f61521da66383e7675ecab47451fdda/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt#L1113)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Use FrequencyVector?
</blockquote></details>

Done.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh, @SanjayVas, and @uakyol)

**Review by renjiezh — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @uakyol)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @uakyol)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 437 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655#-O-Nnt208i0Wh3YAQLYV:-O-Nnt208i0Wh3YAQLYW:b-1644r0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4046fc342ae112e7e89016d1284a233941587ccd/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L437)):*
> ```Kotlin
>     val measurementSpec =
>       MeasurementSpec.parseFrom(token.computationDetails.kingdomComputation.measurementSpec)
>     val result =
> ```

nit: explicit types when not obvious. I can't tell from looking at this without an IDE what the type is.

See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 461 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655#-O-No6oZE0foonJ46Ngm:-O-No6oZE0foonJ46Ngn:b-tbpyip) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4046fc342ae112e7e89016d1284a233941587ccd/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L461)):*
> ```Kotlin
> 
>   private suspend fun aggregationPhase(token: ComputationToken): ComputationToken {
>     val measurementSpec =
> ```

It's not safe to parse this before the API version check. It's the API version that tells you what version of the MeasurementSpec message/class to use.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @renjiezh, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 437 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655#-O-Nnt208i0Wh3YAQLYV:-O-bZuJnEpcK736qBQ8S:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4046fc342ae112e7e89016d1284a233941587ccd/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L437)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: explicit types when not obvious. I can't tell from looking at this without an IDE what the type is.

See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 461 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655#-O-No6oZE0foonJ46Ngm:-O-b_-83930yo9ZquMZw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4046fc342ae112e7e89016d1284a233941587ccd/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L461)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's not safe to parse this before the API version check. It's the API version that tells you what version of the MeasurementSpec message/class to use.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1655)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Pull request merged**
