### PR TITLE
HSMM reach-only integration test

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1679)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 17 files at r1, 9 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1679)* status: 14 of 19 files reviewed, 3 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/k8s/dev/duchy_eks.cue` line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1679#-O1SnZ-u0U1rI3la0N1-:-O1SnZ-u0U1rI3la0N10:b-gliyv5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/00d7eef28d9a005d9955e6ed125eabf4d6991139/src/main/k8s/dev/duchy_eks.cue#L80)):*
> ```CUE
> 	}
> }
> #FulfillmentMaxHeapSize:             "700M"
> ```

nit: the max heap I spot for worker1 over the past week is 282 MiB, so I'd figure a value of 320 MiB would be fine. 700 seems a bit large. Is there just a shorter spike that's not visible in the graphs? Or is this just headroom for more simultaneous fulfillments?
___
*[`src/main/k8s/dev/duchy_eks.cue` line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1679#-O1SmNU19jpFRFWHJRCX:-O1SmNU19jpFRFWHJRCY:bm078iv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/00d7eef28d9a005d9955e6ed125eabf4d6991139/src/main/k8s/dev/duchy_eks.cue#L90)):*
> ```CUE
> 	}
> }
> #ControlServiceMaxHeapSize: "350M"
> ```

nit: the peak heap I spotted over the last week for the aggregator is 261 MiB. Maybe 288 (256 + 32) or 320 (256+64) is a better fit?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 428 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1679#-O1SkzJ3Ans6FO2juZ54:-O1SkzJ4AAYN6tIgze7f:bcrnrt7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/00d7eef28d9a005d9955e6ed125eabf4d6991139/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L428)):*
> ```Kotlin
>     }
> 
>     logger.log(Level.WARNING, "registerCount=${request.sketchParams.registerCount}")
> ```

Why is this a warning?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1679)* status: 11 of 19 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 428 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1679#-O1SkzJ3Ans6FO2juZ54:-O1Sz-ke2KRCgh5Avimo:b-mfkptl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/00d7eef28d9a005d9955e6ed125eabf4d6991139/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L428)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this a warning?
</blockquote></details>

Done.
Deleted as it is not needed.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 17 files at r1, 3 of 12 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1679)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

___
*[`src/main/k8s/dev/duchy_eks.cue` line 74 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1679#-O1T0xdlEN8RHdNk7PCg:-O1T0xdlEN8RHdNk7PCh:b6aut5p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8aca85e0372b3a05772575184e85981077c7552f/src/main/k8s/dev/duchy_eks.cue#L74)):*
> ```CUE
> 	requests: {
> 		cpu:    "200m"
> 		memory: "1Gi"
> ```

Update this to reflect the change in max heap size. Max observed value was 519 MiB, so maybe 576 MiB (512+64)?

**Review by ple13 — APPROVED** [review]
> Reviewed 7 of 17 files at r1, 9 of 12 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1679)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 7 of 17 files at r1, 9 of 12 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1679)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 7 of 17 files at r1, 7 of 12 files at r2, 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1679)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
