### PR TITLE
Update Kingdom measurement creation to support HMSS protocol.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404)* status: all files reviewed, 3 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-NnkGG7lDzjln-J7oG2q:-NnkGG7lDzjln-J7oG2r:b-o7n9e1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61696891c09b692c2babb6e8e552df1b0a046e72/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L109)):*
> ```Kotlin
>         ProtocolConfig.ProtocolCase.HONEST_MAJORITY_SHARE_SHUFFLE ->
>           HmssProtocolConfig.requiredExternalDuchyIds
>         else -> emptySet()
> ```

Use an exhaustive when.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 131 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-NnkGJ596FU1A3JEXfhU:-NnkGJ596FU1A3JEXfhV:b3suv6f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61696891c09b692c2babb6e8e552df1b0a046e72/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L131)):*
> ```Kotlin
>         ProtocolConfig.ProtocolCase.HONEST_MAJORITY_SHARE_SHUFFLE ->
>           HmssProtocolConfig.requiredExternalDuchyIds.size
>         else -> 0
> ```

Use an exhaustive when
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto` line 183 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-NnkFkezDohqy_Sn3_cj:-NnkFkezDohqy_Sn3_ck:b4atzkx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61696891c09b692c2babb6e8e552df1b0a046e72/src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto#L183)):*
> ```proto
>   // Length of each register in bytes.
>   //
>   // The product of `maximum_frequency` and the `number_of_edps` should be no
> ```

nit: these fields don't exist on this message. Is there a better way to document this, or is it fine to drop it here?



_Code quote:_
```proto
`maximum_frequency` and the `number_of_edps`
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-NnkGG7lDzjln-J7oG2q:-NnoMaA10m-bK7F3SczM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61696891c09b692c2babb6e8e552df1b0a046e72/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L109)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use an exhaustive when.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 131 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-NnkGJ596FU1A3JEXfhU:-NnoMbKm0ZvjaFcoEkgv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61696891c09b692c2babb6e8e552df1b0a046e72/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L131)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use an exhaustive when
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404)* status: all files reviewed, 5 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-Nnou9Ea3Z7ZE_zcqYDl:-Nnou9Ea3Z7ZE_zcqYDm:bpeksys) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d10e302d0744c246dcba09872cb8ef777fa089f6/src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto#L41)):*
> ```proto
>   ProtocolConfig.HonestMajorityShareShuffle protocol_config = 1;
>   // List of required duchies for this protocol.
>   repeated string required_external_duchy_ids = 2;
> ```

wdyt about adding max and min duchy_participatnt_count ?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/HmssProtocolConfig.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-NnojswR7i5vcU4n4pal:-NnpMPs289Rl5F1es61s:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d10e302d0744c246dcba09872cb8ef777fa089f6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/HmssProtocolConfig.kt#L1)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

2024
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/HmssProtocolConfig.kt` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-NnokaSS5JdiVcerwC9z:-NnpHMGY8Upo4O31HT0g:b-cd8puw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d10e302d0744c246dcba09872cb8ef777fa089f6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/HmssProtocolConfig.kt#L31)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Do we need DuchyProtocolConfig? I think in llv2, we use it to specify differential privacy params.
</blockquote></details>

In llv2, DuchyProtocolConfig contains several sets of dp params for different intermediate noise.  But HMSS should only have one type of noise whose dp params is specified via measurement creation. Please correct me if I misunderstand it.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto` line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-NnomPfh2qqpPWoyfEfy:-NnpHDdw1KFZ_E2UwJ8Z:b-gankek) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d10e302d0744c246dcba09872cb8ef777fa089f6/src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto#L140)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

We need DifferentialPrivacyParams to go with noise_mechanism.
</blockquote></details>

I think output DP params are specified by the MC during measurement creation. Is this correct? 
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto` line 182 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-NnomrLL15M097tAUaK5:-NnpLelP090pu3R0C-dg:b-gza4r3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d10e302d0744c246dcba09872cb8ef777fa089f6/src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto#L182)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

We need a field to specify the ring modulus too (e.g. uint32 ring_modulus = 3;). The modulus is needed when the computation is done over a ring which is not Z_{2^k}.
</blockquote></details>

Done.
Please let me know if the description needs update.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-Nnou9Ea3Z7ZE_zcqYDl:-NnpGkQbDrJ5HjMwf5cL:bhwl8c2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d10e302d0744c246dcba09872cb8ef777fa089f6/src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

wdyt about adding max and min duchy_participatnt_count ?
</blockquote></details>

For HMSS protocol, the number of DuchyParticipants is fixed as 3. I don't see the potential change in the near future. So I think we would not config that.

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-Nnsc_mG402ykubqBTch:-Nnsc_mG402ykubqBTci:b-dz391b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd88a27e27c88b4dcb020e6380ed3d30b84f1a48/src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto#L1)):*
> ```proto
> // Copyright 2024 The Cross-Media Measurement Authors
> ```

This is not a new file, should we keep 2021?
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto` line 184 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-Nnscs1ABVahnNrscTyR:-Nnscs1BCpjZIz9ZGr0T:bazfkz7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd88a27e27c88b4dcb020e6380ed3d30b84f1a48/src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto#L184)):*
> ```proto
>   int32 bytes_per_register = 2;
> 
>   // Modulus for computations whose ring is not Z_{2^k}.
> ```

Maybe just `Secret share modulus`? (as we haven't defined k anywhere).



_Code quote:_
```proto
Modulus for computations whose ring is not Z_{2^k}.
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @ple13 and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-Nnsc_mG402ykubqBTch:-NntfvnQ2JDyC5qn1G-k:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd88a27e27c88b4dcb020e6380ed3d30b84f1a48/src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto#L1)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

This is not a new file, should we keep 2021?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto` line 184 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404#-Nnscs1ABVahnNrscTyR:-Nntfw73693zpVcLnTFZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd88a27e27c88b4dcb020e6380ed3d30b84f1a48/src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto#L184)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Maybe just `Secret share modulus`? (as we haven't defined k anywhere).
</blockquote></details>

Done.

**Review by ple13 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1404)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
