### PR TITLE
Add synthetic_event_group_specs with 5M reach each.

### PR DESCRIPTION
**Pull request by renjiezh**
Added but not activated in EDP simulator yet. 
To use new spec, more memory is required for EDP simulator and RequisitionFulfillmentService. Mills need more memory to process the Computation.
Check [this draft](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1302) for configuration reference.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1303)

**Review by SanjayVas — COMMENTED** [review]
Would you mind putting the updated memory config in this same PR? Basically the K8s dev test should pass at any merged commit.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1303#-:-Nh3ZsNh7cY4C8Ko4GZe:b-dbymz)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by SanjayVas — COMMENTED** [review]
> These three new specs are not deployed in dev env by the config.

This PR adds them to the confile files Kustomization for the dev env.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1303#-:-Nh3eKEoA9vPIDdvWAjw:bgdoui)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by renjiezh — COMMENTED** [review]
yeah, they are added but not picked up by any EDP simulators. I did this to make it more convenient to manually edit EDP simulator in the GKE console. Do you want me to remove them from Kustomization or thoroughly update the config to make enough memory for large dataset? 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1303#-:-Nh3efq1CJoD8pwa493X:b4la3va)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by SanjayVas — COMMENTED** [review]
Remove them from the Kustomization. We generally don't want manual edits. If someone wants to update, they should edit a Kustomization dir locally and apply that.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1303#-:-Nh3tQhw-sW_Lf5bSXco:b-dmhi1z)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by renjiezh — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1303#-:-Nh3u-Oz-fQOMHfDGPJx:b-896fix)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @tristanvuong2021)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
