### PR TITLE
Fix storage of Kingdom Measurements in Reporting Server when creating a Report.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: all files reviewed, 3 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 154 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGNZ4HjBNEjNU5rUBCL:-NGNZ4Hk6HzONx0lNKzc:b-nnmwd2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9afff296885636ba2e8c6e27f3b3da30b441b4d3/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L154)):*
> ```Kotlin
>                 .measurement
>                 .measurementReferenceId
>             name += measurementReferenceId
> ```

IIUC, this is appending to the name field? That doesn't seem right, as `MEASUREMENT` already has its name set to `MEASUREMENT_NAME` (meaning that `MEASUREMENT` appears to be the Kingdom Measurement as opposed to the CreateMeasurement request).
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 159 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGNZX6s1WP-PkiPKIuT:-NGNZX6s1WP-PkiPKIuU:b-ndrwht) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9afff296885636ba2e8c6e27f3b3da30b441b4d3/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L159)):*
> ```Kotlin
>       onBlocking { getMeasurement(any()) }
>         .thenAnswer {
>           val name = it.getArgument(0, GetMeasurementRequest::class.java).name
> ```

Use argument matchers instead of `Answer`.

```kotlin
onBlocking { getMeasurement(eq(MEASUREMENT_NAME)) }.thenReturn(MEASUREMENT)
onBlocking { getMeasurement(not(MEASUREMENT_NAME)) }.thenThrow(Status.NOT_FOUND.asRuntimeException())
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 501 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGNamUH-I0dLtW-Q61S:-NGNamUH-I0dLtW-Q61T:b-chwahi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9afff296885636ba2e8c6e27f3b3da30b441b4d3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L501)):*
> ```Kotlin
>           .createMeasurement(createMeasurementRequest)
>       weightedMeasurementInfo.kingdomMeasurementId =
>         MeasurementKey.fromName(measurement.name)!!.measurementId
> ```

nit: only use this when you can guarantee it's true but the compiler can't figure it out. e.g. if you have a previous call to MeasurementKey.fromName that has to have succeeded to get to this line.

Otherwise, use requireNotNull or checkNotNull (depending on whether what you're checking is an argument or existing state)



_Code quote:_
```Kotlin
!!
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: all files reviewed, 3 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 154 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGNZ4HjBNEjNU5rUBCL:-NGNdgRiAuRv0RpUP5CP:b-cc1ge9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9afff296885636ba2e8c6e27f3b3da30b441b4d3/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L154)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

IIUC, this is appending to the name field? That doesn't seem right, as `MEASUREMENT` already has its name set to `MEASUREMENT_NAME` (meaning that `MEASUREMENT` appears to be the Kingdom Measurement as opposed to the CreateMeasurement request).
</blockquote></details>

I am doing this as a way to create different measurements, but still make it obvious that this is the kingdom measurement name

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: all files reviewed, 3 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 154 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGNZ4HjBNEjNU5rUBCL:-NGNmC8eD9gyNMUZZNbY:b-lrgv65) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9afff296885636ba2e8c6e27f3b3da30b441b4d3/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L154)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I am doing this as a way to create different measurements, but still make it obvious that this is the kingdom measurement name
</blockquote></details>

Sure, but the `name` field on the Kingdom public API Measurement is the resource name. I think appending the reference ID provided by the reporting server may make this confusing and potentially lead to the same kind of mistake.

Maybe add sequential stubbing for multiple calls? e.g. have *n* known measurement resource names that you return in sequence. You can move the stubbing to the individual test method if you need the behavior to differ per-method.

```kotlin
onBlocking { createMeasurement(any()) }
  .thenReturn(MEASUREMENT.copy { name = MEASUREMENT_NAME_1 })
  .thenReturn(MEASUREMENT.copy { name = MEASUREMENT_NAME_2 })
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 154 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGNZ4HjBNEjNU5rUBCL:-NGOCtoJ8umxH9276vEF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9afff296885636ba2e8c6e27f3b3da30b441b4d3/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L154)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sure, but the `name` field on the Kingdom public API Measurement is the resource name. I think appending the reference ID provided by the reporting server may make this confusing and potentially lead to the same kind of mistake.

Maybe add sequential stubbing for multiple calls? e.g. have *n* known measurement resource names that you return in sequence. You can move the stubbing to the individual test method if you need the behavior to differ per-method.

```kotlin
onBlocking { createMeasurement(any()) }
  .thenReturn(MEASUREMENT.copy { name = MEASUREMENT_NAME_1 })
  .thenReturn(MEASUREMENT.copy { name = MEASUREMENT_NAME_2 })
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 159 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGNZX6s1WP-PkiPKIuT:-NGOCv-F3otugagKkELE:bd1kata) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9afff296885636ba2e8c6e27f3b3da30b441b4d3/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L159)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use argument matchers instead of `Answer`.

```kotlin
onBlocking { getMeasurement(eq(MEASUREMENT_NAME)) }.thenReturn(MEASUREMENT)
onBlocking { getMeasurement(not(MEASUREMENT_NAME)) }.thenThrow(Status.NOT_FOUND.asRuntimeException())
```
</blockquote></details>

Should I still do this even with multiple names.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 159 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGNZX6s1WP-PkiPKIuT:-NGOGJ2vDYVTpTqIF6XR:b-ep7otg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9afff296885636ba2e8c6e27f3b3da30b441b4d3/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L159)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Should I still do this even with multiple names.
</blockquote></details>

 I suppose this is fine since there's not a built-in argument matcher for a set, but I do think it would be clearer to use a custom argument matcher with `argThat`.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 147 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGOICTLAHLR7xCmTA55:-NGOICTLAHLR7xCmTA56:b73n744) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24d45a4ee3a9b3e364137a05ccd1c2a09ca0086c/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L147)):*
> ```Kotlin
>         .thenReturn(
>           MEASUREMENT.copy { name = MEASUREMENT_NAME_SET.first() },
>           *MEASUREMENT_NAME_SET.filter { it != MEASUREMENT_NAME_SET.first() }
> ```

This is a bit messy. A couple options:
1. Use `drop(1)` for the subsequent items
2. Use a loop.
    ```kotlin
    onBlocking { createMeasurement(any()) }.apply { 
        for (name in MEASUREMENT_NAME_SET) { thenReturn(name) }
    }
    ```



_Code quote:_
```Kotlin
      onBlocking { createMeasurement(any()) }
        .thenReturn(
          MEASUREMENT.copy { name = MEASUREMENT_NAME_SET.first() },
          *MEASUREMENT_NAME_SET.filter { it != MEASUREMENT_NAME_SET.first() }
            .map { MEASUREMENT.copy { name = it } }
            .toTypedArray()
        )
```

**Review by riemanli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 475 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGOJkad1ReI2fveN9SF:-NGOJkad1ReI2fveN9SG:b-bd2ob0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efb77b70728a9e0b1730f5fe3b2bc4beb19052f0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L475)):*
> ```Kotlin
>       )
> 
>     if (existingInternalMeasurement != null) return
> ```

Do we not reuse the measurement from the internal measurement database?



_Code quote:_
```Kotlin
    val existingInternalMeasurement: InternalMeasurement? =
      getInternalMeasurement(
        reportInfo.measurementConsumerReferenceId,
        weightedMeasurementInfo.measurementReferenceId
      )

    if (existingInternalMeasurement != null) return
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 475 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGOJkad1ReI2fveN9SF:-NGObs_h2r4e6XBpk5JS:bna4h22) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efb77b70728a9e0b1730f5fe3b2bc4beb19052f0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L475)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Do we not reuse the measurement from the internal measurement database?
</blockquote></details>

This lookup no longer works with this change, but the kingdom createMeasurement returns an existing measurement if a measurement was already created using the kingdom measurement measurementReferenceId field.

**Review by riemanli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 475 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGOJkad1ReI2fveN9SF:-NGOfjmz8Nc6chgMJ35I:b-7p9z34) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efb77b70728a9e0b1730f5fe3b2bc4beb19052f0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L475)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This lookup no longer works with this change, but the kingdom createMeasurement returns an existing measurement if a measurement was already created using the kingdom measurement measurementReferenceId field.
</blockquote></details>

Does the request of creating a measurement with an existing kingdom measurementReferenceId need to wait for fulfillment? I am worried that getting an existing measurement with `createMeasurement` might take a long time.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 475 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGOJkad1ReI2fveN9SF:-NGOrzshDiFxvYiTx2JC:bb8fw4u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efb77b70728a9e0b1730f5fe3b2bc4beb19052f0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L475)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Does the request of creating a measurement with an existing kingdom measurementReferenceId need to wait for fulfillment? I am worried that getting an existing measurement with `createMeasurement` might take a long time.
</blockquote></details>

Nope. It basically turns `createMeasurement` into `getMeasurement`

**Review by riemanli — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 475 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGOJkad1ReI2fveN9SF:-NGOt1lfDnzxnmwxCRGf:bn32tgu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efb77b70728a9e0b1730f5fe3b2bc4beb19052f0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L475)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Nope. It basically turns `createMeasurement` into `getMeasurement`
</blockquote></details>

I see. Given that the process of building a `createMeasurementRequest` shouldn't take too long, I think this makes great sense.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 147 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-NGOICTLAHLR7xCmTA55:-NGOtrUS0s-a34ZvXMVD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7894e7f2bf3893d74efd9fe6362d815089ae85f3/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L147)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is a bit messy. A couple options:
1. Use `drop(1)` for the subsequent items
2. Use a loop.
    ```kotlin
    onBlocking { createMeasurement(any()) }.apply { 
        for (name in MEASUREMENT_NAME_SET) { thenReturn(name) }
    }
    ```
</blockquote></details>

Done.

**Review by mariolamassaavedra — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by mariolamassaavedra — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743#-:-NGSAMDbBs908UWpO7lm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by riemanli — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/743)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
