### PR TITLE
Add PanelMatchResourceSetupRunner binary to setup resources before Pa…

### PR DESCRIPTION
**Pull request by yunyeng**
…nelMatchDaemon

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @wangyaopw)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @wangyaopw and @yunyeng)

___
*[src/main/k8s/kingdom.cue, line 139 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0d9s99aJHrLw2c22c:-Mv0d9s99aJHrLw2c22d:b-j62z3f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5994bbec65d58b8863e3fc9e285a7a7f8b58a763/src/main/k8s/kingdom.cue#L139)):*
> ```CUE
> 				"system-api-server-app",
> 				"resource-setup-app",
> 				"panel-match-resource-setup-app",
> ```

1. I don't see any K8s resource with this label defined yet.
2. Does this resource need a unique app label, or can it just use `resource-setup-app`?
___
*[src/main/k8s/panel_match_resource_setup.cue, line 0 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0d4mn2jfHZ7R-YOFN:-Mv0d4mn2jfHZ7R-YOFO:boo122i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5994bbec65d58b8863e3fc9e285a7a7f8b58a763/src/main/k8s/panel_match_resource_setup.cue#L0)):*
Don't create this file until you have something to put in it



_Code quote:_
```CUE
Empty
```
___
*[src/main/k8s/dev/panel_match_resource_setup_gke.cue, line 0 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0d8moDdqgyCxDtzWF:-Mv0d8moDdqgyCxDtzWG:boo122i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5994bbec65d58b8863e3fc9e285a7a7f8b58a763/src/main/k8s/dev/panel_match_resource_setup_gke.cue#L0)):*
Don't create this file until you have something to put in it
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0c-biDtSHEyEXu30Z:-Mv0c-biDtSHEyEXu30_:bw0wpq4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cbeeb0653b877b6585814a1bc875e372aa28463/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/BUILD.bazel#L15)):*
> ```Starlark
>     testonly = True,
>     srcs = [
>         "PanelMatchResourceSetup.kt",
> ```

Why change this glob? If it's a library for a specific subset of files, it shouldn't be the default target for the package.

Either the name of this target should be something else, or the target should use glob.



_Code quote:_
```Starlark
        "PanelMatchResourceSetup.kt",
```

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/k8s/kingdom.cue, line 139 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0d9s99aJHrLw2c22c:-Mv0fxQc4_35W6QHDwch:b-a6bzl1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5994bbec65d58b8863e3fc9e285a7a7f8b58a763/src/main/k8s/kingdom.cue#L139)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. I don't see any K8s resource with this label defined yet.
2. Does this resource need a unique app label, or can it just use `resource-setup-app`?
</blockquote></details>

I believe this is for whitelisting for multiclusters. 
___
*[src/main/k8s/panel_match_resource_setup.cue, line  at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0d4mn2jfHZ7R-YOFN:-Mv0g5Kp7ZwbDToHe8nY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5994bbec65d58b8863e3fc9e285a7a7f8b58a763/src/main/k8s/panel_match_resource_setup.cue#L)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't create this file until you have something to put in it
</blockquote></details>

Done.
___
*[src/main/k8s/dev/panel_match_resource_setup_gke.cue, line  at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0d8moDdqgyCxDtzWF:-Mv0g5tQEMii3kXN_mCG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5994bbec65d58b8863e3fc9e285a7a7f8b58a763/src/main/k8s/dev/panel_match_resource_setup_gke.cue#L)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't create this file until you have something to put in it
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0c-biDtSHEyEXu30Z:-Mv0g6ld0q_ujQkXnfYC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cbeeb0653b877b6585814a1bc875e372aa28463/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/BUILD.bazel#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why change this glob? If it's a library for a specific subset of files, it shouldn't be the default target for the package.

Either the name of this target should be something else, or the target should use glob.
</blockquote></details>

Done.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 5 of 8 files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/k8s/panel_match_resource_setup.cue, line 17 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0kYqk2Xc7tUeczVXv:-Mv0kYqk2Xc7tUeczVXw:b-yklnp2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/k8s/panel_match_resource_setup.cue#L17)):*
> ```CUE
> package k8s
> 
> #PanelMatchResourceSetup: {
> ```

what is this PanelMatchResourceSetup job doing?

creating a EDP and a MP?

I didn't see any data related to EDP and MP.



_Code quote:_
```CUE
PanelMatchResourceSetup
```
___
*[src/main/k8s/panel_match_resource_setup.cue, line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0kCnJ2HB4BBPyUJse:-Mv0kCnKEzV5AdtyRUXP:b9w65qv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/k8s/panel_match_resource_setup.cue#L22)):*
> ```CUE
> 	_job_image_pull_policy:      string | *"Always"
> 	_tls_cert_key_files_flags: [
> 		"--tls-cert-file=/var/run/secrets/files/mc_tls.pem",
> ```

this has nothing to do with the mc.

Use the kingdom_tld to talk to the internal API



_Code quote:_
```CUE
mc_tls.pem
```

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 5 of 8 files reviewed, 8 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0mJZQC1SdCYrbgzty:-Mv0mJZQC1SdCYrbgztz:b-5g8h70) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.kingdom.service.internal.testing.integration
> ```

It feel weird to deploy something under `integration` to GKE.

I assume this code should only be used in in-memory integration test



_Code quote:_
```Kotlin
org.wfanet.measurement.kingdom.service.internal.testing.integration
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 110 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0ma3l3HE2jh7IaUBL:-Mv0ma3l3HE2jh7IaUBM:bwquwse) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L110)):*
> ```Kotlin
>               notValidBefore = Instant.ofEpochSecond(12345).toProtoTime()
>               notValidAfter = Instant.ofEpochSecond(23456).toProtoTime()
>               details =
> ```

Doesn't panel exchange need to use actual certificate to do something?



_Code quote:_
```Kotlin
              details =
                CertificateKt.details {
                  x509Der = ByteString.copyFromUtf8("This is a certificate der.")
                }
```

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 5 of 8 files reviewed, 9 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 80 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0otei1SLSHKwHMe0F:-Mv0otej2XUd531i1Qdi:b-vehp88) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L80)):*
> ```Kotlin
> 
>     val externalDataProviderId = createDataProvider()
>     logger.info("Successfully created data provider: $externalDataProviderId.")
> ```

you need to print the resourceNames, which will be used in the configMap file.



_Code quote:_
```Kotlin
$externalDataProviderId.
```

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 4 of 8 files reviewed, 9 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 80 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0otei1SLSHKwHMe0F:-Mv0viHA5W_9QQ4ES6_o:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L80)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

you need to print the resourceNames, which will be used in the configMap file.
</blockquote></details>

Done.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 4 of 8 files reviewed, 9 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/k8s/panel_match_resource_setup.cue, line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0kCnJ2HB4BBPyUJse:-Mv0xNxV4YTcU7DfVSLF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/k8s/panel_match_resource_setup.cue#L22)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

this has nothing to do with the mc.

Use the kingdom_tld to talk to the internal API
</blockquote></details>

Done.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 4 of 8 files reviewed, 8 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/k8s/kingdom.cue, line 139 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0d9s99aJHrLw2c22c:-Mv0y3e71F9SBt3HdK22:b6ybbha) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5994bbec65d58b8863e3fc9e285a7a7f8b58a763/src/main/k8s/kingdom.cue#L139)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

I believe this is for whitelisting for multiclusters. 
</blockquote></details>

This has nothing to do with multiclusters. All resourceSetupJobs run inside the kingdom clusters.


You can surely reuse the `resource-setup-app` label. 
___
*[src/main/k8s/panel_match_resource_setup.cue, line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0ybtS-a4V_159a5iX:-Mv0ybtTCAGuaVRNIJZ8:b-g0ts7y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/596d3c808502286d08382a8cd72968021eb63ea9/src/main/k8s/panel_match_resource_setup.cue#L32)):*
> ```CUE
> 
> 	resource_setup_job: #Job & {
> 		_name:            "panel-match-resource-setup"
> ```

If you use `resource-setup` here, you don't need to change the kingdom networkPolicy



_Code quote:_
```CUE
panel-match-resource-setup
```

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 3 of 8 files reviewed, 8 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/k8s/panel_match_resource_setup.cue, line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0ybtS-a4V_159a5iX:-Mv15RpBDL--MKf8U4T8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/596d3c808502286d08382a8cd72968021eb63ea9/src/main/k8s/panel_match_resource_setup.cue#L32)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

If you use `resource-setup` here, you don't need to change the kingdom networkPolicy
</blockquote></details>

Done.
___
*[src/main/k8s/kingdom.cue, line 139 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0d9s99aJHrLw2c22c:-Mv15UO71KWLFiAlAVsB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5994bbec65d58b8863e3fc9e285a7a7f8b58a763/src/main/k8s/kingdom.cue#L139)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

This has nothing to do with multiclusters. All resourceSetupJobs run inside the kingdom clusters.


You can surely reuse the `resource-setup-app` label. 
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r5, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0mJZQC1SdCYrbgzty:-Mv1EKvR9362gHom_6H0:b-v5vi90) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L15)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

It feel weird to deploy something under `integration` to GKE.

I assume this code should only be used in in-memory integration test
</blockquote></details>

+1. `integration` package is for in-memory integration test. This should likely go next to the other resource setup.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 110 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0ma3l3HE2jh7IaUBL:-Mv1Ei3R3_qWi6hj9zOi:b-4zvq43) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L110)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Doesn't panel exchange need to use actual certificate to do something?
</blockquote></details>

Regardless of whether it does, I'm pretty sure this call will just fail. IIRC, the service will actually parse this certificate to pull out the AKID and expiration date.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 1 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/k8s/panel_match_resource_setup.cue, line 17 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0kYqk2Xc7tUeczVXv:-Mv5Qzkj8jeXkxnhf1T1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/k8s/panel_match_resource_setup.cue#L17)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

what is this PanelMatchResourceSetup job doing?

creating a EDP and a MP?

I didn't see any data related to EDP and MP.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0mJZQC1SdCYrbgzty:-Mv5R-ss6E-0nZsoPSGq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

+1. `integration` package is for in-memory integration test. This should likely go next to the other resource setup.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 110 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0ma3l3HE2jh7IaUBL:-Mv5QxVW4cUURT-T0NqI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L110)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Regardless of whether it does, I'm pretty sure this call will just fail. IIRC, the service will actually parse this certificate to pull out the AKID and expiration date.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r8, 1 of 2 files at r9, 3 of 3 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: all files reviewed, 4 unresolved discussions (waiting on @wangyaopw and @yunyeng)

___
*[src/main/k8s/kingdom.cue, line 139 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv65M5o0xC3NEMU3VEE:-Mv65M5o0xC3NEMU3VEF:byfav51) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/692a53c1e56f27f91141b8d514544907fdb98581/src/main/k8s/kingdom.cue#L139)):*
> ```CUE
> 				"system-api-server-app",
> 				"resource-setup-app",
> 				"panel-match-resource-setup-app",
> ```

Drop this, since it looks like this job is sharing the app label `resource-setup-app`.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 14 of 16 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/k8s/kingdom.cue, line 139 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv65M5o0xC3NEMU3VEE:-Mv6ivabA4jUEVtsPlsk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/692a53c1e56f27f91141b8d514544907fdb98581/src/main/k8s/kingdom.cue#L139)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop this, since it looks like this job is sharing the app label `resource-setup-app`.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: all files reviewed, 3 unresolved discussions (waiting on @wangyaopw)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 11 of 18 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt, line 29 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-MvK7v-J-jBJJMmmohpi:-MvK7v-K9xvKfFZAjW9g:bbbxwv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8739a8554120476353b93cbe255ad11dcfe79518/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt#L29)):*
> ```Kotlin
>     val internalCertificateId = idGenerator.generateInternalId()
> 
>     dataProvider.certificate.toInsertMutation(internalCertificateId).bufferTo(transactionContext)
> ```

@sanjayvas PTAL here. This line is broken, I think should be using the transactionContext.bufferInsertMutation. Even we remove this line there is a Certificate written in Certificates table btw.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 17 of 18 files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt, line 29 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-MvK7v-J-jBJJMmmohpi:-MvKOMDh4hr_KBplP7dn:b-j8uiw8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8739a8554120476353b93cbe255ad11dcfe79518/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt#L29)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

My Change fixes things. Old code uses "insertMutation" which is buggy. Reviewable somehow doesn't show the diff properly.
</blockquote></details>

How is `insertMutation` buggy exactly? We should fix whatever bug given that it's used elsewhere rather than just working around it here.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 16 of 18 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt, line 29 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-MvK7v-J-jBJJMmmohpi:-MvLK6g8CULls_i1U4TW:b19rgn1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8739a8554120476353b93cbe255ad11dcfe79518/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

How is `insertMutation` buggy exactly? We should fix whatever bug given that it's used elsewhere rather than just working around it here.
</blockquote></details>

Talked offline, deployed, and tested several times. Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 110 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-Mv0ma3l3HE2jh7IaUBL:-MvLJNRJC3mfPirlUny9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/996fda5e06ed122f31f8537ec4710d31234e7fd4/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L110)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think Reviewable is showing the diffs for each commit fine. What I missed was that this is calling the internal service, which doesn't actually parse the certificate DER. I thought this was calling the public service, which would fail.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: all files reviewed, 4 unresolved discussions (waiting on @wangyaopw and @yunyeng)

**Review by yunyeng — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-:-MvLNGVl8nrugWkxOBVW:bnfp4nl)* status: 16 of 18 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

**Review by yunyeng — COMMENTED** [review]
> Dismissed @wangyaopw from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: 16 of 18 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> Reviewed 3 of 12 files at r8, 2 of 3 files at r10, 2 of 3 files at r11, 1 of 2 files at r12, 3 of 7 files at r13, 1 of 1 files at r16, 1 of 2 files at r17, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by yunyeng — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436#-:-MvLWSEG8sykAAP3Xjmc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> Reviewed 1 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> Reviewed 1 of 12 files at r8, 1 of 2 files at r12, 1 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> Reviewed 1 of 12 files at r8, 1 of 2 files at r12, 1 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> Reviewed 1 of 12 files at r8, 1 of 2 files at r12, 1 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
