### PR TITLE
fix: Update Kingdom's duchy id config to select fulfillingDuchyId for HMSS

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737)

**Comment by renjiezh** [comment]
Fix https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1735

**Comment by renjiezh** [comment]
Deployment needs to update the content of `hmss_protocol_config_config.textproto`

**Review by SanjayVas — APPROVED** [review]
The `--hmss_protocol_config_config` flag was only added in b836fc722d63810f9c763f0e09f1edcc42304faa, which has never made it into a full release, so we don't need to specifically call it out in 0.5.7 release notes. It's still indeed a breaking change though.

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737#-:-O3ihAwj-JLTaAvguRcj:be3kotk)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737#-O3ijgXx8Z5ubvjBpXtL:-O3ijgXx8Z5ubvjBpXtM:b-spgnh5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d910f586ed8fb9379b56eaa063b3248fb8b4db35/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L51)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.writers.SpannerWriter.TransactionScope
> 
> private const val HMSS_MINIMUM_NUMBER_OF_REQUIRED_DUCHIES = 3
> ```

nit: this is technically not just the minimum, but also the maximum



_Suggestion:_
```Kotlin
HMSS_DUCHY_COUNT
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737#-O3ijspmCGY2hRYNsvVf:-O3ijWjlDXj-3aY5TCds:b-kjlsi8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d910f586ed8fb9379b56eaa063b3248fb8b4db35/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L51)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.writers.SpannerWriter.TransactionScope
> 
> private const val HMSS_MINIMUM_NUMBER_OF_REQUIRED_DUCHIES = 3
> ```

nit: define new constants in companion object. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin



_Suggestion:_
```Kotlin
HMSS_REQUIRED_DUCHIES
```

**Review by ple13 — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737#-O3nGI3CAf5oetzktLUs:-O3nGI3CAf5oetzktLUt:b-2yt4it) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d910f586ed8fb9379b56eaa063b3248fb8b4db35/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L57)):*
> ```Kotlin
> /** Implementation of `wfa.measurement.api.v2alpha.RequisitionFulfillment` gRPC service. */
> class RequisitionFulfillmentService(
>   private val duchyId: String,
> ```

nit: use externalDuchyId instead of duchyId.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737#-O3nGI3CAf5oetzktLUs:-O3nSegZ17whEjqaI-rM:b2zl1ix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d910f586ed8fb9379b56eaa063b3248fb8b4db35/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L57)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

nit: use externalDuchyId instead of duchyId.
</blockquote></details>

In public service impls, any ID is assumed to be the external ID. The public service impl doesn't even have access to the internal DB IDs. Those are a private implementation detail of the internal service impl.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 476 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737#-O4Dk4Zj8EGlST7gC7Jz:-O4Dk4Zj8EGlST7gC7K-:bagi8ba) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f94add779daf87134e34c8f5c504943f78477ad/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L476)):*
> ```Kotlin
> 
>   companion object {
>     private const val HMSS_DUCHY_COUNT = 3
> ```

this feel really ugly to bury this here in a spanner write. I'd prefer it either stay in the protocol config or be a flag passed in or something like that.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737)* status: 11 of 16 files reviewed, 1 unresolved discussion (waiting on @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 476 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737#-O4Dk4Zj8EGlST7gC7Jz:-O4HB-7FABQCODxiB6LC:br89e1q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f94add779daf87134e34c8f5c504943f78477ad/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L476)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this feel really ugly to bury this here in a spanner write. I'd prefer it either stay in the protocol config or be a flag passed in or something like that.
</blockquote></details>

Done.
Good point.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 13 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1737)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
