### PR TITLE
Add network policies to kingom and duchy

### PR DESCRIPTION
**Pull request by oliver-amzn**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
Can you please write a doc/instruction on what this is doing?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-:-MkP1gEg3Lo_GbK5sJyK:bnmbdls)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/k8s/kingdom.cue, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP0Eu0AD1DXb0_2I62:-MkP0Eu0AD1DXb0_2I63:b-lx7nr2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70e6f85da2c5de9a3667ffbf1dd04447371a34fc/src/main/k8s/kingdom.cue#L78)):*
> ```
>  kingdom_network
> ```

Rename this to `kingdom_internal_network`?


How do we handle external network? e.g., duchy to kingdom?
___
*[src/main/k8s/kingdom.cue, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP-_hK7iuYtK1vrhGJ:-MkP-_hL3hRg1we8Ey1V:b-u518h7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70e6f85da2c5de9a3667ffbf1dd04447371a34fc/src/main/k8s/kingdom.cue#L80)):*
> ```CUE
>   kingdom_network: [
> 				#NetworkPolicy & {
> 					_name: "public-api-server-to-system-api-server"
> ```

is this code to allow `public-api-server` to talk to `system-api-server`?


In the kingdom, we need the `v2alpha-public-api-server` talks to `v2alpha-public-api-server` and  `system-api-server` talks to `v2alpha-public-api-server`
___
*[src/main/k8s/kingdom_and_three_duchies_local.cue, line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP0YpG1vmAwD6h3Evn:-MkP0YpG1vmAwD6h3Evo:b-yny2wx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70e6f85da2c5de9a3667ffbf1dd04447371a34fc/src/main/k8s/kingdom_and_three_duchies_local.cue#L165)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> duchy_network: "nw": #NetworkPolicy & {
> 		_name: "herald-and-mill"
> 		_sourceMatchLabels: "liquid-legions-v2-mill-daemon-pod"
> 		_destinationMatchLabels: "herald-daemon-pod"
> 	}
> ```
</details>

mill doesn't talk to herald

In duchy, we have the following traffic

`herald-daemon-pod`  to `spanner-computations-server-pod`
`liquid-legions-v2-mill-daemon-pod` to `spanner-computations-server-pod`
`async-computation-control-server-pod` to `spanner-computations-server-pod`
`requisition-fulfillment-server-pod` to `spanner-computations-server-pod`
`computation-control-server-pod` to `async-computation-control-server-pod`

Also the actual name of the duchy has the duchy_id prefx. Do we need the prefix in the policy?

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/k8s/kingdom_and_three_duchies_local.cue, line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP0YpG1vmAwD6h3Evn:-MkP1xrl4CmOd77D1eBo:b5qm0hp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70e6f85da2c5de9a3667ffbf1dd04447371a34fc/src/main/k8s/kingdom_and_three_duchies_local.cue#L165)):*
> the actual name of the duchy 
Typo, "the actual name of the pods have the duchy_id as the prefix"

**Review by oliver-amzn — COMMENTED** [review]
Yup, will do, wasn't quite done yet.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-:-MkcTuYP-iuG8jMIQiqd:b3lmeza)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/k8s/kingdom.cue, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP0Eu0AD1DXb0_2I62:-MkcRxCf1IvhY3gdDAu0:b7o6o46) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca1516b1ffa688bc9d768e8c4ce93480d3bb83e5/src/main/k8s/kingdom.cue#L78)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  kingdom_network
> ```

Rename this to `kingdom_internal_network`?


How do we handle external network? e.g., duchy to kingdom?
</blockquote></details>

`kingdom_internal_network` - I like that.

Duchy-to-Kingdom connections travel across the big bad internet (BBI) and are not affected by that. It's up to the kingdom operator how they plan to secure the kingdom cluster. We could (should?) have an opinion on that but it's out of scope for this rally ticket.
___
*[src/main/k8s/kingdom.cue, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP-_hK7iuYtK1vrhGJ:-MkcRyCw4okPw062IeZk:bv6osu5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca1516b1ffa688bc9d768e8c4ce93480d3bb83e5/src/main/k8s/kingdom.cue#L80)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

is this code to allow `public-api-server` to talk to `system-api-server`?


In the kingdom, we need the `v2alpha-public-api-server` talks to `v2alpha-public-api-server` and  `system-api-server` talks to `v2alpha-public-api-server`
</blockquote></details>

Can you clarify `v2alpha-public-api-server talks to v2alpha-public-api-server` - is that correct? It needs to be able to talk to itself?
___
*[src/main/k8s/kingdom_and_three_duchies_local.cue, line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP0YpG1vmAwD6h3Evn:-MkcYAHH9YkyNeaOcf-p:b-4rz0p4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca1516b1ffa688bc9d768e8c4ce93480d3bb83e5/src/main/k8s/kingdom_and_three_duchies_local.cue#L165)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> the actual name of the duchy 
Typo, "the actual name of the pods have the duchy_id as the prefix"
</blockquote></details>

We shouldn't need the prefix, the label match is against the name in the metadata, not the name of the pod.

Thanks for the list of relationships, updated.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/k8s/kingdom.cue, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP0Eu0AD1DXb0_2I62:-MkcloeBCmnMXQgC3VGd:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca1516b1ffa688bc9d768e8c4ce93480d3bb83e5/src/main/k8s/kingdom.cue#L78)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

`kingdom_internal_network` - I like that.

Duchy-to-Kingdom connections travel across the big bad internet (BBI) and are not affected by that. It's up to the kingdom operator how they plan to secure the kingdom cluster. We could (should?) have an opinion on that but it's out of scope for this rally ticket.
</blockquote></details>

sg
___
*[src/main/k8s/kingdom.cue, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP-_hK7iuYtK1vrhGJ:-MkcltolBxBQm01xTayl:b-oz76w3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca1516b1ffa688bc9d768e8c4ce93480d3bb83e5/src/main/k8s/kingdom.cue#L80)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Can you clarify `v2alpha-public-api-server talks to v2alpha-public-api-server` - is that correct? It needs to be able to talk to itself?
</blockquote></details>

sorry, it is a typo"we need the `v2alpha-public-api-server` talks to `gcp-kingdom-data-server` and `system-api-server` talks to `gcp-kingdom-data-server`"
___
*[src/main/k8s/kingdom_and_three_duchies_local.cue, line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP0YpG1vmAwD6h3Evn:-MkcmB9s7tG2doQSS2Nk:b59wlno) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca1516b1ffa688bc9d768e8c4ce93480d3bb83e5/src/main/k8s/kingdom_and_three_duchies_local.cue#L165)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

We shouldn't need the prefix, the label match is against the name in the metadata, not the name of the pod.

Thanks for the list of relationships, updated.

</blockquote></details>

Just curious, after adding the policy, will it start blocking connections not included in the list?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/k8s/duchy.cue, line 197 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-Mkcmqh2EzP_4-T77EQx:-Mkcmqh2EzP_4-T77EQy:bqikfg5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5f5150e3e349aea4f305e772b5863632649cef8/src/main/k8s/duchy.cue#L197)):*
> ```
> "nw"
> ```

What is this `nw` used for? maybe use a more informative string?
___
*[src/main/k8s/duchy.cue, line 199 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkcmzdvDS_vVrOFhxSj:-MkcmzdvDS_vVrOFhxSk:b-npugp2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5f5150e3e349aea4f305e772b5863632649cef8/src/main/k8s/duchy.cue#L199)):*
> ```
> herald-and-spanne
> ```

nit: I am wondering if the name pattern of `A_to_B` makes more sense here.

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/k8s/duchy.cue, line 197 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-Mkcmqh2EzP_4-T77EQx:-MkhZSrE1fpOW6UrB4VY:br9p3rm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5f5150e3e349aea4f305e772b5863632649cef8/src/main/k8s/duchy.cue#L197)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> "nw"
> ```

What is this `nw` used for? maybe use a more informative string?
</blockquote></details>

When I didn't have a string there then it wouldn't properly generate the yaml (not generating the outermost level yaml). Not entire sure what's going on, let me look into it again and at least use a more descriptive string.
___
*[src/main/k8s/duchy.cue, line 199 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkcmzdvDS_vVrOFhxSj:-MkhZRUW1G_WPoBHZZ2M:b-3tcry4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5f5150e3e349aea4f305e772b5863632649cef8/src/main/k8s/duchy.cue#L199)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> herald-and-spanne
> ```

nit: I am wondering if the name pattern of `A_to_B` makes more sense here.
</blockquote></details>

I like it, let me change it
___
*[src/main/k8s/kingdom.cue, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP-_hK7iuYtK1vrhGJ:-Mkde7Jt-uabf7WNYixJ:b-ucfknh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca1516b1ffa688bc9d768e8c4ce93480d3bb83e5/src/main/k8s/kingdom.cue#L80)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

sorry, it is a typo"we need the `v2alpha-public-api-server` talks to `gcp-kingdom-data-server` and `system-api-server` talks to `gcp-kingdom-data-server`"
</blockquote></details>

Thanks!
___
*[src/main/k8s/kingdom_and_three_duchies_local.cue, line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP0YpG1vmAwD6h3Evn:-MkhYL5V7-KmC9_W0qel:b-z7m9jo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca1516b1ffa688bc9d768e8c4ce93480d3bb83e5/src/main/k8s/kingdom_and_three_duchies_local.cue#L165)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Just curious, after adding the policy, will it start blocking connections not included in the list?
</blockquote></details>

Yeah.
From the docs here https://kubernetes.io/docs/concepts/services-networking/network-policies/#isolated-and-non-isolated-pods

`Once there is any NetworkPolicy in a namespace selecting a particular pod, that pod will reject any connections that are not allowed by any NetworkPolicy. Other pods ... that are not selected ... will continue to accept all traffic.`

Which means we might need policies so the test runner can talk to the pods here?

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/k8s/kingdom.cue, line 80 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkhbNSrBBpadDGLk1JA:-MkhbNSrBBpadDGLk1JB:bc2bpev) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53c52be0cbe57ff222738bf43517e0ab54f76cd9/src/main/k8s/kingdom.cue#L80)):*
> ```
> public-api-server-to-system-api-server
> ```
public-api-server-to-internal-data-server
___
*[src/main/k8s/kingdom.cue, line 85 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkhbU7OCOtGxbDdYhkk:-MkhbU7OCOtGxbDdYhkl:b-39fdqy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53c52be0cbe57ff222738bf43517e0ab54f76cd9/src/main/k8s/kingdom.cue#L85)):*
> ```
> system-api-server-to-spublic-api-server
> ```
system-api-server-to-internal-data-server
___
*[src/main/k8s/kingdom_and_three_duchies_local.cue, line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP0YpG1vmAwD6h3Evn:-MkhbZiWB2DpIJKsHqpj:b2msp7d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca1516b1ffa688bc9d768e8c4ce93480d3bb83e5/src/main/k8s/kingdom_and_three_duchies_local.cue#L165)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Yeah.
From the docs here https://kubernetes.io/docs/concepts/services-networking/network-policies/#isolated-and-non-isolated-pods

`Once there is any NetworkPolicy in a namespace selecting a particular pod, that pod will reject any connections that are not allowed by any NetworkPolicy. Other pods ... that are not selected ... will continue to accept all traffic.`

Which means we might need policies so the test runner can talk to the pods here? 

</blockquote></details>

We'll run the test runner in its own cluster, so it would be handled by ingress I think

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn)

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/k8s/kingdom.cue, line 80 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkhbNSrBBpadDGLk1JA:-MkhcmMo5lVfCQStJyst:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53c52be0cbe57ff222738bf43517e0ab54f76cd9/src/main/k8s/kingdom.cue#L80)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> public-api-server-to-system-api-server
> ```
public-api-server-to-internal-data-server
</blockquote></details>

Done.
___
*[src/main/k8s/kingdom.cue, line 85 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkhbU7OCOtGxbDdYhkk:-MkhcmCkASK_RY-kAWTx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53c52be0cbe57ff222738bf43517e0ab54f76cd9/src/main/k8s/kingdom.cue#L85)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> system-api-server-to-spublic-api-server
> ```
system-api-server-to-internal-data-server
</blockquote></details>

Done.
___
*[src/main/k8s/kingdom_and_three_duchies_local.cue, line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP0YpG1vmAwD6h3Evn:-Mkhcn7t3W143f1hwXig:bzfuoug) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca1516b1ffa688bc9d768e8c4ce93480d3bb83e5/src/main/k8s/kingdom_and_three_duchies_local.cue#L165)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

We'll run the test runner in its own cluster, so it would be handled by ingress I think
</blockquote></details>

Oh really? In it's own cluster? Ok, then we should be fine :crossed_fingers:

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @wangyaopw)

___
*[src/main/k8s/kingdom_and_three_duchies_local.cue, line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP0YpG1vmAwD6h3Evn:-MkhdHny66VSABbov2Ki:b-ag0r1u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca1516b1ffa688bc9d768e8c4ce93480d3bb83e5/src/main/k8s/kingdom_and_three_duchies_local.cue#L165)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Oh really? In it's own cluster? Ok, then we should be fine :crossed_fingers: 
</blockquote></details>

Yep. In M1A, all pods and jobs are in the same cluster. In M1B, we will  have a kingdom cluster, server duchy clusters, and a simulator cluster (for all simulator and the test runner).

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @wangyaopw)

___
*[src/main/k8s/kingdom_and_three_duchies_local.cue, line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-MkP0YpG1vmAwD6h3Evn:-MkheO7CE6DLQr42zzhu:bjwa7hh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca1516b1ffa688bc9d768e8c4ce93480d3bb83e5/src/main/k8s/kingdom_and_three_duchies_local.cue#L165)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Yep. In M1A, all pods and jobs are in the same cluster. In M1B, we will  have a kingdom cluster, server duchy clusters, and a simulator cluster (for all simulator and the test runner).
</blockquote></details>

:tada:

**Review by oliver-amzn — COMMENTED** [review]
Added a blurb what this does

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290#-:-Mkhnu-q4M6Nm1hmVjN7:bxg7tyg)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/290)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
