### PR TITLE
Implement Get Method for ExchangeStepAttempts service

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241)* status: all files reviewed, 1 unresolved discussion (waiting on @kgaynor, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241#-MiOvGRq6kFLmaXVKkWj:-MiOvGRq6kFLmaXVKkWk:b82chk1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6607ccc72d1756326df117387fe425b01cb7fa81/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt#L52)):*
> ```Kotlin
>           )
>           appendClause("AND ExchangeStepAttempts.Date = @date")
>           appendClause("AND ExchangeStepAttempts.StepIndex = @step_index")
> ```

Multiline string please

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241)* status: all files reviewed, 1 unresolved discussion (waiting on @kgaynor and @yunyeng)

**Review by kgaynor — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241#-MiOvGRq6kFLmaXVKkWj:-Mic1CwR2Ig4o6l_Yzg5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6607ccc72d1756326df117387fe425b01cb7fa81/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Multiline string please
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241#-Mic0l7D2mAOuEls30eR:-Mic0l7E-h_k6JJig1mE:b-1u8ppx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8068c0b6e8c1ef12a49211679f2b4d119d0b14d5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt#L55)):*
> ```Kotlin
>               AND ExchangeStepAttempts.AttemptIndex = @attempt_index
>               )
>               """.trimIndent()
> ```

Nitpick:

It's a little hard to see how things are aligned here, but please make sure it's like this:

```
"""
WHERE ...
  AND ...
  AND ...
""".trimIndent()
```

* First quotes on the first and last lines are aligned
* W in "WHERE" is aligned with first quote
* "AND" has two spaces of additional indentation (so the E in WHERE and the D in AND are in the same column)

Thanks!

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241#-Mic0l7D2mAOuEls30eR:-Mic40LqALNNtD0sLQPE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8068c0b6e8c1ef12a49211679f2b4d119d0b14d5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Nitpick:

It's a little hard to see how things are aligned here, but please make sure it's like this:

```
"""
WHERE ...
  AND ...
  AND ...
""".trimIndent()
```

* First quotes on the first and last lines are aligned
* W in "WHERE" is aligned with first quote
* "AND" has two spaces of additional indentation (so the E in WHERE and the D in AND are in the same column)

Thanks!
</blockquote></details>

Done.

**Review by yunyeng — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241)* status: all files reviewed, 2 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt, line 61 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241#-MicF4CQ8dq_JY8jqQb2:-MicF4CQ8dq_JY8jqQb3:buy5zpl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb38dc58822a0f6b0c6d174a69da10ed4b88024e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt#L61)):*
> ```Kotlin
>               appendClause(
>                 """
>               AND ExchangeSteps.DataProviderId = (
> ```

These too please!
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt, line 71 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241#-MicF8W23nHfWeoHZm2u:-MicF8W23nHfWeoHZm2v:bqujbyh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb38dc58822a0f6b0c6d174a69da10ed4b88024e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt#L71)):*
> ```Kotlin
>               appendClause(
>                 """
>               AND ExchangeSteps.ModelProviderId = (
> ```

Here too

**Review by yunyeng — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt, line 61 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241#-MicF4CQ8dq_JY8jqQb2:-MicJLP19JdvHgUwjFsF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb38dc58822a0f6b0c6d174a69da10ed4b88024e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt#L61)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

These too please!
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt, line 71 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241#-MicF8W23nHfWeoHZm2u:-MicJLgL12YXYXWoffDt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb38dc58822a0f6b0c6d174a69da10ed4b88024e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Here too
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
