### PR TITLE
Add measurement consumer config to reporting principal

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N7vhxxK-xa92VK6Ga6B:-N7vhxxK-xa92VK6Ga6C:bhejfis) (no related file):*
How does this relate to #639? They seem to be doing the same thing.

___

**Comment by tristanvuong2021** [comment]
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N7vhxxK-xa92VK6Ga6B:-N7vil1y7MwNezBW3nga:b-e6oylw) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

How does this relate to #639? They seem to be doing the same thing.
</blockquote></details>

This is the measurement consumer config that looks up the api key I stripped from my other PR

**Comment by tristanvuong2021** [comment]
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N7vhxxK-xa92VK6Ga6B:-N7vj0Hk94wNYK1EJONu:b-yrxo04) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This is the measurement consumer config that looks up the api key I stripped from my other PR
</blockquote></details>

It is building on top of #639

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 126 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N7vl_5pEYMXVCgc3Rfl:-N7vl_5pEYMXVCgc3Rfm:b5zan9s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a346c603a3b8e47d5db3db694c33c5ae63befb3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L126)):*
> ```Kotlin
>   override suspend fun listReports(request: ListReportsRequest): ListReportsResponse {
>     val principal: Principal<*> = principalFromCurrentContext
>     val apiAuthenticationKey = apiKeyFromCurrentContext
> ```

Can this just be added as another field on the MC principal? This would mean putting the API key lookup in the same interceptor.

This would give a clearer result. I'm imagining even if we end up with a more granular principal type of an MC user, then the Principal object would still contain the MC ID and API key.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 126 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N7vl_5pEYMXVCgc3Rfl:-N8-_kW69cDJa6YhoM68:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a346c603a3b8e47d5db3db694c33c5ae63befb3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L126)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can this just be added as another field on the MC principal? This would mean putting the API key lookup in the same interceptor.

This would give a clearer result. I'm imagining even if we end up with a more granular principal type of an MC user, then the Principal object would still contain the MC ID and API key.
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N8-lqtQB8rjhbhEBd02:-N8-lqtQB8rjhbhEBd03:b-hpxs96) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c43c4d6555ecdc527bcae5f73be2f1f2989318f1/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L53)):*
> ```Kotlin
>     val apiAuthenticationKey: String = principal.config.apiKey
> 
>     if (apiAuthenticationKey.isBlank()) {
> ```

nit: you can enforce this in the interceptor, as every MC principal must have an API key.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: 0 of 16 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N853p_q6EB5UvYkV2Jk:-N853p_q6EB5UvYkV2Jl:b6c0ym5) (no related file):*
@sanjayvas Redid it based on the changes to principal

___

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 3 of 13 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: 11 of 16 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N853p_q6EB5UvYkV2Jk:-N864R7d3B13dVBC8-Yc:b-dz3j6u) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

@sanjayvas Redid it based on the changes to principal
</blockquote></details>

@sanjayvas Added new fields to the config proto for signing

___

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 339 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N8ARs_VCX4XWP9X1pf7:-N8ARs_VCX4XWP9X1pf8:b-t84sue) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49aff1d18dac64485dcc10bb1b64d72e2f369d3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L339)):*
> ```Kotlin
> 
>     val signingPrivateKeyDer: ByteString =
>       getRuntimePath(Paths.get(principal.config.signingPrivateKeyDir))!!
> ```

This finds the path in Bazel runfiles, which is where a file gets placed if it's a `data` dependency in the Bazel target.

I assume this gets read from a secret or something instead.
___
*[`src/main/proto/wfa/measurement/config/reporting/measurement_consumer_config.proto` line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N8ASsFOBrjolIwTzc9Z:-N8ASsFOBrjolIwTzc9_:b-74aqr7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49aff1d18dac64485dcc10bb1b64d72e2f369d3/src/main/proto/wfa/measurement/config/reporting/measurement_consumer_config.proto#L26)):*
> ```protobuf
>   // Resource name of the `Certificate` from the CMMS public api.
>   string signing_certificate_name = 2;
>   // Directory where private key is located.
> ```

This should be a command-line option for the key storage dir rather than being in the per-MC configuration.

In practical terms, it would likely just be the volume mount for the secret where these are held.



_Code quote:_
```protobuf
  // Directory where private key is located.
  string signing_private_key_dir = 3;
```
___
*[`src/main/proto/wfa/measurement/config/reporting/measurement_consumer_config.proto` line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N8ATdL-1MgmBUunKKPa:-N8ATdL-1MgmBUunKKPb:b-bsmz49) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49aff1d18dac64485dcc10bb1b64d72e2f369d3/src/main/proto/wfa/measurement/config/reporting/measurement_consumer_config.proto#L28)):*
> ```protobuf
>   // Directory where private key is located.
>   string signing_private_key_dir = 3;
>   // Filename of the private key.
> ```

Something like "Relative path to private key within the private key store". This way even if we end up doing a separate key store/secret for each MC, we can still just have a single flag for the parent directory of the volume mounts.



_Code quote:_
```protobuf
Filename of the private key.
```

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 1 of 13 files at r2, 5 of 12 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: all files reviewed, 5 unresolved discussions (waiting on @duliomatos1 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalServerInterceptor.kt` line 108 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N8AX0dO2w58k7A6Ce6l:-N8AX0dO2w58k7A6Ce6m:b7mxdni) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49aff1d18dac64485dcc10bb1b64d72e2f369d3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalServerInterceptor.kt#L108)):*
> ```Kotlin
>       1 -> {
>         val principal = principals.single()
>         if (principal != null) {
> ```

shouldn't it throw an error if its null?
Also, if you're going to throw an error I kind of prefer
```
        val principal = requireNotNull(principals.single()) { "some error message" }
          if (
            principal.config.apiKey.isBlank() ||
              principal.config.signingCertificateName.isBlank() ||
              principal.config.signingPrivateKeyDir.isBlank() ||
              principal.config.signingPrivateKeyFile.isBlank()
          ) {
            return error(
              call,
              "Missing configuration fields for principal",
              Status.FAILED_PRECONDITION
            )
          }

```
alternatively, you could do something like
```
requireNotNull(singleOrNull(principals))
``` 
that automatically throws errors for multiple or none.

**Comment by tristanvuong2021** [comment]
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalServerInterceptor.kt` line 108 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N8AX0dO2w58k7A6Ce6l:-N8Acf9S5IDKr_QjNGHJ:bv5z9zj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49aff1d18dac64485dcc10bb1b64d72e2f369d3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalServerInterceptor.kt#L108)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't it throw an error if its null?
Also, if you're going to throw an error I kind of prefer
```
        val principal = requireNotNull(principals.single()) { "some error message" }
          if (
            principal.config.apiKey.isBlank() ||
              principal.config.signingCertificateName.isBlank() ||
              principal.config.signingPrivateKeyDir.isBlank() ||
              principal.config.signingPrivateKeyFile.isBlank()
          ) {
            return error(
              call,
              "Missing configuration fields for principal",
              Status.FAILED_PRECONDITION
            )
          }

```
alternatively, you could do something like
```
requireNotNull(singleOrNull(principals))
``` 
that automatically throws errors for multiple or none.

</blockquote></details>

Ending up moving the check back to the initial principal creation so it doesn't have to be done every time.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: 11 of 49 files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 339 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N8ARs_VCX4XWP9X1pf7:-N8AccJR7GTjOpco54qE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49aff1d18dac64485dcc10bb1b64d72e2f369d3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L339)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This finds the path in Bazel runfiles, which is where a file gets placed if it's a `data` dependency in the Bazel target.

I assume this gets read from a secret or something instead.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/config/reporting/measurement_consumer_config.proto` line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N8ASsFOBrjolIwTzc9Z:-N8AccwK6DDNmYTzo1ZU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49aff1d18dac64485dcc10bb1b64d72e2f369d3/src/main/proto/wfa/measurement/config/reporting/measurement_consumer_config.proto#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be a command-line option for the key storage dir rather than being in the per-MC configuration.

In practical terms, it would likely just be the volume mount for the secret where these are held.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/config/reporting/measurement_consumer_config.proto` line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640#-N8ATdL-1MgmBUunKKPa:-N8AcdCj-ydtBbLLe9iZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d49aff1d18dac64485dcc10bb1b64d72e2f369d3/src/main/proto/wfa/measurement/config/reporting/measurement_consumer_config.proto#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Something like "Relative path to private key within the private key store". This way even if we end up doing a separate key store/secret for each MC, we can still just have a single flag for the parent directory of the volume mounts.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 38 files at r5, 33 of 33 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 6 files at r4, 1 of 38 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

**Review by tristanvuong2021 — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/640)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
