### PR TITLE
Fix page token usage.

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #951** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/951" target="_blank">Graphite</a> 
    * **PR #963** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/963" target="_blank">Graphite</a> 
      * **PR #959** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/959" target="_blank">Graphite</a> 
        * **PR #968** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/968" target="_blank">Graphite</a> 
          * **PR #971** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/971" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/971?utm_source=stack-comment).

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @riemanli)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971#-NTzwfkc-t3iUVOu5zrQ:-NTzwfkd0gM4llvrx5wi:bljoqpr) (no related file):*
Since you are changing the package anyways, there should be a page token in the reporting folder. So kingdom and reporting get their own page tokens. Right now, the page token proto has both kingdom and reporting specific messages, but the path is technically the kingdom.

___

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971#-NTzwfkc-t3iUVOu5zrQ:-NU-JQwGEUoQoB0SMRhi:b-25ok4r) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Since you are changing the package anyways, there should be a page token in the reporting folder. So kingdom and reporting get their own page tokens. Right now, the page token proto has both kingdom and reporting specific messages, but the path is technically the kingdom.
</blockquote></details>

That's a good point. For that, do I create a page token proto for both v1 and v2 or separate page token protos for each version?

___

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @riemanli)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971#-NTzwfkc-t3iUVOu5zrQ:-NU2YdDY4hI033Vbha9k:b9b690p) (no related file):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

That's a good point. For that, do I create a page token proto for both v1 and v2 or separate page token protos for each version?
</blockquote></details>

I think it is possible to get away with just one.

___

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971#-NTzwfkc-t3iUVOu5zrQ:-NU3pc2l73h4VnQ-J15w:b-wpvm1c) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I think it is possible to get away with just one.
</blockquote></details>

I ended up creating two for each version because we changed the naming from reference ID to CMMS ID. PTAL.

___

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 14 files at r1, 13 of 14 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971)* status: all files reviewed, 3 unresolved discussions (waiting on @riemanli)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 4 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971#-NU3rubnCuabNt_xfXQ2:-NU3rubnCuabNt_xfXQ3:bqjduql) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/43b9bad56690c1a6ff6946e1aba8eea7adff4b89/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L4)):*
> ```protobuf
>  * Copyright 2021 The Cross-Media Measurement Authors
>  *
>  * Licensed under the Apache License, Version 2.0 (the "License");
> ```

I think the proto files still have the // for the license header
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/page_token.proto` line 10 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971#-NU3s13EBDt6JyRIi7Ge:-NU3s13EBDt6JyRIi7Gf:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/43b9bad56690c1a6ff6946e1aba8eea7adff4b89/src/main/proto/wfa/measurement/reporting/v1alpha/page_token.proto#L10)):*
> ```protobuf
>  *     http://www.apache.org/licenses/LICENSE-2.0
>  *
>  * Unless required by applicable law or agreed to in writing, software
> ```

ditto
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page_token.proto` line 10 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971#-NU3s5IW1SdpbcfOkGwt:-NU3s5IX2oyzTVAD87gw:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/43b9bad56690c1a6ff6946e1aba8eea7adff4b89/src/main/proto/wfa/measurement/reporting/v2alpha/page_token.proto#L10)):*
> ```protobuf
>  *     http://www.apache.org/licenses/LICENSE-2.0
>  *
>  * Unless required by applicable law or agreed to in writing, software
> ```

ditto

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971)* status: 17 of 20 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 4 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971#-NU3rubnCuabNt_xfXQ2:-NU40hlfBjsx6AiCfNKM:b-sw47i6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/43b9bad56690c1a6ff6946e1aba8eea7adff4b89/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L4)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I think the proto files still have the // for the license header
</blockquote></details>

Ah you're right. Thanks for pointing it out. Fixed.
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/page_token.proto` line 10 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971#-NU3s13EBDt6JyRIi7Ge:-NU41Qq91nyzMel1X5jG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/43b9bad56690c1a6ff6946e1aba8eea7adff4b89/src/main/proto/wfa/measurement/reporting/v1alpha/page_token.proto#L10)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page_token.proto` line 10 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971#-NU3s5IW1SdpbcfOkGwt:-NU41RJdABjY0KaSDlQc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/43b9bad56690c1a6ff6946e1aba8eea7adff4b89/src/main/proto/wfa/measurement/reporting/v2alpha/page_token.proto#L10)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by tristanvuong2021 — APPROVED** [review]

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 6 of 14 files at r1, 10 of 14 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Comment by riemanli** [comment]
@riemanli queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/971).

**Comment by riemanli** [comment]
The [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/971) merge of this pull request was cancelled.

**Review by riemanli — COMMENTED** [review]
> Reviewed 6 of 14 files at r1, 10 of 14 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/971)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
