### PR TITLE
Add integration test for eventgroups

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880)* status: all files reviewed, 3 unresolved discussions (waiting on @jcorilla)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAnEventGroupIntegrationTest.kt` line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880#-NPsANzt7aiZ8vZnjYAd:-NPsANzt7aiZ8vZnjYAe:b2rh6hf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8193ef63587ac449ff4c89948bcb79eb433dde7/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAnEventGroupIntegrationTest.kt#L107)):*
> ```Kotlin
>     val eventGroup1 = createEventGroup("1")
>     val deletedEventGroup1 = deleteEventGroup(eventGroup1.name)
>     assertThat(deletedEventGroup1.state).isEqualTo(EventGroup.State.DELETED)
> ```

Each test method should be focused and have one set of assertions at the end. Use multiple test methods if needed to cover everything. e.g.

* `delete transitions EventGroup state to DELETED`
  * Assert that the `EventGroup` returned by `delete` is the right state
  * Assert that the `EventGroup` returned from `get` matches the one returned from `delete`.
* `list does not return deleted EventGroups`
* `list returns deleted EventGroups when show_deleted is true`
___
*[`src/test/kotlin/org/wfanet/measurement/integration/gcloud/BUILD.bazel` line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880#-NPsC5x36J9rxsJpB5pS:-NPsC5x36J9rxsJpB5pT:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8193ef63587ac449ff4c89948bcb79eb433dde7/src/test/kotlin/org/wfanet/measurement/integration/gcloud/BUILD.bazel#L5)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "duchy_provider_rules",
> ```





_Suggestion:_
```Starlark
duchy_provider_rule
```
___
*[`src/test/kotlin/org/wfanet/measurement/integration/gcloud/BUILD.bazel` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880#-NPsC9eQ5dt_zgJIsUVh:-NPsC9eQ5dt_zgJIsUVi:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8193ef63587ac449ff4c89948bcb79eb433dde7/src/test/kotlin/org/wfanet/measurement/integration/gcloud/BUILD.bazel#L24)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "kingdom_provider_rules",
> ```





_Suggestion:_
```Starlark
kingdom_provider_rule
```

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAnEventGroupIntegrationTest.kt` line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880#-NPsANzt7aiZ8vZnjYAd:-NPt-BlZEhwUtTZLVmXp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8193ef63587ac449ff4c89948bcb79eb433dde7/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAnEventGroupIntegrationTest.kt#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Each test method should be focused and have one set of assertions at the end. Use multiple test methods if needed to cover everything. e.g.

* `delete transitions EventGroup state to DELETED`
  * Assert that the `EventGroup` returned by `delete` is the right state
  * Assert that the `EventGroup` returned from `get` matches the one returned from `delete`.
* `list does not return deleted EventGroups`
* `list returns deleted EventGroups when show_deleted is true`
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/integration/gcloud/BUILD.bazel` line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880#-NPsC5x36J9rxsJpB5pS:-NPshFln-LWEGh1J-rYN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8193ef63587ac449ff4c89948bcb79eb433dde7/src/test/kotlin/org/wfanet/measurement/integration/gcloud/BUILD.bazel#L5)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "duchy_provider_rules",
> ```

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/integration/gcloud/BUILD.bazel` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880#-NPsC9eQ5dt_zgJIsUVh:-NPshGHu5VozPGo333_s:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8193ef63587ac449ff4c89948bcb79eb433dde7/src/test/kotlin/org/wfanet/measurement/integration/gcloud/BUILD.bazel#L24)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "kingdom_provider_rules",
> ```

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAnEventGroupIntegrationTest.kt` line 111 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880#-NPt49sm4gpxajIp04jg:-NPt49sm4gpxajIp04jh:bgkweuk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55c2db001c92b5f525b0bc40681bae875ddcaa36/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAnEventGroupIntegrationTest.kt#L111)):*
> ```Kotlin
> 
>     assertThat(deletedEventGroup.state).isEqualTo(EventGroup.State.DELETED)
>     assertThat(readEventGroup.state).isEqualTo(EventGroup.State.DELETED)
> ```

Compare the actual messages. You'll need to import the other `assertThat` from the ProtoTruth extension.



_Suggestion:_
```Kotlin
assertThat(deletedEventGroup).isEqualTo(readEventGroup)
```

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAnEventGroupIntegrationTest.kt` line 111 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880#-NPt49sm4gpxajIp04jg:-NPtQJBk8D49Fy0gCGI4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55c2db001c92b5f525b0bc40681bae875ddcaa36/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAnEventGroupIntegrationTest.kt#L111)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Compare the actual messages. You'll need to import the other `assertThat` from the ProtoTruth extension.
</blockquote></details>

Done.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/880)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
