### PR TITLE
Update local K8s configuration to be runnable on any cluster.

### PR DESCRIPTION
**Pull request by SanjayVas**
This is prefactoring to support running K8s tests against clusters running in cloud environments.

Note that as a result, the correctness test target no longer manages creation/deletion of the cluster. Instead, a cluster as well as a container registry that is accessible from that cluster are expected to already exist.

https://rally1.rallydev.com/#/?detail=/task/697340982035&fdp=true
https://rally1.rallydev.com/#/?detail=/task/697341347719&fdp=true

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923)

**Comment by SanjayVas** [comment]
See if you can manage to load up the CMMS on KinD using the new instructions. I might try to add instructions for K3s and Minikube as well.

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 55 of 55 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/local/config_files_kustomization.yaml` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923#-NSH6QBH24-ixNyYmyBB:-NSH6QBH24-ixNyYmyBC:bb6ht38) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a9de828a21177864b613bb8401c12d381f7bd0bc/src/main/k8s/local/config_files_kustomization.yaml#L1)):*
> ```YAML
> # Copyright 2022 The Cross-Media Measurement Authors
> ```

2023
___
*[`src/main/k8s/local/README.md` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923#-NSH7EbY1jIzkxmhJ5-W:-NSH7EbY1jIzkxmhJ5-X:b-m3620g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a9de828a21177864b613bb8401c12d381f7bd0bc/src/main/k8s/local/README.md#L21)):*
> ```Markdown
> This guide assumes that you have `kubectl` installed and configured to point to
> the cluster you want to use for testing. You should have some familiarity with
> Kubernetes and `kubectl`.
> ```

Link the appendix up here to make it more obvious how to create the local registry.
___
*[`src/main/k8s/local/README.md` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923#-NSH7oLP4ilfA3RWuEr6:-NSH7oLQAfc-L8qvHVTt:b-vtff6z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a9de828a21177864b613bb8401c12d381f7bd0bc/src/main/k8s/local/README.md#L36)):*
> ```Markdown
> 
> If you just want to run the correctness test, you can use the
> `//src/test/kotlin/org/wfanet/measurement/integration/k8s:EmptyClusterCorrectnessTest`
> ```

Quick instructions on how to run this?
___
*[`src/test/kotlin/org/wfanet/measurement/integration/k8s/AbstractCorrectnessTest.kt` line 2 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923#-NSH6hNqCThHKjB6mh3S:-NSH6hNqCThHKjB6mh3T:bb6ht38) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a9de828a21177864b613bb8401c12d381f7bd0bc/src/test/kotlin/org/wfanet/measurement/integration/k8s/AbstractCorrectnessTest.kt#L2)):*
> ```Kotlin
> /*
>  * Copyright 2022 The Cross-Media Measurement Authors
> ```

2023

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923)* status: 53 of 55 files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/k8s/local/config_files_kustomization.yaml` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923#-NSH6QBH24-ixNyYmyBB:-NSHFsAUEr2BExcOS0f6:b-yq8zl9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a9de828a21177864b613bb8401c12d381f7bd0bc/src/main/k8s/local/config_files_kustomization.yaml#L1)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

2023
</blockquote></details>

GitHub doesn't properly show this, but this file was copied from the `testing` package. Therefore the copyright is correct.
___
*[`src/main/k8s/local/README.md` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923#-NSH7EbY1jIzkxmhJ5-W:-NSIkiNx06j_bWxMjMe3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a9de828a21177864b613bb8401c12d381f7bd0bc/src/main/k8s/local/README.md#L21)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Link the appendix up here to make it more obvious how to create the local registry.
</blockquote></details>

Done.
___
*[`src/main/k8s/local/README.md` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923#-NSH7oLP4ilfA3RWuEr6:-NSIkxxr5jcxBuu6j3TY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a9de828a21177864b613bb8401c12d381f7bd0bc/src/main/k8s/local/README.md#L36)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Quick instructions on how to run this?
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/integration/k8s/AbstractCorrectnessTest.kt` line 2 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923#-NSH6hNqCThHKjB6mh3S:-NSHG2_BEMhoeyDlDZrn:b-fyu8o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a9de828a21177864b613bb8401c12d381f7bd0bc/src/test/kotlin/org/wfanet/measurement/integration/k8s/AbstractCorrectnessTest.kt#L2)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

2023
</blockquote></details>

GitHub doesn't properly show this, but this file was renamed from `CorrectnessTest.kt`. Therefore the copyright is correct.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Comment by SanjayVas** [comment]
Apologies that this is such a large PR. Unfortunately I don't believe this can be split due to how intertwined the correctness test is with the local K8s configuration. Here's an explanation of the changes:

* Decoupling from KinD
  * Stop loading images into KinD, instead using a separate container registry.
    * Update image references to point to the container registry.
    * Use the default image pull policy instead of "Always".
  * Drop kind-specific Bazel rules.
  * Drop the KindCluster JUnit test rule.
* Related correctness test refactoring
  * Extract the AbstractCorrectnessTest base class to allow for multiple implementations.
  * Create a single target for pushing an entire image bundle.
    * Since we're now using a separate registry, pushing all the images to it needs to be simpler.
  * Simplify deployment, which also reduces the complexity of the correctness test implementation.
    * Run resource setup locally.
    * Automate more configuration using Kustomize and Bazel rules.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 46 of 55 files at r1, 3 of 5 files at r2, 3 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
