### PR TITLE
Add folder structure for EventFiltration and PrivacyBudgetManager + cel-java dependency

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/440)

### CODE REVIEW

**Review by duliomatos1 — APPROVED** [review]
LG

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/440#-:-Mvczic23pgFG9GtGJ56:b32vy8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg and @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/440)* status: all files reviewed, 2 unresolved discussions (waiting on @matthewclegg and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/440#-Mve7PDB0f7hmWwbZl64:-Mve7PDC0QvwaHTKnFeL:ba28tvv) (no related file):*
Folder structure needs to match JVM package names, which are all lowercase.

---
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/440#-Mve7XrXAMyHzvgOKmZP:-Mve7XrXAMyHzvgOKmZQ:b-mp0r02) (no related file):*
Is there a specific reason that you're doing this as a separate PR? The conventional approach is to do this as part of the first PR that uses it.

---

**Comment by uakyol** [comment]
@SanjayVas changed the folder names. Created the folder structure because Dulio will be working on the validation library and wanted to point him where to put the code also wanted to see what you think about going for this top level eventdataprovider folder.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/440)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/440#-Mve7PDB0f7hmWwbZl64:-MveHjfm1r_CwVsl_LQs:byb3v8c) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Folder structure needs to match JVM package names, which are all lowercase.
</blockquote></details>

sorry, didn't see your comments here first, mistakenly commented on github ui.

Thanks, I changed it

---
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/440#-Mve7XrXAMyHzvgOKmZP:-MveHsMY6kaI6uucPvEr:b-yw3ued) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is there a specific reason that you're doing this as a separate PR? The conventional approach is to do this as part of the first PR that uses it.
</blockquote></details>

Created the folder structure because Dulio will be working on the validation library and wanted to point him where to put the code also wanted to see what you think about going for this top level eventdataprovider folder.

---

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/440)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Pull request merged**
