### PR TITLE
Add covariance calculation for hmss.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1702)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @renjiezh)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiayu-google and @renjiezh)

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiayu-google and @renjiezh)

**Review by renjiezh — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1702)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiayu-google)

**Review by jiayu-google — APPROVED** [review]
:lgtm: thanks Phi!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1702#-:-O2rjI070Z6_T28yTdZH:b-rqmkfc)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
