### PR TITLE
Add internal api keys protos and schema changes.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 394 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-MprcUbK1ylRDcemTAhg:-MprcUbK1ylRDcemTAhh:bey56n6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3491d7fd4a5ac006328b03e4552cf6396e27245e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L394)):*
> ```
>   ApiKeyId INT64 NOT NULL,
> 
>   AccountId INT64 NOT NULL,
> ```

API Keys are owned by MCs, not by Accounts. Any Account that owns an MC can modify its API keys.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 398 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-Mprbw972DrULR8XKHD5:-Mprbw972DrULR8XKHD6:bfy4kc9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3491d7fd4a5ac006328b03e4552cf6396e27245e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L398)):*
> ```
> STRING
> ```
BYTES
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 407 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-Mprc5s17lvv9bzNGGbV:-Mprc5s17lvv9bzNGGbW:b1sc60f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3491d7fd4a5ac006328b03e4552cf6396e27245e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L407)):*
> ```
> ) PRIMARY KEY (ApiKeyId);
> 
> CREATE UNIQUE INDEX ApiKeysByAuthenticationKeyHash
> ```

Not sure this is strictly necessary. I think we'll have the external ApiKey ID whenever we need to do a lookup. Therefore, these also need not be unique (but they likely will be in practice).

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 407 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-Mprc5s17lvv9bzNGGbV:-MproiBq654bPsooUswv:b-dikw2h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3491d7fd4a5ac006328b03e4552cf6396e27245e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L407)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not sure this is strictly necessary. I think we'll have the external ApiKey ID whenever we need to do a lookup. Therefore, these also need not be unique (but they likely will be in practice).
</blockquote></details>

What about when the api authentication key is passed through call credentials.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 407 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-Mprc5s17lvv9bzNGGbV:-MprywpK1fV9_3bWWOtq:b-rdvrnc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3491d7fd4a5ac006328b03e4552cf6396e27245e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L407)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

What about when the api authentication key is passed through call credentials.
</blockquote></details>

In that case we should know the MC they're wanting to act as, so I suppose this can be unique for a given MC.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 394 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-MprcUbK1ylRDcemTAhg:-MpsR6b2B4n72_PqqcdA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3491d7fd4a5ac006328b03e4552cf6396e27245e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L394)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

API Keys are owned by MCs, not by Accounts. Any Account that owns an MC can modify its API keys.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 398 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-Mprbw972DrULR8XKHD5:-MpsR5tK8wIohWESvb07:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3491d7fd4a5ac006328b03e4552cf6396e27245e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L398)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> STRING
> ```
BYTES
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 116 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-MpsRsmb9znqxWqC4Fn6:-MpsRsmc8fdpB-ASWNOw:b2cir6p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f75129b15a175d8bbe0123212b8eb831a0aed3c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L116)):*
> ```
> MAX
> ```
nit: if we know we're using SHA256, we can just make this 256 bits = 32 bytes
___
*[src/main/proto/wfa/measurement/internal/kingdom/api_key.proto, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-MpsZZc45c_8o64-f2JW:-MpsZJ3B8bpn_12Zp67n:b-l4a5p1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f75129b15a175d8bbe0123212b8eb831a0aed3c0/src/main/proto/wfa/measurement/internal/kingdom/api_key.proto#L24)):*
> ```protobuf
> // Proto representation of the internal ApiKey entity type.
> message ApiKey {
>   oneof parent {
> ```

I don't think we need to care about other possible parent types at this point. There's enough code changes needed for supporting an alternative parent that it wouldn't be a huge burden to add the `oneof` at that time.
___
*[src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-MpsYyNCCvwwFyp0ZiKW:-MpsYyNCCvwwFyp0ZiKX:b8uu3j1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f75129b15a175d8bbe0123212b8eb831a0aed3c0/src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto#L27)):*
> ```protobuf
> service ApiKeys {
>   rpc CreateApiKey(ApiKey) returns (ApiKey);
> ```

Do we need a GetApiKeyByAuthorizationHash or something for principal lookup?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/proto/wfa/measurement/internal/kingdom/api_key.proto, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-MpsZZc45c_8o64-f2JW:-MpskFTm3DO3ICRnfQBg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f75129b15a175d8bbe0123212b8eb831a0aed3c0/src/main/proto/wfa/measurement/internal/kingdom/api_key.proto#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think we need to care about other possible parent types at this point. There's enough code changes needed for supporting an alternative parent that it wouldn't be a huge burden to add the `oneof` at that time.
</blockquote></details>

Done.

**Comment by tristanvuong2021** [comment]
___
*[src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-MpsYyNCCvwwFyp0ZiKW:-MpwNTUwCcs9PCZgU067:bwu14jt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f75129b15a175d8bbe0123212b8eb831a0aed3c0/src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we need a GetApiKeyByAuthorizationHash or something for principal lookup?
</blockquote></details>

Added a new method.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-MpsYyNCCvwwFyp0ZiKW:-Mpwc0P65SUdaUV1W1MI:beadzxe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f75129b15a175d8bbe0123212b8eb831a0aed3c0/src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto#L27)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Added a new method.
</blockquote></details>

Shouldn't this return the MeasurementConsumer rather than the ApiKey, as that's the principal? It would throw an error if the ApiKey has been revoked.

**Comment by tristanvuong2021** [comment]
___
*[src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-MpsYyNCCvwwFyp0ZiKW:-MpxLObO-qVuCpAPADpG:b-cjgdpl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f75129b15a175d8bbe0123212b8eb831a0aed3c0/src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this return the MeasurementConsumer rather than the ApiKey, as that's the principal? It would throw an error if the ApiKey has been revoked.
</blockquote></details>

My current plan is to add the ApiKey to the context or the Account to the context, then compare the MeasurementConsumer id in the ApiKey with the MeasurementConsumer Id in the request, and add the list of MeasurementConsumers the Account owns to the internal proto so the MeasurementConsumer id in the request could be compared to the list.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-MpsYyNCCvwwFyp0ZiKW:-MpxYNvo8mufJVWsIiAJ:bwimzrg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f75129b15a175d8bbe0123212b8eb831a0aed3c0/src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto#L27)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

My current plan is to add the ApiKey to the context or the Account to the context, then compare the MeasurementConsumer id in the ApiKey with the MeasurementConsumer Id in the request, and add the list of MeasurementConsumers the Account owns to the internal proto so the MeasurementConsumer id in the request could be compared to the list.
</blockquote></details>

The general design is that an interceptor resolves the credentials to an authenticated principal, putting information about that principal in the current context. In this case, the API key bytes are the credential and the MeasurementConsumer is the principal.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387#-MpsYyNCCvwwFyp0ZiKW:-Mpxo0OL6NczT4xcaJNa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f75129b15a175d8bbe0123212b8eb831a0aed3c0/src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The general design is that an interceptor resolves the credentials to an authenticated principal, putting information about that principal in the current context. In this case, the API key bytes are the credential and the MeasurementConsumer is the principal.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by chipingyeh — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
