### PR TITLE
Provide default value for unspecified NoiseMechanism for old Measurements

### LINKED ISSUE #956: "Invalid internal NoiseMechanism" in from StreamActiveComputations
It appears that #917 introduced a bug where existing Measurements without a `noise_mechanism` set cannot be read. This in turn forces Heralds into a crash loop.

This doesn't get caught by local integration tests as they start with a fresh DB and write new measurement rows. This was observed in the halo-cmm-dev environment.

Stack trace:

```
java.lang.IllegalStateException: Invalid internal NoiseMechanism.
	at org.wfanet.measurement.kingdom.service.system.v1alpha.ProtoConversionsKt.toSystemNoiseMechanism(ProtoConversions.kt:345)
	at org.wfanet.measurement.kingdom.service.system.v1alpha.ProtoConversionsKt.buildMpcProtocolConfig(ProtoConversions.kt:233)
	at org.wfanet.measurement.kingdom.service.system.v1alpha.ProtoConversionsKt.toSystemComputation(ProtoConversions.kt:199)
	at org.wfanet.measurement.kingdom.service.system.v1alpha.ComputationsService$streamActiveComputations$1$2.emit(ComputationsService.kt:115)
	at org.wfanet.measurement.kingdom.service.system.v1alpha.ComputationsService$streamActiveComputations$1$2.emit(ComputationsService.kt:108)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$2.emit(Errors.kt:158)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
	at io.grpc.kotlin.ClientCalls$rpcImpl$1$1.invokeSuspend(ClientCalls.kt:320)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### PR DESCRIPTION
**Pull request by renjiezh**
Fixes #956

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @renjiezh and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957#-NTQUj5-BQZCVFR-eS0c:-NTQUj50Cxe9sbB_tXkA:b-920pzq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/916871062cb69ecab8fba4cefd5a12bf6d82e14d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L141)):*
> ```Kotlin
> fun InternalNoiseMechanism.toNoiseMechanism(): NoiseMechanism {
>   return when (this) {
>     // Due to proto update, NoiseMechanism was unspecified for old Measurements in database. Use
> ```

Do this check on the logic that reads the field rather than here, since it technically applies only to the specific field and not all instances of this enum. 

Technically the enum is only currently used for this one field, but we should appropriately match the internal API documentation. We could have instead made `0` be `GEOMETRIC` for the internal enum, but it's too late to make a binary-incompatible change to a persisted message type.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 143 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957#-NTQUYRm4op_GZGFZlvo:-NTQUYRm4op_GZGFZlvp:b-kp02y1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/916871062cb69ecab8fba4cefd5a12bf6d82e14d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L143)):*
> ```Kotlin
>     // Due to proto update, NoiseMechanism was unspecified for old Measurements in database. Use
>     // GEOMETRIC as the default value.
>     InternalNoiseMechanism.UNRECOGNIZED,
> ```

Unrecognized is still an error.



_Code quote:_
```Kotlin
    InternalNoiseMechanism.UNRECOGNIZED,
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto` line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957#-NTQUDUV0YIA6Q1tuqX-:-NTQUDUW9zUypHmq6SHu:b-ug6ryj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/916871062cb69ecab8fba4cefd5a12bf6d82e14d/src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto#L58)):*
> ```protobuf
> 
>     // The mechanism to generate noise during computation. Use GEOMETRIC as the
>     // default value if unspecified for old Measurements.
> ```

nit: Follow common phrasing used elsewhere



_Suggestion:_
```protobuf
    // The mechanism to generate noise during computation.
    //
    // If not specified the value is assumed to be `GEOMETRIC`.
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957#-NTQUj5-BQZCVFR-eS0c:-NTQX7vw-_lUvwOUEa2c:b13yrce) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/916871062cb69ecab8fba4cefd5a12bf6d82e14d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do this check on the logic that reads the field rather than here, since it technically applies only to the specific field and not all instances of this enum. 

Technically the enum is only currently used for this one field, but we should appropriately match the internal API documentation. We could have instead made `0` be `GEOMETRIC` for the internal enum, but it's too late to make a binary-incompatible change to a persisted message type.
</blockquote></details>

Yeah, having `GEOMETRIC` as 0 could be a better solution but too late.
Assuming those old Measurements exists forever, whenever calling `InternalNoiseMechanism.toNoiseMechanism()`requires the check for unspecified case. Otherwise it is more error-prone because not everyone aware of this pitfall. (I know this is ugly. But a tradeoff is here.)
How do you feel about that?



_Code quote:_
```Kotlin
error("Noise mechanism not specified")
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 143 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957#-NTQUYRm4op_GZGFZlvo:-NTQZZnD3ZNeZhiKwYnO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/916871062cb69ecab8fba4cefd5a12bf6d82e14d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L143)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Unrecognized is still an error.
</blockquote></details>

Done.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957#-NTQUj5-BQZCVFR-eS0c:-NTQ_wsP42i-LZSDe-KE:bn7xb1t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/916871062cb69ecab8fba4cefd5a12bf6d82e14d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L141)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Yeah, having `GEOMETRIC` as 0 could be a better solution but too late.
Assuming those old Measurements exists forever, whenever calling `InternalNoiseMechanism.toNoiseMechanism()`requires the check for unspecified case. Otherwise it is more error-prone because not everyone aware of this pitfall. (I know this is ugly. But a tradeoff is here.)
How do you feel about that?
</blockquote></details>

Just realize I can write a big NOTE there to remind the caller to check unspecified case. Let me update that.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @renjiezh and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957#-NTQUj5-BQZCVFR-eS0c:-NTQbOW1001DthZ6AA-8:bvru1so) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/916871062cb69ecab8fba4cefd5a12bf6d82e14d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L141)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Just realize I can write a big NOTE there to remind the caller to check unspecified case. Let me update that.
</blockquote></details>

The fact that I'm trying to indicate is that the default value *only* applies to the `ProtocolConfig.LiquidLegionsV2.noise_mechanism` field, *not* to every instance of the `NoiseMechanism` enum. Therefore it is incorrect to apply said default in this method, and it should instead be applied wherever that field is accessed.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957#-NTQUj5-BQZCVFR-eS0c:-NTQfKQkDkoUTHhvedj0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/916871062cb69ecab8fba4cefd5a12bf6d82e14d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The fact that I'm trying to indicate is that the default value *only* applies to the `ProtocolConfig.LiquidLegionsV2.noise_mechanism` field, *not* to every instance of the `NoiseMechanism` enum. Therefore it is incorrect to apply said default in this method, and it should instead be applied wherever that field is accessed.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 141 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957#-NTQkclbDsPr4pBtmuek:-NTQkclbDsPr4pBtmuel:b70bnuh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8a1faaf64d4d2cff259a5a0d2fe71cfe33aef6d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L141)):*
> ```Kotlin
>  * Converts an internal [InternalNoiseMechanism] to a public [NoiseMechanism].
>  *
>  * Note: Due to proto update, NoiseMechanism was unspecified for old Measurements internally. Check
> ```

nit: Drop these notes. The field documentation covers what internal API users need to do.



_Code quote:_
```Kotlin
 * Note: Due to proto update, NoiseMechanism was unspecified for old Measurements internally. Check
 * whether they are NOISE_MECHANISM_UNSPECIFIED before calling the conversion.
```

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @tristanvuong2021)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/957)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
