### PR TITLE
Implement Batch Create and Batch Get Measurements Methods.

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 5 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339)* status: 8 of 10 files reviewed, 7 unresolved discussions (waiting on @tristanvuong2021)

___
*[`build/repositories.bzl` line 45 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjBhI1DNma-VBnrObP:-NjjBhI1DNma-VBnrObQ:b7y7xbr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1079486deb507d7a5f89c84c01ac66b5eca1439/build/repositories.bzl#L45)):*
> ```Starlark
>         repo = "cross-media-measurement-api",
>         sha256 = "0265320861104e84fab444f66dfbf123077e0826fdc5f54dc2950409bd4ec189",
>         #version = "0.52.0",
> ```

nit: Add DO_NOT_SUBMIT comment with TODO format here
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 403 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjC2Ih0VgQneCZCsD3:-NjjC2Ih0VgQneCZCsD4:b-u3sl85) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb1849eaa5e7188ddc264dc0ccde9504cbbd59e7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L403)):*
> ```Kotlin
>       encryptedRequisitionSpec = requisitionDetails.encryptedRequisitionSpec
> 
>       // TODO(world-federation-of-advertisers/cross-media-measurement#1301): Stop setting these
> ```

As indicated in the referenced issue, this TODO cannot be completed until v0.5.0 is released. Please revert this change.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 271 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjEw8B03xJ4WdfBIhb:-NjjEw8B03xJ4WdfBIhc:b3ncxuk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1079486deb507d7a5f89c84c01ac66b5eca1439/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L271)):*
> ```Kotlin
> 
>         if (innerParentKey != parentKey) {
>           failGrpc(Status.PERMISSION_DENIED) {
> ```

Either all values of this field on the child request must be unset or they must all match the value in the batch request. If neither case is true, it should be an  INVALID_ARGUMENT error.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 337 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjIOJl9Derc-pMtg6-:-NjjIOJm1f81NyS53no1:bz3cikq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1079486deb507d7a5f89c84c01ac66b5eca1439/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L337)):*
Same here re: INVALID_ARGUMENT, except that it's an error for it to be unset here.

Btw, why did you go for nested request messages here rather than the standard message definition? From AIP-231 (note the last line):

> If the [standard Get request message](https://google.aip.dev/131#request-message) contains a field besides the resource name that needs to be different between different resources being requested, the batch message **may** alternatively hold a `repeated` field of the [standard Get request message](https://google.aip.dev/131#request-message). This is generally discouraged unless your use case really requires it.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt` line 654 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjJJvW6HJirv54AeT-:-NjjJJvW6HJirv54AeT0:b17g0ds) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb1849eaa5e7188ddc264dc0ccde9504cbbd59e7/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L654)):*
> ```Kotlin
>           nonceHash = dataProviderValue.nonceHash
> 
>           // TODO(world-federation-of-advertisers/cross-media-measurement#1301): Stop setting these
> ```

Same comment here re: addressing the TODO before the requisite condition has been met.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 75 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjCX6Z77FjA077OdYP:-NjjCX6Z77FjA077OdYQ:b8v8raz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1079486deb507d7a5f89c84c01ac66b5eca1439/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L75)):*
> ```Kotlin
> 
>   override suspend fun TransactionScope.runTransaction(): List<Measurement> {
>     val measurements = mutableListOf<Measurement>()
> ```

This can be simplified in one of two ways:
1. Separate out the building of the MC external->internal ID map.
2. Add a `require` on init that all of the requests must have the same MC ID.

Both options are based on the same fact: it's okay to iterate over the requests more than once, as O(2n) = O(n).
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 315 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjEOibDbsRypB7bXDX:-NjjEOibDbsRypB7bXDY:b17g0ds) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb1849eaa5e7188ddc264dc0ccde9504cbbd59e7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L315)):*
> ```Kotlin
>         nonceHash = dataProviderValue.nonceHash
> 
>         // TODO(world-federation-of-advertisers/cross-media-measurement#1301): Stop setting these
> ```

Same comment here re: addressing the TODO before the requisite condition has been met.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 403 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjC2Ih0VgQneCZCsD3:-NjjPK9E5C_uiWaDmsNz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb1849eaa5e7188ddc264dc0ccde9504cbbd59e7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L403)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As indicated in the referenced issue, this TODO cannot be completed until v0.5.0 is released. Please revert this change.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 271 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjEw8B03xJ4WdfBIhb:-NjjSUebD5qbtOQwL58r:bdtcd4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1079486deb507d7a5f89c84c01ac66b5eca1439/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L271)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Either all values of this field on the child request must be unset or they must all match the value in the batch request. If neither case is true, it should be an  INVALID_ARGUMENT error.
</blockquote></details>

I interpret the AIP to mean if the request parent is set, then for each child request, their parent needs to either match or not be set, not all one way or all the other.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 337 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjIOJl9Derc-pMtg6-:-NjmfOT2EFyJB5t9tNe-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1079486deb507d7a5f89c84c01ac66b5eca1439/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L337)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here re: INVALID_ARGUMENT, except that it's an error for it to be unset here.

Btw, why did you go for nested request messages here rather than the standard message definition? From AIP-231 (note the last line):

> If the [standard Get request message](https://google.aip.dev/131#request-message) contains a field besides the resource name that needs to be different between different resources being requested, the batch message **may** alternatively hold a `repeated` field of the [standard Get request message](https://google.aip.dev/131#request-message). This is generally discouraged unless your use case really requires it.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt` line 654 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjJJvW6HJirv54AeT-:-NjjPseK16Q2CDYdk5Nz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb1849eaa5e7188ddc264dc0ccde9504cbbd59e7/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L654)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same comment here re: addressing the TODO before the requisite condition has been met.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 75 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjCX6Z77FjA077OdYP:-NjmfLv85QmiMOJo0ci5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1079486deb507d7a5f89c84c01ac66b5eca1439/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L75)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This can be simplified in one of two ways:
1. Separate out the building of the MC external->internal ID map.
2. Add a `require` on init that all of the requests must have the same MC ID.

Both options are based on the same fact: it's okay to iterate over the requests more than once, as O(2n) = O(n).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 315 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjEOibDbsRypB7bXDX:-NjjPL-A96FbQ5yLUs4O:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb1849eaa5e7188ddc264dc0ccde9504cbbd59e7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L315)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same comment here re: addressing the TODO before the requisite condition has been met.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`build/repositories.bzl` line 45 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjBhI1DNma-VBnrObP:-NjnEnAS93lB5bErOKxl:bpljo7f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1079486deb507d7a5f89c84c01ac66b5eca1439/build/repositories.bzl#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Add DO_NOT_SUBMIT comment with TODO format here
</blockquote></details>

TODO format meant doing it like a TODO but with DO_NOT_SUBMIT. e.g. `# DO_NOT_SUBMIT(world-federation-of-advertisers/cross-media-measurement-api#190): Use version`
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 271 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjEw8B03xJ4WdfBIhb:-NjnFKf4AIauK7Mcj_xa:bnt5i1q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1079486deb507d7a5f89c84c01ac66b5eca1439/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L271)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I interpret the AIP to mean if the request parent is set, then for each child request, their parent needs to either match or not be set, not all one way or all the other.
</blockquote></details>

That's not quite it. It's that there is a `parent` field in the batch request, which is required if you only support batching across one parent. Then for the children they must either all have no parent set or all have the value of parent matching the batch request.

1.
    > A `parent` field **should** be included, unless the resource being created is a top-level resource.

2.
    > This field **should** be required if only 1 parent per request is allowed.

3. 
    > If a caller sets this field, and the `parent` field of any child request message does not match, the request **must** fail. The `parent` field of child request messages can be omitted if the `parent` field in this request is set.

Due to (2), the "if a caller sets this field" part of (3) is always true.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 334 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjnHNE62_uCA7mZuk5T:-NjnHNE62_uCA7mZuk5U:b-3jkdip) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5297c55c0f348767cc0533f2f0d1d652d4248f50/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L334)):*
> ```Kotlin
>       val key = grpcRequireNotNull(MeasurementKey.fromName(name)) { "name is invalid." }
> 
>       if (authenticatedMeasurementConsumerKey.measurementConsumerId != key.measurementConsumerId) {
> ```

MeasurementKey implements ChildResourceKey, so you can compare the MeasurementConsumerKey objects.



_Suggestion:_
```Kotlin
parentKey != key.parentKey
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 271 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjEw8B03xJ4WdfBIhb:-NjnKXlC3USH0Mm7Q_ZU:b-3jrggd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1079486deb507d7a5f89c84c01ac66b5eca1439/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L271)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's not quite it. It's that there is a `parent` field in the batch request, which is required if you only support batching across one parent. Then for the children they must either all have no parent set or all have the value of parent matching the batch request.

1.
    > A `parent` field **should** be included, unless the resource being created is a top-level resource.

2.
    > This field **should** be required if only 1 parent per request is allowed.

3. 
    > If a caller sets this field, and the `parent` field of any child request message does not match, the request **must** fail. The `parent` field of child request messages can be omitted if the `parent` field in this request is set.

Due to (2), the "if a caller sets this field" part of (3) is always true.
</blockquote></details>

But then the followup to that sentence says it can be omitted. I am not seeing it strictly saying every request must have it omitted or must have it set. Instead of relying on people interpreting it, I could just pick your interpretation and add a comment to the request message in the API stating it.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 334 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjnHNE62_uCA7mZuk5T:-NjnJUff2T8nXAvgWD3K:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5297c55c0f348767cc0533f2f0d1d652d4248f50/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L334)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

MeasurementKey implements ChildResourceKey, so you can compare the MeasurementConsumerKey objects.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 10 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 271 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NjjEw8B03xJ4WdfBIhb:-NjnTV0-8quHOy7TRVJn:biq5f26) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1079486deb507d7a5f89c84c01ac66b5eca1439/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L271)):*
Sorry, I thought the operative part of your comment was "if the [batch] request parent is set", which will always be true in our case. You were talking about whether the `parent` field value all child requests must be the same, which the AIP indeed has some ambiguity about:

>  If a caller sets this field, and the `parent` field of any child request message does not match, the request **must** fail.

I had read the "does not match" part as applying to the all the child request messages matching, where it appears to instead be talking about the child request matching the batch request. It doesn't seem like an unreasonable restriction to add, but I'll leave it to you.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 7 of 10 files at r4, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 80 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339#-NkG2jHM0ICm5cRJ_80t:-NkG2jHN5lQ4vBkOintK:b7sma4c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e79fe342a3f26ba9a80f685d8cd4cfa9435e6bd7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L80)):*
> ```Kotlin
>       )
> 
>     val measurements = mutableListOf<Measurement>()
> ```

nit: I think this can be refactored using an immutable list. they map 1:1

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 5 of 10 files at r4, 1 of 2 files at r6, 2 of 3 files at r7, 1 of 1 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1339)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
