### PR TITLE
Add CLI command to replace DataProviders duchy list

### PR DESCRIPTION
**Pull request by jojijac0b**
Create CLI command to replace DataProviders duchy list. The two required arguments are 1) data-provider-id and 2) required-duchies.

https://rally1.rallydev.com/#/604612930531d/iterationstatus?detail=%2Ftask%2F697342537849

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 343 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NTz3FkL6XZLK2nbdUso:-NTz3FkL6XZLK2nbdUsp:b-c3jjor) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db84da34f9df75a76c03af80ccff175097136644/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L343)):*
> ```Kotlin
>     require(dataProviderId.toLongOrNull() != null)
>     val request =
>       ReplaceDataProviderRequiredDuchiesRequest()
> ```

you can do this with kotlin dsls
```
replaceDataProviderRequiredDuchiesRequest {
   requiredExternalDuchyIds += requiredDuchies
   externalDataProviderId = dataProviderId.toLong()
}
```

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 343 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NTz3FkL6XZLK2nbdUso:-NU0_ts6Cxq0Zkigt5nl:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db84da34f9df75a76c03af80ccff175097136644/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L343)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you can do this with kotlin dsls
```
replaceDataProviderRequiredDuchiesRequest {
   requiredExternalDuchyIds += requiredDuchies
   externalDataProviderId = dataProviderId.toLong()
}
```

</blockquote></details>

+1

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 318 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NU2TiFf3CgQGgHvd6N2:-NU2TiFg6B_f47-PWIcT:bsiaxru) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f97528b321d410fbbce00f842f15f8cf00329caa/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L318)):*
> ```Kotlin
> }
> 
> @Command(
> ```

This should go in the MeasurementSystem CLI tool, not this one.

**Review by Marco-Premier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 318 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NU2TiFf3CgQGgHvd6N2:-NU2wYbA-nba2e3bspsp:b-44vxdx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f97528b321d410fbbce00f842f15f8cf00329caa/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L318)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should go in the MeasurementSystem CLI tool, not this one.
</blockquote></details>

Are the 2 CLI tool used by different actors @SanjayVas ?
Trying to understand why ```replace_data_provider_duchies``` command should be part of a different CLI tool compared to ```data-provider``` command.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 318 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NU2TiFf3CgQGgHvd6N2:-NU3JPpz0EVuz5p4Nfnf:b-f6vfv0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f97528b321d410fbbce00f842f15f8cf00329caa/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L318)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Are the 2 CLI tool used by different actors @SanjayVas ?
Trying to understand why ```replace_data_provider_duchies``` command should be part of a different CLI tool compared to ```data-provider``` command.
</blockquote></details>

Yes. This CLI tool is for Kingdom operators and calls the internal API. Some method such as CreateDataProvider are intentionally not exposed in the public API, as these operations are not intended to be self-service.

The MeasurementSystem CLI tool is for the public API.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 318 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NU2TiFf3CgQGgHvd6N2:-NU5wR0E9Hzs0rdKrIEd:bxqu92b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f97528b321d410fbbce00f842f15f8cf00329caa/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L318)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes. This CLI tool is for Kingdom operators and calls the internal API. Some method such as CreateDataProvider are intentionally not exposed in the public API, as these operations are not intended to be self-service.

The MeasurementSystem CLI tool is for the public API.
</blockquote></details>

Oh I see now. thanks for sharing this.
@jojijac0b we can move this into Measurement System then

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 343 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NTz3FkL6XZLK2nbdUso:-NU2H2SJA_0ZcdHprBf1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db84da34f9df75a76c03af80ccff175097136644/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L343)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 318 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NU2TiFf3CgQGgHvd6N2:-NUOBCDV-M4lgk0xELxa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f97528b321d410fbbce00f842f15f8cf00329caa/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L318)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Oh I see now. thanks for sharing this.
@jojijac0b we can move this into Measurement System then
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1015 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NUTQqxx06Zk8QX2F73-:-NUTQqxx06Zk8QX2F730:bnkqxva) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7799122b8cb676f3fde1dfb6680098458b579e8e/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1015)):*
> ```Kotlin
> }
> 
> @Command(
> ```

This CLI is organized into subcommands by resource. Add this as a `replace-required-duchies` subcommand of a `data-providers` command.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1063 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NUbckIoEo1hQ285AfyX:-NUbckIoEo1hQ285AfyY:b-pna39u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bccb4d0744ff496c2ba14dda4a368d31a69a02d6/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1063)):*
> ```Kotlin
>   }
> 
>   @Command
> ```

was this meant to be added?

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1063 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NUbckIoEo1hQ285AfyX:-NUgQnBm9q-agphITRyl:bk34hox) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bccb4d0744ff496c2ba14dda4a368d31a69a02d6/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1063)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

was this meant to be added?
</blockquote></details>

it was a mistake. must remove

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1063 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NUbckIoEo1hQ285AfyX:-NUgRFom1AizF7krrMju:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bccb4d0744ff496c2ba14dda4a368d31a69a02d6/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1063)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

it was a mistake. must remove
</blockquote></details>

Done.

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1015 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NUTQqxx06Zk8QX2F73-:-NUgRMhj9T0I-eT0y-gu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7799122b8cb676f3fde1dfb6680098458b579e8e/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1015)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This CLI is organized into subcommands by resource. Add this as a `replace-required-duchies` subcommand of a `data-providers` command.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NUgx0fY5Pu8BgPS5MEN:-NUgx0fY5Pu8BgPS5MEO:b-fy5san) (no related file):*
Update the unit test.

___
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1030 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NUgwoVC3BncO1N-tOEK:-NUgwoVC3BncO1N-tOEL:b-6qxw89) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45e19d12036aed208e20cdd5d4459da7ff5e73a3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1030)):*
> ```Kotlin
> 
>   @Command(
>     name = "replace-data-provider-duchies",
> ```

The DataProvider subject is implied



_Suggestion:_
```Kotlin
replace-required-duchies
```

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b)

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NUgx0fY5Pu8BgPS5MEN:-NVFQVr565qIpmas_Aro:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Update the unit test.
</blockquote></details>

Done.

___
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1030 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970#-NUgwoVC3BncO1N-tOEK:-NVFQcJYCu6EiYfaz8Bg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/45e19d12036aed208e20cdd5d4459da7ff5e73a3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1030)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The DataProvider subject is implied
</blockquote></details>

Done.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/970)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Pull request merged**
