### PR TITLE
Write GKE deployment guide for Reporting server.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/651)

### CODE REVIEW

**Comment by SanjayVas** [comment]
Depends on #649.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/651)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`docs/gke/reporting-server-deployment.md` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/651#-N8a3ot79e0XozCp8UZA:-N8a3ot79e0XozCp8UZB:bmytzli) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b7de9d87b6554da9802f9b52341db787ae1e056/docs/gke/reporting-server-deployment.md#L48)):*
> ```Markdown
> ## Create the database
> 
> The Reporting server expects its own database within your PostgeSQL instance.
> ```

nit: PostgeSQL

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/651)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

___
*[`docs/gke/reporting-server-deployment.md` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/651#-N8a3ot79e0XozCp8UZA:-N8a6H8f70meXNa0ypWy:b-mig7fh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3548fc5dc49bf36fb8dabf8c370801b09c69e90e/docs/gke/reporting-server-deployment.md#L48)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

nit: PostgeSQL
</blockquote></details>

Done (and actually used PostgreSQL, as your comment had the same typo :P )

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/651)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Comment by TNATALI** [comment]
Awesome Work Team. 
M3 is now complete and available.

**Pull request merged**
