### PR TITLE
Implement PrincipalLookup that reads from a textproto file

### PR DESCRIPTION
**Pull request by efoxepstein**
https://rally1.rallydev.com/#/?detail=/userstory/613542239129&fdp=true

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/k8s/kingdom.cue, line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-MnYqiys1q9p9S-YPKQZ:-MnYqiys1q9p9S-YPKQ_:b8u1l1h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2ec82091ceab9b993a601df02f986914c0b3d13/src/main/k8s/kingdom.cue#L122)):*
> ```CUE
> 				_internal_api_target_flag,
> 				_internal_api_cert_host_flag,
> 				"--authority-key-identifier-to-principal-map-file=/var/run/secrets/files/authority_key_identifier_to_principal_map.textproto",
> ```

@wangyaopw: is there anything else I need to do here in the Cue for this?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/TextprotoFilePrincipalLookup.kt, line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-Mna1lkv1nBH6g8HrunH:-Mna1lkv1nBH6g8HrunI:b6t303p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1879732a470b782b69c3a7970931384e10bce11b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/TextprotoFilePrincipalLookup.kt#L31)):*
> ```Kotlin
>  */
> class TextprotoFilePrincipalLookup(textprotoFile: File) : PrincipalLookup {
>   private val map: Map<ByteString, Principal<*>> by lazy {
> ```

I should make this eager so we encounter errors early, rather than on first gRPC request.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt, line 48 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-MnaWJ2j1C1V4UQ9P5PQ:-MnaWJ2j1C1V4UQ9P5PR:btuk2rt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20756f89db5dded8ffb87fae21f25299c9bbac49/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt#L48)):*
> ```
> (String) -> Principal<*>?
> ```
Consider adding a type alias for this

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderKey.kt, line 19 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-Mnarhv69kRN4Ri1Xo3n:-Mnarhv69kRN4Ri1Xo3o:bryewxc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/030daa4fa10f9e944351f8dab16f59bed8be057c/src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderKey.kt#L19)):*
> ```Kotlin
> import org.wfanet.measurement.common.ResourceNameParser
> 
> private val parser = ResourceNameParser("${DataProviderKey.COLLECTION_NAME}/{data_provider}")
> ```

nit: maybe move the parser into the companion object so you don't need to qualify the COLLECTION_NAME const

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/k8s/kingdom.cue, line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-MnYqiys1q9p9S-YPKQZ:-Mnb09eAAZQIOw9uFJyN:b-tm6lc7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2ec82091ceab9b993a601df02f986914c0b3d13/src/main/k8s/kingdom.cue#L122)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@wangyaopw: is there anything else I need to do here in the Cue for this?
</blockquote></details>

You need to create a textproto, and put it inside `src/main/k8s/testing/secretfiles`, and add the file name to the end of `src/main/k8s/testing/secretfiles/kustomization.yaml`.
___
*[src/main/proto/wfa/measurement/api/v2alpha/authority_key_to_principal_map.proto, line 29 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-Mnb-iELCZ_9a3IMUnLO:-Mnb-iELCZ_9a3IMUnLP:b-658zpq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/030daa4fa10f9e944351f8dab16f59bed8be057c/src/main/proto/wfa/measurement/api/v2alpha/authority_key_to_principal_map.proto#L29)):*
> ```protobuf
>     string principal_resource_name = 2;
>   }
> }
> ```

Something weird here. I see two rectangles.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/k8s/kingdom.cue, line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-MnYqiys1q9p9S-YPKQZ:-Mnb1TMd-0iDDnI6eVWz:bmszwes) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2ec82091ceab9b993a601df02f986914c0b3d13/src/main/k8s/kingdom.cue#L122)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

You need to create a textproto, and put it inside `src/main/k8s/testing/secretfiles`, and add the file name to the end of `src/main/k8s/testing/secretfiles/kustomization.yaml`.
</blockquote></details>

Also maybe move this line above to around line 35, so all file names are defined together.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @wangyaopw)

___
*[src/main/k8s/kingdom.cue, line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-MnYqiys1q9p9S-YPKQZ:-Mnb4_Yx5x3BfpvAEQYL:b-oq3912) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2ec82091ceab9b993a601df02f986914c0b3d13/src/main/k8s/kingdom.cue#L122)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Also maybe move this line above to around line 35, so all file names are defined together.
</blockquote></details>

Done, PTAL
___
*[src/main/proto/wfa/measurement/api/v2alpha/authority_key_to_principal_map.proto, line 29 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-Mnb-iELCZ_9a3IMUnLO:-Mnb3CS5EjCSSTZ6rxhs:bk5e2bu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/030daa4fa10f9e944351f8dab16f59bed8be057c/src/main/proto/wfa/measurement/api/v2alpha/authority_key_to_principal_map.proto#L29)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Something weird here. I see two rectangles.
</blockquote></details>

It's probably trying but failing to load these icons:

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)* status: 8 of 14 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto, line 6 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-Mnb5Pfz9fSocNbCSNM6:-Mnb5Pfz9fSocNbCSNM7:b-c9doq3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb6947b87fa67aae167320e5f87f15f4b2a4641/src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto#L6)):*
> ```
> dataProviders/AAAAAAAAAHs
> ```

Should we use the actual names of the resources created in the database? or it doesn't matter here?

If we need actual resource names, then we need to 
1. deploy the kingdom.
2.  run the job to create these two dataprovider and modelProvider
3.  update the config with real resource name
4.  re-deployment the kingdom.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)* status: 8 of 14 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto, line 6 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-Mnb5Pfz9fSocNbCSNM6:-Mnb75R78WZcvOg2IcLf:bcighbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb6947b87fa67aae167320e5f87f15f4b2a4641/src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto#L6)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> dataProviders/AAAAAAAAAHs
> ```

Should we use the actual names of the resources created in the database? or it doesn't matter here?

If we need actual resource names, then we need to 
1. deploy the kingdom.
2.  run the job to create these two dataprovider and modelProvider
3.  update the config with real resource name
4.  re-deployment the kingdom.
</blockquote></details>

Eventually, all EDPs and MPs that want to talk to this deployment will need an entry in here. But for now, it only matters for Panel Match services, I think.

How do we run the job and get real resource names? Is this something that's easy for you to do?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)* status: 8 of 14 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto, line 10 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-Mnb8KKp1woNYk8tgduA:-Mnb8KKp1woNYk8tgduB:b-jtqp2e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb6947b87fa67aae167320e5f87f15f4b2a4641/src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto#L10)):*
> ```
> authority_key_identifier
> ```
The type of `authority_key_identifier` is bytes. I guess we shouldn't put "test-mp-akid" here.

Where do these value come from? can these be arbitrary values or some values associated with the actual created resources?


FYI I am using the format`root_certificate_skid: "\xC9\x81\xE5\xBC\x00\x0D\x2F\x1C\x9C\x4E\xC9\xE2\x07\x8D\x7A\xA5\x54\x7B\x36\x74"` in the duchy_rpc_config.textproto, which is actual skid in the test certificate.

**Review by stevenwarejones — APPROVED** [review]
I'm happy once Yao is happy.

> Reviewed 2 of 8 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 4 of 6 files at r4, 4 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-:-MnbFZXfB1_GWSfTZRRl:b-nynrdq)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @wangyaopw)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto, line 6 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-Mnb5Pfz9fSocNbCSNM6:-MnbUD7lCVVa-7OvQmK_:b-bb5qyb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb6947b87fa67aae167320e5f87f15f4b2a4641/src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto#L6)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Yep. I'll add another modelProvider in current resourceSetupJob. We already have 6 dataproviders you can use.

Just put "TBD" here for the names, I'll update later.
</blockquote></details>

They need to parse as valid ids, so I just put a TODO in a comment.
___
*[src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto, line 10 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-Mnb8KKp1woNYk8tgduA:-MnbUNe03k31pi2u9mXR:buheuer) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb6947b87fa67aae167320e5f87f15f4b2a4641/src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto#L10)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> authority_key_identifier
> ```
The type of `authority_key_identifier` is bytes. I guess we shouldn't put "test-mp-akid" here.

Where do these value come from? can these be arbitrary values or some values associated with the actual created resources?


FYI I am using the format`root_certificate_skid: "\xC9\x81\xE5\xBC\x00\x0D\x2F\x1C\x9C\x4E\xC9\xE2\x07\x8D\x7A\xA5\x54\x7B\x36\x74"` in the duchy_rpc_config.textproto, which is actual skid in the test certificate.
</blockquote></details>

These come from the cert used in the mTLS gRPC connection. They need to be from the real cert used by that party. They need to be different per-party. Can we have separate SKIDs per party?

For now I put in TODOs for you (or I can do it if you tell me how).

There can be multiple entries per party. Basically, `authority_key_identifier`s must be unique but `principal_resource_names` need not be.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto, line 10 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-Mnb8KKp1woNYk8tgduA:-MnbXLtI1G-NabndU4Te:bf5sxke) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb6947b87fa67aae167320e5f87f15f4b2a4641/src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto#L10)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

These come from the cert used in the mTLS gRPC connection. They need to be from the real cert used by that party. They need to be different per-party. Can we have separate SKIDs per party?

For now I put in TODOs for you (or I can do it if you tell me how).

There can be multiple entries per party. Basically, `authority_key_identifier`s must be unique but `principal_resource_names` need not be.
</blockquote></details>

I'll take care of this later.

**Review by wangyaopw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 8 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 3 of 6 files at r4, 5 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346#-:-MnbXTUn-6zf4Cw_3xla:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
