### PR TITLE
Add FrequencySpec and Window to MetricCalculationSpec and Update Time Spec of Report

### PR DESCRIPTION
**Pull request by kungfucraig**
…e time specification for Report.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nl_Txgt3Cno7WaV4_zx:-Nl_Txgt3Cno7WaV4_zy:b3p6r58) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/571a52294a646492d384cbc886d0f83ac1615f4a/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L80)):*
> ```proto
> 
>   // Describes the frequencies for which results are generated.
>   message FrequencySpec {
> ```

I don't think this handles something like "On 2 AM of the 20th day of the month" because that concept is time-zone dependent. That is to say that the only way you can define the start anchor here is in UTC, meaning all of your reports might shift an hour if you're anchoring in a time zone that observes DST/BST.

We handle this in ReportSchedule by using a google.type.DateTime for the start, which has TZ info. This means not using google.type.Interval for the overall interval, as that uses UTC timestamps.

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nl_Txgt3Cno7WaV4_zx:-NliMTJvDiqiKUDRDZ_L:b-y20d7n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/571a52294a646492d384cbc886d0f83ac1615f4a/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L80)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this handles something like "On 2 AM of the 20th day of the month" because that concept is time-zone dependent. That is to say that the only way you can define the start anchor here is in UTC, meaning all of your reports might shift an hour if you're anchoring in a time zone that observes DST/BST.

We handle this in ReportSchedule by using a google.type.DateTime for the start, which has TZ info. This means not using google.type.Interval for the overall interval, as that uses UTC timestamps.
</blockquote></details>

I updated the interval in the Report to be more like schedule and be defined in terms of a Datetime. I think this clears up the issue you raised.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nlj4Ykf-QaYRxbzegtW:-Nlj4Ykf-QaYRxbzegtX:bek5jxx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/632a11669d3b6679ea69bd34d4b73ee452d72cf8/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L80)):*
> ```proto
> 
>   // Describes the frequencies at which results are generated.
>   message FrequencySpec {
> ```

nit: while this is a completely accurate use of this term, it might be best to find another one to avoid confusion with Frequency metrics.



_Code quote:_
```proto
Frequency
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nlj2_k7E6wGzbaEmbpG:-Nlj2_k7E6wGzbaEmbpH:bn8wys0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/632a11669d3b6679ea69bd34d4b73ee452d72cf8/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L99)):*
> ```proto
>     ];
> 
>     // The end date of the report. The time is considered to be the same as
> ```

Is this inclusive or exclusive? Generally we use [start, end) ranges, but it's fine to have it be inclusive as long as it's documented.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 101 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nlj2U7cCz3nPphFI8Ue:-Nlj2U7cCz3nPphFI8Uf:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/632a11669d3b6679ea69bd34d4b73ee452d72cf8/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L101)):*
> ```proto
>     // The end date of the report. The time is considered to be the same as
>     // that specified in the report start.
>     google.type.Date report_end = 1 [
> ```





_Suggestion:_
```proto
2
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nlj2Oba3E2Z0ikyQUWF:-Nlj2Obb-fYNCAAuQJSu:bkcwoc8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/632a11669d3b6679ea69bd34d4b73ee452d72cf8/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L113)):*
> ```proto
>     // this field is set and any MetricCalculationSpec specifies a FrequencySpec
>     // an error will be reported.
>     TimeIntervals time_intervals = 10;
> ```

nit: why did this get a new tag number?



_Code quote:_
```proto
10
```

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nlj4Ykf-QaYRxbzegtW:-NljL6W37oUtN29f5YBL:bv3wax0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/632a11669d3b6679ea69bd34d4b73ee452d72cf8/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L80)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: while this is a completely accurate use of this term, it might be best to find another one to avoid confusion with Frequency metrics.
</blockquote></details>

I hear you. Maybe Recurrence? 
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nlj2_k7E6wGzbaEmbpG:-NljMwIJ1w6gS8gVI4R7:b-gnt7k6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/632a11669d3b6679ea69bd34d4b73ee452d72cf8/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this inclusive or exclusive? Generally we use [start, end) ranges, but it's fine to have it be inclusive as long as it's documented.
</blockquote></details>

It's part of the message documentation, but added it here too.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 101 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nlj2U7cCz3nPphFI8Ue:-NljMzT5B7tNDyVPqaHx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/632a11669d3b6679ea69bd34d4b73ee452d72cf8/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L101)):*
> ```proto
>     // The end date of the report. The time is considered to be the same as
>     // that specified in the report start.
>     google.type.Date report_end = 1 [
> ```

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nlj4Ykf-QaYRxbzegtW:-NlyTS_MA88Ag93l6AkN:b-k1toiw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/632a11669d3b6679ea69bd34d4b73ee452d72cf8/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L80)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I hear you. Maybe Recurrence?
</blockquote></details>

Better than anything I can think of.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nlj2_k7E6wGzbaEmbpG:-NlyTbX81T3S5gyT-OZv:b-gvkadu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/632a11669d3b6679ea69bd34d4b73ee452d72cf8/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L99)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It's part of the message documentation, but added it here too.
</blockquote></details>

Sorry, missed that.

**Review by riemanli — COMMENTED** [review]
The description seems not completed 

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-:-Nlz9U6o-fI6UBsaAjue:b7plz7l)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 86 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nlz8gYO6RtsVTcx6BdC:-Nlz8gYO6RtsVTcx6BdD:bb7phvt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f1cb85926c7b8759d7a779fae19af46b4c8040/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L86)):*
> ```proto
> 
>     // When Weekly is selected the first Metrics are calculated on the first
>     // occurence of the speciied day of week on or after the report_start field
> ```

typo



_Code quote:_
```proto
speciied
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 98 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nlz8yz46S_oA_y-IvIA:-Nlz8yz5C5_5GbEQdDKp:bb7phvt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f1cb85926c7b8759d7a779fae19af46b4c8040/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L98)):*
> ```proto
>     }
> 
>     // When Monthly is slected the first Metrics are calulated on the first
> ```

typo



_Code quote:_
```proto
slected
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 144 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-NlzDu_z-HwS7nTEV5ut:-NlzDua-8e1tJE9BbYas:bfflqrk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f1cb85926c7b8759d7a779fae19af46b4c8040/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L144)):*
> ```proto
>     reserved 3;
> 
>     // TODO: Add a reference to the MetricCalculationSpec?
> ```

`ResultAttribute` should contain necessary info about the result. I can see this might be useful for debugging purpose.



_Code quote:_
```proto
// TODO: Add a reference to the MetricCalculationSpec?
```

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 91 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-Nn9y2bUAXw-92mvx0uK:-Nn9y2bUAXw-92mvx0uL:b-4ux4qf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f1cb85926c7b8759d7a779fae19af46b4c8040/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L91)):*
> ```proto
>     // then the first Metrics are calcualted for the day specified in
>     // start_time. But if day_of_wek is Monday and the start time is a Tuesday
>     // then the first Metrics are calcualted for the first Monday after the
> ```

typo: calcualted

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361)* status: all files reviewed, 5 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 108 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1361#-NnKVDa-Afpq21GUoq5T:-NnKVDa-Afpq21GUoq5U:bb26j05) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f1cb85926c7b8759d7a779fae19af46b4c8040/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L108)):*
> ```proto
> 
>     // The frequency at which the time interval is divided.
>     oneof frequency {
> ```

Should we add a frequency that indicates we use the entire Reporting Window?

**Comment by kungfucraig** [comment]
Obsolete

**Pull request closed without merging**
