### PR TITLE
Clean up Kotlin style issues.

### PR DESCRIPTION
**Pull request by efoxepstein**
- Shadowed implicit parameters
- Unused imports, variables, classes
- Unnecessary modifiers (public/suspend)
- Import correct Bazel library for kt_jvm_*
- And other misc fixes

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 46 of 46 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 372 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287#-MkJ77vlDK-tannYUFTj:-MkJ77vlDK-tannYUFTk:bsmz9er) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22484d710de13d6b08bee4b4a97a16fbfe0877c0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L372)):*
> ```Kotlin
>     return dataClients.computationsClient.updateComputationDetails(
>         UpdateComputationDetailsRequest.newBuilder()
>           .apply {
> ```

Make same change in `completeExecutionPhaseTwoAtAggregator`?
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 374 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287#-MkJ6wVX6ytTt2_bv2GZ:-MkJ6wVX6ytTt2_bv2G_:b-7d5osh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22484d710de13d6b08bee4b4a97a16fbfe0877c0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L374)):*
> ```
> this.
> ```
nit: unnecessary qualification
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287#-MkJ7FMaBqxhAhxZ01Qg:-MkJ7FMaBqxhAhxZ01Qh:b-wst6c6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22484d710de13d6b08bee4b4a97a16fbfe0877c0/src/main/kotlin/org/wfanet/measurement/kingdom/db/Filters.kt#L84)):*
> ```
> ids
> ```
nit: IDs
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287#-MkJ7eXk-wiqeBcnb3tu:-MkJ7eXl-Ja4vUMsQFgo:bdtwxqo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22484d710de13d6b08bee4b4a97a16fbfe0877c0/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L17)):*
> ```Kotlin
> package org.wfanet.measurement.kingdom.service.api.v2alpha
> 
> import kotlin.Long
> ```

This doesn't look right. I don't think we ever have explicit imports for the `kotlin` package.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 231 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287#-MkJ88blAYBNhM2swVTy:-MkJ88blAYBNhM2swVTz:boh6el4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22484d710de13d6b08bee4b4a97a16fbfe0877c0/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L231)):*
> ```
> v2Alpha
> ```
`v2alpha` was correct here. See src/main/kotlin/org/wfanet/measurement/api/Version.kt
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/utils/DuchyOrderTest.kt, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287#-MkJ8wgw2uuaiojuXE9S:-MkJ8wgw2uuaiojuXE9T:bxb0s35) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22484d710de13d6b08bee4b4a97a16fbfe0877c0/src/test/kotlin/org/wfanet/measurement/duchy/daemon/utils/DuchyOrderTest.kt#L18)):*
> ```
> import org.junit.Assert.assertEquals
> ```
Doesn't need to be part of this cleanup PR, but we should use Truth for this. There's never any reason to use assertEquals.

**Review by wangyaopw — APPROVED** [review]
:lgtm:

> Reviewed 46 of 46 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287#-:-MkJAbMs9kOo9F7WkbaO:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287)* status: 41 of 46 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 372 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287#-MkJ77vlDK-tannYUFTj:-MkJEMLaE4A_FY_nUlll:b-26adql) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22484d710de13d6b08bee4b4a97a16fbfe0877c0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L372)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Make same change in `completeExecutionPhaseTwoAtAggregator`?
</blockquote></details>

There wasn't an issue with shadowed `it` there -- I definitely don't want to clean up all proto usage (and if we clean this up any more, we might as well switch to Kotlin builders)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287#-MkJ7eXk-wiqeBcnb3tu:-MkJEsby2-rc1thuCtsH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22484d710de13d6b08bee4b4a97a16fbfe0877c0/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't look right. I don't think we ever have explicit imports for the `kotlin` package.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 231 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287#-MkJ88blAYBNhM2swVTy:-MkJEzDxDwoInfNVMzYa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22484d710de13d6b08bee4b4a97a16fbfe0877c0/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L231)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> v2Alpha
> ```
`v2alpha` was correct here. See src/main/kotlin/org/wfanet/measurement/api/Version.kt
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/utils/DuchyOrderTest.kt, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287#-MkJ8wgw2uuaiojuXE9S:-MkJF9NP9jclfRe2c8DU:bkd5ega) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22484d710de13d6b08bee4b4a97a16fbfe0877c0/src/test/kotlin/org/wfanet/measurement/duchy/daemon/utils/DuchyOrderTest.kt#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> import org.junit.Assert.assertEquals
> ```
Doesn't need to be part of this cleanup PR, but we should use Truth for this. There's never any reason to use assertEquals.
</blockquote></details>

Added a TODO

**Review by duliomatos1 — APPROVED** [review]
lgtm

> Reviewed 41 of 46 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287#-:-MkJUxVpBQ5Cpmd76pRQ:bb7k0qh)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/287)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
