### PR TITLE
Deploy CMMS

### PR DESCRIPTION
**Pull request by wfa-mdharmalingam**
Added files to create infra for QA deployment.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: all files reviewed, 3 unresolved discussions (waiting on @wfa-mdharmalingam and @wfa-siyengar)

___
*[`.github/workflows/deploy-infra.yml` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRiUla24YAWkLE8BWVI:-NRiUla24YAWkLE8BWVJ:b-oa6dcy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c0e083e00bfddcd62a302223f5e12c2279d1a96/.github/workflows/deploy-infra.yml#L15)):*
> ```YAML
> # limitations under the License.
> 
> name: 'Create Infra'
> ```

This isn't just creating the infra, but rather deploying the entire CMMS.



_Code quote:_
```YAML
'Create Infra'
```
___
*[`.github/workflows/deploy-infra.yml` line 18 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRiUMZd46959z0GCcmj:-NRiUMZd46959z0GCcmk:bgqfa59) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c0e083e00bfddcd62a302223f5e12c2279d1a96/.github/workflows/deploy-infra.yml#L18)):*
> ```YAML
> 
> on:
>   # TODO(wfa-siyengar):  Add workflow_dispatch
> ```

Do you mean adding release or workflow_run? This already has `workflow_dispatch`.



_Code quote:_
```YAML
workflow_dispatch
```
___
*[`.github/workflows/deploy-infra.yml` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRiUg897w8kBGSc2saw:-NRiUg897w8kBGSc2sax:b-qhd4n4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c0e083e00bfddcd62a302223f5e12c2279d1a96/.github/workflows/deploy-infra.yml#L36)):*
> ```YAML
>         required: true
>         type: boolean
>       deploy_duchy-3:
> ```

We don't need these inputs for the top-level workflow. We'll do all these things unconditionally. If we want to just do some but not all, we can just run the individual workflows directly.



_Code quote:_
```YAML
      deploy_kingdom:
        required: true
        type: boolean
      deploy_duchy-1:
        required: true
        type: boolean
      deploy_duchy-2:
        required: true
        type: boolean
      deploy_duchy-3:
        required: true
        type: boolean
      image-tag:
        required: true
        type: boolean
      build-push-images:
        required: true
        type: boolean
```

**Review by wfa-siyengar — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`.github/workflows/deploy-infra.yml` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRiUla24YAWkLE8BWVI:-NRkf2i-43mOPbg2z80e:bogxpif) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c0e083e00bfddcd62a302223f5e12c2279d1a96/.github/workflows/deploy-infra.yml#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This isn't just creating the infra, but rather deploying the entire CMMS.
</blockquote></details>

Request you to suggest a name to be given. For now i have given it as "Deploy CMM"
___
*[`.github/workflows/deploy-infra.yml` line 18 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRiUMZd46959z0GCcmj:-NRkfKV1-kBDUmleV72A:b-d4l14x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c0e083e00bfddcd62a302223f5e12c2279d1a96/.github/workflows/deploy-infra.yml#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do you mean adding release or workflow_run? This already has `workflow_dispatch`.
</blockquote></details>

I would like to see the whole workflow running on dispatch before we can trigger it on release. I will add a TODO for trigger on release.
___
*[`.github/workflows/deploy-infra.yml` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRiUg897w8kBGSc2saw:-NRkfgm5B0jgqFo5RSnp:bfi6954) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c0e083e00bfddcd62a302223f5e12c2279d1a96/.github/workflows/deploy-infra.yml#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We don't need these inputs for the top-level workflow. We'll do all these things unconditionally. If we want to just do some but not all, we can just run the individual workflows directly.
</blockquote></details>

Request you to synch with Craig on this and provide us what exactly needs to be done. 
As Craig was looking at orchestrator which conditionally triggers.

Nevertheless, I have added a TODO in the code to remove these conditional variables after the testing is done.

**Review by wfa-siyengar — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

**Review by wfa-siyengar — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, and @wfa-siyengar)

___
*[`.github/workflows/deploy-infra.yml` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRiUg897w8kBGSc2saw:-NRnDDmb9UzRAe63O-y5:b-gzkqrv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c0e083e00bfddcd62a302223f5e12c2279d1a96/.github/workflows/deploy-infra.yml#L36)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Request you to synch with Craig on this and provide us what exactly needs to be done. 
As Craig was looking at orchestrator which conditionally triggers.

Nevertheless, I have added a TODO in the code to remove these conditional variables after the testing is done.
</blockquote></details>

Having them doesn't hurt, does it, especially if we can default them to true. This also gives us a nice one stop shop to control the entire deployment. I don't feel strongly about this one way or the other though.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl and @wfa-mdharmalingam)

___
*[`.github/workflows/deploy-infra.yml` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRiUla24YAWkLE8BWVI:-NRnVTOz5AD6TFjG2C0g:b-syf9u3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c0e083e00bfddcd62a302223f5e12c2279d1a96/.github/workflows/deploy-infra.yml#L15)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Request you to suggest a name to be given. For now i have given it as "Deploy CMM"
</blockquote></details>

I'd suggest "Deploy CMMS", but "Deploy CMM" is fine.
___
*[`.github/workflows/deploy-infra.yml` line 57 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRnVm89Du1fdtVOvtTE:-NRnVm89Du1fdtVOvtTF:bnnwmxn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ef3dd0aa2f0814e207546cf4ed3910485003494c/.github/workflows/deploy-infra.yml#L57)):*
> ```YAML
>     steps:
>       - name: Checkout code
>         uses: actions/checkout@v2
> ```

This should be an output of the create-push-image workflow rather than being generated here. Feel free to just update the TODO to make it clearer since that other workflow isn't called yet. e.g.

```yaml
# TODO(wfa-mdharmalingam): Call the create-push-image workflow and use the image tag from its output rather than generating it here.
```



_Code quote:_
```YAML
  # Generate the Image Tag and pass to the modules where needed.
  get-image-tag:
    runs-on: ubuntu-latest
    if: inputs.create_image == true
    outputs:
      image_tag: ${{ steps.get-image-tag-step.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: generate-tag
        run: sh ./.github/workflows/export-image-tag.sh
      - id: get-image-tag-step
        run: echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
```

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl and @wfa-mdharmalingam)

___
*[`.github/workflows/deploy-infra.yml` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRiUla24YAWkLE8BWVI:-NRnWR8jBUeNYrPp0rjO:b-l0nsif) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c0e083e00bfddcd62a302223f5e12c2279d1a96/.github/workflows/deploy-infra.yml#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'd suggest "Deploy CMMS", but "Deploy CMM" is fine.
</blockquote></details>

Note that the file name should be updated to match.

**Review by wfa-siyengar — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl and @SanjayVas)

___
*[`.github/workflows/deploy-infra.yml` line 57 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRnVm89Du1fdtVOvtTE:-NRnfdtC8f4OXSObckpY:b-xs4ldn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ef3dd0aa2f0814e207546cf4ed3910485003494c/.github/workflows/deploy-infra.yml#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be an output of the create-push-image workflow rather than being generated here. Feel free to just update the TODO to make it clearer since that other workflow isn't called yet. e.g.

```yaml
# TODO(wfa-mdharmalingam): Call the create-push-image workflow and use the image tag from its output rather than generating it here.
```
</blockquote></details>

This will be taken care from the orchestrator flow.

**Review by wfa-siyengar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl)

**Review by bdomen-ggl — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: all files reviewed, 2 unresolved discussions (waiting on @wfa-mdharmalingam)

___
*[`.github/workflows/deploy-cmm.yml` line 71 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRo2-dM6aq6mbljes_U:-NRo2-dM6aq6mbljes_V:boz678q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52c16fce95f16c8d02966238cded48c1d57a5c2b/.github/workflows/deploy-cmm.yml#L71)):*
> ```YAML
>     needs: get-image-tag
>     with:
>       image_tag: ${{ needs.get-image-tag.outputs.image_tag }}
> ```

Are all the previous PRs merged yet? I could have forgotten a bit too much while I was sick too and might need a refresher on how the calls work exactly.

The inputs for `deploy-kingdom` don't match what's in main.
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/.github/workflows/deploy-kingdom.yml#L20
`kingdom` and `environment` are required in main, but I don't see them here.

Same with duchy below:
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/.github/workflows/deploy-duchy.yml#L19
`duchy_name` appears to be called `duchy` in main.
___
*[`.github/workflows/deploy-cmm.yml` line 74 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRo-TaM4caROIqa-60y:-NRo-TaN6uUEBzjq_xdV:b-s9nrag) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52c16fce95f16c8d02966238cded48c1d57a5c2b/.github/workflows/deploy-cmm.yml#L74)):*
> ```YAML
> 
>   # TODO(wfa-mdharmalingam): Connect the deploy-duchy workflow with duchy name duchy-1.
>   deploy-duchy-1:
> ```

Note: Looks like there's ways to dynamically run multiple commands in the same step with different configs using arrays (`matrix` parameter), but that probably makes things more complicated than they need to be. I like how you have it here.

**Review by wfa-siyengar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: all files reviewed, 2 unresolved discussions (waiting on @wfa-mdharmalingam)

**Review by wfa-siyengar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: all files reviewed, 2 unresolved discussions (waiting on @wfa-mdharmalingam)

**Review by wfa-siyengar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: all files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl and @wfa-mdharmalingam)

___
*[`.github/workflows/deploy-cmm.yml` line 71 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRo2-dM6aq6mbljes_U:-NRpRFHT4bjym5_L9vAn:b-3q9ho4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52c16fce95f16c8d02966238cded48c1d57a5c2b/.github/workflows/deploy-cmm.yml#L71)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Are all the previous PRs merged yet? I could have forgotten a bit too much while I was sick too and might need a refresher on how the calls work exactly.

The inputs for `deploy-kingdom` don't match what's in main.
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/.github/workflows/deploy-kingdom.yml#L20
`kingdom` and `environment` are required in main, but I don't see them here.

Same with duchy below:
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/.github/workflows/deploy-duchy.yml#L19
`duchy_name` appears to be called `duchy` in main.
</blockquote></details>

Will align this.

**Review by wfa-siyengar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: all files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl and @wfa-mdharmalingam)

___
*[`.github/workflows/deploy-cmm.yml` line 71 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915#-NRo2-dM6aq6mbljes_U:-NRpRWNE3Z5t6ETyqlZl:b-40c3cg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52c16fce95f16c8d02966238cded48c1d57a5c2b/.github/workflows/deploy-cmm.yml#L71)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Will align this.
</blockquote></details>

THese changes will come up in upcoming PRs

**Review by wfa-siyengar — APPROVED** [review]
> Dismissed @bdomen-ggl from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/915)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wfa-mdharmalingam)

**Pull request merged**
