### PR TITLE
Add protobuf for HonestMajorityShareShuffle protocol.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351)* status: all files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkWwrrh-dDPMrWCiXiH:-NkWwrrh-dDPMrWCiXiI:b-hwcmr4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L68)):*
> ```proto
>     //
>     // 4. Send the result of the share to the aggregator.
>     SHUFFLE_PHASE = 4;
> ```

As we move to the common random string at the beginning, there won't be our/other noise/shuffle seed. Let's update the comments (2 & 3) to make it consistent with what we will implement.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkX36pKBDBshD9MD1DO:-NkX36pKBDBshD9MD1DP:bjkhr8u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L31)):*
> ```proto
> 
> // Request to complete shuffle phase by a non-aggregator.
> message CompleteShufflePhaseRequest {
> ```

As worker 1 and 2 do not execute the same code (e.g. the step to add shares of noises), we may need to have a field/flag to indicate whether this is worker 1 or 2, or at least who will add their noises first.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkX3xgE8P3L8P6L6ZLU:-NkX3xgE8P3L8P6L6ZLV:bm8w0rd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L43)):*
> ```proto
>   // This determines whether to append noise share directly or to subtract
>   // sampled noise.
>   enum NoiseShareType {
> ```

This is not needed. From the common random seed, we get the 2 seeds for the noise. If the worker 1 adds noise first, then it knows that it needs to do subtraction and vice versa. What the worker needs is whether it is adding noise first or after.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkWD5WJDfs_5QVPuTmT:-NkX703y5dSqu42dy4sk:bst14qv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L89)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I don't think the aggregator needs the DP params or the noise mechanism.
</blockquote></details>

What we need is the offset. I wonder if we have another way to compute it (other than from the DP params and the noise mechanism). One possible way is to get it from (num_registers - sketch_size)/(2*#EDPs).

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351)* status: all files reviewed, 10 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkWD5WJDfs_5QVPuTmT:-NkXAiT0EYLdavewTryB:b-ntk4y7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L89)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

What we need is the offset. I wonder if we have another way to compute it (other than from the DP params and the noise mechanism). One possible way is to get it from (num_registers - sketch_size)/(2*#EDPs).
</blockquote></details>

Why does the aggregator need the offset?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351)* status: all files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkWD5WJDfs_5QVPuTmT:-NkXBN-02-Z-zRf2MuXf:b-y8idd6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L89)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why does the aggregator need the offset?
</blockquote></details>

We want the DP noise to have a mean of zero, however, due to the fact that we cannot add a negative number of noise registers, we shift the distribution to the right by `offset` and sample the noise values in [0, 2*offset]. After the aggregator computes the noisy frequency counts, it can subtract the `offset` to make the mean of the DP noise equal to zero.

**Review by SanjayVas — APPROVED** [review]
Approved for style. Pending responses to @kungfucraig's comments on design.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-:-Nkav4641DtIImtPhKw2:bae3yuj)* status: all files reviewed, 10 unresolved discussions (waiting on @ple13 and @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351)* status: 2 of 4 files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkW1XAk3J8dpKaHQwZ2:-NkbRda0Cn8HfcHG7KzO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L53)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Is this is the initial state for the Aggregator? If so, can you say so?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkWwrrh-dDPMrWCiXiH:-NkbRm062YI85qjzO58t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L68)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

As we move to the common random string at the beginning, there won't be our/other noise/shuffle seed. Let's update the comments (2 & 3) to make it consistent with what we will implement.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkX36pKBDBshD9MD1DO:-NkbRnTyDNpAHiHny8jZ:b-k103yp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L31)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

As worker 1 and 2 do not execute the same code (e.g. the step to add shares of noises), we may need to have a field/flag to indicate whether this is worker 1 or 2, or at least who will add their noises first.
</blockquote></details>

Use `order` of either `FIRST` or `SECOND` to specify that. The seeds are separated into own_seed and peer_seed.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkWDK9N9mz_ubKblaov:-NkbS3jyEqMkOg4swYf_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L33)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Use the ShuffleShareSketchParams message instead?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkWCUpJEy9Yv3hsaIyV:-NkbS4H--QiXIkdq-Fvs:bd9lluu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L39)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you use the RandomSeeds message here (only if you can't do what I'm suggesting in the next comment).
</blockquote></details>

Done
Re-organized these part
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkX3xgE8P3L8P6L6ZLU:-NkbSEGW4KTECNAPox1x:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L43)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

This is not needed. From the common random seed, we get the 2 seeds for the noise. If the worker 1 adds noise first, then it knows that it needs to do subtraction and vice versa. What the worker needs is whether it is adding noise first or after.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkWC6nd4PC04H9Py6YN:-NkbSFNjETpG2NxQQ_LT:b-klgeia) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L50)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Any reason not to just create a structure that makes the parallelism explicit? Maybe because one of the seeds is also used for shuffling?
</blockquote></details>

Done.
Reorganized this part.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkWDEfR-1OZCfcu3yIv:-NkbSIHSEhy3uAdtL1Uk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L81)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Use the ShuffleShareSketchParams message instead?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkWD5WJDfs_5QVPuTmT:-NkbSJ4C2hD-WGf7_pUA:b-qsllmg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L89)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Makes sense. Maybe just pass the offset then?
</blockquote></details>

Keep dp_params and noise_mechanism for now. It can be changed later if more suitable.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkWCrdfCFXpOuvruq5f:-NkbSV0LCtFg9oFeKu1j:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c615cae2ea420209b407652df143378f45d67fc3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L100)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Normalized histogram of frequency
</blockquote></details>

Done.

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351)* status: all files reviewed, 8 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkbfVWL7nQeGHvs62GC:-NkbfVWL7nQeGHvs62GD:bwesw2v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c971d408d5ea09d1d21c157f6ca9a7c985828ef3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L42)):*
> ```proto
>   // The order of the non-aggregator worker.
>   enum NonAggregatorOrder {
>     NOISE_SHARE_TYPE_NOT_SPECIFIED = 0;
> ```

NON_AGGREGATOR_ORDER_UNSPECIFIED = 0;



_Code quote:_
```proto
NOISE_SHARE_TYPE_NOT_SPECIFIED = 0;
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkbfVWL7nQeGHvs62GC:-NkkygMC7hES3rTseRfD:b-3vcg5x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c971d408d5ea09d1d21c157f6ca9a7c985828ef3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L42)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

NON_AGGREGATOR_ORDER_UNSPECIFIED = 0;
</blockquote></details>

Done.
Nice catch. Thanks!

**Review by ple13 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351)* status: all files reviewed, 9 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 42 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351#-NkpvwfTCZLg5L-zmv_6:-NkpvwfUBZ5mzQIl82J2:bujfupz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0cb877fa3801531c899a839a1bb37fed75f4444a/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L42)):*
> ```proto
>   // The order of the non-aggregator worker.
>   enum NonAggregatorOrder {
>     NON_AGGREGATOR_ORDER_NOT_SPECIFIED = 0;
> ```

nit: let's use UNSPECIFIED to be consistent with the guideline https://google.aip.dev/126



_Code quote:_
```proto
NOT_SPECIFIED
```

**Review by ple13 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351)* status: all files reviewed, 7 unresolved discussions (waiting on @kungfucraig)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351)* status: all files reviewed, 7 unresolved discussions (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
