### PR TITLE
Define the testRule for InProcessDuchy.

### PR DESCRIPTION
**Pull request by wangyaopw**
This will be used in the inmemory IntegationTest. The current code is just
a best guess. We'll find whether it works or not when the actual test
code is written.

https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F609465361881&view=2c2927c0-626b-4740-8620-af2a93b7d623

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/280)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> IntergationTest

nit: typo

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/280#-:-Mjq0dH0AYSDjUpwVBiC:bpeba6m)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/280#-Mjq1P4I5JqJfKkA8f13:-Mjq1P4I5JqJfKkA8f14:b1c2evf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1ba640e392a52fc7188d867a010fcb8f0e842f2/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L60)):*
> ```
> @param duchyName the name of this duchy
> ```
I think we should refer to this as Duchy ID now, no?
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/280#-Mjq1W4NAuYCWZ1qH5iL:-Mjq1W4NAuYCWZ1qH5iM:bquzrrf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1ba640e392a52fc7188d867a010fcb8f0e842f2/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L61)):*
> ```
> a gRPC channel to the Kingdom
> ```
Specify which server/services. I assume this is to the system API?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/280)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/280#-Mjq1P4I5JqJfKkA8f13:-Mjq6_Z3338E7mZpF2tR:b84jqq9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1ba640e392a52fc7188d867a010fcb8f0e842f2/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> @param duchyName the name of this duchy
> ```
I think we should refer to this as Duchy ID now, no?
</blockquote></details>

Yep.

Done
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/280#-Mjq1W4NAuYCWZ1qH5iL:-Mjq6eHpETLkpESE9M-1:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1ba640e392a52fc7188d867a010fcb8f0e842f2/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> a gRPC channel to the Kingdom
> ```
Specify which server/services. I assume this is to the system API?
</blockquote></details>

Done

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/280)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/280)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
