### PR TITLE
Fix Reporting K8s configurations.

### PR DESCRIPTION
**Pull request by SanjayVas**
* Specify dev public Kingdom API target in dev config.
* Fix typo in _reportingConfigs field.
* Drop DB secret from dev config.
* Extract common fields to definitions.
* Run formatters.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/649)

### CODE REVIEW

**Comment by SanjayVas** [comment]
Depends on world-federation-of-advertisers/common-jvm#144.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/649)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 10 files at r1, 3 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/649)* status: 9 of 15 files reviewed, all discussions resolved (waiting on @stevenwarejones and @tristanvuong2021)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/649)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
