### PR TITLE
Add operations guide for creating resources in the Kingdom.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/442)

### CODE REVIEW

**Comment by SanjayVas** [comment]
CC @renjiezh

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/442)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @SanjayVas and @yunyeng)

___
*[docs/operations/creating-resources.md, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/442#-Mw27gd-6G4qZRNLHc0s:-Mw27gd-6G4qZRNLHc0t:b67kmqp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/250dcae1da6f1aec74b487cbc2848e0f7f238333/docs/operations/creating-resources.md#L59)):*
> ```Markdown
> *   The `AuthorityKeyToPrincipalMap` is in the
>     `authority_key_identifier_to_principal_map.textproto` file in the
>     `config-files` ConfigMap. You'll need to update the file within the
> ```

is there a TODO somewhere to not require a restart?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/442)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[docs/operations/creating-resources.md, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/442#-Mw27gd-6G4qZRNLHc0s:-Mw2jAWs-rV_CnrFUHJH:b9g012h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/250dcae1da6f1aec74b487cbc2848e0f7f238333/docs/operations/creating-resources.md#L59)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is there a TODO somewhere to not require a restart?
</blockquote></details>

It's not much of priority to do dynamic configmap reading for this given that adding a TLS trusted cert would require a restart anyway. Restarting K8s deployments isn't a big deal, as the systems are designed to be restart-tolerant since that's how autoscaling works.

**Review by yunyeng — COMMENTED** [review]
This tool currently uses internal api to create a Recurring Exchange which the internal server should not accept any calls from outside according to the network policy set. So, this tools needs to be run in the same machine with internal server and whitelisted in order to create a recurring exchange. 

We need to either go ahead and submit #441 or implement v2alpha.createRecurringExchange at this point in order to continue with the deployment.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/442#-:-Mw85T1X0xY86o62O-sS:b-3iwowu)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
>  the internal server should not accept any calls from outside according to the network policy set

See the section on port forwarding in the tools README. It explicitly addresses this issue.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/442#-:-Mw8Lz_9ExG2oX7HSD_l:b-ys9658)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @stevenwarejones)

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/442)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @stevenwarejones)

**Comment by SanjayVas** [comment]
Adding @chipingyeh as reviewer since @stevenwarejones is out this week.

**Pull request merged**
