### PR TITLE
Implement Event Groups Service Reporting V2Alpha.

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1088)

**Review by riemanli — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1088)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsServiceTest.kt` line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1088#-NZDWzyo-CO05cEtbq8I:-NZDWzyo-CO05cEtbq8J:b-9fasdb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/953301fabeab52faa05d852a0149329134bba31e/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsServiceTest.kt#L82)):*
> ```Kotlin
>       .thenReturn(
>         listEventGroupsResponse {
>           eventGroups += listOf(CMMS_EVENT_GROUP, CMMS_EVENT_GROUP)
> ```

Why does it return two identical event groups?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1088)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsServiceTest.kt` line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1088#-NZDWzyo-CO05cEtbq8I:-NZDeBSe6TZwwS30cUbn:bths5zc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d888c81097afe4f206c9598489f33552f27b7cf/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsServiceTest.kt#L82)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Why does it return two identical event groups?
</blockquote></details>

Switched to two different event groups now

**Review by riemanli — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1088)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @stevenwarejones)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1088)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
