### PR TITLE
Implement create and get functions

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515)

### CODE REVIEW

**Review by chipingyeh — COMMENTED** [review]
Not sure why cert tests are failing; might be due to PR 501. 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515#-:-MzvMmJfBRPG2RMplajp:bjq45b6)* status: 0 of 10 files reviewed, all discussions resolved

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515#-N--fV9BAbMAE7_rVkSK:-N--fV9BAbMAE7_rVkSL:b-q3nrnt) (no related file):*
You'll also need to register the new service in the V2AlphaPublicApiServer [1].

[1] https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515#-N--eLnD2zGdWnOCyS2P:-N--eLnE3iiIkmT6UeU0:b-pe48my) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8f059b94e17c96509ff923e48465dfb8309731a/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L53)):*
> ```Kotlin
>     val principal = principalFromCurrentContext
> 
>     when (val resourceKey = principal.resourceKey) {
> ```

Measurement consumers should also be allowed to fetch event group metadata descriptors.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, line 135 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515#-N--esRV2oD7qLqDNVd6:-N--esRV2oD7qLqDNVd7:b-7agdam) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8f059b94e17c96509ff923e48465dfb8309731a/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L135)):*
> ```Kotlin
>   ): InternalEventGroupMetadataDescriptor {
>     return internalEventGroupMetadataDescriptor {
>       externalDataProviderId = apiIdToExternalId(dataProviderId)
> ```

Shouldn't there also be an `externalEventGroupMetadataDescriptorId`?

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @robinsons and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515#-N--fV9BAbMAE7_rVkSK:-N-3jkZ0BAunB8BNrI2r:b-896fix) (no related file):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

You'll also need to register the new service in the V2AlphaPublicApiServer [1].

[1] https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt
</blockquote></details>

Done.

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515#-N--eLnD2zGdWnOCyS2P:-N-3lv9f4GIZm7Smnkv-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8f059b94e17c96509ff923e48465dfb8309731a/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L53)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Measurement consumers should also be allowed to fetch event group metadata descriptors.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, line 135 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515#-N--esRV2oD7qLqDNVd6:-N-3oFrS75Yp5puA9lJs:b-6esvk5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8f059b94e17c96509ff923e48465dfb8309731a/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L135)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Shouldn't there also be an `externalEventGroupMetadataDescriptorId`?
</blockquote></details>

This doesn't seem like it will be used until `UpdateEventGroupMetadataDescriptor` is implemented, I'll likely add it later unless I'm missing something?

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, line 135 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515#-N--esRV2oD7qLqDNVd6:-N-5CWee9rTwg6osSizc:b-r9sz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8f059b94e17c96509ff923e48465dfb8309731a/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L135)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

This doesn't seem like it will be used until `UpdateEventGroupMetadataDescriptor` is implemented, I'll likely add it later unless I'm missing something?
</blockquote></details>

That's fine.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsServiceTest.kt, line 112 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515#-N-5D3HnEA5o2OQrXrGj:-N-5D3HnEA5o2OQrXrGk:b-iez4q0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d8cbf82b7b3a1ee0ab494146c182e1e721250ae0/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsServiceTest.kt#L112)):*
> ```Kotlin
> 
>   @Test
>   fun `getEventGroupMetadataDescriptor returns descriptor`() {
> ```

Can we add a test that is similar to this one, but uses an MC instead of an EDP? Would like to ensure that MCs can get these descriptors.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsServiceTest.kt, line 112 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515#-N-5D3HnEA5o2OQrXrGj:-N-5MKZ31hZ9M-qkuD2d:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d8cbf82b7b3a1ee0ab494146c182e1e721250ae0/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsServiceTest.kt#L112)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Can we add a test that is similar to this one, but uses an MC instead of an EDP? Would like to ensure that MCs can get these descriptors.
</blockquote></details>

Done.

**Review by robinsons — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/515)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
