### PR TITLE
Fix reporting integration tests and EDP simulator tests

### PR DESCRIPTION
**Pull request by riemanli**
* Extracted the common code of sampling VIDs to a function `sampleVids`. Affected files:
    * src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
    * src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt
    * src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt
* Computed expected values by VIDs instead of hardcoded values in EDP simulator tests.
* Calculated tolerance for result check using metric variance in reporting integration tests.
* Implemented impression metric result check in the reporting integration tests.
* Fixed bug in reporting integration tests. Bug lists:
    * Use one event group to compute expected value when there are two in the reporting set.
    * The expected value of unique reach in a report is logically incorrect.
    * Report with cumulative doesn't set cumulative to true.
* Added direct reach-only test to src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423)

**Comment by riemanli** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1423?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1413** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1413?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1423** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1423?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1423?utm_source=stack-comment).

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423)* status: 5 of 10 files reviewed, all discussions resolved (waiting on @iverson52000)

**Review by iverson52000 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/common/SampleVids.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423#-NoSgyGn8nnUVT01y-td:-NoSgyGn8nnUVT01y-te:b-8k8812) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c60da4cf88f955f801a9423100c7b54a7daab1f/src/main/kotlin/org/wfanet/measurement/loadtest/common/SampleVids.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

2024?
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 1732 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423#-NoSiMtD3I-b07TfAiuJ:-NoSiMtD3I-b07TfAiuK:bhb9l76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c60da4cf88f955f801a9423100c7b54a7daab1f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L1732)):*
> ```Kotlin
>     assertThat(result)
>       .reachValue()
>       .isWithin(2.0 / MEASUREMENT_SPEC.vidSamplingInterval.width)
> ```

Are these hard coded values tolerance of the noise? Should we use CONSTANT for them?
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 2074 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423#-NoShWNMDynNBxNTeJif:-NoShWNMDynNBxNTeJig:bokx7bq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c60da4cf88f955f801a9423100c7b54a7daab1f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L2074)):*
> ```Kotlin
>       )
>     val result: Measurement.Result = decryptResult(request.encryptedResult, MC_PRIVATE_KEY).unpack()
>     val expected: Long =
> ```

nit: maybe call this expectedReach?
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 2138 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423#-NoShbfT9STmojYe3bt3:-NoShbfT9STmojYe3bt4:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c60da4cf88f955f801a9423100c7b54a7daab1f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L2138)):*
> ```Kotlin
>       )
>     val result: Measurement.Result = decryptResult(request.encryptedResult, MC_PRIVATE_KEY).unpack()
>     val expected: Long =
> ```

ditto

**Review by iverson52000 — COMMENTED** [review]
The changes make the code cleaner. Thanks!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423#-:-NoSj2Xk1JQQMAGWMAId:b2457rn)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @iverson52000 and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/common/SampleVids.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423#-NoSil_I3qfrerjxHOT7:-NoSil_I3qfrerjxHOT8:b-9kelgi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c60da4cf88f955f801a9423100c7b54a7daab1f/src/main/kotlin/org/wfanet/measurement/loadtest/common/SampleVids.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

Is this a new file? If so, the license heading is an old version.

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423)* status: all files reviewed, 5 unresolved discussions (waiting on @riemanli)

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @iverson52000 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/common/SampleVids.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423#-NoSgyGn8nnUVT01y-td:-NoSluRv5FqGMhkRQ1jS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c60da4cf88f955f801a9423100c7b54a7daab1f/src/main/kotlin/org/wfanet/measurement/loadtest/common/SampleVids.kt#L1)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

2024?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/common/SampleVids.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423#-NoSil_I3qfrerjxHOT7:-NoSlulMClCpC6CbBdgz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c60da4cf88f955f801a9423100c7b54a7daab1f/src/main/kotlin/org/wfanet/measurement/loadtest/common/SampleVids.kt#L1)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Is this a new file? If so, the license heading is an old version.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 1732 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423#-NoSiMtD3I-b07TfAiuJ:-NoSm2PF-kpLAiZNF9t3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c60da4cf88f955f801a9423100c7b54a7daab1f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L1732)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Are these hard coded values tolerance of the noise? Should we use CONSTANT for them?
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 2074 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423#-NoShWNMDynNBxNTeJif:-NoSyyPH4b7EApPCrTXd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c60da4cf88f955f801a9423100c7b54a7daab1f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L2074)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

nit: maybe call this expectedReach?
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 2138 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423#-NoShbfT9STmojYe3bt3:-NoSz3v0BCmiDKSLElRo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c60da4cf88f955f801a9423100c7b54a7daab1f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L2138)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 5 of 6 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by riemanli — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 4 of 6 files at r2, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1423)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
