### PR TITLE
Support emptyDir volume mounts.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/686)

### CODE REVIEW

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/686)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @SanjayVas)

___
*[`src/main/k8s/base.cue` line 190 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/686#-NBxWwlx--G4SdQA6gyY:-NBxWwlx--G4SdQA6gyZ:bjb90sp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aef60f47549c09b32c4e003992ec72a286d29ea6/src/main/k8s/base.cue#L190)):*
> ```CUE
> } | {
> 	volume: emptyDir: {}
> }
> ```

Need to add `volumeMount: mountPath: _ | *"/data"` here?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/686)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @iverson52000)

___
*[`src/main/k8s/base.cue` line 190 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/686#-NBxWwlx--G4SdQA6gyY:-NBy330bBNSMyZI3vcHu:bs3c0va) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aef60f47549c09b32c4e003992ec72a286d29ea6/src/main/k8s/base.cue#L190)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Need to add `volumeMount: mountPath: _ | *"/data"` here?
</blockquote></details>

The other defaults were for backwards-compatibility so I didn't have to specify the paths for our existing single secret/configmap. Technically the default secret mount path isn't even in the right place according to the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard).

Each usage of an emptyDir `#Mount` should specify its own mount path, since we don't know e.g. whether it's configuration (under `/etc`), cache (under `/var/cache`), or other files written at runtime (under `/run`).

**Review by iverson52000 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/686)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @iverson52000)

**Review by iverson52000 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/686)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/686)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

___
*[`src/main/k8s/base.cue` line 190 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/686#-NBxWwlx--G4SdQA6gyY:-NC1enrd2Haj2SnBVLYd:b-pu0jtp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aef60f47549c09b32c4e003992ec72a286d29ea6/src/main/k8s/base.cue#L190)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The other defaults were for backwards-compatibility so I didn't have to specify the paths for our existing single secret/configmap. Technically the default secret mount path isn't even in the right place according to the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard).

Each usage of an emptyDir `#Mount` should specify its own mount path, since we don't know e.g. whether it's configuration (under `/etc`), cache (under `/var/cache`), or other files written at runtime (under `/run`).
</blockquote></details>

On second thought, went ahead and added a default.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/686)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
