### PR TITLE
Populate MeasurementSpec.serialized_measurement_public_key field.

### LINKED ISSUE #1596: MeasurementSpec.serialized_measurement_public_key field is not populated
**Describe the bug**
The `serialized_measurement_public_key` field in `MeasurementSpec` is not populated by the MeasurementSystem CLI or by the Reporting system. While this field is deprecated, it must continue to be set until v0.6.0 for DataProvider API compatibility.

**Component(s) affected**
Reporting v1, Reporting v2, MeasurementSystem CLI

**Version**
v0.5.3

### PR DESCRIPTION
**Pull request by SanjayVas**
Closes #1596

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1597)

**Comment by SanjayVas** [comment]
Depends on world-federation-of-advertisers/consent-signaling-client#50

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1597)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

___
*[`MODULE.bazel` line 328 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1597#-Nwt4rdG3n6iCKLHb5Qe:-NwtwpJP4_SZII3xhhcU:b-ra8sxl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ecd11dd67c33b2c2c58bbf3d2cd229f24bac649/MODULE.bazel#L328)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Is this code actually supposed to be merged?
</blockquote></details>

No. "Submit" here means "merge" in Git terms, so this comment is indicating something that needs to be done before this PR is merged. In this case, switching to a released version once the referenced PR has been merged, released, and available in the registry.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1597)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1597)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
