### PR TITLE
Fix parsing provider from request

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: all files reviewed, 3 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-Moda7SM9HXXJZXSupRS:-Moda7SM9HXXJZXSupRT:b-hhww67) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c4bc68bbce3380d1026eef2d6fde9f321905b32/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt#L52)):*
> ```Kotlin
>   val parentFromRequest =
>     when (provider.type) {
>       Provider.Type.MODEL_PROVIDER -> ModelProviderKey.fromName(requestModelProvider)
> ```

combine both these whens? `ModelProviderKey.fromName(requestModelProvider).modelProviderId`
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, line 169 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-ModaHgeE6VwYSFKDJqB:-ModaHgeE6VwYSFKDJqC:bcasjyy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c4bc68bbce3380d1026eef2d6fde9f321905b32/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt#L169)):*
> ```Kotlin
>     val e =
>       assertFailsWith<StatusRuntimeException> {
>         claimReadyExchangeStep { dataProvider = "dataProviders/AAAAAAAAMDk" }
> ```

i'd prefer to keep a test helper here
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesServiceTest.kt, line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-ModaL4cBhnmOtd9_3AE:-ModaL4cBhnmOtd9_3AF:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c4bc68bbce3380d1026eef2d6fde9f321905b32/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesServiceTest.kt#L93)):*
> ```Kotlin
>         getExchange {
>           name = exchangeKey.toName()
>           dataProvider = "dataProviders/AAAAAAAAMDk"
> ```

ditto

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-Moda7SM9HXXJZXSupRS:-ModgpheAmxVuozDss_S:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c4bc68bbce3380d1026eef2d6fde9f321905b32/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

combine both these whens? `ModelProviderKey.fromName(requestModelProvider).modelProviderId`
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, line 169 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-ModaHgeE6VwYSFKDJqB:-ModgogpAcRqoV_N1NOY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c4bc68bbce3380d1026eef2d6fde9f321905b32/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt#L169)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'd prefer to keep a test helper here
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesServiceTest.kt, line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-ModaL4cBhnmOtd9_3AE:-Modgp1I8WbIojiCKJ8D:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c4bc68bbce3380d1026eef2d6fde9f321905b32/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesServiceTest.kt#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-MoeGQUf8zRTqloHao-z:-MoeGQUf8zRTqloHao0-:by6h5zs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8857be7ff21bbef92fe686beceb17cf2342f54fa/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt#L50)):*
> ```Kotlin
>   val provider = getProviderFromContext()
>   @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA") // Proto enums are not null.
>   val parentFromRequest =
> ```

Here's an idea, what do you think?

1. Refactor `getProviderFromContext` to:

```
fun ResourceKey.toProvider(): Provider? {
  when (...) { ... } // Copied from getProviderFromContext
}

fun getProviderFromContext(): Provider {
  return requireNotNull(principalFromCurrentContext.resourceKey.toProvider())
}
```

2. Change `validateRequestProvider` to:

```
fun validateRequestProvider(requestParent: String): Provider {
  val contextProvider = getProviderFromContext()
  grpcRequire(contextProvider == Principal.fromName(requestParent)?.resourceKey?.toProvider()) { ... }
  return contextProvider
}
```

What do you think?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-MoeIN3ZBxRZQYbRp4lR:-MoeG4NG2yWr6nHGaWyB:bhtz6kn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8857be7ff21bbef92fe686beceb17cf2342f54fa/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt#L53)):*
> ```Kotlin
>     when (provider.type) {
>       Provider.Type.MODEL_PROVIDER ->
>         ModelProviderKey.fromName(requestModelProvider)!!.modelProviderId
> ```

Please use `grpcRequireNotNull` instead of `!!` because `requestModelProvider` comes from user input

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-MoeTkWw7Sr_8WJdCJmm:-MoeTkWxC_3YWPq4n5LA:bqsbrv9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8857be7ff21bbef92fe686beceb17cf2342f54fa/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt#L73)):*
> ```Kotlin
> import org.wfanet.measurement.internal.kingdom.streamExchangeStepsRequest
> 
> private const val DATA_PROVIDER = "dataProviders/AAAAAAAAMDk"
> ```

do they have the same id? that's kind of confusing. what about a test helper to generate these?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-MoeGQUf8zRTqloHao-z:-MokJQs02Om385YhuLrk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8857be7ff21bbef92fe686beceb17cf2342f54fa/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt#L50)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Here's an idea, what do you think?

1. Refactor `getProviderFromContext` to:

```
fun ResourceKey.toProvider(): Provider? {
  when (...) { ... } // Copied from getProviderFromContext
}

fun getProviderFromContext(): Provider {
  return requireNotNull(principalFromCurrentContext.resourceKey.toProvider())
}
```

2. Change `validateRequestProvider` to:

```
fun validateRequestProvider(requestParent: String): Provider {
  val contextProvider = getProviderFromContext()
  grpcRequire(contextProvider == Principal.fromName(requestParent)?.resourceKey?.toProvider()) { ... }
  return contextProvider
}
```

What do you think?

</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-MoeIN3ZBxRZQYbRp4lR:-MokJSJC28dabxbuk9gh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8857be7ff21bbef92fe686beceb17cf2342f54fa/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt#L53)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use `grpcRequireNotNull` instead of `!!` because `requestModelProvider` comes from user input
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-MoeTkWw7Sr_8WJdCJmm:-MokJT47-nbZ8E_uBfoo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8857be7ff21bbef92fe686beceb17cf2342f54fa/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt#L73)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do they have the same id? that's kind of confusing. what about a test helper to generate these?
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 174 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-MolYNaWDvIgN8VLK0-V:-MolYNaWDvIgN8VLK0-W:b-uib0hg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cde955fc165b74d0f23ef84e5228ee16a0d10990/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L174)):*
> ```Kotlin
> 
> private fun getProvider(request: ClaimReadyExchangeStepRequest): String {
>   return if (request.hasDataProvider()) {
> ```

Please use a when on the provider case
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesService.kt, line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-MolYWmf88iNNwjWLjli:-MolYWmf88iNNwjWLjlj:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cde955fc165b74d0f23ef84e5228ee16a0d10990/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesService.kt#L62)):*
> ```Kotlin
> private fun getProvider(request: GetExchangeRequest): String {
>   return if (request.hasDataProvider()) {
>     request.dataProvider
> ```

Ditto

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 174 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-MolYNaWDvIgN8VLK0-V:-MolgCMpE8hpxViVbWCy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cde955fc165b74d0f23ef84e5228ee16a0d10990/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L174)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use a when on the provider case
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesService.kt, line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-MolYWmf88iNNwjWLjli:-MolgBcX-8mHsSG6GUlX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cde955fc165b74d0f23ef84e5228ee16a0d10990/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesService.kt#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 174 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-MolYNaWDvIgN8VLK0-V:-Molh9SF23NWhhWysJ3x:b-b8mhtw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cde955fc165b74d0f23ef84e5228ee16a0d10990/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L174)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Shouldn't there be an enum backing the oneof in request?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 174 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367#-MolYNaWDvIgN8VLK0-V:-MonlZjDBNDjZOcUEmP4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cde955fc165b74d0f23ef84e5228ee16a0d10990/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L174)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Shouldn't there be an enum backing the oneof in request? 
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 9 of 15 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 10 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 14 of 14 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
