### PR TITLE
Refactor the EdpSimulator to match the style of other simulators.

### PR DESCRIPTION
**Pull request by wangyaopw**
The key change is defining a single method .process() to cover all works the simulator does, such that the code can be reused in the in-memory integration test easier.

https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F609465361881&view=2c2927c0-626b-4740-8620-af2a93b7d623

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/283)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
IIUC, this mainly extracts the flags and runner base class from the simulator right?

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/283#-:-Mk9nEfY6nGSo2ZPrRI3:buz55y5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by wangyaopw — COMMENTED** [review]
Yep.

The PR has no behavior change. It
1. extracted the flags out as its file.
2.  renamed the RequisitionFulfillmentWorkFlow class to EdpSimulator
3.  renamed the old EdpSimulator class to EdpSimulatorRunner

The new EdpSimulator class will be used inside the in-memory integration test.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/283#-:-MkAL-Cp8Jl22IHjP2L0:bu8gga7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/283)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 73 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/283#-MkCmHyZ5oFaajAYRgJ-:-MkCmHy_2Y13q8JZ8KML:bxh91bo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a726c8ec1621f3981ed611594f560d7c08e3045d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L73)):*
> ```Kotlin
> 
> data class EdpData(
>   /** The Edp's public API resource name. */
> ```

nit: I think this should all be EDP, not Edp. It's not the name of an identifier but the actual abbreviation.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/283)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 73 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/283#-MkCmHyZ5oFaajAYRgJ-:-MkDAtn13A9DgCl6IBI1:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a726c8ec1621f3981ed611594f560d7c08e3045d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L73)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

nit: I think this should all be EDP, not Edp. It's not the name of an identifier but the actual abbreviation.
</blockquote></details>

Done

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 73 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/283#-MkCmHyZ5oFaajAYRgJ-:-MkDBTuCA4ewPAiWt--W:bjwa7hh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a726c8ec1621f3981ed611594f560d7c08e3045d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L73)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Done
</blockquote></details>

:tada:

**Pull request merged**
