### PR TITLE
Support request_id field in CreateEventGroupMetadataDescriptorRequest.

### PR DESCRIPTION
**Pull request by SanjayVas**
This allows for idempotent create operations.

This is for #768 and depends on https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/115

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/785)

### CODE REVIEW

**Review by robinsons — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/785)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/785)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`build/repositories.bzl` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/785#-NIocLQgBzZH9E7wAPyS:-NIocLQgBzZH9E7wAPyT:bh46aen) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99f940b660fd714e61dc516013f43f93561e991d/build/repositories.bzl#L40)):*
> ```Starlark
>     wfa_repo_archive(
>         name = "wfa_measurement_proto",
>         # DO_NOT_SUBMIT: Use version.
> ```

you mean to update to a new version before merging the PR, right?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/785)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`build/repositories.bzl` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/785#-NIocLQgBzZH9E7wAPyS:-NIrzOMWCTomJyV-Ys37:b5w898s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99f940b660fd714e61dc516013f43f93561e991d/build/repositories.bzl#L40)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

you mean to update to a new version before merging the PR, right?
</blockquote></details>

Correct. This comment is to flag that I need to do so before submitting (merging).

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/785)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
