### PR TITLE
Add functionality to check privacy budget would be exceeded without charging

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589)

### CODE REVIEW

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3uQxUxCtVBbcQ3p_xz:-N3uQxUxCtVBbcQ3p_y-:bsslwnk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66fd8feb07c35fd5ab6eefbee7ed34e8c1335653/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L62)):*
> ```Kotlin
>    */
>   fun chargingWillExceedPrivacyBudget(
>     reference: Reference,
> ```

Matthew: "Why is a reference needed?"

Because if this charge is for a requisition that was done before, it will not exceed the budget since it wont be processed. If we don't have this, effectively, this function will have inconsistent results for actually charging. So someone can see that charging will exceed but in reality, when they charge it wont exceed because that reference was charged before.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3uQfgHCBnbjr3mOuYW:-N3uQfgHCBnbjr3mOuYX:brsj1gl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66fd8feb07c35fd5ab6eefbee7ed34e8c1335653/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L65)):*
> ```Kotlin
>     privacyBucketGroups: Set<PrivacyBucketGroup>,
>     charges: Set<Charge>
>   ): Boolean {
> ```

Matthew : "For charging privacy budget, I can see why throwing an error if budget exceeded could make sense. For checking privacy budget, I would have thought that the function should return a boolean. Why is throwing an exception the better choice?"

Thank you, I agree, changed.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3uQofu5P8E3W-LSegt:-N3uQofu5P8E3W-LSegu:bww5w4d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66fd8feb07c35fd5ab6eefbee7ed34e8c1335653/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L97)):*
> ```Kotlin
>    * to commit an update to the database.
>    */
>   fun charge(
> ```

Dulio : "nit: a matter of preference, but how about the public function name be the more expressive one? e.g. checkPrivacyBudgetExceeded(),
and the private helper function could be renamed. Same for the other check() functions"

Thank you, I agree, changed. Made the private funs descriptive as well
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 147 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3uRpSZ2MzXoKUsImwl:-N3uRpSZ2MzXoKUsImwm:b-dq99vt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66fd8feb07c35fd5ab6eefbee7ed34e8c1335653/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L147)):*
> ```Kotlin
>    * exceptions could include a failure to commit the transaction to the database.
>    */
>   fun chargingWillExceedPrivacyBudget(
> ```

Matthew: "Also here, I don't understand the need to include a reference, and I would have it return a boolean value representing whether or not there is available budget for the proposed query."

ditto on the reference comment of the ledger. Agreed on the boolean and changed it.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3uS1Uv8WtDoyiH-1Dn:-N3uS1Uw9cqg9g6jwmwd:bfxcr71) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66fd8feb07c35fd5ab6eefbee7ed34e8c1335653/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L149)):*
> ```Kotlin
>   fun chargingWillExceedPrivacyBudget(
>     reference: Reference,
>     requisitionSpec: RequisitionSpec,
> ```

Matthew: "One other thing that I would strongly consider is the idea of allowing the caller to provide a list of <RequisitionSpec, MeasurementSpec> pairs. This would be useful because I believe it is the case that MC's will be interested in knowing whether they can run an entire report (e.g., for example, all 4K queries in the Comscore report) as opposed to knowing whether they can run just a single query."

I agree this is a great thing to have. How about I update this as a follow on PR?

**Review by matthewclegg — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @duliomatos1 and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3uQxUxCtVBbcQ3p_xz:-N3vaNVQAwxJ2koVjHdk:b-avilrr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66fd8feb07c35fd5ab6eefbee7ed34e8c1335653/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L62)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Matthew: "Why is a reference needed?"

Because if this charge is for a requisition that was done before, it will not exceed the budget since it wont be processed. If we don't have this, effectively, this function will have inconsistent results for actually charging. So someone can see that charging will exceed but in reality, when they charge it wont exceed because that reference was charged before.
</blockquote></details>

I am not sure that I agree with this.  From the perspective of the measurement consumer, I believe the typical workflow will be as follows:

1. Create a collection of related MeasurementSpecs for a report.
2. Call PBM to check if there is available PB to handle these.
3. If yes, create a Reference(s) to refer to these MeasurementSpecs.
4. Call Kingdom to initiate the measurements.
5. Kingdom calls PBM to charge privacy budget.

At step 2, when the check is made, the Reference(s) don't yet exist.  At step 5, when the charge is made, we call chargePrivacyBudget instead of checkPrivacyBudget.  I don't think it should be necessary to create a Reference just to check if there is available privacy budget, and I don't see a realistic case for calling this function if one already has a reference in hand. 
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3vgVKqAZvR-rDg3ANO:-N3vgVKqAZvR-rDg3ANP:b-55uuqa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3d8a2016f9915071d97e89140adcd5b84c22813/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L71)):*
> ```Kotlin
>     }
> 
>     val context = backingStore.startTransaction()
> ```

How does the transaction get committed or aborted?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 125 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3vdSUlBZP_fL4wH4xT:-N3vdSUlBZP_fL4wH4xU:b-jo5uk1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3d8a2016f9915071d97e89140adcd5b84c22813/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L125)):*
> ```Kotlin
>       }
>     if (!failedBucketList.isEmpty()) {
>       context.commit()
> ```

A pending transaction can be thought of as a resource, similar to an open file.  In working with resources like this, I find it much easier to reason about correctness if I use the rule that any function that creates a resource must also be responsible for disposing of that resource.  Otherwise, it can be difficult to ensure that every resource which is created is also eventually disposed of.

Maybe another approach would be to enclose the use of the context in Kotlin's equivalent of try-with-resources:  https://www.baeldung.com/kotlin/try-with-resources
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3uS1Uv8WtDoyiH-1Dn:-N3vcUMb4gRdjPW5grCW:b32wtd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66fd8feb07c35fd5ab6eefbee7ed34e8c1335653/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L149)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Matthew: "One other thing that I would strongly consider is the idea of allowing the caller to provide a list of <RequisitionSpec, MeasurementSpec> pairs. This would be useful because I believe it is the case that MC's will be interested in knowing whether they can run an entire report (e.g., for example, all 4K queries in the Comscore report) as opposed to knowing whether they can run just a single query."

I agree this is a great thing to have. How about I update this as a follow on PR?
</blockquote></details>

ok

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3vgVKqAZvR-rDg3ANO:-N3z5L8Q7OVlUMQrC3fl:bf8idz2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3d8a2016f9915071d97e89140adcd5b84c22813/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L71)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

How does the transaction get committed or aborted?
</blockquote></details>

Commit is handled by `context.commit()`. Abort is handled by closing the `context` without doing a commit (e.g. an exception is thrown inside a `backingStore.startTransaction().use { ... }` block like here).

Here there's only reading from the backing store, that's why there's no `commit()` (the interface currently requires to start a transaction for reading as well)

I've previously made the context and the backingStore implement `AutoCloseable` interface so we always dispose the resources with kotlin's `.use() { ... }` idiom
(`.use()` in kotlin in syntatic suggar for `.close()` in a try block)
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 125 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3vdSUlBZP_fL4wH4xT:-N3z8E7r9EVRB4xxNOyR:b-sswpnr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3d8a2016f9915071d97e89140adcd5b84c22813/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L125)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

A pending transaction can be thought of as a resource, similar to an open file.  In working with resources like this, I find it much easier to reason about correctness if I use the rule that any function that creates a resource must also be responsible for disposing of that resource.  Otherwise, it can be difficult to ensure that every resource which is created is also eventually disposed of.

Maybe another approach would be to enclose the use of the context in Kotlin's equivalent of try-with-resources:  https://www.baeldung.com/kotlin/try-with-resources
</blockquote></details>

I agree, seems to be handled with a `backingStore.startTransaction().use() { ... }` block @uakyol introduced above.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3vgVKqAZvR-rDg3ANO:-N3vwAD9BNvSzn8-29KH:b31scjg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3d8a2016f9915071d97e89140adcd5b84c22813/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L71)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

How does the transaction get committed or aborted?
</blockquote></details>

Thanks for pointing out. Since the context is autoclosable, I think this use block we should be fine.



_Code quote:_
```Kotlin
context = backingStore.startTransacti
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 125 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3vdSUlBZP_fL4wH4xT:-N3vxTRlCtr4dGHBeZQB:b-idt5wx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3d8a2016f9915071d97e89140adcd5b84c22813/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L125)):*
> I don't think we have abort functionality, 
Awesome, changed it. We use this same approach here as well: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L43 Context is already AutoClosable.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3vgVKqAZvR-rDg3ANO:-N3zecFL6lyG5SvW1ktS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3d8a2016f9915071d97e89140adcd5b84c22813/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L71)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Thanks for pointing out. Since the context is autoclosable, I think this use block we should be fine.
</blockquote></details>

Done.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 125 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3vdSUlBZP_fL4wH4xT:-N3zedtu1Kh4noIZLLQp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3d8a2016f9915071d97e89140adcd5b84c22813/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L125)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

> I don't think we have abort functionality, 
Awesome, changed it. We use this same approach here as well: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L43 Context is already AutoClosable. 
</blockquote></details>

Done.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N3uQxUxCtVBbcQ3p_xz:-N3zv48k9AkjdcIv79VZ:bn7cpp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66fd8feb07c35fd5ab6eefbee7ed34e8c1335653/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L62)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

I am not sure that I agree with this.  From the perspective of the measurement consumer, I believe the typical workflow will be as follows:

1. Create a collection of related MeasurementSpecs for a report.
2. Call PBM to check if there is available PB to handle these.
3. If yes, create a Reference(s) to refer to these MeasurementSpecs.
4. Call Kingdom to initiate the measurements.
5. Kingdom calls PBM to charge privacy budget.

At step 2, when the check is made, the Reference(s) don't yet exist.  At step 5, when the charge is made, we call chargePrivacyBudget instead of checkPrivacyBudget.  I don't think it should be necessary to create a Reference just to check if there is available privacy budget, and I don't see a realistic case for calling this function if one already has a reference in hand. 


</blockquote></details>

Thanks Matthew, updated based on our offline conversation. Removed refenceId and added a new func  -> referenceWillBeProcessed

**Review by uakyol — COMMENTED** [review]
> Dismissed @matthewclegg from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589)* status: 1 of 7 files reviewed, all discussions resolved (waiting on @duliomatos1 and @matthewclegg)

**Review by duliomatos1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @matthewclegg and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 42 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N436h62Dw5gvkp4r_AY:-N436h63DGN-8eOxW-pl:b-lubdh0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/720cec1a002b0fcba4802b485a291500110d82ca/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L42)):*
> ```Kotlin
> 
>   /** Checks if calling charge with this [reference] will result in an update in the ledger. */
>   fun referenceWillBeProcessed(reference: Reference) = (!ledger.hasLedgerEntry(reference))
> ```

nit: doesn't really need the parenthesis in the expression to the right
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt` line 118 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N438JOkDxK7HnqFvBgO:-N438JOkDxK7HnqFvBgP:bcfhf0x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/720cec1a002b0fcba4802b485a291500110d82ca/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt#L118)):*
> ```Kotlin
>     pbm.chargePrivacyBudget(createQuery("referenceId1"))
> 
>     // Check returns true because charges would have exceeded the budget.
> ```

I think that the comment doesn't match the assertion. Isn't it just checking the presence of the reference, and not exceeding the budget?
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt` line 132 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N438msH4_n1unH4ZqzW:-N438msH4_n1unH4ZqzX:b-2guby3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/720cec1a002b0fcba4802b485a291500110d82ca/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt#L132)):*
> ```Kotlin
>     pbm.chargePrivacyBudget(createQuery("referenceId1"))
> 
>     // Check returns true because charges would have exceeded the budget.
> ```

same here

**Review by matthewclegg — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589)* status: all files reviewed, 3 unresolved discussions (waiting on @uakyol)

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 42 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N436h62Dw5gvkp4r_AY:-N43S45o6x2wyvkxsnXQ:bozmodt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/720cec1a002b0fcba4802b485a291500110d82ca/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L42)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

nit: doesn't really need the parenthesis in the expression to the right
</blockquote></details>

thank you. yes
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt` line 118 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N438JOkDxK7HnqFvBgO:-N43PM1Y8Z1cj4NkvDjS:b-2c4jee) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/720cec1a002b0fcba4802b485a291500110d82ca/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt#L118)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I think that the comment doesn't match the assertion. Isn't it just checking the presence of the reference, and not exceeding the budget?
</blockquote></details>

ah, thank you!, copied from other test, forgot to change the comment.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt` line 132 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-N438msH4_n1unH4ZqzW:-N43PTSG2iRH-UOLKiuQ:b-1cyu7w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/720cec1a002b0fcba4802b485a291500110d82ca/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt#L132)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

same here
</blockquote></details>

thank you

**Review by duliomatos1 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 5 files at r1, 1 of 2 files at r4, 2 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/589#-:-N47IRc06orqj2j6MEgv:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Pull request merged**
