### PR TITLE
Initial GRPC and Gateway servers with TLS for the BFF

### PR DESCRIPTION
**Pull request by bdomen-ggl**
Adding scaffolding for:
1. BFF gRPC server
2. BFF Gateway server

Gateway Go code mostly taken from the GRPC-Gateway GitHub example:
https://github.com/grpc-ecosystem/grpc-gateway/tree/main/examples/internal/gateway
The example incorporated a lot of things that were unnecessary for us. I tried to strip out the obvious pieces. Code structure is generally left in place to make it easier to add back if desired.
Also added TLS to connect to the GRPC service and to the Gateway service. In both cases client side auth is not required. We will only deploy the services temporarily for testing purposes and shut them down when finished.

Not included (but not limited to):
- Halo and UI request/response transformations
- Updating proto definitions for BFF
- Will need to add other API methods like List Event Groups and Create Report later

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1333)

**Comment by bdomen-ggl** [comment]
@SanjayVas Going through some finishing touches still, but ready to review at a high level. Added the Kotlin gRPC service stub using the common server and the Go gRPC-Gateway service. The gRPC service is mostly a stub. It does technically connect to the Halo Reporting API but passes back a mostly empty object to the caller as the proto definition isn't finished yet. I also went ahead and updated the references to Halo to point to v2Alpha. Since I'm not doing much with the responses there's not really any extra work yet.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1333)* status: all files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1333#-NjK19nQ6NabGTNhh3Ne:-NjK19nQ6NabGTNhh3Nf:bor2nx7) (no related file):*
I don't know much about Golang in order to review that code. Just make sure you're following the [style guide](https://google.github.io/styleguide/go/) and running everything through `go fmt`.

___
___
*[`experimental/reporting-ui/src/main/go/org/wfanet/measurement/reporting/bff/gateway/BUILD.bazel` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1333#-NjK-pTh0ffSWWIvUmTX:-NjK-pTi6L7XsVL4eeRK:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbd3b5d83a34c9923f68ade8329b4f3984d4243c/experimental/reporting-ui/src/main/go/org/wfanet/measurement/reporting/bff/gateway/BUILD.bazel#L36)):*
> ```Starlark
> 
> go_binary(
>     name = "serve",
> ```

nit



_Suggestion:_
```Starlark
server
```

**Comment by bdomen-ggl** [comment]
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

@SanjayVas Going through some finishing touches still, but ready to review at a high level. Added the Kotlin gRPC service stub using the common server and the Go gRPC-Gateway service. The gRPC service is mostly a stub. It does technically connect to the Halo Reporting API but passes back a mostly empty object to the caller as the proto definition isn't finished yet. I also went ahead and updated the references to Halo to point to v2Alpha. Since I'm not doing much with the responses there's not really any extra work yet.
</blockquote></details>

@SanjayVas Ran `gofmt` (reordered some imports and variables) and updated the build target name.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1333)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl)

**Pull request merged**
