### PR TITLE
Refactor read by external id functions after changing SpannerReader

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274#-MjWL17Y8HEWJYEUCpc7:-MjWL17Z00Vz5-4ggYsA:b-v0m1n3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44c9c5293e4f8e695e84b22dc8887189e7973ac8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L112)):*
> ```Kotlin
>           ExternalId(externalRecurringExchangeId)
>         )
>         ?.recurringExchange
> ```

If the `RecurringExchangeReader.Result` is null, we should immediately return PERMISSION_DENIED. This should simplify the code here a bunch too.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274#-MjWL17Y8HEWJYEUCpc7:-Mj_Tbx4-FnHKkyelpK9:b15wg15) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c4b94ee0a9e4aee650c6fa28dbb1ae0fd5f44ab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L112)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If the `RecurringExchangeReader.Result` is null, we should immediately return PERMISSION_DENIED. This should simplify the code here a bunch too.
</blockquote></details>

I added it there, I also added a failed message to CreateExchange and CreateRecurringExchange.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274#-Mj_nsjI374JK6XZssHG:-Mj_nsjJ4l4WC4PsR906:b-8wojqm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5a4e3e340be71d71152ab2ce13a99f9eea49d84/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt#L38)):*
> ```Kotlin
>         )
>         ?.recurringExchangeId
>         ?: failGrpc(Status.NOT_FOUND) { "RecurringExchange not found" }
> ```

Please move the `?:` up as high as possible (right before `?.recurringExchangeId`)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274#-Mj_okwCB1xOUqr83siH:-Mj_okwCB1xOUqr83siI:b-aucxsn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5a4e3e340be71d71152ab2ce13a99f9eea49d84/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt#L40)):*
> ```Kotlin
>         )
>         ?.dataProviderId
>         ?: failGrpc(Status.NOT_FOUND) { "DataProvider not found" }
> ```

Please move up (see other comment on this)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274#-Mj_osl54Q8XoW6xh-5Q:-Mj_osl54Q8XoW6xh-5R:b-aucxsn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5a4e3e340be71d71152ab2ce13a99f9eea49d84/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt#L49)):*
> ```Kotlin
>         )
>         ?.modelProviderId
>         ?: failGrpc(Status.NOT_FOUND) { "ModelProvider not found" }
> ```

Please move up (see other comment on this)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274#-MjWL17Y8HEWJYEUCpc7:-Mj_ny6BBS9PNiEgvJJ9:buvx15j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c4b94ee0a9e4aee650c6fa28dbb1ae0fd5f44ab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L112)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I added it there, I also added a failed message to CreateExchange and CreateRecurringExchange.
</blockquote></details>

Please move the `?:` up as high as possible (right before `?.recurringExchange`)

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274#-Mj_okwCB1xOUqr83siH:-Mj_rwQL5lt5gnNc4FwW:b-fnoa7j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ecbf9cf2d46c9b8990c17c0cbaac610234285e8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please move up (see other comment on this)
</blockquote></details>

This is as high as possible. It is the shorthand for if Result not null else fail.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274#-Mj_okwCB1xOUqr83siH:-Mj_xPR-4zRIszoZ39mG:b11ojl1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ecbf9cf2d46c9b8990c17c0cbaac610234285e8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt#L40)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This is as high as possible. It is the shorthand for if Result not null else fail.
</blockquote></details>

Are you absolutely 100% sure that you can't swap this with the line above it?

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274#-Mj_okwCB1xOUqr83siH:-Mj_xOlL6GeGQjfotIzc:bjamxaw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ecbf9cf2d46c9b8990c17c0cbaac610234285e8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Are you absolutely 100% sure that you can't swap this with the line above it?
</blockquote></details>

Well I could make it an if else instead to do that. Using let and if else for the one in FinishExchangeStepAttempt.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274#-Mj_okwCB1xOUqr83siH:-Mj_zxZ5DozW9XYfFXca:bgw9voy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9ecbf9cf2d46c9b8990c17c0cbaac610234285e8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt#L40)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Well I could make it an if else instead to do that. Using let and if else for the one in FinishExchangeStepAttempt.
</blockquote></details>

Nevermind, let's leave it as is

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 25 of 28 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/274)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
