### PR TITLE
Add internal SpannerRequisitionsService, implementing Get and Stream methods.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)

### CODE REVIEW

**Comment by SanjayVas** [comment]
This is intended to be merged into main after base PR #210

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-Mha-wP93y9sgEiw3-ob:-Mha-wP93y9sgEiw3-oc:b-l4re68) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ef54305c06aba5775b1bc0bd2add7dbf063e168a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L52)):*
> ```Kotlin
> }
> 
> private fun Statement.Builder.appendWhereClause(filter: StreamRequisitionsRequest.Filter) {
> ```

@efoxepstein Just wanted to call out that this isn't using the `org.wfanet.measurement.kingdom.deploy.gcloud.spanner.common.Filters` mechanism. That seemed like a lot of overhead for building a simple WHERE clause. Let me know what you think.

**Comment by SanjayVas** [comment]
This is for #103.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)* status: all files reviewed, 10 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnrthiCtR3QD3QUKhU:-MhnrthjEYyDuXdnoKYM:b1chns) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt#L37)):*
> ```Kotlin
>       .readByExternalId(
>         client.singleUse(),
>         request.externalMeasurementConsumerId,
> ```

Since Requisitions are kind of keyed by a bunch of things, it would help me to see the parameter names on this function call, at least for the last 3 parameters, to make sure no wires are crossed.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-Mha-wP93y9sgEiw3-ob:-MhnsWeQ9OyonvUIBrQn:b-m1ochf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ef54305c06aba5775b1bc0bd2add7dbf063e168a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@efoxepstein Just wanted to call out that this isn't using the `org.wfanet.measurement.kingdom.deploy.gcloud.spanner.common.Filters` mechanism. That seemed like a lot of overhead for building a simple WHERE clause. Let me know what you think.
</blockquote></details>

Is your proposal to just drop `Filters` totally? (I feel like we should be consistent one way or another, I don't care which way)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnsNsq4NfLUWY31ihc:-MhnsNsq4NfLUWY31ihd:b-rmcop0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L37)):*
> ```Kotlin
> 
> class StreamRequisitions(requestFilter: StreamRequisitionsRequest.Filter, limit: Int = 0) :
>   SpannerQuery<Requisition, Requisition>() {
> ```

Should we have `SimpleSpannerQuery<T>` like `SimpleSpannerWriter<T>` that handles the case where `transform` is the identity function?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-Mhnt6TK-Rpc3vVTiC0Q:-Mhnt6TL8TCyuUNpFB6_:b1kgi94) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L52)):*
> ```Kotlin
> 
> private fun Statement.Builder.appendWhereClause(filter: StreamRequisitionsRequest.Filter) {
>   val conjuncts = mutableListOf<String>()
> ```

Maybe `conditions` would be a more natural name?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnvGlq9rsSPjct9lLS:-MhnvGlq9rsSPjct9lLT:b-ybp67q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L36)):*
> ```Kotlin
> 
> private val COMMON_SELECT_EXPRESSIONS =
>   listOf(
> ```

Since these always get joined together, I wonder if it would just be simpler to define them as a single string. There'd be a lot less syntax in the way and it'd be easier to verify that they become valid SQL. You could even tack on FROM_CLAUSE here so it's just one big constant.

Finally, I wonder if it's actually worth it to differentiate the cases. There's probably little harm in always selecting MeasurementDetails and it could simplify the code a bunch (which seems more important than saving a trivial amount of bandwidth).
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 145 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnvraKEon3mqtY86fZ:-MhnvraKEon3mqtY86f_:b7y4aco) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L145)):*
> ```Kotlin
>       fillRequisitionCommon(struct)
>       parentMeasurement =
>         parentMeasurement {
> ```

Maybe make a `buildParentMeasurement` helper too? It's nice when public methods have a really simple flow to follow
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 202 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnuBY-CqtP9k82fbGK:-MhnuBY-CqtP9k82fbGL:bes4v0x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L202)):*
> ```Kotlin
>       liquidLegionsV2 = participantDetails.liquidLegionsV2
>     }
>     ComputationParticipant.Details.ProtocolCase.PROTOCOL_NOT_SET -> Unit
> ```

Just confirming this isn't an error to have a missing protocol (can you add a comment saying why it's fine?)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnwZmm8dx7nAGFtD8n:-MhnwZmm8dx7nAGFtD8o:b-6bqtxg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L65)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> abstract class RequisitionsServiceTest<T : RequisitionsCoroutineService> {
> ```

OOC, why does this need generics? Can't it just operate on `RequisitionsCoroutineService` as a base class?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 79 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnwTbo5wz-Qve6vXKu:-MhnwTbs9PWMUs3Ojjsq:by0fxy5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L79)):*
> ```Kotlin
>   protected lateinit var dataServices: TestDataServices
>     private set
>   /** Subject under test (SUT). */
> ```

Whitespace above this please (and after newTestDataServices too, please)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnxLrg1s7V29_jB7R5:-MhnxLrg1s7V29_jB7R6:b8hf5p5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L156)):*
> ```Kotlin
>           }
>         for (dataProvider in dataProviders) {
>           this.dataProviders.put(
> ```

Kotlin DSL provides `dataProviders[key] = value`, right?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)* status: 10 of 17 files reviewed, 9 unresolved discussions (waiting on @efoxepstein and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnrthiCtR3QD3QUKhU:-MhoqOJuA-iiwAirPPyk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since Requisitions are kind of keyed by a bunch of things, it would help me to see the parameter names on this function call, at least for the last 3 parameters, to make sure no wires are crossed.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-Mha-wP93y9sgEiw3-ob:-MhooHnv2fZuBd5d5x1G:b-8g9dgl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ef54305c06aba5775b1bc0bd2add7dbf063e168a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is your proposal to just drop `Filters` totally? (I feel like we should be consistent one way or another, I don't care which way)
</blockquote></details>

Yes. I feel like the main usefulness was when we were trying to have an abstraction of the DB layer, so we needed a way to reason about filtering in a DB-agnostic way. With our more flattened structure, the multi-layered filter abstraction seems unnecessary.

We could perhaps extract *some* common functionality. Regardless, I'd want to replace the other uses of `Filters` in a separate PR.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnsNsq4NfLUWY31ihc:-MhoroWo2Sih0KLz4vEA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should we have `SimpleSpannerQuery<T>` like `SimpleSpannerWriter<T>` that handles the case where `transform` is the identity function?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-Mhnt6TK-Rpc3vVTiC0Q:-MhopGhI9UswnI3lk1wx:b-agamrg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe `conditions` would be a more natural name?
</blockquote></details>

I had used `conditions` initially, but I wanted to be clear that these are going to be ANDed. If you still would prefer that, I don't mind changing it.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnvGlq9rsSPjct9lLS:-Mhowt_p9JXyBjHo3BR-:b1ytut9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since these always get joined together, I wonder if it would just be simpler to define them as a single string. There'd be a lot less syntax in the way and it'd be easier to verify that they become valid SQL. You could even tack on FROM_CLAUSE here so it's just one big constant.

Finally, I wonder if it's actually worth it to differentiate the cases. There's probably little harm in always selecting MeasurementDetails and it could simplify the code a bunch (which seems more important than saving a trivial amount of bandwidth).
</blockquote></details>

Done, though note that if this amount of bandwidth is trivial then it's arguably simpler to drop the views entirely in this case. WDYT?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 145 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnvraKEon3mqtY86fZ:-Mhoy4o_1fr3dMrn1yC7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L145)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe make a `buildParentMeasurement` helper too? It's nice when public methods have a really simple flow to follow
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 202 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnuBY-CqtP9k82fbGK:-MhozU3n2xaf-ZSPbQ9B:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L202)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Just confirming this isn't an error to have a missing protocol (can you add a comment saying why it's fine?)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnwZmm8dx7nAGFtD8n:-MhozcqE3TuXqEOmXG__:b-52ai9c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

OOC, why does this need generics? Can't it just operate on `RequisitionsCoroutineService` as a base class?
</blockquote></details>

This way if we have any implementation-specific test cases in the subclass, the `service` property will have the appropriate implementation type.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 79 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnwTbo5wz-Qve6vXKu:-Mhp-rYu-kAE7zU4eWVF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L79)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Whitespace above this please (and after newTestDataServices too, please)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnxLrg1s7V29_jB7R5:-Mhp075YEiW-ukKowzgK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L156)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Kotlin DSL provides `dataProviders[key] = value`, right?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-Mha-wP93y9sgEiw3-ob:-Mhp1Csy4arQRFfKrRGs:b-hfghm4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ef54305c06aba5775b1bc0bd2add7dbf063e168a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes. I feel like the main usefulness was when we were trying to have an abstraction of the DB layer, so we needed a way to reason about filtering in a DB-agnostic way. With our more flattened structure, the multi-layered filter abstraction seems unnecessary.

We could perhaps extract *some* common functionality. Regardless, I'd want to replace the other uses of `Filters` in a separate PR.
</blockquote></details>

Sounds good
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-Mhnt6TK-Rpc3vVTiC0Q:-Mhp1EZrDukM1DPePE6e:b-c21idh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I had used `conditions` initially, but I wanted to be clear that these are going to be ANDed. If you still would prefer that, I don't mind changing it.
</blockquote></details>

I generally prefer a word over a non-word but I don't care a strongly.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnvGlq9rsSPjct9lLS:-Mhp1OS1E2bjhbbeYcRn:b-xkr1ci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Done, though note that if this amount of bandwidth is trivial then it's arguably simpler to drop the views entirely in this case. WDYT?
</blockquote></details>

If we care about bandwith, we probably don't want to wildcard-select on any table with a DetailsJson column.

I'd support dropping the views. We can optimize later -- for now, I prefer optimizing for simple code.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnwZmm8dx7nAGFtD8n:-Mhp1oeQ-COBE-wCeDcZ:b5pa595) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This way if we have any implementation-specific test cases in the subclass, the `service` property will have the appropriate implementation type.
</blockquote></details>

Do you have any implementation-specific test cases? (Is this YAGNI?) This comment isn't blocking so do whatever you prefer

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)* status: 11 of 19 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @SanjayVas, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnvGlq9rsSPjct9lLS:-MhpIT2ID9OcN4Th_VGy:b-kt1zny) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If we care about bandwith, we probably don't want to wildcard-select on any table with a DetailsJson column.

I'd support dropping the views. We can optimize later -- for now, I prefer optimizing for simple code.
</blockquote></details>

Dropped Requisition.View.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @zachcwc)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 7 of 14 files at r1, 3 of 7 files at r3, 1 of 1 files at r5, 7 of 8 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 428 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhpNPjo4Qz3LCp64hBU:-MhpNPjo4Qz3LCp64hBV:brb4os2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4d65771477e0de2c2e7690aa252afc9368713ad/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L428)):*
> ```
> API_VERSION = "v2alpha"
> ```

Should this have been defined as a const somewhere by now? Seems like a fairly basic one.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhnwZmm8dx7nAGFtD8n:-MhpOiJFC8E9eIn-GRGT:b-9nz8vi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do you have any implementation-specific test cases? (Is this YAGNI?) This comment isn't blocking so do whatever you prefer
</blockquote></details>

Weird, thought I had replied to this.

Not at the moment, but this is also not a significant amount of complexity.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 428 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-MhpNPjo4Qz3LCp64hBU:-MhpP2p0ChfqR2QXRJdR:bkjiyfc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4d65771477e0de2c2e7690aa252afc9368713ad/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L428)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> ```
> API_VERSION = "v2alpha"
> ```

Should this have been defined as a const somewhere by now? Seems like a fairly basic one.
</blockquote></details>

It wouldn't make as much sense to for this specific case. The internal services just pass through the API version that callers may use for serialization. It doesn't actually matter what string we specify here in the test, but I prefer to use values that are close to valid prod ones where practical.

I at least switched to referencing the Version enum.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)* status: 17 of 19 files reviewed, all discussions resolved (waiting on @corbantek, @efoxepstein, @oliver-amzn, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211#-Mhnt6TK-Rpc3vVTiC0Q:-MhsxsoC2UDXpVmMloeF:b-dgyrvl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd8b347c56ef1038b9157b58c09d9450c63ac508/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L52)):*
I think Reviewable lost some comments.

It is a word. From https://en.wikipedia.org/wiki/Logical_conjunction: 
> An operand of a conjunction is a **conjunct**.

See also https://www.merriam-webster.com/dictionary/conjunct

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 6 of 14 files at r1, 2 of 7 files at r3, 1 of 1 files at r5, 5 of 8 files at r6, 3 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)

**Comment by SanjayVas** [comment]
This is for #103.

**Pull request merged**
