### PR TITLE
Extract RoleInComputation and duchy NoiseMechanism out from LLv2 specific message.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1349)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @ple13)

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1349)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @renjiezh, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1349#-NkQwTdv4iIRmg8PHWbF:-NkQwTdv4iIRmg8PHWbG:bywwkvw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c5eae74457785ef60502c8d3e8aa3aee273755e/src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto#L35)):*
> ```proto
> enum RoleInComputation {
>   // Never set intentionally
>   UNKNOWN = 0;
> ```

ROLE_IN_COMPUTATION_UNSPECIFIED = 0 (https://google.aip.dev/126)



_Code quote:_
```proto
UNKNOWN = 0;
```

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1349)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1349)* status: 32 of 35 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1349#-NkQwTdv4iIRmg8PHWbF:-NkRPyUZ5ksvgazrAnHE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c5eae74457785ef60502c8d3e8aa3aee273755e/src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto#L35)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

ROLE_IN_COMPUTATION_UNSPECIFIED = 0 (https://google.aip.dev/126)
</blockquote></details>

Done.

**Review by ple13 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1349)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

**Review by ple13 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 35 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
