### PR TITLE
refactor: Use separate queries for each bigquery metrics table

### PR DESCRIPTION
**Pull request by tristanvuong2021**
refactor: Use separate queries for each bigquery metrics table

It will be easier to add additional tables this way. StreamRequisitions also had to be refactored to improve the performance to meet the rpc deadline.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 279 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O7_mj_c0KmCKAH93IoI:-O7_mj_c0KmCKAH93IoJ:b6rryki) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8f0e189c246987a0337285e39b2c3545d3c0d05d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L279)):*
> ```Kotlin
>   }
> 
>   private suspend fun exportRequisitions() {
> ```

It seems like there is a lot of copied code from the other function. Can they share some logic? For example, and this is just one example, the code that handles the Measurement Type Case.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 279 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O7_mj_c0KmCKAH93IoI:-O7a1dAtD5jyaH5xeCnd:b-xnnhms) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d7245fbc5376551843082615e922f1ffad4aeb1f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L279)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It seems like there is a lot of copied code from the other function. Can they share some logic? For example, and this is just one example, the code that handles the Measurement Type Case.
</blockquote></details>

The only part I could make shared is the Measurement Type part

**Review by kungfucraig — APPROVED** [review]
> Reviewed 12 of 16 files at r1, 3 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 16 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 16 files at r1, 1 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: 14 of 20 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt` line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O8DzPDJ1_YjbXgzqulY:-O8DzPDKDBRwAFWQCaTx:b8wawx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9d0633b2db89d94e9c2b9114610995f725b36b6e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L24)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.readers.RequisitionReader
> 
> class StreamRequisitions(request: StreamRequisitionsRequest) :
> ```

Move these changes to a separate PR. We'll want them regardless of what happens with metrics export.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 16 files at r1, 2 of 3 files at r4, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: 16 of 20 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt` line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O8DzPDJ1_YjbXgzqulY:-O8hsJ9HCgLLyQPH1n49:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9d0633b2db89d94e9c2b9114610995f725b36b6e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move these changes to a separate PR. We'll want them regardless of what happens with metrics export.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1, 2 of 3 files at r4, 1 of 7 files at r6, 4 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 39 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O8mut0s7YgcbE8p_pQR:-O8mut0s7YgcbE8p_pQS:b-4xz015) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37486cb100ff15ac5df8b07e5119278d8b03efce/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L39)):*
> ```proto
>     // ComputationParticipants.
>     COMPUTATION = 1;
> ```

These changes to the Kingdom internal API should also be in a separate PR.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: 11 of 20 files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 39 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O8mut0s7YgcbE8p_pQR:-O8nTrJo6nWkAi16SShe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a1476e8f6507667fe7337785fdf217deafd2369/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These changes to the Kingdom internal API should also be in a separate PR.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 16 files at r1, 2 of 6 files at r7, 6 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: 19 of 20 files reviewed, 5 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 153 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O8rqZGBBOY5xw2JE8wS:-O8rqZGBBOY5xw2JE8wT:b-tr3ksi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dad7005fe7fc0d305524f7573c14e9b7574b486a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L153)):*
> ```Kotlin
>               var latestUpdateTime: Timestamp = Timestamp.getDefaultInstance()
> 
>               measurementsClient.streamMeasurements(streamMeasurementsRequest).collect { measurement
> ```

All gRPC stub calls must handle StatusException at the call site.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 172 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O8rpHan1jdaHoLcn4h5:-O8rpHao9EjHwPbSlwBC:b-kw53yq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dad7005fe7fc0d305524f7573c14e9b7574b486a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L172)):*
> ```Kotlin
>                     .toInstant()
>                     .minusSeconds(measurement.createTime.toInstant().epochSecond)
>                     .epochSecond
> ```

This is getting the seconds since epoch for the Instant that happens X seconds before, rather than getting the Duration between the two Instants in seconds. The math may come out the same, but it's not describing what you actually want.



_Suggestion:_
```Kotlin
                  Duration.between(measurement.createTime.toInstant(), measurement.updateTime.toInstant()).toSeconds()
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 429 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O8s2RfN274Sq5l_Ch0k:-O8s2RfN274Sq5l_Ch0l:bkpo054) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dad7005fe7fc0d305524f7573c14e9b7574b486a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L429)):*
> ```Kotlin
>       apiVersion: String,
>     ): MeasurementType {
>       val measurementSpec = signedMessage {
> ```

Why do you need to build a SignedMessage then unpack it? Just the following should be sufficient

```kotlin
require(Version.fromString(apiVersion) == Version.V2_ALPHA)

val measurementSpec = MeasurementSpec.parseFrom(serializedMeasurementSpec)
return when (measurementSpec.measurementTypeCase) {
  // ...
}
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 39 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O8mut0s7YgcbE8p_pQR:-O8s4KFJ-OrfIsjMEKpA:bsreey2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a1476e8f6507667fe7337785fdf217deafd2369/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L39)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm still seeing diffs here in this PR.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: 16 of 20 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 153 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O8rqZGBBOY5xw2JE8wS:-O8sMnLeDCb2ij301uZX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dad7005fe7fc0d305524f7573c14e9b7574b486a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L153)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

All gRPC stub calls must handle StatusException at the call site.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 172 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O8rpHan1jdaHoLcn4h5:-O8sEZ1q1sZtNYO7fzdV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dad7005fe7fc0d305524f7573c14e9b7574b486a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L172)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is getting the seconds since epoch for the Instant that happens X seconds before, rather than getting the Duration between the two Instants in seconds. The math may come out the same, but it's not describing what you actually want.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 429 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O8s2RfN274Sq5l_Ch0k:-O8sFjsi5o1djrpSG-kU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dad7005fe7fc0d305524f7573c14e9b7574b486a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L429)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why do you need to build a SignedMessage then unpack it? Just the following should be sufficient

```kotlin
require(Version.fromString(apiVersion) == Version.V2_ALPHA)

val measurementSpec = MeasurementSpec.parseFrom(serializedMeasurementSpec)
return when (measurementSpec.measurementTypeCase) {
  // ...
}
```
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 39 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823#-O8mut0s7YgcbE8p_pQR:-O8sMmNi07VvoNPS1q91:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a1476e8f6507667fe7337785fdf217deafd2369/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm still seeing diffs here in this PR.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 6 files at r7, 3 of 7 files at r8, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1823)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
