### PR TITLE
Add detailed logging for model release and suite service

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1551)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1551#-NuVaEsF1aAOqP1uMWyz:-NuVaEsF1aAOqP1uMWz-:bx9lnok) (no related file):*
You may want a separate PR to go back over and swap all the metadata keys in the public API to lowerCamelCase. From [AIP-193](https://google.aip.dev/193#dynamic-variables):

> Keys **must** be expressed as lower camel-case.

___

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1551)* status: 4 of 18 files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1551#-NuVaEsF1aAOqP1uMWyz:-Nvde_J19QO6Wxn8aUIh:bd7mgno) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You may want a separate PR to go back over and swap all the metadata keys in the public API to lowerCamelCase. From [AIP-193](https://google.aip.dev/193#dynamic-variables):

> Keys **must** be expressed as lower camel-case.
</blockquote></details>

Done. (Added TODO)

___

**Review by SanjayVas — APPROVED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1551)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 4 of 13 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1551)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by jcorilla — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1551#-:-Nvk_Z_sBtuwSdwN7LuZ:bnfp4nl)* status: 17 of 18 files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)

**Review by jcorilla — COMMENTED** [review]
> Reviewed 4 of 13 files at r1, 10 of 14 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1551)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
