### PR TITLE
style: Address lint errors.

### PR DESCRIPTION
**Pull request by kungfucraig**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
Thanks!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972#-:-OEGwM1J-e_jaxUaAPR8:b-ucfknh)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972#-OEGvpeQ8xuVk_ztaPer:-OEGvpeR3qAOF6tgyz5L:b-tz0ffz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08944e4c0c89cc578340dbdd1bb9fe4cea5ca53c/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L40)):*
> ```proto
>   string name = 1 [
>     (google.api.field_behavior) = IDENTIFIER,
>     (google.api.field_behavior) = IMMUTABLE
> ```

Just IDENTIFIER for the `name` field. It implies a subtly different definition of immutability than IMMUTABLE. See https://google.aip.dev/203#identifier
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_sets_service.proto` line 115 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972#-OEGwJuRC514CwJOpXId:-OEGwJuRC514CwJOpXIe:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08944e4c0c89cc578340dbdd1bb9fe4cea5ca53c/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_sets_service.proto#L115)):*
> ```proto
> }
> 
> // Request message for 'GetReportingSetRequeest' method.
> ```





_Suggestion:_
```proto
GetReportingSet
```

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972#-OEGvpeQ8xuVk_ztaPer:-OEPZ2x6-APw4oSI7KNY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08944e4c0c89cc578340dbdd1bb9fe4cea5ca53c/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just IDENTIFIER for the `name` field. It implies a subtly different definition of immutability than IMMUTABLE. See https://google.aip.dev/203#identifier
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_sets_service.proto` line 115 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972#-OEGwJuRC514CwJOpXId:-OEPZDq42mRAUjIDl2Yi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08944e4c0c89cc578340dbdd1bb9fe4cea5ca53c/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_sets_service.proto#L115)):*
> ```proto
> }
> 
> // Request message for 'GetReportingSetRequeest' method.
> ```

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_sets_service.proto` line 115 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972#-OEGwJuRC514CwJOpXId:-OEQcwtG6qdTOjbxkQ0r:byd9oe7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08944e4c0c89cc578340dbdd1bb9fe4cea5ca53c/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_sets_service.proto#L115)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not quite. You have 

```proto
// Request message for 'GetReportingSetRequest' method.
```

instead of 

```proto
// Request message for `GetReportingSet` method.
```

The method name is incorrect and the comment is using single quotes instead of backticks for the symbol.

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_sets_service.proto` line 115 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972#-OEGwJuRC514CwJOpXId:-OEQweXaEI4mFTpx1F1L:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08944e4c0c89cc578340dbdd1bb9fe4cea5ca53c/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_sets_service.proto#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not quite. You have 

```proto
// Request message for 'GetReportingSetRequest' method.
```

instead of 

```proto
// Request message for `GetReportingSet` method.
```

The method name is incorrect and the comment is using single quotes instead of backticks for the symbol.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 7 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1972)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Pull request merged**
