### PR TITLE
Add API key for SimpleReport

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/594)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/594)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 614 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/594#-N4-5gdG65-KMZS9ulYf:-N4-5gdG65-KMZS9ulYg:b-39m53i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db65f1d2269c77067a47e425ab3b341f27097876/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L614)):*
> ```Kotlin
>     description =
>       [
>         "Expected hostname (DNS-ID) in the Kingdom public API server's TLS certificate.",
> ```

Incorrect description.



_Code quote:_
```Kotlin
        "Expected hostname (DNS-ID) in the Kingdom public API server's TLS certificate.",
        "This overrides derivation of the TLS DNS-ID from --kingdom-public-api-target.",
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/594)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 614 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/594#-N4-5gdG65-KMZS9ulYf:-N4-8H9P14p66WZN2-ka:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db65f1d2269c77067a47e425ab3b341f27097876/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L614)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Incorrect description.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/594)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/594)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 9 of 12 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/594)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
