### PR TITLE
feat: Define internal Access API

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1907)

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 5 of 12 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1907)* status: 9 of 12 files reviewed, all discussions resolved

**Review by kungfucraig — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1907)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Comment by SanjayVas** [comment]
Depends on #1662

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 12 files at r1, 3 of 6 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1907)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/access/roles_service.proto` line 62 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1907#-OCdXKY4-41Ipzqb5uFW:-OCdXKY4-41Ipzqb5uFX:b-ze2a0s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9112779bb4a0a3b457ce53513c7448f40c8b9a5a/src/main/proto/wfa/measurement/internal/access/roles_service.proto#L62)):*
> ```proto
>   //
>   // If not specified, there are no more results.
>   ListRolesPageToken next_page_token = 2;
> ```

why is the page token done this way?
___
*[`src/main/proto/wfa/measurement/internal/access/principal.proto` line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1907#-OCdW4bI-0UGGfelH2C2:-OCdW4bI-0UGGfelH2C3:b-a1yim6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9112779bb4a0a3b457ce53513c7448f40c8b9a5a/src/main/proto/wfa/measurement/internal/access/principal.proto#L28)):*
> ```proto
>   string principal_resource_id = 1;
> 
>   message User {
> ```

OAuthUser?

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1907)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/access/roles_service.proto` line 62 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1907#-OCdXKY4-41Ipzqb5uFW:-OCd_2Lp4zWvnCEenwSU:b4is8hg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9112779bb4a0a3b457ce53513c7448f40c8b9a5a/src/main/proto/wfa/measurement/internal/access/roles_service.proto#L62)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why is the page token done this way?
</blockquote></details>

oh - nvm - this is internal

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1907)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1907)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @stevenwarejones)

**Pull request merged**
