### PR TITLE
Add Internal Exchange Workflow proto

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @yunyeng)

___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174#-Mg6t1au-PbX_2L0yTM5:-Mg6t1au-PbX_2L0yTM6:b-wyeq02) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9bd894be9ba45132b0185c9a4524a3fd27cf108/src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto#L37)):*
> ```protobuf
> 
>     // Each step may or may not expect some prerequisite steps to be finished.
>     repeated int32 prerequisite_ids = 3;
> ```

shouldn't this be a repeated `exchangeStepKey`?

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174#-Mg6t1au-PbX_2L0yTM5:-Mg6tITV42hlqnmdMDKB:b-m1s8nr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9bd894be9ba45132b0185c9a4524a3fd27cf108/src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't this be a repeated `exchangeStepKey`?
</blockquote></details>

Since this is an internal proto, we don't want to refer to API resources. This is also the analog of ExchangeWorkflow.Step, not Exchange/ExchangeStep/ExchangeStepAttempt.

Internally (in the database), the steps are just keyed by their index in an ExchangeWorkflow.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174#-Mg6t1au-PbX_2L0yTM5:-Mg6x7t72BrehEg3Q-wX:b-iabvtk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9bd894be9ba45132b0185c9a4524a3fd27cf108/src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since this is an internal proto, we don't want to refer to API resources. This is also the analog of ExchangeWorkflow.Step, not Exchange/ExchangeStep/ExchangeStepAttempt.

Internally (in the database), the steps are just keyed by their index in an ExchangeWorkflow.
</blockquote></details>

wouldn't it be better to have an internal proto that holds this value then?

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174#-Mg6t1au-PbX_2L0yTM5:-Mg6xqs5-zhb1_zReJKK:bfi6cdb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9bd894be9ba45132b0185c9a4524a3fd27cf108/src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

wouldn't it be better to have an internal proto that holds this value then?
</blockquote></details>

This is the internal proto? I guess I don't understand what you're asking

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174#-Mg6t1au-PbX_2L0yTM5:-Mg6zbMmDMTlhEcGe4Ir:bdc8tsy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9bd894be9ba45132b0185c9a4524a3fd27cf108/src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is the internal proto? I guess I don't understand what you're asking
</blockquote></details>

looking through the rest of the code, it looks like its all hard-coded to int32. I was thinking that maybe it could be its own message type which contained a int32. But I'm fine as is. 

However, wouldn't a better name be `prerequisiste_step_indices`?

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174#-Mg6t1au-PbX_2L0yTM5:-Mg7-MxX0HzJX1moY5GX:b1x6mph) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9bd894be9ba45132b0185c9a4524a3fd27cf108/src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

looking through the rest of the code, it looks like its all hard-coded to int32. I was thinking that maybe it could be its own message type which contained a int32. But I'm fine as is. 

However, wouldn't a better name be `prerequisiste_step_indices`?
</blockquote></details>

+1 -- agreed that's a better name!

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174#-Mg6t1au-PbX_2L0yTM5:-Mg7734o42c9FqpWarnq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9bd894be9ba45132b0185c9a4524a3fd27cf108/src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

+1 -- agreed that's a better name!
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @stevenwarejones)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174#-Mg6t1au-PbX_2L0yTM5:-Mg7AuF259QzNsXi1Hfl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9bd894be9ba45132b0185c9a4524a3fd27cf108/src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto#L37)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
