### PR TITLE
Update the cue config for the EdpSimulator.

### PR DESCRIPTION
**Pull request by wangyaopw**
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F607228901955&view=2c2927c0-626b-4740-8620-af2a93b7d623

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/265)

### CODE REVIEW

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/265)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
nit: perhaps a description that better covers the salient change here. Less of this seems to do with the CUE config and more with the changing the flags. Updating the CUE file to match those flags is just incidental to ensure submitting unbroken code.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/265#-:-MjBUiRB3mXN089t2d42:b-e7kcbi)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/265#-MjBRYoCA8WTRm1whX5h:-MjBRYoCA8WTRm1whX5i:b-xm0kjz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/745f46d22ddaa048d833a1e84b84e0469b614236/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L70)):*
> ```
> eventGroup
> ```
nit: `eventGroups`
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/265#-MjBRiOr83PzUeiE2kjS:-MjBRiOr83PzUeiE2kjT:b-5eu1oi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/745f46d22ddaa048d833a1e84b84e0469b614236/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L72)):*
> ```
> certificateService
> ```
nit: `certificates`

**Review by wangyaopw — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/265#-:-MjGQw2n1SApwwOHrw71:bb7f2mf)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/265#-MjBRYoCA8WTRm1whX5h:-MjGQdZB5wCNsyED9cE0:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/745f46d22ddaa048d833a1e84b84e0469b614236/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> eventGroup
> ```
nit: `eventGroups`
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/265#-MjBRiOr83PzUeiE2kjS:-MjGQe3S1v0RKNHoOYuv:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/745f46d22ddaa048d833a1e84b84e0469b614236/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> certificateService
> ```
nit: `certificates`
</blockquote></details>

Done

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/265)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
