### PR TITLE
Implement system API computationsService.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125)* status: all files reviewed, 10 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, line 287 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md3ee_gEvRklbUgVY43:-Md3ee_gEvRklbUgVY44:b-jf2zz3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L287)):*
> ```
> String.toExternalDataProviderId
> ```
Similar note here on conversion functions with a String receiver. Additionally, should only define a conversion (`to`) function if it converts the whole thing, rather than extracting a part. It just happens to be that v2alpha DataProvider resource names only have a single ID segment.

Maybe extractDataProviderId(publicApiVersion, resourceName)?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt, line 69 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md40gfmBcMfycS_YjXo:-Md40gfmBcMfycS_YjXp:b-8y8rmu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/80f4c2e83d94a39f9c8a41635ea8a7754f2c7a51/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt#L69)):*
> ```
> reconnect = Duration.ofHours(1), reconnectDelay = Duration.ofSeconds(1)
> ```
Read these from flags.
___
*[src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4-6t2A07t_qeun_QN:-Md4-6t2A07t_qeun_QO:bmiwe8i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L66)):*
> ```
> api_version
> ```
Why is this needed? I thought the ComputationParticipant in the system API is always obtained via the repeated output-only field in the parent Computation, which should have the API version.
___
*[src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md3zxIO62v-6MxtaHa1:-Md3zxIP734BgOMPVynE:bw3tcr0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/internal/kingdom/requisition.proto#L96)):*
> ```
>     // Version of the public API for serialized message definitions.
>     string api_version = 1;
> ```
Don't include this field in Details, since that message is intended for serialization. Have this as a top-level field instead, and document that it's denormalized from the parent Measurement.
___
*[src/main/proto/wfa/measurement/system/v1alpha/computation.proto, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4-ei032IfNRBFc-vs:-Md4-ei032IfNRBFc-vt:b-lunvpp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L50)):*
> ```protobuf
> 
>   // Resource name of `ProtocolConfig` from the public API.
>   string protocol_config = 6;
> ```

All resource name references should have a resource reference annotation.
___
*[src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4-pxi8hLrK9iubYC_:-Md4-pxi8hLrK9iubYCa:b-lunvpp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto#L66)):*
> ```protobuf
>   message RequisitionParams {
>     // Public API Resource name of the `DuchyCertificate`.
>     string duchy_certificate_name = 1;
> ```

All resource name references should have a resource reference annotation.
___
*[src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md401BH4SVlE_j_dw44:-Md401BH4SVlE_j_dw45:b-xfa5i1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto#L66)):*
> ```
> duchy_certificate_name
> ```
Drop the `_name` suffix.
___
*[src/main/proto/wfa/measurement/system/v1alpha/requisition.proto, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4-r_SBpt-Kg-BD63e:-Md4-r_SBpt-Kg-BD63f:b-lunvpp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/system/v1alpha/requisition.proto#L36)):*
> ```protobuf
>   // Public API Resource name of the `DataProvider` who should fulfill this
>   // requisition. Required. Immutable.
>   string data_provider = 2;
> ```

All resource name references should have a resource reference annotation.
___
*[src/main/kotlin/org/wfanet/measurement/api/PublicApiVersion.kt, line 14 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md3cnAa1jpwGRGTdn1v:-Md3cnAa1jpwGRGTdn1w:b-jg6dyi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/kotlin/org/wfanet/measurement/api/PublicApiVersion.kt#L14)):*
> ```Kotlin
> // See the License for the specific language governing permissions and
> // limitations under the License.
> ```

FYI I was also working on something like this. Here's what I had:

```
package org.wfanet.measurement.api

enum class Version(val string: String) {
  VERSION_UNSPECIFIED(""),
  V2_ALPHA("v2alpha");

  override fun toString(): String = string

  companion object {
    fun fromString(string: String): Version {
      return values().find { it.string == string } ?: VERSION_UNSPECIFIED
    }
  }
}
```
___
*[src/main/kotlin/org/wfanet/measurement/api/PublicApiVersion.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md3_l9GE1jjlQ57Em9v:-Md3_l9GE1jjlQ57Em9w:b-jrafr6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/kotlin/org/wfanet/measurement/api/PublicApiVersion.kt#L17)):*
> ```
> in the duchy
> ```
No longer accurate. Since this is in a common location, it should cover all API versions and code that uses it needs to check if it's a supported version.
___
*[src/main/kotlin/org/wfanet/measurement/api/PublicApiVersion.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md3bDoQEjOE6L_moYHK:-Md3bDoQEjOE6L_moYHL:bgwk6gv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/kotlin/org/wfanet/measurement/api/PublicApiVersion.kt#L23)):*
> ```
> String.toPublicApiVersion
> ```
I know we have these littered throughout the codebase, but I don't like these kinds of conversion extension methods on String. They don't have a name for the receiver parameter, so it's unclear what the input string needs to be. They also blow up the autocomplete list for String.

I prefer `from...` factory functions in the companion object.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125)* status: all files reviewed, 10 unresolved discussions (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, line 287 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md3ee_gEvRklbUgVY43:-Md45VD0ELwwpfTTzjec:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L287)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> String.toExternalDataProviderId
> ```
Similar note here on conversion functions with a String receiver. Additionally, should only define a conversion (`to`) function if it converts the whole thing, rather than extracting a part. It just happens to be that v2alpha DataProvider resource names only have a single ID segment.

Maybe extractDataProviderId(publicApiVersion, resourceName)?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt, line 69 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md40gfmBcMfycS_YjXo:-Md49Ky46kvzEBkx6Sjx:bvye3kt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/80f4c2e83d94a39f9c8a41635ea8a7754f2c7a51/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> reconnect = Duration.ofHours(1), reconnectDelay = Duration.ofSeconds(1)
> ```
Read these from flags.
</blockquote></details>

Moved as the parameter of the service constructor. The server will get the values from flags. 
___
*[src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4-6t2A07t_qeun_QN:-Md46S0dCslC2ZTUT5t5:b3azy4q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> api_version
> ```
Why is this needed? I thought the ComputationParticipant in the system API is always obtained via the repeated output-only field in the parent Computation, which should have the API version.
</blockquote></details>

Yep, you are correct. Removed.
___
*[src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md3zxIO62v-6MxtaHa1:-Md46ynb9E8_hBVnCe-2:b5acbxr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/internal/kingdom/requisition.proto#L96)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     // Version of the public API for serialized message definitions.
>     string api_version = 1;
> ```
Don't include this field in Details, since that message is intended for serialization. Have this as a top-level field instead, and document that it's denormalized from the parent Measurement.
</blockquote></details>

We do have serialized proto messages inside the Details. Isn't version also useful for deserializing them?
___
*[src/main/proto/wfa/measurement/system/v1alpha/computation.proto, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4-ei032IfNRBFc-vs:-Md48-WU60CFtW0X6au9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

All resource name references should have a resource reference annotation.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4-pxi8hLrK9iubYC_:-Md48EB2AxdVcmO-RZ28:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

All resource name references should have a resource reference annotation.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md401BH4SVlE_j_dw44:-Md48Ei74QzIuL02_pQZ:b-cyrb1c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> duchy_certificate_name
> ```
Drop the `_name` suffix.
</blockquote></details>

there is already a duchy_certificate field here. Renaming that one to duchy_certificate_der?
___
*[src/main/proto/wfa/measurement/system/v1alpha/requisition.proto, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4-r_SBpt-Kg-BD63e:-Md48c0X8xItE24JUJxG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/system/v1alpha/requisition.proto#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

All resource name references should have a resource reference annotation.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/PublicApiVersion.kt, line 14 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md3cnAa1jpwGRGTdn1v:-Md43p-j6k6khjMmFndc:b-px95sz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/kotlin/org/wfanet/measurement/api/PublicApiVersion.kt#L14)):*
> enum class Version(val string: String) {
>   VERSION_UNSPECIFIED(""),
>   V2_ALPHA("v2alpha");
> 
>   override fun toString(): String = string
> 
>   companion object {
>     fun fromString(string: String): Version {
>       return values().find { it.string == string } ?: VERSION_UNSPECIFIED
>     }
>   }
> }
Done
___
*[src/main/kotlin/org/wfanet/measurement/api/PublicApiVersion.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md3_l9GE1jjlQ57Em9v:-Md43ruA7_ZWqkv32PT9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/kotlin/org/wfanet/measurement/api/PublicApiVersion.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> in the duchy
> ```
No longer accurate. Since this is in a common location, it should cover all API versions and code that uses it needs to check if it's a supported version.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/PublicApiVersion.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md3bDoQEjOE6L_moYHK:-Md43uL87XM24BVFAMAd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/kotlin/org/wfanet/measurement/api/PublicApiVersion.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> String.toPublicApiVersion
> ```
I know we have these littered throughout the codebase, but I don't like these kinds of conversion extension methods on String. They don't have a name for the receiver parameter, so it's unclear what the input string needs to be. They also blow up the autocomplete list for String.

I prefer `from...` factory functions in the companion object.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 74 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4gPOx9EsiK7O316UU:-Md4gPOx9EsiK7O316UV:bn4ixfw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27b85ece9892e51beb6527db7b9b1ea6d51704ed/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L74)):*
> ```
> Version.fromString(systemComputation.publicApiVersion)
> ```
If you want, you could add an `apiVersion` extension property to Computation that handles this conversion.
___
*[src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md3zxIO62v-6MxtaHa1:-Md4goWw7DmB3idHvyiL:bsm12x9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/internal/kingdom/requisition.proto#L96)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

We do have serialized proto messages inside the Details. Isn't version also useful for deserializing them?
</blockquote></details>

What I mean is that the `Details` message itself is meant to be serialized into the DB row, so putting the `api_version` here would mean that we'd be forced to store a duplicate value in the Requisition row rather than reading it from the parent Measurement row.

We could still decide to denormalize it in the DB row as well, but putting it in the `Details` message forces us to do so.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 74 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4gPOx9EsiK7O316UU:-MdIdpUM59Jwdx8Uc_cV:b-ple952) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27b85ece9892e51beb6527db7b9b1ea6d51704ed/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L74)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Version.fromString(systemComputation.publicApiVersion)
> ```
If you want, you could add an `apiVersion` extension property to Computation that handles this conversion.
</blockquote></details>

FYI, I'll have to add the api_version back to the internal ComputationParticipant proto. Since all the methods in the system computationParticipant service return a standalone ComputationParticipant object, which has no parent computation with it.

However, if we modify all those none-getXXX() methods to return an empty response, we don't need to add the api_version field to either the Requisition or ComputationParticipant messages. Those returned requisition and computationParticipant are not consumed by the caller anyway

WDYT?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 74 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4gPOx9EsiK7O316UU:-MdJ4B715H3C-HPWPeXj:bcuxu9f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27b85ece9892e51beb6527db7b9b1ea6d51704ed/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L74)):*
>I'll have to add the api_version back to the internal ComputationParticipant proto. Since all the methods in the system computationParticipant service return a standalone ComputationParticipant object, which has no parent computation with it.

This isn't actually true. You don't need to add these fields just because the messages can be returned on their own. We're adding them as-needed for cases where it would be inconvenient to have to do an extra call to get the API version from the parent.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 74 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4gPOx9EsiK7O316UU:-MdJ63NM9I4mzuOCxrLm:b-xspf4a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27b85ece9892e51beb6527db7b9b1ea6d51704ed/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L74)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

>I'll have to add the api_version back to the internal ComputationParticipant proto. Since all the methods in the system computationParticipant service return a standalone ComputationParticipant object, which has no parent computation with it.

This isn't actually true. You don't need to add these fields just because the messages can be returned on their own. We're adding them as-needed for cases where it would be inconvenient to have to do an extra call to get the API version from the parent.
</blockquote></details>

converting from the internal ComputationParticipant to the system ComputationParticipant needs the API version due to the duchy_certificate field. so in order to return a system ComputationParticipant back to duchy, we either need to add the api-verison to the internal ComputationParticipant or simply don't return a system ComputationParticipant at all

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 74 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4gPOx9EsiK7O316UU:-MdJTAXw78DuLX0D9SOS:bbfg0lr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27b85ece9892e51beb6527db7b9b1ea6d51704ed/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L74)):*
> converting from the internal ComputationParticipant to the system ComputationParticipant needs the API version due to the duchy_certificate field.

Ah, so we can construct the resource name. I lean towards adding the output-only field that we read from the parent row. The [AIPs indicate](https://google.aip.dev/216) that the response message of a state transition method **should** be the resource itself, but if it's really a pain and we don't use it then I suppose I can deal with dropping it.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125)* status: 23 of 27 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 74 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md4gPOx9EsiK7O316UU:-MdJgX4H6wI_BicoIGXu:b-389dwm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27b85ece9892e51beb6527db7b9b1ea6d51704ed/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L74)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> converting from the internal ComputationParticipant to the system ComputationParticipant needs the API version due to the duchy_certificate field.

Ah, so we can construct the resource name. I lean towards adding the output-only field that we read from the parent row. The [AIPs indicate](https://google.aip.dev/216) that the response message of a state transition method **should** be the resource itself, but if it's really a pain and we don't use it then I suppose I can deal with dropping it.
</blockquote></details>

Not really a pain. Added api_version to internal computationParticipant and Requisition.
___
*[src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125#-Md3zxIO62v-6MxtaHa1:-MdJgThIDzQHcErG4a-N:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8819f03f3429469729de3c9a96e9ee0e647ff754/src/main/proto/wfa/measurement/internal/kingdom/requisition.proto#L96)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What I mean is that the `Details` message itself is meant to be serialized into the DB row, so putting the `api_version` here would mean that we'd be forced to store a duplicate value in the Requisition row rather than reading it from the parent Measurement row.

We could still decide to denormalize it in the DB row as well, but putting it in the `Details` message forces us to do so.
</blockquote></details>

Done

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 12 of 26 files at r1, 11 of 15 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
