### PR TITLE
Add additional filter to MetricCalculationSpec

### PR DESCRIPTION
**Pull request by riemanli**
An addition filter was added to `MetricCalculationSpec` in #1250.  This PR further added the filter to `MetricCalculationResult` and implements the API changes.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1283)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1283** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1283" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1283?utm_source=stack-comment).

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1283)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report.proto` line 56 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1283#-NgUiKevAfYBIbblO_5f:-NgUiKevAfYBIbblO_5g:bgibftw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d559efb1685ea2e3c7b287a9c8423b8f3a83c0ab/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto#L56)):*
> ```proto
>       MetricSpec metric_spec = 2;
>       google.type.Interval time_interval = 3;
>       repeated string grouping_predicates = 4;
> ```

nit: You don't need any new tests, but you should set these new fields in the details in the test class just in case.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1283)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report.proto` line 56 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1283#-NgUiKevAfYBIbblO_5f:-NgV-37s2IrhsM8AKXzx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d559efb1685ea2e3c7b287a9c8423b8f3a83c0ab/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto#L56)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

nit: You don't need any new tests, but you should set these new fields in the details in the test class just in case.
</blockquote></details>

Done.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 3 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Pull request merged**
