### PR TITLE
Implement internal Metrics Service Create Methods for Reporting V2.

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982)

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 2 of 4 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982)* status: 11 of 12 files reviewed, 6 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt` line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982#-NV0mk9L9fi0k3s0Z46E:-NV0mk9L9fi0k3s0Z46F:bz4no5r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f37b190f202ad3d03e049c43dd9b95acf7da1d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt#L48)):*
> ```Kotlin
>       "Metric Spec missing type."
>     }
> ```

I wonder if there is any particular reason that we only check metric type. Should we check other fields as well?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 35 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982#-NV0nOvS2-0wEhGnzg1q:-NV0nOvS2-0wEhGnzg1r:b-yvxm5x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f37b190f202ad3d03e049c43dd9b95acf7da1d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L35)):*
> ```Kotlin
>   suspend fun readMetricsByRequestId(
>     measurementConsumerId: InternalId,
>     createMetricRequestIds: Collection<String>
> ```

Should this be `readMetricRequestIds`?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetric.kt` line 223 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982#-NV1aiKBBrgR3pDoRMAH:-NV1aiKBBrgR3pDoRMAI:b-ktov55) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f37b190f202ad3d03e049c43dd9b95acf7da1d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetric.kt#L223)):*
> ```Kotlin
>                 weightedMeasurements.clear()
>                 weightedMeasurements.addAll(weightedMeasurementsAndBindings.weightedMeasurements)
>               }
> ```

Should we add create time here?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt` line 121 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982#-NV1czsF-prHKN_rzh1I:-NV1czsF-prHKN_rzh1J:b-9rqore) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f37b190f202ad3d03e049c43dd9b95acf7da1d1/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt#L121)):*
> ```Kotlin
>           MetricSpecKt.vidSamplingInterval {
>             start = 1.0f
>             width = 2.0f
> ```

nit: 0 <= start < 1.0 and 0 < start + width <= 1.0 in the real implementation.



_Code quote:_
```Kotlin
            start = 1.0f
            width = 2.0f
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt` line 145 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982#-NV1dxIA9jORtnbDZl_3:-NV1dxIA9jORtnbDZl_4:b-bznwtr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f37b190f202ad3d03e049c43dd9b95acf7da1d1/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt#L145)):*
> ```Kotlin
>                 filters += "filter2"
>               }
>             state = Measurement.State.PENDING
> ```

nit: measurement should not have state before the metric is created.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt` line 169 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982#-NV1e7-E1g_KEus65HZK:-NV1e7-E1g_KEus65HZL:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f37b190f202ad3d03e049c43dd9b95acf7da1d1/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt#L169)):*
> ```Kotlin
>                 filters += "filter2"
>               }
>             state = Measurement.State.PENDING
> ```

ditto

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 35 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982#-NV0nOvS2-0wEhGnzg1q:-NV5Hf8lBEm3Tm8_WiLM:b-6dz1h6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab33d401159871274e935a8268aa1f800da86229/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L35)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Should this be `readMetricRequestIds`?
</blockquote></details>

I need to read the metrics to return them if they exist.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetric.kt` line 223 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982#-NV1aiKBBrgR3pDoRMAH:-NV5IDFe4Rnr-OWB4MkS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab33d401159871274e935a8268aa1f800da86229/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetric.kt#L223)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Should we add create time here?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt` line 169 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982#-NV1e7-E1g_KEus65HZK:-NV5Jdon5lkSLgMAlGZL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab33d401159871274e935a8268aa1f800da86229/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt#L169)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt` line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982#-NV0mk9L9fi0k3s0Z46E:-NVASP_i2HjtqsI9AYJ0:b-kch3nh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab33d401159871274e935a8268aa1f800da86229/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt#L48)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I wonder if there is any particular reason that we only check metric type. Should we check other fields as well?
</blockquote></details>

Added checks for additional fields.

**Review by riemanli — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 1 of 4 files at r2, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/982)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
