### PR TITLE
Add k8s manifests for AWS worker2 duchy

### PR DESCRIPTION
**Pull request by YuhongWang-Amazon**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239)* status: all files reviewed, 6 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`build/variables.bzl` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-Neu6yVg5ia7ux4cW_ZI:-Neu6yVh8R6Yx92mbjmw:bldllqo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858313c9d53b68f8a1c1b8ea0a26ac92ac4a9bd1/build/variables.bzl#L66)):*
> ```Starlark
>     postgres_host = "$(postgres_host)",
>     postgres_port = "$(postgres_port)",
>     postgres_credential_secret_name = "$(postgres_credential_secret_name)",
> ```

The secret names are in this config for legacy reasons before we started using Kustomize. We took it in as a param since we didn't know what the hash appended to the name would be.
___
*[`src/main/k8s/postgres.cue` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-Neu7Op7A3v6gnusCieu:-Neu7Op7A3v6gnusCiev:b-uk8oq5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858313c9d53b68f8a1c1b8ea0a26ac92ac4a9bd1/src/main/k8s/postgres.cue#L60)):*
> ```CUE
> }
> 
> #AwsPostgresConfig: {
> ```

1. Embed `#CommonPostgresConfig` and update `#PostgresConfig` to include `#AwsPostgresConfig` in the disjunction
2. Don't specify the tags here. Do that in the appropriate config.cue file.
___
*[`src/main/k8s/dev/BUILD.bazel` line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-NeuBRCEExjrn3NYYes0:-NeuBRCEExjrn3NYYes1:b-yfat65) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cceea41f671d90f3332ada971910c86e0f7fa63/src/main/k8s/dev/BUILD.bazel#L143)):*
> ```Starlark
>         "image_tag": IMAGE_REPOSITORY_SETTINGS.image_tag,
>         "google_cloud_project": GCLOUD_SETTINGS.project,
>         "spanner_instance": GCLOUD_SETTINGS.spanner_instance,
> ```

Doesn't the GKE version still need the Spanner instance?
___
*[`src/main/k8s/dev/base_gke.cue` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-Neu94ar8dLXxCCXvaDT:-Neu94ar8dLXxCCXvaDU:b-h0pugv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858313c9d53b68f8a1c1b8ea0a26ac92ac4a9bd1/src/main/k8s/dev/base_gke.cue#L59)):*
> ```CUE
> }
> 
> #AwsServiceAccountPodSpec: {
> ```

This is in a file named `base_gke.cue` as it has GKE-specific bits.
___
*[`src/main/k8s/dev/config.cue` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-Neu8T3sA7kQay2nxxXz:-Neu8T3sA7kQay2nxxY-:bgbdwfq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858313c9d53b68f8a1c1b8ea0a26ac92ac4a9bd1/src/main/k8s/dev/config.cue#L1)):*
> ```CUE
> // Copyright 2022 The Cross-Media Measurement Authors
> ```

You probably want to split this file into `config.cue`, `config_gke.cue`, and `config_eks.cue`.
___
*[`src/main/k8s/dev/duchy_eks.cue` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-NeuAxe1217p1Qkm8ngH:-NeuAxe1217p1Qkm8ngI:b-tmbnxx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858313c9d53b68f8a1c1b8ea0a26ac92ac4a9bd1/src/main/k8s/dev/duchy_eks.cue#L21)):*
> ```CUE
> _secret_name:                     string @tag("secret_name")
> _certificateId:                   string @tag("certificate_id")
> _computation_control_server_eips: string @tag("computation_control_server_eips")
> ```

nit: new code should use lowerCamelCase for CUE fields



_Code quote:_
```CUE
_computation_control_server_eips
```

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239)* status: 2 of 11 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`build/variables.bzl` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-Neu6yVg5ia7ux4cW_ZI:-Ney2xIV3K7BIgADmyf0:bn2ef83) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858313c9d53b68f8a1c1b8ea0a26ac92ac4a9bd1/build/variables.bzl#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The secret names are in this config for legacy reasons before we started using Kustomize. We took it in as a param since we didn't know what the hash appended to the name would be.
</blockquote></details>

Should I use kustomize to manage it instead? 
https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kustomize/#:~:text=kubectl%20supports%20using%20the%20Kustomize,the%20API%20server%20using%20kubectl%20.
___
*[`src/main/k8s/postgres.cue` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-Neu7Op7A3v6gnusCieu:-Ney2mkbBVO__X8V3skx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858313c9d53b68f8a1c1b8ea0a26ac92ac4a9bd1/src/main/k8s/postgres.cue#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. Embed `#CommonPostgresConfig` and update `#PostgresConfig` to include `#AwsPostgresConfig` in the disjunction
2. Don't specify the tags here. Do that in the appropriate config.cue file.
</blockquote></details>

Done.
___
*[`src/main/k8s/dev/BUILD.bazel` line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-NeuBRCEExjrn3NYYes0:-Ney2oE7APc4FvuDRKsh:bs2zuph) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cceea41f671d90f3332ada971910c86e0f7fa63/src/main/k8s/dev/BUILD.bazel#L143)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Doesn't the GKE version still need the Spanner instance?
</blockquote></details>

Done. 
that was by accident.
___
*[`src/main/k8s/dev/base_gke.cue` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-Neu94ar8dLXxCCXvaDT:-Ney2rZv7BWqub9AgnzU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858313c9d53b68f8a1c1b8ea0a26ac92ac4a9bd1/src/main/k8s/dev/base_gke.cue#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is in a file named `base_gke.cue` as it has GKE-specific bits.
</blockquote></details>

Done.
___
*[`src/main/k8s/dev/config.cue` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-Neu8T3sA7kQay2nxxXz:-Ney2ual4RSVxfwL_Yiu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858313c9d53b68f8a1c1b8ea0a26ac92ac4a9bd1/src/main/k8s/dev/config.cue#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You probably want to split this file into `config.cue`, `config_gke.cue`, and `config_eks.cue`.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239)* status: all files reviewed, 3 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`build/variables.bzl` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-Neu6yVg5ia7ux4cW_ZI:-NfCTCo5A5BV_I95AVdu:b-5ok2ms) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858313c9d53b68f8a1c1b8ea0a26ac92ac4a9bd1/build/variables.bzl#L66)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

Should I use kustomize to manage it instead? 
https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kustomize/#:~:text=kubectl%20supports%20using%20the%20Kustomize,the%20API%20server%20using%20kubectl%20.
</blockquote></details>

Yes. Secrets should be generated from a `secretGenerator` in a `kustomization.yaml` file.
___
*[`src/main/k8s/dev/base_eks.cue` line 23 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-NfCUGtj8mlqxCzt0SyE:-NfCUGtj8mlqxCzt0SyF:bbluu8x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c31ed29d0f13da52f6c02994819e17db6aea9cc6/src/main/k8s/dev/base_eks.cue#L23)):*
> ```CUE
> }
> 
> #AwsServiceAccountPodSpec: {
> ```

Duplicate definition.
___
*[`src/main/k8s/dev/config_eks.cue` line 24 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-NfCUrrYCvcj_ZaRhOjO:-NfCUrrYCvcj_ZaRhOjP:b747wmk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c31ed29d0f13da52f6c02994819e17db6aea9cc6/src/main/k8s/dev/config_eks.cue#L24)):*
> ```CUE
> #ImageConfig: {
> 	tag: string @tag("image_tag")
> }
> ```

#ContainerRegistryConfig: {
	registry:   string @tag("container_registry")
	repoPrefix: string @tag("image_repo_prefix")
}

#ImageConfig: {
	tag: string @tag("image_tag")
}



_Code quote:_
```CUE
#ContainerRegistryConfig: {
	registry:   string @tag("container_registry")
	repoPrefix: string @tag("image_repo_prefix")
}

#ImageConfig: {
	tag: string @tag("image_tag")
}
```

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239)* status: 6 of 12 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tag)

___
*[`build/variables.bzl` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-Neu6yVg5ia7ux4cW_ZI:-NfCm_P2CDTL-4LZnzFi:bra60zl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858313c9d53b68f8a1c1b8ea0a26ac92ac4a9bd1/build/variables.bzl#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes. Secrets should be generated from a `secretGenerator` in a `kustomization.yaml` file.
</blockquote></details>

Since this secret name was dynamically generated when RDS postgres instance is created, would it be better to pass it in as a parameter. Otherwise, a PR has to be made to update the secret name whenever the RDS postgres instance is re-created.
___
*[`src/main/k8s/dev/base_eks.cue` line 23 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-NfCUGtj8mlqxCzt0SyE:-NfCaFNz4pkhdIOYEisU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c31ed29d0f13da52f6c02994819e17db6aea9cc6/src/main/k8s/dev/base_eks.cue#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Duplicate definition.
</blockquote></details>

Done.
___
*[`src/main/k8s/dev/config_eks.cue` line 24 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-NfCUrrYCvcj_ZaRhOjO:-NfCpFd41YLH665HTxpI:b-79c9kv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c31ed29d0f13da52f6c02994819e17db6aea9cc6/src/main/k8s/dev/config_eks.cue#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

#ContainerRegistryConfig: {
	registry:   string @tag("container_registry")
	repoPrefix: string @tag("image_repo_prefix")
}

#ImageConfig: {
	tag: string @tag("image_tag")
}
</blockquote></details>

I moved these two config into a new file `config_base.cue` since it is common in both config_gke and config_eks.
I guessed that's what you meant here.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239)* status: 6 of 12 files reviewed, 2 unresolved discussions (waiting on @tag)

___
*[`build/variables.bzl` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-Neu6yVg5ia7ux4cW_ZI:-NfCsFgr3Oi4CONdb8wy:bbl0iwu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858313c9d53b68f8a1c1b8ea0a26ac92ac4a9bd1/build/variables.bzl#L66)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

Since this secret name was dynamically generated when RDS postgres instance is created, would it be better to pass it in as a parameter. Otherwise, a PR has to be made to update the secret name whenever the RDS postgres instance is re-created.
</blockquote></details>

Sorry, I assumed this (like all of our other secrets so far) was a secret that would be generated by the Kustomization process. If it's generated externally then it would indeed be correct to pass in the name.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

___
*[`src/main/k8s/dev/config_base.cue` line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-NfCtL19DD2V0MD1LhVi:-NfCtL19DD2V0MD1LhVj:bmx7u86) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2dd01ec5bdc7da10872b2a46afb592c9969199/src/main/k8s/dev/config_base.cue#L1)):*
> ```CUE
> // Copyright 2023 The Cross-Media Measurement Authors
> ```

Keep the name as `config.cue` to avoid confusion with `base.cue`

The overall operation was intended to be extracting both the GKE- and EKS-specific definitions from the original `config.cue` into `config_gke.cue` and `config_eks.cue`, respectively. This would leave the general definitions in the original `config.cue` file.

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/dev/config_base.cue` line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-NfCtL19DD2V0MD1LhVi:-NfCvbtoDXUz9NPz5-7p:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2dd01ec5bdc7da10872b2a46afb592c9969199/src/main/k8s/dev/config_base.cue#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Keep the name as `config.cue` to avoid confusion with `base.cue`

The overall operation was intended to be extracting both the GKE- and EKS-specific definitions from the original `config.cue` into `config_gke.cue` and `config_eks.cue`, respectively. This would leave the general definitions in the original `config.cue` file.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239)* status: all files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

___
*[`src/main/k8s/dev/config_base.cue` line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-NfCtL19DD2V0MD1LhVi:-NfDbSZNBMagRGoNu6ad:b-6r3b9q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2dd01ec5bdc7da10872b2a46afb592c9969199/src/main/k8s/dev/config_base.cue#L1)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Revert the copyright change on the file since this file is just now considered edited.

**Review by YuhongWang-Amazon — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/dev/config_base.cue` line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239#-NfCtL19DD2V0MD1LhVi:-NfGo8TmEGclYVtNtgiG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2dd01ec5bdc7da10872b2a46afb592c9969199/src/main/k8s/dev/config_base.cue#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Revert the copyright change on the file since this file is just now considered edited.
</blockquote></details>

Done.

**Review by YuhongWang-Amazon — COMMENTED** [review]
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Pull request merged**
