### PR TITLE
Manage external IP addresses for GKE in Terraform.

### PR DESCRIPTION
**Pull request by SanjayVas**
This requires GKE 1.29+. Service resources may need to be manually deleted as migration of existing Services to L4-RBS is not supported. This may result in IP address changes.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1583)

**Review by YuhongWang-Amazon — APPROVED** [review]
Do we want to make the same changes for AWS Duchy?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1583#-:-NwB1T9VDWYrL6NZoYa5:b-kro6wt)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
I was under the impression that the AWS Duchy already worked this way, as the EIP allocation IDs are passed in. Are those allocations not managed by Terraform?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1583#-:-NwB7HuZAoiT2LZ7Slo4:b-zhp8os)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> What's the reason to make this change?

This change is part of the prefactoring to support wiping the Kubernetes cluster objects and DBs when updating the `head` environment. We can't have a manual process for specifying the IP addresses via the deprecated loadBalancerIP field. That technically only requires plumbing in the resource names; see below for the Terraform part.

> I thought we keep this step a manual process to avoid unintentionally IP updates caused by terraform recreating the EIPs.

I don't believe this was a consideration. I think this was just an oversight in the migration from fully manual to Terraform. Ideally we want all infra for running CMSS components (everything outside of the K8s object configurations) to be managed by Terraform. For GKE specifically, the ability to specify the IP address resource names is new as of GKE 1.29 so we couldn't even do it this way before.

> The AWS EIPs were manually created. We should be able to import the existing ones into terraform without updating the IPs.

I'll create a follow-up PR for AWS then.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1583#-:-NwBFTbPENZ-kWvtDrva:b-no8mnf)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> We should be able to import the existing ones into terraform without updating the IPs.

As an additional note, Terraform import was insufficient to keep the IPs for gcloud. The existing resources had different names, and changing the name required the resource to be replaced. Theoretically it could have been done by temporarily manually specifying the actual IP addresses in the TF resource, but I wanted to keep the resources in the shared modules where possible.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1583#-:-NwBHl-A7xVLUVOalF5i:b89jqa2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by YuhongWang-Amazon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1583)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1583)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
