### PR TITLE
feat!: enable horizontal autoscaling of Liquid Legions v2 Mill

### PR DESCRIPTION
**Pull request by SanjayVas**
This converts the LLv2 Mill daemon to a Job which processes a single work item. Jobs are scheduled via a new MillJobScheduler daemon.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697)

**Comment by SanjayVas** [comment]
This is an alternate approach to #1686

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 58 of 87 files at r1, 5 of 8 files at r2, 8 of 14 files at r4, 2 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697)* status: 70 of 87 files reviewed, 8 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 69 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2WjFa-4z59BIUHE6ch:-O2WjFa-4z59BIUHE6ci:b-mmn91e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L69)):*
> ```Kotlin
> 
> /** Scheduler for Mill Kubernetes Jobs. */
> class MillJobScheduler(
> ```

Any reason the scheduler has to be LLv2 specific?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 72 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2Win_t2p6ng_2WbxHe:-O2Win_t2p6ng_2WbxHf:b4l9tuf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L72)):*
> ```Kotlin
>   private val duchyId: String,
>   private val computationsStub: ComputationsGrpcKt.ComputationsCoroutineStub,
>   private val deploymentName: String,
> ```

nit: It's not clear what this is for without reading the code. 

I wrote the above and then happened to skip to the bottom of the file and saw the flag definitions. A note in the ktdoc indicating these fields are documented as command line flags below would helop.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 115 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2WlbXF1R5bwmFPVMl4:-O2WlbXF1R5bwmFPVMl5:b-ex0ozy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L115)):*
> ```Kotlin
>     val computationType: ComputationType = computationTypeConfig.computationType
> 
>     val activeJobCount: Int =
> ```

This would avoid the reference to the issue.



_Code snippet:_
```Kotlin
ownedJobs.filter({it.status.active ?:0) > 0}).count() 
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 122 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2Wly9U3eZG7zRt1_HV:-O2Wly9U3eZG7zRt1_HW:bmxjczj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L122)):*
> ```Kotlin
>       }
>     if (activeJobCount >= millType.maximumConcurrency) {
>       logger.fine { "Not scheduling: Maximum concurrency limit reached for $millType" }
> ```

It'd be helpful to have the activeJobCount, and maybe the limit on the log line.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 153 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2Wmotq1y0rnH4vlyj1:-O2Wmotq1y0rnH4vlyj2:b-grbovh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L153)):*
> ```Kotlin
>     logger.info { "Scheduled Job $jobName for Computation $claimedComputationId" }
>     if (activeJobCount + 1 >= millType.maximumConcurrency) {
>       logger.info { "Mill type $millType is now at maximum concurrency" }
> ```

nit: add the max concurrency to the log line
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 162 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2Wn89O4RQIzWeEI9rQ:-O2Wn89O4RQIzWeEI9rR:bksd9x8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L162)):*
> ```Kotlin
>   }
> 
>   private suspend fun Collection<V1Job>.deleteOverLimit(limit: Int, predicate: (V1Job) -> Boolean) {
> ```

When do we expect this function to have work to do?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillFlags.kt` line 17 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2Wo10x9u6Jv0xM4IFg:-O2Wo10x9u6Jv0xM4IFh:b-ozahpk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillFlags.kt#L17)):*
> ```Kotlin
> package org.wfanet.measurement.duchy.deploy.common.daemon.mill.shareshuffle
> 
> import java.io.File
> ```

Why are these changes required in this PR?
___
*[`src/main/terraform/gcloud/examples/duchy/main.tf` line 74 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2WosuZDBbCNzMvvlz7:-O2Wosu_9JIISThbpbAb:bkoqrr2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/terraform/gcloud/examples/duchy/main.tf#L74)):*
> ```HCL
>   service_account = module.common.cluster_service_account
>   machine_type    = "c2-standard-4"
>   max_node_count  = 20
> ```

Is this the same value we expect to be passed to the scheduler? If so, is it possible for the scheduler to read it from the k8s API?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697)* status: 70 of 87 files reviewed, 6 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 69 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2WjFa-4z59BIUHE6ch:-O2_uQJO75cZlbbV0zke:bt7qjlp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L69)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Any reason the scheduler has to be LLv2 specific?
</blockquote></details>

It isn't. It's intended to support multiple mill types. Indeed, that's the reason for the MillType enum. I'm just adding HMSS in a follow up PR.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 72 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2Win_t2p6ng_2WbxHe:-O2_z50Y1QNsRAGiSsrJ:bya4x6j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L72)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

nit: It's not clear what this is for without reading the code. 

I wrote the above and then happened to skip to the bottom of the file and saw the flag definitions. A note in the ktdoc indicating these fields are documented as command line flags below would helop.
</blockquote></details>

Done. Added reference to Flags from KDoc.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 115 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2WlbXF1R5bwmFPVMl4:-O2_ugf808ShbA-QPnAb:b1vyomu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L115)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This would avoid the reference to the issue.
</blockquote></details>

Done. Slightly better syntax though by passing the predicate to `count` rather than using `filter`.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 122 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2Wly9U3eZG7zRt1_HV:-O2a0NQKBo4XuqGbAK_O:b-4e5e1g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L122)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It'd be helpful to have the activeJobCount, and maybe the limit on the log line.
</blockquote></details>

Done.

Note that some of these are at the FINE level.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 162 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2Wn89O4RQIzWeEI9rQ:-O2a0xR8-TP2QMvc7O4c:bh4mpt3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L162)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

When do we expect this function to have work to do?
</blockquote></details>

Added some documentation.

The basic issue is that we don't want to leave a bunch of completed Jobs/Pods around. Rather than using the completed TTL, we instead have a configurable history limit. This is similar to the approach used by CronJob.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillFlags.kt` line 17 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2Wo10x9u6Jv0xM4IFg:-O2_w8gy5HeY29FWZRj7:bfc8cbn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillFlags.kt#L17)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why are these changes required in this PR?
</blockquote></details>

I assume you mean the change to extract the common flags into MillFlags? It's been a longstanding TODO, and in this case it really helped when trying to figure out which flags needed to be moved/copied to the scheduler.

I would have done it in a pre-factoring PR, but had already moved some other things around such as the packages. If you feel strongly, I can still split it out as pre-factoring.
___
*[`src/main/terraform/gcloud/examples/duchy/main.tf` line 74 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2WosuZDBbCNzMvvlz7:-O2_wmccDapIPRflzIoE:b-nccsbs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/terraform/gcloud/examples/duchy/main.tf#L74)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Is this the same value we expect to be passed to the scheduler? If so, is it possible for the scheduler to read it from the k8s API?
</blockquote></details>

As discussed offline, this is not necessarily the same. It'll depend on the chosen machine types vs. the configured resource requirements for each job. It'll also depend on what else you're running in the node pool (or for EKS, node group), for example if you want to use the same pool for both HMSS and LLv2 Mill Jobs.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 11 of 87 files at r1, 1 of 8 files at r2, 1 of 5 files at r5, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697)* status: 83 of 87 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 115 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2WlbXF1R5bwmFPVMl4:-O2aBOMc9duYAO2iDKJD:b-3v5c5g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Done. Slightly better syntax though by passing the predicate to `count` rather than using `filter`.
</blockquote></details>

Indeed. Didn't realize it took a predicate.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 75 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2aComb0rFSswwb1WRb:-O2aComc2yImj18KeHmN:bd7227g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/012442fde2c1b8ce5d29000dd017a5b497867f8f/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L75)):*
> ```Kotlin
>  * See [MillJobScheduler.Flags] for additional parameter documentation.
>  */
> class MillJobScheduler(
> ```

How is this being tested?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillFlags.kt` line 17 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2Wo10x9u6Jv0xM4IFg:-O2aBekw6th2uiFfrjBk:bmfujd5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17941b78a47177c386a60c983cc9094fc3313d0e/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillFlags.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I assume you mean the change to extract the common flags into MillFlags? It's been a longstanding TODO, and in this case it really helped when trying to figure out which flags needed to be moved/copied to the scheduler.

I would have done it in a pre-factoring PR, but had already moved some other things around such as the packages. If you feel strongly, I can still split it out as pre-factoring.
</blockquote></details>

It's fine. I can live with it. :)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 87 files at r1, 2 of 3 files at r6, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 75 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2aComb0rFSswwb1WRb:-O2ayvTm5gz6gX-TWtZD:b-77bzq2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/012442fde2c1b8ce5d29000dd017a5b497867f8f/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L75)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

How is this being tested?
</blockquote></details>

We discussed this offline. Manual testing is probably okay. We also know that KinD tests the happy path. Perhaps there's some way to mock a few things and have some basic tests to show that this class manages concurrency and some of the other clean up tasks correctly?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697)* status: 83 of 92 files reviewed, all discussions resolved (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt` line 75 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697#-O2aComb0rFSswwb1WRb:-O2gNrcQ4-2Dx0PcevF3:b4xw3tl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/012442fde2c1b8ce5d29000dd017a5b497867f8f/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt#L75)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We discussed this offline. Manual testing is probably okay. We also know that KinD tests the happy path. Perhaps there's some way to mock a few things and have some basic tests to show that this class manages concurrency and some of the other clean up tasks correctly?
</blockquote></details>

Indeed, the Kubernetes tests exercise this but don't verify specific behavior (e.g. that the max concurrency limit is respected). I managed to add a unit test by mocking KubernetesClient.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 66 of 87 files at r1, 4 of 8 files at r2, 7 of 14 files at r4, 3 of 5 files at r5, 2 of 3 files at r6, 9 of 10 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 10 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1697)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @stevenwarejones)

**Pull request merged**
