### PR TITLE
Add ResourceSetup class for Panel Match Integration test

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285)* status: all files reviewed, 6 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDPgnP2nwDNvtk3ioz:-MkDPgnP2nwDNvtk3ip-:b-5ej6s8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L45)):*
> ```Kotlin
> 
> /**
>  * Class preparing resources required for the Panel Match Integration test using internal services.
> ```

Change you change the part of speech?

"Prepares resources for Panel Match integration tests using internal APIs." maybe
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDPZTg6Vcj_wfTo2Qb:-MkDPZTg6Vcj_wfTo2Qc:bbptpl6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L47)):*
> ```Kotlin
>  * Class preparing resources required for the Panel Match Integration test using internal services.
>  */
> class ResourceSetup(
> ```

Can you rename this to be Panel-specific? 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDPsEJ6TViGpwU03QK:-MkDPsEJ6TViGpwU03QL:bez4xs1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L54)):*
> ```Kotlin
> 
>   /** Process to create resources. */
>   suspend fun process(exchangeSchedule: String, exchangeWorkflow: ExchangeWorkflow): ProviderKey {
> ```

maybe `createResourcesForWorkflow`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDQd3b-rhe4u2mxXDm:-MkDQd3b-rhe4u2mxXDn:bscziw9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L136)):*
> ```Kotlin
>       stepsList.map { step ->
>         step.stepId.toInt() to
>           Pair(step.partyValue, step.sharedInputLabelsMap.keys.map { it.toInt() })
> ```

Rather than using the value of the enum, can you just use the enum itself and then use a `when` to convert? That's easier to understand, I think.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDQq7o6jhDwhsiIfnQ:-MkDQq7o6jhDwhsiIfnR:b-rwitsu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L136)):*
> ```Kotlin
>       stepsList.map { step ->
>         step.stepId.toInt() to
>           Pair(step.partyValue, step.sharedInputLabelsMap.keys.map { it.toInt() })
> ```

I don't quite understand this conversion to ints, can you explain?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 155 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDQyRA0NWxUOHIhOWI:-MkDQyRA0NWxUOHIhOWJ:bygpac) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L155)):*
> ```Kotlin
> }
> 
> data class ProviderKey(val dataProviderKey: String, val modelProviderKey: String)
> ```

Maybe call this class `RecurringExchangeParticipants`?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDPZTg6Vcj_wfTo2Qb:-MkDX8yb6nI8erz_8Ufu:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you rename this to be Panel-specific? 
</blockquote></details>

+1

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDPgnP2nwDNvtk3ioz:-MkDXicM0lSk89aLih65:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Change you change the part of speech?

"Prepares resources for Panel Match integration tests using internal APIs." maybe
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDPZTg6Vcj_wfTo2Qb:-MkDXhmSBIIlO3UR4IUl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L47)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDPsEJ6TViGpwU03QK:-MkDXjyb6G6tWHh__GMv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

maybe `createResourcesForWorkflow`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDQd3b-rhe4u2mxXDm:-MkDXkl_Ce-zkZxp2CVb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L136)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Rather than using the value of the enum, can you just use the enum itself and then use a `when` to convert? That's easier to understand, I think.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDQq7o6jhDwhsiIfnQ:-MkDXm5H6Ckj3vUgTYG-:b67dd4m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L136)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't quite understand this conversion to ints, can you explain?
</blockquote></details>

In the external proto there doesn't seem to be a int step_index. I assumed step_id is equivalent to step_index but looking at some code in panel-exchange-client it might be characters "a" to "b". Then I think we need to introduce that string step_id in the internal proto as well if thats the one defines the unique step?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 155 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDQyRA0NWxUOHIhOWI:-MkDXlZi3w5eU_IS6lTG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L155)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe call this class `RecurringExchangeParticipants`?
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDQq7o6jhDwhsiIfnQ:-MkDodIKCcERL_bdYGRa:boy41hc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L136)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

In the external proto there doesn't seem to be a int step_index. I assumed step_id is equivalent to step_index but looking at some code in panel-exchange-client it might be characters "a" to "b". Then I think we need to introduce that string step_id in the internal proto as well if thats the one defines the unique step?
</blockquote></details>

No, it's the index in steps that defines the step index. In other words, the first step has index 0, etc. This is documented here: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/kingdom/exchange_step.proto#L37

But also, the logic here is wrong because the `shared_input_labels` do NOT reference step names.

What you want is something like this I think:

```
val outputLabelToStepIndex = stepsList
  .flatMapIndexed { index, step ->
    val outputLabels = sharedOutputLabelsMap.values.toList() + privateOutputLabelsMap.values.toList()
    outputLabels.map { it to index }
  }
 .toMap()

val prerequisites = stepsList.mapIndexed { index, step -> 
  val labels = sharedInputLabelsMap.values.toList() + privateInputLabelsMap.values.toList()
  internalStep {
    stepIndex = index
    party = step.party.toInternal()
    prequisiteStepIndices += labels.flatMap { outputLabelToStepIndex[it] }.toSet()
  }
}
```

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDQq7o6jhDwhsiIfnQ:-MkGOhvw3ekYevL8WYRf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L136)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

No, it's the index in steps that defines the step index. In other words, the first step has index 0, etc. This is documented here: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/kingdom/exchange_step.proto#L37

But also, the logic here is wrong because the `shared_input_labels` do NOT reference step names.

What you want is something like this I think:

```
val outputLabelToStepIndex = stepsList
  .flatMapIndexed { index, step ->
    val outputLabels = sharedOutputLabelsMap.values.toList() + privateOutputLabelsMap.values.toList()
    outputLabels.map { it to index }
  }
 .toMap()

val prerequisites = stepsList.mapIndexed { index, step -> 
  val labels = sharedInputLabelsMap.values.toList() + privateInputLabelsMap.values.toList()
  internalStep {
    stepIndex = index
    party = step.party.toInternal()
    prequisiteStepIndices += labels.flatMap { outputLabelToStepIndex[it] }.toSet()
  }
}
```
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDQq7o6jhDwhsiIfnQ:-MkICzA_6c9KBZJfNukI:bo6qjfp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L136)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The steps aren't necessarily topologically sorted so I think you need to do it in a two-phase approach like I provided

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkDQq7o6jhDwhsiIfnQ:-MkID9CfABLcZqhoj_mV:b4ipde7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2410f8215c0d9685832a6a36ba16eab8a0255bd1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/ResourceSetup.kt#L136)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The steps aren't necessarily topologically sorted so I think you need to do it in a two-phase approach like I provided
</blockquote></details>

Oh wait nevermind, I misread the code here. I'll do a more detailed review later today

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285)* status: all files reviewed, 5 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 69 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkIXvFYCAPaUaQiDFDT:-MkIXvFZ3Cqm0XgpZbT0:bs8pu24) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5964d8c9e76b325b9385d4c6cc52821caf18a498/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L69)):*
> ```Kotlin
>         exchangeDate = LocalDate.now().toProtoDate(),
>         exchangeSchedule = exchangeSchedule,
>         extApiVersion = apiVersion,
> ```

Please don't abbreviate `external` -- can you just call this `publicApiVersion`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 70 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkIY-hx4jlrY5FMH5CT:-MkIY-hx4jlrY5FMH5CU:bb9qfpe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5964d8c9e76b325b9385d4c6cc52821caf18a498/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L70)):*
> ```Kotlin
>         exchangeSchedule = exchangeSchedule,
>         extApiVersion = apiVersion,
>         extExchangeWorkflow = exchangeWorkflow
> ```

Since there's no internal `ExchangeWorkflow`, I think you can just call this parameter `exchangeWorkflow`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 140 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkIYCGh7D1J8MJX7whJ:-MkIY9AU5X84rlnYyiTg:b5a9j3w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5964d8c9e76b325b9385d4c6cc52821caf18a498/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L140)):*
> ```Kotlin
>   private fun ExchangeWorkflow.toInternal(): InternalExchangeWorkflow {
>     val labelsMap = mutableMapOf<String, MutableSet<Int>>()
>     stepsList.forEachIndexed { index, step ->
> ```

I generally prefer for-loops over `forEach` and `forEachIndexed`. If you need indexes, use `for ((index, step) in stepsList.withIndex()) {` -- https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/with-index.html
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 144 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkIYTPr4-np7tAgyQCK:-MkIYTPr4-np7tAgyQCL:b294zvt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5964d8c9e76b325b9385d4c6cc52821caf18a498/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L144)):*
> ```Kotlin
>         step.sharedOutputLabelsMap.values.toList() + step.privateOutputLabelsMap.values.toList()
>       outputLabels.forEach {
>         labelsMap.putIfAbsent(it, mutableSetOf())
> ```

One-liner: `labelsMap.getOrPut(it) { mutableSetOf() }.add(index)`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 158 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkIZ0us9d3CLQfPr0Mc:-MkIZ0us9d3CLQfPr0Md:b-3c23fc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5964d8c9e76b325b9385d4c6cc52821caf18a498/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L158)):*
> ```Kotlin
>             labels
>               .flatMap { value ->
>                 if (labelsMap.contains(value)) {
> ```

One-liner: `labelsMap.getOrDefault(value) { emptyList() }.map { it + 1 }`

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 69 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkIXvFYCAPaUaQiDFDT:-MkJ1o2c0uqofdovm8hl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5964d8c9e76b325b9385d4c6cc52821caf18a498/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L69)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please don't abbreviate `external` -- can you just call this `publicApiVersion`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 70 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkIY-hx4jlrY5FMH5CT:-MkJ1nHj4pxScgP1T8fK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5964d8c9e76b325b9385d4c6cc52821caf18a498/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since there's no internal `ExchangeWorkflow`, I think you can just call this parameter `exchangeWorkflow`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 140 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkIYCGh7D1J8MJX7whJ:-MkJ1mH_C8JKaMGTvfYp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5964d8c9e76b325b9385d4c6cc52821caf18a498/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L140)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I generally prefer for-loops over `forEach` and `forEachIndexed`. If you need indexes, use `for ((index, step) in stepsList.withIndex()) {` -- https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/with-index.html
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 144 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkIYTPr4-np7tAgyQCK:-MkJ1lYuEv4WdiKX20R8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5964d8c9e76b325b9385d4c6cc52821caf18a498/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L144)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

One-liner: `labelsMap.getOrPut(it) { mutableSetOf() }.add(index)`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 158 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285#-MkIZ0us9d3CLQfPr0Mc:-MkJ1jbe3BlbbI8djwzE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5964d8c9e76b325b9385d4c6cc52821caf18a498/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L158)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

One-liner: `labelsMap.getOrDefault(value) { emptyList() }.map { it + 1 }`
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/285)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @kgaynor)

**Pull request merged**
