### PR TITLE
Add library to compute the variances for HMSS protocol.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/BUILD.bazel` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O0u2ACi8-1GiwJj2l_H:-O0u2ACi8-1GiwJj2l_I:b-qj30z4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/508a3d3756333eb4240f541cd21395f7025961f1/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/BUILD.bazel#L30)):*
> ```Starlark
>         ":measurement_statistics",
>         "//src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement:acdp_params_converter",
>         "@wfa_common_jvm//imports/java/org/apache/commons:math3",
> ```

I'm not spotting commons-math3 used in this lib. Are you sure it needs these deps?
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt` line 120 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O0u1t0B5Gib3xzqbSoE:-O0u1t0B5Gib3xzqbSoF:bcvlrk5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/508a3d3756333eb4240f541cd21395f7025961f1/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt#L120)):*
> ```Kotlin
>           LiquidLegionsSketchParams(methodology.decayRate, methodology.sketchSize)
>         }
>         is HonestMajorityShareShuffleMethodology -> {
> ```

Just to clarify, does this mean covariance calculations are not supported for HMSS?
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/HonestMajorityShareShuffle.kt` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O0u3B6U1iFl8gqGo_-k:-O0u3B6V2A6HHVKzAt1q:b1c2mnz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/508a3d3756333eb4240f541cd21395f7025961f1/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/HonestMajorityShareShuffle.kt#L56)):*
> ```Kotlin
> 
>   /**
>    * Outputs the variance of the given [kReach] when k < maximumFrequency, and the variance of
> ```

This doesn't appear to be a valid reference. I'm not spotting which symbol this is referencing.



_Code quote:_
```Kotlin
[kReach]
```
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O0u4ti6DTeMrdZoZ22w:-O0u4ti6DTeMrdZoZ22x:bbqwunc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/508a3d3756333eb4240f541cd21395f7025961f1/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt#L41)):*
> ```Kotlin
> data class HonestMajorityShareShuffleMethodology(val sketchSize: Long) : Methodology
> 
> data class ReachOnlyHonestMajorityShareShuffleMethodology(val sketchSize: Long) : Methodology
> ```

Just to clarify, there's a separate methodology when only computing reach for HMSS? Meaning in the [CMSS public API](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7c8702ed832c51fdcc2b22917ee4a91c0fb11377/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L162), we'd have two methodologies for reach with the HMSS protocol?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: 1 of 9 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/BUILD.bazel` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O0u2ACi8-1GiwJj2l_H:-O0ugyys8d9Kmk-aUoPy:b3txnnx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/508a3d3756333eb4240f541cd21395f7025961f1/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/BUILD.bazel#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not spotting commons-math3 used in this lib. Are you sure it needs these deps?
</blockquote></details>

Thanks. I've removed unnecessary deps.
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt` line 120 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O0u1t0B5Gib3xzqbSoE:-O0ugLjLBh_fzqfsk4ws:b68hhfw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/508a3d3756333eb4240f541cd21395f7025961f1/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt#L120)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just to clarify, does this mean covariance calculations are not supported for HMSS?
</blockquote></details>

I've added a TODO to add support for HMSS covariance calculation.
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/HonestMajorityShareShuffle.kt` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O0u3B6U1iFl8gqGo_-k:-O0ukFz02zUm72SiG5PD:bx13k45) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/508a3d3756333eb4240f541cd21395f7025961f1/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/HonestMajorityShareShuffle.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't appear to be a valid reference. I'm not spotting which symbol this is referencing.
</blockquote></details>

I've updated the descriptions.
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O0u4ti6DTeMrdZoZ22w:-O0ug8YG3PalIj2paG0s:bwut0d5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/508a3d3756333eb4240f541cd21395f7025961f1/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just to clarify, there's a separate methodology when only computing reach for HMSS? Meaning in the [CMSS public API](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7c8702ed832c51fdcc2b22917ee4a91c0fb11377/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L162), we'd have two methodologies for reach with the HMSS protocol?
</blockquote></details>

We do not need another methodology for the reach only HMSS. I've removed it.

**Review by jiayu-google — APPROVED** [review]
The formulas lgtm. Thank you Phi!

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto` line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O1I4Fo6A0l7QjJzou-I:-O1I4Fo6A0l7QjJzou-J:b-ekeaaq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/665cfb3ac43df1894174807c27f5471f30efaaed/src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto#L71)):*
> ```proto
> }
> 
> message ReachOnlyHonestMajorityShareShuffle {
> ```

There's still a separate methodology here

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O1Ig80b5Vc2Kh4C6FUm:-O1Ig80b5Vc2Kh4C6FUn:b-rdu59p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/665cfb3ac43df1894174807c27f5471f30efaaed/src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto#L35)):*
> ```proto
> }
> 
> message ShareShuffleSketchParams {
> ```

Why do we need this? Ultimately what we compute over for HMSS is not a sketch at all, but a Frequency Vector. 

What is the register count intended to capture?

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O1Ig80b5Vc2Kh4C6FUm:-O1IgkHBDkofyJZaZfWy:bgxrtu2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/665cfb3ac43df1894174807c27f5471f30efaaed/src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto#L35)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why do we need this? Ultimately what we compute over for HMSS is not a sketch at all, but a Frequency Vector. 

What is the register count intended to capture?
</blockquote></details>

To clarify my question... is the register count here populationSize*samplingRate or populationSize?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O1Ig80b5Vc2Kh4C6FUm:-O1JFwHl8n4d0DsbFcV2:b-q792a9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/665cfb3ac43df1894174807c27f5471f30efaaed/src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto#L35)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

To clarify my question... is the register count here populationSize*samplingRate or populationSize?
</blockquote></details>

Yeah, "sketch" is not a correct word to use here. The register count is the size of the frequency vector (or Sketch size in this PR), which is equal to populationSize*samplingRate. We need the populationSize to calculate the variances, one way to get it is from the size of the frequencyVector and the sampling rate. I'll update the name to avoid the confusion.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto` line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O1I4Fo6A0l7QjJzou-I:-O1ICA4d7kqddUwx3acn:b-ajpm19) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/665cfb3ac43df1894174807c27f5471f30efaaed/src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There's still a separate methodology here
</blockquote></details>

This is the config for the reach only HMSS protocol, not a methodology.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto` line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O1I4Fo6A0l7QjJzou-I:-O1JJJFi6OuB4byCEmc0:bkgb61f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/665cfb3ac43df1894174807c27f5471f30efaaed/src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto#L71)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

This is the config for the reach only HMSS protocol, not a methodology.
</blockquote></details>

It's used in the `methodology` oneof in Measurement.Result.Reach above.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto` line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O1I4Fo6A0l7QjJzou-I:-O1KTVgB6uIGWmxNulCv:b-obwu94) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/665cfb3ac43df1894174807c27f5471f30efaaed/src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's used in the `methodology` oneof in Measurement.Result.Reach above.
</blockquote></details>

Ah yeah. We do not need this extra config for the reach only HMSS either. I've updated the code.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @renjiezh)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 81 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O1NjmaUCLh7_N56fgf0:-O1NjmaV2404lGdztB8T:bhrpnde) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7305101cea6662fee5c54c1ff91170eff192572e/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L81)):*
> ```proto
>         LiquidLegionsV2 liquid_legions_v2 = 6;
>         ReachOnlyLiquidLegionsV2 reach_only_liquid_legions_v2 = 7;
>         HonestMajorityShareShuffle honest_majority_share_shuffle = 8;
> ```

Should we have a "ReachOnlyHMSS" here? That would make it symmetric with LLv2 and would remove the question of what hmss.maximum_frequency means in this context.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto` line 59 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O1Niuta5fUjD6iUySzE:-O1Niuta5fUjD6iUySzF:b-v2tkhp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7305101cea6662fee5c54c1ff91170eff192572e/src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto#L59)):*
> ```proto
> 
> message HonestMajorityShareShuffle {
>   // The size of the frequency vector. REQUIRED.
> ```

Can you write: "The size of the sampled frequency vector" instead?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 81 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O1NjmaUCLh7_N56fgf0:-O1Nlv7u5b-hYlCpQsjx:bje9ipo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7305101cea6662fee5c54c1ff91170eff192572e/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L81)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Should we have a "ReachOnlyHMSS" here? That would make it symmetric with LLv2 and would remove the question of what hmss.maximum_frequency means in this context.
</blockquote></details>

I had the ReachOnlyHMSS before, but decided to remove it. I've just removed the field maximum_frequency as well as it's not needed here.

In the calculation of the variance, the maximum frequency is obtained from measurementParams, and never from the methodology (this is for both llv2 and hmss -- https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/113f56b1fd5509bc75d8a0050b3cda0134f3585a/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L564). Given that, the ReachOnlyHMSS will be identical to the HMSS.

Having only HonestMajorityShareShuffle is also consistent with a list of available methodologies declared in MetricStatistics.kt.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto` line 59 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O1Niuta5fUjD6iUySzE:-O1NluKp4S5TVIvx0wWb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7305101cea6662fee5c54c1ff91170eff192572e/src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto#L59)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you write: "The size of the sampled frequency vector" instead?
</blockquote></details>

Done.

**Review by kungfucraig — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 81 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677#-O1NjmaUCLh7_N56fgf0:-O1XOx5n5dYAsAbQdZgE:b-i5ilah) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7305101cea6662fee5c54c1ff91170eff192572e/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L81)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I had the ReachOnlyHMSS before, but decided to remove it. I've just removed the field maximum_frequency as well as it's not needed here.

In the calculation of the variance, the maximum frequency is obtained from measurementParams, and never from the methodology (this is for both llv2 and hmss -- https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/113f56b1fd5509bc75d8a0050b3cda0134f3585a/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L564). Given that, the ReachOnlyHMSS will be identical to the HMSS.

Having only HonestMajorityShareShuffle is also consistent with a list of available methodologies declared in MetricStatistics.kt.
</blockquote></details>

Sounds good! Thanks for removing max_freq.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 7 files at r3, 1 of 3 files at r4, 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh and @SanjayVas)

**Review by renjiezh — APPROVED** [review]
> Reviewed 2 of 7 files at r3, 1 of 3 files at r4, 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1677)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
