### PR TITLE
create model shard spanner service

### PR DESCRIPTION
**Pull request by Marco-Premier**
This is the last PR for internal APIs related to VID Model distribution

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r1, 12 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 553 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021#-NW9kaO6-cb8U-sRJ04D:-NW9kaO6-cb8U-sRJ04E:b-3av5y2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6ba5600af9538930e628be4bba1d1d3278993ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L553)):*
> ```Kotlin
> 
> class ModelShardNotFoundException(
>   val externalModelProviderId: ExternalId,
> ```

externalDataProviderId
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelShardReader.kt` line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021#-NW9nglrBhX5gbnlICwP:-NW9nglsCQXVg2a9qpoL:bptw39n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6ba5600af9538930e628be4bba1d1d3278993ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelShardReader.kt#L48)):*
> ```Kotlin
>      FROM ModelShards
>      JOIN DataProviders USING (DataProviderId)
>      LEFT JOIN ModelReleases ON (ModelShards.ModelRelease = ModelReleases.ModelReleaseId)
> ```

Shouldn't be LEFT JOIN since it is supposed to be not null.
___
*[`src/main/resources/kingdom/spanner/add-model-release-unique-index.sql` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021#-NW9mQN20J1MuqmZNxZg:-NW9mQN20J1MuqmZNxZh:b-tgtod3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6ba5600af9538930e628be4bba1d1d3278993ed/src/main/resources/kingdom/spanner/add-model-release-unique-index.sql#L21)):*
> ```TSQL
> -- For model shards APIs.
> CREATE UNIQUE INDEX ModelReleasesByExternalId
>     ON ModelReleases(ExternalModelReleaseId);
> ```

ON ModelReleases(ModelProviderId, ModelSuiteId, ExternalModelReleaseId). This is actually missing for the other external IDs for vid model distribution too. And the foreign keys should be referencing the whole primary key. Don't fix them all in this PR though. Create a separate PR.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021)* status: 10 of 19 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt` line 553 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021#-NW9kaO6-cb8U-sRJ04D:-NWBqMsg31xH05tldltm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6ba5600af9538930e628be4bba1d1d3278993ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L553)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

externalDataProviderId
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelShardReader.kt` line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021#-NW9nglrBhX5gbnlICwP:-NWBqQlpAFkSHM88yuSN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6ba5600af9538930e628be4bba1d1d3278993ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelShardReader.kt#L48)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Shouldn't be LEFT JOIN since it is supposed to be not null.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteModelShard.kt` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021#-NW9PGbO8abNqd4Jyag7:-NWBqiIo33MKvznWFOs8:b-ycoum7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6ba5600af9538930e628be4bba1d1d3278993ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteModelShard.kt#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are we allowing hard deletes?
</blockquote></details>

Yes Steven, we do allow hard deleted for ```ModelRollout``` and ```ModelShard```. Instead we do soft delete for ```ModelOutage```.
___
*[`src/main/resources/kingdom/spanner/add-model-release-unique-index.sql` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021#-NW9mQN20J1MuqmZNxZg:-NWD1mH1A3An5Ggn23fy:bscxesw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6ba5600af9538930e628be4bba1d1d3278993ed/src/main/resources/kingdom/spanner/add-model-release-unique-index.sql#L21)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

ON ModelReleases(ModelProviderId, ModelSuiteId, ExternalModelReleaseId). This is actually missing for the other external IDs for vid model distribution too. And the foreign keys should be referencing the whole primary key. Don't fix them all in this PR though. Create a separate PR.
</blockquote></details>

Fair enough. I fixed the ModelRelease unique index only here. Furthermore I fixed the foreign key just for ModelsShards.
Will add missing Unique indexes and fix remaining foreign keys in a separate PRs once all the internal APIs will be merged

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 4 of 13 files at r2, 8 of 9 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1021)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
