### PR TITLE
Implement public create account and replace account identity.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/353)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/353)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/353#-MoAAEuv4UCJN1vqtAaX:-MoAAEuv4UCJN1vqtAaY:bvtidc7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecca4465b1d0d34eae4c69d6289acaaebc3e0c5c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L57)):*
> ```
> with
> ```
nit: too much nesting and context switching. Do the MeasurementConsumerKey parsing outside of the internalAccount DSL builder.

Additionally, `with` is primarily useful when you are accessing multiple properties from a given object. It's much simpler in cases like this to just declare intermediate variables, e.g. `val ownedMeasurementConsumer = request.account.activationParams.ownedMeasurementConsumer`

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/353)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/353#-MoER6xCEwOzdf2EnbhN:-MoER6xCEwOzdf2EnbhO:b-akenyc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb54e7af40829f1606c457465546da95fe2420e0/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L72)):*
> ```Kotlin
>     }
> 
>     val result = internalAccountsStub.createAccount(internalCreateAccountRequest)
> ```

looks like this is unimplemented. Is the idea that if this method finds an externalId of 0, it will create a new id?

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/353#-MoER6xCEwOzdf2EnbhN:-MoF-aLP0IPj3Z_8-nQn:b5hwath) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26aaf6fabc66ce846398530574038015d3367f5b/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L72)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

looks like this is unimplemented. Is the idea that if this method finds an externalId of 0, it will create a new id?
</blockquote></details>

The idea is that if the owned measurement consumer is set, then the activation parameters for that child account would have the owned measurement consumer field set, meaning it would also become an owner of that measurement consumer upon account activation. If it is not set, then it will not become an owner of a measurement consumer upon account activation.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/353#-MoER6xCEwOzdf2EnbhN:-MoFAWHtBpSyq4B2nlxY:b-as1ioo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26aaf6fabc66ce846398530574038015d3367f5b/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L72)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The idea is that if the owned measurement consumer is set, then the activation parameters for that child account would have the owned measurement consumer field set, meaning it would also become an owner of that measurement consumer upon account activation. If it is not set, then it will not become an owner of a measurement consumer upon account activation.
</blockquote></details>

The creator account has to own that measurement consumer though.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/353#-MoER6xCEwOzdf2EnbhN:-MoKHiq-6pRiu9-4_FzL:b-5oxucg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c19751b31c1c4a2c8b6b2d91a8b943983897991/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L72)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The creator account has to own that measurement consumer though.
</blockquote></details>

Here is the implementation of the internal create account: https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/359

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/353)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/353)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
