### PR TITLE
Fix the GKE correctnessTest deployment.

### PR DESCRIPTION
**Pull request by wangyaopw**
The test was broken since we have made plenty changes to the system.
For example, principal authority and mark variables related changes.

The PR also
1. uploaded a synthetic-labelled-events.csv for completing correctnessTest
on GKE
2. switched the order of EDP and MC creation in the resourceSetupJob to
make sure we call the kingdom public API first. Otherwise, the job may
call the internal kingdom API successfully and fail later when calling
the public API. If this happens, the retry would fail constantly since
the EDPs are already created.
3. Deleted the labels in the NetworkPolicy, since NetworkPolicy doesn't
supoort labels.

https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Fuserstory%2F619653855975

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426)* status: all files reviewed, 4 unresolved discussions (waiting on @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426#-MuMvfiC8dydkxYNikuE:-MuMvfiD59oiEOdRCSmZ:b1q4b80) (no related file):*
> Switched the order of EDP and MC creation in the resourceSetupJob to make sure we call the kingdom public API first. Otherwise, the job may call the internal kingdom API successfully and fail later when calling the public API.

Just to better understand, is the issue that the public API server might not be available yet?

---
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426#-MuMw_u770-XW3dFBv73:-MuMw_u770-XW3dFBv74:bqeiocb) (no related file):*
> Deleted the labels in the NetworkPolicy, since NetworkPolicy doesn't supoort labels.

It doesn't? I see the labels on them when I run `kubectl describe`, and `kubectl apply` doesn't complain about them.


```
$ kubectl describe networkpolicies internal-data-server-network-policy
Name:         internal-data-server-network-policy
Namespace:    default
Created on:   2022-01-19 14:20:22 -0800 PST
Labels:       app.kubernetes.io/part-of=halo-cmms
Annotations:  <none>
```

---
___
*[build/variables.bzl, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426#-MuMySA-7qOeVSDbEPZz:-MuMySA-7qOeVSDbEP_-:bzgyu2w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71a7a4c71565fff1f0facf47b32bc79ad0d47113/build/variables.bzl#L52)):*
> ```Starlark
> # Settings for Kingdom Kubernetes deployments.
> KINGDOM_K8S_SETTINGS = struct(
>     secret_name = "$(k8s_secret_name)",
> ```

Each Make var should only be defined in one struct, so it's clear when the same var is used in multiple places.
___
*[src/main/k8s/base.cue, line 309 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426#-MuMxfqI79stb2qCssNb:-MuMxfqI79stb2qCssNc:b-hviatp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c40a5e9a449df959a136e655a78ee48d44de439a/src/main/k8s/base.cue#L309)):*
> ```CUE
> 	metadata:
> 		name: "default-deny-ingress-and-egress"
> 	labels: {
> ```

I think this was just defined at the wrong level. It should be under `metadata`.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426#-MuMvfiC8dydkxYNikuE:-MuN58JP16guhGI1CItD:b9asro8) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Switched the order of EDP and MC creation in the resourceSetupJob to make sure we call the kingdom public API first. Otherwise, the job may call the internal kingdom API successfully and fail later when calling the public API.

Just to better understand, is the issue that the public API server might not be available yet?

</blockquote></details>

yep. The public API is ready after the internal API. If someone deploys the resourceSetupJob before the public API is ready. It is highly likely it will be able to create the EDPs via internal APIs but fail to create the MC via the public API. Then a later retry of the resource setup job would fail since it cannot create a EDP with the same certificate.

---
___
*[build/variables.bzl, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426#-MuMySA-7qOeVSDbEPZz:-MuN6AA097uK0Wnyooz1:b-qqepaf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71a7a4c71565fff1f0facf47b32bc79ad0d47113/build/variables.bzl#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Each Make var should only be defined in one struct, so it's clear when the same var is used in multiple places.
</blockquote></details>

Should I delete the TEST_K8S_SETTINGS, since it contains everything defined in other struct?

I am not sure if this matters, since each deployment will only use make var from a single struct.



_Code quote:_
```Starlark
TEST_K8S_SETTINGS 
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[build/variables.bzl, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426#-MuMySA-7qOeVSDbEPZz:-MuN7zkYA-YS-C_hWAdV:blbuetz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71a7a4c71565fff1f0facf47b32bc79ad0d47113/build/variables.bzl#L52)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Should I delete the TEST_K8S_SETTINGS, since it contains everything defined in other struct?

I am not sure if this matters, since each deployment will only use make var from a single struct.
</blockquote></details>

This file only exists to document/enumerate all the possible Make vars, as otherwise we would just reference the vars directly in each BUILD file.

Note that each var should be consistent across build targets. e.g. you shouldn't need to change the value of `k8s_secret_name` for Duchy targets vs. Kingdom targets. If something should be different across targets, it should have a different variable. Having it be in only one struct makes it clear when two things use the same variable.

As an aside, I'm looking into using Kustomize to avoid having to specify the secret name as a Make var.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426#-MuMw_u770-XW3dFBv73:-MuNKg3u3TJVWdPXGfjA:b7q5cff) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Deleted the labels in the NetworkPolicy, since NetworkPolicy doesn't supoort labels.

It doesn't? I see the labels on them when I run `kubectl describe`, and `kubectl apply` doesn't complain about them.


```
$ kubectl describe networkpolicies internal-data-server-network-policy
Name:         internal-data-server-network-policy
Namespace:    default
Created on:   2022-01-19 14:20:22 -0800 PST
Labels:       app.kubernetes.io/part-of=halo-cmms
Annotations:  <none>
```

</blockquote></details>

Yeah, As you have pointed out. One of the labels is defined at the wrong level. Added them back and fixed the wrong one.

---
___
*[build/variables.bzl, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426#-MuMySA-7qOeVSDbEPZz:-MuNK9g24OydXS-qr8XM:bqwi65q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71a7a4c71565fff1f0facf47b32bc79ad0d47113/build/variables.bzl#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This file only exists to document/enumerate all the possible Make vars, as otherwise we would just reference the vars directly in each BUILD file.

Note that each var should be consistent across build targets. e.g. you shouldn't need to change the value of `k8s_secret_name` for Duchy targets vs. Kingdom targets. If something should be different across targets, it should have a different variable. Having it be in only one struct makes it clear when two things use the same variable.

As an aside, I'm looking into using Kustomize to avoid having to specify the secret name as a Make var.
</blockquote></details>

Renamed them.

Note that the EDP_SIMULATOR_K8S_SETTINGS and FRONTEND_SIMULATOR_K8S_SETTINGS uses the same secret, since they are deployed in the same cluster.
___
*[src/main/k8s/base.cue, line 309 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426#-MuMxfqI79stb2qCssNb:-MuNJ7Vm8bsWu4mQQsVP:btgpbpu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c40a5e9a449df959a136e655a78ee48d44de439a/src/main/k8s/base.cue#L309)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think this was just defined at the wrong level. It should be under `metadata`.
</blockquote></details>

Yep, you are right.



_Code quote:_
```CUE
		labels: {
			"app.kubernetes.io/part-of": #AppName
		}
```

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 11 of 14 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/426)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
