### PR TITLE
Memoization for advanced composition theorem

### PR DESCRIPTION
**Pull request by uakyol**
This increases the performance of this lookup significantly.  

totalPrivacyBudgetUsageUnderAdvancedComposition works in O(repetition_count^2) and it runs this unnecessarily for all PrivacyBucketGroups that have the same charge.

It will now run O(1) for all PrivacyBucketGroups after the first calculation

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/551)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/551)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AdvancedComposition.kt` line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/551#-N1AJ3iw7B1s7tJF9GlZ:-N1AJ3iw7B1s7tJF9Gl_:b-vntrul) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44abf59f4967b83da8a3c1d36ef9861dffb0735a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AdvancedComposition.kt#L51)):*
> ```Kotlin
>   }
> 
>   private fun calculateAdvnacedComposition(
> ```

`Advanced`

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/551)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AdvancedComposition.kt` line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/551#-N1AJ3iw7B1s7tJF9GlZ:-N1AKSu39SqQOoriVigA:b-1cyu7w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44abf59f4967b83da8a3c1d36ef9861dffb0735a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AdvancedComposition.kt#L51)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`Advanced`
</blockquote></details>

thank you

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/551)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/551)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Pull request merged**
