### PR TITLE
add java_export for cross-media-measurement-eventdataprovider

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

___
*[`WORKSPACE` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1KXuuDEnoj8G9CkHCG:-N1KXuuDEnoj8G9CkHCH:bzgqxzb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc7cead0dc01b26cea5137c14428061f95eae4b0/WORKSPACE#L56)):*
> ```Starlark
> )
> 
> GRPC_JAVA_VERSION = "1.43.2"
> ```

Add a TODO to get these from common-jvm.

I worry these will go out-of-sync.



_Code quote:_
```Starlark
GRPC_JAVA_VERSION = "1.43.2"

KOTLIN_VERSION = "1.4.31"
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1KYLfz3xaIV6kKT3yB:-N1KYLg-6Aq60oBfzlIg:b-4rgyrs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc7cead0dc01b26cea5137c14428061f95eae4b0/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L15)):*
> ```Starlark
>     name = "eventdataprovider",
>     runtime_deps = [
>         "//src/main/kotlin/org/wfanet/measurement/api/v2alpha:event_data_classes",
> ```

Listing out all the transitive dependencies here is a maintenance nightmare.

I think if you just have this library export the `event_filters` and `privacy_budget_manager` libraries, you should be set.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1KZFAS2jWDCvWhxqu4:-N1KZCQ25lU9fIzh3s4c:b-2mtjpz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc7cead0dc01b26cea5137c14428061f95eae4b0/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L44)):*
> ```Starlark
>     ],
> )
> ```

Did you want another library for the postgres backing store? It'd have to exclude the PBM library dep and swap in a maven dep for it instead to depend on the exported Maven version.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1KYLfz3xaIV6kKT3yB:-N1iGYRc7Juf8X8gDRJp:bwb7gcc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc7cead0dc01b26cea5137c14428061f95eae4b0/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Listing out all the transitive dependencies here is a maintenance nightmare.

I think if you just have this library export the `event_filters` and `privacy_budget_manager` libraries, you should be set.
</blockquote></details>

these are all the deps that the edpsimulator currently requires. It needs a lot of what is listed here: grpc proto stuff, any sketch, stuff for identity, event_templates, etc. I can slim it down a little if you want. For example, I think it should include all the grpc resources for making api calls.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1KZFAS2jWDCvWhxqu4:-N1P5YRwDePOB29zKliU:b92ac0m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc7cead0dc01b26cea5137c14428061f95eae4b0/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Did you want another library for the postgres backing store? It'd have to exclude the PBM library dep and swap in a maven dep for it instead to depend on the exported Maven version.
</blockquote></details>

yeah - I was just going to pack it in to this main dep. Its not an exhaustive list yet but I can put it in now.

I was also planning a follow-up with a testing package.

Done.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`WORKSPACE` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1KXuuDEnoj8G9CkHCG:-N1jJ-Tw5D_JzAqR6o7e:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc7cead0dc01b26cea5137c14428061f95eae4b0/WORKSPACE#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add a TODO to get these from common-jvm.

I worry these will go out-of-sync.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1KYLfz3xaIV6kKT3yB:-N1jnAiIDGNpZcfOg3VS:b-leg16l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc7cead0dc01b26cea5137c14428061f95eae4b0/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L15)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

these are all the deps that the edpsimulator currently requires. It needs a lot of what is listed here: grpc proto stuff, any sketch, stuff for identity, event_templates, etc. I can slim it down a little if you want. For example, I think it should include all the grpc resources for making api calls.
</blockquote></details>

What I mean is that we don't want to have to re-list all of our transitive deps here. Bazel should already have all the information it needs to figure that out.

I believe we can just include the top-level libraries that we want in the `exports` attr of this java_library.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1KZFAS2jWDCvWhxqu4:-N1joUdP-3QCO3ushf1t:b-bi8uny) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc7cead0dc01b26cea5137c14428061f95eae4b0/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L44)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - I was just going to pack it in to this main dep. Its not an exhaustive list yet but I can put it in now.

I was also planning a follow-up with a testing package.

Done.
</blockquote></details>

There should be no dependencies on any specific DB in this library. The whole point of having the separate `deploy` package tree is to separate out different implementations with their own dependencies.

If we want to export the postgres backing store (which I assume we do), it should be as a separate library (Maven artifact).

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1KYLfz3xaIV6kKT3yB:-N1k04ym3A49wX9L3x69:b-eiykt4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc7cead0dc01b26cea5137c14428061f95eae4b0/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What I mean is that we don't want to have to re-list all of our transitive deps here. Bazel should already have all the information it needs to figure that out.

I believe we can just include the top-level libraries that we want in the `exports` attr of this java_library.
</blockquote></details>

almost none of these are transitive in existing deps on that list. Do you have certain umbrella deps in mind instead? I slimmed down the list slightly and went through them one by one.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1KZFAS2jWDCvWhxqu4:-N1k0qdI7l7319hyAQPI:b-ozt8gv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc7cead0dc01b26cea5137c14428061f95eae4b0/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There should be no dependencies on any specific DB in this library. The whole point of having the separate `deploy` package tree is to separate out different implementations with their own dependencies.

If we want to export the postgres backing store (which I assume we do), it should be as a separate library (Maven artifact).
</blockquote></details>

added a separate one.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1KYLfz3xaIV6kKT3yB:-N1k2Dma9QuvGzGmCIUZ:b-1z8kj0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc7cead0dc01b26cea5137c14428061f95eae4b0/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L15)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

almost none of these are transitive in existing deps on that list. Do you have certain umbrella deps in mind instead? I slimmed down the list slightly and went through them one by one.
</blockquote></details>

I'm not certain what you mean by these not being transitive existing deps. We want to list no deps at all and just export the relevant top-level libraries under this package. We want to get Bazel to do the work of figuring out the transitive deps for us.

I believe if the java_library is just

```
java_library(
    name = "eventdataprovider",
    exports = [
        "//src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration:event_filters",
        "//src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement:privacy_budget_manager",
    ]
)
```

then java_export should pick things up
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1k3P9Q1OUKl_S4G4P4:-N1k3P9Q1OUKl_S4G4P5:bocdj8y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24d6b2bdc1e30c754ba18091a31ebcf1dcd5dfaf/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L62)):*
> ```Starlark
> java_export(
>     name = "maven-postgres",
>     deploy_env = cross_media_measurement_maven_deploy_env(),
> ```

Need to exclude the eventdataprovider Bazel deps and instead depend on the exported maven artifact. Otherwise this exported JAR will contain the contents of the other one.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N1KYLfz3xaIV6kKT3yB:-N1k5K7TEZFDyK9EnOdW:b-8ypw8r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc7cead0dc01b26cea5137c14428061f95eae4b0/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not certain what you mean by these not being transitive existing deps. We want to list no deps at all and just export the relevant top-level libraries under this package. We want to get Bazel to do the work of figuring out the transitive deps for us.

I believe if the java_library is just

```
java_library(
    name = "eventdataprovider",
    exports = [
        "//src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration:event_filters",
        "//src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement:privacy_budget_manager",
    ]
)
```

then java_export should pick things up
</blockquote></details>

To clarify further, this library should *only* include the libraries in the eventdataprovider tree and their transitive deps.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N2mzNjMDIuO2gBboe1b:-N2mzNjMDIuO2gBboe1c:b-oxhkbo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/053f149fe538f0601c87944a7367c570708302d1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L22)):*
> ```Starlark
> 
> java_library(
>     name = "api",
> ```

Hmm, I hadn't considered ever exporting the generated Java protobuf libraries to Maven. If we're going to do this, we should move the java/kt_jvm library targets to the cross-media-measurement-api and export to Maven from there.

I think we had originally assumed that everyone would just grab the proto files and use things from source.



_Code quote:_
```Starlark
    name = "api",
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 24 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N2n-uv21j1yyCc5wNAj:-N2n-uv21j1yyCc5wNAk:bodtd9r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/053f149fe538f0601c87944a7367c570708302d1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L24)):*
> ```Starlark
>     name = "api",
>     runtime_deps = [
>         "//src/main/kotlin/org/wfanet/measurement/api/v2alpha:event_templates",
> ```

I don't believe these libraries were intended to be used outside of this repo.



_Code quote:_
```Starlark
        "//src/main/kotlin/org/wfanet/measurement/api/v2alpha:event_templates",
        "//src/main/kotlin/org/wfanet/measurement/api/v2alpha:resource_key",
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N2myz3h6avlVlj_dCxk:-N2myz3h6avlVlj_dCxl:bhod7ai) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/053f149fe538f0601c87944a7367c570708302d1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L42)):*
> ```Starlark
>         "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common",
>         "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common/crypto:key_storage",
>         "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common/grpc",
> ```

Each library should be exported from the Bazel package that encompasses the targets. That means that libraries from another repo should be exported by that repo.

Note that it's also not this simple to properly export Maven artifacts that depend on each other, as it involves making sure that each artifact depends on the Maven versions of the other artifacts rather than the versions built from source. This is doable for simple cases in a single leaf library via `deploy_env`, but that quickly becomes unmaintainable once dependencies are being exported.

The proper way involves actually restructuring the Bazel library targets to depend on the `java_export` targets. This includes making sure that nobody accidentally depends on the more granular targets by changing their visibility to private, and only having the `java_export` versions be visible.



_Code quote:_
```Starlark
java_library(
    name = "common",
    runtime_deps = [
        "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common",
        "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common/crypto:key_storage",
        "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common/grpc",
        "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common/identity",
        "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common/throttler",
        "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/storage:client",
    ],
)

java_library(
    name = "consent",
    runtime_deps = [
        "@wfa_consent_signaling_client//src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider",
    ],
)
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 64 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N2n-eUPEi5nJOYC6_w7:-N2n-eUPEi5nJOYC6_w8:b4lngac) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/053f149fe538f0601c87944a7367c570708302d1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L64)):*
> ```Starlark
> 
> java_library(
>     name = "sketch",
> ```

I don't think this would be usable as a Maven JAR due to how we do our JNI. We'd need to make sure the native library can be loaded from a location that's embedded in the JAR. I think rules_swig currently has the java_library depend on the native library as a runtime dep rather than a resource. Changing this would involve also changing usage of `org.wfanet.measurement.common.loadLibrary`.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel` line 136 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/554#-N2n0XB364_DUNj3viom:-N2n0XB364_DUNj3vion:bvxho6b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/053f149fe538f0601c87944a7367c570708302d1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/BUILD.bazel#L136)):*
> ```Starlark
> 
> java_export(
>     name = "maven-all",
> ```

Given that these come from multiple repos, I don't think we should have an "all".



_Code quote:_
```Starlark
"maven-all",
```

**Pull request closed without merging**
