### PR TITLE
Fix that only allows creation of ModelRollouts with RolloutPeriodStartTime after that of previous ModelRollout

### PR DESCRIPTION
**Pull request by jojijac0b**
Update query in readModelRolloutData to return the ModelRollout for a given ModelLine with the latest RolloutPeriodStartTime in CreateModelRollout.kt. Update CreateModelRollout.kt to throw ModelRolloutInvalidArgsException if the RolloutPeriodStartTime of the ModelRollout to be created precedes that of the last ModelRollout. Create tests in ModelRolloutServiceTest.kt. Update 'createModelRollout succeeds with multiple model releases' test to adhere to new RolloutPeriodStartTime limitations.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NY_1vn22PO0axbswaGy:-NY_1vn22PO0axbswaGz:b-ohds77) (no related file):*
Would you mind also documenting this restriction in the API definition?

___
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 183 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NY_2sus0NfwaLSHu2QV:-NY_2sus0NfwaLSHu2QW:b-y5xcht) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a70396a438f88c884bd010bfffa5b450bc9ff719/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L183)):*
> ```Kotlin
>   }
> 
>   private suspend fun TransactionScope.readModelRolloutData(
> ```

Perhaps this should be renamed to indicate that it's reading data for some previous ModelRollout? Also document what is meant by "previous" since that can be ambiguous. It looks like in this case it means the one for the given ModelLine with the least recent RolloutPeriodStartTime.



_Suggestion:_
```Kotlin
readPreviousModelRolloutData
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 187 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NY_3hZF0_v4g_ImPd0a:-NY_3hZF0_v4g_ImPd0b:b-l67zjb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a70396a438f88c884bd010bfffa5b450bc9ff719/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L187)):*
> ```Kotlin
>     externalModelSuiteId: ExternalId,
>     externalModelLineId: ExternalId,
>   ): Struct? {
> ```

nit: Prefer converting to some more specific type immediately rather than consuming a free-from structure like `Struct`. e.g. create a private data class for this purpose.



_Code quote:_
```Kotlin
Struct
```

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NY_1vn22PO0axbswaGy:-NYdlzDL7zAywdYnK50z:b4pm3eg) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Would you mind also documenting this restriction in the API definition?
</blockquote></details>

Commented limitation in API definition in model_rollouts_service.proto

___
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 183 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NY_2sus0NfwaLSHu2QV:-NYdmC5r7xCJ5Ppsz2cG:b-3us1zq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a70396a438f88c884bd010bfffa5b450bc9ff719/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L183)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Perhaps this should be renamed to indicate that it's reading data for some previous ModelRollout? Also document what is meant by "previous" since that can be ambiguous. It looks like in this case it means the one for the given ModelLine with the least recent RolloutPeriodStartTime.
</blockquote></details>

Renamed to readLatestModelRolloutData to reflect the query returning the ModelRollout with the latest RolloutPeriodStartTime.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 187 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NY_3hZF0_v4g_ImPd0a:-NYdmMbK3_UytXkEBilu:bh69iwd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a70396a438f88c884bd010bfffa5b450bc9ff719/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L187)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Prefer converting to some more specific type immediately rather than consuming a free-from structure like `Struct`. e.g. create a private data class for this purpose.
</blockquote></details>

Created data class LatestModelRolloutResult

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NY_1vn22PO0axbswaGy:-NYe0xUn1pkw0ZkdDIY8:b-dg8rkl) (no related file):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Commented limitation in API definition in model_rollouts_service.proto
</blockquote></details>

I had meant a follow-up PR in the public API definition in the cross-media-measurement-api repo.

___
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_rollouts_service.proto` line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NYe15AF4pHAvC1ZPd5q:-NYe15AF4pHAvC1ZPd5r:b-c9gcxx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37edadf08bdb7009577350370d81be881beecaef/src/main/proto/wfa/measurement/internal/kingdom/model_rollouts_service.proto#L27)):*
> ```proto
> // Internal service for persistence of ModelRollout entities.
> service ModelRollouts {
>   // rollout_period_start_time of given `ModelRollout` must be later than that
> ```

Documentation should start with a summary fragment. e.g. "Creates a new `ModelRollout`."

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelRolloutsServiceTest.kt` line 1051 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NYqihMaDksnChdwGtAF:-NYqihMaDksnChdwGtAG:b8x0uln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37edadf08bdb7009577350370d81be881beecaef/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelRolloutsServiceTest.kt#L1051)):*
> ```Kotlin
> 
>   @Test
>   fun `createModelRollout succeeds with multiple model releases`() = runBlocking {
> ```

nit ```multiple model rollouts```



_Code quote:_
```Kotlin
model releases
```

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NYsUHelC1iWppJg4KVj:-NYsS_RD2wRLeoLD9D3o:bssl9er) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5a8c664cb8e81b216dc4db6943a064d7c6a994d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L76)):*
> ```Kotlin
> 
>     val latestModelRolloutData =
>       if (modelRollout.rolloutPeriodStartTime != modelRollout.rolloutPeriodEndTime) {
> ```

How does this case work with the restriction? Instant rollouts can be scheduled whenever? I am thinking about when an instant rollout is scheduled before the latest gradual rollout so the latest gradual rollout still has its previous rollout as the rollout before the instant rollout. If instant rollouts can be scheduled whenever, should the rollout right after the instant rollout have its previous rollout updated to be the instant rollout?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NYsUHelC1iWppJg4KVj:-NYskdj_9kqxK8eRUteC:btjbu61) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5a8c664cb8e81b216dc4db6943a064d7c6a994d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L76)):*
As an aside, I want to call out that TimeInterval had incorrect documentation added in https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/130. The meaning of TimeInterval did *not* change in that PR, meaning this line is incorrect: 

> If equal it represents an exact point in time.

TimeInterval was just our own version of google.type.Interval, which had not yet been published when we initially created the API definition. See https://github.com/world-federation-of-advertisers/cross-media-measurement-api/issues/151

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NYsUHelC1iWppJg4KVj:-NYslZWBBpyLIogKDD9P:b-ihyh3w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5a8c664cb8e81b216dc4db6943a064d7c6a994d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L76)):*
Relevant line from the google.type.Interval documentation:

> When the start equals the end, the interval is empty (matches no time).

**Comment by Marco-Premier** [comment]
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NYsUHelC1iWppJg4KVj:-NYsm0QqCmPoAlOvS_7R:b6j5i7k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5a8c664cb8e81b216dc4db6943a064d7c6a994d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Relevant line from the google.type.Interval documentation:

> When the start equals the end, the interval is empty (matches no time).
</blockquote></details>

That is true @tristanvuong2021 .
Instant rollouts cannot be schedule whenever. They must follow the same logic for rollouts with ```rollout_period```.
@jojijac0b  this should become:

```
val latestModelRolloutData =
  readLatestModelRolloutData(
  ExternalId(modelRollout.externalModelProviderId),
  ExternalId(modelRollout.externalModelSuiteId),
  ExternalId(modelRollout.externalModelLineId)
)
```

Previous model rollout should never be updated.

**Comment by Marco-Premier** [comment]
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NYsUHelC1iWppJg4KVj:-NYsnk1V7ksJq2Gi17Xa:b-lidkjc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5a8c664cb8e81b216dc4db6943a064d7c6a994d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L76)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

That is true @tristanvuong2021 .
Instant rollouts cannot be schedule whenever. They must follow the same logic for rollouts with ```rollout_period```.
@jojijac0b  this should become:

```
val latestModelRolloutData =
  readLatestModelRolloutData(
  ExternalId(modelRollout.externalModelProviderId),
  ExternalId(modelRollout.externalModelSuiteId),
  ExternalId(modelRollout.externalModelLineId)
)
```

Previous model rollout should never be updated.



</blockquote></details>

@SanjayVas this means that once we merge PR #151 we cannot rely on ```modelRollout.rolloutPeriodStartTime != modelRollout.rolloutPeriodEndTime``` anymore. I'd suggest to add a new field in public api ```instant_rollout_time``` which is REQUIRED only when ```timeInterval``` is not provided. What do you think?

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NYsUHelC1iWppJg4KVj:-NYtGs5HBfN0h4j1LqGQ:b21gkd8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5a8c664cb8e81b216dc4db6943a064d7c6a994d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, a `oneof` where you either have a rollout period or a rollout time sounds correct.

Note that there's not actually a PR yet for https://github.com/world-federation-of-advertisers/cross-media-measurement-api/issues/151. Rather, I'm stating that https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/130 introduced a documentation bug where the documentation does not match the previous meaning/usage of `TimeInterval`.
</blockquote></details>

Done. Instant ModelRollouts will now be treated as regular ModelRollouts.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NYsUHelC1iWppJg4KVj:-NYwMgJa75wrD97dLi0n:b-3j3tzr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5a8c664cb8e81b216dc4db6943a064d7c6a994d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L76)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Done. Instant ModelRollouts will now be treated as regular ModelRollouts.
</blockquote></details>

Ok @SanjayVas . I'd say we can wait for the PR to replace ```TimeInterval``` to fix both: logic and documentation.
LMK if you disagree.
thanks

**Comment by Marco-Premier** [comment]
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NYsUHelC1iWppJg4KVj:-NYwlhpR5_91eej8POOK:b-zbdz2h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5a8c664cb8e81b216dc4db6943a064d7c6a994d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L76)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Ok @SanjayVas . I'd say we can wait for the PR to replace ```TimeInterval``` to fix both: logic and documentation.
LMK if you disagree.
thanks
</blockquote></details>

Otherwise we can simply fix this on a separate PR and introduce the ```oneof```

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NYsUHelC1iWppJg4KVj:-NYyzjCt4FUp0nebloLl:b4z2mql) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5a8c664cb8e81b216dc4db6943a064d7c6a994d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L76)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Otherwise we can simply fix this on a separate PR and introduce the ```oneof```
</blockquote></details>

I think the documentation for TimeInterval should be fixed now, which necessitates the introduction of a `oneof` for this case. Swapping from TimeInterval to google.type.Interval after that should be trivial.

**Review by Marco-Premier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt` line 76 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1076#-NYsUHelC1iWppJg4KVj:-NZ0yB6N2-ciTq979b74:b-jrj7tr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5a8c664cb8e81b216dc4db6943a064d7c6a994d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think the documentation for TimeInterval should be fixed now, which necessitates the introduction of a `oneof` for this case. Swapping from TimeInterval to google.type.Interval after that should be trivial.
</blockquote></details>

Created PR for  it: https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/154

**Pull request merged**
