### PR TITLE
Update cross-media-measurement-api dep for API version fields.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1298)

**Comment by SanjayVas** [comment]
Depends on https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/184

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
i'm under the assumption this doesn't need review in lieu of the subsequent PR that uses typeUrl instead

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1298#-:-NhTXMCP0cXj45rJam56:bqlou73)* status: 0 of 68 files reviewed, all discussions resolved

**Comment by SanjayVas** [comment]
Correct. This is superceded by #1306

**Pull request closed without merging**
