### PR TITLE
Run docker containers as nonroot

### PR DESCRIPTION
**Pull request by oliver-amzn**
`distroless` containers run as root but [have a non-root user build in by default](https://github.com/bazelbuild/rules_docker/issues/1678).

We can try to pull in `nonroot` tagged images for our docker images or set the user to `nonroot`. I went with the later option but ran into issues.

Paging the bazel experts @wangyaopw @efoxepstein @SanjayVas  - I tried adding a new `container_image` rule that we can use as the base but when building bazel complains with
```
	File "/local/home/ohardt/cdd2/Users/ohardt/workplace/WFA/cross-media-measurement/src/main/docker/java_image_base_nonroot.bzl", line 3, column 16, in <toplevel>
		container_image(
	File "/local/home/ohardt/.cache/bazel/_bazel_ohardt/a80ab98a267f72a094ee67d1306318a3/external/io_bazel_rules_docker/container/image.bzl", line 875, column 21, in container_image
		container_image_(**kwargs)
Error in container_image_: Cannot instantiate a rule when loading a .bzl file. Rules may be instantiated only in a BUILD thread.
```

Any suggestions on where can/should I put the base container image rule so it's not failing?

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/docker/java_image_base_nonroot.bzl, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-MkiCsGYCYb2GSwDz54f:-MkiCsGYCYb2GSwDz54g:bt96n8c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c17648ff1dcc43c4609ebe789e866093239074f9/src/main/docker/java_image_base_nonroot.bzl#L1)):*
> ```Starlark
> load("@io_bazel_rules_docker//container:container.bzl", "container_image")
> ```

Just move this into `BUILD.bazel` and then you'll just add to your `java_image` rules:

```
java_image(
  name = "...",
  base = "//src/main/docker:java_image_base_nonroot",
  ...
)
```

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/docker/java_image_base_nonroot.bzl, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-MkiCsGYCYb2GSwDz54f:-MkiD9fb2a1bresQx9fW:b-6dians) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c17648ff1dcc43c4609ebe789e866093239074f9/src/main/docker/java_image_base_nonroot.bzl#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Just move this into `BUILD.bazel` and then you'll just add to your `java_image` rules:

```
java_image(
  name = "...",
  base = "//src/main/docker:java_image_base_nonroot",
  ...
)
```
</blockquote></details>

(by "this", I mean the full contents of this file)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-MkiDPM8EnFpGLcj5AHT:-MkiDPM8EnFpGLcj5AHU:b-pqw4zj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c17648ff1dcc43c4609ebe789e866093239074f9/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel#L31)):*
> ```Starlark
> java_image(
>     name = "async_computation_control_server_image",
>     base = ":java_image_base_nonroot",
> ```

It seems like it would be easy to accidentally leave this off.

Should we add something to enforce that our images don't run as root? For example:

* A GitHub action to validate this?
* A wrapper macro around `java_image` that we use instead that sets the base correctly?
* Runtime checks in our `main` methods?

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-MkiDPM8EnFpGLcj5AHT:-MkiGYCLDLCBxAEtu1dC:b-o9bttm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c17648ff1dcc43c4609ebe789e866093239074f9/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It seems like it would be easy to accidentally leave this off.

Should we add something to enforce that our images don't run as root? For example:

* A GitHub action to validate this?
* A wrapper macro around `java_image` that we use instead that sets the base correctly?
* Runtime checks in our `main` methods?
</blockquote></details>

That's a good suggestion. I don't know how to do this in a Github Action but a wrapper around `java_image` would work. Not sure I like runtime checks in main, the executable shouldn't have to worry about this.

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-MkiDPM8EnFpGLcj5AHT:-MkiUqZHCEahTu3npjfK:b-419bcb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c17648ff1dcc43c4609ebe789e866093239074f9/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel#L31)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

That's a good suggestion. I don't know how to do this in a Github Action but a wrapper around `java_image` would work. Not sure I like runtime checks in main, the executable shouldn't have to worry about this.
</blockquote></details>

In that case, put something like this in a `.bzl` file:

```
fun java_image_nonroot(**kwargs):
  java_image(base = "//src/main/docker:java_image_base_nonroot", **kwargs)
```

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-MkiDPM8EnFpGLcj5AHT:-MkmpgDD3rBDUxGvXkJD:bxb3frh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c17648ff1dcc43c4609ebe789e866093239074f9/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In that case, put something like this in a `.bzl` file:

```
fun java_image_nonroot(**kwargs):
  java_image(base = "//src/main/docker:java_image_base_nonroot", **kwargs)
```
</blockquote></details>

The java_image rule from rules_docker by default uses targets named `java_image_base` and `java_debug_image_base` when the `base` attribute isn't specified. We have our own targets for these [defined in `common_jvm`](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/build/io_bazel_rules_docker/base_images.bzl).

If you just rename things such that your custom image targets have the right names, you need not specify the base for each `java_image` target.

That said, I'm not actually sure that the `user` from `base` gets used here at all. It may instead be that we need to specify the user in each java_image target.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-MkiDPM8EnFpGLcj5AHT:-MknFhACEVlkJLWyNU7d:byqdh76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c17648ff1dcc43c4609ebe789e866093239074f9/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The java_image rule from rules_docker by default uses targets named `java_image_base` and `java_debug_image_base` when the `base` attribute isn't specified. We have our own targets for these [defined in `common_jvm`](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/build/io_bazel_rules_docker/base_images.bzl).

If you just rename things such that your custom image targets have the right names, you need not specify the base for each `java_image` target.

That said, I'm not actually sure that the `user` from `base` gets used here at all. It may instead be that we need to specify the user in each java_image target.
</blockquote></details>

So probably a macro is best?

```
fun java_image_nonroot(**kwargs):
  java_image(user = "nonroot", **kwargs)
```

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[src/main/docker/java_image_base_nonroot.bzl, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-MkiCsGYCYb2GSwDz54f:-Mkmnfe7EbOXr1yktv8J:bi6dq5j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c17648ff1dcc43c4609ebe789e866093239074f9/src/main/docker/java_image_base_nonroot.bzl#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

(by "this", I mean the full contents of this file)
</blockquote></details>

Nais - thanks!
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-MkiDPM8EnFpGLcj5AHT:-Mkmnjj-D5XL9fpyq5Jt:bj94jv8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c17648ff1dcc43c4609ebe789e866093239074f9/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

So probably a macro is best?

```
fun java_image_nonroot(**kwargs):
  java_image(user = "nonroot", **kwargs)
```
</blockquote></details>

I can't pass `user` to `java_image` and got to take the scenic detour via `container_image` (see this link for an example: https://github.com/bazelbuild/rules_docker#go_image-custom-base). If I use the container_image with `user` specified then it should get used.

I see what you refer to in common-jvm. What tags do these shas refer to? Maybe there's a nonroot version of the image we can use (and forgo all the java_image and macro fun).

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-MkiDPM8EnFpGLcj5AHT:-MknyYeTACUI2QpXujsN:b-tank0b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c17648ff1dcc43c4609ebe789e866093239074f9/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel#L31)):*
> I can't pass user to java_image and got to take the scenic detour via container_image (see this link for an example: https://github.com/bazelbuild/rules_docker#go_image-custom-base). If I use the container_image with user specified then it should get used.

Ah, I see that you're correct.

> I see what you refer to in common-jvm. What tags do these shas refer to? Maybe there's a nonroot version of the image we can use (and forgo all the java_image and macro fun).

gcr.io/distroless. I do in fact see `11-nonroot` and `11-debug-nonroot` tags! Also we should switch to the newer images based on Debian 11, as it has a newer glibc so we can update our compatibility restrictions and build on newer versions of Linux rather than using a container. e.g. gcr.io/distroless/java-debian11:11-nonroot

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-MkiDPM8EnFpGLcj5AHT:-MkquQEM9GXcitwDy-lT:b8w54xv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c17648ff1dcc43c4609ebe789e866093239074f9/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel#L31)):*
> gcr.io/distroless/java-debian11:11-nonroot

Ok, cool, Then I'll make the change in common-jvm to use that image as the base and leave everything here as is.

**Review by oliver-amzn — COMMENTED** [review]
Updated this PR to only pull in common_jvm 0.15.0 which now has the nonroot base images.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-:-MksKdkc9xlG_c4GFwbU:b-129zd4)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
Already did that in #304 :)

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/296#-:-Mks_gq50jAGGSnFks2o:b93gi4r)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

**Comment by oliver-amzn** [comment]
IMG_6015

**Pull request closed without merging**
