### PR TITLE
Add metrics to local kind

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: 0 of 25 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/k8s/local/README.md` line 327 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NBy5rbl7vDlF5G9dVD_:-NBy5rbl7vDlF5G9dVDa:b-mbzhc8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55659bd9377b35f98207dc185f9f417a49ce22a3/src/main/k8s/local/README.md#L327)):*
> ```Markdown
> ```
> 
> To be able to visit the Prometheus browser GUI at http://localhost:31111/, 
> ```

I think you can just use the `kubectl port-forward` command rather than having to expose it on the node/host.



_Code quote:_
```Markdown
To be able to visit the Prometheus browser GUI at http://localhost:31111/,
add the following to the KiND config.
```shell
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31111
    hostPort: 31111
    listenAddress: "0.0.0.0"
    protocol: tcp
```
```


<!-- Sent from Reviewable.io -->

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/local/README.md` line 327 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NBy5rbl7vDlF5G9dVD_:-NC12tzu07BdSoUu9lAn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55659bd9377b35f98207dc185f9f417a49ce22a3/src/main/k8s/local/README.md#L327)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think you can just use the `kubectl port-forward` command rather than having to expose it on the node/host.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 13 of 25 files at r1, 6 of 14 files at r2, 1 of 4 files at r4, 5 of 5 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: all files reviewed, 7 unresolved discussions (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6lwVN4Y-YudmXRaQQ:-NC6lwVO1jsQOlAeHBx9:bmf2md3) (no related file):*
Would using the [OpenTelemetry K8s Operator](https://github.com/open-telemetry/opentelemetry-operator/) simplify this? We theoretically just need to add one `OpenTelemetryCollector` per cluster, and supposedly can handle sidecar injection for us.

___
___
*[`WORKSPACE` line 29 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6_ajk86eEkGj0yAfC:-NC6_ajk86eEkGj0yAfD:b-ug0yyd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be7b9a69d0e532fd734f574b546557b94ef17814/WORKSPACE#L29)):*
> ```Starlark
> load("//build/open_telemetry_java_agent:repo.bzl", "open_telemetry_java_agent")
> 
> open_telemetry_java_agent()
> ```

nit: I think this should go into `wfa_measurement_system_repositories` if in this repo, though it may be better to add this in common-jvm and just include the file in our java base images. That way it will get included in all java_image targets.
___
*[`src/main/k8s/base.cue` line 99 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6gAqVC6rlA6xFn3hh:-NC6gAqVC6rlA6xFn3hi:b-lonf4g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be7b9a69d0e532fd734f574b546557b94ef17814/src/main/k8s/base.cue#L99)):*
> ```CUE
> 	maxCachedBufferSize:   uint | *262144 // 256KiB
> 	nettyMaxDirectMemory?: int
> 	additionalOptions: [...string]
> ```

The general problem with having lists like this here is that they prevent extension as the CUE union operation can't extend lists.

Perhaps something like this instead:

`openTelemetryAgentOptions?: #OpenTelemetryAgentOptions`

and then in `options`:
```cue
if (openTelemetryAgentOptions != _|_) {
  for option in openTelemetryAgentOptions.options {option}
}
```
___
*[`src/main/k8s/base.cue` line 237 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6bSF00seyYUPZiCex:-NC6bJda3s1WCQ0NhMGy:bmddjx7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be7b9a69d0e532fd734f574b546557b94ef17814/src/main/k8s/base.cue#L237)):*
> ```CUE
> 	apiVersion: "v1"
> 	kind:       "ConfigMap"
> 	metadata:   Metadata=#ObjectMeta & {
> ```

This is basically copying some legacy behavior.

We don't need a `system` annotation. I've been trying to replace its usage with the standard `app.kubernetes.io/component` annotation instead, and use the term "component" in new code rather than "system".

Additionally we don't need a top-level `_name` field. Anyone using this can just set `metadata.name` directly instead.
___
*[`src/main/k8s/base.cue` line 276 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6c3Ff945l12Q4mVLI:-NC6c3Ff945l12Q4mVLJ:b-pox95o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be7b9a69d0e532fd734f574b546557b94ef17814/src/main/k8s/base.cue#L276)):*
This undoes part of #659:
> Refactor definitions to be closer to K8s API.

The idea is to have anyone using the definitions to set the right fields of the K8s resource when possible. We only use hidden fields like this when that would be too difficult if not impossible (e.g. using hidden maps to build lists, or using a single field to drive additional behavior).



_Code quote:_
```CUE
	_name:      string
	_system:    string
```
___
*[`src/main/k8s/base.cue` line 420 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6deO-5kRUt29OP25G:-NC6deO-5kRUt29OP25H:bifu6hv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be7b9a69d0e532fd734f574b546557b94ef17814/src/main/k8s/base.cue#L420)):*
> ```CUE
> 		}
> 	}
> 	_sidecarContainers: [...#Container]
> ```

We don't need this. It's already covered by #PodSpec._containers.



_Code quote:_
```CUE
	_sidecarContainers: [...#Container]
```
___
*[`src/main/k8s/base.cue` line 422 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6fHJnDDocG8GiNHWa:-NC6fHJnDDocG8GiNHWb:b-hah0ej) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be7b9a69d0e532fd734f574b546557b94ef17814/src/main/k8s/base.cue#L422)):*
> ```CUE
> 	_sidecarContainers: [...#Container]
> 	_sidecarMounts: [...#Mount]
> ```

We don't need this. #PodSpec._volumes and the specific container's `_volumeMounts` should be used instead.



_Code quote:_
```CUE
_sidecarMounts: [...#Mount]
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: all files reviewed, 7 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6lwVN4Y-YudmXRaQQ:-NC78L0CDa-nrepPJ9kH:b-6citjx) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Would using the [OpenTelemetry K8s Operator](https://github.com/open-telemetry/opentelemetry-operator/) simplify this? We theoretically just need to add one `OpenTelemetryCollector` per cluster, and supposedly can handle sidecar injection for us.
</blockquote></details>

I tried this initially, but couldn't get the cert-manager to install.

___

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: 2 of 27 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6lwVN4Y-YudmXRaQQ:-NCQoOMQEQGgRam_SKJD:bvtq8b8) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I tried this initially, but couldn't get the cert-manager to install.
</blockquote></details>

Managed to convert it to using the open telemetry operator.

___
___
*[`src/main/k8s/base.cue` line 237 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6bSF00seyYUPZiCex:-NCMIrtdAiZzcWyaRazV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be7b9a69d0e532fd734f574b546557b94ef17814/src/main/k8s/base.cue#L237)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is basically copying some legacy behavior.

We don't need a `system` annotation. I've been trying to replace its usage with the standard `app.kubernetes.io/component` annotation instead, and use the term "component" in new code rather than "system".

Additionally we don't need a top-level `_name` field. Anyone using this can just set `metadata.name` directly instead.
</blockquote></details>

Done.
___
*[`src/main/k8s/base.cue` line 276 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6c3Ff945l12Q4mVLI:-NCMJtaM-z2jHRdl6icb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be7b9a69d0e532fd734f574b546557b94ef17814/src/main/k8s/base.cue#L276)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This undoes part of #659:
> Refactor definitions to be closer to K8s API.

The idea is to have anyone using the definitions to set the right fields of the K8s resource when possible. We only use hidden fields like this when that would be too difficult if not impossible (e.g. using hidden maps to build lists, or using a single field to drive additional behavior).
</blockquote></details>

Done.
___
*[`src/main/k8s/base.cue` line 420 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6deO-5kRUt29OP25G:-NCLpunSBcluAHr0_YWL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be7b9a69d0e532fd734f574b546557b94ef17814/src/main/k8s/base.cue#L420)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We don't need this. It's already covered by #PodSpec._containers.
</blockquote></details>

Done.
___
*[`src/main/k8s/base.cue` line 422 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NC6fHJnDDocG8GiNHWa:-NCMDHzEA2eBYYRwQxjz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be7b9a69d0e532fd734f574b546557b94ef17814/src/main/k8s/base.cue#L422)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We don't need this. #PodSpec._volumes and the specific container's `_volumeMounts` should be used instead.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 16 of 25 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: 18 of 27 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/k8s/base.cue` line 219 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCRwWPGCF_49SM4-K2H:-NCRwWPGCF_49SM4-K2I:by37jpk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/base.cue#L219)):*
> ```CUE
> 	apiVersion: "v1"
> 	kind:       "ConfigMap"
> 	metadata:   Metadata=#ObjectMeta & {
> ```

Just

```cue
metadata: #ObjectMeta
```

since what you're specifying here is already in the `#ObjectMeta` definition



_Code quote:_
```CUE
	metadata:   Metadata=#ObjectMeta & {
		_component: string
		name:       string
		annotations: "component": Metadata._component
	}
```
___
*[`src/main/k8s/base.cue` line 257 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCRwkRu4ci0LMFs0pJi:-NCRwkRu4ci0LMFs0pJj:b-qgcmol) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/base.cue#L257)):*
> ```CUE
> 	kind:       "Service"
> 	metadata:   Metadata=#ObjectMeta & {
> 		_component: string
> ```

These are already defined in `#ObjectMeta`



_Code quote:_
```CUE
		_component: string
		name:       string
```
___
*[`src/main/k8s/base.cue` line 407 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCRxVLsD3BlknftRllm:-NCRxVLsD3BlknftRlln:b-pmuej3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/base.cue#L407)):*
> ```CUE
> 			metadata: {
> 				labels: app: _name + "-app"
> 				annotations: {
> ```

Any reason why we can't just do this at the namespace level?

e.g.

```shell
kubectl annotate namespaces default 'sidecar.opentelemetry.io/inject'=true
kubectl annotate namespaces default 'instrumentation.opentelemetry.io/inject-java'=true
```

I assume we also don't need the container-names annotation, as we just want to instrument everything. We can always add a false annotation on anything we don't want to instrument as-needed. I don't think we care what the injected sidecar container is named either, since container names only need to be unique within a given pod.
___
*[`src/main/k8s/open_telemetry_collector.cue` line 17 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCS12M99cUJQDlg3IZf:-NCS12M99cUJQDlg3IZg:b-icli2v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/open_telemetry_collector.cue#L17)):*
> ```CUE
> package k8s
> 
> #OpenTelemetryCollector: {
> ```

I don't think we need most of this. We should theoretically just need a static `OpenTelemetryCollector` in sidecar mode and `Instrumentation`.
___
*[`src/main/k8s/open_telemetry_collector_sidecar.cue` line 17 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCS21lU78twgU2aop9y:-NCS21lU78twgU2aop9z:b-ye328r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/open_telemetry_collector_sidecar.cue#L17)):*
> ```CUE
> package k8s
> 
> #OpenTelemetryCollectorSidecar: Sidecar={
> ```

Same here. Don't think we need this anymore when using injection.

**Comment by tristanvuong2021** [comment]
*[`src/main/k8s/open_telemetry_collector_sidecar.cue` line 17 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCS21lU78twgU2aop9y:-NCWKy6p8K9fCxbH4cfS:bed4nq8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/open_telemetry_collector_sidecar.cue#L17)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I was thinking of having different sidecars in case we needed to change the config individually.
</blockquote></details>

I could keep it in case a deployment needs a different config, but use a default sidecar otherwise

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 25 files at r8, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/k8s/open_telemetry_collector_sidecar.cue` line 17 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCS21lU78twgU2aop9y:-NCWUs7fCveVkuFb8Pjc:bmqy86v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/open_telemetry_collector_sidecar.cue#L17)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I could keep it in case a deployment needs a different config, but use a default sidecar otherwise
</blockquote></details>

Let's follow the YAGNI principle here. If we end up needing to deal with specific configurations, we can add it in then.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: 16 of 27 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/base.cue` line 407 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCRxVLsD3BlknftRllm:-NCWXMg06mSv1p48-ubt:bq11hy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/base.cue#L407)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Any reason why we can't just do this at the namespace level?

e.g.

```shell
kubectl annotate namespaces default 'sidecar.opentelemetry.io/inject'=true
kubectl annotate namespaces default 'instrumentation.opentelemetry.io/inject-java'=true
```

I assume we also don't need the container-names annotation, as we just want to instrument everything. We can always add a false annotation on anything we don't want to instrument as-needed. I don't think we care what the injected sidecar container is named either, since container names only need to be unique within a given pod.
</blockquote></details>

The injected sidecar container is always named otc-container. This name is something else, but I switched to a single default anyways.
___
*[`src/main/k8s/open_telemetry_collector_sidecar.cue` line 17 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCS21lU78twgU2aop9y:-NCWXcvtBAu1KWxxaxRd:br6995y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/open_telemetry_collector_sidecar.cue#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Let's follow the YAGNI principle here. If we end up needing to deal with specific configurations, we can add it in then.
</blockquote></details>

Simplified things.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r10, 8 of 8 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/k8s/open_telemetry_collector.cue` line 43 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCWrnnaCLY1nscEtd5z:-NCWrnnaCLY1nscEtd6-:b-r8f442) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3d239a324f07545aa6abe7f8db79abe86ed9509/src/main/k8s/open_telemetry_collector.cue#L43)):*
> ```CUE
>         """
> 
> 	sidecars: [Name=string]: {
> ```

Maybe `collectors` since these are `OpenTelemetryCollector` objects



_Code quote:_
```CUE
sidecars
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: 26 of 27 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/open_telemetry_collector.cue` line 43 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCWrnnaCLY1nscEtd5z:-NCWub_-2ws6DdV5Dbf7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c3d239a324f07545aa6abe7f8db79abe86ed9509/src/main/k8s/open_telemetry_collector.cue#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Maybe `collectors` since these are `OpenTelemetryCollector` objects
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: 23 of 27 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/base.cue` line 407 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCRxVLsD3BlknftRllm:-NC_q1H10_qf9UFHU0Io:b-2hkg18) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/base.cue#L407)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The injected sidecar container is always named otc-container. This name is something else, but I switched to a single default anyways.
</blockquote></details>

I could add the namespace annotations to the README, in case someone wants the option to restart one deployment at a time to add metrics to.
___
*[`src/main/k8s/open_telemetry_collector.cue` line 17 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCS12M99cUJQDlg3IZf:-NC_qUpE-BVJpbie8q38:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/open_telemetry_collector.cue#L17)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I guess I am not using it right now so the deployment could go away.
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: 23 of 27 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/base.cue` line 407 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCRxVLsD3BlknftRllm:-NCa42cG4cfP1IChb85l:b-c5e10h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/base.cue#L407)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I could add the namespace annotations to the README, in case someone wants the option to restart one deployment at a time to add metrics to.
</blockquote></details>

Oh wait, but you would still need to rebuild everything anyways to add the pod annotations for scraping.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/k8s/base.cue` line 407 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCRxVLsD3BlknftRllm:-NCaFIBy733-UstHCXVy:b-wuakmv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d053b7f70291d90b0c93c9f5742939ff5961b428/src/main/k8s/base.cue#L407)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Oh wait, but you would still need to rebuild everything anyways to add the pod annotations for scraping.
</blockquote></details>

You'd have to restart the pod even if adding the namespace annotation in order for the pod to pick it up.

My basic goal is to have this be as decoupled as possible, since the OpenTelemetry operator allows for that. Personally I'd prefer to keep those annotations at the namespace level, though it seems like we need the prometheus ones at the pod level. Therefore I leave it up to you.
___
*[`src/main/k8s/base.cue` line 377 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCaFkN7DjkT4KXY-m_z:-NCaFkN7DjkT4KXY-ma-:b-vftx49) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4d91bb3c7dd8da8cfc40d5b548c9f62b433854d/src/main/k8s/base.cue#L377)):*
> ```CUE
> 				labels: {
> 					app:    _name + "-app"
> 					scrape: string | *"true"
> ```

Do you need both the label and the annotation?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/base.cue` line 377 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCaFkN7DjkT4KXY-m_z:-NCaJMNd9S2WxyQdNEUS:btl4pcw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4d91bb3c7dd8da8cfc40d5b548c9f62b433854d/src/main/k8s/base.cue#L377)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do you need both the label and the annotation?
</blockquote></details>

The label is for gke https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.4.3-gke.0/doc/api.md#clusterpodmonitoringspec. I could remove it from this PR and move it to the gke one.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/k8s/base.cue` line 377 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-NCaFkN7DjkT4KXY-m_z:-NCaJyEV69E-2BTbWXJy:bo6ompy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4d91bb3c7dd8da8cfc40d5b548c9f62b433854d/src/main/k8s/base.cue#L377)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The label is for gke https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.4.3-gke.0/doc/api.md#clusterpodmonitoringspec. I could remove it from this PR and move it to the gke one.
</blockquote></details>

Yes please.

**Review by duliomatos1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685#-:-NCahISS2UxArYM2SAOr:bnfp4nl)* status: 22 of 27 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 4 of 25 files at r8, 2 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: 24 of 27 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 3 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @stevenwarejones)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/685)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
