### PR TITLE
Replace common //src/main/ and //src/test/ files with common-jvm import

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/148)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 129 of 175 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/148)* status: 129 of 175 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @stevenwarejones, @tristanvuong2021, and @zachcwc)

___
*[src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/148#-MeWAn8b7WVfNqLnayMO:-MeWAn8b7WVfNqLnayMP:b-932ic5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0afc0b1bc1fdb408c0bb33099c6637371e0e5a93/src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel#L1)):*
> ```Starlark
> load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_test")
> ```

Seems like an odd choice to migrate main but not test.

**Comment by tristanvuong2021** [comment]
___
*[src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/148#-MeWAn8b7WVfNqLnayMO:-MeWNKZpBDwb5n70jX83:bkfxxx6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0afc0b1bc1fdb408c0bb33099c6637371e0e5a93/src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Seems like an odd choice to migrate main but not test.
</blockquote></details>

I will do test too then.

**Comment by tristanvuong2021** [comment]
___
*[src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/148#-MeWAn8b7WVfNqLnayMO:-MeWRrbT6rJZx8pc4cyy:bef07qi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0afc0b1bc1fdb408c0bb33099c6637371e0e5a93/src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel#L1)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I will do test too then.
</blockquote></details>

Deleted common test files as well now.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 38 of 175 files at r1, 27 of 27 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn, @stevenwarejones, and @zachcwc)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 167 of 175 files at r1, 27 of 27 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @zachcwc)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 167 of 175 files at r1, 27 of 27 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Pull request merged**
