### PR TITLE
Add default service config

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1603)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1603#-Nx-gMf--KScGNAhLf-U:-Nx-gMf--KScGNAhLf-V:bblgnbd) (no related file):*
FYI, this is all touching testing files only. That is to say that this would be the default service config only for integration and correctness tests, and not for a production deployment. If that's your intent, then this PR is fine.

___

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1603)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt` line 221 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1603#-NxP-yvnAepzLa3OZo04:-NxP-yvnAepzLa3OZo05:b-sq97i9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3fe7532b76346074260c92dd584d8e08b73b2f8/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L221)):*
> ```Kotlin
>         ProtocolConfig.NoiseMechanism.CONTINUOUS_GAUSSIAN,
>       )
>     private val DEFAULT_SERVICE_CONFIG_MAP: Map<String, *>? by lazy {
> ```

Put this into Configs.kt as well, since you pretty much need to convert to JSON in order to use it. Make it a non-lazy constant there.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt` line 222 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1603#-NxP0O8x4Wdc991qxq0Q:-NxP0O8x4Wdc991qxq0R:b-67s0kc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3fe7532b76346074260c92dd584d8e08b73b2f8/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L222)):*
> ```Kotlin
>       )
>     private val DEFAULT_SERVICE_CONFIG_MAP: Map<String, *>? by lazy {
>       val serviceConfigJson = JsonFormat.printer().print(DEFAULT_SERVICE_CONFIG)
> ```

Use the toJson extension from common-jvm



_Suggestion:_
```Kotlin
DEFAULT_SERVICE_CONFIG.toJson()
```

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1603)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt` line 221 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1603#-NxP-yvnAepzLa3OZo04:-NxPB-ae9Yjdi360GbeT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3fe7532b76346074260c92dd584d8e08b73b2f8/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L221)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Put this into Configs.kt as well, since you pretty much need to convert to JSON in order to use it. Make it a non-lazy constant there.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt` line 222 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1603#-NxP0O8x4Wdc991qxq0Q:-NxPB-r-C_0BrsoJMcqZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3fe7532b76346074260c92dd584d8e08b73b2f8/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L222)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the toJson extension from common-jvm
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
