### PR TITLE
Add index for update metric calculation spec reporting metrics in create metrics

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1538)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1538)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1538#-Nv3-1vK2gb4mMF6V8Po:-Nv3-1vK2gb4mMF6V8Pp:b-tx7rbj) (no related file):*
I'm not quite understanding what this index is for.

Part of this is because I don't quite understand the `MetricCalculationSpecReportingMetrics` table. It appears to be mapping MetricCalculationSpecs to Metrics within the context of a Report. What's odd to me is that CreateMetricRequestId is part of the primary key rather than MetricId. MetricId is also nullable. Is the idea that this row is created separately from Metric creation, and the Metric is created later? Therefore the (MeasurementConsumerId, CreateMetricRequestId) tuple uniquely identifies a future or existing Metric? Why does it have ReportingSetId as part of its primary key then, as each Metric is tied to exactly one ReportingSet?

___
___
*[`src/main/resources/reporting/postgres/add-index-on-metric-calculation-spec-reporting-metrics-table-for-update.sql` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1538#-Nv2yCQh4xU8QqV5Tkai:-Nv2yCQh4xU8QqV5Tkaj:bu2i4hw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6e5e9972d692f34efebca1078caf34dafa2ae9fd/src/main/resources/reporting/postgres/add-index-on-metric-calculation-spec-reporting-metrics-table-for-update.sql#L40)):*
> ```TSQL
> 
> -- changeset tristanvuong2021:add-metric-calculation-spec-reporting-metrics-create-metric-request-id-index dbms:postgresl
> CREATE INDEX metric_calculation_spec_reporting_metrics_create_metric_request_id
> ```

Index names tend to be UpperCamelCase.



_Suggestion:_
```TSQL
MetricCalculationSpecReportingMetricsByCreateMetricRequestId
```
___
*[`src/main/resources/reporting/postgres/changelog-v2.yaml` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1538#-Nv2zIdH2x6jUXH8sTBd:-Nv2zIdIDw29-ewYHChw:b-pntkyh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6e5e9972d692f34efebca1078caf34dafa2ae9fd/src/main/resources/reporting/postgres/changelog-v2.yaml#L48)):*
> ```YAML
> - include:
>     file: add-index-on-metric-calculation-spec-reporting-metrics-table-for-update.sql
>     relativeToChangeLogFile: true    
> ```

nit: trailing whitespace



_Code quote:_
```YAML
····
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1538)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1538#-Nv3-1vK2gb4mMF6V8Po:-Nv3KxT38c8FTwoX6ms-:b9gtk69) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not quite understanding what this index is for.

Part of this is because I don't quite understand the `MetricCalculationSpecReportingMetrics` table. It appears to be mapping MetricCalculationSpecs to Metrics within the context of a Report. What's odd to me is that CreateMetricRequestId is part of the primary key rather than MetricId. MetricId is also nullable. Is the idea that this row is created separately from Metric creation, and the Metric is created later? Therefore the (MeasurementConsumerId, CreateMetricRequestId) tuple uniquely identifies a future or existing Metric? Why does it have ReportingSetId as part of its primary key then, as each Metric is tied to exactly one ReportingSet?
</blockquote></details>

Metrics are created separately from the Report and the rows in this table are first created when creating a Report before being updated later once the metrics are created. 

ReportingSetId isn't needed as part of the primary key. Removed it.

___
___
*[`src/main/resources/reporting/postgres/add-index-on-metric-calculation-spec-reporting-metrics-table-for-update.sql` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1538#-Nv2yCQh4xU8QqV5Tkai:-Nv3FDuGE32Yb9yNt9ZV:b-wn077b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6e5e9972d692f34efebca1078caf34dafa2ae9fd/src/main/resources/reporting/postgres/add-index-on-metric-calculation-spec-reporting-metrics-table-for-update.sql#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Index names tend to be UpperCamelCase.
</blockquote></details>

In postgres, index names tend to use this convention because of lack of case sensitivity

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1538)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/drop-reporting-set-id-from-metric-calculation-spec-reporting-metrics-table-primary-key.sql` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1538#-Nv3SHyOCRMRd31cFFMg:-Nv3SHyOCRMRd31cFFMh:ba1x8in) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/11ac54550673eb4681abb79e74c22fa8f052fdcc/src/main/resources/reporting/postgres/drop-reporting-set-id-from-metric-calculation-spec-reporting-metrics-table-primary-key.sql#L39)):*
> ```TSQL
> --           └── MetricCalculationSpecReportingMetrics
> 
> -- changeset tristanvuong2021:drop-reporting-set-id-column-metric-calculation-spec-reporting-metrics-table-primary-key dbms:postgresql
> ```

nit: you don't need to be this verbose in the file/changeset name. You can add a `-- comment: ` line to the changeset to explain what's happening.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1538)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
