### PR TITLE
Drop some metric labels for GCP

### PR DESCRIPTION
**Pull request by tristanvuong2021**
process_command_line can be too long, which prevents metric ingestion. Other labels that aren't important were dropped to ensure the amount of labels is well under the limit of 30 even if other labels are added later.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1140)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1140)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/k8s/dev/prometheus_gke.cue` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1140#-NaOQZbi5t2vi0yD2Vo9:-NaOQZbj1ns6M-_jyZGk:b-2ep5w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdc9330c57567b0253b54bc649bfd92cc6212913/src/main/k8s/dev/prometheus_gke.cue#L32)):*
> ```CUE
> 				interval: "30s"
> 				metricRelabeling: [{
> 					regex:  "process_.*"
> ```

Won't this end up dropping the JVM process metrics? Those are ones we use frequently.

e.g. `Prometheus/process_runtime_jvm_memory_usage_bytes/gauge` from Cloud Monitoring

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1140)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/dev/prometheus_gke.cue` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1140#-NaOQZbi5t2vi0yD2Vo9:-NaOb4UEAnmoFBAuhH0-:b-wexulq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdc9330c57567b0253b54bc649bfd92cc6212913/src/main/k8s/dev/prometheus_gke.cue#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Won't this end up dropping the JVM process metrics? Those are ones we use frequently.

e.g. `Prometheus/process_runtime_jvm_memory_usage_bytes/gauge` from Cloud Monitoring
</blockquote></details>

This drops only the labels from the metrics not the metrics themselves. So this drops the labels process_runtime_version, process_command_line, process_pid, process_runtime_description, process_runtime_name, and process_executable_path.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
