### PR TITLE
Output uniformly random guess at frequency distribution when reach is too small

### PR DESCRIPTION
**Pull request by riemanli**
The variance calculation of frequency distribution will output `NaN` when reach is zero. Moreover, the estimated variance is not accurate when reach is impractically small. The solution is to check whether the reach is too small using its confidence interval. If the confidence interval of the reach contains values <= 0, we claim the reach is too small for an accurate variance estimate of frequency distribution, and output the variance of uniformly random draw from [0, 1].

### CODE REVIEW

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* **#1498** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1498?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1498?utm_source=stack-comment).

**Review by jiayu-google — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1498#-:-NrE81j4Ei6OA--cOdUo:bnfp4nl)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @chenweiw and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/LiquidLegions.kt` line 275 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1498#-NrE7PUlCnAIqfs-oP-5:-NrE7PUlCnAIqfs-oP-6:b-actbe8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0963363977f20b7f690c748edecc28108ffba4c0/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/LiquidLegions.kt#L275)):*
> ```Kotlin
> 
>     // When reach is too small, we have little info to estimate frequency, and thus the estimate of
>     // relative frequency is equivalent to a uniformly random guess at probability.
> ```

nit: "uniformly random guess of a probability in [0, 1]."

**Review by chenweiw — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1498)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MeasurementStatistics.kt` line 91 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1498#-NrIRf9v5pbXyMIyHB9s:-NrIRf9v5pbXyMIyHB9t:b-wrr05f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0963363977f20b7f690c748edecc28108ffba4c0/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MeasurementStatistics.kt#L91)):*
> ```Kotlin
>  * A reach result is considered too small when computing variances of relative frequency if the 95%
>  * confidence interval of the reach covers 0 or negative values. The 95% confidence interval =
>  * reach_result +/- 1.96 * reach_std.
> ```

Do we always consider "95%" confidence interval here or is "95%" defined by the customer's input? If it is the former, then nothing needs to be changed.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1498)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @chenweiw and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/LiquidLegions.kt` line 275 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1498#-NrE7PUlCnAIqfs-oP-5:-NrJ5TBa10HnDolkU-gE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0963363977f20b7f690c748edecc28108ffba4c0/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/LiquidLegions.kt#L275)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

nit: "uniformly random guess of a probability in [0, 1]."
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MeasurementStatistics.kt` line 91 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1498#-NrIRf9v5pbXyMIyHB9s:-NrJ5Uh_8jYWDLJxmmyV:b-hrfdkf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0963363977f20b7f690c748edecc28108ffba4c0/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MeasurementStatistics.kt#L91)):*
<details><summary><i>Previously, chenweiw wrote…</i></summary><blockquote>

Do we always consider "95%" confidence interval here or is "95%" defined by the customer's input? If it is the former, then nothing needs to be changed.
</blockquote></details>

It's hardcoded right now. Not sure if it makes sense to let user control this.

**Review by chenweiw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1498)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by chenweiw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1498)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1498)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Pull request merged**
