### PR TITLE
Create and implement the Frontend simulator.

### PR DESCRIPTION
**Pull request by wangyaopw**
1. Only createMeasurement is implemented in this PR.
2. No test is planned to be added for this part.
3. Test will be added for computing the expected result using unencrypted
sketches.

https://rally1.rallydev.com/#/605340551071d/portfolioitemstreegrid?detail=%2Fuserstory%2F606023913139&fdp=true&fdp=true?fdp=true

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/193)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/193)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @oliver-amzn, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorFlags.kt, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/193#-MgvnPlt1J3r_SMbOl3C:-MgvnPlt1J3r_SMbOl3D:b-pei5vt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d541e801358d78632d244d774deeabf718a64c4/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorFlags.kt#L50)):*
> ```
> mcCsPrivateKeyDerFiles
> ```
minor: singular
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/193#-MgvoDa91CZdJMhPtkYq:-MgvoDa91CZdJMhPtkYr:b-8rgtoo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d541e801358d78632d244d774deeabf718a64c4/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt#L68)):*
> ```Kotlin
> 
> data class MeasurementConsumerData(
>   val name: String,
> ```

nit: document these properties so we know that they are public API resource name/IDs.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/193)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorFlags.kt, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/193#-MgvnPlt1J3r_SMbOl3C:-MgwhL9c-nhyRDdCF0f8:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d541e801358d78632d244d774deeabf718a64c4/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorFlags.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> mcCsPrivateKeyDerFiles
> ```
minor: singular
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/193#-MgvoDa91CZdJMhPtkYq:-Mgwi25x8wn5HnCkHBZP:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d541e801358d78632d244d774deeabf718a64c4/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt#L68)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: document these properties so we know that they are public API resource name/IDs.
</blockquote></details>

Done

**Review by corbantek — APPROVED** [review]
> Reviewed 9 of 12 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 8 of 12 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
