### PR TITLE
Fix next page tokens always being set

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/240)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/240)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 133 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/240#-MiRjlHhBA5XWwE_p9Er:-MiRjlHhBA5XWwE_p9Es:bazeq6g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21cf88b6cc44c706486808877ceaafabe3f8ebb6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L133)):*
> ```
>  if (results.size == pageSize)
> ```

This check won't work. If there are 50 matched items and pagesize is set to 50, the token shouldn't be set in the result.

Usually we can try to get pageSize+1 items back, and use the existence of the last item to determine whether it is the last page or not.

Also we shouldn't use timestamp as pagetoken, the token should contains 1. the initial request, 2. some id of the last item in previous page. If you want to fix the pagetoken, better to redesign completely.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/240)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 133 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/240#-MiRjlHhBA5XWwE_p9Er:-MiSfO6AEHHNYGqzWFTO:be25n78) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21cf88b6cc44c706486808877ceaafabe3f8ebb6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L133)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  if (results.size == pageSize)
> ```

This check won't work. If there are 50 matched items and pagesize is set to 50, the token shouldn't be set in the result.

Usually we can try to get pageSize+1 items back, and use the existence of the last item to determine whether it is the last page or not.

Also we shouldn't use timestamp as pagetoken, the token should contains 1. the initial request, 2. some id of the last item in previous page. If you want to fix the pagetoken, better to redesign completely.


</blockquote></details>

More broadly, we need to:
1. Communicate from the internal service whether there would have been more results were there not a limit set, so we know whether to set the next page token.
2. Ensure that the page token can uniquely and efficiently determine which entry to start at (timestamp doesn't do this, as multiple entries may have the same timestamp and page can fall between these).

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 133 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/240#-MiRjlHhBA5XWwE_p9Er:-MiWtR0v5PnG7ll3Hg8F:bby3k3t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21cf88b6cc44c706486808877ceaafabe3f8ebb6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L133)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

More broadly, we need to:
1. Communicate from the internal service whether there would have been more results were there not a limit set, so we know whether to set the next page token.
2. Ensure that the page token can uniquely and efficiently determine which entry to start at (timestamp doesn't do this, as multiple entries may have the same timestamp and page can fall between these).
</blockquote></details>

How about the page token contains the limit, the filter, and the external id of the last result, then that is directly passed on to the internal service.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/240)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 133 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/240#-MiRjlHhBA5XWwE_p9Er:-MiXR56UAdmGx72mwboG:b7fnfa0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21cf88b6cc44c706486808877ceaafabe3f8ebb6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L133)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

How about the page token contains the limit, the filter, and the external id of the last result, then that is directly passed on to the internal service.
</blockquote></details>

I think we need a design doc about pagination before coding it. The token also needs to be encrypted in production.

**Pull request closed without merging**
