### PR TITLE
Implement Get Method for ExchangeSteps service

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 2 unresolved discussions (waiting on @kgaynor, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiNTiWB6_FOowjl66qc:-MiNTiWD8wtrwz1IZ-Mr:bbw3z04) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1a40227361fd542daf5a618b97b72c8e885fe870/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L54)):*
> ```Kotlin
>   override suspend fun getExchangeStep(request: GetExchangeStepRequest): ExchangeStep {
>     return requireNotNull(
>         ExchangeStepReader()
> ```

Add temporary variable?

val exchangeStepResult = ...
Return requireNotNull(exchangeStepResult).exchangrStep
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiNSQOv67XrW9zNMUw1:-MiNSQOx2Qc_a_S9pUoh:bbhlni9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1a40227361fd542daf5a618b97b72c8e885fe870/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L57)):*
> ```Kotlin
>           .withBuilder {
>             appendClause("WHERE ")
>             appendClause(
> ```

Multi line string please ("""...""".trimIndent())

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiNTiWB6_FOowjl66qc:-MiNX7Bt-1X1VjIBa7f5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1a40227361fd542daf5a618b97b72c8e885fe870/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Add temporary variable?

val exchangeStepResult = ...
Return requireNotNull(exchangeStepResult).exchangrStep
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiNSQOv67XrW9zNMUw1:-MiNX7xk3ooKqa9kV32g:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1a40227361fd542daf5a618b97b72c8e885fe870/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Multi line string please ("""...""".trimIndent())
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kgaynor and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 1 unresolved discussion (waiting on @kgaynor and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiORrla32wxYlDbmXG-:-MiORrla32wxYlDbmXG0:bxt1ibw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c1456feb2194aee6cae6d58bcdd5617114c34f28/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L94)):*
> ```Kotlin
> 
> private val DATE: Date =
>   Date.newBuilder()
> ```

Does it not work to use the new builder here?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiORrla32wxYlDbmXG-:-MiOqpy0Ds0Bev-fLRzR:b-uxkzfj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c1456feb2194aee6cae6d58bcdd5617114c34f28/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L94)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Does it not work to use the new builder here?
</blockquote></details>

There doesn't seem to be a DateKt class.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 1 unresolved discussion (waiting on @kgaynor and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiORrla32wxYlDbmXG-:-MiOt2V76D8Hn1ed4Ri0:bk09qp6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c1456feb2194aee6cae6d58bcdd5617114c34f28/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L94)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

There doesn't seem to be a DateKt class.
</blockquote></details>

You can add a kt_jvm_proto_library rule for it

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiORrla32wxYlDbmXG-:-MiSSsxADFr3Vv1cglyP:b-lwpskr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c1456feb2194aee6cae6d58bcdd5617114c34f28/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L94)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You can add a kt_jvm_proto_library rule for it
</blockquote></details>

Figured it out. Thank you.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 2 unresolved discussions (waiting on @kgaynor, @stevenwarejones, and @yunyeng)

___
*[src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, line 449 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiSrEli4PPnmO8FuLdf:-MiSrEli4PPnmO8FuLdg:bphgkdm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/80dec9197d94564d17d87288ebe45a0acda909a5/src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel#L449)):*
> ```Starlark
> kt_jvm_proto_library(
>     name = "date_kt_jvm_proto",
>     srcs = ["@com_google_googleapis//google/type:date_proto"],
> ```

Please put this in `src/main/proto/google/type/BUILD.bazel`

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @kgaynor, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, line 449 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiSrEli4PPnmO8FuLdf:-MiSwI-43OROqqKcxPx9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/80dec9197d94564d17d87288ebe45a0acda909a5/src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel#L449)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please put this in `src/main/proto/google/type/BUILD.bazel`
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 3 unresolved discussions (waiting on @kgaynor, @stevenwarejones, and @yunyeng)

___
*[src/main/proto/google/type/BUILD.bazel, line 6 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiT2-Ev39WfKaBsmGfc:-MiT2-Ex8J5wIiNvCmFD:bllewv9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d647389935f643825219ad738d8daeda62f96b96/src/main/proto/google/type/BUILD.bazel#L6)):*
> ```Starlark
> 
> kt_jvm_proto_library(
>     name = "date_kt_jvm_proto",
> ```

@sanjayvas just confirming you're OK with this?
___
*[src/main/proto/wfa/measurement/internal/kingdom/all_protos.bzl, line 49 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiT1ovjAabSvk7bMsrI:-MiT1ovnBEWB1NsWQp9W:btri2tn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d647389935f643825219ad738d8daeda62f96b96/src/main/proto/wfa/measurement/internal/kingdom/all_protos.bzl#L49)):*
> ```Starlark
> 
> KINGDOM_INTERNAL_ENTITY_PROTOS = [
>     "//src/main/proto/google/type:date_kt_jvm_proto",
> ```

I don't think this makes sense here, please just manually add the dep to specific rules that need it.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 3 unresolved discussions (waiting on @kgaynor and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 176 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiTIypo9RFDMPVS0vFV:-MiTIypp30dyVc3P5jJ2:b-ht6glg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d647389935f643825219ad738d8daeda62f96b96/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L176)):*
> ```Kotlin
>     runBlocking {
>       dataProvidersService.createDataProvider(DATA_PROVIDER)
>       modelProvidersService.createModelProvider(ModelProvider.getDefaultInstance())
> ```

modelProvidersService.createModelProvider(modelProvider{})

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @kgaynor, and @yunyeng)

___
*[src/main/proto/google/type/BUILD.bazel, line 6 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiT2-Ev39WfKaBsmGfc:-MiTeOsJ1j661tQbLxel:b-s0zlxw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d647389935f643825219ad738d8daeda62f96b96/src/main/proto/google/type/BUILD.bazel#L6)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@sanjayvas just confirming you're OK with this?
</blockquote></details>

Conceptually yes, but it should be in common-jvm as I believe this message is used there as well.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @kgaynor, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 176 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiTIypo9RFDMPVS0vFV:-MiTok9r6nBDO8DdpLD_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d647389935f643825219ad738d8daeda62f96b96/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L176)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

modelProvidersService.createModelProvider(modelProvider{})
</blockquote></details>

Done.
___
*[src/main/proto/google/type/BUILD.bazel, line 6 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiT2-Ev39WfKaBsmGfc:-MiTokwa3teqwcTNJhQZ:bpar6r2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d647389935f643825219ad738d8daeda62f96b96/src/main/proto/google/type/BUILD.bazel#L6)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Conceptually yes, but it should be in common-jvm as I believe this message is used there as well.
</blockquote></details>

Sent out PR for common-jvm and added a TODO here for now.
___
*[src/main/proto/wfa/measurement/internal/kingdom/all_protos.bzl, line 49 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiT1ovjAabSvk7bMsrI:-MiToqPl9PTS0BaAJA2H:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d647389935f643825219ad738d8daeda62f96b96/src/main/proto/wfa/measurement/internal/kingdom/all_protos.bzl#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't think this makes sense here, please just manually add the dep to specific rules that need it.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 1 unresolved discussion (waiting on @kgaynor and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kgaynor, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 136 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiZoUce5R82GE4oXVFt:-MiZoUce5R82GE4oXVFu:b-tmhq88) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5632e274aa31b5baa7a1bea369db4846812baac1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L136)):*
> ```Kotlin
>       apiVersion = "2"
>       publicKey = ByteString.copyFromUtf8("This is a  public key.")
>       publicKeySignature = ByteString.copyFromUtf8("This is a  public key signature.")
> ```

where does this signature get verified currently? is it in a TODO?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 136 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiZoUce5R82GE4oXVFt:-MigY-kx8DaAVCePs-AY:b-q7jegb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5632e274aa31b5baa7a1bea369db4846812baac1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L136)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

where does this signature get verified currently? is it in a TODO?
</blockquote></details>

I think verification of the signature happens in the public API.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 136 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiZoUce5R82GE4oXVFt:-Migyhbe1Kg9IfCJA9sz:b-xwbrv4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5632e274aa31b5baa7a1bea369db4846812baac1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L136)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

I think verification of the signature happens in the public API.
</blockquote></details>

It's required to set these fields. How they're used is irrelevant to this PR. Does this need to block this PR?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @kgaynor, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 136 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiZoUce5R82GE4oXVFt:-Mj038KG0ZW4iEhbQs1C:b-40j89n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5632e274aa31b5baa7a1bea369db4846812baac1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L136)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's required to set these fields. How they're used is irrelevant to this PR. Does this need to block this PR?
</blockquote></details>

i don't think its needs to block it. I just want a clear architecture who has responsibility of checking the signatures.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 136 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiZoUce5R82GE4oXVFt:-Mj09BOM6B2KuYnNGGQp:b6d98uu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5632e274aa31b5baa7a1bea369db4846812baac1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L136)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i don't think its needs to block it. I just want a clear architecture who has responsibility of checking the signatures.
</blockquote></details>

Your comment is still blocking... if you have questions about this, you should check in with the Measurement folks for how this is used. I don't think this PR is the right place for it

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kgaynor, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 136 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239#-MiZoUce5R82GE4oXVFt:-Mj0DN893vqRddvp672w:b-fsdbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5632e274aa31b5baa7a1bea369db4846812baac1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L136)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Your comment is still blocking... if you have questions about this, you should check in with the Measurement folks for how this is used. I don't think this PR is the right place for it
</blockquote></details>

whoever uses this public key will need to verify the signature, for example, the measurementConsumer.

We don't have code for MC yet. The MC simulator doesn't verify the signature since it is just for test. But it could.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @kgaynor)

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @kgaynor)

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 2 files at r3, 1 of 3 files at r5, 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kgaynor)

**Review by yunyeng — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 4 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kgaynor)

**Pull request merged**
