### PR TITLE
Create the CMM IAC Layout

### PR DESCRIPTION
**Pull request by wfa-siyengar**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927)

**Review by wfa-siyengar — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927#-:-NSA3XFJ-i2Rgab2oCuw:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927#-NS7i7z-6QqA0qH8H7Do:-NSA3RM2Ax-dVI8Ai5IW:brxjmsa) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What is the source of this diagram? We usually don't just check in a diagram image alone. e.g. if it's a LucidChart diagram, we put that into the shared Drive. This way the diagram can be updated as-needed.
</blockquote></details>

Have added a Visio file. 

___

**Review by wfa-siyengar — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by wfa-siyengar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927#-NS7i7z-6QqA0qH8H7Do:-NSCA-2_AtE12sb82IPo:b-3ihu7m) (no related file):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Have added a Visio file. 
</blockquote></details>

Request you to review and approve this One. @SanjayVas 

___

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927)* status: all files reviewed, 1 unresolved discussion (waiting on @wfa-siyengar)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927#-NS7i7z-6QqA0qH8H7Do:-NSDc04z62rFlMwc4Ite:b-2k9lgk) (no related file):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Request you to review and approve this One. @SanjayVas 
</blockquote></details>

Add this to the shared Drive (ask Tej for permissions for a writable subdirectory if you don't have one) rather than the repo.

___

**Review by wfa-siyengar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927#-NS7i7z-6QqA0qH8H7Do:-NSECjO60aq_AN0u4ZUz:b-4dzvy4) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add this to the shared Drive (ask Tej for permissions for a writable subdirectory if you don't have one) rather than the repo.
</blockquote></details>

I was looking for a comment on the Image content. That would give us an idea of the direction ahead. Should i consider no comment as OK and Agreed on the diagram.? @SanjayVas 

___

**Comment by kungfucraig** [comment]
@SanjayVas, we discussed this PR this morning and given this is a Visio source file we probably don't want to submit this, but can you look at the diagram and approve the flow. The PR will be dropped once we're happy with the diagram.

**Review by wfa-siyengar — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by wfa-siyengar — COMMENTED** [review]
I have provided the Visio file to Tej and have kept only the image here.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927#-:-NSTOCMQ8cO7jOox7rx6:bsthv2z)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927)* status: all files reviewed, 1 unresolved discussion (waiting on @wfa-siyengar)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/927#-NS7i7z-6QqA0qH8H7Do:-NSgDaP8CrtFCo3YLrQp:b-aohthb) (no related file):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

I was looking for a comment on the Image content. That would give us an idea of the direction ahead. Should i consider no comment as OK and Agreed on the diagram.? @SanjayVas 
</blockquote></details>

As discussed offline, we don't need a PR here as there's nothing to do in the repo. We can discuss the diagram itself separately, e.g. over Slack or email.

___

**Pull request closed without merging**
