### PR TITLE
Add NONE DirectNoiseMechanism.

### PR DESCRIPTION
**Pull request by iverson52000**
* Add NONE directNoiseMechanism for testing purpose
* Change direct measurement noise mechanism name to `directNoiseMechanism` to differentiate from MPC `noiseMechanism`
* Some improvements to GaussianNoiser

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 149 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040#-NXArJp156IeJvCBgt8X:-NXArJp156IeJvCBgt8Y:btshlw2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8132f35c5f7796268fbccb8f746fefdb3bf900cf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L149)):*
> ```Kotlin
>  */
> enum class DirectNoiseMechanism {
>   NONE,
> ```

can you mark as testing only?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 149 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040#-NXArJp156IeJvCBgt8X:-NXBS3J66BnVADVsM7pC:b-jrxdad) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8132f35c5f7796268fbccb8f746fefdb3bf900cf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L149)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you mark as testing only?
</blockquote></details>

The entire simulator is testing only

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 149 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040#-NXArJp156IeJvCBgt8X:-NXBTG0QDaNYXnvXYv8f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8132f35c5f7796268fbccb8f746fefdb3bf900cf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L149)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The entire simulator is testing only
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 149 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040#-NXArJp156IeJvCBgt8X:-NXGH7WqASvEyICOk5vS:b-aqgvpl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8132f35c5f7796268fbccb8f746fefdb3bf900cf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L149)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Let me clarify - the TODO says to move this to the Public API. I don't have a concern with NONE being in the EDP simulator. I do have concerns with NONE in the Public API. Can you combine both those comments so that NONE is either a) not moved to public api b) moved to public api but marked as testing only?

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 149 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040#-NXArJp156IeJvCBgt8X:-NXGkTQS6Uqx83uTxQpo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8132f35c5f7796268fbccb8f746fefdb3bf900cf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L149)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Let me clarify - the TODO says to move this to the Public API. I don't have a concern with NONE being in the EDP simulator. I do have concerns with NONE in the Public API. Can you combine both those comments so that NONE is either a) not moved to public api b) moved to public api but marked as testing only?
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Review by iverson52000 — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1040)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Pull request merged**
