### PR TITLE
Update Spanner schema for Event Groups.

### PR DESCRIPTION
**Pull request by robinsons**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJkc13ok4CO1uej0N:-MpsJkc13ok4CO1uej0O:b-t7au3z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L180)):*
> ```
>  MeasurementConsumerCertificateId
> ```
what is this certificate used for?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 181 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJGOb1LbiZjh_Vwl9:-MpsJGOb1LbiZjh_VwlA:b-m9xzyn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L181)):*
> ```
> MeasurementConsumerPublicKey
> ```
Is this a serialized proto? which proto?

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJkc13ok4CO1uej0N:-MpsLb6u1VaThuApzDK6:bwnqcrj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L180)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  MeasurementConsumerCertificateId
> ```
what is this certificate used for?
</blockquote></details>

To verify the public key. The context is in [this PR](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/77) which has the API changes.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 181 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJGOb1LbiZjh_Vwl9:-MpsLWTy9S7sDxRCYv2R:b3vbjhm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L181)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> MeasurementConsumerPublicKey
> ```
Is this a serialized proto? which proto?
</blockquote></details>

It's a serialized `EncryptionPublicKey`. Added that info in a comment.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 200 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsNTVG1tQjXoeWc9sw:-MpsNTVG1tQjXoeWc9sx:b-j5dlx7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L200)):*
> ```
> NOT NULL
> ```

Is there a procedure we follow for adding new non-null columns? For example, should I make it nullable to start, and then change it to `NOT NULL` after updating code and any existing data?

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJkc13ok4CO1uej0N:-MpsR5hkEkov2vYn2plm:b-ykpdxa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L180)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

To verify the public key. The context is in [this PR](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/77) which has the API changes.
</blockquote></details>

verified by the MC?
Why does the MC need to verify it is own public Key using it is own certificate?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 181 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJGOb1LbiZjh_Vwl9:-MpsPEmA-ew95lCUHK6j:bnvi0oc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L181)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

It's a serialized `EncryptionPublicKey`. Added that info in a comment.
</blockquote></details>

I think the database only persist kingdom internal protos, no public API protos.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 174 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsSYtxDY4VXpLuNdRm:-MpsSYtxDY4VXpLuNdRn:b99m7ca) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec2b7bb56f6692315087723e05e893125c17147f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L174)):*
> ```
>  EventGroups 
> ```
I am wondering if we need so many columns, or if many of them can be included in a single EventGroupDetail (proto) column.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @robinsons, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJkc13ok4CO1uej0N:-Mps_dRKCH-l0hD_33fi:b-vlysdy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L180)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

verified by the MC?
Why does the MC need to verify it is own public Key using it is own certificate?
</blockquote></details>

So the EDP can verify that the key belongs to the MC before it uses it to encrypt metadata for MC.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 181 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJGOb1LbiZjh_Vwl9:-Mps_qrr-1UzHuHqTVto:b-5i92rn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L181)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I think the database only persist kingdom internal protos, no public API protos.
</blockquote></details>

No, we do serialize public API protos. Usually they're in a Details message which has a corresponding field to indicate the API version.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 200 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsNTVG1tQjXoeWc9sw:-MpsaGyJ2TnWgmf8ZRBs:bbii0t5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L200)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

> ```
> NOT NULL
> ```

Is there a procedure we follow for adding new non-null columns? For example, should I make it nullable to start, and then change it to `NOT NULL` after updating code and any existing data?
</blockquote></details>

Right now with no running instances, we can just make arbitrary changes to the schema. The only restriction is making sure all tests remain passing, which likely means you need this schema change to go in the same PR as the internal services that write to the table.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 174 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsSYtxDY4VXpLuNdRm:-Mps_0A2DWgbEWGTLOlR:b-a2dsy8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec2b7bb56f6692315087723e05e893125c17147f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L174)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  EventGroups 
> ```
I am wondering if we need so many columns, or if many of them can be included in a single EventGroupDetail (proto) column.
</blockquote></details>

Our policy is that anything that's not an index key (whether that be primary, secondary, or foreign key) or a DB timestamp goes inside a serialized Details message.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJkc13ok4CO1uej0N:-Mpsde5Y6pjQN5f2CVKb:bgomdgg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L180)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

So the EDP can verify that the key belongs to the MC before it uses it to encrypt metadata for MC.
</blockquote></details>

But that happens before an eventGroup is created, right?

The EDP calls GetMeasurementConsumer() and get the MC's signed publicKey and certificate to verify it. Then the EDP creates the Eventgroup for this MC using that public Key and tells which publicKey is used to encrypt the data. I feel including the publicKey in the EventGroup is enough.

No one would use this MeasurementConsumerCertificateId in the table.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 181 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJGOb1LbiZjh_Vwl9:-MpscfcL9bSI8ZsGrHHt:b-1utntu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L181)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No, we do serialize public API protos. Usually they're in a Details message which has a corresponding field to indicate the API version.
</blockquote></details>

The `Details` message is an internal kingdom proto. It just happens that it contains a serialized public API proto message as well as its version. 

My point is that no BYTES column in any table in the schema is mapping to a serialized public API proto.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJkc13ok4CO1uej0N:-Mpshs1LE1m6ruLf7ALb:bblocuv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L180)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

But that happens before an eventGroup is created, right?

The EDP calls GetMeasurementConsumer() and get the MC's signed publicKey and certificate to verify it. Then the EDP creates the Eventgroup for this MC using that public Key and tells which publicKey is used to encrypt the data. I feel including the publicKey in the EventGroup is enough.

No one would use this MeasurementConsumerCertificateId in the table.
</blockquote></details>

The EDP can update the encrypted metadata without changing the key. They should be verifying the key signature (and transitively, the certificate chain) every time you use it to encrypt data. Otherwise the key could have been tampered with (e.g. Kingdom response swaps in its own encryption key).

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJkc13ok4CO1uej0N:-Mpsm3UxAg-xT5EtdSRa:b1qbz9b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L180)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The EDP can update the encrypted metadata without changing the key. They should be verifying the key signature (and transitively, the certificate chain) every time you use it to encrypt data. Otherwise the key could have been tampered with (e.g. Kingdom response swaps in its own encryption key).
</blockquote></details>

so it is either
1. get the certificate using the MeasurementConsumerCertificateId and use it to verify the publicKey in the eventGroup and the encrypt
or
2. get the latest MC (including its publicKey and certificate) using the  MeasurementConsumerId, and use the publicKey to encrypt

I feel the latter is more safe since it always use the latest MC certificate and publicKey.

The publicKey is likely to be embedded in the Detail column and get updated each time the eventGroup is updated, no matter if it is the same key or not.

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJkc13ok4CO1uej0N:-Mpw2G3Q6y_Q3dWFFgd3:bsxyjo2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L180)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

so it is either
1. get the certificate using the MeasurementConsumerCertificateId and use it to verify the publicKey in the eventGroup and the encrypt
or
2. get the latest MC (including its publicKey and certificate) using the  MeasurementConsumerId, and use the publicKey to encrypt

I feel the latter is more safe since it always use the latest MC certificate and publicKey.

The publicKey is likely to be embedded in the Detail column and get updated each time the eventGroup is updated, no matter if it is the same key or not.
</blockquote></details>

I don't have a strong preference either way, but would note that including the certificate in the event group wouldn't prevent the EDP from doing \#2, if that's what they prefer.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 181 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJGOb1LbiZjh_Vwl9:-Mpw3sNd9jFvqNWnrptO:buxxaf0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L181)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

The `Details` message is an internal kingdom proto. It just happens that it contains a serialized public API proto message as well as its version. 

My point is that no BYTES column in any table in the schema is mapping to a serialized public API proto.
</blockquote></details>

Updated to use a `Details` message.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 200 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsNTVG1tQjXoeWc9sw:-Mpw6ZYA0pAWkpKND1NF:bt7s1cb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L200)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Right now with no running instances, we can just make arbitrary changes to the schema. The only restriction is making sure all tests remain passing, which likely means you need this schema change to go in the same PR as the internal services that write to the table.
</blockquote></details>

Since I likely won't be the one updating the internal services, and I don't want to block that work, I've made these columns nullable for now with a TODO to add `NOT NULL` after the application logic has been updated. LMK if you'd prefer a different resolution.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 174 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsSYtxDY4VXpLuNdRm:-Mpw0TEk0fnLJW-Exhfz:bl1e179) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec2b7bb56f6692315087723e05e893125c17147f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L174)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Our policy is that anything that's not an index key (whether that be primary, secondary, or foreign key) or a DB timestamp goes inside a serialized Details message.
</blockquote></details>

Got it. In that case, I've also updated the internal proto (#388) to more closely match that pattern.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: all files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsJkc13ok4CO1uej0N:-MpwH7_n-LCvVgTAzDw4:btgfh3k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L180)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

I don't have a strong preference either way, but would note that including the certificate in the event group wouldn't prevent the EDP from doing \#2, if that's what they prefer.
</blockquote></details>

Agreed that it's safer to use the latest key for new encryption. I don't think we need to enforce this, however. It's also safer to keep signatures and their corresponding certificates paired together.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 200 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsNTVG1tQjXoeWc9sw:-MpwI9zS5z1UPZnShbW4:bjjplom) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L200)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Since I likely won't be the one updating the internal services, and I don't want to block that work, I've made these columns nullable for now with a TODO to add `NOT NULL` after the application logic has been updated. LMK if you'd prefer a different resolution.
</blockquote></details>

SG, with the amendment that we should file an issue to keep track of it. Just file in GitHub rather than Rally and follow the corresponding [TODO format](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format).

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @stevenwarejones)

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 200 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-MpsNTVG1tQjXoeWc9sw:-MpwMgvb94eJ71-HSnfC:bb7r145) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fe49eb68498d71cf6cc283d39824dfa2914ab27/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L200)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

SG, with the amendment that we should file an issue to keep track of it. Just file in GitHub rather than Rally and follow the corresponding [TODO format](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format).
</blockquote></details>

Good info, thanks.

**Review by chipingyeh — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 183 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-Mq0XIK_1LajFpIvev5i:-Mq0XIKa7puFV6BZefPl:b2v0odg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04302f386562899a7ae8b5d46a0deebb8a489518/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L183)):*
> ```
> MeasurementConsumerCertificateId 
> ```
One more question.

If the MC revokes its certificate, what do we do to the eventGroups using it?

@sanjayvas

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 183 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-Mq0XIK_1LajFpIvev5i:-Mq0ZG-zBo3mIPf2o5TB:bgnebed) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04302f386562899a7ae8b5d46a0deebb8a489518/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L183)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> MeasurementConsumerCertificateId 
> ```
One more question.

If the MC revokes its certificate, what do we do to the eventGroups using it?

@sanjayvas 
</blockquote></details>

There's no relevant `State` for an event group. It just means the EDP can't update metadata without changing the key/cert.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 183 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389#-Mq0XIK_1LajFpIvev5i:-Mq0hzA_9Y2X_buBSEqh:bep8v1m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04302f386562899a7ae8b5d46a0deebb8a489518/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L183)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There's no relevant `State` for an event group. It just means the EDP can't update metadata without changing the key/cert.
</blockquote></details>

ok. So it seems we won't support deleting a certificate, since the certificateId is foreign key of many other tables.

**Review by robinsons — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/389)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
