### PR TITLE
Add CLI command and tests for ModelRollouts service.

### PR DESCRIPTION
**Pull request by jojijac0b**
Add CLI command and tests for ModelRollouts service.

### CODE REVIEW

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069)* status: all files reviewed, 4 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1485 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NY54sVND3Bp61T1tOs2:-NY54sVND3Bp61T1tOs3:b-6xwybs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1485)):*
> ```Kotlin
>       required = true,
>     )
>     modelRolloutInterval: String,
> ```

Follow how time is handled elsewhere in this file.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1491 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NY54zjDEps9gdN2cUse:-NY54zjDEps9gdN2cUsf:bs4q9op) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1491)):*
> ```Kotlin
>       required = true,
>     )
>     modelRolloutFreezeTime: String,
> ```

Ditto.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1554 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NY574ZX6JcmGZmoxF2f:-NY574ZX6JcmGZmoxF2g:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1554)):*
> ```Kotlin
>       defaultValue = "",
>     )
>     rolloutInterval: String
> ```

Ditto
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1592 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NY57AZhCCkatqWZI7-r:-NY57AZhCCkatqWZI7-s:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1592)):*
> ```Kotlin
>       required = true,
>     )
>     freezeTime: String,
> ```

Ditto

**Review by Marco-Premier — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069)* status: all files reviewed, 11 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1489 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMkMSID2sCPuglw0J_:-NYMkMSID2sCPuglw0Ja:b1kgphq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1489)):*
> ```Kotlin
>       names = ["--rollout-freeze-time"],
>       description = ["The timestamp the rollout must stop expanding its release percentage."],
>       required = true,
> ```

```rollout_freeze_time``` is not a required field and is not inserted into the DB in ```CreateModelRollout``` spanner. Hence can be removed from here



_Code quote:_
```Kotlin
required = true
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1509 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMkrW22bX9y1XlqQLN:-NYMkrW22bX9y1XlqQLO:bmkoc4o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1509)):*
> ```Kotlin
>         rolloutFreezeTime = timestamp {
>           seconds = Instant.parse(modelRolloutFreezeTime).toProtoTime().seconds
>         }
> ```

Ditto on ```rollout_freeze_time```. Remove it from the request



_Code quote:_
```Kotlin
        rolloutFreezeTime = timestamp {
          seconds = Instant.parse(modelRolloutFreezeTime).toProtoTime().seconds
        }
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1546 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMlYKoCf4BaNwA4-8p:-NYMlYKoCf4BaNwA4-8q:b-syd5c9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1546)):*
> ```Kotlin
>     listPageToken: String,
>     @Option(
>       names = ["--interval"],
> ```

maybe call this ```--rollout-period-overlapping``` to reflect naming on public api?



_Code quote:_
```Kotlin
--interval
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1549 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMlLOA0cpm1Hlzl8Jb:-NYMlLOA0cpm1Hlzl8Jc:b-3yueq8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1549)):*
> ```Kotlin
>       description =
>         [
>           "The the overlapping time intervals used to filter the result. Should be in the following format: start time,end time. Times should be written in Java Time-Scale"
> ```

Nit redundant ```the```



_Code quote:_
```Kotlin
the
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1579 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMlr4M4OCUAURfw2lE:-NYMlr4M4OCUAURfw2lF:b-iflxpc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1579)):*
> ```Kotlin
>   }
> 
>   @Command(description = ["Sets model rollout freeze time."])
> ```

We debated on this while designing public api. This should be ```schedule``` and not ```set``` since this api call schedule an event that will happen in the future (i.e. the freeze time)



_Code quote:_
```Kotlin
Sets
```
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1353 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMmZoi2DZjUD1IiwN3:-NYMmZoi2DZjUD1IiwN4:bogr8p4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1353)):*
> ```Kotlin
>           "--parent=$MODEL_LINE_NAME",
>           "--rollout-period=$MODEL_ROLLOUT_ACTIVE_START_TIME,$MODEL_ROLLOUT_ACTIVE_END_TIME",
>           "--rollout-freeze-time=$TIME_STRING_1",
> ```

Remove ```rollout_freeze_time``` from the request



_Code quote:_
```Kotlin
"--rollout-freeze-time=$TIME_STRING_1"
```
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1433 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMn1sK4DUMoIgBwp-s:-NYMn1sLAFsoDrc-P1PP:bdcm4yw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1433)):*
> ```Kotlin
>           "schedule",
>           "--name=$MODEL_ROLLOUT_NAME",
>           "--freeze-time=$TIME_STRING_1",
> ```

As we do use tests as a way to understand how the whole system works, I think this ```$TIME_STRING_1``` can lead to confusion.
```rollout_freeze_time``` is valid when is in between ```rollout_period_start_time``` and ```rollout_period_end_time```.
Therefore I would suggest to create a new variable that respect this constraint. 
I.e. ```private const val MODEL_ROLLOUT_FREEZE_TIME ="2026-07-24T05:00:00.000Z"```



_Code quote:_
```Kotlin
"--freeze-time=$TIME_STRING_1",
```

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @Marco-Premier, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1485 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NY54sVND3Bp61T1tOs2:-NYOWg-A86H3bxiNac6O:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1485)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Follow how time is handled elsewhere in this file.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1489 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMkMSID2sCPuglw0J_:-NYOWj-AEuzoeHkY21eW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1489)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

```rollout_freeze_time``` is not a required field and is not inserted into the DB in ```CreateModelRollout``` spanner. Hence can be removed from here
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1491 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NY54zjDEps9gdN2cUse:-NYOWjTqDKADN9A1y9LL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1491)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1509 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMkrW22bX9y1XlqQLN:-NYOWkpm4TDnF3nWwdKc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1509)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Ditto on ```rollout_freeze_time```. Remove it from the request
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1546 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMlYKoCf4BaNwA4-8p:-NYOWlseBXX72PDrIeBp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1546)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

maybe call this ```--rollout-period-overlapping``` to reflect naming on public api?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1554 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NY574ZX6JcmGZmoxF2f:-NYOWo-uA-xbCLd5Q50D:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1554)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1579 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMlr4M4OCUAURfw2lE:-NYOWoy29z0f8zHs4Cok:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1579)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

We debated on this while designing public api. This should be ```schedule``` and not ```set``` since this api call schedule an event that will happen in the future (i.e. the freeze time)
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1592 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NY57AZhCCkatqWZI7-r:-NYOWqzJE9Z1t5zHYpr_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1592)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1353 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMmZoi2DZjUD1IiwN3:-NYOWz5dChlFmqmdAJZB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1353)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Remove ```rollout_freeze_time``` from the request
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1433 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069#-NYMn1sK4DUMoIgBwp-s:-NYOX-vI0fhZ4tz4goDO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c17103642ac1ff6291da1981b6c742bc7d27204/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1433)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

As we do use tests as a way to understand how the whole system works, I think this ```$TIME_STRING_1``` can lead to confusion.
```rollout_freeze_time``` is valid when is in between ```rollout_period_start_time``` and ```rollout_period_end_time```.
Therefore I would suggest to create a new variable that respect this constraint. 
I.e. ```private const val MODEL_ROLLOUT_FREEZE_TIME ="2026-07-24T05:00:00.000Z"```
</blockquote></details>

Done.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1069)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
