### PR TITLE
Implement RevokeCertificate for Spanner internal Kingdom Service

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288)

### CODE REVIEW

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-MkskdfVAZQEKcuGiInm:-MkskdfW8JjV3ietPafw:bcqir4b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L118)):*
> ```Kotlin
>     } catch (e: KingdomInternalException) {
>       when (e.code) {
>         KingdomInternalException.Code.CERTIFICATE_NOT_FOUND ->
> ```

nit: Why not combine the two: `CERTIFICATE_NOT_FOUND, DUCHY_NOT_FOUND -> ...` ? 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mkskw4_-tm-iTYrzUwG:-Mkskw4_-tm-iTYrzUwH:b-900gw0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L77)):*
> ```Kotlin
> 
>   private val clock: Clock = TestClockWithNamedInstants(TEST_INSTANT)
>   protected val idGenerator = RandomIdGenerator(clock, Random(RANDOM_SEED))
> ```

Is it common to mix protected and private like this or would you rather group same visibility together?

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 121 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mksn0ju2GjaWOZwAaUf:-Mksn0ju2GjaWOZwAaUg:b-mpeg4w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L121)):*
> ```
>         KingdomInternalException.Code.DUCHY_NOT_FOUND ->
>          failGrpc(Status.NOT_FOUND) { "Certificate not found" }
> ```

failGrpc(Status.INVALID_ARGUMENT) { "Duchy not found" }


similar for other parent types

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mksonh41bsE21AIMIM_:-Mksonh41bsE21AIMIMa:b-ukv4xf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L36)):*
> ```
> RevokeCertificate
> ```

can you add a TODO here? Thanks

 // TODO(world-federation-of-advertisers/cross-media-measurement#305) : Consider cancelling all associated active measurements if a certificate is revoked

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288)* status: all files reviewed, 5 unresolved discussions (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 121 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mksn0ju2GjaWOZwAaUf:-Mkt7zkCDo97-78GA_Le:briq4sp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L121)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>         KingdomInternalException.Code.DUCHY_NOT_FOUND ->
>          failGrpc(Status.NOT_FOUND) { "Certificate not found" }
> ```

failGrpc(Status.INVALID_ARGUMENT) { "Duchy not found" }


similar for other parent types
</blockquote></details>

Not quite. Should be FAILED_PRECONDITION. See #247.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mkt6bmJ1yNVjlbmjpEx:-Mkt6bmK9USzvB8sFTWO:b-6ykozb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L33)):*
> ```
> Long
> ```
nit: use InternalId
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mkt6y816Vq4Xs23ZP58:-Mkt6y816Vq4Xs23ZP59:b-22sz16) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L99)):*
> ```
> getLong
> ```
nit: getInternalId
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mksonh41bsE21AIMIM_:-Mkt7C29BAI-5YYzT8cu:b-esj1lw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L36)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> RevokeCertificate
> ```

can you add a TODO here? Thanks

 // TODO(world-federation-of-advertisers/cross-media-measurement#305) : Consider cancelling all associated active measurements if a certificate is revoked
</blockquote></details>

+1, but qualify the issue with the org/repo as described in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mksonh41bsE21AIMIM_:-Mkt8uTfD1LAboP7DexP:bpzush2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

+1, but qualify the issue with the org/repo as described in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format
</blockquote></details>

Yep, the full path is what I typed here. Reviewable displays it as the short link.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288)* status: all files reviewed, 9 unresolved discussions (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mksonh41bsE21AIMIM_:-Mkt9TKm6CQTI_1YViKq:b2km48i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L36)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Yep, the full path is what I typed here. Reviewable displays it as the short link.
</blockquote></details>

Ah. Just be careful and use code fencing.
```
// TODO(world-federation-of-advertisers/cross-media-measurement#305) : Consider cancelling all associated active measurements if a certificate is revoked
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mkt9zWA9GgFhHA4I9Py:-Mkt9zWA9GgFhHA4I9Pz:b6lhn06) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L55)):*
> ```
>           KingdomInternalException.Code.DUCHY_NOT_FOUND
> ```
???
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-MktBOK-55mIfC2ohmxG:-MktBOK-55mIfC2ohmxH:b14k7po) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L68)):*
> ```
>           throw KingdomInternalException(KingdomInternalException.Code.CERTIFICATE_NOT_FOUND) {
>             "Certificate not found."
>           }
> ```
This should be an IllegalStateException, as the presence of the parent field should be checked before this.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 370 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-MktCf7l6Dy3X53cTM6M:-MktCf7l6Dy3X53cTM6N:b-f8k6jk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L370)):*
> ```
> this.
> ```
nit: unnecessary qualification?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 439 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-MktDOsZ5czH1SW9K8po:-MktDOsZ5czH1SW9K8pp:bwjnqmx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L439)):*
> ```Kotlin
>     val revokedCertificate = certificatesService.revokeCertificate(request)
> 
>     assertThat(revokedCertificate)
> ```

This doesn't verify that the certificate was actually written to DB. Need to e.g. ensure that revokeCertificate and getCertificate responses match. Then you can just check revocationState in the revoke response rather than comparing the entire response.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-MkskdfVAZQEKcuGiInm:-MlBPmDG80er5HZraKZL:b-8u90q4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L118)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

nit: Why not combine the two: `CERTIFICATE_NOT_FOUND, DUCHY_NOT_FOUND -> ...` ? 
</blockquote></details>

makes sense Oliver. I think I am confused about this whole thing. Would you mind moving the discussion to the comment below?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 121 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mksn0ju2GjaWOZwAaUf:-MlBOS4ZAjmoUMZlHslN:b-8ocraf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L121)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not quite. Should be FAILED_PRECONDITION. See #247.
</blockquote></details>

This is what I am confused about. Updating to FAILED_PRECONDITION is fine but separating for  "Duchy not found" , "MeasurementConsumer not found" is going against the pattern we used in getCertificate. If I am understanding correctly, on the above getCertificate method, we just return { "Certificate not found" } even if a parentId is wrong. DUCHY_NOT_FOUND seems to be special cased above so I tried to treat it the same way.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mkt6y816Vq4Xs23ZP58:-MlBKcGHDHrBemtC-rB4:bjev91u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> getLong
> ```
nit: getInternalId
</blockquote></details>

thanks! didn't know this existed
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mksonh41bsE21AIMIM_:-MlBLWpp2riNQyutlOgC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah. Just be careful and use code fencing.
```
// TODO(world-federation-of-advertisers/cross-media-measurement#305) : Consider cancelling all associated active measurements if a certificate is revoked
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mkt9zWA9GgFhHA4I9Py:-MlBJDRM8qpmvt3K5CaW:bc27cg2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>           KingdomInternalException.Code.DUCHY_NOT_FOUND
> ```
???
</blockquote></details>

thanks for spotting, weirdly enough it compiles with this, I guess it is an artifact from copy/pasting.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-MktBOK-55mIfC2ohmxG:-MlBRbpA5khR6ytH7snR:bvn7par) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L68)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>           throw KingdomInternalException(KingdomInternalException.Code.CERTIFICATE_NOT_FOUND) {
>             "Certificate not found."
>           }
> ```
This should be an IllegalStateException, as the presence of the parent field should be checked before this.
</blockquote></details>

thank you. I am actually checking this in the Service implementation method. So this case should never be reached. Thus, I am not catching it in the Service implementation. Does this make sense?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mkskw4_-tm-iTYrzUwG:-MlBSXmg5OvswiPLFmRl:b8yjkqt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L77)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Is it common to mix protected and private like this or would you rather group same visibility together? 
</blockquote></details>

thanks Oliver, It seems id generator needed clock and the population needed idGenerator, hence the sandwich. I made the idGenerator private. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 370 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-MktCf7l6Dy3X53cTM6M:-MlBJhtvCdjsfM243rO0:b-k73z76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L370)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> this.
> ```
nit: unnecessary qualification?
</blockquote></details>

thanks
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 439 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-MktDOsZ5czH1SW9K8po:-MlBNokc1v5xuRXwUvW-:b-d89evm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L439)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't verify that the certificate was actually written to DB. Need to e.g. ensure that revokeCertificate and getCertificate responses match. Then you can just check revocationState in the revoke response rather than comparing the entire response.
</blockquote></details>

I see, makes sense. Thanks for the help, updated accordingly.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-MkskdfVAZQEKcuGiInm:-MlC5GDZ3f_lwY6_H9W5:bkgn8il) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L118)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

makes sense Oliver. I think I am confused about this whole thing. Would you mind moving the discussion to the comment below?
</blockquote></details>

Note that Oliver is no longer on the project.

I imagine this comment is because you had the same message for both cases. Therefore, it looked like you could combine the cases since they gave the same result.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 121 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mksn0ju2GjaWOZwAaUf:-MlCGXNH-t9eaqcFh62Q:bignxyz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L121)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

This is what I am confused about. Updating to FAILED_PRECONDITION is fine but separating for  "Duchy not found" , "MeasurementConsumer not found" is going against the pattern we used in getCertificate. If I am understanding correctly, on the above getCertificate method, we just return { "Certificate not found" } even if a parentId is wrong. DUCHY_NOT_FOUND seems to be special cased above so I tried to treat it the same way.
</blockquote></details>

I updated #247 to be more clear on the reasoning. Whether we use `NOT_FOUND` vs. `FAILED_PRECONDITION` isn't as important for a "parent" as long as we make a principled decision and are consistent. My main point was that I don't think `INVALID_ARGUMENT` is correct in this case.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mksonh41bsE21AIMIM_:-MlCPYZhA0utNyrnAAIR:bekkkiq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L36)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Done.
</blockquote></details>

My comment about code fencing was re: Reviewable comments to make sure it doesn't incorrectly parse a code sample.

The TODO should be inside the KDoc, and nothing should separate a KDoc and its subject.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-MktBOK-55mIfC2ohmxG:-MlCPvciC5E1hlks9lmi:ba0dnbe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L68)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thank you. I am actually checking this in the Service implementation method. So this case should never be reached. Thus, I am not catching it in the Service implementation. Does this make sense?
</blockquote></details>

Correct. You generally don't catch IllegalStateException, as it represents a programming error.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 121 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/288#-Mksn0ju2GjaWOZwAaUf:-MlpsoMyE3DrsAIRTCGf:b-bs5plp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/feee7f99a9987750b2cd2a4977cf581474578f9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L121)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Thanks Sanjay. I left it as is. Waiting for Yao to return for the issue about whether or not groping as Certificate not found or casing for each of the other resources.
</blockquote></details>

NOT_FOUND is OK

**Pull request merged**
