### PR TITLE
Fix retrieval of report measurements when getting a report.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/770)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/770)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @mariolamassaavedra and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 537 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/770#-NHztB7p7NeW7nlAx9s4:-NHztB7p7NeW7nlAx9s5:b-xd034t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbf106c877cf3729361c6d9683be7d2775017c4a/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L537)):*
> ```Kotlin
>    */
>   private fun JsonPrimitive.decodePostgresBase64(): ByteArray {
>     return Base64.getDecoder().decode(this.asString.replace("\n", ""))
> ```

I think you could just use [`getMimeDecoder`](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html#getMimeDecoder--) instead of stripping the newlines.



_Code quote:_
```Kotlin
getDecoder
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/770)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @mariolamassaavedra and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 537 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/770#-NHztB7p7NeW7nlAx9s4:-NI-Km1j69_iaaRgjW1l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbf106c877cf3729361c6d9683be7d2775017c4a/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L537)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think you could just use [`getMimeDecoder`](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html#getMimeDecoder--) instead of stripping the newlines.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/770)* status: all files reviewed, 1 unresolved discussion (waiting on @mariolamassaavedra and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 532 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/770#-NI-cItH4bgM4Kw-cMcd:-NI-cItH4bgM4Kw-cMce:b-dptz76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/883ae42562f932ce998224be9f85db6d13c22eda/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L532)):*
> ```Kotlin
> 
>   /**
>    * Postgres base64 encoding adds \n to break up the text for backwards compatibility in older
> ```

nit: could just state that Postgres uses MIME base64 encoding (RFC 2045), which is where the 76-character line limit comes from. See https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html#mime



_Code quote:_
```Kotlin
   * Postgres base64 encoding adds \n to break up the text for backwards compatibility in older
   * systems. The MIME decoder ignores the \n.
```

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/770)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariolamassaavedra)

**Pull request merged**
