### PR TITLE
Implement internal StreamEventGroupMetadataDescriptors

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574)* status: all files reviewed, 3 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574#-N35s39g8pXI_6xQeWcR:-N35s39g8pXI_6xQeWcS:b-ui6s24) (no related file):*
Oh, did we just forget to have a `ListEventGroupMetadataDescriptors` in the public API?

___
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroupMetadataDescriptors.kt` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574#-N35tOy5COqZhpmkpLwM:-N35tOy5COqZhpmkpLwN:b-y3heo9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df933fa21aea95a895f594f55f0dcae434a9a538/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroupMetadataDescriptors.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

Should be the year the code was created. Leave it alone if the whole file was copied.



_Code quote:_
```Kotlin
2021
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574#-N35sPvw9_1mWfcNci78:-N35sPvw9_1mWfcNci79:bwpijnx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df933fa21aea95a895f594f55f0dcae434a9a538/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto#L55)):*
> ```protobuf
>   message Filter {
>     fixed64 external_data_provider_id = 1;
>     repeated fixed64 external_event_group_metadata_descriptor_ids = 2;
> ```

Are we intending to add a [BatchGet method](https://google.aip.dev/231) to the public API? Otherwise I don't see how this field would be used.



_Code quote:_
```protobuf
    repeated fixed64 external_event_group_metadata_descriptor_ids = 2;
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt` line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574#-N36Ot6f1Jbgd9aHnWbD:-N36Ot6g1U8tSQDCJV39:be4a562) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df933fa21aea95a895f594f55f0dcae434a9a538/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt#L41)):*
> ```Kotlin
> ) : EventGroupMetadataDescriptorsCoroutineImplBase() {
>   override suspend fun createEventGroupMetadataDescriptor(
>     eventGroupMetadataDescriptor: EventGroupMetadataDescriptor
> ```

While you're in here, can you fix this warning?

```
src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt:38:5: warning: the corresponding parameter in the supertype 'EventGroupMetadataDescriptorsCoroutineImplBase' is named 'request'. This may cause problems when calling this function with named arguments.
    eventGroupMetadataDescriptor: EventGroupMetadataDescriptor
    ^
```



_Code quote:_
```Kotlin
eventGroupMetadataDescriptor
```

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574#-N35s39g8pXI_6xQeWcR:-N3QMEdnBcXctjCdiqPA:b-cbttgm) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Oh, did we just forget to have a `ListEventGroupMetadataDescriptors` in the public API?
</blockquote></details>

I didn't know if it was needed/a standard part of these APIs -- but no, it's not implemented yet

___
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt` line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574#-N36Ot6f1Jbgd9aHnWbD:-N3QOway9rmSVJexiB7_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df933fa21aea95a895f594f55f0dcae434a9a538/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

While you're in here, can you fix this warning?

```
src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt:38:5: warning: the corresponding parameter in the supertype 'EventGroupMetadataDescriptorsCoroutineImplBase' is named 'request'. This may cause problems when calling this function with named arguments.
    eventGroupMetadataDescriptor: EventGroupMetadataDescriptor
    ^
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroupMetadataDescriptors.kt` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574#-N35tOy5COqZhpmkpLwM:-N3QP2y_8u3zVLmuE_Wy:b-73m6vj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df933fa21aea95a895f594f55f0dcae434a9a538/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroupMetadataDescriptors.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Should be the year the code was created. Leave it alone if the whole file was copied.
</blockquote></details>

Nice catch.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574#-N35sPvw9_1mWfcNci78:-N3QPANJCfj3229MEjGs:b-ldq5lg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df933fa21aea95a895f594f55f0dcae434a9a538/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Are we intending to add a [BatchGet method](https://google.aip.dev/231) to the public API? Otherwise I don't see how this field would be used.
</blockquote></details>

Yes -- I was planning on implementing a Stream method in the public API after this one

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574#-N35sPvw9_1mWfcNci78:-N3VNEoU5rkrBgc4AKPI:bk9lvov) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df933fa21aea95a895f594f55f0dcae434a9a538/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto#L55)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Yes -- I was planning on implementing a Stream method in the public API after this one
</blockquote></details>

On the public API, we use a [standard List method](https://google.aip.dev/132) for getting multiple of something. While List allows for filtering, the proper way to have a method that allows you to get multiple of something by ID is [BatchGet](https://google.aip.dev/231).

Regardless, I'm asking for what the use case is to determine whether it indeed warrants something other than a standard List method.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/574#-N35sPvw9_1mWfcNci78:-N3VrVQf7jroBpz74Lqi:b-2ui52w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df933fa21aea95a895f594f55f0dcae434a9a538/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, I just realized that the use case would get getting the descriptors used by a set of EventGroups. BatchGet seems better than List for that.

This internal method is okay if we're also implementing List in the public API, but if we're only implementing BatchGet then we don't need anything related to pagination. BatchGet also must fail if any of the specified resources is not found, and must return the resources in the same order as the specified resource names. Therefore you might be doing some post-processing on the internal response.

Approving this for now since it could work, but consider the comments above.
</blockquote></details>

Thanks for the input. I'll go ahead and merge this now to build on top of, but create a followup task to update this in the future.

**Pull request merged**
