### PR TITLE
fix:Compare computatation token versions in Millbase during exception handling.

### PR DESCRIPTION
**Pull request by renjiezh**
The computation token could be updated by Herald of ControlService. The error handling should skip for outdated computation token.
fix https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1918

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1920)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt` line 278 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1920#-OBgjPLs8327wOT2COxA:-OBgjPLs8327wOT2COxB:b-yzvsmm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d7160b7d8548277ea651beabebd80408a5818469/src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt#L278)):*
> ```Kotlin
>     if (latestToken.version != token.version) {
>       logger.log(Level.WARNING, e) {
>         "$globalId@$millId: Skip exception handling as token has been outdated."
> ```

I don't think we want to skip  *all* exception handling. For example, handling StatusException. I think the main thing we want to avoid is trying to mutate or enqueue the computation.

You can probably solve this by just checking for StatusException first.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1920)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt` line 278 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1920#-OBgjPLs8327wOT2COxA:-OC5UrIZ2RXG1IEPdi_e:b967f9j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d7160b7d8548277ea651beabebd80408a5818469/src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt#L278)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think we want to skip  *all* exception handling. For example, handling StatusException. I think the main thing we want to avoid is trying to mutate or enqueue the computation.

You can probably solve this by just checking for StatusException first.
</blockquote></details>

Done.
Updated the logic.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1920)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1920)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
