### PR TITLE
Add ListEventGroups command to reporting CLI

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/648)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/648)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 408 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/648#-N8Ubn3AEMrOJ2CGWBnT:-N8Ubn3AEMrOJ2CGWBnU:bgxvbi6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27a901f2dfc6a005524816e8d857ef79ff140200/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L408)):*
> ```Kotlin
>   @CommandLine.Option(
>     names = ["--parent"],
>     description = ["API resource name of the Data Provider"],
> ```

Measurement Consumer ?



_Code quote:_
```Kotlin
Data Provider
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/648)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt` line 408 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/648#-N8Ubn3AEMrOJ2CGWBnT:-N8Ue7nX6fB0Homu3XQO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27a901f2dfc6a005524816e8d857ef79ff140200/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L408)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Measurement Consumer ?
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
The parent of all resources in the reporting API should be measurement consumer. Approving this since it's what the API does right now. We should have a follow-up to fix it.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/648#-:-N8UhAmLCpvMx0bpvP6-:brocsse)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by riemanli — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/648#-:-N8Uho0F1F0epFPGokuY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/648#-:-N8UofZM5zM31iTaV1QM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/648)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
