### PR TITLE
Add stubs for a set of utilities for building a FrequencyVector.

### PR DESCRIPTION
**Pull request by kungfucraig**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 6 of 6 files at r2, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/BUILD.bazel` line 7 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NuQhKCW917Oav28qLG4:-NuQhKCW917Oav28qLG5:b-fbxtr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9dd25fe240193c55ce6219268a1d5c2fcc054c93/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/BUILD.bazel#L7)):*
> ```Starlark
> kt_jvm_library(
>     name = "shareshuffle",
>     srcs = [
> ```

nit: use a glob if you're going to do a single library target for the package
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NuQhk8nEFAHX-lUDNAx:-NuQhk8nEFAHX-lUDNAy:b-36fuqz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9dd25fe240193c55ce6219268a1d5c2fcc054c93/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L46)):*
> ```Kotlin
>    * VidSamplingInterval it is ignored.
>    */
>   fun addVid(vid: Long) {}
> ```

No implementations for these? Should there be TODOs? Or is this class supposed to be abstract?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt` line 36 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NuQi4DF88MDNb0GwCSI:-NuQi4DF88MDNb0GwCSJ:b-r0kgn5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9dd25fe240193c55ce6219268a1d5c2fcc054c93/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt#L36)):*
> ```Kotlin
>    */
>   fun getVidIndex(vid: Long): Int {
>     return 0
> ```

No implementations for this? Should there be a TODO, or is this class supposed to be abstract?
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt` line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NuQiNouAzit3MQ6NlRC:-NuQiNouAzit3MQ6NlRD:b-nst6st) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9dd25fe240193c55ce6219268a1d5c2fcc054c93/src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt#L28)):*
> ```Kotlin
>   @Test
>   fun `demonstrate the usage of the libraries`() {
>     // TODO(kungfucraig): Update this to be an actual test once the implementations
> ```

Add an `@Ignore` annotation so it's clear this test does not yet do anything (so nobody is e.g. misled into thinking this test actually passes)

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: 12 of 16 files reviewed, 3 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NuQhk8nEFAHX-lUDNAx:-NuQyDeK5L9QtcN1xqIx:bex4giu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9dd25fe240193c55ce6219268a1d5c2fcc054c93/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No implementations for these? Should there be TODOs? Or is this class supposed to be abstract?
</blockquote></details>

Added TODOs.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt` line 36 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NuQi4DF88MDNb0GwCSI:-NuQycOn6JDTUsNLfuyG:bex4giu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9dd25fe240193c55ce6219268a1d5c2fcc054c93/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No implementations for this? Should there be a TODO, or is this class supposed to be abstract?
</blockquote></details>

Added TODOs.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt` line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NuQiNouAzit3MQ6NlRC:-NuQz12dEEYNnHypqov4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9dd25fe240193c55ce6219268a1d5c2fcc054c93/src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add an `@Ignore` annotation so it's clear this test does not yet do anything (so nobody is e.g. misled into thinking this test actually passes)
</blockquote></details>

Done.

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 3 of 6 files at r2, 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: 13 of 16 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 61 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NuVZHgrEYFHhKSDEt-x:-NuVZHgrEYFHhKSDEt-y:b7r3nj0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ca2558014502323e6d3474078d79d4ba9ea1c93/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L61)):*
> ```Kotlin
>   /**
>    * Add all vids in the [other] Builder to the [FrequencyVector]. If any vid in the [other] Builder
>    * is not contained by the VidSamplingInterval of this Builder it is ignored.
> ```

If `this` builder and `other` don't share the same VID sampling interval, won't this produce misleading results?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NuVxUVf6zMY1_eVbea8:-NuVxUVf6zMY1_eVbea9:b-bwe5hx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ca2558014502323e6d3474078d79d4ba9ea1c93/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L39)):*
> ```Kotlin
>   /** Build a FrequencyVector. */
>   fun build(): FrequencyVector {
>     // TODO(kungfucraig): Implement this method
> ```

Use correct TODO format when for referencing a GitHub user. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format



_Suggestion:_
```Kotlin
TODO(@kungfucraig)
```
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt` line 27 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NuVxvyJ5vO43yJ6-1Uv:-NuVxvyJ5vO43yJ6-1Uw:boqyotn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ca2558014502323e6d3474078d79d4ba9ea1c93/src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt#L27)):*
> ```Kotlin
> @RunWith(JUnit4::class)
> class FrequencyVectorBuilderTest {
>   @Ignore
> ```

nit: pass the explanation to `@Ignore`. e.g. "SUT not yet implemented"

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: 13 of 16 files reviewed, 2 unresolved discussions (waiting on @ple13, @renjiezh, @robinsons, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NuVxUVf6zMY1_eVbea8:-NuW9ZZiBbBUMA5WnQLc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ca2558014502323e6d3474078d79d4ba9ea1c93/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use correct TODO format when for referencing a GitHub user. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 61 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NuVZHgrEYFHhKSDEt-x:-NuW95hIDw8SO55jDeQQ:b86c090) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ca2558014502323e6d3474078d79d4ba9ea1c93/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L61)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

If `this` builder and `other` don't share the same VID sampling interval, won't this produce misleading results?
</blockquote></details>

I was trying to mimic the filtering behavior of the other add methods, but I can see where it makes sense to have this one throw instead. If you have two Builders floating around you probably should have built them with the same requisition.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13, @renjiezh, and @robinsons)

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @ple13, @renjiezh, @robinsons, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 37 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-Nu_tYsSBaxyt83yLB_2:-Nu_tYsSBaxyt83yLB_3:b-gvz945) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35e362496c8680abc673968f9009e50776a34df8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L37)):*
> ```Kotlin
>   val vidSamplingInterval: VidSamplingInterval,
> ) {
>   /** Construct a FrequencyVectorBuilder with an existing [FrequencyVector].
> ```

@robinsons Here's the additional constructor we discussed.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 4 files at r5, 7 of 10 files at r6, 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: 15 of 16 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @ple13, @renjiezh, @robinsons, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-Nua-68f3ahEEUXReLlg:-Nua-68f3ahEEUXReLlh:bxaypc5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35e362496c8680abc673968f9009e50776a34df8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L33)):*
> ```Kotlin
>  * @constructor Creates a [FrequencyVectorBuilder] for the given [VidIndeMap] and [PopulationSpec]
>  */
> class FrequencyVectorBuilder(
> ```

with all these TODOs, then file looks more like an interface at this point. Wdyt about just making it an interface until implemented? Or are you just looking for feedback on the interface at this point and will fill in before merging?

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: 15 of 16 files reviewed, 3 unresolved discussions (waiting on @ple13, @renjiezh, @robinsons, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-Nua-68f3ahEEUXReLlg:-NuazXITBvgRbcW2nUOY:b-vo2w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35e362496c8680abc673968f9009e50776a34df8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L33)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

with all these TODOs, then file looks more like an interface at this point. Wdyt about just making it an interface until implemented? Or are you just looking for feedback on the interface at this point and will fill in before merging?
</blockquote></details>

If you're okay with the classes and method signatures then I'd like to proceed with this as is. 

Implementations for the empty methods are coming in follow-up PRs. Making either of them interfaces is a detour in a direction I do not wish to take. 

After merging this the following PRs will be generated:
1. An implementation of VID Index that includes validation of the PopulationSpec.
2. An implementation of the Frequency Builder with any needed helper code.
3. A refactoring of the EDP Simulator to use all of this

**Review by robinsons — APPROVED** [review]
> Reviewed 9 of 10 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 37 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-Nu_tYsSBaxyt83yLB_2:-Nudm6af32c258pX8Fdj:b-ucfknh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35e362496c8680abc673968f9009e50776a34df8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L37)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@robinsons Here's the additional constructor we discussed.
</blockquote></details>

Thanks!

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 6 files at r2, 1 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 58 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NueXSoLBGrwwAjx2smE:-NueXSoLBGrwwAjx2smF:b-80lag4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35e362496c8680abc673968f9009e50776a34df8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L58)):*
> ```Kotlin
>    * VidSamplingInterval it is ignored.
>    */
>   fun addVid(vid: Long) {
> ```

do we need this? could the caller just use `fun addVids(vids: Collection<Long>)`
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt` line 26 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NueX7YnEQjMtQuAqhej:-NueX7YnEQjMtQuAqhek:b-bcnx74) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35e362496c8680abc673968f9009e50776a34df8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt#L26)):*
> ```Kotlin
>  * @constructor Creates a [VidIndexMap] for the given [PopulationSpec]
>  */
> class VidIndexMap(populationSpec: PopulationSpec) {
> ```

the underlying structure here won't be a map, will it? Assuming no, maybe we need a better name for this class. Maybe just `VidIndexMapper`
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt` line 54 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NueZgdEATNrzcFWi8xr:-NueZgdEATNrzcFWi8xs:blo5ci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35e362496c8680abc673968f9009e50776a34df8/src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt#L54)):*
> ```Kotlin
>     assertThat(frequencyVector.dataList).isEmpty()
> 
>     // TODO(kungfucraig): should we support a merge function?
> ```

don't you support merge with `fun addVids(other: FrequencyVectorBuilder) {` ?

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: all files reviewed, 4 unresolved discussions (waiting on @ple13, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 58 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NueXSoLBGrwwAjx2smE:-NuebS3f9laKLqfKzG8D:bjjtfol) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35e362496c8680abc673968f9009e50776a34df8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we need this? could the caller just use `fun addVids(vids: Collection<Long>)`
</blockquote></details>

We should have this so clients have some flexibility in usage. 
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt` line 26 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NueX7YnEQjMtQuAqhej:-Nueajht3oprRCBz0X2_:b-qz93h2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35e362496c8680abc673968f9009e50776a34df8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

the underlying structure here won't be a map, will it? Assuming no, maybe we need a better name for this class. Maybe just `VidIndexMapper`
</blockquote></details>

A Map is the description of an interface not an implementation. This is a Map.
https://docs.oracle.com/javase/8/docs/api/java/util/Map.html

The word "Mapper" would indicate some kind of function object, of which this is not.

I suppose if we wanted to be pedantic we could implement Map<Long, Int>, but there's not much value in that given the intended use cases. Also, it's easy to come back and do that in the future if it seems worthwhile.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt` line 54 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552#-NueZgdEATNrzcFWi8xr:-NueaQGw2bGMvrCOGUbR:b5ezh6z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35e362496c8680abc673968f9009e50776a34df8/src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt#L54)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

don't you support merge with `fun addVids(other: FrequencyVectorBuilder) {` ?
</blockquote></details>

We do support merge using the Frequency Builder. This comment is asking whether we should support merge on the protos themselves. Tentatively, let's say the answer to this question is "no," and I will resolve the TODO in a follow-up PR.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 10 files at r6, 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: all files reviewed, 3 unresolved discussions (waiting on @ple13 and @renjiezh)

**Review by renjiezh — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 1 of 6 files at r2, 1 of 4 files at r5, 9 of 10 files at r6, 1 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by renjiezh — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by robinsons — APPROVED** [review]
> Reviewed 1 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, 1 of 6 files at r2, 1 of 4 files at r5, 9 of 10 files at r6, 1 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1552)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
