### PR TITLE
Incorporate custom direct methodology

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1226)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1226** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1226" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1226?utm_source=stack-comment).

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 1 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 1 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by riemanli — COMMENTED** [review]
@SanjayVas @stevenwarejones I removed custom methodology from Population measurements. In addition, I found internal/direct_computation.proto shouldn't have been added because there is no internal measurement result, so I deleted it. 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1226#-:-NeobHeq9o_bqTiNOIUp:b-6edr2q)* status: 6 of 10 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1226)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @stevenwarejones)

___
*[`build/repositories.bzl` line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1226#-Neog3H5-93k4TU0fdCB:-Neog3H6Ckd31sz4E9-h:bi2hvej) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8345245432314c738e573ebc9f8882d93b2b829c/build/repositories.bzl#L47)):*
> ```Starlark
>         repo = "cross-media-measurement-api",
>         sha256 = "a711ff961c87a7f89dbded3849756063f2dfacdaf46481068b1f0285e6245005",
>         commit = "74b48c068eb3e64d1e89a606343764b5327099c5",
> ```

Don't forget to switch this to the version before merging.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[`build/repositories.bzl` line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1226#-Neog3H5-93k4TU0fdCB:-Neoi5JO8jcZLA0oasmo:b-6abjtf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8345245432314c738e573ebc9f8882d93b2b829c/build/repositories.bzl#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't forget to switch this to the version before merging.
</blockquote></details>

Thanks for reminding!

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Pull request merged**
