### PR TITLE
Change internal revokeApiKey to deleteApiKey.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/405)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/405)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — COMMENTED** [review]
How will the system log these delete actions?

> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/405#-:-Mr3egloEhDEN9wGdAir:bf2pudx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Comment by tristanvuong2021** [comment]
Right now, logging is only in place for Measurements failure and cancellation. General logging isn't in place yet.

**Review by stevenwarejones — COMMENTED** [review]
I'm not sure how I feel about this. I prefer having it logged that a key was revoked vs just deleting any record of its existence.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/405#-:-MrOSSUx9Pjvd21olQAd:bvfsjy8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by SanjayVas — APPROVED** [review]
This is modeled after other API key systems, such as Google Cloud API Keys and GitHub Personal Access Tokens, at least from the public API point-of-view

 If we want the existence of an API key to remain, then the compromise would be to treat revoked in the internal API as deleted in the public API. That is to say that no interaction with a revoked API key is possible from the public API, e.g. doesn't show up in Get or List calls.

My personal thought was that when we implement security/audit logging, we could just have a log entry that notes that the API key was deleted. There's no need to keep it around in the DB where it takes up index space, etc.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/405#-:-MrTWxmLDyde5rXQGl6p:b1ogvmu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/405)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

**Pull request merged**
