### PR TITLE
File structure for Spanner implementation of internal Kingdom services.

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r2, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: 10 of 18 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/gcloud/spanner/BUILD.bazel, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-Mbha4CqE9StCeCQzMUs:-Mbha4CrAtT016Ib64s5:b-mcjhew) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382125ff4618fd3bd0bbf63000b7eb885dd5bfb3/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/BUILD.bazel#L11)):*
> ```
>     "//src/main/kotlin/org/wfanet/measurement/kingdom/service:__subpackages__",
> ```
This shouldn't be exposed to the service package. The internal service impls that depend on Spanner should be under a kingdom/deploy/gcloud/spanner.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: 4 of 21 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/gcloud/spanner/BUILD.bazel, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-Mbha4CqE9StCeCQzMUs:-Mbi0PFjDbKHoiW9D5NL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382125ff4618fd3bd0bbf63000b7eb885dd5bfb3/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/BUILD.bazel#L11)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     "//src/main/kotlin/org/wfanet/measurement/kingdom/service:__subpackages__",
> ```
This shouldn't be exposed to the service package. The internal service impls that depend on Spanner should be under a kingdom/deploy/gcloud/spanner.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 8 files at r4, 11 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
This feels very spanner specific. Can the services get abstracted up a layer so they aren't storage-type specific? 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-:-MblZHVg89lEwIb91Mfg:b-p9f7ii)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt, line 29 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-MblYy9IEzEJ9kwXJT1M:-MblYy9IEzEJ9kwXJT1N:b-ylwbh0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13bfd78f8399bed0f765be37528b5866c79e5322/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt#L29)):*
> ```Kotlin
> ): List<BindableService> {
>   return listOf(
>     SpannerCertificatesService(clock, idGenerator, client),
> ```

This feels like a lot of spanner specific code. Can this get abstracted up a level away from the storage type?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt, line 29 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-MblYy9IEzEJ9kwXJT1M:-Mbl_4jn0lVQEW8vWKvQ:b-8g59m2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13bfd78f8399bed0f765be37528b5866c79e5322/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

This feels like a lot of spanner specific code. Can this get abstracted up a level away from the storage type?
</blockquote></details>

This is specifically binding the Spanner versions of these services. A parallel class under a different `deploy` subpackage would bind some other version.

**Review by uakyol — COMMENTED** [review]
The thinking was that the abstraction of the services are the service definitions - proto files under /proto tree that defined the services -  on top of those, we can have different types of storage type implementations. Spanner is just one of them. What do you think?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-:-Mbm5aHIAKMD84YgHmey:b-w2ihtc)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Comment by SanjayVas** [comment]
This is for issue #103.

**Review by stevenwarejones — COMMENTED** [review]
I need to think about this a bit more. I don't know if I like Issue #103 ... why have separate service implementations for each set of cloud products?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-:-MbwFrxN50RbGst-QPrF:bhpf4va)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
There's very little code that's common to the service implementations compared to what's specific to the underlying DB product. Something simple like blob storage we can extract a client interface and have different implementations of that interface, but the DB code is specific to the domain/schema.

In the previous version, we created domain-specific DB interfaces and have different implementations of those. We found that those added little value, as the DB interfaces effectively just had the same methods as the service definitions. Since the service definitions are effectively interfaces, #103 prescribes treating them as such and dropping an unnecessary layer.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-:-MbwQCj39UPNZXeB5cC0:b-zbmkbx)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-McFYh2M1VhdmLiOslqL:-McFYh2M1VhdmLiOslqM:be3qty1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13bfd78f8399bed0f765be37528b5866c79e5322/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt#L23)):*
> ```Kotlin
> 
> /** Builds a list of all the Kingdom's internal data-layer services. */
> fun buildDataServices(
> ```

can this be an interface since it needs to be reimplemented per cloud provider?
I'd like to see it implemented in such a way that it could be mocked up or extended for other cloud providers

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-McFYh2M1VhdmLiOslqL:-McGsgwb45oY7Oe0qOre:bbdrvll) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13bfd78f8399bed0f765be37528b5866c79e5322/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can this be an interface since it needs to be reimplemented per cloud provider?
I'd like to see it implemented in such a way that it could be mocked up or extended for other cloud providers
</blockquote></details>

As mentioned offline, this may not quite work out due to the fact that the function signature would be different depending on the cloud product. `AsyncDatabaseClient` here is a Spanner-specific construct.

The exercise for @uakyol in this PR is to add the Server that goes with the Spanner implementation of the measurement services, coming up with how to best avoid duplication. One idea is to have the DB client be a generic type argument, with possibly an accompanying test base that verifies that implementations bind all the expected service types.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 17 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: all files reviewed, 2 unresolved discussions (waiting on @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt, line 19 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-McH7Wiw9ECghN8AfBiK:-McH7Wix6BxO9olM3w6S:b2z8hs0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55087518914bf0f53fc34e6bba2a0f471df6c164/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt#L19)):*
> ```Kotlin
> import io.grpc.BindableService
> 
> interface DataServices {
> ```

This can wait until a later PR, but let's see if we can add an abstract test base for this that just ensure that the impl returns impls for the right service types.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: 26 of 28 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt, line 19 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-McH7Wiw9ECghN8AfBiK:-McKn2sM4XaD1Xnepp0w:b-7uwlbs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55087518914bf0f53fc34e6bba2a0f471df6c164/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This can wait until a later PR, but let's see if we can add an abstract test base for this that just ensure that the impl returns impls for the right service types.
</blockquote></details>

Agreed, I'll pick this up in the next PR. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-McFYh2M1VhdmLiOslqL:-McKmqfW7ByrcWfwoZCT:b81tz38) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13bfd78f8399bed0f765be37528b5866c79e5322/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As mentioned offline, this may not quite work out due to the fact that the function signature would be different depending on the cloud product. `AsyncDatabaseClient` here is a Spanner-specific construct.

The exercise for @uakyol in this PR is to add the Server that goes with the Spanner implementation of the measurement services, coming up with how to best avoid duplication. One idea is to have the DB client be a generic type argument, with possibly an accompanying test base that verifies that implementations bind all the expected service types.
</blockquote></details>

I implemented this as a interface and build the server in the SpannerKingdomServer. Hope this works.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: 26 of 28 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-McFYh2M1VhdmLiOslqL:-McLaNfr8MPKAQ6sPH28:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13bfd78f8399bed0f765be37528b5866c79e5322/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt#L23)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I implemented this as a interface and build the server in the SpannerKingdomServer. Hope this works. 
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 6 of 8 files at r4, 3 of 11 files at r5, 13 of 17 files at r6, 2 of 2 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt, line 22 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-McM4Na-2KDpL3z6ero_:-McM4Na-2KDpL3z6eroa:b2cpqno) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b967fd602ddd0a1837b5a18268004998074b5c7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt#L22)):*
> ```Kotlin
> 
>   /** Builds a list of all the Kingdom's internal data-layer services. */
>   fun buildDataServices(): List<BindableService>
> ```

Do we actually need an interface for this or can we just use a `() -> List<BindableService>` where needed?

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt, line 22 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-McM4Na-2KDpL3z6ero_:-McQ8GyX9a4NsuZyn0I0:bbkmawz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b967fd602ddd0a1837b5a18268004998074b5c7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do we actually need an interface for this or can we just use a `() -> List<BindableService>` where needed?
</blockquote></details>

Left it as an interface based on our discussion

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 13 files at r2, 6 of 8 files at r4, 3 of 11 files at r5, 13 of 17 files at r6, 2 of 2 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/95#-McFYh2M1VhdmLiOslqL:-MckSY__9UbGTFy8PCTy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13bfd78f8399bed0f765be37528b5866c79e5322/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/DataServices.kt#L23)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Pull request merged**
