### PR TITLE
Add measurement consumers service to internal reporting v2

### PR DESCRIPTION
**Pull request by tristanvuong2021**
Moved out of [#937](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/937)

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/940)

**Review by tristanvuong2021 — COMMENTED** [review]
This is for eventually inserting measurement consumers into the reporting v2 database on server startup from config.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/940#-:-NSlwh3m5E-FKr_9Kt4_:b-uy2uh0)* status: 0 of 21 files reviewed, all discussions resolved

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/940)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MeasurementConsumersServiceTest.kt` line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/940#-NSqU5Oc3FhDVVsennxZ:-NSqU5Oc3FhDVVsennx_:b-7vlndr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad325e5a38f514a5610de87eed9ba558ebf154d1/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MeasurementConsumersServiceTest.kt#L60)):*
> ```Kotlin
> 
>   @Test
>   fun `CreateMeasurementConsumer throws ALREADY_EXISTS when MeasurementConsumer already exists`() {
> ```

nit: consistent casing



_Suggestion:_
```Kotlin
createMeasurementConsumer
```
___
*[`src/main/resources/reporting/postgres/changelog_v2.yaml` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/940#-NSqTl7p9e3J4GzG-NVv:-NSqTl7p9e3J4GzG-NVw:b-3fnkfz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad325e5a38f514a5610de87eed9ba558ebf154d1/src/main/resources/reporting/postgres/changelog_v2.yaml#L1)):*
> ```YAML
> # Copyright 2023 The Cross-Media Measurement Authors
> ```

nit: name this `changelog-v2.yaml` to match the naming of other files in this package.
___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 210 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/940#-NSqUN9MBK1Tp1rcNtkV:-NSqUN9MBK1Tp1rcNtkW:b-ajdqll) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad325e5a38f514a5610de87eed9ba558ebf154d1/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L210)):*
> ```TSQL
> );
> 
> -- changeset tristanvuong2021:add-foreign-key-constraint-reporting-sets dbms:postgresql
> ```

You're already editing changesets here, so might as well include this in the CREATE TABLE statement.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/940)* status: 18 of 21 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 210 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/940#-NSqUN9MBK1Tp1rcNtkV:-NSqdoWE2gnpBgxIGPvq:b7fzifd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7580d7899b3738519276061b0aaa81f63a569a/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L210)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You're already editing changesets here, so might as well include this in the CREATE TABLE statement.
</blockquote></details>

In order to keep the original design, this has to be after the create table statements. Both ReportingSets and SetExpressions have foreign keys to each other. ReportingSets can't have a foreign key to SetExpressions before SetExpressions is created.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/940)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 210 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/940#-NSqUN9MBK1Tp1rcNtkV:-NSqpAztAgKzxDaLXuSm:bkds64x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff7580d7899b3738519276061b0aaa81f63a569a/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L210)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

In order to keep the original design, this has to be after the create table statements. Both ReportingSets and SetExpressions have foreign keys to each other. ReportingSets can't have a foreign key to SetExpressions before SetExpressions is created.
</blockquote></details>

Ah, gotcha!

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 11 of 21 files at r1, 2 of 3 files at r2, 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/940)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 11 of 21 files at r1, 2 of 3 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/940)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
