### PR TITLE
Do not populate providedId columns if they are empty

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278#-Mjf8AeG11Pm8xfHd-2L:-Mjf8AeH4OfE7AFNePn-:bfenb8y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adcd510b58f16ba1b7dcd56f920714c0e1f65718/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L55)):*
> ```
>     return findExistingEventGroup(dataProviderId)
>       ?: createNewEventGroup(dataProviderId, measurementConsumerId)
> ```

I would probably do 

```
return if (eventGroup.providedEventGroupId.isBlank()) {
   createNewEventGroup(dataProviderId, measurementConsumerId)
} else {
   findExistingEventGroup(dataProviderId)
     ?: createNewEventGroup(dataProviderId, measurementConsumerId)
}

```

Since if the providedId is empty, logically we don't need to try to find an existing eventgroup. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278#-Mjf7zNSDQ0iZjeaFqIU:-Mjf7zNT9IJInqOMCEF5:bner80p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adcd510b58f16ba1b7dcd56f920714c0e1f65718/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L71)):*
> ```
> isEmpty()
> ```
isBlank()?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278#-Mjf7sap8DxOCTmT-Pct:-Mjf7sap8DxOCTmT-Pcu:bus6md1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adcd510b58f16ba1b7dcd56f920714c0e1f65718/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L84)):*
> ```
> ·····
> ```
weird`.....` here.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @uakyol)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @uakyol)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278)* status: all files reviewed, 3 unresolved discussions (waiting on @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278#-MjjisymDL_0K8wkEPYT:-Mjjisyn98gdx9XSVqRU:b-1c6rwl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6029788a60dd4db5e686d04fab4d073c9224930/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L55)):*
> ```Kotlin
>         ?: throw KingdomInternalException(KingdomInternalException.Code.DATA_PROVIDER_NOT_FOUND)
> 
>     return if (eventGroup.providedEventGroupId.isBlank()) {
> ```

nit: could you write this more clearly and without having `createNewEventGroup()` twice? 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 108 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278#-MjjjUfW5ugiBEPMo1BG:-MjjjUfX-RuJ3YrM2ivT:b-ilribu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6029788a60dd4db5e686d04fab4d073c9224930/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L108)):*
> ```Kotlin
>       set("ExternalMeasurementId" to externalMeasurementId)
>       set("ExternalComputationId" to externalComputationId)
>       if (!measurement.providedMeasurementId.isEmpty()) {
> ```

I guess a question similar to above, why isEmpty() instead of isBlank() ?

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278#-Mjf7zNSDQ0iZjeaFqIU:-Mjk3c0XCPrDt-V7Fiy-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adcd510b58f16ba1b7dcd56f920714c0e1f65718/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L71)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> isEmpty()
> ```
isBlank()?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278#-Mjf7sap8DxOCTmT-Pct:-Mjk4BV30M5_QKt5DAMN:b-yakmby) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adcd510b58f16ba1b7dcd56f920714c0e1f65718/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L84)):*
> ·
weird, I don't see that, maybe from an earlier  commit. It should be gone now.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278#-MjjisymDL_0K8wkEPYT:-Mjk3uUJEfKsbgB3kjWl:b-nzqkq8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6029788a60dd4db5e686d04fab4d073c9224930/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L55)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

nit: could you write this more clearly and without having `createNewEventGroup()` twice? 
</blockquote></details>

I based it on what Yao wanted me to do in the above comment. Can you please provide an example for how you would like me to write it?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 108 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278#-MjjjUfW5ugiBEPMo1BG:-Mjk3a8M9HgISq5lr-EI:bna5zf1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6029788a60dd4db5e686d04fab4d073c9224930/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L108)):*
> isEmpty
ah thanks!

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278#-MjjisymDL_0K8wkEPYT:-MjkqAcw2i7oqqnkh_Jl:b-prqmob) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6029788a60dd4db5e686d04fab4d073c9224930/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L55)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I based it on what Yao wanted me to do in the above comment. Can you please provide an example for how you would like me to write it?
</blockquote></details>

Sorry, couldn't see the comment by Yao, it was gone. In that case, leave as is.

**Pull request merged**
