### PR TITLE
Update ProtoUtilTest to use a generic test proto

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/116)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/116)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

___
*[src/main/proto/wfa/measurement/test/test_config.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/116#-McplMB-9wXXr3bAvz9m:-McplMB07aNQE0PiYKdI:bp8dmjj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f197d9ad7ba54c6d811f39302142d371e7a5cc55/src/main/proto/wfa/measurement/test/test_config.proto#L17)):*
> ```
> test
> ```
Use `testing` as the package/folder to follow naming guidelines for test code.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/116)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/proto/wfa/measurement/test/test_config.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/116#-McplMB-9wXXr3bAvz9m:-Mcpo9T35tNmxlkPomh9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f197d9ad7ba54c6d811f39302142d371e7a5cc55/src/main/proto/wfa/measurement/test/test_config.proto#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> test
> ```
Use `testing` as the package/folder to follow naming guidelines for test code.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @zachcwc)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)

**Pull request merged**
