### PR TITLE
Add model outages public api

### PR DESCRIPTION
**Pull request by Marco-Premier**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032#-NWrva9K9yDWNk0t8FP_:-NWrva9K9yDWNk0t8FPa:b-vhxlxv) (no related file):*
Model Outages Service proto mentions restrictions in the comment for CreateModelOutage, but I don't see that handled in the internal service.

___
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelOutagesService.kt` line 199 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032#-NWrrYPZCQSrnEzlOBn2:-NWrrYP_0QNNpx_FDPkc:b-9wr8hz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2ce720a5f51c895936c9573f0a1d5f44e2b04a/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelOutagesService.kt#L199)):*
> ```Kotlin
>   /** Converts a public [ListModelOutagesRequest] to an internal [ListModelOutagesPageToken]. */
>   private fun ListModelOutagesRequest.toListModelOutagesPageToken(
>     showDeleted: Boolean,
> ```

The request already contains these parameters so no need to pass them in.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelOutagesServiceTest.kt` line 308 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032#-NWrvKTQBwWkwZKRpuvy:-NWrvKTR32Vo6wActBXC:b-8hdkob) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2ce720a5f51c895936c9573f0a1d5f44e2b04a/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelOutagesServiceTest.kt#L308)):*
> ```Kotlin
>       showDeleted = true
>       filter = filter {
>         timeInterval {
> ```

Forgot to set timeInterval field here.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelOutagesServiceTest.kt` line 358 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032#-NWrvFx39_7URL8rv2Pj:-NWrvFx39_7URL8rv2Pk:b-8hdkob) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2ce720a5f51c895936c9573f0a1d5f44e2b04a/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelOutagesServiceTest.kt#L358)):*
> ```Kotlin
>       showDeleted = true
>       filter = filter {
>         timeInterval {
> ```

Forgot to set timeInterval field here.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032)* status: 9 of 14 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032#-NWrva9K9yDWNk0t8FP_:-NXAHs3k4lqI6xb7PmZS:b-896fix) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Model Outages Service proto mentions restrictions in the comment for CreateModelOutage, but I don't see that handled in the internal service.
</blockquote></details>

Done.

___
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelOutagesService.kt` line 199 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032#-NWrrYPZCQSrnEzlOBn2:-NXAIeqD6z8NFZDSSyqE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2ce720a5f51c895936c9573f0a1d5f44e2b04a/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelOutagesService.kt#L199)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The request already contains these parameters so no need to pass them in.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelOutagesServiceTest.kt` line 308 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032#-NWrvKTQBwWkwZKRpuvy:-NXAJMh02zYNsEYAijFV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2ce720a5f51c895936c9573f0a1d5f44e2b04a/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelOutagesServiceTest.kt#L308)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Forgot to set timeInterval field here.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelOutagesServiceTest.kt` line 358 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032#-NWrvFx39_7URL8rv2Pj:-NXAJNPUEqzB5_pMN0y3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b2ce720a5f51c895936c9573f0a1d5f44e2b04a/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelOutagesServiceTest.kt#L358)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Forgot to set timeInterval field here.
</blockquote></details>

Done.

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelOutagesServiceTest.kt` line 119 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032#-NXB1PXS4nwjws5I70E2:-NXBRMrF20gyjXf6W9Gy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08c8ac864edbadb9500cf7caa47503106e49fb85/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelOutagesServiceTest.kt#L119)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

need another test if backup is not specified
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 2 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by tristanvuong2021 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 1 of 11 files at r1, 3 of 5 files at r2, 1 of 1 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1032)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
