### PR TITLE
Fix local test K8s deployment.

### PR DESCRIPTION
**Pull request by SanjayVas**
This makes some changes to configurations:
* authority_key_identifier_to_principal_map.textproto is now read from a ConfigMap, since it depends on API resource names.
* ComputationControl service targets are specified as flags rather than in DuchyRpcConfig. This allows for K8s service host/port substitution.
* DuchyRpcConfig was renamed to DuchyCertConfig.

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/418)

https://rally1.rallydev.com/#/?detail=/task/623033865659&fdp=true

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> authority_key_identifier_to_principal_map.textproto is now read from a ConfigMap, since it depends on API resource names.

Is this change making any real difference? 

when we add a new EDP,
using configMap, we need to
1. update the proto, 2. delete the old configMap and create a new one, 3. restart the public API.
using k8s secret, we need to
1. update the proto. 2. create a new secret 3. redeploy the public API

They take almost the same amount of time to update. But introducing configMap, we need to remember there are two places for configs in the system.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/418#-:-MtsqLNsEowixPLpuKS4:bcts3ri)* status: 0 of 46 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/k8s/local/README.md, line 123 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/418#-MtsvMev8Yj_aj9cqcEu:-MtsvMev8Yj_aj9cqcEv:bhqjefd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f81fd68ac7fd16e4dd0ae4dabf2d8afb22636827/src/main/k8s/local/README.md#L123)):*
> ```Markdown
> ```
> 
> ## Deploy Duchies
> ```

Might be good to mention here that Duchy, EDP simulator and MC Frontend Simulator all use JNI, so depending on the platform you run those command, you may need to use the tools/bazel-container script and following the "Hybrid Development" instruction.



_Code quote:_
```Markdown
Deploy Duchies
```
___
*[src/main/k8s/local/README.md, line 130 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/418#-Mtsvyb-8ex5aYf_WQdA:-Mtsvyb0EY9iTJOIJxyM:b38f18) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f81fd68ac7fd16e4dd0ae4dabf2d8afb22636827/src/main/k8s/local/README.md#L130)):*
> ```Markdown
> 
> ```shell
> //src/main/k8s/local:duchies_kind --define=k8s_secret_name=certs-and-configs-bmt62gbkh5 --define=aggregator_cert_name=duchies/aggregator/certificates/f3yI3aoXukM --define=worker1_cert_name=duchies/worker1/certificates/QtffTVXoRno --define=worker2_cert_name=duchies/worker2/certificates/eIYIf6oXuSM
> ```

missing `bazel run here`



_Code quote:_
```Markdown
//src/ma
```

**Review by SanjayVas — COMMENTED** [review]
> 1. update the proto, 2. delete the old configMap and create a new one, 3. restart the public API.

2 is actually update the configMap, not delete and recreate.

Secrets are intended to be static/immutable, whereas ConfigMaps are intended to be updatable. ConfigMaps are the right place to put configuration that can be updated, as you can update a ConfigMap and restart without having to redeploy. This is a feature that is desirable in production. In fact, we should probably move all of our configs to ConfigMaps and only have things that actually need to be secret (e.g. private keys) in K8s Secrets.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/418#-:-Mtt1EuoEAzMO2P_R_VB:btut3k9)* status: 0 of 46 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/418)* status: 0 of 46 files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 40 of 45 files at r4, 5 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/418)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/418)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 40 of 45 files at r4, 3 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/418)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
