### PR TITLE
Implement SpannerExchangesService.

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/196)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cs-sswaminathan, @kgaynor, and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cs-sswaminathan and @kgaynor)

**Review by kgaynor — APPROVED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cs-sswaminathan)

**Review by yunyeng — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
