### PR TITLE
Changes sketch decay rate to improve accuracy of reporting

### PR DESCRIPTION
**Pull request by matthewclegg**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/723)

### CODE REVIEW

**Review by jiayu-google — APPROVED** [review]
Thanks Matt
Optimal sampling rate can be adjusted accordingly --- this will depend on sketch size.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/723)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/723)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by matthewclegg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/723)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/k8s/testing/secretfiles/llv2_protocol_config_config.textproto` line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/723#-NECjc2f1dYauWa4OoSc:-NEGnOP024S2b_rWdkla:bw0dzhy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c13386cb7ce68304127736ba9f143846bfacae59/src/main/k8s/testing/secretfiles/llv2_protocol_config_config.textproto#L5)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we have a doc somewhere where we recommend values like this to measurement consumers?
</blockquote></details>

This parameter is set by the Kingdom.  Measurement consumers cannot directly specify it.  Here is a doc that gives a comparison of the improvement in accuracy obtained by using this value as compared to the previous value.  The improvement is specified as the number of additional queries that can be performed for a given level of accuracy.

https://docs.google.com/presentation/d/10etHUJk9lNWAQRbSCQmg_tYgjx4JKxGpQr2_NnKpeM4/edit?resourcekey=0-QZtak50iWlNrpi6rDxYXng#slide=id.p

**Pull request merged**
