### PR TITLE
Implement internal RefuseRequisition method.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/259)

https://rally1.rallydev.com/#/?detail=/task/608697468821&fdp=true

### CODE REVIEW

**Comment by SanjayVas** [comment]
CC @uakyol

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/259)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RefuseRequisition.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/259#-Mj58uUp7BhBOxIXZIxV:-Mj58uUp7BhBOxIXZIxW:brbjsen) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffdac3e9a7cfa4d82539df563e30d5405a6a5bc5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RefuseRequisition.kt#L47)):*
> ```
>       throw KingdomInternalException(KingdomInternalException.Code.MEASUREMENT_STATE_ILLEGAL) {
>         "Expected ${Measurement.State.PENDING_REQUISITION_FULFILLMENT}, got $state"
> ```

I feel it is best the internal service can handle those error cases more elegantly.

For example, if the MC somehow creates a nonsense measurements. All EDPs will later refuse their requisitions. The first EDP who sends the refuse request will get a ACK. But the rest EDPs will get errors and need to figure out what is going on.

For this specific case, I feel we can just update the measurement to FAILED if it is not. WDYT?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/259)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RefuseRequisition.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/259#-Mj58uUp7BhBOxIXZIxV:-Mj5OraN5pYy9etNCDBL:b-5bfez) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24fbec8b28d6246c4ac8ae12d42b25020422709e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RefuseRequisition.kt#L47)):*
I'd rather be strict than attempting to be smart. The goal is not to reduce the likelihood of getting an error, but to have the system behave correctly and predictably. If we always throw an error for an incorrect precondition, we're far less likely to hit edge cases.

> For example, if the MC somehow creates a nonsense measurements. All EDPs will later refuse their requisitions.
> ...
> For this specific case, I feel we can just update the measurement to FAILED if it is not. WDYT?

Well, we should certainly not change any state away from a terminal one. There is an argument for recording that the Requisition was refused even if the Measurement is already FAILED/CANCELLED. Right now, I'm going off of the assumption that we want a single easy-to-determine answer as to *why* a Measurement is in a non-success terminal state.

Examples:
* If the Measurement is in CANCELLED state, we know it did not succeed because the MC cancelled it. Whether an EDP wants to later refuse it is irrelevant.
* If the Measurement is in FAILED state, we look at the child Requisitions and ComputationParticipants. Whichever one is in a non-success terminal state will tell us why the Measurement failed. If a Duchy cancels or has some permanent error, whether an EDP wants to later refuse is irrelevant.

This is also why I prefer giving the EDP access to the parent Measurement state of a Requisition in some way (either directly denormalized or with a synthetic Requisition state that only exists in the public API as you previously suggested). This way the only time we should even hit this error is in a race condition where the EDP has stale state info.

> EDPs will get errors and need to figure out what is going on.

This is par for the course. Note that the EDP code doesn't need to have any special logic around handling these types of errors. `FAILED_PRECONDITION` is non-retriable, so the EDP code should just log the error and move on. When they try to list pending requisitions again, this Requisition will no longer be pending. We can start passing more actionable error details so that the EDP can have logic to determine what level to log this at and therefore whether anyone would need to look at it.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/259)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RefuseRequisition.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/259#-Mj58uUp7BhBOxIXZIxV:-Mj5Yku_9Hr8a335hbFs:bk90aul) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24fbec8b28d6246c4ac8ae12d42b25020422709e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RefuseRequisition.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'd rather be strict than attempting to be smart. The goal is not to reduce the likelihood of getting an error, but to have the system behave correctly and predictably. If we always throw an error for an incorrect precondition, we're far less likely to hit edge cases.

> For example, if the MC somehow creates a nonsense measurements. All EDPs will later refuse their requisitions.
> ...
> For this specific case, I feel we can just update the measurement to FAILED if it is not. WDYT?

Well, we should certainly not change any state away from a terminal one. There is an argument for recording that the Requisition was refused even if the Measurement is already FAILED/CANCELLED. Right now, I'm going off of the assumption that we want a single easy-to-determine answer as to *why* a Measurement is in a non-success terminal state.

Examples:
* If the Measurement is in CANCELLED state, we know it did not succeed because the MC cancelled it. Whether an EDP wants to later refuse it is irrelevant.
* If the Measurement is in FAILED state, we look at the child Requisitions and ComputationParticipants. Whichever one is in a non-success terminal state will tell us why the Measurement failed. If a Duchy cancels or has some permanent error, whether an EDP wants to later refuse is irrelevant.

This is also why I prefer giving the EDP access to the parent Measurement state of a Requisition in some way (either directly denormalized or with a synthetic Requisition state that only exists in the public API as you previously suggested). This way the only time we should even hit this error is in a race condition where the EDP has stale state info.

> EDPs will get errors and need to figure out what is going on.

This is par for the course. Note that the EDP code doesn't need to have any special logic around handling these types of errors. `FAILED_PRECONDITION` is non-retriable, so the EDP code should just log the error and move on. When they try to list pending requisitions again, this Requisition will no longer be pending. We can start passing more actionable error details so that the EDP can have logic to determine what level to log this at and therefore whether anyone would need to look at it.
</blockquote></details>

makes sense, totally agree.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)

**Comment by SanjayVas** [comment]
This is for #103.

**Pull request merged**
