### PR TITLE
Implement internal Create and Get functions for Event Group Metadata

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480)

### CODE REVIEW

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480)* status: all files reviewed, 5 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDAqUfEdJeqCEKZKTo:-MyDAqUfEdJeqCEKZKTp:bdgrwfl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3a6e175a100e2433332544657ad9f32bbf12ac4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt#L41)):*
> ```Kotlin
> class EventGroupMetadataDescriptorReader :
>   BaseSpannerReader<EventGroupMetadataDescriptorReader.Result>() {
>   data class Result(
> ```

Should this class also have `internalDataProviderId`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDB13gEac1GZRk4NdO:-MyDB13gEac1GZRk4NdP:b-6ryugw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3a6e175a100e2433332544657ad9f32bbf12ac4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt#L48)):*
> ```Kotlin
>   override val builder: Statement.Builder = Statement.newBuilder(BASE_SQL)
> 
>   /** Fills [builder], returning this [RequisitionReader] for chaining. */
> ```

nit: EventGroupMetadataDescriptorReader



_Code quote:_
```Kotlin
RequisitionReader
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt, line 77 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDBaucAb7zYJ0qPGy2:-MyDBaucAb7zYJ0qPGy3:b-h0auzs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3a6e175a100e2433332544657ad9f32bbf12ac4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt#L77)):*
> ```Kotlin
>     val externalDataProviderIdParam = "externalDataProviderId"
>     val externalDescriptorIdParam = "externalEventGroupMetadataDescriptorId"
>     println("ID params: " + externalDataProviderId + " " + externalDescriptorId)
> ```

This `println()` can be removed once you're done using it for debugging.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDE3fK1qrr9QV1D6XX:-MyDE3fK1qrr9QV1D6XY:bk9q0j7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3a6e175a100e2433332544657ad9f32bbf12ac4/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto#L27)):*
> ```protobuf
> service EventGroupMetadataDescriptors {
>   rpc CreateEventGroupMetadataDescriptor(
>       CreateEventGroupMetadataDescriptorRequest)
> ```

The `Create` method can just accept the resource to create, i.e. an `EventGroupMetadataDescriptor`.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDEAaSB0jIkd9-jK2-:-MyDEAaSB0jIkd9-jK20:bs4qbgs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3a6e175a100e2433332544657ad9f32bbf12ac4/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto#L39)):*
> ```protobuf
> 
> message GetEventGroupMetadataDescriptorRequest {
>   EventGroupMetadataDescriptor event_group_metadata_descriptor = 1;
> ```

A `Get` request should just have the external IDs of the resource:

```
message GetEventGroupMetadataDescriptorRequest {
  fixed64 external_data_provider_id = 1;
  fixed64 external_event_group_metadata_descriptor_id = 2;
}
```

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480)* status: 8 of 15 files reviewed, 5 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt, line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDvOxr-byNCAthTBoX:-MyDvOxs2DG4VIWGlfGx:b-opc1z8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08f85f0f85644c152f4d8d807f9aa24efd408c2a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt#L172)):*
> ```Kotlin
>       apiVersion = measurementDetails.apiVersion
> 
>         buildFailureLogEntry(
> ```

See comment on LiquidLegions file on why unnecessary whitespace is being added
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDAqUfEdJeqCEKZKTo:-MyDm7WZBaiyQpa2UT56:bgw7iif) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3a6e175a100e2433332544657ad9f32bbf12ac4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt#L41)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Should this class also have `internalDataProviderId`?
</blockquote></details>

Wasn't sure since it wasn't used anywhere atm, but don't mind adding -- done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDB13gEac1GZRk4NdO:-MyDn_iD-gt6CP3vnO7R:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3a6e175a100e2433332544657ad9f32bbf12ac4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt#L48)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

nit: EventGroupMetadataDescriptorReader
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt, line 77 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDBaucAb7zYJ0qPGy2:-MyDngdG9w-GMt48Wvdr:b-hx1emp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3a6e175a100e2433332544657ad9f32bbf12ac4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt#L77)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

This `println()` can be removed once you're done using it for debugging.
</blockquote></details>

Good catch -- done.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDE3fK1qrr9QV1D6XX:-MyDrmzWBl5i6jJmZEPZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3a6e175a100e2433332544657ad9f32bbf12ac4/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto#L27)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

The `Create` method can just accept the resource to create, i.e. an `EventGroupMetadataDescriptor`.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDEAaSB0jIkd9-jK2-:-MyDtW-J9WcoF4qqWUO6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3a6e175a100e2433332544657ad9f32bbf12ac4/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto#L39)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

A `Get` request should just have the external IDs of the resource:

```
message GetEventGroupMetadataDescriptorRequest {
  fixed64 external_data_provider_id = 1;
  fixed64 external_event_group_metadata_descriptor_id = 2;
}
```
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 435 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDuyH1DEguKjNbYjG0:-MyDuyH1DEguKjNbYjG1:b7e6q6m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08f85f0f85644c152f4d8d807f9aa24efd408c2a/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L435)):*
> ```Kotlin
>   }
>   private fun generateRequisitionBlobKey(context: RequisitionBlobContext): String {
>       return listOf(
> ```

I'm not really sure why this keeps happening -- I'm running ktfmt ver 0.30 each time but it's not matching with the linter here for some reason. Do you have any tips on how to lint this properly? This is my current script:

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480)* status: 8 of 15 files reviewed, 5 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 435 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDuyH1DEguKjNbYjG0:-MyE-8noDInZfKRo2i-c:b2ovb8b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08f85f0f85644c152f4d8d807f9aa24efd408c2a/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L435)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

I'm not really sure why this keeps happening -- I'm running ktfmt ver 0.30 each time but it's not matching with the linter here for some reason. Do you have any tips on how to lint this properly? This is my current script: 


</blockquote></details>

Our setup-linters action is using ktfmt 0.32 as of [v1.6.2](https://github.com/world-federation-of-advertisers/actions/releases/tag/v1.6.2)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480)* status: 13 of 15 files reviewed, all discussions resolved (waiting on @robinsons and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 435 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480#-MyDuyH1DEguKjNbYjG0:-MyJD3jm4QYJGdapMS3E:b56c317) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08f85f0f85644c152f4d8d807f9aa24efd408c2a/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L435)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Running 0.34 (the most recent update) changed lots of files - 50+ of them. I didn't want to include that in this PR so I've manually adjusted the quirks for now.
</blockquote></details>

Our lint check only cares about files that were touched by a given PR.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 8 of 13 files at r1, 4 of 7 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/480)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @robinsons)

**Pull request merged**
