### PR TITLE
Update to Bazel 5.1.1

### PR DESCRIPTION
**Pull request by iverson52000**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/622)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/622)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/622)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000)

___
*[`container.bazelrc` line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/622#-N6nhDzx3SQTJOBrR_HH:-N6nhDzx3SQTJOBrR_HI:b4wy42h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/87e016214d8703546804c8136c24ecf94ef0d30e/container.bazelrc#L5)):*
> ```
> 
> # Toolchain configuration.
> build:container --java_runtime_version=remotejdk_11
> ```

I don't think this is right. You need to use the local JDK in the container. You probably need regenerate the rbe configs with this Bazel version to get a `local_java_repository` target you can use for this purpose.

See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/tools/gen-rbe-configs and https://docs.bazel.build/versions/5.1.1/bazel-and-java.html

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/622)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000)

___
*[`container.bazelrc` line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/622#-N6nhDzx3SQTJOBrR_HH:-N6nljFjCh9v2ngdBWfH:b3z4dk0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/87e016214d8703546804c8136c24ecf94ef0d30e/container.bazelrc#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this is right. You need to use the local JDK in the container. You probably need regenerate the rbe configs with this Bazel version to get a `local_java_repository` target you can use for this purpose.

See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/tools/gen-rbe-configs and https://docs.bazel.build/versions/5.1.1/bazel-and-java.html


</blockquote></details>

Grab `rbe_configs_gen_linux_amd64` from https://github.com/bazelbuild/bazel-toolchains/releases/tag/v5.1.1 and put it somewhere in your path as `rbe_configs_gen`. Then you can run 

```shell
tools/gen-rbe-configs 5.1.1 gcr.io/ads-open-measurement/bazel:0.1.0
```

After that, this configuration should have

```
build:container --java_runtime_version=rbe_jdk
build:container --tool_java_runtime_version=rbe_jdk
build:container --extra_toolchains=//third_party/rbe_configs/java:all
```

See https://github.com/bazelbuild/bazel-toolchains for more info.

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/622)* status: 3 of 11 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`container.bazelrc` line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/622#-N6nhDzx3SQTJOBrR_HH:-N6taDmb5kbftlR9I5jA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/87e016214d8703546804c8136c24ecf94ef0d30e/container.bazelrc#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Grab `rbe_configs_gen_linux_amd64` from https://github.com/bazelbuild/bazel-toolchains/releases/tag/v5.1.1 and put it somewhere in your path as `rbe_configs_gen`. Then you can run 

```shell
tools/gen-rbe-configs 5.1.1 gcr.io/ads-open-measurement/bazel:0.1.0
```

After that, this configuration should have

```
build:container --java_runtime_version=rbe_jdk
build:container --tool_java_runtime_version=rbe_jdk
build:container --extra_toolchains=//third_party/rbe_configs/java:all
```

See https://github.com/bazelbuild/bazel-toolchains for more info.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/622)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Pull request merged**
