### PR TITLE
Propagate the image tag created.

### PR DESCRIPTION
**Pull request by wfa-siyengar**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wfa-siyengar)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932)* status: all files reviewed, 1 unresolved discussion (waiting on @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932#-NSNxlj7C5FEpr5JdWf9:-NSNxlj7C5FEpr5JdWfA:b7q1gul) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc2a6469c0c2b52fae9e3dda5c11d09325633400/.github/workflows/create-cmm-images.yml#L103)):*
> ```YAML
>       - name: Push Duchy Image
>         run: |
>           bazelisk query 'filter("push_duchy", kind("container_push", //src/main/docker:all))' |
> ```

This step fails.

```
ERROR: Skipping ' ': no such target '//: ': target ' ' not declared in package '' defined by /home/runner/work/cross-media-measurement/cross-media-measurement/BUILD.bazel
WARNING: Target pattern parsing failed.
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932)* status: all files reviewed, 1 unresolved discussion (waiting on @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932#-NSNxlj7C5FEpr5JdWf9:-NSNyL3Z5ljRy50QA_vy:b-la4zka) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc2a6469c0c2b52fae9e3dda5c11d09325633400/.github/workflows/create-cmm-images.yml#L103)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This step fails.

```
ERROR: Skipping ' ': no such target '//: ': target ' ' not declared in package '' defined by /home/runner/work/cross-media-measurement/cross-media-measurement/BUILD.bazel
WARNING: Target pattern parsing failed.
```
</blockquote></details>

I suspect the issue is that trailing space after `--define image_repo_prefix=world-federation-of-advertisers/packages \`

See the failing run at https://github.com/world-federation-of-advertisers/cross-media-measurement/actions/runs/4633644323

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932)* status: all files reviewed, 2 unresolved discussions (waiting on @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932#-NSNzVY0CpCR1BCUgRvT:-NSNzVY0CpCR1BCUgRvU:ba1epy7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc2a6469c0c2b52fae9e3dda5c11d09325633400/.github/workflows/create-cmm-images.yml#L60)):*
> ```YAML
>           bazelisk query 'filter("push_kingdom", kind("container_push", //src/main/docker:all))' |
>           xargs bazelisk build -c opt --define container_registry=ghcr.io \
>           --define image_repo_prefix=world-federation-of-advertisers/packages \
> ```

This should just be the org name to properly push to the GitHub Packages container registry.



_Suggestion:_
```YAML
world-federation-of-advertisers
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932)* status: all files reviewed, 1 unresolved discussion (waiting on @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932#-NSNzVY0CpCR1BCUgRvT:-NSS3GOd0zv-SFvWYO9n:buyfr8u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc2a6469c0c2b52fae9e3dda5c11d09325633400/.github/workflows/create-cmm-images.yml#L60)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

@SanjayVas the flow fails when we don't provide packages in the path.
</blockquote></details>

Perhaps it's the use of the GHCR_TOKEN secret? I'm not even sure what that secret is. The auth to GHCR should be able to use the built-in GITHUB_TOKEN secret.

All of our [existing packages](https://github.com/orgs/world-federation-of-advertisers/packages) were ones I was able to push either through the ["Push container images" workflow](https://github.com/world-federation-of-advertisers/containers/blob/main/.github/workflows/push-images.yml) in the containers repo or manually with `--define=container_registry=ghcr.io --define=image_repo_prefix=world-federation-of-advertisers`.

Notice how despite having a "successful" run, the packages created by this workflow are not listed there.

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`.github/workflows/create-cmm-images.yml` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932#-NSNzVY0CpCR1BCUgRvT:-NSfzaML7SDSVw5nGa4v:b-zfnkpv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc2a6469c0c2b52fae9e3dda5c11d09325633400/.github/workflows/create-cmm-images.yml#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Perhaps it's the use of the GHCR_TOKEN secret? I'm not even sure what that secret is. The auth to GHCR should be able to use the built-in GITHUB_TOKEN secret.

All of our [existing packages](https://github.com/orgs/world-federation-of-advertisers/packages) were ones I was able to push either through the ["Push container images" workflow](https://github.com/world-federation-of-advertisers/containers/blob/main/.github/workflows/push-images.yml) in the containers repo or manually with `--define=container_registry=ghcr.io --define=image_repo_prefix=world-federation-of-advertisers`.

Notice how despite having a "successful" run, the packages created by this workflow are not listed there.
</blockquote></details>

I am working on it, will comply.

**Review by wfa-mdharmalingam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932#-NSNzVY0CpCR1BCUgRvT:-NSg2SFc55Zraz6M7PWw:b-n9pcex) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc2a6469c0c2b52fae9e3dda5c11d09325633400/.github/workflows/create-cmm-images.yml#L60)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

I am working on it, will comply.
</blockquote></details>

we have removed the packages

**Review by wfa-mdharmalingam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 52 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932#-NSgCLfy6BypVzR3CCZ-:-NSgQ3ra5vUwSbnFx2bY:b-jjmce4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/951c484128a179392320f8ab1ff048c93066f004/.github/workflows/create-cmm-images.yml#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This fails with "Username and password required". See https://github.com/world-federation-of-advertisers/cross-media-measurement/actions/runs/4659649959/jobs/8246767946.

I assume what you actually need is `password: ${{ secrets.GITHUB_TOKEN }}`. The `GITHUB_TOKEN` secret is automatic, i.e. you don't need to explicitly create it within a repo.

Again, please make sure you've tested the workflow and ensured that it works before publishing comments implying that it's ready for another look. For existing workflows with a `workflow_dispatch` event trigger like this one, you can manually run it from a pending PR branch. I ran it using the "Run workflow" button here: https://github.com/world-federation-of-advertisers/cross-media-measurement/actions/workflows/create-cmm-images.yml
</blockquote></details>

We have added password: ${{ secrets.GITHUB_TOKEN }}. so it should take default github secrets

**Review by SanjayVas — CHANGES_REQUESTED** [review]
I did not see another run of this action, indicating that you have not in fact tested it first as I asked. I have kicked off a run myself at https://github.com/world-federation-of-advertisers/cross-media-measurement/actions/runs/4660142752

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932#-:-NSgTIbJ05TruXOkw5ga:b-db95m2)* status: all files reviewed, 1 unresolved discussion (waiting on @wfa-siyengar)

___
*[`.github/workflows/create-cmm-images.yml` line 49 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932#-NSgRQBh45KDKSeZJMf3:-NSgRQBh45KDKSeZJMf4:bn4ftrf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4584ef5fe422ac14fe29e4da18937428d10cc539/.github/workflows/create-cmm-images.yml#L49)):*
> ```YAML
> 
>       - name: Login to GitHub Packages
>         uses: docker/login-action@v1
> ```

Use v2, which was released almost a year ago. I'm seeing deprecation warnings that appear to be coming from using v1.



_Suggestion:_
```YAML
docker/login-action@v2
```

**Review by SanjayVas — COMMENTED** [review]
Run succeeded: https://github.com/world-federation-of-advertisers/cross-media-measurement/actions/runs/4660142752

Note how the relevant packages have a version with tag `4584ef5fe422ac14fe29e4da18937428d10cc539`: https://github.com/orgs/world-federation-of-advertisers/packages

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932#-:-NSghm5o5SoiRbIQQUOA:b-6dvdb2)* status: all files reviewed, 1 unresolved discussion (waiting on @wfa-siyengar)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/932)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wfa-siyengar)

**Pull request merged**
