### PR TITLE
Modify internal createMeasurementConsumer to use creation token.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 3 of 29 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateAccount.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr-93px-g13DnEfREGL:-MqzvOx374NM9pFJzR1o:bv57dj9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1166420af2b7fcccca2faabb0956911e010f836/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateAccount.kt#L56)):*
> ```Kotlin
>           val creatorMeasurementConsumerCreationToken =
>             readCreatorAccountResult.account.measurementConsumerCreationToken
>           if (!isMeasurementConsumerCreationTokenUsed(
> ```

IIUC, this means that someone with an existing Account is creating another Account for one of the MCs they own. Therefore this token should be the one for the MC specified by `externalOwnedMeasurementConsumerId`.

I think this might be slightly off in the docs. I'm updating it.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 3 of 29 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateAccount.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr-93px-g13DnEfREGL:-Mr0-B1G2CNoCsILQZs9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1166420af2b7fcccca2faabb0956911e010f836/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateAccount.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

IIUC, this means that someone with an existing Account is creating another Account for one of the MCs they own. Therefore this token should be the one for the MC specified by `externalOwnedMeasurementConsumerId`.

I think this might be slightly off in the docs. I'm updating it.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 15 of 29 files at r1, 23 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 38 of 39 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 188 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr3nr5p7YhJxFTd6wYy:-Mr3nr5p7YhJxFTd6wYz:b-8gm09j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e7ceba6453053d8dddb49d4757ae8c3e435770c9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L188)):*
> ```Kotlin
> 
>   @Test
>   fun `createMeasurementConsumer fails when account to be owner has not been activated`() =
> ```

Given the error messages, I think you swapped the names of this test and the one before it.



_Code quote:_
```Kotlin
has not been activated
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr3mSSw1ahXjPPWQZMA:-Mr3mSSw1ahXjPPWQZMB:b-igtrpg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e7ceba6453053d8dddb49d4757ae8c3e435770c9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L93)):*
> ```Kotlin
>   ): MeasurementConsumer {
>     val accountTokenPair = createActivatedAccount(accountsService)
>     val account = accountTokenPair.first
> ```

Use [destructuring declarations](https://kotlinlang.org/docs/destructuring-declarations.html).



_Code quote:_
```Kotlin
    val accountTokenPair = createActivatedAccount(accountsService)
    val account = accountTokenPair.first
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 234 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr3m8cX6bh8x35YDeVA:-Mr3m8cX6bh8x35YDeVB:b-avieh8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e7ceba6453053d8dddb49d4757ae8c3e435770c9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L234)):*
> ```Kotlin
>   }
> 
>   /** Returns a pair containing the [Account] and the id token. */
> ```

I don't see any cases where the ID token is used by the caller. Why return both?



_Code quote:_
```Kotlin
pair
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 270 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr3oMYf7vgFg2cZhXRy:-Mr3oMYf7vgFg2cZhXRz:bj57c6i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e7ceba6453053d8dddb49d4757ae8c3e435770c9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L270)):*
> ```Kotlin
>   }
> 
>   suspend fun createMeasurementConsumerCreationTokenHash(
> ```

nit: I think it's clearer to have the caller hash it themselves if needed.



_Code quote:_
```Kotlin
Hash
```

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 234 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr3m8cX6bh8x35YDeVA:-Mr43obt6Fgp6XCdXyCk:bj8gldf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e7ceba6453053d8dddb49d4757ae8c3e435770c9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L234)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see any cases where the ID token is used by the caller. Why return both?
</blockquote></details>

Ahh, I copied this over from another branch where I am actually using it. Changed it.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 36 of 39 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 188 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr3nr5p7YhJxFTd6wYy:-Mr43mkI1iJaxDzI3bQk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e7ceba6453053d8dddb49d4757ae8c3e435770c9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L188)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Given the error messages, I think you swapped the names of this test and the one before it.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr3mSSw1ahXjPPWQZMA:-Mr43nwu1X06p8V5ynVM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e7ceba6453053d8dddb49d4757ae8c3e435770c9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use [destructuring declarations](https://kotlinlang.org/docs/destructuring-declarations.html).
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 24 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 15 of 29 files at r1, 18 of 24 files at r2, 2 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 93 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7eeD9BNp0t-zAX5fH:-Mr7eeD9BNp0t-zAX5fI:b-zi430) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L93)):*
> ```
>   MeasurementConsumerCreationTokenId INT64 NOT NULL,
> 
>   MeasurementConsumerCreationTokenHash BYTES(32) NOT NULL,
> ```

if we're storing a hash, shouldn't we be storing a salt as well?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumerCreationToken.kt, line 29 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7eu7P6ptj8UnTgeyA:-Mr7eu7P6ptj8UnTgeyB:b-k39f00) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumerCreationToken.kt#L29)):*
> ```Kotlin
>     val internalMeasurementConsumerCreationTokenId = idGenerator.generateInternalId()
>     val measurementConsumerCreationToken = idGenerator.generateExternalId()
>     val measurementConsumerCreationTokenHash = hashSha256(measurementConsumerCreationToken.value)
> ```

see my other comment - salt these in case the hashes leak somehow.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt, line 85 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7fKxsCrFpY0UHKeMp:-Mr7fKxsCrFpY0UHKeMq:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt#L85)):*
> ```Kotlin
>           externalAccountId = account.externalAccountId
>           measurementConsumerCreationTokenHash =
>             hashSha256(apiIdToExternalId(request.measurementConsumerCreationToken))
> ```

ditto
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 285 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7g4OuEMG9YJBeT-Ob:-Mr7g4OuEMG9YJBeT-Oc:b6hgpok) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L285)):*
> ```Kotlin
>   ): String {
>     val uriParts = mutableListOf<String>()
>     uriParts.add("openid://?response_type=id_token")
> ```

we have similar code here: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea0b036499049f2770d63d017f037a730ba810c0/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L143 -- do you want to combine into a helper function?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 34 of 42 files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 285 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7g4OuEMG9YJBeT-Ob:-MrNwacu6LLuhSJk9a1O:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L285)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

we have similar code here: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea0b036499049f2770d63d017f037a730ba810c0/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L143 -- do you want to combine into a helper function?
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4, 1 of 1 files at r5, 2 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 36 of 42 files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/common/idtoken/RequestUri.kt, line 15 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-MrTU5WE10JvM2jJrHFr:-MrTU5WE10JvM2jJrHFs:b-htpso4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2016e03c840c8f44605fef4a5442001bfcab5b1/src/main/kotlin/org/wfanet/measurement/common/idtoken/RequestUri.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.common.idtoken
> ```

Anything for `org.wfanet.measurement.common` belongs in the common-jvm repo. We have a couple cases to fix in this repo that either need to be moved to common-jvm or be moved out of `measurement.common` into a different package under `measurement`.

Whether something should be in common is based on whether it's useful to more than one repo. We're likely to need OIDC functionality in the MCFE as well.



_Code quote:_
```Kotlin
org.wfanet.measurement.common.idtoken
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 93 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7eeD9BNp0t-zAX5fH:-MrTUxeO0S5PIJxKsxVH:b-41ob5t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

if we're storing a hash, shouldn't we be storing a salt as well?
</blockquote></details>

I don't believe we need salts in this case, as the token itself is just a random number and not e.g. a user-specified password. Hash values are required to be unique. The hashing is just to make sure the value in the DB can't be used to authenticate via the public AP
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumerCreationToken.kt, line 29 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7eu7P6ptj8UnTgeyA:-MrTUkzd5_c8Jcgde5W_:bwzcsbj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumerCreationToken.kt#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

see my other comment - salt these in case the hashes leak somehow.
</blockquote></details>

Hashes leaking shouldn't be much of an issue. They're useless outside of the internal API, given that they're hashes of random numbers.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/common/idtoken/RequestUri.kt, line 15 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-MrTU5WE10JvM2jJrHFr:-MrTcE8y-rK4fdQXQmrj:bv9f8k2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2016e03c840c8f44605fef4a5442001bfcab5b1/src/main/kotlin/org/wfanet/measurement/common/idtoken/RequestUri.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Anything for `org.wfanet.measurement.common` belongs in the common-jvm repo. We have a couple cases to fix in this repo that either need to be moved to common-jvm or be moved out of `measurement.common` into a different package under `measurement`.

Whether something should be in common is based on whether it's useful to more than one repo. We're likely to need OIDC functionality in the MCFE as well.
</blockquote></details>

Should I move it to common now, or just another package for now.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 36 of 42 files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 93 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7eeD9BNp0t-zAX5fH:-MrTbBkiCE2eWvNjKDFx:b4mpnqj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't believe we need salts in this case, as the token itself is just a random number and not e.g. a user-specified password. Hash values are required to be unique. The hashing is just to make sure the value in the DB can't be used to authenticate via the public AP
</blockquote></details>

if we store the hash and the hashes leak, they can be attacked with a rainbow table if we don't salt the values, right? We probably shouldn't store the API key at all -- just the hash, right?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 36 of 42 files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/common/idtoken/RequestUri.kt, line 15 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-MrTU5WE10JvM2jJrHFr:-MrTdlkL3AkG4_XM27yD:bx17z3j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2016e03c840c8f44605fef4a5442001bfcab5b1/src/main/kotlin/org/wfanet/measurement/common/idtoken/RequestUri.kt#L15)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Should I move it to common now, or just another package for now.
</blockquote></details>

Move to common-jvm as I think we may need this in another repo in the future.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 93 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7eeD9BNp0t-zAX5fH:-MrTduRGAK0TrC-RdhPL:b-b5taqm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L93)):*
> We probably shouldn't store the API key at all -- just the hash, right?

Correct. The key itself is just returned on the initial create call and never stored.

> if we store the hash and the hashes leak, they can be attacked with a rainbow table if we don't salt the values, right?

I don't think we're susceptible to rainbow table attacks given that we enforce by DB constraint that that each API key hash is unique, i.e. we don't store any colliding hashes.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 36 of 42 files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/common/idtoken/RequestUri.kt, line 15 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-MrTU5WE10JvM2jJrHFr:-MrcD1p-1LgNVJOpLQEC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2016e03c840c8f44605fef4a5442001bfcab5b1/src/main/kotlin/org/wfanet/measurement/common/idtoken/RequestUri.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move to common-jvm as I think we may need this in another repo in the future.
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 35 of 42 files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 93 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7eeD9BNp0t-zAX5fH:-MrchTf8EA5iTh4EN1YL:b-rqcoch) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> We probably shouldn't store the API key at all -- just the hash, right?

Correct. The key itself is just returned on the initial create call and never stored.

> if we store the hash and the hashes leak, they can be attacked with a rainbow table if we don't salt the values, right?

I don't think we're susceptible to rainbow table attacks given that we enforce by DB constraint that that each API key hash is unique, i.e. we don't store any colliding hashes.
</blockquote></details>

I don't think the uniqueness makes a difference here. But, I do agree that the need for a salt is very low given the high entropy of API keys. I'm okay to resolve this.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 35 of 42 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumerCreationToken.kt, line 29 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7eu7P6ptj8UnTgeyA:-Mrci4VXDyF78o1zeo2J:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumerCreationToken.kt#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Hashes leaking shouldn't be much of an issue. They're useless outside of the internal API, given that they're hashes of random numbers.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt, line 85 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7fKxsCrFpY0UHKeMp:-Mrci5QtAsZo3oy0zKa1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt#L85)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 1 of 8 files at r6, 1 of 1 files at r7, 2 of 4 files at r8, 11 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 93 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-Mr7eeD9BNp0t-zAX5fH:-MrdYhRkCB6xok7AAj3R:buttfbl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53a122af7a3b57621a3f5b5ddb33217786f4ae32/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I don't think the uniqueness makes a difference here. But, I do agree that the need for a salt is very low given the high entropy of API keys. I'm okay to resolve this.
</blockquote></details>

Sorry, you are correct about the uniqueness not being a factor, and the main factor being the entropy of the input (in this case, 64 bits). These creation tokens are also expected to be short-lived and can have an expiration.

There may be more value in adding salts to API keys for more entropy, and I'm not opposed to that as a pre-launch enhancement. We just need the plumbing for getting the salt to the public service layer so it can hash early.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 249 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404#-MrdcOfh-6RLSy4rhp5w:-MrdcOfh-6RLSy4rhp5x:bo5eejd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5d7b1c3f9f276740c96833c3345d494f8f8bfa01/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L249)):*
> ```Kotlin
> 
>   /**
>    * Generates a self-issued ID token and uses it to activate the [Account]. Returns the ID token.
> ```

nit: use the `@return` KDoc tag



_Code quote:_
```Kotlin
Returns the ID token.
```

**Review by tristanvuong2021 — COMMENTED** [review]
> Dismissed @stevenwarejones from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 44 of 45 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: 44 of 45 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/404)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
