### PR TITLE
Add getReport to reporting server

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628)

### CODE REVIEW

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1760 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628#-N7IWQ7X9Y4gdgZAm8-s:-N7Ins0vAY2g1olKnMHO:b-r9i9ou) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5bd5e9d8d72ef8361d3014c036dc0fdf570667dd/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1760)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use collection subject rather than directly referencing indices.

```kotlin
assertThat(capturedRequests).containsExactly(expectedRequest, expectedRequest)
```
</blockquote></details>

Done.
Cool. Good to know that.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 267 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628#-N7IUiQaC6Rhz3TIpzZi:-N7ImXxP0Lqa3uhWAhMa:bu4ozr6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5bd5e9d8d72ef8361d3014c036dc0fdf570667dd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L267)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is intended to throw an IllegalArgumentException.

I think what you want is 

```kotlin
encryptionKeyPairStore.getPrivateKeyHandle(measurementSpec.measurementPublicKey) ?: failGrpc(Status.FAILED_PRECONDITION) { "Encryption private key not found" }
```
</blockquote></details>

Done.
Thanks.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 180 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628#-N7Juh91-KU2z53R9Fbu:-N7Juh91-KU2z53R9Fbv:b91clmd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5bd5e9d8d72ef8361d3014c036dc0fdf570667dd/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L180)):*
> ```Kotlin
>     MEASUREMENT_CONSUMER_CERTIFICATE.publicKey.algorithm
>   )
> val MEASUREMENT_CONSUMER_SIGNING_KEY_HANDLE =
> ```

Add `private`.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 495 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628#-N7ML91J-sEpbV_iO58O:-N7ML91J-sEpbV_iO58P:bv7wkpt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/268094dc0f7dc24cfc87c5c8a6d2184da876ae5d/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L495)):*
> ```Kotlin
>   measurementReferenceId = WATCH_DURATION_MEASUREMENT_REFERENCE_ID
> 
>   results += resultPair {
> ```

Why are the results removed?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 180 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628#-N7Juh91-KU2z53R9Fbu:-N7MQg9u--JlBHxLVDH8:b-3vcg5k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5bd5e9d8d72ef8361d3014c036dc0fdf570667dd/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L180)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Add `private`.
</blockquote></details>

Done.
Nice catch. Thanks.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 495 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628#-N7ML91J-sEpbV_iO58O:-N7MSBwG582lhtuEiFgE:b-qx7voc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/268094dc0f7dc24cfc87c5c8a6d2184da876ae5d/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L495)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Why are the results removed?
</blockquote></details>

Done.
Nothing removed.

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @riemanli, and @stevenwarejones)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 7 of 9 files at r1, 1 of 2 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @riemanli, and @stevenwarejones)

**Review by renjiezh — COMMENTED** [review]
> Dismissed @riemanli from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/628)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)

**Pull request merged**
