### PR TITLE
Add ExchangeReader base class to retrieve Exchanges

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124#-Md1qfj-8DOXUu7YAxi6:-Md1qfj017VvDSV3QJqD:b-8p1b8l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7636cdb6773e2d153156f689e38a54e6544403ee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt#L26)):*
> ```Kotlin
> 
> /** Reads [Exchange] protos from Spanner. */
> class ExchangeReader(index: Index = Index.NONE) : SpannerReader<ExchangeReader.Result>() {
> ```

Maybe `recurringExchangesIndex`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124#-Md1rWyf8-o0pedSDapJ:-Md1rWyg1Cbf3Lu4AOI9:brvzh8p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7636cdb6773e2d153156f689e38a54e6544403ee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt#L64)):*
> ```Kotlin
>   }
> 
>   private fun buildExchange(struct: Struct): Exchange =
> ```

Could you convert this to a block body please? I think our convention is to use a block body unless it's a single line or starts with a scoping function like `runBlocking` or `sequence`.

```
private fun buildExchange(struct: Struct): Exchange {
  return Exchange.newBuilder()...
}
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt, line 95 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124#-Md1rCQFAcNcfGfA0k5r:-Md1rCQFAcNcfGfA0k5s:b-m8iwfe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7636cdb6773e2d153156f689e38a54e6544403ee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt#L95)):*
> ```Kotlin
> 
>   /** Converts Cloud Spanner Date to [Date]. */
>   fun com.google.cloud.Date.toProtoDate(): Date =
> ```

Maybe put this in a new file src/main/kotlin/org/wfanet/measurement/gcloud/common/Dates.kt much like src/main/kotlin/org/wfanet/measurement/gcloud/common/Timestamps.kt for easy reuse?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124#-Md1qfj-8DOXUu7YAxi6:-Md2ziGKD1nfJfc4_IU7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7636cdb6773e2d153156f689e38a54e6544403ee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe `recurringExchangesIndex`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124#-Md1rWyf8-o0pedSDapJ:-Md2zhmb4c1bWa-FHNrf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7636cdb6773e2d153156f689e38a54e6544403ee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt#L64)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could you convert this to a block body please? I think our convention is to use a block body unless it's a single line or starts with a scoping function like `runBlocking` or `sequence`.

```
private fun buildExchange(struct: Struct): Exchange {
  return Exchange.newBuilder()...
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt, line 95 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124#-Md1rCQFAcNcfGfA0k5r:-Md2zh4G2MEvxlje4IVk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7636cdb6773e2d153156f689e38a54e6544403ee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt#L95)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe put this in a new file src/main/kotlin/org/wfanet/measurement/gcloud/common/Dates.kt much like src/main/kotlin/org/wfanet/measurement/gcloud/common/Timestamps.kt for easy reuse?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/gcloud/common/Dates.kt, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124#-Md2zt5196hRidL748jJ:-Md2zt5196hRidL748jK:bog1ien) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95086c28a182c70d6da937482cc6b2b5fea98eb2/src/main/kotlin/org/wfanet/measurement/gcloud/common/Dates.kt#L20)):*
> ```Kotlin
> import com.google.type.Date
> 
> /** Converts Cloud Spanner Date to [Date]. */
> ```

This is actually not Spanner-specific (just delete the word Spanner)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
