### PR TITLE
Prevent duchy from getting direct measurements and other measurements it shouldn't have access to.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-MyyOND8E-Ktp_0hQD_9:-MyyOND8E-Ktp_0hQD_A:b-fjff8e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a6d7e9eb4443e8feeccf01e97bf06000db55f9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L28)):*
> ```Kotlin
> 
> class StreamMeasurements(
>   private val view: Measurement.View,
> ```

I'm not spotting this and `limit` being used as properties, only as ctor params.



_Code quote:_
```Kotlin
private val view: Measurement.View,
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-MyyMiLn9MpHivV80IB-:-MyyMiLn9MpHivV80IB0:b424gkj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a6d7e9eb4443e8feeccf01e97bf06000db55f9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L107)):*
> ```Kotlin
>   override fun Flow<MeasurementReader.Result>.transform(): Flow<MeasurementReader.Result> {
>     // TODO(@tristanvuong): determine how to do this in the SQL query instead
>     val originalFlow = this
> ```

nit: reduce nesting

```
if (requestFilter.externalDuchyId.isBlank()) {
  return this
}

return filter { //... 
}
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-MyyNSSr7W0LvCBY3mlm:-MyyNSSr7W0LvCBY3mln:b-3ktnbo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a6d7e9eb4443e8feeccf01e97bf06000db55f9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L112)):*
> ```Kotlin
>     } else {
>       originalFlow.filter { value: MeasurementReader.Result ->
>         value.measurement.computationParticipantsList.isNotEmpty() &&
> ```

Is this necessary, or just an optimization?

Regardless, if you're keeping it then you probably want to extract a variable for `value.measurement.computationParticipantsList` since it's referenced more than once.



_Code quote:_
```Kotlin
value.measurement.computationParticipantsList.isNotEmpty()
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 115 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-MyyNDCh2CypfTvtY4gJ:-MyyNDCh2CypfTvtY4gK:b-jp6ba7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a6d7e9eb4443e8feeccf01e97bf06000db55f9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L115)):*
> ```Kotlin
>           value
>             .measurement
>             .computationParticipantsList
> ```

nit: Convert to sequence (`asSequence`) to make the mapping lazy.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-MyyOND8E-Ktp_0hQD_9:-MyyuEtA-qxBVAFo0x9I:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a6d7e9eb4443e8feeccf01e97bf06000db55f9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not spotting this and `limit` being used as properties, only as ctor params.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-MyyNSSr7W0LvCBY3mlm:-MyyuG550opkkvUJgN8J:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a6d7e9eb4443e8feeccf01e97bf06000db55f9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L112)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this necessary, or just an optimization?

Regardless, if you're keeping it then you probably want to extract a variable for `value.measurement.computationParticipantsList` since it's referenced more than once.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 115 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-MyyNDCh2CypfTvtY4gJ:-Myz6_DZ1llu9cFzMpqX:bvhs1cb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a6d7e9eb4443e8feeccf01e97bf06000db55f9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Convert to sequence (`asSequence`) to make the mapping lazy.
</blockquote></details>

I looked up sequence and this doesn't seem like the use case for sequence. Sequence works best with a large collection that involves several intermediate operations.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-Mz1dGK4-YI33_YHOWvv:-Mz1dGK4-YI33_YHOWvw:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82f2c18369289b1d2d751ed49d9308a91f06953d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L28)):*
> ```Kotlin
> 
> class StreamMeasurements(
>   view: Measurement.View,
> ```

ditto



_Code quote:_
```Kotlin
StreamMeasurements
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-Mz1aKFIAgvKR0EjdgeK:-Mz1aKFIAgvKR0EjdgeL:brfr2rs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82f2c18369289b1d2d751ed49d9308a91f06953d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L30)):*
> ```Kotlin
>   view: Measurement.View,
>   private val requestFilter: StreamMeasurementsRequest.Filter,
>   limit: Int = 0
> ```

can limit be private too to Sanjay's point?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-Mz1dGK4-YI33_YHOWvv:-Mz1gSRw2PpGtyKFs1ti:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82f2c18369289b1d2d751ed49d9308a91f06953d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-Mz1aKFIAgvKR0EjdgeK:-Mz1gTPrEryVm6brrWu6:b-c5dluc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82f2c18369289b1d2d751ed49d9308a91f06953d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can limit be private too to Sanjay's point?
</blockquote></details>

Removing the val prevents it from being accessed.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-Mz1aKFIAgvKR0EjdgeK:-Mz1h8eC4PO7yUdG2jJP:b-w52836) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82f2c18369289b1d2d751ed49d9308a91f06953d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L30)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Removing the val prevents it from being accessed.
</blockquote></details>

where are you accessing the class variable outside this class?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-Mz1aKFIAgvKR0EjdgeK:-Mz1iW1A0fOkc_XWq4_4:b-h0fzhl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82f2c18369289b1d2d751ed49d9308a91f06953d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

where are you accessing the class variable outside this class?
</blockquote></details>

I use requestFilter in a non constructor method in the class, but not outside it. That is why it is private val. val makes it a class property.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 115 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-MyyNDCh2CypfTvtY4gJ:-Mz2FiVXBfB2yCkM8bT2:b-ui7gli) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a6d7e9eb4443e8feeccf01e97bf06000db55f9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L115)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I looked up sequence and this doesn't seem like the use case for sequence. Sequence works best with a large collection that involves several intermediate operations.
</blockquote></details>

It's basically a question of whether the `map` operation is applied eagerly or lazily. With List, it will apply eagerly. With Sequence, it will apply lazily. In the latter case, it means you iterate over the list potentially fewer times in the event that the Duchy ID is found earlier in the list.

That said, it doesn't matter much in cases like this where the list is likely to be small.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-Mz1aKFIAgvKR0EjdgeK:-MzMNXnH4W_LIKgQf52B:b-th8ydt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15c07cd0fcc123fb85d6911ac14c93185a1eafcc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L30)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I use requestFilter in a non constructor method in the class, but not outside it. That is why it is private val. val makes it a class property.
</blockquote></details>

I was asking why not make all 3 private val

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498#-Mz1aKFIAgvKR0EjdgeK:-MzMOPsD2idDCPpOgzZp:bajbq5h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15c07cd0fcc123fb85d6911ac14c93185a1eafcc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I was asking why not make all 3 private val
</blockquote></details>

@stevenwarejones Originally, I did that then Sanjay mentioned that I am not even using the other 2 outside of the constructor. By not having private val, it reduces access even more than private val.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/498)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
