### PR TITLE
Order the computationParticipants by their order in the MPC ring.

### PR DESCRIPTION
**Pull request by wangyaopw**
The mill will use this order of the computationParticipants list as
the source of truth of the mpc ring structure.

Also renamed GlobalComputationService to SystemComputationService in the herald.
However, the kingdom's computation id is still called GlobalId or
GlobalComputationId, since word "Global" is already used in the database
column.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/97)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/97)* status: all files reviewed, 3 unresolved discussions (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 95 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/97#-Mbcj3Z_7vZqfoZL7_JC:-Mbcj3Z_7vZqfoZL7_JD:bedn55f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/536f84c75832405e575881db60f7d36c646670bf/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L95)):*
> ```Kotlin
>    * order of all participants in the MPC ring structure.
>    */
>   private fun List<ComputationParticipant>.orderByRoles(
> ```

How does this relate to getDuchyOrderByPublicKeysAndComputationId in DuchyOrder.kt? Should this function replace that one?
___
*[src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/97#-MbckDWz2490AI4vcu5b:-MbckDX-9oS12-QrUGeU:b-cnv1j3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/536f84c75832405e575881db60f7d36c646670bf/src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto#L45)):*
> ```
> worker.
> ```
nif: Let's avoid this term here. They're all Duchies, just one of the Duchies is the Aggregator.
___
*[src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/97#-MbckLz20MGgEwwY_JyQ:-MbckLz20MGgEwwY_JyR:b-3cgsnw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/536f84c75832405e575881db60f7d36c646670bf/src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto#L46)):*
> ```
> external_aggregator_id
> ```
nit: perhaps `external_aggregator_duchy_id`? This would parallel `external_fulfilling_duchy_id` from the Kingdom internal services, where "fulfilling" is indicating which Duchy.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/97)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 95 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/97#-Mbcj3Z_7vZqfoZL7_JC:-Mbcm6yp2vn7SwcqxnwP:bikwvjn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/536f84c75832405e575881db60f7d36c646670bf/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L95)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

How does this relate to getDuchyOrderByPublicKeysAndComputationId in DuchyOrder.kt? Should this function replace that one?
</blockquote></details>

Yep. getDuchyOrderByPublicKeysAndComputationId() is still used by the mill currently and will be deleted when the mill switches to use the order of the list later.

The idea is the let the herald determine the order and persist the order in the computationDetails such that the mill doesn't need to compute it each time it needs it.
___
*[src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/97#-MbckDWz2490AI4vcu5b:-Mbcmvz_5d1Moiyy7asw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/536f84c75832405e575881db60f7d36c646670bf/src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> worker.
> ```
nif: Let's avoid this term here. They're all Duchies, just one of the Duchies is the Aggregator.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/97)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by zachcwc — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/97)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
