### PR TITLE
Fix bugs in HMSS implementation.

### PR DESCRIPTION
**Pull request by renjiezh**
- Bypass ShufflePhaseInput blob from SETUP_PHASE to SHUFFLE_PHASE for worker2.
- ShufflePhase correctly sorts RequisitionsList.
- VerifySecretSeed in ShufflePhase correctly interpret secret seed ciphertext.
- Handle PublicApiVersion for secret seed.
- Get non-aggregator ids from protocol config instead of SystemComputation.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxTRLrO3xzSs5sEoaws:-NxTRLrP8itwtxO-tniN:bnub6sl) (no related file):*
nit: "Fix bugs" is too vague. Be more specific in PR description, even if that just means adding a list of the bugs fixed after the title.

___
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxTRuHt9YlzGeZOM9YD:-NxTRcux91IlME2yaUTR:bn6a8tv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34539c1458801910cc86b70063a2d2b8a5a07e5e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L84)):*
> ```Kotlin
> 
>             val privateKeyHandle = TinkPrivateKeyHandle.generateHpke()
>             requireNotNull(privateKeyStore) { "privateKeyStore cannot be null" }
> ```

nit: put precondition checks as early as possible. No need to wait until computationDetails is being built.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611)* status: all files reviewed, 4 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxTRLrO3xzSs5sEoaws:-NxU9Jmo3eMCjxbJkhlb:b-ozv7u) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: "Fix bugs" is too vague. Be more specific in PR description, even if that just means adding a list of the bugs fixed after the title.
</blockquote></details>

I agree - please list out the defects and the remediations

___
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxU9W4669RqyI7k_ybz:-NxU9W4669RqyI7k_yc-:b-vr6d81) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34539c1458801910cc86b70063a2d2b8a5a07e5e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L81)):*
> ```Kotlin
>   private val protocolsSetupConfig: ProtocolsSetupConfig,
>   private val clock: Clock,
>   private val privateKeyStore: PrivateKeyStore<TinkKeyId, TinkPrivateKeyHandle>? = null,
> ```

when is null a valid use case?
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 155 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxU9mXM5gFX2QAMM38V:-NxU9mXM5gFX2QAMM38W:b-3mgxdv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34539c1458801910cc86b70063a2d2b8a5a07e5e/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L155)):*
> ```proto
> 
>     // The list of ids of non-aggregators participating in this computation.
>     repeated string non_aggregators = 3;
> ```

shouldn't we also have an aggregator field?

**Review by kungfucraig — COMMENTED** [review]
Can you describe what is being fixed in the PR description?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-:-NxUAH0n-G32jzPbUpbe:b-xzrqeb)* status: all files reviewed, 4 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxU9W4669RqyI7k_ybz:-NxUH8_X0oOzsg6zPXxg:bnwg8r5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34539c1458801910cc86b70063a2d2b8a5a07e5e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L81)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

when is null a valid use case?
</blockquote></details>

privateKeyStore is used for the encryption keys for secret seed. Aggregator does not need it for now.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 155 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxU9mXM5gFX2QAMM38V:-NxUHmPp5y78-U1tAHPH:b-9avw5k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34539c1458801910cc86b70063a2d2b8a5a07e5e/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L155)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't we also have an aggregator field?
</blockquote></details>

This non-aggregators field is only used to check whether the aggregator receives both input blob from non-aggregators.

**Review by ple13 — APPROVED** [review]
> Reviewed 12 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 247 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxRvwxw5Ut_FE-nu2sb:-NxRvwxx1tcFrwFbchEv:b-xwt73s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34539c1458801910cc86b70063a2d2b8a5a07e5e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L247)):*
> ```Kotlin
> 
>   private fun aggregatorStub(): ComputationControlCoroutineStub {
>     // The last participant is the aggregator.
> ```

nit: remove the comment line.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxU9W4669RqyI7k_ybz:-NxXt9QF3qqjSnarFwQI:b-wm1bod) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34539c1458801910cc86b70063a2d2b8a5a07e5e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L81)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

privateKeyStore is used for the encryption keys for secret seed. Aggregator does not need it for now.
</blockquote></details>

in the init, what if we check to see if the duchyId is "aggregator" or soemthing like that and throw an error if its not an aggregator but privateKeyStore is null.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 155 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxU9mXM5gFX2QAMM38V:-NxXtbun1mElF3ggEoU2:b-hr7wdw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34539c1458801910cc86b70063a2d2b8a5a07e5e/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L155)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

This non-aggregators field is only used to check whether the aggregator receives both input blob from non-aggregators.
</blockquote></details>

when would an aggregator receive data from another aggregator?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxU9W4669RqyI7k_ybz:-NxYRv_07hu7Bzvub_q9:b-gmt73t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34539c1458801910cc86b70063a2d2b8a5a07e5e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L81)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

in the init, what if we check to see if the duchyId is "aggregator" or soemthing like that and throw an error if its not an aggregator but privateKeyStore is null.
</blockquote></details>

Good idea. I added checks in init {} for both herald and mill to fail it earlier. But to take care of both null and non-null usage, the parameter here will still be nullable.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 155 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxU9mXM5gFX2QAMM38V:-NxYQBkyCesfaAH5OwCf:b2nwdzu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34539c1458801910cc86b70063a2d2b8a5a07e5e/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L155)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

when would an aggregator receive data from another aggregator?
</blockquote></details>

Sorry I didn't make it very clear. This field is used for aggregator's WAIT_ON_AGGREGATION_INPUT phase to determine whether it has received all required AggregationPhaseInput from non-aggregators. This field contains two ids of non-aggregators so the aggregator just check them against the input blobs in storage.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxTRuHt9YlzGeZOM9YD:-NxYpZEO34zdKlij4APl:b-gp5gb9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34539c1458801910cc86b70063a2d2b8a5a07e5e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L84)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: put precondition checks as early as possible. No need to wait until computationDetails is being built.
</blockquote></details>

This is still happening inside of the DSL builder for computationDetails. I meant to move it to `init`.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1611#-NxTRuHt9YlzGeZOM9YD:-NxmsAP045U9nUbm8xb0:b-ewc1s3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/34539c1458801910cc86b70063a2d2b8a5a07e5e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L84)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is still happening inside of the DSL builder for computationDetails. I meant to move it to `init`.
</blockquote></details>

It has been done in Herald's `init` while the starter is just helper functions instead of a real class.

**Pull request merged**
