### PR TITLE
feat: Log ComputationToken details for ALREADY_EXISITS computation.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1897)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1897)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/herald/Herald.kt` line 280 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1897#-OAsfXWYD6KIELXPwAbB:-OAsfXWZ9X9b4ncUGxxt:b-dsa8nv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/91ebbbd8f5fcca699d61997b8fea3d6a3328bf86/src/main/kotlin/org/wfanet/measurement/duchy/herald/Herald.kt#L280)):*
> ```Kotlin
>       // specific exception if it needs to be handled at a higher level.
>       if (e.status.code == Status.Code.ALREADY_EXISTS) {
>         logger.warning("[id=$globalId]: Computation already exists. $e")
> ```

Use overload which takes exception for stack trace logging



_Suggestion:_
```Kotlin
logger.log(Level.WARNING, e) { "[id=$globalId]: Computation already exists." }
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1897)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/herald/Herald.kt` line 280 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1897#-OAsfXWYD6KIELXPwAbB:-OAt88EZ4Bqf3glgM-5S:b-fzgyx8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/91ebbbd8f5fcca699d61997b8fea3d6a3328bf86/src/main/kotlin/org/wfanet/measurement/duchy/herald/Herald.kt#L280)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use overload which takes exception for stack trace logging
</blockquote></details>

Done. 
Thanks.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1897)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1897)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
