### PR TITLE
Command Line Tool Supports Creation of Reach Measurements.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1254)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1254)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1254#-NfI_qldA80grWR-agee:-NfI_qldA80grWR-agef:b-amrzrl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95b582a40a5fa9cc0fabc765e7fe59285f615a72/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1)):*
> ```Kotlin
> /*
> ```

Add test that exercises reach measurement type.

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1254)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md` line 156 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1254#-NfHCkbME6aaGW_kS2Ay:-NfHCkbME6aaGW_kS2Az:b-8svean) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95b582a40a5fa9cc0fabc765e7fe59285f615a72/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md#L156)):*
> ```Markdown
>     create \
>     --measurement-consumer=measurementConsumers/777 \
>     --reach-and-frequency \
> ```

Should we add one more example for --reach?
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/BenchmarkTest.kt` line 269 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1254#-NfHD2iNBVpQ21G92Txb:-NfHD2iO6ZHfpjQnTdsg:b-ehf0ne) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95b582a40a5fa9cc0fabc765e7fe59285f615a72/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/BenchmarkTest.kt#L269)):*
> ```Kotlin
> 
>   @Test
>   fun `Benchmark reach and frequency`() {
> ```

Is it intended to not have the benchmark function for reach only protocol?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1254)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/BenchmarkTest.kt` line 369 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1254#-NfMSA1x2eScc8Xsnrpl:-NfMeei2-ym1PT5d8IG3:b-p4rcev) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bde969b2d8116f80ead69a5f4dadc7aa6336a65/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/BenchmarkTest.kt#L369)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Should it be `SUCCEEDED_REACH_MEASUREMENT` instead of `SUCCEEDED_REACH_AND_FREQUENCY_MEASUREMENT`?
</blockquote></details>

Thanks. Nice catch!

**Review by ple13 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
