### PR TITLE
Add reporting v2 cli tool.

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116)

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 164 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116#-N_pS9LG1VTQcR9f4_rP:-N_pS9LG1VTQcR9f4_rQ:b-tqcrxq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/897ba0e6e52329b6a0ed1cdb66aca860da89b4a7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L164)):*
> ```Kotlin
>                 )
>             }
>         }
> ```

What if the user doesn't provider either?



_Code quote:_
```Kotlin
        if (type.cmmsEventGroups != null && type.cmmsEventGroups!!.isNotEmpty()) {
          primitive =
            ReportingSetKt.primitive { type.cmmsEventGroups!!.forEach { cmmsEventGroups += it } }
        } else if (type.textFormatSetExpression != null) {
          composite =
            ReportingSetKt.composite {
              expression =
                parseTextProto(
                  type.textFormatSetExpression!!.reader(),
                  ReportingSet.SetExpression.getDefaultInstance()
                )
            }
        }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 235 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116#-N_pSOOXBkGBrFTYyv-F:-N_pSOOXBkGBrFTYyv-G:bveiegi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/897ba0e6e52329b6a0ed1cdb66aca860da89b4a7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L235)):*
> ```Kotlin
>     names = ["--reporting-metric-entry"],
>     description = ["ReportingMetricEntry protobuf messages in text format"],
>     required = false,
> ```

Based on `v2alpha/report.proto`, it should be required.

**Review by riemanli — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 164 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116#-N_pS9LG1VTQcR9f4_rP:-N_t4ad81vM1qvs0HtEt:bv3il7t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/897ba0e6e52329b6a0ed1cdb66aca860da89b4a7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L164)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

What if the user doesn't provider either.
</blockquote></details>

It will throw an error. Multiplicity of "1" makes it required.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 235 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116#-N_pSOOXBkGBrFTYyv-F:-N_t41XY75PMi7vkdFVl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/897ba0e6e52329b6a0ed1cdb66aca860da89b4a7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L235)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Based on `v2alpha/report.proto`, it should be required.
</blockquote></details>

Done.

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 235 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116#-N_pSOOXBkGBrFTYyv-F:-N_tNInQ-SsuvdcKd0mQ:b-i4sar0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/897ba0e6e52329b6a0ed1cdb66aca860da89b4a7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L235)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could you add a unit test of when there is no reporting metric entry?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 235 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116#-N_pSOOXBkGBrFTYyv-F:-N_u9lTK5-Xh-KqLPLRc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/897ba0e6e52329b6a0ed1cdb66aca860da89b4a7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L235)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Could you add a unit test of when there is no reporting metric entry?
</blockquote></details>

Done.

**Review by riemanli — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1116)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
