### PR TITLE
Enable public API to use new ReplaceDataProviderRequiredDuchies method in internal API

### PR DESCRIPTION
**Pull request by jojijac0b**
- Update API version in repositories.bzl so replaceDataProviderRequiredDuchies method is generated in api/v2aplha DataProviderService parent class.
- Implement logic in replaceDataProviderRequiredDuchies to parse public API request and call internal replaceDataProviderRequiredDuchies method.
- Updates return DataProvider to include requiredExternalDuchyIds field.
- Update tests for DataProviderService.

https://rally1.rallydev.com/#/604612930531d/iterationstatus?detail=%2Ftask%2F697342967991

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 115 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTtQOFE5P78k2thNMPr:-NTtQOFE5P78k2thNMPs:b-aemrki) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L115)):*
> ```Kotlin
>     val internalDataProvider: org.wfanet.measurement.internal.kingdom.DataProvider =
>       try {
>         internalClient.replaceDataProviderRequiredDuchies(
> ```

this is not returning anything currently in your test. You need to mock this call.

**Review by Marco-Premier — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: all files reviewed, 4 unresolved discussions (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwWcV29Q79HyrQ9JvX:-NTwWcV29Q79HyrQ9JvY:b-2178pv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L91)):*
> ```Kotlin
>     val requiredDuchyList: List<String> =
>       request.requiredExternalDuchiesList.map { name ->
>         val duchyKey = DuchyKey.fromName(name)
> ```

This can be simplified by using the existing Precondition method ```grpcRequireNotNull```



_Code snippet:_
```Kotlin
val requiredDuchyList: List<String> =
  request.requiredExternalDuchiesList.map { name ->
    val duchyKey = grpcRequireNotNull(DuchyKey.fromName(name)) { "Resource name unspecified or invalid" }
    duchyKey.duchyId
  }
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwXqXy8fosyJjbk13U:-NTwXqXy8fosyJjbk13V:b-8y73m9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L113)):*
> ```Kotlin
>     }
> 
>     val internalDataProvider: org.wfanet.measurement.internal.kingdom.DataProvider =
> ```

let's move the mport statement ( ``` import org.wfanet.measurement.internal.kingdom.DataProvider``` ) at the top of the file and only leave ```DataProvider``` here



_Code quote:_
```Kotlin
org.wfanet.measurement.internal.kingdom.DataProvider
```

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwWcV29Q79HyrQ9JvX:-NTy8IABCvzfPXxT_Dkm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L91)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

This can be simplified by using the existing Precondition method ```grpcRequireNotNull```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwXqXy8fosyJjbk13U:-NTy8KRW9Gfvs_21Urxv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L113)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

let's move the mport statement ( ``` import org.wfanet.measurement.internal.kingdom.DataProvider``` ) at the top of the file and only leave ```DataProvider``` here
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersServiceTest.kt` line 75 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTtQ1yJDhyKYI6k4xfW:-NTy8TQMESVrOINlMQLM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersServiceTest.kt#L75)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you need to add replaceDataProviderRequiredDuchies to the mockService
</blockquote></details>

Done.

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 115 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTtQOFE5P78k2thNMPr:-NTy95tfBoNN22nJHRhH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L115)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this is not returning anything currently in your test. You need to mock this call.
</blockquote></details>

Done.

**Review by Marco-Premier — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwXqXy8fosyJjbk13U:-NTyjOC06C0fVekSZFNE:b-qbgtf6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L113)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry I think I explained myself not so well, I meant to move the import statement ```import org.wfanet.measurement.internal.kingdom.DataProvider``` at the topo of the file where all the other imports are, and only use the Class type (DataProvider) here. e.g.

```
val internalDataProvider: DataProvider = 
   try{
      ...
```

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwXqXy8fosyJjbk13U:-NTyth7eAmvgdXsTIR4i:b-elo8p0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L113)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Sorry I think I explained myself not so well, I meant to move the import statement ```import org.wfanet.measurement.internal.kingdom.DataProvider``` at the topo of the file where all the other imports are, and only use the Class type (DataProvider) here. e.g.

```
val internalDataProvider: DataProvider = 
   try{
      ...
```
</blockquote></details>

Removed the type to be consistent with the getDataProvider method(https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L64)

Can import type and add it back if needed.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 104 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTz29q7BpwZHqg_8jbo:-NTz29q7BpwZHqg_8jbp:bvh9xps) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f41676c85e9e29e9d73805b3d4922c7c1d090565/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L104)):*
> ```Kotlin
>       else -> {
>         failGrpc(Status.PERMISSION_DENIED) {
>           "Caller does not have permission to update DataProviders"
> ```

I prefer ```
"Only a DataProvider and update a DataProvider"

**Review by Marco-Premier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwXqXy8fosyJjbk13U:-NTz3dC41o9lPWHaDYS0:b-w999iv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L113)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Removed the type to be consistent with the getDataProvider method(https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L64)

Can import type and add it back if needed.
</blockquote></details>

Happy with the type being inferred :)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwXqXy8fosyJjbk13U:-NU2RVOq-TfIS-mcPsz5:b-ypa779) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L113)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Happy with the type being inferred :)
</blockquote></details>

IIUC, I think what the comment is saying is to add an import for the type rather than using its fully qualified name. In public service implementations, we generally use an import alias for internal message types.


```kotlin
import org.wfanet.measurement.internal.kingdom.DataProvider as InternalDataProvider
```

As per [our style guide](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin), types should be indicated explicitly rather than inferred unless it would be redundant. This is not such a case (the variable name isn't sufficient to consider it redundant, but rather the fact that it's not e.g. calling a constructor or common factory function). A lot of our existing code unfortunately doesn't strictly adhere to this, but all new code certainly should.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersServiceTest.kt` line 211 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NU2T7wlD0tdUnfJN5oN:-NU2T7wlD0tdUnfJN5oO:b-hrbsrn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a2353b239417080dd227e2eba8eccf6ce83d7a1a/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersServiceTest.kt#L211)):*
> ```Kotlin
>       requiredExternalDuchyIds += DUCHIES
>     }
>     assertThat(dataProvider).isEqualTo(expectedDataProvider)
> ```

Also verify the argument to the internal service RPC. (See how other test methods use `verifyProtoArgument`).

**Review by jojijac0b — COMMENTED** [review]
https://rally1.rallydev.com/#/604612930531d/iterationstatus?detail=%2Ftask%2F697342967991

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-:-NU2c3juED4jBHzJSL68:b1y9kgs)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b)

**Review by Marco-Premier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwXqXy8fosyJjbk13U:-NU2vTv99b2fQ_Qvqtua:b38ctlt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L113)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

IIUC, I think what the comment is saying is to add an import for the type rather than using its fully qualified name. In public service implementations, we generally use an import alias for internal message types.


```kotlin
import org.wfanet.measurement.internal.kingdom.DataProvider as InternalDataProvider
```

As per [our style guide](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin), types should be indicated explicitly rather than inferred unless it would be redundant. This is not such a case (the variable name isn't sufficient to consider it redundant, but rather the fact that it's not e.g. calling a constructor or common factory function). A lot of our existing code unfortunately doesn't strictly adhere to this, but all new code certainly should.
</blockquote></details>

Fair enough. Do we have plans for refactoring this old parts of the code. As I become more familiar with the code base, sometime I see different pattern / code style being used for similar use cases. Do we track them somewhere @SanjayVas ?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwXqXy8fosyJjbk13U:-NU38G9AEH2AF3Cw21bc:bzfn8g1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L113)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Fair enough. Do we have plans for refactoring this old parts of the code. As I become more familiar with the code base, sometime I see different pattern / code style being used for similar use cases. Do we track them somewhere @SanjayVas ?
</blockquote></details>

No plans for a large-scale refactor, just trying to apply the policy to new code. For this particular issue, most of the non-conformant cases just slipped through code review as its easy to miss. I've been guilty of violating it too.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwXqXy8fosyJjbk13U:-NU6RSOh1Y3B7g0QOvLO:b-udppy3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L113)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No plans for a large-scale refactor, just trying to apply the policy to new code. For this particular issue, most of the non-conformant cases just slipped through code review as its easy to miss. I've been guilty of violating it too.
</blockquote></details>

Ok. I'll see whether I can devolve a bit of time trying to align the code to explicitly indicates types

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwXqXy8fosyJjbk13U:-NUNmVy05lWVZgCQlJha:bi5ksni) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L113)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Ok. I'll see whether I can devolve a bit of time trying to align the code to explicitly indicates types
</blockquote></details>

you're just wanting him to explicitly set the type, right?

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NTwXqXy8fosyJjbk13U:-NUNmdbV7tbLbnOcYEnJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/732acad2467d8f56c57062709b25217a1b6d842d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L113)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you're just wanting him to explicitly set the type, right?
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersServiceTest.kt` line 211 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966#-NU2T7wlD0tdUnfJN5oN:-NUNmcNz4Wicgy0PNFB_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a2353b239417080dd227e2eba8eccf6ce83d7a1a/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersServiceTest.kt#L211)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also verify the argument to the internal service RPC. (See how other test methods use `verifyProtoArgument`).
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Review by jojijac0b — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/966)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Pull request merged**
