### PR TITLE
Check Measurement ConsumerId in EdpSimulator

### PR DESCRIPTION
**Pull request by uakyol**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 388 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067#-NY1IuQ29gIzYEu4DtNx:-NY1IuQ41diy38LzAXzu:b3h52ya) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed72b6e9f56393d635078595155369b4b7734556/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L388)):*
> ```Kotlin
>     val requisitions =
>       getRequisitions().filter {
>         MeasurementKey.fromName(it.measurement)!!.measurementConsumerId == measurementConsumerName
> ```

This is comparing and ID to a name. Just directly compare it.measurement to measurementConsumerName

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 388 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067#-NY1IuQ29gIzYEu4DtNx:-NY1g9qi5De19xBPtvK7:bh5tyhc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed72b6e9f56393d635078595155369b4b7734556/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L388)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is comparing and ID to a name. Just directly compare it.measurement to measurementConsumerName
</blockquote></details>

ah sorry, didn't see your comment and updated based on lifeofameasurement test failing. How about this?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 388 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067#-NY1IuQ29gIzYEu4DtNx:-NY4CkLq2nDu7sZLup4o:b-ys81jg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed72b6e9f56393d635078595155369b4b7734556/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L388)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

ah sorry, didn't see your comment and updated based on lifeofameasurement test failing. How about this?
</blockquote></details>

Ah, I also made a mistake in my comment. Parse both names to their respective keys, then compare the MC ID fields.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 388 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067#-NY1IuQ29gIzYEu4DtNx:-NY4WeVQ1dojz_zDOuMx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed72b6e9f56393d635078595155369b4b7734556/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L388)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, I also made a mistake in my comment. Parse both names to their respective keys, then compare the MC ID fields.
</blockquote></details>

Done.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 399 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067#-NYOx0VW6TKwRliA9__2:-NYPDazXDTftSQcEJqF4:b-f2iipg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2775994026f78f6905a813e57e8771edf5a62767/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L399)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a logger if you need to log something.
</blockquote></details>

sorry, meant to remove
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 300 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067#-NYOxJl5-3y00rsCnv15:-NYPFKHZEv5tnUw3ULOv:b-oufmx0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2775994026f78f6905a813e57e8771edf5a62767/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L300)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why was this changed? It used to be a `@BeforeClass` for a JVM static member (and had a more descriptive function name).
</blockquote></details>

If I do it that way, the test fails with null check failing. Correct me if I am wrong but I think this is because it is initialized once before the class and not before each test case. This causes other test cases to write to that temp folder and those writes being visible to this new test

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Marco-Premier and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 300 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067#-NYOxJl5-3y00rsCnv15:-NYPZ63l7GLdpdy86lPh:b-qpzbtd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2775994026f78f6905a813e57e8771edf5a62767/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L300)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

If I do it that way, the test fails with null check failing. Correct me if I am wrong but I think this is because it is initialized once before the class and not before each test case. This causes other test cases to write to that temp folder and those writes being visible to this new test
</blockquote></details>

Whether that's right depends on the test design. e.g. if each test method inherently deals with different blob keys, then having the temp directory initialized once is fine.

If you want to switch from `@BeforeClass` to `@Before`, just make sure to keep the same descriptive names. The whole reason JUnit4 switched to annotated methods is to avoid having the non-descript "setup" and "teardown" methods of JUnit3.

**Comment by uakyol** [comment]
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 300 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067#-NYOxJl5-3y00rsCnv15:-NYPhly88ff-69lt01-y:b-qanq0p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2775994026f78f6905a813e57e8771edf5a62767/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L300)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Whether that's right depends on the test design. e.g. if each test method inherently deals with different blob keys, then having the temp directory initialized once is fine.

If you want to switch from `@BeforeClass` to `@Before`, just make sure to keep the same descriptive names. The whole reason JUnit4 switched to annotated methods is to avoid having the non-descript "setup" and "teardown" methods of JUnit3.
</blockquote></details>

thanks, I kept it as `@Before`  and updated the "setup" method name to "initSketchStore" thats what you were referring to right?

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1067)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
