### PR TITLE
Add proto for eventGroup delete

### PR DESCRIPTION
**Pull request by jcorilla**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)

### CODE REVIEW

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815#-NM4mr8_0Zhn8dHkSeaL:-NM4mr8_0Zhn8dHkSeaM:b-225gzg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93343500afc055620608e04a04dda3efa298f3aa/src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto#L48)):*
> ```protobuf
> }
> 
> message DeleteEventGroupRequest {
> ```

Can you update your request message to follow the convention in the AIPs?
Reference: https://google.aip.dev/135#request-message

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815#-NM4mr8_0Zhn8dHkSeaL:-NM5AlfK9YXb7KE6YT5X:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93343500afc055620608e04a04dda3efa298f3aa/src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto#L48)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you update your request message to follow the convention in the AIPs?
Reference: https://google.aip.dev/135#request-message
</blockquote></details>

Done.

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815#-NM4mr8_0Zhn8dHkSeaL:-NM5qSWMBhYbmtuHesD2:b953ewq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93343500afc055620608e04a04dda3efa298f3aa/src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is the internal Kingdom API, so we actually don't want to do this here. The delete request should just use the external IDs.
</blockquote></details>

Changed to require to external ids used by the EventGroupReader.
Also removed the annotations to be consistent with other internal Kingdom api

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla and @kungfucraig)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815#-NM5zWVK44Vxg66fz2B0:-NM5zWVK44Vxg66fz2B1:b-672v8c) (no related file):*
nit: use more accurate/specific PR description. Something like "Add Delete method to internal EventGroups service definition."

"Add proto" is vague, since you could be adding anything to any protobuf message definition.

___

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla)

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815#-NM5zWVK44Vxg66fz2B0:-NM69Etb02-k8IAM1zK7:b7vmp5f) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use more accurate/specific PR description. Something like "Add Delete method to internal EventGroups service definition."

"Add proto" is vague, since you could be adding anything to any protobuf message definition.
</blockquote></details>

Got it, will do before merging

___

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto` line 32 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815#-NMU7Zp09tCkftIrdaK5:-NMUV5gG38a599Yg30wL:becdmss) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/869b8f22b6b664522cd4e9d320f26a5792ed04ee/src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should we be offering a disable option as well? Or is the only use case delete?
</blockquote></details>

This is intended to support retention policies, so this should clear out data.

It likely needs to be a [soft delete](https://google.aip.dev/164) underneath since the Reporting server references these (e.g. Get/List requests need a `show_deleted`field). We wouldn't support undelete, as we're still intentionally deleting some data.

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla)

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @jcorilla)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto` line 32 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815#-NMU7Zp09tCkftIrdaK5:-NMV_fxi9YD0kiAmYLBW:b-e54n78) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/869b8f22b6b664522cd4e9d320f26a5792ed04ee/src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is intended to support retention policies, so this should clear out data.

It likely needs to be a [soft delete](https://google.aip.dev/164) underneath since the Reporting server references these (e.g. Get/List requests need a `show_deleted`field). We wouldn't support undelete, as we're still intentionally deleting some data.
</blockquote></details>

Current plan is to implement as a soft delete, without an undelete/re-enable option since the use case is for retention.

**Review by jcorilla — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
