### PR TITLE
Implement v2alpha public measurements service

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 4 of 8 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 88 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgSaJKN3nvvJOZ1Q589:-MgSaJKN3nvvJOZ1Q58A:b-r69hle) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d8fbb805a039ab7487ff09b99ee1ed4a4c66ee4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L88)):*
> `isValidUtf8`

I don't think we expect any of our serialized byte data to always be valid UTF-8. This is also only relevant if you happen to want to encode as a string.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 140 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgSbHn48hi0pORI_9cC:-MgSbHn48hi0pORI_9cD:b-5dphsv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d8fbb805a039ab7487ff09b99ee1ed4a4c66ee4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L140)):*
> ```Kotlin
>           when (state) {
>             State.STATE_UNSPECIFIED, State.UNRECOGNIZED ->
>               addStates(InternalState.STATE_UNSPECIFIED)
> ```

This should result in an INVALID_ARGUMENT status.

e.g.
```
failGrpc { <some message> }
```

Also put the failure conditions at the end of the `when`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 208 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgScLFK2q50TGaV5I8r:-MgScLFK2q50TGaV5I8s:bjz8sim) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d8fbb805a039ab7487ff09b99ee1ed4a4c66ee4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L208)):*
> ```Kotlin
> private fun InternalState.toState(): State =
>   when (this) {
>     InternalState.STATE_UNSPECIFIED, InternalState.UNRECOGNIZED -> State.STATE_UNSPECIFIED
> ```

nit: put the unspecified condition last
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgS_B8m2MdCNj5-OwcV:-MgS_B8m2MdCNj5-OwcW:bj2qrml) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d8fbb805a039ab7487ff09b99ee1ed4a4c66ee4/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L93)):*
> ```protobuf
>   fixed64 external_measurement_id = 2;
> 
>   Measurement.View measurement_view = 3;
> ```

nit: Cancellation would only happen from MC via public API, so we don't need to support other views here.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 88 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgSaJKN3nvvJOZ1Q589:-MgSwzY_7yR6qbkfgbVG:by6hre9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d8fbb805a039ab7487ff09b99ee1ed4a4c66ee4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> `isValidUtf8`

I don't think we expect any of our serialized byte data to always be valid UTF-8. This is also only relevant if you happen to want to encode as a string.
</blockquote></details>

Removed all UTF-8 checks.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 88 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgSaJKN3nvvJOZ1Q589:-MgSx1pv0wOke0HznA6a:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d8fbb805a039ab7487ff09b99ee1ed4a4c66ee4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L88)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Removed all UTF-8 checks.
</blockquote></details>

Done.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 140 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgSbHn48hi0pORI_9cC:-MgSx3jC5G_R9UhCjgcK:b2pn3l9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d8fbb805a039ab7487ff09b99ee1ed4a4c66ee4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L140)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should result in an INVALID_ARGUMENT status.

e.g.
```
failGrpc { <some message> }
```

Also put the failure conditions at the end of the `when`
</blockquote></details>

Fixed it here and did the same in the Requisitions code.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 140 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgSbHn48hi0pORI_9cC:-MgSxCeP1OGaV1FrM61o:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d8fbb805a039ab7487ff09b99ee1ed4a4c66ee4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L140)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Fixed it here and did the same in the Requisitions code.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgfoyoS594bTltoPIUK:-MgfoyoS594bTltoPIUL:bubwbmy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86f61a4bffd32cd806fc3ba5ae70db1a77e58db8/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L95)):*
> ```Kotlin
>         }
>         try {
>           addAllStates(request.filter.statesList.map(State::toInternal))
> ```

nit: prefer the extensions to do pure conversions and have the caller determine what the exceptional behavior is

e.g.
```
addAllStates(request.filter.statesList.map { state ->
  state.toInternal().also { internalState ->
    grpcRequire(internalState != InternalState.STATE_UNSPECIFIED) { "msg" }
  }
}
```

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgfoyoS594bTltoPIUK:-Mgg5DkQ6UA8I0Goyz6k:b-ipkz7b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86f61a4bffd32cd806fc3ba5ae70db1a77e58db8/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L95)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: prefer the extensions to do pure conversions and have the caller determine what the exceptional behavior is

e.g.
```
addAllStates(request.filter.statesList.map { state ->
  state.toInternal().also { internalState ->
    grpcRequire(internalState != InternalState.STATE_UNSPECIFIED) { "msg" }
  }
}
```
</blockquote></details>

Changed it for the filter states list and removed it for the refusal justification because when I added a test for it, I discovered I didn't need it.

**Comment by tristanvuong2021** [comment]
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgS_B8m2MdCNj5-OwcV:-Mgg6RU38iUl1UFjILbh:b-ynwl21) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d8fbb805a039ab7487ff09b99ee1ed4a4c66ee4/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Cancellation would only happen from MC via public API, so we don't need to support other views here.
</blockquote></details>

I removed it.

**Review by tristanvuong2021 — COMMENTED** [review]
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: 10 of 12 files reviewed, all discussions resolved (waiting on @oliver-amzn and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 80 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgqK9f-BTfKX3QXjWnz:-MgqK9f-BTfKX3QXjWo-:b-8zu3yc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da5c91ccc0de9d5c0c9d5d4a9cbf394e90b6e54d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L80)):*
> ```
> createMeasurement
> ```
@sanjayvas 

where do we validate the measurement? for example, if the output differentialPrivacyParameter is not set in the measurement, the create should fail, either in the pubicApi or get the error from internal service.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 80 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgqK9f-BTfKX3QXjWnz:-MgqP1mMCZ2osADJzQ1e:b45s097) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da5c91ccc0de9d5c0c9d5d4a9cbf394e90b6e54d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L80)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> createMeasurement
> ```
@sanjayvas 

where do we validate the measurement? for example, if the output differentialPrivacyParameter is not set in the measurement, the create should fail, either in the pubicApi or get the error from internal service.
</blockquote></details>

The request should be validated in the public service impl when possible. This includes checking if required fields have been set. Validations that depend on existing DB state will need to be done in the internal service impl and be bubbled up.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 80 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgqK9f-BTfKX3QXjWnz:-MgqR4PpDUtynlXfqVVJ:b33cbvm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da5c91ccc0de9d5c0c9d5d4a9cbf394e90b6e54d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L80)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The request should be validated in the public service impl when possible. This includes checking if required fields have been set. Validations that depend on existing DB state will need to be done in the internal service impl and be bubbled up.
</blockquote></details>

agree. So here we still to validate that 

1. protocolConfig resource name is valid.
2. measurementReferenceId is not empty.

parse the measurementSpec to validate that
3. measurementPublicKey is not empty
4. reachAndFrequency noise parameters are all set, i.e., epsilon and delta > 0

for each dataProviderEntry, validate that
5. key is a valid dataprovider name
6. all fields in the value are set.

We need to validate the message as much as possible in the public service, possibly with xxxxRequestValidator helper class,

But feel free to add a TODO here.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 80 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgqK9f-BTfKX3QXjWnz:-Mgr8_Wl0vyfNzkQp0lK:bh2fpyb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da5c91ccc0de9d5c0c9d5d4a9cbf394e90b6e54d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L80)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

agree. So here we still to validate that 

1. protocolConfig resource name is valid.
2. measurementReferenceId is not empty.

parse the measurementSpec to validate that
3. measurementPublicKey is not empty
4. reachAndFrequency noise parameters are all set, i.e., epsilon and delta > 0

for each dataProviderEntry, validate that
5. key is a valid dataprovider name
6. all fields in the value are set.

We need to validate the message as much as possible in the public service, possibly with xxxxRequestValidator helper class,

But feel free to add a TODO here.
</blockquote></details>

I already have validation for the dataProviderEntries, but I should move it. Should protocolConfig be checked? I didn't do anything with it because the public proto says it is output-only. The measurementReferenceId doesn't have required in the comment in the public proto as well.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 80 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgqK9f-BTfKX3QXjWnz:-MgrAnAd3VoSLx9XRxtI:bpqlt5v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da5c91ccc0de9d5c0c9d5d4a9cbf394e90b6e54d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L80)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I already have validation for the dataProviderEntries, but I should move it. Should protocolConfig be checked? I didn't do anything with it because the public proto says it is output-only. The measurementReferenceId doesn't have required in the comment in the public proto as well.
</blockquote></details>

In addition to check if `dataProvidersList`  is empty or not, we also want to validate each of the entries in the list.

oh, you are right about `protocolConfig`, it shouldn't be set in the request, no need to check it.

**Review by oliver-amzn — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r5, 2 of 2 files at r7, 3 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[build/repositories.bzl, line 42 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgrLUK_3GckSx1Pkxvy:-MgrLUK_3GckSx1Pkxvz:becb188) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c4c266f7d3aae34f7c3e8196b6672981acd838f/build/repositories.bzl#L42)):*
> ```Starlark
>         repo = "cross-media-measurement-api",
>         sha256 = "d6f4844455793b25ba9af230fe09068c5567fc4957ebfe5ae610e2622832f49d",
>         version = "0.2.0",
> ```

Why not pin a version any longer?
(0.3.0 was just released with this sha)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 240 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgrMPYN1AK_rHS5uFLg:-MgrMPYO79NtQ6z_cIoE:ba60dmj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c3eafc8ab1ec70b152d60dbd6db3e6a812150ca/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L240)):*
> ```Kotlin
>     Refusal.Justification.DECLINED -> InternalRefusal.Justification.DECLINED
>     Refusal.Justification.JUSTIFICATION_UNSPECIFIED, Refusal.Justification.UNRECOGNIZED ->
>       org.wfanet.measurement.internal.kingdom.Requisition.Refusal.Justification
> ```

Thy the long import?

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 240 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgrMPYN1AK_rHS5uFLg:-MgrOacY5uCUPwFk9mKb:bt2vr1b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c3eafc8ab1ec70b152d60dbd6db3e6a812150ca/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L240)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Thy the long import? 
</blockquote></details>

Fixed.

**Comment by tristanvuong2021** [comment]
___
*[build/repositories.bzl, line 42 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgrLUK_3GckSx1Pkxvy:-MgrOg2e4XzZe2Tsgbb7:b-rpz18a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c4c266f7d3aae34f7c3e8196b6672981acd838f/build/repositories.bzl#L42)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Why not pin a version any longer?
(0.3.0 was just released with this sha)
</blockquote></details>

Changed it to the new version.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @tristanvuong2021)

___
*[build/repositories.bzl, line 42 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgrLUK_3GckSx1Pkxvy:-MgrPBWB1d8MR5wObtMp:b44tpx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c4c266f7d3aae34f7c3e8196b6672981acd838f/build/repositories.bzl#L42)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Changed it to the new version.
</blockquote></details>

👍
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 240 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgrMPYN1AK_rHS5uFLg:-MgrPHP61iPToo5J77Iv:b44tpx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c3eafc8ab1ec70b152d60dbd6db3e6a812150ca/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L240)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

👍

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 240 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgrMPYN1AK_rHS5uFLg:-MgrQRhk8mRNfpa2Esax:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c3eafc8ab1ec70b152d60dbd6db3e6a812150ca/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L240)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

👍
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 3 files at r8, 1 of 1 files at r9, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 80 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgqK9f-BTfKX3QXjWnz:-MgrB_0d6iw3ZWks4lxH:b-6hxuzg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da5c91ccc0de9d5c0c9d5d4a9cbf394e90b6e54d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L80)):*
> Should protocolConfig be checked? I didn't do anything with it because the public proto says it is output-only.

It is indeed output-only and should not be verified. The service picks the protocol config based on the measurement type specified in the measurement spec. Leave a TODO for this for now since we don't have a ProtocolConfig config (yes, a config file for `ProtocolConfig`s :P )

> The measurementReferenceId doesn't have required in the comment in the public proto as well.

Correct. We've so far stated that this is an optional idempotency key, and therefore only needs to be unique if specified.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 80 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgqK9f-BTfKX3QXjWnz:-MgrWqf2APnZjbA6DA-T:b-hu3w3y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da5c91ccc0de9d5c0c9d5d4a9cbf394e90b6e54d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L80)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Should protocolConfig be checked? I didn't do anything with it because the public proto says it is output-only.

It is indeed output-only and should not be verified. The service picks the protocol config based on the measurement type specified in the measurement spec. Leave a TODO for this for now since we don't have a ProtocolConfig config (yes, a config file for `ProtocolConfig`s :P )

> The measurementReferenceId doesn't have required in the comment in the public proto as well.

Correct. We've so far stated that this is an optional idempotency key, and therefore only needs to be unique if specified.
</blockquote></details>

we can skip the measurementReferenceId check. Nice to check each of the dataProvidersList elements.

but not a blocking comment anyways

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 80 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgqK9f-BTfKX3QXjWnz:-Mgr_wLtC3cOPm1A8Dzu:b-qc6xvf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da5c91ccc0de9d5c0c9d5d4a9cbf394e90b6e54d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L80)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

we can skip the measurementReferenceId check. Nice to check each of the dataProvidersList elements.

but not a blocking comment anyways
</blockquote></details>

maybe also

"parse the measurementSpec to validate that
3. measurementPublicKey is not empty
4.  if hasReachAndFrequency, then two epsilons and two deltas > 0"

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 80 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgqK9f-BTfKX3QXjWnz:-Mgrbk1K4AnEC_KAwX55:bbgq7jj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da5c91ccc0de9d5c0c9d5d4a9cbf394e90b6e54d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L80)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

maybe also

"parse the measurementSpec to validate that
3. measurementPublicKey is not empty
4.  if hasReachAndFrequency, then two epsilons and two deltas > 0"
</blockquote></details>

I moved the check for the elements to createMeasurement so it is in the same spot as all the other checks now and I started working on validating the parsed measurementSpec.

**Review by tristanvuong2021 — COMMENTED** [review]
> Dismissed @oliver-amzn from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @wangyaopw)

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 80 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgqK9f-BTfKX3QXjWnz:-MgvWDLlDnDAf3OLOdkN:b-k4hm5z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da5c91ccc0de9d5c0c9d5d4a9cbf394e90b6e54d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L80)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I moved the check for the elements to createMeasurement so it is in the same spot as all the other checks now and I started working on validating the parsed measurementSpec.
</blockquote></details>

I added the measurement spec validation now.

**Review by wangyaopw — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-:-MgvWcBg2J0mB6_9QW_4:bnfp4nl)* status: 10 of 13 files reviewed, all discussions resolved (waiting on @oliver-amzn and @SanjayVas)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 96 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgvXWBH3UUPe0tN8G79:-MgvXWBIB6n6h3c43xLN:b-3j61la) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e469e3b3dd15f1af5fa7b6d58f5f9760da18194c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L96)):*
> ```
> parsedMeasurementSpec
> ```
 nit: break these grpcRequires to several helper methods to improve readability.

At least, we could have validateMeasurementSpec() validateDataProviders()

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 96 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182#-MgvXWBH3UUPe0tN8G79:-MgvajQBCsrk1JPdablJ:b-qzafhj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e469e3b3dd15f1af5fa7b6d58f5f9760da18194c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L96)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> parsedMeasurementSpec
> ```
 nit: break these grpcRequires to several helper methods to improve readability.

At least, we could have validateMeasurementSpec() validateDataProviders()
</blockquote></details>

I moved some validation out into separate methods now.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 4 files at r5, 1 of 2 files at r7, 1 of 3 files at r8, 2 of 4 files at r11, 2 of 3 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
