### PR TITLE
ci: Keep Trivy cache up-to-date on default branch

### PR DESCRIPTION
**Pull request by SanjayVas**
See https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#updating-caches-in-the-default-branch

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1878)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1878)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`.github/workflows/scan-images.yml` line 99 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1878#-OAI4oC32MOCSFT7fFpB:-OAI4oC32MOCSFT7fFpC:bo9fdvv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/124da422572a3a0034f7c20e7998209cbd3b2e1c/.github/workflows/scan-images.yml#L99)):*
> ```YAML
>         uses: aquasecurity/trivy-action@0.28.0
>         env:
>           TRIVY_SKIP_DB_UPDATE: true
> ```

why would we skip updating the vulnerability db?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1878)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`.github/workflows/scan-images.yml` line 99 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1878#-OAI4oC32MOCSFT7fFpB:-OAJ3ud568H5Dox9hiOx:b-g3ya5p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/124da422572a3a0034f7c20e7998209cbd3b2e1c/.github/workflows/scan-images.yml#L99)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why would we skip updating the vulnerability db?
</blockquote></details>

The idea is to use the cached versions rather than having the Trivy application attempt to download the DBs. The link in the PR description explains this.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1878)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1878)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
