### PR TITLE
Allow Herald to skip stage to catch up with Measurement state.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671#-O0FeLcD1q2HjpoQx0O6:-O0FeLcE1sYWobHjsKUL:b-wkbaax) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9d4b10016e00b3c86d345bb1fa51d221c8155064/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L144)):*
> ```Kotlin
>       // key has been set, skip the stage to catch up to the Measurement state.
>       Stage.INITIALIZED -> {
>         if (!isInitialized(token)) {
> ```

Both pieces of information we're checking here (stage and encryption_key_pair) come from the computation details in the token. Shouldn't these always be consistent?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671#-O0FeLcD1q2HjpoQx0O6:-O0GK1704ZWsPrqDskcD:b-voopkt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9d4b10016e00b3c86d345bb1fa51d221c8155064/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L144)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Both pieces of information we're checking here (stage and encryption_key_pair) come from the computation details in the token. Shouldn't these always be consistent?
</blockquote></details>

Nope. They are not guaranteed consistent.
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/00a8897353e28513952b16fec873ea1b18297c7b/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachFrequencyLiquidLegionsV2Mill.kt#L251-L263
The process is:
1. Update the token with algamal keys if not created, otherwise skip.
2. Update the Participant at the kingdom (with the algamal keys)
3. Update the own stage.
This was to avoid duplication of creating algamal keys.

The check here is to avoid the case that Kingdom's participant state is abnormal (not happening now, but it is a check).

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671)* status: 1 of 3 files reviewed, all discussions resolved

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671#-O0FeLcD1q2HjpoQx0O6:-O0GQYoi5qZKXJtNOMWe:b-aj2p54) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9d4b10016e00b3c86d345bb1fa51d221c8155064/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L144)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Nope. They are not guaranteed consistent.
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/00a8897353e28513952b16fec873ea1b18297c7b/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachFrequencyLiquidLegionsV2Mill.kt#L251-L263
The process is:
1. Update the token with algamal keys if not created, otherwise skip.
2. Update the Participant at the kingdom (with the algamal keys)
3. Update the own stage.
This was to avoid duplication of creating algamal keys.

The check here is to avoid the case that Kingdom's participant state is abnormal (not happening now, but it is a check).
</blockquote></details>

Is this mentioning the existing process, or the new one? It sounds like we need to handle two cases where the encryption key has already been written to the local Duchy DB:

1. Participant not yet updated at Kingdom (crash after step 1 above)
2. Participant updated at Kingdom, but local state transition not yet recorded (crash after step 2 above)

Doesn't this PR only handle (2)?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671#-O0FeLcD1q2HjpoQx0O6:-O0GTL9K6LOkoK0tznHI:b7kv1ed) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9d4b10016e00b3c86d345bb1fa51d221c8155064/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L144)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this mentioning the existing process, or the new one? It sounds like we need to handle two cases where the encryption key has already been written to the local Duchy DB:

1. Participant not yet updated at Kingdom (crash after step 1 above)
2. Participant updated at Kingdom, but local state transition not yet recorded (crash after step 2 above)

Doesn't this PR only handle (2)?
</blockquote></details>

The process is the existing one. This PR is to handle (2)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671#-O0FeLcD1q2HjpoQx0O6:-O0GUoOGBYyXHZ8bodCb:b-ewdnh5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9d4b10016e00b3c86d345bb1fa51d221c8155064/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L144)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

The process is the existing one. This PR is to handle (2)
</blockquote></details>

(1) should have been addressed by your PR 
https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1665/files#diff-1eebd5edc220318daad624461a19b99a772fa8238c8d9c9128ca2416de6655c4R315

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671#-O0FeLcD1q2HjpoQx0O6:-O0GVCLO3IK_XR82kqWy:byl8nv1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9d4b10016e00b3c86d345bb1fa51d221c8155064/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L144)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

(1) should have been addressed by your PR 
https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1665/files#diff-1eebd5edc220318daad624461a19b99a772fa8238c8d9c9128ca2416de6655c4R315
</blockquote></details>

Ah, I missed the fact that only (2) could hit this logic as this is called from the Herald based on computation state.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1671)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
