### PR TITLE
Set participant_child_reference_id for claimWork log entries.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1683)

**Review by renjiezh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1683)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsService.kt` line 362 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1683#-O1JQbXq0W9ztpXIU7f2:-O1JQbXr5XiDgLdmfsKN:b7ziwzu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b1ec774c8334f7e48d759d9634070bc1eaa19cc/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsService.kt#L362)):*
> ```Kotlin
>   }
> 
>   private fun newCreateComputationLogEntryRequest(
> ```

There is a postgres implementation of it in
src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1683)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsService.kt` line 362 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1683#-O1JQbXq0W9ztpXIU7f2:-O1NnNgO7S1YofMoFi6C:bsrodu4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b1ec774c8334f7e48d759d9634070bc1eaa19cc/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsService.kt#L362)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

There is a postgres implementation of it in
src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt
</blockquote></details>

Good catch! Done and updated test.

**Review by renjiezh — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1683)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1683)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1683)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
