### PR TITLE
feat: Mill skips advancing stage when the next stage is in a future stage

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1793)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 23 files at r1, 23 of 25 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1793)* status: 25 of 27 files reviewed, 3 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt` line 794 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1793#-O67VyKz0slDvTPgkvek:-O67VyKz0slDvTPgkvel:bhwm2vh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f18b394fef78b3c02609da6373e74e209e648215/src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt#L794)):*
> ```Kotlin
>   }
> 
>   protected suspend fun getComputationStageInOtherDuchy(
> ```

This method must not throw StatusException.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/mill/liquidlegionsv2/ReachFrequencyLiquidLegionsV2Mill.kt` line 393 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1793#-O67VDnd-pirZPjMczXe:-O67VDnd-pirZPjMczXf:b-o3rdvm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f18b394fef78b3c02609da6373e74e209e648215/src/main/kotlin/org/wfanet/measurement/duchy/mill/liquidlegionsv2/ReachFrequencyLiquidLegionsV2Mill.kt#L393)):*
> ```Kotlin
> 
>     val nextDuchyId = nextDuchyId(llv2Details.participantList)
>     val nextDuchyStub = nextDuchyStub(llv2Details.participantList)
> ```

nit: you don't technically need to call `nextDuchyStub` here as you already have `nextDuchyId`. You can just access `workerStubs` directly.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/mill/liquidlegionsv2/ReachFrequencyLiquidLegionsV2Mill.kt` line 949 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1793#-O67Xk4U3OUs5CTUUJq4:-O67Xk4U3OUs5CTUUJq5:bb9q3cl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f18b394fef78b3c02609da6373e74e209e648215/src/main/kotlin/org/wfanet/measurement/duchy/mill/liquidlegionsv2/ReachFrequencyLiquidLegionsV2Mill.kt#L949)):*
> ```Kotlin
> 
>   /** Returns true when next duchy is in a future stage. */
>   private fun skipAdvanceComputation(expectedStage: Stage, actualStage: Stage): Boolean {
> ```

This function name implies that the function is actually performing the skip, as function names are generally verbs or verb phrases. It also knows too much, e.g. about next vs. current Duchy. I think it would be clearer to refactor/rephrase this function to just tell you whether it's a future stage.

Clearer yet IMO would be to make a [`Comparator<Stage>`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-comparator/) based on a given stage sequence. That class can than be shared across Mill impls.



_Suggestion:_
```Kotlin
  /** Returns whether this [Stage] is after [other] in [stageSequence]. */
  private fun Stage.isSequencedAfter(other: Stage): Boolean {
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1793)* status: 22 of 27 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt` line 794 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1793#-O67VyKz0slDvTPgkvek:-O68jcq93On_Dhhw2ymm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f18b394fef78b3c02609da6373e74e209e648215/src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt#L794)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This method must not throw StatusException.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/mill/liquidlegionsv2/ReachFrequencyLiquidLegionsV2Mill.kt` line 949 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1793#-O67Xk4U3OUs5CTUUJq4:-O68jhAVAzvuFNmJP-vo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f18b394fef78b3c02609da6373e74e209e648215/src/main/kotlin/org/wfanet/measurement/duchy/mill/liquidlegionsv2/ReachFrequencyLiquidLegionsV2Mill.kt#L949)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This function name implies that the function is actually performing the skip, as function names are generally verbs or verb phrases. It also knows too much, e.g. about next vs. current Duchy. I think it would be clearer to refactor/rephrase this function to just tell you whether it's a future stage.

Clearer yet IMO would be to make a [`Comparator<Stage>`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-comparator/) based on a given stage sequence. That class can than be shared across Mill impls.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1793)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 22 of 25 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1793)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
