### PR TITLE
Add Open Telemetry Auto Instrumented Traces to Cloud Trace

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1537)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1537)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/k8s/dev/open_telemetry_gke.cue` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1537#-Nu0w4oyAVAJ58O2wUo5:-Nu0w4oyAVAJ58O2wUo6:bas17e2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/72316f7b760e7a72aa9cded62e52ad61e51a7e99/src/main/k8s/dev/open_telemetry_gke.cue#L52)):*
> ```CUE
> 
> collectors: {
> 	"default": {
> ```

Can you not just specify the parts that need to be overridden? This is just a CUE struct.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1537)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/dev/open_telemetry_gke.cue` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1537#-Nu0w4oyAVAJ58O2wUo5:-Nu52Aem6Nnf97PXJDvZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/72316f7b760e7a72aa9cded62e52ad61e51a7e99/src/main/k8s/dev/open_telemetry_gke.cue#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you not just specify the parts that need to be overridden? This is just a CUE struct.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1537)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1537)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1537)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1537)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
