### PR TITLE
Add CLI tool for validating event templates.

### LINKED ISSUE #1168: Revert the dependency on uk-pilot-event-templates
We added the uk-pilot-event-templates to be later used in the EdpSimulator. (https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1068)

But the plans have changed about using them. Thus, we need to revert that dependency

### PR DESCRIPTION
**Pull request by SanjayVas**
This also drops the UK Pilot event templates from this repository.

Closes #1168

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1156)

**Comment by SanjayVas** [comment]
Depends on https://github.com/world-federation-of-advertisers/uk-pilot-event-templates/pull/5

**Review by uakyol — APPROVED** [review]
Looks great. Thanks for putting this together.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1156#-:-NbMjBYf3ACLgL5W_ADi:b-68jc97)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`build/repositories.bzl` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1156#-NbMhtlA35b53zRVUGo1:-NbMhtlA35b53zRVUGo2:b3dcah6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d5b7430204900b071db0ea23d6d276398d1fdacd/build/repositories.bzl#L51)):*
> ```Starlark
>     wfa_repo_archive(
>         name = "uk_pilot_event_templates",
>         # DO_NOT_SUBMIT(world-federation-of-advertisers/uk-pilot-event-templates#5): Use version.
> ```

Sorry, what does this mean? Does it mean create a release after world-federation-of-advertisers/uk-pilot-event-templates#5 is submitted and then depend on that?
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EventTemplateValidator.kt` line 137 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1156#-NbMikMX9VoBS3uV5rFV:-NbMikMX9VoBS3uV5rFW:b-xw98wv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d5b7430204900b071db0ea23d6d276398d1fdacd/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EventTemplateValidator.kt#L137)):*
> ```Kotlin
>         Descriptors.FieldDescriptor.Type.SINT32,
>         Descriptors.FieldDescriptor.Type.SINT64, ->
>           throw ValidationException("$fieldRef has unsupported type ${field.type.name.lowercase()}")
> ```

This is good to know :)

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @uakyol from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1156)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

___
*[`build/repositories.bzl` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1156#-NbMhtlA35b53zRVUGo1:-NbQ2oPNCjkNrEvKqHIK:b-oyxx95) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d5b7430204900b071db0ea23d6d276398d1fdacd/build/repositories.bzl#L51)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Sorry, what does this mean? Does it mean create a release after world-federation-of-advertisers/uk-pilot-event-templates#5 is submitted and then depend on that?
</blockquote></details>

Yes. Basically saying don't submit (merge) this PR until it has been updated to use a release version that contains the other PR.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1156)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @uakyol from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @uakyol)

**Pull request merged**
