### PR TITLE
Add prioritizedStages for duchy claimTask

### PR DESCRIPTION
**Pull request by renjiezh**
Issue https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1637

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1673)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1673)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationsDatabase.kt` line 130 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1673#-O0Pi6fhAEPPQ1XW6uOM:-O0Pi6fhAEPPQ1XW6uON:by6wz8z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/619028905038eee304988f9d6c0e4236b17285c1/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationsDatabase.kt#L130)):*
> ```Kotlin
>     ownerId: String,
>     lockDuration: Duration,
>     prioritizedStages: List<StageT> = listOf(),
> ```

nit: document the new param
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/readers/ComputationReader.kt` line 376 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1673#-O0PgVNEDdGST4MlKBYF:-O0PgVNEDdGST4MlKBYG:bbwkbra) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/619028905038eee304988f9d6c0e4236b17285c1/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/readers/ComputationReader.kt#L376)):*
> ```Kotlin
>           """
>       } else {
>         // Binding list of String into the IN clause does not work as expected with r2dbc library.
> ```

Direct string replacement is unsafe. You should still always use binding. The way to do it with r2dbc-postgres is unfortunately having to dynamically add the right number of parameters. Luckily, Tristan created ValuesListBoundStatement to help do that for you.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/UnclaimedTasksQuery.kt` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1673#-O0PhIL580wZCWs_CIGM:-O0PhIL580wZCWs_CIGN:bv43b5s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/619028905038eee304988f9d6c0e4236b17285c1/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/UnclaimedTasksQuery.kt#L28)):*
> ```Kotlin
> class UnclaimedTasksQuery<StageT>(
>   protocol: Long,
>   prioritizedStageLongValues: List<Long>,
> ```

Generally we want to keep the specific type until the last moment. In this case, converting to Long only when needed. Any reason we can't do that here?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1673)* status: 14 of 19 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/readers/ComputationReader.kt` line 376 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1673#-O0PgVNEDdGST4MlKBYF:-O1Svx4FAq71ppI49rb_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/619028905038eee304988f9d6c0e4236b17285c1/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/readers/ComputationReader.kt#L376)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Direct string replacement is unsafe. You should still always use binding. The way to do it with r2dbc-postgres is unfortunately having to dynamically add the right number of parameters. Luckily, Tristan created ValuesListBoundStatement to help do that for you.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/UnclaimedTasksQuery.kt` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1673#-O0PhIL580wZCWs_CIGM:-O1Svy8Z-uxPKD4viipl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/619028905038eee304988f9d6c0e4236b17285c1/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/UnclaimedTasksQuery.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Generally we want to keep the specific type until the last moment. In this case, converting to Long only when needed. Any reason we can't do that here?
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1673)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
Currently computations are picked up by mills in order of the creation time. A new computation will not be touched before all older computations are complete. It leads to a problem that new computations could keep waiting in initial stage and EDPs are idle. By prioritize computations in initial stage, we can make sure all computations is in fulfillable stage while mills are doing their job.

Linked the github issue.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1673#-:-O1rzejLDLW3uOD3zc3H:b-wxf859)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 8 of 18 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1673)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 7 of 18 files at r1, 5 of 5 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1673)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
