### PR TITLE
Fix mismatch vid range of synthetic population specs.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1783)

**Comment by renjiezh** [comment]
The global range did not match the last subrange.

**Review by ple13 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1783)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1783)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/k8s/testing/data/synthetic_population_spec_large.textproto` line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1783#-O5Pxfy21_l7X6-xW45q:-O5Pxfy21_l7X6-xW45r:b5p77bf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1724d8f50259ff408fc4706c95c93ed130142298/src/main/k8s/testing/data/synthetic_population_spec_large.textproto#L10)):*
> ```
> vid_range {
>   start: 1
>   end_exclusive: 34335356  # Age 18-64 with known social grade.
> ```

This should be fixed in the event group specs instead. As documented above, this is the real population from the UK census.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1783)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/k8s/testing/data/synthetic_population_spec_large.textproto` line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1783#-O5Pxfy21_l7X6-xW45q:-O5Umqp12ditvRgiH3ME:bg1rqwm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1724d8f50259ff408fc4706c95c93ed130142298/src/main/k8s/testing/data/synthetic_population_spec_large.textproto#L10)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be fixed in the event group specs instead. As documented above, this is the real population from the UK census.
</blockquote></details>

Done.
Updated.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1783)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

___
*[`src/main/k8s/testing/data/synthetic_population_spec_large.textproto` line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1783#-O5Pxfy21_l7X6-xW45q:-O5Ur9OO-RDhZZyN-Q-K:b-74b7yy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1724d8f50259ff408fc4706c95c93ed130142298/src/main/k8s/testing/data/synthetic_population_spec_large.textproto#L10)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
Updated.
</blockquote></details>

For context, this population spec is supposed to match the 2011 UK census. It had some incorrect values, so this PR also fixes those.

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1783)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

___
*[`src/main/k8s/testing/data/synthetic_population_spec_large.textproto` line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1783#-O5Pxfy21_l7X6-xW45q:-O5VEAiZ8iuPvk_voIfK:b6m6fmb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1724d8f50259ff408fc4706c95c93ed130142298/src/main/k8s/testing/data/synthetic_population_spec_large.textproto#L10)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

For context, this population spec is supposed to match the 2011 UK census. It had some incorrect values, so this PR also fixes those.
</blockquote></details>

@renjiezh Can you update the comment "UK population by ..." to "2011 UK population by ..."

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1783)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
