### PR TITLE
Implement updating ComputationDetails + requsitionDetailUpdates.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/72)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/72)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt, line 242 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/72#-MaFVhAJ03bGSM7vibOu:-MaFVhAJ03bGSM7vibOv:b-kv2i4i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1b829b4932f352252c5e82cb41c3a0d3d3acb31/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt#L242)):*
> ```Kotlin
>         tokenBuilder
>           .requisitionsBuilderList
>           .find { it.externalRequisitionId == update.key.externalRequisitionId }
> ```

Rather than an n^2 algorithm, how about:

```
val requisitionBuildersByExternalId = tokenBuilder.requisitionBuilderList.associatedBy { it.externalRequisitionId }
for (update in requisitionDetailUpdates) {
  requisitionBuildersByExternalId[update.key.externalRequisitionId]
    ?.setDetails(update.detail)
    ?: error("requisition not found")
}
```
___
*[src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt, line 285 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/72#-MaFWXiz-XB8ZMcwk-5l:-MaFWXiz-XB8ZMcwk-5m:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1b829b4932f352252c5e82cb41c3a0d3d3acb31/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt#L285)):*
> ```Kotlin
>       val tokenBuilder = existing.toBuilder()
>       tokenBuilder
>         .requisitionsBuilderList
> ```

Ditto

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/72)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt, line 242 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/72#-MaFVhAJ03bGSM7vibOu:-MaFac159feloV4thylz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1b829b4932f352252c5e82cb41c3a0d3d3acb31/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt#L242)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Rather than an n^2 algorithm, how about:

```
val requisitionBuildersByExternalId = tokenBuilder.requisitionBuilderList.associatedBy { it.externalRequisitionId }
for (update in requisitionDetailUpdates) {
  requisitionBuildersByExternalId[update.key.externalRequisitionId]
    ?.setDetails(update.detail)
    ?: error("requisition not found")
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt, line 285 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/72#-MaFWXiz-XB8ZMcwk-5l:-MaFadPXBOXOXxR7f4YN:b39woja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f1b829b4932f352252c5e82cb41c3a0d3d3acb31/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt#L285)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Here it only updates one requisition, so using find() is OK

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/72)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by zachcwc — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/72)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
