### PR TITLE
Clean up outdated references to health probe certificates.

### PR DESCRIPTION
**Pull request by SanjayVas**
The health probe has been using a non-TLS port since 23d2255c84049798aa034be02cacf61f8e475531.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/722)

### CODE REVIEW

**Review by jonmolle — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/722)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @jonmolle and @SanjayVas)

___
*[`docs/gke/kingdom-deployment.md` line 248 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/722#-NDoJlcLBt7lkatSOSkO:-NDoJlcLBt7lkatSOSkP:b-hbtot4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79cdb02dbeaa01ec2b014fa7c3267e0507191ec0/docs/gke/kingdom-deployment.md#L248)):*
> ```Markdown
>     Note: This assumes that all your root certificate PEM files end in newline.
> 
> 1.  `kingdom_tls.pem`
> ```

Are these all supposed to be '1'?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/722)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @jonmolle)

___
*[`docs/gke/kingdom-deployment.md` line 248 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/722#-NDoJlcLBt7lkatSOSkO:-NDoTiaE7BHVbJCb-yti:b-x558nt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/685ed72198ee962c2a4e73c32d3c7f1e343c006b/docs/gke/kingdom-deployment.md#L248)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Are these all supposed to be '1'?
</blockquote></details>

Yep. They get rendered with the right values in the resulting HTML. This prevents you from having to renumber everything when you add/remove an item.

See https://www.markdownguide.org/basic-syntax/#lists-1

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/722)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> Dismissed @jonmolle from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/722)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

**Pull request merged**
