### PR TITLE
ci:Migrate worker2 from AWS to GCP

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1966)

**Review by SanjayVas — APPROVED** [review]
Do you want to also drop AWS Terraforming here, or do that in a future PR?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1966#-:-ODqxUqV8co0JZejljJX:b-61vkwi)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Comment by renjiezh** [comment]
> Do you want to also drop AWS Terraforming here, or do that in a future PR?
> 
> > Reviewed 4 of 4 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1966#-:-ODqxUqV8co0JZejljJX:b-61vkwi)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

I will do that in the next PR.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1966)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
