### PR TITLE
Migrate duchy postgres package to deploy/common

### PR DESCRIPTION
**Pull request by YuhongWang-Amazon**
This migrates duchy postgres package from duchy/deploy/ to duchy/deploy/common/.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1103)

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1103)* status: 0 of 19 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1103#-N_KDLvL8AYPkHCN3Jgd:-N_KDLvL8AYPkHCN3Jge:bn6mkio) (no related file):*
@SanjayVas we discussed that this postgres package should go to common directory. Since I am splitting that large PR out, I think it is good time to migrate before this package gets too large.

___

**Review by SanjayVas — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1103)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

**Review by renjiezh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1103#-:-N_epY0qDtcUhjpG7FAW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

**Pull request merged**
