### PR TITLE
Catch KingdomInternalException and throw Grpc errors

### PR DESCRIPTION
**Pull request by renjiezh**
Issue: https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/247

 When a specific resource is not found, use `FAILED_PRECONDITION`, `INVALID_ARGUMENT` or `NOT_FOUND`?

 As `INVALID_ARGUMENT` is more about the format of arguments, avoid to use it in our cases.

 When the major entity is not found, use `NOT_FOUND`. For example, if `getMeasurement` or `updateMeasurement` fail to find the `Measurement`, we call it `NOT_FOUND`.

 Other than the major entity, use `FAILED_PRECONDITION`. For example, for `getMeasurement` or `updateMeasurement`, if `Account`/`MeasurementConsumer`/`Certificate` not found, call it `FAILED_PRECONDITION`.

 

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/552)

### CODE REVIEW

**Review by SanjayVas — COMMENTED** [review]
`INVALID_ARGUMENT` is only for cases where a request would never work. If some dependent entity could theoretically eventually exist to make the request valid, it's not `INVALID_ARGUMENT`. See https://developers.google.com/maps-booking/reference/grpc-api/status_codes#invalid_argument_vs_failed_precondition_vs_out_of_range

As far as `NOT_FOUND`vs. `FAILED_PRECONDITION`: From the public API, certainly the parent not being found implies the child won't be either so e.g. GetMeasurement should give `NOT_FOUND` if the parent `Measurement` isn't found. Some other resource referenced by the request probably shouldn't give a `NOT_FOUND`. Where things get tricky is in the internal API, as the parent-child relationship isn't as clear. Regardless, I assume the entity being specifically acted on by the method not being found should give `NOT_FOUND` and other things not being found should be `FAILED_PRECONDITION`.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/552#-:-N1EwFi6CpttpSSsiOq_:b-2g7ibk)* status: 0 of 51 files reviewed, all discussions resolved

**Review by renjiezh — COMMENTED** [review]
Make sense. If the parent not found, it also indicates the entity not found. For GetFoo and UpdateFoo it fits.  But for some cases like `CreateApiKey()`, if the parent MC not found, should we return `NOT_FOUND`? Returning `NOT_FOUND` for creating something looks not so good. What about using FAILED_PRECONDITION instead for CreateFoo when parent not found and using NOT_FOUND for GetFoo and Update Foo?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/552#-:-N1G9BrBCLzySp1N85oN:bwk5ymy)* status: 0 of 51 files reviewed, all discussions resolved

**Review by SanjayVas — COMMENTED** [review]
`NOT_FOUND` still makes sense for a create of a child resource in the public API. A Create method is technically operating on the collection, so `NOT_FOUND` indicates that the collection is not found, as it cannot be since the parent resource it belongs to is not found.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/552#-:-N1KeH667OKfyl0iB-7R:bvn81du)* status: 0 of 51 files reviewed, all discussions resolved

**Comment by renjiezh** [comment]
Move to another PR
https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/559

**Comment by renjiezh** [comment]
Move to another PR
https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/559

**Pull request closed without merging**
