### PR TITLE
Add proto definition for simulator synthetic data specification

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037)* status: all files reviewed, 9 unresolved discussions (waiting on @jcorilla, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWnWMLs-D7xs4b0Ioxx:-NWnWMLs-D7xs4b0Ioxy:bqosrto) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L25)):*
> ```proto
> option java_multiple_files = true;
> 
> message SimulatorSyntheticDataSpec {
> ```

Please add a comment that describes this structure.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWmgwwi1H2kN638ZBWk:-NWnVbxf1RPn6xGPsCCO:bu93fzu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: maybe take a cue from Kotlin and use the same naming pattern as [ClosedRange](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/-closed-range/)
</blockquote></details>

Though I'd much prefer Interval, it seems we've been using Range for this. 

We should use half-open ranges [begin, end).
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWnWRT8BN17kYimzjm0:-NWnWRT8BN17kYimzjm1:b-xon1e1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L36)):*
> ```proto
> }
> 
> // The specification of the entire VID space.
> ```

Maybe say: "The specification of a synthetic virtual population"
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWmhUKOErlzgHrLqidV:-NWo1jJ_3JWHoN2yl7of:b-9kvuuy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why did we go with FieldDescriptorProto instead of CEL expression (or basically any string syntax for field traversal, e.g. `person.age_group)`? I don't think there was a tradeoff discussion.

With FieldDescriptorProto, you have the benefit of being really specific and typed when it comes to access and you don't need to do any parsing/evaluating the expression. The downside is that you're sticking likely repeated data into the API. You still need to do some kind of reflective traversal to find the field. There's also no way to distinguish multiple instances of a field (e.g. if you have more than one field using the same message type and you're trying to target a subfield of that message). The other benefit to using a string is that you can use a Map for the values with the string as the key (rather than correlated lists).

It's fine if we're okay with these tradeoffs, I just want to call them out. Note that I wouldn't bother using the CEL library if we were using string expressions since the parsing of an expression that just evaluates to a field value is trivial.

@kungfucraig 
</blockquote></details>

From the point of view of the Simulator, having the Field Descriptors will force the proto to be compiled in, however from the point of view of a downstream EG client it doesn't help much. And maybe it's worse because you can't readily tie a field descriptor back to it's origin (afaik).

It seems like it would be better to go with the strings and make it clear that anyone who wants to work with this structure is expected to agree out of band on the event template messages.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWo2PpJ1mUwP4nOuGfz:-NWo2PpJ1mUwP4nOuGg-:b-7rms8y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L45)):*
> ```proto
>   repeated google.protobuf.FieldDescriptorProto population_fields = 2;
> 
>   // For Device, Location, Duration ...
> ```

Same issue here as with population fields that Sanjay mentioned.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWmk-mt7-JT32qYU2d1:-NWo2Z2pBrxb2Ftzt1Wl:bu6q300) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What is this supposed to be? A `DataProvider` resource name?
</blockquote></details>

It's basically a short description string that identifies the fake media property we are measuring. Dynamically populating it with the simulator name could be reasonable.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWo2xqBD2fRIJM7jPZs:-NWo2xqBD2fRIJM7jPZt:biclu7r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L67)):*
> ```proto
>   string description = 2;
> 
>   // The VIDs reached with their frequency non-population attributes.
> ```

This doesn't make sense.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWo32mm9HkZsSS62AC_:-NWo32mm9HkZsSS62ACa:bh63fly) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L83)):*
> ```proto
>   }
> 
>   message DateSpec {
> ```

Please add a description for this.

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037)* status: all files reviewed, 9 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWnWMLs-D7xs4b0Ioxx:-NWrdlqp1pm345xfZQeh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L25)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please add a comment that describes this structure.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWmgwwi1H2kN638ZBWk:-NWrdtUV-uphaJJhifBh:b-njdbx8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L34)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Though I'd much prefer Interval, it seems we've been using Range for this. 

We should use half-open ranges [begin, end).
</blockquote></details>

Switching to using half open range.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWnWRT8BN17kYimzjm0:-NWrdA8R6aewbYD-QidD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L36)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Maybe say: "The specification of a synthetic virtual population"
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWmhDFT72hRrolbk5Dy:-NWrdczV6wbVZMzvaVlg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The summary fragment should actually describe the field. e.g. "Set of fields that come from population data."
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWmhUKOErlzgHrLqidV:-NWrmkZe7YqioJsr3hiB:bvq41ub) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L43)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

From the point of view of the Simulator, having the Field Descriptors will force the proto to be compiled in, however from the point of view of a downstream EG client it doesn't help much. And maybe it's worse because you can't readily tie a field descriptor back to it's origin (afaik).

It seems like it would be better to go with the strings and make it clear that anyone who wants to work with this structure is expected to agree out of band on the event template messages.


</blockquote></details>

Switching to using Strings instead of Field Descriptors.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWo2PpJ1mUwP4nOuGfz:-NWrdeigEuPFLEWC56xJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L45)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Same issue here as with population fields that Sanjay mentioned.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWo2xqBD2fRIJM7jPZs:-NWrmhljBELD7WlpW6er:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L67)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This doesn't make sense.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWo32mm9HkZsSS62AC_:-NWrhznB0Dfy16gffI4C:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L83)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please add a description for this.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037)* status: all files reviewed, 7 unresolved discussions (waiting on @jcorilla, @kungfucraig, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWmgwwi1H2kN638ZBWk:-NWs7QFF5DEb8GBJsM1y:b-wd7q41) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L34)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

Switching to using half open range.
</blockquote></details>

I'd still recommend using `end_exclusive` for the name of the `end` field to be explicit.

See Kotlin's [OpenEndRange](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/-open-end-range/)
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWmk-mt7-JT32qYU2d1:-NWs7wcL5waphOjfqcu3:b-ohbxz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L64)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It's basically a short description string that identifies the fake media property we are measuring. Dynamically populating it with the simulator name could be reasonable.
</blockquote></details>

I'm not sure I'm seeing a value in this given that this whole spec will go inside of an EventGroup which is a child of a DataProvider. (Each EDP simulator instance is bound to a single DataProvider).

**Review by kungfucraig — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWmk-mt7-JT32qYU2d1:-NWsjecAA9MhQhR-Wdd9:b-8kg3u7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not sure I'm seeing a value in this given that this whole spec will go inside of an EventGroup which is a child of a DataProvider. (Each EDP simulator instance is bound to a single DataProvider).
</blockquote></details>

I'm good dropping it.

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NWmk-mt7-JT32qYU2d1:-NWsy_wk9nqg3Y8JxCax:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da04efd0d63cf8e80c42bd67977ecb7704528a6c/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L64)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I'm good dropping it.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 89 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NXBOdQy5r4Ntb1U1CkG:-NXBOdQy5r4Ntb1U1CkH:b50czwo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f2e384fb4c631e35b3a62f6fd753fd9f64fe460/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L89)):*
> ```proto
>   message DateSpec {
>     // Date the VIDs were reached.
>     google.type.Date date = 1;
> ```

can we make this a date range?

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 89 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-NXBOdQy5r4Ntb1U1CkG:-NXBvWeY7S5VAqr8JAZl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f2e384fb4c631e35b3a62f6fd753fd9f64fe460/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L89)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can we make this a date range?
</blockquote></details>

Done.

**Review by jcorilla — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by jcorilla — COMMENTED** [review]
@kungfucraig Could you take another look at the change in date spec from singular date -> date range? I believe you also have a block on the VidInterval discussion.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037#-:-NXGchQCCgpq2KnaAUG9:b-qp4x75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1037)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
