### PR TITLE
Implement Internal Reporting V2 Reporting Sets Service Read Methods 

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962)* status: all files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt` line 173 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962#-NTaCc3F3Rrwes_8Y8ri:-NTaCc3F3Rrwes_8Y8rj:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f106a1856e5b84d257456aef43941863f1adaf99/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt#L173)):*
> ```Kotlin
>   }
> 
>   fun listReportingSets(
> ```

nit



_Suggestion:_
```Kotlin
read
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt` line 209 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962#-NTaD2t8DTWQHtPXqMLz:-NTaD2t8DTWQHtPXqMM-:b-yxm4tz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f106a1856e5b84d257456aef43941863f1adaf99/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt#L209)):*
> ```Kotlin
>       val reportingSetInfoMap: MutableMap<InternalId, ReportingSetInfo> = mutableMapOf()
> 
>       val translate: Translate = { row: ResultRow ->
> ```

Does `translate` need to form a closure or can it just be a separate private method?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt` line 298 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962#-NTaDMMRDFCYlk9dyzUV:-NTaDMMRDFCYlk9dyzUW:bir6f52) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f106a1856e5b84d257456aef43941863f1adaf99/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt#L298)):*
> ```Kotlin
>       readContext.executeQuery(statement).consume(translate).collect {}
> 
>       reportingSetInfoMap.forEach { (reportingSetId, reportingSetInfo) ->
> ```

If you're naming the variables anyway you should just use a regular for loop rather than the `forEach` function.

In general, you should prefer `for` loops instead of the `forEach` function aside from cases where you're chaining. See https://kotlinlang.org/docs/coding-conventions.html#loops.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt` line 303 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962#-NTaFAwZAsKB_j0Mn2-x:-NTaFAwZAsKB_j0Mn2-y:bmuqe8a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f106a1856e5b84d257456aef43941863f1adaf99/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt#L303)):*
> ```Kotlin
>             measurementConsumerId = reportingSetInfo.measurementConsumerId,
>             reportingSetId = reportingSetId,
>             reportingSet {
> ```

nit: build this as a separate variable rather than in a function parameter expression
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt` line 860 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962#-NTaFRlX0el15u8XogPX:-NTaFRlX0el15u8XogPY:b75txdg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f106a1856e5b84d257456aef43941863f1adaf99/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt#L860)):*
> ```Kotlin
>         }
>       )
>     assertThat(retrievedReportingSets).hasSize(1)
> ```

The containsExactly assertion will inherently compare the size.



_Code quote:_
```Kotlin
   assertThat(retrievedReportingSets).hasSize(1)
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt` line 209 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962#-NTaD2t8DTWQHtPXqMLz:-NTq45MABPDECpdp8Ggk:brduwpk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f106a1856e5b84d257456aef43941863f1adaf99/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt#L209)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does `translate` need to form a closure or can it just be a separate private method?
</blockquote></details>

I need the closure, but I moved things to a separate function to make this function smaller
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt` line 298 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962#-NTaDMMRDFCYlk9dyzUV:-NTpw1nA7yKtDmg1t0u-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f106a1856e5b84d257456aef43941863f1adaf99/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt#L298)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you're naming the variables anyway you should just use a regular for loop rather than the `forEach` function.

In general, you should prefer `for` loops instead of the `forEach` function aside from cases where you're chaining. See https://kotlinlang.org/docs/coding-conventions.html#loops.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt` line 860 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962#-NTaFRlX0el15u8XogPX:-NTpwevg2Nfo2ZiT_scV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f106a1856e5b84d257456aef43941863f1adaf99/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt#L860)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The containsExactly assertion will inherently compare the size.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/962)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
