### PR TITLE
Add documentation for kingdom retention policies

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla)

___
*[`docs/operations/updating-retention-policies.md` line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXBma9P-hnmbBy_SFzZ:-NXBma9P-hnmbBy_SFz_:bjt16kt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bcde7ed4c67889f99970526ecc65f21829dbff3/docs/operations/updating-retention-policies.md#L121)):*
> ```Markdown
> index - 5.
> 
> You can then apply a `JSON` patch using a command like (adding the `-o yaml`
> ```

I think it's simpler in both these cases to say to use `kubectl edit` rather than `kubectl patch`. Just indicate which lines are the relevant ones to change.

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`docs/operations/updating-retention-policies.md` line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXBma9P-hnmbBy_SFzZ:-NXCcs97BB_fGNzvGJfW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bcde7ed4c67889f99970526ecc65f21829dbff3/docs/operations/updating-retention-policies.md#L121)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think it's simpler in both these cases to say to use `kubectl edit` rather than `kubectl patch`. Just indicate which lines are the relevant ones to change.
</blockquote></details>

Done.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla)

___
*[`docs/operations/updating-retention-policies.md` line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXH2WifB_m-J9CK5eyF:-NXH2WifB_m-J9CK5eyG:b1jakc3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49ebc8ffbc387e4bfc34e32b5f67566919a86c32/docs/operations/updating-retention-policies.md#L80)):*
> ```Markdown
> 
> You can then edit and save desired changes using your default text editor.
> ```

You dropped the parts where you explain what the relevant lines to change are. You still need those.

1. Explain that the schedule (when the job runs) is configured in the `schedule` field of the spec (you can link to the relevant K8s API doc: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/cron-job-v1/#CronJobSpec)
2. Explain the relevant options to change in the container args.

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`docs/operations/updating-retention-policies.md` line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXH2WifB_m-J9CK5eyF:-NXHypwJDR9ozYtPKY1i:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49ebc8ffbc387e4bfc34e32b5f67566919a86c32/docs/operations/updating-retention-policies.md#L80)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You dropped the parts where you explain what the relevant lines to change are. You still need those.

1. Explain that the schedule (when the job runs) is configured in the `schedule` field of the spec (you can link to the relevant K8s API doc: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/cron-job-v1/#CronJobSpec)
2. Explain the relevant options to change in the container args.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jcorilla and @Marco-Premier)

___
*[`docs/operations/updating-retention-policies.md` line 75 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXI-tKs8v8iY4TMf0j3:-NXI1yNn7mXOO_VuGoa1:b-kghi04) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a007d90da79d2e8f7b0652490406b9cf55c8fb4f/docs/operations/updating-retention-policies.md#L75)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use `.` as the traversal operator rather than `/`.
</blockquote></details>

To clarify, K8s API objects are represented using JSON (though commonly edited in YAML which is then converted to JSON).

Instead of `spec/jobTemplate/spec/template/spec/containers/0/args` the path syntax would be `spec.jobTemplate.spec.template.spec.containers[0].args`

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`docs/operations/updating-retention-policies.md` line 75 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXI-tKs8v8iY4TMf0j3:-NXLiQky-SSUiWvnc1x5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a007d90da79d2e8f7b0652490406b9cf55c8fb4f/docs/operations/updating-retention-policies.md#L75)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify, K8s API objects are represented using JSON (though commonly edited in YAML which is then converted to JSON).

Instead of `spec/jobTemplate/spec/template/spec/containers/0/args` the path syntax would be `spec.jobTemplate.spec.template.spec.containers[0].args`
</blockquote></details>

Done.
___
*[`docs/operations/updating-retention-policies.md` line 81 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXI01nz0yAlSc5-uGMv:-NXLpYbf7HHp0qOeyJzC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a007d90da79d2e8f7b0652490406b9cf55c8fb4f/docs/operations/updating-retention-policies.md#L81)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't reference the specific arg index as it may change. Just indicate that the options are passed as container args and mention which options they may be interested in adjusting.
</blockquote></details>

Done.
___
*[`docs/operations/updating-retention-policies.md` line 89 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXI0RVh1z-ClPaNq3B2:-NXLmsUgBSZNA90gU9m6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a007d90da79d2e8f7b0652490406b9cf55c8fb4f/docs/operations/updating-retention-policies.md#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's a human-readable duration, not ISO-8601.

Modified from the code comment:

> Human-readable format consisting of a sequence elements each consisting of a decimal number followed by a unit suffix.
>
> The valid suffixes are:
> * `d` - days
> * `h` - hours
> * `m` - minutes
> * `s` - seconds
> * `ms` - milliseconds
> * `ns` - nanoseconds
>
> For example, `3h50m` means 3 hours and 51 minutes.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jcorilla and @Marco-Premier)

___
*[`docs/operations/updating-retention-policies.md` line 75 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXI-tKs8v8iY4TMf0j3:-NXLxUOC6Pz0FWPK8q8M:bors6qq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a007d90da79d2e8f7b0652490406b9cf55c8fb4f/docs/operations/updating-retention-policies.md#L75)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you forget to push? I'm not seeing changes here.

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`docs/operations/updating-retention-policies.md` line 75 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXI-tKs8v8iY4TMf0j3:-NXM1KKi7CeC5MoeupSS:b-kjbxvv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a007d90da79d2e8f7b0652490406b9cf55c8fb4f/docs/operations/updating-retention-policies.md#L75)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Did you forget to push? I'm not seeing changes here.
</blockquote></details>

Re-pushing changes, should be visible in r4
___
*[`docs/operations/updating-retention-policies.md` line 89 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXI0RVh1z-ClPaNq3B2:-NXM0u4o2OZNqq3aYEWx:bj2kf4t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a007d90da79d2e8f7b0652490406b9cf55c8fb4f/docs/operations/updating-retention-policies.md#L89)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is there link I can include which describes the format? I couldn't find one available

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla and @Marco-Premier)

___
*[`docs/operations/updating-retention-policies.md` line 89 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXI0RVh1z-ClPaNq3B2:-NXMB8M31h3E7xUwUb_q:b-1id8bu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a007d90da79d2e8f7b0652490406b9cf55c8fb4f/docs/operations/updating-retention-policies.md#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I copied this from a [code comment](https://github.com/world-federation-of-advertisers/common-jvm/blob/a6f3a96f7badd007b15feb4db3154ae23e7ec203/src/main/kotlin/org/wfanet/measurement/common/Durations.kt#L22) and fixed up the parts that were out-of-date (doesn't mention the days suffix). You should add it somewhere and link to it (maybe just a "Duration format" section under an "Appendix" section in this doc).

Here it is in Markdown for your convenience:

```markdown
 Human-readable format consisting of a sequence elements each consisting of a decimal number followed by a unit suffix.

 The valid suffixes are:
 * `d` - days
 * `h` - hours
 * `m` - minutes
 * `s` - seconds
 * `ms` - milliseconds
 * `ns` - nanoseconds

 For example, `3h50m` means 3 hours and 51 minutes.
```
</blockquote></details>

Of course I goofed in my example and put 3h50 but said it translates to "3 hours and *51* minutes" :P . Please fix that in your version.

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`docs/operations/updating-retention-policies.md` line 89 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXI0RVh1z-ClPaNq3B2:-NXMNwsbDUHp4nn1qr87:b-znwwi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a007d90da79d2e8f7b0652490406b9cf55c8fb4f/docs/operations/updating-retention-policies.md#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Of course I goofed in my example and put 3h50 but said it translates to "3 hours and *51* minutes" :P . Please fix that in your version.
</blockquote></details>

Done. Thanks for the markdown!

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla and @Marco-Premier)

___
*[`docs/operations/updating-retention-policies.md` line 102 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050#-NXMhOeeBgnOI2J81-Ps:-NXMhOeeBgnOI2J81-Pt:b-1axd3w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f4fde2dc003bb8fe393a74f7f663fa10ebaaa28/docs/operations/updating-retention-policies.md#L102)):*
> ```Markdown
> 
> ## Appendix
> #### Human-Readable Duration
> ```

nit: only one level of header lower than the parent section



_Suggestion:_
```Markdown
### Human-Readable Duration
```

**Review by jcorilla — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1050)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
