### PR TITLE
feat: Implement measurement prober metric creation and publication

### PR DESCRIPTION
**Pull request by roaminggypsy**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842)* status: all files reviewed, 6 unresolved discussions (waiting on @roaminggypsy)

___
*[`MODULE.bazel` line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8i_ofH9d9UGHW6DN0G:-O8i_ofH9d9UGHW6DN0H:b-qq2rkl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/MODULE.bazel#L50)):*
> ```Starlark
> bazel_dep(
>     name = "cross-media-measurement-api",
>     version = "0.69.0",
> ```

This should be done in a separate PR that also updates the service implementation for the API changes.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8icMkJCouolFTkMuED:-O8icMkJCouolFTkMuEE:bx42tkz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L92)):*
> ```Kotlin
>   private val lastTerminalMeasurementTimeGauge: LongGauge =
>     Instrumentation.meter
>       .gaugeBuilder("${Instrumentation.ROOT_NAMESPACE}.prober.last_terminal_measurement_time")
> ```

The "time" suffix is for durations. See https://opentelemetry.io/docs/specs/semconv/general/metrics/#instrument-units

Maybe timestamp?



_Suggestion:_
```Kotlin
.timestamp
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8iaXXTE5YVlxNod0z4:-O8iaXXTE5YVlxNod0z5:bpetufa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L93)):*
> ```Kotlin
>     Instrumentation.meter
>       .gaugeBuilder("${Instrumentation.ROOT_NAMESPACE}.prober.last_terminal_measurement_time")
>       .setUnit("{millisecond}")
> ```

1. The unit is the UCUM "c/s" string. Units are also non-prefixed, e.g. durations are in seconds rather than milliseconds. See https://opentelemetry.io/docs/specs/semconv/general/metrics/#instrument-units You may want to use a DoubleGauge so you can record fractional seconds (divide the millis by `1000.0`)
2. This is not actually a duration but a timestamp, so I'm not sure what unit to use. e.g. maybe a non-standard unit string like "s since epoch"?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 248 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8icgFtBNMrR5qrbpWI:-O8icgFtBNMrR5qrbpWJ:be2u2o8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L248)):*
> ```Kotlin
>     }
> 
>     val requisitions = getRequisitionsForMeasurement(lastUpdatedMeasurement.name)
> ```

This shouldn't be done from shouldCreateMeasurement, as that function should be free of side effects. You probably want to move the `getLastUpdatedMeasurement()` call outside of shouldCreateMeasurement and have the last updated measurement passed in as a param.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 252 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8id5suEkD06yTcZXlV:-O8id5suEkD06yTcZXlW:b6x9y82) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L252)):*
> ```Kotlin
>       if (requisition.state == Requisition.State.FULFILLED) {
>         val dataProviderName: String =
>           CanonicalRequisitionKey.fromName(requisition.name)?.dataProviderId ?: ""
> ```

If this returns null, it indicates an error. Treat it as such.



_Code quote:_
```Kotlin
CanonicalRequisitionKey.fromName(requisition.name)
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 253 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8idTfw4jRviwfLF8eX:-O8idTfx-YyoSeIVZdFu:b-shhcnk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L253)):*
> ```Kotlin
>         val dataProviderName: String =
>           CanonicalRequisitionKey.fromName(requisition.name)?.dataProviderId ?: ""
>         val attributes = Attributes.of(AttributeKey.stringKey("data_provider"), dataProviderName)
> ```

Attribute names must be namespaced. See https://opentelemetry.io/docs/specs/semconv/general/attribute-naming/



_Code quote:_
```Kotlin
"data_provider"
```

**Review by roaminggypsy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`MODULE.bazel` line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8i_ofH9d9UGHW6DN0G:-O8s53Cq5KWYLfZnN8VX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/MODULE.bazel#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be done in a separate PR that also updates the service implementation for the API changes.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8icMkJCouolFTkMuED:-O8nTf6NCmFcA4Uq9Rvn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L92)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The "time" suffix is for durations. See https://opentelemetry.io/docs/specs/semconv/general/metrics/#instrument-units

Maybe timestamp?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8iaXXTE5YVlxNod0z4:-O8rf6kh2XV0FJrj670j:bxiwhg5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. The unit is the UCUM "c/s" string. Units are also non-prefixed, e.g. durations are in seconds rather than milliseconds. See https://opentelemetry.io/docs/specs/semconv/general/metrics/#instrument-units You may want to use a DoubleGauge so you can record fractional seconds (divide the millis by `1000.0`)
2. This is not actually a duration but a timestamp, so I'm not sure what unit to use. e.g. maybe a non-standard unit string like "s since epoch"?
</blockquote></details>

For the unit, I use 's', but I added more details in the description. 

Some analysis and visualization tools rely on standard units. Using a non-standard unit like `s since epoch` might cause issues with how these tools interpret and display data.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 248 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8icgFtBNMrR5qrbpWI:-O8rEOLO55N6PYxixLex:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L248)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This shouldn't be done from shouldCreateMeasurement, as that function should be free of side effects. You probably want to move the `getLastUpdatedMeasurement()` call outside of shouldCreateMeasurement and have the last updated measurement passed in as a param.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 252 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8id5suEkD06yTcZXlV:-O8rFeca14Lz5QDLrnpS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L252)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If this returns null, it indicates an error. Treat it as such.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 253 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8idTfw4jRviwfLF8eX:-O8s58uz1I8N-gqfoAb5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L253)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Attribute names must be namespaced. See https://opentelemetry.io/docs/specs/semconv/general/attribute-naming/
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @roaminggypsy)

___
*[`MODULE.bazel` line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8i_ofH9d9UGHW6DN0G:-O8s6xubBmlABlgeutIv:b3vv8qm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/MODULE.bazel#L50)):*
<details><summary><i>Previously, roaminggypsy (Lin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see the change in this PR. Did you follow the process for stacked PRs? Specifically basing this PR branch on the other one and setting the PR base in GitHub?

**Review by roaminggypsy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`MODULE.bazel` line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8i_ofH9d9UGHW6DN0G:-O8s8kSE9M1qLRhPTyFU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e00b8c7ea776cb7eba51f2987f53a800a3b46949/MODULE.bazel#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I still see the change in this PR. Did you follow the process for stacked PRs? Specifically basing this PR branch on the other one and setting the PR base in GitHub?
</blockquote></details>

Done.

**Review by roaminggypsy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 92 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8skMGQ9TdkGSTewir9:-O8slWP95cWaJ_1rZL5T:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2e5bfa570f8fe91615cee62937a9e117b0763764/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L92)):*
> ```Kotlin
>   private val lastTerminalMeasurementTimeGauge: DoubleGauge =
>     Instrumentation.meter
>       .gaugeBuilder("${PROBER_NAMESPACE}.last_terminal_measurement_timestamp")
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 100 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8skmQd5VtRipKBymna:-O8slWxM4Lg7mFH0mWVN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2e5bfa570f8fe91615cee62937a9e117b0763764/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L100)):*
> ```Kotlin
>   private val lastTerminalRequisitionTimeGauge: DoubleGauge =
>     Instrumentation.meter
>       .gaugeBuilder("${PROBER_NAMESPACE}.last_terminal_requisition_timestamp")
> ```

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842)* status: all files reviewed, 2 unresolved discussions (waiting on @roaminggypsy)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 362 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8sxpRk1SsgQdM0h8iI:-O8sxpRk1SsgQdM0h8iJ:b-405vxq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b812045575be4991de1b8d02f6eca4501bfce6c/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L362)):*
> ```Kotlin
> 
>   private suspend fun updateLastTerminalRequisitionGauge(lastUpdatedMeasurement: Measurement?) {
>     if (lastUpdatedMeasurement == null) {
> ```

nit: do this check outside of the function call and take in a non-null parameter
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 391 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8sxz5kDOKiPzFV_oHv:-O8sxz5l1qJ3jZyeCXPo:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b812045575be4991de1b8d02f6eca4501bfce6c/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L391)):*
> ```Kotlin
> 
>     private const val PROBER_NAMESPACE = "${Instrumentation.ROOT_NAMESPACE}.prober"
>     private val PROBER_DATA_PROVIDER_ATTRIBUTE_KEY =
> ```

nit



_Suggestion:_
```Kotlin
DATA_PROVIDER_ATTRIBUTE_KEY
```

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842)* status: all files reviewed, 2 unresolved discussions (waiting on @roaminggypsy and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 362 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842#-O8sxpRk1SsgQdM0h8iI:-O8wvs2qCQlm1riUINJE:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b812045575be4991de1b8d02f6eca4501bfce6c/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L362)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: do this check outside of the function call and take in a non-null parameter
</blockquote></details>

+1

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1842)* status: all files reviewed, 1 unresolved discussion (waiting on @roaminggypsy)

**Pull request merged**
