### PR TITLE
Implement Internal Metrics Service Read Methods for Reporting V2

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009)

**Review by riemanli — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt` line 1743 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009#-NVqXQRc5vx6t674izDG:-NVqXQRc5vx6t674izDH:b-uap1h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a33cfbf085724ab24ef7f7a5e0c5abb0e95a6ecf/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt#L1743)):*
> ```Kotlin
>                   width = 0.5f
>                 }
>             }
> ```

Isn't this the same as what `createCreateMetricRequest` provides?



_Code quote:_
```Kotlin
            metricSpec = metricSpec {
              reach =
                MetricSpecKt.reachParams {
                  privacyParams =
                    MetricSpecKt.differentialPrivacyParams {
                      epsilon = 1.0
                      delta = 2.0
                    }
                }
              vidSamplingInterval =
                MetricSpecKt.vidSamplingInterval {
                  start = 0.1f
                  width = 0.5f
                }
            }
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt` line 1743 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009#-NVqXQRc5vx6t674izDG:-NW4-jQi9h15sB_7ggqa:bdv0suf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/162f643bcbc78f29fed3c7c0a7b4541baad82f2b/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt#L1743)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Isn't this the same as what `createCreateMetricRequest` provides?
</blockquote></details>

I am trying to be more explicit by putting exactly what I am trying to test in the unit test. The default may be the same, but that isn't known from just looking at the unit test.

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt` line 133 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009#-NW9Q6b1Db0mYCrV933t:-NW9Q6b1Db0mYCrV933u:b-m3al6x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c288ac896bde7b65b29fbf757175878fab0e066/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt#L133)):*
> ```Kotlin
>           .toList()
>       } catch (e: IllegalStateException) {
>         failGrpc(Status.DATA_LOSS) { "Metric is missing required fields" }
> ```

what was the thinking behind using this status code?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt` line 160 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009#-NW9Q9pl6iMfSnnscynO:-NW9Q9pl6iMfSnnscynP:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c288ac896bde7b65b29fbf757175878fab0e066/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt#L160)):*
> ```Kotlin
>         )
>       } catch (e: IllegalStateException) {
>         failGrpc(Status.DATA_LOSS) { "Metric is missing required fields" }
> ```

ditto
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetric.kt` line 329 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009#-NW9QjJA3SXJ2UIBrEWk:-NW9QjJA3SXJ2UIBrEWl:bx2ut8w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c288ac896bde7b65b29fbf757175878fab0e066/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetric.kt#L329)):*
> ```Kotlin
>       }
> 
>     if (existingMetricsMap.size < requests.size) {
> ```

why is this if needed?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt` line 133 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009#-NW9Q6b1Db0mYCrV933t:-NW9euiRDD2YhrfctWDu:bkrfzta) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c288ac896bde7b65b29fbf757175878fab0e066/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt#L133)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what was the thinking behind using this status code?
</blockquote></details>

If some fields that shouldn't be null are somehow null when reading, I want to return early with an exception and this was the only status code I could see matching the issue.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt` line 160 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009#-NW9Q9pl6iMfSnnscynO:-NW9eMmP2g4hYNnFKkP1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c288ac896bde7b65b29fbf757175878fab0e066/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt#L160)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetric.kt` line 329 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009#-NW9QjJA3SXJ2UIBrEWk:-NW9fLmn9yrN2KHhkf1n:b30a0yv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c288ac896bde7b65b29fbf757175878fab0e066/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetric.kt#L329)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why is this if needed?
</blockquote></details>

If all the metrics have already been created, then the statements would have 0 bindings. Executing those statements would then throw an exception.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt` line 133 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009#-NW9Q6b1Db0mYCrV933t:-NWAFXNF17_kwzU2Y6Nx:bp63ypf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c288ac896bde7b65b29fbf757175878fab0e066/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt#L133)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

If some fields that shouldn't be null are somehow null when reading, I want to return early with an exception and this was the only status code I could see matching the issue.
</blockquote></details>

What about NOT_FOUND?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetric.kt` line 329 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009#-NW9QjJA3SXJ2UIBrEWk:-NWAFP8G3t_rZ1xUL_sF:bgw7vra) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c288ac896bde7b65b29fbf757175878fab0e066/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetric.kt#L329)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

If all the metrics have already been created, then the statements would have 0 bindings. Executing those statements would then throw an exception.
</blockquote></details>

should this throw an error then for the `else`?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt` line 133 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009#-NW9Q6b1Db0mYCrV933t:-NWCxRpR3Q5nOmF3n-AA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4019b85cb0330128f6dc9e3e2c0d343549805beb/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt#L133)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

What about NOT_FOUND?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetric.kt` line 329 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1009#-NW9QjJA3SXJ2UIBrEWk:-NWCxWcSBBT56LheSWvX:bg1or6n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4019b85cb0330128f6dc9e3e2c0d343549805beb/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetric.kt#L329)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should this throw an error then for the `else`?
</blockquote></details>

No, I still need to return the metrics if they were all already created.

**Pull request merged**
