### PR TITLE
Bump common-jvm to use built-in gPRC health probe

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655)

### CODE REVIEW

**Comment by renjiezh** [comment]
Tested in GCP by deploying a Kingdom

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @renjiezh)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655#-N8k2TRh92SGXSFWw_I1:-N8k2TRi19-SO5iqsKPJ:b1b8m5o) (no related file):*
Drop the now-unused `grpc_health_probe` workspace target.

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655#-N8k2ZPv624GyhqQy1ZL:-N8k2ZPv624GyhqQy1ZM:b-d4bgyt) (no related file):*
Add a section to docs/gke/cluster-config.md regarding our use of the `GRPCContainerProbe` feature, which on GKE requires Kubernetes v1.24+

___
___
*[`build/repositories.bzl` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655#-N8k16JT9dpclzTix_SF:-N8k16JT9dpclzTix_SG:b32ii9t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f44fd26a696722c8b1760c24bf4e670e4595af/build/repositories.bzl#L27)):*
> ```Starlark
>         name = "wfa_common_jvm",
>         repo = "common-jvm",
>         sha256 = "32ed3ef6accda84e9c549746d38cac1b83997117815588b05314b9bb2c4b19d5",
> ```

Add DO_NOT_SUBMIT comment referencing the PR, which should be resolved to use a version before submitting.
___
*[`src/main/k8s/base.cue` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655#-N8k1QMuAxcj7r1HAdZM:-N8k1QMuAxcj7r1HAdZN:b-efkl7i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f44fd26a696722c8b1760c24bf4e670e4595af/src/main/k8s/base.cue#L33)):*
> ```CUE
> #GrpcServicePort: 8443
> 
> #ProbePort: 8442
> ```

nit: use 8080

For background, gRPC uses HTTP/2 which uses the same ports as HTTP/1, namely 80 for unencrypted and 443 for encrypted. Since ports below 1024 are only bindable by root, the ports get pushed into the non-root space by adding 8000 to them. Hence 8443 for the TLS gRPC port and 8080 for the non-TLS one.



_Code quote:_
```CUE
8442
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655)* status: 7 of 15 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655#-N8k2TRh92SGXSFWw_I1:-N93tVbm5YSqbdVeh7jL:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop the now-unused `grpc_health_probe` workspace target.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655#-N8k2ZPv624GyhqQy1ZL:-N93tXm34GGpySuVC-Bz:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add a section to docs/gke/cluster-config.md regarding our use of the `GRPCContainerProbe` feature, which on GKE requires Kubernetes v1.24+
</blockquote></details>

Done.

___
___
*[`build/repositories.bzl` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655#-N8k16JT9dpclzTix_SF:-N93t_3J4qUFHTMxFicx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f44fd26a696722c8b1760c24bf4e670e4595af/build/repositories.bzl#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add DO_NOT_SUBMIT comment referencing the PR, which should be resolved to use a version before submitting.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`docs/gke/duchy-deployment.md` line 162 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655#-N93yuo15TJg6-7u0e3N:-N93yuo15TJg6-7u0e3O:b-1peqw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2dc75bd2932d3cd8fc1a620ecb41dd7eee3f4fc7/docs/gke/duchy-deployment.md#L162)):*
> ```Markdown
> 
> The GKE version should be no older than `1.24.0` in order to support built-in gRPC
> health prob.
> ```

nit: probe.



_Code quote:_
```Markdown
prob.
```

**Review by kungfucraig — APPROVED** [review]
> Reviewed 7 of 12 files at r1, 6 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/655)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @stevenwarejones)

**Pull request merged**
