### PR TITLE
Add missing ignoringRepeatedFieldOrder in ReportsServiceTest V1Alpha

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1622)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1622)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 2116 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1622#-NxydkOj2uoQFEFOGM3y:-NxydkOk4-gTJ93ySCjI:b-ynlihb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44a478a67340175b844b2da607bd8202aa8ae302/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L2116)):*
> ```Kotlin
>         InternalReportingSetsCoroutineImplBase::batchGetReportingSet,
>       )
>       .ignoringRepeatedFieldOrder()
> ```

Just a quick double check: *all* of the repeated fields in this message type are unordered?

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1622)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1622)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
