### PR TITLE
Add the gcloud InProcessLifeOfAMeasurementIntegrationTest.

### PR DESCRIPTION
**Pull request by wangyaopw**
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F609964597029&view=2c2927c0-626b-4740-8620-af2a93b7d623

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/gcloud/DuchyDependencyProviderRule.kt, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-MkPKwY9AfiH2RAJX1BA:-MkPKwYA6WhTS_GD4Ov5:bfw7sf3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b3291338c4de10b6da93b8dd38d21832f5f3186/src/test/kotlin/org/wfanet/measurement/integration/gcloud/DuchyDependencyProviderRule.kt#L53)):*
> ```Kotlin
>   override val value: (String) -> InProcessDuchy.DuchyDependencies = this::buildDuchyDependencies
> 
>   private val computationsDatabaseRules =
> ```

nit: specify type explicitly so it's clear this is a Map
___
*[src/test/kotlin/org/wfanet/measurement/integration/gcloud/KingdomDataServicesProviderRule.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-MkPNWLwAEOAdmHXrIW0:-MkPNWLwAEOAdmHXrIW1:b-uumf6g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b3291338c4de10b6da93b8dd38d21832f5f3186/src/test/kotlin/org/wfanet/measurement/integration/gcloud/KingdomDataServicesProviderRule.kt#L38)):*
> ```
> lazy { dataServices }
> ```
dataServices is already itself lazy, so this should instead be 
```

  get() = dataServices
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/integration/gcloud/DuchyDependencyProviderRule.kt, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-MkPKwY9AfiH2RAJX1BA:-MkPwvmlDLH5D3mOG2Ba:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b3291338c4de10b6da93b8dd38d21832f5f3186/src/test/kotlin/org/wfanet/measurement/integration/gcloud/DuchyDependencyProviderRule.kt#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: specify type explicitly so it's clear this is a Map
</blockquote></details>

Done
___
*[src/test/kotlin/org/wfanet/measurement/integration/gcloud/KingdomDataServicesProviderRule.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-MkPNWLwAEOAdmHXrIW0:-MkPxIZV2GG35X9SHtFD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b3291338c4de10b6da93b8dd38d21832f5f3186/src/test/kotlin/org/wfanet/measurement/integration/gcloud/KingdomDataServicesProviderRule.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> lazy { dataServices }
> ```
dataServices is already itself lazy, so this should instead be 
```

  get() = dataServices
```
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/gcloud/GcpInProcessLifeOfAMeasurementIntegrationTest.kt, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-MknnAS6DBo5oGDXRb9K:-MknnAS6DBo5oGDXRb9L:b-16hpqx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b7d7fae0b255e8280d11b5bc20dad873559087bc/src/test/kotlin/org/wfanet/measurement/integration/gcloud/GcpInProcessLifeOfAMeasurementIntegrationTest.kt#L26)):*
> ```
> GCP backends (Spanner, GCS).
> ```
nit: GCP branding is obsolete aside from the console. The umbrella is Google Cloud, with products such as Cloud Spanner and Cloud Storage. We sometimes put Google in front of these product names to avoid confusing with similarly-named non-Google offerings (e.g. Google Cloud Storage), or leave out Cloud when the shorter name is unambiguous (e.g. Spanner).

Use `GCloud` if you need a camel-cased identifier.

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/gcloud/GcpInProcessLifeOfAMeasurementIntegrationTest.kt, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-MknnAS6DBo5oGDXRb9K:-Mknwp1Z23LiGucK4d14:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b7d7fae0b255e8280d11b5bc20dad873559087bc/src/test/kotlin/org/wfanet/measurement/integration/gcloud/GcpInProcessLifeOfAMeasurementIntegrationTest.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> GCP backends (Spanner, GCS).
> ```
nit: GCP branding is obsolete aside from the console. The umbrella is Google Cloud, with products such as Cloud Spanner and Cloud Storage. We sometimes put Google in front of these product names to avoid confusing with similarly-named non-Google offerings (e.g. Google Cloud Storage), or leave out Cloud when the shorter name is unambiguous (e.g. Spanner).

Use `GCloud` if you need a camel-cased identifier.
</blockquote></details>

done

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 47 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-MkxpW_L8t_nXFi7kADb:-MkxpW_L8t_nXFi7kADc:bbz5ecw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89dd93d6ac8eb0311ad2c7b832c64e9a013b4183/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L47)):*
> ```
> EmptyCoroutineContext
> ```
I made a mistake in my previous code sample. This should be `Dispatchers.Default`.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-Mkxq4QS1XESBGLnqBB0:-Mkxq4QS1XESBGLnqBB1:bbz5ecw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89dd93d6ac8eb0311ad2c7b832c64e9a013b4183/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L83)):*
> ```
> EmptyCoroutineContext
> ```
I made a mistake in my previous code sample. This should be `Dispatchers.Default`.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-Mkxq76B7b_wJh4_cJfE:-Mkxq76B7b_wJh4_cJfF:b-1wm7xx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89dd93d6ac8eb0311ad2c7b832c64e9a013b4183/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
> ```Kotlin
>   }
> 
>   lateinit var edpJob: Job
> ```

Should this be private? (And then expose a helper function to cancel?)

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 2 files at r8, 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-Mkxq4QS1XESBGLnqBB0:-Mky37E67yPS8OeQz55z:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89dd93d6ac8eb0311ad2c7b832c64e9a013b4183/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> EmptyCoroutineContext
> ```
I made a mistake in my previous code sample. This should be `Dispatchers.Default`.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 47 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-MkxpW_L8t_nXFi7kADb:-Mky38WCDbuzOegayZCT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89dd93d6ac8eb0311ad2c7b832c64e9a013b4183/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> EmptyCoroutineContext
> ```
I made a mistake in my previous code sample. This should be `Dispatchers.Default`.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-Mkxq76B7b_wJh4_cJfE:-Mky3AKv9gJ9Km0M28YV:b-575psq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89dd93d6ac8eb0311ad2c7b832c64e9a013b4183/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should this be private? (And then expose a helper function to cancel?)
</blockquote></details>

deleted this Job object, since it doesn't solve the issue.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r8, 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 93 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-MkyGLnnESdtsp9rYUWl:-MkyGLnoBIlQ6HWRZQKx:b-ql08ss) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c10d92b525b10733ef0ac2ccec5cfbd82e9d1549/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L93)):*
> ```Kotlin
> 
>   override fun close() {
>     // TODO(@wangyaopw): maybe cancel the backgroundScope here.
> ```

Update TODO to reference bug for fixing throttler/logAndSuppressExceptionSuspend handling of coroutine cancellation. This should cancel any jobs once that's fixed.

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 2 files at r8, 1 of 2 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 93 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-MkyGLnnESdtsp9rYUWl:-MkyMZAQ70IV4gLkYDt_:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c10d92b525b10733ef0ac2ccec5cfbd82e9d1549/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Update TODO to reference bug for fixing throttler/logAndSuppressExceptionSuspend handling of coroutine cancellation. This should cancel any jobs once that's fixed.
</blockquote></details>

done

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[build/repositories.bzl, line 28 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-MkyZVz3DdRNM0IjDDUa:-MkyZVz44MRPhkcB1QTb:bfdxfjs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca0907eef9103a6c13d023533ccd2c2233486349/build/repositories.bzl#L28)):*
> ```
> 88ca9580c6beab1d3bde581ba23fbff16628304c
> ```
Assuming you'll fix this when that common-jvm change has been submitted?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[build/repositories.bzl, line 28 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293#-MkyZVz3DdRNM0IjDDUa:-Mky_g7BCV9oe5Xl6ql2:bb74ce2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca0907eef9103a6c13d023533ccd2c2233486349/build/repositories.bzl#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> 88ca9580c6beab1d3bde581ba23fbff16628304c
> ```
Assuming you'll fix this when that common-jvm change has been submitted?
</blockquote></details>

Sure

**Pull request merged**
