### PR TITLE
Add getUserVirtualIdUniverse() to EventQuery

### PR DESCRIPTION
**Pull request by renjiezh**
HMSS sketch generation requires the vid universe which should come from the vid model. However, our EdpSimulator needs another way to get the vid universe and make sure all simulators yield the same result. 
For synthetic data EventQuery, the vid universe is specified by the population spec so all the simulators are using the same.
For InProcessEventQuery and BigQueryEventQuery, I hard-coded a range as the universe.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv3e6Q4D44ACh5TYHcm:-Nv3e6Q4D44ACh5TYHcn:bgmm8ij) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1db58eac978030af95dc9b8905e72029949d386/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt#L40)):*
> ```Kotlin
> import org.wfanet.measurement.gcloud.common.toInstant
> 
> private const val VID_VALUE_UPPER_BOUND = 100000000 // 100 million
> ```

Is it possible to have a function that sets the upper bound so that we can pass a small value for the unit tests?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv3e6Q4D44ACh5TYHcm:-Nv3fD4V4EFpYXT1ONd2:b-oft5gc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1db58eac978030af95dc9b8905e72029949d386/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt#L40)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Is it possible to have a function that sets the upper bound so that we can pass a small value for the unit tests?
</blockquote></details>

I will add this as a parameter in the constructor. Of course with a default value.

**Review by ple13 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @SanjayVas)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt` line 176 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv3oQ9832hvbVw3DDzn:-Nv3oQ9832hvbVw3DDzo:b-qhv32v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1db58eac978030af95dc9b8905e72029949d386/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt#L176)):*
> ```Kotlin
> 
>   override fun getUserVirtualIdUniverse(): Sequence<Long> {
>     return (0L until VID_VALUE_UPPER_BOUND).asSequence()
> ```

I think for the BQ one, we'll want it to come from a flag. There's nothing we can do here that makes sense. The value has to come form the impression table. We should also indicate that we expect VIDs in the BQ impression table to all be contained in a range from 1 to N.

Also, VIDs are positive integers.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/InMemoryEventQuery.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv3oklD7q_eC9Z_jQbo:-Nv3oklD7q_eC9Z_jQbp:b-l2e3yd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1db58eac978030af95dc9b8905e72029949d386/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/InMemoryEventQuery.kt#L24)):*
> ```Kotlin
> typealias LabeledTestEvent = LabeledEvent<TestEvent>
> 
> private const val VID_VALUE_UPPER_BOUND = 10000000 // 10 million
> ```

@SanjayVas Can this class deprecated?

Otherwise the caveat that applies to the BQ one applies here too. The value for the max VID needs to be aligned with the source of impressions.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEventQuery.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv3ow3P-rVfByAwbwVw:-Nv3ow3P-rVfByAwbwVx:bq791a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1db58eac978030af95dc9b8905e72029949d386/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEventQuery.kt#L67)):*
> ```Kotlin
>   }
> 
>   override fun getUserVirtualIdUniverse(): Sequence<Long> {
> ```

Can you leave a TODO for me to revisit this as part of introducing the EDP support libs?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt` line 176 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv3oQ9832hvbVw3DDzn:-Nv4JuWDBxYY20QQfcin:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1db58eac978030af95dc9b8905e72029949d386/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt#L176)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think for the BQ one, we'll want it to come from a flag. There's nothing we can do here that makes sense. The value has to come form the impression table. We should also indicate that we expect VIDs in the BQ impression table to all be contained in a range from 1 to N.

Also, VIDs are positive integers.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEventQuery.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv3ow3P-rVfByAwbwVw:-Nv4JtZcEfVIzD8U1XSc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1db58eac978030af95dc9b8905e72029949d386/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEventQuery.kt#L67)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you leave a TODO for me to revisit this as part of introducing the EDP support libs?
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: all files reviewed, 7 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEdpSimulatorRunner.kt` line 66 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv7sopNC9zK4Y9N78iN:-Nv7sopNC9zK4Y9N78iO:b9jfl4y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6e862ae1a7db2704e6ae249e88692a60eb3e7a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEdpSimulatorRunner.kt#L66)):*
> ```Kotlin
> 
>   @set:CommandLine.Option(
>     names = ["--big-query-vid-upper-bound"],
> ```

Don't prefix this with `big-query`, as it's not relating to the BQ dataset. (The flags above are all for identifying the dataset).



_Code quote:_
```Kotlin
--big-query-
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEdpSimulatorRunner.kt` line 67 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv7sI1n6JLeWBN9067E:-Nv7sI1n6JLeWBN9067F:ba32ba3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6e862ae1a7db2704e6ae249e88692a60eb3e7a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEdpSimulatorRunner.kt#L67)):*
> ```Kotlin
>   @set:CommandLine.Option(
>     names = ["--big-query-vid-upper-bound"],
>     description = ["Upper bound (exclusive) of vid values."],
> ```

nit: uppercase acronym



_Suggestion:_
```Kotlin
VID
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt` line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv7sOrL5VQoSCNUyb49:-Nv7sOrL5VQoSCNUyb4A:bfwwbpb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6e862ae1a7db2704e6ae249e88692a60eb3e7a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt#L40)):*
> ```Kotlin
> import org.wfanet.measurement.gcloud.common.toInstant
> 
> private const val DEFAULT_VID_VALUE_UPPER_BOUND = 100000000L // 100 million
> ```

tip: You can use underscores to separate numerical constants for readability



_Suggestion:_
```Kotlin
100_000_000L // 100 million
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt` line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv7tH1d3LvfAR19QwPs:-Nv7tH1e-2G6Yxz2qeSh:b-lr9t3w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6e862ae1a7db2704e6ae249e88692a60eb3e7a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt#L47)):*
> ```Kotlin
>   private val datasetName: String,
>   private val tableName: String,
>   private val vidValueUpperBound: Long = DEFAULT_VID_VALUE_UPPER_BOUND,
> ```

If this were inclusive, we could use "maxVidValue" and be less verbose.



_Code quote:_
```Kotlin
vidValueUpperBound
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEventQuery.kt` line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv7tfXf-kPSph7eEGsb:-Nv7tfXf-kPSph7eEGsc:b-dptmcy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6e862ae1a7db2704e6ae249e88692a60eb3e7a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEventQuery.kt#L68)):*
> ```Kotlin
> 
>   override fun getUserVirtualIdUniverse(): Sequence<Long> {
>     // TODO(@craig): Use EDP support library to retrieve the universe.
> ```

Fix GitHub username reference



_Suggestion:_
```Kotlin
@kungfucraig
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: 4 of 8 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEdpSimulatorRunner.kt` line 66 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv7sopNC9zK4Y9N78iN:-Nv80_d28jBFJsw4d3Q1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6e862ae1a7db2704e6ae249e88692a60eb3e7a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEdpSimulatorRunner.kt#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't prefix this with `big-query`, as it's not relating to the BQ dataset. (The flags above are all for identifying the dataset).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt` line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv7tH1d3LvfAR19QwPs:-Nv80cFF6uTCR6-w3aPp:b-oemnef) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6e862ae1a7db2704e6ae249e88692a60eb3e7a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If this were inclusive, we could use "maxVidValue" and be less verbose.
</blockquote></details>

It is exclusive so I guess upper bound is more accurate.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEventQuery.kt` line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv7tfXf-kPSph7eEGsb:-Nv80kFf4gG4O80y7x6w:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6e862ae1a7db2704e6ae249e88692a60eb3e7a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEventQuery.kt#L68)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Fix GitHub username reference
</blockquote></details>

Done.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: 1 of 8 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt` line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-Nv7tH1d3LvfAR19QwPs:-Nv89E2iD-Wt-9wBCsJP:bn2takv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6e862ae1a7db2704e6ae249e88692a60eb3e7a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt#L47)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

It is exclusive so I guess upper bound is more accurate.
</blockquote></details>

I update it as inclusive to be consistent with population_spec in public api.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by ple13 — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r4, 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 37 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562#-NvIhuQf6fQx8RFNdtdB:-NvIhuQf6fQx8RFNdtdC:b-4snoh9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/983b5e7ccadbe2b6253de21d28ad7a5c89b66915/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L37)):*
> ```Kotlin
> private const val COMPLETE_INDEX = 6
> private const val VID_INDEX = 7
> private const val DEFAULT_MAX_VID_VALUE = 10000000L // 10 million
> ```

ditto on underscores

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r4, 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1562)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
