### PR TITLE
Apply filter expression to EventGroup message.

### PR DESCRIPTION
**Pull request by SanjayVas**
This also fixes an issue where an error would be thrown if metadata wasn't set.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/810)

### CODE REVIEW

**Comment by SanjayVas** [comment]
This replaces #788, which was incorrectly marked as merged.

**Comment by SanjayVas** [comment]
@robinsons: This was technically already approved as #788, but I wouldn't mind another set of eyes from someone who understands protobuf descriptors.

**Comment by SanjayVas** [comment]
`//src/test/kotlin/org/wfanet/measurement/integration/k8s:CorrectnessTest` passes at 0b03c43e8d423b73259b4e1b7e4e265b70afa60e

**Review by robinsons — APPROVED** [review]
Made sure to give a thorough look at the descriptor code in particular. It looks good to me.

I still think it's really cool how all of these things have come together, especially the fact that you can use CEL to filter on an `Any` field.

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/810#-:-NLb3QJBD8cHcxxlfS5T:bcmazzc)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
