### PR TITLE
Improve Performance of Measurement Creation in Create Report

### PR DESCRIPTION
**Pull request by tristanvuong2021**
I tested a Report that created 300 measurements using a PeriodicTimeInterval with 300 increments. On a GKE cluster (e2-standard-2), it originally took ~60 seconds. With this PR, it takes ~30 seconds. Adding BatchCreateMeasurements to the internal Reporting server led to the bulk of the improvement. Caching the GetDataProvider and GetCertificate calls didn't lead to a large improvement. The measurement creation flow (Create Kingdom Measurements -> Create Reporting Measurements) occupies the bulk of the time. The only thing I could think of to further improve the performance is to add BatchCreateMeasurements to the Kingdom Public API.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1310)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1310)* status: all files reviewed, 6 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 246 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1310#-NhYuKFn34x_DW0TZoq2:-NhYuKFn34x_DW0TZoq3:b-jmvubx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adfa83e7f33dfe4678c008c9b0f8765fde314ca2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L246)):*
> ```Kotlin
> 
>   override suspend fun createReport(request: CreateReportRequest): Report {
>     val now = System.currentTimeMillis()
> ```

This looks to be unused. I assume it was for your rough benchmarks.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 331 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1310#-NhYuSwI5qp9RW6LynXV:-NhYuSwI5qp9RW6LynXW:b-quauhh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adfa83e7f33dfe4678c008c9b0f8765fde314ca2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L331)):*
> ```Kotlin
>       }
> 
>     val dataProviderNames = hashSetOf<String>()
> ```

nit: just use mutableSetOf unless the HashSet implementation is important



_Suggestion:_
```Kotlin
mutableSetOf
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1119 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1310#-NhYv9Sg7ocTeGBx4abP:-NhYv9Sh8m8u3_uqfcc7:b161n63) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adfa83e7f33dfe4678c008c9b0f8765fde314ca2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1119)):*
> ```Kotlin
>     dataProviderNames: Collection<String>
>   ): Map<String, DataProviderInfo> {
>     val dataProviderInfoMap = hashMapOf<String, DataProviderInfo>()
> ```

nit: Just use mutableMapOf unless the HashMap implementation is important



_Suggestion:_
```Kotlin
mutableMapOf
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 285 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1310#-NhYwAMm5k_lySW348Ds:-NhYwAMm5k_lySW348Dt:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adfa83e7f33dfe4678c008c9b0f8765fde314ca2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L285)):*
> ```Kotlin
>           .associateBy { it.externalReportingSetId }
> 
>       val dataProviderNames = hashSetOf<String>()
> ```

nit



_Suggestion:_
```Kotlin
mutableSetOf
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 498 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1310#-NhYwEIe2yttZSg68g4B:-NhYwEIe2yttZSg68g4C:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adfa83e7f33dfe4678c008c9b0f8765fde314ca2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L498)):*
> ```Kotlin
>       dataProviderNames: Collection<String>
>     ): Map<String, DataProviderInfo> {
>       val dataProviderInfoMap = hashMapOf<String, DataProviderInfo>()
> ```

nit



_Suggestion:_
```Kotlin
mutableMapOf
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateMeasurements.kt` line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1310#-NhYuCdg1T12ifCzJH6Q:-NhYuCdhEeJ4nqSW9XEh:b376w0l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adfa83e7f33dfe4678c008c9b0f8765fde314ca2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateMeasurements.kt#L30)):*
> ```Kotlin
>  */
> class CreateMeasurements(private val measurements: Collection<Measurement>) :
>   PostgresWriter<Collection<Measurement>>() {
> ```

nit: Couldn't this be `Iterable`? I don't spot anything extra from `Collection` being used (e.g. `size`)



_Suggestion:_
```Kotlin
Iterable
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1310)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 246 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1310#-NhYuKFn34x_DW0TZoq2:-NhZ2f5k1KbWiMBcACfo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adfa83e7f33dfe4678c008c9b0f8765fde314ca2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L246)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This looks to be unused. I assume it was for your rough benchmarks.
</blockquote></details>

Done.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 4 of 7 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1310)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
