### PR TITLE
Use common-jvm crypto key handles for consent signaling.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/400)

https://rally1.rallydev.com/#/?detail=/task/619374830321&fdp=true

### CODE REVIEW

**Comment by SanjayVas** [comment]
This depends on https://github.com/world-federation-of-advertisers/consent-signaling-client/pull/34 and https://github.com/world-federation-of-advertisers/common-jvm/pull/70

**Review by wangyaopw — APPROVED** [review]
Awesome PR!

> Reviewed 69 of 69 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/400#-:-MqaOer_DGss0gszvu9i:b-51d0kj)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt, line 99 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/400#-MqaMR3M6K8W_J11a8z2:-MqaMR3M6K8W_J11a8z3:b-gnsd49) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/280584cb1c6b51da647860a88f30ad51865f1138/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt#L99)):*
> ```
>     val csX509Certificate =
>       flags.csCertificateDerFile.inputStream().use { input -> readCertificate(input) }
> ```

This is a place where we read certificate from DER file.

Here is my comment from another PR explaining why it doesn't read from PEM file when I wrote this code.

"
I find one case in which we read DER file.

When we create certificate resources, we need to DER ByteStrings. So I saved the certificates as DER files such that I don't need to convert from PEM to DER in kotlin. As a result, the EDP, duchy and MC now also read certificate from DER files when they need to sign something.
"

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/400)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt, line 99 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/400#-MqaMR3M6K8W_J11a8z2:-MqaciWV3WF5JJ4y0JtM:b2yxmij) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/280584cb1c6b51da647860a88f30ad51865f1138/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt#L99)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     val csX509Certificate =
>       flags.csCertificateDerFile.inputStream().use { input -> readCertificate(input) }
> ```

This is a place where we read certificate from DER file.

Here is my comment from another PR explaining why it doesn't read from PEM file when I wrote this code.

"
I find one case in which we read DER file.

When we create certificate resources, we need to DER ByteStrings. So I saved the certificates as DER files such that I don't need to convert from PEM to DER in kotlin. As a result, the EDP, duchy and MC now also read certificate from DER files when they need to sign something.
"
</blockquote></details>

This is temporary. See the TODO indicating that `SigningKeyHandle`s should be obtained from a KMS-encrypted store instead. We should never have unencrypted keys lying around.

Note that the store need not read from blob storage. e.g. we can have KmsStorageClient that wraps a FileSystemStorageClient which reads from the K8s secrets volume.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/400)* status: 59 of 74 files reviewed, all discussions resolved (waiting on @stevenwarejones and @wangyaopw)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 58 of 69 files at r1, 15 of 16 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/400)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
