### PR TITLE
Update DP params and maximumPrivacyBudget for integration tests under…

### PR DESCRIPTION
**Pull request by iverson52000**
… ACDP composition

* Update default query DP params in integration tests so privacy budget will not be exceeded under ACDP composition
* Update maximumPrivacyBudget in the privacyBudgetManager in InProcessEdpSimulator to realistic value
* Document sample ACDP calculations in unit tests
* Fix two flaky tests in InProcessLifeOfAReportIntegrationTest.kt

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426)

**Review by iverson52000 — COMMENTED** [review]
@jiayu-google feel free to take a look of the DP params related changes

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426#-:-NoNffvf1U3wvrvrvLKa:b-5bppnd)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @jiayu-google and @uakyol)

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @jiayu-google and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1070 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426#-NoNi_xy7HyC7ldb8SGV:-NoNi_xy7HyC7ldb8SGW:b-7cbgz0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7cb629d10d7369e085c4bd39a4a259c2fbd42b80/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1070)):*
> ```Kotlin
>         }
>       // TODO(@tristanvuong2021): Assert using variance
>       if (
> ```

@riemanli  @tristanvuong2021 We need to update the DP params in this integration test to avoid exceeding privacy budget under ACDP. In this test, I saw sometimes the `expectedResult.reach.value` is 0 and `actualResult` is not because of noise, so the assertion `assertThat(actualResult).reachValue().isWithinPercent(0.5).of(expectedResult.reach.value)` will not work? The updated code is what I saw in other tests to handle this case? Does the change make sense to you?

**Review by jiayu-google — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @iverson52000 and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverterTest.kt` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426#-NoNk4Hp2ZVpfTnQwvSb:-NoNk4Hp2ZVpfTnQwvSc:b51sdlc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7cb629d10d7369e085c4bd39a4a259c2fbd42b80/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverterTest.kt#L132)):*
> ```Kotlin
>     // epsilon should be generally smaller than 1.0.
>     val acdpCharge =
>       AcdpParamsConverter.getDirectAcdpCharge(
> ```

Would you test `getLlv2AcdpCharge(DpParams(1.0, 1e-15), 3)` too just to be safe?

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @jiayu-google and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverterTest.kt` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426#-NoNk4Hp2ZVpfTnQwvSb:-NoNmfzU5riH6FzqmqD5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7cb629d10d7369e085c4bd39a4a259c2fbd42b80/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverterTest.kt#L132)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

Would you test `getLlv2AcdpCharge(DpParams(1.0, 1e-15), 3)` too just to be safe?
</blockquote></details>

Done.

**Comment by riemanli** [comment]
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1070 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426#-NoNi_xy7HyC7ldb8SGV:-NoNqYRdCG1Utq_6WIZG:b-npf3qo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7cb629d10d7369e085c4bd39a4a259c2fbd42b80/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1070)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

@riemanli  @tristanvuong2021 We need to update the DP params in this integration test to avoid exceeding privacy budget under ACDP. In this test, I saw sometimes the `expectedResult.reach.value` is 0 and `actualResult` is not because of noise, so the assertion `assertThat(actualResult).reachValue().isWithinPercent(0.5).of(expectedResult.reach.value)` will not work? The updated code is what I saw in other tests to handle this case? Does the change make sense to you?
</blockquote></details>

Hey Albert thanks for bringing it up. I actually have a PR #1423, and the issue here should be resolved there.

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @jiayu-google, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt` line 1070 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426#-NoNi_xy7HyC7ldb8SGV:-NoO7So27F3OiEkXhySY:b-oqqn6s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7cb629d10d7369e085c4bd39a4a259c2fbd42b80/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt#L1070)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Hey Albert thanks for bringing it up. I actually have a PR #1423, and the issue here should be resolved there.
</blockquote></details>

Great then I will wait for your PR to merge first. Thanks!

**Review by jiayu-google — APPROVED** [review]
:lgtm: Thanks Albert!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426#-:-NoO99Ha6oWRWUQRPDQ2:bvasvih)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021 and @uakyol)

**Review by uakyol — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by iverson52000 — COMMENTED** [review]
> Reviewed 5 of 7 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1426)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Pull request merged**
