### PR TITLE
Fail measurements on edp or duchy certificate revocation.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByDuchyCertificateId.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_Tx1h3EJKmvSxfXqm:-Mo_Tx1h3EJKmvSxfXqn:bg77dm9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/683697912c25524dfb5cc8e490abcb4207424a7b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByDuchyCertificateId.kt#L33)):*
> ```
>           AND ComputationParticipants.State = ${ComputationParticipant.State.REQUISITION_PARAMS_SET.number}
>           AND Measurements.State in (${Measurement.State.PENDING_REQUISITION_PARAMS.number},
> ```
not just PENDING_REQUISITION_PARAMS. All measurements not in a terminal state should be failed.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 120 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_RSnE7uGOPRxnMet3:-Mo_RSnE7uGOPRxnMet4:b-mas4it) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/683697912c25524dfb5cc8e490abcb4207424a7b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L120)):*
> ```
> RevokeCertificateRequest.ParentCase.EXTERNAL_DATA_PROVIDER_ID 
> ```

Possibly we can skip this case.

If the certificate is revoked before the requisition is fulfilled, the EDP can refuse to fulfill the requisition associated with the revoked cert later, which would fail the measurement.

If the certificate is revoked after the requisition is fulfilled. You current code would do nothing.

The only case we might want to handle is that the certificate is revoked after the requisition is fulfilled and before the measurement is done. But that is a short time window. maybe we don't care.


Also, your code is failing all measurements participated by a EDP. But we should only fail the subset of measurements impacted by the cert being revoked.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 125 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_Q75l4u1NDVDmlfoC:-Mo_Q75l4u1NDVDmlfoD:bxzsxvp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/683697912c25524dfb5cc8e490abcb4207424a7b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L125)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             measurementStates += Measurement.State.PENDING_COMPUTATION
>             measurementStates += Measurement.State.PENDING_PARTICIPANT_CONFIRMATION
>             measurementStates += Measurement.State.PENDING_REQUISITION_FULFILLMENT
>             measurementStates += Measurement.State.PENDING_REQUISITION_PARAMS
> ```
</details>

This list is used twice. Consider define a list variable for this, e.g. PENDING_MEASUREMENT_STATEs.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 162 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_PYQz8UlXfgx1g2lG:-Mo_PYR--EoL9B4FtOY5:b-ifkb4o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/683697912c25524dfb5cc8e490abcb4207424a7b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L162)):*
> ```
> else -> {}
> ```
Better to explicitly handle all cases.
```
RevokeCertificateRequest.ParentCase. EXTERNAL_MODEL_PROVIDER_ID -> {
  // Do Nothing.
}
RevokeCertificateRequest.ParentCase. PARENT_NOT_SET -> {
 throw IllegalStateException("RevokeCertificateRequest is missing parent field.")
}
```

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 162 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_PYQz8UlXfgx1g2lG:-MoaNKm0CLo4o3PwSoWI:b-r6oux3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d1d3848e63d3b655981328af72e99b58748efac6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L162)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> else -> {}
> ```
Better to explicitly handle all cases.
```
RevokeCertificateRequest.ParentCase. EXTERNAL_MODEL_PROVIDER_ID -> {
  // Do Nothing.
}
RevokeCertificateRequest.ParentCase. PARENT_NOT_SET -> {
 throw IllegalStateException("RevokeCertificateRequest is missing parent field.")
}
```
</blockquote></details>

All the cases are explicitly handled in the beginning of the class, I just made separate from the earlier handling.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByDuchyCertificateId.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_Tx1h3EJKmvSxfXqm:-MoaOIGfBCztEYfX5T1n:baa6nzg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d1d3848e63d3b655981328af72e99b58748efac6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByDuchyCertificateId.kt#L33)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>           AND ComputationParticipants.State = ${ComputationParticipant.State.REQUISITION_PARAMS_SET.number}
>           AND Measurements.State in (${Measurement.State.PENDING_REQUISITION_PARAMS.number},
> ```
not just PENDING_REQUISITION_PARAMS. All measurements not in a terminal state should be failed.
</blockquote></details>

I already have the four pending states.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByDuchyCertificateId.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_Tx1h3EJKmvSxfXqm:-Mod_R-A4QHcR_VwB4Rg:bu8ig5z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d1d3848e63d3b655981328af72e99b58748efac6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByDuchyCertificateId.kt#L33)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I already have the four pending states.
</blockquote></details>

how about building this query from input pending states based on `PENDING_MEASUREMENT_STATES`?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByDuchyCertificateId.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_Tx1h3EJKmvSxfXqm:-ModnOvq2v50La9BJ5ne:b-ovwaw7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d1d3848e63d3b655981328af72e99b58748efac6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByDuchyCertificateId.kt#L33)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

how about building this query from input pending states based on `PENDING_MEASUREMENT_STATES`?
</blockquote></details>

Good idea.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 120 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_RSnE7uGOPRxnMet3:-ModnSRgBq78xX1EoJcu:b7psqij) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d1d3848e63d3b655981328af72e99b58748efac6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L120)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> RevokeCertificateRequest.ParentCase.EXTERNAL_DATA_PROVIDER_ID 
> ```

Possibly we can skip this case.

If the certificate is revoked before the requisition is fulfilled, the EDP can refuse to fulfill the requisition associated with the revoked cert later, which would fail the measurement.

If the certificate is revoked after the requisition is fulfilled. You current code would do nothing.

The only case we might want to handle is that the certificate is revoked after the requisition is fulfilled and before the measurement is done. But that is a short time window. maybe we don't care.


Also, your code is failing all measurements participated by a EDP. But we should only fail the subset of measurements impacted by the cert being revoked.
</blockquote></details>

I used the data provider id because there is an unique index on the data provider certificates table that doesn't allow certificate reused across data providers.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 125 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_Q75l4u1NDVDmlfoC:-MoaO3UhAtPoRTy_m3ZT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d1d3848e63d3b655981328af72e99b58748efac6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L125)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>             measurementStates += Measurement.State.PENDING_COMPUTATION
>             measurementStates += Measurement.State.PENDING_PARTICIPANT_CONFIRMATION
>             measurementStates += Measurement.State.PENDING_REQUISITION_FULFILLMENT
>             measurementStates += Measurement.State.PENDING_REQUISITION_PARAMS
> ```
This list is used twice. Consider define a list variable for this, e.g. PENDING_MEASUREMENT_STATEs.
</blockquote></details>

Done.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 120 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_RSnE7uGOPRxnMet3:-Moecj3iDbApI7lcqcJ7:bquscwq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d1d3848e63d3b655981328af72e99b58748efac6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L120)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I used the data provider id because there is an unique index on the data provider certificates table that doesn't allow certificate reused across data providers.
</blockquote></details>

A certificate can not be used by multiple data providers. But a data provider can have multiple certificates. Revoking one certificate shouldn't impact measurements using other certificate of this data provider.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 162 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_PYQz8UlXfgx1g2lG:-MoedNjc2ahzAnNQLe9-:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d1d3848e63d3b655981328af72e99b58748efac6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L162)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

All the cases are explicitly handled in the beginning of the class, I just made separate from the earlier handling.
</blockquote></details>

sg

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 120 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Mo_RSnE7uGOPRxnMet3:-Mof3Tma1wfCiYTWl-AC:b6onndz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d1d3848e63d3b655981328af72e99b58748efac6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L120)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

A certificate can not be used by multiple data providers. But a data provider can have multiple certificates. Revoking one certificate shouldn't impact measurements using other certificate of this data provider.
</blockquote></details>

Switched it to certificate instead of edp.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)* status: all files reviewed, 9 unresolved discussions (waiting on @stevenwarejones, @tristanvuong2021, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj95xDE5ylD7NDTdtc:-Moj95xDE5ylD7NDTdtd:b-pp74zf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c88007f0df0374262e4494157f6e825e2f6b17a2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt#L31)):*
> ```Kotlin
>       appendClause("JOIN Requisitions USING (MeasurementConsumerId, MeasurementId)")
>       appendClause(
>         """
> ```

Can you line things up so the W in WHERE lines up with the first `"`? And the first closing `"` lines up with the first opening `"`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt, line 35 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj9-U79iHqFLwZjWJq:-Moj9-U79iHqFLwZjWJr:bjmc748) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c88007f0df0374262e4494157f6e825e2f6b17a2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt#L35)):*
> ```Kotlin
>           AND Requisitions.State = ${Requisition.State.UNFULFILLED.number}
>           AND Measurements.State in UNNEST(@pendingStates)
>           """
> ```

Can you add trimIndent() this string?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt, line 37 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj9iMh0-A-EJBxGYWi:-Moj9iMh0-A-EJBxGYWj:b-2pfdz3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c88007f0df0374262e4494157f6e825e2f6b17a2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt#L37)):*
> ```Kotlin
>           """
>       )
>       bind("pendingStates").toInt64Array(pendingMeasurementStates.map { it.number.toLong() })
> ```

Please use `toProtoEnumArray` instead
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj9lMv5gGKqOKd7uVV:-Moj9lMv5gGKqOKd7uVW:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c88007f0df0374262e4494157f6e825e2f6b17a2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt#L31)):*
> ```Kotlin
>       appendClause("JOIN ComputationParticipants USING (MeasurementConsumerId, MeasurementId)")
>       appendClause(
>         """
> ```

Ditto
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt, line 32 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj9qBM8vQMoBfcvaXh:-Moj9qBM8vQMoBfcvaXi:b-1x6b3h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c88007f0df0374262e4494157f6e825e2f6b17a2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt#L32)):*
> ```Kotlin
>       appendClause(
>         """
>           WHERE ComputationParticipants.CertificateId = ${duchyCertificateId.value}
> ```

Can you please use a bind for the RHS?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj9moD4-DGzgMMU9zC:-Moj9moD4-DGzgMMU9zD:b-1x6b3h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c88007f0df0374262e4494157f6e825e2f6b17a2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt#L33)):*
> ```Kotlin
>         """
>           WHERE ComputationParticipants.CertificateId = ${duchyCertificateId.value}
>           AND ComputationParticipants.State = ${ComputationParticipant.State.REQUISITION_PARAMS_SET.number}
> ```

Can you please use a bind for the RHS?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt, line 37 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj9ztE80MjfQ3-I4h-:-Moj9ztE80MjfQ3-I4h0:bxk7t8w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c88007f0df0374262e4494157f6e825e2f6b17a2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt#L37)):*
> ```Kotlin
>           """
>       )
>       bind("pendingStates").toInt64Array(pendingMeasurementStates.map { it.number.toLong() })
> ```

`toProtoEnumArray` please

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)* status: 4 of 7 files reviewed, 9 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj95xDE5ylD7NDTdtc:-MojLEd941eIqaslzzcN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7952b69b132deb8717952cd138033bf9f3bd6d1c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you line things up so the W in WHERE lines up with the first `"`? And the first closing `"` lines up with the first opening `"`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt, line 35 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj9-U79iHqFLwZjWJq:-MojLF531HEaNM3Wwf6S:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7952b69b132deb8717952cd138033bf9f3bd6d1c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add trimIndent() this string?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt, line 37 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj9iMh0-A-EJBxGYWi:-MojLFLF9HMVpbvWdsXO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7952b69b132deb8717952cd138033bf9f3bd6d1c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use `toProtoEnumArray` instead
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj9lMv5gGKqOKd7uVV:-MojLFygDD_nDYIIak-1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7952b69b132deb8717952cd138033bf9f3bd6d1c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt, line 32 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj9qBM8vQMoBfcvaXh:-MojLGGa3-KSnpbhlWTh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7952b69b132deb8717952cd138033bf9f3bd6d1c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you please use a bind for the RHS?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj9moD4-DGzgMMU9zC:-MojLCqG2dhsb5mkgvts:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7952b69b132deb8717952cd138033bf9f3bd6d1c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you please use a bind for the RHS?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt, line 37 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-Moj9ztE80MjfQ3-I4h-:-MojLDtS5ww6SjtDMCgZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7952b69b132deb8717952cd138033bf9f3bd6d1c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDuchyCertificateId.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`toProtoEnumArray` please
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @wangyaopw)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt, line 25 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-MojyxWA-04Gaocr-i06:-MojyxWA-04Gaocr-i07:b-pspdyj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eee93c34534f9269a0f75572b734e8dee30a3d07/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt#L25)):*
> ```
> StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId
> ```
nit: the name is too long. I vote for `StreamMeasurementByDataProviderCertificate`, but no strong opinion. Similar for the other one.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt, line 25 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363#-MojyxWA-04Gaocr-i06:-Moo9lvl0iJtOmupYcte:ba055bb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f671f176b5305dea2890b672e55c462ff1805e30/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId.kt#L25)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> StreamMeasurementDetailsForPendingMeasurementsByInternalDataProviderCertificateId
> ```
nit: the name is too long. I vote for `StreamMeasurementByDataProviderCertificate`, but no strong opinion. Similar for the other one.
</blockquote></details>

Went ahead and renamed them to your suggestion.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/363)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
