### PR TITLE
Remove clock parameter from SpannerWriter.execute and where it is unused

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/250)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 19 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/250)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/250#-Mih4vIm2Gj3vrvwyjwB:-Mih4vIm2Gj3vrvwyjwC:bv00obn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb528e8430bac7af61cf8e971e272d16a687c41d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L46)):*
> ```Kotlin
>   externalModelProviderId: Long?,
>   externalDataProviderId: Long?,
>   val clock: Clock = Clock.systemUTC()
> ```

Leave the default off here. We want to make sure that the clock dependency is always plumbed through.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 87 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/250#-Mih5Ed8E58-G9tzmYQ3:-Mih5Ed8E58-G9tzmYQ4:b-hj3nvf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb528e8430bac7af61cf8e971e272d16a687c41d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L87)):*
> ```Kotlin
>   suspend fun execute(
>     databaseClient: AsyncDatabaseClient,
>     idGenerator: IdGenerator = RandomIdGenerator()
> ```

nit: While you're in here, can you drop the default value for this param? It's a dependency that should always be plumbed all the way through.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsServiceTest.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/250#-Mih4SV_CZQ2Bnp5e2nn:-Mih4SV_CZQ2Bnp5e2no:bwh8t4j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb528e8430bac7af61cf8e971e272d16a687c41d/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsServiceTest.kt#L30)):*
> ```
> clock: Clock
> ```
unused param?

**Comment by SanjayVas** [comment]
CC @efoxepstein

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/250)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/250#-Mih67M1DWGjVvvomVjm:-Mih67M1DWGjVvvomVjn:biel420) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb528e8430bac7af61cf8e971e272d16a687c41d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L46)):*
> ```Kotlin
>   externalModelProviderId: Long?,
>   externalDataProviderId: Long?,
>   val clock: Clock = Clock.systemUTC()
> ```

`private val`?

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/250#-Mih67M1DWGjVvvomVjm:-MihDHEuEPStCyPVrWH3:b8nmroi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb528e8430bac7af61cf8e971e272d16a687c41d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`private val`?
</blockquote></details>

Whoops, made it private.

**Comment by tristanvuong2021** [comment]
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsServiceTest.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/250#-Mih4SV_CZQ2Bnp5e2nn:-MihDUbLDjez-96Xe3T-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb528e8430bac7af61cf8e971e272d16a687c41d/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsServiceTest.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> clock: Clock
> ```
unused param?
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/250)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 15 of 20 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
