### PR TITLE
Update terraform and workflow to deploy Reporting V2

### PR DESCRIPTION
**Pull request by tristanvuong2021**
There will be one cluster for Reporting V1 and one cluster for Reporting V2.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 6 of 6 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`.github/workflows/configure-reporting-v2.yml` line 89 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223#-Np17i9o2IS5sGbky_Dt:-Np17i9o2IS5sGbky_Du:b-d6iqol) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c45840fea46bd885b04e173bfbc7134befc15c3/.github/workflows/configure-reporting-v2.yml#L89)):*
> ```YAML
>       run: >
>         bazelisk build 
>         "//src/main/k8s/dev:reporting_v2.tar"
> ```

nit: why is this in quotes?
___
*[`.github/workflows/terraform-cmms.yml` line 99 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223#-Np15TOd6GWCav2SEnAK:-Np15TOd6GWCav2SEnAL:b-2mr6qf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/937086a672fb1e893960d70b56d18fd8fae3d7f0/.github/workflows/terraform-cmms.yml#L99)):*
> ```YAML
>       working-directory: ${{ env.GCLOUD_MODULE_PATH }}
>       run: terraform apply -input=false tfplan
> ```

Why was this all removed? This is needed for the worker2 Duchy which runs in AWS.
___
*[`src/main/terraform/gcloud/cmms/reporting_v2.tf` line 15 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223#-Np18ACJ5hiDret32rnp:-Np18ACJ5hiDret32rnq:b-bhp53u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c45840fea46bd885b04e173bfbc7134befc15c3/src/main/terraform/gcloud/cmms/reporting_v2.tf#L15)):*
> ```HCL
> # limitations under the License.
> 
> module "reporting_cluster" {
> ```

These names all need to be changed I think. Terraform basically just concats all the .tf files together.



_Code quote:_
```HCL
"reporting_cluster"
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223)* status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`.github/workflows/configure-reporting-v2.yml` line 89 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223#-Np17i9o2IS5sGbky_Dt:-Np1CO6G5UiVL8i8lufh:b-d1uvyl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c45840fea46bd885b04e173bfbc7134befc15c3/.github/workflows/configure-reporting-v2.yml#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: why is this in quotes?
</blockquote></details>

I copied it from the other file. I removed quotes from both
___
*[`.github/workflows/terraform-cmms.yml` line 99 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223#-Np15TOd6GWCav2SEnAK:-Np1CUmU8rYVyil6xyL4:b-eg7yul) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/937086a672fb1e893960d70b56d18fd8fae3d7f0/.github/workflows/terraform-cmms.yml#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why was this all removed? This is needed for the worker2 Duchy which runs in AWS.
</blockquote></details>

I removed it to try to make the testing run faster.
___
*[`src/main/terraform/gcloud/cmms/reporting_v2.tf` line 15 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223#-Np18ACJ5hiDret32rnp:-Np1CUJ68QSDY3WDGgXx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c45840fea46bd885b04e173bfbc7134befc15c3/src/main/terraform/gcloud/cmms/reporting_v2.tf#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These names all need to be changed I think. Terraform basically just concats all the .tf files together.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`.github/workflows/terraform-cmms.yml` line 99 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223#-Np15TOd6GWCav2SEnAK:-Np1KQW29SLjsPF4tvd3:b-1jbizx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/937086a672fb1e893960d70b56d18fd8fae3d7f0/.github/workflows/terraform-cmms.yml#L99)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I removed it to try to make the testing run faster.
</blockquote></details>

Leave it commented out with a DO_NOT_SUBMIT comment then so it's clear that you intend to put it back before submitting.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223)* status: 4 of 16 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`.github/workflows/terraform-cmms.yml` line 99 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223#-Np15TOd6GWCav2SEnAK:-Np6EJoUAFzzMWILbLCd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/937086a672fb1e893960d70b56d18fd8fae3d7f0/.github/workflows/terraform-cmms.yml#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Leave it commented out with a DO_NOT_SUBMIT comment then so it's clear that you intend to put it back before submitting.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/k8s/reporting_v2.cue` line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223#-Np6F1OR2YKY_V2cneh7:-Np6F1OR2YKY_V2cneh8:b-vl8eyk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e28a1b4d6409a731f04c2e086213477f4888aa02/src/main/k8s/reporting_v2.cue#L21)):*
> ```CUE
> 	_verboseGrpcClientLogging: bool | *false
> 
> 	_reportSchedulingCronSchedule: "30 6 * * *" // Daily at 6:30 AM
> ```

Shouldn't this be overridable?



_Suggestion:_
```CUE
_reportSchedulingCronSchedule: string | *"30 6 * * *" // Daily at 6:30 AM
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/reporting_v2.cue` line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223#-Np6F1OR2YKY_V2cneh7:-Np6M-D_92KHGTeTshm4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e28a1b4d6409a731f04c2e086213477f4888aa02/src/main/k8s/reporting_v2.cue#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this be overridable?
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 6 files at r3, 2 of 5 files at r6, 7 of 11 files at r7, 4 of 4 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1223)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
