### PR TITLE
Add listReport

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1053)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 344 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1053#-NXRgPfjDlPOkLBU4IwW:-NXRgPfjDlPOkLBU4IwX:b-it612b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3e77336a8523023ac102cadda810703fb6ef48d5/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L344)):*
> ```Kotlin
>       }
> 
>       val metrics: List<Metric> =
> ```

You don't need this. You already have the map so externalIdToMetricMap.values would work.

**Review by tristanvuong2021 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1053)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1053)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 718 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1053#-NXTwpwa57FB1WlnJ-gN:-NXTwpwa57FB1WlnJ-gO:bhvvv9n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bfde43db889069d79a71a18e8f103f6adfe60c7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L718)):*
> ```Kotlin
> 
>   val isValidPageSize =
>     source.pageSize != 0 && source.pageSize >= MIN_PAGE_SIZE && source.pageSize <= MAX_PAGE_SIZE
> ```

nit  this could be simplified:  ```source.pageSize in 1..MAX_PAGE_SIZE```



_Code quote:_
```Kotlin
source.pageSize != 0 && source.pageSize >= MIN_PAGE_SIZE && source.pageSize <= MAX_PAGE_SIZE
```

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1053)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @jcorilla, @Marco-Premier, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 718 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1053#-NXTwpwa57FB1WlnJ-gN:-NXW9-rYDQP7GK3TyjUF:b-bjudbj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bfde43db889069d79a71a18e8f103f6adfe60c7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L718)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

nit  this could be simplified:  ```source.pageSize in 1..MAX_PAGE_SIZE```
</blockquote></details>

Thanks for the suggestion! Done.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1053)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla, @Marco-Premier, and @stevenwarejones)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1053)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla and @stevenwarejones)

**Pull request merged**
