### PR TITLE
adding header, cards, and table to Report view

### PR DESCRIPTION
**Pull request by bdomen-ggl**
Adding components to the Report view:
* Header
* Summary Cards
* Summary Table

Graphs will come as a follow up PR.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1203)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 13 of 22 files at r1, 7 of 10 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1203)* status: all files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/util/BUILD.bazel` line 10 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1203#-NdlXi8SCcxPMoq8RYen:-NdlXi8SCcxPMoq8RYeo:b5gfho3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad37ef3b5a1812baa553f4443b73d984c973f832/experimental/reporting-ui/src/main/react/reporting-ui/util/BUILD.bazel#L10)):*
> ```Starlark
> 
> js_library(
>     name = "util",
> ```

If you're using the default target name for the package, use a glob. Otherwise, name the target more specifically. In general, prefer more granular targets if not everything from the package will be used together.



_Suggestion:_
```Starlark
formatting
```
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/util/BUILD.bazel` line 12 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1203#-NdlWpK81yvkR56tHKTF:-NdlWpK81yvkR56tHKTG:ba6az88) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad37ef3b5a1812baa553f4443b73d984c973f832/experimental/reporting-ui/src/main/react/reporting-ui/util/BUILD.bazel#L12)):*
> ```Starlark
>     name = "util",
>     srcs = [
>         "numberWithMagnitude.ts",
> ```

Consistent file naming pattern (lower_snake_case). Also naming suggestion for a file with formatting functions.



_Suggestion:_
```Starlark
formatting.ts
```
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/util/numberWithMagnitude.ts` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1203#-NdlX73q50ASdZxzEu7K:-NdlX73q50ASdZxzEu7L:bxu2bi7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad37ef3b5a1812baa553f4443b73d984c973f832/experimental/reporting-ui/src/main/react/reporting-ui/util/numberWithMagnitude.ts#L23)):*
> ```XML
> });
> 
> export const numberWithMagnitude = (num: number, decimals: number, trailingZeros: boolean = false) => {
> ```

nit: naming that makes what this is doing more obvious



_Suggestion:_
```XML
formatNumberWithMagnitude
```

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1203)* status: 19 of 24 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/util/BUILD.bazel` line 10 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1203#-NdlXi8SCcxPMoq8RYen:-Ndp81OY2NQFc5n9CvOY:b-pprntw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad37ef3b5a1812baa553f4443b73d984c973f832/experimental/reporting-ui/src/main/react/reporting-ui/util/BUILD.bazel#L10)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you're using the default target name for the package, use a glob. Otherwise, name the target more specifically. In general, prefer more granular targets if not everything from the package will be used together.
</blockquote></details>

Gotcha sounds good.
Renamed to `formatting`
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/util/BUILD.bazel` line 12 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1203#-NdlWpK81yvkR56tHKTF:-Ndp85mLAxKB08v-cYDw:b-t23sjb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad37ef3b5a1812baa553f4443b73d984c973f832/experimental/reporting-ui/src/main/react/reporting-ui/util/BUILD.bazel#L12)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Consistent file naming pattern (lower_snake_case). Also naming suggestion for a file with formatting functions.
</blockquote></details>

Oops good one. Had a brain fart on that one. Also like the name suggestion.
Changed names to `formatting.ts`.
___
*[`experimental/reporting-ui/src/main/react/reporting-ui/util/numberWithMagnitude.ts` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1203#-NdlX73q50ASdZxzEu7K:-Ndp8is38mnY8OKzlj4v:b-rtd2sy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad37ef3b5a1812baa553f4443b73d984c973f832/experimental/reporting-ui/src/main/react/reporting-ui/util/numberWithMagnitude.ts#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: naming that makes what this is doing more obvious
</blockquote></details>

Yeah good name suggestion.
Changed the name.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1203)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
