### PR TITLE
Use Workload Identity for EDP simulators on GKE.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/661)

### CODE REVIEW

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/661)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`docs/gke/cluster-config.md` line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/661#-N9bQxiQ8guReWYsRlm1:-N9bQxiQ8guReWYsRlm2:b4p0ewe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5afd794dfe54f7eedb4283f1d95e2fdedce6f2b0/docs/gke/cluster-config.md#L102)):*
> ```Markdown
> ```shell
> gcloud projects add-iam-policy-binding halo-cmm-dev \
>   --role=roles/bigquery.jobUser
> ```

Missing \ at the end of the line
___
*[`docs/gke/cluster-config.md` line 108 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/661#-N9bR2ok3QzC2F0auOrV:-N9bR2olDmRtVk30g9LZ:buo9nmt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5afd794dfe54f7eedb4283f1d95e2fdedce6f2b0/docs/gke/cluster-config.md#L108)):*
> ```Markdown
> ```shell
> bq add-iam-policy-binding --table=true 'demo.labelled_events' \
>   --role=roles/bigquery.dataViewer
> ```

Same here

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/661)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`docs/gke/cluster-config.md` line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/661#-N9bQxiQ8guReWYsRlm1:-NA5N9nY-oNquynm0CAB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5afd794dfe54f7eedb4283f1d95e2fdedce6f2b0/docs/gke/cluster-config.md#L102)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Missing \ at the end of the line
</blockquote></details>

Done.
___
*[`docs/gke/cluster-config.md` line 108 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/661#-N9bR2ok3QzC2F0auOrV:-NA5NAAB-Q1EE3vR6ZgT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5afd794dfe54f7eedb4283f1d95e2fdedce6f2b0/docs/gke/cluster-config.md#L108)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/661)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/661)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
