### PR TITLE
Update building.md

### PR DESCRIPTION
**Pull request by chipingyeh**
Added alternative method to build project on Macs

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @wangyaopw)

___
*[docs/building.md, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFRUPIEBv8BGLndrCW:-MoFRUPIEBv8BGLndrCX:b-ain504) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L35)):*
> ```
> If the above script does not work
> ```
I'm still not certain why this is, as the instructions specified here don't seem meaningfully different than what the script is doing. The script adds the following:
1. Mounting the Bazel and Bazelisk caches.
2. Detecting if Docker is being run in rootless mode, and specifying the user and group IDs if needed so that mounted files get the right permissions.

Perhaps the cache has been poisoned and running `tools/bazel-container clean --expunge` would fix things?

Unfortunately I've only been able to test with my local configuration of rootless Docker on Linux-amd64, with a past additional test of rootless Podman.
___
*[docs/building.md, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFRDYDAOYIqCRyLlXP:-MoFRDYDAOYIqCRyLlXQ:bcikjl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L38)):*
> ```Markdown
> If the above script does not work, you can try pulling and running the ([wfa/bazel image](https://hub.docker.com/r/wfameasurement/bazel)) from the Docker repository manually via the following:
>    1. docker pull wfameasurement/bazel
>    2. docker run -v /path_to_local_repo:/path_to_container_dir -it wfameasurement/bazel /bin/bash
> ```

You'll probably also want a bind mount for the Bazel cache. Otherwise you'll have to completely rebuild everything whenever the container is restarted.

**Comment by chipingyeh** [comment]
___
*[docs/building.md, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFRUPIEBv8BGLndrCW:-MoF_fYa9rvnoI89Sh2q:b-s8btlz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> If the above script does not work
> ```
I'm still not certain why this is, as the instructions specified here don't seem meaningfully different than what the script is doing. The script adds the following:
1. Mounting the Bazel and Bazelisk caches.
2. Detecting if Docker is being run in rootless mode, and specifying the user and group IDs if needed so that mounted files get the right permissions.

Perhaps the cache has been poisoned and running `tools/bazel-container clean --expunge` would fix things?

Unfortunately I've only been able to test with my local configuration of rootless Docker on Linux-amd64, with a past additional test of rootless Podman.
</blockquote></details>

I'm getting a "The 'clean' command is only supported from within a workspace (below a directory having a WORKSPACE file)." error. Is it supposed to be run in a specific directory?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @wangyaopw)

___
*[docs/building.md, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFRUPIEBv8BGLndrCW:-MoFe4Hg0Aqsdjhg5VTa:b2ufxsf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L35)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

I'm getting a "The 'clean' command is only supported from within a workspace (below a directory having a WORKSPACE file)." error. Is it supposed to be run in a specific directory?
</blockquote></details>

The `tools/bazel-container` script is always assumed to be run within the directory where you have the cross-media-measurement source. Hence it should always be run as `tools/bazel-container` rather than some other path. The script mounts the local directory in the container and runs `bazel` there.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @wangyaopw)

___
*[docs/building.md, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFRDYDAOYIqCRyLlXP:-MoFUUF_1huwRTC7lL4b:b-9tno85) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You'll probably also want a bind mount for the Bazel cache. Otherwise you'll have to completely rebuild everything whenever the container is restarted.
</blockquote></details>

We can keep the container running until we restart the machine, right?
___
*[docs/building.md, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFUws47ezH9m9RrKQT:-MoFUws47ezH9m9RrKQU:b-figwv5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L40)):*
> ```
> 4
> ```
this is step 3 and the next one is step 4

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @wangyaopw)

___
*[docs/building.md, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFkEo21OSmf9xG9Vf9:-MoFkEo21OSmf9xG9VfA:byiwww1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L42)):*
> ```Markdown
>    4. cd path_to_container_dir
>    5. bazel build ...
> ```

Can you also mention changing the docker daemon memory to 8GB? the 4GB default doesn't work for me either.

**Comment by chipingyeh** [comment]
___
*[docs/building.md, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFRUPIEBv8BGLndrCW:-MoFp7tH9yPeo82w4e-i:bweteux) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The `tools/bazel-container` script is always assumed to be run within the directory where you have the cross-media-measurement source. Hence it should always be run as `tools/bazel-container` rather than some other path. The script mounts the local directory in the container and runs `bazel` there.
</blockquote></details>

I realized I had slightly modified the `tools/bazel-container` file, and when I reverted it it ran. Unfortunately it didn't seem to work well (Mac had to kill the stale process) and using `tools/bazel-container` to build afterwards still failed (`ERROR: /Users/cpy/git/cross-media-measurement/src/main/swig/protocol/liquidlegionsv2/BUILD.bazel:8:13: TreeArtifact src/main/swig/protocol/liquidlegionsv2/java_files was not created
ERROR: /Users/cpy/git/cross-media-measurement/src/main/swig/protocol/liquidlegionsv2/BUILD.bazel:8:13: SwigCompile src/main/swig/protocol/liquidlegionsv2/liquid_legions_v2_encryption_utility.cc failed: not all outputs were created or valid`).

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[docs/building.md, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFUws47ezH9m9RrKQT:-MoFp5Xq7ODD_SAMX72C:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L40)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> 4
> ```
this is step 3 and the next one is step 4
</blockquote></details>

Done.
___
*[docs/building.md, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFkEo21OSmf9xG9Vf9:-MoFp6j78fQ_ZaFoEvJn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L42)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Can you also mention changing the docker daemon memory to 8GB? the 4GB default doesn't work for me either.
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @wangyaopw)

___
*[docs/building.md, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFRUPIEBv8BGLndrCW:-MoG0ghd5unmcNbSTMEi:b37rpqe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L35)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

I realized I had slightly modified the `tools/bazel-container` file, and when I reverted it it ran. Unfortunately it didn't seem to work well (Mac had to kill the stale process) and using `tools/bazel-container` to build afterwards still failed (`ERROR: /Users/cpy/git/cross-media-measurement/src/main/swig/protocol/liquidlegionsv2/BUILD.bazel:8:13: TreeArtifact src/main/swig/protocol/liquidlegionsv2/java_files was not created
ERROR: /Users/cpy/git/cross-media-measurement/src/main/swig/protocol/liquidlegionsv2/BUILD.bazel:8:13: SwigCompile src/main/swig/protocol/liquidlegionsv2/liquid_legions_v2_encryption_utility.cc failed: not all outputs were created or valid`).
</blockquote></details>

Hmm, so weird that happens. I wonder if there's some oddness with file system operations within the mounted Bazel cache dir. In this particular example, the rule just shells out to `mkdir` to make the `java_files` directory.
___
*[docs/building.md, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFRDYDAOYIqCRyLlXP:-MoG-sve62WuP-MMkwSF:bunoayw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L38)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

We can keep the container running until we restart the machine, right?
</blockquote></details>

Right, though normally you don't want to have to rebuild everything in that case. I assume that Docker writes to a VFS rather than keeping all that in memory, but clears it when the container is no longer running.

Regardless, making this comment non-blocking. We can figure out why the script has other problems separately.

**Comment by chipingyeh** [comment]
___
*[docs/building.md, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFRUPIEBv8BGLndrCW:-MoJtXSY6YblfjHmx9xm:b7lpuol) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Hmm, so weird that happens. I wonder if there's some oddness with file system operations within the mounted Bazel cache dir. In this particular example, the rule just shells out to `mkdir` to make the `java_files` directory.
</blockquote></details>

Discovery update: I printed the command being run, and after removing "--env BAZELISK_HOME=/Users/cpy/.cache/bazelisk" from the command it actually succeeded. Seems to possibly have something to do with the cache specification.

**Comment by chipingyeh** [comment]
___
*[docs/building.md, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFRUPIEBv8BGLndrCW:-MoJusY273ppEfqLxlPL:b-zdthtp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L35)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Discovery update: I printed the command being run, and after removing "--env BAZELISK_HOME=/Users/cpy/.cache/bazelisk" from the command it actually succeeded. Seems to possibly have something to do with the cache specification.
</blockquote></details>

Actually I mistyped - I removed the 2 other --mount flags that were in the statement (`--mount type=bind,source=/var/tmp/_bazel_cpy,target=/Users/cpy/.cache/bazel/_bazel_cpy --mount type=bind,source=/Users/cpy/Library/Caches/bazelisk,target=/Users/cpy/.cache/bazelisk`) after the first --mount flag, not the cache statement. Do we need all 3 --mount flags?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @wangyaopw)

___
*[docs/building.md, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFRUPIEBv8BGLndrCW:-MoK-RMA6hMbqN46DNTo:b-4lpmqb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L35)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Actually I mistyped - I removed the 2 other --mount flags that were in the statement (`--mount type=bind,source=/var/tmp/_bazel_cpy,target=/Users/cpy/.cache/bazel/_bazel_cpy --mount type=bind,source=/Users/cpy/Library/Caches/bazelisk,target=/Users/cpy/.cache/bazelisk`) after the first --mount flag, not the cache statement. Do we need all 3 --mount flags?
</blockquote></details>

The three things being mounted are:
1. The workspace (source code)
2. The Bazel user output root (build/output cache) - Allows for incremental builds
3. The Bazelisk cache - Avoids having to download/extract the Bazel installation for the correct version every time

I assume it's (2) that's triggering the problem, as it's writing all the build output to a mounted location on the host filesystem rather than using Docker's virtual filesystem (VFS). The implication to me is that they may be a bug/limitation in the filesystem call mapping in Docker Desktop for MacOS.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @SanjayVas, and @wangyaopw)

___
*[docs/building.md, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/356#-MoFRDYDAOYIqCRyLlXP:-MoK1Z_55Ja5a8JB_hrh:b-up7ijs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/733fb6e60b1b0c56af312d002fe05ae30520cddc/docs/building.md#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Right, though normally you don't want to have to rebuild everything in that case. I assume that Docker writes to a VFS rather than keeping all that in memory, but clears it when the container is no longer running.

Regardless, making this comment non-blocking. We can figure out why the script has other problems separately.
</blockquote></details>

FYI, due to some irrelevant reason, I restarted my MacBook yesterday and thus needed to restart the container. However, all cached results still work, and `kubectl` and `gcloud` I installed are still available. Not sure how docker exactly works, but it seems docker caches everything unless you delete the container.

**Pull request closed without merging**
