### PR TITLE
Update Deployment Files For Report Scheduling

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1346)

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1346)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`docs/gke/reporting-v2-server-deployment.md` line 200 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1346#-Nm7bDW442Ocnr4GD07z:-Nm8WkBUBbO_opFMbUPz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89c89dd2c50b7eecf59d05333b4757e4b0c5e8e1/docs/gke/reporting-v2-server-deployment.md#L200)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't need to pass this in as a var to the build. Just hard-code a default. It can be customized in the generated YAML.

See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/operations/updating-retention-policies.md
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/V2AlphaFlags.kt` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1346#-Nm7bffe4Z0GRrHMIZb5:-Nm8Wlr87bbIrwwLQnB8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89c89dd2c50b7eecf59d05333b4757e4b0c5e8e1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/V2AlphaFlags.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Isn't this required for the public API server? You may need to split out the flags if you're sharing this with other binaries.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1346)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1346)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
