### PR TITLE
Remove parallelization of Reporting Server Postgres queries.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/741)

### CODE REVIEW

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/741)* status: 0 of 3 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/741#-NFyiNjQ4fjnE8Sa0-D0:-NFyiNjRCOP4ZRTrfqpm:b2icyq9) (no related file):*
If the transaction fails due to serialization, it is possible for another coroutine to already have sent a query to the database before the coroutines can be cancelled. In this case, another exception will occur and this new one could be one that is caught instead of the serialization exception. Instead of trying to work with that exception, this is a simpler solution.

___

**Review by SanjayVas — COMMENTED** [review]
nit: be more explicit in PR description / merge message.

Maybe "Stop parallelizing Reporting DB insertions". "Remove coroutines" could mean a lot of things, depending on what's being done with them. It's also not strictly true, as the DB client itself is coroutine-based.

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/741#-:-NFzN-s61MKw1_kXWw3z:b-82gm3i)* status: 2 of 3 files reviewed, 1 unresolved discussion

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/741)* status: all files reviewed, 1 unresolved discussion

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/741)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/741#-NFyiNjQ4fjnE8Sa0-D0:-NGO_PAcCr_cs48sGgX5:b-hxxu1a) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what was the purpose of originally launching these in separate coroutines?
</blockquote></details>

I was doing it to help speed it up, but started discovering issues later on.

___

**Pull request merged**
