### PR TITLE
Define internal Kingdom ComputationParticipants and MeasurementLogEntries services.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)

### CODE REVIEW

**Comment by SanjayVas** [comment]
These were missed in #52. CC @uakyol

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 253 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-Mct5CJh0ad0MYB4wyLl:-Mct5CJh0ad0MYB4wyLm:b1u432y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d7f8a34363bc4eb04e7f97abd50d736891d47be4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L253)):*
> ```
> measurement.internal.kingdom.RequisitionDetails
> ```
any benefit using INT64 here?

it is not a key or index, and we are not likely to query on the column in any use case.
___
*[src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-Mct6wQT6-XFTqHig73I:-Mct6wQT6-XFTqHig73J:b-ksq3m5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d7f8a34363bc4eb04e7f97abd50d736891d47be4/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L70)):*
> ```
> DuchyMeasurementLogEntry
> ```
Are we going to create a row in the MeasurementLogEntries table during the failComputationParticipant() call?

I am wondering how you will query this field when getting the ComputationParticipant later since this log id is not included anywhere in the ComputationParticipant table

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 253 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-Mct5CJh0ad0MYB4wyLl:-Mctn1Fc2bgv_NLkk7I5:b-h86r7j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d7f8a34363bc4eb04e7f97abd50d736891d47be4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L253)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> measurement.internal.kingdom.RequisitionDetails
> ```
any benefit using INT64 here?

it is not a key or index, and we are not likely to query on the column in any use case.
</blockquote></details>

We use INT64s for any internal IDs, and avoid exposing those values outside of internal services. That principle still applies here, it's just that we don't have a table with this particular ID in its primary key and instead have a config file. If we decide to move from a config file to a Duchies table in the future, we can do so without having to change the column type.
___
*[src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-Mct6wQT6-XFTqHig73I:-Mctnu-B7CjEC2Hb6Qu6:bex9r2m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d7f8a34363bc4eb04e7f97abd50d736891d47be4/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L70)):*
> Are we going to create a row in the MeasurementLogEntries table during the failComputationParticipant() call?

Yes.

> I am wondering how you will query this field when getting the ComputationParticipant later since this log id is not included anywhere in the ComputationParticipant table.

You know you have an entry in the DuchyMeasurementLogEntries table for a given ComputationParticipant in the FAILED state, and every DuchyMeasurementLogEntries row has a corresponding MeasurementLogEntries row. You can query the DuchyMeasurementLogEntries table using the PK of the ComputationParticipant, since it has those columns.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 253 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-Mct5CJh0ad0MYB4wyLl:-MctqiMxAyKcJTt46riH:b-7q5pdx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7c193710d14ed1f0b4295e3c8016478547220c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L253)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We use INT64s for any internal IDs, and avoid exposing those values outside of internal services. That principle still applies here, it's just that we don't have a table with this particular ID in its primary key and instead have a config file. If we decide to move from a config file to a Duchies table in the future, we can do so without having to change the column type.
</blockquote></details>

Slight correction: We *do* have a table with the internal Duchy ID in its primary key, but we don't have a canonical Duchies table.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 253 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-Mct5CJh0ad0MYB4wyLl:-Mcu0eHRBPmUk3Iq5xvA:b-4wh967) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7c193710d14ed1f0b4295e3c8016478547220c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L253)):*
> canonical
sg
___
*[src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-Mct6wQT6-XFTqHig73I:-Mcu1heQAyFkGlRnGg5b:b6bkbiq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7c193710d14ed1f0b4295e3c8016478547220c/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L70)):*
> ComputationParticipant
If using the PK of the ComputationParticipant, the query would return all logs for that ComputationParticipant. How do we find the one that should be put here as failure_log_entry? Are we going to assume that only one of those logs is PERMANENT error log? that won't be guaranteed I think.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-Mct6wQT6-XFTqHig73I:-Mcu5Htj5ZBbqXz_DAA_:bcsxx1w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7c193710d14ed1f0b4295e3c8016478547220c/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L70)):*
> Are we going to assume that only one of those logs is PERMANENT error log? that won't be guaranteed I think.

It will be, since the only way to add a `DuchyMeasurementLogEntries` row for a `PERMANENT` error is through `FailComputationParticipant`, and `FailComputationParticipant` would add that row transactionally with updating the `ComputationParticipant` state.

I updated the documentation for the internal `CreateDuchyMeasurementLogEntryRequest` to clarify that it cannot be used to add PERMANENT error entries, similar to the documentation for the system `CreateComputationLogEntry` method.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-Mct6wQT6-XFTqHig73I:-Mcu8QyyC0xoc6TE0RqK:b5rlb9y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7c193710d14ed1f0b4295e3c8016478547220c/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Are we going to assume that only one of those logs is PERMANENT error log? that won't be guaranteed I think.

It will be, since the only way to add a `DuchyMeasurementLogEntries` row for a `PERMANENT` error is through `FailComputationParticipant`, and `FailComputationParticipant` would add that row transactionally with updating the `ComputationParticipant` state.

I updated the documentation for the internal `CreateDuchyMeasurementLogEntryRequest` to clarify that it cannot be used to add PERMANENT error entries, similar to the documentation for the system `CreateComputationLogEntry` method.
</blockquote></details>

yep, that should work.

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @zachcwc)

**Review by wangyaopw — APPROVED** [review]

**Comment by zachcwc** [comment]
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement_consumer.proto, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-MczouNI4To9tAGo3MZy:-MczouNJ5m-GbOV3vHwk:b83axf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9640d17e5e5dc9519ef6a2ab6ebbd7fc54f722fa/src/main/proto/wfa/measurement/internal/kingdom/measurement_consumer.proto#L32)):*
> ```protobuf
> 
>   // The *preferred* Certificate belonging to this MeasurementConsumer.
>   Certificate preferred_certificate = 3;
> ```

Are we keeping track of preferred cert so that we can fall back on non-preferred certs if preferred becomes compromised or something?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement_consumer.proto, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-MczouNI4To9tAGo3MZy:-MczqENRCe3MDg3IIzaS:b-eebfdm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9640d17e5e5dc9519ef6a2ab6ebbd7fc54f722fa/src/main/proto/wfa/measurement/internal/kingdom/measurement_consumer.proto#L32)):*
<details><summary><i>Previously, zachcwc wrote…</i></summary><blockquote>

Are we keeping track of preferred cert so that we can fall back on non-preferred certs if preferred becomes compromised or something?
</blockquote></details>

This field is to support the field of the same name in the v2alpha public API. I assume your question is why that field exists there rather than here.

We keep track of all certs since they may be referenced by an existing public API resources (e.g. Measurement or PublicKey). The reason we have the *preferred* cert here is so that it's easy to figure out which one you should use for a new signature.

For more info, see the section on certificate preference in https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/640987b5196e26fe717a47875f603360d6c11346/docs/certificates.md.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement_consumer.proto, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-MczouNI4To9tAGo3MZy:-MczrgaV5PIby3m8agEA:btw7bui) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9640d17e5e5dc9519ef6a2ab6ebbd7fc54f722fa/src/main/proto/wfa/measurement/internal/kingdom/measurement_consumer.proto#L32)):*
> I assume your question is why that field exists there rather than here.

To clarify, I mean that I assume your question is really about why we have a preferred_certificate field in the public API resource message rather than why we have one here in the internal representation.

**Comment by zachcwc** [comment]
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement_consumer.proto, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118#-MczouNI4To9tAGo3MZy:-MczsDJWBbHledETzNc2:b-n3ozcd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9640d17e5e5dc9519ef6a2ab6ebbd7fc54f722fa/src/main/proto/wfa/measurement/internal/kingdom/measurement_consumer.proto#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I assume your question is why that field exists there rather than here.

To clarify, I mean that I assume your question is really about why we have a preferred_certificate field in the public API resource message rather than why we have one here in the internal representation.
</blockquote></details>

Yes that is right thank you!

**Review by zachcwc — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @zachcwc)

**Review by zachcwc — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @zachcwc)

**Review by zachcwc — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @oliver-amzn)

**Pull request merged**
