### PR TITLE
Define internal ReplaceDataProviderRequiredDuchies method.

### PR DESCRIPTION
**Pull request by jojijac0b**
Creates service and request to replace DataProvider duchy list

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/data_providers_service.proto` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913#-NRhaw9PEp8_bIAtZ2YO:-NRhaw9PEp8_bIAtZ2YP:bkyim05) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dcc08f4573a137c336c577822cea8367c67c6e98/src/main/proto/wfa/measurement/internal/kingdom/data_providers_service.proto#L30)):*
> ```protobuf
>   rpc GetDataProvider(GetDataProviderRequest) returns (DataProvider);
> 
>   rpc ReplaceDataProviderRequiredDuchies(
> ```

@SanjayVas - should this service also be used to update other fields of a DataProvider, like certificate and public key?

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/data_providers_service.proto` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913#-NRhaw9PEp8_bIAtZ2YO:-NRhrfjF87RgR_3U7wbV:b-vccxb6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dcc08f4573a137c336c577822cea8367c67c6e98/src/main/proto/wfa/measurement/internal/kingdom/data_providers_service.proto#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@SanjayVas - should this service also be used to update other fields of a DataProvider, like certificate and public key?
</blockquote></details>


So this was already discussed previously We already have the PublicKey singleton resource that exists for this purpose and it accepts oneof between ```external_data_provider_id``` or ```external_measurement_consumer_id```. 
Meaning that resource can be used to alter public key for both ```DataProvider``` and ```MeasurementConsumer```.

That's why I suggested Joji to create a custom method to only update the required duchy list as it's the only field that still can't be updated

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913)* status: all files reviewed, 4 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913#-NRiOVRe8V46ILVXJPkK:-NRiOVRe8V46ILVXJPkL:bi48qx) (no related file):*
nit: PR description should be written as an imperative ("Define internal ReplaceDataProviderRequiredDuchies method...")

See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md#pull-request-description

___
___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913#-NRhU80s4JljQrQL_-eG:-NRiOthMC5Md7mBLLQz-:b-1yfsvm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dcc08f4573a137c336c577822cea8367c67c6e98/src/main/k8s/testing/secretfiles/BUILD.bazel#L40)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

has this change been done by the linter automatically?
</blockquote></details>

While this reformatting would be correct as per the formatter, we do not reformat files that weren't otherwise touched by a PR. Please remove the unrelated changes from this PR.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/data_providers_service.proto` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913#-NRhaw9PEp8_bIAtZ2YO:-NRiPPyqE82xr53evfvE:bbroi26) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dcc08f4573a137c336c577822cea8367c67c6e98/src/main/proto/wfa/measurement/internal/kingdom/data_providers_service.proto#L30)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>


So this was already discussed previously We already have the PublicKey singleton resource that exists for this purpose and it accepts oneof between ```external_data_provider_id``` or ```external_measurement_consumer_id```. 
Meaning that resource can be used to alter public key for both ```DataProvider``` and ```MeasurementConsumer```.

That's why I suggested Joji to create a custom method to only update the required duchy list as it's the only field that still can't be updated
</blockquote></details>

Yes. If we wanted to support general updating of all fields, we would drop the PublicKey singleton and implement a [standard Update method](https://google.aip.dev/134). That would be a breaking API change though. Similarly, I don't think this warrants a separate singleton resource. Therefore, a [custom method](https://google.aip.dev/136) just to replace this fields is probably the right approach. This is similar to the `ReplaceAccountIdentity` method.

Note that all of the above discussion is about the public API, where this PR is for the supporting internal API.

**Review by Marco-Premier — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913)* status: all files reviewed, 4 unresolved discussions (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913#-NRhU80s4JljQrQL_-eG:-NRiitVQ2Ss5m4LiWd6l:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dcc08f4573a137c336c577822cea8367c67c6e98/src/main/k8s/testing/secretfiles/BUILD.bazel#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

While this reformatting would be correct as per the formatter, we do not reformat files that weren't otherwise touched by a PR. Please remove the unrelated changes from this PR.
</blockquote></details>

+1
___
*[`src/main/proto/wfa/measurement/internal/kingdom/data_providers_service.proto` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913#-NRhaw9PEp8_bIAtZ2YO:-NRiiUm-CFIql2czcx-j:bkrk4gn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dcc08f4573a137c336c577822cea8367c67c6e98/src/main/proto/wfa/measurement/internal/kingdom/data_providers_service.proto#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes. If we wanted to support general updating of all fields, we would drop the PublicKey singleton and implement a [standard Update method](https://google.aip.dev/134). That would be a breaking API change though. Similarly, I don't think this warrants a separate singleton resource. Therefore, a [custom method](https://google.aip.dev/136) just to replace this fields is probably the right approach. This is similar to the `ReplaceAccountIdentity` method.

Note that all of the above discussion is about the public API, where this PR is for the supporting internal API.
</blockquote></details>

yes that's correct. I decided to implement this first and then take care of public api to provide Joji with little tasks for ramping up easily

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b and @SanjayVas)

**Review by jojijac0b — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913#-:-NSLzgA11dprjYajelJs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913#-NRhU80s4JljQrQL_-eG:-NSLzNWV22SE7CzkRXX1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dcc08f4573a137c336c577822cea8367c67c6e98/src/main/k8s/testing/secretfiles/BUILD.bazel#L40)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

**Review by jojijac0b — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/913)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Pull request merged**
