### PR TITLE
Add population attribute annotations

### PR DESCRIPTION
**Pull request by kungfucraig**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1571)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1571)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Review by stevenwarejones — COMMENTED** [review]
just to make sure I'm on the same page:
1. the Person message will be what is included as an attribute in the PopulationSpec, correct? 
2. the population data provider would need to validate that all population_attribute fields are set (hasFoo), correct?
3. Is the population data provider expected to check all nested message (recursively check all fields) to see what fields are population_attribute-able? Or just the top-level fields?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1571#-:-NvcaDXRCsYX8XQR9FFC:b-740tm7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by SanjayVas — APPROVED** [review]
> We don't expect nesting, just a single level of attributes. [@SanjayVas](https://github.com/SanjayVas) please verify this.

Correct. This is a restriction on template design, at least in guidelines. Might be enforced by PBM validator.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1571#-:-NvclpyA-HDG4E0LgBLt:b-610arr)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by stevenwarejones — APPROVED** [review]
@jojijac0b fyi

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1571#-:-Nvco_DT5XYbM1Q9kVyK:b-kd5bxn)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1571)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by jojijac0b — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1571)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Pull request merged**
