### PR TITLE
Add support to query data from BigQuery in the EdpSimulator.

### PR DESCRIPTION
**Pull request by wangyaopw**
The current code runs a fixed query. When the EventGroups/Filters
implementation is the done. The query will be built based on the
EventFilters.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/350)

### CODE REVIEW

**Comment by wangyaopw** [comment]
@uakyol 

This is the PR I mentioned. It is getting the EDP ready to use EventFilters when eventGroups/Filters are implemented, we will need to refactor the EdpSimulator to build the query parameter from the eventFilters.

**Review by SanjayVas — APPROVED** [review]
Design question: do we think we'll be building queries based on filters, or do you think instead that we'll have a library that converts a filter into a predicate function that can be applied to events?

The reason I was thinking about the latter is that otherwise each EDP will need their own implementation of the filtering logic, as opposed to just needing some custom logic to fill in an Event proto (which could be generated from the template and field descriptors). The downside is that you'd need to apply this filter predicate to all events rather than having the DB engine do it.

@robinsons

> Reviewed 15 of 15 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/350#-:-Mo1AyfF6_i2XFBB023-:b-ufxshh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Review by wangyaopw — COMMENTED** [review]
Not sure how different EDPs store their raw event, as columns in DB or an event proto. But processing all events protos for each query sounds like an impossible task.

Each EDP needs to write plenty of codes to fetch internal data and fulfill the requisition, handling the extra filtering logic is not a big deal I feel.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/350#-:-Mo4_qTP7CT5lWHMnNry:bnn93nj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @uakyol)

**Review by robinsons — COMMENTED** [review]
Processing all events within a given event group should be reasonable, right? If an event filter has the EDP's reference ID, then the EDP would just run a map reduce job that

1. Reads all events with a matching reference ID (i.e. events that are in the event group).
2. Runs a filter stage over the events.
3. Handles the rest of the requisition logic.

With this model, we could help EDPs with step 2 by providing a utility that can evaluate the event filter. As Sanjay said, all the EDP would need to do is write transformation functions -- one per event template -- that convert their internal event representation into an event object that our utility can understand.

This approach is data model agnostic and could help prevent bugs when an EDP tries to convert an event filter into a DB query. However, it's less efficient.

Ultimately, we could provide this capability and let the EDP choose whether to use it, or whether to just convert the filter into a DB query. Knowing whether EDPs would use it in the near term just lets us understand the priority, I think.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/350#-:-Mo4myAe9E9CsNqzAnnn:borj29m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @uakyol)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 13 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/350)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EventQuery.kt, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/350#-Mo4qLd13fQWeZEFpS1s:-Mo4qLd13fQWeZEFpS1t:b-t5mops) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766ed2e5916dddd8d670de875c800151e89220b0/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EventQuery.kt#L23)):*
> ```Kotlin
> }
> 
> enum class AgeGroup(val string: String) {
> ```

these are going to possibly differ per market right?

**Comment by uakyol** [comment]
> Processing all events within a given event group should be reasonable, right? If an event filter has the EDP's reference ID, then the EDP would just run a map reduce job that
> 
> 1. Reads all events with a matching reference ID (i.e. events that are in the event group).
> 2. Runs a filter stage over the events.
> 3. Handles the rest of the requisition logic.
> 
> With this model, we could help EDPs with step 2 by providing a utility that can evaluate the event filter. As Sanjay said, all the EDP would need to do is write transformation functions -- one per event template -- that convert their internal event representation into an event object that our utility can understand.
> 
> This approach is data model agnostic and could help prevent bugs when an EDP tries to convert an event filter into a DB query. However, it's less efficient.
> 
> Ultimately, we could provide this capability and let the EDP choose whether to use it, or whether to just convert the filter into a DB query. Knowing whether EDPs would use it in the near term just lets us understand the priority, I think.
> 
> > _[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/350#-:-Mo4myAe9E9CsNqzAnnn:borj29m)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @uakyol)

I agree with this idea.

**Review by uakyol — APPROVED** [review]

**Review by wangyaopw — COMMENTED** [review]
Let's discuss this in the EventFilters design reviews.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/350#-:-Mo5BqNS63BIfk4ieB3C:b-u56vvo)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/350)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EventQuery.kt, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/350#-Mo4qLd13fQWeZEFpS1s:-Mo5CUFn7ThOsYLvpxZV:b-z7nh4e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766ed2e5916dddd8d670de875c800151e89220b0/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EventQuery.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

these are going to possibly differ per market right?
</blockquote></details>

This is just for test, and the enum values here come from the synthetic data provided by ISBA, which will be used in our M1B correctness test.

In real world, each EDP is free to use whatever value in their own EventGroupTemplates for each market.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/350)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 14 of 15 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/350)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
