### PR TITLE
Add a guide for updating to a new Halo release.

### PR DESCRIPTION
**Pull request by SanjayVas**
https://rally1.rallydev.com/#/?detail=/task/720940466317&fdp=true

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1196)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1196)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`docs/operations/updating-release.md` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1196#-NdCKhDP6Ah9-vLjvhPB:-NdCKhDP6Ah9-vLjvhPC:b-9la0zj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75fdbb656cbca9d278677d2f5a2bd32287cb09c0/docs/operations/updating-release.md#L44)):*
> ```Markdown
> 
>     Run `kubectl apply`.
> ```

Maybe add something about refer to the release notes for references to operational guides on how to enable any new features and enable those features?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1196)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`docs/operations/updating-release.md` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1196#-NdCKhDP6Ah9-vLjvhPB:-NdCNGXzDTC_YZ2QwVmk:bczpga6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75fdbb656cbca9d278677d2f5a2bd32287cb09c0/docs/operations/updating-release.md#L44)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Maybe add something about refer to the release notes for references to operational guides on how to enable any new features and enable those features?
</blockquote></details>

Done in above section.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by mariolamassaavedra — APPROVED** [review]
Thanks Sanjay, guide makes sense and me and the team understand how to proceed

**Pull request merged**
