### PR TITLE
Move ID token validation from internal accounts service to public account service

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 19 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416#-MtEnexI5Dq5-ovY7S_G:-MtEnexI5Dq5-ovY7S_H:b-ei1boc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4d1d73cbbaaa14f868324761cd4df90668d1055e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L68)):*
> ```Kotlin
> 
> class Population(val clock: Clock, val idGenerator: IdGenerator) {
>   data class IdToken(val issuer: String, val subject: String)
> ```

nit: maybe something like IdTokenClaims? This isn't really representing the token itself.



_Code quote:_
```Kotlin
IdToken
```
___
*[src/main/proto/wfa/measurement/internal/kingdom/accounts_service.proto, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416#-MtEpkHI7EYrsKSf13kp:-MtEpkHJ90aK_DbOspDM:b-tvd6ua) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4d1d73cbbaaa14f868324761cd4df90668d1055e/src/main/proto/wfa/measurement/internal/kingdom/accounts_service.proto#L62)):*
> ```protobuf
>   fixed64 activation_token = 2;
> 
>   string issuer = 3;
> ```

Use `OpenIdConnectIdentity` (though I don't know why that has an external ID in it now? As far as I know, identities aren't ever referenced by ID from the public API?)



_Code quote:_
```protobuf
  string issuer = 3;
  string subject = 4;
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416)* status: 12 of 21 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/internal/kingdom/accounts_service.proto, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416#-MtEpkHI7EYrsKSf13kp:-MtEy4_2ANtM93T6gy-O:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4d1d73cbbaaa14f868324761cd4df90668d1055e/src/main/proto/wfa/measurement/internal/kingdom/accounts_service.proto#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use `OpenIdConnectIdentity` (though I don't know why that has an external ID in it now? As far as I know, identities aren't ever referenced by ID from the public API?)
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 9 of 20 files at r1, 7 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 296 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416#-MtIsxgeEzwu7kjGQ5JX:-MtIsxgeEzwu7kjGQ5JY:ba182lh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b44fd005ee7e5b18580e70995fe442e15877443f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L296)):*
> ```Kotlin
>       } else {
>         return InternalAccountKt.openIdConnectIdentity {
>           issuer = verifiedJwt.issuer!!
> ```

nit: since these are on separate lines anyways, maybe use `requireNotNull`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 296 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416#-MtItDgK-nvAnM-IUWg7:-MtItDgK-nvAnM-IUWg8:bvao5y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b44fd005ee7e5b18580e70995fe442e15877443f/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L296)):*
> ```Kotlin
>     val verifiedJwt =
>       SelfIssuedIdTokens.validateJwt(
>         redirectUri = "",
> ```

so, this will come up invalid if the user sends a redirectUri? If so, maybe we should reflect a different error for this and check earlier on that its blank.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt, line 151 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416#-MtIthBB6KYAY4ejq0Kn:-MtIthBB6KYAY4ejq0Ko:bewk2nj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b44fd005ee7e5b18580e70995fe442e15877443f/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt#L151)):*
> ```Kotlin
> 
>   @Test
>   fun `createAccount throws UNAUTHENTICATED when credentials are missing`() {
> ```

can you add tests with a populated and blank redirectUri?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 296 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416#-MtItDgK-nvAnM-IUWg7:-MtJf0ae8nrUNtxuVup8:bfsjotr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b44fd005ee7e5b18580e70995fe442e15877443f/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L296)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

so, this will come up invalid if the user sends a redirectUri? If so, maybe we should reflect a different error for this and check earlier on that its blank.
</blockquote></details>

Whatever is sent as the redirectUri is compared to the redirectUri in the ID token. Leaving it blank here is just a convenience for testing.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt, line 151 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416#-MtIthBB6KYAY4ejq0Kn:-MtJdOVV83Ll0KsQ8wgD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b44fd005ee7e5b18580e70995fe442e15877443f/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt#L151)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add tests with a populated and blank redirectUri?
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 20 files at r1, 1 of 9 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 292 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416#-MtoEWKJCnEieiRcw9mx:-MtoEWKJCnEieiRcw9my:bvgdn07) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c9a4174b7f24d3f8239586ada313e78a35a7efe/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L292)):*
> ```Kotlin
>       }
> 
>       return if (verifiedJwt.subject != null) {
> ```

I think I prefer the flipped: If its null throw the error

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 292 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416#-MtoEWKJCnEieiRcw9mx:-MtoHbTD1hoAb_n4Bhga:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c9a4174b7f24d3f8239586ada313e78a35a7efe/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L292)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think I prefer the flipped: If its null throw the error
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 292 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416#-MtoEWKJCnEieiRcw9mx:-Mtrv2KO3ZCmvasChWkV:b-rshz97) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c9a4174b7f24d3f8239586ada313e78a35a7efe/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L292)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sorry - maybe I'm not being clear
```
if (verifiedJwt.subject == null) {
  throw GeneralSecurityException()
return InternalAccountKt.openIdConnectIdentity {
          issuer = requireNotNull(verifiedJwt.issuer)
          subject = requireNotNull(verifiedJwt.subject)
        }

```

Then we don't need the else at all right?
</blockquote></details>

```
if (verifiedJwt.subject == null)
  throw GeneralSecurityException()
return InternalAccountKt.openIdConnectIdentity {
          issuer = requireNotNull(verifiedJwt.issuer)
          subject = requireNotNull(verifiedJwt.subject)
        }
```

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 292 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416#-MtoEWKJCnEieiRcw9mx:-MtsBfLdEorXrCIrDp_7:bkzrm2m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c9a4174b7f24d3f8239586ada313e78a35a7efe/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L292)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

```
if (verifiedJwt.subject == null)
  throw GeneralSecurityException()
return InternalAccountKt.openIdConnectIdentity {
          issuer = requireNotNull(verifiedJwt.issuer)
          subject = requireNotNull(verifiedJwt.subject)
        }
```
</blockquote></details>

Oh true.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416)* status: 16 of 21 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 4 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/416)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
