### PR TITLE
Implement GetMeasurement Method for Kingdom Internal Measurements Service

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiNn7eS9yTTv7PQidcU:-MiNn7eT7ltuwpEDhKwo:b-12ouxo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fea0f4e29e8d4888cc9366fb33601f92dda4c11f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L59)):*
> ```
> request.measurementView
> ```

add `grpcRequire(request.measurementView == DEFAULT) { message }`?

This method is called by the EDP or the MC, who are not allowed to see the `COMPUTATION_VIEW` I think.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiNni6PENHhOjjAIJaf:-MiNni6PENHhOjjAIJag:b4u0mm1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fea0f4e29e8d4888cc9366fb33601f92dda4c11f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L71)):*
> ```
> ··
> ```

what is this two dots `..` here for? 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 281 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiNo51i2ym7C9lyp36U:-MiNo51i2ym7C9lyp36V:bvxjznl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fea0f4e29e8d4888cc9366fb33601f92dda4c11f/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L281)):*
> ```
> COMPUTATION
> ```
test the DEFAULT view instead

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiNn7eS9yTTv7PQidcU:-MiRIKKmEj2yy7LIoCFP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fea0f4e29e8d4888cc9366fb33601f92dda4c11f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L59)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> request.measurementView
> ```

add `grpcRequire(request.measurementView == DEFAULT) { message }`?

This method is called by the EDP or the MC, who are not allowed to see the `COMPUTATION_VIEW` I think.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiNni6PENHhOjjAIJaf:-MiRFv8t5JlDCVxCKOZX:by8vdbb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fea0f4e29e8d4888cc9366fb33601f92dda4c11f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L71)):*
> ```
> nsumerId··
> ```
so weird, it shows up as a space in the editor. Fixed it, thanks for noticing. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 281 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiNo51i2ym7C9lyp36U:-MiRIKya6BmmJfNc_Din:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fea0f4e29e8d4888cc9366fb33601f92dda4c11f/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L281)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> COMPUTATION
> ```
test the DEFAULT view instead
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiNn7eS9yTTv7PQidcU:-MiRycxl1pqr6JGpwvPj:b-gveuoj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fea0f4e29e8d4888cc9366fb33601f92dda4c11f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L59)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Well, I need to clarify that this method is not called by MC directly, but instead originated from the MC. 

The public API can make sure it always set the view to DEFAULT. but it is still nice that the internalService checks the view to have more safety guarantee.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: all files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiTaUAU5daF2cI_QqaQ:-MiTaUAU5daF2cI_QqaR:b-cdejyc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcc86e2dc8e81ebf08a326f506557a4a2da47035/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L61)):*
> ```
>     grpcRequire(request.measurementView == Measurement.View.DEFAULT) {
>       "getMeasurement only supports DEFAULT View"
>     }
> ```
Same comment as https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/236#pullrequestreview-743233725.

There's no point in having a view field in the request if we're just always going to require it to be a specific one.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 63 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiTbEQ50l4KHn_6a5U8:-MiTbEQ50l4KHn_6a5U9:beh7w0o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcc86e2dc8e81ebf08a326f506557a4a2da47035/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L63)):*
> ```
> readByExternalIdsOrNull
> ```
nit: Just `readByExternalIds`. We should be dropping the `orNull` distinction as per #242 .
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiTb6Nh-KRsm2Z08dpQ:-MiTb6Nh-KRsm2Z08dpR:b-f8k6jk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcc86e2dc8e81ebf08a326f506557a4a2da47035/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L68)):*
> ```
> this.
> ```
nit: unnecessary qualification?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 333 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiTbgjk3heQVLRDpWz1:-MiTbgjk3heQVLRDpWz2:baaak3b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcc86e2dc8e81ebf08a326f506557a4a2da47035/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L333)):*
> ```Kotlin
>       assertThat(measurement)
>         .ignoringFields(
>           Measurement.REQUISITIONS_FIELD_NUMBER,
> ```

Ignore fields that we don't care about their exact value. Clear fields that shouldn't exist in the expected measurement.

The difference is that if we ignore the field, we'd ignore an error that resulted from the field being set when it shouldn't be.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: all files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiTaUAU5daF2cI_QqaQ:-MiTd-Zr6F7yP_wTvSYW:b-j0lv9z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcc86e2dc8e81ebf08a326f506557a4a2da47035/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     grpcRequire(request.measurementView == Measurement.View.DEFAULT) {
>       "getMeasurement only supports DEFAULT View"
>     }
> ```
Same comment as https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/236#pullrequestreview-743233725.

There's no point in having a view field in the request if we're just always going to require it to be a specific one.
</blockquote></details>

so should we let the publicApi make sure it doesn't set a wrong view, or just don't provide this option in the internal API?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: all files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiTaUAU5daF2cI_QqaQ:-MiTfsLwCxp5jOck_Gwq:b-q8kukn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcc86e2dc8e81ebf08a326f506557a4a2da47035/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L61)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

so should we let the publicApi make sure it doesn't set a wrong view, or just don't provide this option in the internal API?
</blockquote></details>

Depends. If we don't have a use case for allowing different views, drop the field in the internal request and document which view the internal service method returns.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 333 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiTbgjk3heQVLRDpWz1:-MiWBe0e9cIMDinal469:b-l67j59) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcc86e2dc8e81ebf08a326f506557a4a2da47035/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L333)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ignore fields that we don't care about their exact value. Clear fields that shouldn't exist in the expected measurement.

The difference is that if we ignore the field, we'd ignore an error that resulted from the field being set when it shouldn't be.
</blockquote></details>

thank you, can you help me a a little more though? I found only update and create time fields to the ignore list, did you have something else in mind?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 333 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiTbgjk3heQVLRDpWz1:-MiXXKg04Yw1G8sfAF1N:boa1yag) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcc86e2dc8e81ebf08a326f506557a4a2da47035/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L333)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thank you, can you help me a a little more though? I found only update and create time fields to the ignore list, did you have something else in mind?
</blockquote></details>

My comment was general advice for asserting proto message equality about when to ignore fields. Following that advice, you shouldn't ignore requisitions or computation participants and should instead make sure they're not set in the expected message. Since this is testing a Get call, you shouldn't need to ignore the timestamp fields either as you have the right values in your expected message.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiTaUAU5daF2cI_QqaQ:-MiaBVYSAF9HC3z4Tw3F:b-xoem3s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcc86e2dc8e81ebf08a326f506557a4a2da47035/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Depends. If we don't have a use case for allowing different views, drop the field in the internal request and document which view the internal service method returns.
</blockquote></details>

Based on our discussion, I got rid of the view parameter in the request and added comments to the measurements_service.proto. Hope this works.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 333 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MiTbgjk3heQVLRDpWz1:-MiaCFbk2vudJCYiJFPU:b-krx4c7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcc86e2dc8e81ebf08a326f506557a4a2da47035/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L333)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

My comment was general advice for asserting proto message equality about when to ignore fields. Following that advice, you shouldn't ignore requisitions or computation participants and should instead make sure they're not set in the expected message. Since this is testing a Get call, you shouldn't need to ignore the timestamp fields either as you have the right values in your expected message.
</blockquote></details>

ah thank you now I see what you mean. Hope this works

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 313 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-Miba8-j6m-6JtxfzaYB:-Miba8-j6m-6JtxfzaYC:brr53i7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e6cb1c51513e5bcdc65132c8865602f80614286/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L313)):*
> ```Kotlin
>           }
>         )
>       // TODO(@uakyol) : Assert dataPoviders field once it is populated in the MeasurementReader.
> ```

The data_providers field is returned for the DEFAULT view as of PR #225
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, line 29 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MibZqAc4WBae2UjkfYN:-MibZqAc4WBae2UjkfYO:bx1bkam) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e6cb1c51513e5bcdc65132c8865602f80614286/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L29)):*
> ```protobuf
>   rpc CreateMeasurement(Measurement) returns (Measurement);
> 
>   // Returns the DEFAULT View for the measurement.
> ```

nit: If you're going to add any documentation to a method, give it the proper form rather than just adding the part that you need to clarify. Indicating the use of DEFAULT view is optional, since it's the default :)

e.g.
```
Returns the Measurement for the specified external ID and parent.
```
and
```
Returns the Measurement for the specified external computation ID, using the COMPUTATION view.
```

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: all files reviewed, 2 unresolved discussions (waiting on @uakyol and @zachcwc)

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 313 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-Miba8-j6m-6JtxfzaYB:-Micxdyy0ihvalvra8lv:bsv417h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e6cb1c51513e5bcdc65132c8865602f80614286/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L313)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The data_providers field is returned for the DEFAULT view as of PR #225
</blockquote></details>

thank you!
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, line 29 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MibZqAc4WBae2UjkfYN:-MicxmMxCCPagbllzSzP:b-1cyu7w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e6cb1c51513e5bcdc65132c8865602f80614286/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: If you're going to add any documentation to a method, give it the proper form rather than just adding the part that you need to clarify. Indicating the use of DEFAULT view is optional, since it's the default :)

e.g.
```
Returns the Measurement for the specified external ID and parent.
```
and
```
Returns the Measurement for the specified external computation ID, using the COMPUTATION view.
```
</blockquote></details>

thank you

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: all files reviewed, 2 unresolved discussions (waiting on @uakyol and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 313 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-Miba8-j6m-6JtxfzaYB:-MicyhYh4ryXD9AccMwg:bm70m7d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e6cb1c51513e5bcdc65132c8865602f80614286/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L313)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thank you!
</blockquote></details>

I still see the TODO here. Are you working on this? (Reviewable has a separate disposition to indicate when you're still working on something).
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 322 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MicyaeM7SCk5A_2g1Sf:-MicyaeN9JeFkivMrmnr:bhmsas9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1f6a28f6a13d260d2e0b294158258fc4eefd319/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L322)):*
> ```Kotlin
>   }
> 
>   fun `getMeasurement COMPUTATION View fails`() =
> ```

I think this test is obsolete

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 313 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-Miba8-j6m-6JtxfzaYB:-MiczhUo5yUZimVUW7uy:b8ag3re) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e6cb1c51513e5bcdc65132c8865602f80614286/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L313)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I still see the TODO here. Are you working on this? (Reviewable has a separate disposition to indicate when you're still working on something).
</blockquote></details>


ah no, todo is done, thanks.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 322 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-MicyaeM7SCk5A_2g1Sf:-MicznIKCPlSHTDfu0xb:b-eg3y4u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1f6a28f6a13d260d2e0b294158258fc4eefd319/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L322)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think this test is obsolete
</blockquote></details>


thanks, artifact of bad rebase.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by uakyol — COMMENTED** [review]
> Reviewed 1 of 4 files at r4, 2 of 4 files at r5, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by wangyaopw — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-:-MigyjZ2DfY8HUNMlDVA:bnfp4nl)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @uakyol and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, line 29 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238#-Migz9v0AFxGqA9gXbT_:-Migz9v0AFxGqA9gXbTa:b-pfftf1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c451ccf932f5b46f53351bb9f510f431d696c9b8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L29)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>   // Returns the Measurement for the specified external ID and parent.
>   rpc GetMeasurement(GetMeasurementRequest) returns (Measurement);
>   // Returns the Measurement for the specified external computation ID, using
>   // the COMPUTATION view.
>   rpc GetMeasurementByComputationId(GetMeasurementByComputationIdRequest)
>       returns (Measurement);
> ```
</details>

nit:
```
  // Returns the DEFAULT view of a Measurement for the specified external ID and parent.
  rpc GetMeasurement(GetMeasurementRequest) returns (Measurement);
  // Returns the COMPUTATION view of a Measurement for the specified external computation ID
  rpc GetMeasurementByComputationId(GetMeasurementByComputationIdRequest)
      returns (Measurement);
```

**Review by uakyol — COMMENTED** [review]
> Reviewed 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @zachcwc)

**Review by uakyol — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Comment by SanjayVas** [comment]
This is for #103.

**Pull request merged**
