### PR TITLE
Store set operation compilation IDs

### PR DESCRIPTION
**Pull request by riemanli**
Part of the changes for implementing error bars in reporting server. To easily find the union of any two weighted measurements in a metric, we store the binary representation of each measurement from the binary representation of the weighed subset union created during set expression compilation of a reporting set.

### CODE REVIEW

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1072** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1072" target="_blank">Graphite</a> 
    * **PR #1080** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1080" target="_blank">Graphite</a> 
      * **PR #1100** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1100" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1100?utm_source=stack-comment).

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1100)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1100)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 125 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1100#-N_ilb0R3dvBrFPpJexg:-N_ilb0R3dvBrFPpJexh:b9c8n1x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c47883031b302700b51c5ee164218f7d3182e754/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L125)):*
> ```TSQL
> 
>   Weight integer NOT NULL,
>   BinaryRepresentation integer NOT NULL,
> ```

I merged my deployment images PR so sql changes now need to go in a new file that updates the schema instead of changing the original schema.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1100)* status: 10 of 15 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 125 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1100#-N_ilb0R3dvBrFPpJexg:-NaNQlWp1NWI53SepKhI:b-jo6avc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c47883031b302700b51c5ee164218f7d3182e754/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L125)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I merged my deployment images PR so sql changes now need to go in a new file that updates the schema instead of changing the original schema.
</blockquote></details>

Added a table modify file and added the log

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1100)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/resources/reporting/postgres/changelog-v2.yaml` line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1100#-NaNRtqr3ApG3qInwCHm:-NaNRtqr3ApG3qInwCHn:bbifrp5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/313a292111fd9e8a0a36a5447a8329efec47cd94/src/main/resources/reporting/postgres/changelog-v2.yaml#L26)):*
> ```YAML
>     relativeToChangeLogFile: true
> - include:
>       file: add-new-rows-to-weighted-subset-unions-and-metric-measurements.sql
> ```

nit: perhaps "add-binary-representation-column-to-weighted-subset-unions-and-metric-measurements" since you only added one column

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1100)* status: 13 of 15 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/changelog-v2.yaml` line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1100#-NaNRtqr3ApG3qInwCHm:-NaNSIEZ39X6ejwpbMNI:b47k6nx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/313a292111fd9e8a0a36a5447a8329efec47cd94/src/main/resources/reporting/postgres/changelog-v2.yaml#L26)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

nit: perhaps "add-binary-representation-column-to-weighted-subset-unions-and-metric-measurements" since you only added one column
</blockquote></details>

Thanks for the suggestion! Done

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 5 of 13 files at r1, 3 of 6 files at r2, 2 of 5 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
