### PR TITLE
Drop useless JobLauncher interface.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1436)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1436)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1436#-Nomr45o0FqSApAYiZ4C:-Nomr45o0FqSApAYiZ4D:b-v9u4kk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b6db0d81b6ff7dd54cf69fac11a569357b02acb/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L118)):*
> ```Kotlin
>     throttler.loopOnReady {
>       // All errors thrown inside the loop should be suppressed such that the daemon doesn't crash.
>       logAndSuppressExceptionSuspend { exchangeStepLauncher.findAndRunExchangeStep() }
> ```

the original idea was that findAndRunExchangeStep would run multiple times in parallel finding and executing as many jobs  as it can (while throttled) - that functionality would still need to exist in this update.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1436)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt` line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1436#-NomvTgX3Pzc6KmMj7jJ:-NomvTgX3Pzc6KmMj7jK:b-osm6od) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b6db0d81b6ff7dd54cf69fac11a569357b02acb/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L102)):*
> ```Kotlin
>   }
> 
>   override fun run() = runBlocking { runSuspending() }
> ```

i suggest removing this runSuspending and instead use launch in this file to findAndRunExchangesSteps - wdyt?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1436)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt` line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1436#-NomvTgX3Pzc6KmMj7jJ:-NonGt6Y6Pf6fl2Z9K1q:b1kmzlp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b6db0d81b6ff7dd54cf69fac11a569357b02acb/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L102)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i suggest removing this runSuspending and instead use launch in this file to findAndRunExchangesSteps - wdyt?
</blockquote></details>

There is a `launch` around `findAndRunExchangesStep`
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1436#-Nomr45o0FqSApAYiZ4C:-NonGHJj4nIcnotSuwLu:b-x6p0og) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b6db0d81b6ff7dd54cf69fac11a569357b02acb/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L118)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

the original idea was that findAndRunExchangeStep would run multiple times in parallel finding and executing as many jobs  as it can (while throttled) - that functionality would still need to exist in this update.
</blockquote></details>

I believe that's still what this is doing. The coroutine scope builder wraps`throttler.onReady`, so the `launch`es should all be executing concurrently. The throttler is therefore just putting a gap between each start.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1436)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1436#-Nomr45o0FqSApAYiZ4C:-Np13uwI1K3HKH5iMa7C:bxdfdq4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b6db0d81b6ff7dd54cf69fac11a569357b02acb/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L118)):*
That PR still has CoroutineLauncher and the whole issue of passing in a scope to a class that it uses to launch something in a suspending method. It's also based on layers of an 0.4.x branch. Do you have a clean PR that's based on main?

> I'm not sold on exactly how I'm instantiating the supervisor scope

There should be a single supervisor scope that all of the child coroutines happen under.

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1436)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @jonmolle)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1436#-Nomr45o0FqSApAYiZ4C:-Np1_S18AEwmHKZfL-BH:b-9n94pw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b6db0d81b6ff7dd54cf69fac11a569357b02acb/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L118)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That PR still has CoroutineLauncher and the whole issue of passing in a scope to a class that it uses to launch something in a suspending method. It's also based on layers of an 0.4.x branch. Do you have a clean PR that's based on main?

> I'm not sold on exactly how I'm instantiating the supervisor scope

There should be a single supervisor scope that all of the child coroutines happen under.
</blockquote></details>

agree they should all happen under a single supervisor scope

**Pull request closed without merging**
