### PR TITLE
Refactor SubmitBatchRequests to use Coroutines

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-NqUCyZq-D1TFCnchpRl:-NqUCyZq-D1TFCnchpRm:bn1wuq5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aaa1d70fa52be870b1f817b8cc0b58ad5e9a615a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt#L59)):*
> ```Kotlin
>   callRpc: suspend (List<ITEM>) -> RESP,
>   parseResponse: (RESP) -> List<RESULT>,
> ): List<RESULT> {
> ```

Thanks for bringing up `Semaphore`. I wonder if there is a particular reason to use `List`. When I wrote this implementation, I chose `Flow` to avoid blocking based on the review feedback.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-NqUCyZq-D1TFCnchpRl:-NqUWO0n11dn8IxcUz5B:bm60oiw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecf2ca11a83f910dbc36fd7e3b896ced49a28fe0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt#L59)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for bringing up `Semaphore`. I wonder if there is a particular reason to use `List`. When I wrote this implementation, I chose `Flow` to avoid blocking based on the review feedback.
</blockquote></details>

I changed it to a flow. Realized a way to make use of flow.

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-NqUCyZq-D1TFCnchpRl:-NqUYWe6EpY_tILWm2Uo:b-fax263) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecf2ca11a83f910dbc36fd7e3b896ced49a28fe0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt#L59)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I changed it to a flow. Realized a way to make use of flow.
</blockquote></details>

Would it be possible to just output `Flow<RESULT>` if you use `items.chunked(limit).flatMapConcat` or something works similarly instead of `items.chunked(limit).map`?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt` line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-NqUXdzL0KYFN57sYjxD:-NqUXdzL0KYFN57sYjxE:b2meav5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/18ba7ce9eff262a5e60762c6b0566796ef7e7f7b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt#L54)):*
> ```Kotlin
> /** Submits multiple RPCs by dividing the input items to batches. */
> suspend fun <ITEM, RESP, RESULT> submitBatchRequests(
>   items: Collection<ITEM>,
> ```

Same question about List vs Flow here for the input.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-NqUCyZq-D1TFCnchpRl:-NqUcWbnEwDSFzUjlV-C:bno0btl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecf2ca11a83f910dbc36fd7e3b896ced49a28fe0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt#L59)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Would it be possible to just output `Flow<RESULT>` if you use `items.chunked(limit).flatMapConcat` or something works similarly instead of `items.chunked(limit).map`?
</blockquote></details>

I made the Flow emit Lists corresponding to the API requests on purpose. Emitting individual elements requires iterating through the Lists, then using this method will require iterating through the elements as well. That is an additional iteration that adds up when considering performance.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt` line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-NqUXdzL0KYFN57sYjxD:-NqUddKcB5gQwGlKTz9o:b-p109wo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/18ba7ce9eff262a5e60762c6b0566796ef7e7f7b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt#L54)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Same question about List vs Flow here for the input.
</blockquote></details>

I don't see how making the input a Flow helps. A Collection or a Flow both require iterating through the elements sequentially to build the batch requests, except the way this method is used, will generally require converting a Collection to a Flow instead of just using the Collection directly.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt` line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-NqUXdzL0KYFN57sYjxD:-NqUgkj21-lEODEqS5Kp:b-iud756) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/18ba7ce9eff262a5e60762c6b0566796ef7e7f7b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt#L54)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I don't see how making the input a Flow helps. A Collection or a Flow both require iterating through the elements sequentially to build the batch requests, except the way this method is used, will generally require converting a Collection to a Flow instead of just using the Collection directly.
</blockquote></details>

I could see how a Flow input would improve things, but I would have to change the way SubmitBatchRequests is used. I will give it a shot and see if it works out.

**Review by riemanli — APPROVED** [review]
> Reviewed 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt` line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-NqUXdzL0KYFN57sYjxD:-NqUh0Y44LTcV6gbnqLW:brconbt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/18ba7ce9eff262a5e60762c6b0566796ef7e7f7b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt#L54)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I could see how a Flow input would improve things, but I would have to change the way SubmitBatchRequests is used. I will give it a shot and see if it works out.
</blockquote></details>

My only concern is when `items` contains numerous elements, which is the exact scenario this implementation designed for. Using `Collection` means we need to wait all elements are ready and also means higher memory consumption, i.e. higher chance of OOM. 

If you think using `Collection` has some advantages over using `Flow`, I am ok with that you want to test it out to see how to make the trade-off as you suggested above.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt` line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-NqUXdzL0KYFN57sYjxD:-NqUnRfA-DlWqbjtF8-K:bcgtazk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/18ba7ce9eff262a5e60762c6b0566796ef7e7f7b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/SubmitBatchRequests.kt#L54)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

My only concern is when `items` contains numerous elements, which is the exact scenario this implementation designed for. Using `Collection` means we need to wait all elements are ready and also means higher memory consumption, i.e. higher chance of OOM. 

If you think using `Collection` has some advantages over using `Flow`, I am ok with that you want to test it out to see how to make the trade-off as you suggested above.
</blockquote></details>

I refactored it.

**Review by riemanli — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 807 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-Nqdd5P20OUJUaFGTHsw:-Nqdd5P20OUJUaFGTHsx:b-iftc9j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d18475ffa01832f06e5be69db720a4900aa1a341/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L807)):*
> ```Kotlin
> 
>       // Most Measurements are expected to be SUCCEEDED so SUCCEEDED Measurements will be collected
>       // via a Flow.
> ```

I guess this is the trade-off if we are not able to use `Flow` for failed measurements. 



_Code quote:_
```Kotlin
      // Most Measurements are expected to be SUCCEEDED so SUCCEEDED Measurements will be collected
      // via a Flow.
```

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 809 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-NqjsqHG-NCmlqPej6kS:-NqjsqHG-NCmlqPej6kT:bo6jzzr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/03a63aa24706f3f5712d2a2c024e06319e1b1bda/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L809)):*
> ```Kotlin
>       // via a Flow.
>       val succeededMeasurements: Flow<Measurement> = flow {
>         getCmmsMeasurements(internalMeasurements, principal).collect { measurements ->
> ```

why do you need to collect then? Why not just map the flow?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @riemanli and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 809 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-NqjsqHG-NCmlqPej6kS:-Nqmss0zEOSy8fK88WsP:bs8nuid) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c45e7f9dce3c8d316d798102f50de345c744db28/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L809)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why do you need to collect then? Why not just map the flow?
</blockquote></details>

The alternative is flatMapConcat or map then flattenConcat instead of just collect, but that just moves the flow builder to inside the transform function. map alone will just create a flow that could return empty lists and that makes things complicated to deal with.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @riemanli and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 809 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-NqjsqHG-NCmlqPej6kS:-NraxRq10nv6gUFJiP54:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c45e7f9dce3c8d316d798102f50de345c744db28/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L809)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Let me clarify. Why doesn't something like the following work?
```
      val succeededMeasurements: Flow<Measurement> = 
        getCmmsMeasurements(internalMeasurements, principal).transform { measurement ->
            @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA") // Protobuf enum fields cannot be null.
            when (measurement.state) {
              Measurement.State.SUCCEEDED -> emit(measurement)
              Measurement.State.CANCELLED,
              Measurement.State.FAILED -> failedMeasurements.add(measurement)
              Measurement.State.COMPUTING,
              Measurement.State.AWAITING_REQUISITION_FULFILLMENT -> {}
              Measurement.State.STATE_UNSPECIFIED ->
                failGrpc(status = Status.FAILED_PRECONDITION, cause = IllegalStateException()) {
                  "The CMMS measurement state should've been set."
                }
              Measurement.State.UNRECOGNIZED -> {
                failGrpc(status = Status.FAILED_PRECONDITION, cause = IllegalStateException()) {
                  "Unrecognized CMMS measurement state."
                }
          }
}
```

</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 324 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-Nrb20wG1NCJIczpaFjS:-Nrb20wH8qxVxgA_rsUr:bbzd7qw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dac02eda757546b5708b9505a9cad756ee6be1e2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L324)):*
> ```Kotlin
>                 if (!contains(primitiveReportingSetBasis.externalReportingSetId)) {
>                   emit(primitiveReportingSetBasis.externalReportingSetId)
>                   add(primitiveReportingSetBasis.externalReportingSetId)
> ```

i'm confused why you are both emitting and adding here
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 398 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-Nrb066jCIymatokYxXj:-Nrb066jCIymatokYxXk:bcouebp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dac02eda757546b5708b9505a9cad756ee6be1e2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L398)):*
> ```Kotlin
>             callBatchCreateMeasurementsRpc,
>           ) { response: BatchCreateMeasurementsResponse ->
>             response.measurementsList
> ```

i think its clearer to transform this to a flow here and then merge the flows instead of flatMapMerge
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 420 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-Nrb0ZBzC_NLoHwUlgTK:-Nrb0ZBzC_NLoHwUlgTL:bmkyxjp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dac02eda757546b5708b9505a9cad756ee6be1e2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L420)):*
> ```Kotlin
>         reportingMetricCalculationSpec.metricCalculationSpecReportingMetricsList.flatMap {
>           metricCalculationSpecReportingMetrics ->
>           metricCalculationSpecReportingMetrics.reportingMetricsList.map {
> ```

I prefer `.asFlow.map{`

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @riemanli and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 324 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-Nrb20wG1NCJIczpaFjS:-Nrb37Wt90OLcPLPdD-0:b-pictg6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dac02eda757546b5708b9505a9cad756ee6be1e2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L324)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'm confused why you are both emitting and adding here
</blockquote></details>

Added comments to clarify.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 398 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-Nrb066jCIymatokYxXj:-Nrb2yk-1-IGKSOfGBI7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dac02eda757546b5708b9505a9cad756ee6be1e2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L398)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think its clearer to transform this to a flow here and then merge the flows instead of flatMapMerge
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 420 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467#-Nrb0ZBzC_NLoHwUlgTK:-Nrb73oM6S6868buRnIL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dac02eda757546b5708b9505a9cad756ee6be1e2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L420)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I prefer `.asFlow.map{`
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1467)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
