### PR TITLE
Improve performance of batch create measurements

### PR DESCRIPTION
**Pull request by tristanvuong2021**
The current implementation doesn't take advantage of batching and has separate reads for each create.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt` line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533#-Nua5QEFBq1FNWO6f5ah:-Nua5QEFBq1FNWO6f5ai:b-o2egur) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/193921d18310b04ce58ed11c8c0ada1f9639b088/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt#L37)):*
> ```Kotlin
>     val dataProviderId: Long,
>     val certificateId: Long,
>     val isValid: Boolean,
> ```

I assume this only applies to the certificate? Also note that the "is" verb is for accessor methods, whereas this is a property.



_Suggestion:_
```Kotlin
certificateValid
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533#-Nua6k_p9XMMw5-bOdOJ:-Nua6k_p9XMMw5-bOdOK:bptf0ie) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b3d3a7441134cbbbfb6bb628481350dd2c2eb699/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L66)):*
> ```Kotlin
>  * @throws [MeasurementConsumerNotFoundException] MeasurementConsumer not found
>  * @throws [DataProviderNotFoundException] DataProvider not found
>  * @throws [MeasurementConsumerCertificateNotFoundException] MeasurementConsumer's Certificate not
> ```

How can this be removed? The caller specifies which of the MC's (potentially multiple) certificates to use, and they can pass an ID for one that doesn't exist.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt` line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533#-Nua5QEFBq1FNWO6f5ah:-NujBpeXAtTdq5_16ooK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61d481332f1f55d99997b9843458f767710ebad1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I assume this only applies to the certificate? Also note that the "is" verb is for accessor methods, whereas this is a property.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533#-Nua6k_p9XMMw5-bOdOJ:-NujBq4sBaVv6NEkhzgM:bhbarkm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffb016dbcabc9df6fe47007fa05346f9355a8624/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

How can this be removed? The caller specifies which of the MC's (potentially multiple) certificates to use, and they can pass an ID for one that doesn't exist.
</blockquote></details>

I fixed it, but do I need to fix it for data provider certificates as well, or is it okay for data providers.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533#-Nua6k_p9XMMw5-bOdOJ:-NujLLs3C5FgfVN5pw1n:b-jysi4d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffb016dbcabc9df6fe47007fa05346f9355a8624/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L66)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I fixed it, but do I need to fix it for data provider certificates as well, or is it okay for data providers.
</blockquote></details>

If you're talking about the `data_provider_certificate` field in `Measurement.DataProviderEntry.Value`, that should indeed be the one that matches the DataProvider's public key at time of Measurement creation.

Note that we plan on dropping that field in v0.6.0

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 85 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533#-NuzZR6v7XrAbTClGo3c:-NuzZR6v7XrAbTClGo3d:b-t8suc3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc273df9e76d88ed459206db1fdb714e21aefbf4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L85)):*
> ```Kotlin
> 
>     val measurementConsumerCertificateIdsMap: Map<Long, InternalId> = buildMap {
>       reader.execute(transactionContext).toList().forEach {
> ```

i don't think you need `toList`
```
reader.execute(transactionContext).onEach{
    validateCertificate(it)
    put(it.certificate.externalCertificateId, it.certificateId)
  }
  .collect{}
```

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 442 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533#-NuzZmn60irf_wkUCREG:-NuzZmn60irf_wkUCREH:b-56a3i6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fc273df9e76d88ed459206db1fdb714e21aefbf4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L442)):*
> ```Kotlin
>       }
>       .execute(transactionContext)
>       .toList()
> ```

ditto on not needing `toList` here

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 85 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533#-NuzZR6v7XrAbTClGo3c:-Nv359JX9fjlBRT3t5nb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9702a1418614236cbc25c1cac5b70fe763478fab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L85)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i don't think you need `toList`
```
reader.execute(transactionContext).onEach{
    validateCertificate(it)
    put(it.certificate.externalCertificateId, it.certificateId)
  }
  .collect{}
```

</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt` line 442 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533#-NuzZmn60irf_wkUCREG:-Nv359hD7CaF0RWBqrzk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9702a1418614236cbc25c1cac5b70fe763478fab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt#L442)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto on not needing `toList` here
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1533)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
