### PR TITLE
Expose deletion_protection variable on gcloud cluster Terraform module

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1939)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1939)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/terraform/gcloud/modules/cluster/variables.tf` line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1939#-OClVnyF42Zfb0zP9ToO:-OClVnyF42Zfb0zP9ToP:b2vku3q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf646acdc33c05f981248731880ead2402e6b81f/src/main/terraform/gcloud/modules/cluster/variables.tf#L49)):*
> ```HCL
>   description = "Whether deletion protection is enabled"
>   type        = bool
>   default     = null
> ```

is this used to mark it as optional?



_Code quote:_
```HCL
default     = null
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1939)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

___
*[`src/main/terraform/gcloud/modules/cluster/variables.tf` line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1939#-OClVnyF42Zfb0zP9ToO:-OD7iaLZ81s-HWpHUmRn:bg97cpf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf646acdc33c05f981248731880ead2402e6b81f/src/main/terraform/gcloud/modules/cluster/variables.tf#L49)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

is this used to mark it as optional?
</blockquote></details>

Yes, that's how the concept of optional works in Terraform if you don't want to pick a default value. This is because Terraform variables have a separate concept of `nullable` which is true by default.

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @Marco-Premier from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1939)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1939)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Comment by mikkokotila** [comment]
Added `feat` prefix to title.

**Pull request merged**
