### PR TITLE
Update common-jvm to 0.59.0.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1084)

**Review by YuhongWang-Amazon — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1084)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/BUILD.bazel` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1084#-NZ2HoBM4qiiodoNv6ce:-NZ2HoBN2Gbajy6XofWh:b8m0q4z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04d55977cc512010c4b6da3383b95133245249b6/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/BUILD.bazel#L19)):*
> ```Starlark
>         "//src/main/proto/wfa/measurement/internal/reporting:reporting_sets_service_kt_jvm_grpc_proto",
>         "//src/main/proto/wfa/measurement/internal/reporting:reports_service_kt_jvm_grpc_proto",
>         "@wfa_common_jvm//imports/java/com/google/code/gson",
> ```

I move this package in previous common-jvm release. Why didn't this cause error?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1084)* status: 2 of 21 files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/BUILD.bazel` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1084#-NZ2HoBM4qiiodoNv6ce:-NZ2TEIY3Dve95qvoBDN:b-tne00x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04d55977cc512010c4b6da3383b95133245249b6/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/BUILD.bazel#L19)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

I move this package in previous common-jvm release. Why didn't this cause error?
</blockquote></details>

Since #1070 hasn't been merged yet, this PR is going from common-jvm 0.56.0 to 0.59.0. Your change was introduced in common-jvm 0.57.0.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 19 files at r1, 19 of 19 files at r2, all commit messages.
> Dismissed @YuhongWang-Amazon from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1084)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Review by YuhongWang-Amazon — APPROVED** [review]
> Reviewed 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1084)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1084)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
