### PR TITLE
feat: configure measurement system prober cron job

### PR DESCRIPTION
**Pull request by roaminggypsy**
There are also some reformat changes due to Intellij's Reformat File action.

Not  very sure about 'Current Kingdom Retention Cronjobs' in updating-retention-policies.md.
Do we want to support flags like time-to-live and days-to-liver for the prober?

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1902)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1902)* status: all files reviewed, 3 unresolved discussions (waiting on @roaminggypsy)

___
*[`docs/gke/kingdom-deployment.md` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1902#-OB1i-eU8eFJr4BscEz6:-OB1i-eU8eFJr4BscEz7:bpx34dd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33ed1823cb90cd732b146a1c6cd7d559c498c513/docs/gke/kingdom-deployment.md#L152)):*
> ```Markdown
>    to the Kingdom, including:
> 
>     * All Duchies
> ```

Unrelated and unintended formatting changes. e.g. the `*` list marker for this unordered list should to line up with the indent level. The number of spaces after the list item marker is chosen to have a 4-space indent at each level.

Googlers have access to an `mdformat` tool to help with this.
___
*[`docs/operations/updating-retention-policies.md` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1902#-OB1k8FV36bmRy_j-SFs:-OB1k8FWDB0H0tvg6Vud:bfamkus) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33ed1823cb90cd732b146a1c6cd7d559c498c513/docs/operations/updating-retention-policies.md#L30)):*
> ```Markdown
> exchanges-deletion-cronjob                40 6 * * *   False   0      10h27m        5h32m
> pending-measurements-cancellation-cronjob 45 * * * *   False   0      22m           5h32m
> measurement-system-prober-cronjob         */30 * * * * False   0      30m           5h32m
> ```

nit: we don't need to cover this here since this CronJob isn't used to enforce retention policies
___
*[`src/main/k8s/kingdom.cue` line 253 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1902#-OB1juX25_Tl7OKEwCbN:-OB1juX25_Tl7OKEwCbO:bxvc790) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33ed1823cb90cd732b146a1c6cd7d559c498c513/src/main/k8s/kingdom.cue#L253)):*
> ```CUE
> 				_kingdom_cert_collection_file_flag,
> 				_kingdomExchangesDaysToLiveFlag,
> 				_kingdomExchangesDryRunRetentionPolicyFlag,
> ```

The prober definitely doesn't have these flags.

Did you test this config in a [local cluster](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/k8s/local/README.md)? Meaning bringing up a local CMMS and seeing that the prober runs correctly?



_Code quote:_
```CUE
				_kingdomExchangesDaysToLiveFlag,
				_kingdomExchangesDryRunRetentionPolicyFlag,
```

**Comment by roaminggypsy** [comment]
reopen as accidentally merged

**Comment by roaminggypsy** [comment]
accidentally closed

**Pull request closed without merging**
