### PR TITLE
Implement StreamEventGroups method for spanner kingdom internal services  

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254)

### CODE REVIEW

**Review by wangyaopw — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj-ukDj7h0HqEm_oShO:-Mj-ukDk0EBt2y1w-YQt:bf59lue) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L62)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     // if (requestFilter.externalMeasurementId != 0L) {
>     //   grpcRequire(requestFilter.externalMeasurementConsumerId != 0L) {
>     //     "external_measurement_consumer_id must be specified if external_measurement_id is
>     // specified"
>     //   }
>     // }
> ```
</details>


is this still needed? uncomment or delete?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj-wTYy5jtYOSmqmY3s:-Mj-wTYy5jtYOSmqmY3t:bpsjvuv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L60)):*
> ```
> conjuncts.add("EventGroups.CreateTime > @${StreamEventGroupParams.CREATED_AFTER}")
> ```

can you add a TODO here? something like `TODO: stop using create_after as a filter.`

If we have multiple items with the same create time, a `create_after` filter won't work.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254)* status: all files reviewed, 7 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj0fiAw9yLMq_c-9lZN:-Mj0fiAw9yLMq_c-9lZO:b3hy6yc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L25)):*
> ```
> StreamEventGroupParams
> ```
nit: Since this is private, you can just call it `Params`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj-wTYy5jtYOSmqmY3s:-Mj0g7BiEnfvnTKWWtHJ:b7cp4q0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L60)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> conjuncts.add("EventGroups.CreateTime > @${StreamEventGroupParams.CREATED_AFTER}")
> ```

can you add a TODO here? something like `TODO: stop using create_after as a filter.`

If we have multiple items with the same create time, a `create_after` filter won't work.
</blockquote></details>

@wangyaopw Since you have the most details, can you file a GH issue that we can reference in TODOs? I know we likely have a defect in Rally, but we should have a publicly-trackable issue for this.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj0gzYm8qWYtgpiGPWY:-Mj0gasdBLfZWFOYkyZH:b-ciom1o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L43)):*
> ```Kotlin
> class EventGroupReader : BaseSpannerReader<EventGroup>() {
>   override val builder = Statement.newBuilder(BASE_SQL)
>   data class Result(val eventGroup: EventGroup, val eventGroupId: Long)
> ```

Unused?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj0gra-4ylKckoFKuTw:-Mj0gra-4ylKckoFKuTx:b-adlotx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L84)):*
> ```Kotlin
>   }
> 
>   //   override suspend fun translate(struct: Struct): Result =
> ```

Same here re: commented code.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj0hAVm8fvBYbEFDLxa:-Mj0hAVm8fvBYbEFDLxb:b-f8k6jk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L102)):*
> ```
> this.
> ```
nit: unnecessary qualification?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj0hIyD2eevzHkOJFnN:-Mj0hIyD2eevzHkOJFnO:b-f8k6jk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L121)):*
> ```
> this.
> ```
nit: unnecessary qualification?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254)* status: all files reviewed, 7 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj-wTYy5jtYOSmqmY3s:-Mj0ph6UEN91Nvq2O9vo:bmvx0ex) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@wangyaopw Since you have the most details, can you file a GH issue that we can reference in TODOs? I know we likely have a defect in Rally, but we should have a publicly-trackable issue for this.
</blockquote></details>

https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/255

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254)* status: all files reviewed, 7 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj0fiAw9yLMq_c-9lZN:-Mj14ej98naa2Mk9h5Cu:bzgs9t5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> StreamEventGroupParams
> ```
nit: Since this is private, you can just call it `Params`.
</blockquote></details>

Ah, I see that there's a redeclaration issue for the same module even if private. The best bet then is to move this into the companion object.

**Review by uakyol — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj-ukDj7h0HqEm_oShO:-Mj13OfT-Ti3jDUCuR8e:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L62)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     // if (requestFilter.externalMeasurementId != 0L) {
>     //   grpcRequire(requestFilter.externalMeasurementConsumerId != 0L) {
>     //     "external_measurement_consumer_id must be specified if external_measurement_id is
>     // specified"
>     //   }
>     // }
> ```

is this still needed? uncomment or delete?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj0fiAw9yLMq_c-9lZN:-Mj13a6p0WbyWd_RmdkZ:brht74q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, I see that there's a redeclaration issue for the same module even if private. The best bet then is to move this into the companion object.
</blockquote></details>

it conflicts with StreamRequisition  Params  "redeclaration: Params" . Assuming this is happening because of same package. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj-wTYy5jtYOSmqmY3s:-Mj15L9-ApOp_2AwKfkv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L60)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/255
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj0gzYm8qWYtgpiGPWY:-Mj149Wt9kqe9JgEa6ZN:b-k73z76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Unused?
</blockquote></details>

thanks
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj0gra-4ylKckoFKuTw:-Mj14FDd9lqk_NRaywZ9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L84)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here re: commented code.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj0fiAw9yLMq_c-9lZN:-Mj1ajR82U5QTdQoS55D:b-ye4bqt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L25)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

it conflicts with StreamRequisition  Params  "redeclaration: Params" . Assuming this is happening because of same package. 
</blockquote></details>

See my above comment noting that and suggesting to move to companion object.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254#-Mj0fiAw9yLMq_c-9lZN:-Mj29BT_9oevc3rXNgIH:b-94bs2r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babe0a782302f32b23bec9e1799d8a13a80e49d1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

See my above comment noting that and suggesting to move to companion object.
</blockquote></details>

ah so sorry, I hadn't seen that, thanks.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @zachcwc)

**Review by uakyol — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @zachcwc)

**Review by uakyol — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 2 of 2 files at r5.
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @zachcwc)

**Review by uakyol — COMMENTED** [review]
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Comment by SanjayVas** [comment]
This is for #103.

**Pull request merged**
