### PR TITLE
cherry pick missing absl transitive dependency

### PR DESCRIPTION
**Pull request by stevenwarejones**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1405)

**Comment by SanjayVas** [comment]
Why do we need this in v0.4.x? Are we planning on cherry-picking another commit that upgrades absl?

**Review by stevenwarejones — COMMENTED** [review]
Two reasons:
1. Best practice to include it directly. 
2. It would be convenient for us to have this so we don't have to patch the code.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1405#-:-NnneEwJ6nj89oFsyXUo:b-gtkl5)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
I'm aware of the best practice, but AFAICT this isn't fixing a bug that exists in 0.4.2. We'll also be releasing 0.5.0 soon.

> It would be convenient for us to have this so we don't have to patch the code.

I'm not sure what you mean here, unless there's some other pending cherry-pick to 0.4.x that depends on this.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1405#-:-NnoJ65gCQQHSeU_ZINN:bm2vpxs)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request closed without merging**
