### PR TITLE
Add utilities for reading/writing a VidIndexMap from/to a file.

### PR DESCRIPTION
**Pull request by kungfucraig**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt` line 135 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-NygbCTK9ySfYXdo9f4i:-NygbCTK9ySfYXdo9f4j:b-3fngdq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67884a4d268b35947ffbe49929d0a8ff6a7d9494/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt#L135)):*
> ```Kotlin
>      *
>      * Overriding the default hash function can cause incompatibilities between EDPs which can lead
>      * to bad measurement. The [hashFunction] is exposed only for testing.
> ```

Make a separate function for testing that exposes the ability to specify the hash function and make its purpose explicit. e.g. `buildForTest`



_Code quote:_
```Kotlin
The [hashFunction] is exposed only for testing.
```
___
*[`src/main/proto/wfa/measurement/eventdataprovider/shareshuffle/vid_index_map_entry.proto` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nyg_jNq0X6gYra7yjfX:-Nyg_jNq0X6gYra7yjfY:bwtlchv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67884a4d268b35947ffbe49929d0a8ff6a7d9494/src/main/proto/wfa/measurement/eventdataprovider/shareshuffle/vid_index_map_entry.proto#L24)):*
> ```proto
> 
> // An entry in a VidIndexMap
> message VidIndexMapEntry {
> ```

Why not use a field with a standard protobuf map type? e.g. `map<int64, VidIndexValue>`

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt` line 135 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-NygbCTK9ySfYXdo9f4i:-Nz-fYwJ7VJ6vy_GNs4c:b-bw8e14) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67884a4d268b35947ffbe49929d0a8ff6a7d9494/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt#L135)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Make a separate function for testing that exposes the ability to specify the hash function and make its purpose explicit. e.g. `buildForTest`
</blockquote></details>

Updated.
___
*[`src/main/proto/wfa/measurement/eventdataprovider/shareshuffle/vid_index_map_entry.proto` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nyg_jNq0X6gYra7yjfX:-Nz-fjuXCAUOauhk6pl7:b-rrctcj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67884a4d268b35947ffbe49929d0a8ff6a7d9494/src/main/proto/wfa/measurement/eventdataprovider/shareshuffle/vid_index_map_entry.proto#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why not use a field with a standard protobuf map type? e.g. `map<int64, VidIndexValue>`
</blockquote></details>

Thanks for this comment. It made me realize the build function taking the Map was not quite right.

This message helps support serialization (e.g. to a CSV or Riegeli file) and as such we'd want to be able to stream the file row by row.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt` line 116 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nz03Ms1EM6P_efIl_9Z:-Nz03Ms1EM6P_efIl_9_:b-kxf8gg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f85671cbc7030cc154a5d491d0042fa34d4c20f4/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt#L116)):*
> ```Kotlin
>      *
>      * @param[populationSpec] The [PopulationSpec] represented by this map
>      * @param [hashFunction] The hash function to use for hashing VIDs.
> ```

comments needs updating

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt` line 116 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nz03Ms1EM6P_efIl_9Z:-Nz0XuV88Pq5HLDjTM_C:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f85671cbc7030cc154a5d491d0042fa34d4c20f4/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt#L116)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

comments needs updating
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt` line 137 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nz3bJMT-BaiR6YF5zfj:-Nz3bJMT-BaiR6YF5zfk:b-wqqwzc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/38d5e54b8b392b4c640dc2443846420bb6474bc3/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt#L137)):*
> ```Kotlin
>     fun build(
>       populationSpec: PopulationSpec,
>       indexMapEntries: Sequence<VidIndexMapEntry>,
> ```

wdyt about having this accept a Flow rather than a Sequence?
___
*[`src/main/proto/wfa/measurement/eventdataprovider/shareshuffle/vid_index_map_entry.proto` line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nz3beKJ1zBO2QiYX99b:-Nz3beKJ1zBO2QiYX99c:b-b97h64) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/38d5e54b8b392b4c640dc2443846420bb6474bc3/src/main/proto/wfa/measurement/eventdataprovider/shareshuffle/vid_index_map_entry.proto#L31)):*
> ```proto
> 
>   // The index of the VID
>   int32 index = 2;
> ```

maybe put a note that this impl only supports up to 2B populations

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt` line 137 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nz3bJMT-BaiR6YF5zfj:-Nz3kAiQ5xBPWyK9VSiQ:b80nbri) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/38d5e54b8b392b4c640dc2443846420bb6474bc3/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt#L137)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

wdyt about having this accept a Flow rather than a Sequence?
</blockquote></details>

Sounds good. Thanks! 
___
*[`src/main/proto/wfa/measurement/eventdataprovider/shareshuffle/vid_index_map_entry.proto` line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nz3beKJ1zBO2QiYX99b:-Nz3jZF72Xt7pZmwMbFk:b7bqfc3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/38d5e54b8b392b4c640dc2443846420bb6474bc3/src/main/proto/wfa/measurement/eventdataprovider/shareshuffle/vid_index_map_entry.proto#L31)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

maybe put a note that this impl only supports up to 2B populations
</blockquote></details>

I added a comment at the message level.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/eventdataprovider/shareshuffle/vid_index_map_entry.proto` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nyg_jNq0X6gYra7yjfX:-NzZxMFcDJ48SqnTWbEM:bptiav2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67884a4d268b35947ffbe49929d0a8ff6a7d9494/src/main/proto/wfa/measurement/eventdataprovider/shareshuffle/vid_index_map_entry.proto#L24)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Thanks for this comment. It made me realize the build function taking the Map was not quite right.

This message helps support serialization (e.g. to a CSV or Riegeli file) and as such we'd want to be able to stream the file row by row.
</blockquote></details>

Using a map shouldn't preclude row streaming. A protobuf map is binary equivalent to the following structure: https://protobuf.dev/programming-guides/proto3/#backwards

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/eventdataprovider/shareshuffle/vid_index_map_entry.proto` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nyg_jNq0X6gYra7yjfX:-Nz_6h4V1f-MqSmMDk8l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67884a4d268b35947ffbe49929d0a8ff6a7d9494/src/main/proto/wfa/measurement/eventdataprovider/shareshuffle/vid_index_map_entry.proto#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Using a map shouldn't preclude row streaming. A protobuf map is binary equivalent to the following structure: https://protobuf.dev/programming-guides/proto3/#backwards
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt` line 102 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nz_9Cy840v4ShMqu7X2:-Nz_9Cy840v4ShMqu7X3:b-57klc1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/745b044b3b410e0d5ace368f4f239fd85312e3cc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt#L102)):*
> ```Kotlin
>   companion object {
>     /** A data class for a VID and its hash value. */
>     data class VidAndHash(val vid: Long, val hash: Long) : Comparable<VidAndHash> {
> ```

nit: I don't think this needs to be defined in the companion object. Can define it just inside the class.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt` line 112 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nz_9hx5BAk4UnzAPMx8:-Nz_9hx5BAk4UnzAPMx9:bn05zd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/745b044b3b410e0d5ace368f4f239fd85312e3cc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt#L112)):*
> ```Kotlin
>      * golden ratio) added to the date this value was created.
>      */
>     private val salt = (1_618_033L + 20_240_417L).toByteString(ByteOrder.BIG_ENDIAN)
> ```

CONST_CASE. This is a constant, just not a compile-time constant (i.e. cannot use the `const` keyword)



_Suggestion:_
```Kotlin
SALT
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt` line 184 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nz_AZ-h63pkdUyWJCPi:-Nz_AZ-h63pkdUyWJCPj:b-ogpi5j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/745b044b3b410e0d5ace368f4f239fd85312e3cc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt#L184)):*
> ```Kotlin
>           }
>         }
>       }
> ```

nit: I think this can be written more idiomatically



_Suggestion:_
```Kotlin
      val vidsNotInIndexMap = populationRanges.flatMap { range ->
        range.filter { vid ->
          !indexMap.containsKey(vid) &&
              vidsNotInPopulationSpec.size <
                InconsistentIndexMapAndPopulationSpecException.MAX_LIST_SIZE
        }
      }
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt` line 217 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nz_CMfj-35uS7O36-q4:-Nz_BiBH-jdRWS_PCoEy:bqqc2ta) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/745b044b3b410e0d5ace368f4f239fd85312e3cc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt#L217)):*
> ```Kotlin
>      * function allows the client to specify the VID hash function. This function is exposed for
>      * testing and should not be used by client code.
>      */
> ```

nit: add `@VisibleForTesting` annotation

org.jetbrains.annotations.VisibleForTesting

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt` line 112 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nz_9hx5BAk4UnzAPMx8:-Nzcqr7y4csDZtfDiZa3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/745b044b3b410e0d5ace368f4f239fd85312e3cc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt#L112)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

CONST_CASE. This is a constant, just not a compile-time constant (i.e. cannot use the `const` keyword)
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt` line 184 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631#-Nz_AZ-h63pkdUyWJCPi:-Nzco7Ni4k1SGJ3kPjvp:b-hay2ib) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/745b044b3b410e0d5ace368f4f239fd85312e3cc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/InMemoryVidIndexMap.kt#L184)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I think this can be written more idiomatically
</blockquote></details>

Thanks!

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1631)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Pull request merged**
