### PR TITLE
PBM api should be suspended and Backing Store test should not impose in transaction write - read ability

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645)

### CODE REVIEW

**Review by matthewclegg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 228 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645#-N8R19XxCCKnYzM4pKTX:-N8R19XxCCKnYzM4pKTY:bun3e0y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88fc466967dbcfb3071d7882379e51b6508dc487/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L228)):*
> ```Kotlin
>       Reference(MEASUREMENT_CONSUMER_ID, "RequisitioId1", false)
>     )
>     assertThat(txContext.findIntersectingBalanceEntries(bucket1).size).isEqualTo(1)
> ```

Just curious, why was this check deleted?
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerTest.kt` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645#-N8R-yjd9JnyB3cBczHX:-N8R-yje0Fx8le3u6Y7U:bqryx9n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/98bcff96a8b2768afef516195de43b50b5ca9089/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerTest.kt#L28)):*
> ```Kotlin
>   @Test
>   fun `Charge works when privacy bucket groups are empty`() =
>     runBlocking<Unit> {
> ```

Just curious, why does this say `runBlocking<Unit> {`, whereas the instances above omit `<Unit>`?
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt` line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645#-N8R0JxY4X1iHIIE3DHs:-N8R0JxY4X1iHIIE3DHt:b3s7r1b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/98bcff96a8b2768afef516195de43b50b5ca9089/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt#L64)):*
> ```Kotlin
>         statement.executeUpdate(
>           """
>           DROP TABLE IF EXISTS LedgerEntries;
> ```

Should this be in a different PR?

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 228 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645#-N8R19XxCCKnYzM4pKTX:-N8YVDzDDXkpVnkFwGmK:b3c60zn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88fc466967dbcfb3071d7882379e51b6508dc487/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L228)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Just curious, why was this check deleted?
</blockquote></details>

It shouldn't have. Thanks for catching this.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerTest.kt` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645#-N8R-yjd9JnyB3cBczHX:-N8YWGxm9o8tuW5UP0dO:b-kv9a8g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/98bcff96a8b2768afef516195de43b50b5ca9089/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerTest.kt#L28)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Just curious, why does this say `runBlocking<Unit> {`, whereas the instances above omit `<Unit>`?
</blockquote></details>

thanks for catching, fixed
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt` line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645#-N8R0JxY4X1iHIIE3DHs:-N8YV_IcBejwACkVK_Pk:b-gsumgg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/98bcff96a8b2768afef516195de43b50b5ca9089/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt#L64)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Should this be in a different PR?
</blockquote></details>

It shouldn't have been changed at all. reverted this. Again, thanks for catching Matthew.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 228 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645#-N8R19XxCCKnYzM4pKTX:-N8YhGOV5S2iJ0r5rjzM:bc685rs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88fc466967dbcfb3071d7882379e51b6508dc487/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L228)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

It shouldn't have. Thanks for catching this.
</blockquote></details>

actually sorry. On second thought, it is deleted on purpose. The same transaction context should not need to read what it wrote. The check is now moved down to a new transaction context.

**Review by duliomatos1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 117 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645#-N8dkehm1djfTBNdR-eG:-N8dkehm1djfTBNdR-eH:b-oe0cw8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a30c251d2059218f1a897206431e8a680c0fdb3d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L117)):*
> ```Kotlin
>   @Test(timeout = 15000)
>   fun `addLedgerEntries as a refund decresases repetitionCount`() = runBlocking {
>     val backingStore = createBackingStore()
> ```

without `.use` the backing store is not being closed.

I've just ported the pbm to MySql and had some one of these tests timing out, closing the backingStore in all tests fixed it.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 163 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645#-N8dlGyLD4GAzh7aeicX:-N8dlGyLD4GAzh7aeicY:b-1g1sz0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a30c251d2059218f1a897206431e8a680c0fdb3d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L163)):*
> ```Kotlin
>       val requisitionId = "RequisitioId1"
>       val otherMeasurementConsumerId = "otherMeasurementConsumerId"
>       val backingStore = createBackingStore()
> ```

ditto about closing the `backingStore`.

If  you think`.use {` is cumbersome to use when you have multiple backingStores, how about a regular try/finally to close?
I would suggest to use either have `.use {` or try/finally at each test in this file for consistency if you agree it's the best approach

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 117 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645#-N8dkehm1djfTBNdR-eG:-N8yQC82EBQ9xhWptcG5:baig0vp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a30c251d2059218f1a897206431e8a680c0fdb3d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L117)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

without `.use` the backing store is not being closed.

I've just ported the pbm to MySql and had some one of these tests timing out, closing the backingStore in all tests fixed it.
</blockquote></details>

thank you Dulio, yes you are definitely right. Thanks for finding this.



_Code quote:_
```Kotlin
addLedgerEntries as a refund decresases repetitionCo
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 163 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645#-N8dlGyLD4GAzh7aeicX:-N8yQyRtC5jOYRrEkxeC:b-yusdj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a30c251d2059218f1a897206431e8a680c0fdb3d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L163)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

ditto about closing the `backingStore`.

If  you think`.use {` is cumbersome to use when you have multiple backingStores, how about a regular try/finally to close?
I would suggest to use either have `.use {` or try/finally at each test in this file for consistency if you agree it's the best approach
</blockquote></details>

.use is perfect. Thanks Dulio for catching this.



_Code quote:_
```Kotlin
addLedgerEntries for different MCs an
```

**Review by duliomatos1 — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 10 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645#-:-N91yR4bEKaOIXttY2Cd:bg7igkv)* status: all files reviewed, 5 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

**Review by uakyol — COMMENTED** [review]
> Reviewed 7 of 10 files at r1, 1 of 3 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645)* status: all files reviewed, 5 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

**Review by uakyol — COMMENTED** [review]
> Dismissed @duliomatos1 and @matthewclegg from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/645)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

**Pull request merged**
