### PR TITLE
Fix resource setup job not respecting service dependencies.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/505)

### CODE REVIEW

**Review by uakyol — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/505)* status: 0 of 1 files reviewed, all discussions resolved

**Review by uakyol — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/505)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by iverson52000 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/505)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariolamassaavedra)

**Review by mariolamassaavedra — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/505)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
