### PR TITLE
refactor: Copy the folder dp consistency from experimental to cmm.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1764)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1764)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @ple13 and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1764#-O4Rw1IF4kFeOKTZLAlz:-O4Rw1IF4kFeOKTZLAm-:bd6mken) (no related file):*
There are extraneous empty commits from the source repo. Did you filter by path?

___

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1764)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1764#-O4Rw1IF4kFeOKTZLAlz:-O4RyP_SD-aWtBDGZejl:b-a6ktq0) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There are extraneous empty commits from the source repo. Did you filter by path?
</blockquote></details>

Yeah, I used the following command to extract all previous commits: `git filter-repo --path dp_consistency/ --force`

___

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1764)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @ple13 and @uakyol)

___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1764#-O4S-D5V4afgm-22-p5W):*
As discussed offline, see if you can manually drop these unrelated commits.



_Code quote:_
```
- c2cd5e0 by Sanjay Vasandani (SanjayVas):
  Initial commit.

  Change-Id: Iced88b6f683a223bed4826f33de88a0c5d155bd1

- c14064f by Eli Fox-Epstein (efoxepstein):
  Initial commit.

  Change-Id: I12c18229ee1d0b4ab99489f76515c852aa9b6360

- d6b66ad by Sanjay Vasandani (SanjayVas):
  Add 'any-sketch/' from commit '0b52e1dbba364362ebfec2b505d43c5827a08693'

  git-subtree-dir: any-sketch
  git-subtree-mainline: 3295ceb9fe9e2703717d2c9d3b5255b0e01d0bdc
  git-subtree-split: 0b52e1dbba364362ebfec2b505d43c5827a08693

- 0d654fd by Sanjay Vasandani (SanjayVas):
  Initial commit

- 2ddb6ee by Sanjay Vasandani (SanjayVas):
  Add 'rules-swig/' from commit 'c207f4e6517bc9491df17d407b561a3916739c1c'

  git-subtree-dir: rules-swig
  git-subtree-mainline: 0f066a9b6ac99a1ecf70d177b77884c298b95aaa
  git-subtree-split: c207f4e6517bc9491df17d407b561a3916739c1c
```
___
*[`-- commits` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1764#-O4S-O_3-1o5QFycMtjP):*
You need to rewrite the commit messages to update these references. git-repo-filter can do this for you.



_Suggestion:_
```
 (world-federation-of-advertisers/experimental#90)
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1764)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @ple13 and @uakyol)

___
*[`-- commits` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1764#-O4S-fqI-q4kj2hFkWYT):*
Do not include merge commits. All of these commits should be rebased on main.



_Code quote:_
```
- 2a849f6 by Phi Hung Le (ple13):
  Merge branch 'main' of ../experimental into lephi-copy-experimental-to-cmm
```

**Pull request closed without merging**
