### PR TITLE
Implement Internal Direct FuilfillRequisiton

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496)

### CODE REVIEW

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 971 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-Mz1Lyyr1z_cjt0kYvEe:-Mz1Lyyr1z_cjt0kYvEf:b-y4ycbi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a535e9ea9c824acc54be151c20cdb1344aa7c292/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L971)):*
> ```Kotlin
> 
>       assertThat(response.parentMeasurement.state)
>         .isEqualTo(Measurement.State.PENDING_PARTICIPANT_CONFIRMATION)
> ```

Should be Measurement.State.SUCCEEDED for direct measurements. Direct measurements skip the duchy related states.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 977 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-Mz1LkKv-w5dsjBa1mDi:-Mz1LkKv-w5dsjBa1mDj:b4dts2y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a535e9ea9c824acc54be151c20cdb1344aa7c292/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L977)):*
> ```Kotlin
>   fun `direct fulfillRequisition thorws NOT_FOUND if requisition not found`() = runBlocking {
>     val provider = population.createDataProvider(dataServices.dataProvidersService)
>     val measurement =
> ```

nit: measurement variable is unused here
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 988 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-Mz1LaTHBW7DUUZV1fwd:-Mz1LaTI6UtCS-vWcuaC:b-d4si86) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a535e9ea9c824acc54be151c20cdb1344aa7c292/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L988)):*
> ```Kotlin
>       )
> 
>     val nonExistantExternalRequisitionId = idGenerator.generateExternalId()
> ```

nit: nonExistant should be nonExistent.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-Mz2HLwT86YKE4mWmcwZ:-Mz2HLwT86YKE4mWmcw_:b-kwzcbh) (no related file):*
Waiting for LGTM from Tristan before taking a pass.

---

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496)* status: all files reviewed, 8 unresolved discussions (waiting on @renjiezh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt, line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGgzDJCPgzQaC6Wj6V:-MzGgzDK-a2WCwOarwPs:bb8jc41) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt#L97)):*
> ```Kotlin
>         }
>         FulfillRequisitionRequest.ParamsCase.DIRECT_PARAMS -> {
>           grpcRequire(!directParams.encryptedData.isEmpty) { "encrypted_data is empty" }
> ```

nit: keep language consistent. Use "not specified" like the other messages



_Code quote:_
```Kotlin
is empty
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGiOB77QTgPfw6UwDP:-MzGiOB77QTgPfw6UwDQ:b-g2gsuc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt#L87)):*
> ```Kotlin
>       }
> 
>     val fulfillDuchyId = if (request.hasComputedParams()) getFulfillingDuchyId() else null
> ```

nit: fulfilling



_Code quote:_
```Kotlin
fulfill
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGj2KJDoxhk2m2rwD7:-MzGj2KJDoxhk2m2rwD8:bq5o21f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L171)):*
> ```Kotlin
>   }
> 
>   // Create Computation Measurement
> ```

Use KDoc syntax for function documentation.

See https://developer.android.com/kotlin/style-guide#documentation
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGjnxK9S8RSXOcz_6n:-MzGjnxL36x9x77xJm0l:b-tsd4fw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L171)):*
> ```Kotlin
>   }
> 
>   // Create Computation Measurement
> ```

nit: I thought we decided on "computed" rather than "computation"



_Code quote:_
```Kotlin
Computation
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGjFq_5MuTjlibjGI9:-MzGjFq_5MuTjlibjGIA:bsrwqvv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L172)):*
> ```Kotlin
> 
>   // Create Computation Measurement
>   suspend fun createMeasurement(
> ```

Rather than using documentation to distinguish these, rename the function instead so they have parallel names.

Tip: Use [IntelliJ's refactoring tools](https://www.jetbrains.com/help/idea/rename-refactorings.html#invoke-rename-refactoring) to make the renaming less error-prone.



_Code quote:_
```Kotlin
createMeasurement
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 189 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGkCF5AZ1_WTDMGJb1:-MzGkCF5AZ1_WTDMGJb2:b-gdy8pn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L189)):*
> ```Kotlin
>             measurementSpec = ByteString.copyFromUtf8("MeasurementSpec")
>             measurementSpecSignature = ByteString.copyFromUtf8("MeasurementSpec signature")
>             duchyProtocolConfig = duchyProtocolConfig {
> ```

If this is the only difference between the two methods, maybe have a common private `createMeasurement` which takes in the details message? 



_Code quote:_
```Kotlin
            duchyProtocolConfig = duchyProtocolConfig {
              liquidLegionsV2 = DuchyProtocolConfig.LiquidLegionsV2.getDefaultInstance()
            }
            protocolConfig = protocolConfig {
              liquidLegionsV2 = ProtocolConfig.LiquidLegionsV2.getDefaultInstance()
            }
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 201 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGj62kAQeoCYnjW79-:-MzGj62kAQeoCYnjW790:bq5o21f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L201)):*
> ```Kotlin
>   }
> 
>   // Create Computation Measurement
> ```

Use KDoc syntax for function documentation.

See https://developer.android.com/kotlin/style-guide#documentation
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 974 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGkaZv7eQIbfzd-f01:-MzGkaZv7eQIbfzd-f02:b-k6t3e6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L974)):*
> ```Kotlin
> 
>   @Test
>   fun `direct fulfillRequisition thorws NOT_FOUND if requisition not found`() = runBlocking {
> ```

throws



_Code quote:_
```Kotlin
thorws
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGj2KJDoxhk2m2rwD7:-MzH4FjpC5bhvPc5MRDa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L171)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use KDoc syntax for function documentation.

See https://developer.android.com/kotlin/style-guide#documentation
</blockquote></details>

Done.



_Code quote:_
```Kotlin
Create Computation Measurement
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGjFq_5MuTjlibjGI9:-MzH4HAy5LGrQti_q9VZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L172)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rather than using documentation to distinguish these, rename the function instead so they have parallel names.

Tip: Use [IntelliJ's refactoring tools](https://www.jetbrains.com/help/idea/rename-refactorings.html#invoke-rename-refactoring) to make the renaming less error-prone.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 189 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGkCF5AZ1_WTDMGJb1:-MzH4IK92k3OwcT2Qzra:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L189)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If this is the only difference between the two methods, maybe have a common private `createMeasurement` which takes in the details message? 
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 201 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGj62kAQeoCYnjW79-:-MzH4IxUA50ST6S86KxQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L201)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use KDoc syntax for function documentation.

See https://developer.android.com/kotlin/style-guide#documentation
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 974 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzGkaZv7eQIbfzd-f01:-MzH4KWt2Gjuhf9TTYDx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d3ca1ede26de9b67928feaf9ce764bdb007053c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L974)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

throws
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496)* status: all files reviewed, 6 unresolved discussions (waiting on @renjiezh)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 185 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzLYUtnCOnFNiFpsuGI:-MzLYUtnCOnFNiFpsuGJ:b-fhanmv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2466fe4f42abd2a0ba7536c5d3977c4964004a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L185)):*
> ```Kotlin
>           measurementConsumer.certificate.externalCertificateId
>         this.details = details
>         this.dataProviders.putAll(dataProviders)
> ```

`this.dataProviders += dataProviders`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 202 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzLYiljEnHM2kVBJMyQ:-MzLYiljEnHM2kVBJMyR:b9li94e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2466fe4f42abd2a0ba7536c5d3977c4964004a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L202)):*
> ```Kotlin
>         measurementSpecSignature = ByteString.copyFromUtf8("MeasurementSpec signature")
>         duchyProtocolConfig = duchyProtocolConfig {
>           liquidLegionsV2 = DuchyProtocolConfig.LiquidLegionsV2.getDefaultInstance()
> ```

liquidLegionsV2 {}



_Code quote:_
```Kotlin
uchyProtocolConfig.LiquidLegionsV2
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 205 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzLYnkd8WWue1pBM0VR:-MzLYnkd8WWue1pBM0VS:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2466fe4f42abd2a0ba7536c5d3977c4964004a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L205)):*
> ```Kotlin
>         }
>         protocolConfig = protocolConfig {
>           liquidLegionsV2 = ProtocolConfig.LiquidLegionsV2.getDefaultInstance()
> ```

ditto
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 240 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzLYrwY6r99Wchmaxps:-MzLYrwY6r99Wchmaxpt:b4xtfet) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2466fe4f42abd2a0ba7536c5d3977c4964004a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L240)):*
> ```Kotlin
>       MeasurementKt.details {
>         apiVersion = API_VERSION
>         measurementSpec = ByteString.copyFromUtf8("MeasurementSpec")
> ```

nit `"MeasurementSpec".toByteStringUtf8()`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 241 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzLYwdUAZbTphvCFNNv:-MzLYwdUAZbTphvCFNNw:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2466fe4f42abd2a0ba7536c5d3977c4964004a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L241)):*
> ```Kotlin
>         apiVersion = API_VERSION
>         measurementSpec = ByteString.copyFromUtf8("MeasurementSpec")
>         measurementSpecSignature = ByteString.copyFromUtf8("MeasurementSpec signature")
> ```

ditto
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzLYzM68Xp6gCXFvioQ:-MzLYzM68Xp6gCXFvioR:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2466fe4f42abd2a0ba7536c5d3977c4964004a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L68)):*
> ```Kotlin
> private const val NONCE_2 = -7004399847946251733L
> private val EXTERNAL_DUCHY_IDS = listOf("Buck", "Rippon", "Shoaks")
> private val REQUISITION_ENCRYPTED_DATA = ByteString.copyFromUtf8("foo")
> ```

ditto

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 185 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzLYUtnCOnFNiFpsuGI:-MzLmWw4BwdUDhori1vz:b-gmjrxi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2466fe4f42abd2a0ba7536c5d3977c4964004a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L185)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`this.dataProviders += dataProviders`
</blockquote></details>

Cannot use += because `this.dataProviders` is a `DslMap` instead of a normal `Map`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 202 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzLYiljEnHM2kVBJMyQ:-MzLmduB5ZRwPkn94X1t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2466fe4f42abd2a0ba7536c5d3977c4964004a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L202)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

liquidLegionsV2 {}
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 205 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzLYnkd8WWue1pBM0VR:-MzLmeS74T_CAHkYTnrt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2466fe4f42abd2a0ba7536c5d3977c4964004a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L205)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, line 241 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzLYwdUAZbTphvCFNNv:-MzLmfGEE_YfAdl4QQFT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2466fe4f42abd2a0ba7536c5d3977c4964004a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L241)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496#-MzLYzM68Xp6gCXFvioQ:-MzLmfw809I0RC1zUFeO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c2466fe4f42abd2a0ba7536c5d3977c4964004a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L68)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by renjiezh — COMMENTED** [review]
> Reviewed 4 of 8 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

**Review by renjiezh — COMMENTED** [review]
> Dismissed @stevenwarejones from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/496)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
