### PR TITLE
model suite public api

### PR DESCRIPTION
**Pull request by Marco-Premier**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelSuitesService.kt` line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NV5WxeABvTmTcn_RgC-:-NV5WxeABvTmTcn_RgC0:b-lka9af) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96882f259c31188ddc3be46417d9700e5f07024d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelSuitesService.kt#L46)):*
> ```Kotlin
>       return CreateModelSuite(request).execute(client, idGenerator)
>     } catch (e: ModelProviderNotFoundException) {
>       e.throwStatusRuntimeException(Status.NOT_FOUND) { "ModelProvider not found." }
> ```

Missing unit test for this exception.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NV5bdrZ4GtXjP_bqMYj:-NV5bdrZ4GtXjP_bqMYk:b-phjohx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96882f259c31188ddc3be46417d9700e5f07024d/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L78)):*
> ```protobuf
>   message PreviousPageEnd {
>     google.protobuf.Timestamp created_after = 1;
>     fixed64 external_model_suite_id = 2;
> ```

I don't see this external model suite id being used. If you just want to order by create time, then the created_after in the message is enough.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelSuitesServiceTest.kt` line 235 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NV5Zh7zAllZ3eGdUdwn:-NV5Zh7zAllZ3eGdUdwo:brvfcf8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96882f259c31188ddc3be46417d9700e5f07024d/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelSuitesServiceTest.kt#L235)):*
> ```Kotlin
> 
>   @Test
>   fun `getModelSuite returns model suite when data provider caller is found`() {
> ```

Is a measurement consumer principal supposed to be allowed. I don't see a test for it, but the service code doesn't fail for a measurement consumer principal.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelSuitesService.kt` line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NV5WxeABvTmTcn_RgC-:-NV8uMUs8qropBLJcjoY:b-j0u440) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96882f259c31188ddc3be46417d9700e5f07024d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelSuitesService.kt#L46)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Missing unit test for this exception.
</blockquote></details>

thanks, added.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NV5bdrZ4GtXjP_bqMYj:-NV8eM8j19DmGKoCvMrT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96882f259c31188ddc3be46417d9700e5f07024d/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L78)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I don't see this external model suite id being used. If you just want to order by create time, then the created_after in the message is enough.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelSuitesServiceTest.kt` line 235 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NV5Zh7zAllZ3eGdUdwn:-NV8yX5fDXdLLjAZ_xYa:b-elwz90) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96882f259c31188ddc3be46417d9700e5f07024d/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelSuitesServiceTest.kt#L235)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Is a measurement consumer principal supposed to be allowed. I don't see a test for it, but the service code doesn't fail for a measurement consumer principal.
</blockquote></details>

Actually not. Right Only DataProvider and ModelProvider are entitled to consume this API right now.
Fixed the checks and tests.

thank Tristan

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelSuitesService.kt` line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NV5WxeABvTmTcn_RgC-:-NVATBjyA4LrW4lUllkT:b-ykc5xq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96882f259c31188ddc3be46417d9700e5f07024d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelSuitesService.kt#L46)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

thanks, added.
</blockquote></details>

I meant the test for this service.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelSuitesService.kt` line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NV5WxeABvTmTcn_RgC-:-NVAkk0A9B4gZTGiiGGH:b-9h4u0d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96882f259c31188ddc3be46417d9700e5f07024d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelSuitesService.kt#L46)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I meant the test for this service.
</blockquote></details>

Oh my bad! added it now

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 77 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NVArIld-5Q5ZfjpDEl1:-NVAtp1a-CIIMHvKUenw:bxqpq7v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcefc71b1492ecc31bb84abd65680ffe0a075a31/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L77)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We normally need to include the IDs that make up the primary key as part of the previous page end. This is because we need a total ordering so that if a page falls between two entries with the same `create_time` we can unambiguously return the right items on the next page.
</blockquote></details>

This would then mean that the stream implementation needs to be updated to use it.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 77 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NVArIld-5Q5ZfjpDEl1:-NVDtp1N08ws_Vt7bKa4:baepwts) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bcefc71b1492ecc31bb84abd65680ffe0a075a31/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L77)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This would then mean that the stream implementation needs to be updated to use it.
</blockquote></details>

I see the collision problem... I added the ```external_model_suite_id``` to the page_token and updated the stream implementation + tests accordingly

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto` line 44 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NVVHBGfBec9CILUot3q:-NVVHBGfBec9CILUot3r:b-io0d6k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c691f906aa9d76b10de559196a41ca900cf9c6b/src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto#L44)):*
> ```protobuf
>     fixed64 external_model_provider_id = 1;
>     google.protobuf.Timestamp created_after = 2;
>     fixed64 external_model_suite_id = 3;
> ```

Same AfterFilter message here.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 5 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

**Review by jojijac0b — APPROVED** [review]
> Reviewed 6 of 12 files at r1, 3 of 8 files at r4, 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto` line 44 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NVVHBGfBec9CILUot3q:-NVYMuef7L_JZWjMacCu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c691f906aa9d76b10de559196a41ca900cf9c6b/src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto#L44)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Same AfterFilter message here.
</blockquote></details>

Done.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 3 of 5 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r6, 1 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto` line 43 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NV_okDnDuk312xYBXkE:-NV_okDnDuk312xYBXkF:b-ycqsl1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99edb957ec5c2f503b04e28802f9d9165c87308e/src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto#L43)):*
> ```protobuf
>     fixed64 external_model_suite_id = 1;
>     google.protobuf.Timestamp create_time = 2;
>   }
> ```

Technically the external_model_suite_id is only guaranteed to be unique within the context of a single external_model_provider_id. This means that if we end up supporting listing across model providers then this isn't sufficient to give a total ordering and you need to include `external_model_provider_id` as well.

This basically means that your SQL query needs to order by (create_time, external_model_provider_id, external_model_suite_id) as well as comparing on these fields in the WHERE clause.



_Code quote:_
```protobuf
  message AfterFilter {
    fixed64 external_model_suite_id = 1;
    google.protobuf.Timestamp create_time = 2;
  }
```

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 7 of 12 files at r1, 2 of 8 files at r4, 3 of 5 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @jojijac0b, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto` line 43 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NV_okDnDuk312xYBXkE:-NV_so1y1gWzAQKpIfz1:bwpjczo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99edb957ec5c2f503b04e28802f9d9165c87308e/src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Technically the external_model_suite_id is only guaranteed to be unique within the context of a single external_model_provider_id. This means that if we end up supporting listing across model providers then this isn't sufficient to give a total ordering and you need to include `external_model_provider_id` as well.

This basically means that your SQL query needs to order by (create_time, external_model_provider_id, external_model_suite_id) as well as comparing on these fields in the WHERE clause.
</blockquote></details>

Done. I've added external_model_provider_id when ordering elements

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r6, 2 of 3 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelSuites.kt` line 56 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NVan3QgCSmjZeC3LSmh:-NVan3QgCSmjZeC3LSmi:b-stxemb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a174c90bfabd344915e9b03cec2fd1f1cd7ec9cc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelSuites.kt#L56)):*
> ```Kotlin
>           ((ModelSuites.CreateTime  > @${CREATED_AFTER})
>           OR (ModelSuites.CreateTime  = @${CREATED_AFTER}
>           AND ModelSuites.ExternalModelSuiteId > @${EXTERNAL_MODEL_SUITE_ID}))
> ```

This clause also has to change to account for externalModelProviderId.



_Code quote:_
```Kotlin
          ((ModelSuites.CreateTime  > @${CREATED_AFTER})
          OR (ModelSuites.CreateTime  = @${CREATED_AFTER}
          AND ModelSuites.ExternalModelSuiteId > @${EXTERNAL_MODEL_SUITE_ID}))
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 77 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NVaoFFc49KIGTVluykr:-NVaoFFc49KIGTVluyks:b-7o5ix1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a174c90bfabd344915e9b03cec2fd1f1cd7ec9cc/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L77)):*
> ```protobuf
>   fixed64 external_model_provider_id = 2;
>   message PreviousPageEnd {
>     google.protobuf.Timestamp create_time = 1;
> ```

You also need `external_model_provider_id` in PreviousPageEnd. See the comment re: AfterFilter for an explanation.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto` line 43 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NV_okDnDuk312xYBXkE:-NVanYq5BwfpBsdi9Yc1:b-zeih3o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99edb957ec5c2f503b04e28802f9d9165c87308e/src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto#L43)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done. I've added external_model_provider_id when ordering elements
</blockquote></details>

`external_model_provider_id` also needs to be part of `AfterFilter. Basically the `external_model_provider_id` field in the Filter message filters by that ID. This field may be optional. The field in `AfterFilter` means that you're indicating that the result must be after a given element. All fields in `AfterFilter` are required.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: 8 of 15 files reviewed, 3 unresolved discussions (waiting on @jojijac0b, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelSuites.kt` line 56 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NVan3QgCSmjZeC3LSmh:-NVcwT0C2x8Rgproo1pZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a174c90bfabd344915e9b03cec2fd1f1cd7ec9cc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelSuites.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This clause also has to change to account for externalModelProviderId.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 77 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NVaoFFc49KIGTVluykr:-NVcwSLCA7mqd6exEAQA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a174c90bfabd344915e9b03cec2fd1f1cd7ec9cc/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L77)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You also need `external_model_provider_id` in PreviousPageEnd. See the comment re: AfterFilter for an explanation.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto` line 43 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NV_okDnDuk312xYBXkE:-NVcwNwP8w3b2WMt5Oax:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99edb957ec5c2f503b04e28802f9d9165c87308e/src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`external_model_provider_id` also needs to be part of `AfterFilter. Basically the `external_model_provider_id` field in the Filter message filters by that ID. This field may be optional. The field in `AfterFilter` means that you're indicating that the result must be after a given element. All fields in `AfterFilter` are required.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 7 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 77 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NVfyGWB8940_ZqUPXAU:-NVfyGWB8940_ZqUPXAV:bijrnpr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d9d1149e144335a550ee7be32e8aa3d048f8376c/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L77)):*
> ```protobuf
>   fixed64 external_model_provider_id = 2;
>   message PreviousPageEnd {
>     google.protobuf.Timestamp create_time = 1;
> ```

nit: rearrange fields by sort order
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto` line 41 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993#-NVfyLEB1oThP4W8Q_fG:-NVfyLEB1oThP4W8Q_fH:bijrnpr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d9d1149e144335a550ee7be32e8aa3d048f8376c/src/main/proto/wfa/measurement/internal/kingdom/model_suites_service.proto#L41)):*
> ```protobuf
> message StreamModelSuitesRequest {
>   message AfterFilter {
>     fixed64 external_model_suite_id = 1;
> ```

nit: rearrange fields by sort order

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 4 of 7 files at r10, 1 of 1 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/993)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
