### PR TITLE
Implement CartesianSyntheticEventGroupSpecRecipe

### PR DESCRIPTION
**Pull request by uakyol**
This PR implements a spec called `CartesianSyntheticEventGroupSpecRecipe` that specifies ratios for population and non population dimensions that is converted into a SyntheticEventGroupSpec by independently applying these ratios.

This allows a considerably more complex synthetic data spec to be defined that will be used in EDP integrations and provide a realistic unique reach & frequency

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @uakyol)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 194 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq3YAHj8qhSr_Yf2gUo:-Nq3YAHj8qhSr_Yf2gUp:b2e2ag1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f9c596d8a4ee60e2c741fb371db5a72f7239e1/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L194)):*
> ```proto
>     // Value of the non_population_field.
>     FieldValue field_value = 2;
>     // Ratio of this field value for this dimension. Must sum up to 1 for specs
> ```

Rather than having an implicit relationship between specs with the same field name, make this explicit by repeating the (field_value, ratio) structure.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 212 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq3YR1g46khF1ZqmaNh:-Nq3YR1g46khF1ZqmaNi:b-rjszdf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f9c596d8a4ee60e2c741fb371db5a72f7239e1/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L212)):*
> ```proto
>     // impressions.
>     int64 total_reach = 2;
>     // Each FrequencyDimensionSpec must have a unique frequency.
> ```

Use protobuf maps so the uniqueness is enforced.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 194 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq3YAHj8qhSr_Yf2gUo:-Nq3o_T5AXtWHDDiAbmV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f9c596d8a4ee60e2c741fb371db5a72f7239e1/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L194)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rather than having an implicit relationship between specs with the same field name, make this explicit by repeating the (field_value, ratio) structure.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 212 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq3YR1g46khF1ZqmaNh:-Nq3o_wq2IZtx3tx4gAD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f9c596d8a4ee60e2c741fb371db5a72f7239e1/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L212)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use protobuf maps so the uniqueness is enforced.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @uakyol)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 191 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq3w5Mt2gIwooUFVkxL:-Nq3w5Mt2gIwooUFVkxM:bqpu45) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9082ad8d1344ff270d62601384c6b2df64d71602/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L191)):*
> ```proto
>       float ratio = 3;
>     }
>     // Ratios in these fields must sum up to 1.
> ```

Is this true? I thought they just needed to sum up to a value <=1.



_Code quote:_
```proto
must sum up to 1
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 210 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq3wHsIEtjzH4sweLQo:-Nq3wHsIEtjzH4sweLQp:bp2n3vh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9082ad8d1344ff270d62601384c6b2df64d71602/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L210)):*
> ```proto
>     // A map of frequencies to their values ratios. Ratios must sum up to 1.
>     map<int64, float> frequency_ratios = 3;
>     // Each NonPopulationDimension must have a unique field_name.
> ```

This should also be a map. Extract the "value" part of NonPopulationDimensionSpec to a message and have the field name be the key. This enforces the uniqueness on field names.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 191 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq3w5Mt2gIwooUFVkxL:-Nq4-gwQ3XR49sfz90XV:b-io5wdu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9082ad8d1344ff270d62601384c6b2df64d71602/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L191)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this true? I thought they just needed to sum up to a value <=1.
</blockquote></details>

Yes, they have to sum up to 1. For example, for age, if you specify 18_25 and 65+ and specify both to be 0.5, then the generated dataset will have half 18_25 and half 65+ . If they don't sum up to 1, we won't know what how to distribute the data in age dimension. 
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 210 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq3wHsIEtjzH4sweLQo:-Nq40H4L1c8jeNc9zyD8:bt1t5c8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9082ad8d1344ff270d62601384c6b2df64d71602/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L210)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should also be a map. Extract the "value" part of NonPopulationDimensionSpec to a message and have the field name be the key. This enforces the uniqueness on field names.
</blockquote></details>

The "value" part of the NonPopulationDimensionSpec is a repeated FieldValueRatio . Are you suggesting to wrap this repeated field in another message type?

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 210 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq3wHsIEtjzH4sweLQo:-Nq485DP4C1gZXPsCJAt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9082ad8d1344ff270d62601384c6b2df64d71602/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L210)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, instead of the current `NonPopulationDimensionSpec` message. Right now that message is effectively a whole map entry. This needs to be split into a key and value, where the key is a string and the value is a message.
</blockquote></details>

Done.

**Review by kungfucraig — APPROVED** [review]
The data format looks good. I did not review the Kotlin code in detail, and will leave that for @SanjayVas .

> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-:-Nq4Wrbo0AXcFHfx8WEB:b8bhis2)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt` line 264 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4qn4R6yFuIILxU-nE:-Nq4qn4R6yFuIILxU-nF:bfcrgk0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt#L264)):*
> ```Kotlin
>  * [SyntheticPopulationSpec].
>  *
>  * For each dateSpec in [the CartesianSyntheticEventGroupSpecRecipe];
> ```

Shouldn't this be in the protobuf definition? Again, the same requirements of being deterministic and language-agnostic apply to `CartesianSyntheticEventGroupSpecRecipe` as to `SyntheticEventGroupSpec`, so the protobuf definition should have all the information needed to correctly implement this.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt` line 287 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4rBcL1qc8Ndwvs3Zo:-Nq4rBcL1qc8Ndwvs3Zp:b-yur34e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt#L287)):*
> ```Kotlin
>  *   frequency or nonpolation dimensions that don't sum up to 1 in thier ratios.
>  */
> fun CartesianSyntheticEventGroupSpecRecipe.toSyntheticEventGroupSpec(
> ```

How does this wire up to EdpSimulator? Do we check whether the EventGroup metadata contains this recipe instead of a `SyntheticEventGroupSpec` and act accordingly? Is that going to be in a follow-up PR?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt` line 315 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4s7IfC4Yixl2b5P4u:-Nq4s7IfC4Yixl2b5P4v:bdmscx5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt#L315)):*
> ```Kotlin
>       }
> 
>       val groupedNonPopulationDimensionSpecs =
> ```

This is basically converting from a grouped structure to a flattened one and then re-grouping them. Is that necessary?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt` line 333 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4surqC7e15WR186TR:-Nq4surqC7e15WR186TS:b-fmix5f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt#L333)):*
> ```Kotlin
>         groupedNonPopulationDimensionSpecs
>           .map { (_, group) -> group }
>           .fold(listOf(emptyList<NonPopulationDimension>())) { acc, inner ->
> ```

nit: this seems unnecessarily "clever" compared to a simple nested loop
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 184 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4pdTt9ySE1bmLUJVs:-Nq4pdTt9ySE1bmLUJVt:b4s4nog) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L184)):*
> ```proto
>     message FieldValueRatio {
>       // Value of the non_population_field.
>       FieldValue field_value = 2;
> ```

These can be renumbered since this message hasn't been used/merged.

`field_value = 1`, `ratio = 2`, and `field_value_ratios = 1`
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 207 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4qKDLD0Z6XtwXysvM:-Nq4qKDLD0Z6XtwXysvN:bieexik) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L207)):*
> ```proto
>     // A map of frequencies to their values ratios. Ratios must sum up to 1.
>     map<int64, float> frequency_ratios = 3;
>     // A map of non population dimension names to their specs.
> ```

nit: these aren't dimension names, but rather items from `non_population_fields`.



_Suggestion:_
```proto
A map of `NonPopulationDimensionSpec` keyed by field from `non_population_fields` in the corresponding `PopulationSpec`.
```

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt` line 264 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4qn4R6yFuIILxU-nE:-Nq8SuR6DwcpAbD7v2MJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt#L264)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this be in the protobuf definition? Again, the same requirements of being deterministic and language-agnostic apply to `CartesianSyntheticEventGroupSpecRecipe` as to `SyntheticEventGroupSpec`, so the protobuf definition should have all the information needed to correctly implement this.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt` line 287 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4rBcL1qc8Ndwvs3Zo:-Nq8JD8A4IgUdQXvXS85:bcb08fo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt#L287)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

How does this wire up to EdpSimulator? Do we check whether the EventGroup metadata contains this recipe instead of a `SyntheticEventGroupSpec` and act accordingly? Is that going to be in a follow-up PR?
</blockquote></details>

yes, that is the plan. I'll implement that with an example in a follow up PR 
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt` line 315 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4s7IfC4Yixl2b5P4u:-Nq8P9qIEdWGK8Fk9ypB:bi5hikt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt#L315)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is basically converting from a grouped structure to a flattened one and then re-grouping them. Is that necessary?
</blockquote></details>

there are different ways to do this and while this seems unnecessary work, I find this to be the most readable. We are trying to take the cartesian product of a list of lists, and I wanted each list to have a clean list of Objects.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt` line 333 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4surqC7e15WR186TR:-Nq8PSNiEYyNEHgC_rxy:bpdzixr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt#L333)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: this seems unnecessarily "clever" compared to a simple nested loop
</blockquote></details>

I agree, but unfortunately, since the number of `NonPopulationDimensionSpec`s are dynamic, we can't just  write a couple of for loops. The best we can do is a more readable recursive approach. I implemented it. Let me know if this looks better or if you have a better idea. I can also revert back to the one before
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 184 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4pdTt9ySE1bmLUJVs:-Nq8JOIv3GQlK6Z_KT94:b-k73z76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L184)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These can be renumbered since this message hasn't been used/merged.

`field_value = 1`, `ratio = 2`, and `field_value_ratios = 1`
</blockquote></details>

thanks
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto` line 207 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4qKDLD0Z6XtwXysvM:-Nq8JZRm3Y7ca_0YvPg6:b-1cyu7w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto#L207)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: these aren't dimension names, but rather items from `non_population_fields`.
</blockquote></details>

thank you

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt` line 333 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465#-Nq4surqC7e15WR186TR:-NqEBHHO6zm76g74ogZ_:bg330ig) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c684bdda3714e63cfee2df51fef74e1a3ff036cd/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt#L333)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I agree, but unfortunately, since the number of `NonPopulationDimensionSpec`s are dynamic, we can't just  write a couple of for loops. The best we can do is a more readable recursive approach. I implemented it. Let me know if this looks better or if you have a better idea. I can also revert back to the one before
</blockquote></details>

In that case, the original looks more readable.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 1 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1465)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Pull request merged**
