### PR TITLE
feat: implement deletePrincipal and lookupPrincipal

### PR DESCRIPTION
**Pull request by roaminggypsy**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970)* status: all files reviewed, 5 unresolved discussions (waiting on @roaminggypsy)

___
*[`src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt` line 176 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGxqun8UJ-qYH-gi24:-OEGxqun8UJ-qYH-gi25:bzat3oo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt#L176)):*
> ```Kotlin
>   )
> 
> class PrincipalNotFoundForUserException(cause: Throwable? = null) :
> ```

Include the issuer and subject
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt` line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGxvGd-0YItmDNZ2eK:-OEGxvGd-0YItmDNZ2eL:b32oq0j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt#L184)):*
> ```Kotlin
>   )
> 
> class PrincipalNotFoundForTlsClientException(cause: Throwable? = null) :
> ```

Include the AKID string. You can get this from the internal service exception, meaning you'll want to add a companion object that implements the `Factory` interface defined in this file.
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt` line 177 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGy_o2CbZjgpoOHuZe:-OEGy_o2CbZjgpoOHuZf:b-lklezt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt#L177)):*
> ```Kotlin
>           PrincipalNotFoundException(request.name, e)
>             .asStatusRuntimeException(Status.Code.NOT_FOUND)
>         InternalErrors.Reason.PRINCIPAL_TYPE_NOT_SUPPORTED ->
> ```

nit: you can save a backend call by checking this condition first. Then you don't need to handle it explicitly since you don't expect to ever get it from the backend.
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt` line 212 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGz1EY9wVl2vX-4c8R:-OEGz1EY9wVl2vX-4c8S:b-ngy9qz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt#L212)):*
> ```Kotlin
>     }
> 
>     if (request.lookupKeyCase == LookupPrincipalRequest.LookupKeyCase.USER) {
> ```

Do these checks in the `when` above
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt` line 224 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGz6LJEarIlTe1HSaV:-OEGz6LJEarIlTe1HSaW:b-ngy9qz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt#L224)):*
> ```Kotlin
>     }
> 
>     if (request.lookupKeyCase == LookupPrincipalRequest.LookupKeyCase.TLS_CLIENT) {
> ```

Do these checks in the `when` above

**Review by roaminggypsy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt` line 176 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGxqun8UJ-qYH-gi24:-OEL8CmU6phs08HJre7U:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt#L176)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Include the issuer and subject
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt` line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGxvGd-0YItmDNZ2eK:-OELgF5m7OUsNmqB9Lox:b-jg8jvl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt#L184)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Include the AKID string. You can get this from the internal service exception, meaning you'll want to add a companion object that implements the `Factory` interface defined in this file.
</blockquote></details>

Done.

But in the lookupPrincipal impl, we are still passing akid from the request right?
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt` line 177 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGy_o2CbZjgpoOHuZe:-OELkw19CjkJCmbD_OQP:bir4xbv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt#L177)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: you can save a backend call by checking this condition first. Then you don't need to handle it explicitly since you don't expect to ever get it from the backend.
</blockquote></details>

deletePrincipal request only has a name field, it does not have type info. The only way to check the condition would be call lookupPrincipal and check the type before calling deletePrincipal? but that does not sound like saving a backend call (since lookupPrincipal is called)
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt` line 212 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGz1EY9wVl2vX-4c8R:-OELgrwo4ex1rq3xz1rb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt#L212)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do these checks in the `when` above
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt` line 224 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGz6LJEarIlTe1HSaV:-OELgs8aA2zL98AyvsP1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt#L224)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do these checks in the `when` above
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970)* status: all files reviewed, 1 unresolved discussion (waiting on @roaminggypsy)

___
*[`src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt` line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGxvGd-0YItmDNZ2eK:-OELoQXD2TKr8DFaDPf3:b-jvc1mr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt#L184)):*
<details><summary><i>Previously, roaminggypsy (Lin) wrote…</i></summary><blockquote>

Done.

But in the lookupPrincipal impl, we are still passing akid from the request right?
</blockquote></details>

Yes, but the internal exception has it formatted as hex bytes. We want to just use that formatted string rather than reformatting it here.
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt` line 177 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGy_o2CbZjgpoOHuZe:-OELoXVPAkYGbkT3qDQv:b6o6uvm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt#L177)):*
<details><summary><i>Previously, roaminggypsy (Lin) wrote…</i></summary><blockquote>

deletePrincipal request only has a name field, it does not have type info. The only way to check the condition would be call lookupPrincipal and check the type before calling deletePrincipal? but that does not sound like saving a backend call (since lookupPrincipal is called)
</blockquote></details>

Ah, sorry. Didn't realize this was for delete.

**Review by roaminggypsy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt` line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGxvGd-0YItmDNZ2eK:-OELq-dX07t7lc1AaB9r:bd0g93e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt#L184)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, but the internal exception has it formatted as hex bytes. We want to just use that formatted string rather than reformatting it here.
</blockquote></details>

so this is done?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970)* status: all files reviewed, 1 unresolved discussion (waiting on @roaminggypsy)

___
*[`src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt` line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGxvGd-0YItmDNZ2eK:-OELuS3o-fJFq47SVdck:b-7f94u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt#L184)):*
<details><summary><i>Previously, roaminggypsy (Lin) wrote…</i></summary><blockquote>

so this is done?
</blockquote></details>

No, because you're calling the exception constructor directly rather than using `fromInternal`. You need to use the value for the AKID string from the internal exception and *not* convert the value in the request to a string yourself.

One thing you can do to enforce this is to make the exception constructor private.

**Review by roaminggypsy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt` line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970#-OEGxvGd-0YItmDNZ2eK:-OEM5R3_DcougxDTvmXO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/966b75a858932d972e9110a5545c9fe0a41f4d7e/src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt#L184)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No, because you're calling the exception constructor directly rather than using `fromInternal`. You need to use the value for the AKID string from the internal exception and *not* convert the value in the request to a string yourself.

One thing you can do to enforce this is to make the exception constructor private.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1970)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)

**Pull request merged**
