### PR TITLE
Revert "Fix local correctness test by passing in Event Templates to Simulators"

### PR DESCRIPTION
**Pull request by uakyol**
Reverts world-federation-of-advertisers/cross-media-measurement#508

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/511)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/511)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Review by uakyol — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/511)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @uakyol)

**Review by uakyol — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/511)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Review by uakyol — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/511)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Pull request merged**
