### PR TITLE
docs: Add command line of key encryption key generation

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1727)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1727)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`docs/operations/enabling-hmss-mpc-procotol.md` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1727#-O39bqF40qjFrbVkXcLp:-O39bqF523yVUseBP9R2:b-hz47ne) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/337c9ed4fc7fef60a6dd7c76c392182fedb22bf5/docs/operations/enabling-hmss-mpc-procotol.md#L1)):*
> ```Markdown
> # Enabling HMSS MPC Protocol
> ```

Is this meant to be in this PR? It looks unfinished.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1727)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`docs/operations/enabling-hmss-mpc-procotol.md` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1727#-O39bqF40qjFrbVkXcLp:-O39cSwh6-_SkGXpmfpT:bx376hi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/337c9ed4fc7fef60a6dd7c76c392182fedb22bf5/docs/operations/enabling-hmss-mpc-procotol.md#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this meant to be in this PR? It looks unfinished.
</blockquote></details>

Done.
Deleted from this PR.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1727)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1727)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
