### PR TITLE
feat: prober cron job local configuration

### PR DESCRIPTION
**Pull request by roaminggypsy**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935)

**Comment by roaminggypsy** [comment]
Local testing:
image
image

Log:
measurement-system-prober-cronjob-28877781-xmbm9                  0/1     Completed   0               2m41s
measurement-system-prober-cronjob-28877782-cxndb                  0/1     Completed   0               101s
measurement-system-prober-cronjob-28877783-89qfq                  0/1     Completed   0               41s

```
lindreamdeyi@lindreamdeyi:/tmp/cmms$ kubectl logs default-collector-689b9c86d4-wgctg 
2024-11-26T23:17:12.363Z	info	service@v0.99.0/service.go:99	Setting up own telemetry...
2024-11-26T23:17:12.364Z	info	service@v0.99.0/telemetry.go:103	Serving metrics	{"address": ":8888", "level": "Normal"}
2024-11-26T23:17:12.365Z	info	memorylimiter/memorylimiter.go:160	Using percentage memory limiter	{"kind": "processor", "name": "memory_limiter", "pipeline": "metrics", "total_memory_mib": 241773, "limit_percentage": 65, "spike_limit_percentage": 20}
2024-11-26T23:17:12.365Z	info	memorylimiter/memorylimiter.go:77	Memory limiter configured	{"kind": "processor", "name": "memory_limiter", "pipeline": "metrics", "limit_mib": 157152, "spike_limit_mib": 48354, "check_interval": 1}
2024-11-26T23:17:12.370Z	info	service@v0.99.0/service.go:166	Starting otelcol-contrib...	{"Version": "0.99.0", "NumCPU": 128}
2024-11-26T23:17:12.370Z	info	extensions/extensions.go:34	Starting extensions...
2024-11-26T23:17:12.370Z	info	extensions/extensions.go:37	Extension is starting...	{"kind": "extension", "name": "health_check"}
2024-11-26T23:17:12.370Z	info	healthcheckextension@v0.99.0/healthcheckextension.go:35	Starting health_check extension	{"kind": "extension", "name": "health_check", "config": {"Endpoint":"0.0.0.0:13133","TLSSetting":null,"CORS":null,"Auth":null,"MaxRequestBodySize":0,"IncludeMetadata":false,"ResponseHeaders":null,"Path":"/","ResponseBody":null,"CheckCollectorPipeline":{"Enabled":false,"Interval":"5m","ExporterFailureThreshold":5}}}
2024-11-26T23:17:12.370Z	warn	internal@v0.99.0/warning.go:42	Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks. Enable the feature gate to change the default and remove this warning.	{"kind": "extension", "name": "health_check", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks", "feature gate ID": "component.UseLocalHostAsDefaultHost"}
2024-11-26T23:17:12.371Z	info	extensions/extensions.go:52	Extension started.	{"kind": "extension", "name": "health_check"}
2024-11-26T23:17:12.371Z	warn	internal@v0.99.0/warning.go:42	Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks. Enable the feature gate to change the default and remove this warning.	{"kind": "exporter", "data_type": "metrics", "name": "prometheus", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks", "feature gate ID": "component.UseLocalHostAsDefaultHost"}
2024-11-26T23:17:12.371Z	warn	internal@v0.99.0/warning.go:42	Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks. Enable the feature gate to change the default and remove this warning.	{"kind": "receiver", "name": "otlp", "data_type": "metrics", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks", "feature gate ID": "component.UseLocalHostAsDefaultHost"}
2024-11-26T23:17:12.371Z	info	otlpreceiver@v0.99.0/otlp.go:102	Starting GRPC server	{"kind": "receiver", "name": "otlp", "data_type": "metrics", "endpoint": "0.0.0.0:4317"}
2024-11-26T23:17:12.371Z	info	healthcheck/handler.go:132	Health Check state change	{"kind": "extension", "name": "health_check", "status": "ready"}
2024-11-26T23:17:12.371Z	info	service@v0.99.0/service.go:192	Everything is ready. Begin running and processing data.
2024-11-26T23:17:12.371Z	warn	localhostgate/featuregate.go:63	The default endpoints for all servers in components will change to use localhost instead of 0.0.0.0 in a future version. Use the feature gate to preview the new default.	{"feature gate ID": "component.UseLocalHostAsDefaultHost"}



```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935)* status: all files reviewed, 12 unresolved discussions (waiting on @roaminggypsy)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCj6wt_Ee-K21Zqh0Fr:-OCj6wt_Ee-K21Zqh0Fs:bq7fj7h) (no related file):*
Move the extra supporting information such as screenshots and logs from the PR description body to a separate comment. The body of the PR description [becomes the commit message body](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md#pull-request-description).
___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCj9ruc00Nde7Mi5xBP:-OCj9ruc00Nde7Mi5xBQ:bpxvmzh) (no related file):*
Update the PR title so it's clear this only covers the local configuration. You'll need a follow-up PR for the `dev` configuration used for real cloud deployments (i.e. GKE).
___
*[`docs/gke/kingdom-deployment.md` line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCj93I2AtJY3C7D7zI2:-OCj93I3-uK43_QFo6gr:b-ffzo8r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/docs/gke/kingdom-deployment.md#L50)):*
> ```Markdown
>     -   `pending-measurements-cancellation-cronjob`
>     -   `exchanges-deletion-cronjob`
>     -   `measurement-system-prober-cronjob`
> ```

This is not actually part of the Kingdom deployment. It's more of an add-on like metrics. You should have a separate deployment guide similar to https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/metrics-deployment.md

This can be in a separate PR, given that this PR only covers the local configuration.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 108 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCj7_jE00tX0CLC0UyM:-OCj7_jE00tX0CLC0UyN:bblcanv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L108)):*
> ```Kotlin
>       )
>       .build()
>   private val lastTerminalMeasurementTimeUpdateCounter: LongCounter =
> ```

Don't add counters just so that they show up in local Prometheus. Instead, assume the gauges will work in a real cloud environment given that you've manually verified that you can see that metrics are exported when you've deployed the prober in a local cluster.
___
*[`docs/operations/updating-retention-policies.md` line 102 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCj7PUw-dBwwxxn_KpE:-OCj7PUw-dBwwxxn_KpF:b-x2sfn1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/docs/operations/updating-retention-policies.md#L102)):*
> ```Markdown
> 
> ## Appendix
> ```

This file shouldn't be touched by this PR.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/MeasurementSystemProberJob.kt` line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCj8Aet2Bu76yxdN279:-OCj8Aet2Bu76yxdN27A:bnsmtqa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/MeasurementSystemProberJob.kt#L35)):*
> ```Kotlin
> import picocli.CommandLine.Option
> 
> private class KingdomPublicApiFlags {
> ```

nit: just move these options into MeasurementSystemProberFlags since this other flags class is never used elsewhere
___
*[`src/main/k8s/measurement_system_prober.cue` line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCjAjas4eSkka9hoZdA:-OCjAjas4eSkka9hoZdB:bspgdv4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/src/main/k8s/measurement_system_prober.cue#L20)):*
> ```CUE
> 
> #MeasurementSystemProber: {
> 	_mc_name:              string
> ```

nit: normalize on lowerCamelCase for CUE fields in new code

We have inconsistencies in existing code where fields are sometimes defined using lower_snake_case



_Suggestion:_
```CUE
_mcName
```
___
*[`src/main/k8s/measurement_system_prober.cue` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCjCMeOERq6cL5npNQy:-OCjCMeOERq6cL5npNQz:b-6dff2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/src/main/k8s/measurement_system_prober.cue#L36)):*
> ```CUE
> 	_kingdom_tls_cert_file_flag:             "--tls-cert-file=/var/run/secrets/files/kingdom_tls.pem"
> 	_kingdom_tls_key_file_flag:              "--tls-key-file=/var/run/secrets/files/kingdom_tls.key"
> 	_kingdom_cert_collection_file_flag:      "--cert-collection-file=/var/run/secrets/files/all_root_certs.pem"
> ```

Drop "kingdom" from these names. This should also be using the MC's TLS cert/key rather than the Kingdom's.



_Code quote:_
```CUE
	_kingdom_tls_cert_file_flag:             "--tls-cert-file=/var/run/secrets/files/kingdom_tls.pem"
	_kingdom_tls_key_file_flag:              "--tls-key-file=/var/run/secrets/files/kingdom_tls.key"
	_kingdom_cert_collection_file_flag:      "--cert-collection-file=/var/run/secrets/files/all_root_certs.pem"
```
___
*[`src/main/k8s/measurement_system_prober.cue` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCjB65w55nY5UNKgo4F:-OCjB65w55nY5UNKgo4G:br6ryne) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/src/main/k8s/measurement_system_prober.cue#L41)):*
> ```CUE
> 	_debug_verbose_grpc_client_logging_flag: "--debug-verbose-grpc-client-logging=\(_verboseGrpcClientLogging)"
> 
> 	_kingdom_secret_name: string
> ```

This need not be the Kingdom secret, just *some* secret that contains all the expected files



_Suggestion:_
```CUE
_secretName
```
___
*[`src/main/k8s/measurement_system_prober.cue` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCjBNJvCPAqMav5-woV:-OCjBNJvCPAqMav5-woW:bgv3qgs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/src/main/k8s/measurement_system_prober.cue#L41)):*
> ```CUE
> 	_debug_verbose_grpc_client_logging_flag: "--debug-verbose-grpc-client-logging=\(_verboseGrpcClientLogging)"
> 
> 	_kingdom_secret_name: string
> ```

nit: move this up with all the other fields without values (those that need to be specified by the "inheriting" CUE file)
___
*[`src/main/docker/images.bzl` line 69 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCj8nCJ6a2dl9lz-3FA:-OCj8nCJ6a2dl9lz-3FB:b66gi0f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/src/main/docker/images.bzl#L69)):*
> ```Starlark
>         repository = _PREFIX + "/kingdom/pending-measurements-cancellation",
>     ),
>     struct(
> ```

Leave out the "kingdom" from all of the naming for this since it isn't actually part of the Kingdom. Since it just uses the public API, it doesn't even technically *need* to be deployed in the same cluster.
___
*[`src/main/docker/images.bzl` line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCjAazH4URzIbdguNoX:-OCjAazH4URzIbdguNoY:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/src/main/docker/images.bzl#L72)):*
> ```Starlark
>         name = "kingdom_measurement_system_prober_image",
>         image = "//src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job:measurement_system_prober_image",
>         repository = _PREFIX + "/kingdom/measurement-system-prober",
> ```





_Suggestion:_
```Starlark
prober
```

**Comment by roaminggypsy** [comment]
Local testing result:
image
image

Log:
measurement-system-prober-cronjob-28877781-xmbm9                  0/1     Completed   0               2m41s
measurement-system-prober-cronjob-28877782-cxndb                  0/1     Completed   0               101s
measurement-system-prober-cronjob-28877783-89qfq                  0/1     Completed   0               41s

```
lindreamdeyi@lindreamdeyi:/tmp/cmms$ kubectl logs default-collector-689b9c86d4-wgctg 
2024-11-26T23:17:12.363Z	info	service@v0.99.0/service.go:99	Setting up own telemetry...
2024-11-26T23:17:12.364Z	info	service@v0.99.0/telemetry.go:103	Serving metrics	{"address": ":8888", "level": "Normal"}
2024-11-26T23:17:12.365Z	info	memorylimiter/memorylimiter.go:160	Using percentage memory limiter	{"kind": "processor", "name": "memory_limiter", "pipeline": "metrics", "total_memory_mib": 241773, "limit_percentage": 65, "spike_limit_percentage": 20}
2024-11-26T23:17:12.365Z	info	memorylimiter/memorylimiter.go:77	Memory limiter configured	{"kind": "processor", "name": "memory_limiter", "pipeline": "metrics", "limit_mib": 157152, "spike_limit_mib": 48354, "check_interval": 1}
2024-11-26T23:17:12.370Z	info	service@v0.99.0/service.go:166	Starting otelcol-contrib...	{"Version": "0.99.0", "NumCPU": 128}
2024-11-26T23:17:12.370Z	info	extensions/extensions.go:34	Starting extensions...
2024-11-26T23:17:12.370Z	info	extensions/extensions.go:37	Extension is starting...	{"kind": "extension", "name": "health_check"}
2024-11-26T23:17:12.370Z	info	healthcheckextension@v0.99.0/healthcheckextension.go:35	Starting health_check extension	{"kind": "extension", "name": "health_check", "config": {"Endpoint":"0.0.0.0:13133","TLSSetting":null,"CORS":null,"Auth":null,"MaxRequestBodySize":0,"IncludeMetadata":false,"ResponseHeaders":null,"Path":"/","ResponseBody":null,"CheckCollectorPipeline":{"Enabled":false,"Interval":"5m","ExporterFailureThreshold":5}}}
2024-11-26T23:17:12.370Z	warn	internal@v0.99.0/warning.go:42	Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks. Enable the feature gate to change the default and remove this warning.	{"kind": "extension", "name": "health_check", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks", "feature gate ID": "component.UseLocalHostAsDefaultHost"}
2024-11-26T23:17:12.371Z	info	extensions/extensions.go:52	Extension started.	{"kind": "extension", "name": "health_check"}
2024-11-26T23:17:12.371Z	warn	internal@v0.99.0/warning.go:42	Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks. Enable the feature gate to change the default and remove this warning.	{"kind": "exporter", "data_type": "metrics", "name": "prometheus", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks", "feature gate ID": "component.UseLocalHostAsDefaultHost"}
2024-11-26T23:17:12.371Z	warn	internal@v0.99.0/warning.go:42	Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks. Enable the feature gate to change the default and remove this warning.	{"kind": "receiver", "name": "otlp", "data_type": "metrics", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks", "feature gate ID": "component.UseLocalHostAsDefaultHost"}
2024-11-26T23:17:12.371Z	info	otlpreceiver@v0.99.0/otlp.go:102	Starting GRPC server	{"kind": "receiver", "name": "otlp", "data_type": "metrics", "endpoint": "0.0.0.0:4317"}
2024-11-26T23:17:12.371Z	info	healthcheck/handler.go:132	Health Check state change	{"kind": "extension", "name": "health_check", "status": "ready"}
2024-11-26T23:17:12.371Z	info	service@v0.99.0/service.go:192	Everything is ready. Begin running and processing data.
2024-11-26T23:17:12.371Z	warn	localhostgate/featuregate.go:63	The default endpoints for all servers in components will change to use localhost instead of 0.0.0.0 in a future version. Use the feature gate to preview the new default.	{"feature gate ID": "component.UseLocalHostAsDefaultHost"}
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935)* status: all files reviewed, 4 unresolved discussions (waiting on @roaminggypsy)

___
*[`docs/operations/updating-retention-policies.md` line 102 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCj7PUw-dBwwxxn_KpE:-OD8WYaX6rWdnx5zplx6:b4rrfy9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/docs/operations/updating-retention-policies.md#L102)):*
<details><summary><i>Previously, roaminggypsy (Lin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still marked as modified (removing newline character at end)
___
*[`src/main/k8s/measurement_system_prober.cue` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCjB65w55nY5UNKgo4F:-OD8Wqm8EvzROUFN6LvT:b-mtlyvc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/src/main/k8s/measurement_system_prober.cue#L41)):*
<details><summary><i>Previously, roaminggypsy (Lin) wrote…</i></summary><blockquote>

Done. Only changed the name, but the value (SECRET_NAME) provided in local BUILD is still the same

In Local build,  for the "secret_name" value of prober cue dump, I tried MC_CONFIG_SECRET_NAME and TEST_K8S_SETTINGS.mc_config_secret, but cron job was not running normally

Error from server (BadRequest): container "measurement-system-prober-container" in pod "measurement-system-prober-cronjob-28886248-rkhpx" is waiting to start: PodInitializing
</blockquote></details>

Using `SECRET_NAME` from the BUILD file is correct. This is not the `MC_CONFIG_SECRET_NAME`, as that's a different secret holding the MC config for the Reporting server.
___
*[`src/main/k8s/measurement_system_prober.cue` line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OD8X53UCSCPR2z1icBz:-OD8X53UCSCPR2z1icC-:b-klr1gg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d9ce485424dda9930d4e86d5d43fa8ba17a9d08a/src/main/k8s/measurement_system_prober.cue#L32)):*
> ```CUE
> 	_verboseGrpcClientLogging: bool | *false
> 	_kingdomPublicApiTarget:   string
> 	_mcSecretName:             string
> ```

nit: just _secretName



_Suggestion:_
```CUE
_secretName
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/MeasurementSystemProberJob.kt` line 135 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OD8XttCCgVH5x2Qbx8n:-OD8XttCCgVH5x2Qbx8o:b-po4rwc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/684948d04042141c3e99db6ee7aa2f92ff9c9d49/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/MeasurementSystemProberJob.kt#L135)):*
> ```Kotlin
>         flags.kingdomApiServerFlags.internalApiFlags.certHost,
>       )
>       .withVerboseLogging(flags.kingdomApiServerFlags.debugVerboseGrpcClientLogging)
> ```

You probably still want a verbose client logging flag
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 277 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OD8Xajt4IjNaxnnzipJ:-OD8XLeC0t8ESqU8gH7p:b-c8f3pz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d9ce485424dda9930d4e86d5d43fa8ba17a9d08a/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L277)):*
> ```Kotlin
>         }
>       if (response.measurementsList.isNotEmpty()) {
>         return response.measurementsList[0]
> ```

I believe your branch is out-of-date. This code is changed at HEAD to use `listResources`.

**Review by roaminggypsy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`docs/operations/updating-retention-policies.md` line 102 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCj7PUw-dBwwxxn_KpE:-OD8nzSd8zSvtqexJd_C:bgf6vhf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/docs/operations/updating-retention-policies.md#L102)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Still marked as modified (removing newline character at end)
</blockquote></details>

in my IDE, there is no newline character at end. I tried remove and retype this line, but no changes will be detected by git. It's the same line, at least to IDE.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/MeasurementSystemProberJob.kt` line 135 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OD8XttCCgVH5x2Qbx8n:-OD8i1pU2_CMh_zWidtn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/684948d04042141c3e99db6ee7aa2f92ff9c9d49/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/MeasurementSystemProberJob.kt#L135)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You probably still want a verbose client logging flag
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935)* status: all files reviewed, 2 unresolved discussions (waiting on @roaminggypsy)

___
*[`docs/operations/updating-retention-policies.md` line 102 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCj7PUw-dBwwxxn_KpE:-ODCXVaq8bmZLQ69OnGV:bbv6zr4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/docs/operations/updating-retention-policies.md#L102)):*
<details><summary><i>Previously, roaminggypsy (Lin) wrote…</i></summary><blockquote>

in my IDE, there is no newline character at end. I tried remove and retype this line, but no changes will be detected by git. It's the same line, at least to IDE.
</blockquote></details>

What's shown in your IDE is not relevant, especially as it may be hiding or auto-formatting things. It's the Git file status that matters. You can try using the `git reset` command. Something like

```shell
git reset origin/main docs/operations/updating-retention-policies.md
```
___
*[`.github/workflows/scan-images.yml` line 85 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-ODCXS5L-nDCUnNEl2VE:-ODCXS5L-nDCUnNEl2VF:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/411407c9d23233db7c0e654d7fabbeaee15c96e2/.github/workflows/scan-images.yml#L85)):*
> ```YAML
>           - duchy/aws-postgres-internal-server
>           - panel-exchange/forwarded-storage-daemon
>           - kingdom/measurement-system-prober
> ```





_Suggestion:_
```YAML
prober
```

**Review by roaminggypsy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`docs/operations/updating-retention-policies.md` line 102 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-OCj7PUw-dBwwxxn_KpE:-ODD5esO4qnWhGxu_joP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46795000f20c3f4495ca7082746b2a0ff8d1539e/docs/operations/updating-retention-policies.md#L102)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What's shown in your IDE is not relevant, especially as it may be hiding or auto-formatting things. It's the Git file status that matters. You can try using the `git reset` command. Something like

```shell
git reset origin/main docs/operations/updating-retention-policies.md
```
</blockquote></details>

Done.
___
*[`.github/workflows/scan-images.yml` line 85 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935#-ODCXS5L-nDCUnNEl2VE:-ODD3NbDAjVBA4TVyVM-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/411407c9d23233db7c0e654d7fabbeaee15c96e2/.github/workflows/scan-images.yml#L85)):*
> ```YAML
>           - duchy/aws-postgres-internal-server
>           - panel-exchange/forwarded-storage-daemon
>           - kingdom/measurement-system-prober
> ```

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 1 of 7 files at r3, 4 of 8 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1935)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)

**Pull request merged**
