### PR TITLE
Update private key injection with EncryptionKeyPairStore

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637#-N7Y2RSz39fkbLCIj-Wq:-N7Y2RT-0gZtjoo3XPsg:b-cyga02) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6b6a83b4dc791ad8de028d6a4a83fef151fc1b33/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L50)):*
> ```Kotlin
>   private val cmmsEventGroupsStub: EventGroupsCoroutineStub,
>   private val eventGroupsMetadataDescriptorsStub: EventGroupMetadataDescriptorsCoroutineStub,
>   private val measurementConsumerPublicKey: ByteString,
> ```

This comes from the CMMS `EventGroup`. It's not injected here.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637#-N7Y2kJUAI6wZ0AZfHwH:-N7Y2kJUAI6wZ0AZfHwI:b95owak) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6b6a83b4dc791ad8de028d6a4a83fef151fc1b33/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L69)):*
> ```Kotlin
>     val cmmsEventGroups = cmmsListEventGroupResponse.eventGroupsList
>     val encryptionPrivateKey =
>       grpcRequireNotNull(encryptionKeyPairStore.getPrivateKeyHandle(measurementConsumerPublicKey)) {
> ```

This will result in `INVALID_ARGUMENT`, where it should be `FAILED_PRECONDITION`.



_Code quote:_
```Kotlin
grpcRequireNotNull
```

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637#-N7Y2RSz39fkbLCIj-Wq:-N7bDhvg7zaN2xL-vJdk:b-bw8e14) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6b6a83b4dc791ad8de028d6a4a83fef151fc1b33/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This comes from the CMMS `EventGroup`. It's not injected here.
</blockquote></details>

Updated.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637#-N7Y2kJUAI6wZ0AZfHwH:-N7bDk3RBNgWGbCzfpdC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6b6a83b4dc791ad8de028d6a4a83fef151fc1b33/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This will result in `INVALID_ARGUMENT`, where it should be `FAILED_PRECONDITION`.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637#-N7bJjDQ5wHsA0LPHyeG:-N7bJjDQ5wHsA0LPHyeH:buqpzan) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0c066ea7193dca4d44dfc5d535bdc81c8768b0b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L78)):*
> ```Kotlin
>             decryptResult(
>                 it.encryptedMetadata,
>                 runBlocking {
> ```

`runBlocking` should generally only be called to bridge to top-level code (e.g. `main` or a test method). Ensure this is called from suspending code instead (e.g. using a Flow).


```kotlin
      cmmsEventGroups
        .asFlow()
        .map {
          val privateKey: PrivateKeyHandle =
            encryptionKeyPairStore.getPrivateKeyHandle(it.measurementConsumerPublicKey.data)
              ?: failGrpc(Status.FAILED_PRECONDITION) {
                "Public key does not have corresponding private key"
              }
          val serializedMetadata: ByteString = decryptResult(it.encryptedMetadata, privateKey).data
          it.name to CmmsEventGroup.Metadata.parseFrom(serializedMetadata)
        }
        .toList()
        .toMap()
```



_Code quote:_
```Kotlin
runBlocking
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 116 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637#-N7bLrFZ38LCzVfT3VH0:-N7bLrFZ38LCzVfT3VH1:bfy609c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0c066ea7193dca4d44dfc5d535bdc81c8768b0b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L116)):*
> ```Kotlin
> 
>     return listEventGroupsResponse {
>       this.eventGroups += filteredEventGroups.map { it.toEventGroup(encryptionKeyPairStore) }
> ```

You already have the decrypted metadata from the map at this point. You shouldn't need to pass the key store.



_Code quote:_
```Kotlin
encryptionKeyPairStore
```

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637#-N7bJjDQ5wHsA0LPHyeG:-N7bjRyaC5uZzJK0P6NR:b-2jyil1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0c066ea7193dca4d44dfc5d535bdc81c8768b0b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L78)):*
> it.name to CmmsEventGroup.Metadata.parseFrom(serializedMetadata)
It turns out I don't need the runBlocking after all; was a bit of a discrepancy between what Intellij was telling me and how it compiled. I've gone ahead and just removed it.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 116 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637#-N7bLrFZ38LCzVfT3VH0:-N7blKSA4fJObsSXKlNb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0c066ea7193dca4d44dfc5d535bdc81c8768b0b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L116)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You already have the decrypted metadata from the map at this point. You shouldn't need to pass the key store.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 123 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637#-N7bnSBa9BTX-hhEfcre:-N7bnSBa9BTX-hhEfcrf:bx1aklu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a397483bf1822c41f7929710c49caf5c2670d78/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L123)):*
> ```Kotlin
> ): EventGroup {
>   val source = this
>   val cmmsMetadata = parsedEventGroupMetadataMap[name]!!
> ```

nit: `parsedEventGroupMetadataMap.getValue(name)`



_Code quote:_
```Kotlin
parsedEventGroupMetadataMap[name]!!
```

**Review by chipingyeh — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @tristanvuong2021)

**Pull request merged**
