### PR TITLE
Make queries use indexes when getting a Report

### PR DESCRIPTION
**Pull request by tristanvuong2021**
Currently, there are too many scans and joins involving way too many rows.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1643)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1643)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1643#-NzdyE8d-ZQN47w9Cg8o:-NzdyE8d-ZQN47w9Cg8p:b4z3tsz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/51af407cdfc5cc50ab67ed3c219be1fc0c6dad45/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L198)):*
> ```Kotlin
>           FROM
>             MeasurementConsumers
>             JOIN Metrics ON MeasurementConsumers.MeasurementConsumerId = $1
> ```

Ugh, I guess this is fine. The queries should be totally equivalent and the query planner should just be able to figure it out :(

Mind leaving comments to make it clear why the queries are written this way? Otherwise a future author may try to refactor to the more natural query syntax.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1643)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1643#-NzdyE8d-ZQN47w9Cg8o:-NzeO87437fUktf1fLgG:b-ybtf1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6671833a5cc25706f4fc598819eac217af30360/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L198)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ugh, I guess this is fine. The queries should be totally equivalent and the query planner should just be able to figure it out :(

Mind leaving comments to make it clear why the queries are written this way? Otherwise a future author may try to refactor to the more natural query syntax.
</blockquote></details>

Added some comments.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
