### PR TITLE
Implement internal authenticate account.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 15 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366)* status: 15 of 18 files reviewed, 7 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/AccountsServerInterceptor.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moe5lHd9UhUl9kOqDeB:-Moe5lHd9UhUl9kOqDeC:b-neyydt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30c0107f7d2e076c3221062c00670184ccb9b1f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/AccountsServerInterceptor.kt#L29)):*
> ```Kotlin
> import org.wfanet.measurement.internal.kingdom.Account
> 
> /** gRPC [ServerInterceptor] to get [Account] credentials coming in from a request. */
> ```

nit: this is technically getting ID Token credentials for an Account principal
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moe-x2r4SVHpLxZCMBY:-Moe-x2r4SVHpLxZCMBZ:bh0mc69) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30c0107f7d2e076c3221062c00670184ccb9b1f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L47)):*
> ```Kotlin
> import org.wfanet.measurement.tools.calculateRSAThumbprint
> 
> const val REDIRECT_URI = "https://localhost:2048"
> ```

private?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 119 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moe0DEe4o9sfYdRbafB:-Moe0DEe4o9sfYdRbafC:b-lxby29) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30c0107f7d2e076c3221062c00670184ccb9b1f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L119)):*
> ```
> if (parsedValidatedIdToken != null) {
> ```
nit: reduce nesting by putting the smaller condition first and dropping the else branch. e.g.

```
if (parsedValidatedIdToken == null) {
  // Throw exception
}
// read Account
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moe0bKX06sieHrc4zK2:-Moe0bKX06sieHrc4zK3:bo5mptu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30c0107f7d2e076c3221062c00670184ccb9b1f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L144)):*
> ```Kotlin
>   }
> 
>   // TODO: Replace with Tink when new Tink release containing JWT support is released
> ```

Move the TODO into KDoc and reference https://github.com/google/tink/issues/541

See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#todos for the format for TODOs referencing GitHub issues.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 147 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moe0nd10Tjmt2mj5p62:-Moe0nd10Tjmt2mj5p63:b-wv50ek) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30c0107f7d2e076c3221062c00670184ccb9b1f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L147)):*
> ```
>    * Returns the issuer and subject if the idToken is valid and null otherwise. Throws
>    * NullPointerException when required claims are missing.
> ```
NPE should only be used to indicate a programming error. Do we need to differentiate this case, or can it also just return `null`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 178 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moe3F5W4Wa_oW2VRp6L:-Moe3F5W4Wa_oW2VRp6M:bu2vxrp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30c0107f7d2e076c3221062c00670184ccb9b1f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L178)):*
> ```
> MAX_AGE
> ```
Persist the expiration timestamp in DB on write rather than comparing to a constant. This way we can guarantee that we're comparing to the request max age (e.g. if we change the value of the constant).
___
*[src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moe5fHy5_8OpqmiGsUi:-Moe5fHy5_8OpqmiGsUj:bp6x1da) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30c0107f7d2e076c3221062c00670184ccb9b1f7/src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt#L27)):*
> ```
> // TODO: "Replace implementation with Tink Java JWT when it is included in a public release"
> ```
Same here re: Tink TODO

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 147 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moe0nd10Tjmt2mj5p62:-MoeM1oaDup5MSfUQobw:baivj0u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c5d2f0a57bc6057c7845818c1e60755034dc675/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L147)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>    * Returns the issuer and subject if the idToken is valid and null otherwise. Throws
>    * NullPointerException when required claims are missing.
> ```
NPE should only be used to indicate a programming error. Do we need to differentiate this case, or can it also just return `null`?
</blockquote></details>

No need to differentiate. I just went ahead and added explicit checks for possible null values inside validateToken. I could also wrap the inside of validateToken in a try/catch.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366)* status: 10 of 18 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moe-x2r4SVHpLxZCMBY:-MoeLVjW4BR2uuzL7KW6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c5d2f0a57bc6057c7845818c1e60755034dc675/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

private?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moe0bKX06sieHrc4zK2:-MoeLWu-1VsHT3cQ8xmG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c5d2f0a57bc6057c7845818c1e60755034dc675/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L144)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move the TODO into KDoc and reference https://github.com/google/tink/issues/541

See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#todos for the format for TODOs referencing GitHub issues.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 178 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moe3F5W4Wa_oW2VRp6L:-MoeLXlz5YP460wx4nGq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c5d2f0a57bc6057c7845818c1e60755034dc675/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L178)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> MAX_AGE
> ```
Persist the expiration timestamp in DB on write rather than comparing to a constant. This way we can guarantee that we're comparing to the request max age (e.g. if we change the value of the constant).
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moe5fHy5_8OpqmiGsUi:-MoeLZ-tE16wDvwJApXF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c5d2f0a57bc6057c7845818c1e60755034dc675/src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> // TODO: "Replace implementation with Tink Java JWT when it is included in a public release"
> ```
Same here re: Tink TODO
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 18 files at r1, 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366)* status: 15 of 18 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 409 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-MoeOsKt-Lzr0ZChFz1-:-MoeOsKt-Lzr0ZChFz10:bji14lx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/beb4782d70ca9389c9e0ff5cb63d4a518ddb49a4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L409)):*
> ```
> MaxAge INT64 NOT NULL
> ```
We want something like `ExpirationTime TIMESTAMP NOT NULL` so we can know when this row can be deleted.

My initial reading of the OIDC spec was incorrect and this doesn't appear to actually match up to the usage of `max_age`. We in fact don't really care about how long it's been since the user authenticated with the OP, but rather how long of a gap we allow between the public API Authenticate call and using that ID Token for bearer auth. Feel free to drop `max_age` from the request and validation of `auth_time`.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 409 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-MoeOsKt-Lzr0ZChFz1-:-Moellkf3GWMhOSC7PW-:b-ti4jy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/beb4782d70ca9389c9e0ff5cb63d4a518ddb49a4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L409)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> MaxAge INT64 NOT NULL
> ```
We want something like `ExpirationTime TIMESTAMP NOT NULL` so we can know when this row can be deleted.

My initial reading of the OIDC spec was incorrect and this doesn't appear to actually match up to the usage of `max_age`. We in fact don't really care about how long it's been since the user authenticated with the OP, but rather how long of a gap we allow between the public API Authenticate call and using that ID Token for bearer auth. Feel free to drop `max_age` from the request and validation of `auth_time`.
</blockquote></details>

I might want to rename MaxAge, but I added CreationTime and add the two together in the reader to check for expiration.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 409 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-MoeOsKt-Lzr0ZChFz1-:-MofJU6bEExJQ6SRSwAE:b-xh282) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/beb4782d70ca9389c9e0ff5cb63d4a518ddb49a4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L409)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I might want to rename MaxAge, but I added CreationTime and add the two together in the reader to check for expiration.
</blockquote></details>

If you want to do it that way, then have `CreateTime` for consistency with other tables and then something like `ValidSeconds` to be clear on the unit and avoid confusing with OIDC `max_age`.
___
*[src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-MofK9dR7-qm2Vcxt5s-:-MofK9dS0yfUy7o2BgBH:b7lxp2t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33a42951e9c62c9d162e39d6a3bf5a30e11e826d/src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt#L27)):*
> ```Kotlin
> import org.wfanet.measurement.common.crypto.hashSha256
> 
> /**
> ```

Err, this is actually documenting the constant. If you want file-level documentation, just use a normal block comment rather than KDoc (`/*` instead of `/**`)

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366)* status: 14 of 19 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 409 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-MoeOsKt-Lzr0ZChFz1-:-MofNV6R5gRtfVjXZDwX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/beb4782d70ca9389c9e0ff5cb63d4a518ddb49a4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L409)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you want to do it that way, then have `CreateTime` for consistency with other tables and then something like `ValidSeconds` to be clear on the unit and avoid confusing with OIDC `max_age`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-MofK9dR7-qm2Vcxt5s-:-MofNUEnAquHmXCR3z1n:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33a42951e9c62c9d162e39d6a3bf5a30e11e826d/src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Err, this is actually documenting the constant. If you want file-level documentation, just use a normal block comment rather than KDoc (`/*` instead of `/**`)
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-MofK9dR7-qm2Vcxt5s-:-MofUToXB7FxiPPyBFRJ:bbaa5vr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33a42951e9c62c9d162e39d6a3bf5a30e11e826d/src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt#L27)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: still is using KDoc format (starting with `/**`) rather than standard block comment (starting with `/*`). I think you still want this higher up in the file too, like right under the license.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 7 of 18 files at r1, 1 of 6 files at r2, 2 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366)* status: 18 of 19 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/AccountsServiceTest.kt, line 312 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-MoiyRn81EsxE58VSFFZ:-MoiyRn81EsxE58VSFF_:b-wm2hzl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d8fbc6492a3fef8739975f3a79e8af875b493d21/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/AccountsServiceTest.kt#L312)):*
> ```Kotlin
> 
>     assertThat(params.nonce != 0L)
>     assertThat(params.state != 0L)
> ```

check for max age
___
*[src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt, line 99 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moiyfx85Z_AkP5DUT2B:-Moiyfx85Z_AkP5DUT2C:b-tgpujj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d8fbc6492a3fef8739975f3a79e8af875b493d21/src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt#L99)):*
> ```Kotlin
>   }
> 
>   return ""
> ```

shouldn't this just throw an error?

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt, line 99 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-Moiyfx85Z_AkP5DUT2B:-MojEfld63DgDDHgiQ4g:bxxx4gf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be334500ab694c6cfa08d11294508f4879a1c07c/src/main/kotlin/org/wfanet/measurement/tools/SelfIssuedIdToken.kt#L99)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't this just throw an error?
</blockquote></details>

That makes sense.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/AccountsServiceTest.kt, line 312 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366#-MoiyRn81EsxE58VSFFZ:-MojEjAH7_ZV0iqnstxo:b-686lwq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be334500ab694c6cfa08d11294508f4879a1c07c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/AccountsServiceTest.kt#L312)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

check for max age
</blockquote></details>

I actually got rid of max age. @sanjayvas 's goal for max age doesn't actually fit the open id spec so I made some modifications to still have an expiration time, but without using open id's max age. You can see the change in measurement.sdl and OpenIdRequestParamsReader.kt.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366)* status: 12 of 19 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366)* status: 12 of 19 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366)* status: 13 of 19 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 18 files at r1, 1 of 6 files at r2, 1 of 3 files at r7, 1 of 1 files at r8, 1 of 2 files at r9, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
