### PR TITLE
Add Get Report to the BFF

### PR DESCRIPTION
**Pull request by bdomen-ggl**
Adding GetReport to the BFF.
* Update proto message. This was to make it easier for the UI to handle unique and cumulative values.
* Add call to get Reporting Sets. This is to get the tags on the Reporting Sets to identify things like unique or union reporting sets.
* Add call to build a Report in the service. This remaps the backend report to a more UI friendly report.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427)* status: all files reviewed, 5 unresolved discussions (waiting on @bdomen-ggl)

___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/BUILD.bazel` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTPAI86rX-IL_LMuqo:-NoTPAI86rX-IL_LMuqp:b-8zugjv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/BUILD.bazel#L27)):*
> ```Starlark
>     srcs = ["ReportingSetsService.kt"],
>     visibility = [
>         "//experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/deploy/common/server:__subpackages__",
> ```

FYI if you're going to put this visibility on every target in here, you can just put it as the default_visibility in the package declaration



_Code quote:_
```Starlark
        "//experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/deploy/common/server:__subpackages__",
```
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportingSetsService.kt` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTPWk7CKLSGpyhdtuH:-NoTPWk7CKLSGpyhdtuI:bmpsxqu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportingSetsService.kt#L21)):*
> ```Kotlin
> import org.wfanet.measurement.reporting.v2alpha.listReportingSetsRequest
> 
> class ListReportingSetsRequest(
> ```

What is this used for?
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportingSetsService.kt` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTPZYcCr5DuJwKLzxb:-NoTPZYdD_xIjdeOeqJO:b-dauxzj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportingSetsService.kt#L26)):*
> ```Kotlin
> ) {}
> 
> class ReportingSetsService(
> ```

Is this only called internally by the BFF ReportsService, or is it meant to be exposed in the BFF API? If it's the former, just drop it and call the backend stub directly from the BFF ReportsService.
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTPwnY7rz9Bi9YrE6m:-NoTPwnZ8uswLbIQsWPQ:bohccpe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L82)):*
> ```Kotlin
>   override suspend fun getReport(request: GetReportRequest): Report {
>     val backendRequest = getReportRequest { name = request.name }
>     val resp = backendReportsStub.getReport(backendRequest)
> ```

Every gRPC method call site should handle StatusException. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 157 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTR8Rw8Qi2Xb9X19e3:-NoTR8Rw8Qi2Xb9X19e4:b7iz6mz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L157)):*
> ```Kotlin
>       source.name.substring(0, source.name.indexOf("/", source.name.indexOf("/")))
>     val reportingSetsRequest = ListReportingSetsRequest(measurementConsumerName, 1000)
>     val reportingSets = reportingSetsService.ListReportingSets(reportingSetsRequest)
> ```

I wouldn't expect a conversion extension method to be suspending (i.e. to make an RPC). That and you don't want to bury your RPCs as otherwise it makes it hard to have the right context for error handling.

Make your outgoing RPC in the top-level method impl where it's easier to handle errors. This means restructuring where you check the view.
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/report.proto` line 95 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTRVuP-tc7MYESA7BF:-NoTRVuP-tc7MYESA7BG:bfohwy0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/src/main/proto/wfa/measurement/reporting/bff/v1alpha/report.proto#L95)):*
> ```proto
>         // The keys are implied to be views of at least that amount (eg. 1 is
>         // really 1+).
>         map<int32, double> frequency_histogram = 3;
> ```

Why is this no longer output-only?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427)* status: all files reviewed, 6 unresolved discussions (waiting on @bdomen-ggl)

___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 113 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTRcGw7lrMdqhr-RqR:-NoTRcGw7lrMdqhr-RqS:bfaxuoa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L113)):*
> ```Kotlin
> 
>     return report {
>       reportId = source.name.substring(source.name.lastIndexOf("/") + 1)
> ```

Don't to manual string manipulation to parse resource names. Implement the ResourceKey interface instead.

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/BUILD.bazel` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTPAI86rX-IL_LMuqo:-Non3-ON0PSe4MuF2sCd:bou1obr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/BUILD.bazel#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

FYI if you're going to put this visibility on every target in here, you can just put it as the default_visibility in the package declaration
</blockquote></details>

Deleted this target. And thanks. I was debating using default_visibility with only two targets.
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTPwnY7rz9Bi9YrE6m:-NoTwzIv0EeNfoyGQv2H:bptd9b9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L82)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Every gRPC method call site should handle StatusException. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin
</blockquote></details>

Ah, we forgot to do that at first too. Fixing them all.
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 113 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTRcGw7lrMdqhr-RqR:-NomwrzEEcvr_KjCLnCg:bguhpul) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L113)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't to manual string manipulation to parse resource names. Implement the ResourceKey interface instead.
</blockquote></details>

So this is mainly used for the list reports view. At least currently, the UI is implemented for one measurement consumer, so we strip out the "measurementConsumers/ABC" from the URLs. Since the names come from the backend List Reports, I'm not sure the ResourceKey would help unless I'm missing something. I can leave the name alone and update the routing in the UI.
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 157 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTR8Rw8Qi2Xb9X19e3:-NoTxEr612jZf0clFRw3:b-7ovuw7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L157)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I wouldn't expect a conversion extension method to be suspending (i.e. to make an RPC). That and you don't want to bury your RPCs as otherwise it makes it hard to have the right context for error handling.

Make your outgoing RPC in the top-level method impl where it's easier to handle errors. This means restructuring where you check the view.
</blockquote></details>

That makes sense. I did several major refactors and this was originally much lower down past early exit conditions where it might be useful not to make extra calls if not necessary. Since the RPC call was moved up it definitely makes sense to make the call in the top level function.
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/report.proto` line 95 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTRVuP-tc7MYESA7BF:-NomwXon3UI7A85Y1f6S:b-u70vgi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/src/main/proto/wfa/measurement/reporting/bff/v1alpha/report.proto#L95)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this no longer output-only?
</blockquote></details>

Ah thanks. I was debugging some weird problems and didn't put that back.
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportingSetsService.kt` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTPWk7CKLSGpyhdtuH:-NoTwsCl2FtQwvzQfmKW:bjcz9jb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportingSetsService.kt#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What is this used for?
</blockquote></details>

Request payload for ListReportingSet. Removing the file.
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportingSetsService.kt` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTPZYcCr5DuJwKLzxb:-NoTZw0q57Qjw-QMW0yo:bknf1gy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportingSetsService.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this only called internally by the BFF ReportsService, or is it meant to be exposed in the BFF API? If it's the former, just drop it and call the backend stub directly from the BFF ReportsService.
</blockquote></details>

The former. I'll drop the file and move the logic over.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427)* status: all files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl)

___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 113 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NoTRcGw7lrMdqhr-RqR:-NonKSRo71rhCs2Fia5R:b-f1ik7k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/707e56861c80ba1efe8cfb6833eea4fc1774bd24/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L113)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

So this is mainly used for the list reports view. At least currently, the UI is implemented for one measurement consumer, so we strip out the "measurementConsumers/ABC" from the URLs. Since the names come from the backend List Reports, I'm not sure the ResourceKey would help unless I'm missing something. I can leave the name alone and update the routing in the UI.
</blockquote></details>

As discussed offline, we eventually want to handle multiple MCs anyway. We're just doing single now for simplicity.
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NonKiEy30ChgucYLbYF:-NonKiEy30ChgucYLbYG:b6vmki2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c350f9cc0907521a18a607a03e7a1e10f1a9c6a6/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L42)):*
> ```Kotlin
> import org.wfanet.measurement.reporting.v2alpha.listReportsRequest
> 
> val UNIQUE_TYPE_TAG = "unique"
> ```

Move these into the companion object and add the `const` keyword
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NonKg5q2wWpljsH2HRB:-NonKg5q2wWpljsH2HRC:bx0a02q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c350f9cc0907521a18a607a03e7a1e10f1a9c6a6/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L46)):*
> ```Kotlin
> val ID_TAG = "ui.halo-cmm.org/reporting_set_id"
> val TYPE_TAG = "ui.halo-cmm.org/reporting_set_type"
> val DISPLAY_NAME_TAG = "ui.halo-cmm.org/display_name"
> ```

Add a TODO to remove this once we have a display name field in Report
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 98 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NonK9QJDfGUitCszYM2:-NonK9QK7B-ZSQWKJvSu:be3eiyp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c350f9cc0907521a18a607a03e7a1e10f1a9c6a6/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L98)):*
> ```Kotlin
>                 it.toFullReport(listReportingSetsResponse)
>               }
>               else ->
> ```

Use exhaustive when instead of `else` so that this code must be updated in the event of a new view being added.



_Code quote:_
```Kotlin
else
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427)* status: all files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl)

___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 87 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NorTyY4CIhI03t_WV3b:-NorTyY4CIhI03t_WV3c:bvwwhlb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec3f432db7d007056af914e03a18debfd523c91f/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L87)):*
> ```Kotlin
>               ReportView.REPORT_VIEW_BASIC,
>               ReportView.REPORT_VIEW_UNSPECIFIED,
>               ReportView.UNRECOGNIZED -> it.toBasicReport()
> ```

Unrecognized is an error.



_Code quote:_
```Kotlin
UNRECOGNIZED
```
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 347 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NorU1ki-6Q3W6itorc0:-NorU1ki-6Q3W6itorc1:bgzmnoy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec3f432db7d007056af914e03a18debfd523c91f/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L347)):*
> ```Kotlin
>     private const val ID_TAG = "ui.halo-cmm.org/reporting_set_id"
>     private const val TYPE_TAG = "ui.halo-cmm.org/reporting_set_type"
>     // TODO (@bdomen-ggl): Remove display name after it's added to the backend report proto.
> ```

Use KDoc syntax for properties

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 87 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NorTyY4CIhI03t_WV3b:-Now4G0J33UdiFiPppr4:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec3f432db7d007056af914e03a18debfd523c91f/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L87)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Unrecognized is an error.
</blockquote></details>

Done
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 347 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NorU1ki-6Q3W6itorc0:-Now4IjS693rdYE1n85R:b6pr9t3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec3f432db7d007056af914e03a18debfd523c91f/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L347)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use KDoc syntax for properties
</blockquote></details>

Done. I think, you mean just like this? I had it with multiple lines, but the formatter put them all on one.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl)

___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 347 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NorU1ki-6Q3W6itorc0:-NowSCcB6S3xh8Ya_Ke9:b-13mp7n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec3f432db7d007056af914e03a18debfd523c91f/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L347)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Done. I think, you mean just like this? I had it with multiple lines, but the formatter put them all on one.
</blockquote></details>

Close. Basically everything other than local variables should use this syntax, following the [style guide](https://developer.android.com/kotlin/style-guide#documentation) (e.g. having a summary fragment). The TODO just goes into this KDoc block.
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 92 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NowRj5NBDi5OO9Gre4l:-NowRj5O1f-jUazPclf1:b-phovrv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a2d14e248d73985506e6101a1b00fced019e95db/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L92)):*
> ```Kotlin
>               }
>               ReportView.UNRECOGNIZED ->
>                 throw Status.INVALID_ARGUMENT.withDescription("UNRECOGNIZED is not a valid view.")
> ```

nit: when you get UNRECOGNIZED, it's not because someone actually passed that value on purpose. It means they've passed some integer value that doesn't correspond to a known enum value on the server end.



_Suggestion:_
```Kotlin
"Unrecognized value for view"
```

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 347 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NorU1ki-6Q3W6itorc0:-Np0nKqt7RpOtO36MS_2:b-lpev8z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec3f432db7d007056af914e03a18debfd523c91f/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L347)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Close. Basically everything other than local variables should use this syntax, following the [style guide](https://developer.android.com/kotlin/style-guide#documentation) (e.g. having a summary fragment). The TODO just goes into this KDoc block.
</blockquote></details>

Added Summary Description. Put the TODO below that.
___
*[`experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt` line 92 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427#-NowRj5NBDi5OO9Gre4l:-Np0MEUl7LS5EUFUU3LB:by0d77v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a2d14e248d73985506e6101a1b00fced019e95db/experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt#L92)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: when you get UNRECOGNIZED, it's not because someone actually passed that value on purpose. It means they've passed some integer value that doesn't correspond to a known enum value on the server end.
</blockquote></details>

Done. Also updated the other message.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1427)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl)

**Pull request merged**
