### PR TITLE
Add ResourceNameParser class for parsing API resource names.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)

### CODE REVIEW

**Comment by SanjayVas** [comment]
This is for #94. This utility can be used by a set of functions that return data classes. We should ideally have a data class for each resource name pattern so we don't have to deal with string map keys.

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MbbjjTb1dPjTzwoItCA:-MbbjjTb1dPjTzwoItCB:bd78vwr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe0e2d77c038b6baac6e262b248a8eb3069b5023/src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt#L40)):*
> ```Kotlin
>     val pullRequest = "123"
>     val idSegments = parser.parseIdSegments("repositories/$repository/pullRequests/$pullRequest")
>     assertThat(idSegments).containsExactly("repository", repository, "pull_request", pullRequest)
> ```

Can we add a test with "recurringExchanges/{recurring_exchange}/exchanges/{exchange}/steps/{exchange_step}/attempts/{exchange_step_attempt}" maybe? So, with this pattern, we should get recurringExchangeId by map.get("recurring_exchange") ?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MbbjjTb1dPjTzwoItCA:-MbbkbOA-_YePc6W4vdF:biikthz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe0e2d77c038b6baac6e262b248a8eb3069b5023/src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt#L40)):*
>Can we add a test with "recurringExchanges/{recurring_exchange}/exchanges/{exchange}/steps/{exchange_step}/attempts/{exchange_step_attempt}" maybe? 

Is there something in particular you're concerned about that the existing tests don't cover?

>  So, with this pattern, we should get recurringExchangeId by map.get("recurring_exchange") ?

Yes.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblWl9_DAVuDxxgqLMa:-MblWl9_DAVuDxxgqLMb:bhjtwzq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt#L19)):*
> ```Kotlin
> private val LITERAL_SEGMENT_PATTERN = Regex("[a-z][a-zA-Z0-9]*")
> private val VARIABLE_NAME_PATTERN = Regex("[a-z][a-z0-9_]*")
> private const val ID_SUFFIX = "_id"
> ```

is this in a spec somehwere?
___
*[src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblTs3SDg8I6Z_YFyH6:-MblTs3T2RSmM8W4mm_P:b-6xp94j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt#L32)):*
> ```Kotlin
>   private val segments: List<Segment>
>   init {
>     val parts: List<String> = pattern.split('/')
> ```

I think you could have a regex to extract all the parts but this is fine too
___
*[src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblVQ-85huV60X6ZemR:-MblVQ-85huV60X6ZemS:bmrtmm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt#L82)):*
> ```Kotlin
>   fun assembleName(idSegments: Map<String, String>): String {
>     val parts: MutableList<String> = ArrayList(segments.size)
>     for (segment: Segment in segments) {
> ```

why not just map the values?
___
*[src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblUGMlB9men7Nulbpa:-MblUGMlB9men7Nulbpb:bsmd0fg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel#L80)):*
> ```Starlark
>         "//imports/java/org/junit",
>         "//imports/kotlin/kotlin/test",
>         "//src/main/kotlin/org/wfanet/measurement/common",
> ```

what dependencies does this have from `//src/main/kotlin/org/wfanet/measurement/common`?
___
*[src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblUdJz6giKqH8NQBpx:-MblUdJz6giKqH8NQBpy:bfr8dy4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt#L26)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> class ResourceNameParserTest {
> ```

can you add a test with complex resource ID path segments that throws a message that we don't support that at least for now? (Or add support - either way)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblWl9_DAVuDxxgqLMa:-MblXdQXEaDBpTs6j7Zv:b-dxsdi2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt#L19)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this in a spec somehwere?
</blockquote></details>

Yes, in the two AIP links referenced in the class KDoc. The `_id` suffix is mentioned in AIP-123 and the regex pattern in AIP-122.
___
*[src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblVQ-85huV60X6ZemR:-MblYDNw1cgsnWed6FH3:bi8jqvl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt#L82)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why not just map the values?
</blockquote></details>

Can you clarify what you mean?
___
*[src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblUGMlB9men7Nulbpa:-MblYMXg8vMRq63SufHi:b2kjh2v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel#L80)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what dependencies does this have from `//src/main/kotlin/org/wfanet/measurement/common`?
</blockquote></details>

The Subject Under Test (SUT). That is the package in the `main` tree that this package in the `test` tree is testing.
___
*[src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblUdJz6giKqH8NQBpx:-MblYoX-1-i4c-d9OcJo:bc3ybcy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add a test with complex resource ID path segments that throws a message that we don't support that at least for now? (Or add support - either way)
</blockquote></details>

Can you clarify what you mean by "complex resource ID path segments"? I believe this supports the possible patterns described by the AIPs.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblUdJz6giKqH8NQBpx:-Mbr0Ehc8KzlLOUnHMF2:bagwqvg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you clarify what you mean by "complex resource ID path segments"? I believe this supports the possible patterns described by the AIPs.
</blockquote></details>

I was referring to something like `pattern: "customers/{customer}/feedItemTargets/{feed}~{feed_item}"`

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblUdJz6giKqH8NQBpx:-Mbr5G0l1kLT9ZD8b0HY:b-3do5h2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I was referring to something like `pattern: "customers/{customer}/feedItemTargets/{feed}~{feed_item}"`
</blockquote></details>

Ah. This is intentionally not supported since we use single string resource IDs and we're following the statement from AIP-122 that "Resource name components should usually alternate between collection identifiers (example: publishers, books, users) and resource IDs (example: 123, les-miserables, vhugo1802)." The exception is for singleton resources, which are not collections and are therefore not signified by collection identifiers.

Updated the class KDoc to reflect what's supported w.r.t. segments.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblUdJz6giKqH8NQBpx:-MbrnhDh7Sv8tdXS-QSy:b3cyy2z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah. This is intentionally not supported since we use single string resource IDs and we're following the statement from AIP-122 that "Resource name components should usually alternate between collection identifiers (example: publishers, books, users) and resource IDs (example: 123, les-miserables, vhugo1802)." The exception is for singleton resources, which are not collections and are therefore not signified by collection identifiers.

Updated the class KDoc to reflect what's supported w.r.t. segments.
</blockquote></details>

can we have a test that will explicitly fail with a good explanation in this case?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblUdJz6giKqH8NQBpx:-Mbs3VQjBasUnj-kfQWG:b-6qzhru) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can we have a test that will explicitly fail with a good explanation in this case?
</blockquote></details>

Added a test that verifies an exception is thrown if a segment has more than one variable.

I assume this is what you meant.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblVQ-85huV60X6ZemR:-Mbw-G2V4EDNXbDfuK89:brxl394) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt#L82)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you clarify what you mean?
</blockquote></details>

Something like this...
```
    return segments.map{
        when (it) {
          is LiteralSegment -> it.value
          is VariableSegment ->
            idSegments.getOrDefault(it.name, "").apply {
              require(isNotEmpty()) { "Missing value for ${it.name}" }
            }
        }
    }.joinToString("/")
```
___
*[src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt, line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MbwEUII-LAK_fwlUMGg:-MbwEUII-LAK_fwlUMGh:bqyla6r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c68e63b5b4fbbd5086ff818ea5762d05c291e4dc/src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt#L35)):*
> ```Kotlin
>   init {
>     val parts: List<String> = pattern.split('/')
>     val segments: MutableList<Segment> = ArrayList(parts.size)
> ```

I don't think you need to use mutable lists much in this file. Its mainly just a mapping exercise.
```
    this.segments = parts.map{
      val content = it.removeSurrounding("{", "}")
      if (it.length > content.length) {
        require(!content.endsWith(ID_SUFFIX)) { "Variable name $content ends in $ID_SUFFIX" }
        require(VARIABLE_NAME_PATTERN.matches(content)) { "Invalid variable name $content" }
        VariableSegment(content)
      } else {
        require(LITERAL_SEGMENT_PATTERN.matches(content)) { "Invalid literal segment $content" }
        LiteralSegment(content)
      }        
    }
```
___
*[src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt, line 64 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MbwDKDQES3pN0TUpF3v:-MbwDKDQES3pN0TUpF3w:bdobf9i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c68e63b5b4fbbd5086ff818ea5762d05c291e4dc/src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt#L64)):*
> ```Kotlin
> 
>     val idSegments: MutableMap<String, String> = mutableMapOf()
>     for ((part: String, segment: Segment) in parts.zip(segments)) {
> ```

This might be simpler to read
```
return parts.zip(segments).mapNotNull{ (part: String, segment: Segment) ->
        when (segment) { 
         	is LiteralSegment -> null
        	is VariableSegment -> segment.name to part
        }
   }.toMap()
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MblVQ-85huV60X6ZemR:-MbwMw6l-kfGBk4KMkPT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24c2940f21a52229ba4e0bbf4497c6b244406dce/src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt#L82)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Something like this...
```
    return segments.map{
        when (it) {
          is LiteralSegment -> it.value
          is VariableSegment ->
            idSegments.getOrDefault(it.name, "").apply {
              require(isNotEmpty()) { "Missing value for ${it.name}" }
            }
        }
    }.joinToString("/")
```

</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt, line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MbwEUII-LAK_fwlUMGg:-MbwJ9S_7RlbSKV3y_AU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c68e63b5b4fbbd5086ff818ea5762d05c291e4dc/src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt#L35)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I don't think you need to use mutable lists much in this file. Its mainly just a mapping exercise.
```
    this.segments = parts.map{
      val content = it.removeSurrounding("{", "}")
      if (it.length > content.length) {
        require(!content.endsWith(ID_SUFFIX)) { "Variable name $content ends in $ID_SUFFIX" }
        require(VARIABLE_NAME_PATTERN.matches(content)) { "Invalid variable name $content" }
        VariableSegment(content)
      } else {
        require(LITERAL_SEGMENT_PATTERN.matches(content)) { "Invalid literal segment $content" }
        LiteralSegment(content)
      }        
    }
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt, line 64 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96#-MbwDKDQES3pN0TUpF3v:-MbwLoja2ggo9Pj6_Hs6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c68e63b5b4fbbd5086ff818ea5762d05c291e4dc/src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt#L64)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

This might be simpler to read
```
return parts.zip(segments).mapNotNull{ (part: String, segment: Segment) ->
        when (segment) { 
         	is LiteralSegment -> null
        	is VariableSegment -> segment.name to part
        }
   }.toMap()
```
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @stevenwarejones from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
