### PR TITLE
Standalone px decrypt

### PR DESCRIPTION
**Pull request by jonmolle**
Adds a tool for a standalone panel exchange private query decryption job.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jonmolle)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473#-Nqbm0ZL76y7s4J-aJK6:-Nqbm0ZL76y7s4J-aJK7:b-j77290) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ccbe5a828f99723b677247e5d85d249f0a89137/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L105)):*
> ```Kotlin
>     required = true,
>   )
>   private lateinit var exchangeStepFile: File
> ```

nit: I don't think this should be a file. This won't work well with EMR. Should be a blob key on the same storage device as everything else.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 135 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473#-NqblNV47zNTCb9Tmfe8:-NqblNV47zNTCb9Tmfe9:bbkgp7p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ccbe5a828f99723b677247e5d85d249f0a89137/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L135)):*
> ```Kotlin
>   private lateinit var storageType: StorageDetails.PlatformCase
> 
>   @Option(
> ```

nit: replace the next two flags with https://github.com/world-federation-of-advertisers/common-jvm/blob/4b7d717e0d4fcfb9ee2ba0564c7ad3b64d95feed/src/main/kotlin/org/wfanet/measurement/aws/s3/S3Flags.kt

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473#-Nqbm0ZL76y7s4J-aJK6:-NqcG4Fp5U6hyz-hWvOX:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ccbe5a828f99723b677247e5d85d249f0a89137/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L105)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit: I don't think this should be a file. This won't work well with EMR. Should be a blob key on the same storage device as everything else.
</blockquote></details>

Done
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 135 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473#-NqblNV47zNTCb9Tmfe8:-NqcG5qR5rmc7AGxyy0n:b-1eh3wi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ccbe5a828f99723b677247e5d85d249f0a89137/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L135)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit: replace the next two flags with https://github.com/world-federation-of-advertisers/common-jvm/blob/4b7d717e0d4fcfb9ee2ba0564c7ad3b64d95feed/src/main/kotlin/org/wfanet/measurement/aws/s3/S3Flags.kt
</blockquote></details>

Sure, done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jonmolle)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 110 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473#-Nqcaz7uDhuPDRfUwURW:-Nqcaz7uDhuPDRfUwURX:bdr3n24) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56ac8115dd7fd19eeaf377a5f47dcbe386f0fb66/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L110)):*
> ```Kotlin
>   private lateinit var exchangeStepBlobKey: String
> 
>   // private val beamStep by lazy {
> ```

delete this please

**Review by stevenwarejones — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473#-:-NqdHvzz5R8GnAjgKD83:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle)

**Review by stevenwarejones — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473#-:-NqdHxsZ9WwdIA1z6DY2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 110 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473#-Nqcaz7uDhuPDRfUwURW:-NqdN_xDDjqRBjgRWgbs:bgbwfyn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56ac8115dd7fd19eeaf377a5f47dcbe386f0fb66/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L110)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

delete this please
</blockquote></details>

Whoops, done

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1473)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

**Pull request merged**
