### PR TITLE
Scan container images with Trivy on release.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1558)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1558)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @kungfucraig)

___
*[`.github/workflows/scan-images.yml` line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1558#-NufCPVk-YO8MVD2k9CU:-NufEoi-8XbCpm8R_0qY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a13fd81f3cf7931c866d451d0b3df177d02345c1/.github/workflows/scan-images.yml#L52)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

You might add a comment here about why this list cannot be autogenerated.
</blockquote></details>

Done.
___
*[`.github/workflows/workflow-testing.yml` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1558#-NufCavy8351K1naUoRm:-NufEpXw2h-ts7jEZLbQ:b-wwcicq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a13fd81f3cf7931c866d451d0b3df177d02345c1/.github/workflows/workflow-testing.yml#L26)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

end with newline?
</blockquote></details>

This file was just for testing and has been removed. Note that this PR was still a draft and not yet ready for review.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
I'm concerned about dependencies getting added or a version upgraded and then we don't notice new vulnerabilities until weeks later after we've built on top of them. I'd like to see some documentation that all dep upgrades across this repo and other repos (common-jvm) need to verify they aren't introducing new vulnerabilities with new dep additions/upgrades.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1558#-:-NuzVV7rDPr1QK0ne9Gt:b-lnws2c)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @kungfucraig)

**Review by SanjayVas — COMMENTED** [review]
We're still working on what we (Halo) want to do in regards to detected vulnerabilities. The one thing we know for sure is that we do **not** want to block the development process on detected vulnerabilities at this time, and instead handle them independently of the development/release process (at least for now).

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1558#-:-Nuzb1oJB5-fK4ol30B_:b-h59f97)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @kungfucraig)

**Review by kungfucraig — COMMENTED** [review]
Overall I think we should get this basic scanning PR in and take some time to craft a policy for dealing with the scan results themselves. Having this enabled will allows us to experiment with what the GitHub Security integration offers and help us come up with a good policy.

@SanjayVas is actually already working on understanding more about the GitHub Security integration works.

He's also planning on proposing some options for us. One of those options will be blocking merges on failed security scans.

> Reviewed 1 of 2 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1558#-:-Nuzn3D7Dpn7jKtwKOUJ:bnpjaoq)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
can we just have a json doc called `known vulnerabilities` that documents existing known vulnerabilities? Tests would fail if said PR includes an unknown vulnerability. I agree that a process for addressing vulnerabilities is a near-term future item

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1558#-:-NvJ-qGB5M3FUqRQeoHv:belornx)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by SanjayVas — COMMENTED** [review]
> [@SanjayVas](https://github.com/SanjayVas) is actually already working on understanding more about the GitHub Security integration works.

Yes, I think I've got it down now.

> He's also planning on proposing some options for us.

Kind of. I have a proposed set of processes.

>  One of those options will be blocking merges on failed security scans.

No. My proposal explicitly does not include this. I do not think we should be blocking the development process on triage/analysis of vulnerabilities. I'm fine adding processes to release. My pending doc explains this a bit.

> Tests would fail if said PR includes an unknown vulnerability.

This is undesired.

> can we just have a json doc called `known vulnerabilities` that documents existing known vulnerabilities?

Why would we roll our own thing with GitHub security gives us a much clearer standard path?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1558#-:-NvJ6WYPEo6CMyLpHMTs:b-dbfmlp)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by kungfucraig — COMMENTED** [review]
I think we need to avoid adding more friction to our development process. Most developers just don't have the ability to deal with these issues and holding up their progress while already busy senior people argue about an issue doesn't seem wise. Security issues not related to a new dep will almost by definition have nothing to do with the PR being merged. What's more, the security issue will be flagged against all pending PRs effectively grinding the team to a halt.

Security issues should be addressed out of band by people who are experienced addressing such matters. Our nightly build process will be able to flag these things.

The exception I would make is when we introduce a new dependency in which case the security scan should be part of PR message.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1558#-:-NvJUOzREZQC2FAmVRCB:bp4tuth)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1558)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
