### PR TITLE
Herald supports reach-only llv2 protocol.

### PR DESCRIPTION
**Pull request by renjiezh**
Depends on https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1125

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 8 of 38 files at r1, 30 of 30 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)* status: all files reviewed, 3 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt` line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135#-NamZP9Y-czj4_inpQNp:-NamZP9ZBu73RIqSf82j:be0j6k0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f3c27728ed1014f18ee8c174e286eaa08f2f4cc/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt#L80)):*
> ```Kotlin
>         globalComputationId = globalId
>         computationDetails = initialComputationDetails
>         this.requisitions += requisitions
> ```

Why +=?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt` line 174 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135#-Nam_BZb84y4d4hLjFx7:-Nam_BZb84y4d4hLjFx8:b-6okjoz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f3c27728ed1014f18ee8c174e286eaa08f2f4cc/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt#L174)):*
> ```Kotlin
>       }
> 
>       // For future stages, we log and exit.
> ```

Do we expect to ever log this? It seems like the client should know better than to call this function.

Maybe this is more a warning than info? I suppose we'd want to be consistent with the full LLv2 convention though.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt` line 202 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135#-NamcCYZ5nTkh63TUHBN:-NamcCYZ5nTkh63TUHBO:b84929r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f3c27728ed1014f18ee8c174e286eaa08f2f4cc/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt#L202)):*
> ```Kotlin
>   ) {
>     require(token.computationDetails.hasReachOnlyLiquidLegionsV2()) {
>       "Liquid Legions V2 computation required"
> ```

Please add "reach only" to the message somewhere.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)* status: 37 of 39 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt` line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135#-NamZP9Y-czj4_inpQNp:-Namm3vz52Ltj_mXqZxc:b-jznc7p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f3c27728ed1014f18ee8c174e286eaa08f2f4cc/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt#L80)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why +=?
</blockquote></details>

I think this is the way to set a list using DSL.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt` line 174 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135#-Nam_BZb84y4d4hLjFx7:-Namp2Cs5LJqPnI8wqUL:bga135i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f3c27728ed1014f18ee8c174e286eaa08f2f4cc/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt#L174)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Do we expect to ever log this? It seems like the client should know better than to call this function.

Maybe this is more a warning than info? I suppose we'd want to be consistent with the full LLv2 convention though.
</blockquote></details>

You're right. The is to log for Computations with unexpected state. The logging level should be warning. I also updated other occurrences. 
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt` line 202 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135#-NamcCYZ5nTkh63TUHBN:-NammvJc3KwvNxLdueLh:b6rs0kz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f3c27728ed1014f18ee8c174e286eaa08f2f4cc/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt#L202)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please add "reach only" to the message somewhere.
</blockquote></details>

Done.
Nice catch.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ple13 and @SanjayVas)

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 38 files at r1, 30 of 30 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt` line 319 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135#-Nan-kWV8-j6d4yH9E3_:-Nan-kWV8-j6d4yH9E3a:bcw3gek) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab531e49bdde7dd14b84d6145fab877f02c20cef/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt#L319)):*
> ```Kotlin
>                     globalReachDpNoise = reach.privacyParams.toDuchyDifferentialPrivacyParams()
>                   }
>                   MeasurementSpec.MeasurementTypeCase.REACH_AND_FREQUENCY -> {
> ```

Do we need to check for the case REACH_AND_FREQUENCY?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)* status: 38 of 39 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt` line 319 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135#-Nan-kWV8-j6d4yH9E3_:-NanEmJS7gVK7kzzRbIs:be8nskc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab531e49bdde7dd14b84d6145fab877f02c20cef/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt#L319)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Do we need to check for the case REACH_AND_FREQUENCY?
</blockquote></details>

Nice catch!
I just delete it. It is an error that Rollv2 receives type of REACH_AND_FREQUENCY.

**Review by ple13 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 38 files at r1, 30 of 30 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/reach_only_liquid_legions_sketch_aggregation_v2.proto` line 104 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135#-NarzoVe7h64HIngGdz-:-NarzoVe7h64HIngGdz0:b-45bn6w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9085efc5aab6a70d648f0913d09fdfb6114b81c2/src/main/proto/wfa/measurement/internal/duchy/protocol/reach_only_liquid_legions_sketch_aggregation_v2.proto#L104)):*
> ```proto
>       // Parameters used for reachOnlyLiquidLegions sketch creation and
>       // estimation.
>       LiquidLegionsSketchParameters reach_only_liquid_legions_sketch = 1;
> ```

nit: This field rename seems unnecessary given that it's nested inside of `ReachOnlyLiquidLegionsSketchAggregationV2`.



_Code quote:_
```proto
reach_only_liquid_legions_sketch 
```
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt` line 404 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135#-Nas-DCS2HK0_wtBUqom:-Nas-DCS2HK0_wtBUqon:b-sni7x0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9085efc5aab6a70d648f0913d09fdfb6114b81c2/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L404)):*
> ```Kotlin
> 
>   @Test
>   fun `syncStatuses creates a new llv2 computations`() = runTest {
> ```

Is there a single computation or multiple? (either "**a** new LLv2 Computation" or "new LLv2 Computation**s**")



_Code quote:_
```Kotlin
 a new llv2 computations
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)* status: 36 of 41 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @Marco-Premier, @ple13, and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt` line 404 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135#-Nas-DCS2HK0_wtBUqom:-Nas58EQ8cBb2dTCY29K:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9085efc5aab6a70d648f0913d09fdfb6114b81c2/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L404)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is there a single computation or multiple? (either "**a** new LLv2 Computation" or "new LLv2 Computation**s**")
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 5 of 38 files at r1, 30 of 30 files at r2, 1 of 2 files at r3, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/k8s/testing/secretfiles/non_aggregator_protocols_setup_config.textproto` line 10 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135#-NauAYg-3wyZ8mz-fSq2:-NauAYg-3wyZ8mz-fSq3:b-k94qj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fde751c778ddeda5fec9bd8420191ce64a9853b5/src/main/k8s/testing/secretfiles/non_aggregator_protocols_setup_config.textproto#L10)):*
> ```
>   role: NON_AGGREGATOR
>   external_aggregator_duchy_id: "aggregator"
> }
> ```

Nit missing new line?



_Code quote:_
```
}
```

**Review by renjiezh — COMMENTED** [review]
> Reviewed 4 of 38 files at r1, 30 of 30 files at r2, 1 of 2 files at r3, 5 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
