### PR TITLE
Enforce UTC time for dates in Spanner

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @SanjayVas, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsServiceTest.kt, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342#-MnR8BIeBq7GsuPn6zWH:-MnR8BIf16xZtlI6k091:b5o46br) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/183f011e0c806a4886923e01c0ce414d55da4b07/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsServiceTest.kt#L80)):*
> ```Kotlin
>   }
> 
>   @Test
> ```

i'd love to see some kind of test where this would have failed except for adding in the UTC fix.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsServiceTest.kt, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342#-MnR8BIeBq7GsuPn6zWH:-MnR8VkW6mNT4fSJOXpk:bqxbpje) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/183f011e0c806a4886923e01c0ce414d55da4b07/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsServiceTest.kt#L80)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'd love to see some kind of test where this would have failed except for adding in the UTC fix.
</blockquote></details>

I'm not really sure how to test this. `CURRENT_DATE` uses `America/Los_Angeles` time and uses the system clock, so it's hard to fake. The test would basically just be testing that `CURRENT_DATE("+0")` is sometimes different from `CURRENT_DATE()`.

Do you have a recommendation for a better test?

**Review by yunyeng — APPROVED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsServiceTest.kt, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342#-MnR8BIeBq7GsuPn6zWH:-MnWQm8XB7m4XKjXMKvG:bgmpy29) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/183f011e0c806a4886923e01c0ce414d55da4b07/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsServiceTest.kt#L80)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

mock up emulator maybe?
</blockquote></details>

How? The Spanner client is deliberately designed to not use a mock implementation of Spanner. See also: https://testing.googleblog.com/2020/07/testing-on-toilet-dont-mock-types-you.html#:~:text=isEqualTo(PaymentStatus.-,SUCCESS)%3B,can%20make%20maintenance%20more%20difficult%3A&text=It%20can%20make%20it%20harder%20to%20know%20whether%20a%20library,under%20test%20has%20a%20bug.

But also, this test case would fail without the fix of specifying the TZ offset, right? Isn't it a test that would have failed without the UTC fix?

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
Thanks for figuring out the mystery of having tests that only fail in the evening when run from my machine in LA :P

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342#-:-MnWTwN_BTZA60WaUxRH:b-s6uyp8)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsServiceTest.kt, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342#-MnR8BIeBq7GsuPn6zWH:-MnWouG_2aun57YPsosA:b-dphf2z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/183f011e0c806a4886923e01c0ce414d55da4b07/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsServiceTest.kt#L80)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How? The Spanner client is deliberately designed to not use a mock implementation of Spanner. See also: https://testing.googleblog.com/2020/07/testing-on-toilet-dont-mock-types-you.html#:~:text=isEqualTo(PaymentStatus.-,SUCCESS)%3B,can%20make%20maintenance%20more%20difficult%3A&text=It%20can%20make%20it%20harder%20to%20know%20whether%20a%20library,under%20test%20has%20a%20bug.

But also, this test case would fail without the fix of specifying the TZ offset, right? Isn't it a test that would have failed without the UTC fix?
</blockquote></details>

Resolving this so that HEAD isn't broken.

**Pull request merged**
