### PR TITLE
Implement internal control service for HMSS protocol.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390)

**Review by SanjayVas — APPROVED** [review]
PR description is too vague. e.g. it doesn't mention HMSS.

> Reviewed 3 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-:-NnkG_yK6TrFuww7zyKj:bhu86af)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390)* status: all files reviewed, 9 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt` line 325 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkBOuv7dQmkoSrxm2E:-NnkBOuv7dQmkoSrxm2F:b-o75zf2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt#L325)):*
> ```Kotlin
>         // one.
>         setOf(
>             HonestMajorityShareShuffle.Stage.INITIALIZED,
> ```

We only skip the WAIT_ON_SHUFFLE_INPUT if the seed arrives during the SETUP_PHASE, right? Is it ok to allow the move from INITIALIZED --> WAIT_ONT_SHUFFLE_INPUT?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt` line 344 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkBv-S0pnkOxkT7udj:-NnkBv-S0pnkOxkT7udk:b842e3z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt#L344)):*
> ```Kotlin
>       HonestMajorityShareShuffle.Stage.WAIT_ON_SHUFFLE_INPUT,
>       HonestMajorityShareShuffle.Stage.SHUFFLE_PHASE,
>       HonestMajorityShareShuffle.Stage.AGGREGATION_PHASE,
> ```

Do you think we need an output blob for SHUFFLE_PHASE and AGGREGATION_PHASE so that we can re-use the computation output in case the duchy crashes?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt` line 357 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-Nnk7Hp55cYeGBLIrgKt:-Nnk7Hp55cYeGBLIrgKu:b2benmw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt#L357)):*
> ```Kotlin
>     @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA") // Protobuf enums fields cannot be null.
>     return when (stage.honestMajorityShareShuffle) {
>       HonestMajorityShareShuffle.Stage.INITIALIZED,
> ```

Do we need to wait for a seed in this phase? According to the protocol description, workers only sample seed in this phase.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt` line 443 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkGfueCIKLZLOqH3dA:-NnkGfueCIKLZLOqH3dB:b-ja8wb1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt#L443)):*
> ```Kotlin
>               seeds =
>                 HonestMajorityShareShuffleKt.ComputationDetailsKt.randomSeeds {
>                   this.commonRandomSeed = COMMON_SEED
> ```

It's possible that the peer's seed has not arrived for the INITIALIZED/SETUP phase, right? We need to clarify in the protocol description about whether worker also waits for the peer's seed in the INITIALIZED phase (https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L30). I think it's okay to have the workers check for the peer's seed during INITIALIZED phase, however, they need to run the SETUP_PHASE no matter what, just having the check there will simplify the code.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt` line 464 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkIO1PDUeD2sGfxxiI:-NnkIO1PDUeD2sGfxxiJ:b-8y8ig4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt#L464)):*
> ```Kotlin
>         computationStageInput = computationStageInput {
>           honestMajorityShareShuffleShufflePhaseInput =
>             HonestMajorityShareShuffleKt.shufflePhaseInput { commonRandomSeed = PEER_COMMON_SEED }
> ```

Why do we assign PEER_COMMON_SEED to commonRandomSeed?
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt` line 532 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkJSG3DhL9Zy5OK_sf:-NnkJSG3DhL9Zy5OK_sg:b-k2bt4u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt#L532)):*
> ```Kotlin
>     runBlocking {
>       verifyHmssAdvanceComputationToShuffleStage(
>         initStage = HmssStage.SETUP_PHASE,
> ```

Is it a typo? SETUP_PHASE --> WAIT_ON_SHUFFLE_INPUT?
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkFzOCAaYBxOib0RcL:-NnkFzOD4oUiw4-2hkAH:bb6ht39) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt#L1)):*
> ```Kotlin
> // Copyright 2023 The Cross-Media Measurement Authors
> ```

2024



_Code quote:_
```Kotlin
2023
```
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkL5qU7WXp9T5emqJ0:-NnkL5qU7WXp9T5emqJ1:bed9h5h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt#L53)):*
> ```Kotlin
>     honestMajorityShareShuffle =
>       HonestMajorityShareShuffleKt.computationDetails {
>         seeds = randomSeeds { this.commonRandomSeed = SEED }
> ```

Same as before. Is this the common seed, or the worker's own seed?
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt` line 180 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkM9Qc9Kr_FCbn-MVP:-NnkM9Qc9Kr_FCbn-MVQ:bdipsn7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt#L180)):*
> ```Kotlin
>           Stage.WAIT_ON_SHUFFLE_INPUT -> {
>             if (
>               currentStage == Stage.INITIALIZED ||
> ```

Same comment about INITIALIZED --> WAIT_ON_SHUFFLE_INPUT transition as before.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390)* status: 4 of 11 files reviewed, 9 unresolved discussions (waiting on @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt` line 325 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkBOuv7dQmkoSrxm2E:-NnlvYalD0Mf8Gejk7MG:byqea3z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt#L325)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

We only skip the WAIT_ON_SHUFFLE_INPUT if the seed arrives during the SETUP_PHASE, right? Is it ok to allow the move from INITIALIZED --> WAIT_ONT_SHUFFLE_INPUT?
</blockquote></details>

INITIALIZED->SETUP is transitioned by the herald and it must happen. Then the Mill try to transit from SETUP. lt could skip WAIT_ON_SHUFFLE_INPUT but SETUP will never be skipped.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt` line 344 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkBv-S0pnkOxkT7udj:-Nnlwdn_9uNY0zHw8ada:b-54jszs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt#L344)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Do you think we need an output blob for SHUFFLE_PHASE and AGGREGATION_PHASE so that we can re-use the computation output in case the duchy crashes?
</blockquote></details>

This is a great question.
In this case we have to store the result every time. Considering the trade-off especially the chance of reusing, I prefer just to rerun the stages. 
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt` line 357 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-Nnk7Hp55cYeGBLIrgKt:-Nnlx4Az50uLQC-K-3bj:baisr2a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt#L357)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Do we need to wait for a seed in this phase? According to the protocol description, workers only sample seed in this phase.
</blockquote></details>

When a computation is INITIALIZED, the seed of it has already been set. The state and seed are set at the same time during creation.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt` line 443 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkGfueCIKLZLOqH3dA:-NnlxStR75jOS1Yyhzz5:bywlm42) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt#L443)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

It's possible that the peer's seed has not arrived for the INITIALIZED/SETUP phase, right? We need to clarify in the protocol description about whether worker also waits for the peer's seed in the INITIALIZED phase (https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L30). I think it's okay to have the workers check for the peer's seed during INITIALIZED phase, however, they need to run the SETUP_PHASE no matter what, just having the check there will simplify the code.
</blockquote></details>

When a worker sends the seed to the peer, we can guarantee that the peer is at least in INITIALIZED. This is by the coordination of the Kingdom.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt` line 464 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkIO1PDUeD2sGfxxiI:-Nnly7Im2i5eTSW3CPng:b-os7o2p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt#L464)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Why do we assign PEER_COMMON_SEED to commonRandomSeed?
</blockquote></details>

Good question. The name caused the confusion. When receiving the ShufflePhaseInput, the random seed is of course from the peer. Let me rename it. Afterall, it is `input`, so the perspective is on the receiver.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt` line 532 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkJSG3DhL9Zy5OK_sf:-Nnm2tr4DKUevt_EV4CV:b-kuf5sn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt#L532)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Is it a typo? SETUP_PHASE --> WAIT_ON_SHUFFLE_INPUT?
</blockquote></details>

Nice catch! Thanks.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkFzOCAaYBxOib0RcL:-Nnm2zx59ik30KOSkHXU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt#L1)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

2024
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkL5qU7WXp9T5emqJ0:-Nnm37kACNUuHgnFJ2bT:b-gw20vl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt#L53)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Same as before. Is this the common seed, or the worker's own seed?
</blockquote></details>

When the name contains `peer`, it is from the peer worker. Otherwise it is the own seed.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt` line 180 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkM9Qc9Kr_FCbn-MVP:-NnlxsgvA4UCSpeR7TBo:b-am03r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt#L180)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Same comment about INITIALIZED --> WAIT_ON_SHUFFLE_INPUT transition as before.
</blockquote></details>

See reply above.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 2 of 4 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390)* status: all files reviewed, 9 unresolved discussions (waiting on @ple13)

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390)* status: all files reviewed, 4 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt` line 325 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkBOuv7dQmkoSrxm2E:-NnofWV_1ziEmEy9L7A5:bncl412) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt#L325)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

INITIALIZED->SETUP is transitioned by the herald and it must happen. Then the Mill try to transit from SETUP. lt could skip WAIT_ON_SHUFFLE_INPUT but SETUP will never be skipped.
</blockquote></details>

In this case, why INITIALIZED is a valid stage?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt` line 357 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-Nnk7Hp55cYeGBLIrgKt:-Nnog9Pv3FWkTMoxgQXy:b-xbs0jv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt#L357)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

When a computation is INITIALIZED, the seed of it has already been set. The state and seed are set at the same time during creation.
</blockquote></details>

I mean the peer's seed. In the protocol description (https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L43) workers only sample and store their seed. They won't send their seed to the other worker until SETUP_PHASE. I wonder if it is necessary to check for peer's seed in the INITIALIZED phase.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt` line 443 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkGfueCIKLZLOqH3dA:-Nnoi3YB5rABDxPChfqa:b6an1oe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt#L443)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

When a worker sends the seed to the peer, we can guarantee that the peer is at least in INITIALIZED. This is by the coordination of the Kingdom.
</blockquote></details>

My question was about whether a worker should expect peer's seed during the INITIALIZED phase, or it should just check for the peer's seed during SETUP/WAIT_ON_SHUFFLE_INPUT phase. As our protocol description doesn't mention that peer's seed is expected in the INITIALIZED phase, I think we should update it to make it consistent. 
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkL5qU7WXp9T5emqJ0:-NnohPcJ1yqWZRy7GBr2:bh32fnm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt#L53)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

When the name contains `peer`, it is from the peer worker. Otherwise it is the own seed.
</blockquote></details>

In the proto, we do not have any field to store the worker's own seed yet. Is it intended?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @ple13 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt` line 325 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkBOuv7dQmkoSrxm2E:-Nnopl-aEeF_qVpvEZyu:b-7e5q52) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt#L325)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

In this case, why INITIALIZED is a valid stage?
</blockquote></details>

For example, when the Measurement in the Kingdom is updated to PENDING_REQUISITION state, the corresponding Computation in Worker_1 is transitioned by Herald to SETUP phase accordingly. Then its mill pick it up and try to send seed to the worker_2. However, it is possible that worker_2's Herald is not fast enough to finish INITIALIZED->SETUP transition, so when worker_1 sending seed, the worker_1's Computation is still INITIALIZED. It is valid to accept the seed.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt` line 357 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-Nnk7Hp55cYeGBLIrgKt:-NnoyV4N7cy4DjSmRrMO:bx9oxkg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt#L357)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I mean the peer's seed. In the protocol description (https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L43) workers only sample and store their seed. They won't send their seed to the other worker until SETUP_PHASE. I wonder if it is necessary to check for peer's seed in the INITIALIZED phase.
</blockquote></details>

I updated the protocol stage description that peer's random seed can also be accepted during `INITiALIZED` and `SETUP`.
In a summary, a worker sends seed in `SETUP`, but it can receive them in [`INITiALIZED`, `SETUP`, and `WAIT_ON_SHUFFLE_INPUT`].
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt` line 443 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkGfueCIKLZLOqH3dA:-Nnoz_dz2W87pSrY8HAz:b6vsa0x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/AsyncComputationControlServiceTest.kt#L443)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

My question was about whether a worker should expect peer's seed during the INITIALIZED phase, or it should just check for the peer's seed during SETUP/WAIT_ON_SHUFFLE_INPUT phase. As our protocol description doesn't mention that peer's seed is expected in the INITIALIZED phase, I think we should update it to make it consistent.
</blockquote></details>

Makes sense. Protocol stage description updated.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-NnkL5qU7WXp9T5emqJ0:-NnozfMm2GZqncKEvCJf:b-wikq2n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/HonestMajorityShareShuffleStagesTest.kt#L53)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

In the proto, we do not have any field to store the worker's own seed yet. Is it intended?
</blockquote></details>

Here it is.
https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1390/files#diff-7379a5552d6af83fc564c94ab0dcb609010e46ebb1c9211641f7f4399b714378R100-R107

**Review by ple13 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-:-Nnp4yso6oDDVh1d5h1G:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt` line 357 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-Nnk7Hp55cYeGBLIrgKt:-Nnp1itTABRqs8SR0Ntm:befe1sl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt#L357)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I updated the protocol stage description that peer's random seed can also be accepted during `INITiALIZED` and `SETUP`.
In a summary, a worker sends seed in `SETUP`, but it can receive them in [`INITiALIZED`, `SETUP`, and `WAIT_ON_SHUFFLE_INPUT`].
</blockquote></details>

Just a side note: I think there is no gain to have workers check for the peer's seed during the INITIALIZED phase. The workers have to advance to SETUP_PHASE anyway (no matter if the peer's seed has arrived or not). And there is also a check in the SETUP_PHASE. The extra check in the INITIALIZED phase will make our code more complicated (with extra logic and tests to handle the scenario where peer's seed has been received in the INITIALIZED phase). We can defer the check till the SETUP_PHASE or it seems like we can just merge the INITIALIZED and SETUP_PHASE into a single phase. Anyway, I think this approach has a bit of overhead, but not too much. It's up to you to decide.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt` line 357 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390#-Nnk7Hp55cYeGBLIrgKt:-NnrMiKM5ppLdVImMOCQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f1943e5000572a37043df8cd74f0c469429f0f/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computationcontrol/ProtocolStages.kt#L357)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Just a side note: I think there is no gain to have workers check for the peer's seed during the INITIALIZED phase. The workers have to advance to SETUP_PHASE anyway (no matter if the peer's seed has arrived or not). And there is also a check in the SETUP_PHASE. The extra check in the INITIALIZED phase will make our code more complicated (with extra logic and tests to handle the scenario where peer's seed has been received in the INITIALIZED phase). We can defer the check till the SETUP_PHASE or it seems like we can just merge the INITIALIZED and SETUP_PHASE into a single phase. Anyway, I think this approach has a bit of overhead, but not too much. It's up to you to decide.
</blockquote></details>

Done.

**Review by renjiezh — COMMENTED** [review]
> Dismissed @ple13 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1390)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
