### PR TITLE
Draft sample of error conversion to contain more information

### PR DESCRIPTION
**Pull request by jcorilla**
Sample of conversion of errors thrown via public api
Not for merging

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305)* status: all files reviewed, 9 unresolved discussions (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 447 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305#-NhDPwepCY6W-cgaG3dL:-NhDPwepCY6W-cgaG3dM:b-fikpbj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97c0c3fe97c14561eaa0674f1c73d31cf38c1f57/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L447)):*
> ```Kotlin
>   val errorInfoPacked =
>     StatusProto.fromStatusAndTrailers(ex.status, ex.trailers).detailsList.find {
>       it.typeUrl.endsWith("/$errorInfoFullName")
> ```

https://github.com/world-federation-of-advertisers/common-jvm/pull/219 has adds a `ProtoReflection.getTypeUrl` function that may help here.



_Code quote:_
```Kotlin
it.typeUrl.endsWith("/$errorInfoFullName")
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 450 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305#-NhDQAU82WcIFuzQ8FL7:-NhDQAU82WcIFuzQ8FL8:b5obp18) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97c0c3fe97c14561eaa0674f1c73d31cf38c1f57/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L450)):*
> ```Kotlin
>     }
>   val errorInfo = errorInfoPacked?.unpack(ErrorInfo::class.java)
>   if (errorInfo != null && errorInfo.domain == "wfa.measurement.internal.kingdom.ErrorCode") {
> ```

Since you're depending on the ErrorCode type, you should be able to call `ErrorCode.getDescriptor().fullName`.



_Code quote:_
```Kotlin
"wfa.measurement.internal.kingdom.ErrorCode"
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 451 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305#-NhDQYNx1jF6sqDuKbTs:-NhDQYNx1jF6sqDuKbTt:bsves2k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97c0c3fe97c14561eaa0674f1c73d31cf38c1f57/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L451)):*
> ```Kotlin
>   val errorInfo = errorInfoPacked?.unpack(ErrorInfo::class.java)
>   if (errorInfo != null && errorInfo.domain == "wfa.measurement.internal.kingdom.ErrorCode") {
>     val statusProto: com.google.rpc.Status = status {
> ```

nit: can you not import this name? If there's some other Status being imported, you can use an import alias (e.g. `GrpcStatus`)



_Code quote:_
```Kotlin
com.google.rpc.Status
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 463 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305#-NhDPNMJA_gPKFpNzcN9:-NhDPNMJA_gPKFpNzcNA:b-6bw40d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97c0c3fe97c14561eaa0674f1c73d31cf38c1f57/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L463)):*
> ```Kotlin
>         )
>     }
>     val status: Status by lazy {
> ```

Drop all the lazy delegation. We use these values right away, so this is just adding overhead for no reason.



_Code quote:_
```Kotlin
 by lazy
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 464 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305#-NhDQmeZ039kidbsNKUE:-NhDQmeZ039kidbsNKUF:bxpur2d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97c0c3fe97c14561eaa0674f1c73d31cf38c1f57/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L464)):*
> ```Kotlin
>     }
>     val status: Status by lazy {
>       when (errorInfo.reason) {
> ```

While these conversions may be true most of the time, the actual status code can depend on the call site.

You may want to just extract common utils for parsing the error code and key-value pairs.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 475 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305#-NhDRKh99tLlWZMAdjgp:-NhDRKhAAeqxWgz4GmTX:bf7izw2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97c0c3fe97c14561eaa0674f1c73d31cf38c1f57/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L475)):*
> ```Kotlin
>       when (errorInfo.reason) {
>         // Adjust for different causes of same error code
>         ErrorCode.MEASUREMENT_NOT_FOUND.toString() -> "Measurement for external computation ID ${errorInfo.metadataMap["external_computation_id"]} not found"
> ```

"External ID" has no meaning in the public API. This should reference the resource name instead.



_Code quote:_
```Kotlin
external computation ID
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 482 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305#-NhDRnqr0PTAghNRIM-n:-NhDRnqr0PTAghNRIM-o:b-ei7btb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97c0c3fe97c14561eaa0674f1c73d31cf38c1f57/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L482)):*
> ```Kotlin
>       }
>     }
>     // generate metadata without using statusproto or use statusproto for status and description as well
> ```

You basically want to extract the common parts out of KingdomInternalException.asStatusRuntimeException.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 485 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305#-NhDRcvTCTBFBO0L2BSE:-NhDRcvTCTBFBO0L2BSF:b32wl4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97c0c3fe97c14561eaa0674f1c73d31cf38c1f57/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L485)):*
> ```Kotlin
>     throw status
>       .withDescription(description)
>       .withCause(ex.cause)
> ```

ex



_Code quote:_
```Kotlin
ex.cause
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 491 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305#-NhDRwlLE8pxW1qUwQLY:-NhDRwlLE8pxW1qUwQLZ:b-56s7ir) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97c0c3fe97c14561eaa0674f1c73d31cf38c1f57/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L491)):*
> ```Kotlin
>   } else {
>     val status: Status by lazy {
>       when (ex.status.code) {
> ```

This logic also can vary by call-site. Sometimes we want to do something else when we see a certain status code for a certain method. For example, we may retry a whole transaction when we see an ABORTED.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305)* status: all files reviewed, 9 unresolved discussions (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 447 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1305#-NhDPwepCY6W-cgaG3dL:-NhDW1keCXZXVdGnHFBu:b-b9mh0j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97c0c3fe97c14561eaa0674f1c73d31cf38c1f57/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L447)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

https://github.com/world-federation-of-advertisers/common-jvm/pull/219 has adds a `ProtoReflection.getTypeUrl` function that may help here.
</blockquote></details>

Actually even simpler is to use the `isA` extension from com.google.protobuf.kotlin

**Comment by kungfucraig** [comment]
Abandoned

**Pull request closed without merging**
