### PR TITLE
Use SyntheticGenerator instead of BigQuery for K8s test workflow.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1128)

**Comment by SanjayVas** [comment]
Current PR stack:

* #1128 <-- This PR
* #1127 
* #1112 <-- Base PR

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
