### PR TITLE
Update claimWork tests with owner

### PR DESCRIPTION
**Pull request by YuhongWang-Amazon**
This updates the claimWork method in Duchy ComputationsService to require the owner field in request and its corresponding tests to cover the owner and lock features.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/906)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/906)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 593 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/906#-NR4S0NYB_zcDEzksVZm:-NR4S0NYB_zcDEzksVZn:b-bo3mze) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af9c356c9e6c35abc7c34467e9ea6d6825bb18/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L593)):*
> ```Kotlin
>       DEFAULT_CLAIM_WORK_REQUEST.copy { lockDuration = Duration.ofSeconds(1).toProtoDuration() }
>     service.claimWork(claimWorkRequest)
>     delay(Duration.ofSeconds(2))
> ```

Use a fake clock rather than introducing real delays in tests. Using a real delay means you're always making the test take 2 seconds longer to run.



_Code quote:_
```Kotlin
    delay(Duration.ofSeconds(2))
```

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/906)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsService.kt` line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/906#-NR4PAaf9IlxijvzmuPa:-NR8ZFZE-MWBs7izRjQN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af9c356c9e6c35abc7c34467e9ea6d6825bb18/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsService.kt#L86)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The "blank" check also covers "empty". If `isEmpty` is true, then `isBlank` is also true.

In Kotlin protobuf messages for proto3, a string field being empty and being unset are equivalent. e.g. if you call `clearOwner()` and `owner = ""` are equivalent statements[^1].

[^1]: It's possible there's a difference on the wire depending on the implementation, but it's generally not observable in code. We prefer calling `clear` for clarity regardless.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 593 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/906#-NR4S0NYB_zcDEzksVZm:-NR8ZLdYEQwW6jjORJ9P:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af9c356c9e6c35abc7c34467e9ea6d6825bb18/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L593)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a fake clock rather than introducing real delays in tests. Using a real delay means you're always making the test take 2 seconds longer to run.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/906)* status: all files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 577 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/906#-NR9KazwELre8XiRU8bR:-NR9KazwELre8XiRU8bS:bvqopy2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c06c292267275384adff431db54135f9f8baaafc/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L577)):*
> ```Kotlin
> 
>     assertThat(exception.status.code).isEqualTo(Status.INVALID_ARGUMENT.code)
>     assertThat(exception.message).contains("owner should not be blank")
> ```

nit: just check that it mentions "owner". The exact message should be free to change.



_Suggestion:_
```Kotlin
owner
```

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/906)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt` line 577 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/906#-NR9KazwELre8XiRU8bR:-NRE4RPN8ZTkVaD2cq7x:b-608bz7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c06c292267275384adff431db54135f9f8baaafc/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt#L577)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: just check that it mentions "owner". The exact message should be free to change.
</blockquote></details>

Thanks. Noticed that you updated this in https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/910#-. I will merge this in.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/906)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Pull request merged**
