### PR TITLE
Implement internal CancelMeasurement method.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/266)

https://rally1.rallydev.com/#/?detail=/task/608697561355&fdp=true

### CODE REVIEW

**Comment by SanjayVas** [comment]
CC @uakyol

**Review by wangyaopw — COMMENTED** [review]
Add one test for succeeded cancelling?

we don't need test for all illegal request I think.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/266#-:-MjApl_ZDmNNNTMQj24x:b3r9oy1)* status: 0 of 4 files reviewed, all discussions resolved

**Review by SanjayVas — COMMENTED** [review]
Ooops, forgot that I hadn't done this yet. Putting this back to draft until I have tests.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/266#-:-MjB6OstBimogIhyG_QT:b-riiakk)* status: 0 of 4 files reviewed, all discussions resolved

**Review by SanjayVas — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/266#-:-MjBthBl4RR_oSyMpT7u:b-896fix)* status: 0 of 6 files reviewed, all discussions resolved

**Review by wangyaopw — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/266#-:-MjBxjrhDBtwcX4m7M0p:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/266)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)

**Pull request merged**
