### PR TITLE
Add tags to metric calculation spec

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1395)

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1395)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecsServiceTest.kt` line 148 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1395#-NnfFLJd41JJtcc1BSoD:-NnfFLJe4eLokIKXQX60:b5g9qzx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b3bf796f6a1a9c1b2a78a3ab35f41b6ba4b0478/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecsServiceTest.kt#L148)):*
> ```Kotlin
>     val request = createMetricCalculationSpecRequest {
>       parent = MEASUREMENT_CONSUMER_NAME
>       this.metricCalculationSpec = metricCalculationSpec
> ```

This is same as `METRIC_CALCULATION_SPEC`. Any reason not to use `METRIC_CALCULATION_SPEC`?



_Code quote:_
```Kotlin
metricCalculationSpec
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1395)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecsServiceTest.kt` line 148 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1395#-NnfFLJd41JJtcc1BSoD:-NnfbR6e4o0UdGjrsEKL:bejwaq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b28a92d04e7e8b356ef4c5cb038fbcb26aeb98/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecsServiceTest.kt#L148)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

This is same as `METRIC_CALCULATION_SPEC`. Any reason not to use `METRIC_CALCULATION_SPEC`?
</blockquote></details>

I wanted to make it obvious for at least one test that new fields like tags are actually being passed correctly

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1395)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecsServiceTest.kt` line 148 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1395#-NnfFLJd41JJtcc1BSoD:-NngjwFKChO_A6gWCPUI:ban4547) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b28a92d04e7e8b356ef4c5cb038fbcb26aeb98/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecsServiceTest.kt#L148)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I wanted to make it obvious for at least one test that new fields like tags are actually being passed correctly
</blockquote></details>

I don't think it's necessary, but I am ok with that.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1395)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @tristanvuong2021)

**Pull request merged**
