### PR TITLE
refactor: use suspendCoroutine instead of Deferred for K8s API calls

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1714)

**Comment by SanjayVas** [comment]
Depends on #1707

**Review by kungfucraig — COMMENTED** [review]
Would you mind adding a brief description about why you are doing this? I'm curious myself and may as well record it for posterity. :)

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1714#-:-O337WUQ4sd9BRB8oaDb:bb2b3ql)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by SanjayVas — COMMENTED** [review]
It's just that using the (higher-level) Deferred is unnecessary in this case. Coroutine continuations (suspendCoroutine) is the lower-level construct that things like Deferred use underneath.

suspendCoroutine is built into the Kotlin standard library, where Deferred comes from the kotlinx.coroutines library.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1714#-:-O33WLu_9EVfpNcqdbjR:b-ku3vqo)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1714)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
