### PR TITLE
Add CLI Commands for ModelOutage and ModelShard Services

### PR DESCRIPTION
**Pull request by jojijac0b**
Create CLI commands and tests for ModelOutage and ModelShard services
Removes unneeded import of ModelSuite service for Benchmark in v2alpha/tools/BUILD.bazel

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066)

**Review by Marco-Premier — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066)* status: all files reviewed, 4 unresolved discussions (waiting on @jojijac0b, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1560 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066#-NY3LPbD6ijAzrADYzFl:-NY3LPbD6ijAzrADYzFm:b56gggy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b006ab42964dcfca00be6e3cf19408c89c6e541f/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1560)):*
> ```Kotlin
>       pageToken = listPageToken
>       showDeleted = showDeletedOutages
>       if (outageInterval.isNotEmpty()) {
> ```

nit this could be ```isNotBlank()``` to prevent reading string made up by spaces only



_Code quote:_
```Kotlin
isNotEmpty()
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1640 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066#-NY3N2EV8ZVWktrUm9eN:-NY3N2EV8ZVWktrUm9eO:bs10igf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b006ab42964dcfca00be6e3cf19408c89c6e541f/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1640)):*
> ```Kotlin
>       modelShard = modelShard {
>         modelRelease = shardModelRelease
>         modelBlob = ModelShard.ModelBlob.newBuilder().setModelBlobPath(shardModelBlobPath).build()
> ```

Use dll for this:

```
modelBlob = {
  modelBlobPath = shardModelBlobpath
}
```
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1486 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066#-NY3P6cq83_MvTXtEqjL:-NY3P6cq83_MvTXtEqjM:b1o5r5w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b006ab42964dcfca00be6e3cf19408c89c6e541f/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1486)):*
> ```Kotlin
>           "create",
>           "--parent=$DATA_PROVIDER_NAME",
>           "--model-release=release1",
> ```

nit we can use constant for this value 
```MODEL_RELEASE_NAME```



_Code quote:_
```Kotlin
release1
```
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 1501 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066#-NY3PGP138OGiFBKmc-I:-NY3PGP138OGiFBKmc-J:b7sh83y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b006ab42964dcfca00be6e3cf19408c89c6e541f/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L1501)):*
> ```Kotlin
>           parent = DATA_PROVIDER_NAME
>           modelShard = modelShard {
>             modelRelease = "release1"
> ```

nit same as above, use constant



_Code quote:_
```Kotlin
"release1"
```

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1640 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066#-NY3N2EV8ZVWktrUm9eN:-NY3gjJ79SzE2hlXB1ah:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b006ab42964dcfca00be6e3cf19408c89c6e541f/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1640)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Use dll for this:

```
modelBlob = {
  modelBlobPath = shardModelBlobpath
}
```
</blockquote></details>

Done.

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066)* status: all files reviewed, 5 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066#-NY52cx67tNcUkxNsuui:-NY52cx67tNcUkxNsuuj:bgt52tx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2e2b2fb6107fd50512dea8f3f307f6ea904a0a3d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L46)):*
> ```Kotlin
> import org.wfanet.measurement.api.v2alpha.EncryptionPublicKey
> import org.wfanet.measurement.api.v2alpha.ListModelLinesRequestKt.filter
> import org.wfanet.measurement.api.v2alpha.ListModelOutagesRequestKt.filter as modelOutagesFilter
> ```

There is still a bug where non top level aliases break autocomplete in Intellij. Instead, import ListModelOutagesRequestKt and use it like ListModelOutagesRequestKt.filter.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1492 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066#-NY51o5135XsA3CrkAPE:-NY51o52Bfy9-xQmyOc9:b-ph2gap) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2e2b2fb6107fd50512dea8f3f307f6ea904a0a3d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1492)):*
> ```Kotlin
>       required = true,
>     )
>     modelOutageInterval: String,
> ```

Use the same format as the other time arguments in this file.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1554 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066#-NY526BM20Gbux1lbiVQ:-NY526BM20Gbux1lbiVR:bs4q9op) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2e2b2fb6107fd50512dea8f3f307f6ea904a0a3d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1554)):*
> ```Kotlin
>       defaultValue = "",
>     )
>     outageInterval: String
> ```

Ditto.
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt` line 72 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066#-NY52xPt39akLM5lRlzr:-NY52xPt39akLM5lRlzs:bs4q9op) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2e2b2fb6107fd50512dea8f3f307f6ea904a0a3d/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L72)):*
> ```Kotlin
> import org.wfanet.measurement.api.v2alpha.ListModelLinesRequestKt.filter
> import org.wfanet.measurement.api.v2alpha.ListModelOutagesRequest
> import org.wfanet.measurement.api.v2alpha.ListModelOutagesRequestKt.filter as modelOutagesFilter
> ```

Ditto.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by jojijac0b — COMMENTED** [review]
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1066)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
