### PR TITLE
Clean up Ledger Code

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1LXwt-7jAGtRXxdM1k:-N1LXwt-7jAGtRXxdM1l:blgd0k1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55df2febcb390182ab850ddeadf4fd72efa160b2/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L118)):*
> ```Kotlin
>     maximumTotalEpsilon: Float
>   ) =
>     (charges.sumOf { it.epsilon.toDouble() * it.count.toDouble() } >
> ```

Consider adding helper functions for clarity:

```
fun ChargeWithRepetitions.totalEpsilon(): Double = epsilon.toDouble() * count
```

and ditto for `delta`.

So then you can do: `charges.sumOf { it.totalEpsilon() }`
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1LWj8o33xIq5MAL4aX:-N1LWj8o33xIq5MAL4aY:b-uf4hcw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b84b1ee53bc65534b6ad36cdb7814a224cfafa3c/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt#L29)):*
> ```Kotlin
> data class ChargeWithRepetitions(val epsilon: Float, val delta: Float, val count: Int) {
> 
>   fun isEquivalentTo(other: ChargeWithRepetitions): Boolean =
> ```

Any particular reason to not just define this as equality?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1LX4dvBIo8xnlLF8td:-N1LX4dvBIo8xnlLF8te:b-if9o48) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b84b1ee53bc65534b6ad36cdb7814a224cfafa3c/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt#L36)):*
> ```Kotlin
> object Composition {
>   /** Memoized computation of binomial coefficients. */
>   private val coeffs = ConcurrentHashMap<Pair<Int, Int>, Float>()
> ```

Why does one cache use a ConcurrentHashMap while the other uses a normal HashMap?

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 30 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1LYwnK2LIWrLznFw09:-N1LYwnL4vgR4mOAX7ql:bctu335) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e952e252bf6743b1b94018390a5b18ca1e3741a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L30)):*
> ```Kotlin
> 
> fun ChargeWithRepetitions.isEquivalentTo(other: ChargeWithRepetitions): Boolean =
>   (abs(this.epsilon - other.epsilon) < PrivacyBudgetLedgerConstants.EPSILON_EPSILON) &&
> ```

Consider making a helper function:

```
inline fun Float.approximatelyEqualTo(other: Float, maximumDifference: Float): Boolean {
  return abs(this - other) < maximumDifference
}
```

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1LXwt-7jAGtRXxdM1k:-N1LZPo98wBtnX_fcBCg:brsazf4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/55df2febcb390182ab850ddeadf4fd72efa160b2/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L118)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Consider adding helper functions for clarity:

```
fun ChargeWithRepetitions.totalEpsilon(): Double = epsilon.toDouble() * count
```

and ditto for `delta`.

So then you can do: `charges.sumOf { it.totalEpsilon() }`
</blockquote></details>

Awesome. 
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 30 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1LYwnK2LIWrLznFw09:-N1L_TTs9sW1jEfvoqFe:b-q55ygh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e952e252bf6743b1b94018390a5b18ca1e3741a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L30)):*
> inline fun Float.approximatelyEqualTo(other: Float, maximumDifference: Float): Boolean {
>   return abs(this - other) < maximumDifference
> }
thank you , got a   warning: expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types , took out inline
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1LWj8o33xIq5MAL4aX:-N1LZ_f2AuNSL5VOj8aG:b-4th3si) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b84b1ee53bc65534b6ad36cdb7814a224cfafa3c/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Any particular reason to not just define this as equality?
</blockquote></details>

I guess you are referring to isEquivalentTo (I apparently pushed after your comment and reviewable doesn't point to right place). The reason is repetition count. They can be different, so 2 charges would not be "equal" but equivalent to each other. I guess that's what Matthew thought when he wrote this.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1LX4dvBIo8xnlLF8td:-N1LYaoTBuYbqsRPQaMe:bx8jycs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b84b1ee53bc65534b6ad36cdb7814a224cfafa3c/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why does one cache use a ConcurrentHashMap while the other uses a normal HashMap?
</blockquote></details>

Concurrent Hash map does not support nulls : https://docs.oracle.com/javase/6/docs/api/java/util/concurrent/ConcurrentHashMap.html "Like Hashtable but unlike HashMap, this class does not allow null to be used as a key or value."   

A workaround is to use a big constant for null. then we can make it a concurrent one, wdyt?

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1LWj8o33xIq5MAL4aX:-N1LnrgfBRJxPwwOojks:b685ys1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b84b1ee53bc65534b6ad36cdb7814a224cfafa3c/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt#L29)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I guess you are referring to isEquivalentTo (I apparently pushed after your comment and reviewable doesn't point to right place). The reason is repetition count. They can be different, so 2 charges would not be "equal" but equivalent to each other. I guess that's what Matthew thought when he wrote this.
</blockquote></details>

actually, you are right, I changed it.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1LWj8o33xIq5MAL4aX:-N1LoB6r1TajSCxRajdv:b-xosr7x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b84b1ee53bc65534b6ad36cdb7814a224cfafa3c/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt#L29)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

actually, you are right, I changed it.
</blockquote></details>

sorry :facepalm: not this comment, I changed the concurrent hashmap :)
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1LX4dvBIo8xnlLF8td:-N1LoHZR6gM-0hkHW-N8:b-u0q4aj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b84b1ee53bc65534b6ad36cdb7814a224cfafa3c/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt#L36)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Concurrent Hash map does not support nulls : https://docs.oracle.com/javase/6/docs/api/java/util/concurrent/ConcurrentHashMap.html "Like Hashtable but unlike HashMap, this class does not allow null to be used as a key or value."   

A workaround is to use a big constant for null. then we can make it a concurrent one, wdyt?
</blockquote></details>

 I changed it.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 146 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1PBg5_5nV9RwW9Stut:-N1PBg5_5nV9RwW9Stuu:bn22o55) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2a00bab18dff1a45778414f8bc5e87ede414449/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L146)):*
> ```Kotlin
>       charges.map { ChargeWithRepetitions(it.epsilon, it.delta, 1) } +
>         ledgerEntries.map {
>           ChargeWithRepetitions(
> ```

Consider adding helper function:

```
private fun PrivacyBudgetLedgerEntry.toChargeWithRepetitions(): ChargeWithRepetitions {
  return ChargeWithRepetitions(privateCharge.epsilon, privacyCharge.delta, repetitionCount)
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt` line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1PAf3A3Opv0YZkuhlN:-N1PAf3A3Opv0YZkuhlO:by2mn17) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2a00bab18dff1a45778414f8bc5e87ede414449/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt#L40)):*
> ```Kotlin
>    * coefficient of x^k in the expansion of (1 + x)^n.
>    */
>   private fun coeff(n: Int, k: Int): Float {
> ```

Consider having this return an `Int` or `Long` and then casting to a float when needed. `Float` cannot represent many integers exactly (such as `16,777,217`). It should also perform faster if it's doing integer addition.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 146 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1PBg5_5nV9RwW9Stut:-N1PKbZS8b3YXZ-drU0f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2a00bab18dff1a45778414f8bc5e87ede414449/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L146)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Consider adding helper function:

```
private fun PrivacyBudgetLedgerEntry.toChargeWithRepetitions(): ChargeWithRepetitions {
  return ChargeWithRepetitions(privateCharge.epsilon, privacyCharge.delta, repetitionCount)
}
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt` line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1PAf3A3Opv0YZkuhlN:-N1PJ38U5hoiMH8m-LBK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2a00bab18dff1a45778414f8bc5e87ede414449/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Consider having this return an `Int` or `Long` and then casting to a float when needed. `Float` cannot represent many integers exactly (such as `16,777,217`). It should also perform faster if it's doing integer addition.
</blockquote></details>

Done.



_Code quote (from src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt):_
```Kotlin
coeff
```

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 37 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1ehdHS7NHkGkn8Hht9:-N1ehdHS7NHkGkn8HhtA:bao1nt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/92f1cf1ae3c9425e3e1de72ff3e3e9f534ef6aa6/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L37)):*
> ```Kotlin
> }
> 
> private fun PrivacyCharge.toChargeWithRepetitions(repetitionCount: Int = 1): ChargeWithRepetitions =
> ```

maybe get rid of a default here. It seemed non-obvious to me this would be the default.

**Review by uakyol — COMMENTED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @efoxepstein, @stevenwarejones, and @uakyol)

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @efoxepstein, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 37 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-N1ehdHS7NHkGkn8Hht9:-N1ejScm3AuBNfLkfD3k:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ffdbd6e4df08fe9447b75df8d7bc57a7e050a7f/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

maybe get rid of a default here. It seemed non-obvious to me this would be the default.
</blockquote></details>

done

**Review by uakyol — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @efoxepstein, @stevenwarejones, and @uakyol)

**Review by uakyol — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @efoxepstein, @stevenwarejones, and @uakyol)

**Review by uakyol — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557#-:-N1ejZea7LCbMLa0Excp:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @efoxepstein, @stevenwarejones, and @uakyol)

**Review by uakyol — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Pull request merged**
