### PR TITLE
Add createReport.

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #985** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/985" target="_blank">Graphite</a> 
    * **PR #992** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/992" target="_blank">Graphite</a> 
      * **PR #1004** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1004" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1004?utm_source=stack-comment).

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @jcorilla and @riemanli)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report.proto` line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NVoScBu-HpQYoD2z_LN:-NVoScBu-HpQYoD2z_LO:b8gncmi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ba151861f0b9759b6c013008247c58e595b03281/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto#L62)):*
> ```protobuf
>     STATE_UNSPECIFIED = 0;
>     // Computation is running.
>     RUNNING = 1;
> ```

State needs to be gone from the db schema too.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 215 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NVoS3621OyaYgobmjs6:-NVoS3621OyaYgobmjs7:b-7pgijc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cd09b3eb5292aa76c280c17427a7cf8ed3d251bf/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L215)):*
> ```protobuf
> 
>   // The specification of what metric to calculate
>   MetricSpec metric_spec = 4 [(google.api.field_behavior) = REQUIRED];
> ```

What part of metric spec can change

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report.proto` line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NVoScBu-HpQYoD2z_LN:-NVqZNlbAWMG-SS_vg4J:b-mikvb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ba151861f0b9759b6c013008247c58e595b03281/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto#L62)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

State needs to be gone from the db schema too.
</blockquote></details>

Thanks for reminding! Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 215 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NVoS3621OyaYgobmjs6:-NVqZlKy12CQR55BlXP5:bapbvas) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cd09b3eb5292aa76c280c17427a7cf8ed3d251bf/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L215)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

What part of metric spec can change
</blockquote></details>

`VidSamplingInterval` and the fields tagged with `optional`. If the user doesn't set those values, metrics service will fill them with the default values and return them back.

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r5, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @jcorilla and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 172 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWNswLB9fDewe6tSpPD:-NWNswLCBeJz_p-f_244:b-dkm451) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69e09b71df3e7ed176615e545c5352e8c3575d49/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L172)):*
> ```Kotlin
>         throw IllegalArgumentException("The metric type in Metric is not specified.")
>     }
>     if (source.hasVidSamplingInterval()) {
> ```

Right now, the schema has VidSamplingIntervalStart and VIdSamplingIntervalWidth as NOT NULL so I always put and retrieve the values so there will always be a vidSamplingInterval.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 491 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWNtyXx0urtcRItJsoN:-NWNtyXx0urtcRItJsoO:b1nbldw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69e09b71df3e7ed176615e545c5352e8c3575d49/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L491)):*
> ```Kotlin
>   InternalMetricSpec.DifferentialPrivacyParams {
>   val source = this
>   return InternalMetricSpecKt.differentialPrivacyParams {
> ```

Epilson and delta are numbers so they are set by default.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report.proto` line 42 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWNrmBY3QvHyArIBv7B:-NWNrmBZB9kKJcVQJUe6:b-p3es3c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69e09b71df3e7ed176615e545c5352e8c3575d49/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto#L42)):*
> ```protobuf
>     // Will be filled by the internal reports service. Use the request ID above
>     // to find the metric.
>     fixed64 external_metric_id = 2;
> ```

Hmm, external_metric_id isn't really part of the createMetricRequest. Perhaps a new message that includes CreateMetricRequest as one field and external_metric_id as another?

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 172 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWNswLB9fDewe6tSpPD:-NWO-5QI8pR4aD8k_Ocy:bqb8mnb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69e09b71df3e7ed176615e545c5352e8c3575d49/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L172)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Right now, the schema has VidSamplingIntervalStart and VIdSamplingIntervalWidth as NOT NULL so I always put and retrieve the values so there will always be a vidSamplingInterval.
</blockquote></details>

I see. Then it's a problem for `epsilon` and `delta` as well. 

We either remove the NOT NULL constraints on the database schema or enforce substitution of default values on the reports service.
I am not sure how difficult it is to do the former option. For the latter one, it will need to do the same thing as in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1316, which I don't know if there is a good way to avoid duplicate code.

Any suggestion?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 491 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWNtyXx0urtcRItJsoN:-NWNzMUQAe0mkdlE64kN:bhtbfjr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69e09b71df3e7ed176615e545c5352e8c3575d49/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L491)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Epilson and delta are numbers so they are set by default.
</blockquote></details>

Epsilon and delta are tagged with `optional` so they have explicit presence. See https://protobuf.dev/programming-guides/field_presence/#how-to-enable-explicit-presence-in-proto3.

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @jcorilla and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 172 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWNswLB9fDewe6tSpPD:-NWOIujg5iR_VcNadzzw:b-1nd242) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69e09b71df3e7ed176615e545c5352e8c3575d49/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L172)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I see. Then it's a problem for `epsilon` and `delta` as well. 

We either remove the NOT NULL constraints on the database schema or enforce substitution of default values on the reports service.
I am not sure how difficult it is to do the former option. For the latter one, it will need to do the same thing as in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1316, which I don't know if there is a good way to avoid duplicate code.

Any suggestion?
</blockquote></details>

It is easy to drop NOT NULL constraints

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 172 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWNswLB9fDewe6tSpPD:-NWPFBL-8IM_KkYCL8CX:b-qjwa5f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69e09b71df3e7ed176615e545c5352e8c3575d49/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L172)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It is easy to drop NOT NULL constraints
</blockquote></details>

I realized the metric spec in `v2/Report.CreateMetricRequest` (`ReportingMetric` now) doesn't make sense. The internal report is created first when there is no corresponding metric, so there is no place to store that metric spec unless we store it in `MetricCalculationSpecMetrics` table, but I think that will be too complicated.

I think the latter option is easier to maintain and understand. Please see the corresponding changes in this PR and https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1041.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report.proto` line 42 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWNrmBY3QvHyArIBv7B:-NWmquSpDioXVr6lV7qD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69e09b71df3e7ed176615e545c5352e8c3575d49/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto#L42)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Hmm, external_metric_id isn't really part of the createMetricRequest. Perhaps a new message that includes CreateMetricRequest as one field and external_metric_id as another?
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, 1 of 7 files at r5, 2 of 7 files at r8, 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @jcorilla, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report.proto` line 39 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWs5H6fEpignC3oDjyB:-NWs5H6fEpignC3oDjyC:b-hhsqw2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d4ded3bd3f06d41b4e2456b4b5c557207b3b625/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto#L39)):*
> ```proto
>     // is no metric can be found based on the metric config from 3-6, generate a
>     // new UUID. (2) When a corresponding metric is found, fill its request ID.
>     string request_id = 1;
> ```

Be more explicit what this is the request ID for, both in the name and in the documentation. Recall that the first line of any field/method documentation should be a summary fragment, e.g. "Request ID for the CreateMetric method."



_Suggestion:_
```proto
create_metric_request_id
```
___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 400 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWs6OoG89I_I9kCmzeH:-NWs6OoG89I_I9kCmzeI:bw6yj10) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d4ded3bd3f06d41b4e2456b4b5c557207b3b625/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L400)):*
> ```TSQL
>   -- Report.CreateMetricRequest which do not need to be indexed by the database.
>   --
>   -- See org.wfanet.measurement.internal.reporting.Report.CreateMetricRequest.Details
> ```

Message doesn't exist. Is this what you meant?



_Suggestion:_
```TSQL
ReportingMetric
```
___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 400 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWs6_liEbS0tSqQqRqA:-NWs6_ljBU9WMEW1QoyZ:bfb0drk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d4ded3bd3f06d41b4e2456b4b5c557207b3b625/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L400)):*
> ```TSQL
>   -- Report.CreateMetricRequest which do not need to be indexed by the database.
>   --
>   -- See org.wfanet.measurement.internal.reporting.Report.CreateMetricRequest.Details
> ```

org.wfanet is for the Java package.



_Suggestion:_
```TSQL
wfa
```

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @jcorilla, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report.proto` line 39 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWs5H6fEpignC3oDjyB:-NWsQdj74cpTxkQOx8Ik:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d4ded3bd3f06d41b4e2456b4b5c557207b3b625/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Be more explicit what this is the request ID for, both in the name and in the documentation. Recall that the first line of any field/method documentation should be a summary fragment, e.g. "Request ID for the CreateMetric method."
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 400 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWs6OoG89I_I9kCmzeH:-NWsGi9G38y8yKuUGK0Q:b-zf5xbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d4ded3bd3f06d41b4e2456b4b5c557207b3b625/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L400)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Message doesn't exist. Is this what you meant?
</blockquote></details>

Thanks for catching it! Fixed.
___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 400 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWs6_liEbS0tSqQqRqA:-NWsHEuUBxucNJAbZeMU:bv40d2q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d4ded3bd3f06d41b4e2456b4b5c557207b3b625/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L400)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

org.wfanet is for the Java package.
</blockquote></details>

Thanks for pointing it out. Modified this and the others in the file.

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 4 of 7 files at r8, 1 of 3 files at r9, 3 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @jcorilla and @SanjayVas)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 8 of 9 files reviewed, 7 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 385 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWssXY65dAd7XrzQ-Aw:-NWssXY65dAd7XrzQ-Ax:b-p4xwdv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b484f284ea040fcb55050cc73db4d79bcda2fda/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L385)):*
> ```Kotlin
> 
>   @Test
>   fun `createReport returns report with two metrics when there are two groupings`() = runBlocking {
> ```

There could be one more test that covers the fanout. Something like 2 groupings and 3 time intervals creates 6 metrics.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 1228 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWsk7sxDUsEkZasiv_9:-NWsk7sxDUsEkZasiv_A:bajl18k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b484f284ea040fcb55050cc73db4d79bcda2fda/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L1228)):*
> ```Kotlin
>     val requestId = "0"
> 
>     val (internalRequestingReport, internalInitialReport, internalPendingReport) = INTERNAL_REPORTS
> ```

These whenever blocks look the same as the top level mocking. 
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 1329 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWsdddvDp0-DDWO9v8y:-NWsdddvDp0-DDWO9v8z:bvrtt4l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b484f284ea040fcb55050cc73db4d79bcda2fda/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L1329)):*
> ```Kotlin
> 
>   @Test
>   fun `createReport throws PERMISSION_DENIED when report doesn't belong to caller`() {
> ```

How is this test different from the one above it.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 1424 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWsejt69UzPhTdLKsZ7:-NWsejt69UzPhTdLKsZ8:b-x22gok) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b484f284ea040fcb55050cc73db4d79bcda2fda/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L1424)):*
> ```Kotlin
> 
>   @Test
>   fun `createReport throws INVALID_ARGUMENT when TimeIntervals is set and cumulative is true`() {
> ```

Should explicitly set TimeIntervals

**Review by SanjayVas — APPROVED** [review]
API changes approved.

> Reviewed 2 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-:-NWt8AaC739NtEJtIVmq:blpzyjz)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @jcorilla and @riemanli)

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @jcorilla, @SanjayVas, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 385 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWssXY65dAd7XrzQ-Aw:-NWtAjxV38aMl-V74v34:b-v3vaxy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b484f284ea040fcb55050cc73db4d79bcda2fda/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L385)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

There could be one more test that covers the fanout. Something like 2 groupings and 3 time intervals creates 6 metrics.
</blockquote></details>

Thanks for the suggestion. I wonder how comprehensive you want it to be. I added one unit test with 2 metric specs, 2 time intervals, and 2 groupings. Adding additional dimensions like multiple reporting sets or multiple `MetricCalculationSpec`s will make the unit test very complicated. 
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 1228 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWsk7sxDUsEkZasiv_9:-NWt9e7901V3bngEbDJi:b-4grvzq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b484f284ea040fcb55050cc73db4d79bcda2fda/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L1228)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

These whenever blocks look the same as the top level mocking. 
</blockquote></details>

Good catch! Removed.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 1329 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWsdddvDp0-DDWO9v8y:-NWtAJ132O1XFccv_cxq:bufe44r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b484f284ea040fcb55050cc73db4d79bcda2fda/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L1329)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

How is this test different from the one above it.
</blockquote></details>

Thanks for catching this. You're right. It's duplicate. Removed.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 1424 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWsejt69UzPhTdLKsZ7:-NWtAgt0ClcWkyT0Mu2C:b-xu0uci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b484f284ea040fcb55050cc73db4d79bcda2fda/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L1424)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Should explicitly set TimeIntervals
</blockquote></details>

Thanks for the suggestion. Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @jcorilla and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 385 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWssXY65dAd7XrzQ-Aw:-NWtTVbS3VsgbaQ1MUOk:b-vy5qny) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b484f284ea040fcb55050cc73db4d79bcda2fda/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L385)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for the suggestion. I wonder how comprehensive you want it to be. I added one unit test with 2 metric specs, 2 time intervals, and 2 groupings. Adding additional dimensions like multiple reporting sets or multiple `MetricCalculationSpec`s will make the unit test very complicated. 
</blockquote></details>

That is good enough. Anything more complicated could be covered in the integration tests.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @jcorilla and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt` line 385 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004#-NWssXY65dAd7XrzQ-Aw:-NWtTzLF2pleIWhcVUZx:b-ucfknh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b484f284ea040fcb55050cc73db4d79bcda2fda/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt#L385)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

That is good enough. Anything more complicated could be covered in the integration tests.
</blockquote></details>

Thanks!

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla and @SanjayVas)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 2 of 7 files at r8, 2 of 3 files at r9, 3 of 4 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla, @SanjayVas, and @stevenwarejones)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla, @SanjayVas, and @stevenwarejones)

**Review by riemanli — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 1 of 3 files at r9, 2 of 4 files at r10, 1 of 1 files at r12, 3 of 4 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1004)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla, @SanjayVas, and @stevenwarejones)

**Pull request merged**
