### PR TITLE
Compare the results within some tolerance since we have DP noises.

### PR DESCRIPTION
**Pull request by wangyaopw**
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F607228901955&view=2c2927c0-626b-4740-8620-af2a93b7d623

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/272)

### CODE REVIEW

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/272)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 157 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/272#-MjVIPNz49Mz35pUA9pb:-MjVIPNz49Mz35pUA9pc:brl96io) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/768480e1f5c3f56dc3ca83ca481b8eacf5a53bd3/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L157)):*
> ```
>     // TODO: use Kotlin's assertEquals with absoluteTolerance when Kotlin 1.5 is supported.
> ```
Why not Truth? https://truth.dev/floating_point

We use Kotlin assertions for booleans and exceptions, and Truth for everything else.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/272)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 157 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/272#-MjVIPNz49Mz35pUA9pb:-MjVLENsBfkUfo_88-EB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/768480e1f5c3f56dc3ca83ca481b8eacf5a53bd3/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L157)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     // TODO: use Kotlin's assertEquals with absoluteTolerance when Kotlin 1.5 is supported.
> ```
Why not Truth? https://truth.dev/floating_point

We use Kotlin assertions for booleans and exceptions, and Truth for everything else.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
