### PR TITLE
Log state transition to SUCCEEDED for MPC Measurements.

### LINKED ISSUE #1612: Internal Measurement state transitions to SUCCEEDED are not logged for MPC computations
**Describe the bug**
The StateTransitionMeasurementLogEntries table does not have any transitions from `PENDING_COMPUTATION` to `SUCCEEDED` even when there are succeeded MPC measurements. It appears that there's no write to the table in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt.

**Component(s) affected**
Kingdom

**Version**
v0.5.4, HEAD

### PR DESCRIPTION
**Pull request by SanjayVas**
Closes #1612

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1621)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1621)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt` line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1621#-Nxxggs67U5wO-nOd1WD:-Nxxggs67U5wO-nOd1WE:b-bux09r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2435736929a199fe05eece0c8573f028fe8f3cd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt#L101)):*
> ```Kotlin
>       nextState = NEXT_MEASUREMENT_STATE,
>       previousState = measurement.state,
>       measurementLogEntryDetails = MeasurementLogEntryKt.details { logMessage = "Succeeded" },
> ```

nit: `"Measurement.STATE is now $NEXT_MEASUREMENT_STATE"`

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1621)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1621)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1621)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt` line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1621#-Nxxggs67U5wO-nOd1WD:-Ny20E_t2b8ReWd-zL3N:bsmk2rs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2435736929a199fe05eece0c8573f028fe8f3cd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt#L101)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Done.

The suggestion would be inconsistent with the log messages for all other Measurement state transitions, so updated to one that would be consistent.
</blockquote></details>

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ef4b15007ef7fc20a6d5483d1dceaa77b95958a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt#L133 uses that but I think its fine

**Pull request merged**
