### PR TITLE
Adding Hello World React app to the reporting UI

### PR DESCRIPTION
**Pull request by bdomen-ggl**
Adding a basic React app to the repo with full bazel support.

Notes:
- Using `pnpm` to better manage a monorepo of JS apps. The root config will have common packages. Each app can override/add their own as they need as well as additional configuration.
- Using `gts` as a linting/prettify tool. It wraps `eslint` and `prettifier`.
- Using `webpack` with `babel` to bundle and transpile TSX/TS. `react-scripts` was limited in its configuration to setup in a monorepo. Specifically it assumes the index is at `public/index.html` and not in a subdirectory. It also outputs files to a hardcoded root, which can cause problems if we have multiple apps. Also it's doing a lot of hand waving that may have issues like browser compatibility.

Future PRs:
- Add linter to the build (the tool, gts, and configs are currently in place but not being run anywhere)
- Finish moving the tests (moved them out of the src directory, but working on getting jest configured)
- Replace the basic React app with our Reporting app.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033)

**Comment by bdomen-ggl** [comment]
@SanjayVas Just looking to see if this seems like about the right approach. This code is just adding the sample hello world (ie. create-react-app) with only some modifications to make it buildable via bazel and removing some of the icons. I'll need to review how we plan to deploy this later.

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033)* status: 2 of 23 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NWmqeV47-k1mo-pXHN_:-NXBRPQqAU-bZgRIcB21:bvohk58) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

How important is the React directory structure? e.g. is it difficult to not have the entire app under the same tree?

If we need to keep the same directory structure for the app, I'd recommend putting this under `src/main/react` to indicate that this is fully framework-specific. If it's really flexible on the structure then move the files around according to language, e.g Typescript source goes under `src/main/typescript`.

The big thing is putting tests under the `src/test` tree and not under `src/main` if at all possible.
</blockquote></details>

The directory structure can technically be flexible. It's most common nowadays to have everything under one project based directory. It's been a while, but I'll try to split up the directory structure as you mentioned with `src/main/typescript` and `src/test`.

___
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/reporting-ui/patches/jest-haste-map+26.6.2.patch` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NWmpwHN4kb_CjlAvYeI:-NXBRm2O76YeiYsNNhBS:b-n3e8ez) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2001e2e1310d26e23b5b34e60f7d0c223526e2a5/src/main/kotlin/org/wfanet/measurement/reporting/reporting-ui/patches/jest-haste-map%2B26.6.2.patch#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should go somewhere under `//build` since it's a patch for a repo target.
</blockquote></details>

Yep thanks. Was just copying these all over from the react bazel example directory (and modifying to make them work). I can definitely move this over as part of this initial code.

**Comment by bdomen-ggl** [comment]
*[`build/repositories.bzl` line 117 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NWmpEeQ01ioAjTcYkS3:-NYTaXASBfual4BpLiVn:b-1h83e5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2001e2e1310d26e23b5b34e60f7d0c223526e2a5/build/repositories.bzl#L117)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that this is changing to `rules_nodejs` in the upcoming 6.x release. See https://bazelbuild.github.io/rules_nodejs/#deprecated-modules
</blockquote></details>

Thanks, changed to use the recommended aspect rules

**Review by bdomen-ggl — COMMENTED** [review]
@SanjayVas Ready for another look over. Had some struggles getting aspect_js/ts/jest working compared to the bazel build rules. Also saw that the `react-scripts` is more to help setup a hello-world react app and doesn't work well in monorepos, so I switched to using pnpm (to manage npm in. monorepos better) with webpack (to help bundle the code and make a local dev server). I haven't used pnpm before, but it seemed like it's best to keep common packages in the root package.json and include app specific packages in their own package.json.

Still working on getting the linter and basic smoke-test working and a bit of cleanup.

I ended up moving everything into `/src/main/react` since reconfiguring to split out `src` and `test` will be more work. I can look at that in a follow up task if we really want to keep them separate. Most frontend code puts them next to each other, but uses tree shaking to not include tests for production bundles.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-:-NYT_HzD8hysGqxeylMH:b-eeu3s4)* status: 0 of 46 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> I ended up moving everything into `/src/main/react` since reconfiguring to split out `src` and `test` will be more work. I can look at that in a follow up task if we really want to keep them separate. Most frontend code puts them next to each other, but uses tree shaking to not include tests for production bundles.

We really do want the trees to be separate. We want the separation of tests to be both very clear in the structure as well as map into Bazel (Bazel should be able to keep track of what needs to be built purely from the BUILD tree, whereas any tree-shaking would happen after Bazel already called the tool).

> Reviewed 41 of 45 files at r2, 4 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-:-NYTpOTlCmXKttKSFYeo:bw9xznw)* status: 34 of 46 files reviewed, 6 unresolved discussions (waiting on @bdomen-ggl)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NWmqeV47-k1mo-pXHN_:-NYTqEOd-WKerJ2i6Gcf:b54w2p7) (no related file):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

The directory structure can technically be flexible. It's most common nowadays to have everything under one project based directory. It's been a while, but I'll try to split up the directory structure as you mentioned with `src/main/typescript` and `src/test`.
</blockquote></details>

Marking as resolved for now to be followed up on later.

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NYTrbgP30J4yPsBKMYR:-NYTrbgP30J4yPsBKMYS:b-56x5ll) (no related file):*
We should update our [lint action](https://github.com/world-federation-of-advertisers/actions/blob/main/lint/lint.sh) to cover the new file formats we're adding. I think clang-format can handle JS. We probably want to integrate [Prettier](https://prettier.io/) for other web languages.

We also need to update the dev guide accordingly indicating the formatters/linters used and any style guides. e.g. we need to decide on whether TypeScript code follows https://google.github.io/styleguide/tsguide.html or some other style guide.

___
___
*[`src/main/react/reporting-ui/BUILD.bazel` line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NYTqqix-NdMy8tZGnDx:-NYTqqix-NdMy8tZGnDy:b-vdpros) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f791c052f718f30ff957e719242ab5822eeaff16/src/main/react/reporting-ui/BUILD.bazel#L9)):*
> ```Starlark
> npm_link_all_packages()
> 
> BUILD_NODE_DEPS = [
> ```

Why is this in a separate constant if it's only referenced by one target?
___
*[`src/main/react/reporting-ui/public/BUILD.bazel` line 5 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NYTtfrH50-OiqEzpVt_:-NYTtfrH50-OiqEzpVta:b-adif1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f791c052f718f30ff957e719242ab5822eeaff16/src/main/react/reporting-ui/public/BUILD.bazel#L5)):*
> ```Starlark
> js_library(
>     name = "public",
>     srcs = glob(["**"]),
> ```

All files? Not just `*.js`?



_Code quote:_
```Starlark
glob(["**"])
```
___
*[`src/main/react/reporting-ui/src/BUILD.bazel` line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NYTv-yq8scMeSuBwnmP:-NYTv-yq8scMeSuBwnmQ:b3j5s1b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f791c052f718f30ff957e719242ab5822eeaff16/src/main/react/reporting-ui/src/BUILD.bazel#L64)):*
> ```Starlark
>     declaration = True,
>     resolve_json_module = True,
>     supports_workers = False,  # worker bug on macos: ERROR: react-cra/src/BUILD.bazel:50:11: output 'src/App.test.js' was not created
> ```

We don't support building on MacOS. Was this copied from somewhere?



_Code quote:_
```Starlark
# worker bug on macos: ERROR
```
___
*[`src/main/react/reporting-ui/README.md` line 5 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NYTtIlg5rYwiLfgW9lj:-NYTtIlh2naneigM3rbB:bgfjxq7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2fb3615aa2492a63e487665d01c073ecb3e0e21d/src/main/react/reporting-ui/README.md#L5)):*
> ```Markdown
> ## Available Scripts
> 
> Just like with stock create-react-app, we have the same developer workflow. In the project directory, you can run:
> ```

Is this accurate? I would figure we'd have to use a Bazel target. Also does "project directory" here mean `reporting-ui`, or the Bazel workspace root (where we run all other commands)?

**Review by bdomen-ggl — COMMENTED** [review]
Ah I see. Don't think it'll be TOO bad to move out the tests. Just been a good while since I've seen them setup that way since they're usually put side-by-side these days.

Also @SanjayVas, ready for a full review. Will update the linting script and add tests as follow up PRs.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-:-NYU19qd2URDeopT-t4M:btdfhjc)* status: 24 of 49 files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/react/reporting-ui/BUILD.bazel` line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NYTqqix-NdMy8tZGnDx:-NYTzzx51ur16tXRnl3G:b-3ldxzp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f791c052f718f30ff957e719242ab5822eeaff16/src/main/react/reporting-ui/BUILD.bazel#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this in a separate constant if it's only referenced by one target?
</blockquote></details>

Was referenced by multiple targets, but ended up moving things around. Still going through some detailed cleanup.
___
*[`src/main/react/reporting-ui/public/BUILD.bazel` line 5 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NYTtfrH50-OiqEzpVt_:-NYU-wls36cizURbSneZ:b-o1cakd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f791c052f718f30ff957e719242ab5822eeaff16/src/main/react/reporting-ui/public/BUILD.bazel#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

All files? Not just `*.js`?
</blockquote></details>

It should be pulling in other files like index.html and favicon.ico, but bundle them up so they can be consumed by webpack for bundling. It could be more specific rather than grab everything. I can also revisit, but was running into issues (I think it was more with the .tsx files with the ts_project rule) where everything wasn't getting grabbed or bundled in the right way. Also the `public` folder will only have a few stock files and should never have anything else added to it. Any additions should be managed in `src` or on a file server.
___
*[`src/main/react/reporting-ui/src/BUILD.bazel` line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NYTv-yq8scMeSuBwnmP:-NYU0gWy2lK24edx0Vae:b-53bdp9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f791c052f718f30ff957e719242ab5822eeaff16/src/main/react/reporting-ui/src/BUILD.bazel#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We don't support building on MacOS. Was this copied from somewhere?
</blockquote></details>

Yes, this target was copied from a create-react-app example. I'm looking into the linting and testing targets right now. I'm going to split them into another PR or two to be more incremental.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/reporting-ui/patches/jest-haste-map+26.6.2.patch` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NWmpwHN4kb_CjlAvYeI:-NYU1-id7tUkdeFdB8TC:bm8m5r1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2001e2e1310d26e23b5b34e60f7d0c223526e2a5/src/main/kotlin/org/wfanet/measurement/reporting/reporting-ui/patches/jest-haste-map%2B26.6.2.patch#L1)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Yep thanks. Was just copying these all over from the react bazel example directory (and modifying to make them work). I can definitely move this over as part of this initial code.
</blockquote></details>

Ended up not using this since it was something for react-scripts, which I opted out of. So I just removed it.
___
*[`src/main/react/reporting-ui/README.md` line 5 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NYTtIlg5rYwiLfgW9lj:-NYU-CLC2IhN218QTqUC:bt235ku) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2fb3615aa2492a63e487665d01c073ecb3e0e21d/src/main/react/reporting-ui/README.md#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this accurate? I would figure we'd have to use a Bazel target. Also does "project directory" here mean `reporting-ui`, or the Bazel workspace root (where we run all other commands)?
</blockquote></details>

Most of these files (reporting-ui/, reporting-ui/src, reporting-ui/public) are verbatim copied from a couple examples just to make sure the Bazel-fication worked correctly. The only things not copied are anything build related (basically all the configs. Even some of the configs and BUILD targets were copied or only barely modified to get things to work. I'll be completely redoing the README when I move from the sample code to our actual code.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r3, 11 of 20 files at r6, 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033)* status: all files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl)

___
*[`src/main/react/reporting-ui/jest.config.js` line 1 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NY_0grn38rh7fy_X39b:-NY_0grn38rh7fy_X39c:bggmrdt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/74a5952c441c83ee3c19be64951e665f027b7d39/src/main/react/reporting-ui/jest.config.js#L1)):*
> ```JavaScript
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

This year doesn't look correct.



_Code quote:_
```JavaScript
2021
```
___
*[`src/main/react/reporting-ui/README.md` line 5 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NYTtIlg5rYwiLfgW9lj:-NY_0wsE20rUzBae__oC:bsdve12) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2fb3615aa2492a63e487665d01c073ecb3e0e21d/src/main/react/reporting-ui/README.md#L5)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Most of these files (reporting-ui/, reporting-ui/src, reporting-ui/public) are verbatim copied from a couple examples just to make sure the Bazel-fication worked correctly. The only things not copied are anything build related (basically all the configs. Even some of the configs and BUILD targets were copied or only barely modified to get things to work. I'll be completely redoing the README when I move from the sample code to our actual code.
</blockquote></details>

Would you mind deleting the parts of the README that really don't apply so we don't have anything misleading? I assume everything related to `yarn` here won't work or shouldn't be attempted.

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033)* status: all files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NYTrbgP30J4yPsBKMYR:-NYdHeoWEsTLvhCEvq3T:bjhuwnn) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We should update our [lint action](https://github.com/world-federation-of-advertisers/actions/blob/main/lint/lint.sh) to cover the new file formats we're adding. I think clang-format can handle JS. We probably want to integrate [Prettier](https://prettier.io/) for other web languages.

We also need to update the dev guide accordingly indicating the formatters/linters used and any style guides. e.g. we need to decide on whether TypeScript code follows https://google.github.io/styleguide/tsguide.html or some other style guide.
</blockquote></details>

Will do as a follow up PR. The linting is working with `gts` (`eslint` under the hood). I'll have to figure out how to plug it in here.

___
___
*[`src/main/react/reporting-ui/jest.config.js` line 1 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NY_0grn38rh7fy_X39b:-NYdHN3uED2zc2-PdHtt:b-xhynq0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/74a5952c441c83ee3c19be64951e665f027b7d39/src/main/react/reporting-ui/jest.config.js#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This year doesn't look correct.
</blockquote></details>

Yep, I forgot to change the year for a few files. Looks like I missed this one when I was going back. Thanks.
___
*[`src/main/react/reporting-ui/README.md` line 5 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033#-NYTtIlg5rYwiLfgW9lj:-NYdHXXB8Imu7GVNYUXy:busd1y2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2fb3615aa2492a63e487665d01c073ecb3e0e21d/src/main/react/reporting-ui/README.md#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Would you mind deleting the parts of the README that really don't apply so we don't have anything misleading? I assume everything related to `yarn` here won't work or shouldn't be attempted.
</blockquote></details>

Sure, I'll rewrite it since most of it is `yarn` scripts anyways.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 22 of 45 files at r2, 2 of 14 files at r3, 10 of 20 files at r6, 11 of 13 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl and @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1033)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl)

**Pull request merged**
