### PR TITLE
feat: Implement Access GetPrincipal and UpdateRole 

### PR DESCRIPTION
**Pull request by SanjayVas**
These two methods are being implemented first to demonstrate the general pattern and make it easier for another engineer to implement the rest.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1954)

**Comment by SanjayVas** [comment]
Depends on #1953

**Comment by SanjayVas** [comment]
Depends on #1953

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1954)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
