### PR TITLE
feat: set up measurement prober flags

### PR DESCRIPTION
**Pull request by roaminggypsy**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @roaminggypsy)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/ProberMeasurementCreation.kt` line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5yoTWaAkV5sFUwFMMG:-O5yoTWaAkV5sFUwFMMH:bqajsne) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/batch/ProberMeasurementCreation.kt#L20)):*
> ```Kotlin
> 
> class ProberMeasurementCreation() {
>   fun run() {}
> ```

nit: leave a TODO here so it's clear this needs to be implemented (as opposed to being left intentionally empty)
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5yqu3F369xUDwFrvP7:-O5yqu3G5t2OvvdgrOxm:brzst41) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L56)):*
> ```Kotlin
> 
>   @Option(
>     names = ["--data-providers"],
> ```

We use singular flag names for collections and indicate that they can be specified more than once in the description. Although Picocli supports both, we want the usage to be `--data-provider=one --data-provider=two` rather than `--data-providers=one,two`



_Suggestion:_
```Kotlin
--data-provider
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5ypXhC3ykh1IiHvKnZ:-O5ypXhC3ykh1IiHvKn_:b-f1nt5y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L65)):*
> ```Kotlin
>   @Option(
>     names = ["--simulator-event-group-name"],
>     description = ["QA event group name to use for requisitions and measurements"],
> ```

The description should include what happens when this is specified.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5yqi8L2fzu1aonhf0H:-O5yqi8L2fzu1aonhf0I:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L78)):*
> ```Kotlin
>     required = true,
>   )
>   lateinit var measurementLookbackDuration: String
> ```





_Suggestion:_
```Kotlin
Duration
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 89 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5yqkEJ1PJreSOhr78_:-O5yqkEK4mzTUYDE2heH:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L89)):*
> ```Kotlin
>     required = true,
>   )
>   lateinit var durationBetweenMeasurement: String
> ```





_Suggestion:_
```Kotlin
Duration
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5yqWvA-LRal_DPV_WQ:-O5yqWvA-LRal_DPV_WR:bvajsod) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L93)):*
> ```Kotlin
> 
> @Command(
>   name = "ProberMeasurementCreationJob",
> ```

I think this can just be called "MeasurementSystemProberJob". The design doc implies that a single job is taking care of measurement creation, verification, and metrics.

**Review by roaminggypsy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5yqu3F369xUDwFrvP7:-O5zB6qr53PM0yDXk05m:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We use singular flag names for collections and indicate that they can be specified more than once in the description. Although Picocli supports both, we want the usage to be `--data-provider=one --data-provider=two` rather than `--data-providers=one,two`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5ypXhC3ykh1IiHvKnZ:-O5zB7q9CgujD1K6yr7U:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The description should include what happens when this is specified.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5yqi8L2fzu1aonhf0H:-O5zB8Qf1t0Zkq9cvaRb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L78)):*
> ```Kotlin
>     required = true,
>   )
>   lateinit var measurementLookbackDuration: String
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 89 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5yqkEJ1PJreSOhr78_:-O5zB8jzAkARhpD8KlUe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L89)):*
> ```Kotlin
>     required = true,
>   )
>   lateinit var durationBetweenMeasurement: String
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5yqWvA-LRal_DPV_WQ:-O5zB9DD8OeDQFSmFaac:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think this can just be called "MeasurementSystemProberJob". The design doc implies that a single job is taking care of measurement creation, verification, and metrics.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @roaminggypsy)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5yqWvA-LRal_DPV_WQ:-O5zHWJe65WAXOU46Kub:b-69lv78) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L93)):*
<details><summary><i>Previously, roaminggypsy (Lin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Need to also rename the class in the `batch` package.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 92 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5zHNxjCPnvOpGRBPVY:-O5zHNxk76pdyNhn_Gm1:b-p9m8m2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5b97ebb650f263b31edc9a788c6d9398831c203/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L92)):*
> ```Kotlin
>     required = true,
>   )
>   var measurementLookbackDuration: Duration = 1.days
> ```

Default should be specified using the `defaultValue` attribute of the `@Option` annotation. We have a converter that gets registered for handling human-readable durations, so this can be specified using `defaultValue = "1d"`



_Suggestion:_
```Kotlin
  lateinit var measurementLookbackDuration: Duration
    private set
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5zHJ1z66qsyBRibF0W:-O5zHJ1z66qsyBRibF0X:bacjp6u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5b97ebb650f263b31edc9a788c6d9398831c203/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L103)):*
> ```Kotlin
>     required = true,
>   )
>   var durationBetweenMeasurement: Duration = 1.hours
> ```

Same here re: defaults



_Code quote:_
```Kotlin
1.hours
```

**Review by roaminggypsy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5yqWvA-LRal_DPV_WQ:-O62hewn76CotdIhA1or:b8jaasq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dfa30f4fb3b41e9dedb1d4be71277fb1058e75b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Need to also rename the class in the `batch` package.
</blockquote></details>

Update the name of both classes and files to make it consistent.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 92 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5zHNxjCPnvOpGRBPVY:-O62h_Fh5ugxc4S1QBuu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5b97ebb650f263b31edc9a788c6d9398831c203/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L92)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Default should be specified using the `defaultValue` attribute of the `@Option` annotation. We have a converter that gets registered for handling human-readable durations, so this can be specified using `defaultValue = "1d"`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt` line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791#-O5zHJ1z66qsyBRibF0W:-O62hdwd6l3WYi7kjJAh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5b97ebb650f263b31edc9a788c6d9398831c203/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ProberMeasurementCreationJob.kt#L103)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here re: defaults
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1791)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)

**Pull request merged**
