### PR TITLE
Use Make variable strings in build/variables.bzl.

### PR DESCRIPTION
**Pull request by SanjayVas**
This allows these values to be specified on the Bazel command-line. Per-run configuration should never be under version control.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)

### CODE REVIEW

**Review by wangyaopw — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[.github/workflows/build-test.yml, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410#-MrYzzU-7sLN7odQZQfo:-MrYzzU-7sLN7odQZQfp:bfv2xc2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a66024e2e166f74ccf83593ef6d81f4b47c9e800/.github/workflows/build-test.yml#L39)):*
> ```YAML
>           build-options: |
>             --host_platform=//build/platforms:ubuntu_18_04
>             --define=container_registry=gcr.io
> ```

delete `gcr.io` and `halo-cmm-dev`?



_Code quote:_
```YAML
gcr.io
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[.github/workflows/build-test.yml, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410#-MrYzzU-7sLN7odQZQfo:-MrZ8dPF1ym2Jn8IjFwD:b6o8bwd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a66024e2e166f74ccf83593ef6d81f4b47c9e800/.github/workflows/build-test.yml#L39)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

delete `gcr.io` and `halo-cmm-dev`?
</blockquote></details>

This is just copying what was in the checked-in version of variables.bzl. I don't care either way what values we end up having here, as they're just used to satisfy the build. They would only have an effect on target run.

Your preference is to just have these be blank as well?

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[.github/workflows/build-test.yml, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410#-MrYzzU-7sLN7odQZQfo:-MrZ9e3WAaZv4BWKCnzG:b-u8w810) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a66024e2e166f74ccf83593ef6d81f4b47c9e800/.github/workflows/build-test.yml#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is just copying what was in the checked-in version of variables.bzl. I don't care either way what values we end up having here, as they're just used to satisfy the build. They would only have an effect on target run.

Your preference is to just have these be blank as well?
</blockquote></details>

I slightly prefer defining all these 7 values to `TBD`.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[.github/workflows/build-test.yml, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410#-MrYzzU-7sLN7odQZQfo:-MrZArkV8m1RRyczXHi2:b-2210cd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a66024e2e166f74ccf83593ef6d81f4b47c9e800/.github/workflows/build-test.yml#L39)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I slightly prefer defining all these 7 values to `TBD`.
</blockquote></details>

I went with blanks. TBD implies that we'll eventually have a real value to put in (and should likely have an accompanying TODO).

**Review by wangyaopw — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[.github/workflows/build-test.yml, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410#-Mrc0JML1-CrmxoJTStY:-Mrc0JML1-CrmxoJTStZ:b-49goep) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d42a9935278e862d1f311120bcb2dfad4cf8804/.github/workflows/build-test.yml#L39)):*
> ```YAML
>           build-options: |
>             --host_platform=//build/platforms:ubuntu_18_04
>             --define=container_registry=
> ```

should this just be in a bazel config file? `build-test.bazelrc`?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[.github/workflows/build-test.yml, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410#-Mrc0JML1-CrmxoJTStY:-MrcQgTwD7HohIl2wZgp:b-rimh5o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d42a9935278e862d1f311120bcb2dfad4cf8804/.github/workflows/build-test.yml#L39)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should this just be in a bazel config file? `build-test.bazelrc`?
</blockquote></details>

Not sure what the benefit is, since then we'd still have to specify `--bazelrc` here to point to that file.

All of our other bazelrc files are used unconditionally (imported from the workspace .bazelrc) and just broken up for organizational purposes. This one would be only used for this workflow.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[.github/workflows/build-test.yml, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410#-Mrc0JML1-CrmxoJTStY:-MrcglMrE5NlYXSA1JKV:bihku80) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6026088a3bd0c53655a8ea64ab772a0928cde3b/.github/workflows/build-test.yml#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not sure what the benefit is, since then we'd still have to specify `--bazelrc` here to point to that file.

All of our other bazelrc files are used unconditionally (imported from the workspace .bazelrc) and just broken up for organizational purposes. This one would be only used for this workflow.
</blockquote></details>

it just puts all the different build flags in one place vs scattered in yaml and also in .bazelrc files. Are you opposed to doing it that way?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @stevenwarejones and @wangyaopw)

___
*[.github/workflows/build-test.yml, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410#-Mrc0JML1-CrmxoJTStY:-Mrcq-G22IdxFEK7tXRY:b6slzez) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6026088a3bd0c53655a8ea64ab772a0928cde3b/.github/workflows/build-test.yml#L39)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

it just puts all the different build flags in one place vs scattered in yaml and also in .bazelrc files. Are you opposed to doing it that way?
</blockquote></details>

I went ahead and [tagged these targets as manual](https://docs.bazel.build/versions/4.2.2/be/common-definitions.html#common.tags), as they require special deployment-specific configuration. We could still add another `bazel-build-test` step to validate some manual targets with dummy configuration values if desired.

Philosophically, I don't see the workspace bazelrc files as "the central place to put all Bazel options" but rather "the place to specify the necessary options and provide valid useful configurations". Given that there are no "valid" values for these fields that the repo could provide, I figured that they don't really belong in any bazelrc.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
