### PR TITLE
feat: Use Bouncy Castle to generate CSRs for AWS private CA.

### PR DESCRIPTION
**Pull request by robinsons**
Removes a dependency on `openssl` for generating CSRs and switches to Bouncy Castle APIs instead. This PR is based on the corresponding changes in #1602.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905)* status: all files reviewed, 4 unresolved discussions (waiting on @robinsons and @sandip80)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905#-OBSdOAh-D11FszQHaiF:-OBSdOAi6h7OypOBJWnE:b-kpg254) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efd12a934d98674b98fee2741528a43f4b73b57a/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L52)):*
> ```Kotlin
>   private val client: CreateCertificateClient,
>   private val signatureAlgorithm: SignatureAlgorithm =
>     SignatureAlgorithm.SHA_256_WITH_RSA_ENCRYPTION,
> ```

nit: can we use ECDSA by default? Most of the web has switched due to smaller key sizes for similar security.
___
*[`MODULE.bazel` line 236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905#-OBSb4t26vf7mDtooKgL:-OBSb4t26vf7mDtooKgM:bg2eztx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efd12a934d98674b98fee2741528a43f4b73b57a/MODULE.bazel#L236)):*
> ```Starlark
> 
>         # Bouncy Castle
>         "org.bouncycastle:bcpkix-jdk15on:1.70",
> ```

Use a newer version built for newer JDK. Note that `jdk18on` here means Java 1.8, i.e. JDK 8.



_Suggestion:_
```Starlark
jdk18on:1.79
```
___
*[`imports/java/org/bouncycastle/bcpkix/BUILD.bazel` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905#-OBSbgIEDnD910EhG461:-OBSbgIEDnD910EhG462:bemhatm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efd12a934d98674b98fee2741528a43f4b73b57a/imports/java/org/bouncycastle/bcpkix/BUILD.bazel#L1)):*
> ```Starlark
> package(default_visibility = ["//visibility:public"])
> ```

Imports follow the Java packages included by the target. This defines many subpackages in `org.bouncycastle`, but not all of them. Therefore the target label should be `//imports/java/org/bouncycastle:bcpkix`
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/GenerateCsr.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905#-OBScNOO3jtKyGIib9ph:-OBScNOO3jtKyGIib9pi:b-s885ra) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efd12a934d98674b98fee2741528a43f4b73b57a/src/main/kotlin/org/wfanet/panelmatch/common/certificates/GenerateCsr.kt#L29)):*
> ```Kotlin
>  * algorithm.
>  */
> fun generateCsrFromKeyPair(
> ```

New non-extension functions should always be defined in the context of a class or object. e.g. `object Certificates` or `object CertificateSigningRequests`. The file and Bazel target name should match this top-level object.

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905)* status: 2 of 15 files reviewed, 4 unresolved discussions (waiting on @sandip80 and @SanjayVas)

___
*[`MODULE.bazel` line 236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905#-OBSb4t26vf7mDtooKgL:-OC5bcYbDnKqeWAQTTEQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efd12a934d98674b98fee2741528a43f4b73b57a/MODULE.bazel#L236)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a newer version built for newer JDK. Note that `jdk18on` here means Java 1.8, i.e. JDK 8.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905#-OBSdOAh-D11FszQHaiF:-OC5ce7Y3JKAGzMSYEVK:b4guh0r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efd12a934d98674b98fee2741528a43f4b73b57a/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: can we use ECDSA by default? Most of the web has switched due to smaller key sizes for similar security.
</blockquote></details>

Done, but I moved this to a flag since Origin's root cert uses RSA. I did set the default to ECDSA.
___
*[`imports/java/org/bouncycastle/bcpkix/BUILD.bazel` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905#-OBSbgIEDnD910EhG461:-OC5bkiB1IoExj6AhBdO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efd12a934d98674b98fee2741528a43f4b73b57a/imports/java/org/bouncycastle/bcpkix/BUILD.bazel#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Imports follow the Java packages included by the target. This defines many subpackages in `org.bouncycastle`, but not all of them. Therefore the target label should be `//imports/java/org/bouncycastle:bcpkix`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/GenerateCsr.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905#-OBScNOO3jtKyGIib9ph:-OC5cb8RCx07H9v67_oB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efd12a934d98674b98fee2741528a43f4b73b57a/src/main/kotlin/org/wfanet/panelmatch/common/certificates/GenerateCsr.kt#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

New non-extension functions should always be defined in the context of a class or object. e.g. `object Certificates` or `object CertificateSigningRequests`. The file and Bazel target name should match this top-level object.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 170 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905#-OC5gn6D6vIKwHENm-CV:-OC5gn6D6vIKwHENm-CW:bhgomow) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c76c09251668d4714071e20a69c3887753c28de7/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L170)):*
> ```Kotlin
>   }
> 
>   private val SignatureAlgorithm.keyAlgorithm: String
> ```

@SanjayVas - I put this here for now, but would you care for me to make this an actual property of SignatureAlgorithm? I can do this in a follow-up PR if you think there'd be value.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 9 of 12 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons and @sandip80)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 170 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905#-OC5gn6D6vIKwHENm-CV:-OC6BYF77eMG8aBYCscE:b-x63dca) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c76c09251668d4714071e20a69c3887753c28de7/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L170)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

@SanjayVas - I put this here for now, but would you care for me to make this an actual property of SignatureAlgorithm? I can do this in a follow-up PR if you think there'd be value.
</blockquote></details>

This is basically the inverse of `fromKeyAndHashAlgorithm`, right? Not a bad idea to move it to SignatureAlgorithm itself eventually. Feel free to just leave a TODO for now.

**Review by sandip80 — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 8 of 12 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1905)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @robinsons)

**Pull request merged**
