### PR TITLE
Update the KingdomApiServer to support binding multiple services.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/168)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/168)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/168#-MfdnXrNAs0BDk_YF3tu:-MfdnXrO8EavziQJb3Fh:bgi180m) (no related file):*
Add a line to the description that indicates that this fixes a bug where SystemApiServer was only binding Requisitions service.

---

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/168)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/168#-MfdnXrNAs0BDk_YF3tu:-Mfdo7Kp6MAl2FgEkzzR:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add a line to the description that indicates that this fixes a bug where SystemApiServer was only binding Requisitions service.
</blockquote></details>

Done.

---

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/168)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/168)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
