### PR TITLE
Implement Public Report Schedule Iterations Service

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249)

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, 1 of 1 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`build/repositories.bzl` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249#-NfXLxUz4sOR2XpM_U1r:-NfXLxUz4sOR2XpM_U1s:b-i28jn1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7dc99c15c8fb25fffffe5ded5d386240f04ad9/build/repositories.bzl#L34)):*
> ```Starlark
>     )
> 
>     wfa_repo_archive(
> ```

Add a comment of DO_NOT_SUBMIT
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt` line 123 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249#-NfXNquO8fNnbpaYrn9v:-NfXNquO8fNnbpaYrn9w:b86g9wd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7dc99c15c8fb25fffffe5ded5d386240f04ad9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt#L123)):*
> ```Kotlin
>       try {
>         internalReportScheduleIterationsStub
>           .listReportScheduleIterations(internalListReportScheduleIterationsRequest)
> ```

Just curious why we use `List` instead of `Stream` in the internal service.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt` line 267 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249#-NfXPNoW-0kZ6X89jevk:-NfXPNoW-0kZ6X89jevl:b-3szj43) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7dc99c15c8fb25fffffe5ded5d386240f04ad9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt#L267)):*
> ```Kotlin
>       ReportScheduleIteration.State.REPORT_CREATED
>     InternalReportScheduleIteration.State.STATE_UNSPECIFIED,
>     InternalReportScheduleIteration.State.UNRECOGNIZED ->
> ```

Why do we allow unrecognized states?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt` line 123 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249#-NfXNquO8fNnbpaYrn9v:-NfXY-_J8-7QQNKEhabi:b-mb27sl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7dc99c15c8fb25fffffe5ded5d386240f04ad9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt#L123)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Just curious why we use `List` instead of `Stream` in the internal service.
</blockquote></details>

There is an overhead cost associated with Stream, which is not worth it if the response is small. What I should eventually do is benchmark to see which one is actually better.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt` line 267 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249#-NfXPNoW-0kZ6X89jevk:-NfXXvl82c09nDYuWPWf:b-iccois) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7dc99c15c8fb25fffffe5ded5d386240f04ad9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt#L267)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Why do we allow unrecognized states?
</blockquote></details>

Changed it to throw an error instead.
___
*[`build/repositories.bzl` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249#-NfXLxUz4sOR2XpM_U1r:-NfXXzI_-jybWmRmal66:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7dc99c15c8fb25fffffe5ded5d386240f04ad9/build/repositories.bzl#L34)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Add a comment of DO_NOT_SUBMIT
</blockquote></details>

Done.

**Review by riemanli — COMMENTED** [review]
Could you explain what we do with the report schedule iterations and what's the relationship between it and the report schedule?

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249#-:-NfXwGIYDenK_7nzKv5u:b-ustek6)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt` line 123 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249#-NfXNquO8fNnbpaYrn9v:-NfXs6S98sukIzXy_CyQ:buy8y5e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7dc99c15c8fb25fffffe5ded5d386240f04ad9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt#L123)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

There is an overhead cost associated with Stream, which is not worth it if the response is small. What I should eventually do is benchmark to see which one is actually better.
</blockquote></details>

nit: add a TODO as a reminder?

**Review by riemanli — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsServiceTest.kt` line 111 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249#-Nflck2H3_GlNpAEW2YD:-Nflck2H3_GlNpAEW2YE:b-gbvu3p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/509767b436eca25bfa6289636d0074b92551f0da/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsServiceTest.kt#L111)):*
> ```Kotlin
>       }
> 
>     val expected = REPORT_SCHEDULE_ITERATION.copy { clearReport() }
> ```

nit: `REPORT_SCHEDULE_ITERATION` itself doesn't have `Report` field set.



_Code quote:_
```Kotlin
.copy { clearReport() }
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt` line 123 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249#-NfXNquO8fNnbpaYrn9v:-NfligLN4iN1-tVcGBve:b-w5d3sd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7dc99c15c8fb25fffffe5ded5d386240f04ad9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt#L123)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

nit: add a TODO as a reminder?
</blockquote></details>

I believe @tristanvuong2021 is referencing #1217, meaning we already have an issue filed for this.

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt` line 123 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249#-NfXNquO8fNnbpaYrn9v:-NfljtWdC0-dQmAjZVXW:byr7f2j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0f7dc99c15c8fb25fffffe5ded5d386240f04ad9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportScheduleIterationsService.kt#L123)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe @tristanvuong2021 is referencing #1217, meaning we already have an issue filed for this.
</blockquote></details>

Thanks for sharing this

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 1 of 1 files at r2, 2 of 3 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1249)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
