### PR TITLE
Add detailed logging to requisitions service

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1550)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1550)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/InternalStatusConversion.kt` line 216 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1550#-NuPmt0v0jxG5AGRUJIq:-NuPmt0v0jxG5AGRUJIr:b-2i395r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/939ac980eb370d4861840a4ad9c233ff8234246d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/InternalStatusConversion.kt#L216)):*
> ```Kotlin
>               checkNotNull(errorInfo.metadataMap["external_requisition_id"]).toLong()
>             )
>           val requisitionState = checkNotNull(errorInfo.metadataMap["requisition_state"]).toString()
> ```

The enums are different between internal and public API, so you cannot just pass the enum value. You need to parse as internal enum then convert to public enum. There are some functions that handle these enums in ProtoConversions.

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1550)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/InternalStatusConversion.kt` line 216 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1550#-NuPmt0v0jxG5AGRUJIq:-NuUSXH43405achoheG3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/939ac980eb370d4861840a4ad9c233ff8234246d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/InternalStatusConversion.kt#L216)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The enums are different between internal and public API, so you cannot just pass the enum value. You need to parse as internal enum then convert to public enum. There are some functions that handle these enums in ProtoConversions.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1550)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @Marco-Premier)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt` line 533 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1550#-NuVZo0H1SckTs1wprG6:-NuVZo0I-_wYDS1x_dcM:b9qrv7x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/209710144a806c59f049cb1a995a8d99303c2a1f/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt#L533)):*
> ```Kotlin
>       .containsEntry(
>         "account_activation_state",
>         InternalAccount.ActivationState.ACTIVATED.toActivationState().toString(),
> ```

Don't call toActiviationState() here, as that's just basically replicating the same code you're trying to test. Instead, either use the corresponding public API enum or the corresponding string directly.



_Code quote:_
```Kotlin
InternalAccount.ActivationState.ACTIVATED.toActivationState().toString()
```

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1550)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt` line 533 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1550#-NuVZo0H1SckTs1wprG6:-NuVsW21B7texyaEGLkU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/209710144a806c59f049cb1a995a8d99303c2a1f/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt#L533)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't call toActiviationState() here, as that's just basically replicating the same code you're trying to test. Instead, either use the corresponding public API enum or the corresponding string directly.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 11 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1550)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 4 of 11 files at r2, 4 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1550)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
