### PR TITLE
Added method for batching search the findAcdpBalanceEntries

### PR DESCRIPTION
**Pull request by RibeiroAna**
At Meta we were facing some performance issues when trying to find privacy bucket groups one by one. We created internally some methods to batch the select queries and that helped. We think this should be added to the interface so other EDP implementing the PBM can also create methods to batch their entries.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1684)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1684)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RibeiroAna)

**Comment by SanjayVas** [comment]
Waiting on @uakyol to take a pass since this is for PBM.

**Comment by RibeiroAna** [comment]
@uakyol can you take a look? I need your approval

**Review by uakyol — APPROVED** [review]
Thanks for putting this together. It makes sense to add this method. LGTM

**Review by uakyol — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1684)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iverson52000 and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1684)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Pull request merged**
