### PR TITLE
Improve debuggability of integration test.

### PR DESCRIPTION
**Pull request by SanjayVas**
* Adjust logging.
* Wait for event group creation rather than polling.
* Use shorter result polling delay.
* Clean up background job start/stop.
* Specify individual test method timeouts.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707)

### CODE REVIEW

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @iverson52000 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 675 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707#-ND46NxR9F3h3OS4tEuL:-ND46NxS0Z1AAht_xiUK:b-n5ich8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d36eabb82fa4a50c9a96d008faa9c222de51ee06/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L675)):*
> ```Kotlin
>   }
> 
>   private suspend inline fun <T> pollForResults(getResults: () -> List<T>): List<T> {
> ```

This is the function used for volumetric measurements?
___
*[`src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudInProcessLifeOfAMeasurementIntegrationTest.kt` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707#-ND45PQ78VmrDBIgL9ch:-ND45PQ78VmrDBIgL9ci:bfrxune) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d36eabb82fa4a50c9a96d008faa9c222de51ee06/src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudInProcessLifeOfAMeasurementIntegrationTest.kt#L32)):*
> ```Kotlin
>   InProcessLifeOfAMeasurementIntegrationTest() {
> 
>   @get:Rule val timeout = CoroutinesTimeout.seconds(60)
> ```

Is this for setting a timeout for coroutines? Which means each coroutine has to finish in 60s?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @iverson52000)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 675 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707#-ND46NxR9F3h3OS4tEuL:-ND4FAHmDmJb2enTFkiW:b-4h7jx3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d36eabb82fa4a50c9a96d008faa9c222de51ee06/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L675)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

This is the function used for volumetric measurements?
</blockquote></details>

Yes. More generically for anything that returns multiple results, which currently means volumetric measurements.
___
*[`src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudInProcessLifeOfAMeasurementIntegrationTest.kt` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707#-ND45PQ78VmrDBIgL9ch:-ND4FYeC-7lOFgYnsX0Y:b-l1xwah) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d36eabb82fa4a50c9a96d008faa9c222de51ee06/src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudInProcessLifeOfAMeasurementIntegrationTest.kt#L32)):*
This is the timeout applied to each test method. It just has some extra coroutine debugging capabilities that the non-coroutine `Timeout` rule doesn't.

From the class description:

> Coroutines timeout rule for JUnit4 that is applied to all methods in the class. This rule is very similar to Timeout rule: it runs tests in a separate thread, fails tests after the given timeout and interrupts test thread.

**Review by iverson52000 — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Comment by SanjayVas** [comment]
This depends on the Herald exception-handling changes in #697.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 143 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707#-ND9q7k_6n-worTVo2NP:-NDA61nPE6HmjadbYFfc:b-2rgjsg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee142a62c9a120c66e9a110f6881baa8d8fc5efc/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L143)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

the rest of the grpc calls in this file aren't caught. Why are you wanting to catch this one?
</blockquote></details>

These are all supposed to be caught everywhere. #664 and #684 covered some cases. I have a follow-up PR (#714) that covers more of them.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorFlags.kt` line 108 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707#-ND9qNKH1OLzklNObB4U:-NDUmpcpBV1Q9HhirBFA:bjz1wm0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5273845ffd0e6a95836964480d9fba021fa6073/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorFlags.kt#L108)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

does the polling interval need to be this high?
</blockquote></details>

This was the value that was previously hard-coded. I'm trying not to change default FE simulator behavior here outside of the integration test.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
