### PR TITLE
Implement UpdateEventGroup in external api

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/425)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/425)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @robinsons)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/425#-MuGnxs_5k7Wb3yQfMnh:-MuGnxs_5k7Wb3yQfMni:b-yg0v7c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab385b0cb726eba7c61dbec7af71dbc8c0edbe1c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L118)):*
> ```Kotlin
>     grpcRequire(
>       !request.eventGroup.hasMeasurementConsumerPublicKey() ||
>         !request.eventGroup.measurementConsumerCertificate.isBlank()
> ```

not: `isNotBlank()`

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/425)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @robinsons)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 86 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/425#-MuGo7bO8l2_QoPQeEX0:-MuGo7bO8l2_QoPQeEX1:bg94js5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab385b0cb726eba7c61dbec7af71dbc8c0edbe1c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L86)):*
> ```Kotlin
>     grpcRequire(
>       !request.eventGroup.hasMeasurementConsumerPublicKey() ||
>         !request.eventGroup.measurementConsumerCertificate.isBlank()
> ```

nit: isNotBlank

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/425)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 131 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/425#-MuHAZiQ3jO2T2AVqkA1:-MuHAZiQ3jO2T2AVqkA2:bmuboar) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab385b0cb726eba7c61dbec7af71dbc8c0edbe1c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L131)):*
> ```Kotlin
>               .toInternal()
>               .toBuilder()
>               .apply { externalDataProviderId = apiIdToExternalId(eventGroupKey.dataProviderId) }
> ```

Also need to set `externalEventGroupId`. Otherwise the internal service won't know which event group to update.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 206 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/425#-MuHCJkhAGVlCkF-qcEv:-MuHCJkhAGVlCkF-qcEw:bfwimhj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab385b0cb726eba7c61dbec7af71dbc8c0edbe1c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L206)):*
> ```Kotlin
> 
> /** Converts a public [EventGroup] to an internal [InternalEventGroup]. */
> private fun EventGroup.toInternal(): InternalEventGroup {
> ```

Could the data provider and event group IDs be passed to this function? Something like

```
private fun EventGroup.toInternal(externalDataProviderId: String, externalEventGroupId: String = ""): InternalEventGroup { ... }
```

This way we don't have to do the `toBuilder().apply { ... }.build()` up above.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/425)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 131 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/425#-MuHAZiQ3jO2T2AVqkA1:-MuHjdhr6lHteEQsAGGt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab385b0cb726eba7c61dbec7af71dbc8c0edbe1c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L131)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Also need to set `externalEventGroupId`. Otherwise the internal service won't know which event group to update.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 206 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/425#-MuHCJkhAGVlCkF-qcEv:-MuHozrgDOiZC0KX0bvl:bcfrnyn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab385b0cb726eba7c61dbec7af71dbc8c0edbe1c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L206)):*
> externalDataProviderId: String, externalEventGroupId: String = ""
I like that -- done.

**Review by robinsons — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/425)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
