### PR TITLE
Add data providers service to Reporting V2

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176)

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 14 files at r1, 2 of 6 files at r2, 1 of 1 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/DataProvidersServiceTest.kt` line 80 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176#-NcA4wOL1aWgF8aDEZom:-NcA4wOL1aWgF8aDEZon:bis2y9p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131244c92fcdbae42ec62bafe77b206c70a5a49c/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/DataProvidersServiceTest.kt#L80)):*
> ```Kotlin
> 
>     assertThat(response).isEqualTo(DATA_PROVIDER)
> ```

Use header interceptor to verify that API key is passed in request header.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176)* status: 10 of 14 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/DataProvidersServiceTest.kt` line 80 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176#-NcA4wOL1aWgF8aDEZom:-NcO2yuu1cQ7xPoGIZ59:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4926ec8752b045d833a995ceeb8e259041b57dbf/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/DataProvidersServiceTest.kt#L80)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use header interceptor to verify that API key is passed in request header.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 1 of 6 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 6 of 14 files at r1, 3 of 6 files at r2, 1 of 1 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/DataProvidersService.kt` line 32 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176#-NcWEf2f0Jq4NNHQVRmG:-NcWEf2f0Jq4NNHQVRmH:b7295m8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5785573d32f818f6edad9c3e84f6decbfcb70ce8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/DataProvidersService.kt#L32)):*
> ```Kotlin
>     when (principal) {
>       is MeasurementConsumerPrincipal -> {}
>     }
> ```

I don't think we need this



_Code quote:_
```Kotlin
    when (principal) {
      is MeasurementConsumerPrincipal -> {}
    }
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176)* status: 6 of 14 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/DataProvidersService.kt` line 32 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176#-NcWEf2f0Jq4NNHQVRmG:-NcYol4sDrHGs0I6XTgM:bvh7a4f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/237705fa59ffab6477d3935a987c0af2df34fb97/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/DataProvidersService.kt#L32)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I don't think we need this
</blockquote></details>

It isn't necessary right now because there is only 1 Reporting principal, but it is a safeguard in case we do add more in the future.

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 6 of 12 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 6 of 12 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1176)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
