### PR TITLE
Add DeleteMeasurement method to internal Kingdom API definition

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/890)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/890)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/890)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/890)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/890#-NQk6jRk0EaimWdmQ4uC:-NRK9Emd6smAemHQAzce:b-7497fw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27705e24b3529abd076324771a85f0af2fa0a347/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L48)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

The difference in behavior was because event group has a soft delete vs the hard delete for measurements and following the suggestions at https://google.aip.dev/135 for response. But the return types are marked as SHOULD rather than MUST, so I am open to returning the measurement if it’s still preferred.
</blockquote></details>

Thx for the clarification. I'm fine either way.

**Pull request closed without merging**
