### PR TITLE
Introduce Requisition Validators

### PR DESCRIPTION
**Pull request by uakyol**
Each EDP needs to make sure the requisitions they fetch are in line with their expectations. 
This class provides the means to do so.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/CompoundValidator.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990#-NV6TUN6D7N3QDiX373f:-NV6TUN6D7N3QDiX373g:b-ril63b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b0ab2d5254384d65c1d109104dc724a6dc20d9d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/CompoundValidator.kt#L24)):*
> ```Kotlin
>  * Validators are applied in order, and the first non-valid result is returned.
>  */
> class CompoundValidator(private val validators: List<RequisitionValidator>) : RequisitionValidator {
> ```

For collection inputs use the least restrictive interface.



_Suggestion:_
```Kotlin
Iterable
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/EventFilterValidator.kt` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990#-NV6Tl0v5Qkjzz7aFLao:-NV6Tl0v5Qkjzz7aFLap:b8a8z0w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b0ab2d5254384d65c1d109104dc724a6dc20d9d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/EventFilterValidator.kt#L36)):*
> ```Kotlin
>     for (eventGroup in requisitionSpec.eventGroupsList) {
>       try {
>         EventFilters.compileProgram(
> ```

Program compilation isn't cheap. We shouldn't do this just for validation if we're going to need the program again later.

**Comment by uakyol** [comment]
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/EventFilterValidator.kt` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990#-NV6Tl0v5Qkjzz7aFLao:-NV6cLGh9VTXFyP0-c_N:b-khaqej) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b0ab2d5254384d65c1d109104dc724a6dc20d9d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/EventFilterValidator.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Program compilation isn't cheap. We shouldn't do this just for validation if we're going to need the program again later.
</blockquote></details>

This is done once for each requisition. Compared to requisition fulfillment time which is in order of minutes now, I think Program compilation time is negligible.
However, I understand your concern and if an EDP doesn't want to use this they don't have to. We also don't need to add this particular validator to the EDPSimulator but I still think it is valuable to have this as a part of the library as reference.

Wdyt?

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/CompoundValidator.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990#-NV6TUN6D7N3QDiX373f:-NV6cIm83EiI4Ewbby61:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b0ab2d5254384d65c1d109104dc724a6dc20d9d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/CompoundValidator.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

For collection inputs use the least restrictive interface.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/EventFilterValidator.kt` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990#-NV6Tl0v5Qkjzz7aFLao:-NV6mzcUB_G3jwSxZCed:bumito2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b0ab2d5254384d65c1d109104dc724a6dc20d9d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/EventFilterValidator.kt#L36)):*
> I still think it is valuable to have this as a part of the library as reference.

I disagree. We don't actually have an EDP client library. All we have is an EDP simulator implementation which we use for testing and also point people to as an example of how the fulfillment process works from the EDP end. That is to say that no code should live here unless it's actually used by our EDP simulator.

With our current simulator implementation, I would just add a try-catch block around eventQuery.getUserVirtualIds that catches EventFilterValidationException, as that's where `EventFilters.compileProgram` is called from.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/EventFilterValidator.kt` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990#-NV6Tl0v5Qkjzz7aFLao:-NV7Mrt2DQ01546klLE6:b-spp4mm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b0ab2d5254384d65c1d109104dc724a6dc20d9d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/EventFilterValidator.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I still think it is valuable to have this as a part of the library as reference.

I disagree. We don't actually have an EDP client library. All we have is an EDP simulator implementation which we use for testing and also point people to as an example of how the fulfillment process works from the EDP end. That is to say that no code should live here unless it's actually used by our EDP simulator.

With our current simulator implementation, I would just add a try-catch block around eventQuery.getUserVirtualIds that catches EventFilterValidationException, as that's where `EventFilters.compileProgram` is called from.
</blockquote></details>

Sounds good. Removed this class.

**Review by SanjayVas — APPROVED** [review]
Approved, but I'm not entirely convinced this structure is necessary. Would have to see how it's used in EdpSimulator.

> Reviewed 1 of 9 files at r2, 2 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990#-:-NVAokBDCNjryiCJBap-:b-87crlv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 1 of 9 files at r2, 2 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/CompoundValidator.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990#-NVH0Iz-D40X8ccPiVqh:-NVH0Iz-D40X8ccPiVqi:bk0oa00) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b4c157ee8851f2e28e6e412198eaecb74b0c13b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/CompoundValidator.kt#L22)):*
> ```Kotlin
> /**
>  * [RequisitionValidator] that validates a requisition against each validator in [validators].
>  * Validators are applied in order, and the first non-valid result is returned.
> ```

I'd prefer to be able to report all the problems with the requisition vs just the first problem encountered.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/CompoundValidator.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990#-NVH0Iz-D40X8ccPiVqh:-NVMwX8N-uGGGN--SsN_:b-nh72it) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b4c157ee8851f2e28e6e412198eaecb74b0c13b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/CompoundValidator.kt#L22)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd prefer to be able to report all the problems with the requisition vs just the first problem encountered.
</blockquote></details>

good point thank you

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/CompoundValidator.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990#-NVH0Iz-D40X8ccPiVqh:-NVMw_d95idrb6TUPgZ9:bvnrpcm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b4c157ee8851f2e28e6e412198eaecb74b0c13b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/validation/CompoundValidator.kt#L22)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

good point thank you
</blockquote></details>

updated

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by uakyol — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/990)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
