### PR TITLE
Add State to Internal Metric

### PR DESCRIPTION
**Pull request by tristanvuong2021**
State is required for [fixing metric reuse](https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1544). This is the first step to fixing the issue.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557)* status: 2 of 13 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1603 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557#-Nu_67mH8DuBdA9wte9H:-Nu_67mH8DuBdA9wte9I:b-lnkl7o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/51763c3ec96a89e217934de6a1b5f07f168cda3d/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1603)):*
> ```Kotlin
> 
>     val anyMeasurementUpdated: Boolean =
>       measurementSupplier.syncInternalMeasurements(
> ```

The internal metric states should be updated in the internal service as part of the transaction that updates the internal Measurement.
___
*[`src/main/resources/reporting/postgres/add-state-column-to-metrics.sql` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557#-Nu_47orCzXcgIH9FBfe:-Nu_47orCzXcgIH9FBff:b-4pcub9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/51763c3ec96a89e217934de6a1b5f07f168cda3d/src/main/resources/reporting/postgres/add-state-column-to-metrics.sql#L40)):*
> ```TSQL
> 
> -- changeset tristanvuong2021:add-state-column-metrics-table dbms:postgresql
> ALTER TABLE Metrics ADD COLUMN State integer NOT NULL DEFAULT 1;
> ```

This will mark all existing Metrics as `RUNNING`. Do we instead want to leave these as `STATE_UNSPECIFIED` so that we can detect which ones we don't actually know the state of and need to calculate?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557)* status: 1 of 17 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1603 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557#-Nu_67mH8DuBdA9wte9H:-Nuf0_dqE1xX3edk-qDl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/51763c3ec96a89e217934de6a1b5f07f168cda3d/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1603)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The internal metric states should be updated in the internal service as part of the transaction that updates the internal Measurement.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/add-state-column-to-metrics.sql` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557#-Nu_47orCzXcgIH9FBfe:-Nuf0b-b4cbEW1NTHChQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/51763c3ec96a89e217934de6a1b5f07f168cda3d/src/main/resources/reporting/postgres/add-state-column-to-metrics.sql#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This will mark all existing Metrics as `RUNNING`. Do we instead want to leave these as `STATE_UNSPECIFIED` so that we can detect which ones we don't actually know the state of and need to calculate?
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r1, 6 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1154 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557#-NuffdLH7YxFswBCQaWJ:-NuffdLH7YxFswBCQaWK:b-1qh1bq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abe7a8081a3bcd30ec22ddce98c8914dcb74d7e9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1154)):*
> ```Kotlin
>         principal,
>       )
>       .first()
> ```

Can this possibly return more than one? If not, perhaps `single()` instead?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1586 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557#-NufhFvKDMtxt20TIxiP:-NufhFvKDMtxt20TIxiQ:bubajeu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abe7a8081a3bcd30ec22ddce98c8914dcb74d7e9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1586)):*
> ```Kotlin
>     principal: MeasurementConsumerPrincipal,
>   ): List<Metric> {
>     // Only syncs pending measurements which can only be in metrics that are still running.
> ```

Doesn't this also need to handle STATE_UNSPECIFIED? i.e. if the state isn't known to the internal service, compute what it would be here and act accordingly.

As a related note, the public API should never return STATE_UNSPECIFIED

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557)* status: 9 of 17 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1154 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557#-NuffdLH7YxFswBCQaWJ:-NujCf_iBaMhmdjl1tRF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abe7a8081a3bcd30ec22ddce98c8914dcb74d7e9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1154)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can this possibly return more than one? If not, perhaps `single()` instead?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1586 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557#-NufhFvKDMtxt20TIxiP:-NujNaMc0lc0jvEtL3rr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abe7a8081a3bcd30ec22ddce98c8914dcb74d7e9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1586)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Doesn't this also need to handle STATE_UNSPECIFIED? i.e. if the state isn't known to the internal service, compute what it would be here and act accordingly.

As a related note, the public API should never return STATE_UNSPECIFIED
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 13 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1620 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557#-Nujaort4t701i_hluYs:-Nujaort4t701i_hluYt:b-8mvyk9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8529033a3b8ad39f401e4bd5b391b5671d9c57bf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1620)):*
> ```Kotlin
>             }
>           }
>           InternalMetric.State.STATE_UNSPECIFIED -> {
> ```

nit: add a comment to indicate that this is to handle old internal Metrics created before internal Metric tracked state.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 13 files at r1, 4 of 13 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1557)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
