### PR TITLE
feat: Regard some DEADLINE_EXCEEDED errors as transient in MillBase

### PR DESCRIPTION
**Pull request by renjiezh**
`advanceComputationStage`, `getLatestComputationToken`, and `updateComputationDetails` will regard DEADLINE_EXCEEDED as transient error.

### CODE REVIEW

**Review by SanjayVas — COMMENTED** [review]
This can only be transient in the same cases that it's retriable. DEADLINE_EXCEEDED is only safe to rety when the RPC is idempotent.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704#-:-O2kslkr6YbqojIwXFvT:b3tgu0o)* status: 0 of 1 files reviewed, all discussions resolved

**Review by renjiezh — COMMENTED** [review]
With this merged [PR](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1793), the mill will check the peer's stage before send the advance request. So it is now safe to retry DEADLINE_EXCEEDED.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704#-:-O6viImX27Q13987QDAO:b-cnyyrz)* status: 0 of 2 files reviewed, all discussions resolved

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt` line 627 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704#-O6vwKx_3KxFKCj19rqc:-O6vzLJV78dXGlys7GO5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab898dfaca4e91ffd214022fe652c9c5f696ada7/src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt#L627)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document why this is safe to retry in this case, as it is normally not.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt` line 789 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704#-O70RGLn0AgXgeqdFftt:-O70RGLo7IUOZ-uSpWM4:bktjdj3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8847a0326bfcbc45e146b7291069d7914315310c/src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt#L789)):*
> ```Kotlin
>         throw when (e.status.code) {
>           Status.Code.UNAVAILABLE,
>           Status.Code.DEADLINE_EXCEEDED,
> ```

Same as before: explain why this is safe. In this case, I believe it's because we always use etags for this method.

**Review by SanjayVas — COMMENTED** [review]
> feat: Regard DEADLINE_EXCEEDED error as transient in MillBase

The PR description is no longer accurate or sufficient. My understanding is that the PR doesn't make *all* RPCs in MillBase treat DEADLINE_EXCEEDED as transient. Regardless, more information is probably needed in the body of the PR description.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704#-:-O70RgcZ7EEGFzg8m523:b-it5k78)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @stevenwarejones)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt` line 789 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704#-O70RGLn0AgXgeqdFftt:-O70TuW3BzXa2rbtSjjA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8847a0326bfcbc45e146b7291069d7914315310c/src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt#L789)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same as before: explain why this is safe. In this case, I believe it's because we always use etags for this method.
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1704)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
