### PR TITLE
Add GetReportByRequestId.

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1007)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1005** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1005" target="_blank">Graphite</a> 
    * **PR #1007** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1007" target="_blank">Graphite</a>  👈
      * **PR #1004** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1004" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1007?utm_source=stack-comment).

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1007)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla and @riemanli)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1007#-NVeujSc8HNmxlIv_WaI:-NVeujSc8HNmxlIv_WaJ:b-lbpg7v) (no related file):*
Is this necessary? CreateReport can return the existing report if one is found with the same request id.

___

**Review by jcorilla — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1007)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1007)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1007#-NVeujSc8HNmxlIv_WaI:-NVg-geN6gBB-4LLDblt:b-4o8ent) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Is this necessary? CreateReport can return the existing report if one is found with the same request id.
</blockquote></details>

You're right. I thought I could save some computation before calling internal `CreateReport` by using `GetReportByRequestId`, but it turned out there is not much to save.  I will close this PR.

___

**Pull request closed without merging**
