### PR TITLE
Implement external update event group metadata descriptor

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @robinsons)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521#-N-P-a8L1eq3BEvnpGVk:-N-P-a8L1eq3BEvnpGVl:bwru29t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cace60b96e926a39f03191ecb7d309572d14d37/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L158)):*
> ```Kotlin
>   private fun EventGroupMetadataDescriptor.toInternal(
>     dataProviderId: String,
>     eventGroupMetadataDescriptorId: String = ""
> ```

can we drop the default?

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521#-N-P-a8L1eq3BEvnpGVk:-N-PAtVREbY6C1esM6xs:b-5kug4t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cace60b96e926a39f03191ecb7d309572d14d37/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L158)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can we drop the default?
</blockquote></details>

This function is also used in in the `Create` function and has a default for that.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @robinsons)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521#-N-P-a8L1eq3BEvnpGVk:-N-PCPS4A-mNCHY6Eepb:bn1dr4g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cace60b96e926a39f03191ecb7d309572d14d37/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L158)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

This function is also used in in the `Create` function and has a default for that.
</blockquote></details>

wouldn't it be cleaner to make it nullable then too?

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521#-N-PI8AMApVYk-5-1Kul:-N-PI8AN7jBbUcCwubTU:b-67u287) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cace60b96e926a39f03191ecb7d309572d14d37/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L121)):*
> ```Kotlin
>         EventGroupMetadataDescriptorKey.fromName(request.eventGroupMetadataDescriptor.name)
>       ) { "EventGroupMetadataDescriptor name is either unspecified or invalid" }
> ```

We should check the principal, such that only the owning EDP can update the metadata descriptor.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521#-N-PI8AMApVYk-5-1Kul:-N-TMRnG6czWfvhLDAPc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cace60b96e926a39f03191ecb7d309572d14d37/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L121)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

We should check the principal, such that only the owning EDP can update the metadata descriptor.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521#-N-P-a8L1eq3BEvnpGVk:-N-TAPkv7Bv2Uz8JScEU:b-u21wgp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cace60b96e926a39f03191ecb7d309572d14d37/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt#L158)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

wouldn't it be cleaner to make it nullable then too? 
</blockquote></details>

That could be possible, although I have a slight lean towards keeping it consistent with the `EventGroup` [implementation](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt?L295) which uses the same design.

**Review by robinsons — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by chipingyeh — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/521)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Pull request merged**
