### PR TITLE
Switch to a single deployment from sidecar opentelemetry collectors.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NH5oVVf0cTV3zjNdYoB:-NH5oVVf0cTV3zjNdYoC:bp7mbfn) (no related file):*
How would you feel about basing this on #747?

___
___
*[`src/main/k8s/dev/config.cue` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NH5oKUV4sLB3ak4oiRo:-NH5oKUV4sLB3ak4oiRp:b-6t5wdh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cb5a96bd5464838fbe1b273849fb8bd9582e0b2b/src/main/k8s/dev/config.cue#L19)):*
> ```CUE
> import "strings"
> 
> #GCloudProject:     "ads-open-measurement"
> ```

Drop this change. We want to keep defaults for halo-cmm-dev.

**Comment by tristanvuong2021** [comment]
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

How would you feel about basing this on #747?
</blockquote></details>

Good idea.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/dev/config.cue` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NH5oKUV4sLB3ak4oiRo:-NH5pdMzE_wQLDgeTeBx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cb5a96bd5464838fbe1b273849fb8bd9582e0b2b/src/main/k8s/dev/config.cue#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop this change. We want to keep defaults for halo-cmm-dev.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @tristanvuong2021)

___
*[`docs/gke/metrics-deployment.md` line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NHBnHU23XuhkudW2Zpe:-NHBnHU23XuhkudW2Zpf:bk0edru) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76dd41d0703ba54266be08ec3d9bdd921bf6ec13/docs/gke/metrics-deployment.md#L94)):*
> ```Markdown
> The default `dev` configuration for OpenTelemetry collection is in
> [`open_telemetry_gke.cue`](../../src/main/k8s/dev/open_telemetry_gke.cue), which
> depends on [`open_telemetry.cue`](../../src/main/k8s/open_telemetry.cue). The
> ```

I believe you'll need to change this part of the guide around, as it's saying to use open_telemetry_gke always and then *additionally* add the Spanner target, whereas I think with this PR you should use one or the other exclusively.
___
*[`src/main/k8s/open_telemetry.cue` line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NHBniJ8D8NrvJ0uFr4y:-NHBniJ8D8NrvJ0uFr4z:b-nkwnrf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3d39270e6713328750c96cbde382cb5c6799283/src/main/k8s/open_telemetry.cue#L26)):*
> ```CUE
> 	}
> 	spec: {
> 		mode:             "deployment" | "sidecar"
> ```

This should match the underlying K8s type, which allows both. It just happens to be that our only collector instance uses "deployment".



_Code quote:_
```CUE
 | "sidecar"
```
___
*[`src/main/k8s/open_telemetry.cue` line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NHBlPWq9pGWzgP3GInS:-NHBlPWr0MWG0nt3j4EN:b7x9t0h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76dd41d0703ba54266be08ec3d9bdd921bf6ec13/src/main/k8s/open_telemetry.cue#L48)):*
> ```CUE
> 
> 	collectors: {
> 		"deployment": {
> ```

I'm guilty of this too, but maybe we want to come up with a more descriptive name? The annoying part is that it will automatically add the "-collector" suffix to the underlying service/deployment, 

Maybe we go back to "default"?



_Code quote:_
```CUE
"deployment"
```
___
*[`src/main/k8s/open_telemetry.cue` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NHBltmVCIsKrx4w5ExP:-NHBltmVCIsKrx4w5ExQ:b-c3dl5l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76dd41d0703ba54266be08ec3d9bdd921bf6ec13/src/main/k8s/open_telemetry.cue#L56)):*
> ```CUE
>                 grpc:
>                   endpoint: 0.0.0.0:\(#OpenTelemetryReceiverPort)
> ```

I think the whitespace might be significant here. I encountered errors when trying to get this working before.

Maybe just left justify the whole multi-line string like in open_telemetry_gke_spanner.cue? That way none of the significant whitespace is trailing.
___
*[`src/main/k8s/open_telemetry.cue` line 127 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NHBmwc9Bmya_q6WdqvA:-NHBmwcA15fWiy9uXBru:bcor5ve) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76dd41d0703ba54266be08ec3d9bdd921bf6ec13/src/main/k8s/open_telemetry.cue#L127)):*
> ```CUE
> 			}
> 			_egresses: {
> 				// Need to send external traffic to Spanner.
> ```

Only specify this in the Spanner version, since it's not needed by the base collector.



_Code quote:_
```CUE
			_egresses: {
				// Need to send external traffic to Spanner.
				any: {}
			}
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/open_telemetry.cue` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NHBltmVCIsKrx4w5ExP:-NHBrkc15dcjv_wrxXok:bioez2k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76dd41d0703ba54266be08ec3d9bdd921bf6ec13/src/main/k8s/open_telemetry.cue#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think the whitespace might be significant here. I encountered errors when trying to get this working before.

Maybe just left justify the whole multi-line string like in open_telemetry_gke_spanner.cue? That way none of the significant whitespace is trailing.
</blockquote></details>

It is significant in cue. Cue requires the whitespace to be all spaces or all tabs, but cannot mix. I got it to work by opening the file in vi and swapping the tabs with spaces since intellij doesn't show the actual whitespace characters.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/k8s/open_telemetry.cue` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NHBltmVCIsKrx4w5ExP:-NHBsQSEBMOTMdBZzRX6:b-p5n835) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76dd41d0703ba54266be08ec3d9bdd921bf6ec13/src/main/k8s/open_telemetry.cue#L56)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It is significant in cue. Cue requires the whitespace to be all spaces or all tabs, but cannot mix. I got it to work by opening the file in vi and swapping the tabs with spaces since intellij doesn't show the actual whitespace characters.
</blockquote></details>

Right, but Reviewable appears to be showing that the spaces were removed by this PR. I think IntelliJ and other formatting tools might remove trailing whitespace by default.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751)* status: 6 of 10 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`docs/gke/metrics-deployment.md` line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NHBnHU23XuhkudW2Zpe:-NHCKRABB9MB3OQnaw4_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76dd41d0703ba54266be08ec3d9bdd921bf6ec13/docs/gke/metrics-deployment.md#L94)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe you'll need to change this part of the guide around, as it's saying to use open_telemetry_gke always and then *additionally* add the Spanner target, whereas I think with this PR you should use one or the other exclusively.
</blockquote></details>

Done.
___
*[`src/main/k8s/open_telemetry.cue` line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NHBniJ8D8NrvJ0uFr4y:-NHCKP9vCSV_nV8tyEdF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3d39270e6713328750c96cbde382cb5c6799283/src/main/k8s/open_telemetry.cue#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should match the underlying K8s type, which allows both. It just happens to be that our only collector instance uses "deployment".
</blockquote></details>

Done.
___
*[`src/main/k8s/open_telemetry.cue` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NHBltmVCIsKrx4w5ExP:-NHQBjiO6B_gmuCQIHFa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76dd41d0703ba54266be08ec3d9bdd921bf6ec13/src/main/k8s/open_telemetry.cue#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Right, but Reviewable appears to be showing that the spaces were removed by this PR. I think IntelliJ and other formatting tools might remove trailing whitespace by default.
</blockquote></details>

Done.
___
*[`src/main/k8s/open_telemetry.cue` line 127 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NHBmwc9Bmya_q6WdqvA:-NHQSr2o90grCC-LjK92:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76dd41d0703ba54266be08ec3d9bdd921bf6ec13/src/main/k8s/open_telemetry.cue#L127)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Only specify this in the Spanner version, since it's not needed by the base collector.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751#-NHRhMKb7M80WMay15aa:-NHRhMKb7M80WMay15ab:bmlxfp2) (no related file):*
The sidecars actually use a lot more memory than desired so this change is for reducing the memory usage.

___

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 4 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Pull request merged**
