### PR TITLE
Implement internal spanner stream exchanges method

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/975)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/975)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt` line 283 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/975#-NV5U1Pa-Tf7h5OUslGG:-NV5U1Pb3K9QzMOVAIOu:bjv6dyj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2aa808662e71f326cd822c8e02ddffb2f289a08/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt#L283)):*
> ```Kotlin
>   @Test
>   fun `streamExchange respects limit`(): Unit = runBlocking {
>     val createRequest1 = CreateExchangeRequest.newBuilder().apply { exchange = EXCHANGE }.build()
> ```

Switch to the builder used elsewhere instead of newBuilder.

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/975)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt` line 283 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/975#-NV5U1Pa-Tf7h5OUslGG:-NV5dP4I92XGJ-oFGOi-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2aa808662e71f326cd822c8e02ddffb2f289a08/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt#L283)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Switch to the builder used elsewhere instead of newBuilder.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/975)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/975)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
