### PR TITLE
Add Report Scheduling Job Skeleton

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325#-Niq5Zf1-invKro4jSmd:-Niq5Zf1-invKro4jSme:b-zxfj7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dea75d670796a20c64b3742f944f9bb28e5ec4dd/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L65)):*
> ```Kotlin
> 
> @CommandLine.Command(
>   name = "Report Scheduling Job",
> ```

This should be the name of the resulting command, i.e. the name of the binary target.



_Suggestion:_
```Kotlin
ReportSchedulingJobExecutor
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 137 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325#-NiqE67w92Uh9_2Yp764:-NiqE67w92Uh9_2Yp765:bb0r5qd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dea75d670796a20c64b3742f944f9bb28e5ec4dd/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L137)):*
> ```Kotlin
>     )
> 
>   InProcessServerBuilder.forName(inProcessMetricsServerName)
> ```

You can extract functions for `startMetricsServer` and `startReportsServer` which return channels. This will shorten the `run` method and limit the scope of some temporary variables.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJobTest.kt` line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325#-NiqEzT96JZuTXLgzrc6:-NiqEzT96JZuTXLgzrc7:bw1qiox) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dea75d670796a20c64b3742f944f9bb28e5ec4dd/src/test/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJobTest.kt#L74)):*
> ```Kotlin
>   }
> 
>   @Test fun `execute creates report for a single schedule for a new iteration`() {}
> ```

nit: mark these with `@Ignore` for now so it doesn't look like the tests are passing.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325)* status: 6 of 13 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325#-Niq5Zf1-invKro4jSmd:-Niq_QmZ9wOnw6yOq-gS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dea75d670796a20c64b3742f944f9bb28e5ec4dd/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be the name of the resulting command, i.e. the name of the binary target.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt` line 137 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325#-NiqE67w92Uh9_2Yp764:-Niq_RKe7fzsph-dRyNy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dea75d670796a20c64b3742f944f9bb28e5ec4dd/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt#L137)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can extract functions for `startMetricsServer` and `startReportsServer` which return channels. This will shorten the `run` method and limit the scope of some temporary variables.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServerMethods.kt` line 30 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325#-NiqjeeZEbt9XZ1t59Ai:-NiqjeeZEbt9XZ1t59Aj:b-m0o3h5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9b906839889039aae1146636126390beb67581f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServerMethods.kt#L30)):*
> ```Kotlin
> import org.wfanet.measurement.common.grpc.ErrorLoggingServerInterceptor
> import org.wfanet.measurement.common.grpc.LoggingServerInterceptor
> ```

Wrap this in an object to avoid polluting namespace.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServerMethods.kt` line 30 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325#-NiqjeeZEbt9XZ1t59Ai:-NiuG0qZ2OKZxI6CGhJX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9b906839889039aae1146636126390beb67581f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServerMethods.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wrap this in an object to avoid polluting namespace.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServerMethods.kt` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325#-NiuROUx5o3WpDnINp58:-NiuROUy7s4GEMagg7qL:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/806c96ffb563f1e196dbdcc81e83c0a389204475/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServerMethods.kt#L31)):*
> ```Kotlin
> import org.wfanet.measurement.common.grpc.LoggingServerInterceptor
> 
> object InProcessServerMethods {
> ```

nit



_Suggestion:_
```Kotlin
InProcessServers
```

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 4 of 6 files at r2, 1 of 3 files at r4, 2 of 4 files at r6, 2 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1325)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
