### PR TITLE
Refactor aws terraform

### PR DESCRIPTION
**Pull request by YuhongWang-Amazon**
This refactors the AWS terraform module so that many resources (e.g. postgres database, vpc, S3 bucket) could be shared by additional duchy or other components to be added.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1264)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
Nice cleanup!

> Reviewed 7 of 11 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1264#-:-NfY-Eqh2Zh5dGjvCFr0:b7oy6or)* status: all files reviewed, 2 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/terraform/aws/cmms/errored.tfstate` line 0 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1264#-NfXzV-n77W4JL5ic2az:-NfXzV-o1aQ_VIAGqFbY:bvatajp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab5f474511092dd45b285f141749ccc5698c9bb0/src/main/terraform/aws/cmms/errored.tfstate#L0)):*
Should this file be under version control?
___
*[`src/main/terraform/aws/modules/eks-cluster/main.tf` line 16 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1264#-NfXzfik8asfb6fcfIRz:-NfXzfik8asfb6fcfIS-:b-w3m02x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab5f474511092dd45b285f141749ccc5698c9bb0/src/main/terraform/aws/modules/eks-cluster/main.tf#L16)):*
> ```HCL
> 
> locals {
>   cluster_version       = "1.28"
> ```

Is this referring to the Kubernetes version? If so, I don't think we want a fixed version in the module. Does EKS not have an auto-update feature for K8s clusters like GKE has, where you just pick a release channel? If we can't just use something like that then this should be a var.



_Code quote:_
```HCL
"1.28"
```

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1264)* status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/terraform/aws/modules/eks-cluster/main.tf` line 16 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1264#-NfXzfik8asfb6fcfIRz:-NfcsacL7yqKj8144XGp:b-phefq0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab5f474511092dd45b285f141749ccc5698c9bb0/src/main/terraform/aws/modules/eks-cluster/main.tf#L16)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this referring to the Kubernetes version? If so, I don't think we want a fixed version in the module. Does EKS not have an auto-update feature for K8s clusters like GKE has, where you just pick a release channel? If we can't just use something like that then this should be a var.
</blockquote></details>

Yep. this is the kubernetes cluster version. I didn't see any default option to pick the latest. Hence making it a variable.
___
*[`src/main/terraform/aws/cmms/errored.tfstate` line  at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1264#-NfXzV-n77W4JL5ic2az:-NfcsSu_CGTYOVOkj67c:bt7hswn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab5f474511092dd45b285f141749ccc5698c9bb0/src/main/terraform/aws/cmms/errored.tfstate#L)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Should this file be under version control?
</blockquote></details>

Opps. Added this one by accident. removed

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1264)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Pull request merged**
