### PR TITLE
Check if there are duplicated dataProvider entries in the measurement.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/276)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/276)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 115 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/276#-MjalWyw6equnQUFmypp:-MjalWyw6equnQUFmypq:bacybsd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/91c0f900d3011b7dd05b7419bf7172fb4273ddb1/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L115)):*
> ```
> dataProvidersList
> ```
nit: reference the proto field name in error messages rather than language-specific proto generated code.

In this case, the field is `data_providers`.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/276)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/276)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 115 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/276#-MjalWyw6equnQUFmypp:-Mje3y9XAKM4OE0gLGWn:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/91c0f900d3011b7dd05b7419bf7172fb4273ddb1/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> dataProvidersList
> ```
nit: reference the proto field name in error messages rather than language-specific proto generated code.

In this case, the field is `data_providers`.
</blockquote></details>

done

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/276)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
