### PR TITLE
Prevent concurrent modification error.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/681)

### CODE REVIEW

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/681)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by tristanvuong2021** [comment]
The method findValidUnionSets does some list modifications. The problem is the coroutines are all calling this method and they all modify the same list. If the coroutines run in the same order they are launched, there is no problem, but any change in order throws a ConcurrentModificationException.

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/681)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/681)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
