### PR TITLE
Update common-jvm dep for base Java image update.

### PR DESCRIPTION
**Pull request by SanjayVas**
* Build and run using JDK 17.
* Use image based on Debian Bookworm for containerized builds.
* Update GitHub workflows to run on Ubuntu 22.04.
* Update Bazel to 7.1.0.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525)

**Comment by SanjayVas** [comment]
See https://github.com/world-federation-of-advertisers/common-jvm/issues/213 and https://github.com/world-federation-of-advertisers/containers/pull/13

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525)* status: 0 of 59 files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/writers/AdvanceComputationStage.kt` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-Nt3O4AF0q6kgCFaNqmt:-Nt3O4AG0dibh9ov32LS:bzgv2rb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95e724778ba01bd80ba813a24f1de5f3c5a3d453/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/writers/AdvanceComputationStage.kt#L89)):*
> ```Kotlin
>     }
> 
>     val writeTime = clock.instant().truncatedTo(ChronoUnit.MICROS)
> ```

FYI JDK 17 added nanosecond resolution support if the underlying system clock supports it. Postgres only support microsecond precision, so we need to truncate all of them so we don't return a timestamp at higher resolution than the one we wrote.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1518 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-Nt3Oa0O8V_9ZvSAhxQI:-Nt3Oa0O8V_9ZvSAhxQJ:b6z4ixc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95e724778ba01bd80ba813a24f1de5f3c5a3d453/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1518)):*
> ```Kotlin
>   }
> 
>   private val randomMock: Random = mock()
> ```

FYI SecureRandom cannot be mocked in JDK 17

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
Why are you preferring debian bookworm over ubuntu for containerized builds?

> Reviewed 53 of 59 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-:-NtGgcl11S837EwOMujL:b-jqdwzs)* status: 53 of 59 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt` line 250 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-NtGh4KE3PxoZ_7hXRZK:-NtGh4KE3PxoZ_7hXRZL:b-eenn7c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95e724778ba01bd80ba813a24f1de5f3c5a3d453/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt#L250)):*
> ```Kotlin
>       "Requested stage list contains non terminal stage."
>     }
>     grpcRequire(request.updatedBefore.nanos > 0) { "Timestamp resolution is 1 microsecond" }
> ```

when is this going to fail? Why was this needed?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1458 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-NtGhbJN4ww4mcDfpWaV:-NtGhbJN4ww4mcDfpWaW:b9anuoq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95e724778ba01bd80ba813a24f1de5f3c5a3d453/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1458)):*
> ```Kotlin
>   private class MeasurementSpecComponentFactory(
>     private val measurementSpecConfig: MeasurementSpecConfig,
>     private val secureRandom: Random,
> ```

this variable name should change if its not always assured to be a `SecureRandom`
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 266 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-NtGhkBP3S_pA7-CuhUG:-NtGhkBP3S_pA7-CuhUH:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95e724778ba01bd80ba813a24f1de5f3c5a3d453/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L266)):*
> ```Kotlin
>     private val measurementConsumersStub: MeasurementConsumersCoroutineStub,
>     private val encryptionKeyPairStore: EncryptionKeyPairStore,
>     private val secureRandom: Random,
> ```

ditto
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1518 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-Nt3Oa0O8V_9ZvSAhxQI:-NtGhmzdCJfQa5q89eVA:b5hv467) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95e724778ba01bd80ba813a24f1de5f3c5a3d453/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1518)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

FYI SecureRandom cannot be mocked in JDK 17
</blockquote></details>

why is that?
___
*[`tools/bazel-container` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-NtGi5i8-P-a_23q4m3D:-NtGi5i8-P-a_23q4m3E:burg4ap) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95e724778ba01bd80ba813a24f1de5f3c5a3d453/tools/bazel-container#L20)):*
> ```
> 
> readonly HOST_BAZEL="${BAZEL:-bazel}"
> readonly IMAGE="${IMAGE:-ghcr.io/world-federation-of-advertisers/bazel@sha256:f44cca282bc8d3d40e43c2f7e3bb32ff35b60739b9e04c2cd402beb868703f7c}"
> ```

this should be versioned, right?

**Review by SanjayVas — COMMENTED** [review]
The main reason for the change is technical. See https://github.com/world-federation-of-advertisers/containers/pull/13, which updates the Bazel build image. It switches from the deprecated rules_docker process (which was more akin to using a Dockerfile rather than repeatable builds) to one based on rules_oci/rules_distroless/rules_debian_packages. The latest version of the latter only supports Debian and not Ubuntu, though Ubuntu support is coming in the future.

In the end, any distro that can have the right versions of the dependencies installed would be fine. This is only for local containerized builds, as the official release artifacts are always built on a GitHub Actions runner. The Distroless image base we're using is based on Debian Bookworm, so in this case it's building on the same distro it will be running on.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-:-NtH5qJS3WAdLNMwK22L:boaxqdd)* status: 53 of 59 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1458 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-NtGhbJN4ww4mcDfpWaV:-NtHA96C9mbRzqQXowQA:b-z5121l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95e724778ba01bd80ba813a24f1de5f3c5a3d453/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1458)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this variable name should change if its not always assured to be a `SecureRandom`
</blockquote></details>

This **must** be a secure implementation of `Random`. We technically do not care what implementation so long as it is a secure one. We cannot enforce the implementation however, and naturally tests may use a different one.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1518 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-Nt3Oa0O8V_9ZvSAhxQI:-NtHB5MA8m7Yuin2ETpU:b-9ns2ck) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95e724778ba01bd80ba813a24f1de5f3c5a3d453/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1518)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why is that?
</blockquote></details>

It appears to be part of the changes for https://bugs.openjdk.org/browse/JDK-8248862

It's a final class, where `Random` is the interface. I don't think `SecureRandom` was ever intended to be subclassable/mockable.
___
*[`tools/bazel-container` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-NtGi5i8-P-a_23q4m3D:-NtHCa7n-rj7kQPR4usN:bgxf3m9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95e724778ba01bd80ba813a24f1de5f3c5a3d453/tools/bazel-container#L20)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this should be versioned, right?
</blockquote></details>

It will have an associated version after https://github.com/world-federation-of-advertisers/containers/pull/13 is released. Due to the nature of the repeatable builds, the release version should have the same image digest. I can wait until that release has happened and indicate the version here instead if you prefer.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525)* status: 52 of 59 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt` line 250 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-NtGh4KE3PxoZ_7hXRZK:-NtHGsKj09RTHdSsBQHS:b-fmg08v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95e724778ba01bd80ba813a24f1de5f3c5a3d453/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/PostgresComputationsService.kt#L250)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

when is this going to fail? Why was this needed?
</blockquote></details>

Dropped, because it's not actually needed.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 59 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525)* status: 58 of 59 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 2256 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-NtLh_nw1kvDHW8s8_mx:-NtLh_nx2XUkDgzaW8cq:blkevt5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bac85c07c9d6944823bdd88a9facaf47770384b/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L2256)):*
> ```Kotlin
>   @Before
>   fun initService() {
>     randomMock.stub {
> ```

insecureRandomMock maybe?
___
*[`tools/bazel-container` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525#-NtGi5i8-P-a_23q4m3D:-NtLhl253dqPKT_wQf-B:b1we0qg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95e724778ba01bd80ba813a24f1de5f3c5a3d453/tools/bazel-container#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It will have an associated version after https://github.com/world-federation-of-advertisers/containers/pull/13 is released. Due to the nature of the repeatable builds, the release version should have the same image digest. I can wait until that release has happened and indicate the version here instead if you prefer.
</blockquote></details>

Yes - I'd prefer to release that one first.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1525)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
