### PR TITLE
Make negation normal form apply the propagated not statements in the leaf nodes

### PR DESCRIPTION
**Pull request by uakyol**
This PR fixes this bug : https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1132

### CODE REVIEW

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1133)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidatorTest.kt` line 408 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1133#-Na8QR0137ihvmN__UbW:-Na8QR0137ihvmN__UbX:brqh8k8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb20816bcc8a4698bbb4c9dbdab04aa7585a3f97/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidatorTest.kt#L408)):*
> ```Kotlin
> 
>     val expectedNormalizedExpression =
>       "(!(person.gender == 2)  && true) && (!(person.age_group == 1) && " +
> ```

I know for non-operative node we always convert it to `True`, ex: `video.viewed_fraction > 0.25`. But for the case that the input expression is `!(person.gender == 2  && video.viewed_fraction > 0.25)`, the code outputs `(!(person.gender == 2) || true)` which is always evaluated as `True`. Is that ok for the PBM?

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1133)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidatorTest.kt` line 408 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1133#-Na8QR0137ihvmN__UbW:-Na8UXBe1X4_D8wP7ZSy:bycowdr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb20816bcc8a4698bbb4c9dbdab04aa7585a3f97/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidatorTest.kt#L408)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I know for non-operative node we always convert it to `True`, ex: `video.viewed_fraction > 0.25`. But for the case that the input expression is `!(person.gender == 2  && video.viewed_fraction > 0.25)`, the code outputs `(!(person.gender == 2) || true)` which is always evaluated as `True`. Is that ok for the PBM?
</blockquote></details>

Yes, the design is done this way. Basically, worst case we will charge more buckets but never less than intended.

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidatorTest.kt` line 408 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1133#-Na8QR0137ihvmN__UbW:-Na8XI1K-rtI1yr1p8M0:by4y8q1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb20816bcc8a4698bbb4c9dbdab04aa7585a3f97/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidatorTest.kt#L408)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Yes, the design is done this way. Basically, worst case we will charge more buckets but never less than intended. 
</blockquote></details>

Got it. Thanks for clarifying!

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Pull request merged**
