### PR TITLE
Hide requisitions with participant params not set from public list requisitions response.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
Thanks for taking care of this!

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432#-:-MuqtZLjAK7Wb0CLmIuX:btrfu2e)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, line 245 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432#-Mv661920j5aZ5uVfRqt:-Mv66193A1_gwsEVrg0s:bpeog0v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e891eed84769bf34b40f40fc53f8a42881af3a8/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt#L245)):*
> ```Kotlin
> }
> 
> /** Converts a kingdom internal Measurement.State to system Api Requisition.State. */
> ```

nit: `Computation`



_Code quote:_
```Kotlin
Requisition
```
___
*[src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432#-Mv66NlQEbdHPLsv1YMv:-Mv66NlQEbdHPLsv1YMw:bq8ipru) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e891eed84769bf34b40f40fc53f8a42881af3a8/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L61)):*
> ```protobuf
>     int64 external_data_provider_id = 3;
>     repeated Requisition.State states = 4;
>     repeated Measurement.State measurement_states = 5;
> ```

The goal was to have internal Requisition states that could be used to determine visibility without needing to look at other fields. That means we should be able to drop this field from the filter, no?



_Code quote:_
```protobuf
    repeated Measurement.State measurement_states = 5;
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432)* status: 2 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432#-Mv66NlQEbdHPLsv1YMv:-MvKglPPBQg98ioh135a:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e891eed84769bf34b40f40fc53f8a42881af3a8/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The goal was to have internal Requisition states that could be used to determine visibility without needing to look at other fields. That means we should be able to drop this field from the filter, no?
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 11 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 120 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432#-MvLMYsTDscjpIBfoT4G:-MvLMYsTDscjpIBfoT4H:b7v6eqe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a0ed977ef1a389680ed17a58b4ca02ce3800db79/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L120)):*
> ```Kotlin
>                 }
> 
>                 // If no Requisition state is specified, still exclude if params haven't been set.
> ```

nit: confusing comment

I assume you meant to say something like "Include all visible states if no state filter set in public request."



_Code quote:_
```Kotlin
// If no Requisition state is specified, still exclude if params haven't been set.
```

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 11 files at r2, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement.proto, line 161 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432#-MvPYZgnCEEC1sk-BYgv:-MvPYZgnCEEC1sk-BYgw:bdso3to) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5f80895d6185fd6d4d25e621a7c79209ea1df421/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L161)):*
> ```protobuf
>   enum State {
>     STATE_UNSPECIFIED = 0;
>     PENDING_PARAMS = 1;
> ```

what is this state meant to capture? Can you add some documentation?

**Comment by tristanvuong2021** [comment]
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement.proto, line 161 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432#-MvPYZgnCEEC1sk-BYgv:-MvPiEt493GowrJnCFDb:b-rfymek) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5f80895d6185fd6d4d25e621a7c79209ea1df421/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L161)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what is this state meant to capture? Can you add some documentation?
</blockquote></details>

Added it. Also see the linked issue: https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/421

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 11 files at r2, 1 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/432)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
