### PR TITLE
Check event filter if null or blank.

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1035)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1035** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1035" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1035?utm_source=stack-comment).

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1035)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariolamassaavedra)

**Review by tristanvuong2021 — APPROVED** [review]

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1035)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariolamassaavedra and @stevenwarejones)

**Review by mariolamassaavedra — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1035)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
