### PR TITLE
Make duchy storage writing error transient.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClients.kt` line 135 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656#-O-37WZX2GTZTb8n3FUS:-O-37WZYDz3E_isRPORs:b-o1hacm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57f1b3485b9ea25297ffe52feed03e83f5ad1217/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClients.kt#L135)):*
> ```Kotlin
>           content,
>         )
>       } catch (e: Exception) {
> ```

Do we want to be more specific about the type of exception, like checking for the 50x errors that we were seeing in logs?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClients.kt` line 135 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656#-O-37WZX2GTZTb8n3FUS:-O-3ASFP2w0iDJQ91F4V:bi1hmi5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57f1b3485b9ea25297ffe52feed03e83f5ad1217/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClients.kt#L135)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Do we want to be more specific about the type of exception, like checking for the 50x errors that we were seeing in logs?
</blockquote></details>

+1. We cannot treat all blob write errors as transient. e.g. if it's some kind of invalid argument error (e.g. 400), that would be a permanent one. An unavailable error (e.g. 503) would be transient.

See [HTTP to gRPC Status Code Mapping](https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md) and [gRPC Status Codes](https://grpc.github.io/grpc/core/md_doc_statuscodes.html), where the latter gives information on whether an error might be retriable.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClients.kt` line 135 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656#-O-37WZX2GTZTb8n3FUS:-O-CkU8P01GXCCJh2G0B:b-s0c049) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57f1b3485b9ea25297ffe52feed03e83f5ad1217/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClients.kt#L135)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

+1. We cannot treat all blob write errors as transient. e.g. if it's some kind of invalid argument error (e.g. 400), that would be a permanent one. An unavailable error (e.g. 503) would be transient.

See [HTTP to gRPC Status Code Mapping](https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md) and [gRPC Status Codes](https://grpc.github.io/grpc/core/md_doc_statuscodes.html), where the latter gives information on whether an error might be retriable.
</blockquote></details>

https://github.com/world-federation-of-advertisers/common-jvm/pull/254
Updated common-jvm to check whether the StorageException is retriable.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`MODULE.bazel` line 131 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656#-O-IhuHC1sc9lX07F0LV:-O-IhuHC1sc9lX07F0LW:b7g7ypc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3e30b970e189733c63c51e8f8d2f673a8c59bfd8/MODULE.bazel#L131)):*
> ```Starlark
> )
> 
> # DO_NOT_SUBMIT: Use release version.
> ```

Would you mind making this a separate prefactoring PR so you can swap to the common-jvm version of ExponentialBackoff everywhere?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`MODULE.bazel` line 131 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656#-O-IhuHC1sc9lX07F0LV:-O-IiPbP3AkUnh-sXv2v:blyphgp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3e30b970e189733c63c51e8f8d2f673a8c59bfd8/MODULE.bazel#L131)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Would you mind making this a separate prefactoring PR so you can swap to the common-jvm version of ExponentialBackoff everywhere?
</blockquote></details>

No problem.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`MODULE.bazel` line 131 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656#-O-IhuHC1sc9lX07F0LV:-O-MvPrC16FS7azoI-fz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3e30b970e189733c63c51e8f8d2f673a8c59bfd8/MODULE.bazel#L131)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

No problem.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`MODULE.bazel.lock` line 3 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656#-O-N5xkA-HxFcWaXfrFQ:-O-N5xkA-HxFcWaXfrFR:b1w9whj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/786075ce7aec2a9bab35e27c5bf78dc78e1f53c3/MODULE.bazel.lock#L3)):*
> ```JSON
> {
>   "lockFileVersion": 6,
>   "moduleFileHash": "44b263166adabb5e6056d84f3bc1c3a6054284f3630e9d1f5301b66beec99366",
> ```

This file should be unchanged by this PR.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`MODULE.bazel.lock` line 3 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656#-O-N5xkA-HxFcWaXfrFQ:-O-NPJ0d13205VpbPxZY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/786075ce7aec2a9bab35e27c5bf78dc78e1f53c3/MODULE.bazel.lock#L3)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This file should be unchanged by this PR.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1656)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
