### PR TITLE
Update common-jvm for Postgres testing.

### PR DESCRIPTION
**Pull request by SanjayVas**
The unused AWS Kingdom schema and its associated test are deleted.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169)

**Comment by SanjayVas** [comment]
Depends on https://github.com/world-federation-of-advertisers/common-jvm/pull/211

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169)* status: 0 of 36 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169#-Nbq0XueBiouRex0-T9a:-Nbq0XueBiouRex0-T9b:b-1prcak) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17d852d5d5cc530e69657026f4db153228a24470/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L39)):*
> ```Kotlin
>  *   by the backing store and should not be used outside this backing store.
>  *
>  * TODO(@uakyol): Use R2DBC-based
> ```

CC @uakyol 
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt` line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169#-Nbq0i_mCTkyVywyyCVn:-Nbq0i_mCTkyVywyyCVo:b-n23lmo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17d852d5d5cc530e69657026f4db153228a24470/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt#L49)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> abstract class ReportingSetsServiceTest<T : ReportingSetsCoroutineImplBase> {
> ```

@tristanvuong2021 this test was failing for some reason when I switched to PostgresDatabaseProviderRule. My first attempt was to simplify the test cases using a sequential ID generator. That worked, so I didn't investigate further. I can share the failure details if you'd like to take a look.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt` line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169#-Nbq0Rr0C57JsgrT5HNo:-Nbq0Rr0C57JsgrT5HNp:b-1prcak) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17d852d5d5cc530e69657026f4db153228a24470/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt#L61)):*
> ```Kotlin
>      * PostgreSQL test container.
>      *
>      * TODO(@uakyol): Use [org.wfanet.measurement.common.db.r2dbc.postgres.testing.PostgresDatabaseProviderRule]
> ```

CC @uakyol

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 35 of 36 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsServiceTest.kt` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169#-NbqOoW9BXgrfqYhZ6Ud:-NbqOoW9BXgrfqYhZ6Ue:bco4azg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e07078401a594a7d509ee69524d336ca7cdcc10c/src/test/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsServiceTest.kt#L31)):*
> ```Kotlin
>     idGenerator: IdGenerator,
>   ): PostgresReportingSetsService {
>     val dbClient: PostgresDatabaseClient = databaseProvider.createDatabase()
> ```

nit: Noticed that this was renamed to dbClient, but the rest was kept as client.

**Review by YuhongWang-Amazon — APPROVED** [review]
> Reviewed 34 of 36 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169)* status: 34 of 36 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021 and @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt` line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169#-Nbq0i_mCTkyVywyyCVn:-NbuDRAPDFiL9iN40RWM:bv0s4eh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/17d852d5d5cc530e69657026f4db153228a24470/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@tristanvuong2021 this test was failing for some reason when I switched to PostgresDatabaseProviderRule. My first attempt was to simplify the test cases using a sequential ID generator. That worked, so I didn't investigate further. I can share the failure details if you'd like to take a look.
</blockquote></details>

Actually the sequential ID generator wasn't even needed since this API now has user-specified IDs.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsServiceTest.kt` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169#-NbqOoW9BXgrfqYhZ6Ud:-NbuD8JtA0T7cLYyxGNW:b-wrkshg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8c75a474febdded3cf54aaadc7e7c9ab6b08b8c/src/test/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsServiceTest.kt#L31)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

nit: Noticed that this was renamed to dbClient, but the rest was kept as client.
</blockquote></details>

Ah, it wasn't renamed but extracted to a new variable. I don't think the inconsistency here is a big issue (arguably `client` everywhere else is a bit vague, but not worth going and renaming them all).

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021 and @YuhongWang-Amazon)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1169)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021 and @YuhongWang-Amazon)

**Pull request merged**
