### PR TITLE
Add MeasurementResultSubject Truth extension.

### PR DESCRIPTION
**Pull request by SanjayVas**
This makes correctness test failure messages more clear.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1002)

**Review by riemanli — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1002)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 316 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1002#-NVBueO4-dzdatFUpjQ-:-NVBueO4-dzdatFUpjQ0:biuu522) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4f32c119e5fd01beee3cb518955c1131f29fbcc5/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L316)):*
> ```Kotlin
>     maximumFrequency: Long
>   ) {
>     // TODO(@riemanli): Use margin of error once its returned with the result.
> ```

Does the margin of error here mean the error bar of the kingdom measurements?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1002)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 316 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1002#-NVBueO4-dzdatFUpjQ-:-NVV9tRJATaHSwDbiZny:bwwqi8q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cfc72f8b834a6f2cfbedb282250ce92a578ac3b/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L316)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Does the margin of error here mean the error bar of the kingdom measurements?
</blockquote></details>

Yes, though after discussion with Craig I think we don't need it in the API. We can just compute it here for the test. I rephrased the comment slighlty.

**Review by riemanli — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1002)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by Marco-Premier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1002)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
