### PR TITLE
Add reporting set tags

### PR DESCRIPTION
**Pull request by riemanli**
This PR implements the tags field which was added to `ReportingSet` in #1251. A change to the DB schema is needed.

### CODE REVIEW

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1283** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1283" target="_blank">Graphite</a> 
    * **PR #1288** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1288" target="_blank">Graphite</a> 
      * **PR #1289** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1289" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1289?utm_source=stack-comment).

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1289)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by riemanli — COMMENTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
