### PR TITLE
feat: Increase chance of getting Event Groups from Reporting Server ListEventGroups

### PR DESCRIPTION
**Pull request by tristanvuong2021**
feat: Increase chance of getting Event Groups from Reporting Server ListEventGroups

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
nit: I'd consider this "feat" rather than "fix", as it's not fixing a bug but rather improving the experience (#1660 is an enhancement)

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762#-:-O4RNom8DJgBFLjiagLR:bh31de8)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt` line 85 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762#-O4ROM-7-6Jb1iFGk1m2:-O4ROM-7-6Jb1iFGk1m3:bg5751x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6af29b15f86aa4d00fa7e5bc9e02e468a3eecb49/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt#L85)):*
> ```Kotlin
>     var numAttempts = 0
> 
>     while (numAttempts < LIST_EVENT_GROUPS_MAX_ATTEMPTS) {
> ```

Do we need a max attempts? This isn't a retry, but rather coalescing results.

If we want to put a cap on latency for this, we can check the remaining deadline from the gRPC context and stop when we're too close to that deadline.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt` line 85 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762#-O4ROM-7-6Jb1iFGk1m2:-O4RP3cpCqwkoA-DJtBJ:b46hl6d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6af29b15f86aa4d00fa7e5bc9e02e468a3eecb49/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt#L85)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we need a max attempts? This isn't a retry, but rather coalescing results.

If we want to put a cap on latency for this, we can check the remaining deadline from the gRPC context and stop when we're too close to that deadline.
</blockquote></details>

`Context.current().getDeadline()`

https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html#getDeadline()

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt` line 85 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762#-O4ROM-7-6Jb1iFGk1m2:-O4Rn1S1EWiZi5bf3qLM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6af29b15f86aa4d00fa7e5bc9e02e468a3eecb49/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt#L85)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`Context.current().getDeadline()`

https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html#getDeadline()
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt` line 87 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762#-O4RwwBr54VReSJwNDLi:-O4RwwBs-mQdAjBpno88:bdm9tsi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db5f5b909bbcf880e15b10220c6da818de2d5e11/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt#L87)):*
> ```Kotlin
>     var nextPageToken = request.pageToken
>     val deadline = Context.current().deadline ?: Deadline.after(30, TimeUnit.SECONDS)
>     while (deadline.timeRemaining(TimeUnit.SECONDS) > 5) {
> ```

If the total deadline is < 5 seconds won't this return an empty response with no next page token? Perhaps this should be a do-while so that at least one iteration happens before the deadline condition is checked.



_Code quote:_
```Kotlin
deadline.timeRemaining(TimeUnit.SECONDS) > 5
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt` line 87 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762#-O4RwwBr54VReSJwNDLi:-O4SBtyqCPJaHvXg1FIv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db5f5b909bbcf880e15b10220c6da818de2d5e11/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt#L87)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If the total deadline is < 5 seconds won't this return an empty response with no next page token? Perhaps this should be a do-while so that at least one iteration happens before the deadline condition is checked.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1762)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
