### PR TITLE
Using CMMS event group key for CMMS event groups.

### PR DESCRIPTION
**Pull request by riemanli**
Bug-fix for issue #1034

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1038)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1035** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1035" target="_blank">Graphite</a> 
    * **PR #1038** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1038" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1038?utm_source=stack-comment).

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1038)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by Marco-Premier — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1038)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1125 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1038#-NWkuV_I6vgyZDZgWvzQ:-NWkuV_I6vgyZDZgWvzR:b9vksik) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70f6beccdbf46c4f60f385a7b46653b1e473774d/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1125)):*
> ```Kotlin
>               key =
>                 org.wfanet.measurement.api.v2alpha
>                   .EventGroupKey(
> ```

shall we make this as full import statement?

```import org.wfanet.measurement.api.v2alpha.EventGroupKey```

and then just use ```key = EventGroupKey(...)``` ?



_Code quote:_
```Kotlin
                org.wfanet.measurement.api.v2alpha
                  .EventGroupKey(
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 539 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1038#-NWkuqgA4PveobGU_qFx:-NWkuqgA4PveobGU_qFy:b-ia41wb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70f6beccdbf46c4f60f385a7b46653b1e473774d/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L539)):*
> ```Kotlin
>       eventGroupEntry {
>         key =
>           org.wfanet.measurement.api.v2alpha
> ```

same comment as above



_Code quote:_
```Kotlin
org.wfanet.measurement.api.v2alpha
```

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1038)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1125 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1038#-NWkuV_I6vgyZDZgWvzQ:-NWmrjbf6w43zXHZAS-m:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70f6beccdbf46c4f60f385a7b46653b1e473774d/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1125)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

shall we make this as full import statement?

```import org.wfanet.measurement.api.v2alpha.EventGroupKey```

and then just use ```key = EventGroupKey(...)``` ?
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 539 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1038#-NWkuqgA4PveobGU_qFx:-NWmt9Jo9y5P-0uFQJ79:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70f6beccdbf46c4f60f385a7b46653b1e473774d/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L539)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

same comment as above
</blockquote></details>

Done.

**Review by Marco-Premier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1038)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @stevenwarejones and @tristanvuong2021)

**Review by riemanli — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1038)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
