### PR TITLE
 Fix extraction of EventGroup's Metadata

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/656)

And use encryption/decryption functions from consent-signaling-client.

### CODE REVIEW

**Comment by renjiezh** [comment]
As discussed in (https://github.com/world-federation-of-advertisers/consent-signaling-client/pull/39#pullrequestreview-1067142704), the MetaData does need to sign.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 12 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/656)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/656)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 680 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/656#-N97pEBj1EWlmj8WuKI8:-N97pEBj1EWlmj8WuKI9:b-ts2hl4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33d0fa25141332cbc4e7e70445a08876c8c34a34/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L680)):*
> ```Kotlin
>     val result = Measurement.Result.parseFrom(signedResult.data)
> 
>     if (!verifyResult(signedResult.signature, result, readCertificate(certificate.x509Der))) {
> ```

serializing result isn't guaranteed to be deterministic is it? If so, I think the old way was better.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/656)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 680 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/656#-N97pEBj1EWlmj8WuKI8:-N97pscI3BsaSvsioMHd:b-chvdqp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33d0fa25141332cbc4e7e70445a08876c8c34a34/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L680)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

serializing result isn't guaranteed to be deterministic is it? If so, I think the old way was better.
</blockquote></details>

Correct, it is not deterministic. 
And the old `verifyResult()` would serialize the `result` back to bytes which caused the bug of non-deterministic to verification. Thus we need the new `verifyResult()`to verify the signature right against the bytes of `signedResult`.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/656)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 680 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/656#-N97pEBj1EWlmj8WuKI8:-N97sV394I9OboDI6atf:bkxuc6p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33d0fa25141332cbc4e7e70445a08876c8c34a34/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L680)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Correct, it is not deterministic. 
And the old `verifyResult()` would serialize the `result` back to bytes which caused the bug of non-deterministic to verification. Thus we need the new `verifyResult()`to verify the signature right against the bytes of `signedResult`.
</blockquote></details>

sorry - was reading the old code as the new code - you have it correct :)

**Review by chipingyeh — APPROVED** [review]
> Reviewed 12 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/656)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 9 of 12 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/656)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
