### PR TITLE
Update workflows for QA environment.

### PR DESCRIPTION
**Pull request by SanjayVas**
This includes updating TLS certificates to add subject alternative names for qa.halo-cmm.org.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1546)

**Review by YuhongWang-Amazon — COMMENTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1546)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`.github/workflows/deploy-qa.yml` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1546#-NuYZOB0AFv1SvDI8Trd:-NuYZOB11ox5lhTMr2RQ:bcf2eoh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6a3ed41798c0b01687ad9635d1a2e940840efaa/.github/workflows/deploy-qa.yml#L15)):*
> ```YAML
> # limitations under the License.
> 
> name: Deploy to dev environment
> ```

Are there any reason why we only want this workflow for qa env?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1546)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

___
*[`.github/workflows/deploy-qa.yml` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1546#-NuYZOB0AFv1SvDI8Trd:-Nu_-j5AElvPPgGjYXaw:b-jjllft) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6a3ed41798c0b01687ad9635d1a2e940840efaa/.github/workflows/deploy-qa.yml#L15)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

Are there any reason why we only want this workflow for qa env?
</blockquote></details>

This is the workflow for deploying on release. I renamed it to make that more clear.

**Review by YuhongWang-Amazon — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1546)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
