### PR TITLE
feat: Expose panel exchange flags via CUE tags

### PR DESCRIPTION
**Pull request by robinsons**
This introduces CUE files with important panel exchange flags configurable via tags using `--define`.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1795)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1795)* status: all files reviewed, 3 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[`src/main/k8s/panelmatch/dev/kingdomless_daemon_aws.cue` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1795#-O6SutGb2OtEfhEbYLmo:-O6SutGb2OtEfhEbYLmp:b-z41xpm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d500c6a5e59e8146e3f51c7ab2f9d8a72f4aa7/src/main/k8s/panelmatch/dev/kingdomless_daemon_aws.cue#L35)):*
> ```CUE
> 		requests: {
> 			cpu:    "100m"
> 			memory: "1Gi"
> ```

Memory request should match memory limit, as memory is incompressible. It's also common to leave off CPU limit and just let anything grow to the size of the node, as long as every container has a sufficient CPU request.
___
*[`src/main/k8s/panelmatch/dev/kingdomless_daemon_gke.cue` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1795#-O6Sl3IS6CrZDHmgicJU:-O6Sl3IT2SgvBGx9p7OS:b-k2nplf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d500c6a5e59e8146e3f51c7ab2f9d8a72f4aa7/src/main/k8s/panelmatch/dev/kingdomless_daemon_gke.cue#L20)):*
> ```CUE
> _partyId:                   string @tag("party_id")
> _recurringExchangeIds:      string @tag("recurring_exchange_ids")
> _iamServiceAccountName:     string @tag("iam_service_account_name")
> ```

nit: if this is just the name, you can choose to have this be hard-coded. e.g. for the Kingdom internal server, we assume that you have an IAM service account named "kingdom-internal"
___
*[`src/main/k8s/panelmatch/dev/kingdomless_daemon_gke.cue` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1795#-O6SuU5K-GxwDRkMdmuR:-O6SuU5K-GxwDRkMdmuS:b58kt5a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d500c6a5e59e8146e3f51c7ab2f9d8a72f4aa7/src/main/k8s/panelmatch/dev/kingdomless_daemon_gke.cue#L32)):*
> ```CUE
> _certOrganization:          string @tag("cert_organization")
> _certDnsName:               string @tag("cert_dns_name")
> _certValidDays:             string @tag("cert_valid_days")
> ```

nit: this can also be hard-coded as it need not differ per environment. If someone wants to change it, they can do so in the generated YAML

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1795)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/k8s/panelmatch/dev/kingdomless_daemon_aws.cue` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1795#-O6SutGb2OtEfhEbYLmo:-O6T2mO7EjCRuZJtZfU1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13d500c6a5e59e8146e3f51c7ab2f9d8a72f4aa7/src/main/k8s/panelmatch/dev/kingdomless_daemon_aws.cue#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Memory request should match memory limit, as memory is incompressible. It's also common to leave off CPU limit and just let anything grow to the size of the node, as long as every container has a sufficient CPU request.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1795)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[`src/main/k8s/panelmatch/dev/kingdomless_daemon_aws.cue` line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1795#-O6TJw2VDBZ0sScHSDUE:-O6TJw2VDBZ0sScHSDUF:b-m71g9t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73d1af03694c7d50665221ff41ee3079e399b024/src/main/k8s/panelmatch/dev/kingdomless_daemon_aws.cue#L33)):*
> ```CUE
> 	resources: ResourceRequirements=#ResourceRequirements & {
> 		requests: {
> 			memory: "2Gi"
> ```

nit: you probably still want a CPU request to make sure there's enough room on the node. It's just the CPU limit that's unnecessary

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1795)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/k8s/panelmatch/dev/kingdomless_daemon_aws.cue` line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1795#-O6TJw2VDBZ0sScHSDUE:-O6TL99G-GK9odqz-tXB:b9xclk8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73d1af03694c7d50665221ff41ee3079e399b024/src/main/k8s/panelmatch/dev/kingdomless_daemon_aws.cue#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: you probably still want a CPU request to make sure there's enough room on the node. It's just the CPU limit that's unnecessary
</blockquote></details>

Aha, I overlooked the distinction from your previous comment. Thanks!

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1795)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @robinsons)

**Pull request merged**
