### PR TITLE
Implement ConfirmComputationParticipant and FailComputationParticipant for internal spannerComputationParticipantService

### PR DESCRIPTION
**Pull request by uakyol**
https://rally1.rallydev.com/#/604612930531d/portfolioitemstreegrid?detail=%2Ftask%2F607707755241&fdp=true?fdp=true

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjB9UY_-e-5Y-IIga8T:-MjB9UYa8lacUdF7xstm:b-73gwa1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66d2f66e02b0194d2ecaf246353036106c4c780b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt#L83)):*
> ```
> CREATED 
> ```
REQUISITION_PARAMS_SET
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt, line 73 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBACzl0xiRIvE3sHS6:-MjBACzl0xiRIvE3sHS7:b3ozbe9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66d2f66e02b0194d2ecaf246353036106c4c780b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L73)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     updateMeasurementState(
>       InternalId(measurementConsumerId),
>       InternalId(measurementId),
>       Measurement.State.FAILED
>     )
> ```
</details>

we should only update the measurementState if it is not in a terminal state yet.

For example, if the measurement is already CANCELLED, we shouldn't change it to FAILED.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjB9UY_-e-5Y-IIga8T:-MjBY5Cs5-u7OdyRpUmK:bdi4kad) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66d2f66e02b0194d2ecaf246353036106c4c780b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt#L83)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> CREATED 
> ```
REQUISITION_PARAMS_SET
</blockquote></details>

good catch thanks!
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt, line 73 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBACzl0xiRIvE3sHS6:-MjBegoHABtQIe7PTUXe:b-p9t2eq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66d2f66e02b0194d2ecaf246353036106c4c780b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L73)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     updateMeasurementState(
>       InternalId(measurementConsumerId),
>       InternalId(measurementId),
>       Measurement.State.FAILED
>     )
> ```
we should only update the measurementState if it is not in a terminal state yet.

For example, if the measurement is already CANCELLED, we shouldn't change it to FAILED.
</blockquote></details>

I see. I updated it. However, in that case Computation Participant State won't be updated either since runTransaction will throw and execute wont commit the transaction. wdyt? I didn't write the test case just did a reference implementation, if we agree we should go this route, I'll write a test.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt, line 73 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBACzl0xiRIvE3sHS6:-MjBh2yG4SuCXfDK0HPX:b99w3qb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66d2f66e02b0194d2ecaf246353036106c4c780b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L73)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I see. I updated it. However, in that case Computation Participant State won't be updated either since runTransaction will throw and execute wont commit the transaction. wdyt? I didn't write the test case just did a reference implementation, if we agree we should go this route, I'll write a test.
</blockquote></details>

sgtm. The requisitionsService refuseRequisition is doing it in a similar way

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: all files reviewed, 8 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt, line 95 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBiSeN859Yf9xf-xfE:-MjBiSeN859Yf9xf-xfF:b-iyzmrg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt#L95)):*
> ```
> "Computation participant not in REQUISITION_PARAMS_SET state."
> ```
nit: The expected state should only be encoded in one place. In this case, it's the writer class. If we want to pass this information in the future, we should update KingdomInternalException (or a subclass thereof) to include it.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt, line 118 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBjc0hBwU0V0tWnxHh:-MjBjc0hBwU0V0tWnxHi:bf9s3rs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt#L118)):*
> ```
> readWithIds
> ```
How is this different than `readByExternalComputationId`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjB9UY_-e-5Y-IIga8T:-MjBjxJ08NgY5Tu1uDQu:bxvlbpg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66d2f66e02b0194d2ecaf246353036106c4c780b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt#L83)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

good catch thanks!
</blockquote></details>

Don't hard-code strings with enum names. Use Kotlin string templating, i.e. `${ComputationParticipant.State.REQUISITION_PARAMS_SET}`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBkOml6KzjRI_t3PxX:-MjBkOml6KzjRI_t3PxY:b3e7aec) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L33)):*
> ```
> computationPartcipant
> ```
nit: ComputationParticipant (typo)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt, line 64 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBk_Fz802moNnh2wgx:-MjBk_Fz802moNnh2wgy:bkt6tye) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L64)):*
> ```
>     val computationParticipant = computationParticipantResult.computationParticipant
>     val measurementId = computationParticipantResult.measurementId
>     val measurementConsumerId = computationParticipantResult.measurementConsumerId
> ```
nit: use a [destructuring declaration](https://kotlinlang.org/docs/destructuring-declarations.html)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, line 411 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBmMNj8Ia3e4brx1NT:-MjBmMNj8Ia3e4brx1NU:b6r04ci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L411)):*
> ```Kotlin
>     }
> 
>     assertThat(computationParticipant)
> ```

This only verifies that the returned participant is correct, but not that it was actually persisted.

Two steps for proper verification:
1. Verify the specific fields you expected to be updated by this SUT.
2. Get the ComputationParticipant from one of the internal services and make sure that equals exactly.
    * Since we don't have a `GetComputationParticipant` method, you can use `GetMeasurementByComputationId`.

See PR #259 for an example.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, line 460 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBlp6i5_16DI-XMgEo:-MjBlp6i5_16DI-XMgEp:bl0jgpu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L460)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
>     requisitionsService.fulfillRequisition(
>       fulfillRequisitionRequest {
>         externalComputationId = measurement.externalComputationId
>         externalRequisitionId = requisitions[0].externalRequisitionId
>         externalFulfillingDuchyId = EXTERNAL_DUCHY_IDS.get(0)
>         dataProviderParticipationSignature = participationSignature
>       }
>     )
>     requisitionsService.fulfillRequisition(
>       fulfillRequisitionRequest {
>         externalComputationId = measurement.externalComputationId
>         externalRequisitionId = requisitions[1].externalRequisitionId
>         externalFulfillingDuchyId = EXTERNAL_DUCHY_IDS.get(1)
>         dataProviderParticipationSignature = participationSignature
>       }
>     )
> ```
</details>

nit: loop through requisitions. For this test, there's no need for each to be fulfilled from a different Duchy.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, line 478 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBlgmBAyF6LzvQ2ySR:-MjBlgmBAyF6LzvQ2ySS:b-3r97qz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L478)):*
> ```
> duchyCertificate in duchyCertificates.values
> ```
nit: just loop through EXTERNAL_DUCHY_IDS. Looping through the certificates is odd just to get the duchy IDs.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt, line 95 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBiSeN859Yf9xf-xfE:-MjBs7s51oZ1ZON3qAAQ:byd2fcc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt#L95)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> "Computation participant not in REQUISITION_PARAMS_SET state."
> ```
nit: The expected state should only be encoded in one place. In this case, it's the writer class. If we want to pass this information in the future, we should update KingdomInternalException (or a subclass thereof) to include it.
</blockquote></details>

Sorry I am not sure I understand correctly. I am guessing what you mean is just sending  "Computation participant in illegal state" is fine here? Is that correct?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt, line 118 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBjc0hBwU0V0tWnxHh:-MjBosbI0BpBSVc4lAi4:b-k5u8fr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt#L118)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> readWithIds
> ```
How is this different than `readByExternalComputationId`?
</blockquote></details>


:facepalm:  it is not, thanks for catching.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjB9UY_-e-5Y-IIga8T:-MjBpDnL0yQsgh4yceWp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66d2f66e02b0194d2ecaf246353036106c4c780b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't hard-code strings with enum names. Use Kotlin string templating, i.e. `${ComputationParticipant.State.REQUISITION_PARAMS_SET}`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt, line 73 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBACzl0xiRIvE3sHS6:-MjBo8_w0hb10mYCVr_K:bhrxarv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66d2f66e02b0194d2ecaf246353036106c4c780b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L73)):*
> refuseRequisition
done

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: all files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt, line 95 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBiSeN859Yf9xf-xfE:-MjC--IvDxBTDwiYzQ2N:bb77ufg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt#L95)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Sorry I am not sure I understand correctly. I am guessing what you mean is just sending  "Computation participant in illegal state" is fine here? Is that correct?
</blockquote></details>

Yes.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt, line 66 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjC-8lhDulZZqFtCPNp:-MjC-8lhDulZZqFtCPNq:bn6vzh6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57c81ed9a9e7547a5b29a38b61496597e1f68c05/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L66)):*
> ```
> val state = 
> ```
nit: don't need a separate val here since you already have `measurementState`.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, line 411 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBmMNj8Ia3e4brx1NT:-MjEvpUq90DanRq3SFNe:b-2mwiup) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L411)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This only verifies that the returned participant is correct, but not that it was actually persisted.

Two steps for proper verification:
1. Verify the specific fields you expected to be updated by this SUT.
2. Get the ComputationParticipant from one of the internal services and make sure that equals exactly.
    * Since we don't have a `GetComputationParticipant` method, you can use `GetMeasurementByComputationId`.

See PR #259 for an example.
</blockquote></details>

Sanjay, this is so good, thank you! It revealed a bug, I wasn't updating the UpdateTime. I changed the test for failComputationParticipant to reflect this as well.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt, line 118 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBjc0hBwU0V0tWnxHh:-MjFufhE6mnxTge-Kexf:b420f3g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt#L118)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

:facepalm:  it is not, thanks for catching.
</blockquote></details>

Duplicate function still exists.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt, line 118 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226#-MjBjc0hBwU0V0tWnxHh:-MjG-4tI614V2JyQAjPT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/094c6e6344827c5d5a6951cb43d9bd9991975223/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt#L118)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Duplicate function still exists.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @wangyaopw, and @zachcwc)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)

**Review by uakyol — COMMENTED** [review]
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)

**Review by uakyol — COMMENTED** [review]
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Comment by SanjayVas** [comment]
This is for #103.

**Pull request merged**
