### PR TITLE
 fix: check updated and created fields before assignment

### LINKED ISSUE #1893: ListMeasurements returns no results when timestamp filter bounds are not set
The issue appears to be that the internal request builder blindly copies the timestamp filters rather than first checking that they are indeed specified. This results in requests having e.g. both a `created_before` and `created_after` always set. If the public API request does not have the filter field specified, it will be copied as a default timestamp instance which effectively means "the beginning of the epoch". The only case where ListMeasurements would actually get a result is if all 4 timestamp filter field are specified.

**Component(s) affected**
Kingdom

**Version**
HEAD (latest: v0.5.12)

### PR DESCRIPTION
**Pull request by roaminggypsy**
Closes #1893

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1895)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1895)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1895)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1895)* status: all files reviewed, 1 unresolved discussion (waiting on @roaminggypsy)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1895#-OAceLXWEfWV-QtDklei:-OAceLXWEfWV-QtDklej:b-bqw4w3) (no related file):*
Can you update the test?

___

**Review by roaminggypsy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1895)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @roaminggypsy, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1895#-OAceLXWEfWV-QtDklei:-OAdYPqf3DPlE606R1lh:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you update the test?
</blockquote></details>

Done.

___

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1895)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
