### PR TITLE
Add getReport.

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1029)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1005** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1005" target="_blank">Graphite</a> 
    * **PR #1007** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1007" target="_blank">Graphite</a> 
    * **PR #1004** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1004" target="_blank">Graphite</a> 
      * **PR #1029** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1029" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1029?utm_source=stack-comment).

**Review by jcorilla — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1029)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1029)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by tristanvuong2021 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1029)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1029)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
