### PR TITLE
Move various symbols related to integration testing to the correct packages.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1175)

**Comment by SanjayVas** [comment]
CC @tristanvuong2021

**Review by YuhongWang-Amazon — COMMENTED** [review]
> Reviewed 40 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1175)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1175#-NcP1lDSCtzYI_wuV_ds:-NcP1lDSCtzYI_wuV_dt:b-fytlxl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9094b4057f0e4e504ac5d3124ef41fe199a86bda/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt#L1)):*
> ```Kotlin
> // Copyright 2020 The Cross-Media Measurement Authors
> ```

Why do we change this from 2021 to 2020?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1175)* status: all files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1175#-NcP1lDSCtzYI_wuV_ds:-NcUPU3K0SOp_YvQp6u1:b-6buc2f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9094b4057f0e4e504ac5d3124ef41fe199a86bda/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDataServicesProviderRule.kt#L1)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

Why do we change this from 2021 to 2020?
</blockquote></details>

GitHub is incorrectly identifying what happened. The real change is that the file at this location was deleted, and then `src/test/kotlin/org/wfanet/measurement/integration/gcloud/KingdomDataServicesProviderRule.kt` was moved here.

Git doesn't track copies/moves/renames, so GitHub/Reviewable has to guess what actually happened. In this case it's incorrectly guessing that `src/test/kotlin/org/wfanet/measurement/integration/gcloud/KingdomDataServicesProviderRule.kt`was deleted and that this file was modified.

**Review by YuhongWang-Amazon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
