### PR TITLE
Add `Principal` for the reporting server

### PR DESCRIPTION
**Pull request by riemanli**
This PR extracts the `Principal` to be a base interface and extends `Principal` to a `ResourcePrincipal` interface. In addition, for each API, a sealed interface of an API-specific principal extended from `ResourcePrincipal` is implemented. `ContextKeys` and `PrincipalServerInterceptor` for each API are modified accordingly.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)

### CODE REVIEW

**Comment by tristanvuong2021** [comment]
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7qLflC-T3oBE40itjU:-N7qLflC-T3oBE40itjV:bf2zusb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/280bcfc2adc6227e8445535b887ecd81e6a76657/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt#L38)):*
> ```Kotlin
>         MeasurementConsumerKey.COLLECTION_NAME ->
>           MeasurementConsumerKey.fromName(name)?.let(::MeasurementConsumer)
>         DuchyKey.COLLECTION_NAME -> DuchyKey.fromName(name)?.let(::Duchy)
> ```

Duchy shouldn't be here.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @SanjayVas)

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7qLflC-T3oBE40itjU:-N7qMA7O8twyCpIhB3vb:b80gbq0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/280bcfc2adc6227e8445535b887ecd81e6a76657/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt#L38)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Duchy shouldn't be here.
</blockquote></details>

Thanks for catching that! Done

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7rVw7X9f6revYeM6T4:-N7rVw7X9f6revYeM6T5:bo709hz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2f8cd41166990c49a53db5a37f5292270eeffd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt#L23)):*
> ```Kotlin
>  * Identifies the sender of an inbound gRPC request.
>  *
>  * TODO: once using Kotlin 1.5, switch to a sealed interface.
> ```

We're already using Kotlin 1.5 as of [common-jvm v0.36.0](https://github.com/world-federation-of-advertisers/common-jvm/releases/tag/v0.36.0).



_Code quote:_
```Kotlin
TODO: once using Kotlin 1.5, switch to a sealed interface.
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7r_9hg091SKmVn-BRu:-N7r_9hg091SKmVn-BRv:b-j3km8i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2f8cd41166990c49a53db5a37f5292270eeffd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt#L25)):*
> ```Kotlin
>  * TODO: once using Kotlin 1.5, switch to a sealed interface.
>  */
> sealed class Principal<T : ResourceKey> {
> ```

I'm thinking an interface hierarchy so we can share across APIs. I think we can also drop the generics due to how Kotlin handles property overrides.

In org.wfanet.measurement.common.api:

```kotlin
interface Principal

interface ResourcePrincipal : Principal {
    val resourceKey: ResourceKey
}
```

In org.wfanet.measurement.reporting.service.api.v1alpha:

```kotlin
sealed interface ReportingPrincipal : ResourcePrincipal {
  companion object {
    fun fromResourceName(name: String): ReportingPrincipal? {
      TODO()
    }
  }
}

data class MeasurementConsumer(override val resourceKey: MeasurementConsumerKey) : ReportingPrincipal
```

In `org.wfanet.measurement.api.v2alpha`:

```kotlin
sealed interface Principal : ResourcePrincipal  // Reusing type name to reduce impact of change
```

See my toy code on Kotlin Playground: https://pl.kotl.in/Wbm4VYsDp
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalConstants.kt` line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7rZ-jL1TANA_hz-Nx5:-N7rZ-jL1TANA_hz-Nx6:b-cd3fvi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2f8cd41166990c49a53db5a37f5292270eeffd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalConstants.kt#L19)):*
> ```Kotlin
> import io.grpc.Context
> 
> object PrincipalConstants {
> ```

You can move this up a package, since it isn't specific to this version.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalConstants.kt` line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7rZHuj73vfJevm6pr2:-N7rZHuj73vfJevm6pr3:b-7queoh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2f8cd41166990c49a53db5a37f5292270eeffd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalConstants.kt#L19)):*
> ```Kotlin
> import io.grpc.Context
> 
> object PrincipalConstants {
> ```

nit: I'd prefer `ContextKeys`. Having `Constants` in a name doesn't really fit with organizing Kotlin files by related things. (I know this is copying an existing pattern).



_Code quote:_
```Kotlin
PrincipalConstants
```

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: 6 of 12 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7rVw7X9f6revYeM6T4:-N7vVEXR3kcjOVixtSNu:b-u0eu59) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2f8cd41166990c49a53db5a37f5292270eeffd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We're already using Kotlin 1.5 as of [common-jvm v0.36.0](https://github.com/world-federation-of-advertisers/common-jvm/releases/tag/v0.36.0).
</blockquote></details>

Removed TODO.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7r_9hg091SKmVn-BRu:-N8-_1R33cAjvosv5tim:bte5brw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2f8cd41166990c49a53db5a37f5292270eeffd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm thinking an interface hierarchy so we can share across APIs. I think we can also drop the generics due to how Kotlin handles property overrides.

In org.wfanet.measurement.common.api:

```kotlin
interface Principal

interface ResourcePrincipal : Principal {
    val resourceKey: ResourceKey
}
```

In org.wfanet.measurement.reporting.service.api.v1alpha:

```kotlin
sealed interface ReportingPrincipal : ResourcePrincipal {
  companion object {
    fun fromResourceName(name: String): ReportingPrincipal? {
      TODO()
    }
  }
}

data class MeasurementConsumer(override val resourceKey: MeasurementConsumerKey) : ReportingPrincipal
```

In `org.wfanet.measurement.api.v2alpha`:

```kotlin
sealed interface Principal : ResourcePrincipal  // Reusing type name to reduce impact of change
```

See my toy code on Kotlin Playground: https://pl.kotl.in/Wbm4VYsDp
</blockquote></details>

In this design, do we have different `contextKey`s and `interceptor`s for the measurement public API and the reporting API? 
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalConstants.kt` line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7rZ-jL1TANA_hz-Nx5:-N7vWi1yE5Lt886QW-1x:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2f8cd41166990c49a53db5a37f5292270eeffd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalConstants.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can move this up a package, since it isn't specific to this version.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalConstants.kt` line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7rZHuj73vfJevm6pr2:-N7v_RIX9Fml2VQw32Pt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2f8cd41166990c49a53db5a37f5292270eeffd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalConstants.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I'd prefer `ContextKeys`. Having `Constants` in a name doesn't really fit with organizing Kotlin files by related things. (I know this is copying an existing pattern).
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7r_9hg091SKmVn-BRu:-N8-l9yTBguF-bevNySb:b3ws05a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2f8cd41166990c49a53db5a37f5292270eeffd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt#L25)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

In this design, do we have different `contextKey`s and `interceptor`s for the measurement public API and the reporting API? 
</blockquote></details>

Yes, but the base Principal/ResourcePrincipal interfaces can be shared to go along with how you put ResourceKey in a shared location in #599.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: 1 of 14 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7r_9hg091SKmVn-BRu:-N80pvkH0x_tB0z51y3e:b-3w5ok) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2f8cd41166990c49a53db5a37f5292270eeffd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, but the base Principal/ResourcePrincipal interfaces can be shared to go along with how you put ResourceKey in a shared location in #599.
</blockquote></details>

Done the refactoring for the reporting server. Please take a look.
Working on the refactoring for the measurement APIs.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: all files reviewed, 5 unresolved discussions (waiting on @chipingyeh, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalServerInterceptor.kt` line 46 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N80vobC6jvjjMinfpOL:-N80vobC6jvjjMinfpOM:b-ppbezn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/84ed0271a7a2b284cd2ae967088f15e2ed323757/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalServerInterceptor.kt#L46)):*
> ```Kotlin
> 
> /**
>  * Executes [block] with [ReportingPrincipal] installed in a new [Context].
> ```

`[principal]` (the param name) in this KDoc rather than the type

I think you might have accidentally applied a case-insensitive find/replace.



_Code quote:_
```Kotlin
[ReportingPrincipal]
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 290 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N811jbYDRUiVfpnnhOe:-N811jbZCauJOZjt-QeL:b6d74nx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/84ed0271a7a2b284cd2ae967088f15e2ed323757/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L290)):*
> ```Kotlin
>         }
>       }
>       else -> {
> ```

The `when` should be exhaustive here, so the `else` case is redundant (the compile should have surfaced this as a warning).
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 390 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N815ljP4cO6t0-Fkdxe:-N815ljQEZyAxVR6rM0J:bate0sz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/84ed0271a7a2b284cd2ae967088f15e2ed323757/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L390)):*
> ```Kotlin
>           )
> 
>         namedSetOperationResults[setOperationId]?.let { setOperationResult ->
> ```

nit: don't use `let` with a named lambda parameter when you aren't using the result, as it doesn't gain you anything over just a plain assignment with a conditional

The following is more readable:

```kotlin
val setOperationResult: SetOperationResult = namedSetOperationResults[setOperationId] ?: continue
// Do something with setOperationResult
```



_Code quote:_
```Kotlin
let
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 391 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N816q9E5MmEW0GENDr8:-N816q9E5MmEW0GENDr9:bgto42j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/84ed0271a7a2b284cd2ae967088f15e2ed323757/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L391)):*
> ```Kotlin
> 
>         namedSetOperationResults[setOperationId]?.let { setOperationResult ->
>           setOperationResult.weightedMeasurementInfoList.map { weightedMeasurementInfo ->
> ```

nit: don't use `map` when you aren't doing anything with the transformation result. A simple for-each loop would work just as well here.



_Code quote:_
```Kotlin
map
```

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: 11 of 39 files reviewed, 3 unresolved discussions (waiting on @chipingyeh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalServerInterceptor.kt` line 46 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N80vobC6jvjjMinfpOL:-N81EtPk6qg_6pJ7NSVG:bd0jggz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/84ed0271a7a2b284cd2ae967088f15e2ed323757/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/PrincipalServerInterceptor.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`[principal]` (the param name) in this KDoc rather than the type

I think you might have accidentally applied a case-insensitive find/replace.
</blockquote></details>

Thanks for catching that. Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 290 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N811jbYDRUiVfpnnhOe:-N81DwFO1bmgnpvIBZmK:bzhk2kk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/84ed0271a7a2b284cd2ae967088f15e2ed323757/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L290)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The `when` should be exhaustive here, so the `else` case is redundant (the compile should have surfaced this as a warning).
</blockquote></details>

Thanks for catching that. I missed that one when rebasing onto the latest main. 

Removed.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 390 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N815ljP4cO6t0-Fkdxe:-N81pnyrAnd738vad4b3:b-nafoa0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/84ed0271a7a2b284cd2ae967088f15e2ed323757/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L390)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: don't use `let` with a named lambda parameter when you aren't using the result, as it doesn't gain you anything over just a plain assignment with a conditional

The following is more readable:

```kotlin
val setOperationResult: SetOperationResult = namedSetOperationResults[setOperationId] ?: continue
// Do something with setOperationResult
```
</blockquote></details>

Thanks for the suggestion! It looks better.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 391 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N816q9E5MmEW0GENDr8:-N81r-0_CRvA02r9aS_E:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/84ed0271a7a2b284cd2ae967088f15e2ed323757/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L391)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: don't use `map` when you aren't doing anything with the transformation result. A simple for-each loop would work just as well here.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: all files reviewed, 5 unresolved discussions (waiting on @chipingyeh, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/PrincipalServerInterceptor.kt` line 49 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N84eb_V953f_Y8H23jg:-N84eb_V953f_Y8H23jh:brshmns) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0eb9ae695692f2fa91735a86fb6cf7caee077e0a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/PrincipalServerInterceptor.kt#L49)):*
> ```Kotlin
>  *
>  * The caller of [withPrincipal] is responsible for guaranteeing that [block] can act as
>  * [MeasurementPrincipal] -- in other words, [principal] is treated as already authenticated.
> ```

nit: `principal`



_Code quote:_
```Kotlin
MeasurementPrincipal
```
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/PrincipalServerInterceptor.kt` line 96 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N84jWeK9oZClnnRaqUk:-N84jWeK9oZClnnRaqUl:bk94qi6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0eb9ae695692f2fa91735a86fb6cf7caee077e0a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/PrincipalServerInterceptor.kt#L96)):*
> ```Kotlin
>  * [ModelProvider], or [Duchy].
>  */
> class PrincipalServerInterceptor(private val principalLookup: PrincipalLookup) : ServerInterceptor {
> ```

nit: leave a TODO here to extract a base class, since there's common code between this and the reporting version.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/Providers.kt` line 46 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N84o1y58eNbd_Z8NSP1:-N84o1y58eNbd_Z8NSP2:bj5ewhu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0eb9ae695692f2fa91735a86fb6cf7caee077e0a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/Providers.kt#L46)):*
> ```Kotlin
> 
> fun getProviderFromContext(): Provider {
>   val principal = requireNotNull(principalFromCurrentContext as? ResourcePrincipal)
> ```

If we don't expect any principals that aren't mapped to resources, we can just have MeasurementPrincipal extend ResourcePrincipal and avoid this cast.



_Code quote:_
```Kotlin
 as? ResourcePrincipal
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/identity/TextprotoFilePrincipalLookup.kt` line 30 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N84mMg56nnnVFGElL2D:-N84mMg56nnnVFGElL2E:b-amd9yh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0eb9ae695692f2fa91735a86fb6cf7caee077e0a/src/main/kotlin/org/wfanet/measurement/common/identity/TextprotoFilePrincipalLookup.kt#L30)):*
> ```Kotlin
>  * @param textprotoFile contains an [AuthorityKeyToPrincipalMap] in textproto format.
>  */
> class TextprotoFilePrincipalLookup(textprotoFile: File) : PrincipalLookup {
> ```

Move to this to `org.wfanet.measurement.api.v2alpha`, since it's specific to a principal type from there.

Better would be to extract a base class that handles this generically for any ResourcePrincipal, but I think that's too much for this PR.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: 32 of 43 files reviewed, 4 unresolved discussions (waiting on @chipingyeh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/PrincipalServerInterceptor.kt` line 49 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N84eb_V953f_Y8H23jg:-N857DKI0io5qsp1sjYp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0eb9ae695692f2fa91735a86fb6cf7caee077e0a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/PrincipalServerInterceptor.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `principal`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/PrincipalServerInterceptor.kt` line 96 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N84jWeK9oZClnnRaqUk:-N8506mTE-jXVJp_Twum:b-6og84e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0eb9ae695692f2fa91735a86fb6cf7caee077e0a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/PrincipalServerInterceptor.kt#L96)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: leave a TODO here to extract a base class, since there's common code between this and the reporting version.
</blockquote></details>

Good idea. Added a TODO.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/Providers.kt` line 46 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N84o1y58eNbd_Z8NSP1:-N858e937ZgJp4_S6K4K:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0eb9ae695692f2fa91735a86fb6cf7caee077e0a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/Providers.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If we don't expect any principals that aren't mapped to resources, we can just have MeasurementPrincipal extend ResourcePrincipal and avoid this cast.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/identity/TextprotoFilePrincipalLookup.kt` line 30 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N84mMg56nnnVFGElL2D:-N85buWUB6-Tqmz8TyL-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0eb9ae695692f2fa91735a86fb6cf7caee077e0a/src/main/kotlin/org/wfanet/measurement/common/identity/TextprotoFilePrincipalLookup.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move to this to `org.wfanet.measurement.api.v2alpha`, since it's specific to a principal type from there.

Better would be to extract a base class that handles this generically for any ResourcePrincipal, but I think that's too much for this PR.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 11 of 11 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @tristanvuong2021)

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639#-N7r_9hg091SKmVn-BRu:-N85dK0n5ae9ZynwcH8i:bu7qmpy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2f8cd41166990c49a53db5a37f5292270eeffd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/Principal.kt#L25)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done the refactoring for the reporting server. Please take a look.
Working on the refactoring for the measurement APIs.
</blockquote></details>

Finished the refactoring.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @tristanvuong2021)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by chipingyeh — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 8 of 13 files at r5, 21 of 28 files at r6, 9 of 11 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Pull request merged**
