### PR TITLE
Implement SpannerExchangeStepAttemptsService

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSIZqE-M2_e4aSurKh:-MgSIZqE-M2_e4aSurKi:b-s3wscp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da9a78198c567d6e0cb2a56f33eac381bac178cb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L54)):*
> ```Kotlin
>       ExchangeStepAttempt.State.FAILED -> temporarilyFail()
>       ExchangeStepAttempt.State.FAILED_STEP -> permanentlyFail()
>       else -> ExchangeStepAttempt.getDefaultInstance()
> ```

Probably just throw an IllegalArgumentException here
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSIea92Y-KV5P6CjNR:-MgSIea92Y-KV5P6CjNS:bfy2psk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da9a78198c567d6e0cb2a56f33eac381bac178cb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L66)):*
> ```Kotlin
>         attemptIndex = reqAttemptIndex,
>       )
>         ?: throw error("Attempt for Step: $reqStepIndex not found.")
> ```

I think this can just be `requireNotNull(findStepAttempt(...)) { "Attempt for Step: ..." }
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 154 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSK4v7A_9-LtypP_I7:-MgSK4v7A_9-LtypP_I8:bf4t7e4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da9a78198c567d6e0cb2a56f33eac381bac178cb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L154)):*
> ```Kotlin
> 
>     if (exchangeFailed) {
>       updateExchangeState(
> ```

I don't think you need to compute `exchangeFailed` -- at this point, you know it will have to become failed
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 199 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSKKlQ4QZfrfAcT-_R:-MgSKKlQ4QZfrfAcT-_S:bl89fdb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da9a78198c567d6e0cb2a56f33eac381bac178cb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L199)):*
> ```Kotlin
>         appendClause("AND ExchangeStepAttempts.Date = @date")
>         appendClause("AND ExchangeStepAttempts.StepIndex = @step_index")
>         appendClause("AND ExchangeStepAttempts.AttemptIndex = @attempt_index")
> ```

For safety reasons, I think we probably want a filter on the external model/data provider id here too. We want to guarantee that the party trying to fail the attempt is the owner of the `ExchangeStep`

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: all files reviewed, 8 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 141 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSnca41DLKUNC3CHX1:-MgSnca41DLKUNC3CHX2:bnc96c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d88d89169a5dedd492b8bd3e0c40586d4869192/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L141)):*
> ```Kotlin
> }
> 
> internal fun SpannerWriter.TransactionScope.updateExchangeStepState(
> ```

If you need other things in this package to reference these can you pull them out to a separate file too?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 168 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSo6JV93909z-XOi-e:-MgSo6JV93909z-XOi-f:b-7lh2zm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d88d89169a5dedd492b8bd3e0c40586d4869192/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L168)):*
> ```Kotlin
>     date: Date
>   ): List<ExchangeWorkflow.Step> {
>     val completedStepIndexes = getCompletedExchangeSteps(recurringExchangeId, date)
> ```

I think this could be problematic because it's reading writes from the same transaction?

In this file it seems like you know that `completedStepIndexes` is an empty set, right? Unless I'm misunderstanding it looks like findReadyExchangeSteps is called right after creating the ExchangeSteps. So you should be able to just pick the ones that have `step.prerequisiteStepIndicesCount == 0`, right?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 176 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSpFtdEPDiDP5LdaDX:-MgSpFtdEPDiDP5LdaDY:b6m2q7q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d88d89169a5dedd492b8bd3e0c40586d4869192/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L176)):*
> ```Kotlin
> }
> 
> internal fun SpannerWriter.TransactionScope.updateExchangeSteps(
> ```

Can you use a more descriptive name like `updateExchangeStepsToReady` or `markExchangeStepsReady`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSmr_R4UqPTAN8nz-B:-MgSmr_R4UqPTAN8nz-C:brrdpes) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d88d89169a5dedd492b8bd3e0c40586d4869192/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt#L49)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> abstract class ExchangeStepAttemptsServiceTest<T : ExchangeStepAttemptsCoroutineImplBase> {
> ```

I'm pretty sure you don't need to template this -- see https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: 2 of 18 files reviewed, 8 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 141 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSnca41DLKUNC3CHX1:-MglM9wR-_KQX4VNipJb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d88d89169a5dedd492b8bd3e0c40586d4869192/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L141)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If you need other things in this package to reference these can you pull them out to a separate file too?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 168 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSo6JV93909z-XOi-e:-MglMAhY4KaPR7CxHs9T:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d88d89169a5dedd492b8bd3e0c40586d4869192/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L168)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think this could be problematic because it's reading writes from the same transaction?

In this file it seems like you know that `completedStepIndexes` is an empty set, right? Unless I'm misunderstanding it looks like findReadyExchangeSteps is called right after creating the ExchangeSteps. So you should be able to just pick the ones that have `step.prerequisiteStepIndicesCount == 0`, right?

</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 176 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSpFtdEPDiDP5LdaDX:-MglMB2Z7eKalWIPsNwP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d88d89169a5dedd492b8bd3e0c40586d4869192/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L176)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you use a more descriptive name like `updateExchangeStepsToReady` or `markExchangeStepsReady`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSIZqE-M2_e4aSurKh:-MglMDa34BYixtxhGKeK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da9a78198c567d6e0cb2a56f33eac381bac178cb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Probably just throw an IllegalArgumentException here
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSIea92Y-KV5P6CjNR:-MglMDuR7pM93hOATHr8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da9a78198c567d6e0cb2a56f33eac381bac178cb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L66)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think this can just be `requireNotNull(findStepAttempt(...)) { "Attempt for Step: ..." }
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 154 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSK4v7A_9-LtypP_I7:-MglMEug3YZ6Q-MFNBFJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da9a78198c567d6e0cb2a56f33eac381bac178cb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L154)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't think you need to compute `exchangeFailed` -- at this point, you know it will have to become failed
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 199 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSKKlQ4QZfrfAcT-_R:-MglMFY1CbB_GsrrlNWF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da9a78198c567d6e0cb2a56f33eac381bac178cb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L199)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For safety reasons, I think we probably want a filter on the external model/data provider id here too. We want to guarantee that the party trying to fail the attempt is the owner of the `ExchangeStep`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSmr_R4UqPTAN8nz-B:-MglMG8h7Qujq0F8y3eL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d88d89169a5dedd492b8bd3e0c40586d4869192/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm pretty sure you don't need to template this -- see https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 13 files at r2, 7 of 16 files at r3, 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: 10 of 18 files reviewed, 10 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, @oliver-amzn, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 199 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSKKlQ4QZfrfAcT-_R:-MglVwZzBF4mxuFyh4an:b6yxptt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da9a78198c567d6e0cb2a56f33eac381bac178cb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L199)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

remind me how we are authenticating their API Key against their model/data provider id?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 86 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MglVba6B5qdxXUbjAph:-MglVba6B5qdxXUbjApi:b-bifld9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/943292583d4c0381d5a14b3ea2e4f45402efefe1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L86)):*
> ```Kotlin
>       ExchangeStepAttempt.State.SUCCEEDED -> succeed(stepResult, stepAttemptResult)
>       ExchangeStepAttempt.State.FAILED -> temporarilyFail(stepResult, stepAttemptResult)
>       ExchangeStepAttempt.State.FAILED_STEP -> permanentlyFail(stepResult, stepAttemptResult)
> ```

do we want to support an `ACTIVE` update --- eg, I'm still working on it and don't auto-fail me after x time
___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto, line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MglWVE13MIGLWYVmTUR:-MglWVE13MIGLWYVmTUS:bupkg2k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/943292583d4c0381d5a14b3ea2e4f45402efefe1/src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto#L93)):*
> ```protobuf
>   // Denormalized party that executes this ExchangeStepAttempt.
>   oneof party {
>     fixed64 external_data_provider_id = 7;
> ```

should these be their own proto to enforce that they are 64 bit everywhere?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 12 of 16 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, @oliver-amzn, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 199 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSKKlQ4QZfrfAcT-_R:-MglduXX1iSQLs4v17PO:b-6ru04y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da9a78198c567d6e0cb2a56f33eac381bac178cb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L199)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

remind me how we are authenticating their API Key against their model/data provider id?
</blockquote></details>

Ask Sanjay
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 203 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-Mgldh8Z0F52z2gE1ONo:-Mgldh8Z0F52z2gE1ONp:b3zjra5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/943292583d4c0381d5a14b3ea2e4f45402efefe1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L203)):*
> ```Kotlin
>         .build()
>     val result = mutableSetOf<Int>()
>     transactionContext.executeQuery(statement).collect { it.getLong("StepIndex").toInt() }
> ```

Did you want to add this into `result`?

**Review by cs-sswaminathan — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 1 of 13 files at r2, 11 of 16 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: all files reviewed, 4 unresolved discussions (waiting on @kgaynor, @oliver-amzn, @stevenwarejones, and @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: 16 of 19 files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 86 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MglVba6B5qdxXUbjAph:-Mgln8QP5jdplloezUA_:b-kv7lyh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/943292583d4c0381d5a14b3ea2e4f45402efefe1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L86)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we want to support an `ACTIVE` update --- eg, I'm still working on it and don't auto-fail me after x time
</blockquote></details>

There is no auto-fail implemented currently? I can also think of something while integration testing after this.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 203 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-Mgldh8Z0F52z2gE1ONo:-Mgln08o4_YOmRmUuljC:bvs55d0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/943292583d4c0381d5a14b3ea2e4f45402efefe1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L203)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Did you want to add this into `result`? 
</blockquote></details>

Thank you
___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto, line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MglWVE13MIGLWYVmTUR:-Mgln2fF6lTVZzML7Y-S:b-yjgzym) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/943292583d4c0381d5a14b3ea2e4f45402efefe1/src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should these be their own proto to enforce that they are 64 bit everywhere?
</blockquote></details>

I believe ExternalId(id: Long) does it already.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 86 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MglVba6B5qdxXUbjAph:-Mglnlh65u1Uw00peuUC:bwinoyb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/943292583d4c0381d5a14b3ea2e4f45402efefe1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L86)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

There is no auto-fail implemented currently? I can also think of something while integration testing after this.
</blockquote></details>

For now let's file a GitHub issue to think about auto-fail and move on.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 86 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MglVba6B5qdxXUbjAph:-MglrpPj74jfdPgD3kN8:bb9j0qr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/943292583d4c0381d5a14b3ea2e4f45402efefe1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L86)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For now let's file a GitHub issue to think about auto-fail and move on.
</blockquote></details>

Done. 
https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/190

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 199 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MgSKKlQ4QZfrfAcT-_R:-MgmB9Yc81xJSe3iMkG-:b-vz8z11) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da9a78198c567d6e0cb2a56f33eac381bac178cb/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L199)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ask Sanjay
</blockquote></details>

okay - following up on slack
___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto, line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MglWVE13MIGLWYVmTUR:-MgmBPyBAkMCiDIIHESz:b-nc6ncu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/943292583d4c0381d5a14b3ea2e4f45402efefe1/src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto#L93)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

I believe ExternalId(id: Long) does it already.
</blockquote></details>

I meant something like this... a message type that could be used across protos.
https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/proto/wfa/panelmatch/client/batchlookup/query_evaluator.proto#L93

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto, line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MglWVE13MIGLWYVmTUR:-MgmDdMT2OLDuNDJU1I9:b-ryw13w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/943292583d4c0381d5a14b3ea2e4f45402efefe1/src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I meant something like this... a message type that could be used across protos.
https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/proto/wfa/panelmatch/client/batchlookup/query_evaluator.proto#L93
</blockquote></details>

This seems like a decent idea, +1

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: 12 of 28 files reviewed, 1 unresolved discussion (waiting on @cs-sswaminathan, @efoxepstein, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto, line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-MglWVE13MIGLWYVmTUR:-MgnPgzZ4yG0graQ_B9k:b-8kq8b4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/943292583d4c0381d5a14b3ea2e4f45402efefe1/src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto#L93)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This seems like a decent idea, +1
</blockquote></details>

Added provider.proto

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 47 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-Mgq-lHSD-5ZsROH5xHT:-Mgq-lHTCKsvCaSv6N5Z:b-ydoyow) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd10a57bb9cbfae63a5d7f39e8fa0b53c4ca4606/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L47)):*
> ```Kotlin
>         .apply {
>           @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA")
>           when (request.partyCase) {
> ```

Push this into the Provider builder:

```
.apply {
  providerBuilder.apply {
    when (request.partyCase) { ... }
  }
}
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, line 78 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183#-Mgq-yGn066X9IOvz0ht:-Mgq-yGn066X9IOvz0hu:b-eer7r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd10a57bb9cbfae63a5d7f39e8fa0b53c4ca4606/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt#L78)):*
> ```Kotlin
>         ClaimReadyExchangeStepRequest.newBuilder()
>           .apply {
>             provider =
> ```

```
.apply {
  providerBuilder.apply { ... }
}
```

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/183)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
