### PR TITLE
Add active time window to Duchy config

### PR DESCRIPTION
**Pull request by Marco-Premier**
Add active time window to duchy config. 
Also changed DuchyIds.setForTest to accept a list of Entry rather than String since now a more complex data struct needs to be consumed.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870)

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt` line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870#-NPM7KSxAHVxcLwMq0DU:-NPM7KSxAHVxcLwMq0DV:b-lwk7va) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50c6141f974c1a562eb4f46a86fe758ba13a1680/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L97)):*
> ```Kotlin
>         Timestamps.fromSeconds(VALID_ACTIVE_TIME_END)
>       )
>     val WORKER3_INVALID_DUCHY =
> ```

It's unused but I added this cause in my next PR I'll need it to test cases where a measurement attempt to use an invalid Duchy



_Code quote:_
```Kotlin
WORKER3_INVALID_DUCHY
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt` line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870#-NPOfKnzCtHDboV35UQD:-NPOfKnzCtHDboV35UQE:bh39c3x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50c6141f974c1a562eb4f46a86fe758ba13a1680/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt#L62)):*
> ```Kotlin
>     val internalDuchyId: Long,
>     val externalDuchyId: String,
>     val activeTimeBegin: Timestamp,
> ```

Use more specific types.

1. `java.time.Instant` instead of `com.google.protobuf.Timestamp` since we're actually going to want evaluate the time range (this is a data class not a protobuf message, so we can eagerly convert to Kotlin types).
2. Use `ClosedRange<Instant>` or `OpenEndTimeRange` depending on whether this is a closed range.



_Code quote:_
```Kotlin
    val activeTimeBegin: Timestamp,
    val activeTimeEnd: Timestamp
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt` line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870#-NPM7KSxAHVxcLwMq0DU:-NPOgQYE4mZ7grWs_uUZ:b6n3v67) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50c6141f974c1a562eb4f46a86fe758ba13a1680/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L97)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

It's unused but I added this cause in my next PR I'll need it to test cases where a measurement attempt to use an invalid Duchy
</blockquote></details>

Since it wouldn't be referenced in DUCHIES, maybe just add it to that test class rather than Population?
___
*[`src/main/proto/wfa/measurement/internal/kingdom/duchy_id_config.proto` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870#-NPOdcX08Y-zN5Rnxy7A:-NPOdcX08Y-zN5Rnxy7B:b-hlwhnw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50c6141f974c1a562eb4f46a86fe758ba13a1680/src/main/proto/wfa/measurement/internal/kingdom/duchy_id_config.proto#L36)):*
> ```protobuf
>     fixed64 internal_duchy_id = 2;
> 
>     // When the duchy becomes active
> ```

Document this as a range, indicating whether its a closed range or one with an open end. The suggestion below assumes a closed range, i.e. `[start, end]`.



_Suggestion:_
```protobuf
    // Start of the Duchy's active time range, inclusive.
    google.protobuf.Timestamp active_start_time = 3;
    // End of the Duchy's active time range, inclusive.
    google.protobuf.Timestamp active_end_time = 4;
```

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870)* status: 17 of 21 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt` line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870#-NPOfKnzCtHDboV35UQD:-NPRdlYl8VJzigGLdt7F:bc1lglz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50c6141f974c1a562eb4f46a86fe758ba13a1680/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use more specific types.

1. `java.time.Instant` instead of `com.google.protobuf.Timestamp` since we're actually going to want evaluate the time range (this is a data class not a protobuf message, so we can eagerly convert to Kotlin types).
2. Use `ClosedRange<Instant>` or `OpenEndTimeRange` depending on whether this is a closed range.
</blockquote></details>

 I wasn't actually sure to what class to use. Thanks for this
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt` line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870#-NPM7KSxAHVxcLwMq0DU:-NPRhzO7-9ukX3JOqIgk:b-38x8v7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50c6141f974c1a562eb4f46a86fe758ba13a1680/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L97)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since it wouldn't be referenced in DUCHIES, maybe just add it to that test class rather than Population?
</blockquote></details>

The idea is to test that a measurement creation fails when it includes a DataProvider having an invalid required duchy. Will remove it now. And add it to the next PR with better context.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/duchy_id_config.proto` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870#-NPOdcX08Y-zN5Rnxy7A:-NPRdkh27MxGNUQ7A-Ar:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50c6141f974c1a562eb4f46a86fe758ba13a1680/src/main/proto/wfa/measurement/internal/kingdom/duchy_id_config.proto#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document this as a range, indicating whether its a closed range or one with an open end. The suggestion below assumes a closed range, i.e. `[start, end]`.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt` line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870#-NPOfKnzCtHDboV35UQD:-NPTQDi_9_N8kTT57eGE:b1day1v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50c6141f974c1a562eb4f46a86fe758ba13a1680/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt#L62)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

 I wasn't actually sure to what class to use. Thanks for this
</blockquote></details>

Np.

Sorry if I wasn't more clear. I had meant to do both (1) and (2), i.e. use a Range type that holds Instants. This way we immediately carry over the information that this is intended to be a closed range.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt` line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870#-NPTQwYc0MGG7uJx8IgH:-NPTQwYc0MGG7uJx8IgI:b-uz0jbb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/557568f3c3e129e5c2ae40cfed523d69b86b1d10/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L72)):*
> ```Kotlin
> class Population(val clock: Clock, val idGenerator: IdGenerator) {
>   companion object {
>     private const val VALID_ACTIVE_START_TIME = 1640991600L // Jan 01 2022 00:00:00 GMT+0000
> ```

nit: rather than using a time format that's not human-readable and using a comment, you can instead use a more human-readable form to construct the range. Since it's just a test, we don't need to worry about the minor inefficiency of doing it this way and can favor readability. e.g.

```kotlin
const val VALID_ACTIVE_START_TIME = Instant.parse("2022-01-01T00:00:00Z")
```

or

```kotlin
const val VALID_ACTIVE_START_TIME = LocalDate.of(2022, 1, 1).atStartOfDay().toInstant(ZoneOffset.UTC)
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt` line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870#-NPTQwYc0MGG7uJx8IgH:-NPTSdVkE2ft8cRq95Fw:b1gy7ij) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/557568f3c3e129e5c2ae40cfed523d69b86b1d10/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: rather than using a time format that's not human-readable and using a comment, you can instead use a more human-readable form to construct the range. Since it's just a test, we don't need to worry about the minor inefficiency of doing it this way and can favor readability. e.g.

```kotlin
const val VALID_ACTIVE_START_TIME = Instant.parse("2022-01-01T00:00:00Z")
```

or

```kotlin
const val VALID_ACTIVE_START_TIME = LocalDate.of(2022, 1, 1).atStartOfDay().toInstant(ZoneOffset.UTC)
```
</blockquote></details>

You can then use the [`rangeTo` operator](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/range-to.html) to construct a `ClosedRange<Instant>`: 

```kotlin
const val ACTIVE_RANGE = VALID_ACTIVE_START_TIME..VALID_ACTIVE_END_TIME
```

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870)* status: 18 of 21 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt` line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870#-NPOfKnzCtHDboV35UQD:-NPWXSof0Ww071Qb5PBc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50c6141f974c1a562eb4f46a86fe758ba13a1680/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Np.

Sorry if I wasn't more clear. I had meant to do both (1) and (2), i.e. use a Range type that holds Instants. This way we immediately carry over the information that this is intended to be a closed range.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 16 of 21 files at r1, 1 of 4 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/870)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
