### PR TITLE
Rollback Transactions when Retrying Reporting Queries instead of Creating new Connections

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/SerializableErrors.kt` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726#-NENP1mu3rZBeNvXu6E5:-NENP1mu3rZBeNvXu6E6:busyxil) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48291d22cd020a68bc1ad013cba6ce3eec8b1e02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/SerializableErrors.kt#L44)):*
> ```Kotlin
>         } catch (e: Exception) {
>           if (e is PostgresqlException) {
>             readContext.rollback()
> ```

Do we need to roll back read transactions like we do write transactions?

Note that I'm not too worried about reusing connections since releasing and getting a connection from a connection pool should be cheap.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/SerializableErrors.kt` line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726#-NENOz-P0-GGwn3U2weq:-NENOz-Q10q_H4jJsqnF:b-y438zb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48291d22cd020a68bc1ad013cba6ce3eec8b1e02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/SerializableErrors.kt#L52)):*
> ```Kotlin
>       try {
>         readContext.close()
>       } catch (_: Exception) {}
> ```

Swallowing the exception seems dangerous.



_Code quote:_
```Kotlin
 } catch (_: Exception) {}
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/SerializableErrors.kt` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726#-NENP1mu3rZBeNvXu6E5:-NEgXXchBxTCG8rrFrN0:b-ql0qhf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48291d22cd020a68bc1ad013cba6ce3eec8b1e02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/SerializableErrors.kt#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we need to roll back read transactions like we do write transactions?

Note that I'm not too worried about reusing connections since releasing and getting a connection from a connection pool should be cheap.
</blockquote></details>

Guess we don't, since it is just reading. I will undo it.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/SerializableErrors.kt` line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726#-NENOz-P0-GGwn3U2weq:-NEgXafK0_xQsQucIAzR:b20jsar) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48291d22cd020a68bc1ad013cba6ce3eec8b1e02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/SerializableErrors.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Swallowing the exception seems dangerous.
</blockquote></details>

https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java has both a close() method and an onComplete that throws an exception whenever it has already been closed. I have seen that error pop up occasionally in tests. Close doesn't do anything else in terms of exceptions. This is also how kotlin use works.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/SerializableErrors.kt` line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726#-NENOz-P0-GGwn3U2weq:-NEkzPxGByL-gHBQ5qV1:btsfvd0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48291d22cd020a68bc1ad013cba6ce3eec8b1e02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/SerializableErrors.kt#L52)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java has both a close() method and an onComplete that throws an exception whenever it has already been closed. I have seen that error pop up occasionally in tests. Close doesn't do anything else in terms of exceptions. This is also how kotlin use works.
</blockquote></details>

Would you mind adding a comment here to that effect? e.g. "Ignore errors from already being closed"

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/SerializableErrors.kt` line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726#-NENOz-P0-GGwn3U2weq:-NEqsrPW4_16mAsfuJDD:b-1gf404) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/48291d22cd020a68bc1ad013cba6ce3eec8b1e02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/SerializableErrors.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Would you mind adding a comment here to that effect? e.g. "Ignore errors from already being closed"
</blockquote></details>

Added comments. Also, the warning is fixed in this PR.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt` line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726#-NFKbwQF9MDppkBz4q-f:-NFKbwQF9MDppkBz4q-g:b-ym8jvy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8733e36b0423d473f1c3479e3a244920b31cdc44/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt#L55)):*
> ```Kotlin
>       return result
>     } catch (e: Exception) {
>       if (e is PostgresqlException) {
> ```

Can just catch `PostgresqlException` to do the same thing



_Suggestion:_
```Kotlin
    } catch (e: PostgresqlException) {
      transactionContext.rollback()
    }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726#-NFKcFjO1GRfoFyB2xEw:-NFKcFjO1GRfoFyB2xEx:b-g59tgt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8733e36b0423d473f1c3479e3a244920b31cdc44/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt#L77)):*
> ```Kotlin
>       return SerializableErrors.retrying { runTransaction(transactionContext, idGenerator) }
>     } finally {
>       // The underlying ReactorNettyClient has both a close and an onComplete method.
> ```

nit: could move this into the implementation of transactionContext.close so we don't have to repeat this everywhere.



_Code quote:_
```Kotlin
      // The underlying ReactorNettyClient has both a close and an onComplete method.
      // Occasionally, the onComplete throws an exception when it has already been closed because
      // of the close method. This discards that.
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt` line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726#-NFKbwQF9MDppkBz4q-f:-NFKj09F1o18FdwoyfEu:b-12hpy1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8733e36b0423d473f1c3479e3a244920b31cdc44/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can just catch `PostgresqlException` to do the same thing
</blockquote></details>

I actually can't. PostgresqlException isn't a Throwable.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt` line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726#-NFKbwQF9MDppkBz4q-f:-NFKlPpw0JpsnfV64qOl:b-fkk5xx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8733e36b0423d473f1c3479e3a244920b31cdc44/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt#L55)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I actually can't. PostgresqlException isn't a Throwable.
</blockquote></details>

Ahh, it's just an interface. Gotcha.

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 1 of 7 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt` line 57 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726#-NJ7SX_d6HXLhcunHnyx:-NJ7SX_d6HXLhcunHnyy:bhyv15h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cd5b1601ee5d8b25976df0c96acae9f018a6b0cf/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt#L57)):*
> ```Kotlin
>     } catch (e: Exception) {
>       if (e is PostgresqlException) {
>         transactionContext.rollback()
> ```

How about this simplification for the same effect?



_Suggestion:_
```Kotlin
    } catch (e: PostgresqlException) {
      transactionContext.rollback()
      throw (e)
    }
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @duliomatos1)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt` line 57 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726#-NJ7SX_d6HXLhcunHnyx:-NJHksXl4TCyQbItgZS4:bkng4b7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/393cc3ba3b191d7c7809819e5bb406775d5ad10a/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt#L57)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

How about this simplification for the same effect?
</blockquote></details>

I added a comment clarifying that PostgresqlException is an interface and not a subclass of Exception.

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/726)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
