### PR TITLE
Don't generate internal protocolConfig for direct reach and frequency measurement

### PR DESCRIPTION
**Pull request by iverson52000**
Don't generate protocolConfig for direct reach and frequency measurement(count of dataProvider is equal to 1) so MPC computation will not be triggered

Add Laplace noise to reach and frequency result in direct measurement in EDP simulator

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)

### CODE REVIEW

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @matthewclegg, @rmirisola, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 247 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6K1-BV70wAkxzcW3JG:-N6K1-BV70wAkxzcW3JH:b-netocn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb7b8505af1f4cd1c7d02624ba0eb069a8ee4548/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L247)):*
> ```Kotlin
>   /** Creates a Measurement on behalf of the [MeasurementConsumer]. */
>   private suspend fun createMeasurement(
>     measurementConsumer: MeasurementConsumer,
> ```

You could modify this to take in the number of data providers then create a separate execute test for direct reach and frequency that creates a measurement with just one data provider.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt` line 256 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6JzNDPAuz6uWrGqVhI:-N6JzNDPAuz6uWrGqVhJ:b1ulcmg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb7b8505af1f4cd1c7d02624ba0eb069a8ee4548/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt#L256)):*
> ```Kotlin
>               clearFailure()
>               if (request.measurement.dataProvidersCount == 1) {
>                 clearProtocolConfig()
> ```

Should make a separate test for this. One with multiple data providers and one with just one.

**Review by matthewclegg — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @jcorilla, @rmirisola, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 435 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6P3ayM6DQpFugr3Wri:-N6P3ayM6DQpFugr3Wrj:br80dma) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb4888a022017f84152094754ad5e30a292667ae/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L435)):*
> ```Kotlin
>     val testValue = apiIdToExternalId(DataProviderKey.fromName(edpData.name)!!.dataProviderId)
>     val requisitionData =
>       MeasurementKt.result {
> ```

Since the EdpSimulator is one of the main references that is available to EDPs when implementing support for Halo, we should illustrate how differentially private noise should be added to the result before returning it.

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @jcorilla, @rmirisola, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt` line 256 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6JzNDPAuz6uWrGqVhI:-N6TjTo22Mc7yyPk-Pkk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb7b8505af1f4cd1c7d02624ba0eb069a8ee4548/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt#L256)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Should make a separate test for this. One with multiple data providers and one with just one.
</blockquote></details>

Done.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @jcorilla, @rmirisola, @SanjayVas, and @stevenwarejones)

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @jcorilla, @matthewclegg, @rmirisola, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 435 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6P3ayM6DQpFugr3Wri:-N6sSfo47TXO8EejaX9G:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb4888a022017f84152094754ad5e30a292667ae/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L435)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Since the EdpSimulator is one of the main references that is available to EDPs when implementing support for Halo, we should illustrate how differentially private noise should be added to the result before returning it.
</blockquote></details>

Done.

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: all files reviewed, 2 unresolved discussions (waiting on @iverson52000, @jcorilla, @matthewclegg, @rmirisola, and @SanjayVas)

___
*[`build/repositories.bzl` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6xay409vuutJT_cCSx:-N6xay409vuutJT_cCSy:br0j040) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8179201c5a9bf3e881044d5add13c90e6838046/build/repositories.bzl#L27)):*
> ```Starlark
>         name = "wfa_common_jvm",
>         repo = "common-jvm",
>         sha256 = None,
> ```

can you add a TODO to version this before merging?

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla, @matthewclegg, @rmirisola, and @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 4 of 5 files at r4, 7 of 13 files at r5, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: 15 of 22 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @jcorilla, @matthewclegg, and @rmirisola)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6yJoq77Op5Qv33PutV:-N6yJoq8EGOmtTJGhs8c:b4ki56g) (no related file):*
@renjiezh Split out a separate PR for updating common-jvm to 0.39.0 and fixing the build.

@iverson52000 Have this PR be based on the PR branch that Renjie creates, but don't merge until this PR's base has been set back to `main` after Renjie's PR has been merged.

___
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 214 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6yIXtJ1GGHKtyHTgdd:-N6yIXtJ1GGHKtyHTgde:b42rzk5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e4e731db92ab6357fbc490e9fc69c444d2623d05/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L214)):*
> ```Kotlin
> 
>       if (
>         requisition.protocolConfig.protocolCase != ProtocolConfig.ProtocolCase.LIQUID_LEGIONS_V2
> ```

Shouldn't we be explicitly checking for whether there's no protocol config or that the protocol isn't specified rather than it not being LLv2? e.g. what if it's a new R/F protocol that this simulator doesn't yet handle?



_Code quote:_
```Kotlin
requisition.protocolConfig.protocolCase != ProtocolConfig.ProtocolCase.LIQUID_LEGIONS_V2
```

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: 15 of 22 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @jcorilla, @matthewclegg, @renjiezh, and @rmirisola)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6yJoq77Op5Qv33PutV:-N6yNKJkCQQutEm0AbZC:b-psq68f) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@renjiezh Split out a separate PR for updating common-jvm to 0.39.0 and fixing the build.

@iverson52000 Have this PR be based on the PR branch that Renjie creates, but don't merge until this PR's base has been set back to `main` after Renjie's PR has been merged.
</blockquote></details>

@sanjayvas OK

___

**Comment by iverson52000** [comment]
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 214 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6yIXtJ1GGHKtyHTgdd:-N6yem4N1zeNp6nu-p33:b-an5lst) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e4e731db92ab6357fbc490e9fc69c444d2623d05/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L214)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't we be explicitly checking for whether there's no protocol config or that the protocol isn't specified rather than it not being LLv2? e.g. what if it's a new R/F protocol that this simulator doesn't yet handle?
</blockquote></details>

Good point. Updated the condition

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 3 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: 18 of 22 files reviewed, 2 unresolved discussions (waiting on @jcorilla, @matthewclegg, @renjiezh, and @rmirisola)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: 18 of 22 files reviewed, 2 unresolved discussions (waiting on @jcorilla, @matthewclegg, @rmirisola, and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6yJoq77Op5Qv33PutV:-N723-D-6q1fS5grmCwn:b-qunmxz) (no related file):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

@sanjayvas OK
</blockquote></details>

FYI, the PR for bumping 0.39.0 has been merged.

___

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: 18 of 22 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @jcorilla, @matthewclegg, @renjiezh, and @rmirisola)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6yJoq77Op5Qv33PutV:-N72Bk67DxEOm_LczfnW:b3oufoh) (no related file):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

FYI, the PR for bumping 0.39.0 has been merged.
</blockquote></details>

Resolve this comment once this PR is up-to-date w.r.t. `main`.

___

**Review by matthewclegg — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r5, 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: all files reviewed, 2 unresolved discussions (waiting on @iverson52000, @jcorilla, @renjiezh, and @rmirisola)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 435 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6P3ayM6DQpFugr3Wri:-N72FqBa2n6b0wU3o3Os:br06oxi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb4888a022017f84152094754ad5e30a292667ae/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L435)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks good, thanks!
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 214 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6yIXtJ1GGHKtyHTgdd:-N726ea_4g0mVQmG-nqU:b-r2haad) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e4e731db92ab6357fbc490e9fc69c444d2623d05/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L214)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Good point. Updated the condition
</blockquote></details>

Actually, I would take Sanjay's point one step further.  Is it always going to be a requirement that all future protocols that involve two or more publishers specify a protocolConfig, while no protocols involving a single publisher will be allowed to have a protocolConfig?  To me, it seems like the safer choice is to have the Kingdom explicitly specify a boolean indicating that this is a single-publisher request.  @sanjayvas What are your thoughts?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: all files reviewed, 2 unresolved discussions (waiting on @iverson52000, @jcorilla, @renjiezh, and @rmirisola)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 214 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6yIXtJ1GGHKtyHTgdd:-N72fKIh8NM5PkqXpMIc:b-7002cc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e4e731db92ab6357fbc490e9fc69c444d2623d05/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L214)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Actually, I would take Sanjay's point one step further.  Is it always going to be a requirement that all future protocols that involve two or more publishers specify a protocolConfig, while no protocols involving a single publisher will be allowed to have a protocolConfig?  To me, it seems like the safer choice is to have the Kingdom explicitly specify a boolean indicating that this is a single-publisher request.  @sanjayvas What are your thoughts?
</blockquote></details>

My main concern is that whatever behavior we're following is documented.

My understanding is that the protocol config is for the MPC protocol, so therefore there would be one specified for anything that uses MPC. Another option would be to explicitly have a protocol type for passing data through the Kingdom to the MC.

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: 8 of 22 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @jcorilla, @matthewclegg, @rmirisola, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-N6yJoq77Op5Qv33PutV:-N7H9axk3-C-VJEfU0wJ:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Resolve this comment once this PR is up-to-date w.r.t. `main`.
</blockquote></details>

Done.

___

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 14 of 14 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @jcorilla, and @rmirisola)

**Review by matthewclegg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619#-:-N7Sdm3X24yhWjNpUDCA:bnfp4nl)* status: 18 of 22 files reviewed, all discussions resolved (waiting on @jcorilla, @rmirisola, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

**Review by matthewclegg — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: 18 of 22 files reviewed, all discussions resolved (waiting on @jcorilla, @rmirisola, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

**Review by matthewclegg — APPROVED** [review]
> Reviewed 1 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: 19 of 22 files reviewed, all discussions resolved (waiting on @jcorilla, @rmirisola, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

**Review by iverson52000 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 5 files at r4, 2 of 14 files at r9, 3 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla and @rmirisola)

**Pull request merged**
