### PR TITLE
Update how measurement calculation time interval is set when cumulative is true

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/796)

### CODE REVIEW

**Review by tristanvuong2021 — COMMENTED** [review]
Since the exact value of the measurement calculation time interval doesn't matter, this is the solution I came up with to fix how cumulative is handled with minimal changes.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/796#-:-NJma5V5AWzY_V866MLI:b-xrx2u9)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @riemanli)

**Review by tristanvuong2021 — COMMENTED** [review]
Ideally, I was considering just changing measurement calculation to not storing time interval at all and just have an Int representing the order.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/796#-:-NJmbaIc6CoctNGbXDOp:b-9mbwyq)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @riemanli)

**Review by riemanli — APPROVED** [review]
Is that because changing measurement calculation will impact some database schema?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/796#-:-NKJq1Z1A5E_z5973yKH:bu1lnxp)* status: 0 of 3 files reviewed, all discussions resolved

**Review by tristanvuong2021 — COMMENTED** [review]
Yes. I suppose I could do a PR that changes the schema and see if people are willing to reset their testing environments.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/796#-:-NKsfCis24OTG-E5DDop:b-q8frco)* status: 0 of 3 files reviewed, all discussions resolved

**Review by duliomatos1 — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/796#-:-NL75ufO8VHEf4Mnl9_O:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by riemanli — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/796)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/796)* status: 1 of 6 files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 3 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/796)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
