### PR TITLE
vid distribution cli

### PR DESCRIPTION
**Pull request by Marco-Premier**
Add CLI tool for:

- ModelLines
- ModelReleases

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1047)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1047)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1047)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1319 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1047#-NXGjUYg5MzjGGrqkI1U:-NXGjUYg5MzjGGrqkI1V:bnx7hnd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee6c9c9f8226afab427d4f63d3b9588b078ce8b7/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1319)):*
> ```Kotlin
>       pageToken = listPageToken
>       if (modelLineTypes != null) {
>         filter = filter { type += modelLineTypes }
> ```

Didn't notice it before, but the field name should be types instead of type since it is repeated.

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1047)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 1319 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1047#-NXGjUYg5MzjGGrqkI1U:-NXHCS1kCw_dPIssd-6R:b-2sskm4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee6c9c9f8226afab427d4f63d3b9588b078ce8b7/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L1319)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Didn't notice it before, but the field name should be types instead of type since it is repeated.
</blockquote></details>

Right, I looked into the code and noticed some inconsistency around naming for repeated fields. Will fix that in a different PR.
Thanks Tristan

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1047)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1047)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
