### PR TITLE
Update PrivacyBudgetManager for ACDP composition

### PR DESCRIPTION
**Pull request by iverson52000**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RibeiroAna and @uakyol)

**Review by uakyol — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157)* status: all files reviewed, 3 unresolved discussions (waiting on @iverson52000 and @RibeiroAna)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157#-NbIk4uVD_LUWk9S9xup:-NbIk4uVD_LUWk9S9xuq:b-q74txj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b776ae78f48688ea7b0392f3198e5a98a5f4d26/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L60)):*
> ```Kotlin
>    */
>   @Deprecated(
>     "Should be removed after completely switching to Gaussian noise and ACDP composition",
> ```

great!
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt` line 128 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157#-NbIkdlv6JbtmsDnr-ku:-NbIkdlv6JbtmsDnr-kv:b-rvm9j6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b776ae78f48688ea7b0392f3198e5a98a5f4d26/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt#L128)):*
> ```Kotlin
>       val backingStore = InMemoryBackingStore()
>       // Set maximumTotalDelta to small value
>       val pbm = PrivacyBudgetManager(privacyBucketFilter, backingStore, 3.0f, 2E-8f)
> ```

why are these params different than the equivalent DpCharge test case?
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt` line 142 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157#-NbIklvvCcPJ71_cWWIP:-NbIklvvCcPJ71_cWWIQ:byc071p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b776ae78f48688ea7b0392f3198e5a98a5f4d26/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt#L142)):*
> ```Kotlin
>     runBlocking {
>       val backingStore = InMemoryBackingStore()
>       val pbm = PrivacyBudgetManager(privacyBucketFilter, backingStore, 3.0f, 2E-4f)
> ```

ditto and below

**Review by RibeiroAna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157)* status: all files reviewed, 4 unresolved discussions (waiting on @iverson52000)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157#-NbKMPcQ6IcRAjKaxwhW:-NbKMPcR66my24YwDMyN:b-cb7qcu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b776ae78f48688ea7b0392f3198e5a98a5f4d26/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L38)):*
> ```Kotlin
>   private val backingStore: PrivacyBudgetLedgerBackingStore,
>   private val maximumPrivacyBudget: Float = MAXIMUM_PRIVACY_USAGE_PER_BUCKET,
>   private val maximumTotalDelta: Float = MAXIMUM_DELTA_PER_BUCKET,
> ```

Question: Should it be MaximumTotalDelta even for acdp? Asking because in one doc I saw the new parameter for ACDP would be a theta. If it is a Delta anyways, where the translation between Delta and Teta are being done? Maybe it is related on the @uakyol question on why the params are different?

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @RibeiroAna, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157#-NbKMPcQ6IcRAjKaxwhW:-NbL6rXREvBKE9QnvC2V:btpuwxh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b776ae78f48688ea7b0392f3198e5a98a5f4d26/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L38)):*
<details><summary><i>Previously, RibeiroAna (Ana Ribeiro) wrote…</i></summary><blockquote>

Question: Should it be MaximumTotalDelta even for acdp? Asking because in one doc I saw the new parameter for ACDP would be a theta. If it is a Delta anyways, where the translation between Delta and Teta are being done? Maybe it is related on the @uakyol question on why the params are different? 
</blockquote></details>

Good question. So externally, we are still using (epsilon, delta) params, which is letting MC set (epsilon, delta) in their measurement query and we set max total (epsilon, delta) budget for each privacy bucket in PBM. The ACDP params (rho, theta) are only used internally in PBM for accounting purpose.

The per-query (epsilon, delta) => (rho, theta) conversion will happen in PrivacyQueryMapper.kt using the AcdpParamsConverter library which will be implemented in the next PR. The total query+balance (rho, theta) => (epsilon, delta) conversion is handled in Composition.totalPrivacyBudgetUsageUnderAcdpComposition(acdpCharges, targetEpsilon)
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt#L134

Note that totalPrivacyBudgetUsageUnderAcdpComposition will take max total epsilon as an parameter and calculate the total delta being used so far and compare against max total delta to see if privacy budget is exceeded.

The logics are documented in Total budget parameters conversion and Per-query parameters conversion sections in the doc:
https://docs.google.com/document/d/1JrOtQgI8wqMAfE6RJdwR0f-YFP1HmfLksQ6LLXUwBVU/edit?pli=1&resourcekey=0-pTCp0oJiIjlAZYrYELSq1g#heading=h.5jmq43rahpaj
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt` line 128 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157#-NbIkdlv6JbtmsDnr-ku:-NbL6id_C75YIZz2pMYj:b-4yeuv0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b776ae78f48688ea7b0392f3198e5a98a5f4d26/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt#L128)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

why are these params different than the equivalent DpCharge test case?
</blockquote></details>

Because these max total (epsilon, delta) params are designed for ACDP params. For the ACDP unit tests, we are using AcdpCharge(rho = 0.04, theta = 5.0E-6). The converted total delta for this charge (with total epsilon = 3) is 1.0542768461593835E-4.

Added another unit test in CompositionTest.kt to document the calculation.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt` line 142 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157#-NbIklvvCcPJ71_cWWIP:-NbL6pPw5SGUrujo0Wek:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b776ae78f48688ea7b0392f3198e5a98a5f4d26/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt#L142)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

ditto and below
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157)* status: all files reviewed, 4 unresolved discussions (waiting on @uakyol)

**Review by uakyol — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157)* status: all files reviewed, 3 unresolved discussions (waiting on @iverson52000)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt` line 128 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157#-NbIkdlv6JbtmsDnr-ku:-NbNJ_qaCygUu5Y6AcZK:b-dqcwi5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b776ae78f48688ea7b0392f3198e5a98a5f4d26/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerTest.kt#L128)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Because these max total (epsilon, delta) params are designed for ACDP params. For the ACDP unit tests, we are using AcdpCharge(rho = 0.04, theta = 5.0E-6). The converted total delta for this charge (with total epsilon = 3) is 1.0542768461593835E-4.

Added another unit test in CompositionTest.kt to document the calculation.
</blockquote></details>

Sounds great Albert, thank you.

**Review by iverson52000 — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
> Dismissed @uakyol from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @uakyol)

**Review by iverson52000 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Pull request merged**
