### PR TITLE
updating WORKSPACE for demo UI

### PR DESCRIPTION
**Pull request by bdomen-ggl**
This is just adding the necessary dependencies in bazel to get the Demo UI code working. This includes some kotlin tooling, grpc gateway dependencies, and React dependencies. The code will be added in follow up PRs.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960)

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl)

___
*[`WORKSPACE` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTZUsHi3pr204Tw00dw:-NTZUsHi3pr204Tw00dx:b-zcf2l9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f27e5720c33592995354dfb21f39c3acc98a0d/WORKSPACE#L15)):*
> ```Starlark
> common_jvm_repositories()
> 
> ####### Demo UI Dependencies #######
> ```

s/Demo/Reporting
___
*[`WORKSPACE` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTZUl9p8vNz9MbK9Q3y:-NTZUl9p8vNz9MbK9Q3z:b-bt5fx2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f27e5720c33592995354dfb21f39c3acc98a0d/WORKSPACE#L20)):*
> ```Starlark
> 
> load("//build:reporting_ui/reporting_ui_deps.bzl", "load_demo_ui_deps")
> load_demo_ui_deps()
> ```

Can this be renamed to "load_reporting_ui_deps()"?

**Comment by bdomen-ggl** [comment]
@kungfucraig @SanjayVas OK, got through my bazel build and linting issues and it looks good now. Ran into what I thought was an issue with the build taking a long time (~1.5 hrs), but that's because I changed a fundamental part of the WORKSPACE and GHA builds the cache basically from scratch. I'll keep an eye on this to make sure it's not an issue in the future.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @bdomen-ggl and @kungfucraig)

___
*[`WORKSPACE` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTZUl9p8vNz9MbK9Q3y:-NTyuSgI7Yqr_fWFNXpN:bwi44qe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f27e5720c33592995354dfb21f39c3acc98a0d/WORKSPACE#L20)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Sure, was trying to make it generic in case we add more UIs later, but can make it specific to reporting for now. In that regard, I forgot to rename the folder and file so I can rename the method instead.
</blockquote></details>

Name it `reporting_ui_repositories()`.
___
*[`WORKSPACE` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTyvtLJBOqh3B4Jito6:-NTyvtLJBOqh3B4Jito7:b-2099l9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6895350d1b1367abe7c1202c0a92ec6c3b3eb413/WORKSPACE#L15)):*
> ```Starlark
> common_jvm_repositories()
> 
> ####### Reporting UI Dependencies #######
> ```

Don't group these by what they're for. I know it's counter-intuitive, but you really want these organized by load order. Anything that's a direct repo dep (e.g. `http_archive` targets) go first. Something like:

* common_jvm_repositories()
* reporting_ui_repositories()
* Things which `load` from the above repos
* Things which `load` from the previous item
* etc
___
*[`WORKSPACE` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTyvOxK0eWpViPn_9HF:-NTyvOxK0eWpViPn_9HG:b-xa1wke) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6895350d1b1367abe7c1202c0a92ec6c3b3eb413/WORKSPACE#L29)):*
> ```Starlark
> 
> # =============== GRPC  GATEWAY =============== #
> ```

Pretty certain these already get loaded from common-jvm.



_Code quote:_
```Starlark
load("@io_bazel_rules_kotlin//kotlin:repositories.bzl", "kotlin_repositories")
kotlin_repositories() # if you want the default. Otherwise see custom kotlinc distribution below

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")
kt_register_toolchains() # to use the default toolchain, otherwise see toolchains below

# =============== GRPC  GATEWAY =============== #

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()
```
___
*[`WORKSPACE` line 116 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTyv5MlBe5Da4zR-rfQ:-NTyv5MlBe5Da4zR-rfR:bz627m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6895350d1b1367abe7c1202c0a92ec6c3b3eb413/WORKSPACE#L116)):*
> ```Starlark
> }.items())
> 
> GATEWAY_ARTIFACTS = [
> ```

Don't check in commented-out code.
___
*[`build/reporting_ui/reporting_ui_deps.bzl` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTytx7i8ZTrG1CeXHX9:-NTytx7i8ZTrG1CeXHXA:bi4btgu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6895350d1b1367abe7c1202c0a92ec6c3b3eb413/build/reporting_ui/reporting_ui_deps.bzl#L23)):*
> ```Starlark
> def load_reporting_ui_deps():
>     """Imports all direct dependencies for Reporting UI."""
>     rules_kotlin_version = "1.7.1"
> ```

Don't define anything here that's already coming from somewhere else.

If you need to override the version of something that's included by e.g. common-jvm, do the version overriding there so we have consistent versions across all of our repos.

**Comment by bdomen-ggl** [comment]
*[`WORKSPACE` line 116 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTyv5MlBe5Da4zR-rfQ:-NTzKNGIDmI5GO5Pn9_2:bij21tf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6895350d1b1367abe7c1202c0a92ec6c3b3eb413/WORKSPACE#L116)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't check in commented-out code.
</blockquote></details>

Ah yeah, thanks. I was experimenting with removing some stuff and missed deleting this block.

**Comment by bdomen-ggl** [comment]
*[`WORKSPACE` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTyvtLJBOqh3B4Jito6:-NTzKqBwCxlErSarJItr:b-v111r9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6895350d1b1367abe7c1202c0a92ec6c3b3eb413/WORKSPACE#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't group these by what they're for. I know it's counter-intuitive, but you really want these organized by load order. Anything that's a direct repo dep (e.g. `http_archive` targets) go first. Something like:

* common_jvm_repositories()
* reporting_ui_repositories()
* Things which `load` from the above repos
* Things which `load` from the previous item
* etc
</blockquote></details>

I think I have that though, no?
Load the http_archive targets, then call `load ` and the methods based on dependency order. Or are you just suggesting I remove the comment blocks? I had those in case someone wanted to reorder the deps for some reason, but that could break the loading order.

**Comment by bdomen-ggl** [comment]
*[`WORKSPACE` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTZUl9p8vNz9MbK9Q3y:-NTzLQs717KekbBtJA7s:b-9yzw86) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46f27e5720c33592995354dfb21f39c3acc98a0d/WORKSPACE#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Name it `reporting_ui_repositories()`.
</blockquote></details>

ok will do

**Comment by bdomen-ggl** [comment]
*[`build/reporting_ui/reporting_ui_deps.bzl` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTytx7i8ZTrG1CeXHX9:-NTzOT2SAjOuLZ-RjHWU:btnasj5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6895350d1b1367abe7c1202c0a92ec6c3b3eb413/build/reporting_ui/reporting_ui_deps.bzl#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't define anything here that's already coming from somewhere else.

If you need to override the version of something that's included by e.g. common-jvm, do the version overriding there so we have consistent versions across all of our repos.
</blockquote></details>

Ah OK. I'll double check all these.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @bdomen-ggl and @kungfucraig)

___
*[`WORKSPACE` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTyvtLJBOqh3B4Jito6:-NU2V-Gl-4qlAP3TLV-j:btr4b1k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6895350d1b1367abe7c1202c0a92ec6c3b3eb413/WORKSPACE#L15)):*
> Or are you just suggesting I remove the comment blocks? I had those in case someone wanted to reorder the deps for some reason, but that could break the loading order.

This. The comment blocks also imply that nothing unrelated should be added between the given lines, but they may need to be.

**Review by bdomen-ggl — COMMENTED** [review]
@SanjayVas Ready for an updated review

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-:-NUNRYTP-w79EaZCO7Rr:bh0m3yf)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

**Comment by bdomen-ggl** [comment]
*[`build/reporting_ui/reporting_ui_deps.bzl` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTytx7i8ZTrG1CeXHX9:-NUNRmWH7zsY8-nuQbXi:b-a5l6eo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6895350d1b1367abe7c1202c0a92ec6c3b3eb413/build/reporting_ui/reporting_ui_deps.bzl#L23)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Ah OK. I'll double check all these.
</blockquote></details>

OK I missed deleting these as well apparently

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl and @kungfucraig)

___
*[`build/reporting_ui/go_repositories.bzl` line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTywsfeA12GgILiyyFU:-NUTVaQ46N7dxm4AhS0g:b-21vfu0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6895350d1b1367abe7c1202c0a92ec6c3b3eb413/build/reporting_ui/go_repositories.bzl#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I have grpc-gateway pulled as a binary from reporting ui deps (which makes the http_archive calls).

What I see is an http_archive of the grpc-gateway source code (e.g. https://github.com/grpc-ecosystem/grpc-gateway/archive/refs/tags/v2.15.0.tar.gz), rather than an http_file that just grabs a pre-compiled binary (e.g. https://github.com/grpc-ecosystem/grpc-gateway/releases/download/v2.15.2/protoc-gen-grpc-gateway-v2.15.2-linux-x86_64).

If you're just grabbing the binary and writing your own rule that calls `protoc` with that plugin binary then I don't think you need any of the Go dependencies for grpc-gateway.
</blockquote></details>

Oh my, I've now realized that grpc-gateway does not at all work the way I thought it does. It looks like this generates Go stubs that you then need to hook into your server. I thought that the gateway came with a standalone HTTP server binary that uses the output of the protoc plugin. It appears that is not the case, and this instead generates Go code. I believe that this means we need to write an entry point in Go that starts an HTTP server.

I think I'd prefer to see separate PRs for:
1. Adding Bazel rules for generating the gateway handler.
2. Adding a server which uses the generated gateway handler.

Where each of these would add whichever deps are necessary. It's difficult to evaluate which deps are needed where otherwise.

**Comment by bdomen-ggl** [comment]
*[`build/reporting_ui/go_repositories.bzl` line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/960#-NTywsfeA12GgILiyyFU:-NUTVOMb4nA1L6OQsMXR:bz533t0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6895350d1b1367abe7c1202c0a92ec6c3b3eb413/build/reporting_ui/go_repositories.bzl#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I have grpc-gateway pulled as a binary from reporting ui deps (which makes the http_archive calls).

What I see is an http_archive of the grpc-gateway source code (e.g. https://github.com/grpc-ecosystem/grpc-gateway/archive/refs/tags/v2.15.0.tar.gz), rather than an http_file that just grabs a pre-compiled binary (e.g. https://github.com/grpc-ecosystem/grpc-gateway/releases/download/v2.15.2/protoc-gen-grpc-gateway-v2.15.2-linux-x86_64).

If you're just grabbing the binary and writing your own rule that calls `protoc` with that plugin binary then I don't think you need any of the Go dependencies for grpc-gateway.
</blockquote></details>

Oh gotcha. I'll try to switch it out.

Unless I'm completely off base with my Bazel understanding and the people I talked to, grpc-gateway is basically just a protoc plugin as far as I can tell. Except it is only written for supporting Go backends. That's what the Go libraries are for. This was the only other example I could find with grpc-gateway + kotlin and the guy still made a gateway in Go. https://github.com/adetalhouet/flux

Example gateway: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/examples/internal/gateway/gateway.go
Example pb dependency: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/examples/internal/proto/oneofenum/BUILD.bazel#L12
Go api v2 BUILD definition: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/BUILD.bazel#L33

If you don't want Go at all, I can scrap the grpc-gateway approach and write our own protoc call to build everything in Kotlin. That will take me quite a bit longer I think.

**Pull request closed without merging**
