### PR TITLE
Add function to convert Report result from internal to external

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by riemanli — COMMENTED** [review]
Hey Renjie, thanks for working on this PR. To make sure that `report.proto` follows AIP rules, could you use `api-linter` on it? For example, run the command at the directory `src/main/proto`:

```
api-linter --config api-linter.yaml  --proto-path cross-media-measurement/bazel-cross-media-measurement/external/com_google_googleapis/ wfa/measurement/reporting/v1alpha/report.proto
```

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635#-:-N7Rn78k9iRhZil09kmi:b-yvawcz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/report.proto` line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635#-N7RoYwh8M5O9hYgftrC:-N7RoYwh8M5O9hYgftrD:bdembn1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46407bc9632c75cba0c7426a520bc288308fa5f5/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto#L103)):*
> ```protobuf
>   State state = 8 [(google.api.field_behavior) = OUTPUT_ONLY];
> 
>   // Results in CSV format. Each result can be seen as one table.
> ```

Use `api-linter` to make sure the proto follows AIP rules.

**Review by riemanli — COMMENTED** [review]
For more info, please see https://linter.aip.dev/.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635#-:-N7Rp6ov01QnvuxYFJ6A:b5jfhkh)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

**Review by riemanli — COMMENTED** [review]
I think they both work. 

Based on https://linter.aip.dev/#usage, `--proto-path src/main/proto` is not necessary as the current working directory is always used. In addition, using `--proto-path cross-media-measurement/bazel-cross-media-measurement/external/com_google_googleapis/` will search all protos under `com_google_googleapis`, so we don't have to specify every FileDescriptorSet.

I think I missed importing descriptor proto based on your command.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635#-:-N7Rs2vf0ANB3zqI2nWB:b-st0tl8)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

**Review by SanjayVas — APPROVED** [review]
> --proto-path src/main/proto is not necessary as the current working directory is always used.

This accounts for the fact that we strip "src/main/proto" from our proto import path. We should be running all commands at workspace root. 

>  using --proto-path cross-media-measurement/bazel-cross-media-measurement/external/com_google_googleapis/ 

This isn't portable, as it assumes your workspace directory is named `cross-media-measurement`.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635#-:-N7SBQ3B9zDzjUt1wQAp:b-pz9lsa)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kungfucraig, and @renjiezh)

**Review by riemanli — COMMENTED** [review]
> We should be running all commands at workspace root.

If that's the case, then we do need `--proto-path src/main/proto`.

> This isn't portable, as it assumes your workspace directory is named cross-media-measurement.

Yeah that's true. Given the fact that we should run all commands at the root folder, the full command is

```
api-linter --proto-path src/main/proto \
--proto-path bazel-${PWD##*/}/external/com_google_googleapis \
--proto-path bazel-${PWD##*/}/external/com_github_protocolbuffers_protobuf \
--config src/main/proto/api-linter.yaml \
wfa/measurement/reporting/v1alpha/report.proto
```

Btw, we should document the usage somewhere for future reference :)

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635#-:-N7SF5dD0YtFX60nK8mA:b-iq2qvy)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kungfucraig, and @renjiezh)

**Review by renjiezh — COMMENTED** [review]
Added comments. 
The api-linter also suggest to add annotation of `output-only`. For example, `string name = 1 [(google.api.field_behavior) = REQUIRED];`. But I haven't seen any of our protos using it. So I didn't apply that suggestion.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635#-:-N7SZ-JR0TQwIwDbj88y:b-iq1uga)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kungfucraig, and @renjiezh)

**Review by riemanli — COMMENTED** [review]
You should add it. All protos in `src/main/proto/wfa/measurement/reporting/v1alpha` follow the AIP rules. If it's a required field, then add `(google.api.field_behavior) = REQUIRED`. Ex: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto#L40

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635#-:-N7SybWg9qwZJCo9fSgd:b-4mex7o)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kungfucraig, @renjiezh, and @SanjayVas)

**Review by renjiezh — COMMENTED** [review]
Thanks for the suggestion. Just added the annotation.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635#-:-N7TB015C9ARgMkxsvKD:bvdtm2)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kungfucraig, @renjiezh, and @SanjayVas)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/report.proto` line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635#-N7RoYwh8M5O9hYgftrC:-N7TB5C5CmwGZPqFCbMU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/46407bc9632c75cba0c7426a520bc288308fa5f5/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto#L103)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Use `api-linter` to make sure the proto follows AIP rules.
</blockquote></details>

Done.

**Review by riemanli — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/635)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
