### PR TITLE
Replace one insert call per row with one insert call for multiple rows

### PR DESCRIPTION
**Pull request by tristanvuong2021**
The addBinding method executes one insert per row. When the number of rows is large, the performance suffers. For 800 metrics with one measurement each and the same reporting set for each metric, insertion takes 4.2 seconds locally. With the change in this PR, insertion takes 1.4 seconds.

The refactoring is done this way because R2DBC doesn't automically transform the inserts into a single batch insert. See [https://github.com/pgjdbc/r2dbc-postgresql/issues/527](https://github.com/pgjdbc/r2dbc-postgresql/issues/527).

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 216 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502#-Nrfmdj287Zm6wcWuJ0L:-Nrfmdj391tn_f2SUPk7:b-db21er) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b92892b1f8490a39c00a22ef79410484f6ea807/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L216)):*
> ```Kotlin
>         )
> 
>         val tempMetricsCurIndex = metricsCurIndex
> ```

I'm not a fan of this approach. There should be a better way to handle this. I know that the JDBC driver has a `reWriteBatchedInserts` option that basically does this for you, but I'm not sure if this applies for R2DBC. You could give that a shot.

If we really need to handle it ourselves, we should do the rewriting in the common-jvm statement builder (basically changing how `add` works).

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 216 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502#-Nrfmdj287Zm6wcWuJ0L:-Nrg0AjL-S7wXQh6-ohE:b1dt0ci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b92892b1f8490a39c00a22ef79410484f6ea807/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L216)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not a fan of this approach. There should be a better way to handle this. I know that the JDBC driver has a `reWriteBatchedInserts` option that basically does this for you, but I'm not sure if this applies for R2DBC. You could give that a shot.

If we really need to handle it ourselves, we should do the rewriting in the common-jvm statement builder (basically changing how `add` works).
</blockquote></details>

For parameterized statements, this is the only method. For statements that aren't parameterized, there is a batch connection.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 216 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502#-Nrfmdj287Zm6wcWuJ0L:-Nrg6nit0nSIwXhcAFwT:bs14nlm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b92892b1f8490a39c00a22ef79410484f6ea807/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L216)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

For parameterized statements, this is the only method. For statements that aren't parameterized, there is a batch connection.
</blockquote></details>

Did you try setting `reWriteBatchedInserts` in the connection options? For the underlying JDBC driver, that option is intended to basically automatically rewrite the multiple insert statements into a single one.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 216 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502#-Nrfmdj287Zm6wcWuJ0L:-Nrg0xdU55JQB2LELk7I:bqv4332) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b92892b1f8490a39c00a22ef79410484f6ea807/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L216)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Did you try setting `reWriteBatchedInserts` in the connection options? For the underlying JDBC driver, that option is intended to basically automatically rewrite the multiple insert statements into a single one.
</blockquote></details>

That isn't one of the connection options for postgres r2dbc

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 216 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502#-Nrfmdj287Zm6wcWuJ0L:-NrgJ4CBBjI9sH1em90A:b-zcdd3c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b92892b1f8490a39c00a22ef79410484f6ea807/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L216)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

That isn't one of the connection options for postgres r2dbc
</blockquote></details>

It's not one of the Option constants, but the options are just strings. The question is whether anything actually reads that option in the R2DBC implementation (e.g. does it end up calling some code from the JDBC impl)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 216 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502#-Nrfmdj287Zm6wcWuJ0L:-NrgMZrmEoefJDmB0GiH:b-gr40uo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b92892b1f8490a39c00a22ef79410484f6ea807/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L216)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's not one of the Option constants, but the options are just strings. The question is whether anything actually reads that option in the R2DBC implementation (e.g. does it end up calling some code from the JDBC impl)
</blockquote></details>

Ah, perhaps this does indeed not do anything for the R2DBC version. Please reference https://github.com/pgjdbc/r2dbc-postgresql/issues/527 in a comment indicating that we need to do this because R2DBC does not support rewriting batched inserts.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 216 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502#-Nrfmdj287Zm6wcWuJ0L:-Nrgg8JFBgh64tc_gmcg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b92892b1f8490a39c00a22ef79410484f6ea807/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L216)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, perhaps this does indeed not do anything for the R2DBC version. Please reference https://github.com/pgjdbc/r2dbc-postgresql/issues/527 in a comment indicating that we need to do this because R2DBC does not support rewriting batched inserts.
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502#-NrgiUiz5kCErW9j56Qa:-NrgiUiz5kCErW9j56Qb:b-6r5ps0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1b92892b1f8490a39c00a22ef79410484f6ea807/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L59)):*
> ```Kotlin
> class CreateMetrics(private val requests: List<CreateMetricRequest>) :
>   PostgresWriter<List<Metric>>() {
>   private data class WeightedMeasurementsAndStatementComponents(
> ```

This is still pretty hard to read. Is there any way to factor things out to make this more readable? I'm thinking something like creating a Postgres-specific builder for multi-valued bound statements. Usage example:

```kotlin
multiValueBoundStatement(paramCount = 3, 
  """
  INSERT INTO Metrics (Foo, Bar, Baz) VALUES (${MultiValueBoundStatement.PARAM_LIST_PLACEHOLDER})
  """
) {
  for (item in items) {
    addBinding {
      bind(paramIndex = 0, item.foo)
      bind(paramIndex = 1, item.bar)
      bind(paramIndex = 2, item.baz)
    }
  }
}
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502#-NrgiUiz5kCErW9j56Qa:-NsFOgtI6KDeEb3wlwIC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/986ead69bacb9f7ac12c4ffa028798b863c58b59/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is still pretty hard to read. Is there any way to factor things out to make this more readable? I'm thinking something like creating a Postgres-specific builder for multi-valued bound statements. Usage example:

```kotlin
multiValueBoundStatement(paramCount = 3, 
  """
  INSERT INTO Metrics (Foo, Bar, Baz) VALUES (${MultiValueBoundStatement.PARAM_LIST_PLACEHOLDER})
  """
) {
  for (item in items) {
    addBinding {
      bind(paramIndex = 0, item.foo)
      bind(paramIndex = 1, item.bar)
      bind(paramIndex = 2, item.baz)
    }
  }
}
```
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`MODULE.bazel` line 132 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502#-NsUMiTe2BgRCgtG3hQB:-NsUMiTe2BgRCgtG3hQC:b-w2uahb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c7a414cc3d97cb170378ac7e6003dfc4fcbf1f6/MODULE.bazel#L132)):*
> ```Starlark
>     repo_name = "wfa_common_jvm",
> )
> archive_override(
> ```

Until you have a version, add a DO_NOT_SUBMIT referencing the source PR.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`MODULE.bazel` line 132 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502#-NsUMiTe2BgRCgtG3hQB:-NsidPBb9DVjgHVlqvfD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd7fe769565c36d0e706e950be4af5c9305dfc75/MODULE.bazel#L132)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Until you have a version, add a DO_NOT_SUBMIT referencing the source PR.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1502)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
