### PR TITLE
Create protobuf message and service for model shards

### PR DESCRIPTION
**Pull request by jojijac0b**
Create ModelShard protobuf message.

Create ModelShards service to create, stream, and delete model shards.

Update BUILD and all_protos files to include new ModelShards service.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980)

**Review by Marco-Premier — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980)* status: all files reviewed, 5 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_shard.proto` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980#-NUukEsk35nbNDTlcOJi:-NUukEsk35nbNDTlcOJj:b-8an3x0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2884cbb4d31b0d73128ea91b75c15e0aa55be650/src/main/proto/wfa/measurement/internal/kingdom/model_shard.proto#L1)):*
> ```protobuf
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

this is the year the file was copyrighted. I.e. ```2023```



_Code quote:_
```protobuf
2021
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_shard.proto` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980#-NUujo2C1PAS18ixDlCK:-NUujo2C1PAS18ixDlCL:bambf79) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2884cbb4d31b0d73128ea91b75c15e0aa55be650/src/main/proto/wfa/measurement/internal/kingdom/model_shard.proto#L25)):*
> ```protobuf
> 
> // Represents a model shard entity.
> message ModelShard {
> ```

Also ```fixed external_data_provider_id = 1;``` key is needed since ModelShard are unique only within their parent DataProvider.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980#-NUukZj07lWAsh8Jew0X:-NUukZj07lWAsh8Jew0Y:bnj7hl0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2884cbb4d31b0d73128ea91b75c15e0aa55be650/src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto#L1)):*
> ```protobuf
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

same as above



_Code quote:_
```protobuf
2021
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980#-NUul0p49o4EHaef6F24:-NUul0p49o4EHaef6F25:b-7b789o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2884cbb4d31b0d73128ea91b75c15e0aa55be650/src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto#L26)):*
> ```protobuf
> option java_multiple_files = true;
> 
> // Internal service for persistence of ModelProvider entities.
> ```

This is ```ModelShard```



_Code quote:_
```protobuf
ModelProvider
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto` line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980#-NUulgvb0YwCenxMrehn:-NUulgvc9lq5_a7v2RAI:b-rtmhgx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2884cbb4d31b0d73128ea91b75c15e0aa55be650/src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto#L41)):*
> ```protobuf
>   // Filter criteria as a conjunction of specified fields.
>   message Filter {
>     int64 external_model_shard_id = 1;
> ```

this is the parent resource from which you want to stream the ModelShards for: ```external_data_provider_id```



_Code quote:_
```protobuf
external_model_shard_id
```

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_shard.proto` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980#-NUukEsk35nbNDTlcOJi:-NUwtYmo31VHa0pg-vbh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2884cbb4d31b0d73128ea91b75c15e0aa55be650/src/main/proto/wfa/measurement/internal/kingdom/model_shard.proto#L1)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

this is the year the file was copyrighted. I.e. ```2023```
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980#-NUukZj07lWAsh8Jew0X:-NUwtaCeEuKebEx0mOhj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2884cbb4d31b0d73128ea91b75c15e0aa55be650/src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto#L1)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto` line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980#-NUulgvb0YwCenxMrehn:-NUwtbU7A425IPEOMGB5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2884cbb4d31b0d73128ea91b75c15e0aa55be650/src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto#L41)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

this is the parent resource from which you want to stream the ModelShards for: ```external_data_provider_id```
</blockquote></details>

Done.

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980#-NUul0p49o4EHaef6F24:-NV-l3fr1qGhFr9GRwiw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2884cbb4d31b0d73128ea91b75c15e0aa55be650/src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto#L26)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

This is ```ModelShard```
</blockquote></details>

Done.

**Review by Marco-Premier — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_shard.proto` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980#-NV04h1R3lLPbjyYSEkq:-NV04h1R3lLPbjyYSEkr:b-yaijnk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f740c2ab5004230905ab9ecdfe8a0edac485d940/src/main/proto/wfa/measurement/internal/kingdom/model_shard.proto#L30)):*
> ```protobuf
>   fixed64 external_model_shard_id = 2;
> 
>   string model_release = 3;
> ```

this is going to be ```external_model_release_id```. Internal value (model_release) are not visible from the outside world :)
Then while creating a new ModelShard you will retrieve the linked ModelRelease by running a query that returns a ModelRelease read by external_model_release_id



_Code quote:_
```protobuf
model_release = 3;
```

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_shard.proto` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980#-NV04h1R3lLPbjyYSEkq:-NV1OrdiCFq90nyhtwXl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f740c2ab5004230905ab9ecdfe8a0edac485d940/src/main/proto/wfa/measurement/internal/kingdom/model_shard.proto#L30)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

this is going to be ```external_model_release_id```. Internal value (model_release) are not visible from the outside world :)
Then while creating a new ModelShard you will retrieve the linked ModelRelease by running a query that returns a ModelRelease read by external_model_release_id
</blockquote></details>

Done.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by jojijac0b — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980#-:-NVG2YEj-t1PJYgUgzDY:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

**Review by Marco-Premier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by jojijac0b — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/980)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Pull request merged**
