### PR TITLE
cherry pick beam main shaded jar

### PR DESCRIPTION
**Pull request by stevenwarejones**
Cherry picks the following
93af154e04a55e389053634ff82b3856dd20571f
49b7059680c2a6503d2f9ba2fd77b555680df9a5
EMR Screenshot
image

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1490)

**Review by jonmolle — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1490#-:-Nqnr5xt7Uo30mPS3vgL:bb6ywmx)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1490)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/storage/aws/s3/S3StorageFactory.kt` line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1490#-NqoIjQH1OWg0ZebB1mM:-NqoIjQIBahYpJPQNbWL:bxtdplv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b332c9f0d3cd39ce717307e89f8bfefc8415557/src/main/kotlin/org/wfanet/panelmatch/client/storage/aws/s3/S3StorageFactory.kt#L45)):*
> ```Kotlin
>     val beamOptions = options.`as`(BeamOptions::class.java)
>     @Suppress("USELESS_ELVIS") // Beam returns String?
>     val accessKey = beamOptions.awsAccessKey ?: ""
> ```

nit: does .orEmpty() not work here?



_Suggestion:_
```Kotlin
 .orEmpty()
```

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1490)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Comment by SanjayVas** [comment]
This was merged bypassing checks. It looks like it broke Spanner integration. I can reproduce the same test failure locally.

From SpannerWriterTest:

```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/google/spanner/v1/TransactionOptions$ReadOnly$Builder.mergeMaxStaleness(Lcom/google/protobuf/Duration;)Lcom/google/spanner/v1/TransactionOptions$ReadOnly$Builder; @74: invokevirtual
  Reason:
    Type 'com/google/protobuf/Duration' (current frame, stack[1]) is not assignable to 'com/google/protobuf/AbstractMessage'
  Current Frame:
    bci: @74
    flags: { }
    locals: { 'com/google/spanner/v1/TransactionOptions$ReadOnly$Builder', 'com/google/protobuf/Duration' }
    stack: { 'com/google/protobuf/SingleFieldBuilderV3', 'com/google/protobuf/Duration' }
  Bytecode:
    0000000: 2ab4 000f c700 392a b400 0906 a000 252a
    0000010: b400 13b8 005c a500 1b2a 2ab4 0013 c000
    0000020: 5bb8 005e 2bb6 005f b600 60b5 0013 a700
    0000030: 082a 2bb5 0013 2ab6 0039 a700 202a b400
    0000040: 0906 a000 0f2a b400 0f2b b600 5357 a700
    0000050: 0c2a b400 0f2b b600 4e57 2a06 b500 092a
    0000060: b0                                     
  Stackmap Table:
    same_frame(@49)
    same_frame(@54)
    same_frame(@61)
    same_frame(@81)
    same_frame(@90)

	at com.google.spanner.v1.TransactionOptions$ReadOnly.toBuilder(TransactionOptions.java:2538)
	at com.google.spanner.v1.TransactionOptions$ReadOnly.newBuilder(TransactionOptions.java:2529)
	at com.google.cloud.spanner.TimestampBound.<clinit>(TimestampBound.java:122)
	at com.google.cloud.spanner.connection.ConnectionImpl.<init>(ConnectionImpl.java:213)
	at com.google.cloud.spanner.connection.ConnectionOptions.getConnection(ConnectionOptions.java:903)
	at com.google.cloud.spanner.jdbc.AbstractJdbcConnection.<init>(AbstractJdbcConnection.java:65)
	at com.google.cloud.spanner.jdbc.JdbcConnection.<init>(JdbcConnection.java:56)
	at com.google.cloud.spanner.jdbc.JdbcDriver.connect(JdbcDriver.java:196)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.wfanet.measurement.gcloud.spanner.testing.SpannerEmulatorDatabaseRule.createDatabase(SpannerEmulatorDatabaseRule.kt:73)
	at org.wfanet.measurement.gcloud.spanner.testing.SpannerEmulatorDatabaseRule.access$createDatabase(SpannerEmulatorDatabaseRule.kt:40)
	at org.wfanet.measurement.gcloud.spanner.testing.SpannerEmulatorDatabaseRule$apply$1.evaluate(SpannerEmulatorDatabaseRule.kt:55)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:108)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:116)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:148)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:75)
```

**Pull request merged**
