### PR TITLE
Replace Data Availability Interval on EDP Simulator Startup

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This covers a wide range of time, which easily allows for Report creation under Report Schedules.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 267 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430#-NoSZhGME7qr7jghl1ck:-NoSZhGME7qr7jghl1cl:bkwzmqk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/961d7e2bece23139a30ae3a80dc3855d6358633d/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L267)):*
> ```Kotlin
>               publicKeySignature = signedPublicKey.signature
>               publicKeySignatureAlgorithmOid = signedPublicKey.signatureAlgorithmOid
>               dataAvailabilityInterval = interval {
> ```

1. This isn't actually doing what the PR description says. What it's really doing is setting the data availability interval to cover at least the *default* range of simulator data, assuming the simulator in question is using one of our *currently* checked-in specs.
2. This only affects environments where ResourceSetup has not yet been run (e.g. empty cluster tests).

Depending on what the use case is, you likely want to do this elsewhere. For example, having the EDP simulator update its data availability on startup.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 267 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430#-NoSZhGME7qr7jghl1ck:-NoTp7qi7tCOY7b0doiR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/961d7e2bece23139a30ae3a80dc3855d6358633d/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L267)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. This isn't actually doing what the PR description says. What it's really doing is setting the data availability interval to cover at least the *default* range of simulator data, assuming the simulator in question is using one of our *currently* checked-in specs.
2. This only affects environments where ResourceSetup has not yet been run (e.g. empty cluster tests).

Depending on what the use case is, you likely want to do this elsewhere. For example, having the EDP simulator update its data availability on startup.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 192 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430#-NoY9hk28Zp9iwv9fkVw:-NoY9hk28Zp9iwv9fkVx:b-u9pgll) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49bf548d3f17f852c37db448b5fe7edc74e7ad89/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L192)):*
> ```Kotlin
>           }
>           endTime = timestamp {
>             seconds = 2209017600 // January 1, 2040 12:00:00 AM, America/Los_Angeles
> ```

Make this relative to current time so that it's evergreen.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 192 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430#-NoY9hk28Zp9iwv9fkVw:-NoYWqm14abXM9J4PScG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49bf548d3f17f852c37db448b5fe7edc74e7ad89/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L192)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Make this relative to current time so that it's evergreen.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 195 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430#-NoYq_8a4GQOFBVKQMiG:-NoYq_8a4GQOFBVKQMiH:bcqtx5o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/baf79469c81a6f3ffe4eb0ee1a4387e614aa94cf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L195)):*
> ```Kotlin
>           endTime =
>             Instant.now()
>               .plusSeconds(60 * 60 * 24 * 5)
> ```

nit: technically just now should be fine. The simulator probably shouldn't be claiming it can guarantee data from the future...

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 6 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1430)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
