### PR TITLE
Push panel exchange container images as part of GitHub workflow.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1079)

**Comment by SanjayVas** [comment]
I did a test run of the workflow, which produced the following images:

* `ghcr.io/world-federation-of-advertisers/panel-exchange/gcloud-example-daemon:110cb2e2a626a732a6bacae80c61aeb3be190aee`
* `ghcr.io/world-federation-of-advertisers/panel-exchange/aws-example-daemon:110cb2e2a626a732a6bacae80c61aeb3be190aee`

Note that the K8s and Terraform changes have not been tested.

**Review by jonmolle — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1079)* status: 0 of 11 files reviewed, all discussions resolved

___
*[`src/main/docker/panel_exchange_client/images.bzl` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1079#-NYsEXLl0s0rg_LhK_kV:-NYsEXLm1_5rFKyMQNB3:bxbkmlk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/90bf9e41d07747691b89865f9c5a13ccefcf082b/src/main/docker/panel_exchange_client/images.bzl#L32)):*
> ```Starlark
> ]
> 
> AWS_IMAGES = [
> ```

Thanks for fixing this

**Review by Marco-Premier — APPROVED** [review]
Nice, thanks for this PR!

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1079#-:-NYwLWTfEeWMw_6GAY4i:b-zk0ob)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1079)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
