### PR TITLE
Create proto conversions for reporting v2alpha

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943#-NSrHWWR-PeU6JrDBcrA:-NSrHWWR-PeU6JrDBcrB:bypppj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ddc6a20cb5a35c06d9f6719bd0a3716a04e102b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L93)):*
> ```Kotlin
> fun MetricSpec.VidSamplingInterval.toInternal(): InternalMetricSpec.VidSamplingInterval {
>   val source = this
>   grpcRequire(source.start >= 0) { "vidSamplingInterval.start cannot be negative." }
> ```

The grpcRequire should be done in MetricsService. The validation can still be done here, but throw an IllegalArgumentException, which is caught by MetricsService and that throws the correct grpc error.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943#-NSrHWWR-PeU6JrDBcrA:-NSrKsGXEbmxcJuK6KQd:boirn3r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ddc6a20cb5a35c06d9f6719bd0a3716a04e102b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L93)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The grpcRequire should be done in MetricsService. The validation can still be done here, but throw an IllegalArgumentException, which is caught by MetricsService and that throws the correct grpc error.
</blockquote></details>

Would it be better to move the checks outside to let the caller handle it?

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943#-NSrHWWR-PeU6JrDBcrA:-NSrMhxn5XDfknftMzEV:b-ua79ru) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ddc6a20cb5a35c06d9f6719bd0a3716a04e102b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L93)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Would it be better to move the checks outside to let the caller handle it?
</blockquote></details>

It will be easier to move these checks to the caller and do them before the conversion since you are already doing a bunch of validation there and you want specific error messages.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943#-NSrHWWR-PeU6JrDBcrA:-NSrU02ME6JjO9dIvbQi:b-g8yzaf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ddc6a20cb5a35c06d9f6719bd0a3716a04e102b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L93)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It will be easier to move these checks to the caller and do them before the conversion since you are already doing a bunch of validation there and you want specific error messages.
</blockquote></details>

Cool. I will remove the checks here and add them to MetricsService. Thanks for pointing this out!

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943#-NSrHWWR-PeU6JrDBcrA:-NSvIAbjAQlUqxUX2OM4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ddc6a20cb5a35c06d9f6719bd0a3716a04e102b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L93)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Cool. I will remove the checks here and add them to MetricsService. Thanks for pointing this out!
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943#-NSw3PZDAWiYmvZWqhFM:-NSw3PZDAWiYmvZWqhFN:bgfoplr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da5915cb4f85f21093397792600315881fd6f9d9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L152)):*
> ```Kotlin
>       }
>       InternalMetricResult.ResultCase
>         .RESULT_NOT_SET, -> {} // No action if the result hasn't been set yet.
> ```

Is there supposed to be a comma here?



_Code quote:_
```Kotlin
,
```

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943#-NSw3PZDAWiYmvZWqhFM:-NSw_mrC8_YcmE46gDLp:b5blu0c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da5915cb4f85f21093397792600315881fd6f9d9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L152)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is there supposed to be a comma here?
</blockquote></details>

No. Thanks for catching it. Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/943)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
