### PR TITLE
Clean up Exchange internal APIs

### PR DESCRIPTION
**Pull request by efoxepstein**
https://rally1.rallydev.com/#/?detail=/defect/609066028953&fdp=true

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @SanjayVas and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310#-Mky4r9nA9nfpTNnecSC:-Mky4r9oCOB4yKphLVYn:b-mvnbfp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/eedb8438c03ae155b4e55fd5c6248edb44eec39b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt#L60)):*
> ```Kotlin
>               appendClause(
>                 """
>                 |  AND ExchangeSteps.DataProviderId = (
> ```

(This is to ensure that the "D" in "AND" lines up with the last "E" in "WHERE")

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @SanjayVas, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 95 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310#-MlAKmC7B9Q8qD07YG3I:-MlAKmC7B9Q8qD07YG3J:b-6pq9z9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2d2ade359db749ba35d0c9a8854716547e95a09/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L95)):*
> ```Kotlin
>     val externalDataProviderId = request.provider.externalDataProviderId
> 
>     CreateExchangesAndSteps(
> ```

Isn't it cleaner to check for one of the parties being populated before this executes, not after?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 95 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310#-MlAKmC7B9Q8qD07YG3I:-MlAYL4B-d2jjsNLiigp:bxn6d61) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2d2ade359db749ba35d0c9a8854716547e95a09/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L95)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Isn't it cleaner to check for one of the parties being populated before this executes, not after?
</blockquote></details>

Sorry, I don't quite follow. Can you elaborate?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @SanjayVas, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 95 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310#-MlAKmC7B9Q8qD07YG3I:-MlB3gUS3ni-Ww82QTIE:bcrse6r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2d2ade359db749ba35d0c9a8854716547e95a09/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L95)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Sorry, I don't quite follow. Can you elaborate?
</blockquote></details>

so, you are removing the code snippet before `CreateExchangesAndStep` that validates that one of the parties is populated. Instead, that validation is now done after this step inside of `ExchangeStepAttemptReader.forExpiredAttempts`

**Review by SanjayVas — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt, line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310#-MlB4FIRCx94dru4h8Kg:-MlB4FIRCx94dru4h8Kh:bfvsoj3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2d2ade359db749ba35d0c9a8854716547e95a09/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt#L82)):*
> ```
>  grpcRequire
> ```
Add a TODO to stop using gRPC exceptions here.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)* status: 12 of 16 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 95 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310#-MlAKmC7B9Q8qD07YG3I:-MlB6i3NDJFA2FKfzBpt:bc36yzw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2d2ade359db749ba35d0c9a8854716547e95a09/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L95)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

so, you are removing the code snippet before `CreateExchangesAndStep` that validates that one of the parties is populated. Instead, that validation is now done after this step inside of `ExchangeStepAttemptReader.forExpiredAttempts`
</blockquote></details>

Ah got it, good catch, done!
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt, line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310#-MlB4FIRCx94dru4h8Kg:-MlB7O0eAUqc8Gx8MUX9:bvzq147) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2d2ade359db749ba35d0c9a8854716547e95a09/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt#L82)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>  grpcRequire
> ```
Add a TODO to stop using gRPC exceptions here.
</blockquote></details>

Changed to `require`

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)* status: 13 of 16 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/Providers.kt, line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310#-MlB95L08jarQ6HTWblF:-MlB95L08jarQ6HTWblG:ba58t6u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e2c38ae5320ad519fcf594cdd9d6d0a8f021284/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/Providers.kt#L33)):*
> ```Kotlin
>     Provider.Type.MODEL_PROVIDER, Provider.Type.DATA_PROVIDER -> null
>     Provider.Type.UNRECOGNIZED, Provider.Type.TYPE_UNSPECIFIED ->
>       failGrpc { "Invalid Provider: $this" }
> ```

Which RPC status needs to be raised is dependent on the method being called. This is making an assumption that the Provider.Type is derived from a gRPC request where the type is required.

At the very least, this should be explicitly specified in the public function KDoc. This also means that this should only be called from the service layer (as opposed to e.g. from Spanner reader/writer layer) where the calling code knows the context of the gRPC method being called.

It would likely be more clear to assume that this is checked up-front in service layer request validation, such that this would be a programming error and results in an IllegalArgumentException.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)* status: 9 of 18 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/Providers.kt, line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310#-MlB95L08jarQ6HTWblF:-MlBEJw4AiigHk9K3Z3s:b-6rqt1w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e2c38ae5320ad519fcf594cdd9d6d0a8f021284/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/Providers.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Which RPC status needs to be raised is dependent on the method being called. This is making an assumption that the Provider.Type is derived from a gRPC request where the type is required.

At the very least, this should be explicitly specified in the public function KDoc. This also means that this should only be called from the service layer (as opposed to e.g. from Spanner reader/writer layer) where the calling code knows the context of the gRPC method being called.

It would likely be more clear to assume that this is checked up-front in service layer request validation, such that this would be a programming error and results in an IllegalArgumentException.
</blockquote></details>

`Provider` is an internal API proto so I think it's a pretty safe assumption that it's coming from a gRPC request. I'll document and restrict visibility to the service layer.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)* status: 9 of 18 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @yunyeng)

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)* status: 9 of 18 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, line 89 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310#-MlGi_Q67bhuDccSJIGm:-MlGi_Q7-SkAs0H-uMh1:b-4uvw24) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0dc22cfd2ececd426dc3813c05c822ec05f9320e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt#L89)):*
> ```Kotlin
>         .singleOrNull()
>         ?: failGrpc(Status.NOT_FOUND) { "ExchangeStepAttempt not found" }
>     // TODO: use a KingdomInternalException above
> ```

Just making a note here to make sure this TODO doesn't hang around too long.

**Pull request merged**
