### PR TITLE
Implement system ComputationLogEntriesService.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/132)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/132)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entry.proto, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/132#-MdPLoGIBvduY_c9IifS:-MdPLoGIBvduY_c9IifT:bklmdfm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7a1a5b4c52f53c912ea3121c321589ef95ad9bf0/src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entry.proto#L62)):*
> ```
>   fixed64 external_computation_id = 3;
> ```
I don't think we need this field. We should already know it from the create request message.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/132)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entry.proto, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/132#-MdPLoGIBvduY_c9IifS:-MdSrJR0DpbS55Tpp5sj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7a1a5b4c52f53c912ea3121c321589ef95ad9bf0/src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entry.proto#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>   fixed64 external_computation_id = 3;
> ```
I don't think we need this field. We should already know it from the create request message.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
