### PR TITLE
Implement v2alpha public API DataProviders service.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/151)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/151)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/151#-MelN48q05j8c6y7AvwZ:-MelN48r5PD9CSBIqwQd:b-476mf9) (no related file):*
We will want a nearly identical service for registering ModelProviders too. Are there parts that we could pull out into helper libraries?

---

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/151)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/151#-MelN48q05j8c6y7AvwZ:-MelbToo4oOxdMAAsb-H:bex2l1y) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We will want a nearly identical service for registering ModelProviders too. Are there parts that we could pull out into helper libraries?
</blockquote></details>

My plan was to identify these as I add MeasurementConsumers. Likely the certificate parts.

---

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/151)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/151)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/151#-MeziRcBEmITj4R-djAb:-MeziRcBEmITj4R-djAc:b-l61p2y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12182379e5cfe599218f73250d50101430325e16/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L45)):*
> ```Kotlin
> class DataProvidersService(private val internalClient: DataProvidersCoroutineStub) :
>   DataProvidersCoroutineService() {
>   override suspend fun createDataProvider(request: CreateDataProviderRequest): DataProvider {
> ```

is the plan to implement the create method and hide it from the public?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/151)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/151#-MeziRcBEmITj4R-djAb:-Mf-17QzECrHKpVHnTod:b-8v3yvn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12182379e5cfe599218f73250d50101430325e16/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt#L45)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

is the plan to implement the create method and hide it from the public?
</blockquote></details>

AFAIK methods can't be hidden, only entire services can.

If we choose to not allow self-service registration, we have a few options. For example:
* For alpha, the current thinking is to lock down the entire Accounts service so that only those with direct access to the cluster can create Accounts and therefore DataProvider/MeasurementConsumer resources. The EDP or MC user would then just be given an API key.
* If this is a requirement for a public deployment, we can restrict access to this method to a configured set of client TLS certificates.

**Review by zachcwc — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/151)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @stevenwarejones, and @wangyaopw)

**Pull request merged**
