### PR TITLE
Migrate build and imports to common-jvm repository import 

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/135)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 143 of 143 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/135)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @oliver-amzn, @tristanvuong2021, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/135#-MdUFZ189opkL_Y357uX:-MdUFZ189opkL_Y357uY:b-vd6eqs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0dfb0d61bd2aeaf118187cede6ac013241dd9620/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/BUILD.bazel#L4)):*
> ```
> load("@wfa_common_jvm//build/platforms:constraints.bzl", "DISTROLESS_JAVA")
> ```
I think this one should stay here and be dropped from wfa_common_jvm. The `platforms` Bazel package has some dependencies on the RBE configs, which aren't part of common-jvm.
___
*[src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/135#-MdUGoA80r8_FmkQymJ2:-MdUGoA80r8_FmkQymJ3:b8ixs4s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0dfb0d61bd2aeaf118187cede6ac013241dd9620/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/BUILD.bazel#L1)):*
> ```Starlark
> load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")
> ```

This whole file should be gone from this repo, as it exists in common-jvm now.

Are you planning on doing all the replacing of targets under `/src/main/kotlin` in a separate PR? If so, make it clear in this PR description that this is just handling `/build` and `/imports`.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/135#-MdUFZ189opkL_Y357uX:-MdY3VNz3PrBdmk-WVN-:b435755) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0dfb0d61bd2aeaf118187cede6ac013241dd9620/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> load("@wfa_common_jvm//build/platforms:constraints.bzl", "DISTROLESS_JAVA")
> ```
I think this one should stay here and be dropped from wfa_common_jvm. The `platforms` Bazel package has some dependencies on the RBE configs, which aren't part of common-jvm.
</blockquote></details>

Made the change.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/135#-MdUGoA80r8_FmkQymJ2:-MdY3dEE3Fp7mEhEp0n0:bf8u45o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0dfb0d61bd2aeaf118187cede6ac013241dd9620/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/BUILD.bazel#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This whole file should be gone from this repo, as it exists in common-jvm now.

Are you planning on doing all the replacing of targets under `/src/main/kotlin` in a separate PR? If so, make it clear in this PR description that this is just handling `/build` and `/imports`.
</blockquote></details>

I will handle /src/main/kotlin in a separate PR.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @zachcwc)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 140 of 143 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)

**Review by zachcwc — APPROVED** [review]

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 134 of 143 files at r1, 2 of 3 files at r2, 1 of 5 files at r5, 3 of 3 files at r6, 1 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 5 files at r5, 3 of 3 files at r6, 1 of 1 files at r8, 4 of 4 files at r9, 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek)

**Pull request merged**
