### PR TITLE
test: Add report creation to correctness test

### PR DESCRIPTION
**Pull request by tristanvuong2021**
test: Add report creation to correctness test

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845)* status: all files reviewed, 6 unresolved discussions (waiting on @tristanvuong2021)

___
*[`.github/workflows/run-k8s-tests.yml` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OBCDqdZDuEdNNcYm5CB:-OBCDqd_-3O2OTjSr-Uy:b-ccy7pc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4b9986eb3a482a16c3c3857bbaaeba384d93140/.github/workflows/run-k8s-tests.yml#L55)):*
> ```YAML
>         MC_API_KEY: ${{ secrets.MC_API_KEY }}
>         GCLOUD_PROJECT: ${{ vars.GCLOUD_PROJECT }}
>         REPORTING_PUBLIC_API_TARGET: v2alpha.reporting.dev.halo-cmm.org:8443
> ```

I went ahead and added the variable for all 3 environments



_Suggestion:_
```YAML
${{ vars.REPORTING_PUBLIC_API_TARGET }}
```
___
*[`src/test/kotlin/org/wfanet/measurement/integration/k8s/SyntheticGeneratorCorrectnessTest.kt` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OBCFjMi6NV_H4DkgGnm:-OBCFjMi6NV_H4DkgGnn:b-cx4819) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4b9986eb3a482a16c3c3857bbaaeba384d93140/src/test/kotlin/org/wfanet/measurement/integration/k8s/SyntheticGeneratorCorrectnessTest.kt#L51)):*
> ```Kotlin
>  * Test for correctness of an existing CMMS on Kubernetes where the EDP simulators use
>  * [SyntheticGeneratorEventQuery] with [SyntheticGenerationSpecs.SYNTHETIC_POPULATION_SPEC_LARGE].
>  * The computation composition is using ACDP by assumption.
> ```

nit: document that this assuming that there's a Reporting system connected to the CMMS
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt` line 134 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OBCEEbi7nZBgfOvWzLP:-OBCEEbi7nZBgfOvWzLQ:b1w3dts) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4b9986eb3a482a16c3c3857bbaaeba384d93140/src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt#L134)):*
> ```Kotlin
>           listEventGroupsRequest {
>             parent = measurementConsumerName
>             pageSize = 1000
> ```

nit: technically you still should be looping through to exhaust all pages regardless of what page size you set rather than relying on the fact that our current impl will give you the results
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt` line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OBCEVtsCBJJsDy_Oxc8:-OBCEVtt-ufZU_l_vz27:b-ae9421) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4b9986eb3a482a16c3c3857bbaaeba384d93140/src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt#L160)):*
> ```Kotlin
>     try {
>       return reportingSetsClient
>         .withAuthenticationKey(apiAuthenticationKey)
> ```

The API key is only for the Kingdom public API.



_Code quote:_
```Kotlin
.withAuthenticationKey(apiAuthenticationKey)
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt` line 234 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OBCEkNf44HcLpszpZe9:-OBCEkNg3b6rNmvlpZDK:b-zgv538) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4b9986eb3a482a16c3c3857bbaaeba384d93140/src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt#L234)):*
> ```Kotlin
>         Report.State.UNRECOGNIZED,
>         Report.State.STATE_UNSPECIFIED -> delay(5000)
>       }
> ```

Add some delay here so we're not polling as fast as possible.
___
*[`src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt` line 179 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OBCFA_fDcPOsfqdAe5T:-OBCFA_fDcPOsfqdAe5U:b-rqrplr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4b9986eb3a482a16c3c3857bbaaeba384d93140/src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt#L179)):*
> ```Kotlin
> 
>     override val reportingTestHarness: ReportingUserSimulator?
>       get() = null
> ```

So this will only work when run on cloud? I assume we're hitting some GHA limit if we try to do this in a local cluster?



_Code quote:_
```Kotlin
null
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845)* status: 6 of 19 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`.github/workflows/run-k8s-tests.yml` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OBCDqdZDuEdNNcYm5CB:-OBRN5-D1ZeqRbP04Rjw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4b9986eb3a482a16c3c3857bbaaeba384d93140/.github/workflows/run-k8s-tests.yml#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I went ahead and added the variable for all 3 environments
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt` line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OBCEVtsCBJJsDy_Oxc8:-OBRPt0QB3aJ5dZ97UTM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4b9986eb3a482a16c3c3857bbaaeba384d93140/src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt#L160)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The API key is only for the Kingdom public API.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt` line 234 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OBCEkNf44HcLpszpZe9:-OBRQF6k0LMejd1FGTWL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4b9986eb3a482a16c3c3857bbaaeba384d93140/src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt#L234)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add some delay here so we're not polling as fast as possible.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt` line 179 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OBCFA_fDcPOsfqdAe5T:-OBklrf10MJghM2ZXNwB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4b9986eb3a482a16c3c3857bbaaeba384d93140/src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt#L179)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

So this will only work when run on cloud? I assume we're hitting some GHA limit if we try to do this in a local cluster?
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845)* status: all files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/k8s/local/testing/empty_encryption_key_pair_config.textproto` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OC-iKtc791H3NsuvjWw:-OC-iKtc791H3NsuvjWx:b-2x48y3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cd9c7c38b1ce3a6bd6bb15530361222542950922/src/main/k8s/local/testing/empty_encryption_key_pair_config.textproto#L1)):*
> ```
> # proto-file: wfa/measurement/config/reporting/encryption_key_pair_config.proto
> ```

This file already exists in the parent directory. If you need it from here, you can just add it to an `exports_files` declaration.
___
*[`src/main/k8s/local/testing/mc_config_kustomization.yaml` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OC-iYB8256MktXRs-6N:-OC-iYB8256MktXRs-6O:bmd94vp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cd9c7c38b1ce3a6bd6bb15530361222542950922/src/main/k8s/local/testing/mc_config_kustomization.yaml#L1)):*
> ```YAML
> # Copyright 2024 The Cross-Media Measurement Authors
> ```

Same here re: existing in the parent package.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt` line 133 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OC-j5WgCYoVhSm21Xp6:-OC-j5WgCYoVhSm21Xp7:bml2i5t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cd9c7c38b1ce3a6bd6bb15530361222542950922/src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt#L133)):*
> ```Kotlin
>               listEventGroupsRequest {
>                 parent = measurementConsumerName
>                 pageSize = 1000
> ```

nit: just use the default page size
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt` line 227 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OC-jLbO03AZoHdJdCBQ:-OC-jLbO03AZoHdJdCBR:b-iackz6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cd9c7c38b1ce3a6bd6bb15530361222542950922/src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt#L227)):*
> ```Kotlin
>         Report.State.RUNNING,
>         Report.State.UNRECOGNIZED,
>         Report.State.STATE_UNSPECIFIED -> delay(5000)
> ```

nit: log that we're checking again in 5s like we do in the MC simulator
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt` line 227 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OC-jgwUDwIwyo64MufP:-OC-jgwUDwIwyo64MufQ:b-vutcnr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cd9c7c38b1ce3a6bd6bb15530361222542950922/src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt#L227)):*
> ```Kotlin
>         Report.State.RUNNING,
>         Report.State.UNRECOGNIZED,
>         Report.State.STATE_UNSPECIFIED -> delay(5000)
> ```

nit: Consider using exponential backoff with a max delay like we do in the MC simulator. This will give us faster results for reports that complete sooner, but eventually go to a longer poll if the report is taking longer

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845)* status: 15 of 20 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/local/testing/empty_encryption_key_pair_config.textproto` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OC-iKtc791H3NsuvjWw:-OC0sttS5OShJe6pkfPB:b-uefnx4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d1782efabc5e53d44d91d132809096c3514f9b4/src/main/k8s/local/testing/empty_encryption_key_pair_config.textproto#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This file already exists in the parent directory. If you need it from here, you can just add it to an `exports_files` declaration.
</blockquote></details>

I can't get this to work. Perhaps this is the reason why the db_creds_kustomization.yaml file is also an exact copy?
___
*[`src/main/k8s/local/testing/mc_config_kustomization.yaml` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OC-iYB8256MktXRs-6N:-OC0st989LqZmkohLODe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d1782efabc5e53d44d91d132809096c3514f9b4/src/main/k8s/local/testing/mc_config_kustomization.yaml#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here re: existing in the parent package.
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845)* status: 18 of 20 files reviewed, all discussions resolved

___
*[`src/main/k8s/local/testing/empty_encryption_key_pair_config.textproto` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OC-iKtc791H3NsuvjWw:-OC0y_tUEt7jcrEsMsNX:b-6hees3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d1782efabc5e53d44d91d132809096c3514f9b4/src/main/k8s/local/testing/empty_encryption_key_pair_config.textproto#L1)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I can't get this to work. Perhaps this is the reason why the db_creds_kustomization.yaml file is also an exact copy?
</blockquote></details>

Oh, I think I remember the issue. Kustomize is sensitive to exact file paths and doesn't even link symlinks. Therefore you will indeed need a copy :(

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1, 9 of 13 files at r2, 1 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OCFaQr68fACkI43vW_M:-OCFaQr68fACkI43vW_N:b4fhbzy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/343010233820662db57ce01968aeb6abf0d3aeaf/src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt#L17)):*
> ```Kotlin
>  */
> 
> package org.wfanet.measurement.loadtest.reporting
> ```

this isn't just for loadtesting, right? shouldn't it be under `org.wfanet.measurement.reporting.testing`?
___
*[`src/main/k8s/local/testing/BUILD.bazel` line 73 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OCFb2rK5P0YYT3S9-ga:-OCFb2rK5P0YYT3S9-gb:b8lei29) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/343010233820662db57ce01968aeb6abf0d3aeaf/src/main/k8s/local/testing/BUILD.bazel#L73)):*
> ```Starlark
> 
> kustomization_dir(
>     name = "config_files_for_panel_match",
> ```

`panel_match_config`?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/k8s/local/testing/BUILD.bazel` line 73 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OCFb2rK5P0YYT3S9-ga:-OCFnpBX2DcBo6ikfN_R:b-jf197c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/343010233820662db57ce01968aeb6abf0d3aeaf/src/main/k8s/local/testing/BUILD.bazel#L73)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`panel_match_config`?
</blockquote></details>

No. The `config_files` part of the name is referring to the ConfigMap named `config-files`.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845#-OCFaQr68fACkI43vW_M:-OCFnNqx5444JAA0i_sS:b-7de133) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/343010233820662db57ce01968aeb6abf0d3aeaf/src/main/kotlin/org/wfanet/measurement/loadtest/reporting/ReportingUserSimulator.kt#L17)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this isn't just for loadtesting, right? shouldn't it be under `org.wfanet.measurement.reporting.testing`?
</blockquote></details>

This is true of the entire `loadtest` package. It's an old mistake that has yet to be rectified.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1845)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
