### PR TITLE
Resolve claim lock contention issue by separating transaction

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1741)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1741)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt` line 148 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1741#-O3mwOla9XtpU6iE0Trj:-O3mumXR64tmvdKJj4Df:bwwogps) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01916394f4364ec282be93ed10b34533ef008506/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt#L148)):*
> ```Kotlin
>     prioritizedStages: List<StageT>,
>   ): String? {
>     /** Claim a specific task represented by the results of running the above sql. */
> ```

This now needs to be done in a broader loop.

1. Query for unclaimed task in first txn
2. Check task is still unclaimed in second transaction. If not, retry starting at (1).
3. Claim in second transaction
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt` line 151 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1741#-O3mw9kx37CbUhCYWBjV:-O3mw9kx37CbUhCYWBjW:b-z4n0ti) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01916394f4364ec282be93ed10b34533ef008506/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt#L151)):*
> ```Kotlin
>     suspend fun claimSpecificTask(result: UnclaimedTaskQueryResult<StageT>): Boolean =
>       databaseClient.readWriteTransaction().execute { txn ->
>         claim(
> ```

Where is the additional read/check in this second transaction? Without that, the original issue from # #1722 is present again.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1741)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt` line 151 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1741#-O3mw9kx37CbUhCYWBjV:-O3myZMvDfqiC8Mp4FK3:b22z1ep) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01916394f4364ec282be93ed10b34533ef008506/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt#L151)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Where is the additional read/check in this second transaction? Without that, the original issue from # #1722 is present again.
</blockquote></details>

I found the claim() function already checks the updateTime. I thought it was added by you in the recent PR. But actually it is there for a long time. Now it is a mystery to me why multiple mills can claim the same Computation at the same time.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1741)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt` line 148 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1741#-O3mwOla9XtpU6iE0Trj:-O3n9UD0D6v6TljmHS0Z:b-jn5s6n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01916394f4364ec282be93ed10b34533ef008506/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt#L148)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This now needs to be done in a broader loop.

1. Query for unclaimed task in first txn
2. Check task is still unclaimed in second transaction. If not, retry starting at (1).
3. Claim in second transaction
</blockquote></details>

Discussed offline.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt` line 151 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1741#-O3mw9kx37CbUhCYWBjV:-O3n9Vq4AWnJP-tyewH8:b-jn5s6n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01916394f4364ec282be93ed10b34533ef008506/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt#L151)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I found the claim() function already checks the updateTime. I thought it was added by you in the recent PR. But actually it is there for a long time. Now it is a mystery to me why multiple mills can claim the same Computation at the same time.
</blockquote></details>

Discussed offline.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1741)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
For some additional context, this is mostly reverting #1726. Using a single transaction can result in a lock contention issue, as the unclaimed tasks query will lock all claimable Computations DB rows. The solution is to use a separate transaction to perform the write, but to re-read the single row and ensure that it's still claimable. The old version of this check had a flaw in that it incorrectly assumes that the JVM clock is monotonic. This PR introduces an additional check based on `LockExpirationTime`, which is less susceptible to clock skew.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1741#-:-O3nRGXv-MMUnOhQXqbb:b2meub7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
