### PR TITLE
Partially Implement Integration Tests for Reporting V2Alpha.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
Tests currently do not compute the expected results and compare them to the actual results. That will be in a followup PR once the EDP simulator uses the synthetic data.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093)

**Review by tristanvuong2021 — COMMENTED** [review]
Tests currently do not compute the expected results and compare them to the actual results. That will be in a followup PR once the EDP simulator uses the synthetic data.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093#-:-NZgxrk07TvtZAWVLAZ_:b-q2qk59)* status: 0 of 12 files reviewed, all discussions resolved

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093)* status: all files reviewed, 3 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093#-NZlcv_0EBEvfQwejf_D:-NZlcv_0EBEvfQwejf_E:b-n2w61i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e5d32ee767d930603bb6f02015a50507dd1da/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L61)):*
> ```Kotlin
>     val createTime: Timestamp,
>     val timeIntervals: MutableSet<TimeInterval>,
>     val isPeriodic: Boolean,
> ```

No `is` prefix for boolean properties.

For background, that prefix was often used for methods since method names should be verb phrases. It doesn't apply to properties.



_Suggestion:_
```Kotlin
periodic
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 371 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093#-NZliiqND1UNlpVRmDnE:-NZliiqOAisi_tZf3lV3:b-tm3lin) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e5d32ee767d930603bb6f02015a50507dd1da/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L371)):*
> ```Kotlin
>         source.timeIntervals.sortedWith { a, b -> Timestamps.compare(a.startTime, b.startTime) }
> 
>       if (source.isPeriodic) {
> ```

Good catch! I didn't think of the fact that you otherwise couldn't tell the difference between multiple time intervals that might even happen to be periodic vs. an intentional periodic interval.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 635 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093#-NZltXb0DEPur7WN4smw:-NZltXb1Ag8cqZfQ_n5G:b-e8qlf0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e5d32ee767d930603bb6f02015a50507dd1da/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L635)):*
I suppose this *technically* complies to turn the UUID request ID to something that is not a UUID :P

From https://google.aip.dev/122:
> User-specified IDs **should not** be permitted to be a UUID (or any value that syntactically appears to be a UUID).
___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 341 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093#-NZlt8FD2Hh05i58jpvk:-NZlt8FD2Hh05i58jpvl:b-jw79dn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e5d32ee767d930603bb6f02015a50507dd1da/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L341)):*
> ```TSQL
>   CreateTime TIMESTAMP WITH TIME ZONE NOT NULL,
> 
>   IsPeriodic bool NOT NULL,
> ```

Same note here.



_Suggestion:_
```TSQL
Periodic
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093#-NZlcv_0EBEvfQwejf_D:-NZwyR5L6a6w6dy6REaT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e5d32ee767d930603bb6f02015a50507dd1da/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No `is` prefix for boolean properties.

For background, that prefix was often used for methods since method names should be verb phrases. It doesn't apply to properties.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 341 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093#-NZlt8FD2Hh05i58jpvk:-NZwyVW16LIYmVI6qbsx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e5d32ee767d930603bb6f02015a50507dd1da/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L341)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same note here.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by riemanli — APPROVED** [review]
> Reviewed 4 of 12 files at r1, 3 of 5 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 221 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093#-NZmI9GyBZE5MDTaYn2o:-NZmI9GyBZE5MDTaYn2p:b-i0k0yy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e5d32ee767d930603bb6f02015a50507dd1da/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L221)):*
> ```Kotlin
>     return try {
>       metricsStub
>         .withPrincipalName(parent)
> ```

Just curious, is this a better way to run the RPC?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 221 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1093#-NZmI9GyBZE5MDTaYn2o:-N_0DLiT81Xe6fyfKS1u:b-7d1s2h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e5d32ee767d930603bb6f02015a50507dd1da/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L221)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Just curious, is this a better way to run the RPC?
</blockquote></details>

The original way doesn't work. Only the kingdom uses the key.

**Pull request merged**
