### PR TITLE
Update local duchy worker2 to use postgres

### PR DESCRIPTION
**Pull request by YuhongWang-Amazon**
Update local duchy worker2 to use postgres database

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160)

**Review by YuhongWang-Amazon — COMMENTED** [review]
> Reviewed 3 of 14 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160)* status: 17 of 18 files reviewed, all discussions resolved

**Comment by renjiezh** [comment]
Hi, yuhong. Before we review this PR, could you please do some end-to-end test on GCP without merging it. This is the doc instructing deploy and test in QA environment. You could follow it to replace duchy_2 with postgres version and play around.
https://docs.google.com/document/d/1A7wXZtYWs0GLTBBZv4YEQpJ995LaHuGy5r7gWe_ZASQ/edit?resourcekey=0-yeM2zwGbYaIsPmPHgynyCw#heading=h.sjos1sttv69g

**Review by YuhongWang-Amazon — COMMENTED** [review]
Sure. Will do that.
Btw, this PR didn't update any terraform and k8s/dev folder, hence all duchies in GCP should still be spanners and will not be impacted. This PR only updates the local env where I updated the worker2 to postgres.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-:-Nb_GzWaEMze-e99jO4m:bbbn44o)* status: 16 of 18 files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — APPROVED** [review]
:lgtm:

> Reviewed 4 of 14 files at r1, 13 of 14 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-:-NbaTZMm2VeaUFdsmAeZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Review by YuhongWang-Amazon — COMMENTED** [review]
@renjiezh Created another [branch](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1167) to update halo-cmm-dev worker2 to use postgres, and passed the [correctness tests.](https://github.com/world-federation-of-advertisers/cross-media-measurement/actions/runs/5871952134/job/15922511426). Had to fix some bugs, please take another look. Appreciated! 

> Reviewed 1 of 14 files at r1, 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-:-Nbv9OGy8Q7JuLwXiAr7:b-t576j6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, 1 of 14 files at r2, 1 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160)* status: all files reviewed, 4 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/docker/images.bzl` line 121 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-NbzLijPBTjmNaI9SmaX:-NbzLijPBTjmNaI9SmaY:bm0rbvj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b20ee095c23e209205a902811b1a4271056c6d1/src/main/docker/images.bzl#L121)):*
> ```Starlark
>     struct(
>         name = "duchy_gcs_postgres_duchy_data_server_image",
>         image = "//src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/server:gcs_postgres_duchy_data_server_image",
> ```

Either mirror the naming of the Spanner one to make this `gcs_spanner_computations_server_image` or switch to more accurate naming to avoid the vague "data server" naming to make this `gcs_postgres_internal_server_image` (updating the image name/repo accordingly).

This is the image for the GCS/Postgres implementation of the server that serves the Duchy internal API.



_Code quote:_
```Starlark
gcs_postgres_duchy_data_server_image
```
___
*[`src/main/k8s/duchy.cue` line 64 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-NbzNMP-9y04jklA9lq_:-NbzNMP-9y04jklA9lqa:b-9e41l2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b20ee095c23e209205a902811b1a4271056c6d1/src/main/k8s/duchy.cue#L64)):*
> ```CUE
> 
> 	_millPollingInterval?:                    string
> 	_duchy_data_server_name:                  string
> ```

1. For some reason in the past we ended up mixing both `lower_snake_case` and `lowerCamelCase` for Cue fields. The latter is the correct casing, which should be used for all new fields.
2. We only use these fields with non-concrete values (e.g. `string`) when we need the option of customizing something that can't easily be specified at the appropriate location (e.g. addressing the pod spec).
___
*[`src/main/k8s/duchy.cue` line 104 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-NbzOBJ890EIsACBeJv9:-NbzOBJ890EIsACBeJvA:b-uefzt8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b20ee095c23e209205a902811b1a4271056c6d1/src/main/k8s/duchy.cue#L104)):*
> ```CUE
> 		"async-computation-control-server": {}
> 		"computation-control-server": _type: "LoadBalancer"
> 		"\(_duchy_data_server_name)": {}
> ```

Rather than having this be customized, just rename it to something generic that works for all cases.



_Suggestion:_
```CUE
"internal-api-server"
```
___
*[`src/main/k8s/duchy.cue` line 187 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-NbzP0sKDNjJGtjK8Rau:-NbzP0sL39HAzvIfAqvV:b-uefzt8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b20ee095c23e209205a902811b1a4271056c6d1/src/main/k8s/duchy.cue#L187)):*
> ```CUE
> 			] + _blob_storage_flags
> 		}
> 		"\(_duchy_data_server_deployment_name)": #ServerDeployment & {
> ```

Rather than having this be customized, just rename it to something generic that works for all cases.



_Suggestion:_
```CUE
"internal-api-server-deployment"
```

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/docker/images.bzl` line 121 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-NbzLijPBTjmNaI9SmaX:-Nbzl9-3AFPnyh8HmatD:bpf30b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b20ee095c23e209205a902811b1a4271056c6d1/src/main/docker/images.bzl#L121)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Either mirror the naming of the Spanner one to make this `gcs_spanner_computations_server_image` or switch to more accurate naming to avoid the vague "data server" naming to make this `gcs_postgres_internal_server_image` (updating the image name/repo accordingly).

This is the image for the GCS/Postgres implementation of the server that serves the Duchy internal API.
</blockquote></details>

I prefer the `gcs_postgres_internal_server_image`. Should I also update the class names? The class is still named GcsPostgresDuchyDataServer.kt

**Review by renjiezh — APPROVED** [review]
> Reviewed 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @YuhongWang-Amazon)

**Review by YuhongWang-Amazon — COMMENTED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/duchy.cue` line 64 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-NbzNMP-9y04jklA9lq_:-Nc-3-LTBAX0Fh5tbiPL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b20ee095c23e209205a902811b1a4271056c6d1/src/main/k8s/duchy.cue#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. For some reason in the past we ended up mixing both `lower_snake_case` and `lowerCamelCase` for Cue fields. The latter is the correct casing, which should be used for all new fields.
2. We only use these fields with non-concrete values (e.g. `string`) when we need the option of customizing something that can't easily be specified at the appropriate location (e.g. addressing the pod spec).
</blockquote></details>

Done.
___
*[`src/main/k8s/duchy.cue` line 104 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-NbzOBJ890EIsACBeJv9:-Nc-2nwz3vz7GXb_JUQX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b20ee095c23e209205a902811b1a4271056c6d1/src/main/k8s/duchy.cue#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rather than having this be customized, just rename it to something generic that works for all cases.
</blockquote></details>

Done.
___
*[`src/main/k8s/duchy.cue` line 187 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-NbzP0sKDNjJGtjK8Rau:-Nc-2pBPCArvu9tS30oa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b20ee095c23e209205a902811b1a4271056c6d1/src/main/k8s/duchy.cue#L187)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rather than having this be customized, just rename it to something generic that works for all cases.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, 9 of 14 files at r2, 3 of 7 files at r4, 5 of 6 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160)* status: all files reviewed, 2 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/docker/images.bzl` line 121 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-NbzLijPBTjmNaI9SmaX:-Nc-cFSu8IHCPnRLQIl1:b-nd89js) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b20ee095c23e209205a902811b1a4271056c6d1/src/main/docker/images.bzl#L121)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

I prefer the `gcs_postgres_internal_server_image`. Should I also update the class names? The class is still named GcsPostgresDuchyDataServer.kt
</blockquote></details>

Yes if you wouldn't mind.
___
*[`src/main/k8s/local/duchies.cue` line 50 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-Nc-ckzjBwmZXz7fjEC5:-Nc-ckzjBwmZXz7fjEC6:b-83sjoh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/534cabfb7d4e2bedb2e9e703957b84ca85d26177/src/main/k8s/local/duchies.cue#L50)):*
> ```CUE
> 		protocolsSetupConfig:    "non_aggregator_protocols_setup_config.textproto"
> 		certificateResourceName: _worker2_cert_name
> 		databaseType:            "postgres"
> ```

Nice!

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160)* status: all files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/docker/images.bzl` line 121 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160#-NbzLijPBTjmNaI9SmaX:-Nc2pJfH6HxhwTAQR66m:b7iqkw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4b20ee095c23e209205a902811b1a4271056c6d1/src/main/docker/images.bzl#L121)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes if you wouldn't mind.
</blockquote></details>

I attempted to update this but found too many changes are required. Also both kingdom and reporting still have the data server names. Hence I decided to leave the class names like this for now. I prefer that we define a common name format for internal data servers of all three components and update them together later.

**Review by YuhongWang-Amazon — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Pull request merged**
