### PR TITLE
Add metric variances to metric results in reporting v2

### PR DESCRIPTION
**Pull request by riemanli**
Compute metric variances in a report using the `Variances` library. Any insufficiency of inputs to the variance calculation will not set `univariate_statistics`.

* Reach: compute variances from weighted reach measurements.
* Frequency histogram: compute variances from weighted reach and frequency measurements.
* Impression count: compute variances only when the operation is union-only. The variance of an impression metric is the sum of the weighted impression results.
* Watch duration: compute variances only when the operation is union-only. The variance of a duration metric is the sum of the weighted duration results.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1265** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1265" target="_blank">Graphite</a> 
    * **PR #1253** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1253" target="_blank">Graphite</a> 
      * **PR #1266** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1266" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1266?utm_source=stack-comment).

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 7 of 10 files at r2, 1 of 4 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: 11 of 13 files reviewed, all discussions resolved

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 5067 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgaGvLN4VmKQVc6lHTg:-NgaGvLN4VmKQVc6lHTh:bcfuf1f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77ca0368ff6d3d25d0aabb23fa55485c3fb5351a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L5067)):*
> ```Kotlin
>     val request = getMetricRequest { name = SUCCEEDED_INCREMENTAL_REACH_METRIC.name }
> 
>     assertFailsWith<IllegalStateException> {
> ```

Where is IllegalStateException coming from here.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 5126 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgaFG3yDi-uCTIsAba1:-NgaFG3yDi-uCTIsAba2:bo80qv5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77ca0368ff6d3d25d0aabb23fa55485c3fb5351a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L5126)):*
> ```Kotlin
>                                 customDirectMethodology = customDirectMethodology {
>                                   frequency =
>                                     org.wfanet.measurement.internal.reporting.v2
> ```

Should import the internal  CustomDirectMethodology with an alias
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 6264 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgaEjWa91zv8B7vJXAN:-NgaEjWa91zv8B7vJXAO:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77ca0368ff6d3d25d0aabb23fa55485c3fb5351a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L6264)):*
> ```Kotlin
>                                 customDirectMethodology = customDirectMethodology {
>                                   frequency =
>                                     org.wfanet.measurement.internal.reporting.v2
> ```

ditto
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 6504 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgaFMtEETP5JVbTGj9G:-NgaFMtEETP5JVbTGj9H:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77ca0368ff6d3d25d0aabb23fa55485c3fb5351a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L6504)):*
> ```Kotlin
>                                   customDirectMethodology = customDirectMethodology {
>                                     frequency =
>                                       org.wfanet.measurement.internal.reporting.v2
> ```

ditto

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 5067 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgaGvLN4VmKQVc6lHTg:-NgaXm937TG5p-VubFsU:b-z581cr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77ca0368ff6d3d25d0aabb23fa55485c3fb5351a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L5067)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Where is IllegalStateException coming from here.
</blockquote></details>

It's from [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/riemanli_add_metric_variance_to_reporting_v2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2187) when the metric is reach type.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 5126 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgaFG3yDi-uCTIsAba1:-Nga_M1Z0Pc4yS6bZBmz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77ca0368ff6d3d25d0aabb23fa55485c3fb5351a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L5126)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Should import the internal  CustomDirectMethodology with an alias
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 6264 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgaEjWa91zv8B7vJXAN:-Nga_Mvo2pqOTmP1zIR6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77ca0368ff6d3d25d0aabb23fa55485c3fb5351a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L6264)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 6504 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgaFMtEETP5JVbTGj9G:-Nga_NXFEdrDDhDCFJAm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77ca0368ff6d3d25d0aabb23fa55485c3fb5351a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L6504)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 5067 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgaGvLN4VmKQVc6lHTg:-Nge2znEA4TmodVWofG4:b44vghi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77ca0368ff6d3d25d0aabb23fa55485c3fb5351a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L5067)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

It's from [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/riemanli_add_metric_variance_to_reporting_v2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2187) when the metric is reach type.
</blockquote></details>

error needs to be replaced with a grpc exception. I checked it and the client just sees UNKNOWN with no message when error is thrown.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 5067 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgaGvLN4VmKQVc6lHTg:-NgeKNQb6h9m05UFf06x:b75mmhc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77ca0368ff6d3d25d0aabb23fa55485c3fb5351a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L5067)):*
> error needs to be replaced with a grpc exception.

Just making sure my understanding is correct. Do you mean gRPC services should always throw gRPC exceptions instead of errors?

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 5067 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgaGvLN4VmKQVc6lHTg:-NgeSVXL4_9j8UCqzlLY:b-wc9026) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77ca0368ff6d3d25d0aabb23fa55485c3fb5351a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L5067)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> error needs to be replaced with a grpc exception.

Just making sure my understanding is correct. Do you mean gRPC services should always throw gRPC exceptions instead of errors?
</blockquote></details>

Yes, so you can provide an error message. The message in error would show up in the server logs, but not in the response to the client.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 5067 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgaGvLN4VmKQVc6lHTg:-NgfDhif4inapyiKP54x:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/77ca0368ff6d3d25d0aabb23fa55485c3fb5351a/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L5067)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Yes, so you can provide an error message. The message in error would show up in the server logs, but not in the response to the client.
</blockquote></details>

Done.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 4 of 10 files at r2, 3 of 4 files at r4, 2 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by jiayu-google — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2012 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgzPq0vDx9glIi7wRH5:-NgzPq0vDx9glIi7wRH6:b-uckshc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01cf34d0396b1427fa102c6bec052d453f4d91f6/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2012)):*
> ```Kotlin
>                 sqrt(frequencyVariances.kPlusCountVariances.getValue(frequency.toInt()))
>             }
>             relativeUnivariateStatistics = univariateStatistics {
> ```

kPlusRelativeUnivariateStatistics?

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @jiayu-google, @Marco-Premier, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2012 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-NgzPq0vDx9glIi7wRH5:-Nh2bIrfBmM--umx4j8Q:b-x8yi3y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01cf34d0396b1427fa102c6bec052d453f4d91f6/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2012)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

kPlusRelativeUnivariateStatistics?
</blockquote></details>

Thanks for catching it! Done.

**Review by jiayu-google — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266#-:-Nh38WBEBDtIHyqmI9-x:bnfp4nl)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @Marco-Premier and @tristanvuong2021)

**Review by riemanli — COMMENTED** [review]
> Reviewed 4 of 10 files at r2, 3 of 4 files at r4, 2 of 3 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @Marco-Premier and @tristanvuong2021)

**Review by riemanli — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1266)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Pull request merged**
