### PR TITLE
Add UI features from Demo work

### PR DESCRIPTION
**Pull request by bdomen-ggl**
Several small changes from added features during the demo:
* Added the "demo" banner at the top of the site and made it sticky.
* Updated some card labels in the Report view and adjusted the styles so the columns aren't fixed. Didn't specifically get feedback from UX on the behavior but this was requested from users.
* Also made the summary cards more flexible for different content.
* Added an overflow to the card in case the user is on a small screen. This was noticeable in the summary table.
* Removed "on target reach" from the charts.
* Updated the title.
* Added Google Analytics.

Bug Fixes:
* Added a margin at the bottom of the site so the feedback button isn't stuck over things at the bottom like charts.
* Fixed fonts. There was an extra "./" in the font src that would work locally but screw up webpack with routes on the server. Also removed the extra font styles and just left sans serif.
* Added more cases to the number to magnitude converter including handling the 0 case to make the logic simpler.
* Updated BUILD files for some ChartGroups. These charts were removed from the current UI so they didn't fail the build.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1495)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1495)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/public/manifest.json` line 6 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1495#-NrCidtx9fwigNLqLLIm:-NrCidtx9fwigNLqLLIn:b-k9a49a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd8c16bebac3d7841eb3ee697f4c6e6e644dc72c/experimental/reporting-ui/src/main/react/reporting-ui/public/manifest.json#L6)):*
> ```JSON
>   "icons": [
>     {
>       "src": "favicon.png",
> ```

Is this generated from somewhere? I only see the .ico file.

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1495)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`experimental/reporting-ui/src/main/react/reporting-ui/public/manifest.json` line 6 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1495#-NrCidtx9fwigNLqLLIm:-NrGZUXm3-ImCt0JSwEN:b-smbp1k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd8c16bebac3d7841eb3ee697f4c6e6e644dc72c/experimental/reporting-ui/src/main/react/reporting-ui/public/manifest.json#L6)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this generated from somewhere? I only see the .ico file.
</blockquote></details>

Ah yeah that should technically be favicon.ico. Don't know why it worked when I built it though.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1495)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl)

**Pull request merged**
