### PR TITLE
Reporting sets service

### PR DESCRIPTION
**Pull request by riemanli**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597)

### CODE REVIEW

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
Missing the unit tests.

> Reviewed 34 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-:-N49wqIF9IK9F7ottIU_:b-uqzsrp)* status: 34 of 36 files reviewed, 3 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N49voYyAtc7ebopmQcX:-N49voYyAtc7ebopmQcY:b-e555e6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c04169a9d222d03de1099fd07e299fe8d050d077/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt#L20)):*
> ```Kotlin
> import kotlin.math.min
> import kotlinx.coroutines.flow.toList
> import org.wfanet.measurement.api.v2.alpha.ListReportingSetsPageToken
> ```

nit: I realized I accidently named this v2.alpha instead of v2alpha.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N49vwd28JmWw1bnbMlK:-N49vwd28JmWw1bnbMlL:b-vs9gka) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c04169a9d222d03de1099fd07e299fe8d050d077/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt#L24)):*
> ```Kotlin
> import org.wfanet.measurement.api.v2.alpha.copy
> import org.wfanet.measurement.api.v2.alpha.listReportingSetsPageToken
> import org.wfanet.measurement.api.v2alpha.EventGroupKey
> ```

Should be using a reporting specific EventGroupKey since the resource name is different from the CMMS one.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt` line 226 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N49w97-1uqIRT68Jkeb:-N49w97-1uqIRT68Jkec:b-te4hvc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c04169a9d222d03de1099fd07e299fe8d050d077/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt#L226)):*
> ```Kotlin
>         )
>         .toName()
>     eventGroups.addAll(eventGroupKeysList.map { it.eventGroupReferenceId })
> ```

Should also be using an EventGroupKey here. eventGroupReferenceId is just the event group specific part. I broke the name down into 3 parts.

**Review by riemanli — COMMENTED** [review]
Yes... I will add one for `ReportingSetsService`.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-:-N4A3HH69oRoaVeqwN0e:b-r6obfz)* status: 34 of 36 files reviewed, 3 unresolved discussions (waiting on @riemanli and @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 33 of 36 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597)* status: 38 of 39 files reviewed, 9 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/AccountKey.kt` line 18 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N4T5uLoAMF4ee60c4wp:-N4T5uLp5-c20W_VWMw5:b-nuaa5j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e5fa71acbddb58ed5e533d35e64a0c5909bb63/src/main/kotlin/org/wfanet/measurement/api/v2alpha/AccountKey.kt#L18)):*
> ```Kotlin
> 
> import org.wfanet.measurement.common.ResourceNameParser
> import org.wfanet.measurement.common.api.ResourceKey
> ```

While not strictly required, it'd be nice if moving `ResourceKey` was in a separate pre-factoring PR.
___
*[`src/main/kotlin/org/wfanet/measurement/common/api/BUILD.bazel` line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N4T66q22mLyZ1Nn4rAW:-N4T66q3Am1YcZ0OHC8-:b-qjfmhg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e5fa71acbddb58ed5e533d35e64a0c5909bb63/src/main/kotlin/org/wfanet/measurement/common/api/BUILD.bazel#L9)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "resource_key_interface",
> ```

nit: just `resource_key`



_Code quote:_
```Starlark
resource_key_interface
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt` line 134 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N4TAL0-5s3MLdeTnKdm:-N4TAL0-5s3MLdeTnKdn:b-7xwmlg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e5fa71acbddb58ed5e533d35e64a0c5909bb63/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt#L134)):*
> ```Kotlin
>             }
>           }
>         nextPageToken = pageToken.toByteArray().base64UrlEncode()
> ```

No need to convert to ByteArray here. There's a `base64UrlEncode()` extension for `ByteString` that may avoid some byte shuffling.



_Code quote:_
```Kotlin
toByteArray().base64UrlEncode()
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt` line 198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N4TC4cs8FM8Ny81tRqG:-N4TC4cs8FM8Ny81tRqH:bqdigvs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e5fa71acbddb58ed5e533d35e64a0c5909bb63/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt#L198)):*
> ```Kotlin
>   return internalReportingSet {
>     measurementConsumerReferenceId = measurementConsumerKey.measurementConsumerId
>     eventGroupKeys.addAll(
> ```

nit: a regular for loop may be easier to read here

```kotlin
for (eventGroup: String in source.eventGroupsList) {
  eventGroupKeys += grpcRequireNotNull(EventGroupKey.fromName(eventGroup)) {/*...*/}.toInternal()
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt` line 199 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N4TBLF606yt6PRfLwAW:-N4TBLF79a_esMlTUmni:bzgtdtp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e5fa71acbddb58ed5e533d35e64a0c5909bb63/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt#L199)):*
> ```Kotlin
>     measurementConsumerReferenceId = measurementConsumerKey.measurementConsumerId
>     eventGroupKeys.addAll(
>       this@toInternal.eventGroupsList.map {
> ```

nit: we tend to do a `val source = this` as the first line as that ends up clearer than using qualified `this`



_Code quote:_
```Kotlin
this@toInternal
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt` line 200 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N4TDRJy91HtcLohnwrS:-N4TDRJz2qksepRUN_GX:b5mbdfx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e5fa71acbddb58ed5e533d35e64a0c5909bb63/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt#L200)):*
> ```Kotlin
>     eventGroupKeys.addAll(
>       this@toInternal.eventGroupsList.map {
>         eventGroupKey {
> ```

nit: Extract an `EventGroupKey.toInternal` extension



_Code quote:_
```Kotlin
eventGroupKey
```

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597)* status: 34 of 40 files reviewed, 9 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt` line 198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N4TC4cs8FM8Ny81tRqG:-N4U4mGI6c-ouTmzthMC:b-rmlqfd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e5fa71acbddb58ed5e533d35e64a0c5909bb63/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt#L198)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: a regular for loop may be easier to read here

```kotlin
for (eventGroup: String in source.eventGroupsList) {
  eventGroupKeys += grpcRequireNotNull(EventGroupKey.fromName(eventGroup)) {/*...*/}.toInternal()
}
```
</blockquote></details>

Thanks for the suggestion. Modified.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt` line 199 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N4TBLF606yt6PRfLwAW:-N4U4dYfC4nylzLeKVzo:bm0sh7b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e5fa71acbddb58ed5e533d35e64a0c5909bb63/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt#L199)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: we tend to do a `val source = this` as the first line as that ends up clearer than using qualified `this`
</blockquote></details>

Thanks for the suggestion. Modified
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt` line 200 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N4TDRJy91HtcLohnwrS:-N4U4g_bCDIhrsR5HFnS:b-43d3il) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e5fa71acbddb58ed5e533d35e64a0c5909bb63/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt#L200)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Extract an `EventGroupKey.toInternal` extension
</blockquote></details>

Thanks for the suggestion. Modified.

**Comment by tristanvuong2021** [comment]
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N49voYyAtc7ebopmQcX:-N4XzFOL2hHk3FW6YuQJ:bn6mpq1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c04169a9d222d03de1099fd07e299fe8d050d077/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt#L20)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for letting me know. Any AI here?
</blockquote></details>

Don't worry about this. I should fix this myself in a separate PR.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597)* status: 38 of 40 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt` line 134 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N4TAL0-5s3MLdeTnKdm:-N4YsTrh6t66MbTNmIXK:b-bg8cd9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63e5fa71acbddb58ed5e533d35e64a0c5909bb63/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportingSetsService.kt#L134)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, what I meant was to convert to `ByteString` instead of `ByteArray`.

This should work:
```
pageToken.toByteString().base64UrlEncode()
```
</blockquote></details>

Understood. Modified.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportingSetsServiceTest.kt` line 352 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N4cMyGgD_sk1FpM-psU:-N4cMyGgD_sk1FpM-psV:b-7kiajp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5f78452aaf1c3ba685f2cdc3839e61ab38640c32/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportingSetsServiceTest.kt#L352)):*
> ```Kotlin
>     }
> 
>     val streamReportingSetsRequest =
> ```

nit: there's a `verifyProtoArgument` helper for this in `org.wfanet.measurement.common.testing`

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597)* status: 38 of 40 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportingSetsServiceTest.kt` line 352 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597#-N4cMyGgD_sk1FpM-psU:-N4dFTpr73wyiQ088fHU:b3jzqqy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5f78452aaf1c3ba685f2cdc3839e61ab38640c32/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportingSetsServiceTest.kt#L352)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: there's a `verifyProtoArgument` helper for this in `org.wfanet.measurement.common.testing`
</blockquote></details>

Thanks for the suggestion! Modified.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r12, 2 of 2 files at r14, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by chipingyeh — APPROVED** [review]
> Reviewed 1 of 36 files at r1, 1 of 6 files at r2, 2 of 5 files at r3, 1 of 2 files at r14, 1 of 1 files at r16, 34 of 34 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Pull request merged**
