### PR TITLE
ci: Use BuildBuddy for Bazel results, remote caching, and remote execution

### PR DESCRIPTION
**Pull request by SanjayVas**
This greatly speeds up builds and provides a detailed UI for results. See https://buildbuddy.io/

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1840)

**Review by stevenwarejones — APPROVED** [review]
what kind of performance gains are you seeing?

> Reviewed 4 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1840#-:-O9tHVZy6KLLcmt5jPv6:b-qg2lyl)* status: 4 of 31 files reviewed, all discussions resolved

**Review by SanjayVas — COMMENTED** [review]
You can compare all the [runs on this branch](https://github.com/world-federation-of-advertisers/cross-media-measurement/actions/workflows/build-test.yml?query=branch%3Asanjayvas-buildbuddy) to runs outside of this branch to see.

Even the cache itself is faster, so a fully cached run on main took 19m where the one on this branch took 5m.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1840#-:-O9u3uE3AeKYHqpNbRSY:b-ewhdy2)* status: 4 of 31 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 27 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1840)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
