### PR TITLE
Move InProcessKingdom to main folder

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein and @wangyaopw)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/gcloud/InProcessKingdom.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314#-MlFxy0uAjbc8PQiLB0V:-MlFxy0uAjbc8PQiLB0W:b-qsep7p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b73968505ff06bc8a1dd74d8094a189c7d66c73/src/main/kotlin/org/wfanet/measurement/integration/deploy/gcloud/InProcessKingdom.kt#L25)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.testing.KINGDOM_SCHEMA
> 
> @get:Rule val spannerDatabase = SpannerEmulatorDatabaseRule(KINGDOM_SCHEMA)
> ```

I don't think this will work. @wangyaopw -- can you help Yunus figure out the right abstraction for this so we can launch an InProcessKingdom from panel-exchange-client repo without having to think about its deps?

**Review by wangyaopw — CHANGES_REQUESTED** [review]
If you move InProcessKingdom, maybe also move InProcessDuchy etc. Otherwise it is weird we have them in different places.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314#-:-MlGSndE7CZ7ggd4dVqr:bbsr9f0)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/gcloud/InProcessKingdom.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314#-MlFxy0uAjbc8PQiLB0V:-MlGSLFlCo_wsvxl0-sY:bhxise0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b73968505ff06bc8a1dd74d8094a189c7d66c73/src/main/kotlin/org/wfanet/measurement/integration/deploy/gcloud/InProcessKingdom.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't think this will work. @wangyaopw -- can you help Yunus figure out the right abstraction for this so we can launch an InProcessKingdom from panel-exchange-client repo without having to think about its deps?
</blockquote></details>

maybe move the `KingdomDataServicesProviderRule` under `main` and make it public and use it in the panel-exchange-client repo
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314#-MlGRPm8358rvkh-w0xD:-MlGRPm8358rvkh-w0xE:b-qfdw6r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b73968505ff06bc8a1dd74d8094a189c7d66c73/src/test/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L45)):*
> ```
> integration/common:in_process_kingdom",
> ```
You are doing transitive dependency here.

The files in here depends on the KINGDOM_SYSTEM_API_SERVICES and KINGDOM_PUBLIC_API_SERVICES directly.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/gcloud/InProcessKingdom.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314#-MlFxy0uAjbc8PQiLB0V:-MlGptVHC0ca626YHUAg:bhh2c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b73968505ff06bc8a1dd74d8094a189c7d66c73/src/main/kotlin/org/wfanet/measurement/integration/deploy/gcloud/InProcessKingdom.kt#L25)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

maybe move the `KingdomDataServicesProviderRule` under `main` and make it public and use it in the panel-exchange-client repo
</blockquote></details>

I'd rather not leak KingdomDataServices to outside of where it is, maybe we just make a `SpannerInProcessKingdomRule` that's self-contained and starts up databases, etc. as necessary?

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 7 files at r2, 1 of 18 files at r3, 18 of 20 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/gcloud/InProcessKingdom.kt, line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314#-MlRNfUi1hGBYh8OhAG4:-MlRx8rf2nPL8NkvSWvL:b-k2nz25) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a67fa9bb5d566796bd6fc28a0a7232d4a91ae667/src/main/kotlin/org/wfanet/measurement/integration/deploy/gcloud/InProcessKingdom.kt#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

After chatting, our plan:

Add: `fun buildKingdomSpannerEmulatorDatabaseRule(): SpannerEmulatorDatabaseRule { return SpannerEmulatorDatabaseRule(KINGDOM_SCHEMA) }`

Use `SpannerEmulatorDatabaseRule` as parameter type here.

Build SpannerDataServices from SpannerEmulatorDatabaseRule in the `dataServicesProvider` lambda below.
</blockquote></details>

How about:

```
fun buildKingdomSpannerEmulatorDatabaseRule(): SpannerEmulatorDatabaseRule {
  return SpannerEmulatorDatabaseRule(KINGDOM_SCHEMA)
}

fun buildSpannerInProcessKingdom(databaseRule: SpannerEmulatorDatabaseRule, clock: Clock = Clock.systemUTC()): InProcessKingdom {
  return InProcessKingdom(
      dataServicesProvider = {
        SpannerDataServices(clock, RandomIdGenerator(clock), databaseRule.databaseClient)
      },
      verboseGrpcLogging = false,
    )
}
```

then clients do:

```
val databaseRule = buildKingdomSpannerEmulatorDatabaseRule()
val inProcessKingdom = buildSpannerInProcessKingdom(databaseRule)
@Rule val chainedRules = chainRulesSequentially(databaseRule, inProcessKingdom)
```

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/gcloud/InProcessKingdom.kt, line 36 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/314#-MlRzqLeAM_RDgj6MHQp:-MlRzqLf1PLYOgaweX_x:b-n7dddr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33ac3059bd1280e92f3a1d97b5aa23b2e1981c8b/src/main/kotlin/org/wfanet/measurement/integration/deploy/gcloud/InProcessKingdom.kt#L36)):*
> ```Kotlin
>       SpannerDataServices(clock, RandomIdGenerator(clock), databaseRule.databaseClient)
>     },
>     verboseGrpcLogging = false,
> ```

Maybe take this in as an optional parameter?

```
fun buildSpannerInProcessKingdom(
  databaseRule: SpannerEmulatorDatabaseRule,
  clock: Clock = Clock.systemUTC(),
  verboseGrpcLogging = false
): InProcessKingdom {
  return InProcessKingdom(
    dataServicesProvider = {
      SpannerDataServices(clock, RandomIdGenerator(clock), databaseRule.databaseClient)
    },
    verboseGrpcLogging = verboseGrpcLogging,
...
```

**Pull request merged**
