### PR TITLE
Update the herald to call the new system ComputationsService (v2alpha design).

### PR DESCRIPTION
**Pull request by wangyaopw**
- Only creating computation is updated in this PR.
- Deleted the ProtocolStarter interface since different protocols are expected to have different sets of methods now.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 167 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-Maa2VvRAqseh2Buvjx_:-Maa2VvRAqseh2Buvjxa:b-8w1gdu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96a9c12204cb81944be65dd3dcfe52c724f036f5/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L167)):*
> ```Kotlin
>           size = publicProtocolConfig.liquidLegionsV2.sketchParams.maxSize
>         }
>         it.noiseBuilder.apply {
> ```

Maybe inside here:

```
val noise = duchyProtocolConfig.liquidLegionsV2.mpcNoise
```

to shorten these lines up
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/PublicApiVersion.kt, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-Maa2ux0E91_q4S-ZE-8:-Maa2ux15Kf1eKeJ2Q1f:buf6iq9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96a9c12204cb81944be65dd3dcfe52c724f036f5/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/PublicApiVersion.kt#L18)):*
> ```Kotlin
> 
> /** Supported public Api versions in the duchy. */
> enum class PublicApiVersions {
> ```

I think enums are generally singular. See e.g. https://google.github.io/styleguide/javaguide.html#s4.8.1-enum-classes or https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html. I would prefer `PublicApiVersion` and `toPublicApiVersion`.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt, line 495 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-Maa3pL9424I3hpnqQkD:-Maa3pL9424I3hpnqQkE:b-m1lp0y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96a9c12204cb81944be65dd3dcfe52c724f036f5/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L495)):*
> ```Kotlin
> 
>   companion object {
>     const val EMPTY_TOKEN = ""
> ```

I think it would be more consistent with other tests to put this outside of the class at the top of the file (and mark it private).

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 167 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-Maa2VvRAqseh2Buvjx_:-Maaazwr2gYQUl7ipTrC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96a9c12204cb81944be65dd3dcfe52c724f036f5/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L167)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe inside here:

```
val noise = duchyProtocolConfig.liquidLegionsV2.mpcNoise
```

to shorten these lines up
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/PublicApiVersion.kt, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-Maa2ux0E91_q4S-ZE-8:-MaabKtJ01pbkVvgjsxz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96a9c12204cb81944be65dd3dcfe52c724f036f5/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/PublicApiVersion.kt#L18)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think enums are generally singular. See e.g. https://google.github.io/styleguide/javaguide.html#s4.8.1-enum-classes or https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html. I would prefer `PublicApiVersion` and `toPublicApiVersion`.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt, line 495 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-Maa3pL9424I3hpnqQkD:-MaabYhY9VPc_pusfEdV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96a9c12204cb81944be65dd3dcfe52c724f036f5/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L495)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think it would be more consistent with other tests to put this outside of the class at the top of the file (and mark it private).
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 14 of 18 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ComputationConverter.kt, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MadU4bv2D8TqIKujlyA:-MadU4bv2D8TqIKujlyB:bqq1hxd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b0dc77fc0ed6ce208e2dd94ed2b27cfbed726c79/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ComputationConverter.kt#L1)):*
> ```Kotlin
> // Copyright 2020 The Cross-Media Measurement Authors
> ```

nit: Maybe name this ComputationConversions.kt instead since there isn't actually a converter class/object.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ComputationConverter.kt, line 18 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MadUJbDD6aUAM2zQHbU:-MadUJbDD6aUAM2zQHbV:b-jlklkt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b0dc77fc0ed6ce208e2dd94ed2b27cfbed726c79/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ComputationConverter.kt#L18)):*
> ```
> v2AlphaEncryptionPublicKey
> ```
Capital `V` since this is still a type.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MadUrNB89fMWy3u2Do1:-MadUrNB89fMWy3u2Do2:bmdpm4s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b0dc77fc0ed6ce208e2dd94ed2b27cfbed726c79/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L50)):*
> ```
> @param systemComputationsClient
> ```
`@param` documentation doesn't seem to match actual name.
___
*[src/main/proto/wfa/measurement/system/v1alpha/computation.proto, line 115 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MadWzOdByttfc1wZuPF:-MadWzOdByttfc1wZuPG:bz11vx1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b0dc77fc0ed6ce208e2dd94ed2b27cfbed726c79/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L115)):*
> ```
> DifferentialPrivacyParams
> ```
Define this at the top level instead of nested in MpcNoise since it could end up useful elsewhere. Possibly in a separate file.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79)* status: all files reviewed, 6 unresolved discussions (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MadRLI98JCMKPziq-m7:-MadRLIA57_QxClvPUXl:bb4pbsk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b0dc77fc0ed6ce208e2dd94ed2b27cfbed726c79/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L160)):*
> ```Kotlin
>     }
> 
>     return Parameters.newBuilder()
> ```

This is totally optional: it might make the code a little easier to read if you extract a bunch of `SomeSubmessage.toLiquidLegionsV2Parameters` helper functions.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt, line 495 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-Maa3pL9424I3hpnqQkD:-MadZyb1ErxUiB1wXqHF:b739c0s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96a9c12204cb81944be65dd3dcfe52c724f036f5/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L495)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I was thinking like this: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClientsTest.kt#L94 because it's a constant.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79)* status: 12 of 20 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MadUrNB89fMWy3u2Do1:-Madc64eCRkASg0ocshv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b0dc77fc0ed6ce208e2dd94ed2b27cfbed726c79/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> @param systemComputationsClient
> ```
`@param` documentation doesn't seem to match actual name.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MadRLI98JCMKPziq-m7:-MaddT9t22wFDmXEFH0E:b-5djkcj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b0dc77fc0ed6ce208e2dd94ed2b27cfbed726c79/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L160)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is totally optional: it might make the code a little easier to read if you extract a bunch of `SomeSubmessage.toLiquidLegionsV2Parameters` helper functions.
</blockquote></details>

there are multiple sub-sources (duchyProtocolConfig measurementSpec, public api ProtocolConfig) and multiple sub-targets, it is a little hard to break it down separately. Just keep it as is to save trouble.
___
*[src/main/proto/wfa/measurement/system/v1alpha/computation.proto, line 115 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MadWzOdByttfc1wZuPF:-Madj0JL1BCyMNGt7Z_u:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b0dc77fc0ed6ce208e2dd94ed2b27cfbed726c79/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> DifferentialPrivacyParams
> ```
Define this at the top level instead of nested in MpcNoise since it could end up useful elsewhere. Possibly in a separate file.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt, line 495 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-Maa3pL9424I3hpnqQkD:-Madn6RdD9ApYqny3m01:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96a9c12204cb81944be65dd3dcfe52c724f036f5/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L495)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I was thinking like this: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClientsTest.kt#L94 because it's a constant.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ComputationConverter.kt, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MadU4bv2D8TqIKujlyA:-MadaEME4n7e7hMHnwgr:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b0dc77fc0ed6ce208e2dd94ed2b27cfbed726c79/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ComputationConverter.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Maybe name this ComputationConversions.kt instead since there isn't actually a converter class/object.
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ComputationConverter.kt, line 18 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MadUJbDD6aUAM2zQHbU:-MadajgL8uR8bF6PatFG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b0dc77fc0ed6ce208e2dd94ed2b27cfbed726c79/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ComputationConverter.kt#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> v2AlphaEncryptionPublicKey
> ```
Capital `V` since this is still a type.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 7 of 8 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @zachcwc)

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @zachcwc)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 7 of 8 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Comment by zachcwc** [comment]
___
*[src/main/proto/wfa/measurement/config/public_api_protocol_configs.proto, line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MajcSbL6VYHnmhRInkR:-MajcSbL6VYHnmhRInkS:b19dafg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a32f77f072388d1afba9ad4aa9e442bc2ace9d59/src/main/proto/wfa/measurement/config/public_api_protocol_configs.proto#L28)):*
> ```protobuf
> message PublicApiProtocolConfigs {
>   // Map of ProtocolConfig resource ID to the config.
>   map<string, .wfa.measurement.api.v2alpha.ProtocolConfig> configs = 1;
> ```

Is this a typo? Why is it ".wfa" instead of "wfa" ?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @SanjayVas, and @zachcwc)

___
*[src/main/proto/wfa/measurement/config/public_api_protocol_configs.proto, line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MajcSbL6VYHnmhRInkR:-MajeIYVBuTi-uwgn6Xl:b-wg8pud) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a32f77f072388d1afba9ad4aa9e442bc2ace9d59/src/main/proto/wfa/measurement/config/public_api_protocol_configs.proto#L28)):*
<details><summary><i>Previously, zachcwc wrote…</i></summary><blockquote>

Is this a typo? Why is it ".wfa" instead of "wfa" ?
</blockquote></details>

actually 
```
.wfa.measurement.api.v2alpha.ProtocolConfig
wfa.measurement.api.v2alpha.ProtocolConfig
measurement.api.v2alpha.ProtocolConfig
api.v2alpha.ProtocolConfig
```
all works.

.wfa means it is the root I think.

updated to `wfa.measurement.api.v2alpha.ProtocolConfig` anyway

**Comment by zachcwc** [comment]
___
*[src/main/proto/wfa/measurement/config/public_api_protocol_configs.proto, line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79#-MajcSbL6VYHnmhRInkR:-Majf1s93pRb9060rd5L:b-3x8z1w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a32f77f072388d1afba9ad4aa9e442bc2ace9d59/src/main/proto/wfa/measurement/config/public_api_protocol_configs.proto#L28)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

actually 
```
.wfa.measurement.api.v2alpha.ProtocolConfig
wfa.measurement.api.v2alpha.ProtocolConfig
measurement.api.v2alpha.ProtocolConfig
api.v2alpha.ProtocolConfig
```
all works.

.wfa means it is the root I think.

updated to `wfa.measurement.api.v2alpha.ProtocolConfig` anyway

</blockquote></details>

Oh interesting, gotcha. Thanks!

**Review by zachcwc — APPROVED** [review]
> Reviewed 11 of 18 files at r1, 1 of 4 files at r2, 7 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/79)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
