### PR TITLE
Update the CMMS to use nonces for verification of DataProvider participation.

### PR DESCRIPTION
**Pull request by SanjayVas**
See world-federation-of-advertisers/cross-media-measurement-api#62.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/proto/wfa/measurement/system/v1alpha/requisition.proto, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-MnazH8s7swTL2uPSwQf:-MnazH8s7swTL2uPSwQg:bj8kwdp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/496ce8502faa42ddd02deb4eb83442a2da6180fe/src/main/proto/wfa/measurement/system/v1alpha/requisition.proto#L57)):*
> ```protobuf
>   // The state of this `Requisition`.
>   State state = 4;
> ```

shouldn't the requisition also contain the nonce which will be set after it is fulfilled?

The duchy will use that to verify participation of all EDPs.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/proto/wfa/measurement/system/v1alpha/requisition.proto, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-MnazH8s7swTL2uPSwQf:-MnbOfXW2SMfkIkoWkWV:bemoil1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/496ce8502faa42ddd02deb4eb83442a2da6180fe/src/main/proto/wfa/measurement/system/v1alpha/requisition.proto#L57)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

shouldn't the requisition also contain the nonce which will be set after it is fulfilled?

The duchy will use that to verify participation of all EDPs.
</blockquote></details>

Yes. I'm actually working on the code to implement this, which includes that change.

**Review by SanjayVas — COMMENTED** [review]
Sorry that this is such a large PR. I don't know if there's a good way to split it up given that we have things like the integration test that really require everything to be work end-to-end.

@wangyaopw Please take a close look at the Duchy changes, as that's the code I'm least familiar with.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-:-MnldSX34zDRyexDqFOL:b-d4wd4o)* status: 0 of 67 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[build/repositories.bzl, line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mnldw_v4YNpUCrsjD3V:-Mnldw_v4YNpUCrsjD3W:b-p6165y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/build/repositories.bzl#L42)):*
> ```Starlark
>         repo = "cross-media-measurement-api",
>         sha256 = "b0f4f4de3dfaff38b725742665a9faa8a7ac4533b5f1d4efbb6c021324a0e2bc",
>         # TODO(world-federation-of-advertisers/cross-media-measurement-api#62):
> ```

Will update this once the relevant PR has been merged. Holding that off until this PR is closer to approval.
___
*[build/repositories.bzl, line 70 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mnle7kw2pRNB-UxWnWU:-Mnle7kw2pRNB-UxWnWV:b-p6165y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/build/repositories.bzl#L70)):*
> ```Starlark
>     wfa_repo_archive(
>         name = "wfa_consent_signaling_client",
>         version = "0.10.0-rc2",
> ```

Will update this once the relevant PR has been merged. Holding that off until this PR is closer to approval.
___
*[src/main/proto/wfa/measurement/system/v1alpha/requisition.proto, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-MnazH8s7swTL2uPSwQf:-MnldmHF5z2r1wx6397Y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/496ce8502faa42ddd02deb4eb83442a2da6180fe/src/main/proto/wfa/measurement/system/v1alpha/requisition.proto#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes. I'm actually working on the code to implement this, which includes that change.
</blockquote></details>

Done.

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 12 of 65 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)* status: 11 of 67 files reviewed, 8 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, line 129 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-MnluS_i4nai-XrsmoyC:-MnluS_i4nai-XrsmoyD:bcmzg1w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L129)):*
> ```
> ]
> ```
redundant `]`
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl, line 132 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-MnlvvRO65ZIh_8Zw6pS:-MnlvvRO65ZIh_8Zw6pT:bwx0b19) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl#L132)):*
> ```
> 32
> ```
use `MAX` here? maybe in the future we want to change the fingerprint to some other content, e.g, a hash concat another hash.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 185 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mnm-2kF906vDl2aTKL3:-Mnm-2kF906vDl2aTKL4:b-ny9afy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L185)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         .apply {
>           name = SystemRequisitionKey(computationId, requisitionId).toName()
>           this@apply.nonce = nonce
>         }
>         .build()
>     )
> ```
</details>

use `systemFulfillRequisitionRequest{}` ?  what is this called? kotlin dsl?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 82 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mnm2FvP6Ctl0JARH35U:-Mnm2FvP6Ctl0JARH35V:bs1trb4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L82)):*
> ```
> dataProvidersMap
> ```

where does this map come from? isn't data_providers just repeated DataProviderEntry? Does it automatically convert the list to a map if the entry contains the key and value fields?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, line 574 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mnm0kr899LdyylS3r77:-Mnm0kr93odTsVfXIfFP:b-1a9i65) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L574)):*
> ```
> 3127743798281582205L
> ```
nit: define two constants for these two values?
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, line 163 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mnm4VfX5ZiCIR9N0T3a:-Mnm4VfX5ZiCIR9N0T3b:buqciri) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L163)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> private suspend fun PrivateKeyHandle.signEncryptionPublicKey(
>   certificate: X509Certificate,
>   publicKey: EncryptionPublicKey
> ): SignedData {
>   val serialized = publicKey.toByteString()
>   val signature = checkNotNull(toJavaPrivateKey(certificate)).sign(certificate, serialized)
>   return signedData {
>     data = serialized
>     this.signature = signature
>   }
> ```
</details>


shouldn't this piece of code exist in the consent_signaling_client repo?

Well, I don't think that is what we should do, but it is just the way we are doing signing.

I would definitely love a generic PrivateKeyHandle.signBytes() methods, and all clients call it.

**Review by wangyaopw — COMMENTED** [review]
This is an awesome PR!

All changes look reasonable to me. Since the integrationTest still passes, I am pretty confident that everything works as expected.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-:-MnmASeHDuHRmHRd2E4M:b-ybvji9)* status: 11 of 67 files reviewed, 8 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)* status: 11 of 67 files reviewed, 8 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, line 129 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-MnluS_i4nai-XrsmoyC:-MnmAbqL4PdqxNV1MFAy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L129)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> ]
> ```
redundant `]`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl, line 132 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-MnlvvRO65ZIh_8Zw6pS:-MnmAjYx9lRjezcOrT9r:b-vyio83) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl#L132)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> 32
> ```
use `MAX` here? maybe in the future we want to change the fingerprint to some other content, e.g, a hash concat another hash.
</blockquote></details>

Increasing the size of a BYTES column is a [supported schema update](https://cloud.google.com/spanner/docs/schema-updates).

Note that changing the fingerprint format is something that needs to be coordinated across multiple parties, so it's not something that should be done lightly regardless.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 185 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mnm-2kF906vDl2aTKL3:-MnmCVbm28HjSFgxHM9d:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L185)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>         .apply {
>           name = SystemRequisitionKey(computationId, requisitionId).toName()
>           this@apply.nonce = nonce
>         }
>         .build()
>     )
> ```
use `systemFulfillRequisitionRequest{}` ?  what is this called? kotlin dsl?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 82 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mnm2FvP6Ctl0JARH35U:-MnmCZjeBAuDYuAyN-je:bm24f84) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L82)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> dataProvidersMap
> ```

where does this map come from? isn't data_providers just repeated DataProviderEntry? Does it automatically convert the list to a map if the entry contains the key and value fields?

</blockquote></details>

It's a repeated field in the public API, but declared as an actual map field in the internal API. We can't use a map on the public API due to needing to annotate key as a resource name.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, line 163 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mnm4VfX5ZiCIR9N0T3a:-MnmD5K_7tXXJINDyPe6:blztbox) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L163)):*
> I would definitely love a generic PrivateKeyHandle.signBytes() methods, and all clients call it.

This now exists in common-jvm using a separate `SigningKeyHandle` type, but consent-signaling-client hasn't yet been updated to use it. Kyle should be handling that when he's back. This is placeholder code until then.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)* status: 11 of 67 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl, line 132 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-MnlvvRO65ZIh_8Zw6pS:-MnmGQp_B9g0z7C2hYAn:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computations.sdl#L132)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Increasing the size of a BYTES column is a [supported schema update](https://cloud.google.com/spanner/docs/schema-updates).

Note that changing the fingerprint format is something that needs to be coordinated across multiple parties, so it's not something that should be done lightly regardless.
</blockquote></details>

sg
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 82 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mnm2FvP6Ctl0JARH35U:-MnmG_gV2NOZYmwMUN_m:b-w6t8v9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L82)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's a repeated field in the public API, but declared as an actual map field in the internal API. We can't use a map on the public API due to needing to annotate key as a resource name.
</blockquote></details>

oh, yep, this is the internal service
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, line 163 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mnm4VfX5ZiCIR9N0T3a:-MnmHEDX91fZX75dJV61:b-eeljl8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L163)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I would definitely love a generic PrivateKeyHandle.signBytes() methods, and all clients call it.

This now exists in common-jvm using a separate `SigningKeyHandle` type, but consent-signaling-client hasn't yet been updated to use it. Kyle should be handling that when he's back. This is placeholder code until then.
</blockquote></details>

add a TODO? you can assign to me

"Use consent signaling client library when it is updated"

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 51 of 65 files at r3, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)* status: 66 of 67 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, line 163 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mnm4VfX5ZiCIR9N0T3a:-MnmPrYd3fsxsO1QYTOr:b-wnirpl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73b1093482942fbf0d46beef2a7cbcfaa215029c/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L163)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

add a TODO? you can assign to me

"Use consent signaling client library when it is updated"
</blockquote></details>

Done.

Note that
1. The person referenced in a TODO is not necessarily an assignee, just someone with context.
2. It's not actually a statement to use the consent signaling library, but rather to use SigningKeyHandle. Whether the function exists in that library vs. this one is a separate point. Using SigningKeyHandle implies having to switch to SigningKeyStore.

**Review by SanjayVas — COMMENTED** [review]
@stevenwarejones This PR touches a little bit of everything. You've already seen the public API changes in the other PR. I'd recommend starting with the system API proto changes, then the internal API proto changes, then the rest.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-:-MnmQcgs94EOV2kDckes:bvvav3j)* status: 66 of 67 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 61 of 65 files at r3, 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, line 137 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mo-XddjDYY5QPaHJ1Pb:-Mo-XddjDYY5QPaHJ1Pc:b-a9p88e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e4cb80c5e00b4a333b1172f4fa0c285b86edf182/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L137)):*
> ```Kotlin
>         V2AlphaEncryptionPublicKey.Format.TINK_KEYSET -> EncryptionPublicKey.Format.TINK_KEYSET
>         V2AlphaEncryptionPublicKey.Format.FORMAT_UNSPECIFIED ->
>           EncryptionPublicKey.Format.FORMAT_UNSPECIFIED
> ```

why aren't we throwing an error here?
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 67 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mo-_88aExKIA2z2KuJm:-Mo-_88aExKIA2z2KuJn:b-l9iugp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e4cb80c5e00b4a333b1172f4fa0c285b86edf182/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L67)):*
> ```Kotlin
>           "Resource name unspecified or invalid."
>         }
>       grpcRequire(header.nonce != 0L) { "nonce unspecified" }
> ```

is it better to check against `ByteString.EMPTY`?
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, line 167 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mo-_RbsCj9FdcO7L-NK:-Mo-_RbsCj9FdcO7L-NL:b-wk94co) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e4cb80c5e00b4a333b1172f4fa0c285b86edf182/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L167)):*
> ```Kotlin
>  * TODO(@wangyaopw): Switch this to use SigningKeyHandle.
>  */
> private suspend fun PrivateKeyHandle.signEncryptionPublicKey(
> ```

shouldn't this go in common-jvm?
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 328 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mo-_ifHC3qFOeEU-2AB:-Mo-_ifI4mOD6YfS1Cnj:b-g3ep72) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e4cb80c5e00b4a333b1172f4fa0c285b86edf182/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L328)):*
> ```Kotlin
>         measurementPublicKeyBuilder.apply {
>           format = EncryptionPublicKey.Format.TINK_KEYSET
>           // TODO(@corbantek): Set to a Tink keyset in order to use real encryption.
> ```

this TODO needs to get changed to someone else probably

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)* status: 66 of 67 files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, line 137 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mo-XddjDYY5QPaHJ1Pb:-Mo-dSTs5T0BMzyHygeo:b-r6crq1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e4cb80c5e00b4a333b1172f4fa0c285b86edf182/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L137)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why aren't we throwing an error here?
</blockquote></details>

This function doesn't have enough context to know whether this is an error or whether the field being unspecified is okay. It's just concerned with doing an accurate conversion.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 67 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mo-_88aExKIA2z2KuJm:-Mo-dlUWBuGH_VYK7kee:b-vqzsm7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e4cb80c5e00b4a333b1172f4fa0c285b86edf182/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L67)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is it better to check against `ByteString.EMPTY`?
</blockquote></details>

`nonce` is a 64-bit integer, not bytes.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, line 167 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mo-_RbsCj9FdcO7L-NK:-Mo-dykTBl5GB_IHPYrI:bwjojp2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e4cb80c5e00b4a333b1172f4fa0c285b86edf182/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L167)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't this go in common-jvm?
</blockquote></details>

This is temporary, hence the TODO.

It should probably actually go in consent-signaling-client since it's referencing a specific API message. All our signature code needs to be updated to use SigningKeyStore/SigningKeyHandle though.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, line 328 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332#-Mo-_ifHC3qFOeEU-2AB:-Mo-evue3RPQS4bQfTd3:br6a59u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e4cb80c5e00b4a333b1172f4fa0c285b86edf182/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L328)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this TODO needs to get changed to someone else probably
</blockquote></details>

Done.

Note that the person referenced by a TODO is not necessarily the person who needs to make the change, but rather the person with appropriate context should someone have a question about it. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#todos

**Comment by SanjayVas** [comment]
@stevenwarejones Friendly ping that this and the corresponding https://github.com/world-federation-of-advertisers/consent-signaling-client/pull/29 are still pending your review.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)* status: 59 of 67 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 53 of 65 files at r3, 3 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 6 of 7 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
