### PR TITLE
Implement Kingdom Internal MeasurementLogEntriesService

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiNhGsxBApWhGsxSGVU:-MiNhGsxBApWhGsxSGVV:b-v8n4mg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b83293ffcca876619e5bc765c62515c500f2af6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt#L37)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     if (request.measurementLogEntryDetails.error.type ==
>         MeasurementLogEntry.ErrorDetails.Type.PERMANENT
>     ) {
>       failGrpc(Status.INVALID_ARGUMENT) {
>         "MeasurementLogEntries Service does not support PERMANENT errors, " +
>           "use FailComputationParticipant instead."
>       }
>     }
> ```
</details>

`TYPE_UNSPECIFIED` also should fail.

Maybe use `grpcRequire(type== TRANSIENT)`. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt, line 95 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiNigxh17qmU3x07pVt:-MiNigxh17qmU3x07pVu:byhuz3q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b83293ffcca876619e5bc765c62515c500f2af6/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L95)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     val measurement =
>       population.createMeasurement(
>         measurementsService,
>         measurementConsumer,
>         "measurement 1",
>         dataProvider
>       )
> ```
</details>


I guess we don't need to create a measurement B to test `measurement A not found`. Just directly call `createDuchyMeasurementLogEntry` and assert failure.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt, line 135 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiNj9nh5geo7j8_3A16:-MiNj9nh5geo7j8_3A17:bbczwsu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b83293ffcca876619e5bc765c62515c500f2af6/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L135)):*
> ```
> // WrongID
> ```
delete the comment, the ID is correct.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt, line 153 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiNjKnd0aWzoO4C9-al:-MiNjKnd0aWzoO4C9-am:bcbacjq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b83293ffcca876619e5bc765c62515c500f2af6/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L153)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>     val measurementConsumer = population.createMeasurementConsumer(measurementConsumersService)
>     val externalMeasurementConsumerId = measurementConsumer.externalMeasurementConsumerId
>     val dataProvider = population.createDataProvider(dataProvidersService)
>     val measurement =
>       population.createMeasurement(
>         measurementsService,
>         measurementConsumer,
>         "measurement 1",
>         dataProvider
>       )
> ```
</details>


same here. Just call the method directly, and assert the failure. You don't even need to set the computationId and duchyId in the request, since checking the error TYPE is the first line of the code.

We only include minimum lines of code to make the test work.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt, line 225 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiNkLoZCTJcJKTRMcMs:-MiNkLoZCTJcJKTRMcMt:b3k3273) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b83293ffcca876619e5bc765c62515c500f2af6/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L225)):*
> ```
>  this.
> ```

nit: these three `.this` are not necessary I think.

also recommend setting the fields by their order in the proto definition.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiNhGsxBApWhGsxSGVU:-MiRESWP25Q_QY_5otFo:bakkrnq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b83293ffcca876619e5bc765c62515c500f2af6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt#L37)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     if (request.measurementLogEntryDetails.error.type ==
>         MeasurementLogEntry.ErrorDetails.Type.PERMANENT
>     ) {
>       failGrpc(Status.INVALID_ARGUMENT) {
>         "MeasurementLogEntries Service does not support PERMANENT errors, " +
>           "use FailComputationParticipant instead."
>       }
>     }
> ```
`TYPE_UNSPECIFIED` also should fail.

Maybe use `grpcRequire(type== TRANSIENT)`. 
</blockquote></details>

much better, thanks!
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt, line 95 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiNigxh17qmU3x07pVt:-MiRDp_v5AmQaVIJw5tQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b83293ffcca876619e5bc765c62515c500f2af6/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L95)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     val measurement =
>       population.createMeasurement(
>         measurementsService,
>         measurementConsumer,
>         "measurement 1",
>         dataProvider
>       )
> ```

I guess we don't need to create a measurement B to test `measurement A not found`. Just directly call `createDuchyMeasurementLogEntry` and assert failure.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt, line 135 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiNj9nh5geo7j8_3A16:-MiRDeNj8YPVMJjjzTjk:b-il4n3s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b83293ffcca876619e5bc765c62515c500f2af6/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L135)):*
> ```
> MeasurementLogEntry fails for miss
> ```
thanks 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt, line 153 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiNjKnd0aWzoO4C9-al:-MiRE8uY1NH_LMlVITne:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b83293ffcca876619e5bc765c62515c500f2af6/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L153)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     val measurementConsumer = population.createMeasurementConsumer(measurementConsumersService)
>     val externalMeasurementConsumerId = measurementConsumer.externalMeasurementConsumerId
>     val dataProvider = population.createDataProvider(dataProvidersService)
>     val measurement =
>       population.createMeasurement(
>         measurementsService,
>         measurementConsumer,
>         "measurement 1",
>         dataProvider
>       )
> ```

same here. Just call the method directly, and assert the failure. You don't even need to set the computationId and duchyId in the request, since checking the error TYPE is the first line of the code.

We only include minimum lines of code to make the test work.
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiNhGsxBApWhGsxSGVU:-MiRy-ms9JhOe1m8KSTJ:b-n1nj9y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b83293ffcca876619e5bc765c62515c500f2af6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt#L37)):*
> ```
>  MeasurementLogEntry.ErrorDetails.Type.TRANSIENT
> ```
nit: I would just
```
import  org.wfanet.measurement.internal.kingdom.MeasurementLogEntry.ErrorDetails.Type.TRANSIENT
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: all files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiNhGsxBApWhGsxSGVU:-MiTEiN6AsDrcZFMA97x:bowla0k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b83293ffcca876619e5bc765c62515c500f2af6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt#L37)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  MeasurementLogEntry.ErrorDetails.Type.TRANSIENT
> ```
nit: I would just
```
import  org.wfanet.measurement.internal.kingdom.MeasurementLogEntry.ErrorDetails.Type.TRANSIENT
```
</blockquote></details>

I personally wouldn't. I'd at most import ErrorDetails. The choice is yours, just making it clear that there are differing opinions :)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiTKHjH8RlwhH-sN3Dr:-MiTKHjH8RlwhH-sN3Ds:b-yyi07o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f8367197a886e65919190b09028eff69b531498/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt#L48)):*
> ```Kotlin
> 
>     val measurementResult =
>       MeasurementReader(Measurement.View.DEFAULT)
> ```

Don't read an entire Measurement just for this! That does joins/subqueries you don't need here. You should only do that when you actually need to return a `Measurement`.

If all you need to do is to get the internal IDs, that's a really simple query which should efficiently use external ID indexes underneath.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt, line 95 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiTNBELBSObyWGqhb_G:-MiTNBELBSObyWGqhb_H:b-u4yvj5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f8367197a886e65919190b09028eff69b531498/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt#L95)):*
> ```
> create
> ```
nit: use `insert` for these internal methods that just buffer an insert mutation. `create` implies the larger process (which is what this writer does on `execute`).
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt, line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiTNekQ0jAwWLCm8YZp:-MiTNekQ0jAwWLCm8YZq:bvwc3tn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f8367197a886e65919190b09028eff69b531498/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt#L99)):*
> ```
> DuchyMeasurementLogEntry
> ```
Returning this partial entity from an insert operation is misleading, given that this method doesn't actually return anything read from the DB. `runTransaction` can build the transaction result on its own.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt, line 167 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiTOuRh4onXOse0B0-R:-MiTOuRh4onXOse0B0-S:bqce889) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f8367197a886e65919190b09028eff69b531498/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L167)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     assertThat(exception)
>       .hasMessageThat()
>       .contains(
>         "MeasurementLogEntries Service only supports TRANSIENT errors, " +
>           "use FailComputationParticipant instead."
>       )
> ```
</details>

nit: I'm not a big fan of verifying the entire error message string, as those strings are intended to be human-readable and should be freely-changeable. If you must, just verify what you need to differentiate between errors that have the same code.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiNhGsxBApWhGsxSGVU:-MiW28Yw8wB1a1PKrNl4:bppllfo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b83293ffcca876619e5bc765c62515c500f2af6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I personally wouldn't. I'd at most import ErrorDetails. The choice is yours, just making it clear that there are differing opinions :)
</blockquote></details>

I don't have a preference, went with Yao's recommendation this time since he brought it up :) 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiTKHjH8RlwhH-sN3Dr:-MiW8bpM-HGyAHUF1rVU:bkxrdxl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f8367197a886e65919190b09028eff69b531498/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't read an entire Measurement just for this! That does joins/subqueries you don't need here. You should only do that when you actually need to return a `Measurement`.

If all you need to do is to get the internal IDs, that's a really simple query which should efficiently use external ID indexes underneath.
</blockquote></details>

 I agree. there is one hiccup though, measurementlogEntry needs externalMeasurementConsumerId and that is not in the Measurements table so there has to be a join to MeasurementConsumers and thus I can't use transactionContext.readRowUsingIndex. Would you prefer I write a simple read query with join here or would you like to keep reading the measurement to keep this simple?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt, line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiTNekQ0jAwWLCm8YZp:-MiW7rVU8am8uiWkO_2Y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f8367197a886e65919190b09028eff69b531498/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> DuchyMeasurementLogEntry
> ```
Returning this partial entity from an insert operation is misleading, given that this method doesn't actually return anything read from the DB. `runTransaction` can build the transaction result on its own.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiTKHjH8RlwhH-sN3Dr:-MiXVWZ926FvmoomFjwl:bnai2zd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f8367197a886e65919190b09028eff69b531498/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt#L48)):*
> so there has to be a join to MeasurementConsumers and thus I can't use transactionContext.readRowUsingIndex.

Yes, that's why I mentioned doing a simple query rather than an index read.

> Would you prefer I write a simple read query with join here or would you like to keep reading the measurement to keep this simple?

Yes, as doing that query here is just as simple. Doing the full MeasurementReader query and building a Measurement is overkill, and I assume the performance impact of those extra joins/subqueries would be significant.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-MiTKHjH8RlwhH-sN3Dr:-Mia2QcwBc-PT8K10yDJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f8367197a886e65919190b09028eff69b531498/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> so there has to be a join to MeasurementConsumers and thus I can't use transactionContext.readRowUsingIndex.

Yes, that's why I mentioned doing a simple query rather than an index read.

> Would you prefer I write a simple read query with join here or would you like to keep reading the measurement to keep this simple?

Yes, as doing that query here is just as simple. Doing the full MeasurementReader query and building a Measurement is overkill, and I assume the performance impact of those extra joins/subqueries would be significant.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @wangyaopw, and @zachcwc)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)

**Review by uakyol — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)

**Review by uakyol — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)

**Review by uakyol — COMMENTED** [review]
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by uakyol — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by wangyaopw — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237#-:-MigVXZc1U7bhYnTNTQA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/237)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Comment by SanjayVas** [comment]
This is for #103.

**Pull request merged**
