### PR TITLE
Add StreamExchanges class to stream Exchanges based on Filters

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 363 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128#-MdJJ23TEr6ZkTJTr5FD:-MdJJ23TEr6ZkTJTr5FE:bgp16j6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66a9541bc522f9f4a3e2a64bf0a31585adaeb294/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L363)):*
> ```Kotlin
>     write(
>       Mutation.newInsertBuilder("RecurringExchanges")
>         .set("RecurringExchangeId")
> ```

Preferred syntax: `.set("State" to state)` (Sanjay added some helpers for this)
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamExchangesTest.kt, line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128#-MdJJPh2AJR7mOiDmYNw:-MdJJPh2AJR7mOiDmYNx:b-x0fyiv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66a9541bc522f9f4a3e2a64bf0a31585adaeb294/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamExchangesTest.kt#L121)):*
> ```Kotlin
>       fun filter(date: Date) = streamExchangesFilter(nextExchangeDate = date)
> 
>       ProtoTruth.assertThat(executeToList(filter(DATE1), 10))
> ```

Please add an import for `assertThat` itself.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 363 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128#-MdJJ23TEr6ZkTJTr5FD:-MdJQCOT1il9RDvPMgP1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66a9541bc522f9f4a3e2a64bf0a31585adaeb294/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L363)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Preferred syntax: `.set("State" to state)` (Sanjay added some helpers for this)
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamExchangesTest.kt, line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128#-MdJJPh2AJR7mOiDmYNw:-MdJQECvCei6DtRNvmWx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66a9541bc522f9f4a3e2a64bf0a31585adaeb294/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamExchangesTest.kt#L121)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please add an import for `assertThat` itself.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/exchange.sdl, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128#-MdJuwWgATqHjruX-Qzh:-MdJuwWgATqHjruX-Qzi:b-kw1au9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e18664f4208aed850d5a14adede47e8d643fb9ce/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/exchange.sdl#L57)):*
> ```
> 
>   -- RecurringExchange.State enum as int.
>   State                         INT64 NOT NULL,
> ```

shouldn't we be using strings? seems like it will be hard to debug in the future if the enums change

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/exchange.sdl, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128#-MdJuwWgATqHjruX-Qzh:-MdTGBS1D0hyPdDljrI3:bsy2xs1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e18664f4208aed850d5a14adede47e8d643fb9ce/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/exchange.sdl#L57)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't we be using strings? seems like it will be hard to debug in the future if the enums change
</blockquote></details>

This was discussed in slack channel.

**Review by efoxepstein — APPROVED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
