### PR TITLE
Convert uncaught Exceptions to StatusException

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664)

### CODE REVIEW

**Comment by renjiezh** [comment]
@SanjayVas this is a draft for the exception vulnerability. I will go through public services and do two things:
1. Wrap internal calls with try-catch blocks.
2. Wrap parse functions to throw StatusException.
Could you share the thoughts and I can apply it to all services?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt` line 91 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664#-N9YNQnwCfPrVZgJ5i8y:-N9YNQnwCfPrVZgJ5i8z:b70dcpd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/179b271dc1b98e47fc21f2c917eda1537ae0d29f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L91)):*
> ```Kotlin
>       try {
>         internalAccountsStub.createAccount(internalCreateAccountRequest)
>       } catch (ex: StatusException) {
> ```

1. Don't try to catch arbitrary throwables. Anything that isn't a gRPC exception will get converted to an UNKNOWN with no details automatically.
2. Don't rethrow gRPC exceptions (StatusException) from service calls. This is actually what leaks the information from the internal server, and is also misleading as it makes it appear that the internal server error is the public server error.

The correct behavior is as follows:
* Catch StatusException
* If we know what the external status for this exception should be, throw that specific status as a StatusRuntimeException.
* If we don't know, throw an UNKNOWN status as a StatusRuntimeException.

In either case, include the original exception as the cause of the StatusRuntimeException. This way we have the opportunity for interceptors to include the information in server debug logs.



_Code quote:_
```Kotlin
      } catch (ex: StatusException) {
        throw ex
      } catch (ex: Throwable) {
        failGrpc(Status.UNKNOWN) { "Unknown exception from internal createAccount." }
      }
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt` line 91 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664#-N9YNQnwCfPrVZgJ5i8y:-N9YjoDT3JwEAOdLxlVY:b-lkarzc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/179b271dc1b98e47fc21f2c917eda1537ae0d29f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L91)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. Don't try to catch arbitrary throwables. Anything that isn't a gRPC exception will get converted to an UNKNOWN with no details automatically.
2. Don't rethrow gRPC exceptions (StatusException) from service calls. This is actually what leaks the information from the internal server, and is also misleading as it makes it appear that the internal server error is the public server error.

The correct behavior is as follows:
* Catch StatusException
* If we know what the external status for this exception should be, throw that specific status as a StatusRuntimeException.
* If we don't know, throw an UNKNOWN status as a StatusRuntimeException.

In either case, include the original exception as the cause of the StatusRuntimeException. This way we have the opportunity for interceptors to include the information in server debug logs.
</blockquote></details>

Thanks for the instruction.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664)* status: 4 of 13 files reviewed, 2 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt` line 237 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664#-N9n7RcnCQomRX4P9119:-N9n7RcnCQomRX4P911A:b-b85d1g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e56904f1e094b3d71549a167f70d935a8809c637/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L237)):*
> ```Kotlin
>           Status.ALREADY_EXISTS ->
>             failGrpc(Status.ALREADY_EXISTS, ex) {
>               "Certificate with the subject key identifier (SKID) already exists."
> ```

nit: we don't technically know this is the case without inspecting the exception
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt` line 350 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664#-N9n7rlA29g8VYDXmEXz:-N9n7rlA29g8VYDXmEY-:bszu55z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e56904f1e094b3d71549a167f70d935a8809c637/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L350)):*
> ```Kotlin
>       } catch (ex: StatusRuntimeException) {
>         when (ex.status) {
>           Status.NOT_FOUND -> failGrpc(Status.NOT_FOUND, ex) { ex.message ?: "Not found" }
> ```

Is this safe? If the exception returned by the internal service contains the context, then this may be leaking info such as external IDs in integer format (as opposed to encoded "API ID" format)

If we make sure that we exclude context information from the message of internal exceptions, then it's generally fine to pass on this message.



_Code quote:_
```Kotlin
ex.message
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664)* status: 4 of 13 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt` line 237 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664#-N9n7RcnCQomRX4P9119:-N9n9nHmBITARHTUc93J:b-osbenb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e56904f1e094b3d71549a167f70d935a8809c637/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L237)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: we don't technically know this is the case without inspecting the exception
</blockquote></details>

The internal API will throw ALREADY_EXISTS only with message "subject key already exists". Do we want to make the message more vague like `Certificate already exists` on behalf of public API?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt` line 350 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664#-N9n7rlA29g8VYDXmEXz:-N9n8VlB1TwhN4BuxPzY:bcq9ayj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e56904f1e094b3d71549a167f70d935a8809c637/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L350)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this safe? If the exception returned by the internal service contains the context, then this may be leaking info such as external IDs in integer format (as opposed to encoded "API ID" format)

If we make sure that we exclude context information from the message of internal exceptions, then it's generally fine to pass on this message.
</blockquote></details>

For all usages of `ex.message`, I have censored possible cases from the internal api. They are scoped into two or three categories whose messages don't have sensitive info.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 9 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt` line 237 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664#-N9n7RcnCQomRX4P9119:-NA5OWul4z2Abwlx2OzD:bywhc7i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e56904f1e094b3d71549a167f70d935a8809c637/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L237)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

The internal API will throw ALREADY_EXISTS only with message "subject key already exists". Do we want to make the message more vague like `Certificate already exists` on behalf of public API?
</blockquote></details>

No, giving the info that it's the SKID that already exists is better.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @stevenwarejones)

**Pull request merged**
