### PR TITLE
Fail associated active measurements when certificate is revoked

### PR DESCRIPTION
**Pull request by tristanvuong2021**
…ked.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-Mm081EJBCxqGiuuDfo1:-Mm081EJBCxqGiuuDfo2:b-mhf6iu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c20627faa8ca3eba01ea8d7ad79fbf0bd12c1eab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L37)):*
> ```
>  * TODO(world-federation-of-advertisers/cross-media-measurement#305) : Consider cancelling all
>  * associated active measurements if a certificate is revoked
> ```

The TODO is not fully completed yet. This PR only deal with the revocation of MC certificate. Revocation of EDP cert and duchy cert should also cancel the measurement.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-Mm08R3z19o9W4WpT9fN:-Mm08R3z19o9W4WpT9fO:b-i973k4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/520a51daf728105691417a03b3c262e85f1dd08d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L101)):*
> ```
> 10000
> ```
why hardcoded 10000 here?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 108 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-Mm08pBsDNnyyzxkN3c2:-Mm08pBsDNnyyzxkN3c3:b70nbsd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/520a51daf728105691417a03b3c262e85f1dd08d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L108)):*
> ```
> set("CertificateId" to certificateResult.certificateId.value)
> ```

no need for this. CertificateId is not a key and its value doesn't change.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-Mm093IO1v_-jO7XrMCi:-Mm093IO1v_-jO7XrMCj:b5exe8m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/520a51daf728105691417a03b3c262e85f1dd08d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L109)):*
> ```
> CANCELLED
> ```
we also need to add a log to the measurement. Otherwise there is no way to know why it is cancelled.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-Mm093IO1v_-jO7XrMCi:-Mm0JStt4W8MNsPb2X15:bjltbej) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/520a51daf728105691417a03b3c262e85f1dd08d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L109)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> CANCELLED
> ```
we also need to add a log to the measurement. Otherwise there is no way to know why it is cancelled.
</blockquote></details>

How do we handle logging for things like this? Do I create a MeasurementLogEntry for each cancellation.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 114 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-Mm4DlD56czIfHLCmEwB:-Mm4P6ci0_G5gMsaBq3Y:b-o2foad) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b75267225cee56d88d77a158ba506eb06216fc2b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L114)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also check that the certificate is within its validity period. You'll probably want to rename the error code to`CERTIFICATE_IS_INVALID`.
</blockquote></details>

Just saw this, working on this for the separate PR I just made.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326)* status: 1 of 15 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-Mm093IO1v_-jO7XrMCi:-MmAQBFK05iY0WdzC6tl:bn2phk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/520a51daf728105691417a03b3c262e85f1dd08d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L109)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> How do we handle logging for things like this? Do I create a MeasurementLogEntry for each cancellation.

We do want to add measurement log entries for more cases like this, but you don't need to do it right now.

> Should we add a new field in the internal measurement and public Api measurement which can tell the client why a measurement is cancelled or failed?

We don't strictly need it for FAILED as you can determine that from the child ComputationParticipant and Requisition states. We may need it for CANCELLED , as you don't know whether the MC cancelled manually or the certificate was revoked. You could inspect the certificate to see, but that's not entirely obvious. Additionally, the MC could have cancelled manually *and then* revoked the certificate. In that case, the certificate validity is actually irrelevant.

I guess we should add a `CancellationCause` enum and corresponding field that's only set when the state is `CANCELLED`. The values would be something like `CERTIFICATE_REVOKED` and `MANUAL`. We'd need to set the latter on `CancelMeasurement`.

You may want to split this up into multiple PRs. e.g.
1. Preventing creation with invalid certificate
2. Adding cancellation cause.
3. Cancelling on certificate revocation

where 2 and 3 could possibly be combined.
</blockquote></details>

we don’t have a computationParticipants service in the public API. If the measurement failed due to some issue reported by the mpc workers, the MC won’t be able to figure out the cause of the failure. Also the logs are not directly visible to the MC I guess, some human readable string message in the public measurement might be helpful.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 105 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-MmYjn2V1d9ITUUgoAMr:-MmYlXIS9j4ur_wMmwmt:b-otm4cy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ada2a1a98d0295c7c7513f5528072a606fa16c5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L105)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what about letting MPC nodes know so they can cancel current work?
</blockquote></details>

@wangyaopw Will Duchies pick this up when polling for Measurement updates?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @SanjayVas and @wangyaopw)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-Mm093IO1v_-jO7XrMCi:-MnCvgiu7S8gCs5a87TC:b4rm0ff) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/520a51daf728105691417a03b3c262e85f1dd08d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L109)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

sure. That can be a separate PR
</blockquote></details>

@tristanvuong2021 added this in world-federation-of-advertisers/cross-media-measurement-api#64. This PR should be changed to use FAILED instead of CANCELLED and set the Failure. This includes making sure that Failure is persisted and read back.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-Mm093IO1v_-jO7XrMCi:-MnDK0JICC6AJN247Bq7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/520a51daf728105691417a03b3c262e85f1dd08d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L109)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@tristanvuong2021 added this in world-federation-of-advertisers/cross-media-measurement-api#64. This PR should be changed to use FAILED instead of CANCELLED and set the Failure. This includes making sure that Failure is persisted and read back.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 44 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-MnWlsek4_csUqeujmzx:-MnWlsel-WMpqZukizJQ:b-4agwi1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb3c72512270778dab3f74cb359bd9e4da683953/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L44)):*
> ```
>  * TODO(world-federation-of-advertisers/cross-media-measurement#305) : Consider failing all
>  * associated active measurements if a certificate is revoked
> ```
Doesn't this PR take care of this TODO?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 475 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-MnWm5cJ57sY7qqGZ0Rv:-MnWm5cK9rOQHg8xG--a:bc4go80) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb3c72512270778dab3f74cb359bd9e4da683953/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L475)):*
> ```
> measurementOne
> ```
`measurementTwo` ? Technically the same content, but should be clear.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 475 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-MnWm5cJ57sY7qqGZ0Rv:-MnWwPPh463NJfr_YkFD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a54dda5aa560ee7b2f16a6ef8d1849239956c12/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L475)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> measurementOne
> ```
`measurementTwo` ? Technically the same content, but should be clear.
</blockquote></details>

Done.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 44 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-MnWlsek4_csUqeujmzx:-MnX-CyQ1lZ-BEuA6tDY:b-nuawse) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a54dda5aa560ee7b2f16a6ef8d1849239956c12/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>  * TODO(world-federation-of-advertisers/cross-media-measurement#305) : Consider failing all
>  * associated active measurements if a certificate is revoked
> ```
Doesn't this PR take care of this TODO?
</blockquote></details>

I think I deleted it at one point, but @wangyaopw mentioned something about other things to add later so we should leave it. I can't find this comment though, so maybe it didn't happen.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, line 44 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326#-MnWlsek4_csUqeujmzx:-MnX8Ou28XGpBLEcXIGO:b-w95x0b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a54dda5aa560ee7b2f16a6ef8d1849239956c12/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L44)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I think I deleted it at one point, but @wangyaopw mentioned something about other things to add later so we should leave it. I can't find this comment though, so maybe it didn't happen.
</blockquote></details>

The comment was `The TODO is not fully completed yet. This PR only deal with the revocation of MC certificate. Revocation of EDP cert and duchy cert should also cancel the measurement.`

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 3 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by tristanvuong2021 — COMMENTED** [review]
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/326)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
