### PR TITLE
Delete non-necessary test harness interfaces.

### PR DESCRIPTION
**Pull request by wangyaopw**
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Fuserstory%2F606023913139

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/203)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
Apparently, github is not able to smartly figure out the actual diff of such PR.

There is really not too many lines of changes. I deleted the XXXImpl, and replaced XXX with code in XXXImpl. 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/203#-:-MhQN-qZ5dQQ5Yf5ZMZj:b-flcss2)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @SanjayVas)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/203)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/203)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek)

**Review by corbantek — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/203)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 181 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/203#-MhUPY_6B9Cg0jBvIAZP:-MhUPY_72W7UfyFQCzpe:b4lhi5e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b545f2538fc7025548b71fc93ea3476d743ed21/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L181)):*
> ```Kotlin
>           ::fakeGetHybridCryptorForCipherSuite
>         )
>       Result.parseFrom(signedResult.data)
> ```

Should you also verify the signature of the Result here too?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/203)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, line 181 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/203#-MhUPY_6B9Cg0jBvIAZP:-MhUVUnS-kKWfeExvFIz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b545f2538fc7025548b71fc93ea3476d743ed21/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L181)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Should you also verify the signature of the Result here too?
</blockquote></details>

Done.

**Review by corbantek — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/203)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
