### PR TITLE
refactor: verify liquid legion sketch params when computing variances.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1860)

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1860)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/LiquidLegions.kt` line 131 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1860#-O9L2ni78otOART6GhJi:-O9M1503-3xhJ1rY5Wfd:bo2fdmv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50f98c3ef9c82a826ccbddbb1099ba59e7653ba3/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/LiquidLegions.kt#L131)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you check if there are other functions in this file (directory) that need these kinds of checks?

Let's take the opportunity to double check and harden this entire stats module.

I know the noise correction stuff is high on your list of priorities, so if you think this is going to take too much time, maybe file an Issue and come back to it in December?
</blockquote></details>

I've gone through the stats directory and added bound checks.
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt` line 505 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1860#-O9L2g0HEAioLz6zgrFr:-O9M13TZCxhNbjGqR6nd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50f98c3ef9c82a826ccbddbb1099ba59e7653ba3/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt#L505)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you update all of the other arg checks in this file to include the argument in the message (e.g. the one right above this one).
</blockquote></details>

Done.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1860)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1860)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1860)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/HonestMajorityShareShuffle.kt` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1860#-O9MDuaXCCDZaHy3_I9z:-O9MDuaXCCDZaHy3_IA-:bv0is7e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d2b010d3d4f02f7bf6e14b990482d7c17427d756/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/HonestMajorityShareShuffle.kt#L46)):*
> ```Kotlin
>     }
>     require(reachNoiseVariance >= 0) {
>       "Reach noise variance must be a non-negative value, but got ${reachNoiseVariance}."
> ```

nit: `$reachNoiseVariance`

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1860)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/HonestMajorityShareShuffle.kt` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1860#-O9MDuaXCCDZaHy3_I9z:-O9MFGpU6-hrbkeHV-26:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d08fc43e24c6654ed7b35ce4e6421222da368cb7/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/HonestMajorityShareShuffle.kt#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit: `$reachNoiseVariance`
</blockquote></details>

Done.

**Review by ple13 — COMMENTED** [review]
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1860)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
