### PR TITLE
Reporting list event group now correctly calls kingdom list event groups

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/771)

### CODE REVIEW

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/771)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/771)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/771#-NHzs5vYBRcVcDZaKdq5:-NHzs5vZDF6rr5etQJdC:bm51xrl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f62f6ba962b9ae0229349af891cf681c438ca46/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L78)):*
> ```Kotlin
>             filter = filter {
>               measurementConsumers +=
>                 MeasurementConsumerKey(principal.resourceKey.measurementConsumerId).toName()
> ```

I'm pretty sure that `principal.resourceKey` is already a v2alpha CMMS `MeasurementConsumerKey`, meaning that the resource name is already in the local variable `principalName`.

**Comment by tristanvuong2021** [comment]
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/771#-NHzs5vYBRcVcDZaKdq5:-NI-HrZ0CcVJkIez306P:b6av435) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f62f6ba962b9ae0229349af891cf681c438ca46/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm pretty sure that `principal.resourceKey` is already a v2alpha CMMS `MeasurementConsumerKey`, meaning that the resource name is already in the local variable `principalName`.
</blockquote></details>

Oh it is.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/771)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
