### PR TITLE
Fix Reader bugs when provided Ids are null

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/284)

### CODE REVIEW

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/284)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 91 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/284#-MkCl_kr2XkHwzBbzdP8:-MkCl_ks7tRgtm_GM5tk:b4cm1s3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ee530a268fab0bdf639dab9bd3c0f4fa5534b7c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L91)):*
> ```Kotlin
>         externalDataProviderId = struct.getLong("ExternalDataProviderId")
>         externalMeasurementConsumerId = struct.getLong("ExternalMeasurementConsumerId")
>         if (!struct.isNull("ProvidedEventGroupId")) {
> ```

Is there no snazzy Kotlin one-liner for this?

**Review by oliver-amzn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/284)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 91 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/284#-MkCqffQEmFUw-cdybvs:-MkD3FY2C1_GehPjH5mC:byq69o5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/196419a618c1a0832e270b9ec5c07ca29681e487/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L91)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

LGTM as is

`Struct.isNull` seems to be needed here given the methods available in`Struct`. Could use "if" as a ternary to have a single expression, but I think the line would be too big

```
providedEventGroupId = if (!struct.isNull("ProvidedEventGroupId")) struct.getString("ProvidedEventGroupId") else null
```
</blockquote></details>

Agreed, that doesn't make it better.

**Review by wangyaopw — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/284#-:-MkD9z4A16Uk6iuJpjYy:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @uakyol)

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/284)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 91 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/284#-MkCqffQEmFUw-cdybvs:-MkDZUEh3SpO42CTVbRG:b7wctkw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/196419a618c1a0832e270b9ec5c07ca29681e487/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L91)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Agreed, that doesn't make it better.
</blockquote></details>

thanks for the discussion

**Review by uakyol — COMMENTED** [review]
> Dismissed @duliomatos1 and @oliver-amzn from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/284)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Pull request merged**
