### PR TITLE
Reporting server images

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 17 files at r1, 28 of 28 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632)* status: all files reviewed, 10 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/docker/images.bzl` line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7bsTJB6GWIH0VjFVUL:-N7bsTJB6GWIH0VjFVUM:b-yegh90) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/docker/images.bzl#L110)):*
> ```Starlark
>     ),
>     struct(
>         name = "gc_reporting_data_server_image",
> ```

nit: `gcloud`



_Code quote:_
```Starlark
gc
```
___
*[`src/main/docker/images.bzl` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7bselb4ogLQyjPmAoj:-N7bselb4ogLQyjPmAok:b-hnwffp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/docker/images.bzl#L150)):*
> ```Starlark
>         name = "reporting_data_server_image",
>         image = "//src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/server:postgres_reporting_data_server_image",
>         repository = _PREFIX + "/reporting/data-server",
> ```

`repository` has no meaning for local images
___
*[`src/main/kotlin/org/wfanet/measurement/common/identity/TextprotoFileApiKeyLookup.kt` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7bt53K8nlBu2xyErDp:-N7bt53K8nlBu2xyErDq:b-mf4q1q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/kotlin/org/wfanet/measurement/common/identity/TextprotoFileApiKeyLookup.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.common.identity
> ```

nit: put this somewhere specific to reporting, e.g. as a sibling to `MeasurementConsumerServerInterceptor`.

We really shouldn't have anything in `org.wfanet.measurement.common.identity` in this repo. This is a nit because other classes with similar functionality are already there.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/BUILD.bazel` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7btYj67jzr1sNjZM8v:-N7btYj67jzr1sNjZM8w:b-14eenn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/BUILD.bazel#L22)):*
> ```Starlark
> kt_jvm_library(
>     name = "flags",
>     testonly = False,
> ```

nit: only include `testonly` attr when it doesn't match the package default
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/BUILD.bazel` line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7c-QTQ9YdyOnQzg_q3:-N7c-QTQ9YdyOnQzg_q4:b-u3vm9i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/BUILD.bazel#L27)):*
> ```Starlark
> kt_jvm_library(
>     name = "v1alpha_public_api_server",
>     srcs = ["V1alphaPublicApiServer.kt"],
> ```

nit: V1Alpha (to match how we do our enum for CMMS API version, e.g. `V2_ALPHA`)



_Code quote:_
```Starlark
V1alpha
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1alphaPublicApiServer.kt` line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7c0zmb1w_NqYT_1qwC:-N7c0zmb1w_NqYT_1qwD:blpvf2g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1alphaPublicApiServer.kt#L54)):*
> ```Kotlin
>       trustedCertCollectionFile = commonServerFlags.tlsFlags.certCollectionFile
>     )
>   val channel =
> ```

nit: explicit types where not obvious
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/service/DataServices.kt` line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7btnZ96_xHHsxySCwG:-N7btnZ96_xHHsxySCwH:b-26s75p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/service/DataServices.kt#L23)):*
> ```Kotlin
> import org.wfanet.measurement.internal.reporting.ReportsGrpcKt.ReportsCoroutineImplBase
> 
> interface DataServices {
> ```

nit: don't copy this pattern from Kingdom, as it's unnecessary

You can just declare a `Services` data class inside of `ReportingDataServer` since that's the only context where it should be used
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/gcloud/postgres/server/BUILD.bazel` line 7 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7bzy7sCpB3VoDEbhtG:-N7bzy7sCpB3VoDEbhtH:b-k6fvp4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/kotlin/org/wfanet/measurement/reporting/deploy/gcloud/postgres/server/BUILD.bazel#L7)):*
> ```Starlark
> kt_jvm_library(
>     name = "gcloud_postgres_reporting_data_server",
>     srcs = ["GcloudPostgresReportingDataServer.kt"],
> ```

nit: GCloud



_Code quote:_
```Starlark
Gcloud
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/gcloud/postgres/server/GcloudPostgresReportingDataServer.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7c-4QA9p8XCDdOQqmu:-N7c-4QA9p8XCDdOQqmv:bscl5cv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/kotlin/org/wfanet/measurement/reporting/deploy/gcloud/postgres/server/GcloudPostgresReportingDataServer.kt#L34)):*
> ```Kotlin
>   showDefaultValues = true
> )
> class PostgresReportingDataServer : ReportingDataServer() {
> ```

Class name should match file name.



_Code quote:_
```Kotlin
PostgresReportingDataServer
```
___
*[`src/main/proto/wfa/measurement/config/reporting/measurement_consumer_to_api_key_map.proto` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7c1Etx0jItY7dAdb_S:-N7c1Etx0jItY7dAdb_T:b-nf2pa4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/proto/wfa/measurement/config/reporting/measurement_consumer_to_api_key_map.proto#L22)):*
> ```protobuf
> option java_multiple_files = true;
> 
> message MeasurementConsumerToApiKeyMap {
> ```

Follow the same pattern as `EncryptionKeyPairConfig`
e.g.

```protobuf
message MeasurementConsumerConfig {
  string api_key = 1;
  // Possibly other per-MC config fields here in the future, such as folding in the key pair mapping.
}

message MeasurementConsumerConfigs {
  map<string, MeasurementConsumerConfigs> configs_map = 1;
}
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632)* status: 12 of 34 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/docker/images.bzl` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7bselb4ogLQyjPmAoj:-N7q1n753bYuqCNSEqC5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/docker/images.bzl#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`repository` has no meaning for local images
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1alphaPublicApiServer.kt` line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7c0zmb1w_NqYT_1qwC:-N7q1rUU-TJCWzOCpfpf:bmav4y6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1alphaPublicApiServer.kt#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: explicit types where not obvious
</blockquote></details>

The type is Channel so I don't think that really helps here.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/gcloud/postgres/server/GcloudPostgresReportingDataServer.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7c-4QA9p8XCDdOQqmu:-N7q1yhnDC6B078p5sNH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/kotlin/org/wfanet/measurement/reporting/deploy/gcloud/postgres/server/GcloudPostgresReportingDataServer.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Class name should match file name.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/config/reporting/measurement_consumer_to_api_key_map.proto` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7c1Etx0jItY7dAdb_S:-N7q2-_M8ZhQsvYNqoHC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/proto/wfa/measurement/config/reporting/measurement_consumer_to_api_key_map.proto#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Follow the same pattern as `EncryptionKeyPairConfig`
e.g.

```protobuf
message MeasurementConsumerConfig {
  string api_key = 1;
  // Possibly other per-MC config fields here in the future, such as folding in the key pair mapping.
}

message MeasurementConsumerConfigs {
  map<string, MeasurementConsumerConfigs> configs_map = 1;
}
```


</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 18 of 22 files at r4, 2 of 2 files at r5, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/ReportingDataServer.kt` line 36 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7rAKtQ3sv-29UcQQdA:-N7rAKtQ3sv-29UcQQdB:b-cmhv9f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9dae0c39e3550311c145cfe8b51aa11edf9e8a93/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/ReportingDataServer.kt#L36)):*
> ```Kotlin
> 
>   companion object {
>     data class Services(
> ```

nit: define inside the class, not the companion object

Right now this is `ReportingDataServer.Companion.Services` where you probably want it to be `ReportingDataServer.Services`.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1alphaPublicApiServer.kt` line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N7c0zmb1w_NqYT_1qwC:-N7rAdfW1XWj_hkmxu0T:bht8t5i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/138757eaa9e35945f6c14a766ed0924410b94b68/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1alphaPublicApiServer.kt#L54)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The type is Channel so I don't think that really helps here.
</blockquote></details>

1. This was meant as a general comment, not just for this line.
2. It would still help, as someone reading this without an IDE can figure out what the type is just from this file without having to go look up what buildMutualTlsChannel returns.

"Obvious" above means e.g. cases where you're assigning from a constructor call or well-known factory function. Said another way, the default should be specifying a type. The type *may* be omitted when it's obvious.

I'm aware we don't do a great job of this in existing code. I'm trying to be better about catching it.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 17 files at r1, 4 of 28 files at r2, 11 of 22 files at r4, 2 of 2 files at r5, 3 of 4 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt` line 100 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N80ARbHCquZN3c6-A1_:-N80ARbHCquZN3c6-A1a:b3kre) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24e7bde9f92863f644a805aadab640740e143608/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt#L100)):*
> ```Kotlin
>       ReportingSetsService(InternalReportingSetsCoroutineStub(channel))
>         .withPrincipalsFromX509AuthorityKeyIdentifiers(principalLookup),
>       /*
> ```

?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/gcloud/postgres/server/GCloudPostgresReportingDataServer.kt` line 30 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N80AbNP1_zZqkDSO8VU:-N80AbNQ4Rta7uOedelf:b9zrhy9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24e7bde9f92863f644a805aadab640740e143608/src/main/kotlin/org/wfanet/measurement/reporting/deploy/gcloud/postgres/server/GCloudPostgresReportingDataServer.kt#L30)):*
> ```Kotlin
> /** Implementation of [ReportingDataServer] using Google Cloud Postgres. */
> @CommandLine.Command(
>   name = "GCloudPostgresReportingDataServer",
> ```

is this postgres impl specific to gcloud? Feels cloud agnostic to me.

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt` line 100 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N80ARbHCquZN3c6-A1_:-N80Tm5k5aTJ7NwpkVPb:b57zmzs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24e7bde9f92863f644a805aadab640740e143608/src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt#L100)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

?
</blockquote></details>

Removed commented out code.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/gcloud/postgres/server/GCloudPostgresReportingDataServer.kt` line 30 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632#-N80AbNP1_zZqkDSO8VU:-N80FkkF0xwbmZHzHQnE:b-2e4ogo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/24e7bde9f92863f644a805aadab640740e143608/src/main/kotlin/org/wfanet/measurement/reporting/deploy/gcloud/postgres/server/GCloudPostgresReportingDataServer.kt#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this postgres impl specific to gcloud? Feels cloud agnostic to me.
</blockquote></details>

It is. Made it more clear it is using gcloud specific flags.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632)* status: 27 of 34 files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 4 of 4 files at r13, 3 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/632)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
