### PR TITLE
Modify CreateReport to allow specifying a ReportSchedule for the Report to be associated with

### PR DESCRIPTION
**Pull request by tristanvuong2021**
I thought of a way to have the Report  created and associated with the ReportSchedule in a single transaction instead of two separate transactions, but still work the same way as before when a ReportSchedule is not involved in the Report creation.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1316)

**Review by riemanli — COMMENTED** [review]
> Reviewed 5 of 15 files at r1, 2 of 6 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1316)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 216 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1316#-NiHg8Qj0o96jNv8OImn:-NiHg8Qj0o96jNv8OImo:b-ab5i6x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/225bde9c3b62c24e9dd71a26ced2c99801de8603/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L216)):*
> ```Kotlin
>           boundStatement(
>             """
>             INSERT INTO ReportsReportSchedules
> ```

nit: Fix `ReportSchedulesReports` to `ReportsReportSchedules` in the table hierarchy in `add-report-scheduling-tables.sql` 



_Code quote:_
```Kotlin
INSERT INTO ReportsReportSchedules
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 294 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1316#-NiHhF745ckd9jD-mT8N:-NiHhF745ckd9jD-mT8O:b1pkdxa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/225bde9c3b62c24e9dd71a26ced2c99801de8603/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L294)):*
> ```Kotlin
>                 Status.NOT_FOUND.withDescription("Resource required for report creation not found.")
>               } else {
>                 if (e.message!!.contains("external_report_schedule_id")) {
> ```

nit: Use `checkNotNull`?



_Code quote:_
```Kotlin
e.message!!
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1316)* status: 10 of 16 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 294 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1316#-NiHhF745ckd9jD-mT8N:-NiLGFrE41yElaCMk9KX:b45ynyy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/225bde9c3b62c24e9dd71a26ced2c99801de8603/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L294)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

nit: Use `checkNotNull`?
</blockquote></details>

I don't think I need this check in the first place so I removed it.

**Review by riemanli — APPROVED** [review]
> Reviewed 1 of 15 files at r1, 3 of 6 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1316)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt` line 294 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1316#-NiHhF745ckd9jD-mT8N:-NiMIVu7DP5CGnxJXwSo:b-ciqdn8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/225bde9c3b62c24e9dd71a26ced2c99801de8603/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt#L294)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I don't think I need this check in the first place so I removed it.
</blockquote></details>

Just thought it might be better than `!!`. No strong opinion.

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 5 of 15 files at r1, 5 of 6 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1316)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

**Pull request merged**
