### PR TITLE
Create PanelMatchResourceSetup from Channel

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-MkhR4J08t3JRsakGsMl:-MkhR4J08t3JRsakGsMm:b-qdpgkf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56dfcb1f0b96a70a73d94d70c74949147a8dc25a/src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel#L60)):*
> ```Starlark
>     name = "data_providers_service_kt_jvm_grpc",
>     srcs = [":data_providers_service_proto"],
>     visibility = ["//visibility:public"],
> ```

Why is this needed? These services definitely shouldn't be used outside of this repo

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @wangyaopw)

___
*[src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-MkhR4J08t3JRsakGsMl:-Mki4Xh63gGTE5sTKsgv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56dfcb1f0b96a70a73d94d70c74949147a8dc25a/src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel#L60)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why is this needed? These services definitely shouldn't be used outside of this repo
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: all files reviewed, 5 unresolved discussions (waiting on @wangyaopw and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki4iEo0I6Q27wb_yI8:-Mki4iEo0I6Q27wb_yI9:bnoq5vv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L48)):*
> ```Kotlin
> /** Prepares resources for Panel Match integration tests using internal APIs. */
> class PanelMatchResourceSetup(
>   private val dataProvidersServiceStub: DataProvidersCoroutineStub,
> ```

Can you please rename these 3 to `dataProvidersStub`, etc? In other words, no need to have both `service` and `stub` in the name?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 176 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki54QwCs9II4xwW0Fh:-Mki54QwCs9II4xwW0Fi:b-mcim3x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L176)):*
> ```Kotlin
>     private val logger: Logger = Logger.getLogger(this::class.java.name)
> 
>     fun fromTargetFlags(flags: PanelMatchResourceSetupFlags): PanelMatchResourceSetup {
> ```

maybe just `fromFlags`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki4vO1BNU3kia6ReSR:-Mki4vO1BNU3kia6ReSS:b-xvyuws) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L184)):*
> ```Kotlin
>         )
>       val channel: Channel =
>         buildMutualTlsChannel(flags.target, clientCerts, flags.certHost)
> ```

@wangyaopw was there some issue with mTLS in in-process tests?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki58LB6ZTUXL_Rk0H8:-Mki58LB6ZTUXL_Rk0H9:b-u4fmyz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt#L32)):*
> ```Kotlin
>     required = true
>   )
>   lateinit var target: String
> ```

rename to `internalApiTarget`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki5Ec08Rg1ytCFOo2M:-Mki5Ec08Rg1ytCFOo2N:b-i5u72r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt#L39)):*
> ```Kotlin
>     required = true
>   )
>   lateinit var certHost: String
> ```

`internalApiCertHost`?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki4iEo0I6Q27wb_yI8:-Mki6_rj6LluB9xpZn6A:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you please rename these 3 to `dataProvidersStub`, etc? In other words, no need to have both `service` and `stub` in the name?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 176 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki54QwCs9II4xwW0Fh:-Mki6bZU0DykCC8gUJ-a:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L176)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

maybe just `fromFlags`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki58LB6ZTUXL_Rk0H8:-Mki6dBu6d-iL7xJUXUr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

rename to `internalApiTarget`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki5Ec08Rg1ytCFOo2M:-Mki6doz24Yed889agM0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`internalApiCertHost`?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @yunyeng)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki4vO1BNU3kia6ReSR:-Mki5YQU5Gpd7lBvwyGE:b-6o2pzo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L184)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@wangyaopw was there some issue with mTLS in in-process tests?
</blockquote></details>

Yep. we just use plaintext channel in the in-process tests.


Actually I suggest adding two constructors

import io.grpc.ManagedChannel
import io.grpc.Channel


```
constructor(kingdomInternalApiChannel: Channel) : this(DataProvidersCoroutineStub(kingdomInternalApiChannel), ModelProvidersCoroutineStub(kingdomInternalApiChannel), RecurringExchangesCoroutineStub(kingdomInternalApiChannel)),

constructor(kingdomInternalApiChannel: ManagedChannel) : this(DataProvidersCoroutineStub(kingdomInternalApiChannel), ModelProvidersCoroutineStub(kingdomInternalApiChannel), RecurringExchangesCoroutineStub(kingdomInternalApiChannel)),

```

The flags should be defined together with the runner binary, not with this class

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt, line 21 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki8pqY01_guKQLogKi:-Mki8pqY01_guKQLogKj:b939y2u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ac214a62e8bb23d4ed6bb6dd76ee80e04439547/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt#L21)):*
> ```
> PanelMatchResourceSetupFlags
> ```

In the in-process integration test, we won't use flags I think.

command line Flags are more for starting actual server/daemon runners.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki4vO1BNU3kia6ReSR:-Mki9PAT5Tx6A4x-mniF:bskm1wn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L184)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Yep. we just use plaintext channel in the in-process tests.


Actually I suggest adding two constructors

import io.grpc.ManagedChannel
import io.grpc.Channel


```
constructor(kingdomInternalApiChannel: Channel) : this(DataProvidersCoroutineStub(kingdomInternalApiChannel), ModelProvidersCoroutineStub(kingdomInternalApiChannel), RecurringExchangesCoroutineStub(kingdomInternalApiChannel)),

constructor(kingdomInternalApiChannel: ManagedChannel) : this(DataProvidersCoroutineStub(kingdomInternalApiChannel), ModelProvidersCoroutineStub(kingdomInternalApiChannel), RecurringExchangesCoroutineStub(kingdomInternalApiChannel)),

```

The flags should be defined together with the runner binary, not with this class

</blockquote></details>

The channel one can be used in the in-process integration test.
The ManagedChannel one can be used in the GKE correctness test

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: all files reviewed, 2 unresolved discussions (waiting on @yunyeng)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki4vO1BNU3kia6ReSR:-MkiBiGt7a_4A9nzPEuC:b-zcjvte) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L184)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

The channel one can be used in the in-process integration test.
The ManagedChannel one can be used in the GKE correctness test
</blockquote></details>

Thanks

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt, line 21 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki8pqY01_guKQLogKi:-MkiBlpF5MBHpdmcjTJo:bpanhx3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ac214a62e8bb23d4ed6bb6dd76ee80e04439547/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt#L21)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> PanelMatchResourceSetupFlags
> ```

In the in-process integration test, we won't use flags I think.

command line Flags are more for starting actual server/daemon runners.
</blockquote></details>

Good point -- maybe just add two constructors: one that takes in a Channel, one for a ManagedChannel?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt, line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki4vO1BNU3kia6ReSR:-MkiEPfI5mHdMAW_3bAS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ed5d57f56a7111dbeaf63a87859a9df1220bff9/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt#L184)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Thanks
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt, line 21 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295#-Mki8pqY01_guKQLogKi:-MkiEQsb0YPEaX_ecrPw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ac214a62e8bb23d4ed6bb6dd76ee80e04439547/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetupFlags.kt#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Good point -- maybe just add two constructors: one that takes in a Channel, one for a ManagedChannel?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/295)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
