### PR TITLE
refactor: Prevent Get Report failure when result or variance calculation fails

### PR DESCRIPTION
**Pull request by tristanvuong2021**
refactor: Prevent Get Report failure when result or variance calculation fails

GetMetric returns a FAILED Metric instead of throwing an RPC error when variance calculations fail.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1693 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9HENMa72ZXWTvSl2_K:-O9HENMa72ZXWTvSl2_L:bii1llq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bea522c5299ff6a8bddbfe9a39086a322558e70/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1693)):*
> ```Kotlin
>           result = buildMetricResult(source, variances)
>         } catch (e: Exception) {
>           if (e is IllegalArgumentException || e is IllegalStateException) {
> ```

These exception types are used to indicate programming bugs. They should never be caught and handled like this, as that means we're hiding a bug elsewhere.

In this case, I believe we've determined this happens when the methodology is missing required fields. That should be raised as its own exception somewhere, but not using one of these runtime exception types.

@kungfucraig @ple13 
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1697 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9HErUt8vkgNTXlGiWX:-O9HErUt8vkgNTXlGiWY:bah2a0f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bea522c5299ff6a8bddbfe9a39086a322558e70/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1697)):*
> ```Kotlin
>             logger.warning(
>               "Failed to process metric result for metric with ID ${source.externalMetricId}: ${e.message}"
>             )
> ```

Use logging function which takes exception



_Suggestion:_
```Kotlin
            logger.log(Level.WARNING, e) {
              "Failed to process metric result for metric with ID ${source.externalMetricId}: ${e.message}"
            }
```

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ple13, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1693 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9HENMa72ZXWTvSl2_K:-O9HRWT4-NofFtNwBQdi:b-mv74j4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bea522c5299ff6a8bddbfe9a39086a322558e70/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1693)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These exception types are used to indicate programming bugs. They should never be caught and handled like this, as that means we're hiding a bug elsewhere.

In this case, I believe we've determined this happens when the methodology is missing required fields. That should be raised as its own exception somewhere, but not using one of these runtime exception types.

@kungfucraig @ple13
</blockquote></details>

We should have a failure reason in the Metric and record the problem there (and log it too). 

The error that we are seeing comes from failing a "require(variance >= 0)"

That aside, why the special handling of these two exception types?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @ple13, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1693 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9HENMa72ZXWTvSl2_K:-O9HsXbSDBiMPd8Guz5j:b-klm5ml) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bea522c5299ff6a8bddbfe9a39086a322558e70/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1693)):*
> The error that we are seeing comes from failing a "require(variance >= 0)"

`require` is a precondition function which throws IllegalArgumentException. If that's the code, it's stating that it is a programming error to call that function with an argument such that the variance is 0. If that is indeed the intent, then it means the calling code has a bug if it does not guarantee that condition before calling the function.

IllegalArgumentException and IllegalStateException are exclusively used to indicate programming errors. We should not be catching them here for partial failures. It would in fact be correct for those errors to trigger a panic/shutdown of the whole system.

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ple13 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1693 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9HENMa72ZXWTvSl2_K:-O9L1-0hDYDGIZ3ijusz:bhg522w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bea522c5299ff6a8bddbfe9a39086a322558e70/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1693)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> The error that we are seeing comes from failing a "require(variance >= 0)"

`require` is a precondition function which throws IllegalArgumentException. If that's the code, it's stating that it is a programming error to call that function with an argument such that the variance is 0. If that is indeed the intent, then it means the calling code has a bug if it does not guarantee that condition before calling the function.

IllegalArgumentException and IllegalStateException are exclusively used to indicate programming errors. We should not be catching them here for partial failures. It would in fact be correct for those errors to trigger a panic/shutdown of the whole system.
</blockquote></details>

The Report contains so many metrics we should not be failing a report on a single Metric failure. I think it's reasonable to propagate the Metric error into the report.

Case in point, we would not have a fully broken environment right now if we propagated this error. Moreover, it would be very apparent which Metrics were broken and we could have tracked the problem down much sooner.

If you still disagree we should get on a call.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1693 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9HENMa72ZXWTvSl2_K:-O9L4qQcBo-D_W6m701K:b6ocllr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bea522c5299ff6a8bddbfe9a39086a322558e70/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1693)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify, what I'm just stating that the correct way to handle this in general is to check the conditions before calling a function that has the specified preconditions and throw a more specific exception type. These exception types are for programming errors, meaning the code author made a mistake. If we see one of these exception types here, it indicates something is **seriously** wrong and should have been prevented.
</blockquote></details>

I just changed which exceptions are thrown and added some additional checks just in case
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1697 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9HErUt8vkgNTXlGiWX:-O9L4pCk4FtW5L3nn7o8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bea522c5299ff6a8bddbfe9a39086a322558e70/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1697)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use logging function which takes exception
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by ple13 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @ple13 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1990 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9LmJlQCM29J7nqV_5Y:-O9LmJlQCM29J7nqV_5Z:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1990)):*
> ```Kotlin
>                     )
>                   )
>                 } catch (e: Throwable) {
> ```





_Suggestion:_
```Kotlin
Exception
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2148 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9LmMhB1qKRiGvLD62c:-O9LmMhB1qKRiGvLD62d:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2148)):*
> ```Kotlin
>                     )
>                   )
>                 } catch (e: Throwable) {
> ```





_Suggestion:_
```Kotlin
Exception
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2332 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9LmWsu1utgMFuNn154:-O9LmWsu1utgMFuNn155:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2332)):*
> ```Kotlin
>             FrequencyMetricVarianceParams(weightedMeasurementVarianceParamsList)
>           )
>         } catch (e: Throwable) {
> ```





_Suggestion:_
```Kotlin
Exception
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2403 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9LlnD45jLUK2s70S53:-O9LlnD45jLUK2s70S54:bqv1jen) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2403)):*
> ```Kotlin
>         ),
>       )
>     } catch (e: Throwable) {
> ```

Catching Errors (as opposed to Exceptions) is almost never correct.



_Suggestion:_
```Kotlin
Exception
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2563 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9Lm_Fc50x1DeZfncYh:-O9Lm_FdDr8xDf4RLZxA:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2563)):*
> ```Kotlin
>                   ReachMetricVarianceParams(weightedMeasurementVarianceParamsList)
>                 )
>               } catch (e: Throwable) {
> ```





_Suggestion:_
```Kotlin
Exception
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2627 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9LmbHN85KhG1qI6isC:-O9LmbHN85KhG1qI6isD:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2627)):*
> ```Kotlin
>                   ReachMetricVarianceParams(weightedMeasurementVarianceParamsList)
>                 )
>               } catch (e: Throwable) {
> ```





_Suggestion:_
```Kotlin
Exception
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @ple13 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1872 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9LnCRpD7aqUNBRWiW4:-O9LnCRpD7aqUNBRWiW5:b-g3m8mt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1872)):*
> ```Kotlin
> 
> /** Aggregates a list of [InternalMeasurement.Result]s to a [InternalMeasurement.Result] */
> private fun aggregateResults(
> ```

nit: document that this function throws `MetricResultNotComputableException` with a `@throws` KDoc tag

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1990 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9LmJlQCM29J7nqV_5Y:-O9M5kqV-6ht5ufafteb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1990)):*
> ```Kotlin
>                     )
>                   )
>                 } catch (e: Throwable) {
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2148 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9LmMhB1qKRiGvLD62c:-O9M5lT44-J_-PekDhLH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2148)):*
> ```Kotlin
>                     )
>                   )
>                 } catch (e: Throwable) {
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2332 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9LmWsu1utgMFuNn154:-O9M5gdY-NBgtIrcCIBN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2332)):*
> ```Kotlin
>             FrequencyMetricVarianceParams(weightedMeasurementVarianceParamsList)
>           )
>         } catch (e: Throwable) {
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2403 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9LlnD45jLUK2s70S53:-O9M5m8KDCq-J1LYTe1y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2403)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Catching Errors (as opposed to Exceptions) is almost never correct.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2563 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9Lm_Fc50x1DeZfncYh:-O9M5mmm5gAl5hLCQ6ik:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2563)):*
> ```Kotlin
>                   ReachMetricVarianceParams(weightedMeasurementVarianceParamsList)
>                 )
>               } catch (e: Throwable) {
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2627 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9LmbHN85KhG1qI6isC:-O9M5h2bC-Wye3qqpr8b:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01fca09421f9b9eb54b1d24df4021f884e85f7cc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2627)):*
> ```Kotlin
>                   ReachMetricVarianceParams(weightedMeasurementVarianceParamsList)
>                 )
>               } catch (e: Throwable) {
> ```

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2753 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9Uvkiz8hrXOGvntmcO:-O9Uvkiz8hrXOGvntmcP:b-x3n51w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aef616e9e2276291ddc78bb98ae692fb03b07faf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2753)):*
> ```Kotlin
>         }
>         CustomDirectMethodology.Variance.TypeCase.UNAVAILABLE -> {
>           return null
> ```

this should throw if the Reason is unspecified, right?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2791 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9UwBZv0DNuX3W4qd_f:-O9UwBZv0DNuX3W4qd_g:b42p7de) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aef616e9e2276291ddc78bb98ae692fb03b07faf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2791)):*
> ```Kotlin
>     }
>     InternalMeasurement.Result.Reach.MethodologyCase.METHODOLOGY_NOT_SET -> {
>       return null
> ```

why not throw an error if this isn't set?

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2753 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9Uvkiz8hrXOGvntmcO:-O9k-q1SA00qyoCEa2HE:byf62b5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aef616e9e2276291ddc78bb98ae692fb03b07faf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2753)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this should throw if the Reason is unspecified, right?
</blockquote></details>

I added a comment above to clarify that UNAVAILABLE is a deliberate selection.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2791 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9UwBZv0DNuX3W4qd_f:-O9k0E_z4e5zNz-vSpf7:bfnbc0x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aef616e9e2276291ddc78bb98ae692fb03b07faf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2791)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why not throw an error if this isn't set?
</blockquote></details>

It is allowed to not be set, but if it is set, then it must follow certain restrictions.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2791 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9UwBZv0DNuX3W4qd_f:-O9oeGKj0piiVlHSpEzp:br26cse) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aef616e9e2276291ddc78bb98ae692fb03b07faf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2791)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It is allowed to not be set, but if it is set, then it must follow certain restrictions.
</blockquote></details>

@SanjayVas - When is the plan to make this be required to be set?

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2791 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1859#-O9UwBZv0DNuX3W4qd_f:-O9q7jRKB35pPm3Kf115:bv8hg4y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aef616e9e2276291ddc78bb98ae692fb03b07faf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2791)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@SanjayVas - When is the plan to make this be required to be set?
</blockquote></details>

It depends where you're talking about. In new Requisition fulfillments, we might expect it after all EDPs are on 0.5, which is blocked on all Kingdoms being on 0.5. If it's for code that needs to handle existing Measurements, I don't know if we've yet set a horizon.

**Pull request merged**
