### PR TITLE
Add population fields to model release

### PR DESCRIPTION
**Pull request by jojijac0b**
Add population fields to model release service

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
For clarification, it looks like what this PR is doing is updating the Kingdom internal ModelReleases, ModelRollouts, and ModelShards service impls for population fields. Ideally this should have been done in the same PR that updated the internal service protobuf definitions.

> Reviewed 3 of 5 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420#-:-Nnz-YMfBoE11CwUz2Mm:b-7z6w1d)* status: all files reviewed, 5 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRelease.kt` line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420#-Nnz1K6LCTbipQ-QDjZM:-Nnz1K6M1-Kl9hNbSPf0:bccupfa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be6124bab989521f021bf1fcc928441480864368/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRelease.kt#L45)):*
> ```Kotlin
>       )
>         ?: throw ModelSuiteNotFoundException(
>           ExternalId(modelRelease.externalModelProviderId),
> ```

nit: extract variable so you don't need to do this twice



_Code quote:_
```Kotlin
ExternalId(modelRelease.externalModelProviderId)
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRelease.kt` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420#-Nnz1Wa54De2oashpK6f:-Nnz1Wa54De2oashpK6g:bp3cjei) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be6124bab989521f021bf1fcc928441480864368/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRelease.kt#L52)):*
> ```Kotlin
>         ExternalId(modelRelease.externalDataProviderId),
>         ExternalId(modelRelease.externalPopulationId)
>       ) ?: failGrpc(Status.NOT_FOUND) { "Population not found" }
> ```

Nothing in readers/writers packages should throw gRPC errors. Throw a KingdomInternalException instead and convert to a gRPC error in the service impl.



_Code quote:_
```Kotlin
failGrpc(Status.NOT_FOUND)
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRelease.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420#-Nnz2a-RC9CDWSRNLlFE:-Nnz2a-RC9CDWSRNLlFF:bim5eoe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be6124bab989521f021bf1fcc928441480864368/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRelease.kt#L113)):*
> ```Kotlin
>       }
> 
>     return transactionContext.executeQuery(statement).singleOrNull()
> ```

Prefer org.wfanet.measurement.common.singleOrNullIfEmpty. That way you get an exception if there's more than one rather than treating it the same as not being found.



_Code quote:_
```Kotlin
singleOrNull
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt` line 131 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420#-Nnz3HTh3uDJeFxNyr6A:-Nnz3HTh3uDJeFxNyr6B:b5pit8b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be6124bab989521f021bf1fcc928441480864368/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt#L131)):*
> ```Kotlin
>   fun `getModelRelease returns created model release`() = runBlocking {
>     val modelSuite = population.createModelSuite(modelProvidersService, modelSuitesService)
>     val population = population.createPopulation(dataProvidersService, populationsService)
> ```

nit: use a different name to avoid shadowing the `population` instance variable



_Code quote:_
```Kotlin
population
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt` line 243 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420#-Nnz3W878KEDxOGg_QMr:-Nnz3W878KEDxOGg_QMs:b-7ze27q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be6124bab989521f021bf1fcc928441480864368/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L243)):*
> ```Kotlin
>         }
>     }
>     val dataProvider = dataProvidersService.createDataProvider(DATA_PROVIDER)
> ```

Pass in the DataProvider instead of creating it here.



_Code quote:_
```Kotlin
    val DATA_PROVIDER = dataProvider {
      certificate {
        notValidBefore = timestamp { seconds = 12345 }
        notValidAfter = timestamp { seconds = 23456 }
        details =
          CertificateKt.details { x509Der = ByteString.copyFromUtf8("This is a certificate der.") }
      }
      details =
        DataProviderKt.details {
          apiVersion = "v2alpha"
          publicKey = ByteString.copyFromUtf8("This is a  public key.")
          publicKeySignature = ByteString.copyFromUtf8("This is a  public key signature.")
        }
    }
    val dataProvider = dataProvidersService.createDataProvider(DATA_PROVIDER)
```

**Review by stevenwarejones — APPROVED** [review]
i'm good with it once Sanjay is happy

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420#-:-NnzRHY72HPbWdy-yYdv:b-h3y4kv)* status: all files reviewed, 5 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRelease.kt` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420#-Nnz1Wa54De2oashpK6f:-NnzCBr0EseflkPS4bjy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be6124bab989521f021bf1fcc928441480864368/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRelease.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Nothing in readers/writers packages should throw gRPC errors. Throw a KingdomInternalException instead and convert to a gRPC error in the service impl.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt` line 243 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420#-Nnz3W878KEDxOGg_QMr:-Nnza7FU4hsfO6S4Fptn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be6124bab989521f021bf1fcc928441480864368/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L243)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Pass in the DataProvider instead of creating it here.
</blockquote></details>

Done.

**Review by jojijac0b — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420#-:-No-qJ2aEQIAf0jMKwKM:bnfp4nl)* status: 6 of 11 files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)

**Review by jojijac0b — COMMENTED** [review]
@SanjayVas @stevenwarejones can you please re-accept? i am still blocked by the review check for some reason

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420#-:-No-qdxZ2WHa3Elj9_y-:bzien7c)* status: 6 of 11 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1420)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Pull request merged**
