### PR TITLE
Use grpc-java from Maven.

### PR DESCRIPTION
**Pull request by SanjayVas**
This updates common-jvm and common-cpp.

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563)

### CODE REVIEW

**Comment by SanjayVas** [comment]
This depends on https://github.com/world-federation-of-advertisers/common-jvm/pull/117 and is for https://github.com/world-federation-of-advertisers/common-jvm/issues/115.

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @SanjayVas)

___
*[`build/repositories.bzl` line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563#-N2CetFr6_61WTy_BPAl:-N2CetFr6_61WTy_BPAm:b-yirvu0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b485397943f83a0e31129e5eb4f826df8d45a76/build/repositories.bzl#L86)):*
> ```Starlark
> 
>     http_archive(
>         name = "com_google_private_join_and_compute",
> ```

why aren't you updating this here? https://github.com/world-federation-of-advertisers/common-cpp/blob/0b9562ff4ce63d7dbbf570f083b23fdba2f3c876/build/com_google_private_join_and_compute/repo.bzl#L26



_Code quote:_
```Starlark
com_google_private_join_and_compute
```

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`build/repositories.bzl` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563#-N2CjgxY3kTHsc8eWcaE:-N2CjgxZ7aql1BXP3NwY:bu2xkts) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b485397943f83a0e31129e5eb4f826df8d45a76/build/repositories.bzl#L22)):*
> ```Starlark
> load("//build/wfa:repositories.bzl", "wfa_repo_archive")
> 
> _PJC_COMMIT = "505ba981d66c9e5e73e18cfa647b4685f74784cb"
> ```

PJC is private join and compute?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`build/repositories.bzl` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563#-N2CjgxY3kTHsc8eWcaE:-N2Cl4If5gR9DVNM1FtK:bsutmc5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b485397943f83a0e31129e5eb4f826df8d45a76/build/repositories.bzl#L22)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

PJC is private join and compute?
</blockquote></details>

Yes. It's how that library refers to itself in its codebase.
___
*[`build/repositories.bzl` line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563#-N2CetFr6_61WTy_BPAl:-N2CjfVTDQ4yCY73vIv-:b-5z48m8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b485397943f83a0e31129e5eb4f826df8d45a76/build/repositories.bzl#L86)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why aren't you updating this here? https://github.com/world-federation-of-advertisers/common-cpp/blob/0b9562ff4ce63d7dbbf570f083b23fdba2f3c876/build/com_google_private_join_and_compute/repo.bzl#L26
</blockquote></details>

It's specific to how `common-jvm` loads `@com_google_protobuf` via `rules_proto` in the latest PR. `common-cpp` does not currently do this. I can follow up and make common-cpp load rules_proto explicitly, at which point it's PJC loading def can be updated.

Note that the real fix is probably getting PJC to not depend on `@com_google_protobuf//:protobuf_lite`, as I suspect looking at the code that this dependency may not actually be used.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`build/repositories.bzl` line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563#-N2CetFr6_61WTy_BPAl:-N2D-zij4VSvZ5I0uAFD:b-tlwpie) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b485397943f83a0e31129e5eb4f826df8d45a76/build/repositories.bzl#L86)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's specific to how `common-jvm` loads `@com_google_protobuf` via `rules_proto` in the latest PR. `common-cpp` does not currently do this. I can follow up and make common-cpp load rules_proto explicitly, at which point it's PJC loading def can be updated.

Note that the real fix is probably getting PJC to not depend on `@com_google_protobuf//:protobuf_lite`, as I suspect looking at the code that this dependency may not actually be used.
</blockquote></details>

Done (updated common-cpp).

**Comment by SanjayVas** [comment]
Now depends on world-federation-of-advertisers/common-cpp#30 as well.

**Review by iverson52000 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/563)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
