### PR TITLE
Controlplane KMS client

### PR DESCRIPTION
**Pull request by Marco-Premier**
Classes to interact with Google KMS.

This class is needed to decrypt a DEK using a KEK.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874#-O9pzrClBwgr3SfEOjqu:-O9pzrClBwgr3SfEOjqv:bw4dcp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/812559ff09c3ed1f919fd3ae275e79f0e8775eba/src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/BUILD.bazel#L14)):*
> ```Starlark
> )
> 
> kt_jvm_library(
> ```

Follow the package conventions, which has everything that is specific to a cloud provider go under the appropriate `deploy` subpackage. e.g. `deploy.gcloud`

This also should not be under the versioned API package if it doesn't depend on a given API version.
___
*[`src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/KmsClient.kt` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874#-O9q-EcG08vcMVjNjGQ2:-O9q-EcG08vcMVjNjGQ3:bwakgux) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/812559ff09c3ed1f919fd3ae275e79f0e8775eba/src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/KmsClient.kt#L25)):*
> ```Kotlin
>  * using the provider's respective KMS service.
>  */
> interface KmsClient {
> ```

We already have a KmsClient interface and implementations from Tink. See com.google.crypto.tink.KmsClient, which has both gcloud and AWS implementations. We even have [our own fake in common-jvm](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/testing/FakeKmsClient.kt).

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @dawnwang22, @Marco-Premier, and @stevenwarejones)

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @dawnwang22, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/KmsClient.kt` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874#-O9q-EcG08vcMVjNjGQ2:-O9tLicGEXeraOiHn5DC:b-8wow12) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/812559ff09c3ed1f919fd3ae275e79f0e8775eba/src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/KmsClient.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We already have a KmsClient interface and implementations from Tink. See com.google.crypto.tink.KmsClient, which has both gcloud and AWS implementations. We even have [our own fake in common-jvm](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/testing/FakeKmsClient.kt).
</blockquote></details>

Oh many thanks for that @SanjayVas !
I also found this class: https://github.com/tink-crypto/tink/blob/master/java_src/src/main/java/com/google/crypto/tink/integration/gcpkms/GcpKmsAead.java

Particularly the method `decrypt.

I think we can simply reuse this one, what you think?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @dawnwang22, @Marco-Premier, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/BUILD.bazel` line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874#-O9okfYj6e9KE7yq8Jfn:-O9okfYj6e9KE7yq8Jfo:b-m5xnu1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/812559ff09c3ed1f919fd3ae275e79f0e8775eba/src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/BUILD.bazel#L5)):*
> ```Starlark
> 
> package(default_visibility = [
>     "//src/main/kotlin/org/wfanet/measurement/securecomputation:__subpackages__",
> ```

ditto that I don't think you need `v1alpha1` in the path
___
*[`src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/KmsClient.kt` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874#-O9q-EcG08vcMVjNjGQ2:-O9tSgoh1uoNJQWSvZTG:b-eobhjl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/812559ff09c3ed1f919fd3ae275e79f0e8775eba/src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/KmsClient.kt#L25)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Oh many thanks for that @SanjayVas !
I also found this class: https://github.com/tink-crypto/tink/blob/master/java_src/src/main/java/com/google/crypto/tink/integration/gcpkms/GcpKmsAead.java

Particularly the method `decrypt.

I think we can simply reuse this one, what you think?
</blockquote></details>

you'll want to use https://github.com/tink-crypto/tink-java-gcpkms/blob/512609d7bd1c7f44d4a4cb731bf08a1b9aa1b8bc/src/main/java/com/google/crypto/tink/integration/gcpkms/GcpKmsClient.java#L49 I believe

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @dawnwang22 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/KmsClient.kt` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874#-O9q-EcG08vcMVjNjGQ2:-O9uIOTG-qDcnqxhOIQa:b-v85qmy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/812559ff09c3ed1f919fd3ae275e79f0e8775eba/src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/KmsClient.kt#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you'll want to use https://github.com/tink-crypto/tink-java-gcpkms/blob/512609d7bd1c7f44d4a4cb731bf08a1b9aa1b8bc/src/main/java/com/google/crypto/tink/integration/gcpkms/GcpKmsClient.java#L49 I believe
</blockquote></details>

Yes, that class has the `getAead` function that returns a `GcpKmsAead`

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @dawnwang22, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/KmsClient.kt` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874#-O9q-EcG08vcMVjNjGQ2:-O9vcT-tDMxh_2YQ18IP:b-pqtrkj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/812559ff09c3ed1f919fd3ae275e79f0e8775eba/src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/KmsClient.kt#L25)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Yes, that class has the `getAead` function that returns a `GcpKmsAead`
</blockquote></details>

To clarify, I think this whole PR can therefore be dropped.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @dawnwang22, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/KmsClient.kt` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1874#-O9q-EcG08vcMVjNjGQ2:-O9xXx1YAHGx_aARUu_R:b-6ldl4l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/812559ff09c3ed1f919fd3ae275e79f0e8775eba/src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/client/v1alpha/kms/KmsClient.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify, I think this whole PR can therefore be dropped.
</blockquote></details>

Yes indeed.

**Comment by Marco-Premier** [comment]
https://github.com/tink-crypto/tink-java-gcpkms/blob/512609d7bd1c7f44d4a4cb731bf08a1b9aa1b8bc/src/main/java/com/google/crypto/tink/integration/gcpkms/GcpKmsClient.java#L49 class will be used instead.

**Pull request closed without merging**
