### PR TITLE
Clarify cert-host flags, making them optional.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/484)

### CODE REVIEW

**Review by yunyeng — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/484)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/484)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/ServiceFlags.kt, line 69 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/484#-Mz1a5Zq5GJQRcv3qXBI:-Mz1a5Zr1USRl8iW6tW-:b-sfhqwf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8089376fe7a8b6f615dfe1ab96f245a6e5fcd6bc/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/ServiceFlags.kt#L69)):*
> ```Kotlin
>       [
>         "Expected hostname (DNS-ID) in the Kingdom system API server's TLS certificate.",
>         "This overrides derivation of the TLS DNS-ID from --kingdom-system-api-target.",
> ```

what is the use case for this override?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/484)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/ServiceFlags.kt, line 69 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/484#-Mz1a5Zq5GJQRcv3qXBI:-Mz1ur4o8KzU19JMxiyD:b8lk6x7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8089376fe7a8b6f615dfe1ab96f245a6e5fcd6bc/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/ServiceFlags.kt#L69)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what is the use case for this override?
</blockquote></details>

It's for when the gRPC target doesn't match a hostname (DNS-ID in [RFC 6125](https://datatracker.ietf.org/doc/html/rfc6125)) in the server certificate. This is common when connecting via cluster IP (i.e. within a cluster) or [using K8s port forwarding](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md#port-forwarding).

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/484)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
