### PR TITLE
Add measurement-consumers create command to MeasurementSystem CLI.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/634)

### CODE REVIEW

**Review by renjiezh — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/634)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 272 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/634#-N8UcwlHBnWpDD2YAhMU:-N8UcwlHBnWpDD2YAhMV:btsokqd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/970845e1c822936995a14c7a1e901f97adae5882/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L272)):*
> ```Kotlin
>     @Option(
>       names = ["--display-name"],
>       required = false,
> ```

Seems `required` field is by default false. Do we need to set other options as true?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/634)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 272 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/634#-N8UcwlHBnWpDD2YAhMU:-N8_Fgdw21V_o5Yy1kRG:boj1qgt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/970845e1c822936995a14c7a1e901f97adae5882/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L272)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Seems `required` field is by default false. Do we need to set other options as true?
</blockquote></details>

Good catch. Done.

**Review by renjiezh — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/634)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 9 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/634)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 4 of 9 files at r1, 3 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/634)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
