### PR TITLE
Update cross-media-measurement-api for max watch duration.

### PR DESCRIPTION
**Pull request by SanjayVas**
Update the cross-media-measurement-api dependency for world-federation-of-advertisers/cross-media-measurement-api#167.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1192)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 20 of 30 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Comment by SanjayVas** [comment]
Depends on #1183

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
