### PR TITLE
Add UpdateExchangeStepState class to update the state of an ExchangeStep

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161#-:-MfA-Uh67TjLMGox4eIT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStepState.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161#-Mf9zq0_01hvyALoeJiD:-Mf9zq0_01hvyALoeJiE:bvjit7s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ba838b38a2975abf5b1675fc16fc78cb2988b80/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStepState.kt#L41)):*
> ```Kotlin
>         stepIndex = stepIndex
>       )
>     val result = GetExchangeStep(filter).executeSingle(transactionContext)
> ```

I'm a little worried that this will be a lot of separate reads because updating the state of an ExchangeStep can then cause other ExchangeSteps to become ready, or possibly the Exchange itself to change state.

I think it's fine for now but could you add a TODO somewhere to look into combining all the updates into a single read and then a bunch of writes?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStepState.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161#-Mf9zq0_01hvyALoeJiD:-MfA3DEU-jlKG9unmsi9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ba838b38a2975abf5b1675fc16fc78cb2988b80/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStepState.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm a little worried that this will be a lot of separate reads because updating the state of an ExchangeStep can then cause other ExchangeSteps to become ready, or possibly the Exchange itself to change state.

I think it's fine for now but could you add a TODO somewhere to look into combining all the updates into a single read and then a bunch of writes?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161#-:-MfA9xO1E2iKOcMQT_4M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 432 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161#-MfEV2j25vqsLttkJ8o2:-MfEV2j35RsnCXbyMd1q:b-st3epx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c919e27648e5bcc9d5fdcc8b8d354245972e169/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L432)):*
> ```Kotlin
>   }
> 
>   protected fun readAllExchangeStepsInSpanner(): List<ExchangeStep> = runBlocking {
> ```

i'm a little confused about the functionality. Does this return all the exchange steps for a particular EXCHANGE_ID? If so, shouldn't that be passed as input?
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStepStateTest.kt, line 130 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161#-MfEVvImCgIX7vOeVJTZ:-MfEVvImCgIX7vOeVJT_:b-m3xpdc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c919e27648e5bcc9d5fdcc8b8d354245972e169/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStepStateTest.kt#L130)):*
> ```Kotlin
>   }
> 
>   private suspend fun directlyUpdateState(state: ExchangeStep.State) {
> ```

do we need this function? Why can't we juse use `updateExchangeStepState`?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 432 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161#-MfEV2j25vqsLttkJ8o2:-MfF8KWXExIY9yPG2NhA:b-ja29ey) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c919e27648e5bcc9d5fdcc8b8d354245972e169/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L432)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'm a little confused about the functionality. Does this return all the exchange steps for a particular EXCHANGE_ID? If so, shouldn't that be passed as input?
</blockquote></details>

No, this is actually grabbing all the ExchangeSteps from db independent of the EXCHANGE_ID. At the beginning of the test (populateDatabase) I only inserted one ExchangeStep to test. So, its only retrieving that one. Let me know if you have more questions.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStepStateTest.kt, line 130 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161#-MfEVvImCgIX7vOeVJTZ:-MfF7xD-EFQR30PX8qH0:b-ri9xn9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c919e27648e5bcc9d5fdcc8b8d354245972e169/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStepStateTest.kt#L130)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we need this function? Why can't we juse use `updateExchangeStepState`?
</blockquote></details>

This is actually directly talking to Spanner and updating the state rather than using the UpdateExchangeStepState class, then we basically compare the both results if the UpdateExchangeStepState class working properly updating the state. Let me know if you have more questions.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/161)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @stevenwarejones)

**Pull request merged**
