### PR TITLE
Filter public Requisitions by parent Measurement state.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-MihHUPq-KA6TR2HDBiq:-MihHUPq-KA6TR2HDBir:bthx252) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ec07c5ecb7cd8dd0911977047a525c8be3e4c84/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L160)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>       InternalMeasurement.State.PENDING_PARTICIPANT_CONFIRMATION,
>       InternalMeasurement.State.PENDING_COMPUTATION,
>       InternalMeasurement.State.SUCCEEDED,
>       InternalMeasurement.State.FAILED,
>       InternalMeasurement.State.CANCELLED -> true
> ```
</details>

It is a little tricky here.

In one hand, I feel the EDPs only need to know requisitions whose parent measurements are in PENDING_REQUISITION_FULFILLMENT. For example, if the MC cancels a measurement, the EDP doesn't need to fulfill the requisition of that measurement any more.

However, there is another corner case that
1. EDP A refuses to fulfill its requisition, which causes the measurement be transited to FAILED.
2.  later, EDP B tries to fulfill its requisition for that measurement. The internal rpc will fail due to REQUISITION_STATE_ILLEGAL.
As a result, EDP B needs to be able to figure out why such a request fails. If it checks the state of that requisition, it is still UNFULFILLED, which will confuse EDP B.

Any idea on how to handle both cases gracefully?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-MihHUPq-KA6TR2HDBiq:-MihToC3C3g2k-SqP8gc:b-k292ar) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ec07c5ecb7cd8dd0911977047a525c8be3e4c84/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L160)):*
One premise I'm following is that a Requisition shouldn't disappear once its visible in the public API. While the parent Measurement could become cancelled/failed before all Duchies set their requisition params, I don't think we want to track the state of whether the Requisition has ever been visible before. Therefore, we err on having it visible in that case.

> later, EDP B tries to fulfill its requisition for that measurement. The internal rpc will fail due to REQUISITION_STATE_ILLEGAL.

Actually, it won't fail in the current implementation. You can fulfill an unfulfilled requisition even if the parent measurement is failed/cancelled. We could check for this and fail with an internal MEASUREMENT_STATE_ILLEGAL, which would translate to a FAILED_PRECONDITION at the gRPC layer.

> As a result, EDP B needs to be able to figure out why such a request fails. If it checks the state of that requisition, it is still UNFULFILLED, which will confuse EDP B.

Assuming we make the above change to check parent Measurement state, the error detail should make it clear that the issue is the parent measurement state rather than the requisition state. The Requisition contains the parent measurement resource name which allows the EDP to Get the parent Measurement.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-MihHUPq-KA6TR2HDBiq:-MihY_uU8JP4YhX_7D9p:bbl13w7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ec07c5ecb7cd8dd0911977047a525c8be3e4c84/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L160)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

One premise I'm following is that a Requisition shouldn't disappear once its visible in the public API. While the parent Measurement could become cancelled/failed before all Duchies set their requisition params, I don't think we want to track the state of whether the Requisition has ever been visible before. Therefore, we err on having it visible in that case.

> later, EDP B tries to fulfill its requisition for that measurement. The internal rpc will fail due to REQUISITION_STATE_ILLEGAL.

Actually, it won't fail in the current implementation. You can fulfill an unfulfilled requisition even if the parent measurement is failed/cancelled. We could check for this and fail with an internal MEASUREMENT_STATE_ILLEGAL, which would translate to a FAILED_PRECONDITION at the gRPC layer.

> As a result, EDP B needs to be able to figure out why such a request fails. If it checks the state of that requisition, it is still UNFULFILLED, which will confuse EDP B.

Assuming we make the above change to check parent Measurement state, the error detail should make it clear that the issue is the parent measurement state rather than the requisition state. The Requisition contains the parent measurement resource name which allows the EDP to Get the parent Measurement.
</blockquote></details>

Yep, I think we should check the measurement state when fulfilling a requisition and reject if the state is not in PENDING_REQUISITION_FULFILLMENT.

Otherwise there is corner case like
1. The MC cancels the measurement
2. All EDPs fulfill their requisitions eventually.
3.  Then the measurement is updated to PENDING_PARTICIPANT_CONFIRMATION again.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-MihHUPq-KA6TR2HDBiq:-Mih_aer8vLveJ1o_7vu:b-8838uc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ec07c5ecb7cd8dd0911977047a525c8be3e4c84/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L160)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Yep, I think we should check the measurement state when fulfilling a requisition and reject if the state is not in PENDING_REQUISITION_FULFILLMENT.

Otherwise there is corner case like
1. The MC cancels the measurement
2. All EDPs fulfill their requisitions eventually.
3.  Then the measurement is updated to PENDING_PARTICIPANT_CONFIRMATION again.
</blockquote></details>

That is long error chain.

EDP -> duchy public API -> King System API -> King Internal API. Maybe just add a TODO to deal with this later

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-MihHUPq-KA6TR2HDBiq:-MihiCfyBkSeA6S_gAR7:burnsuw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ec07c5ecb7cd8dd0911977047a525c8be3e4c84/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L160)):*
> Yep, I think we should check the measurement state when fulfilling a requisition and reject if the state is not in PENDING_REQUISITION_FULFILLMENT.

Updated PR #249 to handle this since there were other bugs related to not checking the state.

> That is long error chain.
>
> EDP -> duchy public API -> King System API -> King Internal API. Maybe just add a TODO to deal with this later

Long chains like that are unfortunately expected. What we need to do is plumb machine-readable error info (e.g. what the wrong internal Measurement state) from KingdomInternalException through the gRPC [error details](https://github.com/googleapis/api-common-protos/blob/master/google/rpc/error_details.proto) so that the public API has enough info to throw an actionable error (e.g. by converting to public API measurement state).

**Review by wangyaopw — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-:-MihoT3M7nMB_HX78YLY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 161 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-MiiBStA3148GLlmfaOh:-MiiBStA3148GLlmfaOi:b-f143h6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ec07c5ecb7cd8dd0911977047a525c8be3e4c84/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L161)):*
> ```Kotlin
>       InternalMeasurement.State.FAILED,
>       InternalMeasurement.State.CANCELLED -> true
>       InternalMeasurement.State.PENDING_REQUISITION_PARAMS,
> ```

nit: This isn't very readable with the true and false buried in the list of consts - is there any better way of formatting or expressing this?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-MihHUPq-KA6TR2HDBiq:-MimUxm_3RciUJS5KT5S:b-4jprjc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ec07c5ecb7cd8dd0911977047a525c8be3e4c84/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L160)):*
>  The Requisition contains the parent measurement resource name which allows the EDP to Get the parent Measurement.

I am not sure if EDPs should be allowed to call GetMeasurement(). The measurement contains the name of all other EDPs, should the list be visible to all EDPs of a measurement? 

The authorization is also a little complicated since we can not pre-determine if a EDP is participating a measurement or not. We have to read the measurement to see if the caller is in its dataProviderList.

so it would be best if the EDP doesn't need to figure out if a failed fulfillRequsition call is due to measurement state illegal. Maybe the kingdom System API should just ACK the request if the error indicates the failure is caused by unexpected measurement state.

**Review by corbantek — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-:-Mj-arrL1sIQEmmCqsyK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-MihHUPq-KA6TR2HDBiq:-Mj06_PUBvYqLffYZ4pc:b7njfu9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ec07c5ecb7cd8dd0911977047a525c8be3e4c84/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L160)):*
> I am not sure if EDPs should be allowed to call GetMeasurement(). The measurement contains the name of all other EDPs, should the list be visible to all EDPs of a measurement?

Sorry, you're correct.

> Maybe the kingdom System API should just ACK the request if the error indicates the failure is caused by unexpected measurement state.

This would be fine, but we could also denormalize the Measurement state into the public Requisition the same way we do for the internal one. WDYT?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 161 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-MiiBStA3148GLlmfaOh:-Mj076N36XLel7wBYf09:be3o1sx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ec07c5ecb7cd8dd0911977047a525c8be3e4c84/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L161)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

nit: This isn't very readable with the true and false buried in the list of consts - is there any better way of formatting or expressing this?
</blockquote></details>

Unfortunately this is how ktfmt formats `when`s. I'm not certain of a way to write it such that it gets formatted more clearly.

For background, we're using an exhaustive `when` here to ensure that compilation fails if a new internal Measurement state gets added and it's not considered here.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-MihHUPq-KA6TR2HDBiq:-Mj0Bfq76Jq5bFAo9ZLX:b-tvqfg1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ec07c5ecb7cd8dd0911977047a525c8be3e4c84/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L160)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I am not sure if EDPs should be allowed to call GetMeasurement(). The measurement contains the name of all other EDPs, should the list be visible to all EDPs of a measurement?

Sorry, you're correct.

> Maybe the kingdom System API should just ACK the request if the error indicates the failure is caused by unexpected measurement state.

This would be fine, but we could also denormalize the Measurement state into the public Requisition the same way we do for the internal one. WDYT?
</blockquote></details>

I personally prefer adding another state to the public requisition (e.g., ABANDONED) than a parentMeasurement state field.

But it would be nice we don't need such a state in the internal requisition. so we don't need to update all requisitions rows when the measurement state changes. The pubic API can overwrite the public requisition state based on the internal parentMeasurement.State.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-MihHUPq-KA6TR2HDBiq:-Mj0ihB7D0m9NQLPvVNG:bkz1j37) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ec07c5ecb7cd8dd0911977047a525c8be3e4c84/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L160)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I personally prefer adding another state to the public requisition (e.g., ABANDONED) than a parentMeasurement state field.

But it would be nice we don't need such a state in the internal requisition. so we don't need to update all requisitions rows when the measurement state changes. The pubic API can overwrite the public requisition state based on the internal parentMeasurement.State.
</blockquote></details>

Not a bad idea. Regardless, is what we have here fine for now?

**Review by wangyaopw — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 160 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251#-MihHUPq-KA6TR2HDBiq:-Mj0kP151M2fO7hTspCy:b-7j86r0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ec07c5ecb7cd8dd0911977047a525c8be3e4c84/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L160)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not a bad idea. Regardless, is what we have here fine for now?
</blockquote></details>

sure.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Pull request merged**
