### PR TITLE
Fix several issues in Public Report Schedules Create Method

### PR DESCRIPTION
**Pull request by tristanvuong2021**
Several issues were discovered when testing:

1. The first Report event time was always set to be event start. This makes sense for daily frequency, but not for weekly or monthly. The first Report event time is now set to the first occurrence of the specified day of the week if it is weekly frequency and the first occurrence of the day of the month if it is monthly frequency.

2. The api key metadata was not set for calls to the kingdom event groups service and data providers service.

3. The helper function for the Report lookback window didn't work if utc offset was used instead of time zone.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366)

**Comment by riemanli** [comment]
Could you provide some context about the issues?

**Comment by riemanli** [comment]
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 356 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366#-Nlzkr3eAXPy2ZUwB8aa:-Nlzkr3eAXPy2ZUwB8ab:b-u7bhhd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97775c106ce2ec530012f87f3c743ee90bb7d05a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L356)):*
> ```Kotlin
> 
>     val nextReportCreationTime: Timestamp =
>       if (source.eventStart.hasUtcOffset()) {
> ```

Sorry could you remind me again if `eventStart` gets incremented when a report is created? If so, could you point me to where it happens?



_Code quote:_
```Kotlin
source.eventStart
```

**Review by riemanli — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 325 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366#-Nlzu1z2CeUQZVXBTuB6:-Nlzu1z2CeUQZVXBTuB7:b-njp2yq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97775c106ce2ec530012f87f3c743ee90bb7d05a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L325)):*
> ```Kotlin
>     val source = this
> 
>     val eventStart = source.eventStart
> ```

Dumb question: could a user specify invalid `eventStart` e.g. `{eventStart.year = 2023, eventStart.month = 13, eventStart.day = 40}`?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 781 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366#-NlzsrdO4B2-2swjr8lV:-NlzsrdO4B2-2swjr8lW:b9y1ob5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97775c106ce2ec530012f87f3c743ee90bb7d05a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L781)):*
> ```Kotlin
>           ) {
>             offsetDateTime.withDayOfMonth(frequency.monthly.dayOfMonth).toInstant().toProtoTime()
>           } else if (frequency.monthly.dayOfMonth > lastDayOfMonth) {
> ```

What will happen if `frequency.monthly.dayOfMonth == 30`, `lastDayOfMonth==28`, and `offsetDateTime.dayOfMonth == 31`?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 325 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366#-Nlzu1z2CeUQZVXBTuB6:-NlzyGIA1OYVIqyM4mSo:b-dhcaje) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97775c106ce2ec530012f87f3c743ee90bb7d05a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L325)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Dumb question: could a user specify invalid `eventStart` e.g. `{eventStart.year = 2023, eventStart.month = 13, eventStart.day = 40}`?
</blockquote></details>

It would throw an error because the Java DateTime classes throw an exception for that.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 356 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366#-Nlzkr3eAXPy2ZUwB8aa:-NlzxycF-apYtsKt4WHP:bpea031) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97775c106ce2ec530012f87f3c743ee90bb7d05a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L356)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Sorry could you remind me again if `eventStart` gets incremented when a report is created? If so, could you point me to where it happens?
</blockquote></details>

eventStart doesn't get incremented. nextReportCreationTime does though, not here, but in the job implementation.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 781 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366#-NlzsrdO4B2-2swjr8lV:-NlzyYOU5EmCEplGVjaH:b86qbdi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97775c106ce2ec530012f87f3c743ee90bb7d05a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L781)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

What will happen if `frequency.monthly.dayOfMonth == 30`, `lastDayOfMonth==28`, and `offsetDateTime.dayOfMonth == 31`?
</blockquote></details>

That can't happen because lastDayOfMonth is offsetDateTime adjusted to the last day of the month, meaning lastDayOfMonth is >= offsetDateTime.dayOfMonth.

**Review by riemanli — APPROVED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt` line 356 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366#-Nlzkr3eAXPy2ZUwB8aa:-Nlzziqj3-ynQBIWQHU4:b-cbb2dh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/97775c106ce2ec530012f87f3c743ee90bb7d05a/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesService.kt#L356)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

eventStart doesn't get incremented. nextReportCreationTime does though, not here, but in the job implementation.
</blockquote></details>

nit: I see. Would you mind adding a comment to indicate that `next_report_creation_time` will get incremented whenever a new report is created in `report_schedule.proto` ?
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt` line 1297 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366#-Nm-30BD0iuqvPPG7qhd:-Nm-30BD0iuqvPPG7qhe:b-v14huu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4482748fa6484563a63c1a9e5571759795394bfa/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt#L1297)):*
> ```Kotlin
>             dataAvailabilityInterval = interval {
>               startTime =
>                 dateTime {
> ```

nit: Any reason not to do like this but use `seconds`?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt` line 1297 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366#-Nm-30BD0iuqvPPG7qhd:-Nm2AEasEjaPQaNYD-JU:bjkl8f8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a26248d264c9045e68c1c7233ff9eceb2245d08/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt#L1297)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

nit: Any reason not to do like this but use `seconds`?
</blockquote></details>

I actually did change it in this PR. This comment is attached to the old version.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt` line 1297 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366#-Nm-30BD0iuqvPPG7qhd:-Nm3GjKW7WiBsWjgNIsA:b-9uoaig) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a26248d264c9045e68c1c7233ff9eceb2245d08/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt#L1297)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I actually did change it in this PR. This comment is attached to the old version.
</blockquote></details>

That's what I am curious about. Why is the new change
```
startTime = timestamp {
  seconds = 48282210000 // January 1, 3500 at 1 PM, America/Los_Angeles
}
```
more preferred than the old one?
```
dateTime {
  year = 9100
  month = 1
  day = 1
  hours = 6
  timeZone = timeZone { id = "America/New_York" }
}
.toTimestamp()
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt` line 1297 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366#-Nm-30BD0iuqvPPG7qhd:-Nm3m1iG617-4Q3E5-cD:br514si) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a26248d264c9045e68c1c7233ff9eceb2245d08/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportSchedulesServiceTest.kt#L1297)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

That's what I am curious about. Why is the new change
```
startTime = timestamp {
  seconds = 48282210000 // January 1, 3500 at 1 PM, America/Los_Angeles
}
```
more preferred than the old one?
```
dateTime {
  year = 9100
  month = 1
  day = 1
  hours = 6
  timeZone = timeZone { id = "America/New_York" }
}
.toTimestamp()
```
</blockquote></details>

I don't want the unit tests to rely on a function that is also used in the actual implementation.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1366)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
