### PR TITLE
Initial duchy code

### PR DESCRIPTION
**Pull request by wfa-hkawalkar**
**Phase 1 - Duchy Terraform**

- [x] “Step 3" - Create the storage bucket. (**storage-bucket.tf**)
- [x] “Step 5” - Create the cluster. (**gke.tf**)
- [x] "step 10a" - Reserve external IPs (**external-ip.tf**)

Details for each step is referred from the link below.
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/kingdom-deployment.md

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878)

**Review by wfa-siyengar — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878)* status: all files reviewed, 3 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @kungfucraig, @SanjayVas, and @TNATALI)

___
*[`src/main/terraform/duchy/gcloud/spanner.tf` line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NPc_cKrCm_WOxGVtY8P:-NPcwd5Q1SirjkFICkKw:bsj646i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e070565d5cc48408c202f60bfd32c4e4d253e654/src/main/terraform/duchy/gcloud/spanner.tf#L29)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Can you see comments on previously abandoned diffs about this flag? https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/842#-NNwcHmyBx_je86VB6s5
</blockquote></details>

Corrected.
___
*[`src/main/terraform/duchy/gcloud/storage-bucket.tf` line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NPcabpt3iQRW943HHdj:-NPcwBAcApJ0PQFZN5F3:bsj646i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e070565d5cc48408c202f60bfd32c4e4d253e654/src/main/terraform/duchy/gcloud/storage-bucket.tf#L20)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Maybe there is a better name? This looks like a domain name...
</blockquote></details>

Corrected.
___
*[`src/main/terraform/duchy/gcloud/storage-bucket.tf` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NPcajhoDr5hL080Fdn_:-NPcwLew0J78op-WWtgK:b-gvolu3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e070565d5cc48408c202f60bfd32c4e4d253e654/src/main/terraform/duchy/gcloud/storage-bucket.tf#L21)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I see the cluster is located at us-central1, shouldn't this be "US"?
</blockquote></details>

Corrected, thanks for the keen eye.

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 1 of 3 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl, @kungfucraig, @SanjayVas, @TNATALI, and @wfa-siyengar)

**Review by bdomen-ggl — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, @TNATALI, @wfa-hkawalkar, and @wfa-siyengar)

___
*[`src/main/terraform/duchy/gcloud/gke.tf` line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NProo9F0d8G2mAJERSN:-NProo9F0d8G2mAJERSO:bpjiwb6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb5a45245dd2db841fc8bf75d352aa8168803131/src/main/terraform/duchy/gcloud/gke.tf#L24)):*
> ```HCL
> 
>   initial_node_count = 1
>   node_config {
> ```

FYI: Think you're on this, but this should use a similar configuration and same Terraform-ness as the Kingdom PR.
Notably to use the `google_container_node_pool` resource instead of the `node_config` parameter and to add the autoscaling and oath scope configs. The actual autoscaling values are a little different though (2 to 4, default 2 and uses the e2-standard-2 machine type).
___
*[`src/main/terraform/duchy/gcloud/spanner.tf` line 21 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NPe3zH33BvhQqfA6SZD:-NPe3zH33BvhQqfA6SZE:bql6prt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb5a45245dd2db841fc8bf75d352aa8168803131/src/main/terraform/duchy/gcloud/spanner.tf#L21)):*
> ```HCL
> resource "google_spanner_instance" "duchy_db" {
>   config       = "regional-${var.region}"
>   display_name = "duchy_spanner_instance"
> ```

@SanjayVas Just to check, should we use a different spanner instance for Duchy vs Kingdom? It looks like we currently have the Duchy and Kingdom databases in the same Spanner instance `dev-instance`. I think it would make sense in the deployment to separate them into their own spanner instances.
___
*[`src/main/terraform/duchy/gcloud/spanner.tf` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NPr-7UUB8kR-9qPjYVf:-NPr-7UUB8kR-9qPjYVg:b-iemqxu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb5a45245dd2db841fc8bf75d352aa8168803131/src/main/terraform/duchy/gcloud/spanner.tf#L31)):*
> ```HCL
>   deletion_protection = true
> 
>   depends_on = [google_spanner_instance.duchy_db]
> ```

FYI: You might be on this, but similar comment from the Kingdom PR. Depends on isn't necessary since there's a reference to the resource in the `instance` parameter.

**Review by duliomatos1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @TNATALI, @wfa-hkawalkar, and @wfa-siyengar)

___
*[`src/main/terraform/duchy/gcloud/external-ip.tf` line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NPsOGu83oPJAz9E9v1u:-NPsOGu83oPJAz9E9v1v:b-lw40o6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb5a45245dd2db841fc8bf75d352aa8168803131/src/main/terraform/duchy/gcloud/external-ip.tf#L1)):*
> ```HCL
> # Copyright 2020 The Cross-Media Measurement Authors
> ```

Should update the year at new files
`# Copyright 2023 The Cross-Media Measurement Authors`



_Code quote:_
```HCL
# Copyright 2020 The Cross-Media Measurement Authors
```

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @TNATALI, and @wfa-siyengar)

___
*[`src/main/terraform/duchy/gcloud/gke.tf` line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NProo9F0d8G2mAJERSN:-NPtkZLgCzYeWiYyCf0p:byetske) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb5a45245dd2db841fc8bf75d352aa8168803131/src/main/terraform/duchy/gcloud/gke.tf#L24)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

FYI: Think you're on this, but this should use a similar configuration and same Terraform-ness as the Kingdom PR.
Notably to use the `google_container_node_pool` resource instead of the `node_config` parameter and to add the autoscaling and oath scope configs. The actual autoscaling values are a little different though (2 to 4, default 2 and uses the e2-standard-2 machine type).
</blockquote></details>

Awaiting approval and merge of kingdom, post which we will raise PR for Duchy. And yes it will all be on line.

**Review by bdomen-ggl — COMMENTED** [review]
Looks pretty close just a couple notes around the cluster creation.

Also, it was noted as another task within step 5 in the doc, but we need a service account similar to the previous PR.
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b3c439bc2f5c024c466ec88fcacf82d81f26f497/src/main/terraform/kingdom/gcloud/service-account.tf

In the Duchy case, you need to give the service account access to the bucket (probably spanner too?).

```
Create an additional service account for storage, granting it the Storage Object Admin role on the Storage bucket.
See Granting Cloud Storage bucket access.
```

> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-:-NQ2Cz4p71-wFuOGVgJQ:brftm35)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @TNATALI, @wfa-hkawalkar, and @wfa-siyengar)

___
*[`src/main/terraform/duchy/gcloud/gke.tf` line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NProo9F0d8G2mAJERSN:-NQ29NGu0Qjm0IRBb40v:bzc5oyl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb5a45245dd2db841fc8bf75d352aa8168803131/src/main/terraform/duchy/gcloud/gke.tf#L24)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

Awaiting approval and merge of kingdom, post which we will raise PR for Duchy. And yes it will all be on line.
</blockquote></details>

Looks like it's still using the `node_config` instead of the `google_container_cluster`.
___
*[`src/main/terraform/duchy/gcloud/gke.tf` line 30 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NQ2BQsbBNt0LX_qnSb3:-NQ2BQsbBNt0LX_qnSb4:bpsy39v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c61b2c903a6e4099aeaee1ff85504781c6901f93/src/main/terraform/duchy/gcloud/gke.tf#L30)):*
> ```HCL
> }
> 
> resource "google_container_cluster" "worker" {
> ```

Instead of creating two clusters, we should be creating a cluster and a node pool similar in the previous PR.

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b3c439bc2f5c024c466ec88fcacf82d81f26f497/src/main/terraform/kingdom/gcloud/gke.tf

Specifically, one `google_container_cluster` with one `google_container_node_pool` associated to that container and no `node_config` in the `google_container_cluster`.

The idea is that since this is in a module, we can call the module multiple times to easily create multiple duchies if desired rather than create multiple duchies (or clusters in this case) in the module.
___
*[`src/main/terraform/duchy/gcloud/gke.tf` line 38 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NQ28YJeBHRjxDAlgggU:-NQ28YJeBHRjxDAlgggV:b-t27xtm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c61b2c903a6e4099aeaee1ff85504781c6901f93/src/main/terraform/duchy/gcloud/gke.tf#L38)):*
> ```HCL
> 
>   cluster_autoscaling {
>     enabled = false
> ```

We should have autoscaling right? I see this line when creating the cluster:
```
  --num-nodes=3 --enable-autoscaling --min-nodes=3 --max-nodes=6 \
```
___
*[`src/main/terraform/duchy/gcloud/spanner.tf` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NPr-7UUB8kR-9qPjYVf:-NQ2A1ae4bC2vQesKUTO:b-1g10fz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb5a45245dd2db841fc8bf75d352aa8168803131/src/main/terraform/duchy/gcloud/spanner.tf#L31)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

FYI: You might be on this, but similar comment from the Kingdom PR. Depends on isn't necessary since there's a reference to the resource in the `instance` parameter.
</blockquote></details>

Oops, I guess I accidentally resolved the comment, but don't need the `depends_on` attribute.

**Review by duliomatos1 — APPROVED** [review]
LGTM I think @bdomen-ggl may have some items still for the final approval

> Reviewed 1 of 5 files at r9, 1 of 6 files at r10, 1 of 1 files at r11, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-:-NQ6P3uQ7I0x0xTyxH5X:bpspf6m)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @TNATALI, @wfa-hkawalkar, and @wfa-siyengar)

**Review by bdomen-ggl — COMMENTED** [review]
> Reviewed 1 of 6 files at r10, 1 of 1 files at r11, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @TNATALI, @wfa-hkawalkar, and @wfa-siyengar)

___
*[`src/main/terraform/duchy/gcloud/spanner.tf` line 21 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NPe3zH33BvhQqfA6SZD:-NQ6PYYS5g7m_xhtbWa3:b-rdzajd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb5a45245dd2db841fc8bf75d352aa8168803131/src/main/terraform/duchy/gcloud/spanner.tf#L21)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

@SanjayVas Just to check, should we use a different spanner instance for Duchy vs Kingdom? It looks like we currently have the Duchy and Kingdom databases in the same Spanner instance `dev-instance`. I think it would make sense in the deployment to separate them into their own spanner instances.
</blockquote></details>

Summary from meeting discussion:
```
Normally there will be one spanner instance per entity since each entity will be managing a single kingdom or duchy. However, spinning up spanner instances is expensive and to save costs we want to consolidate all the DBs into the same instance.
```

There are some clever things we can do here, but to keep it simple we can probably assume that Kingdom is deploy successfully first via the GitHub Action. If you decide to take a simpler route like this with assumptions, please make some notes somewhere (probably a common deployment doc).

**Review by wfa-hkawalkar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @TNATALI, and @wfa-siyengar)

___
*[`src/main/terraform/duchy/gcloud/spanner.tf` line 21 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NPe3zH33BvhQqfA6SZD:-NQ9NzjS5nbLkdPrsBzh:b-w76rh7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb5a45245dd2db841fc8bf75d352aa8168803131/src/main/terraform/duchy/gcloud/spanner.tf#L21)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Summary from meeting discussion:
```
Normally there will be one spanner instance per entity since each entity will be managing a single kingdom or duchy. However, spinning up spanner instances is expensive and to save costs we want to consolidate all the DBs into the same instance.
```

There are some clever things we can do here, but to keep it simple we can probably assume that Kingdom is deploy successfully first via the GitHub Action. If you decide to take a simpler route like this with assumptions, please make some notes somewhere (probably a common deployment doc).
</blockquote></details>

@bdomen-ggl, we will remove db.tf from duchy then.

**Comment by wfa-hkawalkar** [comment]
@bdomen-ggl , as requested db.tf is removed from duchy. please take and look on it.

**Review by wfa-siyengar — APPROVED** [review]
> Reviewed 1 of 5 files at r9, 2 of 6 files at r10, 1 of 1 files at r11, 5 of 6 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @TNATALI)

___
*[`src/main/terraform/duchy/gcloud/spanner.tf` line 21 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878#-NPe3zH33BvhQqfA6SZD:-NQA2yZQBYq8PhKV_pEB:bvioq75) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb5a45245dd2db841fc8bf75d352aa8168803131/src/main/terraform/duchy/gcloud/spanner.tf#L21)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

@bdomen-ggl, we will remove db.tf from duchy then.
</blockquote></details>

File db.tf is removed. request approval.

**Review by wfa-siyengar — APPROVED** [review]
> Reviewed 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @TNATALI)

**Review by bdomen-ggl — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/878)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @TNATALI)

**Pull request merged**
