### PR TITLE
refactor[edp-simulator]: Consolidate logging of Requisition refusal

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1759)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1759)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1759#-O4II8ah6WSdl5WCiIx0:-O4II8ah6WSdl5WCiIx1:b42bkrh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/288a4e8cb20bb8da15f0b8e74fe0f1a2910e82de/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L165)):*
> ```Kotlin
> 
>         logger.log(Level.WARNING, e) { "Refusing Requisition ${requisition.name}" }
>         refuseRequisition(requisition.name, e.justification, e.message)
> ```

No need for default message anymore?



_Code quote:_
```Kotlin
e.message
```

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @Marco-Premier from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1759)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1759)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1759)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
