### PR TITLE
Update duchy computationsService proto.

### PR DESCRIPTION
**Pull request by wangyaopw**
The changes are to support requisition related oeprations.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @wangyaopw, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/duchy/computations_service.proto, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61#-M_c9enS5jS3QW-fgcYI:-M_c9enS5jS3QW-fgcYJ:b-nw51w9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83b96c829b84476c71e89d195ddafe43c280a90e/src/main/proto/wfa/measurement/internal/duchy/computations_service.proto#L72)):*
> ```
>   // Looks up a requisition by external requisition key.
>   rpc LookupRequisition(LookupRequisitionRequest)
> ```
This appears to actually look up a `ComputationToken` given a public API `Requisition` resource key.

Also grammar nit: the verb phrase is "look up" (as opposed to the noun "lookup"), so this should be `LookUp`.
___
*[src/main/proto/wfa/measurement/internal/duchy/computations_service.proto, line 245 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61#-M_cA7af2jAGbQiH4YrJ:-M_cA7af2jAGbQiH4YrK:b937f7p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83b96c829b84476c71e89d195ddafe43c280a90e/src/main/proto/wfa/measurement/internal/duchy/computations_service.proto#L245)):*
> ```
> // External key of a requisition.
> ```
Document that this is the key of a `Requisition` resource from the public API (as opposed to from the system API).

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/duchy/computations_service.proto, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61#-M_c9enS5jS3QW-fgcYI:-M_cDfhx4u2Svsk4e2d7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83b96c829b84476c71e89d195ddafe43c280a90e/src/main/proto/wfa/measurement/internal/duchy/computations_service.proto#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>   // Looks up a requisition by external requisition key.
>   rpc LookupRequisition(LookupRequisitionRequest)
> ```
This appears to actually look up a `ComputationToken` given a public API `Requisition` resource key.

Also grammar nit: the verb phrase is "look up" (as opposed to the noun "lookup"), so this should be `LookUp`.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/duchy/computations_service.proto, line 245 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61#-M_cA7af2jAGbQiH4YrJ:-M_cE34U9770sb0QeXFd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83b96c829b84476c71e89d195ddafe43c280a90e/src/main/proto/wfa/measurement/internal/duchy/computations_service.proto#L245)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> // External key of a requisition.
> ```
Document that this is the key of a `Requisition` resource from the public API (as opposed to from the system API).
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/duchy/computations_service.proto, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61#-M_c9enS5jS3QW-fgcYI:-M_cJjR56vhV57D2vYWM:b-fx2gh7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83b96c829b84476c71e89d195ddafe43c280a90e/src/main/proto/wfa/measurement/internal/duchy/computations_service.proto#L72)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you want to rename the method too? `LookUpRequisition` seems to imply that a `Requisition` is what's returned. Maybe `LookUpRequisitionComputationToken`?

Or since Get methods on internal services don't need to follow the standard method definition from AIPs, I'd even be okay with treating this as an overload of `GetComputationToken` (e.g. put a oneof in the request that you specify either the computation ID or the requisition resource key). WDYT?

**Review by zachcwc — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @kungfucraig, @SanjayVas, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/duchy/computations_service.proto, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61#-M_c9enS5jS3QW-fgcYI:-M_dcKzb-sZQNlvnVLOp:b-6i61ne) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83b96c829b84476c71e89d195ddafe43c280a90e/src/main/proto/wfa/measurement/internal/duchy/computations_service.proto#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Did you want to rename the method too? `LookUpRequisition` seems to imply that a `Requisition` is what's returned. Maybe `LookUpRequisitionComputationToken`?

Or since Get methods on internal services don't need to follow the standard method definition from AIPs, I'd even be okay with treating this as an overload of `GetComputationToken` (e.g. put a oneof in the request that you specify either the computation ID or the requisition resource key). WDYT?
</blockquote></details>

Sounds a good idea to me. Updated.

**Review by SanjayVas — APPROVED** [review]
> Add two new methods

nit: no longer accurate

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61#-:-M_f_kh04UT3YeLzd92Y:b-al7nt9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by wangyaopw — COMMENTED** [review]
updated

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61#-:-M_fc-4Z0OOvNW11LbvM:bvnrpcm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/proto/wfa/measurement/internal/duchy/computations_service.proto, line 261 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61#-M_gwj0r4tSK7WekG3sT:-M_gwj0r4tSK7WekG3sU:b-bxm35l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed1c658d06c5229d2538a8314a0d793a69c12a9/src/main/proto/wfa/measurement/internal/duchy/computations_service.proto#L261)):*
> ```protobuf
>   // The blob path where the data of the requisition is stored.
>   // Required. Must be non-empty.
>   string blob_path_added = 3;
> ```

Just blob_path?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/proto/wfa/measurement/internal/duchy/computations_service.proto, line 261 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61#-M_gwj0r4tSK7WekG3sT:-M_gxQ97ErQF6Q1zT5Q0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed1c658d06c5229d2538a8314a0d793a69c12a9/src/main/proto/wfa/measurement/internal/duchy/computations_service.proto#L261)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Just blob_path?
</blockquote></details>

Done.

**Pull request merged**
