### PR TITLE
Add operation documentations for AWS Duchy

### PR DESCRIPTION
**Pull request by YuhongWang-Amazon**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1312)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1312)* status: all files reviewed, 4 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`docs/eks/duchy-deployment.md` line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1312#-Ni11whE8Ohwd6h_nByd:-Ni11whE8Ohwd6h_nBye:b-xb9bp1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/134c40205a3fbd105c5d517754f30349418fd7b9/docs/eks/duchy-deployment.md#L140)):*
> ```Markdown
>   --define s3_region=us-west-2 \
>   --define duchy_cert_id=Yq3IyKAQ5Qc \
>   --define container_registry=ghcr.io \
> ```

nit: keep the container/image options together, meaning put this right above `image_repo_prefix`.
___
*[`docs/eks/duchy-deployment.md` line 314 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1312#-Ni12Q_SB0n7U3ZpDkI-:-Ni12Q_SB0n7U3ZpDkI0:brh34t1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/134c40205a3fbd105c5d517754f30349418fd7b9/docs/eks/duchy-deployment.md#L314)):*
> ```Markdown
> 
> For example
> ```shell
> ```

nit: Leave newlines around code fences. This is technically required by the spec, though most Markdown implementations will still render correctly. Some other tools which use stricter Markdown parsing may get confused however.
___
*[`docs/eks/metrics-deployment.md` line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1312#-Ni13BJC2GaSmI3Nae6E:-Ni13BJC2GaSmI3Nae6F:bh96s0r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/134c40205a3fbd105c5d517754f30349418fd7b9/docs/eks/metrics-deployment.md#L51)):*
> ```Markdown
> set up Amazon Managed Grafana for use with Amazon Managed Service for Prometheus
> 
> ## Setup EKS cluster to send metric to AMP
> ```

nit: "setup" is a noun. You want the verb phrase "set up" here.



_Suggestion:_
```Markdown
Set up
```
___
*[`src/main/terraform/aws/examples/duchy/main.tf` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1312#-Ni149yP7UfpIDKVm4Ma:-Ni149yQA1FWuH9u3jHp:bkz4om4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/134c40205a3fbd105c5d517754f30349418fd7b9/src/main/terraform/aws/examples/duchy/main.tf#L31)):*
> ```HCL
>   duchy_name  = "duchy"
>   vpc_name    = "duchy-dev"
>   bucket_name = "duchy-dev-bucket"
> ```

Perhaps these should be vars to indicate that they will likely need to differ for each user of this example. This is especially true of the S3 bucket if it follows the same uniqueness rules as GCS (i.e. not scoped to a single account).



_Code quote:_
```HCL
  duchy_name  = "duchy"
  vpc_name    = "duchy-dev"
  bucket_name = "duchy-dev-bucket"
```

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1312)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/terraform/aws/examples/duchy/main.tf` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1312#-Ni149yP7UfpIDKVm4Ma:-NiALj2L-dfyxwN_lJlZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/134c40205a3fbd105c5d517754f30349418fd7b9/src/main/terraform/aws/examples/duchy/main.tf#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Perhaps these should be vars to indicate that they will likely need to differ for each user of this example. This is especially true of the S3 bucket if it follows the same uniqueness rules as GCS (i.e. not scoped to a single account).
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1312)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Pull request merged**
