### PR TITLE
Marcopremier panelexchange kindtest refactor

### PR DESCRIPTION
**Pull request by Marco-Premier**
Delete DoubleBlindWorkflowTest in favor of EmpyClusterPanelMatchCorrectnessTest.
The newly created class holds the logic to setup a k8s local environment and creates resources needed to run the Panel Exchange: model provider and data provider.
AbstractPanelMatchCorrectnessTest wraps the tests that are executed by the PanelMatchSimulator.

the above mimics the logic we already have for the EmptyClusterCorrectnessTest.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328)* status: 15 of 16 files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/panelmatch/PanelMatchCorectnessTestDataProvider.kt` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328#-NipYJCR8rCQPE7Fqgxb:-NipYJCS70K1ZxS7C1QO:bwybg6i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c681f49ba162074be9e6b2bd4009138b4d26adf/src/main/kotlin/org/wfanet/measurement/loadtest/panelmatch/PanelMatchCorectnessTestDataProvider.kt#L31)):*
> ```Kotlin
> 
> /** Provide utility functions to set up workflows in [PanelMatchSimulator]. */
> object PanelMatchCorectnessTestDataProvider {
> ```

nit: maybe come up with a name that doesn't include "DataProvider". From the name alone, I assumed this was supposed to be acting as the `DataProvider` in the panel exchange.



_Code quote:_
```Kotlin
PanelMatchCorectnessTestDataProvider
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/panelmatch/PanelMatchSimulator.kt` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328#-NipYZKoC6iVtCibgGM1:-NipYZKoC6iVtCibgGM2:b2h2xux) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c681f49ba162074be9e6b2bd4009138b4d26adf/src/main/kotlin/org/wfanet/measurement/loadtest/panelmatch/PanelMatchSimulator.kt#L57)):*
> ```Kotlin
> import org.wfanet.panelmatch.integration.testing.parsePlaintextResults
> 
> /** Simulator for PanelMatch flows. */
> ```

Which entity is this simulating? Or is it acting as both EDP and MP?

For the life of a Measurement tests, our simulator are named after the entity being simulated (EdpSimulator, MeasurementConsumerSimulator).
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/panelmatchresourcesetup/PanelMatchResourceSetup.kt` line 318 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328#-NipZ-s2DeLcXs61vCVg:-NipZ-s2DeLcXs61vCVh:bfoq4pi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c681f49ba162074be9e6b2bd4009138b4d26adf/src/main/kotlin/org/wfanet/measurement/loadtest/panelmatchresourcesetup/PanelMatchResourceSetup.kt#L318)):*
> ```Kotlin
>     const val AKID_PRINCIPAL_MAP_FILE = "authority_key_identifier_to_principal_map.textproto"
>     const val BAZEL_RC_FILE = "resource-setup.bazelrc"
>     var dataProviderId: Long = 0L
> ```

Why does this need public class-level mutable variables? Shouldn't the EDP and MP be at the instance level at the very least?
___
*[`src/test/kotlin/org/wfanet/panelmatch/integration/k8s/AbstractPanelMatchCorrectnessTest.kt` line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328#-Nip_R_o8sDMp4u5cwNA:-Nip_R_o8sDMp4u5cwNB:b-kqy25t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c681f49ba162074be9e6b2bd4009138b4d26adf/src/test/kotlin/org/wfanet/panelmatch/integration/k8s/AbstractPanelMatchCorrectnessTest.kt#L107)):*
> ```Kotlin
>     private val WORKSPACE_PATH: Path = Paths.get("wfa_measurement_system")
> 
>     @JvmStatic protected val KINGDOM_INTERNAL_DEPLOYMENT_NAME = "gcp-kingdom-data-server-deployment"
> ```

Do we actually need all these to be defined here an accessible by subclasses? For Measurement tests, these are only needed in the "empty cluster" impl in order to populate the cluster.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 14 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/panelmatch/PanelMatchCorectnessTestDataProvider.kt` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328#-NipYJCR8rCQPE7Fqgxb:-NitdnNjAc3rEFQo2A_n:big4bmn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c681f49ba162074be9e6b2bd4009138b4d26adf/src/main/kotlin/org/wfanet/measurement/loadtest/panelmatch/PanelMatchCorectnessTestDataProvider.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: maybe come up with a name that doesn't include "DataProvider". From the name alone, I assumed this was supposed to be acting as the `DataProvider` in the panel exchange.
</blockquote></details>

also nit: correctness is mispelled
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/panelmatch/PanelMatchCorectnessTestDataProvider.kt` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328#-Nite7vZ0w4XFhZMvQ9s:-Nite7vZ0w4XFhZMvQ9t:b-ihtu8d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c681f49ba162074be9e6b2bd4009138b4d26adf/src/main/kotlin/org/wfanet/measurement/loadtest/panelmatch/PanelMatchCorectnessTestDataProvider.kt#L67)):*
> ```Kotlin
>   }
> 
>   private fun getInitialDataProviderInputsForFullWithPreprocessing(): Map<String, ByteString> {
> ```

You could combine all these getInitialInputs steps by inputing a list of input blobs you want written. Each blob key then maps to a function to generate that data. You could make it common across mp and edp.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/panelmatch/PanelMatchSimulator.kt` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328#-NipYZKoC6iVtCibgGM1:-Nj8KTXlDc2bqE40Kjn4:b-i9x1sj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c681f49ba162074be9e6b2bd4009138b4d26adf/src/main/kotlin/org/wfanet/measurement/loadtest/panelmatch/PanelMatchSimulator.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Which entity is this simulating? Or is it acting as both EDP and MP?

For the life of a Measurement tests, our simulator are named after the entity being simulated (EdpSimulator, MeasurementConsumerSimulator).
</blockquote></details>

It's actually both. Meaning that EDP and MP have their own daemon running that fetch recurring exchange. The simulator initialize the input, wait for the flow to complete and later check the output.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/panelmatchresourcesetup/PanelMatchResourceSetup.kt` line 318 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328#-NipZ-s2DeLcXs61vCVg:-Nj8Nxqj1s1HUKTKOzV0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c681f49ba162074be9e6b2bd4009138b4d26adf/src/main/kotlin/org/wfanet/measurement/loadtest/panelmatchresourcesetup/PanelMatchResourceSetup.kt#L318)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why does this need public class-level mutable variables? Shouldn't the EDP and MP be at the instance level at the very least?
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/panelmatch/integration/k8s/AbstractPanelMatchCorrectnessTest.kt` line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328#-Nip_R_o8sDMp4u5cwNA:-Nj8PVWS565iMjImEa2U:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c681f49ba162074be9e6b2bd4009138b4d26adf/src/test/kotlin/org/wfanet/panelmatch/integration/k8s/AbstractPanelMatchCorrectnessTest.kt#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we actually need all these to be defined here an accessible by subclasses? For Measurement tests, these are only needed in the "empty cluster" impl in order to populate the cluster.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 2 of 3 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 6 of 16 files at r1, 2 of 3 files at r3, 8 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1328)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

**Comment by SanjayVas** [comment]
This introduced a new compiler warning:

> ```
> INFO: From KotlinCompile //src/main/kotlin/org/wfanet/measurement/loadtest/panelmatch:simulator { kt: 2, java: 0, srcjars: 0 } for k8:
> src/main/kotlin/org/wfanet/measurement/loadtest/panelmatch/PanelMatchSimulator.kt:126:33: warning: unnecessary non-null assertion (!!) on a non-null receiver of type ByteString
>       parsePlaintextResults(blob!!.parseDelimitedMessages(keyedDecryptedEventDataSet {})).map {
>                                 ^
> ```

**Pull request merged**
