### PR TITLE
Specify request_id in CreateMeasurement and CreateEventGroup requests.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023)

**Review by riemanli — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 4047 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023#-NWDkCle-WxLWIbF3IcS:-NWDkCle-WxLWIbF3IcT:b-kx6bo4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c4025c0a82b47e0603c3a468599e097ee4f1995/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L4047)):*
> ```Kotlin
>     private val ENCRYPTED_REQUISITION_SPEC_FIELD_DESCRIPTOR =
>       Measurement.DataProviderEntry.Value.getDescriptor()
>         .findFieldByNumber(ENCRYPTED_REQUISITION_SPEC_FIELD_NUMBER)
> ```

This is very nice! I wonder if you could do the same for v2alpha metrics service test in this PR.



_Code quote:_
```Kotlin
  companion object {
    private val MEASUREMENT_SPEC_FIELD_DESCRIPTOR =
      Measurement.getDescriptor().findFieldByNumber(Measurement.MEASUREMENT_SPEC_FIELD_NUMBER)
    private val ENCRYPTED_REQUISITION_SPEC_FIELD_DESCRIPTOR =
      Measurement.DataProviderEntry.Value.getDescriptor()
        .findFieldByNumber(ENCRYPTED_REQUISITION_SPEC_FIELD_NUMBER)
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 169 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023#-NWDgrdeCD0uv-6FESDt:-NWDgrdeCD0uv-6FESDu:bacry79) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c4025c0a82b47e0603c3a468599e097ee4f1995/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L169)):*
> ```Kotlin
> import org.wfanet.measurement.internal.reporting.v2.timeInterval as internalTimeInterval
> import org.wfanet.measurement.reporting.service.api.InMemoryEncryptionKeyPairStore
> import org.wfanet.measurement.reporting.service.api.v2alpha.RequestIdMatcher.Companion.requestIdEq
> ```

Does this import the private class `RequestIdMatcher` at the bottom? What's rationale behind this?
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 1372 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023#-NWDlAhFBuQpRzE1E-5T:-NWDlAhFBuQpRzE1E-5U:bpt5p2j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4d03b20db41f3296a74dd31c4bf5e277ff1536c/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L1372)):*
> ```Kotlin
>     onBlocking { createMeasurement(any()) }
>       .thenAnswer {
>         val request = it.arguments[0] as CreateMeasurementRequest
> ```

Just curious, is mapping the request to a measurement not a correct way to do?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 4047 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023#-NWDkCle-WxLWIbF3IcS:-NWEFbSCDyb-dfS3tQXV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c4025c0a82b47e0603c3a468599e097ee4f1995/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L4047)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

This is very nice! I wonder if you could do the same for v2alpha metrics service test in this PR.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 169 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023#-NWDgrdeCD0uv-6FESDt:-NWEA0qbEoDGYihpBFiA:b-quwp05) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c4025c0a82b47e0603c3a468599e097ee4f1995/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L169)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Does this import the private class `RequestIdMatcher` at the bottom? What's rationale behind this?
</blockquote></details>

For the same reason that we import other Mockito ArgumentMatcher factories (e.g. `org.mockito.kotlin.eq`): improved readability when using the matcher. We generally don't want to introduce non-extension functions as top-level declarations in a package (we have quite a few in our codebase that really should be inside objects), so we define the factory in the companion object and then import it for improved readability in this file.

Usage example:

```kotlin
        createMeasurement(
          requestIdEq(INTERNAL_PENDING_UNION_ALL_REACH_MEASUREMENT.cmmsCreateMeasurementRequestId)
        )
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 1372 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023#-NWDlAhFBuQpRzE1E-5T:-NWECeLe1whoQnfQkR0-:b-5hddda) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4d03b20db41f3296a74dd31c4bf5e277ff1536c/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L1372)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Just curious, is mapping the request to a measurement not a correct way to do?
</blockquote></details>

This is still effectively returning the appropriate response based on the request ID. It's just using our custom `ArgumentMatcher` so that we can use `thenReturn`, as that's preferred over `thenAnswer`.

**Review by riemanli — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 169 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023#-NWDgrdeCD0uv-6FESDt:-NWEd-cx1iZ5aiNuB7ZZ:b6vnx2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c4025c0a82b47e0603c3a468599e097ee4f1995/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L169)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

For the same reason that we import other Mockito ArgumentMatcher factories (e.g. `org.mockito.kotlin.eq`): improved readability when using the matcher. We generally don't want to introduce non-extension functions as top-level declarations in a package (we have quite a few in our codebase that really should be inside objects), so we define the factory in the companion object and then import it for improved readability in this file.

Usage example:

```kotlin
        createMeasurement(
          requestIdEq(INTERNAL_PENDING_UNION_ALL_REACH_MEASUREMENT.cmmsCreateMeasurementRequestId)
        )
```
</blockquote></details>

Learned a lot. Thanks!
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 1372 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023#-NWDlAhFBuQpRzE1E-5T:-NWEdCJ7AdpQFXUEGOnN:b-2ror9g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4d03b20db41f3296a74dd31c4bf5e277ff1536c/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L1372)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is still effectively returning the appropriate response based on the request ID. It's just using our custom `ArgumentMatcher` so that we can use `thenReturn`, as that's preferred over `thenAnswer`.
</blockquote></details>

Got it thanks!

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1023)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
