### PR TITLE
Validate certificate path when validating signatures.

### PR DESCRIPTION
**Pull request by SanjayVas**
This also updates EdpSimulator to verify the signed ElGamal public keys from Duchy participants when using the Liquid Legions v2 protocol.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)

https://rally1.rallydev.com/#/?detail=/task/672131374749&fdp=true

### CODE REVIEW

**Comment by SanjayVas** [comment]
Depends on https://github.com/world-federation-of-advertisers/consent-signaling-client/pull/40

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt` line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NI4_XZ63uOQZ4K3oEry:-NI4_XZ63uOQZ4K3oErz:b-xw2mwo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2707c956f1493c4669f3101ec392db50b7a182/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt#L294)):*
> ```Kotlin
>       )
>       DuchyInfo.initializeFromConfig(
>         loadTextProto("duchy_cert_config.textproto", DuchyCertConfig.getDefaultInstance())
> ```

```
loadTextProto("duchy_cert_config.textproto", duchyCertConfig {})
```




_Code quote:_
```Kotlin
loadTextProto("duchy_cert_config.textproto", DuchyCertConfig.getDefaultInstance())
```
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt` line 1082 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NI4ZR_d3E8mrkXb-A7k:-NI4ZR_d3E8mrkXb-A7l:baq3ur7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2707c956f1493c4669f3101ec392db50b7a182/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L1082)):*
> ```Kotlin
>                 "java.lang.Exception: @Mill a nice mill, Computation 1234 failed due to:\n" +
>                   "Cannot verify participation of all DataProviders.\n" +
>                   "Invalid ElGamal public key signature for Duchy DUCHY_TWO"
> ```

```
"Invalid ElGamal public key signature for Duchy $DUCHY_TWO_NAME"
```




_Code quote:_
```Kotlin
"Invalid ElGamal public key signature for Duchy DUCHY_TWO"
```

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)* status: 16 of 33 files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt` line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NI4_XZ63uOQZ4K3oEry:-NI9dzyw1fjuQLv6a7de:b-3m355p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2707c956f1493c4669f3101ec392db50b7a182/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt#L294)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

```
loadTextProto("duchy_cert_config.textproto", duchyCertConfig {})
```

</blockquote></details>

NACK. `getDefaultInstance` is preferred since it returns a singleton rather than constructing a new object.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 15 files at r2, 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)* status: 20 of 33 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 362 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NID8QyS55cGU5ALvHC_:-NID8QyS55cGU5ALvHCa:br6u6l6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3818764ea66d76167d452905f3f5a6dc156f6582/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L362)):*
> ```Kotlin
>     private val TRUSTED_CERTIFICATES =
>       readCertificateCollection(SECRETS_DIR.resolve("all_root_certs.pem")).associateBy {
>         it.subjectKeyIdentifier!!
> ```

see my slack messages -- it seems messy to have some of these be root and some of these be intermediate certs. I'd either prefer separate root cert collections for grpc and consent (which is probably cleanest) or just require everything to be a root cert.

If you want to go with the former, I'm happy with that being a TODO somewhere.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)* status: 19 of 33 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 362 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NID8QyS55cGU5ALvHC_:-NIEGhQ959Ae0JPLKR9A:bw8pkzn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29ddb06661dbc340e6ec9d9a8ea2b19588e78a45/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L362)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

see my slack messages -- it seems messy to have some of these be root and some of these be intermediate certs. I'd either prefer separate root cert collections for grpc and consent (which is probably cleanest) or just require everything to be a root cert.

If you want to go with the former, I'm happy with that being a TODO somewhere.
</blockquote></details>

If we want to codify all trusted certs being root certs, the right place would probably be in SigningCerts in common-jvm as that's the non-test entry point for loading trusted certs. I'm good with doing this as a simplification, it just means we should also note it in the setup docs. In fact, some of our docs might already use the terms "root" and "CA" interchangeably.

In practice, most integrators will probably just end up using a single cloud CA for all their certs.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)* status: 19 of 33 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt` line 362 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NID8QyS55cGU5ALvHC_:-NIETRPa6g3Go6RrpsKM:b-vbrxgo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29ddb06661dbc340e6ec9d9a8ea2b19588e78a45/src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessLifeOfAReportIntegrationTest.kt#L362)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If we want to codify all trusted certs being root certs, the right place would probably be in SigningCerts in common-jvm as that's the non-test entry point for loading trusted certs. I'm good with doing this as a simplification, it just means we should also note it in the setup docs. In fact, some of our docs might already use the terms "root" and "CA" interchangeably.

In practice, most integrators will probably just end up using a single cloud CA for all their certs.
</blockquote></details>

Created https://github.com/world-federation-of-advertisers/common-jvm/pull/173

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 9 of 15 files at r2, 3 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)* status: 32 of 33 files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt` line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NI4_XZ63uOQZ4K3oEry:-NIIoBmB95hd3S6W-Axr:bb7p5eq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af2707c956f1493c4669f3101ec392db50b7a182/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt#L294)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

NACK. `getDefaultInstance` is preferred since it returns a singleton rather than constructing a new object.
</blockquote></details>

thx!
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 200 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIIobzD7bxrdvs73NQy:-NIIobzD7bxrdvs73NQz:bbpsoqb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7191ccfe5751e150d38b17340bc10638b3439177/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L200)):*
> ```Kotlin
> 
>     val signedRequisitionSpec: SignedData =
>       decryptRequisitionSpec(requisition.encryptedRequisitionSpec, edpData.encryptionKey)
> ```

this too could throw a `GeneralSecurityException` -- I suggest catching that
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 216 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIIqWYx41y1W6QLY460:-NIIqWYx41y1W6QLY461:bsf2vxj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7191ccfe5751e150d38b17340bc10638b3439177/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L216)):*
> ```Kotlin
>   private val certificatesServiceMock: CertificatesCoroutineImplBase = mockService {
>     onBlocking {
>         getCertificate(eq(getCertificateRequest { name = MEASUREMENT_CONSUMER_CERTIFICATE.name }))
> ```

whats the purpose of `eq` here? Isn't this the default behavior?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)* status: 32 of 33 files reviewed, 5 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 240 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIJ836yAI1OWFJzJzg8:-NIJ836yAI1OWFJzJzg9:byistpn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7191ccfe5751e150d38b17340bc10638b3439177/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L240)):*
> ```Kotlin
>     // consider having a mapping of Duchy to issuer certificate.
>     val trustedIssuer =
>       trustedCertificates[checkNotNull(duchyX509Certificate.authorityKeyIdentifier)]
> ```

yeah - might be better to have a `Map<ResourceKey, Map<AKI, X509Certificate>>` wdyt?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 304 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIJ8kXd1F7PBudVzDkU:-NIJ8kXd1F7PBudVzDkV:buabk2j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7191ccfe5751e150d38b17340bc10638b3439177/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L304)):*
> ```Kotlin
>           }
>           if (protocols.any { it.hasLiquidLegionsV2() }) {
>             for (duchyEntry in requisition.duchiesList) {
> ```

this will attempt to fullfill the refusedRequisition. wdyt about doing it this way instead?
```
val invalidDuchiesStatus = requistions.duchiesList.any{
   ....
}
if (invalidDuchiesStatus) {
   refuseRequisition(...)
} else {
   duchyFulfillRequisitionForReachAndFrequencyMeasurement(...)
}
```

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 321 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIJ9iUbB5TArKM6CkpU:-NIJ9iUbB5TArKM6CkpV:bxu2zbz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7191ccfe5751e150d38b17340bc10638b3439177/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L321)):*
> ```Kotlin
>                   e.message.orEmpty()
>                 )
>                 continue
> ```

this continue doesn't do anything, since its at the end of a for loop.

Can you add a test that refuse was called once and fulfill zero times for invalid duchies?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)* status: 32 of 33 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 240 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIJ836yAI1OWFJzJzg8:-NIYul1K-Q0PW_0M9Rnb:b-1pggai) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7191ccfe5751e150d38b17340bc10638b3439177/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L240)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - might be better to have a `Map<ResourceKey, Map<AKI, X509Certificate>>` wdyt?
</blockquote></details>

This comment is basically indicating that it's what someone might want to do in a real production environment, but that we're not going to bother doing it for tests.

My instinct for how a real EDP would do this is to have a separate DB or config file with resource key to AKID mapping, similar to what's used by the principal interceptors but in reverse.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 304 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIJ8kXd1F7PBudVzDkU:-NIYvfuR02KkceAV_NPC:bl7jf4t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7191ccfe5751e150d38b17340bc10638b3439177/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L304)):*
> this will attempt to fullfill the refusedRequisition

There's a `continue` to go to the next item in the for loop after refusal so that it doesn't hit the fulfillment code.

The reason for writing it this way is to have a single log statement at the end of the loop body to cover unhandled protocols.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 321 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIJ9iUbB5TArKM6CkpU:-NIYvx11DVleTLrHXvlq:b-gh3de8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7191ccfe5751e150d38b17340bc10638b3439177/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L321)):*
> this continue doesn't do anything, since its at the end of a for loop.

It's not at the end of a for loop. It's before the call to fulfill.

I can see about adding tests. EdpSimulatorTest unfortunately doesn't cover very much, so need to set up test cases from scratch :(
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 216 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIIqWYx41y1W6QLY460:-NIYxDOC9msY7VIkMw9V:b51oib3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7191ccfe5751e150d38b17340bc10638b3439177/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L216)):*
It's safer to always use argument matchers as there are cases where they are required, e.g. if you have multiple arguments to the stubbed method.

From [JavaDoc for ArgumentMatchers](https://javadoc.io/static/org.mockito/mockito-core/3.2.0/org/mockito/ArgumentMatchers.html):

> **Warning**:
> If you are using argument matchers, **all arguments** have to be provided by matchers

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)* status: 27 of 36 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 200 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIIobzD7bxrdvs73NQy:-NId8a5J6wk43jL7Vsuo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7191ccfe5751e150d38b17340bc10638b3439177/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L200)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this too could throw a `GeneralSecurityException` -- I suggest catching that
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 304 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIJ8kXd1F7PBudVzDkU:-NId7yQiBIikKy9TWBoy:b-f82bjj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7191ccfe5751e150d38b17340bc10638b3439177/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L304)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> this will attempt to fullfill the refusedRequisition

There's a `continue` to go to the next item in the for loop after refusal so that it doesn't hit the fulfillment code.

The reason for writing it this way is to have a single log statement at the end of the loop body to cover unhandled protocols.
</blockquote></details>

Fixed by moving catch block outside of duchy loop.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 321 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIJ9iUbB5TArKM6CkpU:-NId8QOM2RMY11WhRbys:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7191ccfe5751e150d38b17340bc10638b3439177/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L321)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, I see what you mean. This is applying to the duchies loop and not the requisitions loop.
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)* status: 35 of 36 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 708 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773#-NIrhwa3DXgvvksahK3E:-NIrhwa3DXgvvksahK3F:b5an243) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/604e3ceaab1aef07f60e84f7886153f84ebca7b3/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L708)):*
> ```Kotlin
> 
>     val refuseRequest: RefuseRequisitionRequest =
>       verifyAndCapture(requisitionsServiceMock, RequisitionsCoroutineImplBase::refuseRequisition)
> ```

we should also verify refuseRequisition was only called 1x

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/773)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
