### PR TITLE
Implement public activate account.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt, line 162 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo4pOKl27Tyepx0zV58:-Mo4pOKl27Tyepx0zV59:b-7rayck) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5496ac904cf30d98e2bd5ee5ae7397b1cfc479/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt#L162)):*
> ```Kotlin
>   @Test
>   fun `replaceAccountIdentity with openIdConnectidentity type returns account with same type`():
>     Unit = runBlocking {}
> ```

probably best to have these check for unimplemented for now, right?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountServerInterceptor.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo4wkTt7TY09NwPjhbV:-Mo4wkTt7TY09NwPjhbW:bhj0uo5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5496ac904cf30d98e2bd5ee5ae7397b1cfc479/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountServerInterceptor.kt#L46)):*
> ```
>       if (!fullMethodName.contains(AUTHENTICATE_METHOD_NAME)) {
>         if (fullMethodName.contains(ACTIVATE_ACCOUNT_METHOD_NAME)) {
> ```
We don't want to bind to the method here, but rather allow the service code to check for the expected principal. What we want the interceptor to do is put the authenticated principal into the current context. This requires doing a DB lookup to authenticate the account (hence the `AuthenticateAccount` method).

My apologies, I owe a design doc on these auth parts. I didn't realize you'd need them immediately for activation.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountServerInterceptor.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo4wkTt7TY09NwPjhbV:-Mo56hhP1d-ZThHsinF8:b-21x7fa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5496ac904cf30d98e2bd5ee5ae7397b1cfc479/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountServerInterceptor.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>       if (!fullMethodName.contains(AUTHENTICATE_METHOD_NAME)) {
>         if (fullMethodName.contains(ACTIVATE_ACCOUNT_METHOD_NAME)) {
> ```
We don't want to bind to the method here, but rather allow the service code to check for the expected principal. What we want the interceptor to do is put the authenticated principal into the current context. This requires doing a DB lookup to authenticate the account (hence the `AuthenticateAccount` method).

My apologies, I owe a design doc on these auth parts. I didn't realize you'd need them immediately for activation.
</blockquote></details>

I get what that means for the other methods, but don't I still need to check the method since authenticate just requires the issuer and with activateAccount there is no account to be authenticated yet since it hasn't been activated.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountServerInterceptor.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo4wkTt7TY09NwPjhbV:-Mo5BsZUCNFHsig6zBog:bvyt7cm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5496ac904cf30d98e2bd5ee5ae7397b1cfc479/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountServerInterceptor.kt#L46)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I get what that means for the other methods, but don't I still need to check the method since authenticate just requires the issuer and with activateAccount there is no account to be authenticated yet since it hasn't been activated.
</blockquote></details>

What I mean is that we want the code that indicates what the expected credentials/principal are to live closer to the service method. In the future we could do something like using proto annotations and checking the options from the method descriptor here, but a simpler approach for now would be just to have the interceptor do nothing if there are no credentials and let the method impl throw an exception if it can't find the expected context key.

**Comment by tristanvuong2021** [comment]
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt, line 162 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo4pOKl27Tyepx0zV58:-Mo5S-rp1HtIsVP7CWNs:br7eojk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5496ac904cf30d98e2bd5ee5ae7397b1cfc479/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt#L162)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

probably best to have these check for unimplemented for now, right?
</blockquote></details>

These tests now assert against an error with the TODO comment above them.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountServerInterceptor.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo4wkTt7TY09NwPjhbV:-Mo5SFkuANYdlW8BvwNM:bo6vrhw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5496ac904cf30d98e2bd5ee5ae7397b1cfc479/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountServerInterceptor.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What I mean is that we want the code that indicates what the expected credentials/principal are to live closer to the service method. In the future we could do something like using proto annotations and checking the options from the method descriptor here, but a simpler approach for now would be just to have the interceptor do nothing if there are no credentials and let the method impl throw an exception if it can't find the expected context key.
</blockquote></details>

Modified the interceptor now.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/AccountConstants.kt, line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo5kgOl7q-v6-_zEibb:-Mo5kgOl7q-v6-_zEibc:b61w31i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/851d4f912da8c0b3ccaf5fecfb0984f4254b0dc3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/AccountConstants.kt#L21)):*
> ```Kotlin
> import org.wfanet.measurement.internal.kingdom.Account
> 
> object AccountConstants {
> ```

I don't think this is the right package. This isn't specific to the v2alpha version of the API.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo5jlv9CQSymsgJtz1-:-Mo5jlv9CQSymsgJtz10:bqqpyaa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/851d4f912da8c0b3ccaf5fecfb0984f4254b0dc3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L92)):*
> ```
> this@toAccount
> ```
nit: put `val source = this` before the return. Then you can reference the source without having to use qualified `this`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo5jNFB12oWeFAMU33Z:-Mo5jNFB12oWeFAMU33_:bx417sl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/851d4f912da8c0b3ccaf5fecfb0984f4254b0dc3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L97)):*
> ```
> with
> ```
Why using `with` here? Seems to only make things more confusing w.r.t. what `this` is.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo5jNFB12oWeFAMU33Z:-Mo5pSWH92PtWeq7y2xo:b-fo2i2f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/851d4f912da8c0b3ccaf5fecfb0984f4254b0dc3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt#L97)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> with
> ```
Why using `with` here? Seems to only make things more confusing w.r.t. what `this` is.
</blockquote></details>

Removed with here.

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/AccountConstants.kt, line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo5kgOl7q-v6-_zEibb:-Mo5pX4X9qb25ghTfZgI:b-za7nyy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/851d4f912da8c0b3ccaf5fecfb0984f4254b0dc3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/AccountConstants.kt#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this is the right package. This isn't specific to the v2alpha version of the API.
</blockquote></details>

I moved it to org.wfanet.measurement.api.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt, line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo5y2QS8ov02KD_Ro23:-Mo5y2QT1eKfVg9RgiE7:b-5iro2w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/51b0b4b31d0f6ec32d27949b351e598711b568d2/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt#L99)):*
> ```
>   // TODO("Not yet implemented")
> ```
What are these about?

**Comment by tristanvuong2021** [comment]
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt, line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo5y2QS8ov02KD_Ro23:-Mo69EAv6EFVY4Qohm5H:bz4by5i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/51b0b4b31d0f6ec32d27949b351e598711b568d2/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>   // TODO("Not yet implemented")
> ```
What are these about?
</blockquote></details>

Just listing out the tests I will have to do later since those methods aren't implemented yet.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt, line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo5y2QS8ov02KD_Ro23:-Mo6CaLL8Mce4aksaaQT:b8nuui8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/51b0b4b31d0f6ec32d27949b351e598711b568d2/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt#L99)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Just listing out the tests I will have to do later since those methods aren't implemented yet.
</blockquote></details>

Either write the actual tests knowing that they'll fail and mark them with `@Ignore`, or don't implement the test methods at all. Otherwise it looks like these are actually implemented tests that are passing.

Note that this `TODO` syntax is a Kotlin construct that's used within an actual function body and throws when you try to call it, as opposed to our [TODO comments](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#todos) which are for documentation.

**Comment by tristanvuong2021** [comment]
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt, line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo5y2QS8ov02KD_Ro23:-Mo6KmTe8Twvi1rDTmia:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/51b0b4b31d0f6ec32d27949b351e598711b568d2/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Either write the actual tests knowing that they'll fail and mark them with `@Ignore`, or don't implement the test methods at all. Otherwise it looks like these are actually implemented tests that are passing.

Note that this `TODO` syntax is a Kotlin construct that's used within an actual function body and throws when you try to call it, as opposed to our [TODO comments](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#todos) which are for documentation.
</blockquote></details>

Done.

**Comment by tristanvuong2021** [comment]
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt, line 162 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351#-Mo4pOKl27Tyepx0zV58:-Mo6KqNhBSFkGnsOgrBi:bbkxmo2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5496ac904cf30d98e2bd5ee5ae7397b1cfc479/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt#L162)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

These tests now assert against an error with the TODO comment above them.
</blockquote></details>

Added implementations and made them ignored.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
