### PR TITLE
Internal ComputationParticipants Service Skeleton

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189)

### CODE REVIEW

**Review by wangyaopw — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189#-:-MgmQxf9CJ4pwvwP4910:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 299 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189#-MgqB8qV1w5BB7gVF_yN:-MgqB8qV1w5BB7gVF_yO:b-fwib85) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af9c79d6bfa1905cef3ae65b715dc30fe74085f6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L299)):*
> ```
>   ParticipantDetails          BYTES(MAX),
>   ParticipantDetailsJson      STRING(MAX),
> ```

Add foreign key constraint for this.
```
FOREIGN KEY (DuchyId, CertificateId)
  REFERENCES DuchyCertificates(DuchyId, CertificateId),
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189#-MgqBsYp9Ye82CuadaWt:-MgqBsYp9Ye82CuadaWu:bts9g4z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af9c79d6bfa1905cef3ae65b715dc30fe74085f6/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L60)):*
> ```Kotlin
>   }
> 
>   @Test fun `setParticipantRequisitionParams succeeds for non-last duchy`() = runBlocking {}
> ```

Mark these with `@Ignore` so they don't give the appearance of passing tests for these cases.

**Review by oliver-amzn — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189)* status: all files reviewed, 3 unresolved discussions (waiting on @uakyol and @zachcwc)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189#-MgquBdd-fuWbxAOYbrz:-MgquBdd-fuWbxAOYbs-:bqbvqzq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af9c79d6bfa1905cef3ae65b715dc30fe74085f6/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel#L69)):*
> ```Starlark
>     deps = [
>         "//src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner:services",
>         "//src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing",
> ```

Isn't this including the next line as well?

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 299 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189#-MgqB8qV1w5BB7gVF_yN:-MgvOyKh-cpeB6AVIvlW:bqx4sjw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af9c79d6bfa1905cef3ae65b715dc30fe74085f6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L299)):*
> FOREIGN KEY (DuchyId, CertificateId)
>   REFERENCES DuchyCertificates(DuchyId, CertificateId),
thank you
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189#-MgqBsYp9Ye82CuadaWt:-MgvOxgKE0i6JoSO47Na:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af9c79d6bfa1905cef3ae65b715dc30fe74085f6/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Mark these with `@Ignore` so they don't give the appearance of passing tests for these cases.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189#-MgquBdd-fuWbxAOYbrz:-MgvO9Q3B9CO5eI84o8I:b-zc81x4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af9c79d6bfa1905cef3ae65b715dc30fe74085f6/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel#L69)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Isn't this including the next line as well? 
</blockquote></details>

Unfortunately no Oliver, //src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing is actually a shorthand for //src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing:testing . If the target name matches the leaf folder name, you don't have to put :target_name . But, in that BUILD file there are seperate targets for testing and kingdom_data_services :


https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/BUILD.bazel#L10

We need them both

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @zachcwc)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189#-MgquBdd-fuWbxAOYbrz:-MgwHUhF1C5GjlTe-hHT:bl0ni3j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af9c79d6bfa1905cef3ae65b715dc30fe74085f6/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel#L69)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Unfortunately no Oliver, //src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing is actually a shorthand for //src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing:testing . If the target name matches the leaf folder name, you don't have to put :target_name . But, in that BUILD file there are seperate targets for testing and kingdom_data_services :


https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/BUILD.bazel#L10

We need them both
</blockquote></details>

Ahhhhhhhhh ok. Thx!

**Review by uakyol — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 3 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Pull request merged**
