### PR TITLE
fix: Fix FrequencyVectorBuilder performance issue by range count.

### PR DESCRIPTION
**Pull request by renjiezh**
Range count in kotlin is done by iterating from range beginning til the end. It prevents the generation of FrequencyVector of wrapping interval in a practical data size.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1832)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1832)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1832)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/FrequencyVectorBuilder.kt` line 91 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1832#-O82Dodu1CPrVRQng1o5:-O82Dodu1CPrVRQng1o6:b-57sfc1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d10509283afb646bd8d19436897d9caf66bba53a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/v2alpha/FrequencyVectorBuilder.kt#L91)):*
> ```Kotlin
>   private val primaryRange: IntRange
> 
>   private val primaryRangeCount: Int
> ```

where and how is this used?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1832)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
