### PR TITLE
return all buckets if privacy bucket mappers operative field set is empty

### PR DESCRIPTION
**Pull request by stevenwarejones**
…mpty

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1396)

**Comment by uakyol** [comment]
Thank you. While you are here, I think it will be good to also add a comment [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6702c271c17f83a516c39936b2c4c0f38936162e/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L53) that states if the operative fields are empty, normalization operation is not done.

**Review by uakyol — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1396)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1396)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketMapper.kt` line 36 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1396#-NnjlT8U2ekP37GazOII:-NnjlT8V-KLHIn9Oj0-c:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bc6def3b8e0dc1ed14d05443c5e6bf07404a9b8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketMapper.kt#L36)):*
> ```Kotlin
> 
>   /**
>    * Returns if a [privacyBucketGroup] matches for a given cel [program]. Always returns true if
> ```

nit



_Suggestion:_
```Kotlin
whether
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketMapper.kt` line 36 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1396#-NnjlXdK9mG5rPMdQYgn:-NnjlXdK9mG5rPMdQYgo:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bc6def3b8e0dc1ed14d05443c5e6bf07404a9b8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketMapper.kt#L36)):*
> ```Kotlin
> 
>   /**
>    * Returns if a [privacyBucketGroup] matches for a given cel [program]. Always returns true if
> ```

nit



_Suggestion:_
```Kotlin
`true`
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AlwaysChargingPrivacyBucketMapper.kt` line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1396#-NnjllSJAYGLoirEQarn:-NnjllSJAYGLoirEQaro:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bc6def3b8e0dc1ed14d05443c5e6bf07404a9b8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AlwaysChargingPrivacyBucketMapper.kt#L43)):*
> ```Kotlin
> 
>   override fun toEventMessage(privacyBucketGroup: PrivacyBucketGroup): Message {
>     return testEvent {}
> ```

nit



_Suggestion:_
```Kotlin
TestEvent.getDefaultInstance()
```
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketFilterTest.kt` line 274 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1396#-Nnjm9Ls8WjRYGGX_KC3:-Nnjm9Lt4tfIwHpR63CY:b-7oyn45) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bc6def3b8e0dc1ed14d05443c5e6bf07404a9b8/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketFilterTest.kt#L274)):*
> ```Kotlin
> 
>   @Test
>   fun `Mapper succeeds with empty operative fields`() {
> ```

nit: Generally tests methods should follow the pattern of "<MUT> <action> when <condition>".



_Suggestion:_
```Kotlin
getPrivacyBucketGroups returns all groups when mapper operativeFields is empty
```

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1396)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketFilterTest.kt` line 274 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1396#-Nnjm9Ls8WjRYGGX_KC3:-NnjmlYsA3cZ7QI50qvg:bw2c7cv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3bc6def3b8e0dc1ed14d05443c5e6bf07404a9b8/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketFilterTest.kt#L274)):*
Sorry, formatting ate my comment.

> "\<MUT> \<action> [when \<condition>]"

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1396)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
