### PR TITLE
Add tables for Certificates to Kingdom Spanner schema.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/81)

### CODE REVIEW

**Comment by SanjayVas** [comment]
This is intended to be merged into main after the base PR #78.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/81)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/81#-MaireYSBf-ud3CvYdX6:-MaireYT1P9OL3DMb1yt:b-flsh4p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22b60eac283dab9a12609120245f6d792f5ab37d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L20)):*
> ```
> --   Root
> --   ├── Certificates
> --   ├── DataProviders
> ```

Does it make any sense to split each root table into its own SDL file?

I'm just thinking it's a little arbitrary that it lives here and not with ModelProviders with the panel match tables.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/81)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/81#-MaireYSBf-ud3CvYdX6:-Maj4aYCEycP1zpwdnoO:bzb25bq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22b60eac283dab9a12609120245f6d792f5ab37d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Does it make any sense to split each root table into its own SDL file?

I'm just thinking it's a little arbitrary that it lives here and not with ModelProviders with the panel match tables.
</blockquote></details>

Let me give it a shot and make sure the ordering works out.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/81)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/81#-MaireYSBf-ud3CvYdX6:-MajnCp01zOrh_ZcL3rA:b-rb1myg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22b60eac283dab9a12609120245f6d792f5ab37d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Let me give it a shot and make sure the ordering works out.
</blockquote></details>

So I was surprised that nothing broke ordering-wise, and then I realized it's because we were stripping all the FK constraints out when processing the SDL file. I created #83 to address that. The upshot is that this would require more granular splitting in order to get all the tables and references in the right order (meaning just splitting by root table would be insufficient).

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/81)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/81)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, and @zachcwc)

**Review by zachcwc — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/81)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @oliver-amzn)

**Review by corbantek — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/81)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
