### PR TITLE
Update the duchy to call the new kingdom system APIs.

### PR DESCRIPTION
**Pull request by wangyaopw**
As a byproduct of this change:
1. All deprecated system/internal API definitions and implementations are deleted, e.g globalComputation, metricValue
2. All inusefully codes are deleted, e.g., duchyPublickey, cryptoKeySert

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110)

### CODE REVIEW

**Comment by wangyaopw** [comment]
Sorry for this giant PR.

Most are just clean up codes.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 75 of 77 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, line 247 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110#-McPvLkA1OKv6gqcC02F:-McPvLkA1OKv6gqcC02G:b-7qmztb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2c1d8a8e799e16e243d539cfee5ee67fb8474ea/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L247)):*
> ```
> also
> ```
nit: `also` is primarily useful for when there are name conflicts as an alternative to qualifying with `this`. `apply` is generally preferred, particularly when there are no name conflicts.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdomAndDuchyIntegrationTestBase.kt, line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110#-McQ0f9Z-T8e4RfQmIaG:-McQ0f9Z-T8e4RfQmIaH:bc9gofk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2c1d8a8e799e16e243d539cfee5ee67fb8474ea/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdomAndDuchyIntegrationTestBase.kt#L74)):*
> ```
>   // TODO(wangyaopw): add test for this when v2alpha kingdom is done.
> ```
Mark these tests with `@Ignore` so it doesn't look like we have them implemented when looking at test results.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110)* status: 76 of 78 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, line 247 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110#-McPvLkA1OKv6gqcC02F:-McQ2fpj0A8QsiOR2u6z:b-nmmjww) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2c1d8a8e799e16e243d539cfee5ee67fb8474ea/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L247)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> also
> ```
nit: `also` is primarily useful for when there are name conflicts as an alternative to qualifying with `this`. `apply` is generally preferred, particularly when there are no name conflicts.
</blockquote></details>

actually there is a name conflict here.

reach(frequency)Builder is conflicting with reach(frequency). If using apply(), the compiler thinks the reach/frequency are the proto fields, not the ReachAndFrequency object.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdomAndDuchyIntegrationTestBase.kt, line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110#-McQ0f9Z-T8e4RfQmIaG:-McQ5A0rDFmTYSxsaWED:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2c1d8a8e799e16e243d539cfee5ee67fb8474ea/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdomAndDuchyIntegrationTestBase.kt#L74)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>   // TODO(wangyaopw): add test for this when v2alpha kingdom is done.
> ```
Mark these tests with `@Ignore` so it doesn't look like we have them implemented when looking at test results.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110)* status: 78 of 81 files reviewed, 2 unresolved discussions (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/AsyncComputationControlServer.kt, line 61 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110#-McosGtF8nGqIoMjQhb6:-McosGtF8nGqIoMjQhb7:b-z3te02) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d50338b783e26147e7e8fbc7fe936b190382f98d/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/AsyncComputationControlServer.kt#L61)):*
> ```
> otherDuch
> ```

nit: Further up you changed it to `.minus()` (which I think is more readable) - is it worth changing this so it's consistent?
___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/server/SpannerComputationsServer.kt, line 40 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110#-McosaC81DzmtpbCQ4OV:-McosaC81DzmtpbCQ4OW:bxs2f0g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d50338b783e26147e7e8fbc7fe936b190382f98d/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/server/SpannerComputationsServer.kt#L40)):*
> ```Kotlin
> 
>   private val otherDuchyNames: List<String>
>     get() = flags.duchyIdFlags.duchyIds.filter { it != flags.duchy.duchyName }
> ```

nit: same

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110)* status: 78 of 81 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/AsyncComputationControlServer.kt, line 61 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110#-McosGtF8nGqIoMjQhb6:-McpGWFM4mGEBQDrjoCF:b-wp60w8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d50338b783e26147e7e8fbc7fe936b190382f98d/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/AsyncComputationControlServer.kt#L61)):*
> minus
Here the flags.duchyIdFlags.duchyIds is an array, which doesn't have a minus() method.

The places using .minus() are lists.

Yep, it is a little annoying they are not consistent. Maybe we can use filter{} at all places, and fine to use minus() wherever it is supported.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110)* status: 66 of 81 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/AsyncComputationControlServer.kt, line 61 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/110#-McosGtF8nGqIoMjQhb6:-McvUxEZBW1T0a1e7azz:bllcgq0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d50338b783e26147e7e8fbc7fe936b190382f98d/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/AsyncComputationControlServer.kt#L61)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> minus
Here the flags.duchyIdFlags.duchyIds is an array, which doesn't have a minus() method.

The places using .minus() are lists.

Yep, it is a little annoying they are not consistent. Maybe we can use filter{} at all places, and fine to use minus() wherever it is supported.
</blockquote></details>

Updated to use DuchyInfo. now it can use .minus()

**Comment by wangyaopw** [comment]
I am merging this PR before the merging conflicting gets out of control.

**Pull request merged**
