### PR TITLE
sync file with panel-exchange-client repo

### PR DESCRIPTION
**Pull request by Marco-Premier**
[Rally task](https://rally1.rallydev.com/#/604612930531d/search?detail=%2Ftask%2F691273137535&keywords=413)

[panel-exchange-client PR](https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/368)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: 5 of 12 files reviewed, 6 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`WORKSPACE` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAnVIVBLE_q6Xk1dGT:-NVAnVIVBLE_q6Xk1dGU:bxhbb4y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/WORKSPACE#L29)):*
> ```Starlark
> load("//build:deps.bzl", "panel_exchange_client_deps")
> 
> panel_exchange_client_deps()
> ```

Split these up into the right places in the existing structure rather than having a separate def for panel exchange. Note that this is highly sensitive to ordering. Simple repo targets (http_archive) can go into `wfa_measurement_system_repositories()`, for example. Deps that require a load must go after the target that loads them.
___
*[`WORKSPACE` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAnGdLDYPCMoNpfuT7:-NVAnGdLDYPCMoNpfuT8:b-ewogj8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/WORKSPACE#L37)):*
> ```Starlark
> )
> 
> load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")
> ```

rules_jvm_external is already pulled in and configured by common-jvm.
___
*[`build/panel_exchange_client_maven_deps.bzl` line 85 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAm6Np3-U8n-t6hOUW:-NVAm6Np3-U8n-t6hOUX:b8wcygb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/build/panel_exchange_client_maven_deps.bzl#L85)):*
> ```Starlark
>     return _ARTIFACTS
> 
> def panel_exchange_client_maven_excluded_artifacts():
> ```

This is basically COMMON_JVM_EXCLUDED_ARTIFACTS
___
*[`build/repositories.bzl` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAmVc9-XJhH4AdaAS0:-NVAmVc9-XJhH4AdaAS1:bp7t0z8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/build/repositories.bzl#L28)):*
> ```Starlark
>     """Imports all direct dependencies for wfa_measurement_system."""
> 
>     com_google_riegeli_repo()
> ```

This should already be pulled in by common_cpp_repositories()
___
*[`build/com_google_riegeli/repo.bzl` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAmmnUCVcDBILdkdhW:-NVAmmnUCVcDBILdkdhX:b-en8zb5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/build/com_google_riegeli/repo.bzl#L1)):*
> ```Starlark
> # Copyright 2021 The Cross-Media Measurement Authors
> ```

Don't include this file here. This dep is already pulled in by common-cpp.
___
*[`build/tink/repositories.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAn4Oo63_0zbvsFk-c:-NVAn4Oo63_0zbvsFk-d:bp3immr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/build/tink/repositories.bzl#L26)):*
> ```Starlark
> )
> 
> def tink_base():
> ```

tink_base is already included by common-jvm.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 12 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: all files reviewed, 9 unresolved discussions (waiting on @Marco-Premier)

___
*[`build/repositories.bzl` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NV_6VBQ86KNkkTGdmuD:-NV_6VBQ86KNkkTGdmuE:b-2dynqx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d65c5162e73c0f328ef29de477150c733169c9b/build/repositories.bzl#L36)):*
> ```Starlark
>     native.local_repository(
>         name = "wfa_common_jvm",
>         path = "/home/marcopremier/XMM/common-jvm",
> ```

just a reminder to update this before merge
___
*[`build/variables.bzl` line 95 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NV_7G8-Byhxp-v1NDBE:-NV_7G8-Byhxp-v1NDBF:bb4ly12) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d65c5162e73c0f328ef29de477150c733169c9b/build/variables.bzl#L95)):*
> ```Starlark
> 
> # Config for Panel Exchange Client Example Daemon.
> EXAMPLE_DAEMON_CONFIG = struct(
> ```

`EXAMPLE_PANEL_EXCHANGE_CLIENT_DAEMON_CONFIG`
___
*[`build/variables.bzl` line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NV_7Mnj7NUA_UxnrbRC:-NV_7Mnj7NUA_UxnrbRD:b-nyrvuu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d65c5162e73c0f328ef29de477150c733169c9b/build/variables.bzl#L103)):*
> ```Starlark
> 
> # Settings for deploying tests to Google Cloud.
> TEST_GOOGLE_CLOUD_SETTINGS = struct(
> ```

ditto making the name panel specific

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: all files reviewed, 9 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`WORKSPACE` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAnVIVBLE_q6Xk1dGT:-NVdz1LSCWq3bCYn3tPx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/WORKSPACE#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Split these up into the right places in the existing structure rather than having a separate def for panel exchange. Note that this is highly sensitive to ordering. Simple repo targets (http_archive) can go into `wfa_measurement_system_repositories()`, for example. Deps that require a load must go after the target that loads them.
</blockquote></details>

Done.
___
*[`WORKSPACE` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAnGdLDYPCMoNpfuT7:-NW8SIBw2kNfOnSW8Dwe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/WORKSPACE#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

rules_jvm_external is already pulled in and configured by common-jvm.
</blockquote></details>

Done.
___
*[`build/panel_exchange_client_maven_deps.bzl` line 85 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAm6Np3-U8n-t6hOUW:-NW8HCLnEuUiy7G7ePKR:b-4gjrxz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/build/panel_exchange_client_maven_deps.bzl#L85)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is basically COMMON_JVM_EXCLUDED_ARTIFACTS
</blockquote></details>

It actually is except that the build would fail.
There is an existing TODO to investigate on this further: 
```TODO(@efoxepstein): why does org.slf4j:slf4j-log4j12 cause build failures?```
___
*[`build/repositories.bzl` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAmVc9-XJhH4AdaAS0:-NVExCNG6LywOMYhZ4wY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/build/repositories.bzl#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should already be pulled in by common_cpp_repositories()
</blockquote></details>

Done.
___
*[`build/repositories.bzl` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NV_6VBQ86KNkkTGdmuD:-NVdyDt831pIDydDeAI_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d65c5162e73c0f328ef29de477150c733169c9b/build/repositories.bzl#L36)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

just a reminder to update this before merge
</blockquote></details>

Done.
___
*[`build/variables.bzl` line 95 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NV_7G8-Byhxp-v1NDBE:-NVdyQx4D1jdtsFOeuTe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d65c5162e73c0f328ef29de477150c733169c9b/build/variables.bzl#L95)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`EXAMPLE_PANEL_EXCHANGE_CLIENT_DAEMON_CONFIG`
</blockquote></details>

Done.
___
*[`build/variables.bzl` line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NV_7Mnj7NUA_UxnrbRC:-NVdygqu6yBx6KKykwUX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d65c5162e73c0f328ef29de477150c733169c9b/build/variables.bzl#L103)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto making the name panel specific
</blockquote></details>

Done.
___
*[`build/com_google_riegeli/repo.bzl` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAmmnUCVcDBILdkdhW:-NVExUxi3ddB62O3MZPk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/build/com_google_riegeli/repo.bzl#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't include this file here. This dep is already pulled in by common-cpp.
</blockquote></details>

Done.
___
*[`build/tink/repositories.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAn4Oo63_0zbvsFk-c:-NVe2Xlj9eMDmNUmFzIF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/build/tink/repositories.bzl#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

tink_base is already included by common-jvm.
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r1, 4 of 7 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: all files reviewed, 7 unresolved discussions (waiting on @Marco-Premier)

___
*[`WORKSPACE` line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NW9fJnE33-hqbL7zRSV:-NW9fJnE33-hqbL7zRSW:bg6jzow) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/670ea1e94f22ad3817dbd6f76dade80cda0f1848/WORKSPACE#L33)):*
> ```Starlark
> load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
> 
> rules_pkg_dependencies()
> ```

This is already called by common_jvm_deps()



_Code quote:_
```Starlark
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()
```
___
*[`build/panel_exchange_client_maven_deps.bzl` line 85 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAm6Np3-U8n-t6hOUW:-NW9cqoQ7npIqsHpIcdI:b38ypu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/build/panel_exchange_client_maven_deps.bzl#L85)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

It actually is except that the build would fail.
There is an existing TODO to investigate on this further: 
```TODO(@efoxepstein): why does org.slf4j:slf4j-log4j12 cause build failures?```
</blockquote></details>

What I mean is that we shouldn't have a def for `panel_exchange_client_maven_excluded_artifacts` and instead do this modification to excluded_artifacts nearer to the maven_install target.

Basically avoid having as much that's marked as being specifically for panel exchange. The only things that are really specific to panel exchange that we want to mark as such are related to the `java_export` build targets, which use a separate `maven_install` repo target named "maven_export".
___
*[`build/repo.bzl` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NW9fpYT0KN62VKncGak:-NW9fpYT0KN62VKncGal:bpaggj6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/670ea1e94f22ad3817dbd6f76dade80cda0f1848/build/repo.bzl#L1)):*
> ```Starlark
> # Copyright 2021 The Cross-Media Measurement Authors
> ```

Put this inside of a `grpc_health_probe` folder under `//build`. This file will need an empty sibling `BUILD.bazel` file.
___
*[`build/repositories.bzl` line 107 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NW9gR9CCQPsesjP7JXn:-NW9gR9CCQPsesjP7JXo:bnvhe7c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/670ea1e94f22ad3817dbd6f76dade80cda0f1848/build/repositories.bzl#L107)):*
> ```Starlark
>     )
> 
> def wfa_measurement_system_tink_repository(tink_commit):
> ```

Move this to a file under `build/tink` and just call it `tink_cc` (basically what you had before, but without the `tink_base` def and with the `tink_commit` param).

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: all files reviewed, 8 unresolved discussions (waiting on @Marco-Premier)

___
*[`build/repositories.bzl` line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NW9gvWz5W8M5x-xza_n:-NW9gvWz5W8M5x-xza_o:b-yj05qk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/670ea1e94f22ad3817dbd6f76dade80cda0f1848/build/repositories.bzl#L99)):*
> ```Starlark
> 
>     http_archive(
>         name = "rules_pkg",
> ```

This is already included by common_jvm_repositories

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: all files reviewed, 8 unresolved discussions (waiting on @SanjayVas)

___
*[`WORKSPACE` line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NW9fJnE33-hqbL7zRSV:-NWDIpMQ6_6n4FeyMgtb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/670ea1e94f22ad3817dbd6f76dade80cda0f1848/WORKSPACE#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is already called by common_jvm_deps()
</blockquote></details>

Done.
___
*[`build/panel_exchange_client_maven_deps.bzl` line 85 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NVAm6Np3-U8n-t6hOUW:-NWDW5_6-Dkeh3HRQ2zV:b-gi4lqd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c002ecdf4e39f4336b8c39a490de8795e5fa8897/build/panel_exchange_client_maven_deps.bzl#L85)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What I mean is that we shouldn't have a def for `panel_exchange_client_maven_excluded_artifacts` and instead do this modification to excluded_artifacts nearer to the maven_install target.

Basically avoid having as much that's marked as being specifically for panel exchange. The only things that are really specific to panel exchange that we want to mark as such are related to the `java_export` build targets, which use a separate `maven_install` repo target named "maven_export".
</blockquote></details>

I see, thanks Sanjay. I moved it just above the ```maven_install``` and wrapped it inside ```COMMON_JVM_EXCLUSION```.
___
*[`build/repositories.bzl` line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NW9gvWz5W8M5x-xza_n:-NWDJa708gsCIk4uxGeS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/670ea1e94f22ad3817dbd6f76dade80cda0f1848/build/repositories.bzl#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is already included by common_jvm_repositories
</blockquote></details>

Done.
___
*[`build/repositories.bzl` line 107 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NW9gR9CCQPsesjP7JXn:-NWDLk5FB-z7dZ7GUBnW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/670ea1e94f22ad3817dbd6f76dade80cda0f1848/build/repositories.bzl#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move this to a file under `build/tink` and just call it `tink_cc` (basically what you had before, but without the `tink_base` def and with the `tink_commit` param).
</blockquote></details>

Done.
___
*[`build/repo.bzl` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NW9fpYT0KN62VKncGak:-NWDNg-16yeeESAMG5i1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/670ea1e94f22ad3817dbd6f76dade80cda0f1848/build/repo.bzl#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Put this inside of a `grpc_health_probe` folder under `//build`. This file will need an empty sibling `BUILD.bazel` file.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier)

___
*[`WORKSPACE` line 69 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NWJ4Tet8-_Ea5BICbdW:-NWJ4Tet8-_Ea5BICbdX:bt0w2h9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d6d6892d42612f3d6dcf8085f422b2efe058aa1/WORKSPACE#L69)):*
> ```Starlark
> }.items())
> 
> COMMON_JVM_EXCLUSION = [x for x in COMMON_JVM_EXCLUDED_ARTIFACTS if x != "org.slf4j:slf4j-log4j12"] + ["org.apache.beam:beam-sdks-java-io-kafka"]
> ```

nit: name this something else, since we're excluding more than what common-jvm does. e.g. just `EXCLUDED_MAVEN_ARTIFACTS`
___
*[`build/tink/repositories.bzl` line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NWJ5AXf5KjPoIeL0ODS:-NWJ5AXf5KjPoIeL0ODT:b-uiiziv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d6d6892d42612f3d6dcf8085f422b2efe058aa1/build/tink/repositories.bzl#L31)):*
> ```Starlark
>             strip_prefix = "tink-{commit}/cc".format(commit = tink_commit),
>             url = _tink_url,
>             repo_mapping = {
> ```

nit: we should be able to drop this now, as the underlying issue has been fixed.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier)

___
*[`build/tink/repositories.bzl` line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NWJ5AXf5KjPoIeL0ODS:-NWJNOwIEA28JDy9FaYU:b-75ejsf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d6d6892d42612f3d6dcf8085f422b2efe058aa1/build/tink/repositories.bzl#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: we should be able to drop this now, as the underlying issue has been fixed.
</blockquote></details>

i think sanjay means to drop the `repo_mapping` field @Marco-Premier

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`build/tink/repositories.bzl` line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999#-NWJ5AXf5KjPoIeL0ODS:-NWLxIIR7SGy3ufIQ-e3:b-nm5rz0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8d6d6892d42612f3d6dcf8085f422b2efe058aa1/build/tink/repositories.bzl#L31)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think sanjay means to drop the `repo_mapping` field @Marco-Premier 
</blockquote></details>

Right, my bad. Thanks Steven

**Review by Marco-Premier — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 2 of 12 files at r1, 2 of 7 files at r2, 2 of 4 files at r3, 5 of 7 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/999)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
