### PR TITLE
Add back dispatch for image push.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1598)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1598)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`.github/workflows/push-images.yml` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1598#-Nwl02skAWhC9WnRNccL:-Nwl02skAWhC9WnRNccM:bjq2i0m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf042abb97b7aa607a4b4e902b90c117d40747bd/.github/workflows/push-images.yml#L18)):*
> ```YAML
> 
> on:
>   workflow_dispatch:
> ```

This is incorrect. Add workflow_dispatch to maybe-push-images instead so the image tag generation there is always called.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1598)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`.github/workflows/push-images.yml` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1598#-Nwl02skAWhC9WnRNccL:-Nwl1-pA2RALJ6PEwPS8:bza9luy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf042abb97b7aa607a4b4e902b90c117d40747bd/.github/workflows/push-images.yml#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is incorrect. Add workflow_dispatch to maybe-push-images instead so the image tag generation there is always called.
</blockquote></details>

Smart.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1598)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1598)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
