### PR TITLE
Fix event filtration formation in v2alpha metrics service

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1044)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1041** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1041" target="_blank">Graphite</a> 
    * **PR #1004** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1004" target="_blank">Graphite</a> 
      * **PR #1029** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1029" target="_blank">Graphite</a> 
        * **PR #1044** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1044" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1044?utm_source=stack-comment).

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1044)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1044)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by riemanli — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1044)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by riemanli — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1044)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
