### PR TITLE
Implement Report Scheduling Job

### PR DESCRIPTION
**Pull request by tristanvuong2021**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1377)

**Review by riemanli — CHANGES_REQUESTED** [review]
Is this going to work with the generic queue stack (ex: RabbitMQ) we will use? 

> Reviewed 16 of 19 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1377#-:-Nmcfztw9b2qZUACxFbR:btcmwry)* status: 18 of 19 files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt` line 105 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1377#-NmchsfLAyWslj1aq1Sp:-NmchsfLAyWslj1aq1Sq:b-kxcy17) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf89ab1c2e6ceed73df11aad6ed6ef502c209678/src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt#L105)):*
> ```Kotlin
>                   }
>                   state = ReportSchedule.State.ACTIVE
>                 }
> ```

nit: Is this a good process order? Should we process older schedules first?



_Code quote:_
```Kotlin
                ListReportSchedulesRequestKt.filter {
                  cmmsMeasurementConsumerId = measurementConsumerId
                  if (listReportSchedulesResponse.reportSchedulesList.size > 0) {
                    externalReportScheduleIdAfter =
                      listReportSchedulesResponse.reportSchedulesList
                        .last()
                        .externalReportScheduleId
                  }
                  state = ReportSchedule.State.ACTIVE
                }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt` line 347 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1377#-NmcpXWK7bRWaIK6R-AD:-NmcpXWK7bRWaIK6R-AE:b-rdtto4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf89ab1c2e6ceed73df11aad6ed6ef502c209678/src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt#L347)):*
> ```Kotlin
> 
>         // When checking data availability, the report window is compared against the event group's
>         // data availability when bounded by its data provider's data availability.
> ```

Could you also add some comments to explain what the if-conditions do? For example, IIUC, the first two if-conditions checks if there is any intersection between the data provider's data availability and event group's.



_Code quote:_
```Kotlin
        // When checking data availability, the report window is compared against the event group's
        // data availability when bounded by its data provider's data availability.
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt` line 365 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1377#-NmcrBYR18S6fcH-K4r3:-NmcrBYR18S6fcH-K4r4:ba680eo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf89ab1c2e6ceed73df11aad6ed6ef502c209678/src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt#L365)):*
> ```Kotlin
>         ) {
>           return false
>         }
> ```

You can just check if `dataAvailabilityIntervalStart <= dataAvailabilityIntervalEnd` later to know if they intersect, right?



_Code quote:_
```Kotlin
        if (
          Timestamps.compare(
            dataProvider!!.dataAvailabilityInterval.endTime,
            eventGroup!!.dataAvailabilityInterval.startTime
          ) <= 0
        ) {
          return false
        }

        if (
          eventGroup.dataAvailabilityInterval.hasEndTime() &&
            Timestamps.compare(
              dataProvider.dataAvailabilityInterval.startTime,
              eventGroup.dataAvailabilityInterval.endTime
            ) >= 0
        ) {
          return false
        }
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJobTest.kt` line 216 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1377#-Nmd8B5pCn1-k81AfvJL:-Nmd6t336T-WeoJKd75k:b-2ektgg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf89ab1c2e6ceed73df11aad6ed6ef502c209678/src/test/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJobTest.kt#L216)):*
> ```Kotlin
>               periodicTimeInterval = periodicTimeInterval {
>                 startTime =
>                   buildReportWindowStartTimestamp(
> ```

nit: I am thinking to use specific numbers to decouple the test from the implementation. WDYT?

**Review by tristanvuong2021 — COMMENTED** [review]
Not in this PR.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1377#-:-Nmgr0zz452WAMIXFblb:b-u1vy19)* status: 16 of 19 files reviewed, 3 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt` line 105 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1377#-NmchsfLAyWslj1aq1Sp:-NmgvmTN4O3L45L5UjCh:b-q5wdos) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf89ab1c2e6ceed73df11aad6ed6ef502c209678/src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt#L105)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

nit: Is this a good process order? Should we process older schedules first?
</blockquote></details>

I changed the sort order for processing the schedules. It is a small change and I see the benefit to it.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt` line 347 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1377#-NmcpXWK7bRWaIK6R-AD:-NmgrHmF62j8mdI5NnFG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf89ab1c2e6ceed73df11aad6ed6ef502c209678/src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt#L347)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Could you also add some comments to explain what the if-conditions do? For example, IIUC, the first two if-conditions checks if there is any intersection between the data provider's data availability and event group's.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt` line 365 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1377#-NmcrBYR18S6fcH-K4r3:-NmgrIzz5kaXoDYCrj-G:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf89ab1c2e6ceed73df11aad6ed6ef502c209678/src/main/kotlin/org/wfanet/measurement/reporting/job/ReportSchedulingJob.kt#L365)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

You can just check if `dataAvailabilityIntervalStart <= dataAvailabilityIntervalEnd` later to know if they intersect, right?
</blockquote></details>

Done.

**Review by riemanli — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1377)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 13 of 19 files at r1, 2 of 2 files at r2, 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1377)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
