### PR TITLE
Refactor public reports service to reduce number of connections to support larger reports

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NIo1Pop-YngLvcTGv-b:-NIo1Poq179Yo3XNq0CH:bggoe1r) (no related file):*
Reducing RPCs/connections by using batch operations is definitely good, but I don't know about reducing parallelism at the public API server level. If we're having issues with too many simultaneous connections, that's something we should be able to constrain at the internal server level. e.g. limiting the number of RPCs we handle at a time.

___
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/kingdom/service/api/v2alpha/FakeMeasurementsService.kt` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NInvrh9DZoCrJFlTSTG:-NInvrh9DZoCrJFlTSTH:be2kfag) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/integration/common/kingdom/service/api/v2alpha/FakeMeasurementsService.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.integration.common.kingdom.service.api.v2alpha
> ```

Put this inside of a `testing` subpackage.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/kingdom/service/api/v2alpha/FakeMeasurementsService.kt` line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NInwc_C2j2O1mpvfUKT:-NInwc_D7CF6GFMEm2eK:b-2jh1zv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/integration/common/kingdom/service/api/v2alpha/FakeMeasurementsService.kt#L50)):*
> ```Kotlin
> 
>   override suspend fun cancelMeasurement(request: CancelMeasurementRequest): Measurement {
>     throw Status.UNIMPLEMENTED.asRuntimeException()
> ```

nit: I believe this is the default implementation of all methods, so no need to override it here. That is to say that these aren't abstract methods in `MeasurementsCoroutineImplBase`
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NInyI6B-rkhSfF6-9Eg:-NInyI6B-rkhSfF6-9Eh:b-fk09sx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt#L152)):*
> ```Kotlin
>     }
> 
>     var j = 2
> ```

Wait, you can't just bind a list?

If you actually can't do that, then I think it would be clearer to rewrite this using `join` using a Map of param identifier to value (or two parallel lists).
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 326 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NIo-4cI7khRRwwR8Md2:-NIo-4cI7khRRwwR8Md3:b5gkjeq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L326)):*
> ```Kotlin
>     val reportInfo: ReportInfo = buildReportInfo(request, resourceKey.measurementConsumerId)
> 
>     val reportingSetExternalIds = mutableSetOf<Long>()
> ```

It looks like you have multiple methods that mutate an argument. If it would be really awkward to avoid this, then at minimum document each of these methods to make it very clear that they mutate the argument (and exactly how they do so).

Consider alternatives such as extracting a separate class to contain the mutable variable as class state.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NIo1Pop-YngLvcTGv-b:-NIo3lfjDCbLvgZqkmrl:bfe8zkq) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Reducing RPCs/connections by using batch operations is definitely good, but I don't know about reducing parallelism at the public API server level. If we're having issues with too many simultaneous connections, that's something we should be able to constrain at the internal server level. e.g. limiting the number of RPCs we handle at a time.
</blockquote></details>

It is possible to add some of the parallelism back using async wait. launch didn't work in multiple places, like adding to a list.

___

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 326 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NIo-4cI7khRRwwR8Md2:-NIoaEGzBlvB9mVV_m0f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L326)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It looks like you have multiple methods that mutate an argument. If it would be really awkward to avoid this, then at minimum document each of these methods to make it very clear that they mutate the argument (and exactly how they do so).

Consider alternatives such as extracting a separate class to contain the mutable variable as class state.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/kingdom/service/api/v2alpha/FakeMeasurementsService.kt` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NInvrh9DZoCrJFlTSTG:-NIoa91pCnlvoS5N5YQs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/integration/common/kingdom/service/api/v2alpha/FakeMeasurementsService.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Put this inside of a `testing` subpackage.
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NInyI6B-rkhSfF6-9Eg:-NIokt6U2c0-iN231gNp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt#L152)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wait, you can't just bind a list?

If you actually can't do that, then I think it would be clearer to rewrite this using `join` using a Map of param identifier to value (or two parallel lists).
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 326 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NIo-4cI7khRRwwR8Md2:-NItJXfZAgNwHrqWkfrK:b-54a7kt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L326)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Err, the class you created isn't really want I meant, especially since you're copying it. The suggestion was to move the methods that need to mutate the collection into a separate class that has private access to said mutable collection. This way only the methods that need to mutate it can do so, and the mutability has a limited lifecycle.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 326 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NIo-4cI7khRRwwR8Md2:-NItTLxFAcCoaXjpRg-B:b-pyfd9z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L326)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Err, the class you created isn't really want I meant, especially since you're copying it. The suggestion was to move the methods that need to mutate the collection into a separate class that has private access to said mutable collection. This way only the methods that need to mutate it can do so, and the mutability has a limited lifecycle.
</blockquote></details>

The copy is only ever used in one method. Outside of that, only that class mutates it and exposes only one method for mutation

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 326 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NIo-4cI7khRRwwR8Md2:-NItUixBDY7iwQFfYt7M:b-qa5dz4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L326)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The copy is only ever used in one method. Outside of that, only that class mutates it and exposes only one method for mutation
</blockquote></details>

But the copy is itself mutable. I get that it need not be the same mutable instance, but it's basically the same thing being mutated in more than one place. My suggestion was all around making sure the mutability is itself contained.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 326 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NIo-4cI7khRRwwR8Md2:-NItVPbh60R2dmWWAr3f:bohgs6e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L326)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

But the copy is itself mutable. I get that it need not be the same mutable instance, but it's basically the same thing being mutated in more than one place. My suggestion was all around making sure the mutability is itself contained.
</blockquote></details>

I didn't want to expose additional set methods because the other set methods are only ever used in that one method. The other methods only need to add.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 326 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NIo-4cI7khRRwwR8Md2:-NJ6P093EUBzENFvnlyC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L326)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Oh wait, did you mean a separate class that would have one public method that returns the reporting sets and that class would create the mutable collection and use it
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 3 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 326 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NIo-4cI7khRRwwR8Md2:-NJ6NXet-sb_JG3RIcBv:b6g5dtc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/662f751fd6aab8d72ed01d003182e823053ab655/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L326)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Oh wait, did you mean a separate class that would have one public method that returns the reporting sets and that class would create the mutable collection and use it
</blockquote></details>

What you have now LGTM.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1251 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NJ6Nj1r6pduJaxDRz9p:-NJ6Nj1r6pduJaxDRz9q:b-q0tqul) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/874d4ffad3ab57704ee346243aedbfb85f760caf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1251)):*
> ```Kotlin
>     private lateinit var internalReportingSetMap: Map<Long, InternalReportingSet>
> 
>     suspend fun process() {
> ```

nit: check that one of the  lateinit vars hasn't been instantiated yet to prevent someone from calling this twice

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 3 of 10 files at r1, 3 of 5 files at r3, 1 of 2 files at r4, 1 of 3 files at r6, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt` line 125 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NJIsbko1MPp5Tumq5fW:-NJIsbko1MPp5Tumq5fX:b-cc5bxh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e3d8cf3241cb8e7a630037f99817530c3ebe60d7/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt#L125)):*
> ```Kotlin
> 
>     return flow {
>       val readContext = client.readTransaction()
> ```

nit: if `readContext` is closeable you can apply `.use()` pattern



_Suggestion:_
```Kotlin
      client.readTransaction().use( readContext -> 
        emitAll(readContext.executeQuery(statement).consume(::translate))
      }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1381 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783#-NJIvzPJA_6rw4y1lLfG:-NJIvzPJA_6rw4y1lLfH:b2p1n4s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e3d8cf3241cb8e7a630037f99817530c3ebe60d7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1381)):*
> ```Kotlin
>         val errorMessage = StringBuilder("The following reporting set names were not found:")
>         internalReportingSetsList.forEach {
>           if (reportingSetExternalIds.contains(it.externalReportingSetId)) {
> ```

nit: `MutableSet.remove()` wouldn't need a check, it will just return a Boolean to indicate if value was present



_Suggestion:_
```Kotlin
          reportingSetExternalIds.remove(it.externalReportingSetId)
```

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/783)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

**Pull request merged**
