### PR TITLE
Batch DDL statements for Spanner schema creation.

### PR DESCRIPTION
**Pull request by SanjayVas**
This avoids synchronization delays between individual DDL transactions.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/629)

### CODE REVIEW

**Comment by SanjayVas** [comment]
Tested in halo-cmm-dev. Entire update took ~37s, down from the ~20m previously reported.

```
Aug 02, 2022 6:50:37 PM org.wfanet.measurement.common.db.liquibase.tools.BaseUpdateSchema run
INFO: Loading changelog from /kingdom/spanner/changelog.yaml
Aug 02, 2022 6:50:41 PM org.wfanet.measurement.common.db.liquibase.tools.BaseUpdateSchema run
INFO: Updating...
Aug 02, 2022 6:51:56 PM liquibase.lockservice
INFO: Successfully acquired change log lock
Aug 02, 2022 6:51:57 PM liquibase.ext
INFO: Creating database history table with name: DATABASECHANGELOG
Aug 02, 2022 6:52:16 PM liquibase.ext
INFO: Reading from DATABASECHANGELOG
Running Changeset: kingdom/spanner/create-measurement-schema.sql::1::sanjayvas
Aug 02, 2022 6:52:38 PM liquibase.changelog
INFO: Custom SQL executed
Aug 02, 2022 6:52:38 PM liquibase.changelog
INFO: ChangeSet kingdom/spanner/create-measurement-schema.sql::1::sanjayvas ran successfully in 20559ms
Running Changeset: kingdom/spanner/create-exchange-schema.sql::2::efoxepstein
Aug 02, 2022 6:52:50 PM liquibase.changelog
INFO: Custom SQL executed
Aug 02, 2022 6:52:50 PM liquibase.changelog
INFO: ChangeSet kingdom/spanner/create-exchange-schema.sql::2::efoxepstein ran successfully in 12054ms
Aug 02, 2022 6:52:50 PM liquibase.lockservice
INFO: Successfully released change log lock
```

**Comment by SanjayVas** [comment]
Filed https://github.com/cloudspannerecosystem/liquibase-spanner/issues/119 to fix documentation on how to use batch DDL.

**Review by matthewclegg — COMMENTED** [review]
Thank you, Sanjay!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/629#-:-N8W2ZVlBJ2EiarYqZQN:b-loem6x)* status: 0 of 5 files reviewed, all discussions resolved

**Review by matthewclegg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/629#-:-N8W2dBeBfGtMFylp9Oq:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved

**Review by duliomatos1 — APPROVED** [review]
Great :lgtm_strong: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/629#-:-N8dnEiQEdGyMFuTRKTZ:b-kk7ui)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
