### PR TITLE
Add Retries on Serializable Failure to Reporting Server.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: 3 of 10 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5PjWg81By_CwA6qvj:-NA5PjWh7XE1oHJHd-5-:boaegki) (no related file):*
nit: reference advice in Postgres documentation that mentions that these should be retried (https://www.postgresql.org/docs/14/transaction-iso.html#XACT-SERIALIZABLE)

___
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5WXz694L2T4lyZa-Q:-NA5WXz7E6O6zyUwucc1:b-xzkvmw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccef74bc24445c277e80c75d860243a73359fb02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt#L51)):*
> ```Kotlin
>   override suspend fun getMeasurement(request: GetMeasurementRequest): Measurement {
>     return try {
>       flow {
> ```

Extract a `retryingSerializableErrors` function since this pattern is repeated in multiple places.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5WZjqEanQkN6sOfQq:-NA5WZjqEanQkN6sOfQr:b-xik6ta) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccef74bc24445c277e80c75d860243a73359fb02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt#L55)):*
> ```Kotlin
>             MeasurementReader()
>               .readMeasurementByReferenceIds(
>                 client.singleUse(),
> ```

Are we getting this error even on read-only transactions? I was under the impression that those don't usually take predicate locks.



_Code quote:_
```Kotlin
                client.singleUse(),
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt` line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5PJ1v7mPOgzbUtM9y:-NA5PJ1v7mPOgzbUtM9z:bcrwikx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccef74bc24445c277e80c75d860243a73359fb02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt#L62)):*
This is roughly equivalent to dealing with aborted transactions on Spanner. The advice [given there](https://cloud.google.com/spanner/docs/reference/rest/v1/TransactionOptions) is more specific on retrying:

> a transaction can abort many times in a short period before successfully committing. Thus, it is not a good idea to cap the number of retries a transaction can attempt; instead, it is better to limit the total amount of time spent retrying.

Kotlin's TimeSource.Monotonic provides a nice API for checking this. Something like 

```kotlin
private val SERIALIZABLE_RETRY_DURATION = 2.seconds
// ...
val retryLimit: TimeMark = TimeSource.Monotonic.markNow().plus(SERIALIZABLE_RETRY_DURATION)
// ...
retryLimit.hasNotPassedNow() && e is PostgresqlException && e.errorDetails.code == PostgresErrorCodes.SERIALIZABLE_ERROR_CODE
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt` line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5T4F46Iv4QOc44TGH:-NA5T4F46Iv4QOc44TGI:bk2mold) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccef74bc24445c277e80c75d860243a73359fb02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt#L65)):*
> ```Kotlin
>           (e is PostgresqlException &&
>               e.errorDetails.code == PostgresErrorCodes.SERIALIZABLE_ERROR_CODE)
>             .also { if (it) delay(200) }
> ```

I took a peek at the equivalent code for retries in Spanner, and they don't bother with a delay unless it's a batch DML statement (e.g. for schema updates). As long as we properly suspend/yield (which using this flow construct already does), then it should be fine to not use a delay.



_Code quote:_
```Kotlin
if (it) delay(200)
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5QoyTEp1_ZYbdprf8:-NA5QoyTEp1_ZYbdprf9:b-odbl3p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccef74bc24445c277e80c75d860243a73359fb02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt#L67)):*
> ```Kotlin
>             .also { if (it) delay(200) }
>         }
>         .first()
> ```

Shouldn't this be `single()`, since we expect exactly one?



_Code quote:_
```Kotlin
first()
```

**Comment by tristanvuong2021** [comment]
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5WZjqEanQkN6sOfQq:-NA5atce00hvVnmuK9Ec:b-dh43fk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccef74bc24445c277e80c75d860243a73359fb02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Are we getting this error even on read-only transactions? I was under the impression that those don't usually take predicate locks.
</blockquote></details>

I haven't gotten any in my testing. I added this just in case because it could happen, just a lot more rare.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: 3 of 10 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5WZjqEanQkN6sOfQq:-NA5dECt3rgbzNepEhM-:bm9vdcp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccef74bc24445c277e80c75d860243a73359fb02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt#L55)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I haven't gotten any in my testing. I added this just in case because it could happen, just a lot more rare.
</blockquote></details>

Doing more reading, I think we may be able to completely avoid needing this on read-only transactions by marking the transaction as deferrable. This is done in [PostgresDatabaseClient](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresDatabaseClient.kt).

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5WXz694L2T4lyZa-Q:-NA5kauF5GdtUwpl4HGz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccef74bc24445c277e80c75d860243a73359fb02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Extract a `retryingSerializableErrors` function since this pattern is repeated in multiple places.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt` line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5PJ1v7mPOgzbUtM9y:-NA5kcJ-8Jl2BVLEeP81:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccef74bc24445c277e80c75d860243a73359fb02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is roughly equivalent to dealing with aborted transactions on Spanner. The advice [given there](https://cloud.google.com/spanner/docs/reference/rest/v1/TransactionOptions) is more specific on retrying:

> a transaction can abort many times in a short period before successfully committing. Thus, it is not a good idea to cap the number of retries a transaction can attempt; instead, it is better to limit the total amount of time spent retrying.

Kotlin's TimeSource.Monotonic provides a nice API for checking this. Something like 

```kotlin
private val SERIALIZABLE_RETRY_DURATION = 2.seconds
// ...
val retryLimit: TimeMark = TimeSource.Monotonic.markNow().plus(SERIALIZABLE_RETRY_DURATION)
// ...
retryLimit.hasNotPassedNow() && e is PostgresqlException && e.errorDetails.code == PostgresErrorCodes.SERIALIZABLE_ERROR_CODE
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5QoyTEp1_ZYbdprf8:-NA5k_WZ6BjNnMD6mgy_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccef74bc24445c277e80c75d860243a73359fb02/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt#L67)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this be `single()`, since we expect exactly one?
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5zj2CAeUa5Bw5ZP_2:-NA5zj2CAeUa5Bw5ZP_3:bvtrkes) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/737a99ee56fe93d647dbcf5a794e8f1833ad3212/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L30)):*
> ```Kotlin
>   @OptIn(ExperimentalTime::class) private val SERIALIZABLE_RETRY_DURATION = 30.seconds
> 
>   fun <T> withRetries(block: suspend () -> T): Flow<T> {
> ```

This should be a suspend function that just returns a `T`. The fact that this uses a flow underneath is an implementation detail.

Note that T can be a nullable type, e.g. `Measurement?`. Therefore you can just always use `single()` on the underlying flow to return a single `T`.



_Code quote:_
```Kotlin
Flow<T>
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA5zj2CAeUa5Bw5ZP_2:-NA64auz7lKRoAr5RXKi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/737a99ee56fe93d647dbcf5a794e8f1833ad3212/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be a suspend function that just returns a `T`. The fact that this uses a flow underneath is an implementation detail.

Note that T can be a nullable type, e.g. `Measurement?`. Therefore you can just always use `single()` on the underlying flow to return a single `T`.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/k8s/local/BUILD.bazel` line 134 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA655PCEOQwucn1xS7-:-NA655PCEOQwucn1xS70:b82gkl8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cf3d3f64edf1bef4d9770f2f08a5007dc40724c/src/main/k8s/local/BUILD.bazel#L134)):*
> ```Starlark
> )
> 
> cue_dump(
> ```

Unrelated to this PR.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/k8s/local/BUILD.bazel` line 134 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NA655PCEOQwucn1xS7-:-NA67NK25ayhoIwmrPus:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cf3d3f64edf1bef4d9770f2f08a5007dc40724c/src/main/k8s/local/BUILD.bazel#L134)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Unrelated to this PR.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3, 3 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NAFHd7eAChlxRYh4HFG:-NAFHd7eAChlxRYh4HFH:bnhdh44) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8b0e97b5fea7277b13f8237dc840755021449bd/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L40)):*
> ```Kotlin
>     return this.retry { e ->
>       (retryLimit.hasNotPassedNow() &&
>         e is PostgresqlException &&
> ```

i dont think we only want to retry for postgres exceptions
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 41 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NAFHbfaALF3Ju_42AIW:-NAFHbfaALF3Ju_42AIX:b-kiqv9b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8b0e97b5fea7277b13f8237dc840755021449bd/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L41)):*
> ```Kotlin
>       (retryLimit.hasNotPassedNow() &&
>         e is PostgresqlException &&
>         e.errorDetails.code == SERIALIZABLE_ERROR_CODE)
> ```

what about a list of error codes on which we retry? wouldn't we want to retry on 503s?

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NAFHd7eAChlxRYh4HFG:-NAFht745-Err9i6XXhr:blmaah4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8b0e97b5fea7277b13f8237dc840755021449bd/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i dont think we only want to retry for postgres exceptions
</blockquote></details>

I could retry on more postgres exceptions since this only captures the database related exceptions.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 41 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NAFHbfaALF3Ju_42AIW:-NAFfG2q-Ux5EOP12wmq:bj0w4k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8b0e97b5fea7277b13f8237dc840755021449bd/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what about a list of error codes on which we retry? wouldn't we want to retry on 503s?
</blockquote></details>

This is a postgres error code from here: https://www.postgresql.org/docs/current/errcodes-appendix.html. I could retry on all retriable exceptions, which would be all the 40 class exceptions.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NAFHd7eAChlxRYh4HFG:-NAFiMm3EK3uA7SvCKuR:b2f6fkr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8b0e97b5fea7277b13f8237dc840755021449bd/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L40)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I could retry on more postgres exceptions since this only captures the database related exceptions.
</blockquote></details>

Note the object name of PostgresSerializable, as in this is specifically for retrying Postgres serializable errors and nothing else.

Let's keep this PR focused on just that, as the Postgres docs specifically say to retry on this error type when using serializable isolation. Any other retry logic/conditions is out of scope.

I'd recommend updating the PR description to being more specific as well.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 41 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NAFHbfaALF3Ju_42AIW:-NAFj32T-Zr5GR9QHqCa:bsjte78) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8b0e97b5fea7277b13f8237dc840755021449bd/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L41)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This is a postgres error code from here: https://www.postgresql.org/docs/current/errcodes-appendix.html. I could retry on all retriable exceptions, which would be all the 40 class exceptions.
</blockquote></details>

See above comment.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r2, 2 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 36 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NAFrK1t9_lo-U2kNzYg:-NAFrK1t9_lo-U2kNzYh:b5fhjlm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8b0e97b5fea7277b13f8237dc840755021449bd/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L36)):*
> ```Kotlin
> 
>   @OptIn(ExperimentalTime::class)
>   fun <T> Flow<T>.withRetries(): Flow<T> {
> ```

what about renaming this to `withSerializableErrorRetries` ?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NAFHd7eAChlxRYh4HFG:-NAFqshw65d856puF1p_:bhxi73c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8b0e97b5fea7277b13f8237dc840755021449bd/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note the object name of PostgresSerializable, as in this is specifically for retrying Postgres serializable errors and nothing else.

Let's keep this PR focused on just that, as the Postgres docs specifically say to retry on this error type when using serializable isolation. Any other retry logic/conditions is out of scope.

I'd recommend updating the PR description to being more specific as well.
</blockquote></details>

I'm okay with this approach.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 36 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NAFrK1t9_lo-U2kNzYg:-NAG118m7dA5X1_evSER:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a82137e284c95513a008b30fffa407baecd40a39/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L36)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what about renaming this to `withSerializableErrorRetries` ?
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 36 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NAFrK1t9_lo-U2kNzYg:-NAG-XcjBIxhIHMHE-a4:b-z5qv5l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a82137e284c95513a008b30fffa407baecd40a39/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L36)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Alternatively, just don't import the function and always qualify with the enclosing object. That way it's clear from the call site and you also aren't repeating the "serializable" part in two places. Maybe even just rename the object to `SerializableErrors` and the function to `retrying`, since we're already in a `postgres` package. e.g.

```kotlin
SerializableErrors.retrying {
  // Code to retry
}
```

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 9 files at r2, 2 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt` line 36 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671#-NAFrK1t9_lo-U2kNzYg:-NAG5ZdZ79_20Nw0VwQs:bkaakyt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a82137e284c95513a008b30fffa407baecd40a39/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresSerializable.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Alternatively, just don't import the function and always qualify with the enclosing object. That way it's clear from the call site and you also aren't repeating the "serializable" part in two places. Maybe even just rename the object to `SerializableErrors` and the function to `retrying`, since we're already in a `postgres` package. e.g.

```kotlin
SerializableErrors.retrying {
  // Code to retry
}
```
</blockquote></details>

yeah - I considered both these options - slightly prefer what I suggested but also like Sanjay's idea

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 6 files at r4, 1 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: 7 of 12 files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 5 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/671)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
