### PR TITLE
modelrelease internal api

### PR DESCRIPTION
**Pull request by Marco-Premier**

### CODE REVIEW

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @jcorilla, @jojijac0b, @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRelease.kt` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVFPezABkdevF0i4h5M:-NVT8IkG6mqCVqegDyFm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3860a864a87da6fc4153fd8071cb319ba087538a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRelease.kt#L43)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Should be externalModelProviderId
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 13 of 16 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla, @riemanli, and @tristanvuong2021)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 16 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988)* status: all files reviewed, 9 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelReleases.kt` line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVeacRL1Eu1Ku6-QtfU:-NVeacRL1Eu1Ku6-QtfV:b-9ghkuv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelReleases.kt#L54)):*
> ```Kotlin
>     }
> 
>     if (filter.hasCreatedAfter()) {
> ```

Would need to be changed to match the After field.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelReleaseReader.kt` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVeZzBuEYZbFsnOkJdg:-NVeZzBuEYZbFsnOkJdh:bow6i37) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelReleaseReader.kt#L41)):*
> ```Kotlin
>       ModelSuites.ModelProviderId,
>       ModelSuites.ModelSuiteId,
>       ModelProviders.ModelProviderId,
> ```

You don't need to select the ModelProviderId twice.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelReleaseReader.kt` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVe_1Or-k2IMZSFkSPB:-NVe_1Or-k2IMZSFkSPC:b-p77bbm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelReleaseReader.kt#L44)):*
> ```Kotlin
>       ModelProviders.ExternalModelProviderId,
>       FROM ModelReleases
>       JOIN (ModelSuites JOIN ModelProviders USING (ModelProviderId)) USING (ModelSuiteId)
> ```

This would look simpler if it was just



_Code snippet:_
```Kotlin
FROM ModelReleases
JOIN ModelSuites USING (ModelProviderId, ModelSuiteId)
JOIN ModelProviders USING (ModelProviderId)
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVebdE_-UqzcXhL6Adu:-NVebdE_-UqzcXhL6Adv:bxchuq8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt#L46)):*
> ```Kotlin
> private const val RANDOM_SEED = 1
> 
> @RunWith(JUnit4::class)
> ```

Missing test for createModelRelease when it fails due to not finding model suite.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVeakxc8zKdr1eLJCo-:-NVeakxc8zKdr1eLJCo0:b-6nlpp0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt#L88)):*
> ```Kotlin
>     val createdModelRelease = modelReleasesService.createModelRelease(modelRelease)
> 
>     ProtoTruth.assertThat(createdModelRelease)
> ```

Import ProtoTruth.assertThat.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt` line 95 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVeb03S5URUcnd2nd8E:-NVeb03S5URUcnd2nd8F:btmos0d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt#L95)):*
> ```Kotlin
>       .isEqualTo(
>         modelRelease {
>           externalModelProviderId = modelSuite.externalModelProviderId
> ```

This message is already created above. Could reuse that.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt` line 120 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVebGyQ0gA6mgZNp2Pt:-NVebGyQ0gA6mgZNp2Pu:b-181jhd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt#L120)):*
> ```Kotlin
> 
>     ProtoTruth.assertThat(createdModelRelease)
>       .ignoringFields(ModelRelease.CREATE_TIME_FIELD_NUMBER)
> ```

Create time in this case should be equal so it shouldn't be ignored.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_releases_service.proto` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVea-PoBGNB5raJfKTl:-NVea-PoBGNB5raJfKTm:bueelwc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/proto/wfa/measurement/internal/kingdom/model_releases_service.proto#L49)):*
> ```protobuf
>     int64 external_model_suite_id = 1;
>     int64 external_model_provider_id = 2;
>     google.protobuf.Timestamp created_after = 3;
> ```

After message here.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988)* status: 11 of 16 files reviewed, 9 unresolved discussions (waiting on @jojijac0b, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelReleases.kt` line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVeacRL1Eu1Ku6-QtfU:-NVexqYe3qZMoV2AyjdR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelReleases.kt#L54)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Would need to be changed to match the After field.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelReleaseReader.kt` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVeZzBuEYZbFsnOkJdg:-NVeksqi90KynIU7Tn5F:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelReleaseReader.kt#L41)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

You don't need to select the ModelProviderId twice.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelReleaseReader.kt` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVe_1Or-k2IMZSFkSPB:-NVekyUgD5NGQurX-8si:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelReleaseReader.kt#L44)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This would look simpler if it was just
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVebdE_-UqzcXhL6Adu:-NVexlqg4L8VMar3FIsy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt#L46)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Missing test for createModelRelease when it fails due to not finding model suite.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVeakxc8zKdr1eLJCo-:-NVelL1T3PAON9A1_DtA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt#L88)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Import ProtoTruth.assertThat.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt` line 95 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVeb03S5URUcnd2nd8E:-NVewn194rxT44e6Ps9V:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt#L95)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This message is already created above. Could reuse that.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt` line 120 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVebGyQ0gA6mgZNp2Pt:-NVewb_Z9EFVNxoQvWys:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelReleasesServiceTest.kt#L120)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Create time in this case should be equal so it shouldn't be ignored.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_releases_service.proto` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVea-PoBGNB5raJfKTl:-NVexwx20ITLNjmfBN-s:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/461959fa6738f198c168c984dc9319607490baef/src/main/proto/wfa/measurement/internal/kingdom/model_releases_service.proto#L49)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

After message here.
</blockquote></details>

Done.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_releases_service.proto` line 45 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVkQH_vAVuHO9uze6_j:-NVkQH_vAVuHO9uze6_k:bsq5y5a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a0fc2ca71488ac6d2ad4964a2237aa1d77f35fa/src/main/proto/wfa/measurement/internal/kingdom/model_releases_service.proto#L45)):*
> ```protobuf
> 
> message StreamModelReleasesRequest {
>   message AfterFilter {
> ```

nit: reverse the order of the after filter fields
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_releases_service.proto` line 56 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988#-NVkQOcK4o-wxJrB4cNa:-NVkQOcK4o-wxJrB4cNb:b-n0iwmf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a0fc2ca71488ac6d2ad4964a2237aa1d77f35fa/src/main/proto/wfa/measurement/internal/kingdom/model_releases_service.proto#L56)):*
> ```protobuf
>     int64 external_model_suite_id = 1;
>     int64 external_model_provider_id = 2;
>     AfterFilter after = 4;
> ```

nit: 3

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 3 of 16 files at r1, 1 of 3 files at r2, 5 of 5 files at r3, 7 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/988)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b)

**Pull request merged**
