### PR TITLE
Add resource requests and limits to k8s pods

### PR DESCRIPTION
**Pull request by oliver-amzn**
@wangyaopw @SanjayVas - looking for feedback if this is the right approach to add this.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282)

### CODE REVIEW

**Review by SanjayVas — COMMENTED** [review]
Seems reasonable to me. Let me know when ready for final review.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282#-:-Mk8MgUd2jbOl5S4J9sd:bnicihp)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/k8s/base.cue, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282#-Mk8NgjE33pLBb1CM0hE:-Mk8P2Ar-fOlSLpYFQtX:b-z80b4d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b38c3492f98f9d4efb120739b1c20cf72d19fb6a/src/main/k8s/base.cue#L82)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

The duchy mill has jvm flag `jvm_flags: "-Xmx4g -Xms256m"`, does it need to override these resource flags accordingly?
</blockquote></details>

IIUC these are two separate things.

The K8s resource config is akin to setting up the hardware of the machine to run on. The JVM can be set to use up to 4 GiB, but it can never actually reach that if the resource config limits it to 512 MiB.

**Review by oliver-amzn — COMMENTED** [review]
Thanks! Ready for review.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282#-:-Mk8YZMo9ZClJBmrgfIF:bhnruph)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/k8s/base.cue, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282#-Mk8NgjE33pLBb1CM0hE:-Mk8Y_YS6Xh0DhJmgRos:bebqu0y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b38c3492f98f9d4efb120739b1c20cf72d19fb6a/src/main/k8s/base.cue#L82)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Yep, so apparently the resource limit here should be greater than the jvm limit (which is what we need to complete some large size computations)
</blockquote></details>

Correct. The "request" param is used when scheduling the pod, the "limit" param is, well, for limiting the pod during runtime.

I set the defaults for all services to 2CPUs and 256MB of memory and explicitly gave the mill more (see below).
For simple gRPC services that seems like enough but we can up it if you think we should.
___
*[src/main/k8s/duchy.cue, line 111 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282#-Mk8Z9iL-2_fH7a6V6i1:-Mk8Z9iL-2_fH7a6V6i2:b5m6vze) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af48672fad5b7b2850f240f6481a1e3ed82af57/src/main/k8s/duchy.cue#L111)):*
> ```
> _resourceRequestCpu: "16"
> ```

@wangyaopw - what kind of host with what CPU count do you run the mill on? What do you think would be a sensible request/limit for the mill?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/k8s/duchy.cue, line 111 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282#-Mk8Z9iL-2_fH7a6V6i1:-Mk8fThP74LOfIw2AyWj:b8c67v5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af48672fad5b7b2850f240f6481a1e3ed82af57/src/main/k8s/duchy.cue#L111)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> ```
> _resourceRequestCpu: "16"
> ```

@wangyaopw - what kind of host with what CPU count do you run the mill on? What do you think would be a sensible request/limit for the mill? 
</blockquote></details>

The mill now runs a single thread for loop, so the thread is not sensible I think.

In the correctness test, we deploy all (20+) pods to a test cluster which has 4 nodes and machine type of google GCE c2-standard-4. Do the flags you added impact how the pods run in the test cluster?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/k8s/base.cue, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282#-Mk8NgjE33pLBb1CM0hE:-Mk8h2ib4PHXe83UnUCQ:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b38c3492f98f9d4efb120739b1c20cf72d19fb6a/src/main/k8s/base.cue#L82)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Correct. The "request" param is used when scheduling the pod, the "limit" param is, well, for limiting the pod during runtime.

I set the defaults for all services to 2CPUs and 256MB of memory and explicitly gave the mill more (see below).
For simple gRPC services that seems like enough but we can up it if you think we should.
</blockquote></details>

sg

**Review by wangyaopw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282#-:-Mk8h8qTB5jWgWG52i6n:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/k8s/duchy.cue, line 111 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282#-Mk8Z9iL-2_fH7a6V6i1:-Mk8h9f9CSIwm_bX05wG:b-vpefb2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af48672fad5b7b2850f240f6481a1e3ed82af57/src/main/k8s/duchy.cue#L111)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

The mill now runs a single thread for loop, so the thread is not sensible I think.

In the correctness test, we deploy all (20+) pods to a test cluster which has 4 nodes and machine type of google GCE c2-standard-4. Do the flags you added impact how the pods run in the test cluster?
</blockquote></details>

Oh really, I didn't know. So it's just using one core? In that case I'll reduce it the number of allocated resources.
And yes, the flags will apply to all pods running in the test cluster. The cluster has 4x4=16 CPUs total, we might want to set the default request cpu limit to "1" so we don't run out of resources.

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/k8s/duchy.cue, line 111 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282#-Mk8Z9iL-2_fH7a6V6i1:-Mk8iMvqEHwg4lHzpQZJ:byrydwe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af48672fad5b7b2850f240f6481a1e3ed82af57/src/main/k8s/duchy.cue#L111)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Oh really, I didn't know. So it's just using one core? In that case I'll reduce it the number of allocated resources.
And yes, the flags will apply to all pods running in the test cluster. The cluster has 4x4=16 CPUs total, we might want to set the default request cpu limit to "1" so we don't run out of resources.
</blockquote></details>

Ah, just saw the `20+` pods. In that case let's reduce the requested CPU even more to just half a core to make sure it all fits.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
