### PR TITLE
Implement /ExchangeSteps.listExchangeSteps

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360#-MoKhWxWBlNAIIiN7hk_:-MoKhWxWBlNAIIiN7hka:bom51s1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8778d508d6a9c82fe8f3e29c607effa89644dce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L103)):*
> ```Kotlin
>     val dataProviders: List<Provider> =
>       request.filter.recurringExchangeDataProvidersList.map {
>         provider {
> ```

Add `fun DataProviderKey.toProvider(): Provider` extension function please (same for ModelProviderKey)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 89 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360#-MoKtbUXBzoUmwrJQaan:-MoKtbUXBzoUmwrJQaao:b-kbfa00) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8778d508d6a9c82fe8f3e29c607effa89644dce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L89)):*
> ```Kotlin
>     val provider =
>       validateRequestProvider(request.filter.modelProvider, request.filter.dataProvider)
>     val key =
> ```

As discussed, `key` also needs to be able to parse a `dataProvider` or `modelProvider`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 125 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360#-MoKtR2K-ToEn-8mtO6R:-MoKtR2K-ToEn-8mtO6S:b-94y2lh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8778d508d6a9c82fe8f3e29c607effa89644dce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L125)):*
> ```Kotlin
>             updatedAfter = Timestamp.parseFrom(request.pageToken.base64UrlDecode())
>           }
>           stepProvider = provider
> ```

I think we need a new filter field here, actually.

Maybe add a `principal` field that `provider` goes into. It's not safe to just put it into `recurringExchangeParticipants` because that field is treated as an OR, not an AND, if there are multiple things specified.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 129 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360#-MoKrrpJCKBxAjXs5fO7:-MoKrrpJCKBxAjXs5fO8:bnxesm2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8778d508d6a9c82fe8f3e29c607effa89644dce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L129)):*
> ```Kotlin
>           recurringExchangeParticipants += modelProviders
>           externalRecurringExchangeIds += apiIdToExternalId(key.recurringExchangeId)
>           dates += LocalDate.parse(key.exchangeId).toProtoDate()
> ```

Only if `exchangeId` is not `-`

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @yunyeng)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360)* status: all files reviewed, 6 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 150 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360#-MoLLV-50PaBarl7krrU:-MoLLV-50PaBarl7krrV:b-5rvb7c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/548a8b7963e0f7f562b8b83bf74c0647c0e366e7/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L150)):*
> ```Kotlin
>   }
> 
>   private fun String.toProvider(providerType: Provider.Type): Provider {
> ```

I'd prefer `DataProviderKey.toProvider()` and `ModelProviderKey.toProvider()` -- not a huge fan of specific extensions on String.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, line 236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360#-MoLL0UW0aiNBpOUh3WF:-MoLKdGd-zT9CXWvurF_:b-rao28q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a85fd52bbfd9a13880f8f9e31969f01d2f28635/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt#L236)):*
> ```Kotlin
> 
>   @Test
>   fun `listExchangeSteps unauthenticated`() {
> ```

This test should still exist I think. We need to make sure there's a provider from the gRPC context.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 89 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360#-MoKtbUXBzoUmwrJQaan:-MoMOahp3NCrnNa9X-SU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8778d508d6a9c82fe8f3e29c607effa89644dce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L89)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

As discussed, `key` also needs to be able to parse a `dataProvider` or `modelProvider`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360#-MoKhWxWBlNAIIiN7hk_:-MoMObkt9zC0zwc3Jg-T:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8778d508d6a9c82fe8f3e29c607effa89644dce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L103)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Add `fun DataProviderKey.toProvider(): Provider` extension function please (same for ModelProviderKey)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 125 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360#-MoKtR2K-ToEn-8mtO6R:-MoMOdD49vc7NwcEiWxI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8778d508d6a9c82fe8f3e29c607effa89644dce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L125)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we need a new filter field here, actually.

Maybe add a `principal` field that `provider` goes into. It's not safe to just put it into `recurringExchangeParticipants` because that field is treated as an OR, not an AND, if there are multiple things specified.


</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 129 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360#-MoKrrpJCKBxAjXs5fO7:-MoMOe0u-YwGjqxXZESH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8778d508d6a9c82fe8f3e29c607effa89644dce/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L129)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Only if `exchangeId` is not `-`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 150 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360#-MoLLV-50PaBarl7krrU:-MoMOf9r64Cq2JGPTIL2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/548a8b7963e0f7f562b8b83bf74c0647c0e366e7/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L150)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'd prefer `DataProviderKey.toProvider()` and `ModelProviderKey.toProvider()` -- not a huge fan of specific extensions on String.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, line 236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360#-MoLL0UW0aiNBpOUh3WF:-MoMOgf_C6PKpe1s5whb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5a85fd52bbfd9a13880f8f9e31969f01d2f28635/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt#L236)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This test should still exist I think. We need to make sure there's a provider from the gRPC context.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 11 of 11 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> Reviewed 10 of 11 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
