### PR TITLE
Add data-providers update-capabilities subcommand to MeasurementSystem CLI.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1528)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1528)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 952 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1528#-NtLrBIL8HXk7x-VAk1x:-NtLrBIL8HXk7x-VAk1y:b-aouym1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a85a48acc17217020fd93ed839b8feb24cd2e5ca/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L952)):*
> ```Kotlin
>   }
> 
>   @Command(name = "update-capabilities", description = ["Updates DataProvider's capabilities"])
> ```

do we want to encourage cli updates for things that EDPs should be updating via the API?

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1528)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 952 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1528#-NtLrBIL8HXk7x-VAk1x:-NtMD3qj4ov8TgcThkNZ:b-7wmfzs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a85a48acc17217020fd93ed839b8feb24cd2e5ca/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L952)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we want to encourage cli updates for things that EDPs should be updating via the API?
</blockquote></details>

I actually think the preferred way for EDPs to update this is via the CLI as these are basically one off updates.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1528)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt` line 952 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1528#-NtLrBIL8HXk7x-VAk1x:-NtMzAEIE0ag8Bh35ug7:byvvx48) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a85a48acc17217020fd93ed839b8feb24cd2e5ca/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt#L952)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I actually think the preferred way for EDPs to update this is via the CLI as these are basically one off updates.
</blockquote></details>

To give further background, this is something that EDPs are expected to call infrequently/manually. Contrast this with e.g. CreateEventGroup or ReplaceDataAvailabilityInterval, which EDPs are expected to call as part of automated processes.

Additionally, this CLI can be a useful testing tool.

**Pull request merged**
