### PR TITLE
Add state and delete time to internal event group proto definition

### PR DESCRIPTION
**Pull request by jcorilla**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836)

### CODE REVIEW

**Review by kungfucraig — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_group.proto` line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836#-NN4EdUPB6ziunOZBVCd:-NN4EdUPB6ziunOZBVCe:b-uiqae) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3e2063c45f1d5d0e11bc1f5eb8c1b4fd3e02cb5a/src/main/proto/wfa/measurement/internal/kingdom/event_group.proto#L62)):*
> ```protobuf
> 
>   // Time the Event Group was deleted.
>   google.protobuf.Timestamp delete_time = 9;
> ```

Why can't we just use update_time given that DELETED is a terminal state? The EventGroup can never be updated after it's DELETED.



_Code quote:_
```protobuf
  // Time the Event Group was deleted.
  google.protobuf.Timestamp delete_time = 9;
```

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_group.proto` line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836#-NN4EdUPB6ziunOZBVCd:-NN8B0G7Bho--LC6VuZ3:bainqc7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3e2063c45f1d5d0e11bc1f5eb8c1b4fd3e02cb5a/src/main/proto/wfa/measurement/internal/kingdom/event_group.proto#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why can't we just use update_time given that DELETED is a terminal state? The EventGroup can never be updated after it's DELETED.
</blockquote></details>

Done, Was looking at https://google.aip.dev/148, which suggests the field as a "should" for soft delete (Initially misread as a "must"). You're right, since we don't support undelete, this field would be redundant with update time (treating a delete as an update)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla and @SanjayVas)

___
*[`src/main/resources/kingdom/spanner/add-event-group-state-and-delete-time.sql` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836#-NN8uSie6Fd8VUuN_okV:-NN8uSie6Fd8VUuN_okW:b-pdjt0y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd21824fc7b8e42b0f7ff9308dde8d68680b142c/src/main/resources/kingdom/spanner/add-event-group-state-and-delete-time.sql#L22)):*
> ```TSQL
> ALTER TABLE EventGroups
>   -- EventGroup.State enum as int with default to ACTIVE.
>   ADD COLUMN State INT64 NOT NULL DEFAULT (1);
> ```

if these are going to be deleted on state=deleted, do we even need a state column?

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/resources/kingdom/spanner/add-event-group-state-and-delete-time.sql` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836#-NN8uSie6Fd8VUuN_okV:-NN9BraSCMVNXzKno1jL:bxvzujo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd21824fc7b8e42b0f7ff9308dde8d68680b142c/src/main/resources/kingdom/spanner/add-event-group-state-and-delete-time.sql#L22)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

if these are going to be deleted on state=deleted, do we even need a state column?
</blockquote></details>

The state column would be to mark deletion for a soft delete. We wanted to have a soft delete for event groups since the Reporting Server's ReportingSets reference the kingdoms eventgroups.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/resources/kingdom/spanner/changelog.yaml` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836#-NND-fyV3ZNlyWjEmF3M:-NNDJVgKE5qs4fiY07R2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd21824fc7b8e42b0f7ff9308dde8d68680b142c/src/main/resources/kingdom/spanner/changelog.yaml#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rename this as it's no longer adding a DeleteTime column.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/836)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
