### PR TITLE
Add createReportingSet.

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/985)

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #985** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/985" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/985?utm_source=stack-comment).

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/985)* status: all files reviewed, 4 unresolved discussions (waiting on @jcorilla and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 153 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/985#-NV05Ldv3orekvk1en3L:-NV05Ldv3orekvk1en3M:b808mv5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1834676c93df18208e294d03941476a97ec84b1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L153)):*
> ```Kotlin
>                 this.externalReportingSetId = externalReportingSetId.value
> 
>                 if (!reportingSet.filter.isNullOrEmpty()) {
> ```

nit: It can't be null here so an empty check is good enough.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt` line 221 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/985#-NV0W2NrA57emxiw0nvG:-NV0W2NrA57emxiw0nvH:b8ih4v1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1834676c93df18208e294d03941476a97ec84b1/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt#L221)):*
> ```Kotlin
>       ReportingSet.SetExpression.Operand.OperandCase.REPORTING_SET -> {
>         val internalReportingSet =
>           getInternalReportingSet(operand.reportingSet, cmmsMeasurementConsumerId)
> ```

I notice reporting sets are retrieved one at a time. It works, but it does introduce additional network calls. Can always be changed later if issues actually occur.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt` line 256 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/985#-NV0VeaCDZtkFHkJvlOc:-NV0VeaCDZtkFHkJvlOd:b-hi75tu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1834676c93df18208e294d03941476a97ec84b1/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt#L256)):*
> ```Kotlin
>               )
>               .also {
>                 // Remove current operand from parents and remove its filter from filters.
> ```

What does the "Remove current operand" part mean. I only see a filter removal.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt` line 322 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/985#-NV0L66LBAaBYXOvlWH1:-NV0BXhy06Tqi7wb3qXQ:b-da8s6d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b1834676c93df18208e294d03941476a97ec84b1/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt#L322)):*
> ```Kotlin
> 
>   @Test
>   fun `createReportingSet returns reporting set when primitiveReportingSetBases are not unique`() {
> ```

What makes the primitiveReportingSetBases here not unique, but the ones in the following test are?

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/985)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/985)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 2 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/985)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla and @stevenwarejones)

**Review by jcorilla — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 2 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/985)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by riemanli — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, 2 of 3 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/985)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
