### PR TITLE
Fix the mismatch of dataset k8s config.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1628)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1628)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/k8s/dev/synthetic_generator_config_files_kustomization.yaml` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1628#-NyzXFeb3-YF2XlrLVCU:-Nz-8SrXCKYW7Q05Be9h:b-pz7im0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f5a8e6d9019c73b9984b1d26d0bcf2f3159eb953/src/main/k8s/dev/synthetic_generator_config_files_kustomization.yaml#L21)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I thought we wanted the smaller data sets for the k8s tests?
</blockquote></details>

The small dataset is only for in-process tests. K8s test are still using the old(large) dataset.

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1628)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by renjiezh — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1628)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

**Pull request merged**
