### PR TITLE
Fix key format of testing ModelProvider signing key.

### PR DESCRIPTION
**Pull request by SanjayVas**
The file was incorrectly not in PKCS#8 format.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/461)

### CODE REVIEW

**Comment by SanjayVas** [comment]
See #458.

**Comment by SanjayVas** [comment]
CC @yunyeng

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/461)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by yunyeng — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/461)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
