### PR TITLE
Refactor panel exchange to use Kustomize

### PR DESCRIPTION
**Pull request by Marco-Premier**
- Delete ```DeployToGke.kt```
- Use Kustomize for panel exchange daemon deployment

Configurations for local deployment to run Kind test will follow in a separate PR.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/k8s/panelmatch/dev/BUILD.bazel` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090#-NZb42fF5ElAqT9kQyUM:-NZb42fF5ElAqT9kQyUN:b-xjs6qj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6bbba769eb9245c5ef0c74d4ea3170848c898b3/src/main/k8s/panelmatch/dev/BUILD.bazel#L40)):*
> ```Starlark
>     cue_tags = {
>         "party_name": EXAMPLE_PANEL_EXCHANGE_CLIENT_DAEMON_CONFIG.edp_name,
>         "secret_name": EXAMPLE_PANEL_EXCHANGE_CLIENT_DAEMON_CONFIG.edp_secret_name,
> ```

Don't use a variable for the secret name. Kustomize will generate the hash suffix and update it everywhere for you.



_Code quote:_
```Starlark
       "secret_name": EXAMPLE_PANEL_EXCHANGE_CLIENT_DAEMON_CONFIG.edp_secret_name,
```
___
*[`src/main/k8s/panelmatch/dev/BUILD.bazel` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090#-NZb53wnD27CfYyFcCLY:-NZb53wnD27CfYyFcCLZ:b4kwb0o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6bbba769eb9245c5ef0c74d4ea3170848c898b3/src/main/k8s/panelmatch/dev/BUILD.bazel#L144)):*
> ```Starlark
>     name = "k8s_deployer",
>     packages = ["//src/main/kotlin/org/wfanet/panelmatch/tools/..."],
> )
> ```

You shouldn't need these anymore, as they exist to support DeployToGke



_Code quote:_
```Starlark
ALL_IMAGE_ARCHIVES = [
    image_spec.image + ".tar"
    for image_spec in GCLOUD_IMAGES + AWS_IMAGES
]

filegroup(
    name = "all_archives",
    srcs = ALL_IMAGE_ARCHIVES,
    tags = ["manual"],
)

filegroup(
    name = "k8s_deployment_config",
    srcs = [":example_daemon_from_cue_gke.yaml"],
    data = [":all_archives"],
    tags = ["manual"],
    visibility = [":k8s_deployer"],
)

package_group(
    name = "k8s_deployer",
    packages = ["//src/main/kotlin/org/wfanet/panelmatch/tools/..."],
)
```

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/k8s/panelmatch/dev/BUILD.bazel` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090#-NZb42fF5ElAqT9kQyUM:-NZeAZRaCgt7dlbwWgPD:bs7wumx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6bbba769eb9245c5ef0c74d4ea3170848c898b3/src/main/k8s/panelmatch/dev/BUILD.bazel#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't use a variable for the secret name. Kustomize will generate the hash suffix and update it everywhere for you.
</blockquote></details>

Done. 
___
*[`src/main/k8s/panelmatch/dev/BUILD.bazel` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090#-NZb53wnD27CfYyFcCLY:-NZe0IwOB3R49VQ3BVI-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6bbba769eb9245c5ef0c74d4ea3170848c898b3/src/main/k8s/panelmatch/dev/BUILD.bazel#L144)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You shouldn't need these anymore, as they exist to support DeployToGke
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

___
*[`src/main/k8s/panelmatch/dev/resource_requirements.yaml` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090#-NZmT3y3E3FE4WQ62L-M:-NZmT3y3E3FE4WQ62L-N:b-rlav9h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49379876ee136d3875b686d874d0211ded8c5e46/src/main/k8s/panelmatch/dev/resource_requirements.yaml#L24)):*
> ```YAML
>       defaultRequest:
>         cpu: 10m
>         memory: 192Mi
> ```

does kind respect these limits @SanjayVas @Marco-Premier ?

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt` line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090#-NZmTeRy6NoQu9ncJJHe:-NZmTeRy6NoQu9ncJJHf:b45wsjw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/605763b6ff7507acbf4a63a24cba1d06a1934871/src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt#L25)):*
> ```Kotlin
> import picocli.CommandLine.Command
> 
> @Command(name = "deploy_to_gke", description = ["Deploys containers on gcr.io to GKE"])
> ```

removing this is a breaking change until we set up actions to do some same.... is that the plan?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/k8s/panelmatch/dev/resource_requirements.yaml` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090#-NZmT3y3E3FE4WQ62L-M:-NZmVBaUDDTUDaSzXY_7:b-ieiz1b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49379876ee136d3875b686d874d0211ded8c5e46/src/main/k8s/panelmatch/dev/resource_requirements.yaml#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

does kind respect these limits @SanjayVas @Marco-Premier ?
</blockquote></details>

Kind does not respect these, but this is for the `dev` configuration, not `local`. There isn't yet a `local` configuration for panel match.
___
*[`src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt` line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090#-NZmTeRy6NoQu9ncJJHe:-NZmVUzyDQ7226DhPfms:bh71b9s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/605763b6ff7507acbf4a63a24cba1d06a1934871/src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

removing this is a breaking change until we set up actions to do some same.... is that the plan?
</blockquote></details>

I'm not sure what you mean by "breaking change" here, unless you mean relative to the deployment guide? Of course the deployment guide needs to be updated to reflect any changes here. I can't really verify whether that's being done since that guide isn't under version control and I have no idea of its current state.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/k8s/panelmatch/dev/resource_requirements.yaml` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090#-NZmT3y3E3FE4WQ62L-M:-N_0Nllb0v6Jc-HGEH0x:b-drbyef) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49379876ee136d3875b686d874d0211ded8c5e46/src/main/k8s/panelmatch/dev/resource_requirements.yaml#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Kind does not respect these, but this is for the `dev` configuration, not `local`. There isn't yet a `local` configuration for panel match.
</blockquote></details>

can you add that as a TODO @Marco-Premier ?
___
*[`src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt` line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090#-NZmTeRy6NoQu9ncJJHe:-N_0O7q53TnKEDYUtC7-:ba898i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/605763b6ff7507acbf4a63a24cba1d06a1934871/src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not sure what you mean by "breaking change" here, unless you mean relative to the deployment guide? Of course the deployment guide needs to be updated to reflect any changes here. I can't really verify whether that's being done since that guide isn't under version control and I have no idea of its current state.
</blockquote></details>

@Marco-Premier - we should add a task to commit the deployment guides

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt` line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090#-NZmTeRy6NoQu9ncJJHe:-N_IxpRN7DDHgSxgDZs8:b7n8iee) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/605763b6ff7507acbf4a63a24cba1d06a1934871/src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@Marco-Premier - we should add a task to commit the deployment guides
</blockquote></details>

Sure thing! wanted to gather feedback on this first. Will update the guide too.

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/k8s/panelmatch/dev/resource_requirements.yaml` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090#-NZmT3y3E3FE4WQ62L-M:-N_IyzLEEU4Q6QMa46AT:b2mtojh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/546ce9b4b079d0b87bc22a9cce0e6b7b7dfc8cc0/src/main/k8s/panelmatch/dev/resource_requirements.yaml#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add that as a TODO @Marco-Premier ?
</blockquote></details>

I think that's in the PR description. Local configuration will be added with the kind test itself

**Review by Marco-Premier — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by Marco-Premier — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1090)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
