### PR TITLE
Updated parent definition and usage in reporting server EventGroup service

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657#-N8k8tvB-OHlQvJetgIW:-N8k8tvC4oPiBAjQMxY4:b-3gy4l4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e92f0e49393f5d978fd683a7537c48b01b5e43b2/src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto#L45)):*
> ```protobuf
> message ListEventGroupsRequest {
>   // Resource key of the parent `DataProvider`. The wildcard ID (`-`) may be
>   // used in place of the `DataProvider` ID to list across `DataProvider`s, in
> ```

Fix this description as well.



_Code quote:_
```protobuf
  // Resource key of the parent `DataProvider`. The wildcard ID (`-`) may be
  // used in place of the `DataProvider` ID to list across `DataProvider`s, in
  // which case a filter should be specified.
```

**Review by chipingyeh — COMMENTED** [review]
Updated some logic in the code too, as the parent would need some conversion between services

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657#-:-N98KE2_DA4o6CteDK43:b7r1s1r)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657#-N8k8tvB-OHlQvJetgIW:-N98F4dlAqEdwOE5qpaE:bcchwy9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e92f0e49393f5d978fd683a7537c48b01b5e43b2/src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Fix this description as well.
</blockquote></details>

Updated partially -- I assumed the `filter` would still filter across `DataProviders`, though if that's not the case I'll need to change the impl as well.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657)* status: all files reviewed, 3 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657#-N98quPG3UJ46l04FTT0:-N98quPG3UJ46l04FTT1:b-1cq2rw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5823085c4abcd1fa3f3fa9396568cfe7e37945d/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L19)):*
> ```Kotlin
> import io.grpc.Status
> import org.projectnessie.cel.Program
> import org.wfanet.measurement.api.v2alpha.DataProviderKey
> ```

nit: maybe import this as CmmsDataProviderKey to be consistent?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657#-N98g21552ZEp_l44MW_:-N98g21552ZEp_l44MWa:basnipg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5823085c4abcd1fa3f3fa9396568cfe7e37945d/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L58)):*
> ```Kotlin
>     }
>     val apiAuthenticationKey: String = principal.config.apiKey
>     val dataProviderId =
> ```

nit: `dataProviderName`



_Code quote:_
```Kotlin
dataProviderId
```
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657#-N8k8tvB-OHlQvJetgIW:-N98r1Cy0PMA-s9LSBWv:b-67r4pt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e92f0e49393f5d978fd683a7537c48b01b5e43b2/src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto#L45)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Updated partially -- I assumed the `filter` would still filter across `DataProviders`, though if that's not the case I'll need to change the impl as well.
</blockquote></details>

This should really be something like 

```
Resource name of the parent `DataProvider` under a given `MeasurementConsumer`, in the form `measurementConsumers/{measurement_consumer}/dataProviders/{data_provider}`
```

We basically want to be more specific here as the `DataProvider` resource type isn't exposed in this API, so there's nothing that the user can look at to see the resource name pattern. It is indeed true that only the DataProvider ID segment can be replaced with the wildcard character.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657#-N8k8tvB-OHlQvJetgIW:-N9DUAC3EX8mWaZcPG9Q:b-vreuam) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e92f0e49393f5d978fd683a7537c48b01b5e43b2/src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto#L45)):*
> Resource name of the parent `DataProvider` under a given `MeasurementConsumer`, in the form `measurementConsumers/{measurement_consumer}/dataProviders/{data_provider}`
Makes sense -- updated.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by chipingyeh — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/657)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
