### PR TITLE
feat: Add database schema for internal Access API

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1900)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1900)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/resources/access/spanner/changelog.yaml` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1900#-OC5S_NQElhy2LmXf0CK:-OC5S_NQElhy2LmXf0CL:b-svaqd4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89560afb62ea89b55636266cc785a2641fff6553/src/main/resources/access/spanner/changelog.yaml#L20)):*
> ```YAML
>   - include:
>       file: create-access-schema.sql
>       relativeToChangeLogFile: true
> ```

nit: missing new line
___
*[`src/test/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/AccessSchemaTest.kt` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1900#-OC5Spx35OKMfILNCp7J:-OC5Spx35OKMfILNCp7K:bb6vtog) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89560afb62ea89b55636266cc785a2641fff6553/src/test/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/AccessSchemaTest.kt#L28)):*
> ```Kotlin
> class AccessSchemaTest : UsingSpannerEmulator(Schemata.ACCESS_CHANGELOG_PATH) {
> 
>   @Test fun `database is created`() {}
> ```

Can you assert something or explain why it's not necessary to do so?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1900)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/test/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/AccessSchemaTest.kt` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1900#-OC5Spx35OKMfILNCp7J:-OC9rdPp2YpTeljSMMxo:bp3zhde) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89560afb62ea89b55636266cc785a2641fff6553/src/test/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/AccessSchemaTest.kt#L28)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you assert something or explain why it's not necessary to do so?
</blockquote></details>

Done. Note that this follows the pattern of other schema tests in the repo.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1900)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Pull request merged**
