### PR TITLE
model release public api

### PR DESCRIPTION
**Pull request by Marco-Premier**

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt` line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022#-NWDJPJjBGmPEcSGFjNM:-NWDJPJjBGmPEcSGFjNN:bnz0vnl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7811c3683997ca0ffe35a2583557fff35cf2072e/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt#L65)):*
> ```Kotlin
> import org.wfanet.measurement.internal.kingdom.StreamModelReleasesRequest
> import org.wfanet.measurement.internal.kingdom.StreamModelReleasesRequestKt.afterFilter
> import org.wfanet.measurement.internal.kingdom.StreamModelReleasesRequestKt.filter as internalFilter
> ```

There is an open bug that causes aliases for non top level messages to break code completion An alias for StreamModelReleasesRequestKt would work, but not StreamModelReleasesRequestKt.filter.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt` line 394 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022#-NWDIBJL5tuprv80mm2l:-NWDIBJMAqvGyDspH3Dh:b-a3pc3o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7811c3683997ca0ffe35a2583557fff35cf2072e/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt#L394)):*
> ```Kotlin
>         MODEL_RELEASE.copy {
>           name = MODEL_RELEASE_NAME_3
>           MODEL_RELEASE
> ```

extra MODEL_RELEASE
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt` line 433 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022#-NWDILXu2Rat6lGTpJKA:-NWDILXu2Rat6lGTpJKB:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7811c3683997ca0ffe35a2583557fff35cf2072e/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt#L433)):*
> ```Kotlin
>         MODEL_RELEASE.copy {
>           name = MODEL_RELEASE_NAME_3
>           MODEL_RELEASE
> ```

ditto

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt` line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022#-NWDJPJjBGmPEcSGFjNM:-NWDgUWY9bTEFOpQlCOx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7811c3683997ca0ffe35a2583557fff35cf2072e/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt#L65)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

There is an open bug that causes aliases for non top level messages to break code completion An alias for StreamModelReleasesRequestKt would work, but not StreamModelReleasesRequestKt.filter.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt` line 394 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022#-NWDIBJL5tuprv80mm2l:-NWDfj1YChUl6bkGaZcg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7811c3683997ca0ffe35a2583557fff35cf2072e/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt#L394)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

extra MODEL_RELEASE
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt` line 433 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022#-NWDILXu2Rat6lGTpJKA:-NWDflEi2gWoWeioMTbu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7811c3683997ca0ffe35a2583557fff35cf2072e/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt#L433)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 1 of 1 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1022)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
