### PR TITLE
Use resource names instead of Key messages in system API.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/107)

### CODE REVIEW

**Comment by SanjayVas** [comment]
This is intended to be merged into main after the base PR #99.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/107)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/107#-MbxPt9c0a4BjGf2sQfp:-MbxPt9c0a4BjGf2sQfq:b-r85i4y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4083506057632e0a5e39f39785a8d19bbd69e3a0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L132)):*
> ```Kotlin
>   private suspend fun processSystemComputationChange(response: StreamActiveComputationsResponse) {
>     val globalId: String = response.computation.key.computationId
>     require(globalId.isNotEmpty())
> ```

nit: Add a more informative error message for each require()?

Not sure what the default error message looks like.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/107)* status: 0 of 24 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/107#-MbxPt9c0a4BjGf2sQfp:-McG2-kGDuzKVq82--BW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4083506057632e0a5e39f39785a8d19bbd69e3a0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L132)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

nit: Add an more informative error message for each require()?

Not sure what the default error message look like.
</blockquote></details>

Done.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 18 of 24 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)

**Pull request merged**
