### PR TITLE
Specify signature algorithm in CMMS API.

### PR DESCRIPTION
**Pull request by SanjayVas**
Updates common-jvm to 0.67.0, cross-media-measurement-api to 0.45.0, and consent-signaling-client to 0.18.0.

Closes world-federation-of-advertisers/cross-media-measurement-api#176

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263)

**Comment by SanjayVas** [comment]
Depends on:

- https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/177
- https://github.com/world-federation-of-advertisers/common-jvm/pull/218
- https://github.com/world-federation-of-advertisers/consent-signaling-client/pull/46

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263)* status: 0 of 51 files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/storage/VerifyingStorageClient.kt` line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263#-NfTSeNRCu2GMwnYvbP3:-NfTSeNS8QanaWmM_TUS:b-5qsqaz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d69e143225543cd61f00c6f5d02e2deb16104e87/src/main/kotlin/org/wfanet/panelmatch/client/storage/VerifyingStorageClient.kt#L54)):*
> ```Kotlin
>     val namedSignature: NamedSignature = sharedStorage.getBlobSignature(blobKey)
> 
>     // We assume that the signature algorithm is the one from the certificate, since that is the
> ```

@stevenwarejones Just wanted to call this out as a case that's not handled by this PR. I'll leave it to you if you want to expand certificate support for panel match.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
Will these changes to the duchy require that all duchies be redeployed using the new version?

> Reviewed 51 of 51 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263#-:-NfWNqcQCQpdC2P2V_ng:bg5z6sq)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt` line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263#-NfWNc8W6xodT5GPA10s:-NfWNc8W6xodT5GPA10t:bspcja6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d69e143225543cd61f00c6f5d02e2deb16104e87/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt#L122)):*
> ```Kotlin
>     names = ["--algorithm", "--signature-algorithm"],
>     description = ["Signature algorithm. One will be chosen if not specified."],
>     required = false
> ```

i'd prefer the default be explicit here
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/storage/VerifyingStorageClient.kt` line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263#-NfTSeNRCu2GMwnYvbP3:-NfWONST8hN4rFnHMWPI:b2ngthx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d69e143225543cd61f00c6f5d02e2deb16104e87/src/main/kotlin/org/wfanet/panelmatch/client/storage/VerifyingStorageClient.kt#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@stevenwarejones Just wanted to call this out as a case that's not handled by this PR. I'll leave it to you if you want to expand certificate support for panel match.
</blockquote></details>

+1

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt` line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263#-NfWNc8W6xodT5GPA10s:-NfXWQXP3Zq1lX5ac7mv:b-hxuw0w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d69e143225543cd61f00c6f5d02e2deb16104e87/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt#L122)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'd prefer the default be explicit here
</blockquote></details>

There is no single default. It's derived from the key type, and the derivation function might change. We instead output the chosen algorithm.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt` line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263#-NfWNc8W6xodT5GPA10s:-NfXd7kF6bzoDvSx6nuX:b-sahtba) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d69e143225543cd61f00c6f5d02e2deb16104e87/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt#L122)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There is no single default. It's derived from the key type, and the derivation function might change. We instead output the chosen algorithm.
</blockquote></details>

See my other comments. I think this should be required.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt` line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263#-NfWNc8W6xodT5GPA10s:-NfXr3eFBNLTV0XAtdK0:b-ilz429) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d69e143225543cd61f00c6f5d02e2deb16104e87/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt#L122)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

See my other comments. I think this should be required.
</blockquote></details>

I disagree. We shouldn't force users of this CLI to care about the choice of signing algorithm. If they do happen to care, they can specify one.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt` line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263#-NfWNc8W6xodT5GPA10s:-NfXtPDY50cqo1GGTpkw:b-xr65w0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d69e143225543cd61f00c6f5d02e2deb16104e87/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt#L122)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I disagree. We shouldn't force users of this CLI to care about the choice of signing algorithm. If they do happen to care, they can specify one.
</blockquote></details>

Recall that we're just trying to solve the following two issues:

1. The verifier of a signature doesn't know which algorithm was used, so that needs to be communicated.
2. Our logic for picking a signature algorithm was flawed and does not work for all certificates.

There's no requirement there for any *user* to pick a signature algorithm as long as the algorithm is one that's compatible with the key and is communicated to the verifier. I just added this option for bonus flexibility - the CLI need not even provide it. We similarly don't offer an option of signature algorithm in the Reporting API; the Reporting system just picks one.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt` line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263#-NfWNc8W6xodT5GPA10s:-NfkH5cI6atP8Uxdx8h1:bi2d4r8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d69e143225543cd61f00c6f5d02e2deb16104e87/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt#L122)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Recall that we're just trying to solve the following two issues:

1. The verifier of a signature doesn't know which algorithm was used, so that needs to be communicated.
2. Our logic for picking a signature algorithm was flawed and does not work for all certificates.

There's no requirement there for any *user* to pick a signature algorithm as long as the algorithm is one that's compatible with the key and is communicated to the verifier. I just added this option for bonus flexibility - the CLI need not even provide it. We similarly don't offer an option of signature algorithm in the Reporting API; the Reporting system just picks one.
</blockquote></details>

See other comment - unblocking this.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
Components that haven't been updated just won't read/write the `signature_algorithm_oid` field, so they'll fall back to the old logic of using the certificate's signature algorithm.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263#-:-NfmKNX95Sa60-1rcH2A:b5ztfw7)* status: 50 of 51 files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt` line 120 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263#-NfkGUqd5_ahAjDwcibv:-NfmKvxu0ucobidCDSl3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d69e143225543cd61f00c6f5d02e2deb16104e87/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt#L120)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit: I'd prefer just `--signature-algorithm` as algorithm might also refer to other things in the future
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
