### PR TITLE
Add in process postgres duchy correctness tests

### PR DESCRIPTION
**Pull request by YuhongWang-Amazon**
This adds in process postgres duchy correctness tests

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152)

**Review by renjiezh — APPROVED** [review]
> Reviewed 22 of 26 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 16 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152)* status: all files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/service/BUILD.bazel` line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152#-NbLuIxJ1IvYQ_ektCnq:-NbLuIxJ1IvYQ_ektCnr:b-2kovc5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da10ab493ba1d58318b46bed64d75000c6ea13a0/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/service/BUILD.bazel#L33)):*
> ```Starlark
> )
> 
> kt_jvm_library(
> ```

If it's under `deploy/common`, it implies it's not specific to a given cloud. Anything specific to gcloud (e.g. Spanner) would go under `deploy/gcloud`.

As an aside, I've never been a fan of the "data services" interface and figure anything that needs a specific implementation of a service can call its constructor. That said, it's totally fine to keep it.

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152)* status: 23 of 28 files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/service/BUILD.bazel` line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152#-NbLuIxJ1IvYQ_ektCnq:-NbPlPeq-NV9Bc83BobR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da10ab493ba1d58318b46bed64d75000c6ea13a0/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/service/BUILD.bazel#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If it's under `deploy/common`, it implies it's not specific to a given cloud. Anything specific to gcloud (e.g. Spanner) would go under `deploy/gcloud`.

As an aside, I've never been a fan of the "data services" interface and figure anything that needs a specific implementation of a service can call its constructor. That said, it's totally fine to keep it.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 26 files at r1, 4 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152)* status: all files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152#-NbQEqOI937CPaWR9rsT:-NbQEqOI937CPaWR9rsU:bqbvlgx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da847a44f96dee5bc253fc8f7fc74ae3fa90fc11/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L37)):*
> ```Kotlin
> 
> /** Implementation of [InProcessLifeOfAReportIntegrationTest] for Postgres. */
> class V2PostgresInProcessLifeOfAReportIntegrationTest : InProcessLifeOfAReportIntegrationTest() {
> ```

What's the V2 about, btw?



_Code quote:_
```Kotlin
V2
```

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152#-NbQEqOI937CPaWR9rsT:-NbQGkuu15GCZjZ9Iv9q:btdhsue) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da847a44f96dee5bc253fc8f7fc74ae3fa90fc11/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What's the V2 about, btw?
</blockquote></details>

I think it means to test the v2 reporting service: https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152#-NbQEqOI937CPaWR9rsT:-NbQHPpm6r8dLIXgzCE7:b-gr50e0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfcd0634f769ae5effbaeffb61a660908217ba20/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L37)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

I think it means to test the v2 reporting service: https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2
</blockquote></details>

Sorry, I knew that. I misread this as being a Duchy test.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152)* status: all files reviewed, 1 unresolved discussion

___
*[`src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudPostgresInProcessLifeOfAMeasurementIntegrationTest.kt` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152#-NbRfyXQCwXtCYoXEvrs:-NbRfyXQCwXtCYoXEvrt:b-594vyu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd1a3535609146bc5d30e8dfe8b1e5c99a49d7ec/src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudPostgresInProcessLifeOfAMeasurementIntegrationTest.kt#L29)):*
> ```Kotlin
> 
> /**
>  * Implementation of [InProcessLifeOfAMeasurementIntegrationTest] for GCloud backends with Postgres
> ```

Sorry I had missed this before. The naming and comment are inaccurate since the Kingdom still uses Spanner here. Only the Duchies were swapped to Postgres.



_Code quote:_
```Kotlin
GCloud backends with Postgres
```
___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152#-NbRgOuL1ysnne36xXb0:-NbRgOuL1ysnne36xXb1:b-9s74sm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd1a3535609146bc5d30e8dfe8b1e5c99a49d7ec/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L46)):*
> ```Kotlin
>     ProviderRule<
>       (String, ComputationLogEntriesCoroutineStub) -> InProcessDuchy.DuchyDependencies
>     > by lazy { PostgresDuchyDependencyProviderRule(ALL_DUCHY_NAMES) }
> ```

@tristanvuong2021 reported that this change made the test significantly slower.

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152)* status: all files reviewed, 1 unresolved discussion

___
*[`src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudPostgresInProcessLifeOfAMeasurementIntegrationTest.kt` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152#-NbRfyXQCwXtCYoXEvrs:-Nb__HHc20gMkLvuAFV2:bxmvad8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd1a3535609146bc5d30e8dfe8b1e5c99a49d7ec/src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudPostgresInProcessLifeOfAMeasurementIntegrationTest.kt#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry I had missed this before. The naming and comment are inaccurate since the Kingdom still uses Spanner here. Only the Duchies were swapped to Postgres.
</blockquote></details>

Any suggestions for the class name? I can update the comment to point out the kingdom is still spanner.
___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152#-NbRgOuL1ysnne36xXb0:-Nb__jo63OMZTFeGz6i9:byjlvsi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd1a3535609146bc5d30e8dfe8b1e5c99a49d7ec/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@tristanvuong2021 reported that this change made the test significantly slower.
</blockquote></details>

The Postgres Version of the lifeOfmeasurementTest is also slower than the spanner version. My guess is that in process postgres is slow?
I can update this the reporting integration test to use spanner duchy if needed.

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152)* status: all files reviewed, 1 unresolved discussion

___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152#-NbRgOuL1ysnne36xXb0:-Nb_jHYL-VbG8dIbR8eF:baf7jrz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd1a3535609146bc5d30e8dfe8b1e5c99a49d7ec/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L46)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

The Postgres Version of the lifeOfmeasurementTest is also slower than the spanner version. My guess is that in process postgres is slow?
I can update this the reporting integration test to use spanner duchy if needed.
</blockquote></details>

Did some tests locally, when using postgres duchy, the tests took 196s. when using spanner duchy, the tests took 110s.
@tristanvuong2021 does the above numbers match with the original performance?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152)* status: all files reviewed, 1 unresolved discussion

___
*[`src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudPostgresInProcessLifeOfAMeasurementIntegrationTest.kt` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152#-NbRfyXQCwXtCYoXEvrs:-Nba6js9B-swASa4kyh3:b-9ag1mu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd1a3535609146bc5d30e8dfe8b1e5c99a49d7ec/src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudPostgresInProcessLifeOfAMeasurementIntegrationTest.kt#L29)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

Any suggestions for the class name? I can update the comment to point out the kingdom is still spanner.
</blockquote></details>

I'm thinking instead of having a different class name and a different test, perhaps just go back to a single test but replace one of the Duchies with a Postgres implementation.
___
*[`src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1152#-NbRgOuL1ysnne36xXb0:-Nba6RXg1K3DESiJ5OIT:b-mu4o94) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd1a3535609146bc5d30e8dfe8b1e5c99a49d7ec/src/test/kotlin/org/wfanet/measurement/integration/postgres/V2PostgresInProcessLifeOfAReportIntegrationTest.kt#L46)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

Did some tests locally, when using postgres duchy, the tests took 196s. when using spanner duchy, the tests took 110s.
@tristanvuong2021 does the above numbers match with the original performance?
</blockquote></details>

We know for sure that the embedded postgres implementation we use for testing has more overhead due to being a full Postgres instance running in a Docker container, as opposed to the lightweight in-memory emulator we have for Spanner. I'm not sure what the differences are in performance of the two once actually started up.

Regardless, I don't think we actually need to have made any changes here. It can just be reverted back to using the Spanner Duchy implementation for the time being.

**Pull request merged**
