### PR TITLE
Add CreateResource binary for making EDPs, MPs, RecurringExchanges.

### PR DESCRIPTION
**Pull request by efoxepstein**
https://rally1.rallydev.com/#/?detail=/userstory/608698956441&fdp=true

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MojdB8d7Ku1jkwLMrn8:-MojdB8d7Ku1jkwLMrn9:bczxgkk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6498fa7074706f0209b9daa488e665bbfb370287/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L66)):*
> ```
> certificateDerFile
> ```
who is the owner of this certificate?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MojdLQADJLypp48iwYG:-MojdLQADJLypp48iwYH:b5vuzgt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6498fa7074706f0209b9daa488e665bbfb370287/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L75)):*
> ```
> publicKeySignatureFile
> ```
who is the owner of this publicKey?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 124 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MojdRBQ7NFlZPg5nv_4:-MojdRBQ7NFlZPg5nv_5:bjhpn1i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6498fa7074706f0209b9daa488e665bbfb370287/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L124)):*
> ```
> publicKeySignatureFil
> ```
do EDP and MP using the same publicKey?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MojdB8d7Ku1jkwLMrn8:-MojrQlZEG9Bgx9z1M9Y:b-c5zo2j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6498fa7074706f0209b9daa488e665bbfb370287/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L66)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> certificateDerFile
> ```
who is the owner of this certificate?
</blockquote></details>

If you're creating a DataProvider, the data provider is the owner. If you're creating a ModelProvider, the model provider is the owner. Otherwise, this is unused.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MojdLQADJLypp48iwYG:-MojrZdOCKbJFGPXdit9:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6498fa7074706f0209b9daa488e665bbfb370287/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L75)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> publicKeySignatureFile
> ```
who is the owner of this publicKey?
</blockquote></details>

Ditto
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 124 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MojdRBQ7NFlZPg5nv_4:-Mojr_q9BdvX9B8rU4WQ:b-hcfqrb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6498fa7074706f0209b9daa488e665bbfb370287/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L124)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> publicKeySignatureFil
> ```
do EDP and MP using the same publicKey?
</blockquote></details>

This binary only creates one entity at a time. Since this method (and the others) are annotated with `@Command`, they are subcommands. So the binary works like:

```
$ create_resource data_provider --public-key-file=/some/path --public-key-signature=/some/path --etc
```

**Review by yunyeng — APPROVED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 124 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MojdRBQ7NFlZPg5nv_4:-MojsPnc4NqOl5PMMXar:b7ny77c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6498fa7074706f0209b9daa488e665bbfb370287/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L124)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This binary only creates one entity at a time. Since this method (and the others) are annotated with `@Command`, they are subcommands. So the binary works like:

```
$ create_resource data_provider --public-key-file=/some/path --public-key-signature=/some/path --etc
```
</blockquote></details>

Can we create a simple README inside the folder with couple of these sample commands?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 133 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MojsmHS3qWwoDRnyIZw:-MojsmHS3qWwoDRnyIZx:b-hjdg6g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6498fa7074706f0209b9daa488e665bbfb370287/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L133)):*
> ```Kotlin
> 
>     val apiId = externalIdToApiId(outputModelProvider.externalModelProviderId)
>     println(ModelProviderKey(apiId).toName())
> ```

I assume the prints are intentional

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 133 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MojsmHS3qWwoDRnyIZw:-MojtAGJAIRfhPivzxsA:blu188r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6498fa7074706f0209b9daa488e665bbfb370287/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L133)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

I assume the prints are intentional
</blockquote></details>

Yes, very much so

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 124 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MojdRBQ7NFlZPg5nv_4:-Mok-Rzb9S2vJGN503Lz:b-kr9bm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6498fa7074706f0209b9daa488e665bbfb370287/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L124)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Can we create a simple README inside the folder with couple of these sample commands?
</blockquote></details>

Are you going to deploy the binary on GKE to create one entity and then update the flags and deploy again to create another one and then another one?

Could we modify https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt to create all resources needed?

The code is still using the publicApi, and need to be refactored to use the internal API

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 124 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MojdRBQ7NFlZPg5nv_4:-Mok6Lg-Bx8MKzCeE8LA:btf86vh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6498fa7074706f0209b9daa488e665bbfb370287/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L124)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Are you going to deploy the binary on GKE to create one entity and then update the flags and deploy again to create another one and then another one?

Could we modify https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt to create all resources needed?

The code is still using the publicApi, and need to be refactored to use the internal API
</blockquote></details>

This will be a tool used by admins of the Kingdom to create entities as needed. They can run it with `kubectl`, this will be easy. In general the different entities will be created at different times.

Added example usage in a comment.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 1 of 7 files reviewed, all discussions resolved (waiting on @stevenwarejones and @yunyeng)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MooIcok4RZY545wAUE4:-MooIcok4RZY545wAUE5:b-co6zfi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ab3a06426be0811cf6a2e4b8b0f1c8152dc7cdd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L81)):*
> ```Kotlin
>   @Option(
>     names = ["--certificate-der-file"],
>     description = ["Certificate for the principal"],
> ```

doesn't the certificate already contain the public key and its signature?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 127 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MooIoT35Or3Rj5LtC7X:-MooIoT35Or3Rj5LtC7Y:btyb5kp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ab3a06426be0811cf6a2e4b8b0f1c8152dc7cdd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L127)):*
> ```Kotlin
>     val dataProvidersStub = DataProvidersCoroutineStub(apiFlags.channel)
>     val outputDataProvider =
>       runBlocking(Dispatchers.IO) { dataProvidersStub.createDataProvider(dataProvider) }
> ```

this automatically returns a non-zero exit code if it fails, correct?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MooIcok4RZY545wAUE4:-MooK4UGAm3GZWnWOaMn:b-ynqvyt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de46cba10cf8e12dd190d69d206c6fe25639898/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L81)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

doesn't the certificate already contain the public key and its signature?
</blockquote></details>

It only contains the public key of this certificate. We don't need signature for the certificate. We need the signature of the publicKey signed by this certificate.

Maybe we should rename `publicKeySignature` to `EncrpytionPublicKeySignature`

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MooIcok4RZY545wAUE4:-MooZv683KSqG2ioCJ6O:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de46cba10cf8e12dd190d69d206c6fe25639898/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L81)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

It only contains the public key of this certificate. We don't need signature for the certificate. We need the signature of the publicKey signed by this certificate.

Maybe we should rename `publicKeySignature` to `EncrpytionPublicKeySignature`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 127 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MooIoT35Or3Rj5LtC7X:-MooRzfA9wvFXAlb9RRN:b7umojs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0de46cba10cf8e12dd190d69d206c6fe25639898/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L127)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this automatically returns a non-zero exit code if it fails, correct?
</blockquote></details>

Yes: https://picocli.info/#_exception_exit_codes

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 91 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MoosM-14fT15QSzYqcz:-MoosM-14fT15QSzYqd-:bp7zfen) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/18735a8e7b47f4e07f6bbbc4fd44d1e9193921c2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L91)):*
> ```
> public-key-file
> ```
encryption-public-key-file
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 95 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MoosK2PD5-s0603l90l:-MoosK2PD5-s0603l90m:b1pljz0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/18735a8e7b47f4e07f6bbbc4fd44d1e9193921c2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L95)):*
> ```
> publicKeyFile
> ```
encryptionPublicKey
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 97 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MoosY24BgRFYf41Bqob:-MoosY24BgRFYf41Bqoc:byabn94) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/18735a8e7b47f4e07f6bbbc4fd44d1e9193921c2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L97)):*
> ```
> serializedPublicKey
> ```
serializedEncryptionPublicKey

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 91 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MoosM-14fT15QSzYqcz:-MoowgpjBtpQe_ZnzUVW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/18735a8e7b47f4e07f6bbbc4fd44d1e9193921c2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L91)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> public-key-file
> ```
encryption-public-key-file
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 95 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MoosK2PD5-s0603l90l:-MoowheuBG34Rhu4JS1c:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/18735a8e7b47f4e07f6bbbc4fd44d1e9193921c2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L95)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> publicKeyFile
> ```
encryptionPublicKey
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, line 97 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371#-MoosY24BgRFYf41Bqob:-MoowiUeCAUjF_wWdzND:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/18735a8e7b47f4e07f6bbbc4fd44d1e9193921c2/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L97)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> serializedPublicKey
> ```
serializedEncryptionPublicKey
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
