### PR TITLE
Remove otherDuchies from various constructors.

### PR DESCRIPTION
**Pull request by wangyaopw**
The duchy list is now included inside the computation details. We don't
need it upfront. This also allows different computations to use different subsets of the
duchies.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/145)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 15 of 23 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/145)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/145#-MeCcOQ93Y-bbi4LzqIm:-MeCcOQ93Y-bbi4LzqIn:b3z1x19) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2887a0fd87b9e1c34199b07354011aea3b4bc521/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L117)):*
> ```
> logger: Logger
> ```
Not from this PR, but why do these functions take in a logger instead of having one defined in this object?
___
*[src/main/kotlin/org/wfanet/measurement/duchy/db/computation/LiquidLegionsSketchAggregationV2Protocol.kt, line 130 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/145#-MeCd4l53hc4moktqDRE:-MeCd4l53hc4moktqDRF:b-zg3xc1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2887a0fd87b9e1c34199b07354011aea3b4bc521/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/LiquidLegionsSketchAggregationV2Protocol.kt#L130)):*
> ```
> computationDetail
> ```
nit: plural to match type name

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/145#-MeCcOQ93Y-bbi4LzqIm:-MeQij0K9FxJIvY5papQ:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2887a0fd87b9e1c34199b07354011aea3b4bc521/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L117)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> logger: Logger
> ```
Not from this PR, but why do these functions take in a logger instead of having one defined in this object?
</blockquote></details>

done.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/db/computation/LiquidLegionsSketchAggregationV2Protocol.kt, line 130 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/145#-MeCd4l53hc4moktqDRE:-MeQj_VHDSpvFqzlIWaM:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2887a0fd87b9e1c34199b07354011aea3b4bc521/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/LiquidLegionsSketchAggregationV2Protocol.kt#L130)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> computationDetail
> ```
nit: plural to match type name
</blockquote></details>

done

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 12 of 23 files at r1, 9 of 12 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
